name: "Kumar One"
designer: "Indian Type Foundry"
license: "OFL"
category: "DISPLAY"
date_added: "2016-06-20"
fonts {
  name: "Kumar One"
  style: "normal"
  weight: 400
  filename: "KumarOne-Regular.ttf"
  post_script_name: "KumarOne-Regular"
  full_name: "Kumar One Regular"
  copyright: "Copyright (c) 2016 Indian Type Foundry (info@indiantypefoundry.com)"
}
subsets: "gujarati"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
stroke: "SERIF"
classifications: "DISPLAY"
