name: "Puppies Play"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-10-13"
fonts {
  name: "Puppies Play"
  style: "normal"
  weight: 400
  filename: "PuppiesPlay-Regular.ttf"
  post_script_name: "PuppiesPlay-Regular"
  full_name: "Puppies Play Regular"
  copyright: "Copyright 2009-2021 The Puppies Play Project Authors (https://github.com/googlefonts/puppies-play)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
