name: "Numerals, or figures"
excerpt: "The glyphs in a typeface that represent numbers. In OpenType, it’s possible to select different kinds of numerals intended for different uses."
related_lessons: "understanding_numerals"
related_lessons: "introducing_alternate_glyphs"
related_lessons: "open_type_features_in_practice"
