id: "gaa"
name: "Ga"
preferred_name: ""
autonym: "Gã"
population: 821525
region: "GH"
script: "Latin"
exemplar_chars {
  base: "A B D E Ɛ F G H I J K L M N Ŋ O Ɔ P R S T U V W Y Z Ã Ẽ Ĩ Õ Ũ a b d e ɛ f g h i j k l m n ŋ o ɔ p r s t u v w y z ã ẽ ĩ õ ũ"
  marks: "◌̃"
}
