id: "dz"
name: "Dzongkha"
preferred_name: ""
autonym: "རྫོང་ཁ་"
population: 370341
region: "BT"
region: "IN"
script: "Tibetan"
exemplar_chars {
  base: "ཀ ཁ ག ང ཅ ཆ ཇ ཉ ཏ ཐ ད ན པ ཕ བ མ ཙ ཚ ཛ ཝ ཞ ཟ འ ཡ ར ལ ཤ ས ཧ ཨ ཊ ཋ ཌ ཎ ཥ"
  auxiliary: "\\u0F84 ཊ ཋ ཌ ཎ \\u0F7E ཥ \\u0F80 \\u0F7B \\u0F7D \\u0F9A \\u0F9B \\u0F9C \\u0F9E \\u0FBA \\u0FBB \\u0FBC"
  marks: "◌ི ◌ུ ◌ེ ◌ོ ◌ྵ"
  numerals: "༠ ༡ ༢ ༣ ༤ ༥ ༦ ༧ ༨ ༩"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … \' ‘ ’ \" “ ” ( ) \\[ \\] ༼ ༽ § @ * / \\& # † ‡ ༄ ༅ ༆ ༈ ༉ ༊ ࿐ ࿑ ༒ ࿒ ࿓ ࿔ ༶ ྾ ྿ ༌ ། ༎ ༏ ༐ ༑ ༔ ༴"
  index: "ཀ ཁ ག ང ཅ ཆ ཇ ཉ ཏ ཐ ད ན པ ཕ བ མ ཙ ཚ ཛ ཝ ཞ ཟ འ ཡ ར ལ ཤ ས ཧ ཨ"
}
