id: "tem"
name: "Timne"
preferred_name: ""
autonym: "KʌThemnɛ"
population: 1722481
region: "SL"
script: "Latin"
exemplar_chars {
  base: "A Ʌ B D E Ɛ Ə F G H I K L M N Ŋ O Ɔ P R S T U W a ʌ b d e ɛ ə f g h i k l m n ŋ o ɔ p r s t u w"
}
