name: "Emotive considerations for choosing typefaces"
authors: "Elliot Jay Stocks"
reviewers: "Bram Stein"
reviewers: "Bruce Willen"
reviewers: "Jason Santa Maria"
reviewers: "Mark Boulton"
reviewers: "Matthew Smith"
reviewers: "Mike Kus"
reviewers: "Richard Rutter"
reviewers: "Santiago Orozco"
topics: "choosing_type"
topics: "essentials"
prev_lessons: "a_checklist_for_choosing_type"
next_lessons: "choosing_reliable_typefaces"
related_terms: "typeface"
excerpt: "The emotional response to the shape of letterforms is a very personal experience, and when readers first see type, they react to it in an emotional way before anything else."
