id: "es"
name: "Spanish"
preferred_name: ""
autonym: "Español"
population: 487664084
region: "GQ"
region: "SV"
region: "US"
region: "MX"
region: "RO"
region: "AR"
region: "GI"
region: "MA"
region: "EA"
region: "EC"
region: "BZ"
region: "UY"
region: "HN"
region: "CL"
region: "PE"
region: "PT"
region: "CR"
region: "BR"
region: "FR"
region: "PH"
region: "GT"
region: "ES"
region: "VE"
region: "TT"
region: "CW"
region: "IC"
region: "DO"
region: "PY"
region: "BO"
region: "NI"
region: "PR"
region: "PA"
region: "SX"
region: "CO"
region: "CU"
region: "AD"
region: "DE"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Á É Í Ñ Ó Ú Ü a b c d e f g h i j k l m n o p q r s t u v w x y z á é í ñ ó ú ü ¡ ¿"
  auxiliary: "ª à ă â å ä ã ā æ ç è ĕ ê ë ē ì ĭ î ï ī º ò ŏ ô ö ø ō œ ù ŭ û ū ý ÿ"
  marks: "◌́ ◌̃ ◌̈"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ¡ ? ¿ . … \' ‘ ’ \" “ ” « » ( ) \\[ \\] § @ * / \\\\ \\& # † ‡ ′ ″"
  index: "A B C D E F G H I J K L M N Ñ O P Q R S T U V W X Y Z"
}
