name: "Em"
excerpt: "A unit of measurement, 1em is equal to the size of a font. Adjusting font size will resize glyphs relative to the em square."
related_lessons: "exploring_x_height_the_em_square"
related_lessons: "exploring_punctuation"
