name: "Em"
excerpt: "A unit of measurement in typography based on the width of the capital M in a particular typeface. The em square is the “box” each glyph is sized relative to."
related_lessons: "exploring_x_height_the_em_square"
related_lessons: "exploring_punctuation"
