name: "Factors that influence the efficiency of variable web fonts"
authors: "Nick Sherman"
reviewers: "Laurence Penney"
reviewers: "Piper Haywood"
topics: "variable_fonts"
related_terms: "variable_fonts"
prev_lessons: "interactive_animations_with_variable_fonts"
excerpt: "Which specific font qualities make the biggest impact on efficiency?"
