name: "Blackletter"
excerpt: "A historical classification that relates to typefaces that initially arose—and/or became popular in—medieval Europe."
related_lessons: "making_sense_of_typographic_classifications"
