name: "Comforter Brush"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-09-17"
fonts {
  name: "Comforter Brush"
  style: "normal"
  weight: 400
  filename: "ComforterBrush-Regular.ttf"
  post_script_name: "ComforterBrush-Regular"
  full_name: "Comforter Brush Regular"
  copyright: "Copyright 2015 The Comforter Brush Project Authors (https://github.com/googlefonts/comforter-brush)"
}
subsets: "cyrillic"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
