name: "Kavivanar"
designer: "Tharique Azeez"
license: "OFL"
category: "HANDWRITING"
date_added: "2016-06-20"
fonts {
  name: "Kavivanar"
  style: "normal"
  weight: 400
  filename: "Kavivanar-Regular.ttf"
  post_script_name: "Kavivanar-Regular"
  full_name: "Kavivanar Regular"
  copyright: "Copyright (c) 2015, Tharique Azeez (http://thariqueazeez.com|zeezat@gmail.com)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "tamil"
classifications: "DISPLAY"
classifications: "HANDWRITING"
