name: "Pairing typefaces by the same type designer or type foundry"
authors: "Elliot Jay Stocks"
reviewers: "Doug Wilson"
reviewers: "Jessica Hische"
reviewers: "John Boardley"
reviewers: "Thomas Phinney"
topics: "choosing_type"
topics: "pairing_type"
topics: "systems"
prev_lessons: "pairing_typefaces"
prev_lessons: "pairing_typefaces_within_a_family_superfamily"
next_lessons: "exploring_x_height_the_em_square"
related_terms: "type_designer"
related_terms: "type_foundry"
excerpt: "Type designers often have certain stylistic ways of drawing letterforms, and certain technical ways of creating font files."
