name: "Moon Dance"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-11-18"
fonts {
  name: "Moon Dance"
  style: "normal"
  weight: 400
  filename: "MoonDance-Regular.ttf"
  post_script_name: "MoonDance-Regular"
  full_name: "Moon Dance Regular"
  copyright: "Copyright 2004 The Moon Dance Project Authors (https://github.com/googlefonts/moondance)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
