name: "The complications of typographic size on the web"
authors: "Nick Sherman"
reviewers: "Piper Haywood"
reviewers: "Laurence Penney"
topics: "web_fonts"
prev_lessons: "introducing_parametric_axes"
next_lessons: "typesetting_on_a_curved_path"
related_terms: "web_font"
related_terms: "variable_fonts"
excerpt: "The process of establishing an appropriate font size for different elements is more complicated than it might seem at first, and, in the context of web design, it can be especially tricky to weigh all the factors involved for an ideal reader experience."
