name: "The complications of typographic size on the web"
authors: "Nick Sherman"
reviewers: "Piper Haywood"
reviewers: "Laurence Penney"
topics: "web_fonts"
prev_lessons: "INSERT_PREV"
next_lessons: "INSERT_NEXT"
related_terms: "web_font"
related_terms: "variable_fonts"
excerpt: "INSERT_EXCERPT"
