name: "Choosing reliable typefaces"
authors: "Elliot Jay Stocks"
reviewers: "Bruce Willen"
reviewers: "David Brezina"
reviewers: "Doug Wilson"
reviewers: "Ellen Lupton"
reviewers: "Frank Rausch"
reviewers: "Jessica Hische"
reviewers: "Mark Boulton"
reviewers: "Matthew Smith"
reviewers: "Micah Rich"
reviewers: "Mike Kus"
reviewers: "Thomas Jockin"
reviewers: "Thomas Phinney"
topics: "choosing_type"
topics: "essentials"
topics: "families"
topics: "language_support"
topics: "open_type"
topics: "style"
topics: "systems"
topics: "weight"
topics: "width"
prev_lessons: "emotive_considerations_for_choosing_typefaces"
next_lessons: "exploring_typefaces_with_multiple_weights_or_grades"
related_terms: "weight"
related_terms: "width"
related_terms: "optical_sizes"
related_terms: "open_type"
excerpt: "Ideally, a reliable typeface should include language support, legible details, multiple weights and styles, and alternate characters."
