name: "Problems with variable fonts"
authors: "Dave Crossland"
reviewers: "Laurence Penney"
reviewers: "Elliot Jay Stocks"
topics: "variable_fonts"
related_terms: "variable_fonts"
prev_lessons: "factors_that_influence_the_efficiency_of_variable_web_fonts"
excerpt: "Variable fonts are still a relatively new technology, and users encounter common technical problems using them, that often have workarounds."
