name: "Introducing weights & styles"
authors: "Elliot Jay Stocks"
reviewers: "Bruce Willen"
reviewers: "Doug Wilson"
reviewers: "Erik Spiekermann"
reviewers: "Jamie Clarke"
reviewers: "Jessica Hische"
reviewers: "Laurence Penney"
reviewers: "Matthew Smith"
reviewers: "Micah Rich"
reviewers: "Thomas Jockin"
reviewers: "Viviana Monsalve"
topics: "style"
topics: "weight"
prev_lessons: "exploring_punctuation"
next_lessons: "introducing_alternate_glyphs"
next_lessons: "understanding_numerals"
related_terms: "weight"
related_terms: "style"
related_terms: "small_caps"
related_terms: "faux_fake_pseudo_synthesized"
excerpt: "If we consider a typeface to be the “core” design, then different weights and styles could be said to be extensions of that design."
