id: "bem"
name: "Bemba"
preferred_name: ""
autonym: "Chibemba"
population: 5402246
region: "ZM"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P S T U V W Y a b c d e f g h i j k l m n o p s t u v w y"
  auxiliary: "d h q r v x z"
  index: "A B C E F G I J K L M N O P S {SH} T U W Y"
}
