name: "Breaking the rules"
authors: "Elliot Jay Stocks"
reviewers: "Doug Wilson"
reviewers: "Ellen Lupton"
reviewers: "Frank Rausch"
reviewers: "Jessica Hische"
reviewers: "Laurence Penney"
reviewers: "Thomas Phinney"
reviewers: "Tyler Finck"
topics: "systems"
prev_lessons: "working_with_hanging_punctuation"
prev_lessons: "exploring_typefaces_with_multiple_weights_or_grades"
prev_lessons: "choosing_a_suitable_line_height"
next_lessons: "designing_with_variable_fonts_in_desktop_apps"
related_terms: "weight"
related_terms: "italic"
related_terms: "line_height_leading"
excerpt: "There are plenty of typesetting scenarios where the standard way of doing things can create undesirable visual effects."
