name: "Petemoss"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-10-08"
fonts {
  name: "Petemoss"
  style: "normal"
  weight: 400
  filename: "Petemoss-Regular.ttf"
  post_script_name: "Petemoss-Regular"
  full_name: "Petemoss Regular"
  copyright: "Copyright 2008-2021 The Petemoss Project Authors (https://github.com/googlefonts/petemoss)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
