name: "Parametric Ascender Height axis (YTAS)"
excerpt: "A parametric axis for varying the height of lowercase ascenders."
related_lessons: "introducing_variable_fonts"
related_lessons: "introducing_parametric_axes"
