name: "Kings"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-10-22"
fonts {
  name: "Kings"
  style: "normal"
  weight: 400
  filename: "Kings-Regular.ttf"
  post_script_name: "Kings-Regular"
  full_name: "Kings Regular"
  copyright: "Copyright 2013-2021 The Kings Project Authors (https://github.com/googlefonts/kings)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
