name: "Introducing AR/VR"
authors: "Niteesh Yadav"
reviewers: "Andrew Johnson"
reviewers: "Gerry Leonidas"
topics: "ar_vr"
next_lessons: "designing_for_ar_vr"
related_terms: "font"
related_terms: "glyph"
related_terms: "legibility"
excerpt: "With the immersive worlds of augmented reality (AR) and virtual reality (VR), digital experiences extend beyond a flat, two-dimensional world and we interact with text in the three-dimensional space around us."
