name: "Noto Sans Devanagari"
designer: "Google"
license: "OFL"
category: "SANS_SERIF"
date_added: "2020-11-19"
fonts {
  name: "Noto Sans Devanagari"
  style: "normal"
  weight: 100
  filename: "NotoSansDevanagari-Thin.ttf"
  post_script_name: "NotoSansDevanagari-Thin"
  full_name: "Noto Sans Devanagari Thin"
  copyright: "Copyright 2015 Google Inc. All Rights Reserved."
}
fonts {
  name: "Noto Sans Devanagari"
  style: "normal"
  weight: 200
  filename: "NotoSansDevanagari-ExtraLight.ttf"
  post_script_name: "NotoSansDevanagari-ExtraLight"
  full_name: "Noto Sans Devanagari ExtraLight"
  copyright: "Copyright 2015 Google Inc. All Rights Reserved."
}
fonts {
  name: "Noto Sans Devanagari"
  style: "normal"
  weight: 300
  filename: "NotoSansDevanagari-Light.ttf"
  post_script_name: "NotoSansDevanagari-Light"
  full_name: "Noto Sans Devanagari Light"
  copyright: "Copyright 2015 Google Inc. All Rights Reserved."
}
fonts {
  name: "Noto Sans Devanagari"
  style: "normal"
  weight: 400
  filename: "NotoSansDevanagari-Regular.ttf"
  post_script_name: "NotoSansDevanagari-Regular"
  full_name: "Noto Sans Devanagari Regular"
  copyright: "Copyright 2015 Google Inc. All Rights Reserved."
}
fonts {
  name: "Noto Sans Devanagari"
  style: "normal"
  weight: 500
  filename: "NotoSansDevanagari-Medium.ttf"
  post_script_name: "NotoSansDevanagari-Medium"
  full_name: "Noto Sans Devanagari Medium"
  copyright: "Copyright 2015 Google Inc. All Rights Reserved."
}
fonts {
  name: "Noto Sans Devanagari"
  style: "normal"
  weight: 600
  filename: "NotoSansDevanagari-SemiBold.ttf"
  post_script_name: "NotoSansDevanagari-SemiBold"
  full_name: "Noto Sans Devanagari SemiBold"
  copyright: "Copyright 2015 Google Inc. All Rights Reserved."
}
fonts {
  name: "Noto Sans Devanagari"
  style: "normal"
  weight: 700
  filename: "NotoSansDevanagari-Bold.ttf"
  post_script_name: "NotoSansDevanagari-Bold"
  full_name: "Noto Sans Devanagari Bold"
  copyright: "Copyright 2015 Google Inc. All Rights Reserved."
}
fonts {
  name: "Noto Sans Devanagari"
  style: "normal"
  weight: 800
  filename: "NotoSansDevanagari-ExtraBold.ttf"
  post_script_name: "NotoSansDevanagari-ExtraBold"
  full_name: "Noto Sans Devanagari ExtraBold"
  copyright: "Copyright 2015 Google Inc. All Rights Reserved."
}
fonts {
  name: "Noto Sans Devanagari"
  style: "normal"
  weight: 900
  filename: "NotoSansDevanagari-Black.ttf"
  post_script_name: "NotoSansDevanagari-Black"
  full_name: "Noto Sans Devanagari Black"
  copyright: "Copyright 2015 Google Inc. All Rights Reserved."
}
subsets: "devanagari"
subsets: "menu"
is_noto: true
languages: "anp"
languages: "awa"
languages: "bap"
languages: "bfy"
languages: "bgc"
languages: "bhb"
languages: "bhi"
languages: "bho"
languages: "bjj"
languages: "bra"
languages: "brx"
languages: "btv"
languages: "gbm"
languages: "ggn"
languages: "gom"
languages: "gon"
languages: "gvr"
languages: "hi"
languages: "hif"
languages: "hne"
languages: "hoc"
languages: "hoj"
languages: "jml"
languages: "kfr"
languages: "kfy"
languages: "khn"
languages: "kok"
languages: "kru"
languages: "ks_Deva"
languages: "lif"
languages: "mag"
languages: "mai"
languages: "mgp"
languages: "mr"
languages: "mrd"
languages: "mtr"
languages: "mwr"
languages: "ne"
languages: "new"
languages: "noe"
languages: "pi"
languages: "raj"
languages: "rjs"
languages: "sa"
languages: "sat_Deva"
languages: "sck"
languages: "sd_Deva"
languages: "srx"
languages: "swv"
languages: "taj"
languages: "tdg"
languages: "tdh"
languages: "thl"
languages: "thq"
languages: "thr"
languages: "tkt"
languages: "tsf"
languages: "unr_Deva"
languages: "unx_Deva"
languages: "wbr"
languages: "wtm"
languages: "xnr"
languages: "xsr"
languages: "anp"
languages: "awa"
languages: "bap"
languages: "bfy"
languages: "bgc"
languages: "bhb"
languages: "bhi"
languages: "bho"
languages: "bjj"
languages: "bra"
languages: "brx"
languages: "btv"
languages: "gbm"
languages: "ggn"
languages: "gom"
languages: "gon"
languages: "gvr"
languages: "hi"
languages: "hif"
languages: "hne"
languages: "hoc"
languages: "hoj"
languages: "jml"
languages: "kfr"
languages: "kfy"
languages: "khn"
languages: "kok"
languages: "kru"
languages: "ks_Deva"
languages: "lif"
languages: "mag"
languages: "mai"
languages: "mgp"
languages: "mr"
languages: "mrd"
languages: "mtr"
languages: "mwr"
languages: "ne"
languages: "new"
languages: "noe"
languages: "pi"
languages: "raj"
languages: "rjs"
languages: "sa"
languages: "sat_Deva"
languages: "sck"
languages: "sd_Deva"
languages: "srx"
languages: "swv"
languages: "taj"
languages: "tdg"
languages: "tdh"
languages: "thl"
languages: "thq"
languages: "thr"
languages: "tkt"
languages: "tsf"
languages: "unr_Deva"
languages: "unx_Deva"
languages: "wbr"
languages: "wtm"
languages: "xnr"
languages: "xsr"
languages: "awa"
languages: "bho"
languages: "dty"
languages: "gom"
languages: "mag"
languages: "taj"
languages: "xnr"
