name: "Dene Syllabics"
authors: "Kevin King"
reviewers: "Elliot Jay Stocks"
topics: "INSERT"
prev_lessons: "INSERT"
next_lessons: "INSERT"
related_terms: "INSERT"
excerpt: "This article presents and describes the local orthographic requirements and typographic preferences for the Dene (Athabaskan) Syllabics-using communities."
