name: "Typesetting"
excerpt: "Typesetting is the act of setting type: arranging characters and making informed typographic decisions that will optimize the readability of that text."
related_lessons: "why_care_about_typography"
related_lessons: "choosing_reliable_typefaces"
