id: "kaa"
name: "Kara-Kalpak"
preferred_name: ""
autonym: "Қарақалпақ"
population: 489046
region: "UZ"
script: "Cyrillic"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Á Ǵ Ń Ú a b c d e f g h i j k l m n o p q r s t u v w x y z á İ ı ǵ ń ú"
  marks: "◌́ ◌̇"
}
