sources:
  - Baloo2.glyphs
  - BalooBhai2.glyphs
  - BalooBhaijaan2.glyphs
  - BalooBhaina2.glyphs
  - BalooChettan2.glyphs
  - BalooDa2.glyphs
  - BalooPaaji2.glyphs
  - BalooTamma2.glyphs
  - BalooTammudu2.glyphs
  - BalooThambi2.glyphs