name: "Fill axis (FILL)"
excerpt: "excerpt: "An axis found in some variable fonts, intended to provide a treatment of the design that fills in transparent forms with opaque ones."
related_lessons: "INSERT_RELATED_LESSONS_AS_MANY_AS_NEEDED"
