name: "Introducing parametric axes"
authors: "Dave Crossland"
topics: "variable_fonts"
prev_lessons: "introducing_variable_fonts"
next_lessons: "styling_type_on_the_web_with_variable_fonts"
related_terms: "xopq_axis"
related_terms: "yopq_axis"
related_terms: "xtra_axis"
related_terms: "ytuc_axis"
related_terms: "ytlc_axis"
related_terms: "ytas_axis"
related_terms: "ytde_axis"
related_terms: "ytfi_axis"
excerpt: "Learn what parametric axes are and how experts use them to finesse opaque (positive) and transparent (negative) shapes to solve various typographic challenges."
