name: "Choosing a suitable line height"
authors: "Elliot Jay Stocks"
reviewers: "Bram Stein"
reviewers: "Bruce Willen"
reviewers: "David Brezina"
reviewers: "Ellen Lupton"
reviewers: "Jessica Hische"
reviewers: "Micah Rich"
reviewers: "Thomas Jockin"
reviewers: "Trent Walton"
reviewers: "Yves Peters"
topics: "essentials"
prev_lessons: "exploring_x_height_the_em_square"
prev_lessons: "language_support_in_fonts"
next_lessons: "understanding_measure_line_length"
related_terms: "line_height_leading"
related_terms: "measure_line_length"
excerpt: "Line height is a property so often left at its default value that it can be easily overlooked."
