name: "Monolinear"
excerpt: "A typeface with strokes of a consistent thickness; i.e., little or no contrast. Typically, sans serifs tend to have less contrast than serifs."
related_lessons: "choosing_typefaces_that_have_optical_sizes"
