id: "nym"
name: "Nyamwezi"
preferred_name: ""
autonym: ""
population: 1932242
region: "TZ"
script: "Latin"
exemplar_chars {
  base: "A B D E Ɛ F G H I J L M N Ŋ O Ɔ P S T U V W Z a b d e ɛ f g h i j l m n ŋ o ɔ p s t u v w z"
}
