name: "Choosing web fonts: A beginner's all-in-one guide"
authors: "Google Fonts"
reviewers: "Yuin Chien"
reviewers: "Joana Correia"
reviewers: "Dave Crossland"
reviewers: "Natanael Gama"
reviewers: "Octavio Pardo"
reviewers: "Eben Sorkin"
reviewers: "Eduardo Tunni"
topics: "essentials"
topics: "web_fonts"
prev_lessons: "why_care_about_typography"
related_terms: "typography"
related_terms: "serif"
related_terms: "sans_serif"