name: "Hurricane"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-10-08"
fonts {
  name: "Hurricane"
  style: "normal"
  weight: 400
  filename: "Hurricane-Regular.ttf"
  post_script_name: "Hurricane-Regular"
  full_name: "Hurricane Regular"
  copyright: "Copyright 2016-2021 The Hurricane Project Authors (https://github.com/googlefonts/hurricane)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
