name: "Katibeh"
designer: "KB Studio"
license: "OFL"
category: "DISPLAY"
date_added: "2016-06-20"
fonts {
  name: "Katibeh"
  style: "normal"
  weight: 400
  filename: "Katibeh-Regular.ttf"
  post_script_name: "Katibeh-Regular"
  full_name: "Katibeh Regular"
  copyright: "Copyright 2015, 2016 KB-Studio (www.k-b-studio.com|tarobish@gmail.com). Copyright 2015, 2016 Lasse Fister (lasse@graphicore.de). Copyright 2015, 2016 Eduardo Tunni(edu@tipo.net.ar)."
}
subsets: "arabic"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
stroke: "SERIF"
classifications: "DISPLAY"
