name: "CJK Typesetting Rules"
authors: "Min-Young Kim"
reviewers: "Lisa Huang"
reviewers: "Minjoo Ham"
reviewers: "Shoko Mugikura"
topics: "cjk"
related_terms: "cjk"
prev_lessons: "type_classification_in_cjk"
next_lessons: "japanese_typography_basics"
excerpt: "INSERT_EXCERPT"
