id: "bs_Cyrl"
name: "Bosnian (Cyrillic)"
preferred_name: ""
autonym: ""
population: 3797234
region: "BA"
script: "Cyrillic"
script: "Latin"
exemplar_chars {
  base: "а б в г д ђ е ж з и ј к л љ м н њ о п р с т ћ у ф х ц ч џ ш"
  auxiliary: ""
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "А Б В Г Д Ђ Е Ж З И Ј К Л Љ М Н Њ О П Р С Т Ћ У Ф Х Ц Ч Џ Ш"
}
