name: "Italic"
excerpt: "An almost-always slanted type style that's designed to create emphasis in text. Originally based on semi-cursive forms, italics are a direct contrast to the Roman style."
related_lessons: "introducing_weights_styles"
