name: "Uppercase & lowercase"
excerpt: "Uppercase (or capital) letters are used for the beginning of sentences, proper nouns, and abbreviations. Lowercase letters are used for every other scenario."
related_lessons: "track_carefully_or_not_at_all"
