name: "Typesetting on a curved path"
authors: "Elliot Jay Stocks"
authors: "Adam Twardoch"
reviewers: "Lily Darling"
reviewers: "Laurence Penney"
topics: "readability"
topics: "width"
prev_lessons: "track_carefully_or_not_at_all"
next_lessons: "understanding_measure_line_length"
related_terms: "baseline"
related_terms: "width"
related_terms: "variable_fonts"
excerpt: "Most of the time when we set type, we do so on a straight line, but occasionally we need to manipulate the baseline so that it follows a curve. And while this is generally rare, it’s something to consider when using type in circular interfaces, like those found on smartwatches."
