name: "Transitional faces"
authors: "John Boardley"
reviewers: "Gerry Leonidas"
reviewers: "Ben Weiner"
topics: "type_history"
prev_lessons: "what_have_the_romans_ever_done_for_us"
next_lessons: "modern_type"
related_terms: "blackletter"
related_terms: "contrast"
related_terms: "italic"
related_terms: "latin"
related_terms: "letterform"
related_terms: "transitional_neo_classical"
excerpt: "The rise of roman fonts and the French typographic revolution."
