name: "Why care about typography?"
authors: "Elliot Jay Stocks"
reviewers: "Erik Spiekermann"
reviewers: "Gerry Leonidas"
reviewers: "Jessica Hische"
reviewers: "John Boardley"
reviewers: "Matthew Smith"
reviewers: "Thomas Jockin"
reviewers: "Viviana Monsalve"
reviewers: "Yves Peters"
topics: "essentials"
topics: "language_support"
next_lessons: "an_overview_of_latin_type_anatomy"
next_lessons: "making_sense_of_typographic_classifications"
next_lessons: "introducing_weights_styles"
next_lessons: "choosing_reliable_typefaces"
next_lessons: "pairing_typefaces"
related_terms: "typeface"
related_terms: "italic"
related_terms: "weight"
excerpt: "Deliberate typeface choices and thoughtful typographic decisions serve to honor the content."
