id: "dv"
name: "Divehi"
preferred_name: ""
autonym: "ދިވެހި"
population: 372368
region: "MV"
region: "IN"
script: "Thaana"
exemplar_chars {
  base: "އ ކ ޅ ބ ރ ނ ށ ހ ޏ ގ ލ ތ ދ ފ މ ވ ޗ ޖ ޕ ޔ ޓ ޒ ޑ ސ ޱ ‎"
  marks: "◌ަ ◌ާ ◌ި ◌ީ ◌ު ◌ޫ ◌ެ ◌ޭ ◌ޮ ◌ޯ ◌ް"
}
