name: "BhuTuka Expanded One"
designer: "Erin McLaughlin"
license: "OFL"
category: "SERIF"
date_added: "2022-01-21"
fonts {
  name: "BhuTuka Expanded One"
  style: "normal"
  weight: 400
  filename: "BhuTukaExpandedOne-Regular.ttf"
  post_script_name: "BhuTukaExpandedOne-Regular"
  full_name: "BhuTuka Expanded One Regular"
  copyright: "Copyright 2017 The BhuTuka Expanded One Project Authors (https://github.com/erinmclaughlin/BhuTuka-Extended-One)"
}
subsets: "gurmukhi"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
stroke: "SLAB_SERIF"
classifications: "DISPLAY"
