name: "CJK Typesetting Rules"
authors: "Min-Young Kim"
reviewers: "Lisa Huang"
reviewers: "Minjoo Ham"
reviewers: "Shoko Mugikura"
topics: "cjk"
related_terms: "cjk"
related_terms: "script_writing_system"
prev_lessons: "type_classification_in_cjk_korean"
next_lessons: "japanese_typography_basics"
excerpt: "There are four big differences in rules of typesetting between Latin and CJK fonts: Full-width versus monospaced, use of punctuation, balance of the type, and the existence of italic."
