id: "ve"
name: "Venda"
preferred_name: ""
autonym: "Tshivenḓa"
population: 1391759
region: "ZA"
region: "ZW"
script: "Latin"
exemplar_chars {
  base: "A B D Ḓ E F G H I K L Ḽ M N Ṋ Ṅ O P R S T Ṱ U V W X Y Z a b d ḓ e f g h i k l ḽ m n ṋ ṅ o p r s t ṱ u v w x y z"
  marks: "◌̇ ◌̭"
}
