id: "lua"
name: "Luba-Lulua"
preferred_name: ""
autonym: "Tshiluba"
population: 9770880
region: "CD"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P S T U V W Y Z a b c d e f g h i j k l m n o p s t u v w y z"
}
