name: "Body"
excerpt: "Either the main text in a piece of content, or the “body” optical size (which serves as the opposite of “display”)."
related_lessons: "choosing_typefaces_that_have_optical_sizes"
