name: "Color"
excerpt: "The overall presence of type on a page—its lightness and darkness compared to the negative space."
related_lessons: "introducing_weights_styles"
related_lessons: "choosing_a_suitable_line_height"
