id: "ab_Cyrl"
language: "ab"
script: "Cyrl"
name: "Abkhazian"
autonym: "Аԥсшәа"
population: 91952
region: "GE"
region: "TR"
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я Џ Қ Ҟ Ҩ Ҭ Ҳ Ҵ Ҷ Ҽ Ҿ Ә Ӡ Ӷ Ԥ а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я џ қ ҟ ҩ ҭ ҳ ҵ ҷ ҽ ҿ ә ӡ ӷ ԥ"
  marks: "◌̆"
}
sample_text {
  masthead_full: "ДдАа"
  masthead_partial: "Рр"
  styles: "Дызусҭзаалак, ауаатәыҩсатә ҭаацәара иалахәу"
  tester: "иара убас ауаҩы изинқәа ратәамбареи хырҩаа рымҭареи, ламыс змоу"
  poster_sm: "иара убас, ауаҩы"
  poster_md: "иара убас"
  poster_lg: "ауаҩы"
  specimen_48: "иара убас Еиду Амилаҭқәа Реиҿкаара иалахәу ажәларқәа ауаҩ ихадароу"
  specimen_36: "Дызусҭзаалак, ауаатәыҩсатә ҭаацәара иалахәу иҳаҭыри, иара иузиҟәымҭхо имоу изинқәеи, ахақәиҭреи, аиашареи,"
  specimen_32: "Дызусҭзаалак, ауаатәыҩсатә ҭаацәара иалахәу иҳаҭыри, иара иузиҟәымҭхо имоу изинқәеи, ахақәиҭреи, аиашареи, адунеижәларбжьаратәи аҭынчреи шьаҭас ишрымоу хшыҩзышьҭра азуа,"
  specimen_21: "Дызусҭзаалак, ауаатәыҩсатә ҭаацәара иалахәу иҳаҭыри, иара иузиҟәымҭхо имоу изинқәеи, ахақәиҭреи, аиашареи, адунеижәларбжьаратәи аҭынчреи шьаҭас ишрымоу хшыҩзышьҭра азуа,\nиара убас ауаҩы изинқәа ратәамбареи хырҩаа рымҭареи, ламыс змоу дарбанзаалак изымычҳаша агыгшәыгратә хымҩаҧгашьа аҟынӡа ауаҩы дышнанагахьо еилкааны, насгьы ауаҩы иажәеи идунеихәаҧшышьеи дрықәиҭны, ашәареи амамзаареи дыдмыргәаҟуа – адунеи иахьабалак абри аҩыза аҧсҭазаара аҧҵара ауаҩы зегь иреиҳау игәыҕрақәа ишыруакыу хшыҩзышьҭра азуа,"
  specimen_16: "Дызусҭзаалак, ауаатәыҩсатә ҭаацәара иалахәу иҳаҭыри, иара иузиҟәымҭхо имоу изинқәеи, ахақәиҭреи, аиашареи, адунеижәларбжьаратәи аҭынчреи шьаҭас ишрымоу хшыҩзышьҭра азуа,\nиара убас ауаҩы изинқәа ратәамбареи хырҩаа рымҭареи, ламыс змоу дарбанзаалак изымычҳаша агыгшәыгратә хымҩаҧгашьа аҟынӡа ауаҩы дышнанагахьо еилкааны, насгьы ауаҩы иажәеи идунеихәаҧшышьеи дрықәиҭны, ашәареи амамзаареи дыдмыргәаҟуа – адунеи иахьабалак абри аҩыза аҧсҭазаара аҧҵара ауаҩы зегь иреиҳау игәыҕрақәа ишыруакыу хшыҩзышьҭра азуа,\nиара убас, ауаҩы аџьамыҕәеи ахәуреи иаартны дырҿамгылар ада царҭа имамкәа аҟынӡа инамгараз, ауаҩы изинқәа азакуан амчра иамыхьчар ада ҧсыхәа шыҟам хшыҩзышьҭра азуа,"
}
