id: "acu_Latn"
language: "acu"
script: "Latn"
name: "Achuar-Shiwiar, Latin, Ecuador"
region: "EC"
region: "US"
sample_text {
  masthead_full: "PpEe"
  masthead_partial: "Nn"
  styles: "Penker inintimsamka mash aintsti ankan, metekrin"
  tester: "Penker inintimsamka mash aintsti ankan, metekrin nuya nii penkerin"
  poster_sm: "Penker"
  poster_md: "Penker"
  poster_lg: "Penker"
  specimen_48: "Penker inintimsamka mash aintsti ankan, metekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti arantukmau atinuitji mai metekrak."
  specimen_36: "Penker inintimsamka mash aintsti ankan, metekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti arantukmau atinuitji mai metekrak."
  specimen_32: "Penker inintimsamka mash aintsti ankan, metekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti arantukmau atinuitji mai metekrak."
  specimen_21: "Penker inintimsamka mash aintsti ankan, metekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti arantukmau atinuitji mai metekrak.\nPenker inintimsamka mash aintsti ankan, metekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti arantukmau atinuitji mai metekrak.\nPenker inintimsamka mash aintsti ankan, metekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti arantukmau atinuitji mai metekrak."
  specimen_16: "Penker inintimsamka mash aintsti ankan, metekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti arantukmau atinuitji mai metekrak.\nPenker inintimsamka mash aintsti ankan, metekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti arantukmau atinuitji mai metekrak.\nPenker inintimsamka mash aintsti ankan, metekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti arantukmau atinuitji mai metekrak.\nPenker inintimsamka mash aintsti ankan, metekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti arantukmau atinuitji mai metekrak.\nPenker inintimsamka mash aintsti ankan, metekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti arantukmau atinuitji mai metekrak."
}
