id: "adl_Latn"
language: "adl"
script: "Latn"
name: "Galo, Latin"
sample_text {
  masthead_full: "LlEe"
  masthead_partial: "Mm"
  styles: "L\ne\n \nm\no\nn\nd\ne\n \nv\ni\ne\nn\ne\nn\nt\n \ns\nu\n \nl"
  tester: "L\ne\n \nm\no\nn\nd\ne\n \nv\ni\ne\nn\ne\nn\nt\n \ns\nu\n \nl\na\n \nt\né\nr\nr\ne\n \nl\ni"
  poster_sm: "L\ne\n \nm\no\nn"
  poster_md: "L\ne\n \nm\no"
  poster_lg: "L\ne"
  specimen_48: "L\ne\n \nm\no\nn\nd\ne\n \nv\ni\ne\nn\ne\nn\nt\n \ns\nu\n \nl\na\n \nt\né\nr\nr\ne\n \nl\ni"
  specimen_36: "L\ne\n \nm\no\nn\nd\ne\n \nv\ni\ne\nn\ne\nn\nt\n \ns\nu\n \nl\na\n \nt\né\nr\nr\ne\n \nl\ni\nb\nr\ns\n \nt\ne\nr\nt\no\nu\ns\n \ne\n \ns\n\'\ne\nn\nt\n\'\nv"
  specimen_32: "L\ne\n \nm\no\nn\nd\ne\n \nv\ni\ne\nn\ne\nn\nt\n \ns\nu\n \nl\na\n \nt\né\nr\nr\ne\n \nl\ni\nb\nr\ns\n \nt\ne\nr\nt\no\nu\ns\n \ne\n \ns\n\'\ne\nn\nt\n\'\nv\na\nl\ne\nn\nt\n \ne\nn\n \nd\nr\ne\nt\ns\n \ne\n \nd\ni\ng"
  specimen_21: "L\ne\n \nm\no\nn\nd\ne\n \nv\ni\ne\nn\ne\nn\nt\n \ns\nu\n \nl\na\n \nt\né\nr\nr\ne\n \nl\ni\nb\nr\ns\n \nt\ne\nr\nt\no\nu\ns\n \ne\n \ns\n\'\ne\nn\nt\n\'\nv\na\nl\ne\nn\nt\n \ne\nn\n \nd\nr\ne\nt\ns\n \ne\n \nd\ni\ng\nn\ni\nt\në\n.\n \nI\nl\n \nl\no\nu\n \na\np\na\nr\nt\ni\ne\nn\nt\n \nd\n\'\na\nv\na\ne\nr\n \nd\ne\n \nl\na\n \nr\né\ns\no\nn\n \ne\n \nd\ne\n \nl\na\n \nc\no\nn\ns\nc\ni\ne\nn\nc\ne\n \ne\n \ni\nl\n \no\nn\nt\n \nd\ne\n \ns\n\'\ne\nn\nt\n\'\ne\nn"
  specimen_16: "L\ne\n \nm\no\nn\nd\ne\n \nv\ni\ne\nn\ne\nn\nt\n \ns\nu\n \nl\na\n \nt\né\nr\nr\ne\n \nl\ni\nb\nr\ns\n \nt\ne\nr\nt\no\nu\ns\n \ne\n \ns\n\'\ne\nn\nt\n\'\nv\na\nl\ne\nn\nt\n \ne\nn\n \nd\nr\ne\nt\ns\n \ne\n \nd\ni\ng\nn\ni\nt\në\n.\n \nI\nl\n \nl\no\nu\n \na\np\na\nr\nt\ni\ne\nn\nt\n \nd\n\'\na\nv\na\ne\nr\n \nd\ne\n \nl\na\n \nr\né\ns\no\nn\n \ne\n \nd\ne\n \nl\na\n \nc\no\nn\ns\nc\ni\ne\nn\nc\ne\n \ne\n \ni\nl\n \no\nn\nt\n \nd\ne\n \ns\n\'\ne\nn\nt\n\'\ne\nn\nc\nh\ne\nv\ni\n \nc\no\nn\nm\ne\n \nf\ne\nr\na\ne\nn\n \nd\né\ns\n \nf\nr\ne\nr\ne\ns\n.\nL\ne\n \nm\no\nn\nd\ne\n \nv\ni\ne\nn\ne\nn\nt\n \ns\nu\n \nl\na\n \nt\né\nr\nr\ne\n \nl\ni\nb\nr\ns\n \nt\ne\nr\nt\no\nu\ns\n \ne\n \ns\n\'\ne\nn\nt\n\'\nv\na\nl\ne\nn\nt\n \ne\nn\n \nd\nr\ne\nt\ns\n \ne\n \nd\ni\ng\nn\ni\nt\në\n.\n \nI\nl\n \nl\no\nu\n \na\np\na\nr\nt\ni\ne\nn\nt\n \nd\n\'"
}
