id: "ady"
language: "ady"
script: "Cyrl"
name: "Adyghe"
autonym: "Адыгабзэ"
population: 444583
region: "RU"
region: "TR"
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я Ё Ӏ а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я ё ӏ"
  marks: "◌̆ ◌̈"
}
sample_text {
  masthead_full: "ЦцIi"
  masthead_partial: "Ыы"
  styles: "Дунэепстэу Къэрал Зэгохьэныгъэм (ДКъЗ) и Зэфэсым"
  tester: "мы джэпсалъэр сыдигъуи янэгу кIагъэтызэ, мыщ къыщыхэщырэ цIыф"
  poster_sm: "ЦIыф пстэури"
  poster_md: "Хэтрэ цIыфи"
  poster_lg: "ЦIыф"
  specimen_48: "Ащ нэмыкIэу, къэрал шъхьэфити, нэмыкIым иунашъо кIэти, зышъхьэфитыжьныгъэ"
  specimen_36: "Дунэепстэу Къэрал Зэгохьэныгъэм (ДКъЗ) и Зэфэсым егъэIу;\nДунэепстэу цIыфыгъэм къыхиубытэрэ хэтрэ зы цIыфи зэгохьэныгъи;"
  specimen_32: "мы джэпсалъэр сыдигъуи янэгу кIагъэтызэ, мыщ къыщыхэщырэ цIыф фэшъуашэхэмрэ фитыныгъэхэмрэ янэIэ зэрэтырагъэтырэм, фашIырэ лъытэныгъэм егъэджэныгъэ-гъэсэныгъэ гъогукIэ зырагъэужьынэу;"
  specimen_21: "Дунэепстэу Къэрал Зэгохьэныгъэм (ДКъЗ) и Зэфэсым егъэIу;\nДунэепстэу цIыфыгъэм къыхиубытэрэ хэтрэ зы цIыфи зэгохьэныгъи;\nмы джэпсалъэр сыдигъуи янэгу кIагъэтызэ, мыщ къыщыхэщырэ цIыф фэшъуашэхэмрэ фитыныгъэхэмрэ янэIэ зэрэтырагъэтырэм, фашIырэ лъытэныгъэм егъэджэныгъэ-гъэсэныгъэ гъогукIэ зырагъэужьынэу;\nцIыф фэшъуашэхэм афэгъэхьыгъэу цIыф жъугъэхэми лъэпкъхэми язэфэдэ идеал"
  specimen_16: "Дунэепстэу Къэрал Зэгохьэныгъэм (ДКъЗ) и Зэфэсым егъэIу;\nДунэепстэу цIыфыгъэм къыхиубытэрэ хэтрэ зы цIыфи зэгохьэныгъи;\nмы джэпсалъэр сыдигъуи янэгу кIагъэтызэ, мыщ къыщыхэщырэ цIыф фэшъуашэхэмрэ фитыныгъэхэмрэ янэIэ зэрэтырагъэтырэм, фашIырэ лъытэныгъэм егъэджэныгъэ-гъэсэныгъэ гъогукIэ зырагъэужьынэу;\nхэгъэгу кIоцIхэми дунэепстэуми кIо къэсми нахьы зыщызыужьырэ амалхэр зыфагъэшъхьэпэзэ мы зэгохьэныгъэм хэт къэралхэм ежьымэ ялъэпкъхэри, яунашъо кIагъэтырэ нэмыкIрэ къэралмэ ялъэпкъхэри къызэкIиубытэу, дунэепстэум и тэдэрэ чIапIи мы цIыф фэшъуашэхэмрэ фитыныгъэхэмрэ къыщащтэным, лъэшэу щызэрагъэкIоным, щагъэцэкIэным фэкъудыинхэу,"
}
