id: "af"
language: "af"
script: "Latn"
name: "Afrikaans"
autonym: "Afrikaans"
population: 9318845
region: "BW"
region: "NA"
region: "ZA"
exemplar_chars {
  base: "a á â b c d e é è ê ë f g h i î ï j k l m n o ô ö p q r s t u û v w x y z"
  auxiliary: "à å ä ã æ ç í ì ó ò ú ù ü ý"
  marks: "◌̀ ◌̂ ◌̈"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ \" “ ” ( ) [ ] § @ * / & # † ‡ ′ ″"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
}
sample_text {
  masthead_full: "AaLl"
  masthead_partial: "Ee"
  styles: "AANGESIEN erkenning vir die inherente waardigheid"
  tester: "AANGESIEN minagting vir menseregte barbaarse dade wat die gewete"
  poster_sm: "AANGESIEN dit"
  poster_md: "AANGESIEN"
  poster_lg: "Alle"
  specimen_48: "AANGESIEN die volke wat lid van die Verenigde Volke Organisasie"
  specimen_36: "AANGESIEN ’n algemene begrip van hierdie regte en vryhede van groot belang vir die bereiking van hierdie voorneme is,"
  specimen_32: "Hierdie Universele Verklaring van Menseregte as ’n algemene standaard vir die verwesenliking deur alle mense en nasies, om te verseker dat elke individu en elke"
  specimen_21: "deel van die gemeenskap hierdie Verklaring in ag sal neem en deur opvoeding, respek vir hierdie regte en vryhede te bevorder, op nasionale en internasionale vlak, daarna sal strewe om die universele en effektiewe erkenning en agting van hierdie regte te verseker, nie net vir die mense van die Lidstate nie, maar ook vir die mense in die gebiede onder hul jurisdiksie."
  specimen_16: "Alle menslike wesens word vry, met gelyke waardigheid en regte, gebore. Hulle het rede en gewete en behoort in die gees van broederskap teenoor mekaar op te tree.\nElke persoon het die reg tot al die regte en vryhede soos in die Verklaring vervat is, sonder uitsondering van enige aard soos op grond van ras, geslag, kleur, taal, godsdiens, geboorte of enige ander status.\nDaarbenewens sal geen onderskeid op grond van politieke, geregtelike of internasionale status van die land of gebied waartoe ’n persoon behoort gemaak word nie, hetsy dit ’n onafhanklike trust, nie‐selfregerend of onder enige ander beperking van soewereiniteit is."
}
