id: "aii"
language: "aii"
script: "Cyrl"
name: "Assyrian Neo-Aramaic"
preferred_name: "Assyrian"
autonym: "Лышана Атураја"
population: 0
exemplar_chars {
  base: "А Б В Г Ԁ Е Ә Ж З И Ј К Л Q L М Н П Р С Т T У Х Һ Ч Ш Ы D а б в г ԁ е ә ж з и ј к л q l м н п р с т t у х һ ч ш ы d"
}
sample_text {
  masthead_full: "ܟܠܒܪ"
  masthead_partial: "ܢܫ"
  styles: "ܡܢ ܣܒܒ ܡܘܕܝܬܐ ܒܐܝܩܪܐ ܫܪܫܢܝܐ ܠܟܠܗ ܗܕܡܐ ܕܟܠܦܬ"
  tester: "ܡܢ ܣܒܒ ܦܠܛܐ ܕܠܐ ܡܝܩܪܬܐ ܘܡܣܠܝܬܐ ܕܙܕܩܐ ܐܢܫܝܐ ܝܒ݂ܕܥܢܐ ܠܥܒ݂ܕܘܝܬܐ ܒܪܒܪܝܐ"
  poster_sm: "ܡܢ ܣܒܒ ܥܡܹܐ"
  poster_md: "ܐܝܟܐ ܦܪܡܝܬܐ"
  poster_lg: "ܒܪܢܫܐ"
  specimen_48: "ܡܘܕܘܝܠܗ ܕܐܗܐ ܒܘܕܩܐ ܬܝܒ݂ܠܝܐ ܕܙܕܩܐ ܐܢܫܝܐ ܐܝܠܐ ܚܕ ܡܟܡܠܬܐ ܓܘܢܝܬܐ ܩܐ"
  specimen_36: "ܟܠ ܒܪܢܫܐ ܒܪܝܠܗ ܚܐܪܐ ܘܒܪܒܪ ܓܘ ܐܝܩܪܐ ܘܙܕܩܐ. ܘܦܝܫܝܠܗ ܝܗܒܐ ܗܘܢܐ ܘܐܢܝܬ. ܒܘܕ ܕܐܗܐ ܓܫܩܬܝ ܥܠ ܐܚܪܢܐ ܓܪܓ ܗܘܝܐ ܒܚܕ ܪܘܚܐ ܕܐܚܢܘܬܐ."
  specimen_32: "ܟܠ ܐܢܫܐ ܝܠܗ ܒܪܒܪ ܩܡ ܩܐܢܘܢ ܘܓܪܓ ܦܐܫ ܢܛܝܪܐ ܒܝܕ ܩܐܢܘܢ ܕܠܐ ܡܬܘܬܐ ܕܦܘܪܫܘܢܝܐ ܒܠܝܗܝ. ܘܟܠ ܐܢܫܐ ܓܪܓ ܦܝܫܝ ܢܛܝܪܐ ܒܪܒܪ ܩܡ ܟܠ ܦܘܪܫܘܢܝܐ ܕܫܡܛܬܐ ܕܫܪܥܬ ܕܐܗܐ ܒܘܕܩܐ."
  specimen_21: "ܟܠ ܚܕ ܐܝܬܠܗ ܗܩܘܬܐ ܕܦܐܫ ܦܘܪܥܝܐ ܒܝܕ ܚܕ ܒܝܬ ܕܝܢܐ ܩܐ ܥܒ݂ܕܘܝܬܐ ܠܐ ܐܢܫܝܐ ܕܦܝܫܝ ܘܝܕܐ ܕܪܩܒܠ ܕܙܕܩܐ ܫܪܫܢܝܐ ܕܢܛܝܪܢܐ ܒܝܕ ܩܢܘܢܐ ܫܬܣܝܐ ܝܢ ܒܝܕ ܩܐܢܘܢ.\nܓܪܓ ܗܟ̰ ܚܕ ܠܐ ܦܐܫ ܕܒ݂ܝܩܐ ܝܢ ܡܘܬܒܐ ܓܘ ܒܝܬ ܐܣܝܪܐ ܝܢ ܛܪܝܕܐ ܡܢ ܐܬܪܐ ܕܠܐ ܩܐܢܘܢ.\nܟܠ ܚܕ ܐܝܠܗ ܒܪܒܪ ܩܡ ܒܝܬ ܕܝܢܐ ܚܐܪܐ ܘܠܐ ܡܬܓܢܝܢܐ ܓܘ ܩܛܝܬܐ ܕܗܩܘܬܐ ܘܓ̰ܒܘܝܬܐ ܘܟܠ ܓܘܢܚܐ ܕܪܩܘܠܗ.\nܓܪܓ ܠܐ ܥܘܪܝ ܓܘ ܚܝܐ ܕܝܠܢܝܐ ܕܚܕ ܦܪܣܘܦܐ ܝܢ ܒܝܬܐ ܝܢ ܐܓܪܝܬܐ ܝܢ ܐܝܩܪܐ ܝܢ ܫܡܐ ܛܒ݂ܐ ܡܫܡܗܘܬܐ. ܟܠ ܚܕ ܦܪܣܘܦܐ ܐܝܬܠܗ ܗܩܘܬܐ ܕܦܐܫ ܢܛܝܪܐ ܒܝܕ ܩܐܢܘܢ ܕܪܩܘܒܠ ܗܕܚܐ ܨܦܚܝܬܐ."
  specimen_16: "ܟܠ ܚܕ ܐܝܬܠܗ ܗܩܘܬܐ ܕܬܚܡܢܬܐ ܘܕܐܢܝܬ ܘܬܘܕܝܬܐ. ܐܗܐ ܗܩܘܬܐ ܒܚܒ݂ܫܝܠܐ ܗܩܘܬܐ ܕܫܚܠܦܬܐ ܕܬܘܕܝܬܐ ܝܢ ܗܝܡܢܘܬܐ ܘܚܐܪܘܬܐ ܒܢܘܦܫܐ ܝܢ ܥܡ ܓܘ ܫܘܬܦܘܬܐ ܥܡ ܐܚܪܢܐ.\nܟܠ ܚܕ ܐܝܬܠܗ ܗܩܘܬܐ ܕܪܥܝܢܐ ܘܗܡܙܡܬܐ. ܐܗܐ ܚܐܪܘܬܐ ܒܚܒ݂ܫܝܠܐ ܚܐܪܘܬܐ ܕܪܥܝܢܐ ܕܠܐ ܘܪܬܐ ܕܓܘܝ ܡܢ ܗܟ̰ ܐܢܫܐ ܘܛܥܘܝܐ ܒܬܪ ܘܩܒܠܬܐ ܡܕܥܢܘܬܐ ܒܟܠ ܐܘܪܚܐ ܕܗܘܝܐ ܕܠܐ ܩܝܕܐ ܕܬܚܘܒܐ.\nܟܠ ܚܕ ܦܪܣܘܦܐ ܐܝܟ ܚܕ ܗܕܡܐ ܓܘ ܫܘܬܦܘܬܐ ܐܝܬܠܗ ܗܩܘܬܐ ܠܚܬܪܓ̰ܡܥܘܬܐ ܫܘܬܦܬܐ ܓܘ ܬܡܡܬܐ ܒܐܘܪܚܐ ܥܒ݂ܕܘܬܐ ܐܬܪܝܬܐ ܘܗܝܪܬܐ ܬܒ݂ܠܝܬܐ. ܘܟܠ ܚܕ ܐܝܟ ܡܒܘܥܐ ܕܐܬܪܐ ܐܝܬܠܗ ܗܩܘܬܐ ܠܗܝܪܬܐ ܐܩܢܘܡܝܬܐ ܘܫܘܬܦܝܬܐ ܘܡܪܕܘܬܢܝܬܐ ܕܘܩܐ ܥܡ ܐܝܩܪܐ ܘܡܛܘܪܬܐ ܦܪܣܘܦܝܬܐ.\nܟܠ ܚܕ ܐܝܬܠܗ ܗܩܘܬܐ ܩܐ ܡܢܝܚܬܐ ܘܒܘܣܡܐ ܘܒܚܒܫܐ ܡܬܚܡܬܐ ܣܥܬܐ ܕܦܘܠܚܢܐ ܘܝܘܡܐ ܕܡܢܝܚܬܐ ܒܦܘܪܥܢܐ."
}
