id: "aii_Sogo"
language: "aii"
script: "Sogo"
name: "Assyrian Neo-Aramaic, Old Sogdian"
sample_text {
  masthead_full: "𐼋𐼌𐼂𐼘"
  masthead_partial: "𐼎𐼙"
  styles: "𐼍𐼏 𐼑𐼂𐼃 𐼍𐼇𐼌𐼊𐼚𐼁 𐼂𐼀𐼊𐼋𐼘𐼁 𐼙𐼘𐼙𐼎𐼊𐼁 𐼌𐼋𐼌𐼅 𐼆𐼌𐼍𐼁 𐼌𐼋"
  tester: "𐼍𐼏 𐼑𐼂𐼃 𐼔𐼌𐼔𐼁 𐼌𐼌𐼁 𐼍𐼊𐼋𐼘𐼚𐼁 𐼇𐼍𐼑𐼌𐼊𐼚𐼁 𐼌𐼈𐼌𐼋𐼁 𐼀𐼎𐼙𐼊𐼁 𐼊𐼂𐼌𐼓𐼎𐼁 𐼌𐼓𐼂𐼌𐼇𐼊𐼚𐼁 𐼂"
  poster_sm: "𐼍𐼏 𐼑𐼂𐼃 𐼀𐼎𐼎"
  poster_md: "𐼍𐼏 𐼑𐼂𐼃"
  poster_lg: "𐼂𐼘𐼎𐼙𐼁"
  specimen_48: "𐼇𐼍𐼏 𐼑𐼂𐼃 𐼌𐼀𐼚𐼘𐼇𐼚𐼁 𐼆𐼌𐼍𐼁 𐼋𐼂𐼇𐼌𐼎𐼁 𐼌𐼆𐼊𐼘𐼁 𐼓𐼍 𐼀𐼍𐼇𐼚𐼁 𐼍𐼉𐼊𐼌𐼁 𐼌"
  specimen_36: "𐼋𐼌 𐼂𐼘𐼎𐼙𐼁 𐼂𐼘𐼊𐼌𐼅 𐼉𐼀𐼘𐼁 𐼇𐼂𐼘𐼂𐼘 𐼄𐼇 𐼀𐼊𐼋𐼘𐼁 𐼇𐼈𐼌𐼋𐼁. 𐼇𐼔𐼊𐼙𐼊𐼌𐼅 𐼊𐼆𐼂𐼁 𐼆𐼇𐼎𐼁 𐼇𐼀𐼎𐼊𐼛. 𐼂𐼇𐼌 𐼌𐼀𐼆𐼁 𐼄𐼙𐼋𐼚𐼊 𐼧 𐼀𐼉𐼘𐼎𐼁 𐼄𐼘𐼄 𐼆𐼇𐼊𐼁 𐼂𐼉𐼌 𐼘𐼇𐼉𐼁 𐼌𐼀𐼉𐼎𐼇𐼚𐼁."
  specimen_32: "𐼋𐼌 𐼀𐼎𐼙𐼁 𐼊𐼌𐼅 𐼂𐼘𐼂𐼘 𐼋𐼍 𐼋𐼀𐼎𐼇𐼏 𐼇𐼄𐼘𐼄 𐼔𐼀𐼙 𐼎𐼔𐼊𐼘𐼁 𐼂𐼊𐼌 𐼋𐼀𐼎𐼇𐼏 𐼌𐼌𐼁 𐼍𐼚𐼇𐼚𐼁 𐼌𐼔𐼇𐼘𐼙𐼇𐼎𐼊𐼁 𐼂𐼌𐼊𐼆𐼊. 𐼇𐼋𐼌 𐼀𐼎𐼙𐼁 𐼄𐼘𐼄 𐼔𐼊𐼙𐼊 𐼎𐼔𐼊𐼘𐼁 𐼂𐼘𐼂𐼘 𐼋𐼍 𐼋𐼌 𐼔𐼇𐼘𐼙𐼇𐼎𐼊𐼁 𐼌𐼙𐼍𐼔𐼚𐼁 𐼌𐼙𐼘𐼓𐼛 𐼌𐼀𐼆𐼁 𐼂𐼇𐼌𐼋𐼁."
  specimen_21: "𐼋𐼌 𐼉𐼌 𐼀𐼊𐼚𐼌𐼅 𐼆𐼋𐼇𐼚𐼁 𐼌𐼔𐼀𐼙 𐼔𐼇𐼘𐼓𐼊𐼁 𐼂𐼊𐼌 𐼉𐼌 𐼂𐼊𐼛 𐼌𐼊𐼎𐼁 𐼋𐼁 𐼓𐼂𐼌𐼇𐼊𐼚𐼁 𐼌𐼁 𐼀𐼎𐼙𐼊𐼁 𐼌𐼔𐼊𐼙𐼊 𐼇𐼊𐼌𐼁 𐼌𐼘𐼋𐼂𐼌 𐼌𐼈𐼌𐼋𐼁 𐼙𐼘𐼙𐼎𐼊𐼁 𐼌𐼎𐼔𐼊𐼘𐼎𐼁 𐼂𐼊𐼌 𐼋𐼎𐼇𐼎𐼁 𐼙𐼚𐼑𐼊𐼁 𐼊𐼏 𐼂𐼊𐼌 𐼋𐼀𐼎𐼇𐼏.\n𐼄𐼘𐼄 𐼆𐼋 𐼉𐼌 𐼌𐼁 𐼔𐼀𐼙 𐼌𐼂𐼊𐼋𐼁 𐼊𐼏 𐼍𐼇𐼚𐼂𐼁 𐼄𐼇 𐼂𐼊𐼛 𐼀𐼑𐼊𐼘𐼁 𐼊𐼏 𐼔𐼘𐼊𐼌𐼁 𐼍𐼏 𐼀𐼚𐼘𐼁 𐼌𐼌𐼁 𐼋𐼀𐼎𐼇𐼏.\n𐼋𐼌 𐼉𐼌 𐼀𐼊𐼌𐼅 𐼂𐼘𐼂𐼘 𐼋𐼍 𐼂𐼊𐼛 𐼌𐼊𐼎𐼁 𐼉𐼀𐼘𐼁 𐼇𐼌𐼁 𐼍𐼚𐼄𐼎𐼊𐼎𐼁 𐼄𐼇 𐼋𐼔𐼊𐼚𐼁 𐼌𐼆𐼋𐼇𐼚𐼁 𐼇𐼄𐼂𐼇𐼊𐼚𐼁 𐼇𐼋𐼌 𐼄𐼇𐼎𐼉𐼁 𐼌𐼘𐼋𐼇𐼌𐼅.\n𐼄𐼘𐼄 𐼌𐼁 𐼓𐼇𐼘𐼊 𐼄𐼇 𐼉𐼊𐼁 𐼌𐼊𐼌𐼎𐼊𐼁 𐼌𐼉𐼌 𐼔𐼘𐼑𐼇𐼔𐼁 𐼊𐼏 𐼂𐼊𐼚𐼁 𐼊𐼏 𐼀𐼄𐼘𐼊𐼚𐼁 𐼊𐼏 𐼀𐼊𐼋𐼘𐼁 𐼊𐼏 𐼙𐼍𐼁 𐼔𐼂𐼁 𐼍𐼙𐼍𐼆𐼇𐼚𐼁. 𐼋𐼌 𐼉𐼌 𐼔𐼘𐼑𐼇𐼔𐼁 𐼀𐼊𐼚𐼌𐼅 𐼆𐼋𐼇𐼚𐼁 𐼌𐼔𐼀𐼙 𐼎𐼔𐼊𐼘𐼁 𐼂𐼊𐼌 𐼋𐼀𐼎𐼇𐼏 𐼌𐼘𐼋𐼇𐼂𐼌 𐼆𐼌𐼉𐼁 𐼕𐼔𐼉𐼊𐼚𐼁."
  specimen_16: "𐼋𐼌 𐼉𐼌 𐼀𐼊𐼚𐼌𐼅 𐼆𐼋𐼇𐼚𐼁 𐼌𐼚𐼉𐼍𐼎𐼚𐼁 𐼇𐼌𐼀𐼎𐼊𐼛 𐼇𐼚𐼇𐼌𐼊𐼚𐼁. 𐼀𐼆𐼁 𐼆𐼋𐼇𐼚𐼁 𐼂𐼉𐼂𐼙𐼊𐼌𐼁 𐼆𐼋𐼇𐼚𐼁 𐼌𐼙𐼉𐼌𐼔𐼚𐼁 𐼌𐼚𐼇𐼌𐼊𐼚𐼁 𐼊𐼏 𐼆𐼊𐼍𐼎𐼇𐼚𐼁 𐼇𐼉𐼀𐼘𐼇𐼚𐼁 𐼂𐼎𐼇𐼔𐼙𐼁 𐼊𐼏 𐼓𐼍 𐼄𐼇 𐼙𐼇𐼚𐼔𐼇𐼚𐼁 𐼓𐼍 𐼀𐼉𐼘𐼎𐼁.\n𐼋𐼌 𐼉𐼌 𐼀𐼊𐼚𐼌𐼅 𐼆𐼋𐼇𐼚𐼁 𐼌𐼘𐼓𐼊𐼎𐼁 𐼇𐼆𐼍𐼈𐼍𐼚𐼁. 𐼀𐼆𐼁 𐼉𐼀𐼘𐼇𐼚𐼁 𐼂𐼉𐼂𐼙𐼊𐼌𐼁 𐼉𐼀𐼘𐼇𐼚𐼁 𐼌𐼘𐼓𐼊𐼎𐼁 𐼌𐼌𐼁 𐼇𐼘𐼚𐼁 𐼌𐼄𐼇𐼊 𐼍𐼏 𐼆𐼋 𐼀𐼎𐼙𐼁 𐼇𐼔𐼓𐼇𐼊𐼁 𐼂𐼚𐼘 𐼇𐼋𐼂𐼌𐼚𐼁 𐼍𐼌𐼓𐼎𐼇𐼚𐼁 𐼂𐼋𐼌 𐼀𐼇𐼘𐼉𐼁 𐼌𐼆𐼇𐼊𐼁 𐼌𐼌𐼁 𐼋𐼊𐼌𐼁 𐼌𐼚𐼉𐼇𐼂𐼁.\n𐼋𐼌 𐼉𐼌 𐼔𐼘𐼑𐼇𐼔𐼁 𐼀𐼊𐼋 𐼉𐼌 𐼆𐼌𐼍𐼁 𐼄𐼇 𐼙𐼇𐼚𐼔𐼇𐼚𐼁 𐼀𐼊𐼚𐼌𐼅 𐼆𐼋𐼇𐼚𐼁 𐼌𐼉𐼚𐼘𐼄𐼍𐼓𐼇𐼚𐼁 𐼙𐼇𐼚𐼔𐼚𐼁 𐼄𐼇 𐼚𐼍𐼍𐼚𐼁 𐼂𐼀𐼇𐼘𐼉𐼁 𐼓𐼂𐼌𐼇𐼚𐼁 𐼀𐼚𐼘𐼊𐼚𐼁 𐼇𐼆𐼊𐼘𐼚𐼁 𐼚𐼂𐼌𐼊𐼚𐼁. 𐼇𐼋𐼌 𐼉𐼌 𐼀𐼊𐼋 𐼍𐼂𐼇𐼓𐼁 𐼌𐼀𐼚𐼘𐼁 𐼀𐼊𐼚𐼌𐼅 𐼆𐼋𐼇𐼚𐼁 𐼌𐼆𐼊𐼘𐼚𐼁 𐼀𐼋𐼎𐼇𐼍𐼊𐼚𐼁 𐼇𐼙𐼇𐼚𐼔𐼊𐼚𐼁 𐼇𐼍𐼘𐼌𐼇𐼚𐼎𐼊𐼚𐼁 𐼌𐼇𐼋𐼁 𐼓𐼍 𐼀𐼊𐼋𐼘𐼁 𐼇𐼍𐼔𐼇𐼘𐼚𐼁 𐼔𐼘𐼑𐼇𐼔𐼊𐼚𐼁.\n𐼋𐼌 𐼉𐼌 𐼀𐼊𐼚𐼌𐼅 𐼆𐼋𐼇𐼚𐼁 𐼋𐼁 𐼍𐼎𐼊𐼉𐼚𐼁 𐼇𐼂𐼇𐼑𐼍𐼁 𐼇𐼂𐼉𐼂𐼙𐼁 𐼍𐼚𐼉𐼍𐼚𐼁 𐼑𐼓𐼚𐼁 𐼌𐼔𐼇𐼌𐼉𐼎𐼁 𐼇𐼊𐼇𐼍𐼁 𐼌𐼍𐼎𐼊𐼉𐼚𐼁 𐼂𐼔𐼇𐼘𐼓𐼎𐼁."
}
