id: "aii_Latn"
language: "aii"
script: "Latn"
name: "Assyrian Neo-Aramaic, Latin"
region: "IQ"
sample_text {
  masthead_full: "KkUu"
  masthead_partial: "Ll"
  styles: "Kulleh birnasheh ina biryeh kheereh U\' damyaneh"
  tester: "Kulleh birnasheh ina biryeh kheereh U\' damyaneh B\' iqara U\' zitqeh."
  poster_sm: "Kulleh"
  poster_md: "Kulleh"
  poster_lg: "Kulleh"
  specimen_48: "Kulleh birnasheh ina biryeh kheereh U\' damyaneh B\' iqara U\' zitqeh"
  specimen_36: "Kulleh birnasheh ina biryeh kheereh U\' damyaneh B\' iqara U\' zitqeh. Biryena B\' parmeta U\' hona, U\' shart awi min oudaleh B\' roukha D\' akhunawoota."
  specimen_32: "Kulleh birnasheh ina biryeh kheereh U\' damyaneh B\' iqara U\' zitqeh. Biryena B\' parmeta U\' hona, U\' shart awi min oudaleh B\' roukha D\' akhunawoota."
  specimen_21: "Kulleh birnasheh ina biryeh kheereh U\' damyaneh B\' iqara U\' zitqeh. Biryena B\' parmeta U\' hona, U\' shart awi min oudaleh B\' roukha D\' akhunawoota.\nKulleh birnasheh ina biryeh kheereh U\' damyaneh B\' iqara U\' zitqeh. Biryena B\' parmeta U\' hona, U\' shart awi min oudaleh B\' roukha D\' akhunawoota.\nKulleh birnasheh ina biryeh kheereh U\' damyaneh B\' iqara U\' zitqeh. Biryena B\' parmeta U\' hona, U\' shart awi min oudaleh B\' roukha D\' akhunawoota."
  specimen_16: "Kulleh birnasheh ina biryeh kheereh U\' damyaneh B\' iqara U\' zitqeh. Biryena B\' parmeta U\' hona, U\' shart awi min oudaleh B\' roukha D\' akhunawoota.\nKulleh birnasheh ina biryeh kheereh U\' damyaneh B\' iqara U\' zitqeh. Biryena B\' parmeta U\' hona, U\' shart awi min oudaleh B\' roukha D\' akhunawoota.\nKulleh birnasheh ina biryeh kheereh U\' damyaneh B\' iqara U\' zitqeh. Biryena B\' parmeta U\' hona, U\' shart awi min oudaleh B\' roukha D\' akhunawoota.\nKulleh birnasheh ina biryeh kheereh U\' damyaneh B\' iqara U\' zitqeh. Biryena B\' parmeta U\' hona, U\' shart awi min oudaleh B\' roukha D\' akhunawoota.\nKulleh birnasheh ina biryeh kheereh U\' damyaneh B\' iqara U\' zitqeh. Biryena B\' parmeta U\' hona, U\' shart awi min oudaleh B\' roukha D\' akhunawoota."
}
