id: "ak"
language: "ak"
script: "Latn"
name: "Akan"
autonym: "Fante"
population: 11442678
region: "GH"
exemplar_chars {
  base: "a b d e ɛ f g h i k l m n o ɔ p r s t u w y"
  auxiliary: "c j q v z"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B C D E Ɛ F G H I J K L M N O Ɔ P Q R S T U V W X Y Z"
}
sample_text {
  masthead_full: "WwƆɔ"
  masthead_partial: "Oo"
  styles: "Ɔnam dɛ adasa hɔn enyimnyam yɛ pɛr na ndzinoa"
  tester: "Ɔnam dɛ tsia a yetsiatsia nyimpa ne ndzinoa do no dze ewurkadze"
  poster_sm: "Ɔnam dɛ ohia"
  poster_md: "Ɔnam dɛ aman"
  poster_lg: "Wɔwo"
  specimen_48: "NHYIAMU KƐSE NO YI ADASA NDZINOA HO DAWURBƆ no kyerɛ dɛ: ɔno nye"
  specimen_36: "Onnyi dɛ wɔdze obiara to nkowaasom mu anaadɛ wɔma ɔsom ɔsomhun; ɔwɔ dɛ wogu nkowaasom na ndɔnkɔgua korakora."
  specimen_32: "Obiara a wɔayɛ bɔn etsia ne ndzinoa a mbra na amambu ho mbra ma no ho kwan no, wɔ ho kwan dɛ odua asɛndzi baguafo do gye nsiesie anaa mpata a ɔfata."
  specimen_21: "Onnyi dɛ abɔtsirmu ara wɔkyer obi, wɔdze no sie, anaa wotwa no esu.\nObiara wɔ ho kwan dɛ bagua asɛndzifo a wɔnntɔn hɔn asowa nndzi tsena hwehwɛ n\'asɛm mu pefee wɔ ne ndzinoa, n\'asadze anaa ewudzisɛm ho sombo bi a wɔdze abɔ no ho.\nOnnyi dɛ abɔtsirmu ara wɔdze ɔho hyehyɛ obi no kɔkoamunsɛm, n\'ebusuasɛm anaa n\'efisɛm mu; anaadɛ wogu n\'enyimnyam na ne dzin ho fi. Ɔyɛ obiara ne ndzinoa dɛ mbra bɔ no ho ban tsia ndzeyɛɛ a ɔtsetse dɛm yi."
  specimen_16: "Obiara wɔ ndzinoa dɛ ɔyɛ n\'adwen, ɔsoa noara ne tsibowa, ɔfa nyamesom biara a ɔpɛ. Dɛm ndzinoa yi ne fã bi nye kwan a obiara wɔ dɛ ɔsesa ne nyamesom anaa ne gyedzi na kwan so a ɔfa do dze ma ne gyedzi no da edzi wɔ bagua mu anaa nsumaa mu, dɛ ɔno nko anaadɛ nyimpa binom kã ho wɔ iyi mu.\nObiara wɔ ho kwan dɛ ɔkyerɛ n\'adwen wɔ biribi ho. Dza ɔkã dɛm ndzinoa yi ho nye dɛ obiara botum ayɛ n\'adwen wɔ biribi ho a ntotoananmu biara nnyi mu. Dza ɔkã ho bio so nye dɛ otum anaa otsie asɛm nye nsusui biara a ɔnam kwan biara do na efi mbea nyina, na ɔma nyimpa binom so tse."
}
