id: "akk_Xsux"
language: "akk"
script: "Xsux"
name: "Akkadian"
population: 0
sample_text {
  masthead_full: "𒀭𒆗𒀳𒁇"
  masthead_partial: "𒀀𒈾"
  styles: "𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸"
  tester: "𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸"
  poster_sm: "𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸"
  poster_md: "𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸"
  poster_lg: "𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸"
  specimen_48: "𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸"
  specimen_36: "𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸"
  specimen_32: "𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸\n𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸"
  specimen_21: "𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸\n𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸\n𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸\n𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸"
  specimen_16: "𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸\n𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸\n𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸\n𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸\n𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸\n𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸\n𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸\n𒀭𒆗𒀳𒀭𒁇𒀀𒈾𒀭𒀜𒋾𒀀𒇉𒈦𒄘𒃼𒀭𒅎𒀭𒀀𒇉𒀀𒌑𒋛𒀪𒀉𒁍𒁕𒀜𒋫𒀀𒈝𒀊𒁍𒀸𒅗𒇻𒈾𒀫𒀀𒈾𒆪𒀠𒁍𒌝𒀀𒇉𒌓𒄒𒉣𒀉𒋾𒀀𒊏𒀭𒌓𒀝𒆪𒌋𒀭𒆷𒈦𒇻𒀭𒆘𒀀𒁺𒀭𒀫𒌓𒀭𒈾𒀭𒇸𒀀𒉿𒈝𒀸"
}
historical: true
