id: "ale_Latn"
language: "ale"
script: "Latn"
name: "Aleut"
population: 0
region: "US"
sample_text {
  masthead_full: "AaNn"
  masthead_partial: "Ĝĝ"
  styles: "Anĝaĝinam huzungis agaxtakuu ingisxigikux̂"
  tester: "Anĝaĝinam huzungis agaxtakuu ingisxigikux̂ ama liidax̂ nagan sahnganaxtada."
  poster_sm: "Anĝaĝinam huzungis"
  poster_md: "Anĝaĝinam"
  poster_lg: "huzungis"
  specimen_48: "Anĝaĝinam huzungis agaxtakuu ingisxigikux̂ ama liidax̂"
  specimen_36: "Anĝaĝinam huzungis agaxtakuu ingisxigikux̂ ama liidax̂ nagan sahnganaxtada. Txin sakaaĝatal anagis mataxchx̂ida inaqamchix̂ agangudaganasaaĝiiĝutakus ludaangan huzuu ngaan quĝasaatakus."
  specimen_32: "Anĝaĝinam huzungis agaxtakuu ingisxigikux̂ ama liidax̂ nagan sahnganaxtada. Txin sakaaĝatal anagis mataxchx̂ida inaqamchix̂ agangudaganasaaĝiiĝutakus ludaangan huzuu ngaan quĝasaatakus."
  specimen_21: "Anĝaĝinam huzungis agaxtakuu ingisxigikux̂ ama liidax̂ nagan sahnganaxtada. Txin sakaaĝatal anagis mataxchx̂ida inaqamchix̂ agangudaganasaaĝiiĝutakus ludaangan huzuu ngaan quĝasaatakus.\nAnĝaĝinam huzungis agaxtakuu ingisxigikux̂ ama liidax̂ nagan sahnganaxtada. Txin sakaaĝatal anagis mataxchx̂ida inaqamchix̂ agangudaganasaaĝiiĝutakus ludaangan huzuu ngaan quĝasaatakus."
  specimen_16: "Anĝaĝinam huzungis agaxtakuu ingisxigikux̂ ama liidax̂ nagan sahnganaxtada. Txin sakaaĝatal anagis mataxchx̂ida inaqamchix̂ agangudaganasaaĝiiĝutakus ludaangan huzuu ngaan quĝasaatakus.\nAnĝaĝinam huzungis agaxtakuu ingisxigikux̂ ama liidax̂ nagan sahnganaxtada. Txin sakaaĝatal anagis mataxchx̂ida inaqamchix̂ agangudaganasaaĝiiĝutakus ludaangan huzuu ngaan quĝasaatakus.\nAnĝaĝinam huzungis agaxtakuu ingisxigikux̂ ama liidax̂ nagan sahnganaxtada. Txin sakaaĝatal anagis mataxchx̂ida inaqamchix̂ agangudaganasaaĝiiĝutakus ludaangan huzuu ngaan quĝasaatakus.\nAnĝaĝinam huzungis agaxtakuu ingisxigikux̂ ama liidax̂ nagan sahnganaxtada. Txin sakaaĝatal anagis mataxchx̂ida inaqamchix̂ agangudaganasaaĝiiĝutakus ludaangan huzuu ngaan quĝasaatakus."
}
