id: "amr_Latn"
language: "amr"
script: "Latn"
name: "Amarakaeri"
sample_text {
  masthead_full: "AaYy"
  masthead_partial: "Dd"
  styles: "A\ny\na\n\'\nd\na\n \na\nr\na\nt\nb\nu\nt\n \nk\na\nt\ne\np\ni"
  tester: "A\ny\na\n\'\nd\na\n \na\nr\na\nt\nb\nu\nt\n \nk\na\nt\ne\np\ni\n\'\n \ne\nk\na\n\'\nt\na\n\'\n \no\nn"
  poster_sm: "A\ny\na\n\'\nd\na"
  poster_md: "A\ny\na\n\'\nd"
  poster_lg: "A\ny"
  specimen_48: "A\ny\na\n\'\nd\na\n \na\nr\na\nt\nb\nu\nt\n \nk\na\nt\ne\np\ni\n\'\n \ne\nk\na\n\'\nt\na\n\'\n \no\nn"
  specimen_36: "A\ny\na\n\'\nd\na\n \na\nr\na\nt\nb\nu\nt\n \nk\na\nt\ne\np\ni\n\'\n \ne\nk\na\n\'\nt\na\n\'\n \no\nn\n\'\np\na\nk\np\no\n \nk\na\n\'\nd\ni\nk\n \no\ṉ\n\'\nn\ne\n.\n \nN"
  specimen_32: "A\ny\na\n\'\nd\na\n \na\nr\na\nt\nb\nu\nt\n \nk\na\nt\ne\np\ni\n\'\n \ne\nk\na\n\'\nt\na\n\'\n \no\nn\n\'\np\na\nk\np\no\n \nk\na\n\'\nd\ni\nk\n \no\ṉ\n\'\nn\ne\n.\n \nN\no\ng\n \na\nr\na\nt\nb\nu\nt\n \nh\nu\na\nd\na\nk\n \no\ṉ\n\'"
  specimen_21: "A\ny\na\n\'\nd\na\n \na\nr\na\nt\nb\nu\nt\n \nk\na\nt\ne\np\ni\n\'\n \ne\nk\na\n\'\nt\na\n\'\n \no\nn\n\'\np\na\nk\np\no\n \nk\na\n\'\nd\ni\nk\n \no\ṉ\n\'\nn\ne\n.\n \nN\no\ng\n \na\nr\na\nt\nb\nu\nt\n \nh\nu\na\nd\na\nk\n \no\ṉ\n\'\nn\ne\np\no\n \nk\no\ṉ\nn\ni\ng\nt\ni\n \no\np\nu\nd\no\ṉ\nm\ne\ny\n \nh\nu\na\nd\na\nk\n \nm\no\n\'\ne\ṉ\n.\n \nA\ny\na\n\'\nd\na\n \nh\nu\na\nd\na\nk\n \ne\nk\na\n\'\n \nn\no\np\no\ne\ṉ\n\'\nd\ni\nk\n \no\ṉ\n\'\nn\ne\n \nk\ne\nn\np\na\n\'\nt\ni\n \nd\na\nk"
  specimen_16: "A\ny\na\n\'\nd\na\n \na\nr\na\nt\nb\nu\nt\n \nk\na\nt\ne\np\ni\n\'\n \ne\nk\na\n\'\nt\na\n\'\n \no\nn\n\'\np\na\nk\np\no\n \nk\na\n\'\nd\ni\nk\n \no\ṉ\n\'\nn\ne\n.\n \nN\no\ng\n \na\nr\na\nt\nb\nu\nt\n \nh\nu\na\nd\na\nk\n \no\ṉ\n\'\nn\ne\np\no\n \nk\no\ṉ\nn\ni\ng\nt\ni\n \no\np\nu\nd\no\ṉ\nm\ne\ny\n \nh\nu\na\nd\na\nk\n \nm\no\n\'\ne\ṉ\n.\n \nA\ny\na\n\'\nd\na\n \nh\nu\na\nd\na\nk\n \ne\nk\na\n\'\n \nn\no\np\no\ne\ṉ\n\'\nd\ni\nk\n \no\ṉ\n\'\nn\ne\n \nk\ne\nn\np\na\n\'\nt\ni\n \nd\na\nk\nh\nu\ne\na\n\'\n \ne\nk\na\n\'\n \nn\no\np\no\ne\ṉ\n\'\nd\ni\nk\n \no\ṉ\n\'\nn\ne\n \nk\ne\nn\np\na\n\'\nt\ni\n \nk\no\ṉ\nn\ni\ng\n \nh\nu\na\nm\na\n\'\nb\nu\ny\nt\na\nj\n \no\n \n\'\nt\ni\nh\nu\na\np\no\nk\ni\nk\na\n\'\n \nk\no\ṉ\nn\ni\ng\nt\ni\n \nn\no\ng\no\ṉ\nm\ne\ny\nt\na\nj\n \nt\ni\nh\nu\na\np\no\nk\ni\nk\na\n \n\'\nd\ni\nk\n \no\ṉ\n\'\nn\ne\n.\nA\ny\na\n\'\nd\na\n \na\nr\na\nt\nb\nu\nt\n \nk\na"
}
