id: "amr_Latn"
language: "amr"
script: "Latn"
name: "Amarakaeri"
region: "PE"
sample_text {
  masthead_full: "AaYy"
  masthead_partial: "Dd"
  styles: "Aya\'da aratbut katepi\' eka\'ta\' on\'pakpo ka\'dik"
  tester: "Aya\'da aratbut katepi\' eka\'ta\' on\'pakpo ka\'dik o̱\'ne. Nog aratbut huadak"
  poster_sm: "Aya\'da aratbut"
  poster_md: "Aya\'da"
  poster_lg: "Aya\'da"
  specimen_48: "Aya\'da aratbut katepi\' eka\'ta\' on\'pakpo ka\'dik o̱\'ne. Nog aratbut huadak o̱\'nepo"
  specimen_36: "Aya\'da aratbut katepi\' eka\'ta\' on\'pakpo ka\'dik o̱\'ne. Nog aratbut huadak o̱\'nepo ko̱nigti opudo̱mey huadak mo\'e̱. Aya\'da huadak eka\' nopoe̱\'dik o̱\'ne kenpa\'ti dakhuea\' eka\' nopoe̱\'dik o̱\'ne kenpa\'ti ko̱nig huama\'buytaj o \'tihuapokika\' ko̱nigti nogo̱meytaj tihuapokika \'dik o̱\'ne.\nAya\'da aratbut katepi\' eka\'ta\' on\'pakpo ka\'dik o̱\'ne. Nog aratbut huadak o̱\'nepo ko̱nigti opudo̱mey huadak mo\'e̱. Aya\'da huadak eka\' nopoe̱\'dik o̱\'ne kenpa\'ti dakhuea\' eka\' nopoe̱\'dik o̱\'ne kenpa\'ti ko̱nig huama\'buytaj o \'tihuapokika\' ko̱nigti nogo̱meytaj tihuapokika \'dik o̱\'ne."
  specimen_32: "Aya\'da aratbut katepi\' eka\'ta\' on\'pakpo ka\'dik o̱\'ne. Nog aratbut huadak o̱\'nepo ko̱nigti opudo̱mey huadak mo\'e̱. Aya\'da huadak eka\' nopoe̱\'dik o̱\'ne kenpa\'ti dakhuea\' eka\' nopoe̱\'dik o̱\'ne kenpa\'ti ko̱nig huama\'buytaj o \'tihuapokika\' ko̱nigti nogo̱meytaj tihuapokika \'dik o̱\'ne.\nAya\'da aratbut katepi\' eka\'ta\' on\'pakpo ka\'dik o̱\'ne. Nog aratbut huadak o̱\'nepo ko̱nigti opudo̱mey huadak mo\'e̱. Aya\'da huadak eka\' nopoe̱\'dik o̱\'ne kenpa\'ti dakhuea\' eka\' nopoe̱\'dik o̱\'ne kenpa\'ti ko̱nig huama\'buytaj o \'tihuapokika\' ko̱nigti nogo̱meytaj tihuapokika \'dik o̱\'ne."
  specimen_21: "Aya\'da aratbut katepi\' eka\'ta\' on\'pakpo ka\'dik o̱\'ne. Nog aratbut huadak o̱\'nepo ko̱nigti opudo̱mey huadak mo\'e̱. Aya\'da huadak eka\' nopoe̱\'dik o̱\'ne kenpa\'ti dakhuea\' eka\' nopoe̱\'dik o̱\'ne kenpa\'ti ko̱nig huama\'buytaj o \'tihuapokika\' ko̱nigti nogo̱meytaj tihuapokika \'dik o̱\'ne.\nAya\'da aratbut katepi\' eka\'ta\' on\'pakpo ka\'dik o̱\'ne. Nog aratbut huadak o̱\'nepo ko̱nigti opudo̱mey huadak mo\'e̱. Aya\'da huadak eka\' nopoe̱\'dik o̱\'ne kenpa\'ti dakhuea\' eka\' nopoe̱\'dik o̱\'ne kenpa\'ti ko̱nig huama\'buytaj o \'tihuapokika\' ko̱nigti nogo̱meytaj tihuapokika \'dik o̱\'ne."
  specimen_16: "Aya\'da aratbut katepi\' eka\'ta\' on\'pakpo ka\'dik o̱\'ne. Nog aratbut huadak o̱\'nepo ko̱nigti opudo̱mey huadak mo\'e̱. Aya\'da huadak eka\' nopoe̱\'dik o̱\'ne kenpa\'ti dakhuea\' eka\' nopoe̱\'dik o̱\'ne kenpa\'ti ko̱nig huama\'buytaj o \'tihuapokika\' ko̱nigti nogo̱meytaj tihuapokika \'dik o̱\'ne.\nAya\'da aratbut katepi\' eka\'ta\' on\'pakpo ka\'dik o̱\'ne. Nog aratbut huadak o̱\'nepo ko̱nigti opudo̱mey huadak mo\'e̱. Aya\'da huadak eka\' nopoe̱\'dik o̱\'ne kenpa\'ti dakhuea\' eka\' nopoe̱\'dik o̱\'ne kenpa\'ti ko̱nig huama\'buytaj o \'tihuapokika\' ko̱nigti nogo̱meytaj tihuapokika \'dik o̱\'ne.\nAya\'da aratbut katepi\' eka\'ta\' on\'pakpo ka\'dik o̱\'ne. Nog aratbut huadak o̱\'nepo ko̱nigti opudo̱mey huadak mo\'e̱. Aya\'da huadak eka\' nopoe̱\'dik o̱\'ne kenpa\'ti dakhuea\' eka\' nopoe̱\'dik o̱\'ne kenpa\'ti ko̱nig huama\'buytaj o \'tihuapokika\' ko̱nigti nogo̱meytaj tihuapokika \'dik o̱\'ne."
}
