id: "arc_Nbat"
language: "arc"
script: "Nbat"
name: "Aramaic, Nabataean"
population: 0
sample_text {
  masthead_full: "𐢅𐢕𐢆𐢚"
  masthead_partial: "𐢂𐢛"
  styles: "𐢅𐢕𐢆 𐢚𐢂𐢛𐢀 𐢅𐢍 𐢗𐢃𐢅 𐢏𐢇𐢑𐢔 𐢁𐢖𐢍𐢀 𐢃𐢛 𐢈𐢁𐢑𐢔 𐢑𐢕𐢘𐢝𐢆 𐢈𐢍𐢑𐢅𐢆"
  tester: "𐢅𐢕𐢆 𐢚𐢂𐢛𐢀 𐢅𐢍 𐢗𐢃𐢅 𐢏𐢇𐢑𐢔 𐢁𐢖𐢍𐢀 𐢃𐢛 𐢈𐢁𐢑𐢔 𐢑𐢕𐢘𐢝𐢆 𐢈𐢍𐢑𐢅𐢆 𐢈𐢁𐢊𐢛𐢆 𐢁𐢝𐢅𐢚 𐢗𐢅 𐢗𐢑𐢒"
  poster_sm: "𐢅𐢕𐢆 𐢚𐢂𐢛𐢀 𐢅𐢍"
  poster_md: "𐢅𐢕𐢆 𐢚𐢂𐢛𐢀"
  poster_lg: "𐢅𐢕𐢆"
  specimen_48: "𐢅𐢕𐢆 𐢚𐢂𐢛𐢀 𐢅𐢍 𐢗𐢃𐢅 𐢏𐢇𐢑𐢔 𐢁𐢖𐢍𐢀 𐢃𐢛 𐢈𐢁𐢑𐢔 𐢑𐢕𐢘𐢝𐢆 𐢈𐢍𐢑𐢅𐢆 𐢈𐢁𐢊𐢛𐢆"
  specimen_36: "𐢅𐢕𐢆 𐢚𐢂𐢛𐢀 𐢅𐢍 𐢗𐢃𐢅 𐢏𐢇𐢑𐢔 𐢁𐢖𐢍𐢀 𐢃𐢛 𐢈𐢁𐢑𐢔 𐢑𐢕𐢘𐢝𐢆 𐢈𐢍𐢑𐢅𐢆 𐢈𐢁𐢊𐢛𐢆 𐢁𐢝𐢅𐢚 𐢗𐢅 𐢗𐢑𐢒 𐢈𐢁𐢍𐢞𐢌 𐢚𐢃𐢛𐢀 𐢅𐢕𐢆 𐢊𐢛𐢒 𐢏𐢊𐢑𐢍𐢚𐢞 𐢊𐢛𐢓𐢀 𐢅𐢌 𐢓𐢊𐢛𐢒 𐢑𐢅𐢈𐢝𐢛𐢀 𐢃𐢕𐢃𐢋𐢈 𐢈𐢝𐢑𐢓𐢈"
  specimen_32: "𐢅𐢕𐢆 𐢚𐢂𐢛𐢀 𐢅𐢍 𐢗𐢃𐢅 𐢏𐢇𐢑𐢔 𐢁𐢖𐢍𐢀 𐢃𐢛 𐢈𐢁𐢑𐢔 𐢑𐢕𐢘𐢝𐢆 𐢈𐢍𐢑𐢅𐢆 𐢈𐢁𐢊𐢛𐢆 𐢁𐢝𐢅𐢚 𐢗𐢅 𐢗𐢑𐢒 𐢈𐢁𐢍𐢞𐢌 𐢚𐢃𐢛𐢀 𐢅𐢕𐢆 𐢊𐢛𐢒 𐢏𐢊𐢑𐢍𐢚𐢞 𐢊𐢛𐢓𐢀 𐢅𐢌 𐢓𐢊𐢛𐢒 𐢑𐢅𐢈𐢝𐢛𐢀 𐢃𐢕𐢃𐢋𐢈 𐢈𐢝𐢑𐢓𐢈"
  specimen_21: "𐢅𐢕𐢆 𐢚𐢂𐢛𐢀 𐢅𐢍 𐢗𐢃𐢅 𐢏𐢇𐢑𐢔 𐢁𐢖𐢍𐢀 𐢃𐢛 𐢈𐢁𐢑𐢔 𐢑𐢕𐢘𐢝𐢆 𐢈𐢍𐢑𐢅𐢆 𐢈𐢁𐢊𐢛𐢆 𐢁𐢝𐢅𐢚 𐢗𐢅 𐢗𐢑𐢒 𐢈𐢁𐢍𐢞𐢌 𐢚𐢃𐢛𐢀 𐢅𐢕𐢆 𐢊𐢛𐢒 𐢏𐢊𐢑𐢍𐢚𐢞 𐢊𐢛𐢓𐢀 𐢅𐢌 𐢓𐢊𐢛𐢒 𐢑𐢅𐢈𐢝𐢛𐢀 𐢃𐢕𐢃𐢋𐢈 𐢈𐢝𐢑𐢓𐢈\n𐢅𐢕𐢆 𐢚𐢂𐢛𐢀 𐢅𐢍 𐢗𐢃𐢅 𐢏𐢇𐢑𐢔 𐢁𐢖𐢍𐢀 𐢃𐢛 𐢈𐢁𐢑𐢔 𐢑𐢕𐢘𐢝𐢆 𐢈𐢍𐢑𐢅𐢆 𐢈𐢁𐢊𐢛𐢆 𐢁𐢝𐢅𐢚 𐢗𐢅 𐢗𐢑𐢒 𐢈𐢁𐢍𐢞𐢌 𐢚𐢃𐢛𐢀 𐢅𐢕𐢆 𐢊𐢛𐢒 𐢏𐢊𐢑𐢍𐢚𐢞 𐢊𐢛𐢓𐢀 𐢅𐢌 𐢓𐢊𐢛𐢒 𐢑𐢅𐢈𐢝𐢛𐢀 𐢃𐢕𐢃𐢋𐢈 𐢈𐢝𐢑𐢓𐢈\n𐢅𐢕𐢆 𐢚𐢂𐢛𐢀 𐢅𐢍 𐢗𐢃𐢅 𐢏𐢇𐢑𐢔 𐢁𐢖𐢍𐢀 𐢃𐢛 𐢈𐢁𐢑𐢔 𐢑𐢕𐢘𐢝𐢆 𐢈𐢍𐢑𐢅𐢆 𐢈𐢁𐢊𐢛𐢆 𐢁𐢝𐢅𐢚 𐢗𐢅 𐢗𐢑𐢒 𐢈𐢁𐢍𐢞𐢌 𐢚𐢃𐢛𐢀 𐢅𐢕𐢆 𐢊𐢛𐢒 𐢏𐢊𐢑𐢍𐢚𐢞 𐢊𐢛𐢓𐢀 𐢅𐢌 𐢓𐢊𐢛𐢒 𐢑𐢅𐢈𐢝𐢛𐢀 𐢃𐢕𐢃𐢋𐢈 𐢈𐢝𐢑𐢓𐢈"
  specimen_16: "𐢅𐢕𐢆 𐢚𐢂𐢛𐢀 𐢅𐢍 𐢗𐢃𐢅 𐢏𐢇𐢑𐢔 𐢁𐢖𐢍𐢀 𐢃𐢛 𐢈𐢁𐢑𐢔 𐢑𐢕𐢘𐢝𐢆 𐢈𐢍𐢑𐢅𐢆 𐢈𐢁𐢊𐢛𐢆 𐢁𐢝𐢅𐢚 𐢗𐢅 𐢗𐢑𐢒 𐢈𐢁𐢍𐢞𐢌 𐢚𐢃𐢛𐢀 𐢅𐢕𐢆 𐢊𐢛𐢒 𐢏𐢊𐢑𐢍𐢚𐢞 𐢊𐢛𐢓𐢀 𐢅𐢌 𐢓𐢊𐢛𐢒 𐢑𐢅𐢈𐢝𐢛𐢀 𐢃𐢕𐢃𐢋𐢈 𐢈𐢝𐢑𐢓𐢈\n𐢅𐢕𐢆 𐢚𐢂𐢛𐢀 𐢅𐢍 𐢗𐢃𐢅 𐢏𐢇𐢑𐢔 𐢁𐢖𐢍𐢀 𐢃𐢛 𐢈𐢁𐢑𐢔 𐢑𐢕𐢘𐢝𐢆 𐢈𐢍𐢑𐢅𐢆 𐢈𐢁𐢊𐢛𐢆 𐢁𐢝𐢅𐢚 𐢗𐢅 𐢗𐢑𐢒 𐢈𐢁𐢍𐢞𐢌 𐢚𐢃𐢛𐢀 𐢅𐢕𐢆 𐢊𐢛𐢒 𐢏𐢊𐢑𐢍𐢚𐢞 𐢊𐢛𐢓𐢀 𐢅𐢌 𐢓𐢊𐢛𐢒 𐢑𐢅𐢈𐢝𐢛𐢀 𐢃𐢕𐢃𐢋𐢈 𐢈𐢝𐢑𐢓𐢈\n𐢅𐢕𐢆 𐢚𐢂𐢛𐢀 𐢅𐢍 𐢗𐢃𐢅 𐢏𐢇𐢑𐢔 𐢁𐢖𐢍𐢀 𐢃𐢛 𐢈𐢁𐢑𐢔 𐢑𐢕𐢘𐢝𐢆 𐢈𐢍𐢑𐢅𐢆 𐢈𐢁𐢊𐢛𐢆 𐢁𐢝𐢅𐢚 𐢗𐢅 𐢗𐢑𐢒 𐢈𐢁𐢍𐢞𐢌 𐢚𐢃𐢛𐢀 𐢅𐢕𐢆 𐢊𐢛𐢒 𐢏𐢊𐢑𐢍𐢚𐢞 𐢊𐢛𐢓𐢀 𐢅𐢌 𐢓𐢊𐢛𐢒 𐢑𐢅𐢈𐢝𐢛𐢀 𐢃𐢕𐢃𐢋𐢈 𐢈𐢝𐢑𐢓𐢈\n𐢅𐢕𐢆 𐢚𐢂𐢛𐢀 𐢅𐢍 𐢗𐢃𐢅 𐢏𐢇𐢑𐢔 𐢁𐢖𐢍𐢀 𐢃𐢛 𐢈𐢁𐢑𐢔 𐢑𐢕𐢘𐢝𐢆 𐢈𐢍𐢑𐢅𐢆 𐢈𐢁𐢊𐢛𐢆 𐢁𐢝𐢅𐢚 𐢗𐢅 𐢗𐢑𐢒 𐢈𐢁𐢍𐢞𐢌 𐢚𐢃𐢛𐢀 𐢅𐢕𐢆 𐢊𐢛𐢒 𐢏𐢊𐢑𐢍𐢚𐢞 𐢊𐢛𐢓𐢀 𐢅𐢌 𐢓𐢊𐢛𐢒 𐢑𐢅𐢈𐢝𐢛𐢀 𐢃𐢕𐢃𐢋𐢈 𐢈𐢝𐢑𐢓𐢈\n𐢅𐢕𐢆 𐢚𐢂𐢛𐢀 𐢅𐢍 𐢗𐢃𐢅 𐢏𐢇𐢑𐢔 𐢁𐢖𐢍𐢀 𐢃𐢛 𐢈𐢁𐢑𐢔 𐢑𐢕𐢘𐢝𐢆 𐢈𐢍𐢑𐢅𐢆 𐢈𐢁𐢊𐢛𐢆 𐢁𐢝𐢅𐢚 𐢗𐢅 𐢗𐢑𐢒 𐢈𐢁𐢍𐢞𐢌 𐢚𐢃𐢛𐢀 𐢅𐢕𐢆 𐢊𐢛𐢒 𐢏𐢊𐢑𐢍𐢚𐢞 𐢊𐢛𐢓𐢀 𐢅𐢌 𐢓𐢊𐢛𐢒 𐢑𐢅𐢈𐢝𐢛𐢀 𐢃𐢕𐢃𐢋𐢈 𐢈𐢝𐢑𐢓𐢈"
}
historical: true
