id: "arc_Palm"
language: "arc"
script: "Palm"
name: "Aramaic, Palmyrene"
population: 0
sample_text {
  masthead_full: "𐡲𐡫𐡬𐡩"
  masthead_partial: "𐡥𐡯"
  styles: "𐡲𐡫𐡬 𐡩𐡥𐡫𐡩𐡯 𐡠𐡥𐡴𐡫𐡩𐡯 𐡦𐡡𐡣𐡫𐡠 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡮𐡵𐡥𐡬"
  tester: "𐡲𐡫𐡬 𐡩𐡥𐡫𐡩𐡯 𐡠𐡥𐡴𐡫𐡩𐡯 𐡦𐡡𐡣𐡫𐡠 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡮𐡵𐡥𐡬 𐡣𐡩 𐡤𐡥𐡠 𐡠𐡯𐡨𐡴𐡨𐡢 𐡫𐡳𐡫𐡮𐡩𐡠"
  poster_sm: "𐡲𐡫𐡬 𐡩𐡥𐡫𐡩𐡯 𐡠𐡥𐡴𐡫𐡩𐡯"
  poster_md: "𐡲𐡫𐡬 𐡩𐡥𐡫𐡩𐡯"
  poster_lg: "𐡲𐡫𐡬"
  specimen_48: "𐡲𐡫𐡬 𐡩𐡥𐡫𐡩𐡯 𐡠𐡥𐡴𐡫𐡩𐡯 𐡦𐡡𐡣𐡫𐡠 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡮𐡵𐡥𐡬 𐡣𐡩 𐡤𐡥𐡠"
  specimen_36: "𐡲𐡫𐡬 𐡩𐡥𐡫𐡩𐡯 𐡠𐡥𐡴𐡫𐡩𐡯 𐡦𐡡𐡣𐡫𐡠 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡮𐡵𐡥𐡬 𐡣𐡩 𐡤𐡥𐡠 𐡠𐡯𐡨𐡴𐡨𐡢 𐡫𐡳𐡫𐡮𐡩𐡠 𐡡𐡬𐡩𐡶𐡥𐡩𐡶𐡠 𐡣𐡩 𐡠𐡫𐡤𐡠 𐡠𐡫𐡪𐡯𐡮𐡣𐡴𐡥𐡯 𐡳𐡯𐡴 𐡥𐡵𐡬𐡵 𐡩𐡣𐡪 𐡤𐡥𐡠 𐡶𐡮𐡭 𐡳𐡴𐡯𐡱𐡩𐡮𐡥𐡯 𐡤𐡩𐡢𐡬𐡥𐡮𐡠 𐡥𐡪𐡣𐡩 𐡠𐡶𐡩 𐡫𐡪𐡠 𐡩𐡶 𐡫𐡢𐡩𐡮𐡩𐡠 𐡦𐡡𐡥𐡭 𐡯𐡢𐡩𐡠𐡭 𐡥𐡤𐡥𐡠 𐡴𐡡 𐡵𐡥𐡳 𐡣𐡩 𐡠𐡳𐡩𐡬 𐡫𐡤 𐡡𐡥𐡫𐡠 𐡥𐡣𐡬𐡥𐡯 𐡫𐡩𐡳𐡴𐡤 𐡵𐡮𐡶 𐡽𐡾𐡿𐡿𐡾𐡼𐡷"
  specimen_32: "𐡲𐡫𐡬 𐡩𐡥𐡫𐡩𐡯 𐡠𐡥𐡴𐡫𐡩𐡯 𐡦𐡡𐡣𐡫𐡠 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡮𐡵𐡥𐡬 𐡣𐡩 𐡤𐡥𐡠 𐡠𐡯𐡨𐡴𐡨𐡢 𐡫𐡳𐡫𐡮𐡩𐡠 𐡡𐡬𐡩𐡶𐡥𐡩𐡶𐡠 𐡣𐡩 𐡠𐡫𐡤𐡠 𐡠𐡫𐡪𐡯𐡮𐡣𐡴𐡥𐡯 𐡳𐡯𐡴 𐡥𐡵𐡬𐡵 𐡩𐡣𐡪 𐡤𐡥𐡠 𐡶𐡮𐡭 𐡳𐡴𐡯𐡱𐡩𐡮𐡥𐡯 𐡤𐡩𐡢𐡬𐡥𐡮𐡠 𐡥𐡪𐡣𐡩 𐡠𐡶𐡩 𐡫𐡪𐡠 𐡩𐡶 𐡫𐡢𐡩𐡮𐡩𐡠 𐡦𐡡𐡥𐡭 𐡯𐡢𐡩𐡠𐡭 𐡥𐡤𐡥𐡠 𐡴𐡡 𐡵𐡥𐡳 𐡣𐡩 𐡠𐡳𐡩𐡬 𐡫𐡤 𐡡𐡥𐡫𐡠 𐡥𐡣𐡬𐡥𐡯 𐡫𐡩𐡳𐡴𐡤 𐡵𐡮𐡶 𐡽𐡾𐡿𐡿𐡾𐡼𐡷"
  specimen_21: "𐡲𐡫𐡬 𐡩𐡥𐡫𐡩𐡯 𐡠𐡥𐡴𐡫𐡩𐡯 𐡦𐡡𐡣𐡫𐡠 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡮𐡵𐡥𐡬 𐡣𐡩 𐡤𐡥𐡠 𐡠𐡯𐡨𐡴𐡨𐡢 𐡫𐡳𐡫𐡮𐡩𐡠 𐡡𐡬𐡩𐡶𐡥𐡩𐡶𐡠 𐡣𐡩 𐡠𐡫𐡤𐡠 𐡠𐡫𐡪𐡯𐡮𐡣𐡴𐡥𐡯 𐡳𐡯𐡴 𐡥𐡵𐡬𐡵 𐡩𐡣𐡪 𐡤𐡥𐡠 𐡶𐡮𐡭 𐡳𐡴𐡯𐡱𐡩𐡮𐡥𐡯 𐡤𐡩𐡢𐡬𐡥𐡮𐡠 𐡥𐡪𐡣𐡩 𐡠𐡶𐡩 𐡫𐡪𐡠 𐡩𐡶 𐡫𐡢𐡩𐡮𐡩𐡠 𐡦𐡡𐡥𐡭 𐡯𐡢𐡩𐡠𐡭 𐡥𐡤𐡥𐡠 𐡴𐡡 𐡵𐡥𐡳 𐡣𐡩 𐡠𐡳𐡩𐡬 𐡫𐡤 𐡡𐡥𐡫𐡠 𐡥𐡣𐡬𐡥𐡯 𐡫𐡩𐡳𐡴𐡤 𐡵𐡮𐡶 𐡽𐡾𐡿𐡿𐡾𐡼𐡷\n𐡲𐡫𐡬 𐡩𐡥𐡫𐡩𐡯 𐡠𐡥𐡴𐡫𐡩𐡯 𐡦𐡡𐡣𐡫𐡠 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡮𐡵𐡥𐡬 𐡣𐡩 𐡤𐡥𐡠 𐡠𐡯𐡨𐡴𐡨𐡢 𐡫𐡳𐡫𐡮𐡩𐡠 𐡡𐡬𐡩𐡶𐡥𐡩𐡶𐡠 𐡣𐡩 𐡠𐡫𐡤𐡠 𐡠𐡫𐡪𐡯𐡮𐡣𐡴𐡥𐡯 𐡳𐡯𐡴 𐡥𐡵𐡬𐡵 𐡩𐡣𐡪 𐡤𐡥𐡠 𐡶𐡮𐡭 𐡳𐡴𐡯𐡱𐡩𐡮𐡥𐡯 𐡤𐡩𐡢𐡬𐡥𐡮𐡠 𐡥𐡪𐡣𐡩 𐡠𐡶𐡩 𐡫𐡪𐡠 𐡩𐡶 𐡫𐡢𐡩𐡮𐡩𐡠 𐡦𐡡𐡥𐡭 𐡯𐡢𐡩𐡠𐡭 𐡥𐡤𐡥𐡠 𐡴𐡡 𐡵𐡥𐡳 𐡣𐡩 𐡠𐡳𐡩𐡬 𐡫𐡤 𐡡𐡥𐡫𐡠 𐡥𐡣𐡬𐡥𐡯 𐡫𐡩𐡳𐡴𐡤 𐡵𐡮𐡶 𐡽𐡾𐡿𐡿𐡾𐡼𐡷"
  specimen_16: "𐡲𐡫𐡬 𐡩𐡥𐡫𐡩𐡯 𐡠𐡥𐡴𐡫𐡩𐡯 𐡦𐡡𐡣𐡫𐡠 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡮𐡵𐡥𐡬 𐡣𐡩 𐡤𐡥𐡠 𐡠𐡯𐡨𐡴𐡨𐡢 𐡫𐡳𐡫𐡮𐡩𐡠 𐡡𐡬𐡩𐡶𐡥𐡩𐡶𐡠 𐡣𐡩 𐡠𐡫𐡤𐡠 𐡠𐡫𐡪𐡯𐡮𐡣𐡴𐡥𐡯 𐡳𐡯𐡴 𐡥𐡵𐡬𐡵 𐡩𐡣𐡪 𐡤𐡥𐡠 𐡶𐡮𐡭 𐡳𐡴𐡯𐡱𐡩𐡮𐡥𐡯 𐡤𐡩𐡢𐡬𐡥𐡮𐡠 𐡥𐡪𐡣𐡩 𐡠𐡶𐡩 𐡫𐡪𐡠 𐡩𐡶 𐡫𐡢𐡩𐡮𐡩𐡠 𐡦𐡡𐡥𐡭 𐡯𐡢𐡩𐡠𐡭 𐡥𐡤𐡥𐡠 𐡴𐡡 𐡵𐡥𐡳 𐡣𐡩 𐡠𐡳𐡩𐡬 𐡫𐡤 𐡡𐡥𐡫𐡠 𐡥𐡣𐡬𐡥𐡯 𐡫𐡩𐡳𐡴𐡤 𐡵𐡮𐡶 𐡽𐡾𐡿𐡿𐡾𐡼𐡷\n𐡲𐡫𐡬 𐡩𐡥𐡫𐡩𐡯 𐡠𐡥𐡴𐡫𐡩𐡯 𐡦𐡡𐡣𐡫𐡠 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡮𐡵𐡥𐡬 𐡣𐡩 𐡤𐡥𐡠 𐡠𐡯𐡨𐡴𐡨𐡢 𐡫𐡳𐡫𐡮𐡩𐡠 𐡡𐡬𐡩𐡶𐡥𐡩𐡶𐡠 𐡣𐡩 𐡠𐡫𐡤𐡠 𐡠𐡫𐡪𐡯𐡮𐡣𐡴𐡥𐡯 𐡳𐡯𐡴 𐡥𐡵𐡬𐡵 𐡩𐡣𐡪 𐡤𐡥𐡠 𐡶𐡮𐡭 𐡳𐡴𐡯𐡱𐡩𐡮𐡥𐡯 𐡤𐡩𐡢𐡬𐡥𐡮𐡠 𐡥𐡪𐡣𐡩 𐡠𐡶𐡩 𐡫𐡪𐡠 𐡩𐡶 𐡫𐡢𐡩𐡮𐡩𐡠 𐡦𐡡𐡥𐡭 𐡯𐡢𐡩𐡠𐡭 𐡥𐡤𐡥𐡠 𐡴𐡡 𐡵𐡥𐡳 𐡣𐡩 𐡠𐡳𐡩𐡬 𐡫𐡤 𐡡𐡥𐡫𐡠 𐡥𐡣𐡬𐡥𐡯 𐡫𐡩𐡳𐡴𐡤 𐡵𐡮𐡶 𐡽𐡾𐡿𐡿𐡾𐡼𐡷\n𐡲𐡫𐡬 𐡩𐡥𐡫𐡩𐡯 𐡠𐡥𐡴𐡫𐡩𐡯 𐡦𐡡𐡣𐡫𐡠 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡡𐡴 𐡬𐡫𐡪𐡥 𐡮𐡵𐡥𐡬 𐡣𐡩 𐡤𐡥𐡠 𐡠𐡯𐡨𐡴𐡨𐡢 𐡫𐡳𐡫𐡮𐡩𐡠 𐡡𐡬𐡩𐡶𐡥𐡩𐡶𐡠 𐡣𐡩 𐡠𐡫𐡤𐡠 𐡠𐡫𐡪𐡯𐡮𐡣𐡴𐡥𐡯 𐡳𐡯𐡴 𐡥𐡵𐡬𐡵 𐡩𐡣𐡪 𐡤𐡥𐡠 𐡶𐡮𐡭 𐡳𐡴𐡯𐡱𐡩𐡮𐡥𐡯 𐡤𐡩𐡢𐡬𐡥𐡮𐡠 𐡥𐡪𐡣𐡩 𐡠𐡶𐡩 𐡫𐡪𐡠 𐡩𐡶 𐡫𐡢𐡩𐡮𐡩𐡠 𐡦𐡡𐡥𐡭 𐡯𐡢𐡩𐡠𐡭 𐡥𐡤𐡥𐡠 𐡴𐡡 𐡵𐡥𐡳 𐡣𐡩 𐡠𐡳𐡩𐡬 𐡫𐡤 𐡡𐡥𐡫𐡠 𐡥𐡣𐡬𐡥𐡯 𐡫𐡩𐡳𐡴𐡤 𐡵𐡮𐡶 𐡽𐡾𐡿𐡿𐡾𐡼𐡷"
}
historical: true
