id: "arl_Latn"
language: "arl"
script: "Latn"
name: "Arabela"
sample_text {
  masthead_full: "PpUu"
  masthead_partial: "Ee"
  styles: "P\nu\ne\ny\na\nn\no\n \np\na\n \nq\nu\ni\ns\nh\na\nc\na\nr\ni"
  tester: "P\nu\ne\ny\na\nn\no\n \np\na\n \nq\nu\ni\ns\nh\na\nc\na\nr\ni\n,\n \np\nu\ne\nt\nu\nn\nu\n "
  poster_sm: "P\nu\ne\ny\na\nn"
  poster_md: "P\nu\ne\ny\na"
  poster_lg: "P\nu"
  specimen_48: "P\nu\ne\ny\na\nn\no\n \np\na\n \nq\nu\ni\ns\nh\na\nc\na\nr\ni\n,\n \np\nu\ne\nt\nu\nn\nu\n "
  specimen_36: "P\nu\ne\ny\na\nn\no\n \np\na\n \nq\nu\ni\ns\nh\na\nc\na\nr\ni\n,\n \np\nu\ne\nt\nu\nn\nu\n \np\na\nj\na\nn\ni\ny\na\nj\na\nn\na\na\n \nm\na\nr\ni\ny\na"
  specimen_32: "P\nu\ne\ny\na\nn\no\n \np\na\n \nq\nu\ni\ns\nh\na\nc\na\nr\ni\n,\n \np\nu\ne\nt\nu\nn\nu\n \np\na\nj\na\nn\ni\ny\na\nj\na\nn\na\na\n \nm\na\nr\ni\ny\na\nt\na\n \nm\ni\ni\ns\nh\ni\ny\na\n \nm\na\nn\ni\nn\ni\na\n,\n "
  specimen_21: "P\nu\ne\ny\na\nn\no\n \np\na\n \nq\nu\ni\ns\nh\na\nc\na\nr\ni\n,\n \np\nu\ne\nt\nu\nn\nu\n \np\na\nj\na\nn\ni\ny\na\nj\na\nn\na\na\n \nm\na\nr\ni\ny\na\nt\na\n \nm\ni\ni\ns\nh\ni\ny\na\n \nm\na\nn\ni\nn\ni\na\n,\n \nm\na\nj\na\n \ns\no\no\ns\nh\ni\ny\na\n \nt\na\nm\no\nn\nu\n.\n \nP\nu\ne\nt\nu\nn\nu\n \np\nu\ne\ny\na\nj\na\nn\na\na\nr\ni\n \nn\ni\ni\ns\nh\ni\nt\ni\na\nj\na\nr\na\nc\na\n,\n \nj\ni\nu\nu\nj\ni\na\na\nr\na\nc\na\nn\ni\no\n \np\nu\ne\ny\na"
  specimen_16: "P\nu\ne\ny\na\nn\no\n \np\na\n \nq\nu\ni\ns\nh\na\nc\na\nr\ni\n,\n \np\nu\ne\nt\nu\nn\nu\n \np\na\nj\na\nn\ni\ny\na\nj\na\nn\na\na\n \nm\na\nr\ni\ny\na\nt\na\n \nm\ni\ni\ns\nh\ni\ny\na\n \nm\na\nn\ni\nn\ni\na\n,\n \nm\na\nj\na\n \ns\no\no\ns\nh\ni\ny\na\n \nt\na\nm\no\nn\nu\n.\n \nP\nu\ne\nt\nu\nn\nu\n \np\nu\ne\ny\na\nj\na\nn\na\na\nr\ni\n \nn\ni\ni\ns\nh\ni\nt\ni\na\nj\na\nr\na\nc\na\n,\n \nj\ni\nu\nu\nj\ni\na\na\nr\na\nc\na\nn\ni\no\n \np\nu\ne\ny\na\nc\nu\na\n \np\na\n \nt\na\nr\na\na\nj\ne\nn\nu\nr\na\n.\n \nN\na\na\nr\na\nt\ne\n \nm\na\nn\ni\nn\ni\na\n \np\na\n \nj\ni\ny\na\nn\no\no\nt\ni\no\no\nr\ne\n \nj\nu\nh\nu\na\n \np\na\n \nt\na\np\nu\ne\ny\no\nc\nu\na\nc\na\n.\nP\nu\ne\ny\na\nn\no\n \np\na\n \nq\nu\ni\ns\nh\na\nc\na\nr\ni\n,\n \np\nu\ne\nt\nu\nn\nu\n \np\na\nj\na\nn\ni\ny\na\nj\na\nn\na\na\n \nm\na\nr\ni\ny\na"
}
