id: "arp_Latn"
language: "arp"
script: "Latn"
name: "Arapaho"
population: 0
region: "US"
sample_text {
  masthead_full: "BbEe"
  masthead_partial: "Ii"
  styles: "Beisiihi\' hineeniteeno\' tohcebii\'oo3i\' beehni\'iine\'etii3i\',"
  tester: "Beisiihi\' hineeniteeno\' tohcebii\'oo3i\' beehni\'iine\'etii3i\', beehnii3inou\'u"
  poster_sm: "Beisiihi\' hineeniteeno\' tohcebii\'oo3i\' beehni\'iine\'etii3i\', beehnii3inou\'u nuhu\' neneehiisou\'u niihenehiitoono noh bobooteenetiit. Heetnookohuusniini\'iheti3i\' wootii hiniito\'eino hookoh niini\'kokoh\'u3ecoo3i\' noh hee\'eihi3i\'"
  poster_md: "Beisiihi\'"
  poster_lg: "Beisiihi\'"
  specimen_48: "Beisiihi\' hineeniteeno\' tohcebii\'oo3i\' beehni\'iine\'etii3i\',"
  specimen_36: "Beisiihi\' hineeniteeno\' tohcebii\'oo3i\' beehni\'iine\'etii3i\', beehnii3inou\'u nuhu\' neneehiisou\'u niihenehiitoono noh bobooteenetiit. Heetnookohuusniini\'iheti3i\' wootii hiniito\'eino hookoh niini\'kokoh\'u3ecoo3i\' noh hee\'eihi3i\'."
  specimen_32: "Beisiihi\' hineeniteeno\' tohcebii\'oo3i\' beehni\'iine\'etii3i\', beehnii3inou\'u nuhu\' neneehiisou\'u niihenehiitoono noh bobooteenetiit. Heetnookohuusniini\'iheti3i\' wootii hiniito\'eino hookoh niini\'kokoh\'u3ecoo3i\' noh hee\'eihi3i\'."
  specimen_21: "Beisiihi\' hineeniteeno\' tohcebii\'oo3i\' beehni\'iine\'etii3i\', beehnii3inou\'u nuhu\' neneehiisou\'u niihenehiitoono noh bobooteenetiit. Heetnookohuusniini\'iheti3i\' wootii hiniito\'eino hookoh niini\'kokoh\'u3ecoo3i\' noh hee\'eihi3i\'.\nBeisiihi\' hineeniteeno\' tohcebii\'oo3i\' beehni\'iine\'etii3i\', beehnii3inou\'u nuhu\' neneehiisou\'u niihenehiitoono noh bobooteenetiit. Heetnookohuusniini\'iheti3i\' wootii hiniito\'eino hookoh niini\'kokoh\'u3ecoo3i\' noh hee\'eihi3i\'."
  specimen_16: "Beisiihi\' hineeniteeno\' tohcebii\'oo3i\' beehni\'iine\'etii3i\', beehnii3inou\'u nuhu\' neneehiisou\'u niihenehiitoono noh bobooteenetiit. Heetnookohuusniini\'iheti3i\' wootii hiniito\'eino hookoh niini\'kokoh\'u3ecoo3i\' noh hee\'eihi3i\'.\nBeisiihi\' hineeniteeno\' tohcebii\'oo3i\' beehni\'iine\'etii3i\', beehnii3inou\'u nuhu\' neneehiisou\'u niihenehiitoono noh bobooteenetiit. Heetnookohuusniini\'iheti3i\' wootii hiniito\'eino hookoh niini\'kokoh\'u3ecoo3i\' noh hee\'eihi3i\'.\nBeisiihi\' hineeniteeno\' tohcebii\'oo3i\' beehni\'iine\'etii3i\', beehnii3inou\'u nuhu\' neneehiisou\'u niihenehiitoono noh bobooteenetiit. Heetnookohuusniini\'iheti3i\' wootii hiniito\'eino hookoh niini\'kokoh\'u3ecoo3i\' noh hee\'eihi3i\'."
}
