id: "art_Latn"
language: "art"
script: "Latn"
name: "Artificial languages, Latin, World"
sample_text {
  masthead_full: "JjAa"
  masthead_partial: "Nn"
  styles: "j\na\nn\n \na\nl\ne\n/\na\nl\ni\n \nl\ni\n \nk\na\nm\na\n \nl"
  tester: "j\na\nn\n \na\nl\ne\n/\na\nl\ni\n \nl\ni\n \nk\na\nm\na\n \nl\no\nn\n \nn\na\ns\ni\nn\n \nn"
  poster_sm: "j\na\nn\n \na\nl"
  poster_md: "j\na\nn\n \na"
  poster_lg: "j\na"
  specimen_48: "j\na\nn\n \na\nl\ne\n/\na\nl\ni\n \nl\ni\n \nk\na\nm\na\n \nl\no\nn\n \nn\na\ns\ni\nn\n \nn"
  specimen_36: "j\na\nn\n \na\nl\ne\n/\na\nl\ni\n \nl\ni\n \nk\na\nm\na\n \nl\no\nn\n \nn\na\ns\ni\nn\n \nn\ni\n:\n \no\nn\na\n \nl\ni\n \nk\ne\nn\n \np\na\nl\ni\n \ne\n "
  specimen_32: "j\na\nn\n \na\nl\ne\n/\na\nl\ni\n \nl\ni\n \nk\na\nm\na\n \nl\no\nn\n \nn\na\ns\ni\nn\n \nn\ni\n:\n \no\nn\na\n \nl\ni\n \nk\ne\nn\n \np\na\nl\ni\n \ne\n \nw\ni\nl\ne\n \no\nn\na\n.\n \no\nn\na\n \nl\ni\n \nj\no\n "
  specimen_21: "j\na\nn\n \na\nl\ne\n/\na\nl\ni\n \nl\ni\n \nk\na\nm\na\n \nl\no\nn\n \nn\na\ns\ni\nn\n \nn\ni\n:\n \no\nn\na\n \nl\ni\n \nk\ne\nn\n \np\na\nl\ni\n \ne\n \nw\ni\nl\ne\n \no\nn\na\n.\n \no\nn\na\n \nl\ni\n \nj\no\n \ne\n \ns\nu\nl\ni\n \nj\na\nn\n \ns\na\nm\na\n \ne\n \nk\ne\nn\n \ns\na\nm\na\n.\n \no\nn\na\n \nl\ni\n \nj\no\n \ne\n \ns\no\nn\na\n \np\no\nn\na\n \ne\n \nl\na\nw\na\n \ni\nn\ns\na\n \np\ni\n \np\na\nl\ni\n \np\no\nn\na\n.\n \nn\ni\n \nl\na"
  specimen_16: "j\na\nn\n \na\nl\ne\n/\na\nl\ni\n \nl\ni\n \nk\na\nm\na\n \nl\no\nn\n \nn\na\ns\ni\nn\n \nn\ni\n:\n \no\nn\na\n \nl\ni\n \nk\ne\nn\n \np\na\nl\ni\n \ne\n \nw\ni\nl\ne\n \no\nn\na\n.\n \no\nn\na\n \nl\ni\n \nj\no\n \ne\n \ns\nu\nl\ni\n \nj\na\nn\n \ns\na\nm\na\n \ne\n \nk\ne\nn\n \ns\na\nm\na\n.\n \no\nn\na\n \nl\ni\n \nj\no\n \ne\n \ns\no\nn\na\n \np\no\nn\na\n \ne\n \nl\na\nw\na\n \ni\nn\ns\na\n \np\ni\n \np\na\nl\ni\n \np\no\nn\na\n.\n \nn\ni\n \nl\na\n,\n \no\nn\na\n \nl\ni\n \nw\ni\nl\ne\n \np\na\nl\ni\n \nt\na\nw\na\n \nj\na\nn\n \na\nn\nt\ne\n \na\nl\ne\n/\na\nl\ni\n \nk\ne\np\ne\nk\ne\nn\n \nn\na\ns\ni\nn\n \no\nl\ni\nn\n.\nj\na\nn\n \na\nl\ne\n/\na\nl\ni\n \nl\ni\n \nk\na\nm\na\n \nl\no\nn\n \nn\na\ns\ni\nn\n \nn\ni\n:\n \no\nn\na\n \nl\ni\n \nk\ne\nn\n \np\na\nl\ni\n \ne\n \nw\ni\nl\ne\n \no\nn\na\n.\n \no\nn\na\n \nl\ni"
}
