id: "as"
language: "as"
script: "Beng"
name: "Assamese"
autonym: "অসমীয়া"
population: 17239170
region: "IN"
exemplar_chars {
  base: "\\u09BC অ আ ই ঈ উ ঊ ঋ এ ঐ ও ঔ ং \\u0981 ঃ ক খ গ ঘ ঙ চ ছ জ ঝ ঞ ট ঠ ড {ড\\u09BC} ঢ {ঢ\\u09BC} ণ ত থ দ ধ ন প ফ ব ভ ম য {য\\u09BC} ৰ ল ৱ শ ষ স হ {ক\\u09CDষ} া ি ী \\u09C1 \\u09C2 \\u09C3 ে ৈ ো ৌ \\u09CD"
  auxiliary: "\\u200C\\u200D ৲ ৎ র"
  marks: "◌ঁ ◌ং ◌ঃ ◌় ◌া ◌ি ◌ী ◌ু ◌ূ ◌ৃ ◌ৄ ◌ে ◌ৈ ◌্ ◌ৗ ◌ৢ ◌ৣ"
  numerals: "\\- ‑ , . % ‰ + 0০ 1১ 2২ 3৩ 4৪ 5৫ 6৬ 7৭ 8৮ 9৯"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … । \' ‘ ’ \" “ ” ( ) \\[ \\] § @ * / \\& # † ‡ ′ ″"
  index: "\\u09BC অ আ ই ঈ উ ঊ ঋ এ ঐ ও ঔ ং ঃ ক খ গ ঘ ঙ চ ছ জ ঝ ঞ ট ঠ ড ঢ ণ ৎ ত থ দ ধ ন প ফ ব ভ ম য ৰ ল ৱ শ ষ স হ \\u09CD"
}
sample_text {
  fallback_language: "bn"
}
