id: "as"
language: "as"
script: "Beng"
name: "Assamese"
autonym: "অসমীয়া"
population: 17239170
region: "IN"
exemplar_chars {
  base: "় অ আ ই ঈ উ ঊ ঋ এ ঐ ও ঔ ং ঁ ঃ ক খ গ ঘ ঙ চ ছ জ ঝ ঞ ট ঠ ড {ড়} ঢ {ঢ়} ণ ত থ দ ধ ন প ফ ব ভ ম য {য়} ৰ ল ৱ শ ষ স হ {ক্ষ} া ি ী ু ূ ৃ ে ৈ ো ৌ ্ {ড়} {ঢ়} {য়} {ক্ষ} {ড়} {ঢ়} {য়} {ক্ষ} {ড়} {ঢ়} {য়} {ক্ষ} {ড়} {ঢ়} {য়} {ক্ষ} {ড়} {ঢ়} {য়} {ক্ষ} {ড়} {ঢ়} {য়} {ক্ষ} {ড়} {ঢ়} {য়} {ক্ষ} {ড়} {ঢ়} {য়} {ক্ষ} {ড়} {ঢ়} {য়} {ক্ষ} {ড়} {ঢ়} {য়} {ক্ষ} {ড়} {ঢ়} {য়} {ক্ষ} {ড়} {ঢ়} {য়} {ক্ষ} {ড়} {ঢ়} {য়} {ক্ষ} {ড়} {ঢ়} {য়} {ক্ষ} {ড়} {ঢ়} {য়} {ক্ষ}"
  auxiliary: "‌‍ ৲ ৎ র"
  marks: "◌ঁ ◌ং ◌ঃ ◌় ◌া ◌ি ◌ী ◌ু ◌ূ ◌ৃ ◌ৄ ◌ে ◌ৈ ◌্ ◌ৗ ◌ৢ ◌ৣ"
  numerals: "- ‑ , . % ‰ + 0০ 1১ 2২ 3৩ 4৪ 5৫ 6৬ 7৭ 8৮ 9৯"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … । \' ‘ ’ \" “ ” ( ) [ ] § @ * / & # † ‡ ′ ″"
  index: "় অ আ ই ঈ উ ঊ ঋ এ ঐ ও ঔ ং ঃ ক খ গ ঘ ঙ চ ছ জ ঝ ঞ ট ঠ ড ঢ ণ ৎ ত থ দ ধ ন প ফ ব ভ ম য ৰ ল ৱ শ ষ স হ ্"
}
sample_text {
  fallback_language: "bn"
}
