id: "ast"
language: "ast"
script: "Latn"
name: "Asturian"
autonym: "Asturianu"
population: 650205
region: "ES"
exemplar_chars {
  base: "a á b c d e é f g h ḥ i í l ḷ m n ñ o ó p q r s t u ú ü v x y z"
  auxiliary: "ª à ă â å ä ã ā æ ç è ĕ ê ë ē ì ĭ î ï ī j k º ò ŏ ô ö ø ō œ ù ŭ û ū w ÿ"
  marks: "◌́ ◌̃ ◌̈ ◌̣"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ¡ ? ¿ . … \' ‘ ’ \" “ ” « » ( ) [ ] § @ * / \\ & # † ‡ ′ ″"
  index: "A B C D E F G H I L M N Ñ O P Q R S T U V X Y Z"
}
sample_text {
  masthead_full: "TtOo"
  masthead_partial: "Ll"
  styles: "Visto que la llibertá, la xusticia y la paz"
  tester: "Visto que desconocer o facer de menos los drechos humanos foi"
  poster_sm: "Visto que ye"
  poster_md: "Visto que"
  poster_lg: "Tolos"
  specimen_48: "Visto que los pueblos dexaron llantáu na Carta de les Naciones"
  specimen_36: "Naide nun será sometíu a esclavismu nin a servidume; l\'esclavismu y el comerciu d\'esclavos prohíbense en toles sos formes."
  specimen_32: "Toa persona non solo tien drechu al descansu y a la folganza, sinón tamién a una duración razonable del tiempu de trabayu y a vacaciones periódiques pagaes."
  specimen_21: "Toa persona tien drechu a que s\'estableza un orde social y internacional u los drechos y llibertaes proclamaos nesta Declaración aporten a ser efeutivos dafechu.\nNada de la presente Declaración nun podrá interpretase nel sen d\'atribuyi-y al Estáu, a un grupu o a una persona\'l drechu d\'entamar y desendolcar actividaes o realizar aiciones empobinaes a desaniciar cualesquier drechu o llibertá de les que nesta Declaración se proclamen."
  specimen_16: "Visto que la llibertá, la xusticia y la paz en mundu sofítense na reconocencia de la dignidá intrínseca y de los drechos iguales y inayenables de tolos miembros que formen la familia humana;\nVisto que desconocer o facer de menos los drechos humanos foi la causa d\'actos xabaces y dañibles pa la conciencia de la humanidá, y que se proclamó, comu aspiración cimera del home, el llogru d\'un mundu onde los seres humanos, llibres del mieu y de la llaceria, gocen de la llibertá de palabra y de la llibertá de creyencies;\nVisto que ye esencial un réxime de Drechu que protexa los drechos humanos, p\'asina nun se ver emburriáu l\'home al recursu caberu de rebelase escontra de la tiranía y de la opresión;"
}
