id: "auc_Latn"
language: "auc"
script: "Latn"
name: "Waorani, Latin, Ecuador"
sample_text {
  masthead_full: "TtOo"
  masthead_partial: "Mm"
  styles: "T\no\nm\na\nm\no\n \nw\na\no\nm\no\n \ne\nk\na\nm\ne\n \nw\ne"
  tester: "T\no\nm\na\nm\no\n \nw\na\no\nm\no\n \ne\nk\na\nm\ne\n \nw\ne\ne\n \na\nn\na\nm\na\ny\n \ni"
  poster_sm: "T\no\nm\na\nm\no"
  poster_md: "T\no\nm\na\nm"
  poster_lg: "T\no"
  specimen_48: "T\no\nm\na\nm\no\n \nw\na\no\nm\no\n \ne\nk\na\nm\ne\n \nw\ne\ne\n \na\nn\na\nm\na\ny\n \ni"
  specimen_36: "T\no\nm\na\nm\no\n \nw\na\no\nm\no\n \ne\nk\na\nm\ne\n \nw\ne\ne\n \na\nn\na\nm\na\ny\n \ni\nn\na\nn\ni\n \nt\no\nm\ne\nm\no\n \nk\ne\nw\ne\nn\ng\ni\n "
  specimen_32: "T\no\nm\na\nm\no\n \nw\na\no\nm\no\n \ne\nk\na\nm\ne\n \nw\ne\ne\n \na\nn\na\nm\na\ny\n \ni\nn\na\nn\ni\n \nt\no\nm\ne\nm\no\n \nk\ne\nw\ne\nn\ng\ni\n \nb\ne\ny\ne\n \nt\no\nm\na\nm\no\n \nn\ne\ne\nm\no\nm\np\na"
  specimen_21: "T\no\nm\na\nm\no\n \nw\na\no\nm\no\n \ne\nk\na\nm\ne\n \nw\ne\ne\n \na\nn\na\nm\na\ny\n \ni\nn\na\nn\ni\n \nt\no\nm\ne\nm\no\n \nk\ne\nw\ne\nn\ng\ni\n \nb\ne\ny\ne\n \nt\no\nm\na\nm\no\n \nn\ne\ne\nm\no\nm\np\na\n \nn\no\ny\nn\ng\na\n \ni\nm\np\na\n \na\ny\ne\n \na\nn\no\nb\na\ny\n \ni\nm\np\na\n \nw\na\nd\na\nn\ni\n \ni\nn\na\nn\ni\nt\ne\n \nw\na\nk\ne\nk\ni\n \nb\ne\ny\ne\n \na\nn\ng\na\nm\np\na\n.\nT\no\nm\na\nm\no\n \nw\na\no\nm\no\n \ne\nk\na"
  specimen_16: "T\no\nm\na\nm\no\n \nw\na\no\nm\no\n \ne\nk\na\nm\ne\n \nw\ne\ne\n \na\nn\na\nm\na\ny\n \ni\nn\na\nn\ni\n \nt\no\nm\ne\nm\no\n \nk\ne\nw\ne\nn\ng\ni\n \nb\ne\ny\ne\n \nt\no\nm\na\nm\no\n \nn\ne\ne\nm\no\nm\np\na\n \nn\no\ny\nn\ng\na\n \ni\nm\np\na\n \na\ny\ne\n \na\nn\no\nb\na\ny\n \ni\nm\np\na\n \nw\na\nd\na\nn\ni\n \ni\nn\na\nn\ni\nt\ne\n \nw\na\nk\ne\nk\ni\n \nb\ne\ny\ne\n \na\nn\ng\na\nm\np\na\n.\nT\no\nm\na\nm\no\n \nw\na\no\nm\no\n \ne\nk\na\nm\ne\n \nw\ne\ne\n \na\nn\na\nm\na\ny\n \ni\nn\na\nn\ni\n \nt\no\nm\ne\nm\no\n \nk\ne\nw\ne\nn\ng\ni\n \nb\ne\ny\ne\n \nt\no\nm\na\nm\no\n \nn\ne\ne\nm\no\nm\np\na\n \nn\no\ny\nn\ng\na\n \ni\nm\np\na\n \na\ny\ne\n \na\nn\no\nb\na\ny\n \ni\nm\np\na\n \nw\na\nd\na\nn\ni\n \ni\nn\na\nn\ni\nt\ne\n \nw\na\nk\ne\nk\ni\n \nb\ne\ny\ne\n \na\nn\ng\na\nm\np\na\n.\nT\no\nm\na\nm\no\n "
}
