id: "az_Cyrl"
language: "az"
script: "Cyrl"
name: "Azerbaijani (Cyrillic)"
autonym: "Азәрбајҹан"
population: 1142175
region: "AZ"
region: "RU"
exemplar_chars {
  base: "а ә б в г ғ д е ж з и й ј к ҝ л м н о ө п р с т у ү ф х һ ч ҹ ш ы"
  auxiliary: "ц щ ъ ь э ю я"
  marks: "◌̆"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "А Ә Б В Г Ғ Д Е Ж З И Й Ј К Ҝ Л М Н О Ө П Р С Т У Ү Ф Х Һ Ч Ҹ Ш Ы"
}
sample_text {
  masthead_full: "БбҮү"
  masthead_partial: "Тт"
  styles: "Бәшәр аиләсинин бүтүн үзвләринә хас олан"
  tester: "инсан һүгугларына етинасызлыг вә нифрәтин бәшәријјәти дәһшәтә"
  poster_sm: "инсанын сон"
  poster_md: "Бирләшмиш"
  poster_lg: "Бүтүн"
  specimen_48: "үзв дөвләтләрин БМТ илә әмәкдашлыг шәраитиндә инсан һүгугларына"
  specimen_36: "Һеч ким көлә вә ја асылы вәзијјәтдә сахланыла билмәз; гулдарлыг вә гул тиҹарәти бүтүн формаларда гадаған едилир."
  specimen_32: "Һәр бир шәхс Конститусијанын вә ја ганунун она вердији һүгугларын позулмасы заманы сәләаһијјәтли милли мәһкәмәләр тәрәфиндән һүгугларынын бәрпа олунмасы һүгугуна маликдир."
  specimen_21: "Һеч ким өзбашына һәбсә, тутулмаја вә ја сүрҝүнә мәруз гала билмәз.\nҺәр бир шәхс онун һүгуг вә вәзифәләринин тәјини вә она гаршы ирәли сүрүлмүш ҹинајәт иттиһамынын әсаслылығынын мүәјјәнләшдирилмәси үчүн онун ишинин мүстәгил вә битәрәф мәһкәмәдә, там бәрабәрлик әсасында, ашкарлыг вә әдаләтин бүтүн тәләбләринин ҝөзләнилмәси шәраитиндә бахылмасы һүгугуна маликдир."
  specimen_16: "Һеч ким шәхси вә аилә һәјатына мүдахиләјә, евинин тохунулмазлығына, мәктублашмасынын ҝизлилијинә, шәрәф вә нүфузуна өзбашына гәсдә мәруз гала билмәз. Һәр бир шәхсин белә мүдахилә вә гәсдән ганун тәрәфиндән мүдафиә олунмаг һүгугу вар.\nҺәр бир шәхс  дүшүнҹә, виҹдан вә дин азадлығы һүгугуна маликдир; бу һүгуга өз динини вә етигадыны дәјишмәк азадлығы вә өз дининә вә инанҹларына тәһсил, дуа вә дини вә ритуал ајинләр заманы тәкликдә вә ја башгалары илә бирликдә, ашкар вә ја фәрди шәкилдә етигад етмәк азадлығы дахилдир.\nҺәр бир шәхсин истираһәт вә асудә вахт, о ҹүмләдән иш ҝүнүнүн ағлабатан һүдуду вә өдәнилән мүтамади мәзунијјәт һүгугу вар."
}
