id: "azj_Cyrl"
language: "azj"
script: "Cyrl"
name: "Azerbaijani, North, Cyrillic"
sample_text {
  masthead_full: "БбҮү"
  masthead_partial: "Тт"
  styles: "Б\nү\nт\nү\nн\n \nи\nн\nс\nа\nн\nл\nа\nр\n \nл\nә\nј\nа\nг\nә"
  tester: "Б\nү\nт\nү\nн\n \nи\nн\nс\nа\nн\nл\nа\nр\n \nл\nә\nј\nа\nг\nә\nт\n \nв\nә\n \nһ\nү\nг\nу\nг"
  poster_sm: "Б\nү\nт\nү\nн\n "
  poster_md: "Б\nү\nт\nү\nн"
  poster_lg: "Б\nү"
  specimen_48: "Б\nү\nт\nү\nн\n \nи\nн\nс\nа\nн\nл\nа\nр\n \nл\nә\nј\nа\nг\nә\nт\n \nв\nә\n \nһ\nү\nг\nу\nг"
  specimen_36: "Б\nү\nт\nү\nн\n \nи\nн\nс\nа\nн\nл\nа\nр\n \nл\nә\nј\nа\nг\nә\nт\n \nв\nә\n \nһ\nү\nг\nу\nг\nл\nа\nр\nы\nн\nа\n \nҝ\nө\nр\nә\n \nа\nз\nа\nд\n \nв\nә\n "
  specimen_32: "Б\nү\nт\nү\nн\n \nи\nн\nс\nа\nн\nл\nа\nр\n \nл\nә\nј\nа\nг\nә\nт\n \nв\nә\n \nһ\nү\nг\nу\nг\nл\nа\nр\nы\nн\nа\n \nҝ\nө\nр\nә\n \nа\nз\nа\nд\n \nв\nә\n \nб\nә\nр\nа\nб\nә\nр\n \nд\nо\nғ\nу\nл\nу\nр\nл\nа\nр\n.\n "
  specimen_21: "Б\nү\nт\nү\nн\n \nи\nн\nс\nа\nн\nл\nа\nр\n \nл\nә\nј\nа\nг\nә\nт\n \nв\nә\n \nһ\nү\nг\nу\nг\nл\nа\nр\nы\nн\nа\n \nҝ\nө\nр\nә\n \nа\nз\nа\nд\n \nв\nә\n \nб\nә\nр\nа\nб\nә\nр\n \nд\nо\nғ\nу\nл\nу\nр\nл\nа\nр\n.\n \nО\nн\nл\nа\nр\nы\nн\n \nш\nү\nу\nр\nл\nа\nр\nы\n \nв\nә\n \nв\nи\nҹ\nд\nа\nн\nл\nа\nр\nы\n \nв\nа\nр\n \nв\nә\n \nб\nи\nр\n-\nб\nи\nр\nл\nә\nр\nи\nн\nә\n \nм\nү\nн\nа\nс\nи\nб\nә\nт\nд\nә\n \nг\nа\nр\nд\nа\nш\nл\nы\nг\n \nр\nу\nһ\nу\nн\nд\nа"
  specimen_16: "Б\nү\nт\nү\nн\n \nи\nн\nс\nа\nн\nл\nа\nр\n \nл\nә\nј\nа\nг\nә\nт\n \nв\nә\n \nһ\nү\nг\nу\nг\nл\nа\nр\nы\nн\nа\n \nҝ\nө\nр\nә\n \nа\nз\nа\nд\n \nв\nә\n \nб\nә\nр\nа\nб\nә\nр\n \nд\nо\nғ\nу\nл\nу\nр\nл\nа\nр\n.\n \nО\nн\nл\nа\nр\nы\nн\n \nш\nү\nу\nр\nл\nа\nр\nы\n \nв\nә\n \nв\nи\nҹ\nд\nа\nн\nл\nа\nр\nы\n \nв\nа\nр\n \nв\nә\n \nб\nи\nр\n-\nб\nи\nр\nл\nә\nр\nи\nн\nә\n \nм\nү\nн\nа\nс\nи\nб\nә\nт\nд\nә\n \nг\nа\nр\nд\nа\nш\nл\nы\nг\n \nр\nу\nһ\nу\nн\nд\nа\n \nд\nа\nв\nр\nа\nн\nм\nа\nл\nы\nд\nы\nр\nл\nа\nр\n.\nБ\nү\nт\nү\nн\n \nи\nн\nс\nа\nн\nл\nа\nр\n \nл\nә\nј\nа\nг\nә\nт\n \nв\nә\n \nһ\nү\nг\nу\nг\nл\nа\nр\nы\nн\nа\n \nҝ\nө\nр\nә\n \nа\nз\nа\nд\n \nв\nә\n \nб\nә\nр\nа\nб\nә\nр\n \nд\nо\nғ\nу\nл\nу\nр\nл\nа\nр\n.\n \nО\nн\nл\nа\nр\nы\nн\n \nш\nү\nу\nр\nл\nа\nр\nы\n \nв\nә\n \nв\nи\nҹ\nд\nа\nн\nл\nа\nр\nы\n \nв\nа\nр\n \nв\nә"
}
