id: "ba_Latn"
language: "ba"
script: "Latn"
name: "Bashkir, Latin"
sample_text {
  masthead_full: "BbAa"
  masthead_partial: "Rr"
  styles: "B\na\nr\nl\nı\nq\n \nk\ne\nş\ne\nl\nä\nr\n \ni\nr\ne\nk\nl\ne"
  tester: "B\na\nr\nl\nı\nq\n \nk\ne\nş\ne\nl\nä\nr\n \ni\nr\ne\nk\nl\ne\n,\n \nd\nä\nr\nä\nj\nä\nl\nä"
  poster_sm: "B\na\nr\nl\nı\nq"
  poster_md: "B\na\nr\nl\nı"
  poster_lg: "B\na"
  specimen_48: "B\na\nr\nl\nı\nq\n \nk\ne\nş\ne\nl\nä\nr\n \ni\nr\ne\nk\nl\ne\n,\n \nd\nä\nr\nä\nj\nä\nl\nä"
  specimen_36: "B\na\nr\nl\nı\nq\n \nk\ne\nş\ne\nl\nä\nr\n \ni\nr\ne\nk\nl\ne\n,\n \nd\nä\nr\nä\nj\nä\nl\nä\nr\ne\n \nh\nä\nm\n \nx\no\nq\nu\nq\nt\na\nr\nı\n \nt\ni\nñ"
  specimen_32: "B\na\nr\nl\nı\nq\n \nk\ne\nş\ne\nl\nä\nr\n \ni\nr\ne\nk\nl\ne\n,\n \nd\nä\nr\nä\nj\nä\nl\nä\nr\ne\n \nh\nä\nm\n \nx\no\nq\nu\nq\nt\na\nr\nı\n \nt\ni\nñ\n \nb\nu\nl\nı\np\n \nt\nı\nu\na\nl\na\nr\n.\n \nU\nl\na\nr\n "
  specimen_21: "B\na\nr\nl\nı\nq\n \nk\ne\nş\ne\nl\nä\nr\n \ni\nr\ne\nk\nl\ne\n,\n \nd\nä\nr\nä\nj\nä\nl\nä\nr\ne\n \nh\nä\nm\n \nx\no\nq\nu\nq\nt\na\nr\nı\n \nt\ni\nñ\n \nb\nu\nl\nı\np\n \nt\nı\nu\na\nl\na\nr\n.\n \nU\nl\na\nr\n \na\nq\nı\nl\n \nh\nä\nm\n \nv\nı\nj\nd\na\nn\n \ne\ny\nä\nh\ne\n \nh\nä\nm\n \nb\ne\nr\n-\nb\ne\nr\ne\nh\ne\nn\nä\n \nq\na\nr\na\nt\na\n \nq\nä\nr\nź\nä\nş\nl\ne\nk\n \nr\nu\nx\nı\nn\nd\na\n \nx\nä\nr\nä\nk\nä\nt\n \ni\nt\ne\nr\ng\nä\n \nt"
  specimen_16: "B\na\nr\nl\nı\nq\n \nk\ne\nş\ne\nl\nä\nr\n \ni\nr\ne\nk\nl\ne\n,\n \nd\nä\nr\nä\nj\nä\nl\nä\nr\ne\n \nh\nä\nm\n \nx\no\nq\nu\nq\nt\na\nr\nı\n \nt\ni\nñ\n \nb\nu\nl\nı\np\n \nt\nı\nu\na\nl\na\nr\n.\n \nU\nl\na\nr\n \na\nq\nı\nl\n \nh\nä\nm\n \nv\nı\nj\nd\na\nn\n \ne\ny\nä\nh\ne\n \nh\nä\nm\n \nb\ne\nr\n-\nb\ne\nr\ne\nh\ne\nn\nä\n \nq\na\nr\na\nt\na\n \nq\nä\nr\nź\nä\nş\nl\ne\nk\n \nr\nu\nx\nı\nn\nd\na\n \nx\nä\nr\nä\nk\nä\nt\n \ni\nt\ne\nr\ng\nä\n \nt\ne\ny\ne\nş\nt\nä\nr\n.\nB\na\nr\nl\nı\nq\n \nk\ne\nş\ne\nl\nä\nr\n \ni\nr\ne\nk\nl\ne\n,\n \nd\nä\nr\nä\nj\nä\nl\nä\nr\ne\n \nh\nä\nm\n \nx\no\nq\nu\nq\nt\na\nr\nı\n \nt\ni\nñ\n \nb\nu\nl\nı\np\n \nt\nı\nu\na\nl\na\nr\n.\n \nU\nl\na\nr\n \na\nq\nı\nl\n \nh\nä\nm\n \nv\nı\nj\nd\na\nn\n \ne\ny\nä\nh\ne\n \nh\nä\nm\n \nb\ne\nr\n-\nb\ne\nr\ne\nh\ne\nn\nä\n \nq\na\nr\na\nt\na\n \nq"
}
