id: "bax_Latn"
language: "bax"
script: "Latn"
name: "Bamun"
sample_text {
  masthead_full: "PpEe"
  masthead_partial: "Nn"
  styles: "P\ne\n \nn\na\n̂\n \nm\nv\ne\ń\n \ng\nu\ń\n \np\nu\ne\nn\n \nn"
  tester: "P\ne\n \nn\na\n̂\n \nm\nv\ne\ń\n \ng\nu\ń\n \np\nu\ne\nn\n \nn\ny\nu\n̈\nt\nu\n \np\no\n̂\n \nt"
  poster_sm: "P\ne\n \nn\na\n̂"
  poster_md: "P\ne\n \nn\na"
  poster_lg: "P\ne"
  specimen_48: "P\ne\n \nn\na\n̂\n \nm\nv\ne\ń\n \ng\nu\ń\n \np\nu\ne\nn\n \nn\ny\nu\n̈\nt\nu\n \np\no\n̂\n \nt"
  specimen_36: "P\ne\n \nn\na\n̂\n \nm\nv\ne\ń\n \ng\nu\ń\n \np\nu\ne\nn\n \nn\ny\nu\n̈\nt\nu\n \np\no\n̂\n \nt\ne\n \nm\nb\ne\n \nk\nu\ń\n \ng\nh\ne\ń\nt\n \nn\ng\na\nm\n "
  specimen_32: "P\ne\n \nn\na\n̂\n \nm\nv\ne\ń\n \ng\nu\ń\n \np\nu\ne\nn\n \nn\ny\nu\n̈\nt\nu\n \np\no\n̂\n \nt\ne\n \nm\nb\ne\n \nk\nu\ń\n \ng\nh\ne\ń\nt\n \nn\ng\na\nm\n \np\nu\na\n \nn\ng\nu\ń\ne\nn\ne\nn\ng\nu\ń\ne\n \nm\nb\ne\n "
  specimen_21: "P\ne\n \nn\na\n̂\n \nm\nv\ne\ń\n \ng\nu\ń\n \np\nu\ne\nn\n \nn\ny\nu\n̈\nt\nu\n \np\no\n̂\n \nt\ne\n \nm\nb\ne\n \nk\nu\ń\n \ng\nh\ne\ń\nt\n \nn\ng\na\nm\n \np\nu\na\n \nn\ng\nu\ń\ne\nn\ne\nn\ng\nu\ń\ne\n \nm\nb\ne\n \nt\ne\n \nw\nu\n̂\nm\ne\n \nn\ns\ne\nb\ne\n \np\nu\na\n \np\na\n \nm\nf\ne\ń\ne\ń\nk\ne\n̂\nt\n.\n \nP\ne\nn\n \na\n̂\n \nn\nt\nu\ń\nm\n \nt\ne\n \nm\nb\ne\n \nk\nu\ń\n \nr\ne\nm\n \nn\ng\na\nm\n \np\nu\na\n \nf\na\nb\ns\nh\ne\n \nn\ng\na\nm\n,\n \na"
  specimen_16: "P\ne\n \nn\na\n̂\n \nm\nv\ne\ń\n \ng\nu\ń\n \np\nu\ne\nn\n \nn\ny\nu\n̈\nt\nu\n \np\no\n̂\n \nt\ne\n \nm\nb\ne\n \nk\nu\ń\n \ng\nh\ne\ń\nt\n \nn\ng\na\nm\n \np\nu\na\n \nn\ng\nu\ń\ne\nn\ne\nn\ng\nu\ń\ne\n \nm\nb\ne\n \nt\ne\n \nw\nu\n̂\nm\ne\n \nn\ns\ne\nb\ne\n \np\nu\na\n \np\na\n \nm\nf\ne\ń\ne\ń\nk\ne\n̂\nt\n.\n \nP\ne\nn\n \na\n̂\n \nn\nt\nu\ń\nm\n \nt\ne\n \nm\nb\ne\n \nk\nu\ń\n \nr\ne\nm\n \nn\ng\na\nm\n \np\nu\na\n \nf\na\nb\ns\nh\ne\n \nn\ng\na\nm\n,\n \na\n \nn\ns\nh\ni\n \nn\nj\ni\n̂\nr\n’\na\np\n \nn\ne\n \ny\ni\n \nn\ns\nh\na\n̂\nn\ne\n \nn\ng\ne\ń\nt\nn\ne\n \nn\ng\na\n \ns\nh\na\np\n \np\no\n̂\n \nt\ne\n \nw\nu\np\nm\ne\n \np\no\nn\nt\na\n̂\n.\nP\ne\n \nn\na\n̂\n \nm\nv\ne\ń\n \ng\nu\ń\n \np\nu\ne\nn\n \nn\ny\nu\n̈\nt\nu\n \np\no\n̂\n \nt\ne\n \nm\nb\ne\n \nk\nu\ń\n \ng\nh\ne\ń\nt\n \nn\ng\na\nm\n \np\nu\na\n \nn\ng\nu\ń\ne\nn\ne\nn"
}
