id: "be"
language: "be"
script: "Cyrl"
name: "Belarusian"
autonym: "Беларуская"
population: 10064517
region: "BY"
region: "PL"
region: "UA"
exemplar_chars {
  base: "а б в г д {дж} {дз} е ё ж з і й к л м н о п р с т у ў ф х ц ч ш ы ь э ю я {дж} {дз} {дж} {дз} {дж} {дз} {дж} {дз} {дж} {дз} {дж} {дз} {дж} {дз} {дж} {дз} {дж} {дз} {дж} {дз} {дж} {дз} {дж} {дз} {дж} {дз} {дж} {дз} {дж} {дз}"
  auxiliary: "{а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́} {а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́} {а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́} {а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́} {а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́} {а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́} {а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́} {а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́} {а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́} {а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́} {а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́} {а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́} {а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́} {а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́} {а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́} {а́} {е́} {ё́} {і́} {о́} {у́} {ы́} {э́} {ю́} {я́}"
  marks: "◌̆ ◌̈"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‑ , ; : ! ? . « » ( ) [ ] { } { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "А Б В Г Д Е Ё Ж З І Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Ы Ь Э Ю Я"
}
sample_text {
  masthead_full: "УуСс"
  masthead_partial: "Ее"
  styles: "Прымаючы пад увагу, што прызнанне годнасці,"
  tester: "прымаючы пад увагу, што грэбаванне і пагарда да правоў чалавека"
  poster_sm: "прымаючы пад"
  poster_md: "прымаючы"
  poster_lg: "Усе"
  specimen_48: "прымаючы пад увагу, што народы Абʼяднаных Нацый пацвердзілі ў"
  specimen_36: "Ні над кім не павінны ўчыняцца катаванні або жорсткія, бесчалавечныя або ўніжаючыя яго годнасць абыходжанне і пакаранне."
  specimen_32: "Кожны чалавек мае права на эфектыўнае аднаўленне ў правах кампетэнтнымі нацыянальнымі судамі ў выпадках парушэння яго асноўных правоў, якія дадзены яму канстытуцыяй або законам."
  specimen_21: "Ні над кім не павінны ўчыняцца самавольны арышт, затрыманне або выгнанне.\nКожны чалавек, для вызначэння яго правоў і абавязкаў і для ўстанаўлення абгрунтаванасці прадʼяўленага яму крымінальнага абвінавачання, мае права, на падставе поўнай роўнасці, на тое, каб яго справа была разгледжана публічна і з захаваннем усіх патрабаванняў справядлівасці незалежным і непрадузятым судом."
  specimen_16: "Ні над кім не павінны ўчыняцца самавольнае ўмяшанне ў яго асабістае і сямейнае жыццё, самавольны замах на недатыкальнасць яго жылля, тайну яго карэспандэнцыі або на яго гонар і рэпутацыю. Кожны чалавек мае права на абарону закону ад такога ўмяшання або такіх замахаў.\nКожны чалавек мае права на свабоду думкі, сумлення і рэлігіі; гэта права ўключае свабоду мяняць сваю рэлігію або пераканні і свабоду спавядаць сваю рэлігію або перакананні як аднаасобна, так і разам з іншымі, публічным або прыватным парадкам у вучэнні, богаслужэнні і выкананні рэлігійных і рытуальных абрадаў."
}
