id: "be_Latn"
language: "be"
script: "Latn"
name: "Belarusian, Latin"
sample_text {
  masthead_full: "UuSs"
  masthead_partial: "Ii"
  styles: "U\ns\ni\ne\n \nl\nu\nd\nz\ni\n \nn\na\nr\na\nd\nž\na\nj\nu\nc"
  tester: "U\ns\ni\ne\n \nl\nu\nd\nz\ni\n \nn\na\nr\na\nd\nž\na\nj\nu\nc\nc\na\n \ns\nv\na\nb\no\nd\nn"
  poster_sm: "U\ns\ni\ne\n \nl"
  poster_md: "U\ns\ni\ne\n "
  poster_lg: "U\ns"
  specimen_48: "U\ns\ni\ne\n \nl\nu\nd\nz\ni\n \nn\na\nr\na\nd\nž\na\nj\nu\nc\nc\na\n \ns\nv\na\nb\no\nd\nn"
  specimen_36: "U\ns\ni\ne\n \nl\nu\nd\nz\ni\n \nn\na\nr\na\nd\nž\na\nj\nu\nc\nc\na\n \ns\nv\na\nb\no\nd\nn\ny\nm\ni\n \ni\n \nr\no\nŭ\nn\ny\nm\ni\n \nŭ\n \ns\nv\na\nj"
  specimen_32: "U\ns\ni\ne\n \nl\nu\nd\nz\ni\n \nn\na\nr\na\nd\nž\na\nj\nu\nc\nc\na\n \ns\nv\na\nb\no\nd\nn\ny\nm\ni\n \ni\n \nr\no\nŭ\nn\ny\nm\ni\n \nŭ\n \ns\nv\na\nj\no\nj\n \nh\no\nd\nn\na\nś\nc\ni\n \ni\n \np\nr\na\nv\na\nc"
  specimen_21: "U\ns\ni\ne\n \nl\nu\nd\nz\ni\n \nn\na\nr\na\nd\nž\na\nj\nu\nc\nc\na\n \ns\nv\na\nb\no\nd\nn\ny\nm\ni\n \ni\n \nr\no\nŭ\nn\ny\nm\ni\n \nŭ\n \ns\nv\na\nj\no\nj\n \nh\no\nd\nn\na\nś\nc\ni\n \ni\n \np\nr\na\nv\na\nc\nh\n.\n \nJ\na\nn\ny\n \nn\na\nd\nz\ni\ne\nl\ne\nn\ny\n \nr\no\nz\nu\nm\na\nm\n \ni\n \ns\nu\nm\nl\ne\nń\nn\ni\ne\nm\n \ni\n \np\na\nv\ni\nn\nn\ny\n \ns\nt\na\nv\ni\nc\nc\na\n \na\nd\nz\ni\nn\n \nd\na\n \na\nd\nn\na\nh\no\n \nŭ\n \nd\nu\nc"
  specimen_16: "U\ns\ni\ne\n \nl\nu\nd\nz\ni\n \nn\na\nr\na\nd\nž\na\nj\nu\nc\nc\na\n \ns\nv\na\nb\no\nd\nn\ny\nm\ni\n \ni\n \nr\no\nŭ\nn\ny\nm\ni\n \nŭ\n \ns\nv\na\nj\no\nj\n \nh\no\nd\nn\na\nś\nc\ni\n \ni\n \np\nr\na\nv\na\nc\nh\n.\n \nJ\na\nn\ny\n \nn\na\nd\nz\ni\ne\nl\ne\nn\ny\n \nr\no\nz\nu\nm\na\nm\n \ni\n \ns\nu\nm\nl\ne\nń\nn\ni\ne\nm\n \ni\n \np\na\nv\ni\nn\nn\ny\n \ns\nt\na\nv\ni\nc\nc\na\n \na\nd\nz\ni\nn\n \nd\na\n \na\nd\nn\na\nh\no\n \nŭ\n \nd\nu\nc\nh\nu\n \nb\nr\na\nc\nt\nv\na\n.\nU\ns\ni\ne\n \nl\nu\nd\nz\ni\n \nn\na\nr\na\nd\nž\na\nj\nu\nc\nc\na\n \ns\nv\na\nb\no\nd\nn\ny\nm\ni\n \ni\n \nr\no\nŭ\nn\ny\nm\ni\n \nŭ\n \ns\nv\na\nj\no\nj\n \nh\no\nd\nn\na\nś\nc\ni\n \ni\n \np\nr\na\nv\na\nc\nh\n.\n \nJ\na\nn\ny\n \nn\na\nd\nz\ni\ne\nl\ne\nn\ny\n \nr\no\nz\nu\nm\na\nm\n \ni\n \ns\nu\nm\nl\ne\nń\nn\ni\ne\nm\n \ni\n \np\na"
}
