id: "bew_Latn"
language: "bew"
script: "Latn"
name: "Betawi"
population: 5607546
region: "ID"
sample_text {
  masthead_full: "SsEe"
  masthead_partial: "Mm"
  styles: "Semue orang ntu dilahirin bebas ame punye"
  tester: "Semue orang ntu dilahirin bebas ame punye martabat dan hak-hak"
  poster_sm: "Semue orang"
  poster_md: "Semue"
  poster_lg: "Semue"
  specimen_48: "Semue orang ntu dilahirin bebas ame punye martabat"
  specimen_36: "Semue orang ntu dilahirin bebas ame punye martabat dan hak-hak yang same. Mereka ntu dikasih akal ame ati nurani dan kudu bergaul satu ame lainnye dalem semangat persaudaraan."
  specimen_32: "Semue orang ntu dilahirin bebas ame punye martabat dan hak-hak yang same. Mereka ntu dikasih akal ame ati nurani dan kudu bergaul satu ame lainnye dalem semangat persaudaraan."
  specimen_21: "Semue orang ntu dilahirin bebas ame punye martabat dan hak-hak yang same. Mereka ntu dikasih akal ame ati nurani dan kudu bergaul satu ame lainnye dalem semangat persaudaraan.\nSemue orang ntu dilahirin bebas ame punye martabat dan hak-hak yang same. Mereka ntu dikasih akal ame ati nurani dan kudu bergaul satu ame lainnye dalem semangat persaudaraan."
  specimen_16: "Semue orang ntu dilahirin bebas ame punye martabat dan hak-hak yang same. Mereka ntu dikasih akal ame ati nurani dan kudu bergaul satu ame lainnye dalem semangat persaudaraan.\nSemue orang ntu dilahirin bebas ame punye martabat dan hak-hak yang same. Mereka ntu dikasih akal ame ati nurani dan kudu bergaul satu ame lainnye dalem semangat persaudaraan.\nSemue orang ntu dilahirin bebas ame punye martabat dan hak-hak yang same. Mereka ntu dikasih akal ame ati nurani dan kudu bergaul satu ame lainnye dalem semangat persaudaraan.\nSemue orang ntu dilahirin bebas ame punye martabat dan hak-hak yang same. Mereka ntu dikasih akal ame ati nurani dan kudu bergaul satu ame lainnye dalem semangat persaudaraan."
}
