id: "bfa_Latn"
language: "bfa"
script: "Latn"
name: "Bari"
sample_text {
  masthead_full: "ŊŋUu"
  masthead_partial: "Tt"
  styles: "Ŋ\nu\nt\nu\n \nl\ni\nŋ\n \na\n \ny\nu\nŋ\nw\ne\n \nk\na\nn\na"
  tester: "Ŋ\nu\nt\nu\n \nl\ni\nŋ\n \na\n \ny\nu\nŋ\nw\ne\n \nk\na\nn\na\n,\n \nj\no\nj\no\n \ni\n \nt"
  poster_sm: "Ŋ\nu\nt\nu\n \nl"
  poster_md: "Ŋ\nu\nt\nu\n "
  poster_lg: "Ŋ\nu"
  specimen_48: "Ŋ\nu\nt\nu\n \nl\ni\nŋ\n \na\n \ny\nu\nŋ\nw\ne\n \nk\na\nn\na\n,\n \nj\no\nj\no\n \ni\n \nt"
  specimen_36: "Ŋ\nu\nt\nu\n \nl\ni\nŋ\n \na\n \ny\nu\nŋ\nw\ne\n \nk\na\nn\na\n,\n \nj\no\nj\no\n \ni\n \nt\no\nď\ni\nr\ni\n \nk\no\n \nď\ne\nk\ne\ns\ni\n \nk\no\n \nt"
  specimen_32: "Ŋ\nu\nt\nu\n \nl\ni\nŋ\n \na\n \ny\nu\nŋ\nw\ne\n \nk\na\nn\na\n,\n \nj\no\nj\no\n \ni\n \nt\no\nď\ni\nr\ni\n \nk\no\n \nď\ne\nk\ne\ns\ni\n \nk\no\n \nt\ni\n \ns\ne\n \nt\no\nk\ni\nt\na\nk\ni\n \nk\no\n \n‘\nb\nö\nr"
  specimen_21: "Ŋ\nu\nt\nu\n \nl\ni\nŋ\n \na\n \ny\nu\nŋ\nw\ne\n \nk\na\nn\na\n,\n \nj\no\nj\no\n \ni\n \nt\no\nď\ni\nr\ni\n \nk\no\n \nď\ne\nk\ne\ns\ni\n \nk\no\n \nt\ni\n \ns\ne\n \nt\no\nk\ni\nt\na\nk\ni\n \nk\no\n \n‘\nb\nö\nr\ni\nk\n \nk\no\n \nm\nu\nl\nö\nk\nö\nt\ny\no\n \nl\no\n \nt\no\nl\nu\nŋ\na\ns\ne\nr\na\nn\n.\n \nS\ne\n \na\n \nď\no\nk\na\n \nk\no\n \nd\ne\nn\ne\nt\n \nn\na\n \nk\nu\nl\ny\na\n \nn\na\n’\nb\nu\nt\n \nk\no\n \nn\na\nr\no\nk\n.\nŊ\nu\nt\nu\n "
  specimen_16: "Ŋ\nu\nt\nu\n \nl\ni\nŋ\n \na\n \ny\nu\nŋ\nw\ne\n \nk\na\nn\na\n,\n \nj\no\nj\no\n \ni\n \nt\no\nď\ni\nr\ni\n \nk\no\n \nď\ne\nk\ne\ns\ni\n \nk\no\n \nt\ni\n \ns\ne\n \nt\no\nk\ni\nt\na\nk\ni\n \nk\no\n \n‘\nb\nö\nr\ni\nk\n \nk\no\n \nm\nu\nl\nö\nk\nö\nt\ny\no\n \nl\no\n \nt\no\nl\nu\nŋ\na\ns\ne\nr\na\nn\n.\n \nS\ne\n \na\n \nď\no\nk\na\n \nk\no\n \nd\ne\nn\ne\nt\n \nn\na\n \nk\nu\nl\ny\na\n \nn\na\n’\nb\nu\nt\n \nk\no\n \nn\na\nr\no\nk\n.\nŊ\nu\nt\nu\n \nl\ni\nŋ\n \na\n \ny\nu\nŋ\nw\ne\n \nk\na\nn\na\n,\n \nj\no\nj\no\n \ni\n \nt\no\nď\ni\nr\ni\n \nk\no\n \nď\ne\nk\ne\ns\ni\n \nk\no\n \nt\ni\n \ns\ne\n \nt\no\nk\ni\nt\na\nk\ni\n \nk\no\n \n‘\nb\nö\nr\ni\nk\n \nk\no\n \nm\nu\nl\nö\nk\nö\nt\ny\no\n \nl\no\n \nt\no\nl\nu\nŋ\na\ns\ne\nr\na\nn\n.\n \nS\ne\n \na\n \nď\no\nk\na\n \nk\no\n \nd\ne\nn\ne\nt\n \nn\na\n \nk\nu\nl\ny\na\n "
}
