id: "bho"
name: "Bhojpuri"
preferred_name: ""
autonym: "भोजपुरी"
population: 32934797
region: "IN"
region: "MU"
region: "NP"
script: "Devanagari"
exemplar_chars {
  base: "𑂃 𑂄 𑂅 𑂆 𑂇 𑂈 𑂉 𑂊 𑂋 𑂌 𑂍 𑂎 𑂏 𑂐 𑂑 𑂒 𑂓 𑂔 𑂕 𑂖 𑂗 𑂘 𑂙 𑂚 𑂛 𑂜 𑂝 𑂞 𑂟 𑂠 𑂡 𑂢 𑂣 𑂤 𑂥 𑂦 𑂧 𑂨 𑂩 𑂪 𑂫 𑂬 𑂭 𑂮 𑂯"
  auxiliary: "ॐ"
  marks: "◌𑂀 ◌𑂂 ◌𑂰 ◌𑂲 ◌𑂳 ◌𑂴 ◌𑂵 ◌𑂶 ◌𑂸 ◌𑂺"
  numerals: "० १ २ ३ ४ ५ ६ ७ ८ ९ 0 1 2 3 4 5 6 7 8 9"
  punctuation: "। ॥ ॰"
}
sample_text {
  masthead_full: "सबहल"
  masthead_partial: "कन"
  tester: "सबहिं के ओकर उचित सम्मान आओर मानव परिवार के सभे आदिमी के बराबरी के हक ही विश्व समुदाय"
  poster_sm: "मानवाधिकार के उल्लंघन"
  poster_md: "यदि केहु तानाशाही"
  poster_lg: "सबहि"
  specimen_48: "संयुक्त राष्ट्र के लोगिन आपन चार्टर में मौलिक मानवाधिकार, मानव के सम्मान आओर उपयोगिता तथा"
  specimen_36: "केहु के खिलाफ अपराधिक मामला होखे चाहे केकरो अधिकार और कर्तव्य के निर्धारण के सिलसिला में कौनो स्वतंत्रा आओर निष्पक्ष संगठन के सामने निष्पक्ष सुनवाई खातिर समान अधिकार हवे ।"
  specimen_32: "सब लोगनि के सोचे के आओर कौनो धर्म अपनावे के अधिकार हवे तथा ओ आपन धर्म और मान्यता में भी बदलाव ला सकेला। संगे ओ अकेले आओर समूह में कौनो सार्वजनिक या नीजि जगह पर आपन धर्म या विश्वास के पालन, प्रवचन आओर पूजा-पाठ के जरिए कर सकेला।"
  specimen_21: "सबहिं के विचार आओर अभियक्ति के अधिकार हवे। आओर ओकर ई विचार में कौनो दखल ना हो सकता, संगे ओ संचार के कौनो साधन के जरिए कही से कैसनो सूचना आओर विचार प्राप्त कर सकेला।\nसमाज के हरेक आदिमी के सामाजिक सुरक्षा के अधिकार हवे। साथहिं देश के आर्थिक, सामाजिक आओर सांस्कृतिक अधिकार के उपयोग करे के अधिकार ह, जे ओकर व्यक्तिघ् के उपयोग राष्टघीय प्रयास आओर अन्तर्राष्ट्रीय सहयोग से ही संभव हो सकेला जे ओ राष्ट्र के संसाधन ओओर संगठन पर निर्भर करता।"
  specimen_16: "सबकरा के आराम तथा छुघ् मनाबे के अधिकार बा तथा काज करे के समय के सेहो एक उचित सीमा बा तथा समय-समय पर वेतन सहित छुघेि के उपभोग करे के अधिकारो बा।\nसबहिं के इ घोषणा में निर्धारित अधिकार आओर आजादी के सामाजिक आओर अन्तर्राष्ट्रीय स्तर पर पावे के अधिकार बा।\nई घोषणा में लिखल कौनो अनुच्छेद के मतलब इ ना ह कि कौनो राज्य, समूह चाहे व्यक्ति कौनो ऐसन काज में शामिल होखे चाहे कौनो ऐसन काम करे, जेकरा से ए में लिखल अधिकार और स्वतंत्रता नष्ट होखे।\nसबहिं के ओकर उचित सम्मान आओर मानव परिवार के सभे आदिमी के बराबरी के हक ही विश्व समुदाय के अजादी, न्याय आओर शांति के बुनियाद हवे।\nमानवाधिकार के उल्लंघन हरदम अमानवीय काज के कारणो होखेला जा के चलते मानवता के अंत:करण दु:खी होखेला। एक आम आदिमी के सबसे बड़ा इच्छा इहे होखेला कि इ दुनिया में ओके भाषण और विचार के आजादी मिले साथ हि डर आओर इच्छा से हो मुक्ति मिले।"
}
