id: "blt"
language: "blt"
script: "Tavt"
population: 0
region: "VN"
sample_text {
  masthead_full: "ꪹꪕꪉꪀ"
  masthead_partial: "ꪱꪋ"
  styles: "ꪫꪸꪀ ꪶꪀꪉ ꪐꪽ ꪻꪬ ꪩꪾꪣ ꫛ ꪶꪔꪙ ꪠꪴ - ꪝꪳꪉ ꪁꪫꪸꪙ ꪹꪋꪷꪉ ꪝꪸꪉ ꪹꪚꪱ"
  tester: "ꪫꪸꪀ ꪹꪤꪸꪒ ꪩꪳꪚ ꪩꪱꪙ ꪀꪾꪚ ꪒꪴ ꪉꪱꪥ  ꪩꪾꪣ ꫛ ꪶꪔꪙ ꪠꪴ ꪭꪳ ꪝꪱ ꪼꪝ ꪭꪮꪒ ꪝꪳꪉ ꪄꪴ ꪹꪤꪸꪒ ꪶꪏꪥ ꪚꪱꪚ"
  poster_sm: "ꪩꪾꪣ ꫛ ꪶꪔꪙ ꪠꪴ"
  poster_md: "ꪹꪜꪸꪙ ꪹꪊꪉ ꪹꪋ"
  poster_lg: "ꪹꪕꪸꪉ"
  specimen_48: "ꪝꪳꪉ ꪹꪘꪀ ꪹꪊꪱ ꪹꪭꪙ ꪼꪒ ꪐꪽ ꪝꪱꪫ, ꪝꪮꪣ ꪀꪾꪚ ꪩꪺꪉ ꪜꪴꪙ ꪵꪔꪉ  ꪨꪸꪙ ꪹꪭꪷꪚ ꪀꪺꪀ, ꪹꪬꪙ ꪭꪳꪒ"
  specimen_36: "ꪹꪚꪱ ꪣꪲ ꪻꪠ ꪜꪰꪒ ꪄꪮꪥ ꪹꪏꪷ ꪭꪳ ꪫꪱ ꪊꪺꪚ ꪶꪄꪣ ꪙꪱꪚ ꪹꪏꪉ ꫛ ꪄꪮꪥ  ꪹꪏꪷ, ꪋꪴ ꪮꪽ ꪹꪏꪉ ꪹꪜꪸꪙ ꪄꪮꪥ ꪹꪏꪷ ꪀꪾꪚ ꪁꪱ ꪄꪱꪥ ꪄꪮꪥ ꪹꪏꪷ ꪒꪷ ꪹꪜꪸꪙ ꪄꪴ ꪹꪀꪷꪣ ꪀꪰꪒ ꪹꪁꪸꪉ."
  specimen_32: "ꪹꪕꪸꪉ ꪀꪱ ꪋꪴ ꫛ ꪻꪠ ꪁꪷ ꪼꪒ ꪹꪋꪷꪉ ꪝꪸꪉ  ꪕꪮꪥ ꪠꪱꪚ ꪨꪺꪒ ꪼꪜ ꪵꪊ ꪹꪏꪉ ꪒꪸꪫ ꪹꪚꪱ ꪣꪲ ꪄꪴ ꪻꪒ ꪜꪽ ꪵꪊꪀ - ꪹꪕꪸꪉ ꪀꪱ ꪋꪴ ꫛ ꪝꪮꪣ ꪼꪒ ꪼꪜ ꪵꪊ ꪹꪏꪉ ꪒꪸꪫ -ꪼꪒ ꪁꪾꪣ ꪔꪷ ꪝꪳꪉ ꪄꪴ ꪜꪽ ꪵꪊꪀ ꪄꪮꪉ ꪁꪫꪱꪣ ꪜꪱꪫ ꪙꪲ ꪵꪀꪉ ꪼꪒ ꪁꪾꪣ ꪔꪷ  ꪝꪳꪉ  ꪄꪴ ꪑꪮꪀ ꪑꪺꪙ ꪵꪚꪉ ꪵꪑꪀ ꪎꪸ ꪀꪽ ꪽ."
  specimen_21: "ꪋꪴ ꫛ ꪻꪠ ꪁꪷ ꪣꪲ ꪁꪫꪸꪙ ꪼꪒ ꪕꪫꪱ ꪮꪱꪙ ꪹꪣꪉ ꪽ ꪼꪜ  ꪵꪊ ꪕꪮꪥ ꪠꪱꪚ ꪩꪺꪒ ꪁꪾꪣ ꪔꪷ ꪝꪳꪉ ꪄꪴ  ꪹꪥꪸꪒ ꪠꪲꪒ ꪕꪮꪥ ꪭꪲꪒ ꪻꪐ ꪒꪺꪉ ꪄꪮꪉ ꪠꪱꪚ ꪩꪺꪒ ꪕꪰꪒ ꪮꪮꪀ.\nꪹꪚꪱ ꪣꪲ ꪻꪠ ꪊꪺꪚ ꪜꪰꪒ,  ꪎꪰꪉ ꪼꪫ ꪭꪳ ꪫꪱ ꪬꪱꪀ ꪩꪰꪀ ꪶꪎꪉ  ꪼꪜ ꪹꪣꪉ ꪮꪳꪙ\nꪋꪴ ꫛ ꪻꪠ ꪁꪷ ꪻꪬ ꪼꪒ ꪣꪲ ꪁꪫꪸꪙ  ꪹꪋꪷꪉ ꪝꪸꪉ, ꪼꪒ ꪕꪫꪱ ꪮꪱꪙ ꪹꪣꪉ ꪽ ꪵꪔꪉ ꪹꪩꪷꪉ ꪹꪎꪷꪉ ꪋꪮꪚ ꪵꪊꪉ ꪵꪊꪀ ꪹꪚꪱ ꪚꪰꪀ ꪶꪕꪥ ꪎꪴ ꫛ ꪻꪒ ꪁꪫꪸꪙ ꪚꪰꪀ ꪩꪱ ꪫꪱ ꪮꪫꪱꪙ.\nꪹꪚꪱ ꪣꪲ ꪻꪠ ꪊꪺꪚ ꫛ ꪮꪳꪙ ꪮꪱꪉ ꪕꪷ ꪹꪊꪱ ꪵꪙꪉ ꪹꪤꪸꪒ ꪻꪬ ꪋꪺ  ꪹꪩꪷꪥ ꪚꪮꪣ, ꪋꪺ ꪹꪭꪙ,  ꪚꪮꪙ ꪤꪴ ꪵꪀꪉ ꪎꪳ ꪎꪱꪙ ꪄꪮꪉ ꪚꪮꪣ ꫛ ꪽ ꪹꪚꪱ ꪵꪝꪒ ꪝꪱꪙ ꪭꪮꪒ ꪋꪳ ꪎꪸꪉ ꪘꪱ ꪔꪱ ꪄꪮꪉ ꪹꪊꪱ. ꪋꪴ ꫛ ꪝꪮꪣ ꪼꪒ ꪠꪱꪚ ꪩꪺꪒ ꪼꪜ ꪵꪊ ꪹꪮꪱ ꪁꪾꪣ  ꪔꪷ ꪝꪳꪉ  ꪄꪴ  ꪵꪮ  ꪹꪥꪸꪒ ꪒꪴ ꪉꪱꪥ ꪵꪝ  ꪹꪊꪱ ꪹꪏꪉ ꪽ."
  specimen_16: "ꪋꪴ ꫛ ꪝꪮꪣ ꪼꪒ ꪣꪲ ꪁꪫꪸꪙ ꪈꪾ ꪜꪴꪙ ꪮꪮꪀ ꪒꪰꪀ ꪵꪒꪣ ꪀꪾꪚ ꪎꪱꪉ ꪭꪲꪒ ꪅꪮꪉ, ꪹꪕꪸꪉ ꪀꪱ ꪕꪳ ꪕꪱꪉ ꪜꪸꪙ ꪹꪋ ꪎꪱꪥ ꪵꪀꪉ ꪭꪲꪒ ꪅꪮꪉ, ꪀꪾꪚ ꪼꪒ ꪕꪳ ꪕꪱꪉ ꪮꪮꪀ ꪘꪱ ꫛ ꪹꪋ ꪎꪱꪥ ꪣꪲ ꪭꪳ ꪎꪱꪉ ꪭꪲꪒ ꪅꪮꪉ ꪵꪔ ꪜꪱꪉ ꪒꪱꪥ ꪋꪸꪙ ꪣꪱ ꪹꪤꪸꪒ ꪹꪎꪸꪙ ꪡꪮꪙ, ꪀꪴꪉ ꪹꪏꪷ,ꪹꪜꪸꪙ ꪄꪮꪉ ꪚꪮꪣ ꪹꪊꪱ ꪭꪳ ꪫꪱ ꪄꪮꪉ ꪭꪺꪣ ꪀꪽ ꪹꪜꪸꪙ ꪮꪮꪀ ꪘꪱ ꪭꪳ ꪄꪮꪉ ꪤꪸꪉ ꪚꪮꪣ ꪹꪊꪱ.\nꪋꪴ ꫛ ꪝꪮꪣ ꪣꪲ ꪁꪫꪸꪙ ꪕꪳ ꪕꪱꪉ ꪜꪱꪀ ꪹꪫꪱ ꪎꪳ ꪎꪱꪙ ꪵꪀꪉ ꪵꪀ ꪼꪄ ꪮꪮꪀ  ꪩꪱꪉ ꪈꪾ ꪩꪱꪉ ꪜꪮꪉ ꪕꪳ ꪕꪱꪉ ꪩꪱꪉ ꪈꪾ ꪭꪲꪒ ꪄꪮꪉ ꪹꪊꪱ, ꪹꪚꪱ ꪤꪴ ꪀꪮꪉ ꪄꪴ ꪶꪄꪣ ꪙꪱꪚ ꪻꪒ, ꪕꪳ ꪕꪱꪉ ꪏꪮꪀ ꪎꪱꪫ ꪹꪮꪱ ꪁꪫꪱꪣ ꪭꪴ ꪏꪸꪉ ꪄꪮꪉ ꫛ ꪮꪳꪙ ꪹꪎꪱ ꪜꪱꪫ ꪣꪱ ꪹꪚꪱ ꪁꪫꪱꪣ ꪹꪣꪉ ꪻꪒ.\nꪋꪴ ꫛ ꪹꪜꪸꪙ ꪹꪊꪱ ꪚꪱꪙ ꪹꪣꪉ, ꪝꪮꪣ ꪼꪒ ꪣꪲ ꪁꪫꪸꪙ ꪚꪱꪫ ꪬꪸꪣ ꪎꪱ ꪶꪭꪥ ꪁꪷ ꪹꪏꪉ ꪒꪸꪫ ꪫꪸꪀ ꪹꪥꪸꪒ ꪀꪲꪙ ꪣꪱ ꪕꪱꪉ ꪠꪱꪥ ꪹꪉꪷꪙ ꪘꪰꪉ ꪎꪱ ꪶꪭꪥ ꪀꪾꪚ ꪪꪽ ꪬꪫꪱ ꪹꪚꪱ ꪹꪖꪸ ꪒꪴꪒ ꪖꪸꪫ ꪻꪬ ꪩꪾ ꫛ ꪶꪔꪙ ꪠꪴ ꪄꪮꪉ ꪹꪊꪱ, ꪶꪎ ꪫꪱꪙ ꪀꪫꪱꪉ ꪄꪫꪱꪉ ꪘꪰꪉ ꪒꪮꪣ ꪹꪣꪉ ꪁꪱꪙ ꪠꪱ ꪀꪾꪚ ꪋꪴ ꪹꪣꪉ, ꪋꪮꪚ ꪹꪋꪷꪉ ꪫꪸꪀ ꪔꪰꪉ ꪵꪕꪉ ꪩꪺꪉ ꪜꪴꪙ ꪄꪮꪉ ꪢꪮꪥ ꪹꪣꪉ."
}
