id: "boa_Latn"
language: "boa"
script: "Latn"
name: "Bora"
sample_text {
  masthead_full: "PpÁá"
  masthead_partial: "Mm"
  styles: "P\ná\nm\ne\ne\nr\ne\n \ní\ní\nñ\nú\nj\nɨ\nr\ni\n \nm\ne\ní\nj"
  tester: "P\ná\nm\ne\ne\nr\ne\n \ní\ní\nñ\nú\nj\nɨ\nr\ni\n \nm\ne\ní\nj\nc\ny\na\nm\ne\n \nt\ns\ná\n "
  poster_sm: "P\ná\nm\ne\ne\nr"
  poster_md: "P\ná\nm\ne\ne"
  poster_lg: "P\ná"
  specimen_48: "P\ná\nm\ne\ne\nr\ne\n \ní\ní\nñ\nú\nj\nɨ\nr\ni\n \nm\ne\ní\nj\nc\ny\na\nm\ne\n \nt\ns\ná\n "
  specimen_36: "P\ná\nm\ne\ne\nr\ne\n \ní\ní\nñ\nú\nj\nɨ\nr\ni\n \nm\ne\ní\nj\nc\ny\na\nm\ne\n \nt\ns\ná\n \nm\nú\nh\nó\nj\nɨ\ń\ns\nɨ\ń\n \np\na\nñ\né\n \nɨ\ń\nc\nu\nb"
  specimen_32: "P\ná\nm\ne\ne\nr\ne\n \ní\ní\nñ\nú\nj\nɨ\nr\ni\n \nm\ne\ní\nj\nc\ny\na\nm\ne\n \nt\ns\ná\n \nm\nú\nh\nó\nj\nɨ\ń\ns\nɨ\ń\n \np\na\nñ\né\n \nɨ\ń\nc\nu\nb\ná\nh\nr\ná\nd\nú\n \nm\ne\ní\nj\nc\ny\ná\ní\nt\ny\nu\nr\nó"
  specimen_21: "P\ná\nm\ne\ne\nr\ne\n \ní\ní\nñ\nú\nj\nɨ\nr\ni\n \nm\ne\ní\nj\nc\ny\na\nm\ne\n \nt\ns\ná\n \nm\nú\nh\nó\nj\nɨ\ń\ns\nɨ\ń\n \np\na\nñ\né\n \nɨ\ń\nc\nu\nb\ná\nh\nr\ná\nd\nú\n \nm\ne\ní\nj\nc\ny\ná\ní\nt\ny\nu\nr\nó\nn\ne\n.\n \nP\ná\nm\ne\ne\nr\ne\n \nt\ns\na\nh\nd\nú\nr\né\n \ni\nm\ní\n \nm\ne\ní\nj\nc\ny\na\nm\ne\n \nm\ne\nw\ná\nj\ny\nú\nj\nc\na\nt\ns\ní\nñ\ne\n \nm\né\np\nɨ\ń\ná\ná\nb\nó\nj\nc\na\nt\ns\ní\ni\ny\ná\n \nt\ns\na\na\nt\né\nk\né\n \né\nh"
  specimen_16: "P\ná\nm\ne\ne\nr\ne\n \ní\ní\nñ\nú\nj\nɨ\nr\ni\n \nm\ne\ní\nj\nc\ny\na\nm\ne\n \nt\ns\ná\n \nm\nú\nh\nó\nj\nɨ\ń\ns\nɨ\ń\n \np\na\nñ\né\n \nɨ\ń\nc\nu\nb\ná\nh\nr\ná\nd\nú\n \nm\ne\ní\nj\nc\ny\ná\ní\nt\ny\nu\nr\nó\nn\ne\n.\n \nP\ná\nm\ne\ne\nr\ne\n \nt\ns\na\nh\nd\nú\nr\né\n \ni\nm\ní\n \nm\ne\ní\nj\nc\ny\na\nm\ne\n \nm\ne\nw\ná\nj\ny\nú\nj\nc\na\nt\ns\ní\nñ\ne\n \nm\né\np\nɨ\ń\ná\ná\nb\nó\nj\nc\na\nt\ns\ní\ni\ny\ná\n \nt\ns\na\na\nt\né\nk\né\n \né\nh\nd\nɨ\ń\nȈ\ń\nv\ná\nl\nl\ne\nt\nú\nm\né\n \né\nh\nn\ne\n \nm\nú\nu\n \nm\né\np\na\nñ\né\nt\nú\né\nn\né\n \nn\na\nh\nb\né\nm\nu\nm\na\n \nm\ne\ní\nj\nc\ny\na\nd\nu\n.\nP\ná\nm\ne\ne\nr\ne\n \ní\ní\nñ\nú\nj\nɨ\nr\ni\n \nm\ne\ní\nj\nc\ny\na\nm\ne\n \nt\ns\ná\n \nm\nú\nh\nó\nj\nɨ\ń\ns\nɨ\ń\n \np\na\nñ\né\n \nɨ\ń\nc\nu\nb\ná\nh\nr\ná\nd\nú\n \nm\ne\ní\nj\nc\ny\ná\ní\nt\ny\nu\nr\nó"
}
