id: "brx"
language: "brx"
script: "Deva"
name: "Bodo"
autonym: "बरʼ"
population: 1856526
region: "IN"
exemplar_chars {
  base: "़ ँ ं अ आ इ ई उ ऊ ऍ ए ऐ ऑ ओ औ क ख ग घ च छ ज झ ञ ट ठ ड {ड़} ढ ण त थ द ध न प फ ब भ म य र ल ळ व श ष स ह ा ि ी ु ू ृ ॅ े ै ॉ ो ौ ् {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़}"
  auxiliary: "‌‍"
  marks: "◌ँ ◌ं ◌ः ◌़ ◌ा ◌ि ◌ी ◌ु ◌ू ◌ृ ◌े ◌ै ◌ो ◌ौ ◌्"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "। ॥ ॰"
  index: "अ आ इ ई उ ऊ ऍ ए ऐ ऑ ओ औ क ख ग घ च छ ज झ ञ ट ठ ड {ड़} ढ ण त थ द ध न प फ ब भ म य र ल ळ व श ष स ह {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़} {ड़}"
}
sample_text {
  fallback_language: "hi"
}
