id: "brx_Latn"
language: "brx"
script: "Latn"
name: "Bodo, Latin"
sample_text {
  masthead_full: "GgAa"
  masthead_partial: "Ss"
  styles: "G\na\ns\nw\ni\n \ns\nu\nb\nu\nn\ng\n \na\nn\nw\n \nu\nd\na\nn"
  tester: "G\na\ns\nw\ni\n \ns\nu\nb\nu\nn\ng\n \na\nn\nw\n \nu\nd\na\nn\ng\nw\ni\n \nm\na\nn\n \ns\na"
  poster_sm: "G\na\ns\nw\ni\n "
  poster_md: "G\na\ns\nw\ni"
  poster_lg: "G\na"
  specimen_48: "G\na\ns\nw\ni\n \ns\nu\nb\nu\nn\ng\n \na\nn\nw\n \nu\nd\na\nn\ng\nw\ni\n \nm\na\nn\n \ns\na"
  specimen_36: "G\na\ns\nw\ni\n \ns\nu\nb\nu\nn\ng\n \na\nn\nw\n \nu\nd\na\nn\ng\nw\ni\n \nm\na\nn\n \ns\na\nn\nm\na\nn\n \na\nr\nw\n \nm\nw\nn\nt\nh\na\ni\n \nl\na\nn"
  specimen_32: "G\na\ns\nw\ni\n \ns\nu\nb\nu\nn\ng\n \na\nn\nw\n \nu\nd\na\nn\ng\nw\ni\n \nm\na\nn\n \ns\na\nn\nm\na\nn\n \na\nr\nw\n \nm\nw\nn\nt\nh\na\ni\n \nl\na\nn\na\n \nj\nw\nn\nw\nm\n \nl\na\ny\nw\n \n(\nj\na\ny\nw\n)\n.\n "
  specimen_21: "G\na\ns\nw\ni\n \ns\nu\nb\nu\nn\ng\n \na\nn\nw\n \nu\nd\na\nn\ng\nw\ni\n \nm\na\nn\n \ns\na\nn\nm\na\nn\n \na\nr\nw\n \nm\nw\nn\nt\nh\na\ni\n \nl\na\nn\na\n \nj\nw\nn\nw\nm\n \nl\na\ny\nw\n \n(\nj\na\ny\nw\n)\n.\n \nB\ni\ns\nw\nr\nw\n \nm\nw\nj\na\nn\ng\n-\ng\na\nj\nr\ni\n \ns\na\nn\nn\nw\n \nh\na\nn\na\ni\n \ng\nw\nh\nw\n \na\nr\nw\n \ns\nw\nl\nw\n \nd\no\nn\ng\n.\n \nB\ni\ns\nw\nr\nw\n \ng\na\no\nk\nh\nw\nu\nn\nw\n \ng\na\no\n \nb\ni\nd\na\n \np\nh\no"
  specimen_16: "G\na\ns\nw\ni\n \ns\nu\nb\nu\nn\ng\n \na\nn\nw\n \nu\nd\na\nn\ng\nw\ni\n \nm\na\nn\n \ns\na\nn\nm\na\nn\n \na\nr\nw\n \nm\nw\nn\nt\nh\na\ni\n \nl\na\nn\na\n \nj\nw\nn\nw\nm\n \nl\na\ny\nw\n \n(\nj\na\ny\nw\n)\n.\n \nB\ni\ns\nw\nr\nw\n \nm\nw\nj\na\nn\ng\n-\ng\na\nj\nr\ni\n \ns\na\nn\nn\nw\n \nh\na\nn\na\ni\n \ng\nw\nh\nw\n \na\nr\nw\n \ns\nw\nl\nw\n \nd\no\nn\ng\n.\n \nB\ni\ns\nw\nr\nw\n \ng\na\no\nk\nh\nw\nu\nn\nw\n \ng\na\no\n \nb\ni\nd\na\n \np\nh\no\nn\ng\nb\na\ni\n \nb\na\ni\nd\ni\n \nb\na\nh\na\ni\n \nl\na\ni\nn\na\nn\ng\nw\nu\n.\nG\na\ns\nw\ni\n \ns\nu\nb\nu\nn\ng\n \na\nn\nw\n \nu\nd\na\nn\ng\nw\ni\n \nm\na\nn\n \ns\na\nn\nm\na\nn\n \na\nr\nw\n \nm\nw\nn\nt\nh\na\ni\n \nl\na\nn\na\n \nj\nw\nn\nw\nm\n \nl\na\ny\nw\n \n(\nj\na\ny\nw\n)\n.\n \nB\ni\ns\nw\nr\nw\n \nm\nw\nj\na\nn\ng\n-\ng\na\nj\nr\ni\n \ns\na\nn\nn\nw\n \nh\na"
}
