id: "bua"
name: "Buriat"
preferred_name: "Russian Buriat"
autonym: "Буряад"
population: 311788
region: "RU"
script: "Cyrillic"
exemplar_chars {
  base: "A B C Ç D E F G H I J K L M N O Ө P R S Ş T U V X Y Z Ƶ a b c ç d e f g h i j k l m n o ө p r s ş t u v x y z ƶ"
  marks: "◌̧"
}
sample_text {
  fallback_language: "ru"
}
