id: "bum"
language: "bum"
script: "Latn"
name: "Bulu"
population: 1276269
region: "CM"
sample_text {
  masthead_full: "AaBb"
  masthead_partial: "Ii"
  styles: "Eyóñ bia noñ na fili, sosoo ai mvoe bia so"
  tester: "Eyóñ bia noñ na fili ya nyol ai a nsisim ene dzom ya mod ose"
  poster_sm: "Eyóñ bia noñ"
  poster_md: "Eyóñ bia"
  poster_lg: "Abiali"
  specimen_48: "Eyóñ bia noñ na Akōk Memvende Ekuan Elad Meyoñ amem na aluman"
  specimen_36: "Eyóñ bia noñ na abui minnam mbamena ai Ekuan Elad meyoñ mo yebe ovañ ye na si ese ebaala memvende m\'enyiñ ma."
  specimen_32: "Eyóñ bia noñ na fili ya nyol ai a nsisim ene dzom ya mod ose ayi, adzeñe fe, ai na ndimi, tege yene, ebiandi y\'akar so e minsingi ai minyanda a minnam."
  specimen_21: "Eyóñ bia noñ na fili, sosoo ai mvoe bia so bia olugu biave ekokom mod.\nEyóñ bia noñ na fili ya nyol ai a nsisim ene dzom ya mod ose ayi, adzeñe fe, ai na ndimi, tege yene, ebiandi y\'akar so e minsingi ai minyanda a minnam.\nEyóñ bia noñ na ngomena ayian kala enyiñ asu e na bod be za bam nge batibili bo.\nEyóñ bia noñ na fulu mbga etam, fulu anyañ, fulu ediñ ndzo ene mfi asu mie bod ya minnam."
  specimen_16: "Eyóñ bia noñ na fili, sosoo ai mvoe bia so bia olugu biave ekokom mod.\nEyóñ bia noñ na fili ya nyol ai a nsisim ene dzom ya mod ose ayi, adzeñe fe, ai na ndimi, tege yene, ebiandi y\'akar so e minsingi ai minyanda a minnam.\nEyóñ bia noñ na ngomena ayian kala enyiñ asu e na bod be za bam nge batibili bo.\nEyóñ bia noñ na fulu mbga etam, fulu anyañ, fulu ediñ ndzo ene mfi asu mie bod ya minnam.\nEyóñ bia noñ na Akōk Memvende Ekuan Elad Meyoñ amem na aluman asu na enyiñ bod bese etebe etu dzia.\nEyóñ bia noñ na abui minnam mbamena ai Ekuan Elad meyoñ mo yebe ovañ ye na si ese ebaala memvende m\'enyiñ ma."
}
