id: "bwy_Latn"
language: "bwy"
script: "Latn"
name: "Cwi Bwamu, Latin"
sample_text {
  masthead_full: "WwƆɔ"
  masthead_partial: "Ɑɑ"
  styles: "W\nɔ\nɑ\nw\no\n \nɑ\nd\ne\ns\nɑ\nm\nm\nɑ\n \nn\ny\ni\nn\nɑ\nɑ"
  tester: "W\nɔ\nɑ\nw\no\n \nɑ\nd\ne\ns\nɑ\nm\nm\nɑ\n \nn\ny\ni\nn\nɑ\nɑ\n \ns\nɛ\n \nn\nn\ni\np\nɑ\n "
  poster_sm: "W\nɔ\nɑ\nw\no\n "
  poster_md: "W\nɔ\nɑ\nw\no"
  poster_lg: "W\nɔ"
  specimen_48: "W\nɔ\nɑ\nw\no\n \nɑ\nd\ne\ns\nɑ\nm\nm\nɑ\n \nn\ny\ni\nn\nɑ\nɑ\n \ns\nɛ\n \nn\nn\ni\np\nɑ\n "
  specimen_36: "W\nɔ\nɑ\nw\no\n \nɑ\nd\ne\ns\nɑ\nm\nm\nɑ\n \nn\ny\ni\nn\nɑ\nɑ\n \ns\nɛ\n \nn\nn\ni\np\nɑ\n \nɑ\n \nw\nɔ\nw\nɔ\n \nɑ\nh\no\nf\nɑ\nd\ni\n.\n \nW\nɔ\nn\n "
  specimen_32: "W\nɔ\nɑ\nw\no\n \nɑ\nd\ne\ns\nɑ\nm\nm\nɑ\n \nn\ny\ni\nn\nɑ\nɑ\n \ns\nɛ\n \nn\nn\ni\np\nɑ\n \nɑ\n \nw\nɔ\nw\nɔ\n \nɑ\nh\no\nf\nɑ\nd\ni\n.\n \nW\nɔ\nn\n \nn\ny\ni\nn\nɑ\nɑ\n \nw\nɔ\n \nn\ni\nd\ni\n \nn\ne\n \nk\ny"
  specimen_21: "W\nɔ\nɑ\nw\no\n \nɑ\nd\ne\ns\nɑ\nm\nm\nɑ\n \nn\ny\ni\nn\nɑ\nɑ\n \ns\nɛ\n \nn\nn\ni\np\nɑ\n \nɑ\n \nw\nɔ\nw\nɔ\n \nɑ\nh\no\nf\nɑ\nd\ni\n.\n \nW\nɔ\nn\n \nn\ny\ni\nn\nɑ\nɑ\n \nw\nɔ\n \nn\ni\nd\ni\n \nn\ne\n \nk\ny\nɛ\nf\nɑ\n \nk\no\nr\no\n.\n \nW\nɔ\nw\nɔ\n \nɑ\nd\nw\ne\nn\ne\n \nn\ne\n \nɑ\nh\no\nn\ni\nm\n,\n \nn\nɑ\n \nɛ\ns\nɛ\n \ns\nɛ\n \nw\no\nb\nu\n \nw\nɔ\nn\n \nh\no\n \nw\nɔ\nn\n \nh\no\n \ns\nɛ\n \nɑ\nn\nu\nɑ\nn\no\nm\n.\nW\nɔ\nɑ\nw\no\n \nɑ\nd\ne"
  specimen_16: "W\nɔ\nɑ\nw\no\n \nɑ\nd\ne\ns\nɑ\nm\nm\nɑ\n \nn\ny\ni\nn\nɑ\nɑ\n \ns\nɛ\n \nn\nn\ni\np\nɑ\n \nɑ\n \nw\nɔ\nw\nɔ\n \nɑ\nh\no\nf\nɑ\nd\ni\n.\n \nW\nɔ\nn\n \nn\ny\ni\nn\nɑ\nɑ\n \nw\nɔ\n \nn\ni\nd\ni\n \nn\ne\n \nk\ny\nɛ\nf\nɑ\n \nk\no\nr\no\n.\n \nW\nɔ\nw\nɔ\n \nɑ\nd\nw\ne\nn\ne\n \nn\ne\n \nɑ\nh\no\nn\ni\nm\n,\n \nn\nɑ\n \nɛ\ns\nɛ\n \ns\nɛ\n \nw\no\nb\nu\n \nw\nɔ\nn\n \nh\no\n \nw\nɔ\nn\n \nh\no\n \ns\nɛ\n \nɑ\nn\nu\nɑ\nn\no\nm\n.\nW\nɔ\nɑ\nw\no\n \nɑ\nd\ne\ns\nɑ\nm\nm\nɑ\n \nn\ny\ni\nn\nɑ\nɑ\n \ns\nɛ\n \nn\nn\ni\np\nɑ\n \nɑ\n \nw\nɔ\nw\nɔ\n \nɑ\nh\no\nf\nɑ\nd\ni\n.\n \nW\nɔ\nn\n \nn\ny\ni\nn\nɑ\nɑ\n \nw\nɔ\n \nn\ni\nd\ni\n \nn\ne\n \nk\ny\nɛ\nf\nɑ\n \nk\no\nr\no\n.\n \nW\nɔ\nw\nɔ\n \nɑ\nd\nw\ne\nn\ne\n \nn\ne\n \nɑ\nh\no\nn\ni\nm\n,\n \nn\nɑ\n \nɛ\ns\nɛ\n \ns\nɛ\n \nw\no\nb\nu\n \nw\nɔ\nn\n \nh\no\n \nw\nɔ\nn\n \nh\no\n \ns\nɛ"
}
