id: "byh_Deva"
language: "byh"
script: "Deva"
name: "Bhujel, Devanagari"
sample_text {
  masthead_full: "सकतब"
  masthead_partial: "यल"
  styles: "स\nक\n्\nत\n \nब\n्\nय\nा\nक\n्\nत\nी\n \nल\nम\nक\nो\n \nप\n्\nर\nत\nि\nष"
  tester: "स\nक\n्\nत\n \nब\n्\nय\nा\nक\n्\nत\nी\n \nल\nम\nक\nो\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nए\nव\nे\nत\n \nअ\nध"
  poster_sm: "स\nक\n्\nत\n \nब"
  poster_md: "स\nक\n्\nत\n "
  poster_lg: "स\nक"
  specimen_48: "स\nक\n्\nत\n \nब\n्\nय\nा\nक\n्\nत\nी\n \nल\nम\nक\nो\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nए\nव\nे\nत\n \nअ\nध"
  specimen_36: "स\nक\n्\nत\n \nब\n्\nय\nा\nक\n्\nत\nी\n \nल\nम\nक\nो\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nए\nव\nे\nत\n \nअ\nध\nि\nक\nा\nर\nक\nो\n \nआ\nध\nा\nर\nह\nा\nङ\n \nज\nम\n्\nम\nज\nा\nत\n \nस"
  specimen_32: "स\nक\n्\nत\n \nब\n्\nय\nा\nक\n्\nत\nी\n \nल\nम\nक\nो\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nए\nव\nे\nत\n \nअ\nध\nि\nक\nा\nर\nक\nो\n \nआ\nध\nा\nर\nह\nा\nङ\n \nज\nम\n्\nम\nज\nा\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nए\nव\nे\nत\n \nव\nि\nव\nे\nक\n \nल\nे\nव"
  specimen_21: "स\nक\n्\nत\n \nब\n्\nय\nा\nक\n्\nत\nी\n \nल\nम\nक\nो\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nए\nव\nे\nत\n \nअ\nध\nि\nक\nा\nर\nक\nो\n \nआ\nध\nा\nर\nह\nा\nङ\n \nज\nम\n्\nम\nज\nा\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nए\nव\nे\nत\n \nव\nि\nव\nे\nक\n \nल\nे\nव\nे\nत\n \nव\nा\nङ\nो\n \nग\nे\nन\nा\n \nए\nव\nे\nत\n \nआ\nत\n्\nव\nो\nत\n \nध\nे\n \nप\n्\nर\nत\nि\n \nभ\nा\nत\nु\nत\n्\nव\nक\n \nब\n्\nय\nव\nा\nह\nा\nर\n \nर\nा\nम\nै\n \nप\nर\nन\nा\n।\nस\nक\n्\nत\n \nब\n्\nय\nा\nक\n्\nत\nी\n \nल\nम\nक\nो\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nए\nव\nे\nत\n "
  specimen_16: "स\nक\n्\nत\n \nब\n्\nय\nा\nक\n्\nत\nी\n \nल\nम\nक\nो\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nए\nव\nे\nत\n \nअ\nध\nि\nक\nा\nर\nक\nो\n \nआ\nध\nा\nर\nह\nा\nङ\n \nज\nम\n्\nम\nज\nा\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nए\nव\nे\nत\n \nव\nि\nव\nे\nक\n \nल\nे\nव\nे\nत\n \nव\nा\nङ\nो\n \nग\nे\nन\nा\n \nए\nव\nे\nत\n \nआ\nत\n्\nव\nो\nत\n \nध\nे\n \nप\n्\nर\nत\nि\n \nभ\nा\nत\nु\nत\n्\nव\nक\n \nब\n्\nय\nव\nा\nह\nा\nर\n \nर\nा\nम\nै\n \nप\nर\nन\nा\n।\nस\nक\n्\nत\n \nब\n्\nय\nा\nक\n्\nत\nी\n \nल\nम\nक\nो\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nए\nव\nे\nत\n \nअ\nध\nि\nक\nा\nर\nक\nो\n \nआ\nध\nा\nर\nह\nा\nङ\n \nज\nम\n्\nम\nज\nा\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nए\nव\nे\nत\n \nव\nि\nव\nे\nक\n \nल\nे\nव\nे\nत\n \nव\nा\nङ\nो\n \nग\nे\nन\nा\n \nए\nव\nे\nत\n \nआ\nत\n्\nव\nो\nत\n \nध\nे\n \nप\n्\nर\nत\nि\n \nभ\nा\nत\nु\nत\n्\nव\nक\n \nब\n्\nय\nव\nा\nह\nा\nर\n \nर\nा\nम\nै\n \nप\nर\nन\nा\n।\nस\nक\n्\nत\n \nब\n्\nय\nा\nक\n्\nत\nी\n \nल\nम\nक\nो\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nए\nव\nे\nत\n \nअ\nध\nि\nक"
}
