id: "cak_Latn"
language: "cak"
script: "Latn"
name: "Kaqchikel, Central"
sample_text {
  masthead_full: "KkOo"
  masthead_partial: "Nn"
  styles: "K\no\nn\no\nj\ne\nl\n \nr\ni\n \nw\ni\nn\na\nq\ni\n\'\n \nk\na"
  tester: "K\no\nn\no\nj\ne\nl\n \nr\ni\n \nw\ni\nn\na\nq\ni\n\'\n \nk\na\nn\n \nk\na\nl\na\nx\ni\nb\n\'\ne"
  poster_sm: "K\no\nn\no\nj\ne"
  poster_md: "K\no\nn\no\nj"
  poster_lg: "K\no"
  specimen_48: "K\no\nn\no\nj\ne\nl\n \nr\ni\n \nw\ni\nn\na\nq\ni\n\'\n \nk\na\nn\n \nk\na\nl\na\nx\ni\nb\n\'\ne"
  specimen_36: "K\no\nn\no\nj\ne\nl\n \nr\ni\n \nw\ni\nn\na\nq\ni\n\'\n \nk\na\nn\n \nk\na\nl\na\nx\ni\nb\n\'\ne\nn\n \np\ne\n \nr\ni\n \nk\no\nl\no\nt\na\nj\nï\nk\n,\n \nr"
  specimen_32: "K\no\nn\no\nj\ne\nl\n \nr\ni\n \nw\ni\nn\na\nq\ni\n\'\n \nk\na\nn\n \nk\na\nl\na\nx\ni\nb\n\'\ne\nn\n \np\ne\n \nr\ni\n \nk\no\nl\no\nt\na\nj\nï\nk\n,\n \nr\ni\n \nj\nu\nn\na\nn\n \nk\ni\nq\n\'\ni\nj\n,\n \nr\ni\n \nj\nu"
  specimen_21: "K\no\nn\no\nj\ne\nl\n \nr\ni\n \nw\ni\nn\na\nq\ni\n\'\n \nk\na\nn\n \nk\na\nl\na\nx\ni\nb\n\'\ne\nn\n \np\ne\n \nr\ni\n \nk\no\nl\no\nt\na\nj\nï\nk\n,\n \nr\ni\n \nj\nu\nn\na\nn\n \nk\ni\nq\n\'\ni\nj\n,\n \nr\ni\n \nj\nu\nn\na\nn\n \nk\ne\nj\nq\na\nl\ne\nn\n,\n \nj\nu\nn\na\nn\n \nk\ni\nc\nh\n\'\no\nj\ni\nb\n\'\na\nl\n \np\na\n \nk\ni\nk\n\'\na\ns\nl\ne\nn\n,\n \nx\na\n \na\nc\nh\ni\n\'\ne\nl\n \nk\n\'\na\n \nr\ni\n \nk\ni\nk\n\'\no\nj\nl\ne\nn\n,\n \nr\ni\n \nk\ni\nn\no\nj\ni"
  specimen_16: "K\no\nn\no\nj\ne\nl\n \nr\ni\n \nw\ni\nn\na\nq\ni\n\'\n \nk\na\nn\n \nk\na\nl\na\nx\ni\nb\n\'\ne\nn\n \np\ne\n \nr\ni\n \nk\no\nl\no\nt\na\nj\nï\nk\n,\n \nr\ni\n \nj\nu\nn\na\nn\n \nk\ni\nq\n\'\ni\nj\n,\n \nr\ni\n \nj\nu\nn\na\nn\n \nk\ne\nj\nq\na\nl\ne\nn\n,\n \nj\nu\nn\na\nn\n \nk\ni\nc\nh\n\'\no\nj\ni\nb\n\'\na\nl\n \np\na\n \nk\ni\nk\n\'\na\ns\nl\ne\nn\n,\n \nx\na\n \na\nc\nh\ni\n\'\ne\nl\n \nk\n\'\na\n \nr\ni\n \nk\ni\nk\n\'\no\nj\nl\ne\nn\n,\n \nr\ni\n \nk\ni\nn\no\nj\ni\nb\n\'\na\nl\n \nk\ni\nc\nh\na\nj\ni\nn\n \nx\na\n \nt\ni\nk\n\'\na\nm\nu\nn\n \nk\n\'\na\n \nc\nh\ni\n \nn\ni\nm\na\nl\nä\nj\n \nk\no\nn\no\nj\ne\nl\n \nx\nt\ni\nk\na\nj\no\n\'\n \nk\ni\n\'\n.\nK\no\nn\no\nj\ne\nl\n \nr\ni\n \nw\ni\nn\na\nq\ni\n\'\n \nk\na\nn\n \nk\na\nl\na\nx\ni\nb\n\'\ne\nn\n \np\ne\n \nr\ni\n \nk\no\nl\no\nt\na\nj\nï\nk\n,\n \nr\ni\n \nj\nu\nn\na\nn\n \nk\ni\nq\n\'\ni\nj\n,"
}
