id: "cbi_Latn"
language: "cbi"
script: "Latn"
name: "Chachi"
sample_text {
  masthead_full: "NnAa"
  masthead_partial: "Jj"
  styles: "N\na\na\nj\nu\n \nc\nh\na\nc\nh\ni\nl\nl\na\n \nb\na\ni\nn\n "
  tester: "N\na\na\nj\nu\n \nc\nh\na\nc\nh\ni\nl\nl\na\n \nb\na\ni\nn\n \nm\nu\n\'\n \nc\nh\na\nc\nh\ni"
  poster_sm: "N\na\na\nj\nu\n "
  poster_md: "N\na\na\nj\nu"
  poster_lg: "N\na"
  specimen_48: "N\na\na\nj\nu\n \nc\nh\na\nc\nh\ni\nl\nl\na\n \nb\na\ni\nn\n \nm\nu\n\'\n \nc\nh\na\nc\nh\ni"
  specimen_36: "N\na\na\nj\nu\n \nc\nh\na\nc\nh\ni\nl\nl\na\n \nb\na\ni\nn\n \nm\nu\n\'\n \nc\nh\na\nc\nh\ni\nl\nl\na\n \nb\na\ni\nn\n \nn\na\n \nk\na\ny\na\nt\nu\n \nt"
  specimen_32: "N\na\na\nj\nu\n \nc\nh\na\nc\nh\ni\nl\nl\na\n \nb\na\ni\nn\n \nm\nu\n\'\n \nc\nh\na\nc\nh\ni\nl\nl\na\n \nb\na\ni\nn\n \nn\na\n \nk\na\ny\na\nt\nu\n \nt\ni\nc\nh\ni\nb\na\n \nb\nu\nl\nl\na\n \nj\nu\nt\ny\nu\n \nn"
  specimen_21: "N\na\na\nj\nu\n \nc\nh\na\nc\nh\ni\nl\nl\na\n \nb\na\ni\nn\n \nm\nu\n\'\n \nc\nh\na\nc\nh\ni\nl\nl\na\n \nb\na\ni\nn\n \nn\na\n \nk\na\ny\na\nt\nu\n \nt\ni\nc\nh\ni\nb\na\n \nb\nu\nl\nl\na\n \nj\nu\nt\ny\nu\n \nn\na\na\nk\ne\nn\nd\ny\na\n\'\nb\na\n \nk\ne\nn\nu\n \nd\ne\ne\nc\nh\nu\n \nt\na\na\n \nn\na\n \nk\na\ny\na\nm\nu\n \nd\ne\nj\nu\n,\n \nt\ns\ne\nn\nm\ni\nn\ny\na\n,\nn\na\na\nj\nu\n \nj\nu\nñ\nu\n \nb\na\ni\nn\n \nn\ne\n \nt\ns\na\na\nv\ne\n \nt\ni"
  specimen_16: "N\na\na\nj\nu\n \nc\nh\na\nc\nh\ni\nl\nl\na\n \nb\na\ni\nn\n \nm\nu\n\'\n \nc\nh\na\nc\nh\ni\nl\nl\na\n \nb\na\ni\nn\n \nn\na\n \nk\na\ny\na\nt\nu\n \nt\ni\nc\nh\ni\nb\na\n \nb\nu\nl\nl\na\n \nj\nu\nt\ny\nu\n \nn\na\na\nk\ne\nn\nd\ny\na\n\'\nb\na\n \nk\ne\nn\nu\n \nd\ne\ne\nc\nh\nu\n \nt\na\na\n \nn\na\n \nk\na\ny\na\nm\nu\n \nd\ne\nj\nu\n,\n \nt\ns\ne\nn\nm\ni\nn\ny\na\n,\nn\na\na\nj\nu\n \nj\nu\nñ\nu\n \nb\na\ni\nn\n \nn\ne\n \nt\ns\na\na\nv\ne\n \nt\ni\n\'\n,\n \nu\nu\nk\na\nv\ni\nn\nu\n \nj\nu\nt\ny\nu\n \nn\na\na\n,\n \nt\ni\nd\ne\ne\nc\nh\nu\n \nj\nu\nu\nc\nh\ni\n \nb\na\ni\nn\n,\n \nm\nu\nb\na\ni\nn\n \nm\nu\nb\na\ni\nn\n \nt\ns\na\nr\ne\nn\n \nd\ne\nj\nu\nv\ne\n,\n \nt\ns\ne\nn\nm\ni\nn\n \ns\nh\ni\nl\nl\ni\n \np\ne\nn\ns\na\nn\ng\ne\nn\nu\n \np\nu\nd\ne\n \nd\ne\nj\nu\n\'\n.\n \nm\ni\nt\ny\na\n,\n \nt\ns\ne\nn\nr\n)\n1\ni\nn\n "
}
