id: "cbu_Latn"
language: "cbu"
script: "Latn"
name: "Candoshi-Shapra"
sample_text {
  masthead_full: "IiYy"
  masthead_partial: "Tt"
  styles: "I\ny\n \nt\np\no\nt\ns\ni\nn\ni\n \ni\nc\nh\ni\ng\no\nr\no\nn"
  tester: "I\ny\n \nt\np\no\nt\ns\ni\nn\ni\n \ni\nc\nh\ni\ng\no\nr\no\nn\ni\n \nk\ni\ns\n \nt\na\nm\na"
  poster_sm: "I\ny\n \nt\np\no"
  poster_md: "I\ny\n \nt\np"
  poster_lg: "I\ny"
  specimen_48: "I\ny\n \nt\np\no\nt\ns\ni\nn\ni\n \ni\nc\nh\ni\ng\no\nr\no\nn\ni\n \nk\ni\ns\n \nt\na\nm\na"
  specimen_36: "I\ny\n \nt\np\no\nt\ns\ni\nn\ni\n \ni\nc\nh\ni\ng\no\nr\no\nn\ni\n \nk\ni\ns\n \nt\na\nm\na\nm\n \nz\na\nd\nk\ni\nn\ni\n,\n \nv\na\nt\na\nm\n \nt\np\no"
  specimen_32: "I\ny\n \nt\np\no\nt\ns\ni\nn\ni\n \ni\nc\nh\ni\ng\no\nr\no\nn\ni\n \nk\ni\ns\n \nt\na\nm\na\nm\n \nz\na\nd\nk\ni\nn\ni\n,\n \nv\na\nt\na\nm\n \nt\np\no\nt\ns\ni\nn\ni\nv\na\n.\n \nV\na\nt\na\nm\n \ni\nc\nh\ni\ng\no"
  specimen_21: "I\ny\n \nt\np\no\nt\ns\ni\nn\ni\n \ni\nc\nh\ni\ng\no\nr\no\nn\ni\n \nk\ni\ns\n \nt\na\nm\na\nm\n \nz\na\nd\nk\ni\nn\ni\n,\n \nv\na\nt\na\nm\n \nt\np\no\nt\ns\ni\nn\ni\nv\na\n.\n \nV\na\nt\na\nm\n \ni\nc\nh\ni\ng\no\nr\no\nn\ni\n \nm\na\ng\ni\nn\ni\n \nt\na\nr\no\nv\na\n;\n \na\ns\nh\ni\nr\ni\ny\na\n \nc\nh\ni\nn\na\nk\na\nn\ni\ny\na\n.\n \nA\ns\nh\ni\nr\no\nc\nh\na\n,\n \nz\no\nv\na\nl\nl\ni\na\nt\ns\ni\nc\nh\n \nt\na\nm\na\np\na\nr\ni\na\n-\na\ns\nh\ni\nr"
  specimen_16: "I\ny\n \nt\np\no\nt\ns\ni\nn\ni\n \ni\nc\nh\ni\ng\no\nr\no\nn\ni\n \nk\ni\ns\n \nt\na\nm\na\nm\n \nz\na\nd\nk\ni\nn\ni\n,\n \nv\na\nt\na\nm\n \nt\np\no\nt\ns\ni\nn\ni\nv\na\n.\n \nV\na\nt\na\nm\n \ni\nc\nh\ni\ng\no\nr\no\nn\ni\n \nm\na\ng\ni\nn\ni\n \nt\na\nr\no\nv\na\n;\n \na\ns\nh\ni\nr\ni\ny\na\n \nc\nh\ni\nn\na\nk\na\nn\ni\ny\na\n.\n \nA\ns\nh\ni\nr\no\nc\nh\na\n,\n \nz\no\nv\na\nl\nl\ni\na\nt\ns\ni\nc\nh\n \nt\na\nm\na\np\na\nr\ni\na\n-\na\ns\nh\ni\nr\no\ns\n \ns\na\nn\np\na\nt\na\n \nc\nh\ni\nn\na\ng\nt\ns\na\n \na\nt\ni\nn\ni\ny\na\n.\nI\ny\n \nt\np\no\nt\ns\ni\nn\ni\n \ni\nc\nh\ni\ng\no\nr\no\nn\ni\n \nk\ni\ns\n \nt\na\nm\na\nm\n \nz\na\nd\nk\ni\nn\ni\n,\n \nv\na\nt\na\nm\n \nt\np\no\nt\ns\ni\nn\ni\nv\na\n.\n \nV\na\nt\na\nm\n \ni\nc\nh\ni\ng\no\nr\no\nn\ni\n \nm\na\ng\ni\nn\ni\n \nt\na\nr\no\nv\na\n;\n \na\ns\nh\ni\nr\ni"
}
