id: "ccp_Beng"
language: "ccp"
script: "Beng"
name: "Chakma, Bengali"
population: 729137
region: "BD"
region: "IN"
exemplar_chars {
  base: "𑄀 𑄁 𑄂 𑄃 𑄄 𑄅 𑄆 𑄇 𑄈 𑄉 𑄊 𑄋 𑄌 𑄍 𑄎 𑄏 𑄐 𑄑 𑄒 𑄓 𑄔 𑄕 𑄖 𑄗 𑄘 𑄙 𑄚 𑄛 𑄜 𑄝 𑄞 𑄟 𑄠 𑄡 𑄢 𑄣 𑄤 𑄥 𑄦 𑄧 𑄨 𑄩 𑄪 𑄫 𑄬 𑄭 𑄮 𑄯 𑄰 𑄱 𑄲 𑄳 𑄴"
  auxiliary: ""
  numerals: "- ‑ , . % ‰ + 𑄶 𑄷 𑄸 𑄹 𑄺 𑄻 𑄼 𑄽 𑄾 𑄿"
  punctuation: "- ‐ ‑ – — , ; : ! ? 𑅃 . … 𑅁 𑅂 𑅀 \' ‘ ’ \" “ ” ( ) [ ] § @ * / & # † ‡ ′ ″"
  index: "𑄃 𑄄 𑄅 𑄆 𑄇 𑄈 𑄉 𑄊 𑄋 𑄌 𑄍 𑄎 𑄏 𑄐 𑄑 𑄒 𑄓 𑄔 𑄕 𑄖 𑄗 𑄘 𑄙 𑄚 𑄛 𑄜 𑄝 𑄞 𑄟 𑄠 𑄡 𑄢 𑄣 𑄤 𑄥 𑄦"
}
sample_text {
  masthead_full: "বগমন"
  masthead_partial: "ষস"
  styles: "বেগ মানুষসুন স্বাধীনগরি এক্কই মর্যাদা আর অধিকার লনে লই জন্ম"
  tester: "বেগ মানুষসুন স্বাধীনগরি এক্কই মর্যাদা আর অধিকার লনে লই জন্ম অন। তারার বিবেক বুদ্ধি বেক্কানি"
  poster_sm: "বেগ মানুষসুন স্বাধীনগরি"
  poster_md: "বেগ মানুষসুন"
  poster_lg: "মানুষসুন"
  specimen_48: "বেগ মানুষসুন স্বাধীনগরি এক্কই মর্যাদা আর অধিকার লনে লই জন্ম অন। তারার"
  specimen_36: "বেগ মানুষসুন স্বাধীনগরি এক্কই মর্যাদা আর অধিকার লনে লই জন্ম অন। তারার বিবেক বুদ্ধি বেক্কানি আগে। সেনত্তে আমার বেক্কুনেল্লেই দোল চিত্তলই সংপরানা উচিৎ।"
  specimen_32: "বেগ মানুষসুন স্বাধীনগরি এক্কই মর্যাদা আর অধিকার লনে লই জন্ম অন। তারার বিবেক বুদ্ধি বেক্কানি আগে। সেনত্তে আমার বেক্কুনেল্লেই দোল চিত্তলই সংপরানা উচিৎ।"
  specimen_21: "বেগ মানুষসুন স্বাধীনগরি এক্কই মর্যাদা আর অধিকার লনে লই জন্ম অন। তারার বিবেক বুদ্ধি বেক্কানি আগে। সেনত্তে আমার বেক্কুনেল্লেই দোল চিত্তলই সংপরানা উচিৎ।\nবেগ মানুষসুন স্বাধীনগরি এক্কই মর্যাদা আর অধিকার লনে লই জন্ম অন। তারার বিবেক বুদ্ধি বেক্কানি আগে। সেনত্তে আমার বেক্কুনেল্লেই দোল চিত্তলই সংপরানা উচিৎ।\nবেগ মানুষসুন স্বাধীনগরি এক্কই মর্যাদা আর অধিকার লনে লই জন্ম অন। তারার বিবেক বুদ্ধি বেক্কানি আগে। সেনত্তে আমার বেক্কুনেল্লেই দোল চিত্তলই সংপরানা উচিৎ।"
  specimen_16: "বেগ মানুষসুন স্বাধীনগরি এক্কই মর্যাদা আর অধিকার লনে লই জন্ম অন। তারার বিবেক বুদ্ধি বেক্কানি আগে। সেনত্তে আমার বেক্কুনেল্লেই দোল চিত্তলই সংপরানা উচিৎ।\nবেগ মানুষসুন স্বাধীনগরি এক্কই মর্যাদা আর অধিকার লনে লই জন্ম অন। তারার বিবেক বুদ্ধি বেক্কানি আগে। সেনত্তে আমার বেক্কুনেল্লেই দোল চিত্তলই সংপরানা উচিৎ।\nবেগ মানুষসুন স্বাধীনগরি এক্কই মর্যাদা আর অধিকার লনে লই জন্ম অন। তারার বিবেক বুদ্ধি বেক্কানি আগে। সেনত্তে আমার বেক্কুনেল্লেই দোল চিত্তলই সংপরানা উচিৎ।\nবেগ মানুষসুন স্বাধীনগরি এক্কই মর্যাদা আর অধিকার লনে লই জন্ম অন। তারার বিবেক বুদ্ধি বেক্কানি আগে। সেনত্তে আমার বেক্কুনেল্লেই দোল চিত্তলই সংপরানা উচিৎ।\nবেগ মানুষসুন স্বাধীনগরি এক্কই মর্যাদা আর অধিকার লনে লই জন্ম অন। তারার বিবেক বুদ্ধি বেক্কানি আগে। সেনত্তে আমার বেক্কুনেল্লেই দোল চিত্তলই সংপরানা উচিৎ।\nবেগ মানুষসুন স্বাধীনগরি এক্কই মর্যাদা আর অধিকার লনে লই জন্ম অন। তারার বিবেক বুদ্ধি বেক্কানি আগে। সেনত্তে আমার বেক্কুনেল্লেই দোল চিত্তলই সংপরানা উচিৎ।"
}
