id: "cfm_Latn"
language: "cfm"
script: "Latn"
name: "Chin, Falam"
sample_text {
  masthead_full: "MmIi"
  masthead_partial: "Kk"
  styles: "M\ni\nk\ni\np\n \ni\nn\n \nb\na\nn\ng\nr\ne\np\n \ni\ni\n \nz"
  tester: "M\ni\nk\ni\np\n \ni\nn\n \nb\na\nn\ng\nr\ne\np\n \ni\ni\n \nz\na\nl\ne\nn\n \nn\na\nk\n \nl"
  poster_sm: "M\ni\nk\ni\np\n "
  poster_md: "M\ni\nk\ni\np"
  poster_lg: "M\ni"
  specimen_48: "M\ni\nk\ni\np\n \ni\nn\n \nb\na\nn\ng\nr\ne\np\n \ni\ni\n \nz\na\nl\ne\nn\n \nn\na\nk\n \nl"
  specimen_36: "M\ni\nk\ni\np\n \ni\nn\n \nb\na\nn\ng\nr\ne\np\n \ni\ni\n \nz\na\nl\ne\nn\n \nn\na\nk\n \nl\ne\n \ns\nu\nn\nl\na\nw\ni\nh\n \nn\na\nk\n \nt\nh\na\nw\nn"
  specimen_32: "M\ni\nk\ni\np\n \ni\nn\n \nb\na\nn\ng\nr\ne\np\n \ni\ni\n \nz\na\nl\ne\nn\n \nn\na\nk\n \nl\ne\n \ns\nu\nn\nl\na\nw\ni\nh\n \nn\na\nk\n \nt\nh\na\nw\nn\n,\n \nb\na\nn\ng\nr\ne\np\n \ni\nn\n \nc\no\nv\no\n \nn\ne"
  specimen_21: "M\ni\nk\ni\np\n \ni\nn\n \nb\na\nn\ng\nr\ne\np\n \ni\ni\n \nz\na\nl\ne\nn\n \nn\na\nk\n \nl\ne\n \ns\nu\nn\nl\na\nw\ni\nh\n \nn\na\nk\n \nt\nh\na\nw\nn\n,\n \nb\na\nn\ng\nr\ne\np\n \ni\nn\n \nc\no\nv\no\n \nn\ne\ni\n \ni\nn\n,\n \na\ns\nu\na\nk\n \nm\ni\n \nk\na\nn\n \ns\ni\n.\n \nA\nn\nm\na\nh\n \ni\nn\n \nh\nl\ne\ni\nd\na\nn\n \nt\nh\ne\ni\n \nn\na\nk\n \nf\ni\nm\n \nn\na\nk\n \nl\ne\n \nn\nu\nn\nc\na\nn\n \nn\ne\ni\nh\n \nt\nh\ne\ni\n \nn\na\nk\n "
  specimen_16: "M\ni\nk\ni\np\n \ni\nn\n \nb\na\nn\ng\nr\ne\np\n \ni\ni\n \nz\na\nl\ne\nn\n \nn\na\nk\n \nl\ne\n \ns\nu\nn\nl\na\nw\ni\nh\n \nn\na\nk\n \nt\nh\na\nw\nn\n,\n \nb\na\nn\ng\nr\ne\np\n \ni\nn\n \nc\no\nv\no\n \nn\ne\ni\n \ni\nn\n,\n \na\ns\nu\na\nk\n \nm\ni\n \nk\na\nn\n \ns\ni\n.\n \nA\nn\nm\na\nh\n \ni\nn\n \nh\nl\ne\ni\nd\na\nn\n \nt\nh\ne\ni\n \nn\na\nk\n \nf\ni\nm\n \nn\na\nk\n \nl\ne\n \nn\nu\nn\nc\na\nn\n \nn\ne\ni\nh\n \nt\nh\ne\ni\n \nn\na\nk\n \nr\nu\na\nh\n \nn\na\nk\n \nn\ne\ni\n \ni\ni\n,\n \np\na\nk\nh\na\nt\n \nl\ne\n \np\na\nk\nh\na\nt\n \nd\nu\nh\n \nd\na\nw\nt\n \nn\na\nk\n,\n \np\na\nw\nl\n \na\nw\nk\n \nn\na\nk\n \nn\ne\ni\n \nd\ni\nn\ng\n \na\ns\ni\n.\nM\ni\nk\ni\np\n \ni\nn\n \nb\na\nn\ng\nr\ne\np\n \ni\ni\n \nz\na\nl\ne\nn\n \nn\na\nk\n \nl\ne\n \ns\nu\nn\nl\na\nw\ni\nh\n \nn\na\nk\n \nt\nh\na\nw\nn\n,\n "
}
