id: "chj_Latn"
language: "chj"
script: "Latn"
name: "Chinantec, Ojitlán"
sample_text {
  masthead_full: "LlAa"
  masthead_partial: "Jj"
  styles: "L\na\n \nj\nu\nu\n \nd\ns\na\n \nl\nu\n \ns\ni\nä\n \n–\nD\ns"
  tester: "L\na\n \nj\nu\nu\n \nd\ns\na\n \nl\nu\n \ns\ni\nä\n \n–\nD\ns\na\n \nk\nö\n \nñ\ni\n \nb\na"
  poster_sm: "L\na\n \nj\nu\nu"
  poster_md: "L\na\n \nj\nu"
  poster_lg: "L\na"
  specimen_48: "L\na\n \nj\nu\nu\n \nd\ns\na\n \nl\nu\n \ns\ni\nä\n \n–\nD\ns\na\n \nk\nö\n \nñ\ni\n \nb\na"
  specimen_36: "L\na\n \nj\nu\nu\n \nd\ns\na\n \nl\nu\n \ns\ni\nä\n \n–\nD\ns\na\n \nk\nö\n \nñ\ni\n \nb\na\n \nd\ns\na\n,\n \nn\ní\na\n \nk\nö\n \nn\ni\n\'\n \nb\na\n \nn"
  specimen_32: "L\na\n \nj\nu\nu\n \nd\ns\na\n \nl\nu\n \ns\ni\nä\n \n–\nD\ns\na\n \nk\nö\n \nñ\ni\n \nb\na\n \nd\ns\na\n,\n \nn\ní\na\n \nk\nö\n \nn\ni\n\'\n \nb\na\n \nn\na\n \nl\nu\n\'\n \nd\ns\na\n \ne\n \nd\ns\na\n \nt\nï\n \né\n "
  specimen_21: "L\na\n \nj\nu\nu\n \nd\ns\na\n \nl\nu\n \ns\ni\nä\n \n–\nD\ns\na\n \nk\nö\n \nñ\ni\n \nb\na\n \nd\ns\na\n,\n \nn\ní\na\n \nk\nö\n \nn\ni\n\'\n \nb\na\n \nn\na\n \nl\nu\n\'\n \nd\ns\na\n \ne\n \nd\ns\na\n \nt\nï\n \né\n \nl\ni\n \nj\nn\ni\na\n\'\n \nr\no\nö\n\'\n.\nL\na\n \nj\nu\nu\n \nd\ns\na\n \nl\nu\n \ns\ni\nä\n \n–\nD\ns\na\n \nk\nö\n \nñ\ni\n \nb\na\n \nd\ns\na\n,\n \nn\ní\na\n \nk\nö\n \nn\ni\n\'\n \nb\na\n \nn\na\n \nl\nu\n\'\n \nd\ns\na\n \ne\n \nd\ns\na\n \nt"
  specimen_16: "L\na\n \nj\nu\nu\n \nd\ns\na\n \nl\nu\n \ns\ni\nä\n \n–\nD\ns\na\n \nk\nö\n \nñ\ni\n \nb\na\n \nd\ns\na\n,\n \nn\ní\na\n \nk\nö\n \nn\ni\n\'\n \nb\na\n \nn\na\n \nl\nu\n\'\n \nd\ns\na\n \ne\n \nd\ns\na\n \nt\nï\n \né\n \nl\ni\n \nj\nn\ni\na\n\'\n \nr\no\nö\n\'\n.\nL\na\n \nj\nu\nu\n \nd\ns\na\n \nl\nu\n \ns\ni\nä\n \n–\nD\ns\na\n \nk\nö\n \nñ\ni\n \nb\na\n \nd\ns\na\n,\n \nn\ní\na\n \nk\nö\n \nn\ni\n\'\n \nb\na\n \nn\na\n \nl\nu\n\'\n \nd\ns\na\n \ne\n \nd\ns\na\n \nt\nï\n \né\n \nl\ni\n \nj\nn\ni\na\n\'\n \nr\no\nö\n\'\n.\nL\na\n \nj\nu\nu\n \nd\ns\na\n \nl\nu\n \ns\ni\nä\n \n–\nD\ns\na\n \nk\nö\n \nñ\ni\n \nb\na\n \nd\ns\na\n,\n \nn\ní\na\n \nk\nö\n \nn\ni\n\'\n \nb\na\n \nn\na\n \nl\nu\n\'\n \nd\ns\na\n \ne\n \nd\ns\na\n \nt\nï\n \né\n \nl\ni\n \nj\nn\ni\na\n\'\n \nr\no\nö\n\'\n.\nL\na\n \nj\nu\nu\n \nd\ns\na\n \nl\nu\n \ns\ni\nä\n \n–\nD\ns\na\n \nk\nö\n "
}
