id: "cjk_Latn"
language: "cjk"
script: "Latn"
name: "Chokwe"
sample_text {
  masthead_full: "MmWw"
  masthead_partial: "Ee"
  styles: "M\nw\ne\ns\ne\n \ny\no\nz\ne\n \nm\na\ns\ne\nm\nu\nk\na\n \nk"
  tester: "M\nw\ne\ns\ne\n \ny\no\nz\ne\n \nm\na\ns\ne\nm\nu\nk\na\n \nk\na\nt\ne\nl\na\n \nu\nk\nu\nl"
  poster_sm: "M\nw\ne\ns\ne\n "
  poster_md: "M\nw\ne\ns\ne"
  poster_lg: "M\nw"
  specimen_48: "M\nw\ne\ns\ne\n \ny\no\nz\ne\n \nm\na\ns\ne\nm\nu\nk\na\n \nk\na\nt\ne\nl\na\n \nu\nk\nu\nl"
  specimen_36: "M\nw\ne\ns\ne\n \ny\no\nz\ne\n \nm\na\ns\ne\nm\nu\nk\na\n \nk\na\nt\ne\nl\na\n \nu\nk\nu\nl\nu\nn\ng\nu\nn\ng\na\n \nu\nl\ne\nn\ng\nu\nn\ng\na\n \nu\nl"
  specimen_32: "M\nw\ne\ns\ne\n \ny\no\nz\ne\n \nm\na\ns\ne\nm\nu\nk\na\n \nk\na\nt\ne\nl\na\n \nu\nk\nu\nl\nu\nn\ng\nu\nn\ng\na\n \nu\nl\ne\nn\ng\nu\nn\ng\na\n \nu\nl\ne\nm\nu\n \nn\ny\ni\n \nv\nu\nm\nb\ni\n \ne\ns\nw\ne\n \nc"
  specimen_21: "M\nw\ne\ns\ne\n \ny\no\nz\ne\n \nm\na\ns\ne\nm\nu\nk\na\n \nk\na\nt\ne\nl\na\n \nu\nk\nu\nl\nu\nn\ng\nu\nn\ng\na\n \nu\nl\ne\nn\ng\nu\nn\ng\na\n \nu\nl\ne\nm\nu\n \nn\ny\ni\n \nv\nu\nm\nb\ni\n \ne\ns\nw\ne\n \nc\ni\n \nm\nw\ni\nk\nh\na\n.\n \nE\ns\nw\ne\n \nk\na\nl\ni\nn\ng\ni\nl\ne\n \nk\nu\np\nw\na\n \nn\ny\ni\n \nu\ns\na\nm\nb\ne\n \nn\ny\ni\n \nm\na\nn\ng\na\nn\na\n \nn\ny\ni\n \nk\nu\nh\na\ns\na\n \nk\nu\nl\ni\nm\ni\nk\na\n \nn\ny\nu\nm\nw\ne"
  specimen_16: "M\nw\ne\ns\ne\n \ny\no\nz\ne\n \nm\na\ns\ne\nm\nu\nk\na\n \nk\na\nt\ne\nl\na\n \nu\nk\nu\nl\nu\nn\ng\nu\nn\ng\na\n \nu\nl\ne\nn\ng\nu\nn\ng\na\n \nu\nl\ne\nm\nu\n \nn\ny\ni\n \nv\nu\nm\nb\ni\n \ne\ns\nw\ne\n \nc\ni\n \nm\nw\ni\nk\nh\na\n.\n \nE\ns\nw\ne\n \nk\na\nl\ni\nn\ng\ni\nl\ne\n \nk\nu\np\nw\na\n \nn\ny\ni\n \nu\ns\na\nm\nb\ne\n \nn\ny\ni\n \nm\na\nn\ng\na\nn\na\n \nn\ny\ni\n \nk\nu\nh\na\ns\na\n \nk\nu\nl\ni\nm\ni\nk\na\n \nn\ny\nu\nm\nw\ne\n \nn\ny\ni\n \nm\nu\nk\nw\no\n \nn\ny\ni\n \nk\nu\nl\ni\nt\na\n \nn\ny\ni\n \nm\nb\nu\nn\ng\ne\n \ny\na\n \nu\nl\ne\nm\nu\n \nw\na\n \nu\nt\nu\n.\nM\nw\ne\ns\ne\n \ny\no\nz\ne\n \nm\na\ns\ne\nm\nu\nk\na\n \nk\na\nt\ne\nl\na\n \nu\nk\nu\nl\nu\nn\ng\nu\nn\ng\na\n \nu\nl\ne\nn\ng\nu\nn\ng\na\n \nu\nl\ne\nm\nu\n \nn\ny\ni\n \nv\nu\nm\nb\ni\n \ne\ns\nw\ne\n \nc\ni\n \nm\nw\ni\nk"
}
