id: "ckt_Cyrl"
language: "ckt"
script: "Cyrl"
name: "Chukot"
autonym: "Ԓыгъоравэтԓьэн"
population: 0
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я Ё Ӄ Ӈ Ԓ а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я ё ӄ ӈ ԓ ’"
  marks: "◌̆ ◌̈"
}
