id: "cni_Latn"
language: "cni"
script: "Latn"
name: "Asháninka"
sample_text {
  masthead_full: "AaQq"
  masthead_partial: "Uu"
  styles: "A\nq\nu\ne\nm\np\ne\nt\na\nv\na\nc\na\na\nj\ne\ni\nt\na\n \nm"
  tester: "A\nq\nu\ne\nm\np\ne\nt\na\nv\na\nc\na\na\nj\ne\ni\nt\na\n \nm\na\na\nr\no\nn\ni\n \na\nt\ni"
  poster_sm: "A\nq\nu\ne\nm\np"
  poster_md: "A\nq\nu\ne\nm"
  poster_lg: "A\nq"
  specimen_48: "A\nq\nu\ne\nm\np\ne\nt\na\nv\na\nc\na\na\nj\ne\ni\nt\na\n \nm\na\na\nr\no\nn\ni\n \na\nt\ni"
  specimen_36: "A\nq\nu\ne\nm\np\ne\nt\na\nv\na\nc\na\na\nj\ne\ni\nt\na\n \nm\na\na\nr\no\nn\ni\n \na\nt\ni\nr\ni\n.\n \nT\ni\nm\na\nt\ns\ni\n \na\nq\nu\ne\nn\nq\nu\ne"
  specimen_32: "A\nq\nu\ne\nm\np\ne\nt\na\nv\na\nc\na\na\nj\ne\ni\nt\na\n \nm\na\na\nr\no\nn\ni\n \na\nt\ni\nr\ni\n.\n \nT\ni\nm\na\nt\ns\ni\n \na\nq\nu\ne\nn\nq\nu\ne\ns\nh\ni\nr\ne\nj\ne\ni\nt\na\nn\nt\na\nr\ni\n \nm\na\na\nr"
  specimen_21: "A\nq\nu\ne\nm\np\ne\nt\na\nv\na\nc\na\na\nj\ne\ni\nt\na\n \nm\na\na\nr\no\nn\ni\n \na\nt\ni\nr\ni\n.\n \nT\ni\nm\na\nt\ns\ni\n \na\nq\nu\ne\nn\nq\nu\ne\ns\nh\ni\nr\ne\nj\ne\ni\nt\na\nn\nt\na\nr\ni\n \nm\na\na\nr\no\nn\ni\n,\n \nt\ni\nm\na\nt\ns\ni\n \na\nm\ne\nj\ne\ni\nt\na\nr\ni\n,\n \na\ny\no\nj\ne\ni\nt\ni\n \np\na\ni\nt\na\nr\ni\nc\na\n \no\nc\na\nm\ne\ne\nt\ns\na\nt\ni\n \na\nn\nt\na\nj\ne\ni\nt\ni\nr\ni\n:\n \nt\ne\n \no\nn\nc\na\nm\ne\ne\nt\ns\na"
  specimen_16: "A\nq\nu\ne\nm\np\ne\nt\na\nv\na\nc\na\na\nj\ne\ni\nt\na\n \nm\na\na\nr\no\nn\ni\n \na\nt\ni\nr\ni\n.\n \nT\ni\nm\na\nt\ns\ni\n \na\nq\nu\ne\nn\nq\nu\ne\ns\nh\ni\nr\ne\nj\ne\ni\nt\na\nn\nt\na\nr\ni\n \nm\na\na\nr\no\nn\ni\n,\n \nt\ni\nm\na\nt\ns\ni\n \na\nm\ne\nj\ne\ni\nt\na\nr\ni\n,\n \na\ny\no\nj\ne\ni\nt\ni\n \np\na\ni\nt\na\nr\ni\nc\na\n \no\nc\na\nm\ne\ne\nt\ns\na\nt\ni\n \na\nn\nt\na\nj\ne\ni\nt\ni\nr\ni\n:\n \nt\ne\n \no\nn\nc\na\nm\ne\ne\nt\ns\na\nt\ne\nj\ni\n \ni\nn\nt\ns\na\nn\ne\na\np\ni\nt\ns\na\nj\ne\ni\nt\ne\ne\nr\no\n \ni\nt\ns\ni\np\na\np\ne\ne\n.\n \nT\ne\n \no\nn\nc\na\nm\ne\ne\nt\ns\na\nt\ne\nj\ni\n \ni\nm\np\ne\nr\na\nn\na\nj\ne\ni\nt\ne\ne\n,\n \nt\ne\n \no\nn\nc\na\nm\ne\ne\nt\ns\na\nt\ne\nj\ni\n \ni\nr\no\na\ns\nh\ni\nn\no\nn\nc\na\na\nj\ne\ni\nt\ne\ne\n,\n \ni\nr\no\ni\nn\nt\ni\n \no\nc\na\nm\ne\ne\nt"
}
