id: "cop_Copt"
language: "cop"
script: "Copt"
name: "Coptic, Coptic"
population: 0
region: "EG"
sample_text {
  masthead_full: "ⲤⲥⲞⲟ"
  masthead_partial: "Ⲩⲩ"
  styles: "ⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ ⲛⲓⲙ ⲉⲩϣⲏϣ ⲉ ⲛⲉⲩⲉⲣⲏⲩ ϩⲛ ⲟⲩⲇⲓⲕⲁⲓⲟⲥⲩⲛⲏ"
  tester: "ⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ ⲛⲓⲙ ⲉⲩϣⲏϣ ⲉ ⲛⲉⲩⲉⲣⲏⲩ ϩⲛ ⲟⲩⲇⲓⲕⲁⲓⲟⲥⲩⲛⲏ. ⲟⲩⲛ ϭⲟⲙ ⲙⲙⲟⲩ"
  poster_sm: "ⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ"
  poster_md: "ⲥⲟⲩⲙⲟⲥⲉ"
  poster_lg: "ⲥⲟⲩⲙⲟⲥⲉ"
  specimen_48: "ⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ ⲛⲓⲙ ⲉⲩϣⲏϣ ⲉ ⲛⲉⲩⲉⲣⲏⲩ ϩⲛ ⲟⲩⲇⲓⲕⲁⲓⲟⲥⲩⲛⲏ. ⲟⲩⲛ"
  specimen_36: "ⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ ⲛⲓⲙ ⲉⲩϣⲏϣ ⲉ ⲛⲉⲩⲉⲣⲏⲩ ϩⲛ ⲟⲩⲇⲓⲕⲁⲓⲟⲥⲩⲛⲏ. ⲟⲩⲛ ϭⲟⲙ ⲙⲙⲟⲩ ⲉⲧⲣⲉⲩⲙⲉⲉⲩⲉ ⲁⲩⲱ ϣϣⲉ ⲉⲧⲣⲉⲩⲣⲙⲛⲧⲙⲁⲓⲥⲟⲛ."
  specimen_32: "ⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ ⲛⲓⲙ ⲉⲩϣⲏϣ ⲉ ⲛⲉⲩⲉⲣⲏⲩ ϩⲛ ⲟⲩⲇⲓⲕⲁⲓⲟⲥⲩⲛⲏ. ⲟⲩⲛ ϭⲟⲙ ⲙⲙⲟⲩ ⲉⲧⲣⲉⲩⲙⲉⲉⲩⲉ ⲁⲩⲱ ϣϣⲉ ⲉⲧⲣⲉⲩⲣⲙⲛⲧⲙⲁⲓⲥⲟⲛ."
  specimen_21: "ⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ ⲛⲓⲙ ⲉⲩϣⲏϣ ⲉ ⲛⲉⲩⲉⲣⲏⲩ ϩⲛ ⲟⲩⲇⲓⲕⲁⲓⲟⲥⲩⲛⲏ. ⲟⲩⲛ ϭⲟⲙ ⲙⲙⲟⲩ ⲉⲧⲣⲉⲩⲙⲉⲉⲩⲉ ⲁⲩⲱ ϣϣⲉ ⲉⲧⲣⲉⲩⲣⲙⲛⲧⲙⲁⲓⲥⲟⲛ.\nⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ ⲛⲓⲙ ⲉⲩϣⲏϣ ⲉ ⲛⲉⲩⲉⲣⲏⲩ ϩⲛ ⲟⲩⲇⲓⲕⲁⲓⲟⲥⲩⲛⲏ. ⲟⲩⲛ ϭⲟⲙ ⲙⲙⲟⲩ ⲉⲧⲣⲉⲩⲙⲉⲉⲩⲉ ⲁⲩⲱ ϣϣⲉ ⲉⲧⲣⲉⲩⲣⲙⲛⲧⲙⲁⲓⲥⲟⲛ.\nⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ ⲛⲓⲙ ⲉⲩϣⲏϣ ⲉ ⲛⲉⲩⲉⲣⲏⲩ ϩⲛ ⲟⲩⲇⲓⲕⲁⲓⲟⲥⲩⲛⲏ. ⲟⲩⲛ ϭⲟⲙ ⲙⲙⲟⲩ ⲉⲧⲣⲉⲩⲙⲉⲉⲩⲉ ⲁⲩⲱ ϣϣⲉ ⲉⲧⲣⲉⲩⲣⲙⲛⲧⲙⲁⲓⲥⲟⲛ.\nⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ ⲛⲓⲙ ⲉⲩϣⲏϣ ⲉ ⲛⲉⲩⲉⲣⲏⲩ ϩⲛ ⲟⲩⲇⲓⲕⲁⲓⲟⲥⲩⲛⲏ. ⲟⲩⲛ ϭⲟⲙ ⲙⲙⲟⲩ ⲉⲧⲣⲉⲩⲙⲉⲉⲩⲉ ⲁⲩⲱ ϣϣⲉ ⲉⲧⲣⲉⲩⲣⲙⲛⲧⲙⲁⲓⲥⲟⲛ."
  specimen_16: "ⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ ⲛⲓⲙ ⲉⲩϣⲏϣ ⲉ ⲛⲉⲩⲉⲣⲏⲩ ϩⲛ ⲟⲩⲇⲓⲕⲁⲓⲟⲥⲩⲛⲏ. ⲟⲩⲛ ϭⲟⲙ ⲙⲙⲟⲩ ⲉⲧⲣⲉⲩⲙⲉⲉⲩⲉ ⲁⲩⲱ ϣϣⲉ ⲉⲧⲣⲉⲩⲣⲙⲛⲧⲙⲁⲓⲥⲟⲛ.\nⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ ⲛⲓⲙ ⲉⲩϣⲏϣ ⲉ ⲛⲉⲩⲉⲣⲏⲩ ϩⲛ ⲟⲩⲇⲓⲕⲁⲓⲟⲥⲩⲛⲏ. ⲟⲩⲛ ϭⲟⲙ ⲙⲙⲟⲩ ⲉⲧⲣⲉⲩⲙⲉⲉⲩⲉ ⲁⲩⲱ ϣϣⲉ ⲉⲧⲣⲉⲩⲣⲙⲛⲧⲙⲁⲓⲥⲟⲛ.\nⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ ⲛⲓⲙ ⲉⲩϣⲏϣ ⲉ ⲛⲉⲩⲉⲣⲏⲩ ϩⲛ ⲟⲩⲇⲓⲕⲁⲓⲟⲥⲩⲛⲏ. ⲟⲩⲛ ϭⲟⲙ ⲙⲙⲟⲩ ⲉⲧⲣⲉⲩⲙⲉⲉⲩⲉ ⲁⲩⲱ ϣϣⲉ ⲉⲧⲣⲉⲩⲣⲙⲛⲧⲙⲁⲓⲥⲟⲛ.\nⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ ⲛⲓⲙ ⲉⲩϣⲏϣ ⲉ ⲛⲉⲩⲉⲣⲏⲩ ϩⲛ ⲟⲩⲇⲓⲕⲁⲓⲟⲥⲩⲛⲏ. ⲟⲩⲛ ϭⲟⲙ ⲙⲙⲟⲩ ⲉⲧⲣⲉⲩⲙⲉⲉⲩⲉ ⲁⲩⲱ ϣϣⲉ ⲉⲧⲣⲉⲩⲣⲙⲛⲧⲙⲁⲓⲥⲟⲛ.\nⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ ⲛⲓⲙ ⲉⲩϣⲏϣ ⲉ ⲛⲉⲩⲉⲣⲏⲩ ϩⲛ ⲟⲩⲇⲓⲕⲁⲓⲟⲥⲩⲛⲏ. ⲟⲩⲛ ϭⲟⲙ ⲙⲙⲟⲩ ⲉⲧⲣⲉⲩⲙⲉⲉⲩⲉ ⲁⲩⲱ ϣϣⲉ ⲉⲧⲣⲉⲩⲣⲙⲛⲧⲙⲁⲓⲥⲟⲛ.\nⲥⲟⲩⲙⲟⲥⲉ ⲣⲱⲙⲉ ⲛⲓⲙ ⲉⲩϣⲏϣ ⲉ ⲛⲉⲩⲉⲣⲏⲩ ϩⲛ ⲟⲩⲇⲓⲕⲁⲓⲟⲥⲩⲛⲏ. ⲟⲩⲛ ϭⲟⲙ ⲙⲙⲟⲩ ⲉⲧⲣⲉⲩⲙⲉⲉⲩⲉ ⲁⲩⲱ ϣϣⲉ ⲉⲧⲣⲉⲩⲣⲙⲛⲧⲙⲁⲓⲥⲟⲛ."
}
historical: true
