id: "cot_Latn"
language: "cot"
script: "Latn"
name: "Caquinte"
sample_text {
  masthead_full: "AaQq"
  masthead_partial: "Uu"
  styles: "A\nq\nu\ne\nj\ne\nt\na\nv\na\nc\na\na\nj\ni\na\nc\na\n \nm\na"
  tester: "A\nq\nu\ne\nj\ne\nt\na\nv\na\nc\na\na\nj\ni\na\nc\na\n \nm\na\na\ns\na\nn\no\n \nc\na\nq\nu"
  poster_sm: "A\nq\nu\ne\nj\ne"
  poster_md: "A\nq\nu\ne\nj"
  poster_lg: "A\nq"
  specimen_48: "A\nq\nu\ne\nj\ne\nt\na\nv\na\nc\na\na\nj\ni\na\nc\na\n \nm\na\na\ns\na\nn\no\n \nc\na\nq\nu"
  specimen_36: "A\nq\nu\ne\nj\ne\nt\na\nv\na\nc\na\na\nj\ni\na\nc\na\n \nm\na\na\ns\na\nn\no\n \nc\na\nq\nu\ni\nn\nt\ne\n.\n \nC\nh\no\no\nc\na\n \na\nq\nu\ne\nn\nq\nu"
  specimen_32: "A\nq\nu\ne\nj\ne\nt\na\nv\na\nc\na\na\nj\ni\na\nc\na\n \nm\na\na\ns\na\nn\no\n \nc\na\nq\nu\ni\nn\nt\ne\n.\n \nC\nh\no\no\nc\na\n \na\nq\nu\ne\nn\nq\nu\ne\nj\na\nn\nt\na\nc\na\n \nm\na\na\ns\na\nn\no\n,\n \nc\nh\no"
  specimen_21: "A\nq\nu\ne\nj\ne\nt\na\nv\na\nc\na\na\nj\ni\na\nc\na\n \nm\na\na\ns\na\nn\no\n \nc\na\nq\nu\ni\nn\nt\ne\n.\n \nC\nh\no\no\nc\na\n \na\nq\nu\ne\nn\nq\nu\ne\nj\na\nn\nt\na\nc\na\n \nm\na\na\ns\na\nn\no\n,\n \nc\nh\no\no\nc\na\n \na\nm\ne\nj\ni\ng\na\nc\na\n,\n \na\nt\ns\na\nj\ni\na\nq\nu\ne\n \nt\na\na\nc\na\n \no\np\na\nj\ni\nt\na\np\na\ne\n \no\nc\na\nm\ne\ne\nt\ns\na\nt\na\nq\nu\ne\n \na\nn\nt\na\nj\ni\ng\nu\ni\nc\na\n.\n \nT\ne\ne\n \no\nn\nc\na\nm\ne"
  specimen_16: "A\nq\nu\ne\nj\ne\nt\na\nv\na\nc\na\na\nj\ni\na\nc\na\n \nm\na\na\ns\na\nn\no\n \nc\na\nq\nu\ni\nn\nt\ne\n.\n \nC\nh\no\no\nc\na\n \na\nq\nu\ne\nn\nq\nu\ne\nj\na\nn\nt\na\nc\na\n \nm\na\na\ns\na\nn\no\n,\n \nc\nh\no\no\nc\na\n \na\nm\ne\nj\ni\ng\na\nc\na\n,\n \na\nt\ns\na\nj\ni\na\nq\nu\ne\n \nt\na\na\nc\na\n \no\np\na\nj\ni\nt\na\np\na\ne\n \no\nc\na\nm\ne\ne\nt\ns\na\nt\na\nq\nu\ne\n \na\nn\nt\na\nj\ni\ng\nu\ni\nc\na\n.\n \nT\ne\ne\n \no\nn\nc\na\nm\ne\ne\nt\ns\na\nt\ne\nj\ni\n \ni\nr\no\nm\np\ne\nr\na\np\ne\nr\na\nn\na\nj\ni\nc\na\nj\ni\n,\n \nt\ne\ne\n \no\nn\nc\na\nm\ne\ne\nt\ns\na\nt\ne\nj\ni\n \ni\nr\no\ng\na\ns\nh\ni\nn\no\nn\nc\na\nj\na\nj\ni\na\nc\na\nj\ni\n.\n \nJ\ne\nr\no\n \nc\na\nm\ne\ne\nt\ns\na\nt\na\nt\ns\ni\nc\na\n \na\na\nv\na\nc\na\nj\n \na\ni\na\nq\nu\ne\nm\np\na\n.\nA\nq\nu\ne\nj\ne\nt\na\nv\na\nc\na\na"
}
