id: "crj_Latn"
language: "crj"
script: "Latn"
name: "Southern East Cree, Latin"
population: 0
region: "AC"
region: "AD"
region: "AF"
region: "AG"
region: "AI"
region: "AL"
region: "AM"
region: "AO"
region: "AR"
region: "AS"
region: "AT"
region: "AU"
region: "AW"
region: "AX"
region: "AZ"
region: "BA"
region: "BB"
region: "BD"
region: "BE"
region: "BF"
region: "BG"
region: "BI"
region: "BJ"
region: "BL"
region: "BM"
region: "BN"
region: "BO"
region: "BQ"
region: "BR"
region: "BS"
region: "BT"
region: "BW"
region: "BY"
region: "BZ"
region: "CA"
region: "CC"
region: "CD"
region: "CF"
region: "CG"
region: "CH"
region: "CI"
region: "CK"
region: "CL"
region: "CM"
region: "CN"
region: "CO"
region: "CR"
region: "CU"
region: "CV"
region: "CW"
region: "CX"
region: "CY"
region: "CZ"
region: "DE"
region: "DG"
region: "DJ"
region: "DK"
region: "DM"
region: "DO"
region: "DZ"
region: "EA"
region: "EC"
region: "EE"
region: "EG"
region: "ER"
region: "ES"
region: "ET"
region: "FI"
region: "FJ"
region: "FK"
region: "FM"
region: "FO"
region: "FR"
region: "GA"
region: "GB"
region: "GD"
region: "GE"
region: "GF"
region: "GG"
region: "GH"
region: "GI"
region: "GL"
region: "GM"
region: "GN"
region: "GP"
region: "GQ"
region: "GR"
region: "GT"
region: "GU"
region: "GW"
region: "GY"
region: "HK"
region: "HN"
region: "HR"
region: "HT"
region: "HU"
region: "IC"
region: "ID"
region: "IE"
region: "IL"
region: "IM"
region: "IN"
region: "IO"
region: "IQ"
region: "IR"
region: "IS"
region: "IT"
region: "JE"
region: "JM"
region: "JO"
region: "KE"
region: "KG"
region: "KI"
region: "KM"
region: "KN"
region: "KY"
region: "KZ"
region: "LA"
region: "LB"
region: "LC"
region: "LI"
region: "LK"
region: "LR"
region: "LS"
region: "LT"
region: "LU"
region: "LV"
region: "MA"
region: "MC"
region: "MD"
region: "ME"
region: "MF"
region: "MG"
region: "MH"
region: "MK"
region: "ML"
region: "MM"
region: "MN"
region: "MO"
region: "MP"
region: "MQ"
region: "MR"
region: "MS"
region: "MT"
region: "MU"
region: "MW"
region: "MX"
region: "MY"
region: "MZ"
region: "NA"
region: "NC"
region: "NE"
region: "NF"
region: "NG"
region: "NI"
region: "NL"
region: "NO"
region: "NP"
region: "NR"
region: "NU"
region: "NZ"
region: "PA"
region: "PE"
region: "PF"
region: "PG"
region: "PH"
region: "PK"
region: "PL"
region: "PM"
region: "PN"
region: "PR"
region: "PT"
region: "PW"
region: "PY"
region: "RE"
region: "RO"
region: "RS"
region: "RU"
region: "RW"
region: "SB"
region: "SC"
region: "SD"
region: "SE"
region: "SG"
region: "SH"
region: "SI"
region: "SJ"
region: "SK"
region: "SL"
region: "SM"
region: "SN"
region: "SO"
region: "SR"
region: "SS"
region: "ST"
region: "SV"
region: "SX"
region: "SY"
region: "SZ"
region: "TA"
region: "TC"
region: "TD"
region: "TF"
region: "TG"
region: "TH"
region: "TJ"
region: "TK"
region: "TL"
region: "TM"
region: "TN"
region: "TO"
region: "TR"
region: "TT"
region: "TV"
region: "TW"
region: "TZ"
region: "UA"
region: "UG"
region: "UM"
region: "US"
region: "UY"
region: "UZ"
region: "VA"
region: "VC"
region: "VE"
region: "VG"
region: "VI"
region: "VN"
region: "VU"
region: "WF"
region: "WS"
region: "XK"
region: "YE"
region: "YT"
region: "ZA"
region: "ZM"
region: "ZW"
sample_text {
  fallback_language: "en"
}
