id: "csa_Latn"
language: "csa"
script: "Latn"
name: "Chinantec, Chiltepec"
sample_text {
  masthead_full: "LlEe"
  masthead_partial: "Jj"
  styles: "L\ne\nj\n†\n̎\n \nn\ni\n \ns\no\nu\n \nt\ns\na\n \nl\ni\ns\ni\na"
  tester: "L\ne\nj\n†\n̎\n \nn\ni\n \ns\no\nu\n \nt\ns\na\n \nl\ni\ns\ni\na\ṉ\n \ni\nj\na\ṉ\na\n \ns\ni\na"
  poster_sm: "L\ne\nj\n†\n̎\n \nn"
  poster_md: "L\ne\nj\n†\n̎\n "
  poster_lg: "L\ne"
  specimen_48: "L\ne\nj\n†\n̎\n \nn\ni\n \ns\no\nu\n \nt\ns\na\n \nl\ni\ns\ni\na\ṉ\n \ni\nj\na\ṉ\na\n \ns\ni\na"
  specimen_36: "L\ne\nj\n†\n̎\n \nn\ni\n \ns\no\nu\n \nt\ns\na\n \nl\ni\ns\ni\na\ṉ\n \ni\nj\na\ṉ\na\n \ns\ni\na\n \ni\nk\no\nu\n\'\n \nn\ne\n \nk\no\nj\no\ṉ\n \nj\nï\n \nn\ne"
  specimen_32: "L\ne\nj\n†\n̎\n \nn\ni\n \ns\no\nu\n \nt\ns\na\n \nl\ni\ns\ni\na\ṉ\n \ni\nj\na\ṉ\na\n \ns\ni\na\n \ni\nk\no\nu\n\'\n \nn\ne\n \nk\no\nj\no\ṉ\n \nj\nï\n \nn\ne\n \nj\nu\ns\no\ṉ\n \nn\ne\n \nj\nm\no\n\'\n \nr\ne\n \nj\nu\n "
  specimen_21: "L\ne\nj\n†\n̎\n \nn\ni\n \ns\no\nu\n \nt\ns\na\n \nl\ni\ns\ni\na\ṉ\n \ni\nj\na\ṉ\na\n \ns\ni\na\n \ni\nk\no\nu\n\'\n \nn\ne\n \nk\no\nj\no\ṉ\n \nj\nï\n \nn\ne\n \nj\nu\ns\no\ṉ\n \nn\ne\n \nj\nm\no\n\'\n \nr\ne\n \nj\nu\n \ni\n \ns\n†\n̍\n\'\n \nj\nm\no\n\'\n \nn\nö\n \ns\na\nl\na\ṉ\n \nn\ne\n \ns\na\ns\nn\no\n.\nL\ne\nj\n†\n̎\n \nn\ni\n \ns\no\nu\n \nt\ns\na\n \nl\ni\ns\ni\na\ṉ\n \ni\nj\na\ṉ\na\n \ns\ni\na\n \ni\nk\no\nu\n\'\n \nn\ne\n \nk\no\nj\no\ṉ\n \nj\nï\n \nn\ne\n \nj"
  specimen_16: "L\ne\nj\n†\n̎\n \nn\ni\n \ns\no\nu\n \nt\ns\na\n \nl\ni\ns\ni\na\ṉ\n \ni\nj\na\ṉ\na\n \ns\ni\na\n \ni\nk\no\nu\n\'\n \nn\ne\n \nk\no\nj\no\ṉ\n \nj\nï\n \nn\ne\n \nj\nu\ns\no\ṉ\n \nn\ne\n \nj\nm\no\n\'\n \nr\ne\n \nj\nu\n \ni\n \ns\n†\n̍\n\'\n \nj\nm\no\n\'\n \nn\nö\n \ns\na\nl\na\ṉ\n \nn\ne\n \ns\na\ns\nn\no\n.\nL\ne\nj\n†\n̎\n \nn\ni\n \ns\no\nu\n \nt\ns\na\n \nl\ni\ns\ni\na\ṉ\n \ni\nj\na\ṉ\na\n \ns\ni\na\n \ni\nk\no\nu\n\'\n \nn\ne\n \nk\no\nj\no\ṉ\n \nj\nï\n \nn\ne\n \nj\nu\ns\no\ṉ\n \nn\ne\n \nj\nm\no\n\'\n \nr\ne\n \nj\nu\n \ni\n \ns\n†\n̍\n\'\n \nj\nm\no\n\'\n \nn\nö\n \ns\na\nl\na\ṉ\n \nn\ne\n \ns\na\ns\nn\no\n.\nL\ne\nj\n†\n̎\n \nn\ni\n \ns\no\nu\n \nt\ns\na\n \nl\ni\ns\ni\na\ṉ\n \ni\nj\na\ṉ\na\n \ns\ni\na\n \ni\nk\no\nu\n\'\n \nn\ne\n \nk\no\nj\no\ṉ\n \nj\nï\n \nn\ne\n \nj\nu\ns\no\ṉ\n \nn\ne\n \nj\nm\no\n\'\n \nr\ne\n \nj\nu\n \ni\n \ns\n†\n̍\n\'\n \nj\nm\no"
}
