id: "csw"
name: "Swampy Cree"
preferred_name: ""
autonym: "ᓀᐦᐃᔭᐍᐏᐣ"
population: 4900
region: "CA"
script: "UCAS"
exemplar_chars {
  base: "ᐁ ᐃ ᐅ ᐊ ᐍ ᐏ ᐑ ᐓ ᐕ ᐘ ᐚ ᐤ ᐯ ᐱ ᐲ ᐳ ᐴ ᐸ ᐹ ᑊ ᑌ ᑎ ᑏ ᑐ ᑑ ᑕ ᑖ ᐟ ᑫ ᑭ ᑮ ᑯ ᑰ ᑲ ᑳ ᐠ ᒉ ᒋ ᒌ ᒍ ᒎ ᒐ ᒑ ᐨ ᒣ ᒥ ᒦ ᒧ ᒨ ᒪ ᒫ ᒼ ᓀ ᓂ ᓃ ᓄ ᓅ ᓇ ᓈ ᐣ ᓭ ᓯ ᓰ ᓱ ᓲ ᓴ ᓵ ᐢ ᔦ ᔨ ᔩ ᔪ ᔫ ᔭ ᔮ ᓬ ᕒ ᐦ ᐩ ᕁ ᑵ"
}
sample_text {
  masthead_full: "ᒥᓯᐌᐃ"
  masthead_partial: "ᓂᐤ"
  tester: "ᐃᑕ ᐁ ᐃᔑ ᓂᓯᑕᐎᓂᒋᑲᑌᐠ ᒥᓯᐌ ᑲ ᑕᔑᐟ ᐎᒋᔕᓂᑐᐎᓂᐠ ᑭᐡᑌᓂᑕᑯᓯᐎᓂᐠ ᐁᑭ ᐃᔑ ᓂᑕᐎᑭᐟ ᓀᐢᑕ"
  poster_sm: "ᐁᑯ ᒪᑲ ᐁᑲ ᐁ"
  poster_md: "ᐁ ᑭᐢᑌᓂᑕᑾᐠ"
  poster_lg: "ᒥᓯᐌ"
  specimen_48: "ᓀᐢᑕ ᐊᓂᑭ ᐃᓂᓂᐗᐠ ᐱᒋ ᒪᒪᐎ ᐃᑕᐢᑲᓀᓯᐎᓂᐠ ᐱᒋ ᐅᓇᔓᐌᐎᓂᐠ ᐁ ᑕᐱ ᐃᑗᒋᐠ ᐁ ᑕᐺᔦᓂᑕᑭᐠ"
  specimen_36: "ᓀᐢᑕ ᐁ ᑭᐢᑌᓂᑕᑾᐠ ᑭᒋ ᔑᑭᑕᓂᐗᐠ ᐅᑐᑌᒥᒥᑐᐎᓂᐠ ᑭᒋ ᐃᔑ ᑲᓇᐗᐸᒥᑐᒋᐠ ᐃᑕᐢᑲᓀᓯᐎᓇ᙮\nᒥᓯᐌ ᐊᐌᓇ ᐃᔑ ᒥᓂᑯᐎᓯᐤ ᑭᒋ ᐱᒪᑎᓯᐟ ᓀᐢᑕ ᑎᐯᓂᒥᑎᓱᐎᓂᓂᐤ ᓀᐢᑕ ᐁᑲ ᑭᒋ ᐅᒋ ᓇᓂᓴᓂᓯᐟ᙮"
  specimen_32: "ᐁ ᑭᐢᑌᓂᑕᑾᐠ ᒪᑲ ᐃᓂᓂᐎ ᒥᓂᑯᐎᓯᐎᐣ ᑭᒋ ᑲᓇᐌᓂᒋᑲᑌᐠ ᐱᒋ ᐅᓇᔓᐌᐎᓂᐠ ᒪᑲ ᑭᔕᐢᐱᐣ ᐃᓂᓂᐤ ᐁᑲ ᑲ ᐸᑭᑎᓂᐟ ᑭᒋ ᐊᔭᐢᐸᐣ ᐱᑐᐡ ᑫᑾᓂᐤ ᑫ ᑭᑐᑕᐠ ᑲᓇᑫ ᒪᒋᐨ ᑫ ᐅᒋ ᒪᔑᑕᐟ ᐅᑭᒪᐎᐎᓂᓂᐤ ᐯᔭᐠ ᑭᒋ ᐅᑭᒪᐤ ᐁ ᑎᐯᐣᒋᑫᐟ ᓀᐢᑕ ᐁ ᐸᑕᑯᓄᐌᐟ᙮"
  specimen_21: "ᐃᑕ ᐁ ᐃᔑ ᓂᓯᑕᐎᓂᒋᑲᑌᐠ ᒥᓯᐌ ᑲ ᑕᔑᐟ ᐎᒋᔕᓂᑐᐎᓂᐠ ᑭᐡᑌᓂᑕᑯᓯᐎᓂᐠ ᐁᑭ ᐃᔑ ᓂᑕᐎᑭᐟ ᓀᐢᑕ ᐊᓂᐃ ᒥᓂᑯᐎᓯᐎᓇ ᐯᔭᑾᓄᐠ ᐁ ᐃᔑ ᒥᓂᑯᐎᓯᐟ ᓀᐢᑕ ᐁᑲ ᒋᑭ ᐊᓂᐢᑫᐸᓂᓂᐠ ᐎᓇ ᐱᑯ ᑲ ᑭ ᐃᔑ ᒥᓂᑯᐎᓯᐟ ᐁᑯᑕ ᐌᒋ ᓂᐸᐎᒪᑲᐠ ᑎᐯᓂᒥᑎᓱᐎᐣ ᓀᐢᑕ ᑾᔭᐢᑭᑕᑎᓯᐎᐣ ᓀᐢᑕ ᑲᔭᒣᓂᑕᒧᐎᐣ ᐅᑕ ᐊᐢᑭᐠ᙮\nᐁᑯ ᒪᑲ ᐁᑲ ᐁ ᐱᓯᐢᑫᓂᒋᑲᑌᐠ ᓀᐢᑕ ᐁ ᐱᑯᓂᑲᑌᑭ ᐃᓂᓂᐎ ᒥᓂᑯᐎᓯᐎᓇ ᐁ ᑲᑾᑕᑭᐃᒋᐠ ᐃᓂᓂᐗᐠ ᐁ ᑭᔑᐗᐃᑯᓇᓂᐗᐠ ᓀᐢᑕ ᐁ ᐊᑎ ᓄᑾᐠ ᐊᐢᑭᐠ ᐃᓂᓂᐤ ᐁ ᐸᑭᑎᓇᒪᑯᐎᓯᐟ ᑭᒋ ᒥᓉᓂᑕᐠ ᐗᐃᑗᐟ ᐱᑯ ᑫᑾᓂᐤ ᑭᒋ ᐃᑗᐟ ᓀᐢᑕ ᐅᑕᐺᔦᓂᑕᒧᐎᐣ ᓀᐢᑕ ᐅᑎᐯᓂᒥᑎᓱᐎᐣ ᐁᑲ ᑭᒋ ᓇᓂᒋᐟ ᓀᐢᑕ ᐱᑯ ᑭᒋ ᓄᑌᐸᓂᐟ ᐁ ᑭᒋ ᐃᑡᓂᐗᐠ ᐅᑕ ᐁ ᐅᑯᒪ ᒪᐗᐨ ᑲ ᐃᔑ ᒧᐡᑌᔦᓂᑕᐠ ᐃᓂᓂᐤ᙮"
  specimen_16: "ᐃᑕ ᐁ ᐃᔑ ᓂᓯᑕᐎᓂᒋᑲᑌᐠ ᒥᓯᐌ ᑲ ᑕᔑᐟ ᐎᒋᔕᓂᑐᐎᓂᐠ ᑭᐡᑌᓂᑕᑯᓯᐎᓂᐠ ᐁᑭ ᐃᔑ ᓂᑕᐎᑭᐟ ᓀᐢᑕ ᐊᓂᐃ ᒥᓂᑯᐎᓯᐎᓇ ᐯᔭᑾᓄᐠ ᐁ ᐃᔑ ᒥᓂᑯᐎᓯᐟ ᓀᐢᑕ ᐁᑲ ᒋᑭ ᐊᓂᐢᑫᐸᓂᓂᐠ ᐎᓇ ᐱᑯ ᑲ ᑭ ᐃᔑ ᒥᓂᑯᐎᓯᐟ ᐁᑯᑕ ᐌᒋ ᓂᐸᐎᒪᑲᐠ ᑎᐯᓂᒥᑎᓱᐎᐣ ᓀᐢᑕ ᑾᔭᐢᑭᑕᑎᓯᐎᐣ ᓀᐢᑕ ᑲᔭᒣᓂᑕᒧᐎᐣ ᐅᑕ ᐊᐢᑭᐠ᙮\nᐁᑯ ᒪᑲ ᐁᑲ ᐁ ᐱᓯᐢᑫᓂᒋᑲᑌᐠ ᓀᐢᑕ ᐁ ᐱᑯᓂᑲᑌᑭ ᐃᓂᓂᐎ ᒥᓂᑯᐎᓯᐎᓇ ᐁ ᑲᑾᑕᑭᐃᒋᐠ ᐃᓂᓂᐗᐠ ᐁ ᑭᔑᐗᐃᑯᓇᓂᐗᐠ ᓀᐢᑕ ᐁ ᐊᑎ ᓄᑾᐠ ᐊᐢᑭᐠ ᐃᓂᓂᐤ ᐁ ᐸᑭᑎᓇᒪᑯᐎᓯᐟ ᑭᒋ ᒥᓉᓂᑕᐠ ᐗᐃᑗᐟ ᐱᑯ ᑫᑾᓂᐤ ᑭᒋ ᐃᑗᐟ ᓀᐢᑕ ᐅᑕᐺᔦᓂᑕᒧᐎᐣ ᓀᐢᑕ ᐅᑎᐯᓂᒥᑎᓱᐎᐣ ᐁᑲ ᑭᒋ ᓇᓂᒋᐟ ᓀᐢᑕ ᐱᑯ ᑭᒋ ᓄᑌᐸᓂᐟ ᐁ ᑭᒋ ᐃᑡᓂᐗᐠ ᐅᑕ ᐁ ᐅᑯᒪ ᒪᐗᐨ ᑲ ᐃᔑ ᒧᐡᑌᔦᓂᑕᐠ ᐃᓂᓂᐤ᙮\nᐁ ᑭᐢᑌᓂᑕᑾᐠ ᒪᑲ ᐃᓂᓂᐎ ᒥᓂᑯᐎᓯᐎᐣ ᑭᒋ ᑲᓇᐌᓂᒋᑲᑌᐠ ᐱᒋ ᐅᓇᔓᐌᐎᓂᐠ ᒪᑲ ᑭᔕᐢᐱᐣ ᐃᓂᓂᐤ ᐁᑲ ᑲ ᐸᑭᑎᓂᐟ ᑭᒋ ᐊᔭᐢᐸᐣ ᐱᑐᐡ ᑫᑾᓂᐤ ᑫ ᑭᑐᑕᐠ ᑲᓇᑫ ᒪᒋᐨ ᑫ ᐅᒋ ᒪᔑᑕᐟ ᐅᑭᒪᐎᐎᓂᓂᐤ ᐯᔭᐠ ᑭᒋ ᐅᑭᒪᐤ ᐁ ᑎᐯᐣᒋᑫᐟ ᓀᐢᑕ ᐁ ᐸᑕᑯᓄᐌᐟ᙮"
}
