id: "cu_Cyrl"
language: "cu"
script: "Cyrl"
name: "Church Slavic"
autonym: "Церковнослове́нскїй"
population: 0
region: "RU"
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Ю Є Ѕ Џ Ѥ Ѩ Ѭ Ҁ І Ї Ѡ Ѣ Ѧ Ѫ Ѯ Ѱ Ѳ Ѵ Ѷ Ѻ Ѽ Ѿ Ꙁ Ꙋ Ꙍ Ꙗ Ꙃ а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь ю є ѕ џ ѥ ѩ ѭ ҁ і ї ѡ ѣ ѧ ѫ ѯ ѱ ѳ ѵ ѷ ѻ ѽ ѿ ꙁ ꙋ ꙍ ꙗ ꙃ"
  marks: "◌́ ◌̆ ◌̈ ◌̏"
}
sample_text {
  masthead_full: "ВвЬь"
  masthead_partial: "Сс"
  styles: "Вьси бо людиѥ родѧтъ сѧ свободьни и равьни"
  tester: "Вьси бо людиѥ родѧтъ сѧ свободьни и равьни въ достоиньствѣ и"
  poster_sm: "Вьси бо людиѥ"
  poster_md: "Вьси бо"
  poster_lg: "Вьси"
  specimen_48: "Вьси бо людиѥ родѧтъ сѧ свободьни и равьни въ достоиньствѣ"
  specimen_36: "Вьси бо людиѥ родѧтъ сѧ свободьни и равьни въ достоиньствѣ и законѣ. Они сѫтъ одарѥни разоумомь и съвѣдиѭ и дължьни сѫтъ дѣ ıати въ доусѣ братьства."
  specimen_32: "Вьси бо людиѥ родѧтъ сѧ свободьни и равьни въ достоиньствѣ и законѣ. Они сѫтъ одарѥни разоумомь и съвѣдиѭ и дължьни сѫтъ дѣ ıати въ доусѣ братьства."
  specimen_21: "Вьси бо людиѥ родѧтъ сѧ свободьни и равьни въ достоиньствѣ и законѣ. Они сѫтъ одарѥни разоумомь и съвѣдиѭ и дължьни сѫтъ дѣ ıати въ доусѣ братьства.\nВьси бо людиѥ родѧтъ сѧ свободьни и равьни въ достоиньствѣ и законѣ. Они сѫтъ одарѥни разоумомь и съвѣдиѭ и дължьни сѫтъ дѣ ıати въ доусѣ братьства.\nВьси бо людиѥ родѧтъ сѧ свободьни и равьни въ достоиньствѣ и законѣ. Они сѫтъ одарѥни разоумомь и съвѣдиѭ и дължьни сѫтъ дѣ ıати въ доусѣ братьства."
  specimen_16: "Вьси бо людиѥ родѧтъ сѧ свободьни и равьни въ достоиньствѣ и законѣ. Они сѫтъ одарѥни разоумомь и съвѣдиѭ и дължьни сѫтъ дѣ ıати въ доусѣ братьства.\nВьси бо людиѥ родѧтъ сѧ свободьни и равьни въ достоиньствѣ и законѣ. Они сѫтъ одарѥни разоумомь и съвѣдиѭ и дължьни сѫтъ дѣ ıати въ доусѣ братьства.\nВьси бо людиѥ родѧтъ сѧ свободьни и равьни въ достоиньствѣ и законѣ. Они сѫтъ одарѥни разоумомь и съвѣдиѭ и дължьни сѫтъ дѣ ıати въ доусѣ братьства.\nВьси бо людиѥ родѧтъ сѧ свободьни и равьни въ достоиньствѣ и законѣ. Они сѫтъ одарѥни разоумомь и съвѣдиѭ и дължьни сѫтъ дѣ ıати въ доусѣ братьства."
}
historical: true
