id: "cu_Glag"
language: "cu"
script: "Glag"
name: "Church Slavic, Glagolitic"
sample_text {
  masthead_full: "ⰂⰲⰠⱐ"
  masthead_partial: "Ⱄⱄ"
  styles: "ⰲ\nⱐ\nⱄ\nⰻ\n \nⰱ\nⱁ\n \nⰾ\nⱓ\nⰴ\nⰻ\nⰵ\n \nⱃ\nⱁ\nⰴ\nⱔ\nⱅ\nⱏ\n "
  tester: "ⰲ\nⱐ\nⱄ\nⰻ\n \nⰱ\nⱁ\n \nⰾ\nⱓ\nⰴ\nⰻ\nⰵ\n \nⱃ\nⱁ\nⰴ\nⱔ\nⱅ\nⱏ\n \nⱄ\nⱔ\n \nⱄ\nⰲ\nⱁ\nⰱ\nⱁ\nⰴ\nⱐ"
  poster_sm: "ⰲ\nⱐ\nⱄ\nⰻ\n \nⰱ"
  poster_md: "ⰲ\nⱐ\nⱄ\nⰻ\n "
  poster_lg: "ⰲ\nⱐ"
  specimen_48: "ⰲ\nⱐ\nⱄ\nⰻ\n \nⰱ\nⱁ\n \nⰾ\nⱓ\nⰴ\nⰻ\nⰵ\n \nⱃ\nⱁ\nⰴ\nⱔ\nⱅ\nⱏ\n \nⱄ\nⱔ\n \nⱄ\nⰲ\nⱁ\nⰱ\nⱁ\nⰴ\nⱐ"
  specimen_36: "ⰲ\nⱐ\nⱄ\nⰻ\n \nⰱ\nⱁ\n \nⰾ\nⱓ\nⰴ\nⰻ\nⰵ\n \nⱃ\nⱁ\nⰴ\nⱔ\nⱅ\nⱏ\n \nⱄ\nⱔ\n \nⱄ\nⰲ\nⱁ\nⰱ\nⱁ\nⰴ\nⱐ\nⱀ\nⰻ\n \nⰻ\n \nⱃ\nⰰ\nⰲ\nⱐ\nⱀ\nⰻ\n \nⰲ\nⱏ\n \nⰴ\nⱁ\nⱄ\nⱅ\nⱁ"
  specimen_32: "ⰲ\nⱐ\nⱄ\nⰻ\n \nⰱ\nⱁ\n \nⰾ\nⱓ\nⰴ\nⰻ\nⰵ\n \nⱃ\nⱁ\nⰴ\nⱔ\nⱅ\nⱏ\n \nⱄ\nⱔ\n \nⱄ\nⰲ\nⱁ\nⰱ\nⱁ\nⰴ\nⱐ\nⱀ\nⰻ\n \nⰻ\n \nⱃ\nⰰ\nⰲ\nⱐ\nⱀ\nⰻ\n \nⰲ\nⱏ\n \nⰴ\nⱁ\nⱄ\nⱅ\nⱁ\nⰻ\nⱀ\nⱐ\nⱄ\nⱅ\nⰲ\nⱑ\n \nⰻ\n \nⰸ\nⰰ\nⰽ\nⱁ\nⱀ\nⱑ\n·\n \nⱁ\nⱀ"
  specimen_21: "ⰲ\nⱐ\nⱄ\nⰻ\n \nⰱ\nⱁ\n \nⰾ\nⱓ\nⰴ\nⰻ\nⰵ\n \nⱃ\nⱁ\nⰴ\nⱔ\nⱅ\nⱏ\n \nⱄ\nⱔ\n \nⱄ\nⰲ\nⱁ\nⰱ\nⱁ\nⰴ\nⱐ\nⱀ\nⰻ\n \nⰻ\n \nⱃ\nⰰ\nⰲ\nⱐ\nⱀ\nⰻ\n \nⰲ\nⱏ\n \nⰴ\nⱁ\nⱄ\nⱅ\nⱁ\nⰻ\nⱀ\nⱐ\nⱄ\nⱅ\nⰲ\nⱑ\n \nⰻ\n \nⰸ\nⰰ\nⰽ\nⱁ\nⱀ\nⱑ\n·\n \nⱁ\nⱀ\nⰻ\n \nⱄ\nⱘ\nⱅ\nⱏ\n \nⱁ\nⰴ\nⰰ\nⱃ\nⰵ\nⱀ\nⰻ\n \nⱃ\nⰰ\nⰸ\nⱆ\nⰿ\nⱁ\nⰿ\nⱐ\n \nⰻ\n \nⱄ\nⱏ\nⰲ\nⱑ\nⰴ\nⰻ\nⱙ\n \nⰻ\n \nⰴ\nⱏ\nⰾ\nⰶ\nⱐ\nⱀ\nⰻ\n \nⱄ\nⱘ\nⱅ\nⱏ\n \nⰴ\nⱑ\nⰰ\nⱅ\nⰻ\n \nⰲ\nⱏ\n \nⰴ\nⱆ\nⱄ\nⱑ\n \nⰱ\nⱃ\nⰰ\nⱅ\nⱐ\nⱄ\nⱅ\nⰲ\nⰰ\n·\nⰲ\nⱐ\nⱄ\nⰻ\n \nⰱ\nⱁ\n "
  specimen_16: "ⰲ\nⱐ\nⱄ\nⰻ\n \nⰱ\nⱁ\n \nⰾ\nⱓ\nⰴ\nⰻ\nⰵ\n \nⱃ\nⱁ\nⰴ\nⱔ\nⱅ\nⱏ\n \nⱄ\nⱔ\n \nⱄ\nⰲ\nⱁ\nⰱ\nⱁ\nⰴ\nⱐ\nⱀ\nⰻ\n \nⰻ\n \nⱃ\nⰰ\nⰲ\nⱐ\nⱀ\nⰻ\n \nⰲ\nⱏ\n \nⰴ\nⱁ\nⱄ\nⱅ\nⱁ\nⰻ\nⱀ\nⱐ\nⱄ\nⱅ\nⰲ\nⱑ\n \nⰻ\n \nⰸ\nⰰ\nⰽ\nⱁ\nⱀ\nⱑ\n·\n \nⱁ\nⱀ\nⰻ\n \nⱄ\nⱘ\nⱅ\nⱏ\n \nⱁ\nⰴ\nⰰ\nⱃ\nⰵ\nⱀ\nⰻ\n \nⱃ\nⰰ\nⰸ\nⱆ\nⰿ\nⱁ\nⰿ\nⱐ\n \nⰻ\n \nⱄ\nⱏ\nⰲ\nⱑ\nⰴ\nⰻ\nⱙ\n \nⰻ\n \nⰴ\nⱏ\nⰾ\nⰶ\nⱐ\nⱀ\nⰻ\n \nⱄ\nⱘ\nⱅ\nⱏ\n \nⰴ\nⱑ\nⰰ\nⱅ\nⰻ\n \nⰲ\nⱏ\n \nⰴ\nⱆ\nⱄ\nⱑ\n \nⰱ\nⱃ\nⰰ\nⱅ\nⱐ\nⱄ\nⱅ\nⰲ\nⰰ\n·\nⰲ\nⱐ\nⱄ\nⰻ\n \nⰱ\nⱁ\n \nⰾ\nⱓ\nⰴ\nⰻ\nⰵ\n \nⱃ\nⱁ\nⰴ\nⱔ\nⱅ\nⱏ\n \nⱄ\nⱔ\n \nⱄ\nⰲ\nⱁ\nⰱ\nⱁ\nⰴ\nⱐ\nⱀ\nⰻ\n \nⰻ\n \nⱃ\nⰰ\nⰲ\nⱐ\nⱀ\nⰻ\n \nⰲ\nⱏ\n \nⰴ\nⱁ\nⱄ\nⱅ\nⱁ\nⰻ\nⱀ\nⱐ\nⱄ\nⱅ\nⰲ\nⱑ\n \nⰻ\n \nⰸ\nⰰ\nⰽ\nⱁ\nⱀ\nⱑ\n·\n \nⱁ\nⱀ\nⰻ\n \nⱄ\nⱘ\nⱅ\nⱏ\n \nⱁ\nⰴ\nⰰ\nⱃ\nⰵ\nⱀ\nⰻ\n \nⱃ\nⰰ\nⰸ\nⱆ\nⰿ\nⱁ\nⰿ\nⱐ\n \nⰻ\n \nⱄ\nⱏ\nⰲ\nⱑ\nⰴ\nⰻ\nⱙ\n \nⰻ\n \nⰴ\nⱏ\nⰾ\nⰶ\nⱐ\nⱀ\nⰻ\n \nⱄ\nⱘ\nⱅ\nⱏ\n \nⰴ\nⱑ\nⰰ\nⱅ\nⰻ\n \nⰲ\nⱏ\n \nⰴ\nⱆ\nⱄ\nⱑ"
}
