id: "dag_Latn"
language: "dag"
script: "Latn"
name: "Dagbani"
sample_text {
  masthead_full: "SsAa"
  masthead_partial: "Ll"
  styles: "S\na\nl\n\'\n \nl\na\n \ns\na\nl\na\n.\n \nB\nɛ\nh\ni\ng\n\'\n \nb"
  tester: "S\na\nl\n\'\n \nl\na\n \ns\na\nl\na\n.\n \nB\nɛ\nh\ni\ng\n\'\n \nb\ne\n \ns\no\nk\na\nm\n \ns\na"
  poster_sm: "S\na\nl\n\'\n \nl"
  poster_md: "S\na\nl\n\'\n "
  poster_lg: "S\na"
  specimen_48: "S\na\nl\n\'\n \nl\na\n \ns\na\nl\na\n.\n \nB\nɛ\nh\ni\ng\n\'\n \nb\ne\n \ns\no\nk\na\nm\n \ns\na"
  specimen_36: "S\na\nl\n\'\n \nl\na\n \ns\na\nl\na\n.\n \nB\nɛ\nh\ni\ng\n\'\n \nb\ne\n \ns\no\nk\na\nm\n \ns\na\nn\ni\nm\ni\n,\n \nd\ni\nn\n \np\na\n \nl\na\n \na\nm\ni\ni\n."
  specimen_32: "S\na\nl\n\'\n \nl\na\n \ns\na\nl\na\n.\n \nB\nɛ\nh\ni\ng\n\'\n \nb\ne\n \ns\no\nk\na\nm\n \ns\na\nn\ni\nm\ni\n,\n \nd\ni\nn\n \np\na\n \nl\na\n \na\nm\ni\ni\n.\n \nS\nu\nh\ni\nz\nɔ\nb\no\n \nb\ne\n \ns\no\nk\na\nm\n \ns"
  specimen_21: "S\na\nl\n\'\n \nl\na\n \ns\na\nl\na\n.\n \nB\nɛ\nh\ni\ng\n\'\n \nb\ne\n \ns\no\nk\na\nm\n \ns\na\nn\ni\nm\ni\n,\n \nd\ni\nn\n \np\na\n \nl\na\n \na\nm\ni\ni\n.\n \nS\nu\nh\ni\nz\nɔ\nb\no\n \nb\ne\n \ns\no\nk\na\nm\n \ns\na\nn\ni\n;\n \nk\na\n \nn\na\nm\nb\nɔ\nɣ\nu\n \nb\ne\nn\ni\n.\n \nS\nu\nh\nu\nb\nɔ\nh\ni\nb\no\n \nm\ni\n \nb\ni\n \nl\na\nn\n \nk\nɔ\nŋ\n \ny\ni\ng\nu\nn\na\na\nd\na\nm\n \nk\na\nm\n \ns\na\nn\ni\n.\n \nD\ni\nn\nz\nu\nɣ\nu\n \nd\ni\nm\nb\nɔ\nŋ"
  specimen_16: "S\na\nl\n\'\n \nl\na\n \ns\na\nl\na\n.\n \nB\nɛ\nh\ni\ng\n\'\n \nb\ne\n \ns\no\nk\na\nm\n \ns\na\nn\ni\nm\ni\n,\n \nd\ni\nn\n \np\na\n \nl\na\n \na\nm\ni\ni\n.\n \nS\nu\nh\ni\nz\nɔ\nb\no\n \nb\ne\n \ns\no\nk\na\nm\n \ns\na\nn\ni\n;\n \nk\na\n \nn\na\nm\nb\nɔ\nɣ\nu\n \nb\ne\nn\ni\n.\n \nS\nu\nh\nu\nb\nɔ\nh\ni\nb\no\n \nm\ni\n \nb\ni\n \nl\na\nn\n \nk\nɔ\nŋ\n \ny\ni\ng\nu\nn\na\na\nd\na\nm\n \nk\na\nm\n \ns\na\nn\ni\n.\n \nD\ni\nn\nz\nu\nɣ\nu\n \nd\ni\nm\nb\nɔ\nŋ\nɔ\n \nz\na\na\n \nw\nu\nh\ni\ny\na\n \nk\na\n \nd\na\nm\na\n \nd\ni\n \nt\nu\n \nk\na\nm\na\na\nt\na\n \nk\na\n \nt\ni\n \nz\na\na\n \ny\nu\n \nt\na\nb\n\'\n \nh\na\nl\ni\n \nn\ni\n \nt\ni\n \np\nu\nu\nn\ni\n.\nS\na\nl\n\'\n \nl\na\n \ns\na\nl\na\n.\n \nB\nɛ\nh\ni\ng\n\'\n \nb\ne\n \ns\no\nk\na\nm\n \ns\na\nn\ni\nm\ni\n,\n \nd\ni\nn\n \np\na\n \nl\na\n \na\nm\ni\ni\n.\n \nS\nu\nh\ni"
}
