id: "ddn_Latn"
language: "ddn"
script: "Latn"
name: "Dendi"
sample_text {
  masthead_full: "AaDd"
  masthead_partial: "Uu"
  styles: "A\nd\nu\nn\ni\ny\na\n \nk\nu\nn\na\n \nn\n \ng\nu\n \ni\nb\nu"
  tester: "A\nd\nu\nn\ni\ny\na\n \nk\nu\nn\na\n \nn\n \ng\nu\n \ni\nb\nu\nn\na\n \nd\na\nm\na\ny\no\n "
  poster_sm: "A\nd\nu\nn\ni\ny"
  poster_md: "A\nd\nu\nn\ni"
  poster_lg: "A\nd"
  specimen_48: "A\nd\nu\nn\ni\ny\na\n \nk\nu\nn\na\n \nn\n \ng\nu\n \ni\nb\nu\nn\na\n \nd\na\nm\na\ny\no\n "
  specimen_36: "A\nd\nu\nn\ni\ny\na\n \nk\nu\nn\na\n \nn\n \ng\nu\n \ni\nb\nu\nn\na\n \nd\na\nm\na\ny\no\n \nh\nɛ\ni\n \nn\nɔ\n \nd\ne\ni\n-\nd\ne\ni\n \nn\nn\n \nd\na"
  specimen_32: "A\nd\nu\nn\ni\ny\na\n \nk\nu\nn\na\n \nn\n \ng\nu\n \ni\nb\nu\nn\na\n \nd\na\nm\na\ny\no\n \nh\nɛ\ni\n \nn\nɔ\n \nd\ne\ni\n-\nd\ne\ni\n \nn\nn\n \nd\na\na\nm\na\n \nn\nn\na\n \nn\n \nb\nu\nr\nu\nc\ni\nn\ni\nt\nɛ"
  specimen_21: "A\nd\nu\nn\ni\ny\na\n \nk\nu\nn\na\n \nn\n \ng\nu\n \ni\nb\nu\nn\na\n \nd\na\nm\na\ny\no\n \nh\nɛ\ni\n \nn\nɔ\n \nd\ne\ni\n-\nd\ne\ni\n \nn\nn\n \nd\na\na\nm\na\n \nn\nn\na\n \nn\n \nb\nu\nr\nu\nc\ni\nn\ni\nt\nɛ\nr\nɛ\n \nf\nɔ\n,\n \nn\n \nl\na\ns\na\nb\nu\n \nn\nn\na\n \nl\na\na\nk\na\nr\ni\n \ny\na\n \nn\na\nm\n \nn\nn\n \nm\nɔ\n \nh\nu\nr\no\n \nc\nɛ\nr\nɛ\n \nk\nu\nn\na\n \nn\ny\na\nn\nz\ne\n \nt\nɛ\nr\nɛ\n \nb\nɔ\nŋ\nɔ\nɔ\n.\nA\nd\nu\nn\ni\ny\na"
  specimen_16: "A\nd\nu\nn\ni\ny\na\n \nk\nu\nn\na\n \nn\n \ng\nu\n \ni\nb\nu\nn\na\n \nd\na\nm\na\ny\no\n \nh\nɛ\ni\n \nn\nɔ\n \nd\ne\ni\n-\nd\ne\ni\n \nn\nn\n \nd\na\na\nm\na\n \nn\nn\na\n \nn\n \nb\nu\nr\nu\nc\ni\nn\ni\nt\nɛ\nr\nɛ\n \nf\nɔ\n,\n \nn\n \nl\na\ns\na\nb\nu\n \nn\nn\na\n \nl\na\na\nk\na\nr\ni\n \ny\na\n \nn\na\nm\n \nn\nn\n \nm\nɔ\n \nh\nu\nr\no\n \nc\nɛ\nr\nɛ\n \nk\nu\nn\na\n \nn\ny\na\nn\nz\ne\n \nt\nɛ\nr\nɛ\n \nb\nɔ\nŋ\nɔ\nɔ\n.\nA\nd\nu\nn\ni\ny\na\n \nk\nu\nn\na\n \nn\n \ng\nu\n \ni\nb\nu\nn\na\n \nd\na\nm\na\ny\no\n \nh\nɛ\ni\n \nn\nɔ\n \nd\ne\ni\n-\nd\ne\ni\n \nn\nn\n \nd\na\na\nm\na\n \nn\nn\na\n \nn\n \nb\nu\nr\nu\nc\ni\nn\ni\nt\nɛ\nr\nɛ\n \nf\nɔ\n,\n \nn\n \nl\na\ns\na\nb\nu\n \nn\nn\na\n \nl\na\na\nk\na\nr\ni\n \ny\na\n \nn\na\nm\n \nn\nn\n \nm\nɔ\n \nh\nu\nr\no\n \nc\nɛ\nr\nɛ\n \nk\nu\nn\na\n \nn\ny\na\nn\nz\ne"
}
