id: "de_Latn"
language: "de"
script: "Latn"
name: "German"
autonym: "Deutsch"
population: 134799567
region: "AT"
region: "BE"
region: "BG"
region: "BR"
region: "CA"
region: "CH"
region: "CZ"
region: "DE"
region: "DK"
region: "FI"
region: "FR"
region: "GB"
region: "GR"
region: "HU"
region: "IT"
region: "KZ"
region: "LI"
region: "LT"
region: "LU"
region: "NA"
region: "NL"
region: "PL"
region: "PY"
region: "RO"
region: "SI"
region: "SK"
region: "US"
exemplar_chars {
  base: "a ä b c d e f g h i j k l m n o ö p q r s ß t u ü v w x y z"
  auxiliary: "á à ă â å ã ā æ ç é è ĕ ê ë ē ğ í ì ĭ î ï İ ī ı ñ ó ò ŏ ô ø ō œ ş ú ù ŭ û ū ÿ"
  marks: "◌̈ ◌̀ ◌́"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ‚ \" “ „ « » ( ) [ ] { } § @ * / & # { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
}
sample_text {
  masthead_full: "AaLl"
  masthead_partial: "Ee"
  styles: "A\nl\nl\ne\n \nM\ne\nn\ns\nc\nh\ne\nn\n \ns\ni\nn\nd\n \nf\nr"
  tester: "A\nl\nl\ne\n \nM\ne\nn\ns\nc\nh\ne\nn\n \ns\ni\nn\nd\n \nf\nr\ne\ni\n \nu\nn\nd\n \ng\nl\ne"
  poster_sm: "A\nl\nl\ne\n \nM"
  poster_md: "A\nl\nl\ne\n "
  poster_lg: "A\nl"
  specimen_48: "A\nl\nl\ne\n \nM\ne\nn\ns\nc\nh\ne\nn\n \ns\ni\nn\nd\n \nf\nr\ne\ni\n \nu\nn\nd\n \ng\nl\ne"
  specimen_36: "A\nl\nl\ne\n \nM\ne\nn\ns\nc\nh\ne\nn\n \ns\ni\nn\nd\n \nf\nr\ne\ni\n \nu\nn\nd\n \ng\nl\ne\ni\nc\nh\n \na\nn\n \nW\nü\nr\nd\ne\n \nu\nn\nd\n \nR\ne\nc"
  specimen_32: "A\nl\nl\ne\n \nM\ne\nn\ns\nc\nh\ne\nn\n \ns\ni\nn\nd\n \nf\nr\ne\ni\n \nu\nn\nd\n \ng\nl\ne\ni\nc\nh\n \na\nn\n \nW\nü\nr\nd\ne\n \nu\nn\nd\n \nR\ne\nc\nh\nt\ne\nn\n \ng\ne\nb\no\nr\ne\nn\n.\n \nS\ni\ne\n \ns\ni"
  specimen_21: "A\nl\nl\ne\n \nM\ne\nn\ns\nc\nh\ne\nn\n \ns\ni\nn\nd\n \nf\nr\ne\ni\n \nu\nn\nd\n \ng\nl\ne\ni\nc\nh\n \na\nn\n \nW\nü\nr\nd\ne\n \nu\nn\nd\n \nR\ne\nc\nh\nt\ne\nn\n \ng\ne\nb\no\nr\ne\nn\n.\n \nS\ni\ne\n \ns\ni\nn\nd\n \nm\ni\nt\n \nV\ne\nr\nn\nu\nn\nf\nt\n \nu\nn\nd\n \nG\ne\nw\ni\ns\ns\ne\nn\n \nb\ne\ng\na\nb\nt\n \nu\nn\nd\n \ns\no\nl\nl\ne\nn\n \ne\ni\nn\na\nn\nd\ne\nr\n \ni\nm\n \nG\ne\ni\ns\nt\n \nd\ne\nr\n \nB\nr\nü\nd\ne\nr\nl\ni\nc\nh\nk"
  specimen_16: "A\nl\nl\ne\n \nM\ne\nn\ns\nc\nh\ne\nn\n \ns\ni\nn\nd\n \nf\nr\ne\ni\n \nu\nn\nd\n \ng\nl\ne\ni\nc\nh\n \na\nn\n \nW\nü\nr\nd\ne\n \nu\nn\nd\n \nR\ne\nc\nh\nt\ne\nn\n \ng\ne\nb\no\nr\ne\nn\n.\n \nS\ni\ne\n \ns\ni\nn\nd\n \nm\ni\nt\n \nV\ne\nr\nn\nu\nn\nf\nt\n \nu\nn\nd\n \nG\ne\nw\ni\ns\ns\ne\nn\n \nb\ne\ng\na\nb\nt\n \nu\nn\nd\n \ns\no\nl\nl\ne\nn\n \ne\ni\nn\na\nn\nd\ne\nr\n \ni\nm\n \nG\ne\ni\ns\nt\n \nd\ne\nr\n \nB\nr\nü\nd\ne\nr\nl\ni\nc\nh\nk\ne\ni\nt\n \nb\ne\ng\ne\ng\nn\ne\nn\n.\nA\nl\nl\ne\n \nM\ne\nn\ns\nc\nh\ne\nn\n \ns\ni\nn\nd\n \nf\nr\ne\ni\n \nu\nn\nd\n \ng\nl\ne\ni\nc\nh\n \na\nn\n \nW\nü\nr\nd\ne\n \nu\nn\nd\n \nR\ne\nc\nh\nt\ne\nn\n \ng\ne\nb\no\nr\ne\nn\n.\n \nS\ni\ne\n \ns\ni\nn\nd\n \nm\ni\nt\n \nV\ne\nr\nn\nu\nn\nf\nt\n \nu\nn\nd\n \nG\ne\nw\ni\ns\ns\ne\nn\n \nb\ne\ng\na\nb\nt\n \nu\nn\nd\n \ns\no"
}
