id: "dga_Latn"
language: "dga"
script: "Latn"
name: "Dagaare, Southern"
region: "GH"
sample_text {
  masthead_full: "NnEe"
  masthead_partial: "Gg"
  styles: "Nengsaala zaa ba nang dɔge so la o menga,"
  tester: "Nengsaala zaa ba nang dɔge so la o menga, ka o ne o taaba zaa"
  poster_sm: "Nengsaala zaa"
  poster_md: "Nengsaala"
  poster_lg: "zaa"
  specimen_48: "Nengsaala zaa ba nang dɔge so la o menga, ka o ne o taaba zaa sengtaa"
  specimen_36: "Nengsaala zaa ba nang dɔge so la o menga, ka o ne o taaba zaa sengtaa noba emmo ane yɛlɛsoobo sobic poɔ. Ba dɔgɛɛ ba zaa ne yɛng ane yɛlɛ-iruu k\'a da seng ka ba erɛ yɛlɛ korɔ taa a nga yɔɔmine.\nNengsaala zaa ba nang dɔge so la o menga, ka o ne o taaba zaa sengtaa noba emmo ane yɛlɛsoobo sobic poɔ. Ba dɔgɛɛ ba zaa ne yɛng ane yɛlɛ-iruu k\'a da seng ka ba erɛ yɛlɛ korɔ taa a nga yɔɔmine."
  specimen_32: "Nengsaala zaa ba nang dɔge so la o menga, ka o ne o taaba zaa sengtaa noba emmo ane yɛlɛsoobo sobic poɔ. Ba dɔgɛɛ ba zaa ne yɛng ane yɛlɛ-iruu k\'a da seng ka ba erɛ yɛlɛ korɔ taa a nga yɔɔmine.\nNengsaala zaa ba nang dɔge so la o menga, ka o ne o taaba zaa sengtaa noba emmo ane yɛlɛsoobo sobic poɔ. Ba dɔgɛɛ ba zaa ne yɛng ane yɛlɛ-iruu k\'a da seng ka ba erɛ yɛlɛ korɔ taa a nga yɔɔmine."
  specimen_21: "Nengsaala zaa ba nang dɔge so la o menga, ka o ne o taaba zaa sengtaa noba emmo ane yɛlɛsoobo sobic poɔ. Ba dɔgɛɛ ba zaa ne yɛng ane yɛlɛ-iruu k\'a da seng ka ba erɛ yɛlɛ korɔ taa a nga yɔɔmine.\nNengsaala zaa ba nang dɔge so la o menga, ka o ne o taaba zaa sengtaa noba emmo ane yɛlɛsoobo sobic poɔ. Ba dɔgɛɛ ba zaa ne yɛng ane yɛlɛ-iruu k\'a da seng ka ba erɛ yɛlɛ korɔ taa a nga yɔɔmine."
  specimen_16: "Nengsaala zaa ba nang dɔge so la o menga, ka o ne o taaba zaa sengtaa noba emmo ane yɛlɛsoobo sobic poɔ. Ba dɔgɛɛ ba zaa ne yɛng ane yɛlɛ-iruu k\'a da seng ka ba erɛ yɛlɛ korɔ taa a nga yɔɔmine.\nNengsaala zaa ba nang dɔge so la o menga, ka o ne o taaba zaa sengtaa noba emmo ane yɛlɛsoobo sobic poɔ. Ba dɔgɛɛ ba zaa ne yɛng ane yɛlɛ-iruu k\'a da seng ka ba erɛ yɛlɛ korɔ taa a nga yɔɔmine.\nNengsaala zaa ba nang dɔge so la o menga, ka o ne o taaba zaa sengtaa noba emmo ane yɛlɛsoobo sobic poɔ. Ba dɔgɛɛ ba zaa ne yɛng ane yɛlɛ-iruu k\'a da seng ka ba erɛ yɛlɛ korɔ taa a nga yɔɔmine."
}
