id: "dga_Latn"
language: "dga"
script: "Latn"
name: "Dagaare, Southern"
sample_text {
  masthead_full: "NnEe"
  masthead_partial: "Gg"
  styles: "N\ne\nn\ng\ns\na\na\nl\na\n \nz\na\na\n \nb\na\n \nn\na\nn\ng"
  tester: "N\ne\nn\ng\ns\na\na\nl\na\n \nz\na\na\n \nb\na\n \nn\na\nn\ng\n \nd\nɔ\ng\ne\n \ns\no\n \nl"
  poster_sm: "N\ne\nn\ng\ns\na"
  poster_md: "N\ne\nn\ng\ns"
  poster_lg: "N\ne"
  specimen_48: "N\ne\nn\ng\ns\na\na\nl\na\n \nz\na\na\n \nb\na\n \nn\na\nn\ng\n \nd\nɔ\ng\ne\n \ns\no\n \nl"
  specimen_36: "N\ne\nn\ng\ns\na\na\nl\na\n \nz\na\na\n \nb\na\n \nn\na\nn\ng\n \nd\nɔ\ng\ne\n \ns\no\n \nl\na\n \no\n \nm\ne\nn\ng\na\n,\n \nk\na\n \no\n \nn\ne\n \no"
  specimen_32: "N\ne\nn\ng\ns\na\na\nl\na\n \nz\na\na\n \nb\na\n \nn\na\nn\ng\n \nd\nɔ\ng\ne\n \ns\no\n \nl\na\n \no\n \nm\ne\nn\ng\na\n,\n \nk\na\n \no\n \nn\ne\n \no\n \nt\na\na\nb\na\n \nz\na\na\n \ns\ne\nn\ng\nt\na\na\n \nn"
  specimen_21: "N\ne\nn\ng\ns\na\na\nl\na\n \nz\na\na\n \nb\na\n \nn\na\nn\ng\n \nd\nɔ\ng\ne\n \ns\no\n \nl\na\n \no\n \nm\ne\nn\ng\na\n,\n \nk\na\n \no\n \nn\ne\n \no\n \nt\na\na\nb\na\n \nz\na\na\n \ns\ne\nn\ng\nt\na\na\n \nn\no\nb\na\n \ne\nm\nm\no\n \na\nn\ne\n \ny\nɛ\nl\nɛ\ns\no\no\nb\no\n \ns\no\nb\ni\nc\n \np\no\nɔ\n.\n \nB\na\n \nd\nɔ\ng\nɛ\nɛ\n \nb\na\n \nz\na\na\n \nn\ne\n \ny\nɛ\nn\ng\n \na\nn\ne\n \ny\nɛ\nl\nɛ\n-\ni\nr\nu\nu\n \nk\n\'\na\n \nd\na\n \ns\ne\nn"
  specimen_16: "N\ne\nn\ng\ns\na\na\nl\na\n \nz\na\na\n \nb\na\n \nn\na\nn\ng\n \nd\nɔ\ng\ne\n \ns\no\n \nl\na\n \no\n \nm\ne\nn\ng\na\n,\n \nk\na\n \no\n \nn\ne\n \no\n \nt\na\na\nb\na\n \nz\na\na\n \ns\ne\nn\ng\nt\na\na\n \nn\no\nb\na\n \ne\nm\nm\no\n \na\nn\ne\n \ny\nɛ\nl\nɛ\ns\no\no\nb\no\n \ns\no\nb\ni\nc\n \np\no\nɔ\n.\n \nB\na\n \nd\nɔ\ng\nɛ\nɛ\n \nb\na\n \nz\na\na\n \nn\ne\n \ny\nɛ\nn\ng\n \na\nn\ne\n \ny\nɛ\nl\nɛ\n-\ni\nr\nu\nu\n \nk\n\'\na\n \nd\na\n \ns\ne\nn\ng\n \nk\na\n \nb\na\n \ne\nr\nɛ\n \ny\nɛ\nl\nɛ\n \nk\no\nr\nɔ\n \nt\na\na\n \na\n \nn\ng\na\n \ny\nɔ\nɔ\nm\ni\nn\ne\n.\nN\ne\nn\ng\ns\na\na\nl\na\n \nz\na\na\n \nb\na\n \nn\na\nn\ng\n \nd\nɔ\ng\ne\n \ns\no\n \nl\na\n \no\n \nm\ne\nn\ng\na\n,\n \nk\na\n \no\n \nn\ne\n \no\n \nt\na\na\nb\na\n \nz\na\na\n \ns\ne\nn\ng\nt\na\na\n \nn\no\nb\na\n \ne\nm\nm\no\n \na\nn\ne\n \ny\nɛ"
}
