id: "dhw_Deva"
language: "dhw"
script: "Deva"
name: "Dhanwar, Nepal, Devanagari"
region: "NP"
sample_text {
  masthead_full: "सभमन"
  masthead_partial: "हक"
  styles: "सभे मानहुकसब प्रतिष्ठा आ अधिकारक आधारम जन्मजात स्वतंत्र"
  tester: "सभे मानहुकसब प्रतिष्ठा आ अधिकारक आधारम जन्मजात स्वतंत्र आ समान हबछो। ओकरसिक बुद्धि"
  poster_sm: "सभे मानहुकसब प्रतिष्ठा"
  poster_md: "सभे मानहुकसब"
  poster_lg: "मानहुकसब"
  specimen_48: "सभे मानहुकसब प्रतिष्ठा आ अधिकारक आधारम जन्मजात स्वतंत्र आ समान हबछो। ओकरसिक बुद्धि आ"
  specimen_36: "सभे मानहुकसब प्रतिष्ठा आ अधिकारक आधारम जन्मजात स्वतंत्र आ समान हबछो। ओकरसिक बुद्धि आ विवेक लिइक आइल रहछो आ एक अर्कापखा आपनपनक व्यबहार करपर्तो।"
  specimen_32: "सभे मानहुकसब प्रतिष्ठा आ अधिकारक आधारम जन्मजात स्वतंत्र आ समान हबछो। ओकरसिक बुद्धि आ विवेक लिइक आइल रहछो आ एक अर्कापखा आपनपनक व्यबहार करपर्तो।"
  specimen_21: "सभे मानहुकसब प्रतिष्ठा आ अधिकारक आधारम जन्मजात स्वतंत्र आ समान हबछो। ओकरसिक बुद्धि आ विवेक लिइक आइल रहछो आ एक अर्कापखा आपनपनक व्यबहार करपर्तो।\nसभे मानहुकसब प्रतिष्ठा आ अधिकारक आधारम जन्मजात स्वतंत्र आ समान हबछो। ओकरसिक बुद्धि आ विवेक लिइक आइल रहछो आ एक अर्कापखा आपनपनक व्यबहार करपर्तो।\nसभे मानहुकसब प्रतिष्ठा आ अधिकारक आधारम जन्मजात स्वतंत्र आ समान हबछो। ओकरसिक बुद्धि आ विवेक लिइक आइल रहछो आ एक अर्कापखा आपनपनक व्यबहार करपर्तो।"
  specimen_16: "सभे मानहुकसब प्रतिष्ठा आ अधिकारक आधारम जन्मजात स्वतंत्र आ समान हबछो। ओकरसिक बुद्धि आ विवेक लिइक आइल रहछो आ एक अर्कापखा आपनपनक व्यबहार करपर्तो।\nसभे मानहुकसब प्रतिष्ठा आ अधिकारक आधारम जन्मजात स्वतंत्र आ समान हबछो। ओकरसिक बुद्धि आ विवेक लिइक आइल रहछो आ एक अर्कापखा आपनपनक व्यबहार करपर्तो।\nसभे मानहुकसब प्रतिष्ठा आ अधिकारक आधारम जन्मजात स्वतंत्र आ समान हबछो। ओकरसिक बुद्धि आ विवेक लिइक आइल रहछो आ एक अर्कापखा आपनपनक व्यबहार करपर्तो।\nसभे मानहुकसब प्रतिष्ठा आ अधिकारक आधारम जन्मजात स्वतंत्र आ समान हबछो। ओकरसिक बुद्धि आ विवेक लिइक आइल रहछो आ एक अर्कापखा आपनपनक व्यबहार करपर्तो।\nसभे मानहुकसब प्रतिष्ठा आ अधिकारक आधारम जन्मजात स्वतंत्र आ समान हबछो। ओकरसिक बुद्धि आ विवेक लिइक आइल रहछो आ एक अर्कापखा आपनपनक व्यबहार करपर्तो।\nसभे मानहुकसब प्रतिष्ठा आ अधिकारक आधारम जन्मजात स्वतंत्र आ समान हबछो। ओकरसिक बुद्धि आ विवेक लिइक आइल रहछो आ एक अर्कापखा आपनपनक व्यबहार करपर्तो।"
}
