id: "dhw_Deva"
language: "dhw"
script: "Deva"
name: "Dhanwar, Nepal, Devanagari"
sample_text {
  masthead_full: "सभमन"
  masthead_partial: "हक"
  styles: "स\nभ\nे\n \nम\nा\nन\nह\nु\nक\nस\nब\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nआ"
  tester: "स\nभ\nे\n \nम\nा\nन\nह\nु\nक\nस\nब\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nआ\n \nअ\nध\nि\nक\nा\nर\nक\n \nआ\nध"
  poster_sm: "स\nभ\nे\n \nम\nा\nन"
  poster_md: "स\nभ\nे\n \nम"
  poster_lg: "स\nभ"
  specimen_48: "स\nभ\nे\n \nम\nा\nन\nह\nु\nक\nस\nब\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nआ\n \nअ\nध\nि\nक\nा\nर\nक\n \nआ\nध"
  specimen_36: "स\nभ\nे\n \nम\nा\nन\nह\nु\nक\nस\nब\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nआ\n \nअ\nध\nि\nक\nा\nर\nक\n \nआ\nध\nा\nर\nम\n \nज\nन\n्\nम\nज\nा\nत\n \nस\n्\nव\nत\nं\nत\n्\nर\n \nआ\n "
  specimen_32: "स\nभ\nे\n \nम\nा\nन\nह\nु\nक\nस\nब\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nआ\n \nअ\nध\nि\nक\nा\nर\nक\n \nआ\nध\nा\nर\nम\n \nज\nन\n्\nम\nज\nा\nत\n \nस\n्\nव\nत\nं\nत\n्\nर\n \nआ\n \nस\nम\nा\nन\n \nह\nब\nछ\nो\n।\n \nओ\nक\nर\nस\nि\nक\n \nब\nु\nद\n्\nध"
  specimen_21: "स\nभ\nे\n \nम\nा\nन\nह\nु\nक\nस\nब\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nआ\n \nअ\nध\nि\nक\nा\nर\nक\n \nआ\nध\nा\nर\nम\n \nज\nन\n्\nम\nज\nा\nत\n \nस\n्\nव\nत\nं\nत\n्\nर\n \nआ\n \nस\nम\nा\nन\n \nह\nब\nछ\nो\n।\n \nओ\nक\nर\nस\nि\nक\n \nब\nु\nद\n्\nध\nि\n \nआ\n \nव\nि\nव\nे\nक\n \nल\nि\nइ\nक\n \nआ\nइ\nल\n \nर\nह\nछ\nो\n \nआ\n \nए\nक\n \nअ\nर\n्\nक\nा\nप\nख\nा\n \nआ\nप\nन\nप\nन\nक\n \nव\n्\nय\nब\nह\nा\nर\n \nक\nर\nप\nर\n्\nत\nो\n।\nस\nभ\nे\n \nम\nा\nन\nह\nु\nक\nस\nब\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nआ\n \nअ\nध\nि\nक\nा"
  specimen_16: "स\nभ\nे\n \nम\nा\nन\nह\nु\nक\nस\nब\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nआ\n \nअ\nध\nि\nक\nा\nर\nक\n \nआ\nध\nा\nर\nम\n \nज\nन\n्\nम\nज\nा\nत\n \nस\n्\nव\nत\nं\nत\n्\nर\n \nआ\n \nस\nम\nा\nन\n \nह\nब\nछ\nो\n।\n \nओ\nक\nर\nस\nि\nक\n \nब\nु\nद\n्\nध\nि\n \nआ\n \nव\nि\nव\nे\nक\n \nल\nि\nइ\nक\n \nआ\nइ\nल\n \nर\nह\nछ\nो\n \nआ\n \nए\nक\n \nअ\nर\n्\nक\nा\nप\nख\nा\n \nआ\nप\nन\nप\nन\nक\n \nव\n्\nय\nब\nह\nा\nर\n \nक\nर\nप\nर\n्\nत\nो\n।\nस\nभ\nे\n \nम\nा\nन\nह\nु\nक\nस\nब\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nआ\n \nअ\nध\nि\nक\nा\nर\nक\n \nआ\nध\nा\nर\nम\n \nज\nन\n्\nम\nज\nा\nत\n \nस\n्\nव\nत\nं\nत\n्\nर\n \nआ\n \nस\nम\nा\nन\n \nह\nब\nछ\nो\n।\n \nओ\nक\nर\nस\nि\nक\n \nब\nु\nद\n्\nध\nि\n \nआ\n \nव\nि\nव\nे\nक\n \nल\nि\nइ\nक\n \nआ\nइ\nल\n \nर\nह\nछ\nो\n \nआ\n \nए\nक\n \nअ\nर\n्\nक\nा\nप\nख\nा\n \nआ\nप\nन\nप\nन\nक\n \nव\n्\nय\nब\nह\nा\nर\n \nक\nर\nप\nर\n्\nत\nो\n।\nस\nभ\nे\n \nम\nा\nन\nह\nु\nक\nस\nब\n \nप\n्\nर\nत\nि\nष\n्\nठ\nा\n \nआ\n \nअ\nध\nि\nक\nा"
}
