id: "dsb"
language: "dsb"
script: "Latn"
name: "Lower Sorbian"
autonym: "Dolnoserbšćina"
population: 6973
region: "DE"
exemplar_chars {
  base: "a b c č ć d e ě f g h {ch} i j k ł l m n ń o ó p q r ŕ s š ś t u v w x y z ž ź {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch}"
  auxiliary: "á à ă â å ä ã ą ā æ ç ď đ é è ĕ ê ë ė ę ē ğ í ì ĭ î ï İ ī ı ĺ ľ ň ñ ò ŏ ô ö ő ø ō œ ř ş ß ť ú ù ŭ û ů ü ű ū ý ÿ ż"
  marks: "◌́ ◌̌"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ ‚ \" “ „ « » ( ) [ ] { } § @ * / & # { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "A B C Č Ć D E F G H {Ch} I J K Ł L M N O P Q R S Š Ś T U V W X Y Z Ž Ź {Ch} {Ch} {Ch} {Ch} {Ch} {Ch} {Ch} {Ch} {Ch} {Ch} {Ch} {Ch} {Ch} {Ch} {Ch}"
}
sample_text {
  fallback_language: "en"
}
