id: "dua"
language: "dua"
script: "Latn"
name: "Duala"
autonym: "Duálá"
population: 133176
region: "CM"
exemplar_chars {
  base: "a á b ɓ c d ɗ e é ɛ {ɛ́} f g i í j k l m n {ny} ŋ o ó ɔ {ɔ́} p r s t u ú ū w y {ɛ́} {ny} {ɔ́} {ɛ́} {ny} {ɔ́} {ɛ́} {ny} {ɔ́} {ɛ́} {ny} {ɔ́} {ɛ́} {ny} {ɔ́} {ɛ́} {ny} {ɔ́} {ɛ́} {ny} {ɔ́} {ɛ́} {ny} {ɔ́} {ɛ́} {ny} {ɔ́} {ɛ́} {ny} {ɔ́} {ɛ́} {ny} {ɔ́} {ɛ́} {ny} {ɔ́} {ɛ́} {ny} {ɔ́} {ɛ́} {ny} {ɔ́} {ɛ́} {ny} {ɔ́}"
  auxiliary: "h q v x z"
  marks: "◌́ ◌̄"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B Ɓ C D Ɗ E Ɛ F G I J K L M N Ŋ O Ɔ P S T U W Y"
}
sample_text {
  fallback_language: "en"
}
