id: "ebu"
language: "ebu"
script: "Latn"
name: "Embu"
autonym: "Kiembu"
population: 802918
region: "KE"
exemplar_chars {
  base: "a b c d e f g h i ĩ j k l m n o p q r s t u ũ v w x y z"
  marks: "◌̃"
  index: "A B C D E F G H I Ĩ J K L M N O P Q R S T U Ũ V W X Y Z"
}
sample_text {
  fallback_language: "en"
}
