id: "egy_Egyp"
language: "egy"
script: "Egyp"
name: "Ancient Egyptian"
population: 0
sample_text {
  masthead_full: "𓇋𓅱𓄙𓅓"
  masthead_partial: "𓈖𓎿"
  styles: "𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱"
  tester: "𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱"
  poster_sm: "𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍"
  poster_md: "𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃"
  poster_lg: "𓈖𓎿𓊃"
  specimen_48: "𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱"
  specimen_36: "𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱"
  specimen_32: "𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱"
  specimen_21: "𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱"
  specimen_16: "𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱\n𓇋𓅱𓐷𓄙𓐱𓅓𓐸𓐰𓈖𓎿𓊃𓐰𓏏𓀁𓐍𓐰𓂋𓇓𓏏𓐰𓈖𓋴𓉼𓐷𓎵𓐱𓏤𓐸𓐰𓂋𓇋𓏏𓐰𓆑𓀀𓏪𓆣𓐰𓂋𓅱𓂋𓐰𓄂𓐰𓏏𓀀𓇋𓅱"
}
historical: true
