id: "el_Grek"
language: "el"
script: "Grek"
name: "Greek"
preferred_name: "Modern Greek"
autonym: "Ελληνικά"
population: 12384861
region: "AL"
region: "CY"
region: "DE"
region: "EG"
region: "GB"
region: "GR"
region: "IT"
region: "RO"
region: "TR"
region: "UA"
exemplar_chars {
  base: "α ά β γ δ ε έ ζ η ή θ ι ί ϊ ΐ κ λ μ ν ξ ο ό π ρ σ ς τ υ ύ ϋ ΰ φ χ ψ ω ώ"
  auxiliary: "ἀ ἄ ἂ ἆ ἁ ἅ ἃ ἇ ὰ ᾶ ἐ ἔ ἒ ἑ ἕ ἓ ὲ ἠ ἤ ἢ ἦ ἡ ἥ ἣ ἧ ὴ ῆ ἰ ἴ ἲ ἶ ἱ ἵ ἳ ἷ ὶ ῖ ῒ ῗ ὄ ὂ ὃ ὸ ὐ ὔ ὒ ὖ ὑ ὕ ὓ ὗ ὺ ῦ ῢ ῧ ὤ ὢ ὦ ὥ ὣ ὧ ὼ ῶ"
  marks: "◌́ ◌̈"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! . … \" « » ( ) [ ] § @ * / \\ &"
  index: "Α Β Γ Δ Ε Ζ Η Θ Ι Κ Λ Μ Ν Ξ Ο Π Ρ Σ Τ Υ Φ Χ Ψ Ω"
}
sample_text {
  masthead_full: "ΌόΛλ"
  masthead_partial: "Οο"
  styles: "Ό\nλ\nο\nι\n \nο\nι\n \nά\nν\nθ\nρ\nω\nπ\nο\nι\n \nγ\nε\nν\nν"
  tester: "Ό\nλ\nο\nι\n \nο\nι\n \nά\nν\nθ\nρ\nω\nπ\nο\nι\n \nγ\nε\nν\nν\nι\nο\nύ\nν\nτ\nα\nι\n \nε\nλ"
  poster_sm: "Ό\nλ\nο\nι\n \nο"
  poster_md: "Ό\nλ\nο\nι\n "
  poster_lg: "Ό\nλ"
  specimen_48: "Ό\nλ\nο\nι\n \nο\nι\n \nά\nν\nθ\nρ\nω\nπ\nο\nι\n \nγ\nε\nν\nν\nι\nο\nύ\nν\nτ\nα\nι\n \nε\nλ"
  specimen_36: "Ό\nλ\nο\nι\n \nο\nι\n \nά\nν\nθ\nρ\nω\nπ\nο\nι\n \nγ\nε\nν\nν\nι\nο\nύ\nν\nτ\nα\nι\n \nε\nλ\nε\nύ\nθ\nε\nρ\nο\nι\n \nκ\nα\nι\n \nί\nσ\nο\nι\n \nσ\nτ\nη"
  specimen_32: "Ό\nλ\nο\nι\n \nο\nι\n \nά\nν\nθ\nρ\nω\nπ\nο\nι\n \nγ\nε\nν\nν\nι\nο\nύ\nν\nτ\nα\nι\n \nε\nλ\nε\nύ\nθ\nε\nρ\nο\nι\n \nκ\nα\nι\n \nί\nσ\nο\nι\n \nσ\nτ\nη\nν\n \nα\nξ\nι\nο\nπ\nρ\nέ\nπ\nε\nι\nα\n \nκ\nα\nι\n \nτ\nα"
  specimen_21: "Ό\nλ\nο\nι\n \nο\nι\n \nά\nν\nθ\nρ\nω\nπ\nο\nι\n \nγ\nε\nν\nν\nι\nο\nύ\nν\nτ\nα\nι\n \nε\nλ\nε\nύ\nθ\nε\nρ\nο\nι\n \nκ\nα\nι\n \nί\nσ\nο\nι\n \nσ\nτ\nη\nν\n \nα\nξ\nι\nο\nπ\nρ\nέ\nπ\nε\nι\nα\n \nκ\nα\nι\n \nτ\nα\n \nδ\nι\nκ\nα\nι\nώ\nμ\nα\nτ\nα\n.\n \nΕ\nί\nν\nα\nι\n \nπ\nρ\nο\nι\nκ\nι\nσ\nμ\nέ\nν\nο\nι\n \nμ\nε\n \nλ\nο\nγ\nι\nκ\nή\n \nκ\nα\nι\n \nσ\nυ\nν\nε\nί\nδ\nη\nσ\nη\n,\n \nκ\nα\nι\n \nο\nφ\nε\nί\nλ\nο\nυ\nν\n \nν\nα\n \nσ\nυ\nμ\nπ\nε\nρ\nι\nφ"
  specimen_16: "Ό\nλ\nο\nι\n \nο\nι\n \nά\nν\nθ\nρ\nω\nπ\nο\nι\n \nγ\nε\nν\nν\nι\nο\nύ\nν\nτ\nα\nι\n \nε\nλ\nε\nύ\nθ\nε\nρ\nο\nι\n \nκ\nα\nι\n \nί\nσ\nο\nι\n \nσ\nτ\nη\nν\n \nα\nξ\nι\nο\nπ\nρ\nέ\nπ\nε\nι\nα\n \nκ\nα\nι\n \nτ\nα\n \nδ\nι\nκ\nα\nι\nώ\nμ\nα\nτ\nα\n.\n \nΕ\nί\nν\nα\nι\n \nπ\nρ\nο\nι\nκ\nι\nσ\nμ\nέ\nν\nο\nι\n \nμ\nε\n \nλ\nο\nγ\nι\nκ\nή\n \nκ\nα\nι\n \nσ\nυ\nν\nε\nί\nδ\nη\nσ\nη\n,\n \nκ\nα\nι\n \nο\nφ\nε\nί\nλ\nο\nυ\nν\n \nν\nα\n \nσ\nυ\nμ\nπ\nε\nρ\nι\nφ\nέ\nρ\nο\nν\nτ\nα\nι\n \nμ\nε\nτ\nα\nξ\nύ\n \nτ\nο\nυ\nς\n \nμ\nε\n \nπ\nν\nε\nύ\nμ\nα\n \nα\nδ\nε\nλ\nφ\nο\nσ\nύ\nν\nη\nς\n.\nΌ\nλ\nο\nι\n \nο\nι\n \nά\nν\nθ\nρ\nω\nπ\nο\nι\n \nγ\nε\nν\nν\nι\nο\nύ\nν\nτ\nα\nι\n \nε\nλ\nε\nύ\nθ\nε\nρ\nο\nι\n \nκ\nα\nι\n \nί\nσ\nο\nι\n \nσ\nτ\nη\nν\n \nα\nξ\nι\nο\nπ\nρ\nέ\nπ\nε\nι\nα\n \nκ\nα\nι\n \nτ\nα\n \nδ\nι\nκ\nα\nι\nώ\nμ\nα\nτ\nα\n.\n "
}
