id: "en_Brai"
language: "en"
script: "Brai"
name: "English, Braille"
sample_text {
  masthead_full: "⠉⠽⠑⠝"
  masthead_partial: "⠉⠽"
  styles: "⠁⠇⠇ ⠓⠥⠍⠁⠝ ⠃⠑⠊⠝⠛⠎ ⠁⠗⠑ ⠃⠕⠗⠝ ⠋⠗⠑⠑ ⠁⠝⠙ ⠑⠟⠥⠁⠇"
  tester: "⠑⠧⠑⠗⠽⠕⠝⠑ ⠊⠎ ⠑⠝⠞⠊⠞⠇⠑⠙ ⠞⠕ ⠁⠇⠇ ⠞⠓⠑ ⠗⠊⠛⠓⠞⠎ ⠁⠝⠙ ⠋⠗⠑⠑⠙⠕⠍⠎ ⠎⠑⠞ ⠋⠕⠗⠞⠓"
  poster_sm: "⠋⠥⠗⠞⠓⠑⠗⠍⠕⠗⠑⠂"
  poster_md: "⠑⠧⠑⠗⠽⠕⠝⠑"
  poster_lg: "⠁⠇⠇"
  specimen_48: "⠝⠕ ⠕⠝⠑ ⠎⠓⠁⠇⠇ ⠃⠑ ⠓⠑⠇⠙ ⠊⠝ ⠎⠇⠁⠧⠑⠗⠽ ⠕⠗ ⠎⠑⠗⠧⠊⠞⠥⠙⠑⠆ ⠎⠇⠁⠧⠑⠗⠽ ⠁⠝⠙ ⠞⠓⠑"
  specimen_36: "⠝⠕ ⠕⠝⠑ ⠎⠓⠁⠇⠇ ⠃⠑ ⠓⠑⠇⠙ ⠊⠝ ⠎⠇⠁⠧⠑⠗⠽ ⠕⠗ ⠎⠑⠗⠧⠊⠞⠥⠙⠑⠆ ⠎⠇⠁⠧⠑⠗⠽ ⠁⠝⠙ ⠞⠓⠑ ⠎⠇⠁⠧⠑ ⠞⠗⠁⠙⠑ ⠎⠓⠁⠇⠇ ⠃⠑ ⠏⠗⠕⠓⠊⠃⠊⠞⠑⠙ ⠊⠝ ⠁⠇⠇ ⠞⠓⠑⠊⠗ ⠋⠕⠗⠍⠎⠲"
  specimen_32: "⠁⠇⠇ ⠓⠥⠍⠁⠝ ⠃⠑⠊⠝⠛⠎ ⠁⠗⠑ ⠃⠕⠗⠝ ⠋⠗⠑⠑ ⠁⠝⠙ ⠑⠟⠥⠁⠇ ⠊⠝ ⠙⠊⠛⠝⠊⠞⠽ ⠁⠝⠙ ⠗⠊⠛⠓⠞⠎⠲ ⠞⠓⠑⠽ ⠁⠗⠑ ⠑⠝⠙⠕⠺⠑⠙ ⠺⠊⠞⠓ ⠗⠑⠁⠎⠕⠝ ⠁⠝⠙ ⠉⠕⠝⠎⠉⠊⠑⠝⠉⠑ ⠁⠝⠙ ⠎⠓⠕⠥⠇⠙ ⠁⠉⠞ ⠞⠕⠺⠁⠗⠙⠎ ⠕⠝⠑ ⠁⠝⠕⠞⠓⠑⠗ ⠊⠝ ⠁ ⠎⠏⠊⠗⠊⠞ ⠕⠋ ⠃⠗⠕⠞⠓⠑⠗⠓⠕⠕⠙⠲"
  specimen_21: "⠁⠇⠇ ⠓⠥⠍⠁⠝ ⠃⠑⠊⠝⠛⠎ ⠁⠗⠑ ⠃⠕⠗⠝ ⠋⠗⠑⠑ ⠁⠝⠙ ⠑⠟⠥⠁⠇ ⠊⠝ ⠙⠊⠛⠝⠊⠞⠽ ⠁⠝⠙ ⠗⠊⠛⠓⠞⠎⠲ ⠞⠓⠑⠽ ⠁⠗⠑ ⠑⠝⠙⠕⠺⠑⠙ ⠺⠊⠞⠓ ⠗⠑⠁⠎⠕⠝ ⠁⠝⠙ ⠉⠕⠝⠎⠉⠊⠑⠝⠉⠑ ⠁⠝⠙ ⠎⠓⠕⠥⠇⠙ ⠁⠉⠞ ⠞⠕⠺⠁⠗⠙⠎ ⠕⠝⠑ ⠁⠝⠕⠞⠓⠑⠗ ⠊⠝ ⠁ ⠎⠏⠊⠗⠊⠞ ⠕⠋ ⠃⠗⠕⠞⠓⠑⠗⠓⠕⠕⠙⠲\n⠑⠧⠑⠗⠽⠕⠝⠑ ⠊⠎ ⠑⠝⠞⠊⠞⠇⠑⠙ ⠞⠕ ⠁⠇⠇ ⠞⠓⠑ ⠗⠊⠛⠓⠞⠎ ⠁⠝⠙ ⠋⠗⠑⠑⠙⠕⠍⠎ ⠎⠑⠞ ⠋⠕⠗⠞⠓ ⠊⠝ ⠞⠓⠊⠎ ⠙⠑⠉⠇⠁⠗⠁⠞⠊⠕⠝⠂ ⠺⠊⠞⠓⠕⠥⠞ ⠙⠊⠎⠞⠊⠝⠉⠞⠊⠕⠝ ⠕⠋ ⠁⠝⠽ ⠅⠊⠝⠙⠂ ⠎⠥⠉⠓ ⠁⠎ ⠗⠁⠉⠑⠂ ⠉⠕⠇⠕⠥⠗⠂ ⠎⠑⠭⠂ ⠇⠁⠝⠛⠥⠁⠛⠑⠂ ⠗⠑⠇⠊⠛⠊⠕⠝⠂ ⠏⠕⠇⠊⠞⠊⠉⠁⠇ ⠕⠗ ⠕⠞⠓⠑⠗ ⠕⠏⠊⠝⠊⠕⠝⠂ ⠝⠁⠞⠊⠕⠝⠁⠇ ⠕⠗ ⠎⠕⠉⠊⠁⠇ ⠕⠗⠊⠛⠊⠝⠂ ⠏⠗⠕⠏⠑⠗⠞⠽⠂ ⠃⠊⠗⠞⠓ ⠕⠗ ⠕⠞⠓⠑⠗ ⠎⠞⠁⠞⠥⠎⠲"
  specimen_16: "⠁⠇⠇ ⠓⠥⠍⠁⠝ ⠃⠑⠊⠝⠛⠎ ⠁⠗⠑ ⠃⠕⠗⠝ ⠋⠗⠑⠑ ⠁⠝⠙ ⠑⠟⠥⠁⠇ ⠊⠝ ⠙⠊⠛⠝⠊⠞⠽ ⠁⠝⠙ ⠗⠊⠛⠓⠞⠎⠲ ⠞⠓⠑⠽ ⠁⠗⠑ ⠑⠝⠙⠕⠺⠑⠙ ⠺⠊⠞⠓ ⠗⠑⠁⠎⠕⠝ ⠁⠝⠙ ⠉⠕⠝⠎⠉⠊⠑⠝⠉⠑ ⠁⠝⠙ ⠎⠓⠕⠥⠇⠙ ⠁⠉⠞ ⠞⠕⠺⠁⠗⠙⠎ ⠕⠝⠑ ⠁⠝⠕⠞⠓⠑⠗ ⠊⠝ ⠁ ⠎⠏⠊⠗⠊⠞ ⠕⠋ ⠃⠗⠕⠞⠓⠑⠗⠓⠕⠕⠙⠲\n⠑⠧⠑⠗⠽⠕⠝⠑ ⠊⠎ ⠑⠝⠞⠊⠞⠇⠑⠙ ⠞⠕ ⠁⠇⠇ ⠞⠓⠑ ⠗⠊⠛⠓⠞⠎ ⠁⠝⠙ ⠋⠗⠑⠑⠙⠕⠍⠎ ⠎⠑⠞ ⠋⠕⠗⠞⠓ ⠊⠝ ⠞⠓⠊⠎ ⠙⠑⠉⠇⠁⠗⠁⠞⠊⠕⠝⠂ ⠺⠊⠞⠓⠕⠥⠞ ⠙⠊⠎⠞⠊⠝⠉⠞⠊⠕⠝ ⠕⠋ ⠁⠝⠽ ⠅⠊⠝⠙⠂ ⠎⠥⠉⠓ ⠁⠎ ⠗⠁⠉⠑⠂ ⠉⠕⠇⠕⠥⠗⠂ ⠎⠑⠭⠂ ⠇⠁⠝⠛⠥⠁⠛⠑⠂ ⠗⠑⠇⠊⠛⠊⠕⠝⠂ ⠏⠕⠇⠊⠞⠊⠉⠁⠇ ⠕⠗ ⠕⠞⠓⠑⠗ ⠕⠏⠊⠝⠊⠕⠝⠂ ⠝⠁⠞⠊⠕⠝⠁⠇ ⠕⠗ ⠎⠕⠉⠊⠁⠇ ⠕⠗⠊⠛⠊⠝⠂ ⠏⠗⠕⠏⠑⠗⠞⠽⠂ ⠃⠊⠗⠞⠓ ⠕⠗ ⠕⠞⠓⠑⠗ ⠎⠞⠁⠞⠥⠎⠲\n⠋⠥⠗⠞⠓⠑⠗⠍⠕⠗⠑⠂ ⠝⠕ ⠙⠊⠎⠞⠊⠝⠉⠞⠊⠕⠝ ⠎⠓⠁⠇⠇ ⠃⠑ ⠍⠁⠙⠑ ⠕⠝ ⠞⠓⠑ ⠃⠁⠎⠊⠎ ⠕⠋ ⠞⠓⠑ ⠏⠕⠇⠊⠞⠊⠉⠁⠇⠂ ⠚⠥⠗⠊⠎⠙⠊⠉⠞⠊⠕⠝⠁⠇ ⠕⠗ ⠊⠝⠞⠑⠗⠝⠁⠞⠊⠕⠝⠁⠇ ⠎⠞⠁⠞⠥⠎ ⠕⠋ ⠞⠓⠑ ⠉⠕⠥⠝⠞⠗⠽ ⠕⠗ ⠞⠑⠗⠗⠊⠞⠕⠗⠽ ⠞⠕ ⠺⠓⠊⠉⠓ ⠁ ⠏⠑⠗⠎⠕⠝ ⠃⠑⠇⠕⠝⠛⠎⠂ ⠺⠓⠑⠞⠓⠑⠗ ⠊⠞ ⠃⠑ ⠊⠝⠙⠑⠏⠑⠝⠙⠑⠝⠞⠂ ⠞⠗⠥⠎⠞⠂ ⠝⠕⠝⠤⠎⠑⠇⠋⠤⠛⠕⠧⠑⠗⠝⠊⠝⠛ ⠕⠗ ⠥⠝⠙⠑⠗ ⠁⠝⠽ ⠕⠞⠓⠑⠗ ⠇⠊⠍⠊⠞⠁⠞⠊⠕⠝ ⠕⠋ ⠎⠕⠧⠑⠗⠑⠊⠛⠝⠞⠽⠲"
}
