id: "es"
language: "es"
script: "Latn"
name: "Spanish"
autonym: "Español"
population: 487664084
region: "AD"
region: "AR"
region: "BO"
region: "BR"
region: "BZ"
region: "CL"
region: "CO"
region: "CR"
region: "CU"
region: "CW"
region: "DE"
region: "DO"
region: "EA"
region: "EC"
region: "ES"
region: "FR"
region: "GI"
region: "GQ"
region: "GT"
region: "HN"
region: "IC"
region: "MA"
region: "MX"
region: "NI"
region: "PA"
region: "PE"
region: "PH"
region: "PR"
region: "PT"
region: "PY"
region: "RO"
region: "SV"
region: "SX"
region: "TT"
region: "US"
region: "UY"
region: "VE"
exemplar_chars {
  base: "a á b c d e é f g h i í j k l m n ñ o ó p q r s t u ú ü v w x y z"
  auxiliary: "ª à ă â å ä ã ā æ ç è ĕ ê ë ē ì ĭ î ï ī º ò ŏ ô ö ø ō œ ù ŭ û ū ý ÿ"
  marks: "◌́ ◌̃ ◌̈"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ¡ ? ¿ . … \' ‘ ’ \" “ ” « » ( ) [ ] § @ * / \\ & # † ‡ ′ ″"
  index: "A B C D E F G H I J K L M N Ñ O P Q R S T U V W X Y Z"
}
sample_text {
  masthead_full: "TtOo"
  masthead_partial: "Dd"
  styles: "Considerando que la libertad, la justicia"
  tester: "Considerando que el desconocimiento y el menosprecio de los derechos"
  poster_sm: "Considerando"
  poster_md: "La Asamblea"
  poster_lg: "Todos"
  specimen_48: "Proclama la presente Declaración Universal de Derechos Humanos"
  specimen_36: "Considerando también esencial promover el desarrollo de relaciones amistosas entre las naciones,\nLa Asamblea General"
  specimen_32: "Considerando que una concepción común de estos derechos y libertades es de la mayor importancia para el pleno cumplimiento de dicho compromiso,"
  specimen_21: "Considerando que la libertad, la justicia y la paz en el mundo tienen por base el reconocimiento de la dignidad intrínseca y de los derechos iguales e inalienables de todos los miembros de la familia humana,\nConsiderando esencial que los derechos humanos sean protegidos por un régimen de Derecho, a fin de que el hombre no se vea compelido al supremo recurso de la rebelión contra la tiranía y la opresión,"
  specimen_16: "Considerando que la libertad, la justicia y la paz en el mundo tienen por base el reconocimiento de la dignidad intrínseca y de los derechos iguales e inalienables de todos los miembros de la familia humana,\nConsiderando que el desconocimiento y el menosprecio de los derechos humanos han originado actos de barbarie ultrajantes para la conciencia de la humanidad; y que se ha proclamado, como la aspiración más elevada del hombre, el advenimiento de un mundo en que los seres humanos, liberados del temor y de la miseria, disfruten de la libertad de palabra y de la libertad de creencias,"
}
