id: "ese_Latn"
language: "ese"
script: "Latn"
name: "Ese Ejja"
sample_text {
  masthead_full: "OoJj"
  masthead_partial: "Aa"
  styles: "O\nj\nj\na\nñ\na\n \ne\ns\ne\nj\nj\na\n \no\nj\nj\na\nñ\na\n "
  tester: "O\nj\nj\na\nñ\na\n \ne\ns\ne\nj\nj\na\n \no\nj\nj\na\nñ\na\n \no\ny\na\nj\na\n \ny\no\nj\nj"
  poster_sm: "O\nj\nj\na\nñ\na"
  poster_md: "O\nj\nj\na\nñ"
  poster_lg: "O\nj"
  specimen_48: "O\nj\nj\na\nñ\na\n \ne\ns\ne\nj\nj\na\n \no\nj\nj\na\nñ\na\n \no\ny\na\nj\na\n \ny\no\nj\nj"
  specimen_36: "O\nj\nj\na\nñ\na\n \ne\ns\ne\nj\nj\na\n \no\nj\nj\na\nñ\na\n \no\ny\na\nj\na\n \ny\no\nj\nj\na\ny\na\n \nc\nu\na\ny\na\nn\ni\n \nq\nu\ni\na\np\na\nm\ne"
  specimen_32: "O\nj\nj\na\nñ\na\n \ne\ns\ne\nj\nj\na\n \no\nj\nj\na\nñ\na\n \no\ny\na\nj\na\n \ny\no\nj\nj\na\ny\na\n \nc\nu\na\ny\na\nn\ni\n \nq\nu\ni\na\np\na\nm\ne\n \no\ny\na\nj\na\ny\no\nj\nj\na\ny\na\n \nq\nu\ni\na\np\na"
  specimen_21: "O\nj\nj\na\nñ\na\n \ne\ns\ne\nj\nj\na\n \no\nj\nj\na\nñ\na\n \no\ny\na\nj\na\n \ny\no\nj\nj\na\ny\na\n \nc\nu\na\ny\na\nn\ni\n \nq\nu\ni\na\np\na\nm\ne\n \no\ny\na\nj\na\ny\no\nj\nj\na\ny\na\n \nq\nu\ni\na\np\na\nm\ne\n \no\nj\nj\na\nñ\na\n \ne\ns\ne\ny\na\n \nq\nu\ni\na\np\na\nm\ne\n \nq\nu\ni\na\n \nt\na\ni\n \nj\nj\na\ns\nh\na\nu\na\nb\na\nt\na\ni\nq\nu\ni\na\nn\ni\n \ne\nc\nu\ne\ny\na\n \ne\np\ne\nj\nj\ni\n \nj\na\ny\no\n \nj\nj\na\ny\na\n \no"
  specimen_16: "O\nj\nj\na\nñ\na\n \ne\ns\ne\nj\nj\na\n \no\nj\nj\na\nñ\na\n \no\ny\na\nj\na\n \ny\no\nj\nj\na\ny\na\n \nc\nu\na\ny\na\nn\ni\n \nq\nu\ni\na\np\na\nm\ne\n \no\ny\na\nj\na\ny\no\nj\nj\na\ny\na\n \nq\nu\ni\na\np\na\nm\ne\n \no\nj\nj\na\nñ\na\n \ne\ns\ne\ny\na\n \nq\nu\ni\na\np\na\nm\ne\n \nq\nu\ni\na\n \nt\na\ni\n \nj\nj\na\ns\nh\na\nu\na\nb\na\nt\na\ni\nq\nu\ni\na\nn\ni\n \ne\nc\nu\ne\ny\na\n \ne\np\ne\nj\nj\ni\n \nj\na\ny\no\n \nj\nj\na\ny\na\n \no\nj\nj\na\nñ\na\n \nj\na\nj\nj\ni\n \no\nj\nj\na\nñ\na\nj\na\na\ns\ns\ni\n \ne\ns\ne\ny\na\nj\na\ny\no\nj\nj\na\n.\nO\nj\nj\na\nñ\na\n \ne\ns\ne\nj\nj\na\n \no\nj\nj\na\nñ\na\n \no\ny\na\nj\na\n \ny\no\nj\nj\na\ny\na\n \nc\nu\na\ny\na\nn\ni\n \nq\nu\ni\na\np\na\nm\ne\n \no\ny\na\nj\na\ny\no\nj\nj\na\ny\na\n \nq\nu\ni\na\np\na\nm\ne\n \no\nj\nj\na\nñ\na\n \ne\ns\ne\ny\na\n "
}
