id: "eve_Cyrl"
language: "eve"
script: "Cyrl"
name: "Even"
sample_text {
  masthead_full: "БбЭэ"
  masthead_partial: "Йй"
  styles: "Б\nэ\nй\nи\nл\n \nб\nо\nк\nэ\nт\nч\nу\nр\n \nо\nм\nэ\nн\n \nх"
  tester: "Б\nэ\nй\nи\nл\n \nб\nо\nк\nэ\nт\nч\nу\nр\n \nо\nм\nэ\nн\n \nх\nи\nл\nк\nи\nч\n \nн\nя\nн\n "
  poster_sm: "Б\nэ\nй\nи\nл\n "
  poster_md: "Б\nэ\nй\nи\nл"
  poster_lg: "Б\nэ"
  specimen_48: "Б\nэ\nй\nи\nл\n \nб\nо\nк\nэ\nт\nч\nу\nр\n \nо\nм\nэ\nн\n \nх\nи\nл\nк\nи\nч\n \nн\nя\nн\n "
  specimen_36: "Б\nэ\nй\nи\nл\n \nб\nо\nк\nэ\nт\nч\nу\nр\n \nо\nм\nэ\nн\n \nх\nи\nл\nк\nи\nч\n \nн\nя\nн\n \nу\nр\nу\nм\nк\nэ\nр\n \nб\nа\nл\nд\nа\nр\nи\nт\nн\nо\n,\n "
  specimen_32: "Б\nэ\nй\nи\nл\n \nб\nо\nк\nэ\nт\nч\nу\nр\n \nо\nм\nэ\nн\n \nх\nи\nл\nк\nи\nч\n \nн\nя\nн\n \nу\nр\nу\nм\nк\nэ\nр\n \nб\nа\nл\nд\nа\nр\nи\nт\nн\nо\n,\n \nт\nе\nм\nи\n \nн\nо\nҥ\nа\nр\nд\nу\nк\n \nэ\nг\nд\nь\nэ\nн"
  specimen_21: "Б\nэ\nй\nи\nл\n \nб\nо\nк\nэ\nт\nч\nу\nр\n \nо\nм\nэ\nн\n \nх\nи\nл\nк\nи\nч\n \nн\nя\nн\n \nу\nр\nу\nм\nк\nэ\nр\n \nб\nа\nл\nд\nа\nр\nи\nт\nн\nо\n,\n \nт\nе\nм\nи\n \nн\nо\nҥ\nа\nр\nд\nу\nк\n \nэ\nг\nд\nь\nэ\nн\n \nҥ\nи\n‐\nд\nа\n \nа\nч\nч\nа\n.\n \nБ\nэ\nй\nи\nл\n \nб\nө\nк\nэ\nт\nч\nу\nр\n \nм\nэ\nн\n \nд\nо\nл\nа\nн\n \nа\nк\nа\nг\nч\nи\nм\nу\nр\n \nб\nи\nн\nн\nэ\nт\nы\nн\n.\nБ\nэ\nй\nи\nл\n \nб\nо\nк\nэ\nт\nч\nу\nр\n \nо\nм\nэ\nн\n \nх\nи\nл\nк\nи"
  specimen_16: "Б\nэ\nй\nи\nл\n \nб\nо\nк\nэ\nт\nч\nу\nр\n \nо\nм\nэ\nн\n \nх\nи\nл\nк\nи\nч\n \nн\nя\nн\n \nу\nр\nу\nм\nк\nэ\nр\n \nб\nа\nл\nд\nа\nр\nи\nт\nн\nо\n,\n \nт\nе\nм\nи\n \nн\nо\nҥ\nа\nр\nд\nу\nк\n \nэ\nг\nд\nь\nэ\nн\n \nҥ\nи\n‐\nд\nа\n \nа\nч\nч\nа\n.\n \nБ\nэ\nй\nи\nл\n \nб\nө\nк\nэ\nт\nч\nу\nр\n \nм\nэ\nн\n \nд\nо\nл\nа\nн\n \nа\nк\nа\nг\nч\nи\nм\nу\nр\n \nб\nи\nн\nн\nэ\nт\nы\nн\n.\nБ\nэ\nй\nи\nл\n \nб\nо\nк\nэ\nт\nч\nу\nр\n \nо\nм\nэ\nн\n \nх\nи\nл\nк\nи\nч\n \nн\nя\nн\n \nу\nр\nу\nм\nк\nэ\nр\n \nб\nа\nл\nд\nа\nр\nи\nт\nн\nо\n,\n \nт\nе\nм\nи\n \nн\nо\nҥ\nа\nр\nд\nу\nк\n \nэ\nг\nд\nь\nэ\nн\n \nҥ\nи\n‐\nд\nа\n \nа\nч\nч\nа\n.\n \nБ\nэ\nй\nи\nл\n \nб\nө\nк\nэ\nт\nч\nу\nр\n \nм\nэ\nн\n \nд\nо\nл\nа\nн\n \nа\nк\nа\nг\nч\nи\nм\nу\nр\n \nб\nи\nн\nн\nэ\nт\nы\nн\n.\nБ\nэ\nй\nи\nл\n \nб\nо\nк\nэ\nт\nч\nу\nр\n \nо\nм\nэ\nн\n \nх\nи\nл\nк"
}
