id: "ext_Latn"
language: "ext"
script: "Latn"
name: "Extremaduran"
population: 245077
region: "ES"
sample_text {
  masthead_full: "TtOo"
  masthead_partial: "Ll"
  styles: "T\no\nl\no\ns\n \nh\no\nm\nb\nr\ni\ns\n \nn\na\nc\ni\nn\n \nl"
  tester: "T\no\nl\no\ns\n \nh\no\nm\nb\nr\ni\ns\n \nn\na\nc\ni\nn\n \nl\ni\nb\nr\ni\ns\n \ni\n \ne\ng"
  poster_sm: "T\no\nl\no\ns\n "
  poster_md: "T\no\nl\no\ns"
  poster_lg: "T\no"
  specimen_48: "T\no\nl\no\ns\n \nh\no\nm\nb\nr\ni\ns\n \nn\na\nc\ni\nn\n \nl\ni\nb\nr\ni\ns\n \ni\n \ne\ng"
  specimen_36: "T\no\nl\no\ns\n \nh\no\nm\nb\nr\ni\ns\n \nn\na\nc\ni\nn\n \nl\ni\nb\nr\ni\ns\n \ni\n \ne\ng\nu\na\nl\ni\ns\n \ne\nn\n \nd\ni\ng\nn\ni\ná\n \ni\n \nd\ne"
  specimen_32: "T\no\nl\no\ns\n \nh\no\nm\nb\nr\ni\ns\n \nn\na\nc\ni\nn\n \nl\ni\nb\nr\ni\ns\n \ni\n \ne\ng\nu\na\nl\ni\ns\n \ne\nn\n \nd\ni\ng\nn\ni\ná\n \ni\n \nd\ne\nr\ne\nc\nh\nu\ns\n \ni\n,\n \nc\no\nm\nu\n \ng\na\ns\nt\na"
  specimen_21: "T\no\nl\no\ns\n \nh\no\nm\nb\nr\ni\ns\n \nn\na\nc\ni\nn\n \nl\ni\nb\nr\ni\ns\n \ni\n \ne\ng\nu\na\nl\ni\ns\n \ne\nn\n \nd\ni\ng\nn\ni\ná\n \ni\n \nd\ne\nr\ne\nc\nh\nu\ns\n \ni\n,\n \nc\no\nm\nu\n \ng\na\ns\nt\na\nn\n \nr\na\nz\nó\nn\n \ni\n \nc\no\nn\nc\né\nn\nc\ni\na\n,\n \ne\nb\ni\nn\n \nc\no\nm\np\no\nr\nt\na\nl\n-\ns\ne\n \nc\no\nm\nu\n \nh\ne\nr\nm\na\nn\nu\ns\n \nl\no\ns\n \nu\nn\nu\ns\n \nc\no\nn\no\ns\n \no\nt\nr\nu\ns\n.\nT\no\nl\no\ns\n \nh\no"
  specimen_16: "T\no\nl\no\ns\n \nh\no\nm\nb\nr\ni\ns\n \nn\na\nc\ni\nn\n \nl\ni\nb\nr\ni\ns\n \ni\n \ne\ng\nu\na\nl\ni\ns\n \ne\nn\n \nd\ni\ng\nn\ni\ná\n \ni\n \nd\ne\nr\ne\nc\nh\nu\ns\n \ni\n,\n \nc\no\nm\nu\n \ng\na\ns\nt\na\nn\n \nr\na\nz\nó\nn\n \ni\n \nc\no\nn\nc\né\nn\nc\ni\na\n,\n \ne\nb\ni\nn\n \nc\no\nm\np\no\nr\nt\na\nl\n-\ns\ne\n \nc\no\nm\nu\n \nh\ne\nr\nm\na\nn\nu\ns\n \nl\no\ns\n \nu\nn\nu\ns\n \nc\no\nn\no\ns\n \no\nt\nr\nu\ns\n.\nT\no\nl\no\ns\n \nh\no\nm\nb\nr\ni\ns\n \nn\na\nc\ni\nn\n \nl\ni\nb\nr\ni\ns\n \ni\n \ne\ng\nu\na\nl\ni\ns\n \ne\nn\n \nd\ni\ng\nn\ni\ná\n \ni\n \nd\ne\nr\ne\nc\nh\nu\ns\n \ni\n,\n \nc\no\nm\nu\n \ng\na\ns\nt\na\nn\n \nr\na\nz\nó\nn\n \ni\n \nc\no\nn\nc\né\nn\nc\ni\na\n,\n \ne\nb\ni\nn\n \nc\no\nm\np\no\nr\nt\na\nl\n-\ns\ne\n \nc\no\nm\nu\n \nh\ne\nr\nm\na\nn\nu\ns\n \nl\no\ns\n \nu\nn\nu\ns\n \nc"
}
