id: "fa"
language: "fa"
script: "Arab"
name: "Persian"
population: 84465446
region: "AE"
region: "AF"
region: "IQ"
region: "IR"
region: "OM"
region: "PK"
region: "QA"
region: "TJ"
exemplar_chars {
  base: "ً ٍ ٌ ّ ٔ آ ا ء أ ؤ ئ ب پ ت ث ج چ ح خ د ذ ر ز ژ س ش ص ض ط ظ ع غ ف ق ک گ ل م ن و ه ة ی"
  auxiliary: "ـ‌‍‎‏ َ ِ ُ ْ ٖ ٰ إ ك ى ي"
  numerals: "‎ , ٫ ٬ . % ٪ ‰ ؉ + − 0۰ 1۱ 2۲ 3۳ 4۴ 5۵ 6۶ 7۷ 8۸ 9۹"
  punctuation: "- ‐ ‑ ، ٫ ٬ ؛ : ! ؟ . … ‹ › « » ( ) [ ] * / \\"
  index: "آ ا ب پ ت ث ج چ ح خ د ذ ر ز ژ س ش ص ض ط ظ ع غ ف ق ک گ ل م ن و ه ی"
}
sample_text {
  masthead_full: "تماف"
  masthead_partial: "رد"
  styles: "از آنجا که شناسائی حیثیت ذاتی کلیهٔ اعضای"
  tester: "از آنجا که عدم شناسائی و تحقیر حقوق بشر منتهی به اعمال وحشیانه‌ای"
  poster_sm: "از آنجا که"
  poster_md: "مجمع عمومی"
  poster_lg: "تمام"
  specimen_48: "تمام افراد بشر آزاد بدنیا میایند و از لحاظ حیثیت و حقوق با هم"
  specimen_36: "احدی را نمیتوان تحت شکنجه یا مجازات یا رفتاری قرار داد که ظالمانه و یا بر خلاف انسانیت و شئون بشری یا موهن باشد."
  specimen_32: "در برابر اعمالی که حقوق اساسی فرد را مورد تجاوز قرار بدهد و آن حقوق بوسیله قانون اساسی یا قانون دیگری برای او شناخته‌شده باشد، هر کس حق رجوع مؤثر بمحاکم ملیِ صالحه دارد."
  specimen_21: "احدی نمیتواند خودسرانه توقیف ‐ حبس یا تبعید بشود.\nهر کس با مساوات کامل حق دارد که دعوایش بوسیله دادگاه مستقل و بی‌طرفی، منصفانه و علناً رسیدگی بشود و چنین دادگاهی درباره حقوق و الزامات او یا هر اتهام جزائی که باو توجه پیدا کرده باشد إتخاذ تصمیم بنماید.\nاحدی در زندگی خصوصی، امور خانوادگی، اقامتگاه یا مکاتبات خود، نباید مورد مداخله‌های خودسرانه واقع شود و شرافت و اسم و رسمش نباید مورد حمله قرار گیرد. هر کس حق دارد که در مقابل اینگونه مداخلات و حملات مورد حمایت قانون قرار گیرد."
  specimen_16: "هر کس حق دارد که از آزادی فکر، وجدان و مذهب بهره‌مند شود. این حق متضمن آزادی تغییر مذهب یا عقیده و همچنین متضمن آزادی اظهار عقیده و ایمان میباشد و نیز شامل تعلیمات مذهبی و اجرای مراسم دینی است. هر کس میتواند از این حقوق منفرداً یا مجتمعاً بطور خصوصی یا بطور عمومی برخوردار باشد.\nهر کس حق آزادی عقیده و بیان دارد و حق مزبور شامل آنست که از داشتن عقاید خود بیم و اضطرابی نداشته باشد و در کسب اطلاعات و افکار و در اخذ و انتشار آن بتمام وسائل ممکن و بدون ملاحظات مرزی آزاد باشد.\nهر کس بعنوان عضو اجتماع حق امنیت اجتماعی دارد و مجاز است بوسیله مساعی ملی و همکاری بین‌المللی حقوق اقتصادی و اجتماعی و فرهنگی خود را که لازمهٔ مقام و نمود آزادانه شخصیت او است با رعایت تشکیلات و منابع هر کشور بدست آورد."
}
