id: "ff"
language: "ff"
script: "Latn"
name: "Fulah"
autonym: "Futa Tooro"
population: 7788902
region: "BF"
region: "CM"
region: "GH"
region: "GM"
region: "GN"
region: "GW"
region: "LR"
region: "MR"
region: "NE"
region: "NG"
region: "SL"
region: "SN"
exemplar_chars {
  base: "a b ɓ c d ɗ e f g h i j k l m n ñ ŋ o p r s t u w y ƴ"
  auxiliary: "q v x z"
  marks: "◌̃"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B Ɓ C D Ɗ E F G H I J K L M N Ñ Ŋ O P R S T U W Y Ƴ"
}
sample_text {
  masthead_full: "NnEe"
  masthead_partial: "Dd"
  styles: "TAWEEDE NDELO HETTAARE, NUNDHAL E BHUTTU ADUNAAN"
  tester: "TAWEEDE, MADDYEEDE E BIKKHTAARE HANDANDHI NEDDHO WONUNO SABU AAWASEEDYI"
  poster_sm: "TAWEEDE, SINAA"
  poster_md: "TAWEEDE KO"
  poster_lg: "FOW"
  specimen_48: "TAWEEDE LAAMATEERIIDYI WONDHI E ADUNA ON, TAWAADHI KA SUUSEETI"
  specimen_36: "TAWEEDE KO HEBHBHITANNDE FOTTANAANDE E DHII HANDIIDYI E NDEE HETTAARE BHURI KELDHUDE E FII HUNNUGOL NDII AHADI;"
  specimen_32: "NEDDHANKE EN FOW DYIBINTE NO HETTII NO FOTA E DHI FOW, E NDIMU E HANDANDHI. BHE DYIBINDINTE E HAGGHIL E FAAMU ; HIBHE HAANI DYOGONDIRDE E NDER HAGGHIL NEENEGOOTAANKAAKU."
  specimen_21: "MO KALA NO WAAWI TIPPUDE E DHII SARTIIDYI NDII AHADI, DHUN NON REWAA LENYOL, MBAADI BHANNDU, NOONE AWRA, NOONE DHENGAL, DIINA MAA DAWLA WOO; DHUN REWA NGALU, DYIBBIANDE MAA KALA KO NANDI E DHUN.\nGOOTO NYAAWITIRTAAKE DAWLA MAA SARIYA LEYDI MUUN, WONI HETTIINDI MAA LAAMAANDI.\nKALA NEDDHO NO HANNDI E GURDAN, HETTAARE E HOOLORDE DADHUGOL."
  specimen_16: "GOOTO DYOGORTAAKE MATTYANGAAKU, KURKAADUYAAGAL E NGEYNGU YIMBHE.\nGOOTO TUDHETAAKE E LETTE, TAMPERE, YANNGI MAA E KUUDHE WIRTAYDHE.\nKALA NO HANNDI ANDITANEEDE NOKKU FOW NDIMANKAAKU MUN.\nSARIYA ON NO POTA E FOW. KALA NO HANNDI E DANDIREEDE ON SARIYA, KO REWA BHURNONDIRAL. FOW NO HANNDI E DANDEEDE TELEMMA HAASINGAAKU BONNITATAYNGU OO SARIYA.\nKALA TOONYAADHO NO HANNDI E WULLITAGOL KA TYUUDHI SARIYA LEYDI MUN.\nGOOTO GASIRTAAKE NANGIREEDE NII TUN, DYOGEE, RADHEE KA LEYDI MUN.\nKALA NO HAANAA NDYENTEADE, SIFOO KA MBATU, YEESO NYAAWOOBHE NUNDHUBHE, ADO O WADHEEDE SARIYA, WONI KO O TOONYUDHO MAA KO O TOONYAADHO."
}
