id: "fuf_Latn"
language: "fuf"
script: "Latn"
name: "Pular"
sample_text {
  masthead_full: "NnEe"
  masthead_partial: "Dd"
  styles: "N\nE\nD\nD\nH\nA\nN\nK\nE\n \nE\nN\n \nF\nO\nW\n \nD\nY\nI\nB"
  tester: "N\nE\nD\nD\nH\nA\nN\nK\nE\n \nE\nN\n \nF\nO\nW\n \nD\nY\nI\nB\nI\nN\nT\nE\n \nN\nO\n \nH\nE"
  poster_sm: "N\nE\nD\nD\nH\nA"
  poster_md: "N\nE\nD\nD\nH"
  poster_lg: "N\nE"
  specimen_48: "N\nE\nD\nD\nH\nA\nN\nK\nE\n \nE\nN\n \nF\nO\nW\n \nD\nY\nI\nB\nI\nN\nT\nE\n \nN\nO\n \nH\nE"
  specimen_36: "N\nE\nD\nD\nH\nA\nN\nK\nE\n \nE\nN\n \nF\nO\nW\n \nD\nY\nI\nB\nI\nN\nT\nE\n \nN\nO\n \nH\nE\nT\nT\nI\nI\n \nN\nO\n \nF\nO\nT\nA\n \nE\n \nD\nH\nI\n \nF"
  specimen_32: "N\nE\nD\nD\nH\nA\nN\nK\nE\n \nE\nN\n \nF\nO\nW\n \nD\nY\nI\nB\nI\nN\nT\nE\n \nN\nO\n \nH\nE\nT\nT\nI\nI\n \nN\nO\n \nF\nO\nT\nA\n \nE\n \nD\nH\nI\n \nF\nO\nW\n,\n \nE\n \nN\nD\nI\nM\nU\n \nE\n \nH\nA\nN\nD\nA\nN"
  specimen_21: "N\nE\nD\nD\nH\nA\nN\nK\nE\n \nE\nN\n \nF\nO\nW\n \nD\nY\nI\nB\nI\nN\nT\nE\n \nN\nO\n \nH\nE\nT\nT\nI\nI\n \nN\nO\n \nF\nO\nT\nA\n \nE\n \nD\nH\nI\n \nF\nO\nW\n,\n \nE\n \nN\nD\nI\nM\nU\n \nE\n \nH\nA\nN\nD\nA\nN\nD\nH\nI\n.\n \nB\nH\nE\n \nD\nY\nI\nB\nI\nN\nD\nI\nN\nT\nE\n \nE\n \nH\nA\nG\nG\nH\nI\nL\n \nE\n \nF\nA\nA\nM\nU\n \n;\n \nH\nI\nB\nH\nE\n \nH\nA\nA\nN\nI\n \nD\nY\nO\nG\nO\nN\nD\nI\nR\nD\nE\n \nE\n \nN\nD\nE\nR\n \nH\nA\nG\nG\nH\nI\nL\n \nN"
  specimen_16: "N\nE\nD\nD\nH\nA\nN\nK\nE\n \nE\nN\n \nF\nO\nW\n \nD\nY\nI\nB\nI\nN\nT\nE\n \nN\nO\n \nH\nE\nT\nT\nI\nI\n \nN\nO\n \nF\nO\nT\nA\n \nE\n \nD\nH\nI\n \nF\nO\nW\n,\n \nE\n \nN\nD\nI\nM\nU\n \nE\n \nH\nA\nN\nD\nA\nN\nD\nH\nI\n.\n \nB\nH\nE\n \nD\nY\nI\nB\nI\nN\nD\nI\nN\nT\nE\n \nE\n \nH\nA\nG\nG\nH\nI\nL\n \nE\n \nF\nA\nA\nM\nU\n \n;\n \nH\nI\nB\nH\nE\n \nH\nA\nA\nN\nI\n \nD\nY\nO\nG\nO\nN\nD\nI\nR\nD\nE\n \nE\n \nN\nD\nE\nR\n \nH\nA\nG\nG\nH\nI\nL\n \nN\nE\nE\nN\nE\nG\nO\nO\nT\nA\nA\nN\nK\nA\nA\nK\nU\n.\nN\nE\nD\nD\nH\nA\nN\nK\nE\n \nE\nN\n \nF\nO\nW\n \nD\nY\nI\nB\nI\nN\nT\nE\n \nN\nO\n \nH\nE\nT\nT\nI\nI\n \nN\nO\n \nF\nO\nT\nA\n \nE\n \nD\nH\nI\n \nF\nO\nW\n,\n \nE\n \nN\nD\nI\nM\nU\n \nE\n \nH\nA\nN\nD\nA\nN\nD\nH\nI\n.\n \nB\nH\nE\n \nD\nY\nI\nB\nI\nN\nD\nI\nN\nT\nE\n \nE\n \nH\nA\nG\nG\nH\nI\nL\n \nE\n \nF\nA\nA\nM\nU\n "
}
