id: "fuf_Adlm"
language: "fuf"
script: "Adlm"
name: "Pular, Adlam"
sample_text {
  masthead_full: "𞤋𞤭𞤐𞤲"
  masthead_partial: "𞤀𞤢"
  styles: "𞤋\n𞤲\n𞥆\n𞤢\n𞤥\n𞤢\n \n𞤢\n𞥄\n𞤣\n𞤫\n𞥅\n𞤶\n𞤭\n \n𞤬\n𞤮\n𞤬\n \n𞤨\n𞤮\n𞤼"
  tester: "𞤋\n𞤲\n𞥆\n𞤢\n𞤥\n𞤢\n \n𞤢\n𞥄\n𞤣\n𞤫\n𞥅\n𞤶\n𞤭\n \n𞤬\n𞤮\n𞤬\n \n𞤨\n𞤮\n𞤼\n𞤭\n،\n \n𞤲\n\'\n𞤣\n𞤭\n𞤥\n𞤯\n𞤭\n𞤣"
  poster_sm: "𞤋\n𞤲\n𞥆\n𞤢\n𞤥\n𞤢"
  poster_md: "𞤋\n𞤲\n𞥆\n𞤢\n𞤥"
  poster_lg: "𞤋\n𞤲"
  specimen_48: "𞤋\n𞤲\n𞥆\n𞤢\n𞤥\n𞤢\n \n𞤢\n𞥄\n𞤣\n𞤫\n𞥅\n𞤶\n𞤭\n \n𞤬\n𞤮\n𞤬\n \n𞤨\n𞤮\n𞤼\n𞤭\n،\n \n𞤲\n\'\n𞤣\n𞤭\n𞤥\n𞤯\n𞤭\n𞤣"
  specimen_36: "𞤋\n𞤲\n𞥆\n𞤢\n𞤥\n𞤢\n \n𞤢\n𞥄\n𞤣\n𞤫\n𞥅\n𞤶\n𞤭\n \n𞤬\n𞤮\n𞤬\n \n𞤨\n𞤮\n𞤼\n𞤭\n،\n \n𞤲\n\'\n𞤣\n𞤭\n𞤥\n𞤯\n𞤭\n𞤣\n𞤭\n \n𞤫\n \n𞤶\n𞤭\n𞤦\n𞤭\n𞤲\n𞤢\n𞤲\n𞥆\n𞤣\n𞤫\n \n𞤼\n𞤮\n \n𞤦\n𞤢\n𞤲"
  specimen_32: "𞤋\n𞤲\n𞥆\n𞤢\n𞤥\n𞤢\n \n𞤢\n𞥄\n𞤣\n𞤫\n𞥅\n𞤶\n𞤭\n \n𞤬\n𞤮\n𞤬\n \n𞤨\n𞤮\n𞤼\n𞤭\n،\n \n𞤲\n\'\n𞤣\n𞤭\n𞤥\n𞤯\n𞤭\n𞤣\n𞤭\n \n𞤫\n \n𞤶\n𞤭\n𞤦\n𞤭\n𞤲\n𞤢\n𞤲\n𞥆\n𞤣\n𞤫\n \n𞤼\n𞤮\n \n𞤦\n𞤢\n𞤲\n𞥆\n𞤺\n𞤫\n \n𞤸\n𞤢\n𞤳\n𞥆\n𞤫\n𞥅\n𞤶\n𞤭\n.\n \n𞤉\n𞤩\n𞤫\n \n𞤲\n\'\n𞤺\n𞤮"
  specimen_21: "𞤋\n𞤲\n𞥆\n𞤢\n𞤥\n𞤢\n \n𞤢\n𞥄\n𞤣\n𞤫\n𞥅\n𞤶\n𞤭\n \n𞤬\n𞤮\n𞤬\n \n𞤨\n𞤮\n𞤼\n𞤭\n،\n \n𞤲\n\'\n𞤣\n𞤭\n𞤥\n𞤯\n𞤭\n𞤣\n𞤭\n \n𞤫\n \n𞤶\n𞤭\n𞤦\n𞤭\n𞤲\n𞤢\n𞤲\n𞥆\n𞤣\n𞤫\n \n𞤼\n𞤮\n \n𞤦\n𞤢\n𞤲\n𞥆\n𞤺\n𞤫\n \n𞤸\n𞤢\n𞤳\n𞥆\n𞤫\n𞥅\n𞤶\n𞤭\n.\n \n𞤉\n𞤩\n𞤫\n \n𞤲\n\'\n𞤺\n𞤮\n𞥅\n𞤣\n𞤭\n \n𞤥\n𞤭\n𞥅\n𞤶\n𞤮\n \n𞤫\n \n𞤸\n𞤢\n𞤳\n𞥆\n𞤭\n𞤤\n𞤢\n𞤲\n𞤼\n𞤢\n𞥄\n𞤺\n𞤢\n𞤤\n \n𞤫\n𞤼\n𞤫\n \n𞤫\n𞤩\n𞤫\n \n𞤨\n𞤮\n𞤼\n𞤭\n \n𞤸\n𞤵\n𞥅\n𞤬\n𞤮\n \n𞤲\n\'\n𞤣\n𞤭\n𞤪\n𞤣\n𞤫\n \n𞤫\n \n𞤲\n\'\n𞤣\n𞤫\n𞤪\n \n𞤩\n \n𞤭\n𞤴\n𞤲\n𞤺\n𞤵\n𞤴\n𞤵\n𞤥\n𞥆\n𞤢\n𞥄\n𞤺\n𞤵\n.\n𞤋\n𞤲\n𞥆\n𞤢\n𞤥\n𞤢\n \n𞤢"
  specimen_16: "𞤋\n𞤲\n𞥆\n𞤢\n𞤥\n𞤢\n \n𞤢\n𞥄\n𞤣\n𞤫\n𞥅\n𞤶\n𞤭\n \n𞤬\n𞤮\n𞤬\n \n𞤨\n𞤮\n𞤼\n𞤭\n،\n \n𞤲\n\'\n𞤣\n𞤭\n𞤥\n𞤯\n𞤭\n𞤣\n𞤭\n \n𞤫\n \n𞤶\n𞤭\n𞤦\n𞤭\n𞤲\n𞤢\n𞤲\n𞥆\n𞤣\n𞤫\n \n𞤼\n𞤮\n \n𞤦\n𞤢\n𞤲\n𞥆\n𞤺\n𞤫\n \n𞤸\n𞤢\n𞤳\n𞥆\n𞤫\n𞥅\n𞤶\n𞤭\n.\n \n𞤉\n𞤩\n𞤫\n \n𞤲\n\'\n𞤺\n𞤮\n𞥅\n𞤣\n𞤭\n \n𞤥\n𞤭\n𞥅\n𞤶\n𞤮\n \n𞤫\n \n𞤸\n𞤢\n𞤳\n𞥆\n𞤭\n𞤤\n𞤢\n𞤲\n𞤼\n𞤢\n𞥄\n𞤺\n𞤢\n𞤤\n \n𞤫\n𞤼\n𞤫\n \n𞤫\n𞤩\n𞤫\n \n𞤨\n𞤮\n𞤼\n𞤭\n \n𞤸\n𞤵\n𞥅\n𞤬\n𞤮\n \n𞤲\n\'\n𞤣\n𞤭\n𞤪\n𞤣\n𞤫\n \n𞤫\n \n𞤲\n\'\n𞤣\n𞤫\n𞤪\n \n𞤩\n \n𞤭\n𞤴\n𞤲\n𞤺\n𞤵\n𞤴\n𞤵\n𞤥\n𞥆\n𞤢\n𞥄\n𞤺\n𞤵\n.\n𞤋\n𞤲\n𞥆\n𞤢\n𞤥\n𞤢\n \n𞤢\n𞥄\n𞤣\n𞤫\n𞥅\n𞤶\n𞤭\n \n𞤬\n𞤮\n𞤬\n \n𞤨\n𞤮\n𞤼\n𞤭\n،\n \n𞤲\n\'\n𞤣\n𞤭\n𞤥\n𞤯\n𞤭\n𞤣\n𞤭\n \n𞤫\n \n𞤶\n𞤭\n𞤦\n𞤭\n𞤲\n𞤢\n𞤲\n𞥆\n𞤣\n𞤫\n \n𞤼\n𞤮\n \n𞤦\n𞤢\n𞤲\n𞥆\n𞤺\n𞤫\n \n𞤸\n𞤢\n𞤳\n𞥆\n𞤫\n𞥅\n𞤶\n𞤭\n.\n \n𞤉\n𞤩\n𞤫\n \n𞤲\n\'\n𞤺\n𞤮\n𞥅\n𞤣\n𞤭\n \n𞤥\n𞤭\n𞥅\n𞤶\n𞤮\n \n𞤫\n \n𞤸\n𞤢\n𞤳\n𞥆\n𞤭\n𞤤\n𞤢\n𞤲\n𞤼\n𞤢\n𞥄\n𞤺\n𞤢\n𞤤\n \n𞤫\n𞤼\n𞤫\n \n𞤫\n𞤩\n𞤫\n \n𞤨\n𞤮\n𞤼\n𞤭\n \n𞤸\n𞤵\n𞥅\n𞤬\n𞤮\n \n𞤲\n\'\n𞤣\n𞤭\n𞤪\n𞤣\n𞤫\n \n𞤫\n \n𞤲\n\'\n𞤣\n𞤫\n𞤪\n \n𞤩\n \n𞤭"
}
