id: "fvr_Latn"
language: "fvr"
script: "Latn"
name: "Fur"
population: 1230163
region: "SD"
sample_text {
  masthead_full: "KkWw"
  masthead_partial: "Aa"
  styles: "k\nw\na\n-\ns\ní\n \nn\ny\né\nt\nt\ni\nŋ\n \nb\na\na\nj\nt\nó"
  tester: "k\nw\na\n-\ns\ní\n \nn\ny\né\nt\nt\ni\nŋ\n \nb\na\na\nj\nt\nó\nl\ná\n \nk\ne\nr\ne\nl\ni\n "
  poster_sm: "k\nw\na\n-\ns\ní"
  poster_md: "k\nw\na\n-\ns"
  poster_lg: "k\nw"
  specimen_48: "k\nw\na\n-\ns\ní\n \nn\ny\né\nt\nt\ni\nŋ\n \nb\na\na\nj\nt\nó\nl\ná\n \nk\ne\nr\ne\nl\ni\n "
  specimen_36: "k\nw\na\n-\ns\ní\n \nn\ny\né\nt\nt\ni\nŋ\n \nb\na\na\nj\nt\nó\nl\ná\n \nk\ne\nr\ne\nl\ni\n \nn\ná\ns\n \nn\ni\ns\ni\nl\na\n \nn\na\n \nt\na\ṉ\ng\nɨ\nd\nɨ"
  specimen_32: "k\nw\na\n-\ns\ní\n \nn\ny\né\nt\nt\ni\nŋ\n \nb\na\na\nj\nt\nó\nl\ná\n \nk\ne\nr\ne\nl\ni\n \nn\ná\ns\n \nn\ni\ns\ni\nl\na\n \nn\na\n \nt\na\ṉ\ng\nɨ\nd\nɨ\nŋ\n \na\nr\nr\ná\n \nk\na\ṉ\nɨ\nŋ\n,\n \nN\na\nŋ\n-\ns\ní\n "
  specimen_21: "k\nw\na\n-\ns\ní\n \nn\ny\né\nt\nt\ni\nŋ\n \nb\na\na\nj\nt\nó\nl\ná\n \nk\ne\nr\ne\nl\ni\n \nn\ná\ns\n \nn\ni\ns\ni\nl\na\n \nn\na\n \nt\na\ṉ\ng\nɨ\nd\nɨ\nŋ\n \na\nr\nr\ná\n \nk\na\ṉ\nɨ\nŋ\n,\n \nN\na\nŋ\n-\ns\ní\n \nu\ng\no\nl\na\n \nn\na\n \nk\ni\nl\nm\na\nŋ\ná\n \na\nr\nr\ná\n \nk\na\ṉ\nɨ\nŋ\n \nn\na\nm\ná\n \ni\nn\n \nl\nó\nŋ\n \ná\nl\ná\nŋ\n \ns\nǔ\nr\nŋ\nâ\n-\ns\ní\n \nk\ní\n \nj\na\ni\nŋ\na\n \ni\nn\n \nk\né\né\nl\n \nn\ná\n \ns\nǔ\nr\nŋ\nâ\n \ns"
  specimen_16: "k\nw\na\n-\ns\ní\n \nn\ny\né\nt\nt\ni\nŋ\n \nb\na\na\nj\nt\nó\nl\ná\n \nk\ne\nr\ne\nl\ni\n \nn\ná\ns\n \nn\ni\ns\ni\nl\na\n \nn\na\n \nt\na\ṉ\ng\nɨ\nd\nɨ\nŋ\n \na\nr\nr\ná\n \nk\na\ṉ\nɨ\nŋ\n,\n \nN\na\nŋ\n-\ns\ní\n \nu\ng\no\nl\na\n \nn\na\n \nk\ni\nl\nm\na\nŋ\ná\n \na\nr\nr\ná\n \nk\na\ṉ\nɨ\nŋ\n \nn\na\nm\ná\n \ni\nn\n \nl\nó\nŋ\n \ná\nl\ná\nŋ\n \ns\nǔ\nr\nŋ\nâ\n-\ns\ní\n \nk\ní\n \nj\na\ni\nŋ\na\n \ni\nn\n \nk\né\né\nl\n \nn\ná\n \ns\nǔ\nr\nŋ\nâ\n \ns\nu\nu\nr\nꞌ\ní\nŋ\n \nb\nâ\nr\nŋ\na\n.\nk\nw\na\n-\ns\ní\n \nn\ny\né\nt\nt\ni\nŋ\n \nb\na\na\nj\nt\nó\nl\ná\n \nk\ne\nr\ne\nl\ni\n \nn\ná\ns\n \nn\ni\ns\ni\nl\na\n \nn\na\n \nt\na\ṉ\ng\nɨ\nd\nɨ\nŋ\n \na\nr\nr\ná\n \nk\na\ṉ\nɨ\nŋ\n,\n \nN\na\nŋ\n-\ns\ní\n \nu\ng\no\nl\na\n \nn\na\n \nk\ni\nl\nm\na\nŋ\ná\n \na\nr\nr\ná\n \nk\na\ṉ\nɨ\nŋ\n \nn\na\nm\ná\n \ni\nn\n \nl\nó\nŋ\n \ná\nl\ná"
}
