id: "gan"
language: "gan"
script: "Hans"
name: "Gan Chinese"
preferred_name: "Gan"
population: 23698340
region: "CN"
sample_text {
  masthead_full: "人生而自"
  masthead_partial: "由在"
  styles: "鉴于对人类家庭所有成员个固有志向及其平等个跟不移个权利个承认，乃是世界头上自由、正义跟和平个基础"
  tester: "鉴于对人权个无视跟耻笑已发展为野蛮暴行，讲样个暴行玷污了人类个良心，而一个人人享有言论跟信仰自由并冒有恐惧跟匮乏个世界个来临"
  poster_sm: "人人有权享有生命、自由跟人身安全"
  poster_md: "任何人都不许加以酷刑"
  poster_lg: "人人生而自由"
  specimen_48: "法律之前人人平等，并有权享受法律个平等保护，不受任何歧视。人人有权享受平等保护，以避开昧到本布告个任何歧视行为以及煽动讲样个歧视个任何行为之害"
  specimen_36: "鉴于对人类家庭所有成员个固有志向及其平等个跟不移个权利个承认，乃是世界头上自由、正义跟和平个基础，\n鉴于为使人类不致迫不得已铤而走险对暴政跟压迫进行反叛，有必要使人权受法治个保护，\n鉴于有必要促进各国间知己关系个发展，"
  specimen_32: "鉴于对人类家庭所有成员个固有志向及其平等个跟不移个权利个承认，乃是世界头上自由、正义跟和平个基础，\n鉴于对人权个无视跟耻笑已发展为野蛮暴行，讲样个暴行玷污了人类个良心，而一个人人享有言论跟信仰自由并冒有恐惧跟匮乏个世界个来临，已被宣布为普通人民个最高愿望，\n鉴于为使人类不致迫不得已铤而走险对暴政跟压迫进行反叛，有必要使人权受法治个保护，"
  specimen_21: "鉴于对人类家庭所有成员个固有志向及其平等个跟不移个权利个承认，乃是世界头上自由、正义跟和平个基础，\n鉴于对人权个无视跟耻笑已发展为野蛮暴行，讲样个暴行玷污了人类个良心，而一个人人享有言论跟信仰自由并冒有恐惧跟匮乏个世界个来临，已被宣布为普通人民个最高愿望，\n鉴于为使人类不致迫不得已铤而走险对暴政跟压迫进行反叛，有必要使人权受法治个保护，\n鉴于有必要促进各国间知己关系个发展，\n鉴于各联合国国家个人民已在联合国宪章理头重申渠们对基本人权、人格志向跟价值以及男女平等权利个信念，并决心促成较大自由中个社会进步跟生活水平个改善，\n鉴于各会员国业已誓愿同联合国合作以促进对人权跟基本自由个普遍尊重跟遵行，\n鉴于对讲样个权利跟自由个普遍知根知底对于箇誓愿个充分舞正具有蛮大个重要性，"
  specimen_16: "鉴于对人类家庭所有成员个固有志向及其平等个跟不移个权利个承认，乃是世界头上自由、正义跟和平个基础，\n鉴于对人权个无视跟耻笑已发展为野蛮暴行，讲样个暴行玷污了人类个良心，而一个人人享有言论跟信仰自由并冒有恐惧跟匮乏个世界个来临，已被宣布为普通人民个最高愿望，\n鉴于为使人类不致迫不得已铤而走险对暴政跟压迫进行反叛，有必要使人权受法治个保护，\n鉴于有必要促进各国间知己关系个发展，\n鉴于各联合国国家个人民已在联合国宪章理头重申渠们对基本人权、人格志向跟价值以及男女平等权利个信念，并决心促成较大自由中个社会进步跟生活水平个改善，\n鉴于各会员国业已誓愿同联合国合作以促进对人权跟基本自由个普遍尊重跟遵行，\n鉴于对讲样个权利跟自由个普遍知根知底对于箇誓愿个充分舞正具有蛮大个重要性，\n因此箇时间，\n大会，\n发布箇世界人权布告，作为所有人民跟所有国家努力舞正个共同标准，指望每一个人跟社会机构经常记到本布告，努力通过教诲跟教育促进对权利跟自由个尊重，并通过国家个跟国际个渐进措施，使讲样个权利跟自由在各会员国本身人民及在其管辖下领土个人民中得到普遍跟有效个承认跟遵行；\n人人生而自由，在志向跟权利上一律平等。渠们赋有理性跟良心，并理当以弟兄义气相对待。\n人人有资格享有本布告所载个一切权利跟自由，不分种族、肤色、性别、语言、宗教、政治或其他见解、国籍或社会出身、财产、出生或其他身分等任何区别。"
}
