id: "gbz_Arab"
language: "gbz"
script: "Arab"
name: "Zoroastrian Dari"
population: 7982
region: "IR"
sample_text {
  masthead_full: "تماف"
  masthead_partial: "رد"
  styles: "ت\nم\nا\nم\n \nا\nف\nر\nا\nد\n \nب\nش\nر\n \nآ\nز\nا\nد\n \nز"
  tester: "ت\nم\nا\nم\n \nا\nف\nر\nا\nد\n \nب\nش\nر\n \nآ\nز\nا\nد\n \nز\nا\nد\nه\n \nم\nی\nش\nو\nن\nد"
  poster_sm: "ت\nم\nا\nم\n \nا"
  poster_md: "ت\nم\nا\nم\n "
  poster_lg: "ت\nم"
  specimen_48: "ت\nم\nا\nم\n \nا\nف\nر\nا\nد\n \nب\nش\nر\n \nآ\nز\nا\nد\n \nز\nا\nد\nه\n \nم\nی\nش\nو\nن\nد"
  specimen_36: "ت\nم\nا\nم\n \nا\nف\nر\nا\nد\n \nب\nش\nر\n \nآ\nز\nا\nد\n \nز\nا\nد\nه\n \nم\nی\nش\nو\nن\nد\n \nو\n \nا\nز\n \nل\nح\nا\nظ\n \nح\nی\nث\nی\nت\n \nو\n \nک"
  specimen_32: "ت\nم\nا\nم\n \nا\nف\nر\nا\nد\n \nب\nش\nر\n \nآ\nز\nا\nد\n \nز\nا\nد\nه\n \nم\nی\nش\nو\nن\nد\n \nو\n \nا\nز\n \nل\nح\nا\nظ\n \nح\nی\nث\nی\nت\n \nو\n \nک\nر\nا\nم\nت\n \nو\n \nح\nق\nو\nق\n \nب\nا\n \nه\nم\n \nب\nر"
  specimen_21: "ت\nم\nا\nم\n \nا\nف\nر\nا\nد\n \nب\nش\nر\n \nآ\nز\nا\nد\n \nز\nا\nد\nه\n \nم\nی\nش\nو\nن\nد\n \nو\n \nا\nز\n \nل\nح\nا\nظ\n \nح\nی\nث\nی\nت\n \nو\n \nک\nر\nا\nم\nت\n \nو\n \nح\nق\nو\nق\n \nب\nا\n \nه\nم\n \nب\nر\nا\nب\nر\nا\nن\nد\n.\n \nه\nم\nگ\nی\n \nد\nا\nر\nا\nی\n \nع\nق\nل\n \nو\n \nو\nج\nد\nا\nن\n \nه\nس\nت\nن\nد\n \nو\n \nب\nا\nی\nد\n \nب\nا\n \nی\nک\nد\nی\nگ\nر\n \nب\nا\n \nر\nو\nح\nی\nه\n \nا\nی\n \nب\nر\nا\nد\nر\nا\nن\nه\n \nر\nف\nت\nا\nر"
  specimen_16: "ت\nم\nا\nم\n \nا\nف\nر\nا\nد\n \nب\nش\nر\n \nآ\nز\nا\nد\n \nز\nا\nد\nه\n \nم\nی\nش\nو\nن\nد\n \nو\n \nا\nز\n \nل\nح\nا\nظ\n \nح\nی\nث\nی\nت\n \nو\n \nک\nر\nا\nم\nت\n \nو\n \nح\nق\nو\nق\n \nب\nا\n \nه\nم\n \nب\nر\nا\nب\nر\nا\nن\nد\n.\n \nه\nم\nگ\nی\n \nد\nا\nر\nا\nی\n \nع\nق\nل\n \nو\n \nو\nج\nد\nا\nن\n \nه\nس\nت\nن\nد\n \nو\n \nب\nا\nی\nد\n \nب\nا\n \nی\nک\nد\nی\nگ\nر\n \nب\nا\n \nر\nو\nح\nی\nه\n \nا\nی\n \nب\nر\nا\nد\nر\nا\nن\nه\n \nر\nف\nت\nا\nر\n \nک\nن\nن\nد\n.\nت\nم\nا\nم\n \nا\nف\nر\nا\nد\n \nب\nش\nر\n \nآ\nز\nا\nد\n \nز\nا\nد\nه\n \nم\nی\nش\nو\nن\nد\n \nو\n \nا\nز\n \nل\nح\nا\nظ\n \nح\nی\nث\nی\nت\n \nو\n \nک\nر\nا\nم\nت\n \nو\n \nح\nق\nو\nق\n \nب\nا\n \nه\nم\n \nب\nر\nا\nب\nر\nا\nن\nد\n.\n \nه\nم\nگ\nی\n \nد\nا\nر\nا\nی\n \nع\nق\nل\n \nو\n \nو\nج\nد\nا\nن\n \nه\nس\nت\nن\nد\n \nو\n \nب\nا\nی\nد\n \nب\nا\n \nی\nک"
}
