id: "gcf_Latn"
language: "gcf"
script: "Latn"
name: "Guadeloupean Creole French, Latin, Martinique"
sample_text {
  masthead_full: "TtOo"
  masthead_partial: "Uu"
  styles: "T\no\nu\nt\n \nz\ni\nm\ne\nn\n \nk\na\n \nn\ne\nt\n \nl\ni\nb"
  tester: "T\no\nu\nt\n \nz\ni\nm\ne\nn\n \nk\na\n \nn\ne\nt\n \nl\ni\nb\n \ne\nk\n \ne\ng\na\nl\n \ne"
  poster_sm: "T\no\nu\nt\n \nz"
  poster_md: "T\no\nu\nt\n "
  poster_lg: "T\no"
  specimen_48: "T\no\nu\nt\n \nz\ni\nm\ne\nn\n \nk\na\n \nn\ne\nt\n \nl\ni\nb\n \ne\nk\n \ne\ng\na\nl\n \ne"
  specimen_36: "T\no\nu\nt\n \nz\ni\nm\ne\nn\n \nk\na\n \nn\ne\nt\n \nl\ni\nb\n \ne\nk\n \ne\ng\na\nl\n \ne\nn\n \nd\ni\ng\nn\ni\nt\ne\n \ne\nk\n \ne\nn\n \nd\nr\no\ni"
  specimen_32: "T\no\nu\nt\n \nz\ni\nm\ne\nn\n \nk\na\n \nn\ne\nt\n \nl\ni\nb\n \ne\nk\n \ne\ng\na\nl\n \ne\nn\n \nd\ni\ng\nn\ni\nt\ne\n \ne\nk\n \ne\nn\n \nd\nr\no\ni\n.\n \nY\no\n \nn\ni\n \nr\ne\ns\no\nn\n \ne\nk\n \nk\no\nn"
  specimen_21: "T\no\nu\nt\n \nz\ni\nm\ne\nn\n \nk\na\n \nn\ne\nt\n \nl\ni\nb\n \ne\nk\n \ne\ng\na\nl\n \ne\nn\n \nd\ni\ng\nn\ni\nt\ne\n \ne\nk\n \ne\nn\n \nd\nr\no\ni\n.\n \nY\no\n \nn\ni\n \nr\ne\ns\no\nn\n \ne\nk\n \nk\no\nn\ns\ny\na\nn\ns\n,\n \ne\n \nd\nw\ne\nt\n \na\ng\ni\n \ny\no\nn\nn\n \np\no\nu\n \nl\no\nt\n \na\nd\na\nn\n \na\nn\n \nl\ne\ns\np\nr\ni\n \nd\ni\n \nf\nr\na\nt\ne\nr\nn\ni\nt\ne\n.\nT\no\nu\nt\n \nz\ni\nm\ne\nn\n \nk\na\n \nn\ne\nt\n \nl\ni\nb"
  specimen_16: "T\no\nu\nt\n \nz\ni\nm\ne\nn\n \nk\na\n \nn\ne\nt\n \nl\ni\nb\n \ne\nk\n \ne\ng\na\nl\n \ne\nn\n \nd\ni\ng\nn\ni\nt\ne\n \ne\nk\n \ne\nn\n \nd\nr\no\ni\n.\n \nY\no\n \nn\ni\n \nr\ne\ns\no\nn\n \ne\nk\n \nk\no\nn\ns\ny\na\nn\ns\n,\n \ne\n \nd\nw\ne\nt\n \na\ng\ni\n \ny\no\nn\nn\n \np\no\nu\n \nl\no\nt\n \na\nd\na\nn\n \na\nn\n \nl\ne\ns\np\nr\ni\n \nd\ni\n \nf\nr\na\nt\ne\nr\nn\ni\nt\ne\n.\nT\no\nu\nt\n \nz\ni\nm\ne\nn\n \nk\na\n \nn\ne\nt\n \nl\ni\nb\n \ne\nk\n \ne\ng\na\nl\n \ne\nn\n \nd\ni\ng\nn\ni\nt\ne\n \ne\nk\n \ne\nn\n \nd\nr\no\ni\n.\n \nY\no\n \nn\ni\n \nr\ne\ns\no\nn\n \ne\nk\n \nk\no\nn\ns\ny\na\nn\ns\n,\n \ne\n \nd\nw\ne\nt\n \na\ng\ni\n \ny\no\nn\nn\n \np\no\nu\n \nl\no\nt\n \na\nd\na\nn\n \na\nn\n \nl\ne\ns\np\nr\ni\n \nd\ni\n \nf\nr\na\nt\ne\nr\nn\ni\nt\ne\n.\nT\no\nu\nt\n \nz\ni\nm\ne\nn\n \nk\na\n \nn\ne\nt"
}
