id: "gcf_Latn"
language: "gcf"
script: "Latn"
name: "Guadeloupean Creole French, Latin, Martinique"
region: "GP"
region: "MQ"
sample_text {
  masthead_full: "TtOo"
  masthead_partial: "Uu"
  styles: "Tout zimen ka net lib ek egal en dignite"
  tester: "Tout zimen ka net lib ek egal en dignite ek en droi. Yo ni reson"
  poster_sm: "Tout zimen"
  poster_md: "Tout"
  poster_lg: "Tout"
  specimen_48: "Tout zimen ka net lib ek egal en dignite ek en droi. Yo ni reson ek"
  specimen_36: "Tout zimen ka net lib ek egal en dignite ek en droi. Yo ni reson ek konsyans, e dwet agi yonn pou lot adan an lespri di fraternite."
  specimen_32: "Tout zimen ka net lib ek egal en dignite ek en droi. Yo ni reson ek konsyans, e dwet agi yonn pou lot adan an lespri di fraternite."
  specimen_21: "Tout zimen ka net lib ek egal en dignite ek en droi. Yo ni reson ek konsyans, e dwet agi yonn pou lot adan an lespri di fraternite.\nTout zimen ka net lib ek egal en dignite ek en droi. Yo ni reson ek konsyans, e dwet agi yonn pou lot adan an lespri di fraternite.\nTout zimen ka net lib ek egal en dignite ek en droi. Yo ni reson ek konsyans, e dwet agi yonn pou lot adan an lespri di fraternite."
  specimen_16: "Tout zimen ka net lib ek egal en dignite ek en droi. Yo ni reson ek konsyans, e dwet agi yonn pou lot adan an lespri di fraternite.\nTout zimen ka net lib ek egal en dignite ek en droi. Yo ni reson ek konsyans, e dwet agi yonn pou lot adan an lespri di fraternite.\nTout zimen ka net lib ek egal en dignite ek en droi. Yo ni reson ek konsyans, e dwet agi yonn pou lot adan an lespri di fraternite.\nTout zimen ka net lib ek egal en dignite ek en droi. Yo ni reson ek konsyans, e dwet agi yonn pou lot adan an lespri di fraternite.\nTout zimen ka net lib ek egal en dignite ek en droi. Yo ni reson ek konsyans, e dwet agi yonn pou lot adan an lespri di fraternite."
}
