id: "gd"
language: "gd"
script: "Latn"
name: "Scottish Gaelic"
autonym: "Gàidhlig"
population: 65103
region: "GB"
exemplar_chars {
  base: "a à b c d e è f g h i ì l m n o ò p r s t u ù"
  auxiliary: "á ă â å ä ã ā æ ċ ç ḋ é ĕ ê ë ē ḟ ġ í ĭ î ï ī ı j k ł ṁ ñ ó ŏ ô ö ø ō œ ṗ q ṡ ş ș ṫ ú ŭ û ü ū v w x y ÿ z"
  marks: "◌̀ ◌́"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ¡ ? . … · \' ‘ ’ \" “ ” ( ) [ ] { } § ¶ @ * / & ⁊ # % † ‡ ‧ ° © ® ™ { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "A B C D E F G H I L M N O P R S T U"
}
sample_text {
  masthead_full: "TtHh"
  masthead_partial: "Aa"
  styles: "Do bhrìgh \'s gu bheil e air aideachadh gu"
  tester: "Do bhrìgh \'s gun do dh\' adhbharaich a bhith a\' cur còirichean dhaoine"
  poster_sm: "Do bhrìgh \'s"
  poster_md: "Do bhrìgh"
  poster_lg: "Tha"
  specimen_48: "Do bhrìgh \'s gun do chuir sluagh nan Dùthchannan Aonaichte an"
  specimen_36: "Do bhrìgh \'s gu bheil e do-sheachanta feumail cleamhnasan càirdeil a stèidheachadh eadar dùthchannan,\nMar sin, a nis,"
  specimen_32: "Do bhrìgh \'s gu bheil e air aideachadh gu bheil dualchas nàdarra agus còirichean neo-sgaraichte uile bhuill a\' chinne-daonna na stèidh airson saorsa, ceartas agus sìth an t-saoghail,"
  specimen_21: "Do bhrìgh \'s gu bheil e air aideachadh gu bheil dualchas nàdarra agus còirichean neo-sgaraichte uile bhuill a\' chinne-daonna na stèidh airson saorsa, ceartas agus sìth an t-saoghail,\nDo bhrìgh \'s gun do dh\' adhbharaich a bhith a\' cur còirichean dhaoine ann an suarachas gnìomhan borba a shàraich cogaisean, a bhith air an cleachdadh, agus gum bheil an latha air teachd anns am bi saor-labhartas, saor chreideamh agus saorsa bho eagal agus dìth air a ghairm mar àrd-mhiann an t-sluaigh choitcheann,"
  specimen_16: "Do bhrìgh \'s gu bheil e air aideachadh gu bheil dualchas nàdarra agus còirichean neo-sgaraichte uile bhuill a\' chinne-daonna na stèidh airson saorsa, ceartas agus sìth an t-saoghail,\nDo bhrìgh \'s gun do dh\' adhbharaich a bhith a\' cur còirichean dhaoine ann an suarachas gnìomhan borba a shàraich cogaisean, a bhith air an cleachdadh, agus gum bheil an latha air teachd anns am bi saor-labhartas, saor chreideamh agus saorsa bho eagal agus dìth air a ghairm mar àrd-mhiann an t-sluaigh choitcheann,\nDo bhrìgh \'s gu bheil e uile do-sheachanta feumail - mas e nach bi an duine air a cho-èigneachadh mu dheireadh gu ceannairc a dhèanamh an aghaidh ain-tighearnas agus fòirneart gum bi còirichean an duine air an dìon tro riaghladh an lagha,"
}
