id: "gem_Latn"
language: "gem"
script: "Latn"
name: "Germanic languages, Latin"
sample_text {
  masthead_full: "AaLl"
  masthead_partial: "Ii"
  styles: "A\nl\nl\na\ni\n \nm\na\nn\nn\ni\nz\n \nf\nr\ni\nj\na\ni\n \ng"
  tester: "A\nl\nl\na\ni\n \nm\na\nn\nn\ni\nz\n \nf\nr\ni\nj\na\ni\n \ng\na\nl\nī\nk\na\ni\nh\nw\n \nm"
  poster_sm: "A\nl\nl\na\ni\n "
  poster_md: "A\nl\nl\na\ni"
  poster_lg: "A\nl"
  specimen_48: "A\nl\nl\na\ni\n \nm\na\nn\nn\ni\nz\n \nf\nr\ni\nj\na\ni\n \ng\na\nl\nī\nk\na\ni\nh\nw\n \nm"
  specimen_36: "A\nl\nl\na\ni\n \nm\na\nn\nn\ni\nz\n \nf\nr\ni\nj\na\ni\n \ng\na\nl\nī\nk\na\ni\nh\nw\n \nm\ni\nd\ni\n \nw\ne\nr\nþ\nō\n \nr\ne\nh\nt\na\nm\ni\nz\nu\nh"
  specimen_32: "A\nl\nl\na\ni\n \nm\na\nn\nn\ni\nz\n \nf\nr\ni\nj\na\ni\n \ng\na\nl\nī\nk\na\ni\nh\nw\n \nm\ni\nd\ni\n \nw\ne\nr\nþ\nō\n \nr\ne\nh\nt\na\nm\ni\nz\nu\nh\n \ng\na\nb\nu\nr\na\nn\na\ni\n \ns\ni\nn\nd\ni\n.\n \nÞ\na"
  specimen_21: "A\nl\nl\na\ni\n \nm\na\nn\nn\ni\nz\n \nf\nr\ni\nj\na\ni\n \ng\na\nl\nī\nk\na\ni\nh\nw\n \nm\ni\nd\ni\n \nw\ne\nr\nþ\nō\n \nr\ne\nh\nt\na\nm\ni\nz\nu\nh\n \ng\na\nb\nu\nr\na\nn\na\ni\n \ns\ni\nn\nd\ni\n.\n \nÞ\na\ni\nm\na\nz\n \na\nt\ng\ne\nb\na\nn\nō\n \ns\ni\nn\nd\ni\n \nm\ni\nd\nw\ni\ns\ns\nį\n̄\n \ng\na\nh\nu\ng\nd\ni\nz\nu\nh\n,\n \na\nu\nk\n \na\nn\nþ\ni\nr\na\ni\nm\na\nz\n \na\nn\na\nd\na\nn\nų\n \nb\nr\nō\nþ\nu\nr\nl\nī\nk\na\nn\nǭ\n \na\nu\ng"
  specimen_16: "A\nl\nl\na\ni\n \nm\na\nn\nn\ni\nz\n \nf\nr\ni\nj\na\ni\n \ng\na\nl\nī\nk\na\ni\nh\nw\n \nm\ni\nd\ni\n \nw\ne\nr\nþ\nō\n \nr\ne\nh\nt\na\nm\ni\nz\nu\nh\n \ng\na\nb\nu\nr\na\nn\na\ni\n \ns\ni\nn\nd\ni\n.\n \nÞ\na\ni\nm\na\nz\n \na\nt\ng\ne\nb\na\nn\nō\n \ns\ni\nn\nd\ni\n \nm\ni\nd\nw\ni\ns\ns\nį\n̄\n \ng\na\nh\nu\ng\nd\ni\nz\nu\nh\n,\n \na\nu\nk\n \na\nn\nþ\ni\nr\na\ni\nm\na\nz\n \na\nn\na\nd\na\nn\nų\n \nb\nr\nō\nþ\nu\nr\nl\nī\nk\na\nn\nǭ\n \na\nu\ng\ni\nj\na\nn\ną\n \ns\nk\nu\nl\nu\nn\n.\nA\nl\nl\na\ni\n \nm\na\nn\nn\ni\nz\n \nf\nr\ni\nj\na\ni\n \ng\na\nl\nī\nk\na\ni\nh\nw\n \nm\ni\nd\ni\n \nw\ne\nr\nþ\nō\n \nr\ne\nh\nt\na\nm\ni\nz\nu\nh\n \ng\na\nb\nu\nr\na\nn\na\ni\n \ns\ni\nn\nd\ni\n.\n \nÞ\na\ni\nm\na\nz\n \na\nt\ng\ne\nb\na\nn\nō\n \ns\ni\nn\nd\ni\n \nm\ni\nd\nw\ni\ns\ns\nį\n̄\n \ng\na\nh\nu\ng\nd\ni\nz\nu\nh\n,\n \na"
}
