id: "gez_Ethi"
language: "gez"
script: "Ethi"
name: "Geez"
population: 0
region: "ET"
sample_text {
  masthead_full: "ተወልዱ"
  masthead_partial: "ኵሉ"
  styles: "ተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡"
  tester: "ተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና"
  poster_sm: "ተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና"
  poster_md: "ተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና"
  poster_lg: "ተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና"
  specimen_48: "ተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ"
  specimen_36: "ተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።"
  specimen_32: "ተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።\nተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።"
  specimen_21: "ተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።\nተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።\nተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።\nተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።\nተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።"
  specimen_16: "ተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።\nተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።\nተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።\nተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።\nተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።\nተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።\nተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።\nተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።\nተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።\nተወልዱ፡ኵሉ፡ሰብእ፡ግዑዛን፡ወዕሩያን፡በማዕረግ፡ወብሕግ።ቦሙ፡ኅሊና፡ወዐቅል፡ወይትጌበሩ፡አሐዱ፡ ምስለ፡አሀዱ፡በመንፈሰ፡እኍና።"
}
historical: true
