id: "gez_Ethi"
language: "gez"
script: "Ethi"
name: "Geez"
population: 0
region: "ER"
region: "ET"
region: "IL"
sample_text {
  masthead_full: "ተወልዱ"
  masthead_partial: "ኵሉ"
  styles: "ተ\nወ\nል\nዱ\n፡\nኵ\nሉ\n፡\nሰ\nብ\nእ\n፡\nግ\nዑ\nዛ\nን\n፡\nወ\nዕ\nሩ\nያ\nን\n፡"
  tester: "ተ\nወ\nል\nዱ\n፡\nኵ\nሉ\n፡\nሰ\nብ\nእ\n፡\nግ\nዑ\nዛ\nን\n፡\nወ\nዕ\nሩ\nያ\nን\n፡\nበ\nማ\nዕ\nረ\nግ\n፡\nወ\nብ\nሕ\nግ\n።"
  poster_sm: "ተ\nወ\nል\nዱ\n፡\nኵ"
  poster_md: "ተ\nወ\nል\nዱ\n፡"
  poster_lg: "ተ\nወ"
  specimen_48: "ተ\nወ\nል\nዱ\n፡\nኵ\nሉ\n፡\nሰ\nብ\nእ\n፡\nግ\nዑ\nዛ\nን\n፡\nወ\nዕ\nሩ\nያ\nን\n፡\nበ\nማ\nዕ\nረ\nግ\n፡\nወ\nብ\nሕ\nግ\n።"
  specimen_36: "ተ\nወ\nል\nዱ\n፡\nኵ\nሉ\n፡\nሰ\nብ\nእ\n፡\nግ\nዑ\nዛ\nን\n፡\nወ\nዕ\nሩ\nያ\nን\n፡\nበ\nማ\nዕ\nረ\nግ\n፡\nወ\nብ\nሕ\nግ\n።\nቦ\nሙ\n፡\nኅ\nሊ\nና\n፡\nወ\nዐ\nቅ\nል\n፡\nወ\nይ\nት\nጌ\nበ\nሩ\n፡\nአ\nሐ\nዱ"
  specimen_32: "ተ\nወ\nል\nዱ\n፡\nኵ\nሉ\n፡\nሰ\nብ\nእ\n፡\nግ\nዑ\nዛ\nን\n፡\nወ\nዕ\nሩ\nያ\nን\n፡\nበ\nማ\nዕ\nረ\nግ\n፡\nወ\nብ\nሕ\nግ\n።\nቦ\nሙ\n፡\nኅ\nሊ\nና\n፡\nወ\nዐ\nቅ\nል\n፡\nወ\nይ\nት\nጌ\nበ\nሩ\n፡\nአ\nሐ\nዱ\n፡\n \nም\nስ\nለ\n፡\nአ\nሀ\nዱ\n፡\nበ\nመ\nን\nፈ\nሰ\n፡\nእ\nኍ\nና\n።\nተ\nወ\nል"
  specimen_21: "ተ\nወ\nል\nዱ\n፡\nኵ\nሉ\n፡\nሰ\nብ\nእ\n፡\nግ\nዑ\nዛ\nን\n፡\nወ\nዕ\nሩ\nያ\nን\n፡\nበ\nማ\nዕ\nረ\nግ\n፡\nወ\nብ\nሕ\nግ\n።\nቦ\nሙ\n፡\nኅ\nሊ\nና\n፡\nወ\nዐ\nቅ\nል\n፡\nወ\nይ\nት\nጌ\nበ\nሩ\n፡\nአ\nሐ\nዱ\n፡\n \nም\nስ\nለ\n፡\nአ\nሀ\nዱ\n፡\nበ\nመ\nን\nፈ\nሰ\n፡\nእ\nኍ\nና\n።\nተ\nወ\nል\nዱ\n፡\nኵ\nሉ\n፡\nሰ\nብ\nእ\n፡\nግ\nዑ\nዛ\nን\n፡\nወ\nዕ\nሩ\nያ\nን\n፡\nበ\nማ\nዕ\nረ\nግ\n፡\nወ\nብ\nሕ\nግ\n።\nቦ\nሙ\n፡\nኅ\nሊ\nና\n፡\nወ\nዐ\nቅ\nል\n፡\nወ\nይ\nት\nጌ\nበ\nሩ\n፡\nአ\nሐ\nዱ\n፡\n \nም\nስ\nለ\n፡\nአ\nሀ\nዱ\n፡\nበ\nመ\nን\nፈ\nሰ\n፡\nእ\nኍ\nና\n።\nተ\nወ\nል\nዱ\n፡\nኵ\nሉ\n፡\nሰ\nብ\nእ\n፡\nግ\nዑ\nዛ\nን"
  specimen_16: "ተ\nወ\nል\nዱ\n፡\nኵ\nሉ\n፡\nሰ\nብ\nእ\n፡\nግ\nዑ\nዛ\nን\n፡\nወ\nዕ\nሩ\nያ\nን\n፡\nበ\nማ\nዕ\nረ\nግ\n፡\nወ\nብ\nሕ\nግ\n።\nቦ\nሙ\n፡\nኅ\nሊ\nና\n፡\nወ\nዐ\nቅ\nል\n፡\nወ\nይ\nት\nጌ\nበ\nሩ\n፡\nአ\nሐ\nዱ\n፡\n \nም\nስ\nለ\n፡\nአ\nሀ\nዱ\n፡\nበ\nመ\nን\nፈ\nሰ\n፡\nእ\nኍ\nና\n።\nተ\nወ\nል\nዱ\n፡\nኵ\nሉ\n፡\nሰ\nብ\nእ\n፡\nግ\nዑ\nዛ\nን\n፡\nወ\nዕ\nሩ\nያ\nን\n፡\nበ\nማ\nዕ\nረ\nግ\n፡\nወ\nብ\nሕ\nግ\n።\nቦ\nሙ\n፡\nኅ\nሊ\nና\n፡\nወ\nዐ\nቅ\nል\n፡\nወ\nይ\nት\nጌ\nበ\nሩ\n፡\nአ\nሐ\nዱ\n፡\n \nም\nስ\nለ\n፡\nአ\nሀ\nዱ\n፡\nበ\nመ\nን\nፈ\nሰ\n፡\nእ\nኍ\nና\n።\nተ\nወ\nል\nዱ\n፡\nኵ\nሉ\n፡\nሰ\nብ\nእ\n፡\nግ\nዑ\nዛ\nን\n፡\nወ\nዕ\nሩ\nያ\nን\n፡\nበ\nማ\nዕ\nረ\nግ\n፡\nወ\nብ\nሕ\nግ\n።\nቦ\nሙ\n፡\nኅ\nሊ\nና\n፡\nወ\nዐ\nቅ\nል\n፡\nወ\nይ\nት\nጌ\nበ\nሩ\n፡\nአ\nሐ\nዱ\n፡\n \nም\nስ\nለ\n፡\nአ\nሀ\nዱ\n፡\nበ\nመ\nን\nፈ\nሰ\n፡\nእ\nኍ\nና\n።\nተ\nወ\nል\nዱ\n፡\nኵ\nሉ\n፡\nሰ\nብ\nእ\n፡\nግ\nዑ\nዛ\nን\n፡\nወ\nዕ\nሩ\nያ\nን\n፡\nበ\nማ\nዕ\nረ\nግ\n፡\nወ\nብ\nሕ\nግ\n።\nቦ\nሙ\n፡\nኅ\nሊ\nና\n፡\nወ\nዐ\nቅ\nል\n፡\nወ\nይ\nት\nጌ\nበ\nሩ\n፡\nአ\nሐ\nዱ\n፡\n \nም\nስ\nለ\n፡\nአ\nሀ\nዱ\n፡\nበ\nመ\nን\nፈ\nሰ\n፡\nእ\nኍ\nና\n።\nተ\nወ\nል\nዱ"
}
historical: true
