id: "giw_Latn"
language: "giw"
script: "Latn"
name: "Gelao, Klau"
sample_text {
  masthead_full: "CcHh"
  masthead_partial: "Ii"
  styles: "C\nh\ni\nx\n \nz\no\nx\n \nk\ne\ny\n \nz\ni\nf\ny\no\nu\nr\n,"
  tester: "C\nh\ni\nx\n \nz\no\nx\n \nk\ne\ny\n \nz\ni\nf\ny\no\nu\nr\n,\n \na\nn\n \nh\nu\n \nt\ns\nu"
  poster_sm: "C\nh\ni\nx\n \nz"
  poster_md: "C\nh\ni\nx\n "
  poster_lg: "C\nh"
  specimen_48: "C\nh\ni\nx\n \nz\no\nx\n \nk\ne\ny\n \nz\ni\nf\ny\no\nu\nr\n,\n \na\nn\n \nh\nu\n \nt\ns\nu"
  specimen_36: "C\nh\ni\nx\n \nz\no\nx\n \nk\ne\ny\n \nz\ni\nf\ny\no\nu\nr\n,\n \na\nn\n \nh\nu\n \nt\ns\nu\nn\nx\ny\na\nn\nr\n \nt\nh\nu\nn\ng\ns\n \nc\nh\ni\na\nn\nr"
  specimen_32: "C\nh\ni\nx\n \nz\no\nx\n \nk\ne\ny\n \nz\ni\nf\ny\no\nu\nr\n,\n \na\nn\n \nh\nu\n \nt\ns\nu\nn\nx\ny\na\nn\nr\n \nt\nh\nu\nn\ng\ns\n \nc\nh\ni\na\nn\nr\nl\ni\nf\n \nn\nu\n \np\nh\ni\nn\nr\nt\ne\nn\n.\n \nT\ns\no\nx"
  specimen_21: "C\nh\ni\nx\n \nz\no\nx\n \nk\ne\ny\n \nz\ni\nf\ny\no\nu\nr\n,\n \na\nn\n \nh\nu\n \nt\ns\nu\nn\nx\ny\na\nn\nr\n \nt\nh\nu\nn\ng\ns\n \nc\nh\ni\na\nn\nr\nl\ni\nf\n \nn\nu\n \np\nh\ni\nn\nr\nt\ne\nn\n.\n \nT\ns\no\nx\nn\nu\nr\n \nn\ne\ns\n \nl\ni\ns\nh\ni\nn\nf\n \nt\nh\nu\nn\ng\ns\n \nl\ne\ny\nx\n \no\n,\n \nl\na\ni\nv\n \nk\nu\na\nn\nx\ns\nh\ni\nf\n \nt\no\n \nt\ns\ne\ny\nr\n \nt\ni\n \nc\ni\nn\nx\ns\ne\nn\nr\n \ns\nh\ni\na\nn\ng\nx\nt\na\ni\nf\n.\nC\nh"
  specimen_16: "C\nh\ni\nx\n \nz\no\nx\n \nk\ne\ny\n \nz\ni\nf\ny\no\nu\nr\n,\n \na\nn\n \nh\nu\n \nt\ns\nu\nn\nx\ny\na\nn\nr\n \nt\nh\nu\nn\ng\ns\n \nc\nh\ni\na\nn\nr\nl\ni\nf\n \nn\nu\n \np\nh\ni\nn\nr\nt\ne\nn\n.\n \nT\ns\no\nx\nn\nu\nr\n \nn\ne\ns\n \nl\ni\ns\nh\ni\nn\nf\n \nt\nh\nu\nn\ng\ns\n \nl\ne\ny\nx\n \no\n,\n \nl\na\ni\nv\n \nk\nu\na\nn\nx\ns\nh\ni\nf\n \nt\no\n \nt\ns\ne\ny\nr\n \nt\ni\n \nc\ni\nn\nx\ns\ne\nn\nr\n \ns\nh\ni\na\nn\ng\nx\nt\na\ni\nf\n.\nC\nh\ni\nx\n \nz\no\nx\n \nk\ne\ny\n \nz\ni\nf\ny\no\nu\nr\n,\n \na\nn\n \nh\nu\n \nt\ns\nu\nn\nx\ny\na\nn\nr\n \nt\nh\nu\nn\ng\ns\n \nc\nh\ni\na\nn\nr\nl\ni\nf\n \nn\nu\n \np\nh\ni\nn\nr\nt\ne\nn\n.\n \nT\ns\no\nx\nn\nu\nr\n \nn\ne\ns\n \nl\ni\ns\nh\ni\nn\nf\n \nt\nh\nu\nn\ng\ns\n \nl\ne\ny\nx\n \no\n,\n \nl\na\ni\nv\n \nk\nu\na\nn\nx\ns\nh\ni\nf\n \nt\no\n \nt\ns\ne\ny\nr\n \nt"
}
