id: "gju_Deva"
language: "gju"
script: "Deva"
name: "Gujari, Devanagari"
region: "IN"
sample_text {
  masthead_full: "सगलम"
  masthead_partial: "नख"
  styles: "सागला मिनख आज़ाद अर प्रतिष्ठा ने आधिकारां री बरोबरी लियोडा पैदा"
  tester: "सागला मिनख आज़ाद अर प्रतिष्ठा ने आधिकारां री बरोबरी लियोडा पैदा होवे। क्हां में इन बात री समझ"
  poster_sm: "सागला मिनख आज़ाद"
  poster_md: "सागला मिनख आज"
  poster_lg: "सागला"
  specimen_48: "सागला मिनख आज़ाद अर प्रतिष्ठा ने आधिकारां री बरोबरी लियोडा पैदा होवे। क्हां में इन बात री समझ अर"
  specimen_36: "सागला मिनख आज़ाद अर प्रतिष्ठा ने आधिकारां री बरोबरी लियोडा पैदा होवे। क्हां में इन बात री समझ अर विवेक होवे के क्हाने एक दूजे रे सागे भाईचारे सूं रैणों है।"
  specimen_32: "सागला मिनख आज़ाद अर प्रतिष्ठा ने आधिकारां री बरोबरी लियोडा पैदा होवे। क्हां में इन बात री समझ अर विवेक होवे के क्हाने एक दूजे रे सागे भाईचारे सूं रैणों है।"
  specimen_21: "सागला मिनख आज़ाद अर प्रतिष्ठा ने आधिकारां री बरोबरी लियोडा पैदा होवे। क्हां में इन बात री समझ अर विवेक होवे के क्हाने एक दूजे रे सागे भाईचारे सूं रैणों है।\nसागला मिनख आज़ाद अर प्रतिष्ठा ने आधिकारां री बरोबरी लियोडा पैदा होवे। क्हां में इन बात री समझ अर विवेक होवे के क्हाने एक दूजे रे सागे भाईचारे सूं रैणों है।\nसागला मिनख आज़ाद अर प्रतिष्ठा ने आधिकारां री बरोबरी लियोडा पैदा होवे। क्हां में इन बात री समझ अर विवेक होवे के क्हाने एक दूजे रे सागे भाईचारे सूं रैणों है।"
  specimen_16: "सागला मिनख आज़ाद अर प्रतिष्ठा ने आधिकारां री बरोबरी लियोडा पैदा होवे। क्हां में इन बात री समझ अर विवेक होवे के क्हाने एक दूजे रे सागे भाईचारे सूं रैणों है।\nसागला मिनख आज़ाद अर प्रतिष्ठा ने आधिकारां री बरोबरी लियोडा पैदा होवे। क्हां में इन बात री समझ अर विवेक होवे के क्हाने एक दूजे रे सागे भाईचारे सूं रैणों है।\nसागला मिनख आज़ाद अर प्रतिष्ठा ने आधिकारां री बरोबरी लियोडा पैदा होवे। क्हां में इन बात री समझ अर विवेक होवे के क्हाने एक दूजे रे सागे भाईचारे सूं रैणों है।\nसागला मिनख आज़ाद अर प्रतिष्ठा ने आधिकारां री बरोबरी लियोडा पैदा होवे। क्हां में इन बात री समझ अर विवेक होवे के क्हाने एक दूजे रे सागे भाईचारे सूं रैणों है।\nसागला मिनख आज़ाद अर प्रतिष्ठा ने आधिकारां री बरोबरी लियोडा पैदा होवे। क्हां में इन बात री समझ अर विवेक होवे के क्हाने एक दूजे रे सागे भाईचारे सूं रैणों है।\nसागला मिनख आज़ाद अर प्रतिष्ठा ने आधिकारां री बरोबरी लियोडा पैदा होवे। क्हां में इन बात री समझ अर विवेक होवे के क्हाने एक दूजे रे सागे भाईचारे सूं रैणों है।"
}
