id: "gkp_Latn"
language: "gkp"
script: "Latn"
name: "Kpelle, Guinea"
sample_text {
  masthead_full: "NnUu"
  masthead_partial: "Kk"
  styles: "N\nu\nk\na\nn\n \ng\ne\nl\ne\n \nk\na\na\n \np\nə\nl\nə\n \nk"
  tester: "N\nu\nk\na\nn\n \ng\ne\nl\ne\n \nk\na\na\n \np\nə\nl\nə\n \nk\na\na\n \nt\na\nn\nɔ\nn\n,\n "
  poster_sm: "N\nu\nk\na\nn\n "
  poster_md: "N\nu\nk\na\nn"
  poster_lg: "N\nu"
  specimen_48: "N\nu\nk\na\nn\n \ng\ne\nl\ne\n \nk\na\na\n \np\nə\nl\nə\n \nk\na\na\n \nt\na\nn\nɔ\nn\n,\n "
  specimen_36: "N\nu\nk\na\nn\n \ng\ne\nl\ne\n \nk\na\na\n \np\nə\nl\nə\n \nk\na\na\n \nt\na\nn\nɔ\nn\n,\n \ny\ni\nl\ni\nɓ\na\n \nn\nu\n \nk\nə\nl\ne\n \nm\na\na\nw\ni"
  specimen_32: "N\nu\nk\na\nn\n \ng\ne\nl\ne\n \nk\na\na\n \np\nə\nl\nə\n \nk\na\na\n \nt\na\nn\nɔ\nn\n,\n \ny\ni\nl\ni\nɓ\na\n \nn\nu\n \nk\nə\nl\ne\n \nm\na\na\nw\ni\ny\nə\n \np\nə\nl\nə\n \nd\na\n \nt\nɔ\nɔ\ni\n \ng\na\na\n "
  specimen_21: "N\nu\nk\na\nn\n \ng\ne\nl\ne\n \nk\na\na\n \np\nə\nl\nə\n \nk\na\na\n \nt\na\nn\nɔ\nn\n,\n \ny\ni\nl\ni\nɓ\na\n \nn\nu\n \nk\nə\nl\ne\n \nm\na\na\nw\ni\ny\nə\n \np\nə\nl\nə\n \nd\na\n \nt\nɔ\nɔ\ni\n \ng\na\na\n \nɲ\ne\ni\n \ny\nɛ\nn\nɛ\ny\ni\ni\n \nh\nu\n \nk\nɛ\np\nə\nl\nə\n \nk\na\na\nl\nɔ\n \nt\na\nn\nɔ\nn\n;\n \nd\ni\n \nk\nɛ\nm\nɛ\nn\ni\n \na\n \nn\nu\nk\na\nn\n \nŋ\na\na\n \nɓ\nə\n \ng\nɛ\nɛ\n \nh\nw\nə\nk\nɛ\nl\ni\n \nw\nɛ\nl\ni\nk\nɛ\nm\na\na"
  specimen_16: "N\nu\nk\na\nn\n \ng\ne\nl\ne\n \nk\na\na\n \np\nə\nl\nə\n \nk\na\na\n \nt\na\nn\nɔ\nn\n,\n \ny\ni\nl\ni\nɓ\na\n \nn\nu\n \nk\nə\nl\ne\n \nm\na\na\nw\ni\ny\nə\n \np\nə\nl\nə\n \nd\na\n \nt\nɔ\nɔ\ni\n \ng\na\na\n \nɲ\ne\ni\n \ny\nɛ\nn\nɛ\ny\ni\ni\n \nh\nu\n \nk\nɛ\np\nə\nl\nə\n \nk\na\na\nl\nɔ\n \nt\na\nn\nɔ\nn\n;\n \nd\ni\n \nk\nɛ\nm\nɛ\nn\ni\n \na\n \nn\nu\nk\na\nn\n \nŋ\na\na\n \nɓ\nə\n \ng\nɛ\nɛ\n \nh\nw\nə\nk\nɛ\nl\ni\n \nw\nɛ\nl\ni\nk\nɛ\nm\na\na\n \nə\n \nl\nɔ\n \nd\ni\n \nl\nu\nw\na\ni\n.\nN\nu\nk\na\nn\n \ng\ne\nl\ne\n \nk\na\na\n \np\nə\nl\nə\n \nk\na\na\n \nt\na\nn\nɔ\nn\n,\n \ny\ni\nl\ni\nɓ\na\n \nn\nu\n \nk\nə\nl\ne\n \nm\na\na\nw\ni\ny\nə\n \np\nə\nl\nə\n \nd\na\n \nt\nɔ\nɔ\ni\n \ng\na\na\n \nɲ\ne\ni\n \ny\nɛ\nn\nɛ\ny\ni\ni\n \nh\nu\n \nk\nɛ\np\nə\nl\nə\n \nk\na\na\nl\nɔ\n \nt\na\nn\nɔ\nn\n;\n \nd\ni\n \nk\nɛ"
}
