id: "got_Runr"
language: "got"
script: "Runr"
name: "Gothic, Runic"
region: "UA"
sample_text {
  masthead_full: "ᚨᛚᛁᛗ"
  masthead_partial: "ᚾᚠ"
  styles: "ᚨᛚᛚᚨᛁ ᛗᚨᚾᚾᚨ ᚠᚱᛖᛁᚺᚨᛚᛋ ᛃᚨᚺ ᛋᚨᛗᚨᛚᛖᛁᚲᛟ ᛁᚾ ᚹᚨᛁᚱᚦᛁᛞᚨᛁ"
  tester: "ᚨᛚᛚᚨᛁ ᛗᚨᚾᚾᚨ ᚠᚱᛖᛁᚺᚨᛚᛋ ᛃᚨᚺ ᛋᚨᛗᚨᛚᛖᛁᚲᛟ ᛁᚾ ᚹᚨᛁᚱᚦᛁᛞᚨᛁ ᛃᚨᚺ ᚱᚨᛁᚺᛏᛖᛁᛋ"
  poster_sm: "ᚨᛚᛚᚨᛁ ᛗᚨᚾᚾᚨ"
  poster_md: "ᚨᛚᛚᚨᛁ"
  poster_lg: "ᚨᛚᛚᚨᛁ"
  specimen_48: "ᚨᛚᛚᚨᛁ ᛗᚨᚾᚾᚨ ᚠᚱᛖᛁᚺᚨᛚᛋ ᛃᚨᚺ ᛋᚨᛗᚨᛚᛖᛁᚲᛟ ᛁᚾ ᚹᚨᛁᚱᚦᛁᛞᚨᛁ ᛃᚨᚺ ᚱᚨᛁᚺᛏᛖᛁᛋ ᚹᚨᚢᚱᚦᚨᚾᛋ."
  specimen_36: "ᚨᛚᛚᚨᛁ ᛗᚨᚾᚾᚨ ᚠᚱᛖᛁᚺᚨᛚᛋ ᛃᚨᚺ ᛋᚨᛗᚨᛚᛖᛁᚲᛟ ᛁᚾ ᚹᚨᛁᚱᚦᛁᛞᚨᛁ ᛃᚨᚺ ᚱᚨᛁᚺᛏᛖᛁᛋ ᚹᚨᚢᚱᚦᚨᚾᛋ. ᚠᚱᚨᚦᛖᛁ ᛃᚨᚺ ᛗᛁᚦᚹᛁᛋᛋᛖᛁ ᚷᛁᛒᚾᚨᚾᛋ ᛃᚨᚺ ᛚᛁᛒᚨᚾᛞᚨᚢ ᛋᚹᛇ ᛒᚱᛟᚦᚱᛃᚢᛋ."
  specimen_32: "ᚨᛚᛚᚨᛁ ᛗᚨᚾᚾᚨ ᚠᚱᛖᛁᚺᚨᛚᛋ ᛃᚨᚺ ᛋᚨᛗᚨᛚᛖᛁᚲᛟ ᛁᚾ ᚹᚨᛁᚱᚦᛁᛞᚨᛁ ᛃᚨᚺ ᚱᚨᛁᚺᛏᛖᛁᛋ ᚹᚨᚢᚱᚦᚨᚾᛋ. ᚠᚱᚨᚦᛖᛁ ᛃᚨᚺ ᛗᛁᚦᚹᛁᛋᛋᛖᛁ ᚷᛁᛒᚾᚨᚾᛋ ᛃᚨᚺ ᛚᛁᛒᚨᚾᛞᚨᚢ ᛋᚹᛇ ᛒᚱᛟᚦᚱᛃᚢᛋ."
  specimen_21: "ᚨᛚᛚᚨᛁ ᛗᚨᚾᚾᚨ ᚠᚱᛖᛁᚺᚨᛚᛋ ᛃᚨᚺ ᛋᚨᛗᚨᛚᛖᛁᚲᛟ ᛁᚾ ᚹᚨᛁᚱᚦᛁᛞᚨᛁ ᛃᚨᚺ ᚱᚨᛁᚺᛏᛖᛁᛋ ᚹᚨᚢᚱᚦᚨᚾᛋ. ᚠᚱᚨᚦᛖᛁ ᛃᚨᚺ ᛗᛁᚦᚹᛁᛋᛋᛖᛁ ᚷᛁᛒᚾᚨᚾᛋ ᛃᚨᚺ ᛚᛁᛒᚨᚾᛞᚨᚢ ᛋᚹᛇ ᛒᚱᛟᚦᚱᛃᚢᛋ.\nᚨᛚᛚᚨᛁ ᛗᚨᚾᚾᚨ ᚠᚱᛖᛁᚺᚨᛚᛋ ᛃᚨᚺ ᛋᚨᛗᚨᛚᛖᛁᚲᛟ ᛁᚾ ᚹᚨᛁᚱᚦᛁᛞᚨᛁ ᛃᚨᚺ ᚱᚨᛁᚺᛏᛖᛁᛋ ᚹᚨᚢᚱᚦᚨᚾᛋ. ᚠᚱᚨᚦᛖᛁ ᛃᚨᚺ ᛗᛁᚦᚹᛁᛋᛋᛖᛁ ᚷᛁᛒᚾᚨᚾᛋ ᛃᚨᚺ ᛚᛁᛒᚨᚾᛞᚨᚢ ᛋᚹᛇ ᛒᚱᛟᚦᚱᛃᚢᛋ.\nᚨᛚᛚᚨᛁ ᛗᚨᚾᚾᚨ ᚠᚱᛖᛁᚺᚨᛚᛋ ᛃᚨᚺ ᛋᚨᛗᚨᛚᛖᛁᚲᛟ ᛁᚾ ᚹᚨᛁᚱᚦᛁᛞᚨᛁ ᛃᚨᚺ ᚱᚨᛁᚺᛏᛖᛁᛋ ᚹᚨᚢᚱᚦᚨᚾᛋ. ᚠᚱᚨᚦᛖᛁ ᛃᚨᚺ ᛗᛁᚦᚹᛁᛋᛋᛖᛁ ᚷᛁᛒᚾᚨᚾᛋ ᛃᚨᚺ ᛚᛁᛒᚨᚾᛞᚨᚢ ᛋᚹᛇ ᛒᚱᛟᚦᚱᛃᚢᛋ."
  specimen_16: "ᚨᛚᛚᚨᛁ ᛗᚨᚾᚾᚨ ᚠᚱᛖᛁᚺᚨᛚᛋ ᛃᚨᚺ ᛋᚨᛗᚨᛚᛖᛁᚲᛟ ᛁᚾ ᚹᚨᛁᚱᚦᛁᛞᚨᛁ ᛃᚨᚺ ᚱᚨᛁᚺᛏᛖᛁᛋ ᚹᚨᚢᚱᚦᚨᚾᛋ. ᚠᚱᚨᚦᛖᛁ ᛃᚨᚺ ᛗᛁᚦᚹᛁᛋᛋᛖᛁ ᚷᛁᛒᚾᚨᚾᛋ ᛃᚨᚺ ᛚᛁᛒᚨᚾᛞᚨᚢ ᛋᚹᛇ ᛒᚱᛟᚦᚱᛃᚢᛋ.\nᚨᛚᛚᚨᛁ ᛗᚨᚾᚾᚨ ᚠᚱᛖᛁᚺᚨᛚᛋ ᛃᚨᚺ ᛋᚨᛗᚨᛚᛖᛁᚲᛟ ᛁᚾ ᚹᚨᛁᚱᚦᛁᛞᚨᛁ ᛃᚨᚺ ᚱᚨᛁᚺᛏᛖᛁᛋ ᚹᚨᚢᚱᚦᚨᚾᛋ. ᚠᚱᚨᚦᛖᛁ ᛃᚨᚺ ᛗᛁᚦᚹᛁᛋᛋᛖᛁ ᚷᛁᛒᚾᚨᚾᛋ ᛃᚨᚺ ᛚᛁᛒᚨᚾᛞᚨᚢ ᛋᚹᛇ ᛒᚱᛟᚦᚱᛃᚢᛋ.\nᚨᛚᛚᚨᛁ ᛗᚨᚾᚾᚨ ᚠᚱᛖᛁᚺᚨᛚᛋ ᛃᚨᚺ ᛋᚨᛗᚨᛚᛖᛁᚲᛟ ᛁᚾ ᚹᚨᛁᚱᚦᛁᛞᚨᛁ ᛃᚨᚺ ᚱᚨᛁᚺᛏᛖᛁᛋ ᚹᚨᚢᚱᚦᚨᚾᛋ. ᚠᚱᚨᚦᛖᛁ ᛃᚨᚺ ᛗᛁᚦᚹᛁᛋᛋᛖᛁ ᚷᛁᛒᚾᚨᚾᛋ ᛃᚨᚺ ᛚᛁᛒᚨᚾᛞᚨᚢ ᛋᚹᛇ ᛒᚱᛟᚦᚱᛃᚢᛋ.\nᚨᛚᛚᚨᛁ ᛗᚨᚾᚾᚨ ᚠᚱᛖᛁᚺᚨᛚᛋ ᛃᚨᚺ ᛋᚨᛗᚨᛚᛖᛁᚲᛟ ᛁᚾ ᚹᚨᛁᚱᚦᛁᛞᚨᛁ ᛃᚨᚺ ᚱᚨᛁᚺᛏᛖᛁᛋ ᚹᚨᚢᚱᚦᚨᚾᛋ. ᚠᚱᚨᚦᛖᛁ ᛃᚨᚺ ᛗᛁᚦᚹᛁᛋᛋᛖᛁ ᚷᛁᛒᚾᚨᚾᛋ ᛃᚨᚺ ᛚᛁᛒᚨᚾᛞᚨᚢ ᛋᚹᛇ ᛒᚱᛟᚦᚱᛃᚢᛋ.\nᚨᛚᛚᚨᛁ ᛗᚨᚾᚾᚨ ᚠᚱᛖᛁᚺᚨᛚᛋ ᛃᚨᚺ ᛋᚨᛗᚨᛚᛖᛁᚲᛟ ᛁᚾ ᚹᚨᛁᚱᚦᛁᛞᚨᛁ ᛃᚨᚺ ᚱᚨᛁᚺᛏᛖᛁᛋ ᚹᚨᚢᚱᚦᚨᚾᛋ. ᚠᚱᚨᚦᛖᛁ ᛃᚨᚺ ᛗᛁᚦᚹᛁᛋᛋᛖᛁ ᚷᛁᛒᚾᚨᚾᛋ ᛃᚨᚺ ᛚᛁᛒᚨᚾᛞᚨᚢ ᛋᚹᛇ ᛒᚱᛟᚦᚱᛃᚢᛋ."
}
