id: "guz"
language: "guz"
script: "Latn"
name: "Gusii"
autonym: "Ekegusii"
population: 2622867
region: "KE"
exemplar_chars {
  base: "a b c d e f g h i j k l m n o p r s t u v w y z"
  auxiliary: "q x"
  index: "A B C D E F G H I J K L M N O P R S T U V W Y Z"
}
sample_text {
  fallback_language: "en"
}
