id: "gyr_Latn"
language: "gyr"
script: "Latn"
name: "Guarayu"
sample_text {
  masthead_full: "OoPp"
  masthead_partial: "Aa"
  styles: "O\np\na\nk\na\nt\nu\n \na\nv\na\n \ny\no\nr\no\n’\na\n \nn\nd"
  tester: "O\np\na\nk\na\nt\nu\n \na\nv\na\n \ny\no\nr\no\n’\na\n \nn\nd\na\n’\ne\ni\n \nt\ne\nm\nb\ni\ng"
  poster_sm: "O\np\na\nk\na\nt"
  poster_md: "O\np\na\nk\na"
  poster_lg: "O\np"
  specimen_48: "O\np\na\nk\na\nt\nu\n \na\nv\na\n \ny\no\nr\no\n’\na\n \nn\nd\na\n’\ne\ni\n \nt\ne\nm\nb\ni\ng"
  specimen_36: "O\np\na\nk\na\nt\nu\n \na\nv\na\n \ny\no\nr\no\n’\na\n \nn\nd\na\n’\ne\ni\n \nt\ne\nm\nb\ni\ng\nw\na\ni\ng\nw\na\n \no\ny\no\ny\na\nt\nu\np\nr\ni\n,\n \ns"
  specimen_32: "O\np\na\nk\na\nt\nu\n \na\nv\na\n \ny\no\nr\no\n’\na\n \nn\nd\na\n’\ne\ni\n \nt\ne\nm\nb\ni\ng\nw\na\ni\ng\nw\na\n \no\ny\no\ny\na\nt\nu\np\nr\ni\n,\n \ns\ne\nk\no\nt\nu\np\nr\ni\n,\n \nv\na\në\nr\na\n,\n \ni\nm\nb\no"
  specimen_21: "O\np\na\nk\na\nt\nu\n \na\nv\na\n \ny\no\nr\no\n’\na\n \nn\nd\na\n’\ne\ni\n \nt\ne\nm\nb\ni\ng\nw\na\ni\ng\nw\na\n \no\ny\no\ny\na\nt\nu\np\nr\ni\n,\n \ns\ne\nk\no\nt\nu\np\nr\ni\n,\n \nv\na\në\nr\na\n,\n \ni\nm\nb\no\ne\nt\ne\ni\ns\na\nr\na\n,\n \no\ni\nk\na\nt\nu\n \ni\np\ni\n’\na\n \ny\ne\nm\no\nñ\ne\nt\na\n,\n \ni\nm\nb\na\ne\nk\nu\na\n,\n \nn\nd\ni\ny\na\ni\n \ny\nu\nr\ne\nk\no\nr\na\ni\nr\na\ni\n \nñ\ne\np\në\ni\n \np\në\ni\n \na\nm\nb\nu\na\n \nr\ne\ns"
  specimen_16: "O\np\na\nk\na\nt\nu\n \na\nv\na\n \ny\no\nr\no\n’\na\n \nn\nd\na\n’\ne\ni\n \nt\ne\nm\nb\ni\ng\nw\na\ni\ng\nw\na\n \no\ny\no\ny\na\nt\nu\np\nr\ni\n,\n \ns\ne\nk\no\nt\nu\np\nr\ni\n,\n \nv\na\në\nr\na\n,\n \ni\nm\nb\no\ne\nt\ne\ni\ns\na\nr\na\n,\n \no\ni\nk\na\nt\nu\n \ni\np\ni\n’\na\n \ny\ne\nm\no\nñ\ne\nt\na\n,\n \ni\nm\nb\na\ne\nk\nu\na\n,\n \nn\nd\ni\ny\na\ni\n \ny\nu\nr\ne\nk\no\nr\na\ni\nr\na\ni\n \nñ\ne\np\në\ni\n \np\në\ni\n \na\nm\nb\nu\na\n \nr\ne\ns\ne\n.\nO\np\na\nk\na\nt\nu\n \na\nv\na\n \ny\no\nr\no\n’\na\n \nn\nd\na\n’\ne\ni\n \nt\ne\nm\nb\ni\ng\nw\na\ni\ng\nw\na\n \no\ny\no\ny\na\nt\nu\np\nr\ni\n,\n \ns\ne\nk\no\nt\nu\np\nr\ni\n,\n \nv\na\në\nr\na\n,\n \ni\nm\nb\no\ne\nt\ne\ni\ns\na\nr\na\n,\n \no\ni\nk\na\nt\nu\n \ni\np\ni\n’\na\n \ny\ne\nm\no\nñ\ne\nt\na\n,\n \ni\nm\nb\na\ne\nk\nu\na\n,\n \nn\nd\ni\ny\na\ni\n \ny\nu\nr\ne\nk"
}
