id: "ha_Arab"
name: "Hausa (Arabic)"
preferred_name: ""
autonym: ""
population: 2999231
region: "CM"
region: "NG"
region: "SD"
script: "Latin"
script: "Perso-Arabic"
exemplar_chars {
}
sample_text {
  fallback_language: "ha"
}
