id: "ha_Latn"
language: "ha"
script: "Latn"
name: "Hausa"
autonym: "Hausa"
population: 37412649
region: "GH"
region: "NE"
region: "NG"
exemplar_chars {
  base: "a b ɓ c d ɗ e f g h i j k ƙ l m n o r s {sh} t {ts} u w y ƴ z ʼ {sh} {ts} {sh} {ts} {sh} {ts} {sh} {ts} {sh} {ts} {sh} {ts} {sh} {ts} {sh} {ts} {sh} {ts} {sh} {ts} {sh} {ts} {sh} {ts} {sh} {ts} {sh} {ts} {sh} {ts}"
  auxiliary: "á à â é è ê í ì î ó ò ô p q {r̃} ú ù û v x {r̃} {r̃} {r̃} {r̃} {r̃} {r̃} {r̃} {r̃} {r̃} {r̃} {r̃} {r̃} {r̃} {r̃} {r̃}"
  marks: "◌̃ ◌̀ ◌́ ◌̂"
  punctuation: "- ‑ , ; : ! ? . \' ‘ ’ \" “ ” ( ) [ ] { } ′ ″ { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "A B Ɓ C D Ɗ E F G H I J K Ƙ L M N O R S T U W Y Ƴ Z"
}
sample_text {
  masthead_full: "DdUu"
  masthead_partial: "Kk"
  styles: "Duk ‘yan’adan ana haihuwarsu ne a matsayin"
  tester: "Duk ‘yan’adan ana haihuwarsu ne a matsayin ‘yantattun ‘ya’ya, kuma"
  poster_sm: "Duk ‘yan’adan"
  poster_md: "Duk ‘yan’adan"
  poster_lg: "Duk"
  specimen_48: "Duk ‘yan’adan ana haihuwarsu ne a matsayin ‘yantattun"
  specimen_36: "Duk ‘yan’adan ana haihuwarsu ne a matsayin ‘yantattun ‘ya’ya, kuma mutuncinsu da haqqoqinsu daidai yake da na kowa. Suna da tunani da cikakken hankali, saboda haka ake son duk mu’amalar da za su yi, ta kasance akwai ‘yan’uwantaka a tsakani."
  specimen_32: "Duk ‘yan’adan ana haihuwarsu ne a matsayin ‘yantattun ‘ya’ya, kuma mutuncinsu da haqqoqinsu daidai yake da na kowa. Suna da tunani da cikakken hankali, saboda haka ake son duk mu’amalar da za su yi, ta kasance akwai ‘yan’uwantaka a tsakani."
  specimen_21: "Duk ‘yan’adan ana haihuwarsu ne a matsayin ‘yantattun ‘ya’ya, kuma mutuncinsu da haqqoqinsu daidai yake da na kowa. Suna da tunani da cikakken hankali, saboda haka ake son duk mu’amalar da za su yi, ta kasance akwai ‘yan’uwantaka a tsakani.\nDuk ‘yan’adan ana haihuwarsu ne a matsayin ‘yantattun ‘ya’ya, kuma mutuncinsu da haqqoqinsu daidai yake da na kowa. Suna da tunani da cikakken hankali, saboda haka ake son duk mu’amalar da za su yi, ta kasance akwai ‘yan’uwantaka a tsakani."
  specimen_16: "Duk ‘yan’adan ana haihuwarsu ne a matsayin ‘yantattun ‘ya’ya, kuma mutuncinsu da haqqoqinsu daidai yake da na kowa. Suna da tunani da cikakken hankali, saboda haka ake son duk mu’amalar da za su yi, ta kasance akwai ‘yan’uwantaka a tsakani.\nDuk ‘yan’adan ana haihuwarsu ne a matsayin ‘yantattun ‘ya’ya, kuma mutuncinsu da haqqoqinsu daidai yake da na kowa. Suna da tunani da cikakken hankali, saboda haka ake son duk mu’amalar da za su yi, ta kasance akwai ‘yan’uwantaka a tsakani.\nDuk ‘yan’adan ana haihuwarsu ne a matsayin ‘yantattun ‘ya’ya, kuma mutuncinsu da haqqoqinsu daidai yake da na kowa. Suna da tunani da cikakken hankali, saboda haka ake son duk mu’amalar da za su yi, ta kasance akwai ‘yan’uwantaka a tsakani."
}
