id: "hak"
name: "Hakka Chinese"
preferred_name: ""
autonym: "客家话 / 客家話"
population: 32062459
region: "CN"
script: "Simplified Han"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U W X Y Z a b c d e f g h i j k l m n o p q r s t u w x y z ü ê ā ē ī ō ū ǖ Ā Ē Ī Ō Ū Ǖ á é í ó ú ǘ Á É Í Ó Ú Ǘ ǎ ě ǐ ǒ ǔ ǚ Ǎ Ě Ǐ Ǒ Ǔ Ǚ à è ì ò ù ǜ À È Ì Ò Ù Ǜ"
  auxiliary: "乒 乓 仂 仓 伞 侣 傈 傣 僳 冥 凉 刨 匕 卑 卞 厘 厦 厨 吕 呣 唇 啤 啮 喱 嗅 噘 噢 坝 堤 墟 奎 妆 婴 媚 宅 寺 尬 尴 屑 屿 巽 巾 弓 彗 惊 戟 扔 扰 扳 抛 挂 捂 摇 撅 撤 杆 杖 柜 柱 栗 栽 桶 棍 棕 棺 楔 楠 榈 槟 橙 洒 浆 涌 淇 滕 滚 滩 灾 烛 烟 焰 煎 犬 猫 瑚 瓢 甫 皱 盆 盔 盲 眨 眯 瞌 矿 碑 祈 祭 祷 禄 稻 竿 笼 筒 篷 粟 粮 纠 纬 缆 缎 耸 脚 舔 舵 艇 艮 芽 苜 苞 菇 菱 葫 葵 蒸 蓿 蔽 薯 蘑 蚂 蛛 蜗 蜘 蜡 蝎 蝴 螃 裹 谍 谬 豚 账 跤 踪 躬 轴 辐 迹 郁 鄙 酢 钉 钥 钮 钯 铂 铅 铛 锄 锑 锚 锤 镑 闺 阱 隧 雕 霾 靴 靶 鞠 颠 馏 驼 骆 髦 魁 鲤 鲸 鳄 鸽"
  marks: "◌̀ ◌́ ◌̂ ◌̄ ◌̈ ◌̌"
  numerals: "% + - . 0 1 2 3 4 5 6 7 8 9 ‰ 〇"
}
sample_text {
  masthead_full: "人生而自"
  masthead_partial: "由在"
  tester: "鉴于对人权个唔知同欺负已发展为刺蛮暴行，这些暴行玷污了人类个好心田，而一个人人享有言论同信仰自由并免予恐惧同匮乏个世界个来临"
  poster_sm: "发布这一世界人权宣言"
  poster_md: "人人有权享有生命"
  poster_lg: "人人生而自由"
  specimen_48: "法律之前人人平等，并有权享受法律个平等保护，唔受脉个歧视。人人有权享受平等保护，以免受违反本宣言个脉个歧视行为同煽动这种歧视个脉个行为之害"
  specimen_36: "鉴于对人类家庭所有成员个自然尊严及其平等个同唔移个权利个承认，系世界自由、正义同和平个墙脚，\n鉴于对人权个唔知同欺负已发展为刺蛮暴行，这些暴行玷污了人类个好心田，而一个人人享有言论同信仰自由并免予恐惧同匮乏个世界个来临，已被宣布为普通人民个最高意思，"
  specimen_32: "鉴于对人类家庭所有成员个自然尊严及其平等个同唔移个权利个承认，系世界自由、正义同和平个墙脚，\n鉴于对人权个唔知同欺负已发展为刺蛮暴行，这些暴行玷污了人类个好心田，而一个人人享有言论同信仰自由并免予恐惧同匮乏个世界个来临，已被宣布为普通人民个最高意思，\n鉴于为使人类唔至到唔好唔铤而走险对暴政同欺负进行反叛，爱使人权受法治个保护，"
  specimen_21: "鉴于对人类家庭所有成员个自然尊严及其平等个同唔移个权利个承认，系世界自由、正义同和平个墙脚，\n鉴于对人权个唔知同欺负已发展为刺蛮暴行，这些暴行玷污了人类个好心田，而一个人人享有言论同信仰自由并免予恐惧同匮乏个世界个来临，已被宣布为普通人民个最高意思，\n鉴于为使人类唔至到唔好唔铤而走险对暴政同欺负进行反叛，爱使人权受法治个保护，\n鉴于爱促进各国之间知己关系个发展，\n鉴于各联合国国家个人民已在联合国宪章之内重申佢丁人对基本人权、人格尊严同价值以及男女平等权利个信念，并决心促成较大自由之内个社会进步同生活水平个改善，\n鉴于各会员国业已誓愿同联合国合作以促进对人权同基本自由个普遍尊重同遵行，\n鉴于对这些权利同自由个知头知尾对于这个誓愿个充分实现具有死大个重要性，"
  specimen_16: "鉴于对人类家庭所有成员个自然尊严及其平等个同唔移个权利个承认，系世界自由、正义同和平个墙脚，\n鉴于对人权个唔知同欺负已发展为刺蛮暴行，这些暴行玷污了人类个好心田，而一个人人享有言论同信仰自由并免予恐惧同匮乏个世界个来临，已被宣布为普通人民个最高意思，\n鉴于为使人类唔至到唔好唔铤而走险对暴政同欺负进行反叛，爱使人权受法治个保护，\n鉴于爱促进各国之间知己关系个发展，\n鉴于各联合国国家个人民已在联合国宪章之内重申佢丁人对基本人权、人格尊严同价值以及男女平等权利个信念，并决心促成较大自由之内个社会进步同生活水平个改善，\n鉴于各会员国业已誓愿同联合国合作以促进对人权同基本自由个普遍尊重同遵行，\n鉴于对这些权利同自由个知头知尾对于这个誓愿个充分实现具有死大个重要性，\n因此现在，\n大会，\n发布这一世界人权宣言，作为所有人民同所有国家努力实现个共同标准，指望每一个人同社会机构时不时记等来本宣言，努力利用教诲同教育促进对权利同自由个尊重，并利用国家个同国际个渐进措施，使这些权利同自由在各会员国本身人民及在其管辖下领土个人民之内得到普遍同有效个承认同遵行；\n人人生而自由，在尊严同权利上一律平等。佢丁人赋有理性同好心田，并应以兄弟关系个精神相对待。\n人人有资格享有本宣言所记录个一切权利同自由，唔分种族、肤色、性别、语言、宗教、政治或其他见解、国籍或社会出身、财产、出生或其他身分等脉个区别。"
}
