id: "hak_Hant"
language: "hak"
script: "Hant"
name: "Hakka Chinese, Traditional"
region: "AU"
region: "BN"
region: "CN"
region: "GB"
region: "GF"
region: "HK"
region: "ID"
region: "MO"
region: "MY"
region: "PA"
region: "PF"
region: "PH"
region: "SR"
region: "TH"
region: "TW"
region: "US"
region: "VN"
sample_text {
  fallback_language: "zh_Hant"
}
