id: "he"
language: "he"
script: "Hebr"
name: "Hebrew"
autonym: "עברית"
population: 8675480
region: "IL"
exemplar_chars {
  base: "א ב ג ד ה ו ז ח ט י כ ך ל מ ם נ ן ס ע פ ף צ ץ ק ר ש ת"
  auxiliary: "ֽׄ‎‏ ְ ֱ ֲ ֳ ִ ֵ ֶ ַ ָ ֹ ֻ ׂ ׁ ּ ֿ ״"
  marks: "◌ְ ◌ֱ ◌ֲ ◌ֳ ◌ִ ◌ֵ ◌ֶ ◌ַ ◌ָ ◌ֹ ◌ֻ ◌ּ ◌ׁ ◌ׂ"
  numerals: "‎ - ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ? . ׳ \' \" ( ) [ ] / ״ ־"
  index: "א ב ג ד ה ו ז ח ט י כ ל מ נ ס ע פ צ ק ר ש ת"
}
sample_text {
  masthead_full: "כלבנ"
  masthead_partial: "יא"
  styles: "כל בני אדם נולדו בני חורין ושווים בערכם ובזכויותיהם."
  tester: "כל אדם זכאי לזכויות ולחרויות שנקבעו בהכרזש זו ללא הפליה כלשהיא"
  poster_sm: "גדולה מזו, לא"
  poster_md: "כל אדם יש"
  poster_lg: "בני"
  specimen_48: "לא יהיה אדם נתון לעינויים, ולא ליחס או לעונש אכזריים, בלתי אנושיים"
  specimen_36: "כל אחד זכאי לתקנה יעילה מטעם בחי הדין הלאומיים המוסמכים נגד מעשים המפירים את זכויות היסוד שניתנו לו על פי החוקה והחוקים."
  specimen_32: "כל אדם זכאי, מתוך שויון גמור עם זולתו, למשפט הוגן ופומבי של בית-דין כלתי תלוי וללא משוא פנים בשעה שבאים לקבוע זכויותיו וחובותיו ולברר כל אשמה פלילית שהובאה נגדו."
  specimen_21: "לא יהא אדם נתון להתערבות שרירותית בחייו הפרטיים, במשפחתו, במעונו, בחליפת מכתבים שלו ולא לפגיעה בכבודו או בשמו הפוב. כל אדם זכאי להגנת החוק בפני התערבות או פגיעה באלה.\nכל אדם זכאי לחירות המחשבה, המצפון והדת; חירות זו כוללת את הזכות להמיר את דתו או את אמונתו ולתת בטוי לדתו או לאמונתו, לבדו או כציבור, ברשות היחיד או ברשות הרבים, דרך הוראה, נוהג, פולחן ושמירת מצוות."
  specimen_16: "כל אדם זכאי לחירות הדעה והבטוי, לרבות החירות להחיק בדעות ללא כל הפרעה, ולבקש ידיעות ודעות, ולקבלן ולמסרן בכל הדרכים וללא סייגי גבולות.\nכל אדם, כחבר החברה, זכאי לבטחון סוציאלי וזכאי לתבוע שהזכויות הכלכליות הסוציאליות והתרבותיות, שהן חיוניות לכבודו כאדם ולהתפתחות החופשית של אישיותו, יובטחו במשמץ לאומי ובשיתוף פעולה בינלאומי בהתאם לארגונה ולאוצרותיה של המדינה.\nכל אדם זכאי למנוחה ולפנאי, ובכלל זש הגבלת שעות העבודה במידה המתקבלת על הדעת וחופשה בשכר לעיתים מזומנות.\nכל אדם זכאי למשטר סוציאלי ובינלאומי, שבו אפשר יהיה לקיים במלואן את הזכויות והחרויות אשר נקבעו בהכזש זו."
}
