id: "hea_Latn"
language: "hea"
script: "Latn"
name: "Hmong, Northern Qiandong"
sample_text {
  masthead_full: "LlAa"
  masthead_partial: "Ii"
  styles: "L\na\ni\nx\n \nl\na\ni\nx\n \nd\ni\na\nn\ng\nl\n \nd\na\nn\ng"
  tester: "L\na\ni\nx\n \nl\na\ni\nx\n \nd\ni\na\nn\ng\nl\n \nd\na\nn\ng\nt\n \nl\no\nl\n \ns\no\nb\n "
  poster_sm: "L\na\ni\nx\n \nl"
  poster_md: "L\na\ni\nx\n "
  poster_lg: "L\na"
  specimen_48: "L\na\ni\nx\n \nl\na\ni\nx\n \nd\ni\na\nn\ng\nl\n \nd\na\nn\ng\nt\n \nl\no\nl\n \ns\no\nb\n "
  specimen_36: "L\na\ni\nx\n \nl\na\ni\nx\n \nd\ni\na\nn\ng\nl\n \nd\na\nn\ng\nt\n \nl\no\nl\n \ns\no\nb\n \nd\na\nb\n \ny\na\nn\ng\nx\n \ng\nh\na\nx\n \nm\na\ni\nx\n "
  specimen_32: "L\na\ni\nx\n \nl\na\ni\nx\n \nd\ni\na\nn\ng\nl\n \nd\na\nn\ng\nt\n \nl\no\nl\n \ns\no\nb\n \nd\na\nb\n \ny\na\nn\ng\nx\n \ng\nh\na\nx\n \nm\na\ni\nx\n \nz\ni\nt\n \ny\ne\nf\n,\n \nn\ni\na\nn\ng\nb\n \nd\ni\no\nt"
  specimen_21: "L\na\ni\nx\n \nl\na\ni\nx\n \nd\ni\na\nn\ng\nl\n \nd\na\nn\ng\nt\n \nl\no\nl\n \ns\no\nb\n \nd\na\nb\n \ny\na\nn\ng\nx\n \ng\nh\na\nx\n \nm\na\ni\nx\n \nz\ni\nt\n \ny\ne\nf\n,\n \nn\ni\na\nn\ng\nb\n \nd\ni\no\nt\n \ng\ni\nd\n \nz\ne\nn\nb\n \nn\ni\ne\ne\nf\n \nh\na\ni\nb\n \ng\ni\nd\n \nq\nu\na\ni\nf\n \nl\ni\nt\n \ng\ni\nd\n \nn\no\nn\ng\nd\n \nj\nu\ns\n \nd\ni\ne\nl\n \np\ni\nn\nf\n \nd\ne\nn\nx\n.\n \nN\ne\nn\nx\n \nd\no\nl\n \nm\na\ni\nx\n \nl\na"
  specimen_16: "L\na\ni\nx\n \nl\na\ni\nx\n \nd\ni\na\nn\ng\nl\n \nd\na\nn\ng\nt\n \nl\no\nl\n \ns\no\nb\n \nd\na\nb\n \ny\na\nn\ng\nx\n \ng\nh\na\nx\n \nm\na\ni\nx\n \nz\ni\nt\n \ny\ne\nf\n,\n \nn\ni\na\nn\ng\nb\n \nd\ni\no\nt\n \ng\ni\nd\n \nz\ne\nn\nb\n \nn\ni\ne\ne\nf\n \nh\na\ni\nb\n \ng\ni\nd\n \nq\nu\na\ni\nf\n \nl\ni\nt\n \ng\ni\nd\n \nn\no\nn\ng\nd\n \nj\nu\ns\n \nd\ni\ne\nl\n \np\ni\nn\nf\n \nd\ne\nn\nx\n.\n \nN\ne\nn\nx\n \nd\no\nl\n \nm\na\ni\nx\n \nl\na\ni\nb\n \nl\ni\nx\n \nx\ne\nn\nt\n \nh\na\ni\nb\n \nj\no\nx\n \nh\nv\ni\nb\n \nv\nu\nt\n,\n \nn\ne\nn\nx\n \nd\no\nl\n \nn\no\nn\ng\nt\n \nl\ni\ne\nk\n \nb\ne\nd\n \nu\nt\n \ni\nd\n \nx\ni\nt\n \nd\ne\ni\nt\n \nd\na\ni\nt\n.\nL\na\ni\nx\n \nl\na\ni\nx\n \nd\ni\na\nn\ng\nl\n \nd\na\nn\ng\nt\n \nl\no\nl\n \ns\no\nb\n \nd\na\nb\n \ny\na\nn\ng\nx\n \ng\nh\na\nx\n \nm\na\ni\nx\n "
}
