id: "hlt_Latn"
language: "hlt"
script: "Latn"
name: "Chin, Matu"
sample_text {
  masthead_full: "TtHh"
  masthead_partial: "Ll"
  styles: "T\nh\nl\na\nn\ng\nb\no\ne\ni\nh\n \nh\ne\n \nr\nh\ni\nm\no\nm"
  tester: "T\nh\nl\na\nn\ng\nb\no\ne\ni\nh\n \nh\ne\n \nr\nh\ni\nm\no\nm\nn\na\n,\n \nv\na\nn\np\ni\nt"
  poster_sm: "T\nh\nl\na\nn\ng"
  poster_md: "T\nh\nl\na\nn"
  poster_lg: "T\nh"
  specimen_48: "T\nh\nl\na\nn\ng\nb\no\ne\ni\nh\n \nh\ne\n \nr\nh\ni\nm\no\nm\nn\na\n,\n \nv\na\nn\np\ni\nt"
  specimen_36: "T\nh\nl\na\nn\ng\nb\no\ne\ni\nh\n \nh\ne\n \nr\nh\ni\nm\no\nm\nn\na\n,\n \nv\na\nn\np\ni\nt\nn\na\n,\n \ny\na\nl\np\no\nn\na\n \nh\na\nm\nh\nm\no\ne\nl\n "
  specimen_32: "T\nh\nl\na\nn\ng\nb\no\ne\ni\nh\n \nh\ne\n \nr\nh\ni\nm\no\nm\nn\na\n,\n \nv\na\nn\np\ni\nt\nn\na\n,\n \ny\na\nl\np\no\nn\na\n \nh\na\nm\nh\nm\no\ne\nl\n \nk\na\n \nt\na\nw\nn\n \nt\nh\nl\na\nn\ng\n \nl\na\n \nc\nu"
  specimen_21: "T\nh\nl\na\nn\ng\nb\no\ne\ni\nh\n \nh\ne\n \nr\nh\ni\nm\no\nm\nn\na\n,\n \nv\na\nn\np\ni\nt\nn\na\n,\n \ny\na\nl\np\no\nn\na\n \nh\na\nm\nh\nm\no\ne\nl\n \nk\na\n \nt\na\nw\nn\n \nt\nh\nl\na\nn\ng\n \nl\na\n \nc\nu\nu\nn\n \nl\na\n \nn\ng\n’\no\nm\n \nu\n.\n \nT\nh\nl\na\nn\ng\nh\ni\nn\ng\n \nh\ne\n \na\nt\nh\na\ne\n-\nt\nh\ne\nn\n \np\na\ne\nk\nb\no\ne\n \nt\nh\na\ni\nn\na\n \nn\ne\nh\n \ny\na\nk\nm\ni\nn\ng\n \nt\nh\na\ni\nn\na\n \nm\no\ne\ni\nb\no\ne"
  specimen_16: "T\nh\nl\na\nn\ng\nb\no\ne\ni\nh\n \nh\ne\n \nr\nh\ni\nm\no\nm\nn\na\n,\n \nv\na\nn\np\ni\nt\nn\na\n,\n \ny\na\nl\np\no\nn\na\n \nh\na\nm\nh\nm\no\ne\nl\n \nk\na\n \nt\na\nw\nn\n \nt\nh\nl\na\nn\ng\n \nl\na\n \nc\nu\nu\nn\n \nl\na\n \nn\ng\n’\no\nm\n \nu\n.\n \nT\nh\nl\na\nn\ng\nh\ni\nn\ng\n \nh\ne\n \na\nt\nh\na\ne\n-\nt\nh\ne\nn\n \np\na\ne\nk\nb\no\ne\n \nt\nh\na\ni\nn\na\n \nn\ne\nh\n \ny\na\nk\nm\ni\nn\ng\n \nt\nh\na\ni\nn\na\n \nm\no\ne\ni\nb\no\ne\n \nk\na\n \nt\na\nw\nn\n \nt\nh\nl\na\nn\ng\n \nl\na\n \nn\n’\no\nm\n \nu\n \nd\no\nn\ng\n \na\nh\n \nk\nh\na\nt\n \nn\ne\nh\n \nk\nh\na\nt\n \nl\nu\nn\ng\nv\na\nt\n \nn\na\n \nn\ne\nh\n \nt\nh\nl\no\ne\nh\nl\na\nn\n \nv\no\ne\nk\nh\nl\na\nk\n \nu\n \nt\nh\na\ne\n \nh\na\nm\n \no\nm\n.\nT\nh\nl\na\nn\ng\nb\no\ne\ni\nh\n \nh\ne\n \nr\nh\ni\nm\no\nm\nn\na\n,\n \nv\na\nn\np\ni\nt"
}
