id: "hna_Latn"
language: "hna"
script: "Latn"
name: "Mina"
sample_text {
  masthead_full: "AaGg"
  masthead_partial: "Bb"
  styles: "A\ng\nb\ne\nt\nɔ\nw\no\n \nk\np\na\nt\na\n \nl\ne\n \nj\ni\nj"
  tester: "A\ng\nb\ne\nt\nɔ\nw\no\n \nk\np\na\nt\na\n \nl\ne\n \nj\ni\nj\ni\nm\nɛ\na\n,\n \nɖ\no\n \nv"
  poster_sm: "A\ng\nb\ne\nt\nɔ"
  poster_md: "A\ng\nb\ne\nt"
  poster_lg: "A\ng"
  specimen_48: "A\ng\nb\ne\nt\nɔ\nw\no\n \nk\np\na\nt\na\n \nl\ne\n \nj\ni\nj\ni\nm\nɛ\na\n,\n \nɖ\no\n \nv"
  specimen_36: "A\ng\nb\ne\nt\nɔ\nw\no\n \nk\np\na\nt\na\n \nl\ne\n \nj\ni\nj\ni\nm\nɛ\na\n,\n \nɖ\no\n \nv\no\ns\ni\nn\nɔ\nn\nɔ\n,\n \nn\ny\ni\n \ng\nb\nè\ns\nɔ\nɛ\ń\nm"
  specimen_32: "A\ng\nb\ne\nt\nɔ\nw\no\n \nk\np\na\nt\na\n \nl\ne\n \nj\ni\nj\ni\nm\nɛ\na\n,\n \nɖ\no\n \nv\no\ns\ni\nn\nɔ\nn\nɔ\n,\n \nn\ny\ni\n \ng\nb\nè\ns\nɔ\nɛ\ń\nm\nɛ\ń\nw\nó\n \nl\ne\n \nn\nu\nj\nɔ\nn\nu\nn\nn\ny\ni\n \nk\nu"
  specimen_21: "A\ng\nb\ne\nt\nɔ\nw\no\n \nk\np\na\nt\na\n \nl\ne\n \nj\ni\nj\ni\nm\nɛ\na\n,\n \nɖ\no\n \nv\no\ns\ni\nn\nɔ\nn\nɔ\n,\n \nn\ny\ni\n \ng\nb\nè\ns\nɔ\nɛ\ń\nm\nɛ\ń\nw\nó\n \nl\ne\n \nn\nu\nj\nɔ\nn\nu\nn\nn\ny\ni\n \nk\nu\n \ng\no\nɖ\no\ne\nj\ni\ns\ne\nw\no\n,\n \na\nm\nɛ\nb\nu\ns\ne\nw\no\n \nm\nɛ\n.\n \nT\na\ng\nb\nɔ\n \nl\ne\n \nw\no\na\n \ns\ni\n,\n \ne\ny\ne\n \nw\nɔ\nn\na\nw\no\n \ns\nɔ\nd\no\nd\na\n \nw\no\na\nn\nɔ\nn\nɔ\nw\no\n \ng\nb\nɔ\na\n \nl\na\n "
  specimen_16: "A\ng\nb\ne\nt\nɔ\nw\no\n \nk\np\na\nt\na\n \nl\ne\n \nj\ni\nj\ni\nm\nɛ\na\n,\n \nɖ\no\n \nv\no\ns\ni\nn\nɔ\nn\nɔ\n,\n \nn\ny\ni\n \ng\nb\nè\ns\nɔ\nɛ\ń\nm\nɛ\ń\nw\nó\n \nl\ne\n \nn\nu\nj\nɔ\nn\nu\nn\nn\ny\ni\n \nk\nu\n \ng\no\nɖ\no\ne\nj\ni\ns\ne\nw\no\n,\n \na\nm\nɛ\nb\nu\ns\ne\nw\no\n \nm\nɛ\n.\n \nT\na\ng\nb\nɔ\n \nl\ne\n \nw\no\na\n \ns\ni\n,\n \ne\ny\ne\n \nw\nɔ\nn\na\nw\no\n \ns\nɔ\nd\no\nd\na\n \nw\no\na\nn\nɔ\nn\nɔ\nw\no\n \ng\nb\nɔ\na\n \nl\na\n \nn\ny\ni\n \nn\nɔ\ń\nv\ni\ns\ni\nl\né\nl\né\n.\nA\ng\nb\ne\nt\nɔ\nw\no\n \nk\np\na\nt\na\n \nl\ne\n \nj\ni\nj\ni\nm\nɛ\na\n,\n \nɖ\no\n \nv\no\ns\ni\nn\nɔ\nn\nɔ\n,\n \nn\ny\ni\n \ng\nb\nè\ns\nɔ\nɛ\ń\nm\nɛ\ń\nw\nó\n \nl\ne\n \nn\nu\nj\nɔ\nn\nu\nn\nn\ny\ni\n \nk\nu\n \ng\no\nɖ\no\ne\nj\ni\ns\ne\nw\no\n,\n \na\nm\nɛ\nb\nu\ns\ne\nw\no\n \nm\nɛ\n.\n \nT\na\ng\nb\nɔ\n \nl\ne\n \nw\no\na"
}
