id: "hne_Deva"
language: "hne"
script: "Deva"
name: "Chhattisgarhi"
population: 14586990
region: "IN"
sample_text {
  masthead_full: "सबलग"
  masthead_partial: "नम"
  styles: "स\nब\nो\n \nल\nो\nग\nन\n \nम\nन\n \nक\nे\n \nग\nौ\nर\nव\n \nअ\nऊ\n "
  tester: "स\nब\nो\n \nल\nो\nग\nन\n \nम\nन\n \nक\nे\n \nग\nौ\nर\nव\n \nअ\nऊ\n \nअ\nध\nि\nक\nा\nर\n \nम\nन\n \nक"
  poster_sm: "स\nब\nो\n \nल\nो\nग"
  poster_md: "स\nब\nो\n \nल"
  poster_lg: "स\nब"
  specimen_48: "स\nब\nो\n \nल\nो\nग\nन\n \nम\nन\n \nक\nे\n \nग\nौ\nर\nव\n \nअ\nऊ\n \nअ\nध\nि\nक\nा\nर\n \nम\nन\n \nक"
  specimen_36: "स\nब\nो\n \nल\nो\nग\nन\n \nम\nन\n \nक\nे\n \nग\nौ\nर\nव\n \nअ\nऊ\n \nअ\nध\nि\nक\nा\nर\n \nम\nन\n \nक\nे\n \nम\nा\nम\nल\nा\n \nम\n \nज\nन\nम\n \nल\nे\n \nम\nि\nल\nे\n \nस"
  specimen_32: "स\nब\nो\n \nल\nो\nग\nन\n \nम\nन\n \nक\nे\n \nग\nौ\nर\nव\n \nअ\nऊ\n \nअ\nध\nि\nक\nा\nर\n \nम\nन\n \nक\nे\n \nम\nा\nम\nल\nा\n \nम\n \nज\nन\nम\n \nल\nे\n \nम\nि\nल\nे\n \nस\n्\nव\nत\nं\nत\n्\nर\nत\nा\n \nअ\nऊ\n \nब\nर\nो\nब\nर\nी\n \nम\nि\nल"
  specimen_21: "स\nब\nो\n \nल\nो\nग\nन\n \nम\nन\n \nक\nे\n \nग\nौ\nर\nव\n \nअ\nऊ\n \nअ\nध\nि\nक\nा\nर\n \nम\nन\n \nक\nे\n \nम\nा\nम\nल\nा\n \nम\n \nज\nन\nम\n \nल\nे\n \nम\nि\nल\nे\n \nस\n्\nव\nत\nं\nत\n्\nर\nत\nा\n \nअ\nऊ\n \nब\nर\nो\nब\nर\nी\n \nम\nि\nल\nे\n \nह\nे\n।\n \nओ\nम\nन\n \nल\n \nब\nु\nद\n्\nध\nि\n \nअ\nऊ\n \nअ\nन\n्\nत\nर\nा\nत\n्\nम\nा\n \nक\nे\n \nद\nे\nन\n \nम\nि\nल\nे\n \nह\nे\n \nअ\nऊ\n \nओ\nम\nन\n \nल\n \nए\nक\n \nद\nू\nस\nर\n \nल\n \nप\nर\nे\nम\n \nभ\nा\nई\nच\nा\nर\nा\n \nक\nे\n \nभ\nा\nव\n \nल\nे\n \nब\nे"
  specimen_16: "स\nब\nो\n \nल\nो\nग\nन\n \nम\nन\n \nक\nे\n \nग\nौ\nर\nव\n \nअ\nऊ\n \nअ\nध\nि\nक\nा\nर\n \nम\nन\n \nक\nे\n \nम\nा\nम\nल\nा\n \nम\n \nज\nन\nम\n \nल\nे\n \nम\nि\nल\nे\n \nस\n्\nव\nत\nं\nत\n्\nर\nत\nा\n \nअ\nऊ\n \nब\nर\nो\nब\nर\nी\n \nम\nि\nल\nे\n \nह\nे\n।\n \nओ\nम\nन\n \nल\n \nब\nु\nद\n्\nध\nि\n \nअ\nऊ\n \nअ\nन\n्\nत\nर\nा\nत\n्\nम\nा\n \nक\nे\n \nद\nे\nन\n \nम\nि\nल\nे\n \nह\nे\n \nअ\nऊ\n \nओ\nम\nन\n \nल\n \nए\nक\n \nद\nू\nस\nर\n \nल\n \nप\nर\nे\nम\n \nभ\nा\nई\nच\nा\nर\nा\n \nक\nे\n \nभ\nा\nव\n \nल\nे\n \nब\nे\nव\nह\nा\nर\n \nक\nर\nन\nा\n \nच\nा\nह\nी\n।\nस\nब\nो\n \nल\nो\nग\nन\n \nम\nन\n \nक\nे\n \nग\nौ\nर\nव\n \nअ\nऊ\n \nअ\nध\nि\nक\nा\nर\n \nम\nन\n \nक\nे\n \nम\nा\nम\nल\nा\n \nम\n \nज\nन\nम\n \nल\nे\n \nम\nि\nल\nे\n \nस\n्\nव\nत\nं\nत\n्\nर\nत\nा\n \nअ\nऊ\n \nब\nर\nो\nब\nर\nी\n \nम\nि\nल\nे\n \nह\nे\n।\n \nओ\nम\nन\n \nल\n \nब\nु\nद\n्\nध\nि\n \nअ\nऊ\n \nअ\nन\n्\nत\nर\nा\nत\n्\nम\nा\n \nक\nे\n \nद\nे\nन\n \nम\nि\nल\nे\n \nह\nे\n \nअ\nऊ"
}
