id: "hni_Latn"
language: "hni"
script: "Latn"
name: "Hani"
sample_text {
  masthead_full: "AaQq"
  masthead_partial: "Ss"
  styles: "A\nq\ns\no\nl\n \nl\ni\nq\n \ny\no\nq\nd\ne\ni\nv\nq\n \ny\no"
  tester: "A\nq\ns\no\nl\n \nl\ni\nq\n \ny\no\nq\nd\ne\ni\nv\nq\n \ny\no\nq\np\ny\nu\nq\n \nb\no\n,\n "
  poster_sm: "A\nq\ns\no\nl\n "
  poster_md: "A\nq\ns\no\nl"
  poster_lg: "A\nq"
  specimen_48: "A\nq\ns\no\nl\n \nl\ni\nq\n \ny\no\nq\nd\ne\ni\nv\nq\n \ny\no\nq\np\ny\nu\nq\n \nb\no\n,\n "
  specimen_36: "A\nq\ns\no\nl\n \nl\ni\nq\n \ny\no\nq\nd\ne\ni\nv\nq\n \ny\no\nq\np\ny\nu\nq\n \nb\no\n,\n \nm\ne\ne\nq\ny\na\no\nv\nq\n \ns\ns\no\nl\nn\ne\ni\n \nc\no"
  specimen_32: "A\nq\ns\no\nl\n \nl\ni\nq\n \ny\no\nq\nd\ne\ni\nv\nq\n \ny\no\nq\np\ny\nu\nq\n \nb\no\n,\n \nm\ne\ne\nq\ny\na\no\nv\nq\n \ns\ns\no\nl\nn\ne\ni\n \nc\no\nl\np\ny\nu\nq\n \nq\ni\nq\n \nk\no\nv\n \nd\ne\ni\n.\n \nD\na"
  specimen_21: "A\nq\ns\no\nl\n \nl\ni\nq\n \ny\no\nq\nd\ne\ni\nv\nq\n \ny\no\nq\np\ny\nu\nq\n \nb\no\n,\n \nm\ne\ne\nq\ny\na\no\nv\nq\n \ns\ns\no\nl\nn\ne\ni\n \nc\no\nl\np\ny\nu\nq\n \nq\ni\nq\n \nk\no\nv\n \nd\ne\ni\n.\n \nD\na\nv\nq\nt\na\nv\nc\no\nl\ns\ns\na\nq\n \nn\ne\ne\nn\ny\nu\nq\n \nb\ne\nl\n \nn\ne\ne\nm\na\n \nm\ne\ne\nq\n \ny\na\n \ns\ni\nq\n,\n \nl\na\no\nn\ng\na\no\nq\n \nm\ne\ni\nl\nn\na\no\nl\n \nn\na\nd\nu\nl\n \nm\ne\ni\nl\n \ne\n \ng\na\nq\n \ns"
  specimen_16: "A\nq\ns\no\nl\n \nl\ni\nq\n \ny\no\nq\nd\ne\ni\nv\nq\n \ny\no\nq\np\ny\nu\nq\n \nb\no\n,\n \nm\ne\ne\nq\ny\na\no\nv\nq\n \ns\ns\no\nl\nn\ne\ni\n \nc\no\nl\np\ny\nu\nq\n \nq\ni\nq\n \nk\no\nv\n \nd\ne\ni\n.\n \nD\na\nv\nq\nt\na\nv\nc\no\nl\ns\ns\na\nq\n \nn\ne\ne\nn\ny\nu\nq\n \nb\ne\nl\n \nn\ne\ne\nm\na\n \nm\ne\ne\nq\n \ny\na\n \ns\ni\nq\n,\n \nl\na\no\nn\ng\na\no\nq\n \nm\ne\ni\nl\nn\na\no\nl\n \nn\na\nd\nu\nl\n \nm\ne\ni\nl\n \ne\n \ng\na\nq\n \ns\ns\no\nl\n \nh\nh\ny\nu\nl\n \nh\nh\na\n \nb\na\nv\nq\nd\nu\nv\n \nn\ni\na\n.\nA\nq\ns\no\nl\n \nl\ni\nq\n \ny\no\nq\nd\ne\ni\nv\nq\n \ny\no\nq\np\ny\nu\nq\n \nb\no\n,\n \nm\ne\ne\nq\ny\na\no\nv\nq\n \ns\ns\no\nl\nn\ne\ni\n \nc\no\nl\np\ny\nu\nq\n \nq\ni\nq\n \nk\no\nv\n \nd\ne\ni\n.\n \nD\na\nv\nq\nt\na\nv\nc\no\nl\ns\ns\na\nq\n \nn\ne\ne\nn\ny\nu\nq\n \nb\ne\nl\n \nn\ne\ne\nm"
}
