id: "hnj"
language: "hnj"
script: "Laoo"
name: "Mong Njua"
population: 0
region: "LA"
sample_text {
  masthead_full: "CcUu"
  masthead_partial: "Aa"
  styles: "Haik zos duef ndax deb nenb houd juab tinx"
  tester: "Haik zos duef nenb ndas dos nuaf zhit dluad muas tab qib dlangs"
  poster_sm: "Haik zos wef"
  poster_md: "Haik zos"
  poster_lg: "Cuat"
  specimen_48: "Haik zos Jinx hox gox cuat lob gox juab nit renx minx nyaob houd"
  specimen_36: "Cuat lenx cuat dol nyaob lob deb qeut dus dis muax ndos lenl zos yos nyaob ndeuf ged jait nit renx gex."
  specimen_32: "Hiak zos cuat lob huef yinx gox dud zheuf das yinf yif dros Jinx hox gox hox zox lol ceub njet duef nenb ndas dos tab jib bend zif youx, guas pud pinf shaib doul tab zhox droud;"
  specimen_21: "Haik zos duef ndax deb nenb houd juab tinx id cuat lenx cuat dol druax jangs muax nit zunb yinx tab nil buab zhit zangd zhit dongf nit ndas dos nit chenx renf, yaos ndax deb dax zis, hof ged tab hox pinx nit ghangb das deut;\nHaik zos wef zhit guas ndax deb nenb zhit doul del maof xind duef cangx baof zhenf zhif tab ghuab yuaf nzend shab nzend bleud, sheud bual uat shud, muax bix yaof guas nenb ndas dos sheuf ged jait ged lil baod fuf;"
  specimen_16: "Haik zos duef ndax deb nenb houd juab tinx id cuat lenx cuat dol druax jangs muax nit zunb yinx tab nil buab zhit zangd zhit dongf nit ndas dos nit chenx renf, yaos ndax deb dax zis, hof ged tab hox pinx nit ghangb das deut;\nHaik zos duef nenb ndas dos nuaf zhit dluad muas tab qib dlangs qib dlend hlob hlangd dout uat shangb uat shud, dex uat shangb uat shud nad, muab ndax dex nenb nit liangx xinb shab nzhuk zhuak bual leuf; lb lob cuat lenx cuat dol sheuf muax nit ged haik fol suex shab, ged nzhes zit haib youx yol, zhit drous nchait zhit drous hef, zhit zhof chaib zhit zhof nkhek nit ndax deb yat lol zos, zhof ntuad haik uat ndax deb nenb nit zuef shab yinf vangf leuf;"
}
