id: "hnj_Latn"
language: "hnj"
script: "Latn"
name: "Hmong Njua"
region: "AC"
region: "AD"
region: "AF"
region: "AG"
region: "AI"
region: "AL"
region: "AM"
region: "AO"
region: "AR"
region: "AS"
region: "AT"
region: "AU"
region: "AW"
region: "AX"
region: "AZ"
region: "BA"
region: "BB"
region: "BD"
region: "BE"
region: "BF"
region: "BG"
region: "BI"
region: "BJ"
region: "BL"
region: "BM"
region: "BN"
region: "BO"
region: "BQ"
region: "BR"
region: "BS"
region: "BT"
region: "BW"
region: "BY"
region: "BZ"
region: "CA"
region: "CC"
region: "CD"
region: "CF"
region: "CG"
region: "CH"
region: "CI"
region: "CK"
region: "CL"
region: "CM"
region: "CN"
region: "CO"
region: "CR"
region: "CU"
region: "CV"
region: "CW"
region: "CX"
region: "CY"
region: "CZ"
region: "DE"
region: "DG"
region: "DJ"
region: "DK"
region: "DM"
region: "DO"
region: "DZ"
region: "EA"
region: "EC"
region: "EE"
region: "EG"
region: "ER"
region: "ES"
region: "ET"
region: "FI"
region: "FJ"
region: "FK"
region: "FM"
region: "FO"
region: "FR"
region: "GA"
region: "GB"
region: "GD"
region: "GE"
region: "GF"
region: "GG"
region: "GH"
region: "GI"
region: "GL"
region: "GM"
region: "GN"
region: "GP"
region: "GQ"
region: "GR"
region: "GT"
region: "GU"
region: "GW"
region: "GY"
region: "HK"
region: "HN"
region: "HR"
region: "HT"
region: "HU"
region: "IC"
region: "ID"
region: "IE"
region: "IL"
region: "IM"
region: "IN"
region: "IO"
region: "IQ"
region: "IR"
region: "IS"
region: "IT"
region: "JE"
region: "JM"
region: "JO"
region: "KE"
region: "KG"
region: "KI"
region: "KM"
region: "KN"
region: "KY"
region: "KZ"
region: "LA"
region: "LB"
region: "LC"
region: "LI"
region: "LK"
region: "LR"
region: "LS"
region: "LT"
region: "LU"
region: "LV"
region: "MA"
region: "MC"
region: "MD"
region: "ME"
region: "MF"
region: "MG"
region: "MH"
region: "MK"
region: "ML"
region: "MM"
region: "MN"
region: "MO"
region: "MP"
region: "MQ"
region: "MR"
region: "MS"
region: "MT"
region: "MU"
region: "MW"
region: "MX"
region: "MY"
region: "MZ"
region: "NA"
region: "NC"
region: "NE"
region: "NF"
region: "NG"
region: "NI"
region: "NL"
region: "NO"
region: "NP"
region: "NR"
region: "NU"
region: "NZ"
region: "PA"
region: "PE"
region: "PF"
region: "PG"
region: "PH"
region: "PK"
region: "PL"
region: "PM"
region: "PN"
region: "PR"
region: "PT"
region: "PW"
region: "PY"
region: "RE"
region: "RO"
region: "RS"
region: "RU"
region: "RW"
region: "SB"
region: "SC"
region: "SD"
region: "SE"
region: "SG"
region: "SH"
region: "SI"
region: "SJ"
region: "SK"
region: "SL"
region: "SM"
region: "SN"
region: "SO"
region: "SR"
region: "SS"
region: "ST"
region: "SV"
region: "SX"
region: "SY"
region: "SZ"
region: "TA"
region: "TC"
region: "TD"
region: "TF"
region: "TG"
region: "TH"
region: "TJ"
region: "TK"
region: "TL"
region: "TM"
region: "TN"
region: "TO"
region: "TR"
region: "TT"
region: "TV"
region: "TW"
region: "TZ"
region: "UA"
region: "UG"
region: "UM"
region: "US"
region: "UY"
region: "UZ"
region: "VA"
region: "VC"
region: "VE"
region: "VG"
region: "VI"
region: "VN"
region: "VU"
region: "WF"
region: "WS"
region: "XK"
region: "YE"
region: "YT"
region: "ZA"
region: "ZM"
region: "ZW"
sample_text {
  masthead_full: "CcUu"
  masthead_partial: "Aa"
  styles: "C\nu\na\nt\n \nl\ne\nn\nx\n \nc\nu\na\nt\n \nd\no\nl\n \nb\no"
  tester: "C\nu\na\nt\n \nl\ne\nn\nx\n \nc\nu\na\nt\n \nd\no\nl\n \nb\no\nn\ng\nb\n \nd\ne\nu\nl\n \nn"
  poster_sm: "C\nu\na\nt\n \nl"
  poster_md: "C\nu\na\nt\n "
  poster_lg: "C\nu"
  specimen_48: "C\nu\na\nt\n \nl\ne\nn\nx\n \nc\nu\na\nt\n \nd\no\nl\n \nb\no\nn\ng\nb\n \nd\ne\nu\nl\n \nn"
  specimen_36: "C\nu\na\nt\n \nl\ne\nn\nx\n \nc\nu\na\nt\n \nd\no\nl\n \nb\no\nn\ng\nb\n \nd\ne\nu\nl\n \nn\nd\na\nx\n \nd\ne\nx\n \nd\no\nu\nf\n \nm\nu\na\nx\n \nz\ni"
  specimen_32: "C\nu\na\nt\n \nl\ne\nn\nx\n \nc\nu\na\nt\n \nd\no\nl\n \nb\no\nn\ng\nb\n \nd\ne\nu\nl\n \nn\nd\na\nx\n \nd\ne\nx\n \nd\no\nu\nf\n \nm\nu\na\nx\n \nz\ni\nf\n \ny\no\nu\nx\n,\n \nn\ny\na\no\nb\n \ns\nh\no\nu\nt\n "
  specimen_21: "C\nu\na\nt\n \nl\ne\nn\nx\n \nc\nu\na\nt\n \nd\no\nl\n \nb\no\nn\ng\nb\n \nd\ne\nu\nl\n \nn\nd\na\nx\n \nd\ne\nx\n \nd\no\nu\nf\n \nm\nu\na\nx\n \nz\ni\nf\n \ny\no\nu\nx\n,\n \nn\ny\na\no\nb\n \ns\nh\no\nu\nt\n \nz\nu\nn\nb\n \ny\ni\nn\nx\n \nt\na\nb\n \nn\nd\na\ns\n \nd\no\ns\n \ni\nd\n,\n \nd\na\nx\n \nz\ni\ns\n \ni\nb\n \ns\nu\nk\n.\n \nN\ni\nl\n \nb\nu\na\nb\n \nd\na\nf\n \nl\no\nl\n \nj\na\no\nx\n \nm\nu\na\nx\n \nl\ni\nd\n \nx\ni\nn\nf\n \nh\nl"
  specimen_16: "C\nu\na\nt\n \nl\ne\nn\nx\n \nc\nu\na\nt\n \nd\no\nl\n \nb\no\nn\ng\nb\n \nd\ne\nu\nl\n \nn\nd\na\nx\n \nd\ne\nx\n \nd\no\nu\nf\n \nm\nu\na\nx\n \nz\ni\nf\n \ny\no\nu\nx\n,\n \nn\ny\na\no\nb\n \ns\nh\no\nu\nt\n \nz\nu\nn\nb\n \ny\ni\nn\nx\n \nt\na\nb\n \nn\nd\na\ns\n \nd\no\ns\n \ni\nd\n,\n \nd\na\nx\n \nz\ni\ns\n \ni\nb\n \ns\nu\nk\n.\n \nN\ni\nl\n \nb\nu\na\nb\n \nd\na\nf\n \nl\no\nl\n \nj\na\no\nx\n \nm\nu\na\nx\n \nl\ni\nd\n \nx\ni\nn\nf\n \nh\nl\nu\nb\n \nh\no\nu\nt\n \nt\na\nb\n \nl\ni\na\nn\ng\nx\n \nx\ni\nn\nb\n \ns\nh\na\nb\n \nn\nz\nh\nu\nk\n,\n \ny\ni\nn\nf\n \ng\na\ni\nb\n \nk\ne\nu\nk\n \ns\nu\nk\n \ng\nu\nd\n \nd\ni\nx\n \nm\no\nl\n \nl\no\nl\n \nn\ni\nt\n \nj\ni\nn\nb\n \ns\nh\ne\nn\nx\n \nl\no\nl\n \ns\nh\ni\nb\n \nd\na\nf\n \ns\nh\ni\nb\n \nh\nl\na\nd\n.\nC\nu\na\nt\n \nl\ne\nn\nx\n \nc\nu\na\nt\n \nd\no"
}
