id: "hnn_Hano"
language: "hnn"
script: "Hano"
name: "Hanunoo, Hanunoo"
autonym: "ᜱᜨᜳᜨᜳᜢ"
population: 0
exemplar_chars {
  base: "ᜠ ᜡ ᜢ ᜣ ᜤ ᜥ ᜦ ᜧ ᜨ ᜩ ᜪ ᜫ ᜬ ᜭ ᜮ ᜯ ᜰ ᜱ"
  marks: "◌ᜲ ◌ᜳ ◌᜴"
  punctuation: "᜵ ᜶"
}
