id: "hns_Latn"
language: "hns"
script: "Latn"
name: "Hindustani, Sarnami"
sample_text {
  masthead_full: "SsAa"
  masthead_partial: "Bb"
  styles: "S\na\nb\n \nd\nj\na\nn\nn\ne\n \na\na\nd\nj\ná\nd\ni\n \na\nu"
  tester: "S\na\nb\n \nd\nj\na\nn\nn\ne\n \na\na\nd\nj\ná\nd\ni\n \na\nu\nr\n \nb\na\nr\na\nb\na\nr\n "
  poster_sm: "S\na\nb\n \nd\nj"
  poster_md: "S\na\nb\n \nd"
  poster_lg: "S\na"
  specimen_48: "S\na\nb\n \nd\nj\na\nn\nn\ne\n \na\na\nd\nj\ná\nd\ni\n \na\nu\nr\n \nb\na\nr\na\nb\na\nr\n "
  specimen_36: "S\na\nb\n \nd\nj\na\nn\nn\ne\n \na\na\nd\nj\ná\nd\ni\n \na\nu\nr\n \nb\na\nr\na\nb\na\nr\n \np\na\ni\nd\na\na\n \nb\nh\na\ni\nl\nè\nn\n,\n \ni\nd\nd\nj"
  specimen_32: "S\na\nb\n \nd\nj\na\nn\nn\ne\n \na\na\nd\nj\ná\nd\ni\n \na\nu\nr\n \nb\na\nr\na\nb\na\nr\n \np\na\ni\nd\na\na\n \nb\nh\na\ni\nl\nè\nn\n,\n \ni\nd\nd\nj\na\nt\n \na\nu\nr\n \nh\na\nk\n \nm\nê\n.\n \nO\nh\ni\n \nd\nj"
  specimen_21: "S\na\nb\n \nd\nj\na\nn\nn\ne\n \na\na\nd\nj\ná\nd\ni\n \na\nu\nr\n \nb\na\nr\na\nb\na\nr\n \np\na\ni\nd\na\na\n \nb\nh\na\ni\nl\nè\nn\n,\n \ni\nd\nd\nj\na\nt\n \na\nu\nr\n \nh\na\nk\n \nm\nê\n.\n \nO\nh\ni\n \nd\nj\na\nn\nn\ne\n \nk\ne\n \nl\na\ng\ne\n \ns\na\nb\n \nk\ne\n \ns\na\nm\na\nd\nj\n-\nb\no\ne\nd\nj\n \na\nu\nr\n \nh\ni\ne\nr\nd\na\na\ni\n \nh\na\ni\n \na\nu\nr\n \nd\no\ne\ns\na\nr\ne\n \ns\ne\n \ns\na\nb\n \ns\no\ne\nm\nm\na\nt\n \ns\nè\n,\n "
  specimen_16: "S\na\nb\n \nd\nj\na\nn\nn\ne\n \na\na\nd\nj\ná\nd\ni\n \na\nu\nr\n \nb\na\nr\na\nb\na\nr\n \np\na\ni\nd\na\na\n \nb\nh\na\ni\nl\nè\nn\n,\n \ni\nd\nd\nj\na\nt\n \na\nu\nr\n \nh\na\nk\n \nm\nê\n.\n \nO\nh\ni\n \nd\nj\na\nn\nn\ne\n \nk\ne\n \nl\na\ng\ne\n \ns\na\nb\n \nk\ne\n \ns\na\nm\na\nd\nj\n-\nb\no\ne\nd\nj\n \na\nu\nr\n \nh\ni\ne\nr\nd\na\na\ni\n \nh\na\ni\n \na\nu\nr\n \nd\no\ne\ns\na\nr\ne\n \ns\ne\n \ns\na\nb\n \ns\no\ne\nm\nm\na\nt\n \ns\nè\n,\n \nd\nj\na\na\nn\ne\n-\nm\na\na\nn\ne\n \nk\ne\n \nc\nh\na\na\nh\ni\nn\n.\nS\na\nb\n \nd\nj\na\nn\nn\ne\n \na\na\nd\nj\ná\nd\ni\n \na\nu\nr\n \nb\na\nr\na\nb\na\nr\n \np\na\ni\nd\na\na\n \nb\nh\na\ni\nl\nè\nn\n,\n \ni\nd\nd\nj\na\nt\n \na\nu\nr\n \nh\na\nk\n \nm\nê\n.\n \nO\nh\ni\n \nd\nj\na\nn\nn\ne\n \nk\ne\n \nl\na\ng\ne\n \ns\na\nb\n \nk\ne\n \ns\na\nm\na\nd\nj\n-\nb\no\ne\nd"
}
