id: "hoc_Deva"
language: "hoc"
script: "Deva"
name: "Ho"
population: 1312829
region: "IN"
sample_text {
  masthead_full: "सबनम"
  masthead_partial: "कअ"
  styles: "सबिन मानमि कोअः हियातिङ अन्डोः एकतियर को रेयः मामले रे जोनोमेए"
  tester: "सबिन मानमि कोअः हियातिङ अन्डोः एकतियर को रेयः मामले रे जोनोमेए तेगे दनामुल अन्डोः बराबरि रेयः"
  poster_sm: "सबिन मानमि कोअः"
  poster_md: "सबिन मानमि"
  poster_lg: "सबिन"
  specimen_48: "सबिन मानमि कोअः हियातिङ अन्डोः एकतियर को रेयः मामले रे जोनोमेए तेगे दनामुल अन्डोः"
  specimen_36: "सबिन मानमि कोअः हियातिङ अन्डोः एकतियर को रेयः मामले रे जोनोमेए तेगे दनामुल अन्डोः बराबरि रेयः नमा कना। इनिकु बुद्दि अन्डोः जिबोन बितर रेयः एनेम नमा कना अन्डोः अकोअको रे हगेयाबोहया (भाईचारे) रेयः जिबोन उङुः तेको जानागर तेयः दोरकर।"
  specimen_32: "सबिन मानमि कोअः हियातिङ अन्डोः एकतियर को रेयः मामले रे जोनोमेए तेगे दनामुल अन्डोः बराबरि रेयः नमा कना। इनिकु बुद्दि अन्डोः जिबोन बितर रेयः एनेम नमा कना अन्डोः अकोअको रे हगेयाबोहया (भाईचारे) रेयः जिबोन उङुः तेको जानागर तेयः दोरकर।"
  specimen_21: "सबिन मानमि कोअः हियातिङ अन्डोः एकतियर को रेयः मामले रे जोनोमेए तेगे दनामुल अन्डोः बराबरि रेयः नमा कना। इनिकु बुद्दि अन्डोः जिबोन बितर रेयः एनेम नमा कना अन्डोः अकोअको रे हगेयाबोहया (भाईचारे) रेयः जिबोन उङुः तेको जानागर तेयः दोरकर।\nसबिन मानमि कोअः हियातिङ अन्डोः एकतियर को रेयः मामले रे जोनोमेए तेगे दनामुल अन्डोः बराबरि रेयः नमा कना। इनिकु बुद्दि अन्डोः जिबोन बितर रेयः एनेम नमा कना अन्डोः अकोअको रे हगेयाबोहया (भाईचारे) रेयः जिबोन उङुः तेको जानागर तेयः दोरकर।\nसबिन मानमि कोअः हियातिङ अन्डोः एकतियर को रेयः मामले रे जोनोमेए तेगे दनामुल अन्डोः बराबरि रेयः नमा कना। इनिकु बुद्दि अन्डोः जिबोन बितर रेयः एनेम नमा कना अन्डोः अकोअको रे हगेयाबोहया (भाईचारे) रेयः जिबोन उङुः तेको जानागर तेयः दोरकर।"
  specimen_16: "सबिन मानमि कोअः हियातिङ अन्डोः एकतियर को रेयः मामले रे जोनोमेए तेगे दनामुल अन्डोः बराबरि रेयः नमा कना। इनिकु बुद्दि अन्डोः जिबोन बितर रेयः एनेम नमा कना अन्डोः अकोअको रे हगेयाबोहया (भाईचारे) रेयः जिबोन उङुः तेको जानागर तेयः दोरकर।\nसबिन मानमि कोअः हियातिङ अन्डोः एकतियर को रेयः मामले रे जोनोमेए तेगे दनामुल अन्डोः बराबरि रेयः नमा कना। इनिकु बुद्दि अन्डोः जिबोन बितर रेयः एनेम नमा कना अन्डोः अकोअको रे हगेयाबोहया (भाईचारे) रेयः जिबोन उङुः तेको जानागर तेयः दोरकर।\nसबिन मानमि कोअः हियातिङ अन्डोः एकतियर को रेयः मामले रे जोनोमेए तेगे दनामुल अन्डोः बराबरि रेयः नमा कना। इनिकु बुद्दि अन्डोः जिबोन बितर रेयः एनेम नमा कना अन्डोः अकोअको रे हगेयाबोहया (भाईचारे) रेयः जिबोन उङुः तेको जानागर तेयः दोरकर।\nसबिन मानमि कोअः हियातिङ अन्डोः एकतियर को रेयः मामले रे जोनोमेए तेगे दनामुल अन्डोः बराबरि रेयः नमा कना। इनिकु बुद्दि अन्डोः जिबोन बितर रेयः एनेम नमा कना अन्डोः अकोअको रे हगेयाबोहया (भाईचारे) रेयः जिबोन उङुः तेको जानागर तेयः दोरकर।"
}
