id: "hr"
language: "hr"
script: "Latn"
name: "Croatian"
autonym: "Hrvatski"
population: 6767930
region: "AT"
region: "BA"
region: "DE"
region: "HR"
region: "HU"
region: "IT"
region: "RS"
region: "SI"
exemplar_chars {
  base: "a b c č ć d {dž} đ e f g h i j k l {lj} m n {nj} o p r s š t u v z ž {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj}"
  auxiliary: "q w x y"
  marks: "◌́ ◌̌"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "‐ – — , ; : ! ? . … \' ‘ ’ ‚ \" “ ” „ ( ) [ ] @ * / ′ ″"
  index: "A B C Č Ć D {DŽ} Đ E F G H I J K L {LJ} M N {NJ} O P Q R S Š T U V W X Y Z Ž {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ}"
}
sample_text {
  masthead_full: "SsVv"
  masthead_partial: "Aa"
  styles: "Budući da su priznavanje urođenog dostojanstva"
  tester: "Budući da su nepoštovanje i preziranje prava čovjeka imali za"
  poster_sm: "Budući da je"
  poster_md: "Budući da"
  poster_lg: "Sva"
  specimen_48: "Budući da su narodi Ujedinjenih naroda ponovno potvrdili u Povelji"
  specimen_36: "Budući da je zajedničko razumijevanje tih prava i sloboda od najveće važnosti za puno ostvarenje te obveze,"
  specimen_32: "Sva ljudska bića rađaju se slobodna i jednaka u dostojanstvu i pravima. Ona su obdarena razumom i sviješću i treba da jedno prema drugome postupaju u duhu bratstva."
  specimen_21: "Svakome su dostupna sva prava i slobode navedene u ovoj Deklaraciji bez razlike bilo koje vrste, kao što su rasa, boja, spol, jezik, vjera, političko ili drugo mišljenje, nacionalno ili društveno porijeklo, imovina, rođenje ili drugi pravni položaj.\nSvatko ima pravo na život, slobodu i osobnu sigurnost.\nNitko ne smije biti držan u ropstvu ili ropskom odnosu; ropstvo i trgovina robljem zabranjuju se u svim svojim oblicima."
  specimen_16: "Nitko ne smije biti podvrgnut mučenju ili okrutnom, nečovječnom ili ponižavajućem postupku ili kažnjavanju.\nSvatko ima pravo da se svagdje pred zakonom priznaje kao osoba.\nSvi su pred zakonom jednaki i imaju pravo, bez ikakve diskriminacije, na jednaku zaštitu zakona. Svi imaju pravo na jednaku zaštitu protiv bilo kakve diskrimininacije kojom se krši ova Deklaracija i protiv svakog poticanja na takvu diskriminaciju.\nSvatko ima pravo na djelotvorna pravna sredstva putem nadležnih nacionalnih sudova zbog djela kojima se krše osnovna prava koja mu pripadaju temeljem ustava i zakona."
}
