id: "hsb"
name: "Upper Sorbian"
preferred_name: ""
autonym: "Hornjoserbšćina"
population: 12825
region: "DE"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ó Ć Č Ě Ł Ń Ř Ś Š Ź Ž a b c d e f g h i j k l m n o p q r s t u v w x y z ó ć č ě ł ń ř ś š ź ž"
  auxiliary: "á à ă â å ä ã ą ā æ ç ď đ é è ĕ ê ë ė ę ē ğ í ì ĭ î ï İ ī ı ĺ ľ ň ñ ò ŏ ô ö ő ø ō œ ŕ ś ş ß ť ú ù ŭ û ů ü ű ū ý ÿ ż ź"
  marks: "◌́ ◌̌"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … \' ‘ ’ ‚ \" “ „ « » ( ) \\[ \\] \\{ \\} § @ * / \\& #"
  index: "A B C Č Ć D {DŹ} E F G H {CH} I J K Ł L M N O P Q R S Š T U V W X Y Z Ž"
}
sample_text {
  masthead_full: "WwŠš"
  masthead_partial: "Ii"
  tester: "Dokelž twori płipóznaće wšěm čłonam čłowjeskeje swójby płisłušaceje"
  poster_sm: "dokelž stej"
  poster_md: "dokelž je"
  poster_lg: "Wšitcy"
  specimen_48: "dokelž su ludy Zjednoćenych narodow we wustawkach znowa swoju"
  specimen_36: "dokelž je zhromadne měnjenje wo tutych prawach a swobodach płewšo wažne za połne spjelnjenje tutoho zawjazka,"
  specimen_32: "Wšitcy čłowjekojo su wot naroda swobodni a su jenacy po dostojnosći a prawach. Woni su z rozumom a swědomjom wobdarjeni a maja mjezsobu w duchu bratrowstwa wobchadźeć."
  specimen_21: "Kóždy je woprawnjeny, w tutym wozjewjenju proklamowane prawa a swobody wužiwać, a to bjez kóždehožkuli rozeznawanja, kaž po rasy, barbje, splahu, rěči, religiji, politiskim abo druhim płeswědčenju, narodnym abo socialnym pochadźe, po zamóženju, narodźe abo druhim statusu .\nKóždy ma prawo na žiwjenje, swobodu a wěstotu wosohy."
  specimen_16: "Nichtó njesmě so w njewólnistwje abo roboćanstwje dźeržeć; njewólnistwo a wikowanje z njewólnikami stej we wšěch swojich formach zakazanej.\nNichtó njesmě so podćisnyć ćwělowanju abo surowemu, nječłowjeskemu abo ponižowacemu wobchadźenju abo chłostanju.\nKóždy ma prawo, wšudźe jako prawakmany płipóznaty hyć.\nWšitcy čłowjekojo su płed zakonjom runi a maja b jez diskriminaeije prawo na jenaki škit płez zakoń. Wšitey maja pawo na jenaki škit płećiwo kóždej diskriminaciji, kotraž by płedležace wozjewjen je zraniła, a płećiwo pozbudźen ju k tajkej diskriminaciji."
}
