id: "hsn_Hans"
language: "hsn"
script: "Hans"
name: "Xiang Chinese"
population: 40426580
region: "CN"
sample_text {
  masthead_full: "人生而自"
  masthead_partial: "由在"
  styles: "人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋"
  tester: "人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n在\n得\n以"
  poster_sm: "人\n人\n生\n而\n自\n由"
  poster_md: "人\n人\n生\n而\n自"
  poster_lg: "人\n人"
  specimen_48: "人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n在\n得\n以"
  specimen_36: "人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n在\n得\n以\n兄\n弟\n关\n系\n的\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n自\n由\n，\n在\n尊\n严"
  specimen_32: "人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n在\n得\n以\n兄\n弟\n关\n系\n的\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n在\n得"
  specimen_21: "人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n在\n得\n以\n兄\n弟\n关\n系\n的\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n在\n得\n以\n兄\n弟\n关\n系\n的\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n在\n得\n以\n兄\n弟\n关\n系\n的\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，"
  specimen_16: "人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n在\n得\n以\n兄\n弟\n关\n系\n的\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n在\n得\n以\n兄\n弟\n关\n系\n的\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n在\n得\n以\n兄\n弟\n关\n系\n的\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n在\n得\n以\n兄\n弟\n关\n系\n的\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n在\n得\n以\n兄\n弟\n关\n系\n的\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n在\n得\n以\n兄\n弟\n关\n系\n的\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n在\n得"
}
