id: "huu_Latn"
language: "huu"
script: "Latn"
name: "Huitoto, Murui"
sample_text {
  masthead_full: "NnAa"
  masthead_partial: "Cc"
  styles: "N\na\nn\na\n \nc\na\nɨ\n \nc\no\nm\nu\ni\nl\nl\na\nm\no\nn\na"
  tester: "N\na\nn\na\n \nc\na\nɨ\n \nc\no\nm\nu\ni\nl\nl\na\nm\no\nn\na\n \nd\na\nm\na\n \nc\na\nɨ\n "
  poster_sm: "N\na\nn\na\n \nc"
  poster_md: "N\na\nn\na\n "
  poster_lg: "N\na"
  specimen_48: "N\na\nn\na\n \nc\na\nɨ\n \nc\no\nm\nu\ni\nl\nl\na\nm\no\nn\na\n \nd\na\nm\na\n \nc\na\nɨ\n "
  specimen_36: "N\na\nn\na\n \nc\na\nɨ\n \nc\no\nm\nu\ni\nl\nl\na\nm\no\nn\na\n \nd\na\nm\na\n \nc\na\nɨ\n \na\nb\ni\nd\no\n \ni\nt\nɨ\nc\na\nɨ\n.\n \nC\na\nɨ\n \nc\no"
  specimen_32: "N\na\nn\na\n \nc\na\nɨ\n \nc\no\nm\nu\ni\nl\nl\na\nm\no\nn\na\n \nd\na\nm\na\n \nc\na\nɨ\n \na\nb\ni\nd\no\n \ni\nt\nɨ\nc\na\nɨ\n.\n \nC\na\nɨ\n \nc\no\nm\nu\ni\nl\nl\na\nm\no\nn\na\n \nj\nɨ\na\nɨ\nm\nɨ\ne\n \na"
  specimen_21: "N\na\nn\na\n \nc\na\nɨ\n \nc\no\nm\nu\ni\nl\nl\na\nm\no\nn\na\n \nd\na\nm\na\n \nc\na\nɨ\n \na\nb\ni\nd\no\n \ni\nt\nɨ\nc\na\nɨ\n.\n \nC\na\nɨ\n \nc\no\nm\nu\ni\nl\nl\na\nm\no\nn\na\n \nj\nɨ\na\nɨ\nm\nɨ\ne\n \na\nn\na\nm\no\n \ni\nñ\ne\nd\nɨ\nc\na\nɨ\n.\n \nN\na\nn\na\n \nd\na\nj\ne\n \nf\na\nc\na\ni\nc\no\nn\ni\n \ni\nt\nɨ\nc\na\nɨ\n.\n \nA\nb\nɨ\n \nu\ni\nñ\nu\na\nn\no\nn\na\n \nc\no\nm\nu\ni\nd\nɨ\nc\na\nɨ\n.\n \nD\na\nn\nɨ\n \nc\no\nn\ni\nn\nɨ\nr\ni"
  specimen_16: "N\na\nn\na\n \nc\na\nɨ\n \nc\no\nm\nu\ni\nl\nl\na\nm\no\nn\na\n \nd\na\nm\na\n \nc\na\nɨ\n \na\nb\ni\nd\no\n \ni\nt\nɨ\nc\na\nɨ\n.\n \nC\na\nɨ\n \nc\no\nm\nu\ni\nl\nl\na\nm\no\nn\na\n \nj\nɨ\na\nɨ\nm\nɨ\ne\n \na\nn\na\nm\no\n \ni\nñ\ne\nd\nɨ\nc\na\nɨ\n.\n \nN\na\nn\na\n \nd\na\nj\ne\n \nf\na\nc\na\ni\nc\no\nn\ni\n \ni\nt\nɨ\nc\na\nɨ\n.\n \nA\nb\nɨ\n \nu\ni\nñ\nu\na\nn\no\nn\na\n \nc\no\nm\nu\ni\nd\nɨ\nc\na\nɨ\n.\n \nD\na\nn\nɨ\n \nc\no\nn\ni\nn\nɨ\nr\ni\ne\n \nc\na\nɨ\n \nn\na\nb\na\ni\nr\ni\nl\nl\na\n.\nN\na\nn\na\n \nc\na\nɨ\n \nc\no\nm\nu\ni\nl\nl\na\nm\no\nn\na\n \nd\na\nm\na\n \nc\na\nɨ\n \na\nb\ni\nd\no\n \ni\nt\nɨ\nc\na\nɨ\n.\n \nC\na\nɨ\n \nc\no\nm\nu\ni\nl\nl\na\nm\no\nn\na\n \nj\nɨ\na\nɨ\nm\nɨ\ne\n \na\nn\na\nm\no\n \ni\nñ\ne\nd\nɨ\nc\na\nɨ\n.\n \nN\na\nn\na\n \nd\na\nj\ne\n \nf\na\nc\na\ni\nc\no\nn\ni\n \ni\nt\nɨ"
}
