id: "hy"
language: "hy"
script: "Armn"
name: "Armenian"
preferred_name: "Eastern Armenian"
autonym: "Հայերեն"
population: 5317271
region: "AM"
region: "CY"
region: "GE"
region: "IR"
region: "LB"
region: "RU"
region: "SY"
region: "TR"
exemplar_chars {
  base: "ա բ գ դ ե զ է ը թ ժ ի լ խ ծ կ հ ձ ղ ճ մ յ ն շ ո չ պ ջ ռ ս վ տ ր ց ւ փ ք օ ֆ"
  auxiliary: "և"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "֊ , ՝ : ՜ ՞ . « » ՚ ՛ ՟"
  index: "Ա Բ Գ Դ Ե Զ Է Ը Թ Ժ Ի Լ Խ Ծ Կ Հ Ձ Ղ Ճ Մ Յ Ն Շ Ո Չ Պ Ջ Ռ Ս Վ Տ Ր Ց Ւ Փ Ք Օ Ֆ"
}
sample_text {
  masthead_full: "ԲբՈո"
  masthead_partial: "Լլ"
  styles: "Քանզի մարդկային ընտանիքի բոլոր անդամներին"
  tester: "Քանզի մարդու իրավունքների նկատմամբ քամահրանքն ու արհամարհանքը"
  poster_sm: "Քանզի անհրաժեշտ"
  poster_md: "Քանզի անդամ"
  poster_lg: "Բոլոր"
  specimen_48: "Քանզի այս իրավունքների ու ազատությունների համընդհանուր ըմբռնումը"
  specimen_36: "Ոչ ոք չպետք է լինի ստրկության կամ անազատ վիճակում․ պետք է արգելվեն ստրկատիրության ու ստրուկների առուծախի բոլոր ձևերը։"
  specimen_32: "Ամեն ոք ունի ազգային լիազոր դատարանների միջոցով իր իրավունքների արդյունավետ վերականգնման իրավունք, եթե խախտվում են սահմանադրությամբ կամ օրենքով սահմանված նրա հիմնական իրավունքները։"
  specimen_21: "Ոչ ոք չի կարող ենթարկվել կամայական կալանքի, բանտարկության կամ արտաքսման։\nԱմեն ոք իր իրավունքների ու պարտականությունների սահմանման համար և իր դեմ ցանկացած քրեական մեղադրանքի դեպքում, լիակատար հավասարության հիման վրա, իրավունք ունի, որ իր գործը արդարացի ու հրապարակայնորեն լսվի անկախ ու անկողմնապահ դատարանի կողմից։"
  specimen_16: "Ոչ ոք չի կարող ենթարկվել կամայական միջամտության իր անձնական ու ընտանեկան կյանքի նկատմամբ, իր տան, թղթակցության և կամ իր պատվի ու համբավի դեմ կամայական ոտնձգության։ Ամեն ոք ունի օրենքով պաշտպանվելու իրավունք ընդդեմ նման միջամտության կամ ոտնձգության։\nՅուրաքանչյուր ոք ունի մտքի, խղճի ու դավանանքի ազատության իրավունք․ այս իրավունքը ներառնում է իր դավանանքը կամ համոզմունքները փոխելու ազատություն և իր դավանանքին կամհամոզմունքներին հետևելու ազատություն, մենակ կամ ուրիշների հետ համատեղ, հրապարակայնորեն կամ գաղտնի՝ քարոզի, ժամերգության, կրոնական ու ծիսական արարողությունների ձևով։"
}
