id: "hyw_Armn"
language: "hyw"
script: "Armn"
name: "Western Armenian, Armenian"
sample_text {
  masthead_full: "ԲբՈո"
  masthead_partial: "Լլ"
  styles: "Բ\nո\nլ\nո\nր\n \nմ\nա\nր\nդ\nի\nկ\n \nկ\nը\n \nծ\nն\nո\nւ\nի"
  tester: "Բ\nո\nլ\nո\nր\n \nմ\nա\nր\nդ\nի\nկ\n \nկ\nը\n \nծ\nն\nո\nւ\nի\nն\n \nա\nզ\nա\nտ\n \nե\nւ\n "
  poster_sm: "Բ\nո\nլ\nո\nր\n "
  poster_md: "Բ\nո\nլ\nո\nր"
  poster_lg: "Բ\nո"
  specimen_48: "Բ\nո\nլ\nո\nր\n \nմ\nա\nր\nդ\nի\nկ\n \nկ\nը\n \nծ\nն\nո\nւ\nի\nն\n \nա\nզ\nա\nտ\n \nե\nւ\n "
  specimen_36: "Բ\nո\nլ\nո\nր\n \nմ\nա\nր\nդ\nի\nկ\n \nկ\nը\n \nծ\nն\nո\nւ\nի\nն\n \nա\nզ\nա\nտ\n \nե\nւ\n \nհ\nա\nւ\nա\nս\nա\nր\n \nի\nր\nե\nն\nց\n \nա\nր\nժ\nա\nն\nա"
  specimen_32: "Բ\nո\nլ\nո\nր\n \nմ\nա\nր\nդ\nի\nկ\n \nկ\nը\n \nծ\nն\nո\nւ\nի\nն\n \nա\nզ\nա\nտ\n \nե\nւ\n \nհ\nա\nւ\nա\nս\nա\nր\n \nի\nր\nե\nն\nց\n \nա\nր\nժ\nա\nն\nա\nպ\nա\nտ\nո\nւ\nո\nւ\nթ\nե\nա\nմ\nբ\n \nե\nւ\n \nի\nր\nա\nւ"
  specimen_21: "Բ\nո\nլ\nո\nր\n \nմ\nա\nր\nդ\nի\nկ\n \nկ\nը\n \nծ\nն\nո\nւ\nի\nն\n \nա\nզ\nա\nտ\n \nե\nւ\n \nհ\nա\nւ\nա\nս\nա\nր\n \nի\nր\nե\nն\nց\n \nա\nր\nժ\nա\nն\nա\nպ\nա\nտ\nո\nւ\nո\nւ\nթ\nե\nա\nմ\nբ\n \nե\nւ\n \nի\nր\nա\nւ\nո\nւ\nն\nք\nն\nե\nր\nո\nվ\n:\n \nԻ\nր\nե\nն\nք\n \nօ\nժ\nտ\nո\nւ\nա\nծ\n \nե\nն\n \nբ\nա\nն\nա\nկ\nա\nն\nո\nւ\nթ\nե\nա\nմ\nբ\n \nո\nւ\n \nխ\nի\nղ\nճ\nո\nվ\n,\n \nե\nւ\n \nպ\nա\nր\nտ\nա\nւ\nո\nր\nո\nւ\nա\nծ\n \nե\nն\n \nմ\nի\nմ\nե\nա\nն\nց\n "
  specimen_16: "Բ\nո\nլ\nո\nր\n \nմ\nա\nր\nդ\nի\nկ\n \nկ\nը\n \nծ\nն\nո\nւ\nի\nն\n \nա\nզ\nա\nտ\n \nե\nւ\n \nհ\nա\nւ\nա\nս\nա\nր\n \nի\nր\nե\nն\nց\n \nա\nր\nժ\nա\nն\nա\nպ\nա\nտ\nո\nւ\nո\nւ\nթ\nե\nա\nմ\nբ\n \nե\nւ\n \nի\nր\nա\nւ\nո\nւ\nն\nք\nն\nե\nր\nո\nվ\n:\n \nԻ\nր\nե\nն\nք\n \nօ\nժ\nտ\nո\nւ\nա\nծ\n \nե\nն\n \nբ\nա\nն\nա\nկ\nա\nն\nո\nւ\nթ\nե\nա\nմ\nբ\n \nո\nւ\n \nխ\nի\nղ\nճ\nո\nվ\n,\n \nե\nւ\n \nպ\nա\nր\nտ\nա\nւ\nո\nր\nո\nւ\nա\nծ\n \nե\nն\n \nմ\nի\nմ\nե\nա\nն\nց\n \nհ\nա\nն\nդ\nէ\nպ\n \nե\nղ\nբ\nա\nյ\nր\nո\nւ\nթ\nե\nա\nն\n \nո\nգ\nի\nո\nվ\n \nվ\nա\nր\nո\nւ\nի\nլ\n:\nԲ\nո\nլ\nո\nր\n \nմ\nա\nր\nդ\nի\nկ\n \nկ\nը\n \nծ\nն\nո\nւ\nի\nն\n \nա\nզ\nա\nտ\n \nե\nւ\n \nհ\nա\nւ\nա\nս\nա\nր\n \nի\nր\nե\nն\nց\n \nա\nր\nժ\nա\nն\nա\nպ\nա\nտ\nո\nւ\nո\nւ\nթ\nե\nա\nմ\nբ\n \nե\nւ\n \nի\nր\nա\nւ\nո\nւ\nն\nք\nն\nե\nր\nո\nվ\n:\n \nԻ\nր\nե\nն\nք\n \nօ\nժ\nտ\nո"
}
