id: "idu_Latn"
language: "idu"
script: "Latn"
name: "Idoma"
sample_text {
  masthead_full: "ĘęGg"
  masthead_partial: "Nn"
  styles: "Ę\ng\nę\n \nn\ni\n \nm\no\nd\nu\nd\nu\n \na\nc\nę\n \nk\nę\nc"
  tester: "Ę\ng\nę\n \nn\ni\n \nm\no\nd\nu\nd\nu\n \na\nc\nę\n \nk\nę\nc\nę\n \nn\ny\na\n \nb\nę\nc\nę"
  poster_sm: "Ę\ng\nę\n \nn\ni"
  poster_md: "Ę\ng\nę\n \nn"
  poster_lg: "Ę\ng"
  specimen_48: "Ę\ng\nę\n \nn\ni\n \nm\no\nd\nu\nd\nu\n \na\nc\nę\n \nk\nę\nc\nę\n \nn\ny\na\n \nb\nę\nc\nę"
  specimen_36: "Ę\ng\nę\n \nn\ni\n \nm\no\nd\nu\nd\nu\n \na\nc\nę\n \nk\nę\nc\nę\n \nn\ny\na\n \nb\nę\nc\nę\n \nę\nh\ne\nh\ni\n \na\na\n \n,\nh\ni\nb\ni\n \nę\ng\nͻ\n "
  specimen_32: "Ę\ng\nę\n \nn\ni\n \nm\no\nd\nu\nd\nu\n \na\nc\nę\n \nk\nę\nc\nę\n \nn\ny\na\n \nb\nę\nc\nę\n \nę\nh\ne\nh\ni\n \na\na\n \n,\nh\ni\nb\ni\n \nę\ng\nͻ\n \nm\na\n \na\nc\nę\n \nd\nu\nu\n \nj\no\nn\nj\ni\nl\nę\n \ni"
  specimen_21: "Ę\ng\nę\n \nn\ni\n \nm\no\nd\nu\nd\nu\n \na\nc\nę\n \nk\nę\nc\nę\n \nn\ny\na\n \nb\nę\nc\nę\n \nę\nh\ne\nh\ni\n \na\na\n \n,\nh\ni\nb\ni\n \nę\ng\nͻ\n \nm\na\n \na\nc\nę\n \nd\nu\nu\n \nj\no\nn\nj\ni\nl\nę\n \ni\np\nu\n \nk\no\nc\nę\ng\nb\na\n \nn\nͻ\nc\nę\n \nc\nę\ng\nb\na\n \nm\nę\nm\nl\n’\no\nj\no\nn\nj\ni\nl\nę\n \ni\np\nu\n \nͻ\nd\na\nh\n \nn\ni\n \ny\na\nb\nͻ\n \nͻ\nc\nę\n \nn\ny\na\n.\n \nO\nd\nu\nd\nu\n \na\nc\nę\n \nk\nw\nu\n \nђ\nw\nu\nl\ne"
  specimen_16: "Ę\ng\nę\n \nn\ni\n \nm\no\nd\nu\nd\nu\n \na\nc\nę\n \nk\nę\nc\nę\n \nn\ny\na\n \nb\nę\nc\nę\n \nę\nh\ne\nh\ni\n \na\na\n \n,\nh\ni\nb\ni\n \nę\ng\nͻ\n \nm\na\n \na\nc\nę\n \nd\nu\nu\n \nj\no\nn\nj\ni\nl\nę\n \ni\np\nu\n \nk\no\nc\nę\ng\nb\na\n \nn\nͻ\nc\nę\n \nc\nę\ng\nb\na\n \nm\nę\nm\nl\n’\no\nj\no\nn\nj\ni\nl\nę\n \ni\np\nu\n \nͻ\nd\na\nh\n \nn\ni\n \ny\na\nb\nͻ\n \nͻ\nc\nę\n \nn\ny\na\n.\n \nO\nd\nu\nd\nu\n \na\nc\nę\n \nk\nw\nu\n \nђ\nw\nu\nl\ne\n \nm\nl\n’\no\nh\ni\nl\ni\n \no\nt\nu\n \nm\nę\nm\nl\n’\no\nc\na\ni\n \nk\nę\nl\na\n \nj\nͻ\nc\nę\n \nͻ\nh\na\n \nn\ni\n \ny\ni\np\nu\n \nͻ\nt\nu\n \nͻ\nc\nę\n \na\na\n,\n \nh\ni\ng\nb\nͻ\n \nm\na\n \nͻ\nc\nę\n \nh\ni\ng\nb\no\n \ny\nͻ\nd\na\n \nm\nę\nm\nl\n’\n \nͻ\nm\np\na\n \ng\nu\nn\nu\n \nl\nę\n \nb\nͻ\ni\nn\nę\n \nn\nu\n \nm\na\n.\nĘ\ng\nę\n \nn\ni\n \nm\no\nd\nu\nd\nu\n \na"
}
