id: "ii"
language: "ii"
script: "Yiii"
name: "Sichuan Yi"
preferred_name: "Nuosu"
population: 8364120
region: "CN"
exemplar_chars {
  base: "ꀀ-ꒌ"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "ꀀ ꀋ ꀗ ꀣ ꀯ ꀺ ꁆ ꁒ ꁞ ꁩ ꁵ ꂁ ꂍ ꂘ ꂤ ꂰ ꂼ ꃇ ꃓ ꃟ ꃫ ꃶ ꄂ ꄎ ꄚ ꄥ ꄱ ꄽ ꅉ ꅔ ꅠ ꅬ ꅸ ꆃ ꆏ ꆛ ꆧ ꆳ ꆾ ꇊ ꇖ ꇢ ꇭ ꇹ ꈅ ꈑ ꈜ ꈨ ꈴ ꉀ ꉋ ꉗ ꉣ ꉯ ꉺ ꊆ ꊒ ꊞ ꊩ ꊵ ꋁ ꋍ ꋘ ꋤ ꋰ ꋼ ꌇ ꌓ ꌟ ꌫ ꌷ ꍂ ꍎ ꍚ ꍦ ꍱ ꍽ ꎉ ꎕ ꎠ ꎬ ꎸ ꏄ ꏏ ꏛ ꏧ ꏳ ꏾ ꐊ ꐖ ꐢ ꐭ ꐹ ꑅ ꑑ ꑜ ꑨ ꑴ ꒀ ꒋ"
}
sample_text {
  masthead_full: "ꊿꂷꃅꄿ"
  masthead_partial: "ꐨꐥ"
  styles: "ꊽꋩꅍꏭꉜꀋꒉꌠꌋꆀꉜꄸꑠꆹꅢꎆꌊꆀꍀꆿꃅꇏꅊꀐ，ꃅꇏꋋꈨꆹꃰꊿꂄꉌꇬꍍꄀꌠꉬ，ꊿꂷꈀꐥꃅꐥꋭꅇꉉꈋꍣꌋꆀꑇꌠꄿꐨꐥ"
  tester: "ꉻꏑꇩꏤꏓꂱꐥꇯꌠꏦꃤꁢꊧꇬꊿꊇꌅꅍꊿꑌꇐꁌꐨꌋꆀꅪꃰꐥꒈꃅꐥꌠꌅꅍꑠꉈꑴꌌꉉꄜꋊ，ꄷꀋꁨꀋꎪꃅꄿꐨꊼꇅꀉꒉꃅꐥꌠꐧꋦꀒꁨꆹꌠꌋꆀꐥꐨꄺꅐꌠꀻꎆꆹꎻ"
  poster_sm: "ꊿꂷꃅꄿꐨꐥ，ꌅꅍꀂꏽꐯꒈꃅꐥꌐ"
  poster_md: "ꏦꃤꂴꆽꐯꒈꃅꐥ"
  poster_lg: "ꊿꂷꃅꄿꐨꐥ"
  specimen_48: "ꊿꑞꂷꉬꅉꂿ，ꋍꐥꐨ、ꑱꈐ、ꀀꅉꌋꆀꅇꈴꋍꑠꈀꏾꃅꇬꏢꇋꀋꉆ，ꋍꂒꅉꌋꆀꂒꉻꑠꏯꑌꁒꐀꀋꉆ，ꊿꂷꇬꐥꆏꏦꃤꇬꀧꌋꃅꌠꌅꐨꐥ，ꇬꏢꇋꇬꁒꐀꀋꉆ"
  specimen_36: "ꊿꂷꈀꐥꌠꋌꐧꋦꇬꊿꂷꉬꆏ，ꐧꋦꀧꏢꃅꐥꋭꌠꌅꅍꐥ，ꄷꀋꁨꋌꋍꊨꏦꐥꐨꐤꏦꌋꆀꋍꄿꐨ ꅢꎆꌠꇬꀋꈁꀋꉆꌠꎆꏣ，ꐧꋦꌋꆀꌧꇐꃆꂮꋍꑠꋍꑵꇬꋯꐨꑠꃅꇬꅜꌠꌅꅍꐥ，ꋌꆹꇩꏤꊋꇤꌠꌋꆀꇩꏤꏓꐯꇯꄉꇩꏤꋋꈨꎀꍹꌋꆀꅐꇐꃆꂮꇬꈴꄉꃅꇬꅜꌠ。"
  specimen_32: "ꌅꅍꌋꆀꄿꐨꋋꈨꊿꃅꇫꅉꐚꌠꆹ，ꃅꐮꏤꒃꋋꏢꇬꃅꇬꑟꌠꆹꀋꉬꀋꉆꌠꉬ，ꑠꅹꃆꃀꀉꒉꋋꂷ，ꋧꃅꊽꌅꅍꋋꏢꌌꄜꋊ，ꉹꁌꏓꂱꈀꐥꌠꌋꆀꇩꏤꈀꐥꃅꊋꇤꄉꃅꇫꑟꂿꄷꌠꇬꎕꏦꏢꉬ，ꊾꂷꇫꐥꌠꌋꆀꐧꋦꏲꉻꈀꐥꌠꃅꅉꅉꃅꇬꎺꄉꌶ，ꊋꇤꃅꉙꂘꌠꇬꈴꄉꌅꅍꌋꆀꄿꐨꁌꒉꌠꊥꎆ，ꉈꑴꇩꏤꌋꆀꇩꏤꇢꊭꇬꈴꏁꁈꄉ，ꌅꅍꌋꆀꋋꈨꁳꉻꏑꇩꏤꈧ ꌠꉹꁌꏓꂱꊨꏦꏲꄸ，ꊿꃅꇬꏚꍆꇬꈴꄉꃅꏢꅊꎻ。"
  specimen_21: "ꃰꊿꑱꈐꊿꂷꃅꐥꋭꐯꒈꃅꐥꌠꌋꆀꌅꅍꏚꍆꌠꆹ，ꋧꃅꄿꐨ，ꑗꉬꌋꆀꄮꐽꃅꐥꌠꅉꃀꉬ。\nꊽꋩꅍꏭꉜꀋꒉꌠꌋꆀꉜꄸꑠꆹꅢꎆꌊꆀꍀꆿꃅꇏꅊꀐ，ꃅꇏꋋꈨꆹꃰꊿꂄꉌꇬꍍꄀꌠꉬ，ꊿꂷꈀꐥꃅꐥꋭꅇꉉꈋꍣꌋꆀꑇꌠꄿꐨꐥ，ꄷꀋꁨꐬꀋꆠꃅꐥꌠꌋꆀꇮꃪꃅꑟꇁꌠꋧꃅꂶꌠꆹ，ꈍꄮꅉꆐꉹꁌꏓꂱꀊꂤꉌꉪꅉꉬꄷꄜꇬꄀꄉꀐ。\nꃰꊿꇬꐥꀋꄐꄉꊾꍅꊿꅷꌠꐤꁏꑠꆹ，ꏦꃤꇬꄉꀧꋭꌠꌅꅍꉬ。\nꇩꏤꈀꐥꌠꇢꊭꇬꐮꄮꃅꐥꃆꂮꀻꎆꌠꊥꎆꄻꅐ。\nꉻꏑꇩꏤꏓꂱꐥꇯꌠꏦꃤꁢꊧꇬꊿꊇꌅꅍꊿꑌꇐꁌꐨꌋꆀꅪꃰꐥꒈꃅꐥꌠꌅꅍꑠꉈꑴꌌꉉꄜꋊ，ꄷꀋꁨꀋꎪꃅꄿꐨꊼꇅꀉꒉꃅꐥꌠꐧꋦꀒꁨꆹꌠꌋꆀꐥꐨꄺꅐꌠꀻꎆꆹꎻ。\nꄚꐊꌠꇩꏤꆹꀋꎪꃅꉻꏑꇩꏤꌋꆀꐯꇯꊽꌅꅍꌋꅿꄿꐨꇬꁌꒉꄷꀋꁨꇫꍬꌬꇫꊥꎆꏤꄉꀐ。"
  specimen_16: "ꃰꊿꑱꈐꊿꂷꃅꐥꋭꐯꒈꃅꐥꌠꌋꆀꌅꅍꏚꍆꌠꆹ，ꋧꃅꄿꐨ，ꑗꉬꌋꆀꄮꐽꃅꐥꌠꅉꃀꉬ。\nꊽꋩꅍꏭꉜꀋꒉꌠꌋꆀꉜꄸꑠꆹꅢꎆꌊꆀꍀꆿꃅꇏꅊꀐ，ꃅꇏꋋꈨꆹꃰꊿꂄꉌꇬꍍꄀꌠꉬ，ꊿꂷꈀꐥꃅꐥꋭꅇꉉꈋꍣꌋꆀꑇꌠꄿꐨꐥ，ꄷꀋꁨꐬꀋꆠꃅꐥꌠꌋꆀꇮꃪꃅꑟꇁꌠꋧꃅꂶꌠꆹ，ꈍꄮꅉꆐꉹꁌꏓꂱꀊꂤꉌꉪꅉꉬꄷꄜꇬꄀꄉꀐ。\nꃰꊿꇬꐥꀋꄐꄉꊾꍅꊿꅷꌠꐤꁏꑠꆹ，ꏦꃤꇬꄉꀧꋭꌠꌅꅍꉬ。\nꇩꏤꈀꐥꌠꇢꊭꇬꐮꄮꃅꐥꃆꂮꀻꎆꌠꊥꎆꄻꅐ。\nꉻꏑꇩꏤꏓꂱꐥꇯꌠꏦꃤꁢꊧꇬꊿꊇꌅꅍꊿꑌꇐꁌꐨꌋꆀꅪꃰꐥꒈꃅꐥꌠꌅꅍꑠꉈꑴꌌꉉꄜꋊ，ꄷꀋꁨꀋꎪꃅꄿꐨꊼꇅꀉꒉꃅꐥꌠꐧꋦꀒꁨꆹꌠꌋꆀꐥꐨꄺꅐꌠꀻꎆꆹꎻ。\nꄚꐊꌠꇩꏤꆹꀋꎪꃅꉻꏑꇩꏤꌋꆀꐯꇯꊽꌅꅍꌋꅿꄿꐨꇬꁌꒉꄷꀋꁨꇫꍬꌬꇫꊥꎆꏤꄉꀐ。\nꌅꅍꌋꆀꄿꐨꋋꈨꊿꃅꇫꅉꐚꌠꆹ，ꃅꐮꏤꒃꋋꏢꇬꃅꇬꑟꌠꆹꀋꉬꀋꉆꌠꉬ，ꑠꅹꃆꃀꀉꒉꋋꂷ，ꋧꃅꊽꌅꅍꋋꏢꌌꄜꋊ，ꉹꁌꏓꂱꈀꐥꌠꌋꆀꇩꏤꈀꐥꃅꊋꇤꄉꃅꇫꑟꂿꄷꌠꇬꎕꏦꏢꉬ，ꊾꂷꇫꐥꌠꌋꆀꐧꋦꏲꉻꈀꐥꌠꃅꅉꅉꃅꇬꎺꄉꌶ，ꊋꇤꃅꉙꂘꌠꇬꈴꄉꌅꅍꌋꆀꄿꐨꁌꒉꌠꊥꎆ，ꉈꑴꇩꏤꌋꆀꇩꏤꇢꊭꇬꈴꏁꁈꄉ，ꌅꅍꌋꆀꋋꈨꁳꉻꏑꇩꏤꈧ ꌠꉹꁌꏓꂱꊨꏦꏲꄸ，ꊿꃅꇬꏚꍆꇬꈴꄉꃅꏢꅊꎻ。\nꊿꂷꃅꄿꐨꐥ，ꌅꅍꀂꏽꐯꒈꃅꐥꌐ。ꊿꊇꉪꍆꌋꆀꁨꉌꑌꐥ，ꄷꀋꁨꂛꊨꅫꃀꃅꐥꄡꑟ。\nꊾꂷꈀꐥꌠꃅꄜꋊꄯꒉꇬꅑꌠꌅꅍꌋꆀꄿꐨꆹ，ꊿꋅ、ꊾꐎꊾꆈ、ꌋꅪꌺꃰ、ꅇꂷ、ꑞꑇꌠ、ꍔꍞꌋꆀꀉꁁꑞꉜꐨ、ꑞꇩꏤ、ꐧꋦꊾꏥ、ꁨꇐ、ꒆꊿꀋꉬꀐꇬꀉꁁꊿꑞꉬꅉꂿꇬꐥꋭꌠꉬ。"
}
