id: "io_Latn"
language: "io"
script: "Latn"
name: "Ido"
sample_text {
  masthead_full: "OoMm"
  masthead_partial: "Nn"
  styles: "O\nm\nn\na\n \nh\no\nm\ni\n \nn\na\ns\nk\na\ns\n \nl\ni\nb\ne"
  tester: "O\nm\nn\na\n \nh\no\nm\ni\n \nn\na\ns\nk\na\ns\n \nl\ni\nb\ne\nr\na\n \ne\nd\n \ne\ng\na\nl"
  poster_sm: "O\nm\nn\na\n \nh"
  poster_md: "O\nm\nn\na\n "
  poster_lg: "O\nm"
  specimen_48: "O\nm\nn\na\n \nh\no\nm\ni\n \nn\na\ns\nk\na\ns\n \nl\ni\nb\ne\nr\na\n \ne\nd\n \ne\ng\na\nl"
  specimen_36: "O\nm\nn\na\n \nh\no\nm\ni\n \nn\na\ns\nk\na\ns\n \nl\ni\nb\ne\nr\na\n \ne\nd\n \ne\ng\na\nl\na\n \nr\ne\nl\na\nt\ne\n \nd\ni\ng\nn\ne\ns\no\n \ne\n \ny"
  specimen_32: "O\nm\nn\na\n \nh\no\nm\ni\n \nn\na\ns\nk\na\ns\n \nl\ni\nb\ne\nr\na\n \ne\nd\n \ne\ng\na\nl\na\n \nr\ne\nl\na\nt\ne\n \nd\ni\ng\nn\ne\ns\no\n \ne\n \ny\nu\nr\ni\n.\n \nL\ni\n \ne\ns\n \nd\no\nt\ni\nt\na\n \np\ne"
  specimen_21: "O\nm\nn\na\n \nh\no\nm\ni\n \nn\na\ns\nk\na\ns\n \nl\ni\nb\ne\nr\na\n \ne\nd\n \ne\ng\na\nl\na\n \nr\ne\nl\na\nt\ne\n \nd\ni\ng\nn\ne\ns\no\n \ne\n \ny\nu\nr\ni\n.\n \nL\ni\n \ne\ns\n \nd\no\nt\ni\nt\na\n \np\ne\nr\n \nr\na\nc\ni\no\nn\no\n \ne\n \nk\no\nn\nc\ni\ne\nn\nc\no\n \ne\n \nd\ne\nv\na\ns\n \na\ng\na\nr\n \nv\ne\nr\ns\n \nl\n\'\nu\nn\na\n \nl\n\'\na\nl\nt\nr\na\n \ne\nn\n \ns\np\ni\nr\ni\nt\no\n \nd\ni\n \nf\nr\na\nt\ne\ns\no\n.\nO\nm\nn\na\n \nh"
  specimen_16: "O\nm\nn\na\n \nh\no\nm\ni\n \nn\na\ns\nk\na\ns\n \nl\ni\nb\ne\nr\na\n \ne\nd\n \ne\ng\na\nl\na\n \nr\ne\nl\na\nt\ne\n \nd\ni\ng\nn\ne\ns\no\n \ne\n \ny\nu\nr\ni\n.\n \nL\ni\n \ne\ns\n \nd\no\nt\ni\nt\na\n \np\ne\nr\n \nr\na\nc\ni\no\nn\no\n \ne\n \nk\no\nn\nc\ni\ne\nn\nc\no\n \ne\n \nd\ne\nv\na\ns\n \na\ng\na\nr\n \nv\ne\nr\ns\n \nl\n\'\nu\nn\na\n \nl\n\'\na\nl\nt\nr\na\n \ne\nn\n \ns\np\ni\nr\ni\nt\no\n \nd\ni\n \nf\nr\na\nt\ne\ns\no\n.\nO\nm\nn\na\n \nh\no\nm\ni\n \nn\na\ns\nk\na\ns\n \nl\ni\nb\ne\nr\na\n \ne\nd\n \ne\ng\na\nl\na\n \nr\ne\nl\na\nt\ne\n \nd\ni\ng\nn\ne\ns\no\n \ne\n \ny\nu\nr\ni\n.\n \nL\ni\n \ne\ns\n \nd\no\nt\ni\nt\na\n \np\ne\nr\n \nr\na\nc\ni\no\nn\no\n \ne\n \nk\no\nn\nc\ni\ne\nn\nc\no\n \ne\n \nd\ne\nv\na\ns\n \na\ng\na\nr\n \nv\ne\nr\ns\n \nl\n\'\nu\nn\na\n \nl\n\'\na\nl\nt\nr\na\n \ne\nn\n \ns\np\ni\nr"
}
