id: "it"
language: "it"
script: "Latn"
name: "Italian"
autonym: "Italiano"
population: 70743415
region: "AT"
region: "AU"
region: "BR"
region: "CA"
region: "CH"
region: "DE"
region: "FR"
region: "GB"
region: "HR"
region: "IT"
region: "MT"
region: "SI"
region: "SM"
region: "US"
region: "VA"
exemplar_chars {
  base: "a à b c d e é è f g h i ì j k l m n o ó ò p q r s t u ù v w x y z"
  auxiliary: "ª á â å ä ã æ ç ê ë í î ï ñ º ô ö õ ø œ ß ú û ü ÿ"
  marks: "◌̀ ◌́ ◌̂ ◌̈"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‑ — , ; : ! ? . … \' ’ \" “ ” « » ( ) [ ] { } @ / { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
}
sample_text {
  masthead_full: "TtUu"
  masthead_partial: "Ii"
  styles: "Considerato che il riconoscimento della dignità"
  tester: "Considerato che il disconoscimento e il disprezzo dei diritti"
  poster_sm: "Considerato"
  poster_md: "L\'ASSEMBLEA"
  poster_lg: "Tutti"
  specimen_48: "la presente dichiarazione universale dei diritti umani come ideale"
  specimen_36: "Nessun individuo potrà essere sottoposto a tortura o a trattamento o a punizione crudeli, inumani o degradanti."
  specimen_32: "Ogni individuo ha diritto al riposo ed allo svago, comprendendo in ciò una ragionevole limitazione delle ore di lavoro e ferie periodiche retribuite."
  specimen_21: "Ogni individuo ha diritto ad un ordine sociale e internazionale nel quale i diritti e le libertà enunciati in questa Dichiarazione possano essere pienamente realizzati.\nNulla nella presente Dichiarazione può essere interpretato nel senso di implicare un diritto di un qualsiasi Stato, gruppo o persona di esercitare un\'attività o di compiere un atto mirante alla distruzione di alcuno dei diritti e delle libertà in essa enunciati."
  specimen_16: "Considerato che il riconoscimento della dignità inerente a tutti i membri della famiglia umana e dei loro diritti, uguali ed inalienabili, costituisce il fondamento della libertà, della giustizia e della pace nel mondo;\nConsiderato che il disconoscimento e il disprezzo dei diritti umani hanno portato ad atti di barbarie che offendono la coscienza dell\'umanità, e che l\'avvento di un mondo in cui gli esseri umani godano della libertà di parola e di credo e della libertà dal timore e dal bisogno è stato proclamato come la più alta aspirazione dell\'uomo;\nConsiderato che è indispensabile promuovere lo sviluppo di rapporti amichevoli tra le Nazioni;"
}
