id: "iu"
name: "Inuktitut"
preferred_name: ""
autonym: "ᐃᓄᒃᑎᑐᑦ"
population: 15831
region: "CA"
script: "Latin"
script: "UCAS"
exemplar_chars {
  base: "ᐃ ᐄ ᐅ ᐆ ᐊ ᐋ ᐦ ᐱ ᐲ ᐳ ᐴ ᐸ ᐹ ᑉ ᑎ ᑏ ᑐ ᑑ ᑕ ᑖ ᑦ ᑭ ᑮ ᑯ ᑰ ᑲ ᑳ ᒃ ᒋ ᒌ ᒍ ᒎ ᒐ ᒑ ᒡ ᒥ ᒦ ᒧ ᒨ ᒪ ᒫ ᒻ ᓂ ᓃ ᓄ ᓅ ᓇ ᓈ ᓐ ᓯ ᓰ ᓱ ᓲ ᓴ ᓵ ᔅ ᓕ ᓖ ᓗ ᓘ ᓚ ᓛ ᓪ ᔨ ᔩ ᔪ ᔫ ᔭ ᔮ ᔾ ᕕ ᕖ ᕗ ᕘ ᕙ ᕚ ᕝ ᕆ ᕇ ᕈ ᕉ ᕋ ᕌ ᕐ ᕿ ᖀ ᖁ ᖂ ᖃ ᖄ ᖅ ᖏ ᖐ ᖑ ᖒ ᖓ ᖔ ᖕ ᖠ ᖡ ᖢ ᖣ ᖤ ᖥ ᖦ"
}
sample_text {
  masthead_full: "ᐃᓅᔪᓕ"
  masthead_partial: "ᒫᑦ"
  tester: "ᐃᒪᐃᒻᒪᑦ ᐃᓕᑕᖅᓯᒪᐅᑎᖃᑦᒪᑦ ᓯᕗᓕᕐᓂᓴᑐᖃᕐᓂᒃ ᓂᕐᓱᐃᓂᑦᒥᒃ ᐊᒻᒪᓗ ᐊᔾᔨᒌᒃᑎᑦᑎᓂᕐᒥᒃ ᐊᒻᒪᓗ"
  poster_sm: "ᐃᒪᐃᒻᒪᑦ ᓱᖁᑎᒋᓇᒍ"
  poster_md: "ᐃᒪᐃᒻᒪᑦ ᓲᖃᐃᒻᒪ,"
  poster_lg: "ᐃᓅᔪᓕᒫᑦ"
  specimen_48: "ᐃᒪᐃᒻᒪᑦ ᑭᓇᒃᑯᑐᐃᓐᓇᐃᑦ ᓯᓚᕐᔪᐊᕐᒥᐅᓂᒃ ᓴᐳᔾᔨᔨᑦ ᔫᓇᐃᑕᓐ ᓇᐃᓴᖕᒍᓂᕋᕐᑕᐅᔪᑦ ᐱᖁᔭᓕᐅᕐᓯᒪᕗᑦ"
  specimen_36: "ᐃᒪᐃᒻᒪᑦ ᐃᓕᑕᖅᓯᒪᐅᑎᖃᑦᒪᑦ ᓯᕗᓕᕐᓂᓴᑐᖃᕐᓂᒃ ᓂᕐᓱᐃᓂᑦᒥᒃ ᐊᒻᒪᓗ ᐊᔾᔨᒌᒃᑎᑦᑎᓂᕐᒥᒃ ᐊᒻᒪᓗ ᐊᔪᙱᔾᔪᑕᐅᔪᓐᓇᖅᑐᓄᑦ ᐱᔪᓐᓇᐅᑎᓂᒃ ᑕᒪᐃᓐᓄᓕᒫᑦᑎᐊᖅ ᐃᓚᒋᔭᐅᔪᓄᑦ"
  specimen_32: "ᐃᒪᐃᒻᒪᑦ ᓲᖃᐃᒻᒪ, ᑭᓇᒃᑯᑐᐃᓐᓇᓕᒫᑦ ᐃᒃᓯᓐᓇᑯᑕᖃᖅᓯᒪᒃᐸᑦ ᐃᑲᔪᖅᑐᐃᐱᖃᖅᑎᑕᐅᓇᓂ, ᐱᕕᑐᐊᑦᑎᐊᕆᓕᕐᓗᒍ, ᐊᑭᒪᓇᓱᐊᕐᓗᓂ ᐊᑭᕋᕐᑐᕐᓂᕐᒥᒍᑦ ᐊᒻᒪᓗ ᐅᖁᒪᐃᓪᓕᐅᖅᓂᖁᑦ, ᑕᒪᓐᓇ ᐃᓅᔪᓄᑦ ᐱᔪᓐᓇᐅᖅᑎᖕᒋᑦ ᓴᐳᒻᒥᔭᒃᑕᐅᔪᒃᓴᐅᕗᑦ ᒪᓕᒐᖕᒐᒍᑦ ᐱᖁᔭᓕᐊᖕᒍᓯᒪᔪᖁᑦ,"
  specimen_21: "ᐃᒪᐃᒻᒪᑦ ᐃᓕᑕᖅᓯᒪᐅᑎᖃᑦᒪᑦ ᓯᕗᓕᕐᓂᓴᑐᖃᕐᓂᒃ ᓂᕐᓱᐃᓂᑦᒥᒃ ᐊᒻᒪᓗ ᐊᔾᔨᒌᒃᑎᑦᑎᓂᕐᒥᒃ ᐊᒻᒪᓗ ᐊᔪᙱᔾᔪᑕᐅᔪᓐᓇᖅᑐᓄᑦ ᐱᔪᓐᓇᐅᑎᓂᒃ ᑕᒪᐃᓐᓄᓕᒫᑦᑎᐊᖅ ᐃᓚᒋᔭᐅᔪᓄᑦ ᑕᒪᒃᑯᐊ ᐃᓈᔪᑦ ᐃᓚᒌᒍᓯᖕᒋᑎᒍᑦ ᑐᙵᕕᐅᓪᓚᕆᖕᒪᑦ ᐃᓱᒪᖅᓱᕐᓂᖅ, ᖃᓄᖕᒐᓴᖅᑕᐅᖕᒋᓐᓂᖅ ᐊᒻᒪᓗ ᓴᐃᓕᒪᓂᖃᕐᓂᖅ ᓯᓚᕐᔪᐊᕐᒥ,\nᐃᒪᐃᒻᒪᑦ ᓲᖃᐃᒻᒪ, ᑭᓇᒃᑯᑐᐃᓐᓇᓕᒫᑦ ᐃᒃᓯᓐᓇᑯᑕᖃᖅᓯᒪᒃᐸᑦ ᐃᑲᔪᖅᑐᐃᐱᖃᖅᑎᑕᐅᓇᓂ, ᐱᕕᑐᐊᑦᑎᐊᕆᓕᕐᓗᒍ, ᐊᑭᒪᓇᓱᐊᕐᓗᓂ ᐊᑭᕋᕐᑐᕐᓂᕐᒥᒍᑦ ᐊᒻᒪᓗ ᐅᖁᒪᐃᓪᓕᐅᖅᓂᖁᑦ, ᑕᒪᓐᓇ ᐃᓅᔪᓄᑦ ᐱᔪᓐᓇᐅᖅᑎᖕᒋᑦ ᓴᐳᒻᒥᔭᒃᑕᐅᔪᒃᓴᐅᕗᑦ ᒪᓕᒐᖕᒐᒍᑦ ᐱᖁᔭᓕᐊᖕᒍᓯᒪᔪᖁᑦ,"
  specimen_16: "ᐃᒪᐃᒻᒪᑦ ᐃᓕᑕᖅᓯᒪᐅᑎᖃᑦᒪᑦ ᓯᕗᓕᕐᓂᓴᑐᖃᕐᓂᒃ ᓂᕐᓱᐃᓂᑦᒥᒃ ᐊᒻᒪᓗ ᐊᔾᔨᒌᒃᑎᑦᑎᓂᕐᒥᒃ ᐊᒻᒪᓗ ᐊᔪᙱᔾᔪᑕᐅᔪᓐᓇᖅᑐᓄᑦ ᐱᔪᓐᓇᐅᑎᓂᒃ ᑕᒪᐃᓐᓄᓕᒫᑦᑎᐊᖅ ᐃᓚᒋᔭᐅᔪᓄᑦ ᑕᒪᒃᑯᐊ ᐃᓈᔪᑦ ᐃᓚᒌᒍᓯᖕᒋᑎᒍᑦ ᑐᙵᕕᐅᓪᓚᕆᖕᒪᑦ ᐃᓱᒪᖅᓱᕐᓂᖅ, ᖃᓄᖕᒐᓴᖅᑕᐅᖕᒋᓐᓂᖅ ᐊᒻᒪᓗ ᓴᐃᓕᒪᓂᖃᕐᓂᖅ ᓯᓚᕐᔪᐊᕐᒥ,\nᐃᒪᐃᒻᒪᑦ ᓱᖁᑎᒋᓇᒍ ᐊᒻᒪᓗ ᓈᓚᖕᓂᕐᓗᖕᓂᖅ ᐃᓅᔪᒧᑦ ᐃᔪᓐᓇᐅᑎᓄᑦ ᖃᐅᔨᓇᖅᓯᐅᑎᓯᒪᔪᖅ ᓇᕐᕈᓇᕐᓂᕐᐹᑎᑐᑦ ᐊᐅᓪᓚᓯᖃᑦᓂᖕᒋᑦ ᓂᙵᒃᓵᕆᔾᔪᑎᖃᕐᐸᒃᑐᑦ ᐃᓄᓪᓚᕆᐅᔫᒐᓗᐊᓂᒃ, ᐊᒻᒪᓗ ᓯᕗᓕᐅᕆᓪᓚᑎᒃ ᓯᓚᕐᔪᐊᕐᒥᒃ ᑕᒪᒃᑯᐊ ᐊᓂᖅᑎᕆᔪᑦ ᐃᓅᔪᑦ ᖁᕕᐊᓲᑎᖃᕐᓯᒪᑎᓪᓗᒋᑦ ᐃᓱᒪᖅᓱᕐᖢᑎᒃ ᐅᖃᐅᓯᕐᒥᒃᑎᒍᑦ ᐊᒻᒪᓗ ᐅᖃᐅᓯᕐᒥᒃᑎᒍᑦ ᐊᒻᒪᓗ ᐃᓱᒪᖅᓱᕈᓐᓇᕐᓂᒃᑯᑦ ᑲᑦᐱᐊᓱᐊᓂᕐᒧᑦ ᐊᒻᒪᓗ ᓇᒧᑐᐃᓐᓇᖅ ᑐᓴᖅᑎᑦᑎᐅᑎᒋᓪᓗᒍ ᐱᔪᒪᓯᒪᖕᒪᑕ ᓲᕐᓗᓕ ᖁᑦᑎᖕᓂᖅᐸᐅᓪᓗᑎᒃ ᐊᔾᔪᒥᒋᔭᒥᒃᑎᒍᑦ ᐃᓄᑐᐃᓐᓇᐅᒐᓗᐊᕆᓪᓗᑎᒃ ᑭᓇᒃᑯᑐᐃᓐᓇᕐᑎᑐᑦ,\nᐃᒪᐃᒻᒪᑦ ᓲᖃᐃᒻᒪ, ᑭᓇᒃᑯᑐᐃᓐᓇᓕᒫᑦ ᐃᒃᓯᓐᓇᑯᑕᖃᖅᓯᒪᒃᐸᑦ ᐃᑲᔪᖅᑐᐃᐱᖃᖅᑎᑕᐅᓇᓂ, ᐱᕕᑐᐊᑦᑎᐊᕆᓕᕐᓗᒍ, ᐊᑭᒪᓇᓱᐊᕐᓗᓂ ᐊᑭᕋᕐᑐᕐᓂᕐᒥᒍᑦ ᐊᒻᒪᓗ ᐅᖁᒪᐃᓪᓕᐅᖅᓂᖁᑦ, ᑕᒪᓐᓇ ᐃᓅᔪᓄᑦ ᐱᔪᓐᓇᐅᖅᑎᖕᒋᑦ ᓴᐳᒻᒥᔭᒃᑕᐅᔪᒃᓴᐅᕗᑦ ᒪᓕᒐᖕᒐᒍᑦ ᐱᖁᔭᓕᐊᖕᒍᓯᒪᔪᖁᑦ,"
}
