id: "jbo_Latn"
language: "jbo"
script: "Latn"
name: "Lojban, Latin"
autonym: "lojban (Latin)"
sample_text {
  masthead_full: "RrOo"
  masthead_partial: "Ee"
  styles: "ro remna cu se jinzi co zifre je simdu\'i be"
  tester: "ro remna cu se jinzi co zifre je simdu\'i be le ry. nilselsi\'a .e"
  poster_sm: "ro remna cu"
  poster_md: "ro remna"
  poster_lg: "remna"
  specimen_48: "ro remna cu se jinzi co zifre je simdu\'i be le ry. nilselsi\'a .e lei"
  specimen_36: "ro remna cu se jinzi co zifre je simdu\'i be le ry. nilselsi\'a .e lei ry. selcru .i ry. se menli gi\'e se sezmarde .i .ei jeseki\'ubo ry. simyzu\'e ta\'i le tunba"
  specimen_32: "ro remna cu se jinzi co zifre je simdu\'i be le ry. nilselsi\'a .e lei ry. selcru .i ry. se menli gi\'e se sezmarde .i .ei jeseki\'ubo ry. simyzu\'e ta\'i le tunba"
  specimen_21: "ro remna cu se jinzi co zifre je simdu\'i be le ry. nilselsi\'a .e lei ry. selcru .i ry. se menli gi\'e se sezmarde .i .ei jeseki\'ubo ry. simyzu\'e ta\'i le tunba\nro remna cu se jinzi co zifre je simdu\'i be le ry. nilselsi\'a .e lei ry. selcru .i ry. se menli gi\'e se sezmarde .i .ei jeseki\'ubo ry. simyzu\'e ta\'i le tunba\nro remna cu se jinzi co zifre je simdu\'i be le ry. nilselsi\'a .e lei ry. selcru .i ry. se menli gi\'e se sezmarde .i .ei jeseki\'ubo ry. simyzu\'e ta\'i le tunba"
  specimen_16: "ro remna cu se jinzi co zifre je simdu\'i be le ry. nilselsi\'a .e lei ry. selcru .i ry. se menli gi\'e se sezmarde .i .ei jeseki\'ubo ry. simyzu\'e ta\'i le tunba\nro remna cu se jinzi co zifre je simdu\'i be le ry. nilselsi\'a .e lei ry. selcru .i ry. se menli gi\'e se sezmarde .i .ei jeseki\'ubo ry. simyzu\'e ta\'i le tunba\nro remna cu se jinzi co zifre je simdu\'i be le ry. nilselsi\'a .e lei ry. selcru .i ry. se menli gi\'e se sezmarde .i .ei jeseki\'ubo ry. simyzu\'e ta\'i le tunba\nro remna cu se jinzi co zifre je simdu\'i be le ry. nilselsi\'a .e lei ry. selcru .i ry. se menli gi\'e se sezmarde .i .ei jeseki\'ubo ry. simyzu\'e ta\'i le tunba"
}
