id: "jiv_Latn"
language: "jiv"
script: "Latn"
name: "Shuar, Latin, Ecuador"
sample_text {
  masthead_full: "PpEe"
  masthead_partial: "Nn"
  styles: "Penker inintimsamka mash aintsti ankan, matekrin"
  tester: "Penker inintimsamka mash aintsti ankan, matekrin nuya nii penkerin"
  poster_sm: ""
  poster_md: ""
  poster_lg: "Penker"
  specimen_48: ""
  specimen_36: ""
  specimen_32: "Penker inintimsamka mash aintsti ankan, matekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti aratukmau atinuitji mai matekrak."
  specimen_21: "Penker inintimsamka mash aintsti ankan, matekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti aratukmau atinuitji mai matekrak.\nPenker inintimsamka mash aintsti ankan, matekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti aratukmau atinuitji mai matekrak.\nPenker inintimsamka mash aintsti ankan, matekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti aratukmau atinuitji mai matekrak."
  specimen_16: "Penker inintimsamka mash aintsti ankan, matekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti aratukmau atinuitji mai matekrak.\nPenker inintimsamka mash aintsti ankan, matekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti aratukmau atinuitji mai matekrak.\nPenker inintimsamka mash aintsti ankan, matekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti aratukmau atinuitji mai matekrak.\nPenker inintimsamka mash aintsti ankan, matekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti aratukmau atinuitji mai matekrak.\nPenker inintimsamka mash aintsti ankan, matekrin nuya nii penkerin takakui nii akiniamunmaya tu ausamti aratukmau atinuitji mai matekrak."
}
