id: "jiv_Latn"
language: "jiv"
script: "Latn"
name: "Shuar, Latin, Ecuador"
sample_text {
  masthead_full: "PpEe"
  masthead_partial: "Nn"
  styles: "P\ne\nn\nk\ne\nr\n \ni\nn\ni\nn\nt\ni\nm\ns\na\nm\nk\na\n \nm"
  tester: "P\ne\nn\nk\ne\nr\n \ni\nn\ni\nn\nt\ni\nm\ns\na\nm\nk\na\n \nm\na\ns\nh\n \na\ni\nn\nt\ns\nt"
  poster_sm: "P\ne\nn\nk\ne\nr"
  poster_md: "P\ne\nn\nk\ne"
  poster_lg: "P\ne"
  specimen_48: "P\ne\nn\nk\ne\nr\n \ni\nn\ni\nn\nt\ni\nm\ns\na\nm\nk\na\n \nm\na\ns\nh\n \na\ni\nn\nt\ns\nt"
  specimen_36: "P\ne\nn\nk\ne\nr\n \ni\nn\ni\nn\nt\ni\nm\ns\na\nm\nk\na\n \nm\na\ns\nh\n \na\ni\nn\nt\ns\nt\ni\n \na\nn\nk\na\nn\n,\n \nm\na\nt\ne\nk\nr\ni\nn\n \nn\nu"
  specimen_32: "P\ne\nn\nk\ne\nr\n \ni\nn\ni\nn\nt\ni\nm\ns\na\nm\nk\na\n \nm\na\ns\nh\n \na\ni\nn\nt\ns\nt\ni\n \na\nn\nk\na\nn\n,\n \nm\na\nt\ne\nk\nr\ni\nn\n \nn\nu\ny\na\n \nn\ni\ni\n \np\ne\nn\nk\ne\nr\ni\nn\n \nt\na\nk\na"
  specimen_21: "P\ne\nn\nk\ne\nr\n \ni\nn\ni\nn\nt\ni\nm\ns\na\nm\nk\na\n \nm\na\ns\nh\n \na\ni\nn\nt\ns\nt\ni\n \na\nn\nk\na\nn\n,\n \nm\na\nt\ne\nk\nr\ni\nn\n \nn\nu\ny\na\n \nn\ni\ni\n \np\ne\nn\nk\ne\nr\ni\nn\n \nt\na\nk\na\nk\nu\ni\n \nn\ni\ni\n \na\nk\ni\nn\ni\na\nm\nu\nn\nm\na\ny\na\n \nt\nu\n \na\nu\ns\na\nm\nt\ni\n \na\nr\na\nt\nu\nk\nm\na\nu\n \na\nt\ni\nn\nu\ni\nt\nj\ni\n \nm\na\ni\n \nm\na\nt\ne\nk\nr\na\nk\n.\nP\ne\nn\nk\ne\nr\n \ni\nn\ni\nn\nt\ni\nm\ns"
  specimen_16: "P\ne\nn\nk\ne\nr\n \ni\nn\ni\nn\nt\ni\nm\ns\na\nm\nk\na\n \nm\na\ns\nh\n \na\ni\nn\nt\ns\nt\ni\n \na\nn\nk\na\nn\n,\n \nm\na\nt\ne\nk\nr\ni\nn\n \nn\nu\ny\na\n \nn\ni\ni\n \np\ne\nn\nk\ne\nr\ni\nn\n \nt\na\nk\na\nk\nu\ni\n \nn\ni\ni\n \na\nk\ni\nn\ni\na\nm\nu\nn\nm\na\ny\na\n \nt\nu\n \na\nu\ns\na\nm\nt\ni\n \na\nr\na\nt\nu\nk\nm\na\nu\n \na\nt\ni\nn\nu\ni\nt\nj\ni\n \nm\na\ni\n \nm\na\nt\ne\nk\nr\na\nk\n.\nP\ne\nn\nk\ne\nr\n \ni\nn\ni\nn\nt\ni\nm\ns\na\nm\nk\na\n \nm\na\ns\nh\n \na\ni\nn\nt\ns\nt\ni\n \na\nn\nk\na\nn\n,\n \nm\na\nt\ne\nk\nr\ni\nn\n \nn\nu\ny\na\n \nn\ni\ni\n \np\ne\nn\nk\ne\nr\ni\nn\n \nt\na\nk\na\nk\nu\ni\n \nn\ni\ni\n \na\nk\ni\nn\ni\na\nm\nu\nn\nm\na\ny\na\n \nt\nu\n \na\nu\ns\na\nm\nt\ni\n \na\nr\na\nt\nu\nk\nm\na\nu\n \na\nt\ni\nn\nu\ni\nt\nj\ni\n \nm\na\ni\n \nm\na\nt\ne\nk\nr\na\nk\n.\nP\ne\nn\nk"
}
