id: "jra_Latn"
language: "jra"
script: "Latn"
name: "Jarai, Latin"
sample_text {
  masthead_full: "AaBb"
  masthead_partial: "Ii"
  styles: "A\nb\ni\nh\n \nb\na\nn\ng\n \nm\nơ\nn\nu\ni\nh\n-\nm\nơ\nn\na"
  tester: "A\nb\ni\nh\n \nb\na\nn\ng\n \nm\nơ\nn\nu\ni\nh\n-\nm\nơ\nn\na\nm\n \nt\nơ\nk\ne\nn\ng\n \nr"
  poster_sm: "A\nb\ni\nh\n \nb"
  poster_md: "A\nb\ni\nh\n "
  poster_lg: "A\nb"
  specimen_48: "A\nb\ni\nh\n \nb\na\nn\ng\n \nm\nơ\nn\nu\ni\nh\n-\nm\nơ\nn\na\nm\n \nt\nơ\nk\ne\nn\ng\n \nr"
  specimen_36: "A\nb\ni\nh\n \nb\na\nn\ng\n \nm\nơ\nn\nu\ni\nh\n-\nm\nơ\nn\na\nm\n \nt\nơ\nk\ne\nn\ng\n \nr\na\ni\n \nr\nơ\nn\ng\na\ni\n \nl\na\ni\nh\n \na\nn\nŭ\nn\n "
  specimen_32: "A\nb\ni\nh\n \nb\na\nn\ng\n \nm\nơ\nn\nu\ni\nh\n-\nm\nơ\nn\na\nm\n \nt\nơ\nk\ne\nn\ng\n \nr\na\ni\n \nr\nơ\nn\ng\na\ni\n \nl\na\ni\nh\n \na\nn\nŭ\nn\n \nm\nơ\nd\nơ\n̆\n-\nm\nơ\nđ\nơ\nr\n \na\nm\nă\nn\ng\n \nt\nơ\nl"
  specimen_21: "A\nb\ni\nh\n \nb\na\nn\ng\n \nm\nơ\nn\nu\ni\nh\n-\nm\nơ\nn\na\nm\n \nt\nơ\nk\ne\nn\ng\n \nr\na\ni\n \nr\nơ\nn\ng\na\ni\n \nl\na\ni\nh\n \na\nn\nŭ\nn\n \nm\nơ\nd\nơ\n̆\n-\nm\nơ\nđ\nơ\nr\n \na\nm\nă\nn\ng\n \nt\nơ\nl\nơ\ni\n \np\nơ\np\nŭ\n-\np\nơ\ny\nô\nm\n \nh\nă\nn\ng\n \nt\nơ\nl\nơ\ni\n \nd\nư\ni\n.\n \nɃ\ni\nn\ng\n \ng\nơ\nñ\nu\n \nt\nŭ\n \nh\nơ\nm\nâ\no\n \nt\nơ\nl\nơ\ni\n \np\nơ\nm\nĭ\nn\n \nh\nă\nn\ng\n \nt\nơ\nl\nơ\ni\n \nt\nh\nâ\no\n \nd\nj\nơ\n̆\n-"
  specimen_16: "A\nb\ni\nh\n \nb\na\nn\ng\n \nm\nơ\nn\nu\ni\nh\n-\nm\nơ\nn\na\nm\n \nt\nơ\nk\ne\nn\ng\n \nr\na\ni\n \nr\nơ\nn\ng\na\ni\n \nl\na\ni\nh\n \na\nn\nŭ\nn\n \nm\nơ\nd\nơ\n̆\n-\nm\nơ\nđ\nơ\nr\n \na\nm\nă\nn\ng\n \nt\nơ\nl\nơ\ni\n \np\nơ\np\nŭ\n-\np\nơ\ny\nô\nm\n \nh\nă\nn\ng\n \nt\nơ\nl\nơ\ni\n \nd\nư\ni\n.\n \nɃ\ni\nn\ng\n \ng\nơ\nñ\nu\n \nt\nŭ\n \nh\nơ\nm\nâ\no\n \nt\nơ\nl\nơ\ni\n \np\nơ\nm\nĭ\nn\n \nh\nă\nn\ng\n \nt\nơ\nl\nơ\ni\n \nt\nh\nâ\no\n \nd\nj\nơ\n̆\n-\ng\nl\na\nĭ\n \nl\na\ni\nh\n \na\nn\nŭ\nn\n \nb\nr\nơ\ni\n \nn\ng\nă\n \nk\nơ\n \nt\nơ\nd\nr\nu\nă\n \na\nm\nă\nn\ng\n \nt\nơ\nl\nơ\ni\n \nk\nh\nă\np\n \na\ny\nŏ\nn\ng\n \na\nd\nơ\ni\n.\nA\nb\ni\nh\n \nb\na\nn\ng\n \nm\nơ\nn\nu\ni\nh\n-\nm\nơ\nn\na\nm\n \nt\nơ\nk\ne\nn\ng\n \nr\na\ni\n \nr\nơ\nn\ng\na\ni\n \nl\na\ni\nh\n \na\nn\nŭ\nn\n \nm\nơ\nd\nơ\n̆\n-\nm\nơ\nđ\nơ\nr\n \na\nm"
}
