id: "ka"
language: "ka"
script: "Geor"
name: "Georgian"
autonym: "ქართული"
population: 3543645
region: "GE"
region: "IR"
region: "TR"
exemplar_chars {
  base: "ა ბ გ დ ე ვ ზ თ ი კ ლ მ ნ ო პ ჟ რ ს ტ უ ფ ქ ღ ყ შ ჩ ც ძ წ ჭ ხ ჯ ჰ"
  auxiliary: "ⴀ ⴁ ⴂ ⴃ ⴄ ⴅ ⴆ ჱ ⴡ ⴇ ⴈ ⴉ ⴊ ⴋ ⴌ ჲ ⴢ ⴍ ⴎ ⴏ ⴐ ⴑ ⴒ ჳ ⴣ ⴓ ⴔ ⴕ ⴖ ⴗ ⴘ ⴙ ⴚ ⴛ ⴜ ⴝ ⴞ ჴ ⴤ ⴟ ⴠ ჵ ⴥ ჶ ჷ ჸ ჹ ჺ"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … ჻ \' ‘ ‚ “ „ « » ( ) [ ] { } § @ * / & # † ‡ ′ ″ № { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "ა ბ გ დ ე ვ ზ თ ი კ ლ მ ნ ო პ ჟ რ ს ტ უ ფ ქ ღ ყ შ ჩ ც ძ წ ჭ ხ ჯ ჰ"
}
sample_text {
  masthead_full: "ყოვე"
  masthead_partial: "ლი"
  styles: "ვინაიდან ადამიანთა ოჯახის ყველა წევრისათვის"
  tester: "ვინაიდან, ადამიანის უფლებათა უგულებელყოფამ და აბუჩად აგდებამ გამოიწვია"
  poster_sm: "ვინაიდან, წევრმა"
  poster_md: "ვინაიდან,"
  poster_lg: "ყოველი"
  specimen_48: "ამ ადამიანის უფლებათა საყოველთაო დეკლარაციას ისეთ ამოცანად, რომლის"
  specimen_36: "ყოველ ადამიანს, სადაც არ უნდა იმყოფებოდეს იგი, უფლება აქვს, რომ აღიარებულ იქნეს მისი სამართალსუბიექტობა."
  specimen_32: "ყველას ვისაც დაერღვა კონსტიტუციით ან კანონით მინიჭებული ძირითადი უფლებები, უნდა ჰქონდეს სამართლებრივი დაცვის ეფექტიანი საშუალება კომპეტენტური ეროვნული სასამართლოებისაგან."
  specimen_21: "არავინ შეიძლება დაექვემდებაროს თვითნებურ დაკავებას, დაპატიმრებას ან გაძევებას.\nყოველ ადამიანს, მის უფლება-მოვალეობათა და მისთვის წაყენებული სისხლის სამართლებრივი ბრალდებათა საფუძვლიანობის განსაზღვროსათვის , სრული თანასწორობის საფუძველზე, უფლება აქვს, მისი საქმე საჯაროდ და სამართლიანობის ყველა მოთხოვნის დაცვით განიხილოს დამოუკიდებელმა და მიუკერძოებელმა სასამართლომ."
  specimen_16: "არავის მიმართ არ შეიძლება თვითნებური ჩარევა მის პირადსა და ოჯახურ ცხოვრებაში, თვითნებური ხელყოფა მისი საცხოვრებელი ბინის ხელშეუხებლობის, მისი კორესპონდენციის საიდუმლოების ანდა მისი პატივისა და რეპუტაციისა. ყოველ ადამიანს აქვს უფლება დაცული იყოს კანონის მიერ ასეთი ჩარევისა თუ ხელყოფისაგან.\nყველა ადამიანს აქვს უფლება აზრის, სინდისისა და რელიგიის თავისუფლებისა; ეს უფლება მოიცავს საკუთარი რელიგიის ან რწმენის შეცვლის, საკუთარი რელიგიის ან აღმსარებლობის, როგორც ინდივიდუალურად, ასევე სხვებთან ერთად, საჯაროდ ან კერძოდ, მოძღვრების, ღვთისმსახურების და რელიგიურ ან რიტუალურ წეს-ჩვეულებათა შესრულების თავისუფლებას."
}
