id: "ka_Geok"
language: "ka"
script: "Geok"
name: "Georgian, Georgian Khutsuri"
sample_text {
  masthead_full: "ႷⴗႥⴅ"
  masthead_partial: "Ⴄⴄ"
  styles: "Ⴗ\nႥ\nႤ\nႪ\nႠ\n \nႠ\nႣ\nႠ\nႫ\nႨ\nႠ\nႬ\nႨ\n \nႨ\nႡ\nႠ\nႣ\nႤ\nႡ"
  tester: "Ⴗ\nႥ\nႤ\nႪ\nႠ\n \nႠ\nႣ\nႠ\nႫ\nႨ\nႠ\nႬ\nႨ\n \nႨ\nႡ\nႠ\nႣ\nႤ\nႡ\nႠ\n \nႧ\nႠ\nႥ\nႨ\nႱ\nႳ\nႴ\nႠ"
  poster_sm: "Ⴗ\nႥ\nႤ\nႪ\nႠ\n "
  poster_md: "Ⴗ\nႥ\nႤ\nႪ\nႠ"
  poster_lg: "Ⴗ\nႥ"
  specimen_48: "Ⴗ\nႥ\nႤ\nႪ\nႠ\n \nႠ\nႣ\nႠ\nႫ\nႨ\nႠ\nႬ\nႨ\n \nႨ\nႡ\nႠ\nႣ\nႤ\nႡ\nႠ\n \nႧ\nႠ\nႥ\nႨ\nႱ\nႳ\nႴ\nႠ"
  specimen_36: "Ⴗ\nႥ\nႤ\nႪ\nႠ\n \nႠ\nႣ\nႠ\nႫ\nႨ\nႠ\nႬ\nႨ\n \nႨ\nႡ\nႠ\nႣ\nႤ\nႡ\nႠ\n \nႧ\nႠ\nႥ\nႨ\nႱ\nႳ\nႴ\nႠ\nႪ\nႨ\n \nႣ\nႠ\n \nႧ\nႠ\nႬ\nႠ\nႱ\nႼ\nႭ\nႰ\nႨ\n \nႧ\nႠ\nႥ\nႨ"
  specimen_32: "Ⴗ\nႥ\nႤ\nႪ\nႠ\n \nႠ\nႣ\nႠ\nႫ\nႨ\nႠ\nႬ\nႨ\n \nႨ\nႡ\nႠ\nႣ\nႤ\nႡ\nႠ\n \nႧ\nႠ\nႥ\nႨ\nႱ\nႳ\nႴ\nႠ\nႪ\nႨ\n \nႣ\nႠ\n \nႧ\nႠ\nႬ\nႠ\nႱ\nႼ\nႭ\nႰ\nႨ\n \nႧ\nႠ\nႥ\nႨ\nႱ\nႨ\n \nႶ\nႨ\nႰ\nႱ\nႤ\nႡ\nႨ\nႧ\nႠ\n \nႣ\nႠ\n \nႳ\nႴ\nႪ\nႤ"
  specimen_21: "Ⴗ\nႥ\nႤ\nႪ\nႠ\n \nႠ\nႣ\nႠ\nႫ\nႨ\nႠ\nႬ\nႨ\n \nႨ\nႡ\nႠ\nႣ\nႤ\nႡ\nႠ\n \nႧ\nႠ\nႥ\nႨ\nႱ\nႳ\nႴ\nႠ\nႪ\nႨ\n \nႣ\nႠ\n \nႧ\nႠ\nႬ\nႠ\nႱ\nႼ\nႭ\nႰ\nႨ\n \nႧ\nႠ\nႥ\nႨ\nႱ\nႨ\n \nႶ\nႨ\nႰ\nႱ\nႤ\nႡ\nႨ\nႧ\nႠ\n \nႣ\nႠ\n \nႳ\nႴ\nႪ\nႤ\nႡ\nႤ\nႡ\nႨ\nႧ\n.\n \nႫ\nႠ\nႧ\n \nႫ\nႨ\nႬ\nႨ\nႽ\nႤ\nႡ\nႳ\nႪ\nႨ\n \nႠ\nႵ\nႥ\nႧ\n \nႢ\nႭ\nႬ\nႤ\nႡ\nႠ\n \nႣ\nႠ\n \nႱ\nႨ\nႬ\nႣ\nႨ\nႱ\nႨ\n \nႣ\nႠ\n \nႤ\nႰ\nႧ\nႫ\nႠ\nႬ\nႤ\nႧ\nႨ\nႱ\n \nႫ\nႨ\nႫ\nႠ\nႰ\nႧ\n \nႳ\nႬ\nႣ\nႠ\n \nႨ\nႵ\nႺ\nႤ\nႭ\nႣ\nႬ\nႤ\nႬ"
  specimen_16: "Ⴗ\nႥ\nႤ\nႪ\nႠ\n \nႠ\nႣ\nႠ\nႫ\nႨ\nႠ\nႬ\nႨ\n \nႨ\nႡ\nႠ\nႣ\nႤ\nႡ\nႠ\n \nႧ\nႠ\nႥ\nႨ\nႱ\nႳ\nႴ\nႠ\nႪ\nႨ\n \nႣ\nႠ\n \nႧ\nႠ\nႬ\nႠ\nႱ\nႼ\nႭ\nႰ\nႨ\n \nႧ\nႠ\nႥ\nႨ\nႱ\nႨ\n \nႶ\nႨ\nႰ\nႱ\nႤ\nႡ\nႨ\nႧ\nႠ\n \nႣ\nႠ\n \nႳ\nႴ\nႪ\nႤ\nႡ\nႤ\nႡ\nႨ\nႧ\n.\n \nႫ\nႠ\nႧ\n \nႫ\nႨ\nႬ\nႨ\nႽ\nႤ\nႡ\nႳ\nႪ\nႨ\n \nႠ\nႵ\nႥ\nႧ\n \nႢ\nႭ\nႬ\nႤ\nႡ\nႠ\n \nႣ\nႠ\n \nႱ\nႨ\nႬ\nႣ\nႨ\nႱ\nႨ\n \nႣ\nႠ\n \nႤ\nႰ\nႧ\nႫ\nႠ\nႬ\nႤ\nႧ\nႨ\nႱ\n \nႫ\nႨ\nႫ\nႠ\nႰ\nႧ\n \nႳ\nႬ\nႣ\nႠ\n \nႨ\nႵ\nႺ\nႤ\nႭ\nႣ\nႬ\nႤ\nႬ\n \nძ\nႫ\nႭ\nႡ\nႨ\nႱ\n \nႱ\nႳ\nႪ\nႨ\nႱ\nႩ\nႥ\nႤ\nႧ\nႤ\nႡ\nႨ\nႧ\n.\nႷ\nႥ\nႤ\nႪ\nႠ\n \nႠ\nႣ\nႠ\nႫ\nႨ\nႠ\nႬ\nႨ\n \nႨ\nႡ\nႠ\nႣ\nႤ\nႡ\nႠ\n \nႧ\nႠ\nႥ\nႨ\nႱ\nႳ\nႴ\nႠ\nႪ\nႨ\n \nႣ\nႠ\n \nႧ\nႠ\nႬ\nႠ\nႱ\nႼ\nႭ\nႰ\nႨ\n \nႧ\nႠ\nႥ\nႨ\nႱ\nႨ\n \nႶ\nႨ\nႰ\nႱ\nႤ\nႡ\nႨ\nႧ\nႠ\n \nႣ\nႠ\n \nႳ\nႴ\nႪ\nႤ\nႡ\nႤ\nႡ\nႨ\nႧ\n.\n \nႫ\nႠ\nႧ\n \nႫ\nႨ\nႬ\nႨ\nႽ\nႤ\nႡ\nႳ\nႪ\nႨ\n \nႠ\nႵ\nႥ\nႧ\n \nႢ\nႭ\nႬ\nႤ\nႡ\nႠ"
}
