id: "kaa"
language: "kaa"
script: "Cyrl"
name: "Kara-Kalpak"
autonym: "Қарақалпақ"
population: 489046
region: "UZ"
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я Ё Ў Ғ Қ Ң Ү Ҳ Ә Ө а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я ё ў ғ қ ң ү ҳ ә ө"
  marks: "◌̆ ◌̈"
}
sample_text {
  fallback_language: "ru"
}
