id: "kaa_Cyrl"
language: "kaa"
script: "Cyrl"
name: "Kara-Kalpak"
autonym: "Қарақалпақ"
population: 489046
region: "UZ"
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я Ё Ў Ғ Қ Ң Ү Ҳ Ә Ө а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я ё ў ғ қ ң ү ҳ ә ө"
  marks: "◌̆ ◌̈"
}
sample_text {
  masthead_full: "ҲҳӘә"
  masthead_partial: "Мм"
  styles: "Ҳ\nә\nм\nм\nе\n \nа\nд\nа\nм\nл\nа\nр\n \nө\nз\n \nқ\nә\nд\nи"
  tester: "Ҳ\nә\nм\nм\nе\n \nа\nд\nа\nм\nл\nа\nр\n \nө\nз\n \nқ\nә\nд\nи\nр\n-\nқ\nы\nм\nб\nа\nт\nы\n "
  poster_sm: "Ҳ\nә\nм\nм\nе\n "
  poster_md: "Ҳ\nә\nм\nм\nе"
  poster_lg: "Ҳ\nә"
  specimen_48: "Ҳ\nә\nм\nм\nе\n \nа\nд\nа\nм\nл\nа\nр\n \nө\nз\n \nқ\nә\nд\nи\nр\n-\nқ\nы\nм\nб\nа\nт\nы\n "
  specimen_36: "Ҳ\nә\nм\nм\nе\n \nа\nд\nа\nм\nл\nа\nр\n \nө\nз\n \nқ\nә\nд\nи\nр\n-\nқ\nы\nм\nб\nа\nт\nы\n \nж\nә\nн\nе\n \nҳ\nу\nқ\nы\nқ\nл\nа\nр\nы\nн\nд\nа\n \nе\nр"
  specimen_32: "Ҳ\nә\nм\nм\nе\n \nа\nд\nа\nм\nл\nа\nр\n \nө\nз\n \nқ\nә\nд\nи\nр\n-\nқ\nы\nм\nб\nа\nт\nы\n \nж\nә\nн\nе\n \nҳ\nу\nқ\nы\nқ\nл\nа\nр\nы\nн\nд\nа\n \nе\nр\nк\nи\nн\n \nҳ\nә\nм\n \nт\nе\nң\n \nб\nо\nл\nы\nп\n \nт\nу"
  specimen_21: "Ҳ\nә\nм\nм\nе\n \nа\nд\nа\nм\nл\nа\nр\n \nө\nз\n \nқ\nә\nд\nи\nр\n-\nқ\nы\nм\nб\nа\nт\nы\n \nж\nә\nн\nе\n \nҳ\nу\nқ\nы\nқ\nл\nа\nр\nы\nн\nд\nа\n \nе\nр\nк\nи\nн\n \nҳ\nә\nм\n \nт\nе\nң\n \nб\nо\nл\nы\nп\n \nт\nу\nў\nы\nл\nа\nд\nы\n.\n \nО\nл\nа\nр\nғ\nа\n \nа\nқ\nы\nл\n \nҳ\nә\nм\n \nҳ\nү\nж\nд\nа\nн\n \nб\nе\nр\nи\nл\nг\nе\nн\n \nб\nо\nл\nы\nп\n,\n \nб\nи\nр\n-\nб\nи\nр\nи\nн\nе\n \nт\nу\nў\nы\nс\nқ\nа\nн\nл\nы\nқ\n \nр\nу\nў\nх\nы\nн\nд\nа\nғ\nы\n \nқ"
  specimen_16: "Ҳ\nә\nм\nм\nе\n \nа\nд\nа\nм\nл\nа\nр\n \nө\nз\n \nқ\nә\nд\nи\nр\n-\nқ\nы\nм\nб\nа\nт\nы\n \nж\nә\nн\nе\n \nҳ\nу\nқ\nы\nқ\nл\nа\nр\nы\nн\nд\nа\n \nе\nр\nк\nи\nн\n \nҳ\nә\nм\n \nт\nе\nң\n \nб\nо\nл\nы\nп\n \nт\nу\nў\nы\nл\nа\nд\nы\n.\n \nО\nл\nа\nр\nғ\nа\n \nа\nқ\nы\nл\n \nҳ\nә\nм\n \nҳ\nү\nж\nд\nа\nн\n \nб\nе\nр\nи\nл\nг\nе\nн\n \nб\nо\nл\nы\nп\n,\n \nб\nи\nр\n-\nб\nи\nр\nи\nн\nе\n \nт\nу\nў\nы\nс\nқ\nа\nн\nл\nы\nқ\n \nр\nу\nў\nх\nы\nн\nд\nа\nғ\nы\n \nқ\nа\nт\nн\nа\nс\nт\nа\n \nб\nо\nл\nы\nў\nы\n \nт\nи\nй\nи\nс\n.\nҲ\nә\nм\nм\nе\n \nа\nд\nа\nм\nл\nа\nр\n \nө\nз\n \nқ\nә\nд\nи\nр\n-\nқ\nы\nм\nб\nа\nт\nы\n \nж\nә\nн\nе\n \nҳ\nу\nқ\nы\nқ\nл\nа\nр\nы\nн\nд\nа\n \nе\nр\nк\nи\nн\n \nҳ\nә\nм\n \nт\nе\nң\n \nб\nо\nл\nы\nп\n \nт\nу\nў\nы\nл\nа\nд\nы\n.\n \nО\nл\nа\nр\nғ\nа\n \nа\nқ\nы\nл\n \nҳ\nә\nм\n \nҳ\nү\nж\nд\nа\nн\n \nб\nе\nр"
}
