id: "kam"
language: "kam"
script: "Latn"
name: "Kamba"
autonym: "Kikamba"
population: 4068120
region: "KE"
exemplar_chars {
  base: "a b c d e f g h i ĩ j k l m n o p q r s t u ũ v w y z"
  marks: "◌̃"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
}
sample_text {
  fallback_language: "en"
}
