id: "kbd"
language: "kbd"
script: "Cyrl"
name: "Kabardian"
autonym: "Адыгэбзэ"
population: 1070872
region: "RU"
region: "TR"
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я Ё Ӏ а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я ё ӏ"
  marks: "◌̆ ◌̈"
}
sample_text {
  masthead_full: "ЦцӀӏ"
  masthead_partial: "Ыы"
  styles: "Цӏыху псори щхьэхуиту, я щӏыхьымрэ я хуэфащэхэмрэкӏэ"
  tester: "Дэтхэнэ зы цӏыхури зэхуэдэу хуитщ мы джэпсалъэм хэт цІыху хуэфащэхэмрэ"
  poster_sm: "Къинэмыщӏауэ,"
  poster_md: "Хэти пщылӏыу"
  poster_lg: "Цӏыху"
  specimen_48: "Хэти лъэщыгъэ епхьэлӏэ хъунукъым, залымыгъэкӏэ, цӏыхугъэм къемызэгъу"
  specimen_36: "Псэуныр, щхьэхуитыныр, шынагъуэншагъэр хэти и хуэфащэщ.\nХэти хуэфащэщ дэнэ щӏыпӏи цӏыхуу, юридическэ лицоуэ къыщалъытэну."
  specimen_32: "Цӏыху псори щхьэхуиту, я щӏыхьымрэ я хуэфащэхэмрэкӏэ зэхуэдэу къалъхур. Акъылрэ зэхэщӏыкӏ гъуазэрэ яӏэщи, зыр зым зэкъуэш зэхащІэ яку дэлъу зэхущытын хуейхэщ."
  specimen_21: "Цӏыху псори щхьэхуиту, я щӏыхьымрэ я хуэфащэхэмрэкӏэ зэхуэдэу къалъхур. Акъылрэ зэхэщӏыкӏ гъуазэрэ яӏэщи, зыр зым зэкъуэш зэхащІэ яку дэлъу зэхущытын хуейхэщ.\nДэтхэнэ зы цӏыхури зэхуэдэу хуитщ мы джэпсалъэм хэт цІыху хуэфащэхэмрэ хуитыныгъэхэмрэ зыхуигъэщхьэпэну, зыщыщ расэм, и фэм, цӏыхубз-цӏыхухъуу зэрыщытым, и бзэм, иӏыгъ диным, политичнэ е нэгъуэщӏ еплъыкӏэу иӏэм, лъэпкъыу е цӏыху гупу къызыхэкӏам, мылъкуу иӏэм, къыщалъхуа-къыздалъхуам емылъытауэ зэхэгъэжыншэу, хуэгъэкӏуэтэныгъэншэу."
  specimen_16: "Цӏыху псори щхьэхуиту, я щӏыхьымрэ я хуэфащэхэмрэкӏэ зэхуэдэу къалъхур. Акъылрэ зэхэщӏыкӏ гъуазэрэ яӏэщи, зыр зым зэкъуэш зэхащІэ яку дэлъу зэхущытын хуейхэщ.\nДэтхэнэ зы цӏыхури зэхуэдэу хуитщ мы джэпсалъэм хэт цІыху хуэфащэхэмрэ хуитыныгъэхэмрэ зыхуигъэщхьэпэну, зыщыщ расэм, и фэм, цӏыхубз-цӏыхухъуу зэрыщытым, и бзэм, иӏыгъ диным, политичнэ е нэгъуэщӏ еплъыкӏэу иӏэм, лъэпкъыу е цӏыху гупу къызыхэкӏам, мылъкуу иӏэм, къыщалъхуа-къыздалъхуам емылъытауэ зэхэгъэжыншэу, хуэгъэкӏуэтэныгъэншэу.\nПсэуныр, щхьэхуитыныр, шынагъуэншагъэр хэти и хуэфащэщ.\nХэти пщылӏыу плъытэ е пщӏылӏыпӏэ ибгъэт хъунукъым, сыт хуэдэ щӏыкӏэуи пщылӏыгъэр, пщылӏ щэн-къэщэхуныр зыми хуэбдэ мыхъуну къуэдыщ."
}
