id: "kbp_Latn"
language: "kbp"
script: "Latn"
name: "Kabiyé"
sample_text {
  masthead_full: "PpAa"
  masthead_partial: "Ll"
  styles: "P\na\nl\nʊ\nl\nʊ\nʊ\n \nɛ\ny\na\na\na\n \nn\nɛ\n \np\na\n-\nt"
  tester: "P\na\nl\nʊ\nl\nʊ\nʊ\n \nɛ\ny\na\na\na\n \nn\nɛ\n \np\na\n-\nt\nɩ\n \ny\nɔ\nɔ\n \nw\nɛ\nʊ\n "
  poster_sm: "P\na\nl\nʊ\nl\nʊ"
  poster_md: "P\na\nl\nʊ\nl"
  poster_lg: "P\na"
  specimen_48: "P\na\nl\nʊ\nl\nʊ\nʊ\n \nɛ\ny\na\na\na\n \nn\nɛ\n \np\na\n-\nt\nɩ\n \ny\nɔ\nɔ\n \nw\nɛ\nʊ\n "
  specimen_36: "P\na\nl\nʊ\nl\nʊ\nʊ\n \nɛ\ny\na\na\na\n \nn\nɛ\n \np\na\n-\nt\nɩ\n \ny\nɔ\nɔ\n \nw\nɛ\nʊ\n \nk\np\na\na\ng\nb\na\na\n \nn\nɛ\n \np\nɛ\nw\nɛ\nɛ\n \nk\nɩ"
  specimen_32: "P\na\nl\nʊ\nl\nʊ\nʊ\n \nɛ\ny\na\na\na\n \nn\nɛ\n \np\na\n-\nt\nɩ\n \ny\nɔ\nɔ\n \nw\nɛ\nʊ\n \nk\np\na\na\ng\nb\na\na\n \nn\nɛ\n \np\nɛ\nw\nɛ\nɛ\n \nk\nɩ\nm\na\nŋ\n \nw\na\nl\na\n \nɛ\ns\nɩ\nn\nd\na\na\n.\n \nP\na\nl"
  specimen_21: "P\na\nl\nʊ\nl\nʊ\nʊ\n \nɛ\ny\na\na\na\n \nn\nɛ\n \np\na\n-\nt\nɩ\n \ny\nɔ\nɔ\n \nw\nɛ\nʊ\n \nk\np\na\na\ng\nb\na\na\n \nn\nɛ\n \np\nɛ\nw\nɛ\nɛ\n \nk\nɩ\nm\na\nŋ\n \nw\na\nl\na\n \nɛ\ns\nɩ\nn\nd\na\na\n.\n \nP\na\nl\nʊ\nl\nʊ\nʊ\n-\nw\nɛ\n \nn\nɛ\n \np\nɔ\n-\nl\nɔ\nŋ\n \nn\nɛ\n \np\na\n-\nm\na\nɣ\nz\nɩ\nm\n;\n \nm\nb\nʊ\n \ny\ne\nk\ni\nn\na\n \nn\nɛ\n \np\nɔ\ns\nɔ\nɔ\nl\nɩ\n \nɖ\na\nm\na\n \ns\ne\n \np\nɛ\nk\nɛ\n \nɛ\ny\na\na\n \np\na\n-\nt\nɩ\nŋ\ng\nɛ\n.\nP\na"
  specimen_16: "P\na\nl\nʊ\nl\nʊ\nʊ\n \nɛ\ny\na\na\na\n \nn\nɛ\n \np\na\n-\nt\nɩ\n \ny\nɔ\nɔ\n \nw\nɛ\nʊ\n \nk\np\na\na\ng\nb\na\na\n \nn\nɛ\n \np\nɛ\nw\nɛ\nɛ\n \nk\nɩ\nm\na\nŋ\n \nw\na\nl\na\n \nɛ\ns\nɩ\nn\nd\na\na\n.\n \nP\na\nl\nʊ\nl\nʊ\nʊ\n-\nw\nɛ\n \nn\nɛ\n \np\nɔ\n-\nl\nɔ\nŋ\n \nn\nɛ\n \np\na\n-\nm\na\nɣ\nz\nɩ\nm\n;\n \nm\nb\nʊ\n \ny\ne\nk\ni\nn\na\n \nn\nɛ\n \np\nɔ\ns\nɔ\nɔ\nl\nɩ\n \nɖ\na\nm\na\n \ns\ne\n \np\nɛ\nk\nɛ\n \nɛ\ny\na\na\n \np\na\n-\nt\nɩ\nŋ\ng\nɛ\n.\nP\na\nl\nʊ\nl\nʊ\nʊ\n \nɛ\ny\na\na\na\n \nn\nɛ\n \np\na\n-\nt\nɩ\n \ny\nɔ\nɔ\n \nw\nɛ\nʊ\n \nk\np\na\na\ng\nb\na\na\n \nn\nɛ\n \np\nɛ\nw\nɛ\nɛ\n \nk\nɩ\nm\na\nŋ\n \nw\na\nl\na\n \nɛ\ns\nɩ\nn\nd\na\na\n.\n \nP\na\nl\nʊ\nl\nʊ\nʊ\n-\nw\nɛ\n \nn\nɛ\n \np\nɔ\n-\nl\nɔ\nŋ\n \nn\nɛ\n \np\na\n-\nm\na\nɣ\nz\nɩ\nm\n;\n \nm\nb\nʊ\n \ny\ne\nk\ni\nn\na\n \nn\nɛ\n \np\nɔ\ns\nɔ\nɔ\nl\nɩ\n \nɖ\na\nm\na"
}
