id: "kca_Cyrl"
language: "kca"
script: "Cyrl"
name: "Khanty"
autonym: "Ханты"
population: 0
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я Ё Є Ў Қ Ң Ҳ Ҷ Ӆ Ӈ Ӑ Ӓ Ә Ӛ Ӧ Ө Ӫ Ӱ Ԓ а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я ё є ў қ ң ҳ ҷ ӆ ӈ ӑ ӓ ә ӛ ӧ ө ӫ ӱ ԓ"
  marks: "◌̆ ◌̈"
}
