id: "kdh_Latn"
language: "kdh"
script: "Latn"
name: "Tem"
sample_text {
  masthead_full: "BbÁá"
  masthead_partial: "Nn"
  styles: "B\ná\nn\nl\nʊ\nr\nʊ\ń\nʊ\n \nɩ\nr\nʊ\ń\n \nb\ná\na\n \nw\ne\ne"
  tester: "B\ná\nn\nl\nʊ\nr\nʊ\ń\nʊ\n \nɩ\nr\nʊ\ń\n \nb\ná\na\n \nw\ne\ne\nn\ní\n \nn\na\n \nk\ne\nz\né"
  poster_sm: "B\ná\nn\nl\nʊ\nr"
  poster_md: "B\ná\nn\nl\nʊ"
  poster_lg: "B\ná"
  specimen_48: "B\ná\nn\nl\nʊ\nr\nʊ\ń\nʊ\n \nɩ\nr\nʊ\ń\n \nb\ná\na\n \nw\ne\ne\nn\ní\n \nn\na\n \nk\ne\nz\né"
  specimen_36: "B\ná\nn\nl\nʊ\nr\nʊ\ń\nʊ\n \nɩ\nr\nʊ\ń\n \nb\ná\na\n \nw\ne\ne\nn\ní\n \nn\na\n \nk\ne\nz\né\nń\nb\ní\ní\nd\ni\n \ng\nɛ\n \nb\nɩ\nk\na\n \nb\nɛ\nd\nɛ\ń"
  specimen_32: "B\ná\nn\nl\nʊ\nr\nʊ\ń\nʊ\n \nɩ\nr\nʊ\ń\n \nb\ná\na\n \nw\ne\ne\nn\ní\n \nn\na\n \nk\ne\nz\né\nń\nb\ní\ní\nd\ni\n \ng\nɛ\n \nb\nɩ\nk\na\n \nb\nɛ\nd\nɛ\ń\nɛ\n \nɖ\nɔ\nɔ\nz\nɩ\ń\nt\nɩ\n \nn\na\n \ny\ní\nk\no\nw\ná\n "
  specimen_21: "B\ná\nn\nl\nʊ\nr\nʊ\ń\nʊ\n \nɩ\nr\nʊ\ń\n \nb\ná\na\n \nw\ne\ne\nn\ní\n \nn\na\n \nk\ne\nz\né\nń\nb\ní\ní\nd\ni\n \ng\nɛ\n \nb\nɩ\nk\na\n \nb\nɛ\nd\nɛ\ń\nɛ\n \nɖ\nɔ\nɔ\nz\nɩ\ń\nt\nɩ\n \nn\na\n \ny\ní\nk\no\nw\ná\n \nk\nɛ\ng\nɛ\ń\nɛ\n \nɖ\né\ny\ní\n-\nɖ\né\ny\ní\n \ng\nɛ\n.\n \nB\nɔ\nw\nɛ\nn\ná\n \nl\na\na\nk\ná\nr\nɩ\n \nn\na\n \nɩ\nr\nʊ\ń\nt\nɩ\n \nb\nɩ\nk\na\n \nb\nɩ\nɩ\nb\nɔ\ń\nɔ\ń\nz\nɩ\n \nb\nɔ\nc\nɔ\nɔ\nn\ná\n \nɖ\na\nm\ná\n \nk\no\no\nb\ní\nr\ne\n "
  specimen_16: "B\ná\nn\nl\nʊ\nr\nʊ\ń\nʊ\n \nɩ\nr\nʊ\ń\n \nb\ná\na\n \nw\ne\ne\nn\ní\n \nn\na\n \nk\ne\nz\né\nń\nb\ní\ní\nd\ni\n \ng\nɛ\n \nb\nɩ\nk\na\n \nb\nɛ\nd\nɛ\ń\nɛ\n \nɖ\nɔ\nɔ\nz\nɩ\ń\nt\nɩ\n \nn\na\n \ny\ní\nk\no\nw\ná\n \nk\nɛ\ng\nɛ\ń\nɛ\n \nɖ\né\ny\ní\n-\nɖ\né\ny\ní\n \ng\nɛ\n.\n \nB\nɔ\nw\nɛ\nn\ná\n \nl\na\na\nk\ná\nr\nɩ\n \nn\na\n \nɩ\nr\nʊ\ń\nt\nɩ\n \nb\nɩ\nk\na\n \nb\nɩ\nɩ\nb\nɔ\ń\nɔ\ń\nz\nɩ\n \nb\nɔ\nc\nɔ\nɔ\nn\ná\n \nɖ\na\nm\ná\n \nk\no\no\nb\ní\nr\ne\n \nc\nɔ\nw\nʊ\nr\nɛ\n.\nB\ná\nn\nl\nʊ\nr\nʊ\ń\nʊ\n \nɩ\nr\nʊ\ń\n \nb\ná\na\n \nw\ne\ne\nn\ní\n \nn\na\n \nk\ne\nz\né\nń\nb\ní\ní\nd\ni\n \ng\nɛ\n \nb\nɩ\nk\na\n \nb\nɛ\nd\nɛ\ń\nɛ\n \nɖ\nɔ\nɔ\nz\nɩ\ń\nt\nɩ\n \nn\na\n \ny\ní\nk\no\nw\ná\n \nk\nɛ\ng\nɛ\ń\nɛ\n \nɖ\né\ny\ní\n-\nɖ\né\ny\ní\n \ng\nɛ\n.\n \nB\nɔ\nw\nɛ\nn\ná\n \nl\na\na\nk\ná\nr\nɩ\n \nn\na\n \nɩ\nr\nʊ\ń\nt\nɩ\n \nb\nɩ\nk"
}
