id: "kek_Latn"
language: "kek"
script: "Latn"
name: "Q\'eqchi\'"
sample_text {
  masthead_full: "CcHh"
  masthead_partial: "Ii"
  styles: "C\nh\ni\nj\nu\nn\ni\nl\n \nl\ni\n \np\no\ny\na\nn\na\nm\n \nj"
  tester: "C\nh\ni\nj\nu\nn\ni\nl\n \nl\ni\n \np\no\ny\na\nn\na\nm\n \nj\nu\nn\nt\na\nq\n\'\ne\ne\nt\n "
  poster_sm: "C\nh\ni\nj\nu\nn"
  poster_md: "C\nh\ni\nj\nu"
  poster_lg: "C\nh"
  specimen_48: "C\nh\ni\nj\nu\nn\ni\nl\n \nl\ni\n \np\no\ny\na\nn\na\nm\n \nj\nu\nn\nt\na\nq\n\'\ne\ne\nt\n "
  specimen_36: "C\nh\ni\nj\nu\nn\ni\nl\n \nl\ni\n \np\no\ny\na\nn\na\nm\n \nj\nu\nn\nt\na\nq\n\'\ne\ne\nt\n \nw\na\nn\nk\ni\nl\n \nx\nl\no\nq\n\'\na\nl\n \nn\na\nq\n \nn\na"
  specimen_32: "C\nh\ni\nj\nu\nn\ni\nl\n \nl\ni\n \np\no\ny\na\nn\na\nm\n \nj\nu\nn\nt\na\nq\n\'\ne\ne\nt\n \nw\na\nn\nk\ni\nl\n \nx\nl\no\nq\n\'\na\nl\n \nn\na\nq\n \nn\na\nk\ne\n\'\ny\no\n\'\nl\na\n,\n \nu\nt\n \nk\na\nm\na\n\'\n \na\nk\n "
  specimen_21: "C\nh\ni\nj\nu\nn\ni\nl\n \nl\ni\n \np\no\ny\na\nn\na\nm\n \nj\nu\nn\nt\na\nq\n\'\ne\ne\nt\n \nw\na\nn\nk\ni\nl\n \nx\nl\no\nq\n\'\na\nl\n \nn\na\nq\n \nn\na\nk\ne\n\'\ny\no\n\'\nl\na\n,\n \nu\nt\n \nk\na\nm\na\n\'\n \na\nk\n \nr\ne\nh\ne\nb\n\'\n \nn\na\nq\n \nw\na\nn\n \nx\nn\na\n\'\nl\ne\nb\n\'\ne\nb\n \nu\nt\n \nn\na\nk\ne\n\'\nr\ne\ne\nk\n\'\na\n \nr\ni\nb\n\'\n,\n \nt\ne\nn\nt\no\n \nn\na\nq\n \nt\ne\n\'\nx\nk\n\'\na\nm\n \nr\ni\nb\n\'\n \ns\na\n\'\n \nu\ns\ni\nl\na\nl\n \nc\nh\ni"
  specimen_16: "C\nh\ni\nj\nu\nn\ni\nl\n \nl\ni\n \np\no\ny\na\nn\na\nm\n \nj\nu\nn\nt\na\nq\n\'\ne\ne\nt\n \nw\na\nn\nk\ni\nl\n \nx\nl\no\nq\n\'\na\nl\n \nn\na\nq\n \nn\na\nk\ne\n\'\ny\no\n\'\nl\na\n,\n \nu\nt\n \nk\na\nm\na\n\'\n \na\nk\n \nr\ne\nh\ne\nb\n\'\n \nn\na\nq\n \nw\na\nn\n \nx\nn\na\n\'\nl\ne\nb\n\'\ne\nb\n \nu\nt\n \nn\na\nk\ne\n\'\nr\ne\ne\nk\n\'\na\n \nr\ni\nb\n\'\n,\n \nt\ne\nn\nt\no\n \nn\na\nq\n \nt\ne\n\'\nx\nk\n\'\na\nm\n \nr\ni\nb\n\'\n \ns\na\n\'\n \nu\ns\ni\nl\na\nl\n \nc\nh\ni\nr\ni\nb\n\'\ni\nl\nr\ni\nb\n\'\ne\nb\n\'\n.\nC\nh\ni\nj\nu\nn\ni\nl\n \nl\ni\n \np\no\ny\na\nn\na\nm\n \nj\nu\nn\nt\na\nq\n\'\ne\ne\nt\n \nw\na\nn\nk\ni\nl\n \nx\nl\no\nq\n\'\na\nl\n \nn\na\nq\n \nn\na\nk\ne\n\'\ny\no\n\'\nl\na\n,\n \nu\nt\n \nk\na\nm\na\n\'\n \na\nk\n \nr\ne\nh\ne\nb\n\'\n \nn\na\nq\n \nw\na\nn\n \nx\nn\na\n\'\nl\ne\nb\n\'\ne\nb\n \nu\nt\n \nn\na\nk\ne\n\'\nr\ne\ne\nk\n\'\na\n \nr\ni\nb\n\'"
}
