id: "khb_Talu"
language: "khb"
script: "Talu"
name: "Lü"
population: 264863
region: "CN"
sample_text {
  masthead_full: "ᦝᧂᦑᦸ"
  masthead_partial: "ᦰᦍ"
  styles: "ᦝᧂᦑᦸᦰ ᦍᦸᧆᦑᦲᧈᦷᦢᦆᧄ ᦅᧀᦂᦱᧂᦐᦸᧂ ᦂᦱᧁ ᦙᦸᧃᦟᦱᧆᦓᧄᧉ ᦶᦙᧈᦷᦎᦶᦂᧄᧉ"
  tester: "ᦝᧂᦑᦸᦰ ᦍᦸᧆᦑᦲᧈᦷᦢᦆᧄ ᦅᧀᦂᦱᧂᦐᦸᧂ ᦂᦱᧁ ᦙᦸᧃᦟᦱᧆᦓᧄᧉ, ᦶᦙᧈᦷᦎᦶᦂᧄᧉ ᦃᦸᧂᧈ ᦋᧄᧉ ᦶᦀᧁ"
  poster_sm: "ᦝᧂᦑᦸᦰ ᦍᦸᧆᦑᦲᧈᦷᦢᦆᧄ"
  poster_md: "ᦝᧂᦑᦸᦰ"
  poster_lg: "ᦝᧂᦑᦸᦰ"
  specimen_48: "ᦝᧂᦑᦸᦰ ᦍᦸᧆᦑᦲᧈᦷᦢᦆᧄ ᦅᧀᦂᦱᧂᦐᦸᧂ ᦂᦱᧁ ᦙᦸᧃᦟᦱᧆᦓᧄᧉ, ᦶᦙᧈᦷᦎᦶᦂᧄᧉ ᦃᦸᧂᧈ"
  specimen_36: "ᦝᧂᦑᦸᦰ ᦍᦸᧆᦑᦲᧈᦷᦢᦆᧄ ᦅᧀᦂᦱᧂᦐᦸᧂ ᦂᦱᧁ ᦙᦸᧃᦟᦱᧆᦓᧄᧉ, ᦶᦙᧈᦷᦎᦶᦂᧄᧉ ᦃᦸᧂᧈ ᦋᧄᧉ ᦶᦀᧁ ᦵᦉᧄᧉ ᦺᦜᧈ ᦺᦃ ᦋᦻᦵᦣᧀ, ᦔᦱᧂ ᦓᦲᦰ ᦋᦻ ᦈᧅ ᦺᦃ ᦺᦔ ᦡᦽᧉᦓᦲᧉ ᦑᦱᧃᦜᧂ ᦶᦎᧈ ᦂᦸᧃᧈ, ᦈᦱ ᦉᦸᧃᧈ ᦠᦹᧉ ᦵᦗᦲᧃᧈᦣᦼᧉᦡᦽᧉᦆᦱᧁᧈᦟᧂᦂᦱ, ᦎᦱᧄᦔᦱᦟᦲᦀᦸᧅᧈ ᦒᧄᦟᧁᧈᦺᦞᧉᦗᦸᦡᧂᧈᦉᦸᧄᧉ ᦡᦸᧅᧈᦺᦙᧉ ᦠᦸᧄ ᦶᦕᧈ ᦵᦙᦲᧂᦺᦑ, ᦅᧄᦺᦘᦷᦎᧅᦶᦑᧃᦺᦡᦵᦗᦲᧃᧈᦠᦱᧅᦟᦹᦌᦰ ᦌᦱᧁᧉ, ᦆᦱᧁᧈᦠᦱᧅᦂᦲᧉᦍᦱᧁᦶᦑᧉ ᦵᦖᦲᧃᦡᧂᧈᦓᧄᧉ ᦶᦙᧈᦦᦱᧂᧉᦉᦖᦳᧆᦺᦊᧈᦉᦱᦅᦸᧃ, ᦢᧆᦓᦲᦰᦂᦸᧃᦅᧄᦙᦲ ᦷᦜᧂᦜᦻᦺᦉᧈ ᦺᦢ ᦑᧂ ᦉᦾᧉ, ᦛᦱᧃ ᦛᦱᧈ ᦀᦾᧉ ᦶᦋᧈ ᦓᧄᧉᦷᦠᧆᦜᦸᧈᦷᦂᧂᦆᦸᦞᦓᦱ."
  specimen_32: "ᦝᧂᦑᦸᦰ ᦍᦸᧆᦑᦲᧈᦷᦢᦆᧄ ᦅᧀᦂᦱᧂᦐᦸᧂ ᦂᦱᧁ ᦙᦸᧃᦟᦱᧆᦓᧄᧉ, ᦶᦙᧈᦷᦎᦶᦂᧄᧉ ᦃᦸᧂᧈ ᦋᧄᧉ ᦶᦀᧁ ᦵᦉᧄᧉ ᦺᦜᧈ ᦺᦃ ᦋᦻᦵᦣᧀ, ᦔᦱᧂ ᦓᦲᦰ ᦋᦻ ᦈᧅ ᦺᦃ ᦺᦔ ᦡᦽᧉᦓᦲᧉ ᦑᦱᧃᦜᧂ ᦶᦎᧈ ᦂᦸᧃᧈ, ᦈᦱ ᦉᦸᧃᧈ ᦠᦹᧉ ᦵᦗᦲᧃᧈᦣᦼᧉᦡᦽᧉᦆᦱᧁᧈᦟᧂᦂᦱ, ᦎᦱᧄᦔᦱᦟᦲᦀᦸᧅᧈ ᦒᧄᦟᧁᧈᦺᦞᧉᦗᦸᦡᧂᧈᦉᦸᧄᧉ ᦡᦸᧅᧈᦺᦙᧉ ᦠᦸᧄ ᦶᦕᧈ ᦵᦙᦲᧂᦺᦑ, ᦅᧄᦺᦘᦷᦎᧅᦶᦑᧃᦺᦡᦵᦗᦲᧃᧈᦠᦱᧅᦟᦹᦌᦰ ᦌᦱᧁᧉ, ᦆᦱᧁᧈᦠᦱᧅᦂᦲᧉᦍᦱᧁᦶᦑᧉ ᦵᦖᦲᧃᦡᧂᧈᦓᧄᧉ ᦶᦙᧈᦦᦱᧂᧉᦉᦖᦳᧆᦺᦊᧈᦉᦱᦅᦸᧃ, ᦢᧆᦓᦲᦰᦂᦸᧃᦅᧄᦙᦲ ᦷᦜᧂᦜᦻᦺᦉᧈ ᦺᦢ ᦑᧂ ᦉᦾᧉ, ᦛᦱᧃ ᦛᦱᧈ ᦀᦾᧉ ᦶᦋᧈ ᦓᧄᧉᦷᦠᧆᦜᦸᧈᦷᦂᧂᦆᦸᦞᦓᦱ."
  specimen_21: "ᦝᧂᦑᦸᦰ ᦍᦸᧆᦑᦲᧈᦷᦢᦆᧄ ᦅᧀᦂᦱᧂᦐᦸᧂ ᦂᦱᧁ ᦙᦸᧃᦟᦱᧆᦓᧄᧉ, ᦶᦙᧈᦷᦎᦶᦂᧄᧉ ᦃᦸᧂᧈ ᦋᧄᧉ ᦶᦀᧁ ᦵᦉᧄᧉ ᦺᦜᧈ ᦺᦃ ᦋᦻᦵᦣᧀ, ᦔᦱᧂ ᦓᦲᦰ ᦋᦻ ᦈᧅ ᦺᦃ ᦺᦔ ᦡᦽᧉᦓᦲᧉ ᦑᦱᧃᦜᧂ ᦶᦎᧈ ᦂᦸᧃᧈ, ᦈᦱ ᦉᦸᧃᧈ ᦠᦹᧉ ᦵᦗᦲᧃᧈᦣᦼᧉᦡᦽᧉᦆᦱᧁᧈᦟᧂᦂᦱ, ᦎᦱᧄᦔᦱᦟᦲᦀᦸᧅᧈ ᦒᧄᦟᧁᧈᦺᦞᧉᦗᦸᦡᧂᧈᦉᦸᧄᧉ ᦡᦸᧅᧈᦺᦙᧉ ᦠᦸᧄ ᦶᦕᧈ ᦵᦙᦲᧂᦺᦑ, ᦅᧄᦺᦘᦷᦎᧅᦶᦑᧃᦺᦡᦵᦗᦲᧃᧈᦠᦱᧅᦟᦹᦌᦰ ᦌᦱᧁᧉ, ᦆᦱᧁᧈᦠᦱᧅᦂᦲᧉᦍᦱᧁᦶᦑᧉ ᦵᦖᦲᧃᦡᧂᧈᦓᧄᧉ ᦶᦙᧈᦦᦱᧂᧉᦉᦖᦳᧆᦺᦊᧈᦉᦱᦅᦸᧃ, ᦢᧆᦓᦲᦰᦂᦸᧃᦅᧄᦙᦲ ᦷᦜᧂᦜᦻᦺᦉᧈ ᦺᦢ ᦑᧂ ᦉᦾᧉ, ᦛᦱᧃ ᦛᦱᧈ ᦀᦾᧉ ᦶᦋᧈ ᦓᧄᧉᦷᦠᧆᦜᦸᧈᦷᦂᧂᦆᦸᦞᦓᦱ."
  specimen_16: "ᦝᧂᦑᦸᦰ ᦍᦸᧆᦑᦲᧈᦷᦢᦆᧄ ᦅᧀᦂᦱᧂᦐᦸᧂ ᦂᦱᧁ ᦙᦸᧃᦟᦱᧆᦓᧄᧉ, ᦶᦙᧈᦷᦎᦶᦂᧄᧉ ᦃᦸᧂᧈ ᦋᧄᧉ ᦶᦀᧁ ᦵᦉᧄᧉ ᦺᦜᧈ ᦺᦃ ᦋᦻᦵᦣᧀ, ᦔᦱᧂ ᦓᦲᦰ ᦋᦻ ᦈᧅ ᦺᦃ ᦺᦔ ᦡᦽᧉᦓᦲᧉ ᦑᦱᧃᦜᧂ ᦶᦎᧈ ᦂᦸᧃᧈ, ᦈᦱ ᦉᦸᧃᧈ ᦠᦹᧉ ᦵᦗᦲᧃᧈᦣᦼᧉᦡᦽᧉᦆᦱᧁᧈᦟᧂᦂᦱ, ᦎᦱᧄᦔᦱᦟᦲᦀᦸᧅᧈ ᦒᧄᦟᧁᧈᦺᦞᧉᦗᦸᦡᧂᧈᦉᦸᧄᧉ ᦡᦸᧅᧈᦺᦙᧉ ᦠᦸᧄ ᦶᦕᧈ ᦵᦙᦲᧂᦺᦑ, ᦅᧄᦺᦘᦷᦎᧅᦶᦑᧃᦺᦡᦵᦗᦲᧃᧈᦠᦱᧅᦟᦹᦌᦰ ᦌᦱᧁᧉ, ᦆᦱᧁᧈᦠᦱᧅᦂᦲᧉᦍᦱᧁᦶᦑᧉ ᦵᦖᦲᧃᦡᧂᧈᦓᧄᧉ ᦶᦙᧈᦦᦱᧂᧉᦉᦖᦳᧆᦺᦊᧈᦉᦱᦅᦸᧃ, ᦢᧆᦓᦲᦰᦂᦸᧃᦅᧄᦙᦲ ᦷᦜᧂᦜᦻᦺᦉᧈ ᦺᦢ ᦑᧂ ᦉᦾᧉ, ᦛᦱᧃ ᦛᦱᧈ ᦀᦾᧉ ᦶᦋᧈ ᦓᧄᧉᦷᦠᧆᦜᦸᧈᦷᦂᧂᦆᦸᦞᦓᦱ.\nᦝᧂᦑᦸᦰ ᦍᦸᧆᦑᦲᧈᦷᦢᦆᧄ ᦅᧀᦂᦱᧂᦐᦸᧂ ᦂᦱᧁ ᦙᦸᧃᦟᦱᧆᦓᧄᧉ, ᦶᦙᧈᦷᦎᦶᦂᧄᧉ ᦃᦸᧂᧈ ᦋᧄᧉ ᦶᦀᧁ ᦵᦉᧄᧉ ᦺᦜᧈ ᦺᦃ ᦋᦻᦵᦣᧀ, ᦔᦱᧂ ᦓᦲᦰ ᦋᦻ ᦈᧅ ᦺᦃ ᦺᦔ ᦡᦽᧉᦓᦲᧉ ᦑᦱᧃᦜᧂ ᦶᦎᧈ ᦂᦸᧃᧈ, ᦈᦱ ᦉᦸᧃᧈ ᦠᦹᧉ ᦵᦗᦲᧃᧈᦣᦼᧉᦡᦽᧉᦆᦱᧁᧈᦟᧂᦂᦱ, ᦎᦱᧄᦔᦱᦟᦲᦀᦸᧅᧈ ᦒᧄᦟᧁᧈᦺᦞᧉᦗᦸᦡᧂᧈᦉᦸᧄᧉ ᦡᦸᧅᧈᦺᦙᧉ ᦠᦸᧄ ᦶᦕᧈ ᦵᦙᦲᧂᦺᦑ, ᦅᧄᦺᦘᦷᦎᧅᦶᦑᧃᦺᦡᦵᦗᦲᧃᧈᦠᦱᧅᦟᦹᦌᦰ ᦌᦱᧁᧉ, ᦆᦱᧁᧈᦠᦱᧅᦂᦲᧉᦍᦱᧁᦶᦑᧉ ᦵᦖᦲᧃᦡᧂᧈᦓᧄᧉ ᦶᦙᧈᦦᦱᧂᧉᦉᦖᦳᧆᦺᦊᧈᦉᦱᦅᦸᧃ, ᦢᧆᦓᦲᦰᦂᦸᧃᦅᧄᦙᦲ ᦷᦜᧂᦜᦻᦺᦉᧈ ᦺᦢ ᦑᧂ ᦉᦾᧉ, ᦛᦱᧃ ᦛᦱᧈ ᦀᦾᧉ ᦶᦋᧈ ᦓᧄᧉᦷᦠᧆᦜᦸᧈᦷᦂᧂᦆᦸᦞᦓᦱ."
}
