id: "khq"
language: "khq"
script: "Latn"
name: "Koyra Chiini"
autonym: "Koyra Chiini"
population: 332407
region: "ML"
exemplar_chars {
  base: "a ã b c d e ẽ f g h i j k l m n ɲ ŋ o õ p q r s š t u w x y z ž"
  auxiliary: "v"
  marks: "◌̃ ◌̌"
  numerals: "  - ‑ . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A Ã B C D E Ẽ F G H I J K L M N Ɲ Ŋ O Õ P Q R S Š T U W X Y Z Ž"
}
sample_text {
  fallback_language: "en"
}
