id: "khr_Beng"
language: "khr"
script: "Beng"
name: "Kharia, Bangla"
region: "IN"
sample_text {
  masthead_full: "সউবম"
  masthead_partial: "লক"
  styles: "সোউবম লেবু কিযাঽ গৈরৱ ওডোঽ ধিকারাঽ মাসন বুঁগ জোনোমজাত সৱতনতরতা"
  tester: "সোউবম লেবু কিযাঽ গৈরৱ ওডোঽ ধিকারাঽ মাসন বুঁগ জোনোমজাত সৱতনতরতা ওডোঽ সমানতা কুঈ সিড"
  poster_sm: "সোউবম লেবু কিযাঽ"
  poster_md: "সোউবম লেবু ক"
  poster_lg: "সোউবম"
  specimen_48: "সোউবম লেবু কিযাঽ গৈরৱ ওডোঽ ধিকারাঽ মাসন বুঁগ জোনোমজাত সৱতনতরতা ওডোঽ সমানতা কুঈ সিড হোতোকে"
  specimen_36: "সোউবম লেবু কিযাঽ গৈরৱ ওডোঽ ধিকারাঽ মাসন বুঁগ জোনোমজাত সৱতনতরতা ওডোঽ সমানতা কুঈ সিড হোতোকে লুর ওডোঽ জাতোমাঽ তের তের কুঈ সিঽ ওডোঽ মুনুডূ হোকী তে ভাঈভাঈ মুন ৱযৱহার করাযনা চাহি।"
  specimen_32: "সোউবম লেবু কিযাঽ গৈরৱ ওডোঽ ধিকারাঽ মাসন বুঁগ জোনোমজাত সৱতনতরতা ওডোঽ সমানতা কুঈ সিড হোতোকে লুর ওডোঽ জাতোমাঽ তের তের কুঈ সিঽ ওডোঽ মুনুডূ হোকী তে ভাঈভাঈ মুন ৱযৱহার করাযনা চাহি।"
  specimen_21: "সোউবম লেবু কিযাঽ গৈরৱ ওডোঽ ধিকারাঽ মাসন বুঁগ জোনোমজাত সৱতনতরতা ওডোঽ সমানতা কুঈ সিড হোতোকে লুর ওডোঽ জাতোমাঽ তের তের কুঈ সিঽ ওডোঽ মুনুডূ হোকী তে ভাঈভাঈ মুন ৱযৱহার করাযনা চাহি।\nসোউবম লেবু কিযাঽ গৈরৱ ওডোঽ ধিকারাঽ মাসন বুঁগ জোনোমজাত সৱতনতরতা ওডোঽ সমানতা কুঈ সিড হোতোকে লুর ওডোঽ জাতোমাঽ তের তের কুঈ সিঽ ওডোঽ মুনুডূ হোকী তে ভাঈভাঈ মুন ৱযৱহার করাযনা চাহি।\nসোউবম লেবু কিযাঽ গৈরৱ ওডোঽ ধিকারাঽ মাসন বুঁগ জোনোমজাত সৱতনতরতা ওডোঽ সমানতা কুঈ সিড হোতোকে লুর ওডোঽ জাতোমাঽ তের তের কুঈ সিঽ ওডোঽ মুনুডূ হোকী তে ভাঈভাঈ মুন ৱযৱহার করাযনা চাহি।"
  specimen_16: "সোউবম লেবু কিযাঽ গৈরৱ ওডোঽ ধিকারাঽ মাসন বুঁগ জোনোমজাত সৱতনতরতা ওডোঽ সমানতা কুঈ সিড হোতোকে লুর ওডোঽ জাতোমাঽ তের তের কুঈ সিঽ ওডোঽ মুনুডূ হোকী তে ভাঈভাঈ মুন ৱযৱহার করাযনা চাহি।\nসোউবম লেবু কিযাঽ গৈরৱ ওডোঽ ধিকারাঽ মাসন বুঁগ জোনোমজাত সৱতনতরতা ওডোঽ সমানতা কুঈ সিড হোতোকে লুর ওডোঽ জাতোমাঽ তের তের কুঈ সিঽ ওডোঽ মুনুডূ হোকী তে ভাঈভাঈ মুন ৱযৱহার করাযনা চাহি।\nসোউবম লেবু কিযাঽ গৈরৱ ওডোঽ ধিকারাঽ মাসন বুঁগ জোনোমজাত সৱতনতরতা ওডোঽ সমানতা কুঈ সিড হোতোকে লুর ওডোঽ জাতোমাঽ তের তের কুঈ সিঽ ওডোঽ মুনুডূ হোকী তে ভাঈভাঈ মুন ৱযৱহার করাযনা চাহি।\nসোউবম লেবু কিযাঽ গৈরৱ ওডোঽ ধিকারাঽ মাসন বুঁগ জোনোমজাত সৱতনতরতা ওডোঽ সমানতা কুঈ সিড হোতোকে লুর ওডোঽ জাতোমাঽ তের তের কুঈ সিঽ ওডোঽ মুনুডূ হোকী তে ভাঈভাঈ মুন ৱযৱহার করাযনা চাহি।\nসোউবম লেবু কিযাঽ গৈরৱ ওডোঽ ধিকারাঽ মাসন বুঁগ জোনোমজাত সৱতনতরতা ওডোঽ সমানতা কুঈ সিড হোতোকে লুর ওডোঽ জাতোমাঽ তের তের কুঈ সিঽ ওডোঽ মুনুডূ হোকী তে ভাঈভাঈ মুন ৱযৱহার করাযনা চাহি।"
}
