id: "khr_Orya"
language: "khr"
script: "Orya"
name: "Kharia, Odia"
region: "IN"
sample_text {
  masthead_full: "ସଉବମ"
  masthead_partial: "ଲକ"
  styles: "ସୋଉବମ ଲେବୁ କିୟାଽ ଗୈରୱ ଓଡୋଽ ଅଧିକାରାଽ ମାସନ ବୁଁଗ ଜୋନୋମଜାତ ସୱତନତରତା"
  tester: "ସୋଉବମ ଲେବୁ କିୟାଽ ଗୈରୱ ଓଡୋଽ ଅଧିକାରାଽ ମାସନ ବୁଁଗ ଜୋନୋମଜାତ ସୱତନତରତା ଓଡୋଽ ସମାନତା କୁଈ ସିଡ"
  poster_sm: "ସୋଉବମ ଲେବୁ କିୟାଽ"
  poster_md: "ସୋଉବମ ଲେବୁ କ"
  poster_lg: "ସୋଉବମ"
  specimen_48: "ସୋଉବମ ଲେବୁ କିୟାଽ ଗୈରୱ ଓଡୋଽ ଅଧିକାରାଽ ମାସନ ବୁଁଗ ଜୋନୋମଜାତ ସୱତନତରତା ଓଡୋଽ ସମାନତା କୁଈ ସିଡ ହୋତୋକେ"
  specimen_36: "ସୋଉବମ ଲେବୁ କିୟାଽ ଗୈରୱ ଓଡୋଽ ଅଧିକାରାଽ ମାସନ ବୁଁଗ ଜୋନୋମଜାତ ସୱତନତରତା ଓଡୋଽ ସମାନତା କୁଈ ସିଡ ହୋତୋକେ ଲୁର ଓଡୋଽ ଜାତୋମାଽ ତେର ତେର କୁଈ ସିଽ ଓଡୋଽ ମୁନୁଡୂ ହୋକୀ ତେ ଵାଈଵାଈ ମୁନ ୱୟୱହାର କରାୟନା ଚାହି‍।"
  specimen_32: "ସୋଉବମ ଲେବୁ କିୟାଽ ଗୈରୱ ଓଡୋଽ ଅଧିକାରାଽ ମାସନ ବୁଁଗ ଜୋନୋମଜାତ ସୱତନତରତା ଓଡୋଽ ସମାନତା କୁଈ ସିଡ ହୋତୋକେ ଲୁର ଓଡୋଽ ଜାତୋମାଽ ତେର ତେର କୁଈ ସିଽ ଓଡୋଽ ମୁନୁଡୂ ହୋକୀ ତେ ଵାଈଵାଈ ମୁନ ୱୟୱହାର କରାୟନା ଚାହି‍।"
  specimen_21: "ସୋଉବମ ଲେବୁ କିୟାଽ ଗୈରୱ ଓଡୋଽ ଅଧିକାରାଽ ମାସନ ବୁଁଗ ଜୋନୋମଜାତ ସୱତନତରତା ଓଡୋଽ ସମାନତା କୁଈ ସିଡ ହୋତୋକେ ଲୁର ଓଡୋଽ ଜାତୋମାଽ ତେର ତେର କୁଈ ସିଽ ଓଡୋଽ ମୁନୁଡୂ ହୋକୀ ତେ ଵାଈଵାଈ ମୁନ ୱୟୱହାର କରାୟନା ଚାହି‍।\nସୋଉବମ ଲେବୁ କିୟାଽ ଗୈରୱ ଓଡୋଽ ଅଧିକାରାଽ ମାସନ ବୁଁଗ ଜୋନୋମଜାତ ସୱତନତରତା ଓଡୋଽ ସମାନତା କୁଈ ସିଡ ହୋତୋକେ ଲୁର ଓଡୋଽ ଜାତୋମାଽ ତେର ତେର କୁଈ ସିଽ ଓଡୋଽ ମୁନୁଡୂ ହୋକୀ ତେ ଵାଈଵାଈ ମୁନ ୱୟୱହାର କରାୟନା ଚାହି‍।\nସୋଉବମ ଲେବୁ କିୟାଽ ଗୈରୱ ଓଡୋଽ ଅଧିକାରାଽ ମାସନ ବୁଁଗ ଜୋନୋମଜାତ ସୱତନତରତା ଓଡୋଽ ସମାନତା କୁଈ ସିଡ ହୋତୋକେ ଲୁର ଓଡୋଽ ଜାତୋମାଽ ତେର ତେର କୁଈ ସିଽ ଓଡୋଽ ମୁନୁଡୂ ହୋକୀ ତେ ଵାଈଵାଈ ମୁନ ୱୟୱହାର କରାୟନା ଚାହି‍।"
  specimen_16: "ସୋଉବମ ଲେବୁ କିୟାଽ ଗୈରୱ ଓଡୋଽ ଅଧିକାରାଽ ମାସନ ବୁଁଗ ଜୋନୋମଜାତ ସୱତନତରତା ଓଡୋଽ ସମାନତା କୁଈ ସିଡ ହୋତୋକେ ଲୁର ଓଡୋଽ ଜାତୋମାଽ ତେର ତେର କୁଈ ସିଽ ଓଡୋଽ ମୁନୁଡୂ ହୋକୀ ତେ ଵାଈଵାଈ ମୁନ ୱୟୱହାର କରାୟନା ଚାହି‍।\nସୋଉବମ ଲେବୁ କିୟାଽ ଗୈରୱ ଓଡୋଽ ଅଧିକାରାଽ ମାସନ ବୁଁଗ ଜୋନୋମଜାତ ସୱତନତରତା ଓଡୋଽ ସମାନତା କୁଈ ସିଡ ହୋତୋକେ ଲୁର ଓଡୋଽ ଜାତୋମାଽ ତେର ତେର କୁଈ ସିଽ ଓଡୋଽ ମୁନୁଡୂ ହୋକୀ ତେ ଵାଈଵାଈ ମୁନ ୱୟୱହାର କରାୟନା ଚାହି‍।\nସୋଉବମ ଲେବୁ କିୟାଽ ଗୈରୱ ଓଡୋଽ ଅଧିକାରାଽ ମାସନ ବୁଁଗ ଜୋନୋମଜାତ ସୱତନତରତା ଓଡୋଽ ସମାନତା କୁଈ ସିଡ ହୋତୋକେ ଲୁର ଓଡୋଽ ଜାତୋମାଽ ତେର ତେର କୁଈ ସିଽ ଓଡୋଽ ମୁନୁଡୂ ହୋକୀ ତେ ଵାଈଵାଈ ମୁନ ୱୟୱହାର କରାୟନା ଚାହି‍।\nସୋଉବମ ଲେବୁ କିୟାଽ ଗୈରୱ ଓଡୋଽ ଅଧିକାରାଽ ମାସନ ବୁଁଗ ଜୋନୋମଜାତ ସୱତନତରତା ଓଡୋଽ ସମାନତା କୁଈ ସିଡ ହୋତୋକେ ଲୁର ଓଡୋଽ ଜାତୋମାଽ ତେର ତେର କୁଈ ସିଽ ଓଡୋଽ ମୁନୁଡୂ ହୋକୀ ତେ ଵାଈଵାଈ ମୁନ ୱୟୱହାର କରାୟନା ଚାହି‍।\nସୋଉବମ ଲେବୁ କିୟାଽ ଗୈରୱ ଓଡୋଽ ଅଧିକାରାଽ ମାସନ ବୁଁଗ ଜୋନୋମଜାତ ସୱତନତରତା ଓଡୋଽ ସମାନତା କୁଈ ସିଡ ହୋତୋକେ ଲୁର ଓଡୋଽ ଜାତୋମାଽ ତେର ତେର କୁଈ ସିଽ ଓଡୋଽ ମୁନୁଡୂ ହୋକୀ ତେ ଵାଈଵାଈ ମୁନ ୱୟୱହାର କରାୟନା ଚାହି‍।"
}
