id: "khr_Beng"
language: "khr"
script: "Beng"
name: "Kharia, Bangla"
sample_text {
  masthead_full: "সউবম"
  masthead_partial: "লক"
  styles: "স\nো\nউ\nব\nম\n \nল\nে\nব\nু\n \nক\nি\nয\nা\nঽ\n \nগ\nৈ\nর\nৱ\n \nও\nড"
  tester: "স\nো\nউ\nব\nম\n \nল\nে\nব\nু\n \nক\nি\nয\nা\nঽ\n \nগ\nৈ\nর\nৱ\n \nও\nড\nো\nঽ\n \nধ\nি\nক\nা\nর\nা\nঽ\n \nম"
  poster_sm: "স\nো\nউ\nব\nম\n "
  poster_md: "স\nো\nউ\nব\nম"
  poster_lg: "স\nো\nউ"
  specimen_48: "স\nো\nউ\nব\nম\n \nল\nে\nব\nু\n \nক\nি\nয\nা\nঽ\n \nগ\nৈ\nর\nৱ\n \nও\nড\nো\nঽ\n \nধ\nি\nক\nা\nর\nা\nঽ\n \nম"
  specimen_36: "স\nো\nউ\nব\nম\n \nল\nে\nব\nু\n \nক\nি\nয\nা\nঽ\n \nগ\nৈ\nর\nৱ\n \nও\nড\nো\nঽ\n \nধ\nি\nক\nা\nর\nা\nঽ\n \nম\nা\nস\nন\n \nব\nু\nঁ\nগ\n \nজ\nো\nন\nো\nম\n-\nজ\nা\nত\n \nস\nৱ\nত\nন"
  specimen_32: "স\nো\nউ\nব\nম\n \nল\nে\nব\nু\n \nক\nি\nয\nা\nঽ\n \nগ\nৈ\nর\nৱ\n \nও\nড\nো\nঽ\n \nধ\nি\nক\nা\nর\nা\nঽ\n \nম\nা\nস\nন\n \nব\nু\nঁ\nগ\n \nজ\nো\nন\nো\nম\n-\nজ\nা\nত\n \nস\nৱ\nত\nন\nত\nর\nত\nা\n \nও\nড\nো\nঽ\n \nস\nম\nা\nন\nত\nা\n \nক\nু\nঈ\n \nস\nি"
  specimen_21: "স\nো\nউ\nব\nম\n \nল\nে\nব\nু\n \nক\nি\nয\nা\nঽ\n \nগ\nৈ\nর\nৱ\n \nও\nড\nো\nঽ\n \nধ\nি\nক\nা\nর\nা\nঽ\n \nম\nা\nস\nন\n \nব\nু\nঁ\nগ\n \nজ\nো\nন\nো\nম\n-\nজ\nা\nত\n \nস\nৱ\nত\nন\nত\nর\nত\nা\n \nও\nড\nো\nঽ\n \nস\nম\nা\nন\nত\nা\n \nক\nু\nঈ\n \nস\nি\nড\n \nহ\nো\nত\nো\nক\nে\n \nল\nু\nর\n \nও\nড\nো\nঽ\n \nজ\nা\nত\nো\nম\nা\nঽ\n \nত\nে\nর\n \nত\nে\nর\n \nক\nু\nঈ\n \nস\nি\nঽ\n \nও\nড\nো\nঽ\n \nম\nু\nন\nু\nড\nূ\n \nহ\nো\nক\nী\n \nত\nে\n \nভ\nা\nঈ\n-\nভ\nা\nঈ\n \nম\nু\nন\n \nৱ\nয\nৱ\nহ\nা\nর\n \nক\nর\nা\nয\nন\nা\n \nচ\nা\nহ\nি\n।\nস\nো"
  specimen_16: "স\nো\nউ\nব\nম\n \nল\nে\nব\nু\n \nক\nি\nয\nা\nঽ\n \nগ\nৈ\nর\nৱ\n \nও\nড\nো\nঽ\n \nধ\nি\nক\nা\nর\nা\nঽ\n \nম\nা\nস\nন\n \nব\nু\nঁ\nগ\n \nজ\nো\nন\nো\nম\n-\nজ\nা\nত\n \nস\nৱ\nত\nন\nত\nর\nত\nা\n \nও\nড\nো\nঽ\n \nস\nম\nা\nন\nত\nা\n \nক\nু\nঈ\n \nস\nি\nড\n \nহ\nো\nত\nো\nক\nে\n \nল\nু\nর\n \nও\nড\nো\nঽ\n \nজ\nা\nত\nো\nম\nা\nঽ\n \nত\nে\nর\n \nত\nে\nর\n \nক\nু\nঈ\n \nস\nি\nঽ\n \nও\nড\nো\nঽ\n \nম\nু\nন\nু\nড\nূ\n \nহ\nো\nক\nী\n \nত\nে\n \nভ\nা\nঈ\n-\nভ\nা\nঈ\n \nম\nু\nন\n \nৱ\nয\nৱ\nহ\nা\nর\n \nক\nর\nা\nয\nন\nা\n \nচ\nা\nহ\nি\n।\nস\nো\nউ\nব\nম\n \nল\nে\nব\nু\n \nক\nি\nয\nা\nঽ\n \nগ\nৈ\nর\nৱ\n \nও\nড\nো\nঽ\n \nধ\nি\nক\nা\nর\nা\nঽ\n \nম\nা\nস\nন\n \nব\nু\nঁ\nগ\n \nজ\nো\nন\nো\nম\n-\nজ\nা\nত\n \nস\nৱ\nত\nন\nত\nর\nত\nা\n \nও\nড\nো\nঽ\n \nস\nম\nা\nন\nত\nা\n \nক\nু\nঈ\n \nস\nি\nড\n \nহ\nো\nত\nো\nক\nে\n \nল\nু\nর\n \nও\nড\nো\nঽ\n \nজ\nা\nত\nো\nম\nা\nঽ\n \nত\nে\nর\n \nত\nে\nর\n \nক\nু\nঈ\n \nস\nি\nঽ\n \nও\nড\nো\nঽ\n \nম\nু\nন\nু\nড\nূ\n \nহ\nো\nক\nী\n \nত\nে\n \nভ\nা\nঈ\n-\nভ"
}
