id: "khr_Deva"
language: "khr"
script: "Deva"
name: "Kharia, Devanagari"
region: "IN"
sample_text {
  masthead_full: "सउबम"
  masthead_partial: "लक"
  styles: "सोउब्म लेबु कियाऽ गैरव ओडोऽ अधिकाराऽ मासन बुँग जोनोमजात स्वतंत्रता"
  tester: "सोउब्म लेबु कियाऽ गैरव ओडोऽ अधिकाराऽ मासन बुँग जोनोमजात स्वतंत्रता ओडोऽ समानता कुई सिड"
  poster_sm: "सोउब्म लेबु कियाऽ"
  poster_md: "सोउब्म लेबु क"
  poster_lg: "सोउब्म"
  specimen_48: "सोउब्म लेबु कियाऽ गैरव ओडोऽ अधिकाराऽ मासन बुँग जोनोमजात स्वतंत्रता ओडोऽ समानता कुई सिड होतोके"
  specimen_36: "सोउब्म लेबु कियाऽ गैरव ओडोऽ अधिकाराऽ मासन बुँग जोनोमजात स्वतंत्रता ओडोऽ समानता कुई सिड होतोके लुर ओडोऽ जातोमाऽ तेर तेर कुई सिऽ ओडोऽ मुनुडू होकी ते भाईभाई मुन व्यवहार करायना चाहि।"
  specimen_32: "सोउब्म लेबु कियाऽ गैरव ओडोऽ अधिकाराऽ मासन बुँग जोनोमजात स्वतंत्रता ओडोऽ समानता कुई सिड होतोके लुर ओडोऽ जातोमाऽ तेर तेर कुई सिऽ ओडोऽ मुनुडू होकी ते भाईभाई मुन व्यवहार करायना चाहि।"
  specimen_21: "सोउब्म लेबु कियाऽ गैरव ओडोऽ अधिकाराऽ मासन बुँग जोनोमजात स्वतंत्रता ओडोऽ समानता कुई सिड होतोके लुर ओडोऽ जातोमाऽ तेर तेर कुई सिऽ ओडोऽ मुनुडू होकी ते भाईभाई मुन व्यवहार करायना चाहि।\nसोउब्म लेबु कियाऽ गैरव ओडोऽ अधिकाराऽ मासन बुँग जोनोमजात स्वतंत्रता ओडोऽ समानता कुई सिड होतोके लुर ओडोऽ जातोमाऽ तेर तेर कुई सिऽ ओडोऽ मुनुडू होकी ते भाईभाई मुन व्यवहार करायना चाहि।\nसोउब्म लेबु कियाऽ गैरव ओडोऽ अधिकाराऽ मासन बुँग जोनोमजात स्वतंत्रता ओडोऽ समानता कुई सिड होतोके लुर ओडोऽ जातोमाऽ तेर तेर कुई सिऽ ओडोऽ मुनुडू होकी ते भाईभाई मुन व्यवहार करायना चाहि।"
  specimen_16: "सोउब्म लेबु कियाऽ गैरव ओडोऽ अधिकाराऽ मासन बुँग जोनोमजात स्वतंत्रता ओडोऽ समानता कुई सिड होतोके लुर ओडोऽ जातोमाऽ तेर तेर कुई सिऽ ओडोऽ मुनुडू होकी ते भाईभाई मुन व्यवहार करायना चाहि।\nसोउब्म लेबु कियाऽ गैरव ओडोऽ अधिकाराऽ मासन बुँग जोनोमजात स्वतंत्रता ओडोऽ समानता कुई सिड होतोके लुर ओडोऽ जातोमाऽ तेर तेर कुई सिऽ ओडोऽ मुनुडू होकी ते भाईभाई मुन व्यवहार करायना चाहि।\nसोउब्म लेबु कियाऽ गैरव ओडोऽ अधिकाराऽ मासन बुँग जोनोमजात स्वतंत्रता ओडोऽ समानता कुई सिड होतोके लुर ओडोऽ जातोमाऽ तेर तेर कुई सिऽ ओडोऽ मुनुडू होकी ते भाईभाई मुन व्यवहार करायना चाहि।\nसोउब्म लेबु कियाऽ गैरव ओडोऽ अधिकाराऽ मासन बुँग जोनोमजात स्वतंत्रता ओडोऽ समानता कुई सिड होतोके लुर ओडोऽ जातोमाऽ तेर तेर कुई सिऽ ओडोऽ मुनुडू होकी ते भाईभाई मुन व्यवहार करायना चाहि।\nसोउब्म लेबु कियाऽ गैरव ओडोऽ अधिकाराऽ मासन बुँग जोनोमजात स्वतंत्रता ओडोऽ समानता कुई सिड होतोके लुर ओडोऽ जातोमाऽ तेर तेर कुई सिऽ ओडोऽ मुनुडू होकी ते भाईभाई मुन व्यवहार करायना चाहि।"
}
