id: "khr_Orya"
language: "khr"
script: "Orya"
name: "Kharia, Odia"
sample_text {
  masthead_full: "ସଉବମ"
  masthead_partial: "ଲକ"
  styles: "ସ\nୋ\nଉ\nବ\nମ\n \nଲ\nେ\nବ\nୁ\n \nକ\nି\nୟ\nା\nଽ\n \nଗ\nୈ\nର\nୱ\n \nଓ\nଡ"
  tester: "ସ\nୋ\nଉ\nବ\nମ\n \nଲ\nେ\nବ\nୁ\n \nକ\nି\nୟ\nା\nଽ\n \nଗ\nୈ\nର\nୱ\n \nଓ\nଡ\nୋ\nଽ\n \nଅ\nଧ\nି\nକ\nା\nର\nା\nଽ\n "
  poster_sm: "ସ\nୋ\nଉ\nବ\nମ\n "
  poster_md: "ସ\nୋ\nଉ\nବ\nମ"
  poster_lg: "ସ\nୋ\nଉ"
  specimen_48: "ସ\nୋ\nଉ\nବ\nମ\n \nଲ\nେ\nବ\nୁ\n \nକ\nି\nୟ\nା\nଽ\n \nଗ\nୈ\nର\nୱ\n \nଓ\nଡ\nୋ\nଽ\n \nଅ\nଧ\nି\nକ\nା\nର\nା\nଽ\n "
  specimen_36: "ସ\nୋ\nଉ\nବ\nମ\n \nଲ\nେ\nବ\nୁ\n \nକ\nି\nୟ\nା\nଽ\n \nଗ\nୈ\nର\nୱ\n \nଓ\nଡ\nୋ\nଽ\n \nଅ\nଧ\nି\nକ\nା\nର\nା\nଽ\n \nମ\nା\nସ\nନ\n \nବ\nୁ\nଁ\nଗ\n \nଜ\nୋ\nନ\nୋ\nମ\n-\nଜ\nା\nତ\n \nସ\nୱ\nତ"
  specimen_32: "ସ\nୋ\nଉ\nବ\nମ\n \nଲ\nେ\nବ\nୁ\n \nକ\nି\nୟ\nା\nଽ\n \nଗ\nୈ\nର\nୱ\n \nଓ\nଡ\nୋ\nଽ\n \nଅ\nଧ\nି\nକ\nା\nର\nା\nଽ\n \nମ\nା\nସ\nନ\n \nବ\nୁ\nଁ\nଗ\n \nଜ\nୋ\nନ\nୋ\nମ\n-\nଜ\nା\nତ\n \nସ\nୱ\nତ\nନ\nତ\nର\nତ\nା\n \nଓ\nଡ\nୋ\nଽ\n \nସ\nମ\nା\nନ\nତ\nା\n \nକ\nୁ\nଈ\n \nସ"
  specimen_21: "ସ\nୋ\nଉ\nବ\nମ\n \nଲ\nେ\nବ\nୁ\n \nକ\nି\nୟ\nା\nଽ\n \nଗ\nୈ\nର\nୱ\n \nଓ\nଡ\nୋ\nଽ\n \nଅ\nଧ\nି\nକ\nା\nର\nା\nଽ\n \nମ\nା\nସ\nନ\n \nବ\nୁ\nଁ\nଗ\n \nଜ\nୋ\nନ\nୋ\nମ\n-\nଜ\nା\nତ\n \nସ\nୱ\nତ\nନ\nତ\nର\nତ\nା\n \nଓ\nଡ\nୋ\nଽ\n \nସ\nମ\nା\nନ\nତ\nା\n \nକ\nୁ\nଈ\n \nସ\nି\nଡ\n \nହ\nୋ\nତ\nୋ\nକ\nେ\n \nଲ\nୁ\nର\n \nଓ\nଡ\nୋ\nଽ\n \nଜ\nା\nତ\nୋ\nମ\nା\nଽ\n \nତ\nେ\nର\n \nତ\nେ\nର\n \nକ\nୁ\nଈ\n \nସ\nି\nଽ\n \nଓ\nଡ\nୋ\nଽ\n \nମ\nୁ\nନ\nୁ\nଡ\nୂ\n \nହ\nୋ\nକ\nୀ\n \nତ\nେ\n \nଵ\nା\nଈ\n-\nଵ\nା\nଈ\n \nମ\nୁ\nନ\n \nୱ\nୟ\nୱ\nହ\nା\nର\n \nକ\nର\nା\nୟ\nନ\nା\n \nଚ\nା\nହ\nି\n‍\n।"
  specimen_16: "ସ\nୋ\nଉ\nବ\nମ\n \nଲ\nେ\nବ\nୁ\n \nକ\nି\nୟ\nା\nଽ\n \nଗ\nୈ\nର\nୱ\n \nଓ\nଡ\nୋ\nଽ\n \nଅ\nଧ\nି\nକ\nା\nର\nା\nଽ\n \nମ\nା\nସ\nନ\n \nବ\nୁ\nଁ\nଗ\n \nଜ\nୋ\nନ\nୋ\nମ\n-\nଜ\nା\nତ\n \nସ\nୱ\nତ\nନ\nତ\nର\nତ\nା\n \nଓ\nଡ\nୋ\nଽ\n \nସ\nମ\nା\nନ\nତ\nା\n \nକ\nୁ\nଈ\n \nସ\nି\nଡ\n \nହ\nୋ\nତ\nୋ\nକ\nେ\n \nଲ\nୁ\nର\n \nଓ\nଡ\nୋ\nଽ\n \nଜ\nା\nତ\nୋ\nମ\nା\nଽ\n \nତ\nେ\nର\n \nତ\nେ\nର\n \nକ\nୁ\nଈ\n \nସ\nି\nଽ\n \nଓ\nଡ\nୋ\nଽ\n \nମ\nୁ\nନ\nୁ\nଡ\nୂ\n \nହ\nୋ\nକ\nୀ\n \nତ\nେ\n \nଵ\nା\nଈ\n-\nଵ\nା\nଈ\n \nମ\nୁ\nନ\n \nୱ\nୟ\nୱ\nହ\nା\nର\n \nକ\nର\nା\nୟ\nନ\nା\n \nଚ\nା\nହ\nି\n‍\n।\nସ\nୋ\nଉ\nବ\nମ\n \nଲ\nେ\nବ\nୁ\n \nକ\nି\nୟ\nା\nଽ\n \nଗ\nୈ\nର\nୱ\n \nଓ\nଡ\nୋ\nଽ\n \nଅ\nଧ\nି\nକ\nା\nର\nା\nଽ\n \nମ\nା\nସ\nନ\n \nବ\nୁ\nଁ\nଗ\n \nଜ\nୋ\nନ\nୋ\nମ\n-\nଜ\nା\nତ\n \nସ\nୱ\nତ\nନ\nତ\nର\nତ\nା\n \nଓ\nଡ\nୋ\nଽ\n \nସ\nମ\nା\nନ\nତ\nା\n \nକ\nୁ\nଈ\n \nସ\nି\nଡ\n \nହ\nୋ\nତ\nୋ\nକ\nେ\n \nଲ\nୁ\nର\n \nଓ\nଡ\nୋ\nଽ\n \nଜ\nା\nତ\nୋ\nମ\nା\nଽ\n \nତ\nେ\nର\n \nତ\nେ\nର\n \nକ\nୁ\nଈ\n \nସ\nି\nଽ\n \nଓ\nଡ\nୋ\nଽ\n \nମ\nୁ\nନ\nୁ\nଡ\nୂ\n \nହ\nୋ\nକ\nୀ\n \nତ\nେ\n \nଵ"
}
