id: "khr_Deva"
language: "khr"
script: "Deva"
name: "Kharia, Devanagari"
sample_text {
  masthead_full: "सउबम"
  masthead_partial: "लक"
  styles: "स\nो\nउ\nब\n्\nम\n \nल\nे\nब\nु\n \nक\nि\nय\nा\nऽ\n \nग\nै\nर\nव\n \nओ"
  tester: "स\nो\nउ\nब\n्\nम\n \nल\nे\nब\nु\n \nक\nि\nय\nा\nऽ\n \nग\nै\nर\nव\n \nओ\nड\nो\nऽ\n \nअ\nध\nि\nक\nा\nर\nा\nऽ"
  poster_sm: "स\nो\nउ\nब\n्\nम\n "
  poster_md: "स\nो\nउ\nब\n्\nम"
  poster_lg: "स\nो\nउ"
  specimen_48: "स\nो\nउ\nब\n्\nम\n \nल\nे\nब\nु\n \nक\nि\nय\nा\nऽ\n \nग\nै\nर\nव\n \nओ\nड\nो\nऽ\n \nअ\nध\nि\nक\nा\nर\nा\nऽ"
  specimen_36: "स\nो\nउ\nब\n्\nम\n \nल\nे\nब\nु\n \nक\nि\nय\nा\nऽ\n \nग\nै\nर\nव\n \nओ\nड\nो\nऽ\n \nअ\nध\nि\nक\nा\nर\nा\nऽ\n \nम\nा\nस\nन\n \nब\nु\nँ\nग\n \nज\nो\nन\nो\nम\n-\nज\nा\nत\n \nस\n्\nव"
  specimen_32: "स\nो\nउ\nब\n्\nम\n \nल\nे\nब\nु\n \nक\nि\nय\nा\nऽ\n \nग\nै\nर\nव\n \nओ\nड\nो\nऽ\n \nअ\nध\nि\nक\nा\nर\nा\nऽ\n \nम\nा\nस\nन\n \nब\nु\nँ\nग\n \nज\nो\nन\nो\nम\n-\nज\nा\nत\n \nस\n्\nव\nत\nं\nत\n्\nर\nत\nा\n \nओ\nड\nो\nऽ\n \nस\nम\nा\nन\nत\nा\n \nक\nु\nई\n "
  specimen_21: "स\nो\nउ\nब\n्\nम\n \nल\nे\nब\nु\n \nक\nि\nय\nा\nऽ\n \nग\nै\nर\nव\n \nओ\nड\nो\nऽ\n \nअ\nध\nि\nक\nा\nर\nा\nऽ\n \nम\nा\nस\nन\n \nब\nु\nँ\nग\n \nज\nो\nन\nो\nम\n-\nज\nा\nत\n \nस\n्\nव\nत\nं\nत\n्\nर\nत\nा\n \nओ\nड\nो\nऽ\n \nस\nम\nा\nन\nत\nा\n \nक\nु\nई\n \nस\nि\nड\n \nह\nो\nत\nो\nक\nे\n \nल\nु\nर\n \nओ\nड\nो\nऽ\n \nज\nा\nत\nो\nम\nा\nऽ\n \nत\nे\nर\n \nत\nे\nर\n \nक\nु\nई\n \nस\nि\nऽ\n \nओ\nड\nो\nऽ\n \nम\nु\nन\nु\nड\nू\n \nह\nो\nक\nी\n \nत\nे\n \nभ\nा\nई\n-\nभ\nा\nई\n \nम\nु\nन\n \nव\n्\nय\nव\nह\nा\nर\n \nक\nर\nा\nय\nन\nा\n \nच\nा\nह"
  specimen_16: "स\nो\nउ\nब\n्\nम\n \nल\nे\nब\nु\n \nक\nि\nय\nा\nऽ\n \nग\nै\nर\nव\n \nओ\nड\nो\nऽ\n \nअ\nध\nि\nक\nा\nर\nा\nऽ\n \nम\nा\nस\nन\n \nब\nु\nँ\nग\n \nज\nो\nन\nो\nम\n-\nज\nा\nत\n \nस\n्\nव\nत\nं\nत\n्\nर\nत\nा\n \nओ\nड\nो\nऽ\n \nस\nम\nा\nन\nत\nा\n \nक\nु\nई\n \nस\nि\nड\n \nह\nो\nत\nो\nक\nे\n \nल\nु\nर\n \nओ\nड\nो\nऽ\n \nज\nा\nत\nो\nम\nा\nऽ\n \nत\nे\nर\n \nत\nे\nर\n \nक\nु\nई\n \nस\nि\nऽ\n \nओ\nड\nो\nऽ\n \nम\nु\nन\nु\nड\nू\n \nह\nो\nक\nी\n \nत\nे\n \nभ\nा\nई\n-\nभ\nा\nई\n \nम\nु\nन\n \nव\n्\nय\nव\nह\nा\nर\n \nक\nर\nा\nय\nन\nा\n \nच\nा\nह\nि\n।\nस\nो\nउ\nब\n्\nम\n \nल\nे\nब\nु\n \nक\nि\nय\nा\nऽ\n \nग\nै\nर\nव\n \nओ\nड\nो\nऽ\n \nअ\nध\nि\nक\nा\nर\nा\nऽ\n \nम\nा\nस\nन\n \nब\nु\nँ\nग\n \nज\nो\nन\nो\nम\n-\nज\nा\nत\n \nस\n्\nव\nत\nं\nत\n्\nर\nत\nा\n \nओ\nड\nो\nऽ\n \nस\nम\nा\nन\nत\nा\n \nक\nु\nई\n \nस\nि\nड\n \nह\nो\nत\nो\nक\nे\n \nल\nु\nर\n \nओ\nड\nो\nऽ\n \nज\nा\nत\nो\nम\nा\nऽ\n \nत\nे\nर\n \nत\nे\nर\n \nक\nु\nई\n \nस\nि\nऽ\n \nओ\nड\nो\nऽ\n \nम\nु\nन\nु\nड\nू\n \nह\nो\nक\nी\n \nत\nे"
}
