id: "khw_Arab"
language: "khw"
script: "Arab"
name: "Khowar"
population: 350251
region: "PK"
sample_text {
  masthead_full: "سفان"
  masthead_partial: "آز"
  styles: "سف انسان آزاد وا حقوق اوچے عزتو اعتبارو سورا"
  tester: "سف انسان آزاد وا حقوق اوچے عزتو اعتبارو سورا برابار پیدا بیتی"
  poster_sm: "سف انسان آزاد"
  poster_md: "سف انسان"
  poster_lg: "انسان"
  specimen_48: "سف انسان آزاد وا حقوق اوچے عزتو اعتبارو سورا برابار"
  specimen_36: "سف انسان آزاد وا حقوق اوچے عزتو اعتبارو سورا برابار پیدا بیتی آسونی، ھیتانتے ضمیر اوچے عقل عطا کورونو بیتی شیر، ھے بچین ھیتان تان موژی برارگاریو سلوکو کوریلک۔ کھوار ترجمہ: رحمت عزیز چترالی"
  specimen_32: "سف انسان آزاد وا حقوق اوچے عزتو اعتبارو سورا برابار پیدا بیتی آسونی، ھیتانتے ضمیر اوچے عقل عطا کورونو بیتی شیر، ھے بچین ھیتان تان موژی برارگاریو سلوکو کوریلک۔ کھوار ترجمہ: رحمت عزیز چترالی"
  specimen_21: "سف انسان آزاد وا حقوق اوچے عزتو اعتبارو سورا برابار پیدا بیتی آسونی، ھیتانتے ضمیر اوچے عقل عطا کورونو بیتی شیر، ھے بچین ھیتان تان موژی برارگاریو سلوکو کوریلک۔ کھوار ترجمہ: رحمت عزیز چترالی\nسف انسان آزاد وا حقوق اوچے عزتو اعتبارو سورا برابار پیدا بیتی آسونی، ھیتانتے ضمیر اوچے عقل عطا کورونو بیتی شیر، ھے بچین ھیتان تان موژی برارگاریو سلوکو کوریلک۔ کھوار ترجمہ: رحمت عزیز چترالی"
  specimen_16: "سف انسان آزاد وا حقوق اوچے عزتو اعتبارو سورا برابار پیدا بیتی آسونی، ھیتانتے ضمیر اوچے عقل عطا کورونو بیتی شیر، ھے بچین ھیتان تان موژی برارگاریو سلوکو کوریلک۔ کھوار ترجمہ: رحمت عزیز چترالی\nسف انسان آزاد وا حقوق اوچے عزتو اعتبارو سورا برابار پیدا بیتی آسونی، ھیتانتے ضمیر اوچے عقل عطا کورونو بیتی شیر، ھے بچین ھیتان تان موژی برارگاریو سلوکو کوریلک۔ کھوار ترجمہ: رحمت عزیز چترالی\nسف انسان آزاد وا حقوق اوچے عزتو اعتبارو سورا برابار پیدا بیتی آسونی، ھیتانتے ضمیر اوچے عقل عطا کورونو بیتی شیر، ھے بچین ھیتان تان موژی برارگاریو سلوکو کوریلک۔ کھوار ترجمہ: رحمت عزیز چترالی"
}
