id: "khw_Latn"
language: "khw"
script: "Latn"
name: "Khowar, Latin"
sample_text {
  masthead_full: "SsAa"
  masthead_partial: "Ff"
  styles: "S\na\nf\n \ni\nn\ns\nā\nn\n \nā\nz\nā\nd\n \nw\na\n \nḥ\nu\nq"
  tester: "S\na\nf\n \ni\nn\ns\nā\nn\n \nā\nz\nā\nd\n \nw\na\n \nḥ\nu\nq\nū\nq\n-\no\nc\nh\na\ny\n \ni"
  poster_sm: "S\na\nf\n \ni\nn"
  poster_md: "S\na\nf\n \ni"
  poster_lg: "S\na"
  specimen_48: "S\na\nf\n \ni\nn\ns\nā\nn\n \nā\nz\nā\nd\n \nw\na\n \nḥ\nu\nq\nū\nq\n-\no\nc\nh\na\ny\n \ni"
  specimen_36: "S\na\nf\n \ni\nn\ns\nā\nn\n \nā\nz\nā\nd\n \nw\na\n \nḥ\nu\nq\nū\nq\n-\no\nc\nh\na\ny\n \ni\nz\nz\na\nt\no\n \nė\nʿ\nt\ni\nb\nā\nr\no\n \ns\no\nr\na\n "
  specimen_32: "S\na\nf\n \ni\nn\ns\nā\nn\n \nā\nz\nā\nd\n \nw\na\n \nḥ\nu\nq\nū\nq\n-\no\nc\nh\na\ny\n \ni\nz\nz\na\nt\no\n \nė\nʿ\nt\ni\nb\nā\nr\no\n \ns\no\nr\na\n \nb\na\nr\nā\nb\na\na\nr\n \np\na\ni\nd\nā\n \nb\ni\nt\ni\n "
  specimen_21: "S\na\nf\n \ni\nn\ns\nā\nn\n \nā\nz\nā\nd\n \nw\na\n \nḥ\nu\nq\nū\nq\n-\no\nc\nh\na\ny\n \ni\nz\nz\na\nt\no\n \nė\nʿ\nt\ni\nb\nā\nr\no\n \ns\no\nr\na\n \nb\na\nr\nā\nb\na\na\nr\n \np\na\ni\nd\nā\n \nb\ni\nt\ni\n \na\ns\nu\nn\ni\n.\n \nh\ne\nt\na\nn\nt\ne\ny\n \nż\na\nm\nī\nr\n \nô\nc\nh\na\ny\n \nʿ\na\nq\nl\n \na\nt\na\na\n \nk\no\nr\no\nn\nu\n \nb\ni\nt\ni\n \ns\nh\ne\nr\n.\n \nH\ne\ny\n \nb\na\nc\nh\ne\nn\n \nh\ne\nt\na\nn\n \nt\na\na\nn\n \nm\nu\nz"
  specimen_16: "S\na\nf\n \ni\nn\ns\nā\nn\n \nā\nz\nā\nd\n \nw\na\n \nḥ\nu\nq\nū\nq\n-\no\nc\nh\na\ny\n \ni\nz\nz\na\nt\no\n \nė\nʿ\nt\ni\nb\nā\nr\no\n \ns\no\nr\na\n \nb\na\nr\nā\nb\na\na\nr\n \np\na\ni\nd\nā\n \nb\ni\nt\ni\n \na\ns\nu\nn\ni\n.\n \nh\ne\nt\na\nn\nt\ne\ny\n \nż\na\nm\nī\nr\n \nô\nc\nh\na\ny\n \nʿ\na\nq\nl\n \na\nt\na\na\n \nk\no\nr\no\nn\nu\n \nb\ni\nt\ni\n \ns\nh\ne\nr\n.\n \nH\ne\ny\n \nb\na\nc\nh\ne\nn\n \nh\ne\nt\na\nn\n \nt\na\na\nn\n \nm\nu\nz\nh\ni\n \nb\nr\na\nr\n \ng\na\nr\ni\ny\no\n \ns\nu\nl\nū\nk\n \nk\no\nr\ne\nl\ni\nk\n.\nS\na\nf\n \ni\nn\ns\nā\nn\n \nā\nz\nā\nd\n \nw\na\n \nḥ\nu\nq\nū\nq\n-\no\nc\nh\na\ny\n \ni\nz\nz\na\nt\no\n \nė\nʿ\nt\ni\nb\nā\nr\no\n \ns\no\nr\na\n \nb\na\nr\nā\nb\na\na\nr\n \np\na\ni\nd\nā\n \nb\ni\nt\ni\n \na\ns\nu\nn\ni\n.\n \nh\ne\nt\na\nn\nt\ne\ny\n \nż\na\nm\nī\nr\n \nô\nc\nh\na\ny"
}
