id: "ki"
language: "ki"
script: "Latn"
name: "Kikuyu"
autonym: "Gĩgĩkũyũ"
population: 9099743
region: "KE"
exemplar_chars {
  base: "a b c d e g h i ĩ j k m n o r t u ũ w y"
  auxiliary: "f l p q s v x z"
  marks: "◌̃"
  index: "A B C D E G H I J K M N O R T U W Y"
}
sample_text {
  fallback_language: "en"
}
