id: "kk"
language: "kk"
script: "Cyrl"
name: "Kazakh"
autonym: "Қазақ тілі"
population: 12219390
region: "KZ"
region: "TR"
exemplar_chars {
  base: "а ә б в г ғ д е ё ж з и й к қ л м н ң о ө п р с т у ұ ү ф х һ ц ч ш щ ъ ы і ь э ю я"
  auxiliary: ""
  marks: "◌̆ ◌̈"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ \" “ ” « » ( ) [ ] { } § @ * / & # { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "А Ә Б В Г Ғ Д Е Ё Ж З И Й К Қ Л М Н Ң О Ө П Р С Т У Ұ Ү Ф Х Һ Ц Ч Ш Щ Ъ Ы І Ь Э Ю Я"
}
sample_text {
  masthead_full: "БбАа"
  masthead_partial: "Рр"
  styles: "Адам баласы үйелменінің барлық мүшелеріне"
  tester: "адам құқықтарына деген елемеушілік, менсінбеушілік адам баласы"
  poster_sm: "адам баласы"
  poster_md: "халықтар"
  poster_lg: "Барлық"
  specimen_48: "БіріккенҰлттар елдері өз Жарғысында негізгі адам құқықтарына,"
  specimen_36: "Ешкім де құлдықта немесе кіріптарлықта ұсталуы тиіс емес. Құлдық пен құл саудасына, қандай түрде болса да, тыйым салынады."
  specimen_32: "Әр адам, конституциямен, немесе заңмен берілген негізгі құқықтары бұзылған жағдайда, құқығын құзыретті ұлттық сот арқылы тиімді түрде қалпына келтіруге құқылы."
  specimen_21: "Ешкім де негізсіз тұтқындалуға, қамауда ұсталуға немесе қуғынға ұшыратылуға тиіс емес.\nӘр адам, өзінің құқықтары мен міндеттерін анықтап, өзіне тағылған қылмыстық айыптаудың негізділігін белгілеу үшін, ісі толық теңдік негізінде, әділеттік талаптарға сай, тәуелсіз және әділ сот арқылы ашық қаралуына құқығы бар."
  specimen_16: "Әр адам жеке және отбасылық өміріне өзгелердің өз бетінше араласуынан, озбырлық жасап баспанасына, хат жазысып‐алысу құпиясына қол сұғуынан, ар‐намысы мен абырой беделіне нұқсан келтіруінен қорғалуға құқығы бар.\nӘр адам ой‐пікір, ар‐ождан және дін бостандығына құқығы бар; бұл құқық өз дінін немесе наным‐сенімін өзгерту еркіндігін, өз дінін, наным‐сенімін жеке өзі, немесе басқа адамдармен бірігіп тұтып, жария түрде, немесе жеке жолмен уағыздау, құдайға құлшылық ету, діни салт‐жораларын орындау бостандығын да қамтыйды.\nӘр адам тынығуға және мәдени демалуға, оның ішінде ақылға қонымды шектеулі жұмыс күніне және мерзімді ақылы демалысқа, кұқылы."
}
