id: "kk_Arab"
language: "kk"
script: "Arab"
name: "Kazakh (Arabic)"
population: 1418002
region: "AF"
region: "CN"
region: "IR"
region: "MN"
sample_text {
  masthead_full: "بارل"
  masthead_partial: "ىق"
  styles: "ب\nا\nر\nل\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nت\nۋ\nم\nى\nس\nى"
  tester: "ب\nا\nر\nل\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nت\nۋ\nم\nى\nس\nى\nن\nا\nن\n \nا\nز\nا\nت\n \nج"
  poster_sm: "ب\nا\nر\nل\nى\nق"
  poster_md: "ب\nا\nر\nل\nى"
  poster_lg: "ب\nا"
  specimen_48: "ب\nا\nر\nل\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nت\nۋ\nم\nى\nس\nى\nن\nا\nن\n \nا\nز\nا\nت\n \nج"
  specimen_36: "ب\nا\nر\nل\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nت\nۋ\nم\nى\nس\nى\nن\nا\nن\n \nا\nز\nا\nت\n \nج\nا\nن\nە\n \nق\nا\nد\nى\nر\n‐\nق\nا\nس\nى\nي\nي\nە\nت\nى\n "
  specimen_32: "ب\nا\nر\nل\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nت\nۋ\nم\nى\nس\nى\nن\nا\nن\n \nا\nز\nا\nت\n \nج\nا\nن\nە\n \nق\nا\nد\nى\nر\n‐\nق\nا\nس\nى\nي\nي\nە\nت\nى\n \nم\nە\nن\n \nك\nۇ\nق\nى\nق\nت\nا\nر\nى\n \nت\nە\nڭ\n \nب\nو"
  specimen_21: "ب\nا\nر\nل\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nت\nۋ\nم\nى\nس\nى\nن\nا\nن\n \nا\nز\nا\nت\n \nج\nا\nن\nە\n \nق\nا\nد\nى\nر\n‐\nق\nا\nس\nى\nي\nي\nە\nت\nى\n \nم\nە\nن\n \nك\nۇ\nق\nى\nق\nت\nا\nر\nى\n \nت\nە\nڭ\n \nب\nو\nل\nى\nپ\n \nد\nۇ\nن\nى\nي\nي\nە\nگ\nە\n \nك\nە\nل\nە\nد\nى\n.\n \nا\nد\nا\nم\nد\nا\nر\nع\nا\n \nا\nق\nى\nل\n‐\nپ\nا\nر\nا\nس\nا\nت\n،\n \nا\nر\n‐\nو\nج\nد\nا\nن\n \nب\nە\nر\nى\nل\nگ\nە\nن\n،\n \nس\nو\nن\nد\nى\nق\nت\nا\nن\n \nو\nل\nا\nر\n \nب\nى\nر"
  specimen_16: "ب\nا\nر\nل\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nت\nۋ\nم\nى\nس\nى\nن\nا\nن\n \nا\nز\nا\nت\n \nج\nا\nن\nە\n \nق\nا\nد\nى\nر\n‐\nق\nا\nس\nى\nي\nي\nە\nت\nى\n \nم\nە\nن\n \nك\nۇ\nق\nى\nق\nت\nا\nر\nى\n \nت\nە\nڭ\n \nب\nو\nل\nى\nپ\n \nد\nۇ\nن\nى\nي\nي\nە\nگ\nە\n \nك\nە\nل\nە\nد\nى\n.\n \nا\nد\nا\nم\nد\nا\nر\nع\nا\n \nا\nق\nى\nل\n‐\nپ\nا\nر\nا\nس\nا\nت\n،\n \nا\nر\n‐\nو\nج\nد\nا\nن\n \nب\nە\nر\nى\nل\nگ\nە\nن\n،\n \nس\nو\nن\nد\nى\nق\nت\nا\nن\n \nو\nل\nا\nر\n \nب\nى\nر\n‐\nب\nى\nر\nى\nم\nە\nن\n \nت\nۋ\nى\nس\nت\nى\nق\n،\n \nب\nا\nۋ\nى\nر\nم\nا\nل\nد\nى\nق\n \nق\nا\nر\nى\nم\n‐\nق\nا\nت\nى\nن\nا\nس\n \nج\nا\nس\nا\nۋ\nل\nا\nر\nى\n \nٴ\nت\nى\nي\nى\nس\n.\nب\nا\nر\nل\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nت\nۋ\nم\nى\nس\nى\nن\nا\nن\n \nا\nز\nا\nت\n \nج\nا\nن\nە\n \nق\nا\nد\nى\nر\n‐\nق\nا\nس\nى\nي\nي\nە\nت\nى\n \nم\nە\nن\n \nك\nۇ\nق\nى\nق\nت\nا\nر\nى\n \nت"
}
