id: "kkj"
name: "Kako"
preferred_name: ""
autonym: "Kakɔ"
population: 149823
region: "CM"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P R S T U V W Y À Á Â È É Ê Ì Í Î Ò Ó Ô Ù Ú Û Ŋ Ǌ Ɓ Ɔ Ɗ Ɛ a b c d e f g h i j k l m n o p r s t u v w y à á â è é ê ì í î ò ó ô ù ú û ŋ ǌ ɓ ɔ ɗ ɛ"
  auxiliary: "Q X Z q x z"
  marks: "◌̀ ◌́ ◌̂ ◌̧"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: ", \\: ! ? . … ‘ ‹ › “ ” « » ( ) *"
  index: "A B Ɓ C D Ɗ {Ɗy} E Ɛ F G {Gb} {Gw} H I {I\\u0327} J K {Kp} {Kw} L M {Mb} N {Nd} ǋ {Ny} Ŋ {Ŋg} {Ŋgb} {Ŋgw} O Ɔ {Ɔ\\u0327} P R S T U {U\\u0327} V W Y"
}
sample_text {
  fallback_language: "en"
}
