id: "kln"
language: "kln"
script: "Latn"
name: "Kalenjin"
autonym: "Markweta"
population: 4068120
region: "KE"
exemplar_chars {
  base: "a b c d e g h i j k l m n o p r s t u w y"
  auxiliary: "f q v x z"
  index: "A B C D E G H I J K L M N O P R S T U W Y"
}
sample_text {
  fallback_language: "en"
}
