id: "km"
language: "km"
script: "Khmr"
name: "Khmer"
autonym: "ភាសាខ្មែរ"
population: 15065030
region: "KH"
exemplar_chars {
  base: "័ ៈ ់ ៉ ៊ ៍ ក ខ គ ឃ ង ច ឆ ជ ឈ ញ ដ ឋ ឌ ឍ ណ ត ថ ទ ធ ន ប ផ ព ភ ម យ រ ឫ ឬ ល ឭ ឮ វ ស ហ ឡ អ {អា} ឥ ឦ ឧ {ឧក} ឩ ឪ ឯ ឰ ឱ ឲ ឳ ា ិ ី ឹ ឺ ុ ូ ួ ើ ឿ ៀ េ ែ ៃ ោ ៅ ំ ះ ្ {អា} {ឧក} {អា} {ឧក} {អា} {ឧក} {អា} {ឧក} {អា} {ឧក} {អា} {ឧក} {អា} {ឧក} {អា} {ឧក} {អា} {ឧក} {អា} {ឧក} {អា} {ឧក} {អា} {ឧក} {អា} {ឧក} {អា} {ឧក} {អា} {ឧក}"
  auxiliary: "឴឵​ ៌ ៎ ៏ ៑ ឝ ឞ"
  marks: "◌឴ ◌឵ ◌ា ◌ិ ◌ី ◌ឹ ◌ឺ ◌ុ ◌ូ ◌ួ ◌ើ ◌ឿ ◌ៀ ◌េ ◌ែ ◌ៃ ◌ោ ◌ៅ ◌ំ ◌ះ ◌ៈ ◌៉ ◌៊ ◌់ ◌៍ ◌័ ◌្"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‑ , ៖ ! ? . ។ ៕ ‘ ’ \" “ ” ( ) [ ] { } ៙ ៚ { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "ក ខ គ ឃ ង ច ឆ ជ ឈ ញ ដ ឋ ឌ ឍ ណ ត ថ ទ ធ ន ប ផ ព ភ ម យ រ ឫ ឬ ល ឭ ឮ វ ស ហ ឡ អ ឥ ឦ ឧ ឩ ឪ ឯ ឰ ឱ ឳ"
}
sample_text {
  masthead_full: "មនសទ"
  masthead_partial: "ងអ"
  styles: "ដោយយល់ឃើញថា ការទទួលស្គាល់សេចក្ដីថ្លៃថ្នូរជាប់ពីកំណើត និងសិទ្ធិស្មើភាពគ្នា"
  tester: "ដោយយល់ឃើញថា ការមិនទទួលស្គាល់ និងការប្រមាថមើលងាយសិទ្ធិមនុស្ស នាំឱ្យមានអំពើ ព្រៃផ្សៃសាហាវយង់ឃ្នង ធ្វើឱ្យក្ដៅក្រហាយដល់សតិសម្បជញ្ញៈមនុស្សជាតិ"
  poster_sm: "ដោយយល់ឃើញថា ជាការចាំបាច់"
  poster_md: "មនុស្សទាំងអស់"
  poster_lg: "មនុស្សទាំងអស់"
  specimen_48: "មនុស្សម្នាក់ៗ អាចប្រើប្រាស់សិទ្ធិនិងសេរីភាពទាំងអស់ ដែលមានចែងក្នុងសេចក្ដីប្រកាសនេះ ដោយគ្មានការប្រកាន់បែងចែកបែបណាមួយ"
  specimen_36: "មនុស្សគ្រប់រូប មានសិទ្ធិរកដំណោះស្រាយស័ក្ដិសិទ្ធិមួយនៅចំពោះមុខសាលាជំរះក្ដីជាតិ ដែល មានសមត្ថកិច្ច ចំពោះអំពើទាំងឡាយណាដែលរំលោភសិទ្ធិមូលដ្ឋានរបស់ខ្លួន ដែលត្រូវបានទទួលស្គាល់ ដោយរដ្ឋធម្មនុញ្ញ ឬដោយច្បាប់។"
  specimen_32: "គ្មានមនុស្សណាម្នាក់ ត្រូវរងការរំលោភជ្រៀតជ្រែកតាមអំពើចិត្ដក្នុងជីវិតឯកជន គ្រួសារ ទី លំនៅ ឬការឆ្លើយឆ្លង ឬការធ្វើឱ្យប៉ះពាល់ដល់កិត្ដិយស និងកេរ្ដិ៍ឈ្មោះរបស់ខ្លួនបានឡើយ។ ជនគ្រប់រូប មានសិទ្ធិ ទទួលការការពារពីច្បាប់ ប្រឆាំងនឹងការជ្រៀតជ្រែក ឬការប៉ះពាល់បែបនេះ។"
  specimen_21: "ជនគ្រប់រូប មានសិទ្ធិសេរីភាពខាងការគិត សតិសម្បជញ្ញៈ និងសាសនា។ សិទ្ធិនេះ រាប់បញ្ចូល ទាំងសេរីភាពផ្លាស់ប្ដូរសាសនា ឬជំនឿ ព្រមទាំងសេរីភាពសម្ដែងសាសនា ឬជំនឿរបស់ខ្លួន តែម្នាក់ឯង ឬដោយរួមជាមួយអ្នកដទៃ ជាសាធារណៈ ឬជាឯកជន តាមការបង្ហាត់បង្រៀន ការអនុវត្ដ ការគោរព បូជា និងការប្រតិបត្ដិតាម។\nមនុស្សគ្រប់រូប មានសិទ្ធិសេរីភាពក្នុងការមានមតិ និងការសម្ដែងមតិ។ សិទ្ធិនេះ រាប់បញ្ចូល ទាំងសេរីភាពក្នុងការប្រកាន់មតិ ដោយគ្មានការជ្រៀតជ្រែក និងសេរីភាពក្នុងការស្វែងរក ការទទួល និងការផ្សព្វផ្សាយព័ត៌មាន និងគំនិតនានាដោយគ្មានព្រំដែនទឹកដី ទោះតាមរយៈមធ្យោបាយសម្ដែង មតិណាមួយក៏ដោយ។"
  specimen_16: "ក្នុងឋានៈជាសមាជិកនៃសង្គម មនុស្សគ្រប់រូប មានសិទ្ធិទទួលបានសន្ដិសុខសង្គម និងមានបុព្វ សិទ្ធិសម្រេចបានសិទ្ធិខាងសេដ្ឋកិច្ច សង្គមកិច្ច និងវប្បធម៌ ដែលចាំបាច់សម្រាប់សេចក្ដីថ្លៃថ្នូរ និងការ រីកចំរើនដោយសេរីនៃបុគ្គលិកលក្ខណៈរបស់ខ្លួន តាមរយៈការខិតខំរបស់ជាតិ និងសហប្រតិបត្ដិការអន្ដរ ជាតិ និងដោយយោងទៅតាមការរៀបចំ និងធនធានរបស់ប្រទេសនីមួយៗ។\nមនុស្សគ្រប់រូប មានសិទ្ធិឈប់សម្រាក និងលំហែកំសាន្ដ រួមបញ្ចូលទាំងកម្រិតម៉ោងការងារ សមហេតុផល និងការឈប់សម្រាក ដោយបានប្រាក់បៀវត្សតាមពេលកំណត់ទៀងទាត់។\nមនុស្សគ្រប់រូប មានសិទ្ធិទទួលបាននូវសណ្ដាប់ធ្នាប់សង្គមនិងអន្ដរជាតិ ដែលធ្វើឱ្យសិទ្ធិ និង សេរីភាព ចែងក្នុងសេចក្ដីប្រកាសនេះ អាចសម្រេចបានដោយពេញលេញ។\nគ្មានបទបញ្ញត្ដិណាមួយនៃសេចក្ដីប្រកាសនេះ អាចត្រូវបានបកស្រាយ តម្រូវថា រដ្ឋណាមួយ ក្រុមណាមួយ ឬបុគ្គលណាម្នាក់ មានសិទ្ធិបែបណាមួយ ក្នុងការធ្វើសកម្មភាព ឬការប្រព្រឹត្ដអំពើអ្វ្វីមួយ ដែលសំដៅទៅបំផ្លិចបំផ្លាញនូវសិទ្ធិ និងសេរីភាពទាំងឡាយ ដែលមានចែងនៅក្នុងសេចក្ដីប្រកាសនេះ ឡើយ។"
}
