id: "ko_Hang"
language: "ko"
script: "Hang"
name: "Korean, Hangul"
autonym: "한국어"
region: "BR"
region: "CN"
region: "JP"
region: "KP"
region: "KR"
region: "US"
sample_text {
  masthead_full: "모든인간"
  masthead_partial: "은태"
  styles: "모\n든\n \n인\n간\n은\n \n태\n어\n날\n \n때\n부\n터\n \n자\n유\n로\n우\n며\n "
  tester: "모\n든\n \n인\n간\n은\n \n태\n어\n날\n \n때\n부\n터\n \n자\n유\n로\n우\n며\n \n그\n \n존\n엄\n과\n \n권\n리\n에\n "
  poster_sm: "모\n든\n \n인\n간\n은"
  poster_md: "모\n든\n \n인\n간"
  poster_lg: "모\n든"
  specimen_48: "모\n든\n \n인\n간\n은\n \n태\n어\n날\n \n때\n부\n터\n \n자\n유\n로\n우\n며\n \n그\n \n존\n엄\n과\n \n권\n리\n에\n "
  specimen_36: "모\n든\n \n인\n간\n은\n \n태\n어\n날\n \n때\n부\n터\n \n자\n유\n로\n우\n며\n \n그\n \n존\n엄\n과\n \n권\n리\n에\n \n있\n어\n \n동\n등\n하\n다\n.\n \n인\n간\n은\n \n천\n부\n적\n으\n로\n \n이"
  specimen_32: "모\n든\n \n인\n간\n은\n \n태\n어\n날\n \n때\n부\n터\n \n자\n유\n로\n우\n며\n \n그\n \n존\n엄\n과\n \n권\n리\n에\n \n있\n어\n \n동\n등\n하\n다\n.\n \n인\n간\n은\n \n천\n부\n적\n으\n로\n \n이\n성\n과\n \n양\n심\n을\n \n부\n여\n받\n았\n으\n며\n \n서\n로\n \n형\n제\n애"
  specimen_21: "모\n든\n \n인\n간\n은\n \n태\n어\n날\n \n때\n부\n터\n \n자\n유\n로\n우\n며\n \n그\n \n존\n엄\n과\n \n권\n리\n에\n \n있\n어\n \n동\n등\n하\n다\n.\n \n인\n간\n은\n \n천\n부\n적\n으\n로\n \n이\n성\n과\n \n양\n심\n을\n \n부\n여\n받\n았\n으\n며\n \n서\n로\n \n형\n제\n애\n의\n \n정\n신\n으\n로\n \n행\n동\n하\n여\n야\n \n한\n다\n.\n모\n든\n \n인\n간\n은\n \n태\n어\n날\n \n때\n부\n터\n \n자\n유\n로\n우\n며\n \n그\n \n존\n엄\n과\n \n권\n리\n에\n \n있\n어\n \n동\n등\n하\n다\n.\n \n인\n간\n은\n \n천\n부\n적\n으\n로\n \n이\n성\n과\n \n양\n심\n을\n \n부\n여\n받\n았\n으\n며\n "
  specimen_16: "모\n든\n \n인\n간\n은\n \n태\n어\n날\n \n때\n부\n터\n \n자\n유\n로\n우\n며\n \n그\n \n존\n엄\n과\n \n권\n리\n에\n \n있\n어\n \n동\n등\n하\n다\n.\n \n인\n간\n은\n \n천\n부\n적\n으\n로\n \n이\n성\n과\n \n양\n심\n을\n \n부\n여\n받\n았\n으\n며\n \n서\n로\n \n형\n제\n애\n의\n \n정\n신\n으\n로\n \n행\n동\n하\n여\n야\n \n한\n다\n.\n모\n든\n \n인\n간\n은\n \n태\n어\n날\n \n때\n부\n터\n \n자\n유\n로\n우\n며\n \n그\n \n존\n엄\n과\n \n권\n리\n에\n \n있\n어\n \n동\n등\n하\n다\n.\n \n인\n간\n은\n \n천\n부\n적\n으\n로\n \n이\n성\n과\n \n양\n심\n을\n \n부\n여\n받\n았\n으\n며\n \n서\n로\n \n형\n제\n애\n의\n \n정\n신\n으\n로\n \n행\n동\n하\n여\n야\n \n한\n다\n.\n모\n든\n \n인\n간\n은\n \n태\n어\n날\n \n때\n부\n터\n \n자\n유\n로\n우\n며\n \n그\n \n존\n엄\n과\n \n권\n리\n에\n \n있\n어\n \n동\n등\n하\n다\n.\n \n인\n간\n은\n \n천\n부\n적\n으\n로\n \n이\n성\n과\n \n양\n심\n을\n \n부\n여\n받\n았\n으\n며\n \n서\n로\n \n형\n제\n애\n의\n \n정\n신\n으\n로\n \n행\n동\n하\n여\n야\n \n한\n다\n.\n모\n든\n \n인\n간\n은\n \n태\n어\n날\n \n때\n부\n터\n \n자\n유\n로"
}
