id: "kok"
language: "kok"
script: "Deva"
name: "Konkani"
population: 4906533
region: "IN"
exemplar_chars {
  base: "़ ० १ २ ३ ४ ५ ६ ७ ८ ९ ॐ ं ँ ः अ आ इ ई उ ऊ ऋ ऌ ऍ ए ऐ ऑ ओ औ क {क़} ख {ख़} ग {ग़} घ ङ च छ ज {ज़} झ ञ ट ठ ड {ड़} ढ {ढ़} ण त थ द ध न प फ {फ़} ब भ म य {य़} र ल व श ष स ह ळ ऽ ा ि ी ु ू ृ ॄ ॅ े ै ॉ ो ौ ् {क़} {ख़} {ग़} {ज़} {ड़} {ढ़} {फ़} {य़} {क़} {ख़} {ग़} {ज़} {ड़} {ढ़} {फ़} {य़} {क़} {ख़} {ग़} {ज़} {ड़} {ढ़} {फ़} {य़} {क़} {ख़} {ग़} {ज़} {ड़} {ढ़} {फ़} {य़} {क़} {ख़} {ग़} {ज़} {ड़} {ढ़} {फ़} {य़} {क़} {ख़} {ग़} {ज़} {ड़} {ढ़} {फ़} {य़} {क़} {ख़} {ग़} {ज़} {ड़} {ढ़} {फ़} {य़} {क़} {ख़} {ग़} {ज़} {ड़} {ढ़} {फ़} {य़} {क़} {ख़} {ग़} {ज़} {ड़} {ढ़} {फ़} {य़} {क़} {ख़} {ग़} {ज़} {ड़} {ढ़} {फ़} {य़} {क़} {ख़} {ग़} {ज़} {ड़} {ढ़} {फ़} {य़} {क़} {ख़} {ग़} {ज़} {ड़} {ढ़} {फ़} {य़} {क़} {ख़} {ग़} {ज़} {ड़} {ढ़} {फ़} {य़} {क़} {ख़} {ग़} {ज़} {ड़} {ढ़} {फ़} {य़} {क़} {ख़} {ग़} {ज़} {ड़} {ढ़} {फ़} {य़}"
  auxiliary: "‌‍"
  numerals: "- ‑ , . % ‰ + 0० 1१ 2२ 3३ 4४ 5५ 6६ 7७ 8८ 9९"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ \" “ ” ( ) [ ] § @ * / & # † ‡ ′ ″"
  index: "अ आ इ ई उ ऊ ऋ ऌ ऍ ए ऐ ऑ ओ औ क ख ग घ ङ च छ ज झ ञ ट ठ ड ढ ण त थ द ध न प फ ब भ म य र ल व श ष स ह ळ"
}
sample_text {
  fallback_language: "hi"
}
