id: "koo_Latn"
language: "koo"
script: "Latn"
name: "Konjo"
sample_text {
  masthead_full: "AaBb"
  masthead_partial: "Nn"
  styles: "A\nb\na\nn\nd\nu\n \no\nm\nu\nb\nu\nb\nu\nt\nh\ni\nr\na\nn\nw"
  tester: "A\nb\na\nn\nd\nu\n \no\nm\nu\nb\nu\nb\nu\nt\nh\ni\nr\na\nn\nw\na\n \nb\na\nk\na\nb\nu\nt\nh"
  poster_sm: "A\nb\na\nn\nd\nu"
  poster_md: "A\nb\na\nn\nd"
  poster_lg: "A\nb"
  specimen_48: "A\nb\na\nn\nd\nu\n \no\nm\nu\nb\nu\nb\nu\nt\nh\ni\nr\na\nn\nw\na\n \nb\na\nk\na\nb\nu\nt\nh"
  specimen_36: "A\nb\na\nn\nd\nu\n \no\nm\nu\nb\nu\nb\nu\nt\nh\ni\nr\na\nn\nw\na\n \nb\na\nk\na\nb\nu\nt\nh\na\nw\na\n \ni\nb\na\nn\na\nw\ni\nt\nh\ne\n \no\nb\nu\nt\nh"
  specimen_32: "A\nb\na\nn\nd\nu\n \no\nm\nu\nb\nu\nb\nu\nt\nh\ni\nr\na\nn\nw\na\n \nb\na\nk\na\nb\nu\nt\nh\na\nw\na\n \ni\nb\na\nn\na\nw\ni\nt\nh\ne\n \no\nb\nu\nt\nh\no\nk\ni\n \nn\no\nb\nu\nh\no\nl\nh\no\n \no\nb\nu\nl\ni\nn"
  specimen_21: "A\nb\na\nn\nd\nu\n \no\nm\nu\nb\nu\nb\nu\nt\nh\ni\nr\na\nn\nw\na\n \nb\na\nk\na\nb\nu\nt\nh\na\nw\na\n \ni\nb\na\nn\na\nw\ni\nt\nh\ne\n \no\nb\nu\nt\nh\no\nk\ni\n \nn\no\nb\nu\nh\no\nl\nh\no\n \no\nb\nu\nl\ni\nn\ng\ni\nr\ni\nr\ne\nn\ne\n,\n \nm\no\nb\na\nh\na\nn\ng\ni\nk\nw\na\n \ni\nb\na\nn\na\nw\ni\nt\nh\ne\n \na\nm\ne\nn\ng\ne\n,\n \nn\ne\nr\ny\no\n \ni\nb\na\nk\na\nt\nh\no\nk\na\n \ne\nr\ni\ng\nh\na\nb\na\nn\ni\na\n \na\nb\na\nt\nh\ny\na\n \ne\nk"
  specimen_16: "A\nb\na\nn\nd\nu\n \no\nm\nu\nb\nu\nb\nu\nt\nh\ni\nr\na\nn\nw\na\n \nb\na\nk\na\nb\nu\nt\nh\na\nw\na\n \ni\nb\na\nn\na\nw\ni\nt\nh\ne\n \no\nb\nu\nt\nh\no\nk\ni\n \nn\no\nb\nu\nh\no\nl\nh\no\n \no\nb\nu\nl\ni\nn\ng\ni\nr\ni\nr\ne\nn\ne\n,\n \nm\no\nb\na\nh\na\nn\ng\ni\nk\nw\na\n \ni\nb\na\nn\na\nw\ni\nt\nh\ne\n \na\nm\ne\nn\ng\ne\n,\n \nn\ne\nr\ny\no\n \ni\nb\na\nk\na\nt\nh\no\nk\na\n \ne\nr\ni\ng\nh\na\nb\na\nn\ni\na\n \na\nb\na\nt\nh\ny\na\n \ne\nk\ni\nb\nu\ny\na\n \nn\ne\nk\ni\ns\na\nn\nd\ni\nr\ne\n.\n \nN\no\nk\nw\ne\nr\ny\no\n \nb\nu\nl\ni\n \nm\nu\ny\ni\nm\na\n \na\nt\nh\no\nl\ne\nr\ne\n \ne\nr\ny\na\nn\nz\na\n \nm\nu\nn\ny\ni\nk\ni\nw\ne\n \nn\ng\na\nb\na\nb\nu\nt\nh\ne\nn\nw\ne\n.\nA\nb\na\nn\nd\nu\n \no\nm\nu\nb\nu\nb\nu\nt\nh\ni\nr\na\nn\nw\na\n \nb\na\nk\na\nb\nu\nt\nh\na\nw\na\n \ni\nb\na\nn\na\nw\ni\nt\nh\ne"
}
