id: "kqn_Latn"
language: "kqn"
script: "Latn"
name: "Kaonde"
sample_text {
  masthead_full: "BbOo"
  masthead_partial: "Nn"
  styles: "B\no\nn\ns\ne\n \nb\na\nn\nt\nu\n \nb\na\ns\ne\nm\nw\na\n \nb"
  tester: "B\no\nn\ns\ne\n \nb\na\nn\nt\nu\n \nb\na\ns\ne\nm\nw\na\n \nb\na\nk\na\ns\nu\nl\nu\nk\na\n "
  poster_sm: "B\no\nn\ns\ne\n "
  poster_md: "B\no\nn\ns\ne"
  poster_lg: "B\no"
  specimen_48: "B\no\nn\ns\ne\n \nb\na\nn\nt\nu\n \nb\na\ns\ne\nm\nw\na\n \nb\na\nk\na\ns\nu\nl\nu\nk\na\n "
  specimen_36: "B\no\nn\ns\ne\n \nb\na\nn\nt\nu\n \nb\na\ns\ne\nm\nw\na\n \nb\na\nk\na\ns\nu\nl\nu\nk\na\n \nk\na\nb\ni\nj\ni\n \nb\na\ne\ns\na\nk\ne\nn\na\n \np\na\nm"
  specimen_32: "B\no\nn\ns\ne\n \nb\na\nn\nt\nu\n \nb\na\ns\ne\nm\nw\na\n \nb\na\nk\na\ns\nu\nl\nu\nk\na\n \nk\na\nb\ni\nj\ni\n \nb\na\ne\ns\na\nk\ne\nn\na\n \np\na\nm\no\n \nm\nu\nb\nu\nn\ne\nm\ne\n.\n \nB\na\nj\ni\n \nn\na\n "
  specimen_21: "B\no\nn\ns\ne\n \nb\na\nn\nt\nu\n \nb\na\ns\ne\nm\nw\na\n \nb\na\nk\na\ns\nu\nl\nu\nk\na\n \nk\na\nb\ni\nj\ni\n \nb\na\ne\ns\na\nk\ne\nn\na\n \np\na\nm\no\n \nm\nu\nb\nu\nn\ne\nm\ne\n.\n \nB\na\nj\ni\n \nn\na\n \nm\na\na\nn\na\n \na\n \nk\nu\nl\na\nn\ng\nu\nl\nu\nk\na\n \nk\na\nb\ni\nj\ni\n \nb\no\nb\ni\nl\na\n \nb\na\nn\nt\nu\n \nb\na\nk\nw\na\nb\no\n \nb\ny\nu\nb\ni\nl\no\n \nb\na\nk\nw\ni\nb\na\ns\ne\nk\ne\ns\nh\na\n.\nB\no\nn\ns\ne\n \nb\na\nn\nt"
  specimen_16: "B\no\nn\ns\ne\n \nb\na\nn\nt\nu\n \nb\na\ns\ne\nm\nw\na\n \nb\na\nk\na\ns\nu\nl\nu\nk\na\n \nk\na\nb\ni\nj\ni\n \nb\na\ne\ns\na\nk\ne\nn\na\n \np\na\nm\no\n \nm\nu\nb\nu\nn\ne\nm\ne\n.\n \nB\na\nj\ni\n \nn\na\n \nm\na\na\nn\na\n \na\n \nk\nu\nl\na\nn\ng\nu\nl\nu\nk\na\n \nk\na\nb\ni\nj\ni\n \nb\no\nb\ni\nl\na\n \nb\na\nn\nt\nu\n \nb\na\nk\nw\na\nb\no\n \nb\ny\nu\nb\ni\nl\no\n \nb\na\nk\nw\ni\nb\na\ns\ne\nk\ne\ns\nh\na\n.\nB\no\nn\ns\ne\n \nb\na\nn\nt\nu\n \nb\na\ns\ne\nm\nw\na\n \nb\na\nk\na\ns\nu\nl\nu\nk\na\n \nk\na\nb\ni\nj\ni\n \nb\na\ne\ns\na\nk\ne\nn\na\n \np\na\nm\no\n \nm\nu\nb\nu\nn\ne\nm\ne\n.\n \nB\na\nj\ni\n \nn\na\n \nm\na\na\nn\na\n \na\n \nk\nu\nl\na\nn\ng\nu\nl\nu\nk\na\n \nk\na\nb\ni\nj\ni\n \nb\no\nb\ni\nl\na\n \nb\na\nn\nt\nu\n \nb\na\nk\nw\na\nb\no\n \nb\ny\nu\nb\ni\nl\no\n \nb\na\nk\nw\ni\nb\na\ns"
}
