id: "kqs_Latn"
language: "kqs"
script: "Latn"
name: "Kissi, Northern"
sample_text {
  masthead_full: "WwAa"
  masthead_partial: "Nn"
  styles: "w\na\nn\nd\na\n \nt\nu\n \nc\ni\no\n \nM\nE\n \np\ni\nl\nO\nO"
  tester: "w\na\nn\nd\na\n \nt\nu\n \nc\ni\no\n \nM\nE\n \np\ni\nl\nO\nO\n \no\n \nw\no\nl\nO\nO\n \nn"
  poster_sm: "w\na\nn\nd\na\n "
  poster_md: "w\na\nn\nd\na"
  poster_lg: "w\na"
  specimen_48: "w\na\nn\nd\na\n \nt\nu\n \nc\ni\no\n \nM\nE\n \np\ni\nl\nO\nO\n \no\n \nw\no\nl\nO\nO\n \nn"
  specimen_36: "w\na\nn\nd\na\n \nt\nu\n \nc\ni\no\n \nM\nE\n \np\ni\nl\nO\nO\n \no\n \nw\no\nl\nO\nO\n \nn\ni\n,\n \nl\ne\n \nw\na\na\n \no\n \nb\na\n \nn\nd\nO\nO\n "
  specimen_32: "w\na\nn\nd\na\n \nt\nu\n \nc\ni\no\n \nM\nE\n \np\ni\nl\nO\nO\n \no\n \nw\no\nl\nO\nO\n \nn\ni\n,\n \nl\ne\n \nw\na\na\n \no\n \nb\na\n \nn\nd\nO\nO\n \nc\ni\no\n,\n \no\n \nb\nE\nE\nl\ne\nn\n \nk\ne\nn\na\nn\nd\no"
  specimen_21: "w\na\nn\nd\na\n \nt\nu\n \nc\ni\no\n \nM\nE\n \np\ni\nl\nO\nO\n \no\n \nw\no\nl\nO\nO\n \nn\ni\n,\n \nl\ne\n \nw\na\na\n \no\n \nb\na\n \nn\nd\nO\nO\n \nc\ni\no\n,\n \no\n \nb\nE\nE\nl\ne\nn\n \nk\ne\nn\na\nn\nd\no\n \nn\ni\n,\n \no\n \nt\nO\nn\ng\nd\no\n \nn\ni\n,\n \nb\nE\nt\nu\n \nn\nO\nn\n \ny\ni\ny\na\nn\nd\no\n \na\n \nk\nu\nl\nl\no\n,\n \no\n \nk\no\nn\n \nn\ni\n \nn\na\na\nn\n \nt\nu\n \nd\nu\na\n \nm\ni\nm\n \nm\na\na\nl\ny\na\nn\n \nk\na\nl\na"
  specimen_16: "w\na\nn\nd\na\n \nt\nu\n \nc\ni\no\n \nM\nE\n \np\ni\nl\nO\nO\n \no\n \nw\no\nl\nO\nO\n \nn\ni\n,\n \nl\ne\n \nw\na\na\n \no\n \nb\na\n \nn\nd\nO\nO\n \nc\ni\no\n,\n \no\n \nb\nE\nE\nl\ne\nn\n \nk\ne\nn\na\nn\nd\no\n \nn\ni\n,\n \no\n \nt\nO\nn\ng\nd\no\n \nn\ni\n,\n \nb\nE\nt\nu\n \nn\nO\nn\n \ny\ni\ny\na\nn\nd\no\n \na\n \nk\nu\nl\nl\no\n,\n \no\n \nk\no\nn\n \nn\ni\n \nn\na\na\nn\n \nt\nu\n \nd\nu\na\n \nm\ni\nm\n \nm\na\na\nl\ny\na\nn\n \nk\na\nl\na\np\ni\nl\nO\ny\nE\ny\ni\n \nn\ni\n.\nw\na\nn\nd\na\n \nt\nu\n \nc\ni\no\n \nM\nE\n \np\ni\nl\nO\nO\n \no\n \nw\no\nl\nO\nO\n \nn\ni\n,\n \nl\ne\n \nw\na\na\n \no\n \nb\na\n \nn\nd\nO\nO\n \nc\ni\no\n,\n \no\n \nb\nE\nE\nl\ne\nn\n \nk\ne\nn\na\nn\nd\no\n \nn\ni\n,\n \no\n \nt\nO\nn\ng\nd\no\n \nn\ni\n,\n \nb\nE\nt\nu\n \nn\nO\nn\n \ny\ni\ny\na\nn\nd\no\n \na\n \nk\nu\nl\nl\no\n,\n "
}
