id: "kru_Deva"
language: "kru"
script: "Deva"
name: "Kurukh"
population: 2519571
region: "IN"
sample_text {
  masthead_full: "हरमआ"
  masthead_partial: "लन"
  styles: "ह\nो\nर\nम\nा\n \nआ\nल\nा\nर\nि\nन\n \nह\nक\n \nग\nह\nि\n \nब\nा\nर\nे"
  tester: "ह\nो\nर\nम\nा\n \nआ\nल\nा\nर\nि\nन\n \nह\nक\n \nग\nह\nि\n \nब\nा\nर\nे\n \nन\nू\n \nम\nल\n्\nल\nी\nन\n्\nत"
  poster_sm: "ह\nो\nर\nम\nा\n \nआ"
  poster_md: "ह\nो\nर\nम\nा\n "
  poster_lg: "ह\nो\nर"
  specimen_48: "ह\nो\nर\nम\nा\n \nआ\nल\nा\nर\nि\nन\n \nह\nक\n \nग\nह\nि\n \nब\nा\nर\nे\n \nन\nू\n \nम\nल\n्\nल\nी\nन\n्\nत"
  specimen_36: "ह\nो\nर\nम\nा\n \nआ\nल\nा\nर\nि\nन\n \nह\nक\n \nग\nह\nि\n \nब\nा\nर\nे\n \nन\nू\n \nम\nल\n्\nल\nी\nन\n्\nत\nा\n \nअ\nज़\nा\nद\nी\n \nअ\nर\nा\n \nआ\nण\n्\nट\nे\nम\n \nम\nन\n्\nन\nा"
  specimen_32: "ह\nो\nर\nम\nा\n \nआ\nल\nा\nर\nि\nन\n \nह\nक\n \nग\nह\nि\n \nब\nा\nर\nे\n \nन\nू\n \nम\nल\n्\nल\nी\nन\n्\nत\nा\n \nअ\nज़\nा\nद\nी\n \nअ\nर\nा\n \nआ\nण\n्\nट\nे\nम\n \nम\nन\n्\nन\nा\n \nग\nह\nी\n \nह\nक़\n \nख़\nख\nर\nक\nी\n \nर\nई\n।\n \nआ\nर\nि\nन"
  specimen_21: "ह\nो\nर\nम\nा\n \nआ\nल\nा\nर\nि\nन\n \nह\nक\n \nग\nह\nि\n \nब\nा\nर\nे\n \nन\nू\n \nम\nल\n्\nल\nी\nन\n्\nत\nा\n \nअ\nज़\nा\nद\nी\n \nअ\nर\nा\n \nआ\nण\n्\nट\nे\nम\n \nम\nन\n्\nन\nा\n \nग\nह\nी\n \nह\nक़\n \nख़\nख\nर\nक\nी\n \nर\nई\n।\n \nआ\nर\nि\nन\n \nल\nू\nर\n \nअ\nर\nा\n \nज\nि\nय\nा\n \nग\nह\nी\n \nद\nव\n \nब\nउ\nस\nा\n \nख़\nख\nक\nी\n \nर\nई\n \nअ\nर\nा\n \nत\nम\n्\nह\nै\nं\n \nम\nझ\nी\n \nन\nू\n \nम\nे\nल\n-\nप\n्\nर\nे\nम\n \nग\nह\nी\n \nब\nे\nव\nह\nा\nर\n \nन\nन\nन\nा\n \nच\nह\nी\n।\nह\nो\nर\nम\nा\n \nआ\nल\nा\nर\nि\nन"
  specimen_16: "ह\nो\nर\nम\nा\n \nआ\nल\nा\nर\nि\nन\n \nह\nक\n \nग\nह\nि\n \nब\nा\nर\nे\n \nन\nू\n \nम\nल\n्\nल\nी\nन\n्\nत\nा\n \nअ\nज़\nा\nद\nी\n \nअ\nर\nा\n \nआ\nण\n्\nट\nे\nम\n \nम\nन\n्\nन\nा\n \nग\nह\nी\n \nह\nक़\n \nख़\nख\nर\nक\nी\n \nर\nई\n।\n \nआ\nर\nि\nन\n \nल\nू\nर\n \nअ\nर\nा\n \nज\nि\nय\nा\n \nग\nह\nी\n \nद\nव\n \nब\nउ\nस\nा\n \nख़\nख\nक\nी\n \nर\nई\n \nअ\nर\nा\n \nत\nम\n्\nह\nै\nं\n \nम\nझ\nी\n \nन\nू\n \nम\nे\nल\n-\nप\n्\nर\nे\nम\n \nग\nह\nी\n \nब\nे\nव\nह\nा\nर\n \nन\nन\nन\nा\n \nच\nह\nी\n।\nह\nो\nर\nम\nा\n \nआ\nल\nा\nर\nि\nन\n \nह\nक\n \nग\nह\nि\n \nब\nा\nर\nे\n \nन\nू\n \nम\nल\n्\nल\nी\nन\n्\nत\nा\n \nअ\nज़\nा\nद\nी\n \nअ\nर\nा\n \nआ\nण\n्\nट\nे\nम\n \nम\nन\n्\nन\nा\n \nग\nह\nी\n \nह\nक़\n \nख़\nख\nर\nक\nी\n \nर\nई\n।\n \nआ\nर\nि\nन\n \nल\nू\nर\n \nअ\nर\nा\n \nज\nि\nय\nा\n \nग\nह\nी\n \nद\nव\n \nब\nउ\nस\nा\n \nख़\nख\nक\nी\n \nर\nई\n \nअ\nर\nा\n \nत\nम\n्\nह\nै\nं\n \nम\nझ\nी\n \nन\nू\n \nम\nे\nल\n-\nप\n्\nर\nे\nम\n \nग\nह\nी\n \nब\nे\nव\nह\nा\nर\n \nन"
}
