id: "kru_Deva"
language: "kru"
script: "Deva"
name: "Kurukh"
population: 2519571
region: "IN"
sample_text {
  masthead_full: "हरमआ"
  masthead_partial: "लन"
  styles: "होरमा आलारिन हक गहि बारे नू मल्लीन्ता अज़ादी अरा आण्टेम मन्ना"
  tester: "होरमा आलारिन हक गहि बारे नू मल्लीन्ता अज़ादी अरा आण्टेम मन्ना गही हक़ ख़खरकी रई। आरिन लूर"
  poster_sm: "होरमा आलारिन हक"
  poster_md: "होरमा आलारिन"
  poster_lg: "होरमा"
  specimen_48: "होरमा आलारिन हक गहि बारे नू मल्लीन्ता अज़ादी अरा आण्टेम मन्ना गही हक़ ख़खरकी"
  specimen_36: "होरमा आलारिन हक गहि बारे नू मल्लीन्ता अज़ादी अरा आण्टेम मन्ना गही हक़ ख़खरकी रई। आरिन लूर अरा जिया गही दव बउसा ख़खकी रई अरा तम्हैं मझी नू मेलप्रेम गही बेवहार ननना चही।"
  specimen_32: "होरमा आलारिन हक गहि बारे नू मल्लीन्ता अज़ादी अरा आण्टेम मन्ना गही हक़ ख़खरकी रई। आरिन लूर अरा जिया गही दव बउसा ख़खकी रई अरा तम्हैं मझी नू मेलप्रेम गही बेवहार ननना चही।"
  specimen_21: "होरमा आलारिन हक गहि बारे नू मल्लीन्ता अज़ादी अरा आण्टेम मन्ना गही हक़ ख़खरकी रई। आरिन लूर अरा जिया गही दव बउसा ख़खकी रई अरा तम्हैं मझी नू मेलप्रेम गही बेवहार ननना चही।\nहोरमा आलारिन हक गहि बारे नू मल्लीन्ता अज़ादी अरा आण्टेम मन्ना गही हक़ ख़खरकी रई। आरिन लूर अरा जिया गही दव बउसा ख़खकी रई अरा तम्हैं मझी नू मेलप्रेम गही बेवहार ननना चही।\nहोरमा आलारिन हक गहि बारे नू मल्लीन्ता अज़ादी अरा आण्टेम मन्ना गही हक़ ख़खरकी रई। आरिन लूर अरा जिया गही दव बउसा ख़खकी रई अरा तम्हैं मझी नू मेलप्रेम गही बेवहार ननना चही।"
  specimen_16: "होरमा आलारिन हक गहि बारे नू मल्लीन्ता अज़ादी अरा आण्टेम मन्ना गही हक़ ख़खरकी रई। आरिन लूर अरा जिया गही दव बउसा ख़खकी रई अरा तम्हैं मझी नू मेलप्रेम गही बेवहार ननना चही।\nहोरमा आलारिन हक गहि बारे नू मल्लीन्ता अज़ादी अरा आण्टेम मन्ना गही हक़ ख़खरकी रई। आरिन लूर अरा जिया गही दव बउसा ख़खकी रई अरा तम्हैं मझी नू मेलप्रेम गही बेवहार ननना चही।\nहोरमा आलारिन हक गहि बारे नू मल्लीन्ता अज़ादी अरा आण्टेम मन्ना गही हक़ ख़खरकी रई। आरिन लूर अरा जिया गही दव बउसा ख़खकी रई अरा तम्हैं मझी नू मेलप्रेम गही बेवहार ननना चही।\nहोरमा आलारिन हक गहि बारे नू मल्लीन्ता अज़ादी अरा आण्टेम मन्ना गही हक़ ख़खरकी रई। आरिन लूर अरा जिया गही दव बउसा ख़खकी रई अरा तम्हैं मझी नू मेलप्रेम गही बेवहार ननना चही।\nहोरमा आलारिन हक गहि बारे नू मल्लीन्ता अज़ादी अरा आण्टेम मन्ना गही हक़ ख़खरकी रई। आरिन लूर अरा जिया गही दव बउसा ख़खकी रई अरा तम्हैं मझी नू मेलप्रेम गही बेवहार ननना चही।"
}
