id: "ks_Arab"
language: "ks"
script: "Arab"
name: "Kashmiri"
population: 5723030
region: "GB"
region: "IN"
region: "PK"
exemplar_chars {
  base: "ء آ أ ٲ ؤ ا ب پ ت ث ٹ ج چ ح خ د ذ ڈ ر ز ڑ ژ س ش ص ض ط ظ ع غ ف ق ک گ ل م ن ں ھ ہ و ۄ ۆ ی ۍ ؠ ے"
  auxiliary: "‎‏ َ ُ ِ ٔ ٕ ٟ ٖ ٗ"
  numerals: "‎ - ‑ , . % ‰ + 0۰ 1۱ 2۲ 3۳ 4۴ 5۵ 6۶ 7۷ 8۸ 9۹"
}
sample_text {
  masthead_full: "سریل"
  masthead_partial: "کھ"
  styles: "س\nٔ\nر\nی\n \nل\nُ\nک\nھ\n \nچ\nه\nہ\nٕ\n \nح\nق\nو\nٗ\nق\n \nت\nِ"
  tester: "س\nٔ\nر\nی\n \nل\nُ\nک\nھ\n \nچ\nه\nہ\nٕ\n \nح\nق\nو\nٗ\nق\n \nت\nِ\nہ\n \nع\nز\nت\n \nل\nِ\nح\nا\nظ"
  poster_sm: "س\nٔ\nر\nی\n \nل"
  poster_md: "س\nٔ\nر\nی\n "
  poster_lg: "س\nٔ\nر"
  specimen_48: "س\nٔ\nر\nی\n \nل\nُ\nک\nھ\n \nچ\nه\nہ\nٕ\n \nح\nق\nو\nٗ\nق\n \nت\nِ\nہ\n \nع\nز\nت\n \nل\nِ\nح\nا\nظ"
  specimen_36: "س\nٔ\nر\nی\n \nل\nُ\nک\nھ\n \nچ\nه\nہ\nٕ\n \nح\nق\nو\nٗ\nق\n \nت\nِ\nہ\n \nع\nز\nت\n \nل\nِ\nح\nا\nظ\nٕ\n \nہ\nِ\nہ\nی\nٖ\n \nژ\nا\nم\nِ\nت\n.\n \nت\nِ\nم\nن\n \nچ\nه\n‍"
  specimen_32: "س\nٔ\nر\nی\n \nل\nُ\nک\nھ\n \nچ\nه\nہ\nٕ\n \nح\nق\nو\nٗ\nق\n \nت\nِ\nہ\n \nع\nز\nت\n \nل\nِ\nح\nا\nظ\nٕ\n \nہ\nِ\nہ\nی\nٖ\n \nژ\nا\nم\nِ\nت\n.\n \nت\nِ\nم\nن\n \nچ\nه\n‍\nہ\nِ\n \nض\nم\nي\nر\n \nت\nِ\nہ\n \nع\nَ\nق\nل\n \nد\nِ\nن\nِ\n \nآ"
  specimen_21: "س\nٔ\nر\nی\n \nل\nُ\nک\nھ\n \nچ\nه\nہ\nٕ\n \nح\nق\nو\nٗ\nق\n \nت\nِ\nہ\n \nع\nز\nت\n \nل\nِ\nح\nا\nظ\nٕ\n \nہ\nِ\nہ\nی\nٖ\n \nژ\nا\nم\nِ\nت\n.\n \nت\nِ\nم\nن\n \nچ\nه\n‍\nہ\nِ\n \nض\nم\nي\nر\n \nت\nِ\nہ\n \nع\nَ\nق\nل\n \nد\nِ\nن\nِ\n \nآ\nم\nٕ\nژ\n.\n \nت\nٔ\nو\nے\n \nپ\nَ\nز\nٕ\n \nت\nُ\nم\nن\n \nب\nھ\nٲ\nئ\nی\n \nب\nر\nا\nد\nر\nی\n \nس\nا\nن\nٛ\n \nر\nو\nز\nُ\nن\n.\nس\nٔ\nر\nی\n \nل\nُ\nک\nھ\n \nچ\nه\nہ\nٕ\n \nح\nق\nو\nٗ\nق\n \nت\nِ\nہ\n \nع\nز\nت\n \nل\nِ\nح\nا\nظ\nٕ\n \nہ\nِ\nہ\nی\nٖ\n \nژ\nا\nم"
  specimen_16: "س\nٔ\nر\nی\n \nل\nُ\nک\nھ\n \nچ\nه\nہ\nٕ\n \nح\nق\nو\nٗ\nق\n \nت\nِ\nہ\n \nع\nز\nت\n \nل\nِ\nح\nا\nظ\nٕ\n \nہ\nِ\nہ\nی\nٖ\n \nژ\nا\nم\nِ\nت\n.\n \nت\nِ\nم\nن\n \nچ\nه\n‍\nہ\nِ\n \nض\nم\nي\nر\n \nت\nِ\nہ\n \nع\nَ\nق\nل\n \nد\nِ\nن\nِ\n \nآ\nم\nٕ\nژ\n.\n \nت\nٔ\nو\nے\n \nپ\nَ\nز\nٕ\n \nت\nُ\nم\nن\n \nب\nھ\nٲ\nئ\nی\n \nب\nر\nا\nد\nر\nی\n \nس\nا\nن\nٛ\n \nر\nو\nز\nُ\nن\n.\nس\nٔ\nر\nی\n \nل\nُ\nک\nھ\n \nچ\nه\nہ\nٕ\n \nح\nق\nو\nٗ\nق\n \nت\nِ\nہ\n \nع\nز\nت\n \nل\nِ\nح\nا\nظ\nٕ\n \nہ\nِ\nہ\nی\nٖ\n \nژ\nا\nم\nِ\nت\n.\n \nت\nِ\nم\nن\n \nچ\nه\n‍\nہ\nِ\n \nض\nم\nي\nر\n \nت\nِ\nہ\n \nع\nَ\nق\nل\n \nد\nِ\nن\nِ\n \nآ\nم\nٕ\nژ\n.\n \nت\nٔ\nو\nے\n \nپ\nَ\nز\nٕ\n \nت\nُ\nم\nن\n \nب\nھ\nٲ\nئ\nی\n \nب\nر\nا\nد\nر\nی\n \nس\nا\nن\nٛ\n \nر\nو\nز\nُ\nن\n.\nس\nٔ\nر\nی\n \nل\nُ\nک\nھ\n \nچ\nه\nہ\nٕ\n \nح\nق\nو\nٗ\nق\n \nت\nِ\nہ\n \nع\nز\nت\n \nل\nِ\nح\nا\nظ\nٕ\n \nہ\nِ\nہ\nی\nٖ\n \nژ\nا\nم\nِ\nت\n.\n \nت\nِ\nم\nن\n \nچ\nه\n‍\nہ\nِ\n \nض\nم"
}
