id: "ksb"
language: "ksb"
script: "Latn"
name: "Shambala"
autonym: "Kishambaa"
population: 995397
region: "TZ"
exemplar_chars {
  base: "a b c d e f g h i j k l m n o p s t u v w y z"
  auxiliary: "q r x"
  index: "A B C D E F G H I J K L M N O P S T U V W Y Z"
}
sample_text {
  fallback_language: "en"
}
