id: "ksf"
language: "ksf"
script: "Latn"
name: "Bafia"
autonym: "Rikpa"
population: 88784
region: "CM"
exemplar_chars {
  base: "a á b c d e é ǝ {ǝ́} ɛ {ɛ́} f g h i í j k l m n ŋ o ó ɔ {ɔ́} p r s t u ú v w y z {ǝ́} {ɛ́} {ɔ́} {ǝ́} {ɛ́} {ɔ́} {ǝ́} {ɛ́} {ɔ́} {ǝ́} {ɛ́} {ɔ́} {ǝ́} {ɛ́} {ɔ́} {ǝ́} {ɛ́} {ɔ́} {ǝ́} {ɛ́} {ɔ́} {ǝ́} {ɛ́} {ɔ́} {ǝ́} {ɛ́} {ɔ́} {ǝ́} {ɛ́} {ɔ́} {ǝ́} {ɛ́} {ɔ́} {ǝ́} {ɛ́} {ɔ́} {ǝ́} {ɛ́} {ɔ́} {ǝ́} {ɛ́} {ɔ́} {ǝ́} {ɛ́} {ɔ́}"
  auxiliary: "q x"
  marks: "◌́"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B C D E Ǝ Ɛ F G H I J K L M N Ŋ O Ɔ P R S T U V W Y Z"
}
sample_text {
  fallback_language: "en"
}
