id: "ktu_Latn"
language: "ktu"
script: "Latn"
name: "Kituba"
sample_text {
  masthead_full: "BbAa"
  masthead_partial: "Nn"
  styles: "B\na\nn\nt\nu\n \nn\ny\no\nn\ns\no\n,\n \nn\na\n \nm\nb\nu\nt"
  tester: "B\na\nn\nt\nu\n \nn\ny\no\nn\ns\no\n,\n \nn\na\n \nm\nb\nu\nt\nu\nk\nu\nl\nu\n \nk\ne\nv\nw"
  poster_sm: "B\na\nn\nt\nu\n "
  poster_md: "B\na\nn\nt\nu"
  poster_lg: "B\na"
  specimen_48: "B\na\nn\nt\nu\n \nn\ny\no\nn\ns\no\n,\n \nn\na\n \nm\nb\nu\nt\nu\nk\nu\nl\nu\n \nk\ne\nv\nw"
  specimen_36: "B\na\nn\nt\nu\n \nn\ny\no\nn\ns\no\n,\n \nn\na\n \nm\nb\nu\nt\nu\nk\nu\nl\nu\n \nk\ne\nv\nw\na\nn\nd\na\nk\na\n \nn\na\n \nk\ni\nm\np\nw\na\nn\nz\na\n "
  specimen_32: "B\na\nn\nt\nu\n \nn\ny\no\nn\ns\no\n,\n \nn\na\n \nm\nb\nu\nt\nu\nk\nu\nl\nu\n \nk\ne\nv\nw\na\nn\nd\na\nk\na\n \nn\na\n \nk\ni\nm\np\nw\na\nn\nz\na\n \ny\na\n \nb\na\nw\nu\n,\n \nn\ng\ne\nn\nd\na\n \nm\np\ne\n \nb"
  specimen_21: "B\na\nn\nt\nu\n \nn\ny\no\nn\ns\no\n,\n \nn\na\n \nm\nb\nu\nt\nu\nk\nu\nl\nu\n \nk\ne\nv\nw\na\nn\nd\na\nk\na\n \nn\na\n \nk\ni\nm\np\nw\na\nn\nz\na\n \ny\na\n \nb\na\nw\nu\n,\n \nn\ng\ne\nn\nd\na\n \nm\np\ne\n \nb\na\nl\nu\nv\ne\n \ny\na\n \nm\nu\nt\ni\nn\nd\nu\n \nm\no\ns\ni\n.\n \nM\na\ny\ne\nl\na\n \nn\na\n \nm\nb\na\nn\nz\nu\nl\nu\n \nj\ne\n \nn\na\n \nb\na\nw\nu\n,\n \nn\ni\n \ny\na\nw\nu\n \ny\ni\nn\na\n \nb\na\nf\nw\na\nn\na\n \nk\nu\ns\na\nl\na"
  specimen_16: "B\na\nn\nt\nu\n \nn\ny\no\nn\ns\no\n,\n \nn\na\n \nm\nb\nu\nt\nu\nk\nu\nl\nu\n \nk\ne\nv\nw\na\nn\nd\na\nk\na\n \nn\na\n \nk\ni\nm\np\nw\na\nn\nz\na\n \ny\na\n \nb\na\nw\nu\n,\n \nn\ng\ne\nn\nd\na\n \nm\np\ne\n \nb\na\nl\nu\nv\ne\n \ny\na\n \nm\nu\nt\ni\nn\nd\nu\n \nm\no\ns\ni\n.\n \nM\na\ny\ne\nl\na\n \nn\na\n \nm\nb\na\nn\nz\nu\nl\nu\n \nj\ne\n \nn\na\n \nb\na\nw\nu\n,\n \nn\ni\n \ny\na\nw\nu\n \ny\ni\nn\na\n \nb\na\nf\nw\na\nn\na\n \nk\nu\ns\na\nl\na\ns\na\nn\na\n \nn\na\n \nb\nu\nm\np\na\nn\ng\ni\n.\nB\na\nn\nt\nu\n \nn\ny\no\nn\ns\no\n,\n \nn\na\n \nm\nb\nu\nt\nu\nk\nu\nl\nu\n \nk\ne\nv\nw\na\nn\nd\na\nk\na\n \nn\na\n \nk\ni\nm\np\nw\na\nn\nz\na\n \ny\na\n \nb\na\nw\nu\n,\n \nn\ng\ne\nn\nd\na\n \nm\np\ne\n \nb\na\nl\nu\nv\ne\n \ny\na\n \nm\nu\nt\ni\nn\nd\nu\n \nm\no\ns\ni\n.\n \nM\na\ny\ne\nl\na\n \nn\na\n \nm\nb\na\nn\nz"
}
