id: "ku"
language: "ku"
script: "Cyrl"
name: "Kurdish"
population: 6773773
region: "AM"
region: "AZ"
region: "DE"
region: "GE"
region: "SY"
region: "TM"
region: "TR"
exemplar_chars {
  base: "a b c ç d e ê f g h i î j k l m n o p q r s ş t u û v w x y z"
  auxiliary: "á à ă â å ä ã ā æ è ĕ ë ē é ì ĭ ï ī í ñ ó ò ŏ ô ø ō œ ß ù ŭ ū ú ÿ"
  marks: "◌̆ ◌̈"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ \" “ ” ( ) [ ] § @ * / & # † ‡ ′ ″"
  index: "A B C Ç D E Ê F G H I Î J K L M N O P Q R S Ş T U Û V W X Y Z"
}
sample_text {
  masthead_full: "HhEe"
  masthead_partial: "Mm"
  styles: "Herwekî nasîna weqara pêgirê hemû endamên"
  tester: "Herwekî nenasîn û piçûkdîtina mafên mirov rê dan barbar ku wijdana"
  poster_sm: "Herweki bingehî"
  poster_md: "wekî îdeala"
  poster_lg: "Hemû"
  specimen_48: "Hemû mirov azad û di weqar û mafan de wekhev tên dinyayê. Ew xwedî"
  specimen_36: "Ewê tukes di koletî an bindestiyê de neyê girtin; koletî û bazirganiya koleyan bi hemû teşeyên xwe ve qedexe ne."
  specimen_32: "Herkes maf heye ku li hemberî kirinên ku mafên bingehî yên ku qanûna bingehî an qanûn jê re dinasin ihlal dikin, serî li mehkemeyên neteweyî yên selahiyetdar bixe."
  specimen_21: "Tukes nikare bi awayekî kêfî bê girtin, hebs an sirgûn kirin.\nHerkes, di wekheviyeke temamî de, maf heye ku doza wî li ber mehkemeyeke serbixwe û bê alî bi awayekî adil û eşkere bê bihîstin ji bo diyarkirina maf û wacibên wî û ya her tawana curmî li dijî wî.\nNabe ku tukes bibe amanca têkilbûnên kêfî yên nav jiyana wî ya arizî, malbata wî, mala wî an nameyên wî, an ziyangihandina şeref û şana wî. Herkes xwediyê mafê parastina qanûn e li hemberî têkilbûn û ziyangihanên wilo."
  specimen_16: "Herkes mafê azadiya fikr, wijdan û olê heye; azadiya ol an bawerî guhartin û azadiya ol û baweriya xwe bi tenê an bi hev re him eşkere him arizî, bi hînkirin, emel, îbadet û bicihanîna ayînan nîşandanê jî di nav vî mafî de ne.\nHerkes mafê azadiya fikr û îfade heye; mafê ji ber ramanên xwe nehatin êşandin û herweha mafê bêî nasîna tu sînoran û bi her cure navgînan li agahdariyan û fikran gerîn, wan bi dest xistin û îfade û belavkirin dikevin nav vî mafî.\nHerkes, wekî endamê civakî, mafê ewleyiya sosyal heye; Ew mafdar e ku bi riya xebata neteweyî û hevkariya navneteweyî û li gora tenzîm û hatiniyên her dewletê, doza bidestxistina mafên aborî, civakî û çandî yên ku jo bo weqara wî û geşbûna serbest a şexsiyeta wî ferz in, bike."
}
