id: "ku_Arab"
name: "Kurdish (Arabic)"
preferred_name: ""
autonym: ""
population: 92983
region: "LB"
script: "Cyrillic"
script: "Latin"
script: "Perso-Arabic"
exemplar_chars {
}
sample_text {
  fallback_language: "uz"
}
