id: "ku_Latn"
language: "ku"
script: "Latn"
name: "Kurdish, Latin"
autonym: "Kurmancî"
population: 0
region: "TR"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ç Ê Î Ş Û a b c d e f g h i j k l m n o p q r s t u v w x y z ç ê î ş û"
  auxiliary: "Ḧ Ẍ ḧ ẍ \'"
  marks: "◌̂ ◌̧ ◌̈"
}
sample_text {
  masthead_full: "HhEe"
  masthead_partial: "Mm"
  styles: "Hemû mirov azad û di weqar û mafan de wekhev"
  tester: "Hemû mirov azad û di weqar û mafan de wekhev tên dinyayê. Ew xwedî"
  poster_sm: "Hemû mirov"
  poster_md: "Hemû mirov"
  poster_lg: "Hemû"
  specimen_48: "Hemû mirov azad û di weqar û mafan de wekhev tên dinyayê."
  specimen_36: "Hemû mirov azad û di weqar û mafan de wekhev tên dinyayê. Ew xwedî hiş û şuûr in û divê li hember hev bi zihniyeteke bratiyê bilivin."
  specimen_32: "Hemû mirov azad û di weqar û mafan de wekhev tên dinyayê. Ew xwedî hiş û şuûr in û divê li hember hev bi zihniyeteke bratiyê bilivin."
  specimen_21: "Hemû mirov azad û di weqar û mafan de wekhev tên dinyayê. Ew xwedî hiş û şuûr in û divê li hember hev bi zihniyeteke bratiyê bilivin.\nHemû mirov azad û di weqar û mafan de wekhev tên dinyayê. Ew xwedî hiş û şuûr in û divê li hember hev bi zihniyeteke bratiyê bilivin.\nHemû mirov azad û di weqar û mafan de wekhev tên dinyayê. Ew xwedî hiş û şuûr in û divê li hember hev bi zihniyeteke bratiyê bilivin."
  specimen_16: "Hemû mirov azad û di weqar û mafan de wekhev tên dinyayê. Ew xwedî hiş û şuûr in û divê li hember hev bi zihniyeteke bratiyê bilivin.\nHemû mirov azad û di weqar û mafan de wekhev tên dinyayê. Ew xwedî hiş û şuûr in û divê li hember hev bi zihniyeteke bratiyê bilivin.\nHemû mirov azad û di weqar û mafan de wekhev tên dinyayê. Ew xwedî hiş û şuûr in û divê li hember hev bi zihniyeteke bratiyê bilivin.\nHemû mirov azad û di weqar û mafan de wekhev tên dinyayê. Ew xwedî hiş û şuûr in û divê li hember hev bi zihniyeteke bratiyê bilivin.\nHemû mirov azad û di weqar û mafan de wekhev tên dinyayê. Ew xwedî hiş û şuûr in û divê li hember hev bi zihniyeteke bratiyê bilivin."
}
