id: "kwi_Latn"
language: "kwi"
script: "Latn"
name: "Awa-Cuaiquer"
region: "CO"
region: "US"
sample_text {
  masthead_full: ""
  masthead_partial: ""
  styles: "[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]"
  tester: "[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]"
  poster_sm: "[?]\n[?]\n[?]"
  poster_md: "[?]\n[?]\n[?]"
  poster_lg: "[?]"
  specimen_48: "[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]"
  specimen_36: "[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]"
  specimen_32: "[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]"
  specimen_21: "[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]"
  specimen_16: "[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]\n[?]"
}
