id: "ky"
language: "ky"
script: "Cyrl"
name: "Kyrgyz"
autonym: "Кыргызча"
population: 2863152
region: "KG"
exemplar_chars {
  base: "а б г д е ё ж з и й к л м н ң о ө п р с т у ү х ч ш ъ ы э ю я"
  auxiliary: "в ф ц щ ь"
  marks: "◌̆ ◌̈"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ‚ \" “ „ « » ( ) [ ] { } § @ * / & # { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "А Б В Г Д Е Ё Ж З И Й К Л М Н Ң О Ө П Р С Т У Ү Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я"
}
sample_text {
  masthead_full: "БбАа"
  masthead_partial: "Рр"
  styles: "Адамзат үй‐бүлөсүнүн бардык мүчөлөрүнөтаандык"
  tester: "адам укуктарын этибарга албоо жана жеккөрүү адамзатынын абийирин"
  poster_sm: "адам акыркы"
  poster_md: "элдердин"
  poster_lg: "Бардык"
  specimen_48: "Бириккен Улуттардын элдери Уставда адамдардын негизги укуктарына,"
  specimen_36: "Эч ким кулчулукта же эрксиз абалда болууга тийиш эмес; кулчулук менен кул сатуучулуктун бардык түрлөрүнө тыюу салынат."
  specimen_32: "Ар бир адам, ага конституция жана мыйзам тарабынан берилген негизги укуктары бузулган учурларда компетентүү улуттук соттор тарабынан укуктарын толук калыбына келтирүү укугуна ээ."
  specimen_21: "Эч ким ээнбаштык менен камакка алынууга, кармалууга же куугунтукталууга тийиш эмес.\nАр бир адам өз укуктары менен милдеттенмелерин аныктоо үчүн жана ага коюлган кылмыш жоопкерчилигинин негиздү үлүгүн аныктоо үчүн толук тең диктин негизинде анын иши маалымдуу түрдө жана көз каранды эмес жана калыс сот тарабынан жана адилеттү үлүктүн бардык талаптарын сактоо менен каралышына жетишү үгөукуктуу."
  specimen_16: "Эч ким анын жеке жана үй‐бүлөлүк турмушуна ээнбаштык менен кийлигишү үгө, анын турак жайынын кол тийбестигине, анын кат‐кабарларынын жашыруундугуна жеанын намысына жана кадыр‐баркына ээнбаштык менен кол салууга дуушар болушу мү мкү н эмес. Ар бир адам мындай кийлигишүү дөн же ушундай кол салуудан мыйзам тарабынан корголууга укуктуу.\nАр бир адам ой, ыйман, дин эркиндиктерине укуктуу; бул укук өз динин же ынанымын эркинче өзгөртүүнү жана жеке өзү, ошондой эле башкалар менен бирге каалаган динин тутуу же ынануу эркиндигин эл менен бирге же жеке өзүнчө динди үйрөнүүнү, кудайга сыйынууну жана диндик жөрөлгөлүү ырасымдарды аткарууну камтыйт."
}
