id: "ky_Arab"
language: "ky"
script: "Arab"
name: "Kyrgyz (Arabic)"
population: 473966
region: "CN"
sample_text {
  masthead_full: "بارد"
  masthead_partial: "ىق"
  styles: "ب\nا\nر\nد\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nۅ\nز\n \nب\nە\nد"
  tester: "ب\nا\nر\nد\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nۅ\nز\n \nب\nە\nد\nە\nل\nى\nن\nد\nە\n \nج\nا\nن"
  poster_sm: "ب\nا\nر\nد\nى\nق"
  poster_md: "ب\nا\nر\nد\nى"
  poster_lg: "ب\nا"
  specimen_48: "ب\nا\nر\nد\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nۅ\nز\n \nب\nە\nد\nە\nل\nى\nن\nد\nە\n \nج\nا\nن"
  specimen_36: "ب\nا\nر\nد\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nۅ\nز\n \nب\nە\nد\nە\nل\nى\nن\nد\nە\n \nج\nا\nن\nا\n \nۇ\nق\nۇ\nق\nت\nا\nر\nى\nن\nد\nا\n \nە\nر\nك\nى\nن\n "
  specimen_32: "ب\nا\nر\nد\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nۅ\nز\n \nب\nە\nد\nە\nل\nى\nن\nد\nە\n \nج\nا\nن\nا\n \nۇ\nق\nۇ\nق\nت\nا\nر\nى\nن\nد\nا\n \nە\nر\nك\nى\nن\n \nج\nا\nن\nا\n \nت\nە\nڭ\n \nۇ\nق\nۇ\nق\nت\nۇ\nۇ\n \nب\nو\nل"
  specimen_21: "ب\nا\nر\nد\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nۅ\nز\n \nب\nە\nد\nە\nل\nى\nن\nد\nە\n \nج\nا\nن\nا\n \nۇ\nق\nۇ\nق\nت\nا\nر\nى\nن\nد\nا\n \nە\nر\nك\nى\nن\n \nج\nا\nن\nا\n \nت\nە\nڭ\n \nۇ\nق\nۇ\nق\nت\nۇ\nۇ\n \nب\nو\nل\nۇ\nپ\n \nج\nا\nر\nا\nل\nا\nت\n.\n۔\n \nا\nل\nا\nر\nد\nى\nن\n \nا\nڭ\n-\nس\nە\nز\nى\nم\nى\n \nم\nە\nن\nە\nن\n \nا\nب\nئ\nي\nى\nر\nى\n \nب\nا\nر\n \nج\nا\nن\nا\n \nب\nئ\nر\nى\n-\nب\nئ\nر\nى\nن\nە\n \nب\nئ\nر\n \nت\nۇ\nۇ\nع\nا\nن\nد\nى\nق\n \nم\nا"
  specimen_16: "ب\nا\nر\nد\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nۅ\nز\n \nب\nە\nد\nە\nل\nى\nن\nد\nە\n \nج\nا\nن\nا\n \nۇ\nق\nۇ\nق\nت\nا\nر\nى\nن\nد\nا\n \nە\nر\nك\nى\nن\n \nج\nا\nن\nا\n \nت\nە\nڭ\n \nۇ\nق\nۇ\nق\nت\nۇ\nۇ\n \nب\nو\nل\nۇ\nپ\n \nج\nا\nر\nا\nل\nا\nت\n.\n۔\n \nا\nل\nا\nر\nد\nى\nن\n \nا\nڭ\n-\nس\nە\nز\nى\nم\nى\n \nم\nە\nن\nە\nن\n \nا\nب\nئ\nي\nى\nر\nى\n \nب\nا\nر\n \nج\nا\nن\nا\n \nب\nئ\nر\nى\n-\nب\nئ\nر\nى\nن\nە\n \nب\nئ\nر\n \nت\nۇ\nۇ\nع\nا\nن\nد\nى\nق\n \nم\nا\nم\nئ\nل\nە\n \nق\nى\nل\nۇ\nۇ\nع\nا\n \nت\nئ\nي\nى\nش\nب\nا\nر\nد\nى\nق\n \nا\nد\nا\nم\nد\nا\nر\n \nۅ\nز\n \nب\nە\nد\nە\nل\nى\nن\nد\nە\n \nج\nا\nن\nا\n \nۇ\nق\nۇ\nق\nت\nا\nر\nى\nن\nد\nا\n \nە\nر\nك\nى\nن\n \nج\nا\nن\nا\n \nت\nە\nڭ\n \nۇ\nق\nۇ\nق\nت\nۇ\nۇ\n \nب\nو\nل\nۇ\nپ\n \nج\nا\nر\nا\nل\nا\nت\n.\n۔\n \nا\nل\nا\nر\nد\nى\nن\n \nا\nڭ\n-\nس\nە\nز\nى\nم\nى\n \nم\nە\nن\nە\nن\n "
}
