id: "kyw_Orya"
language: "kyw"
script: "Orya"
name: "Kudmali, Odia"
region: "IN"
sample_text {
  masthead_full: "ସଭମନ"
  masthead_partial: "ଧତ"
  styles: "ସଭେ ମାନସି ସାଧିନମତେ ସମାନ ମଇର୍ଜାତ ଆର ହକଦାରି ଲେଇକେ ଜନମ ଲେତେକ।"
  tester: "ସଭେ ମାନସି ସାଧିନମତେ ସମାନ ମଇର୍ଜାତ ଆର ହକଦାରି ଲେଇକେ ଜନମ ଲେତେକ। ତାହାରାକାର ଆଁଗାସ ଆର ବୁଇଧ ଆହେକ"
  poster_sm: "ସଭେ ମାନସି ସାଧିନମତେ"
  poster_md: "ସଭେ ମାନସି ସ"
  poster_lg: "ମାନସି"
  specimen_48: "ସଭେ ମାନସି ସାଧିନମତେ ସମାନ ମଇର୍ଜାତ ଆର ହକଦାରି ଲେଇକେ ଜନମ ଲେତେକ। ତାହାରାକାର ଆଁଗାସ ଆର ବୁଇଧ ଆହେକ ତାହେ"
  specimen_36: "ସଭେ ମାନସି ସାଧିନମତେ ସମାନ ମଇର୍ଜାତ ଆର ହକଦାରି ଲେଇକେ ଜନମ ଲେତେକ। ତାହାରାକାର ଆଁଗାସ ଆର ବୁଇଧ ଆହେକ ତାହେ ସଭେକର ଏକେ ଆନେକ ଉପର ଭାୟାଚାରି ମନେକ ଭାବ ଲେଇକେ ଆଚାର କେରା ଉଚିତ।"
  specimen_32: "ସଭେ ମାନସି ସାଧିନମତେ ସମାନ ମଇର୍ଜାତ ଆର ହକଦାରି ଲେଇକେ ଜନମ ଲେତେକ। ତାହାରାକାର ଆଁଗାସ ଆର ବୁଇଧ ଆହେକ ତାହେ ସଭେକର ଏକେ ଆନେକ ଉପର ଭାୟାଚାରି ମନେକ ଭାବ ଲେଇକେ ଆଚାର କେରା ଉଚିତ।"
  specimen_21: "ସଭେ ମାନସି ସାଧିନମତେ ସମାନ ମଇର୍ଜାତ ଆର ହକଦାରି ଲେଇକେ ଜନମ ଲେତେକ। ତାହାରାକାର ଆଁଗାସ ଆର ବୁଇଧ ଆହେକ ତାହେ ସଭେକର ଏକେ ଆନେକ ଉପର ଭାୟାଚାରି ମନେକ ଭାବ ଲେଇକେ ଆଚାର କେରା ଉଚିତ।\nସଭେ ମାନସି ସାଧିନମତେ ସମାନ ମଇର୍ଜାତ ଆର ହକଦାରି ଲେଇକେ ଜନମ ଲେତେକ। ତାହାରାକାର ଆଁଗାସ ଆର ବୁଇଧ ଆହେକ ତାହେ ସଭେକର ଏକେ ଆନେକ ଉପର ଭାୟାଚାରି ମନେକ ଭାବ ଲେଇକେ ଆଚାର କେରା ଉଚିତ।\nସଭେ ମାନସି ସାଧିନମତେ ସମାନ ମଇର୍ଜାତ ଆର ହକଦାରି ଲେଇକେ ଜନମ ଲେତେକ। ତାହାରାକାର ଆଁଗାସ ଆର ବୁଇଧ ଆହେକ ତାହେ ସଭେକର ଏକେ ଆନେକ ଉପର ଭାୟାଚାରି ମନେକ ଭାବ ଲେଇକେ ଆଚାର କେରା ଉଚିତ।"
  specimen_16: "ସଭେ ମାନସି ସାଧିନମତେ ସମାନ ମଇର୍ଜାତ ଆର ହକଦାରି ଲେଇକେ ଜନମ ଲେତେକ। ତାହାରାକାର ଆଁଗାସ ଆର ବୁଇଧ ଆହେକ ତାହେ ସଭେକର ଏକେ ଆନେକ ଉପର ଭାୟାଚାରି ମନେକ ଭାବ ଲେଇକେ ଆଚାର କେରା ଉଚିତ।\nସଭେ ମାନସି ସାଧିନମତେ ସମାନ ମଇର୍ଜାତ ଆର ହକଦାରି ଲେଇକେ ଜନମ ଲେତେକ। ତାହାରାକାର ଆଁଗାସ ଆର ବୁଇଧ ଆହେକ ତାହେ ସଭେକର ଏକେ ଆନେକ ଉପର ଭାୟାଚାରି ମନେକ ଭାବ ଲେଇକେ ଆଚାର କେରା ଉଚିତ।\nସଭେ ମାନସି ସାଧିନମତେ ସମାନ ମଇର୍ଜାତ ଆର ହକଦାରି ଲେଇକେ ଜନମ ଲେତେକ। ତାହାରାକାର ଆଁଗାସ ଆର ବୁଇଧ ଆହେକ ତାହେ ସଭେକର ଏକେ ଆନେକ ଉପର ଭାୟାଚାରି ମନେକ ଭାବ ଲେଇକେ ଆଚାର କେରା ଉଚିତ।\nସଭେ ମାନସି ସାଧିନମତେ ସମାନ ମଇର୍ଜାତ ଆର ହକଦାରି ଲେଇକେ ଜନମ ଲେତେକ। ତାହାରାକାର ଆଁଗାସ ଆର ବୁଇଧ ଆହେକ ତାହେ ସଭେକର ଏକେ ଆନେକ ଉପର ଭାୟାଚାରି ମନେକ ଭାବ ଲେଇକେ ଆଚାର କେରା ଉଚିତ।\nସଭେ ମାନସି ସାଧିନମତେ ସମାନ ମଇର୍ଜାତ ଆର ହକଦାରି ଲେଇକେ ଜନମ ଲେତେକ। ତାହାରାକାର ଆଁଗାସ ଆର ବୁଇଧ ଆହେକ ତାହେ ସଭେକର ଏକେ ଆନେକ ଉପର ଭାୟାଚାରି ମନେକ ଭାବ ଲେଇକେ ଆଚାର କେରା ଉଚିତ।\nସଭେ ମାନସି ସାଧିନମତେ ସମାନ ମଇର୍ଜାତ ଆର ହକଦାରି ଲେଇକେ ଜନମ ଲେତେକ। ତାହାରାକାର ଆଁଗାସ ଆର ବୁଇଧ ଆହେକ ତାହେ ସଭେକର ଏକେ ଆନେକ ଉପର ଭାୟାଚାରି ମନେକ ଭାବ ଲେଇକେ ଆଚାର କେରା ଉଚିତ।"
}
