id: "kyw_Orya"
language: "kyw"
script: "Orya"
name: "Kudmali, Odia"
sample_text {
  masthead_full: "ସଭମନ"
  masthead_partial: "ଧତ"
  styles: "ସ\nଭ\nେ\n \nମ\nା\nନ\nସ\nି\n \nସ\nା\nଧ\nି\nନ\nମ\nତ\nେ\n \nସ\nମ\nା\nନ\n "
  tester: "ସ\nଭ\nେ\n \nମ\nା\nନ\nସ\nି\n \nସ\nା\nଧ\nି\nନ\nମ\nତ\nେ\n \nସ\nମ\nା\nନ\n \nମ\nଇ\nର\n୍\nଜ\nା\nତ\n \nଆ\nର\n "
  poster_sm: "ସ\nଭ\nେ\n \nମ\nା\nନ"
  poster_md: "ସ\nଭ\nେ\n \nମ"
  poster_lg: "ସ\nଭ"
  specimen_48: "ସ\nଭ\nେ\n \nମ\nା\nନ\nସ\nି\n \nସ\nା\nଧ\nି\nନ\nମ\nତ\nେ\n \nସ\nମ\nା\nନ\n \nମ\nଇ\nର\n୍\nଜ\nା\nତ\n \nଆ\nର\n "
  specimen_36: "ସ\nଭ\nେ\n \nମ\nା\nନ\nସ\nି\n \nସ\nା\nଧ\nି\nନ\nମ\nତ\nେ\n \nସ\nମ\nା\nନ\n \nମ\nଇ\nର\n୍\nଜ\nା\nତ\n \nଆ\nର\n \nହ\nକ\nଦ\nା\nର\nି\n \nଲ\nେ\nଇ\nକ\nେ\n \nଜ\nନ\nମ\n \nଲ\nେ\nତ\nେ\nକ\n।\n "
  specimen_32: "ସ\nଭ\nେ\n \nମ\nା\nନ\nସ\nି\n \nସ\nା\nଧ\nି\nନ\nମ\nତ\nେ\n \nସ\nମ\nା\nନ\n \nମ\nଇ\nର\n୍\nଜ\nା\nତ\n \nଆ\nର\n \nହ\nକ\nଦ\nା\nର\nି\n \nଲ\nେ\nଇ\nକ\nେ\n \nଜ\nନ\nମ\n \nଲ\nେ\nତ\nେ\nକ\n।\n \nତ\nା\nହ\nା\nର\nା\nକ\nା\nର\n \nଆ\nଁ\nଗ\nା\nସ\n \nଆ\nର\n \nବ\nୁ\nଇ\nଧ"
  specimen_21: "ସ\nଭ\nେ\n \nମ\nା\nନ\nସ\nି\n \nସ\nା\nଧ\nି\nନ\nମ\nତ\nେ\n \nସ\nମ\nା\nନ\n \nମ\nଇ\nର\n୍\nଜ\nା\nତ\n \nଆ\nର\n \nହ\nକ\nଦ\nା\nର\nି\n \nଲ\nେ\nଇ\nକ\nେ\n \nଜ\nନ\nମ\n \nଲ\nେ\nତ\nେ\nକ\n।\n \nତ\nା\nହ\nା\nର\nା\nକ\nା\nର\n \nଆ\nଁ\nଗ\nା\nସ\n \nଆ\nର\n \nବ\nୁ\nଇ\nଧ\n \nଆ\nହ\nେ\nକ\n \nତ\nା\nହ\nେ\n \nସ\nଭ\nେ\nକ\nର\n \nଏ\nକ\nେ\n \nଆ\nନ\nେ\nକ\n \nଉ\nପ\nର\n \nଭ\nା\nୟ\nା\nଚ\nା\nର\nି\n \nମ\nନ\nେ\nକ\n \nଭ\nା\nବ\n \nଲ\nେ\nଇ\nକ\nେ\n \nଆ\nଚ\nା\nର\n \nକ\nେ\nର\nା\n \nଉ\nଚ\nି\nତ\n।\nସ\nଭ\nେ\n \nମ\nା\nନ\nସ\nି\n \nସ\nା\nଧ\nି\nନ\nମ\nତ\nେ\n \nସ\nମ\nା\nନ\n "
  specimen_16: "ସ\nଭ\nେ\n \nମ\nା\nନ\nସ\nି\n \nସ\nା\nଧ\nି\nନ\nମ\nତ\nେ\n \nସ\nମ\nା\nନ\n \nମ\nଇ\nର\n୍\nଜ\nା\nତ\n \nଆ\nର\n \nହ\nକ\nଦ\nା\nର\nି\n \nଲ\nେ\nଇ\nକ\nେ\n \nଜ\nନ\nମ\n \nଲ\nେ\nତ\nେ\nକ\n।\n \nତ\nା\nହ\nା\nର\nା\nକ\nା\nର\n \nଆ\nଁ\nଗ\nା\nସ\n \nଆ\nର\n \nବ\nୁ\nଇ\nଧ\n \nଆ\nହ\nେ\nକ\n \nତ\nା\nହ\nେ\n \nସ\nଭ\nେ\nକ\nର\n \nଏ\nକ\nେ\n \nଆ\nନ\nେ\nକ\n \nଉ\nପ\nର\n \nଭ\nା\nୟ\nା\nଚ\nା\nର\nି\n \nମ\nନ\nେ\nକ\n \nଭ\nା\nବ\n \nଲ\nେ\nଇ\nକ\nେ\n \nଆ\nଚ\nା\nର\n \nକ\nେ\nର\nା\n \nଉ\nଚ\nି\nତ\n।\nସ\nଭ\nେ\n \nମ\nା\nନ\nସ\nି\n \nସ\nା\nଧ\nି\nନ\nମ\nତ\nେ\n \nସ\nମ\nା\nନ\n \nମ\nଇ\nର\n୍\nଜ\nା\nତ\n \nଆ\nର\n \nହ\nକ\nଦ\nା\nର\nି\n \nଲ\nେ\nଇ\nକ\nେ\n \nଜ\nନ\nମ\n \nଲ\nେ\nତ\nେ\nକ\n।\n \nତ\nା\nହ\nା\nର\nା\nକ\nା\nର\n \nଆ\nଁ\nଗ\nା\nସ\n \nଆ\nର\n \nବ\nୁ\nଇ\nଧ\n \nଆ\nହ\nେ\nକ\n \nତ\nା\nହ\nେ\n \nସ\nଭ\nେ\nକ\nର\n \nଏ\nକ\nେ\n \nଆ\nନ\nେ\nକ\n \nଉ\nପ\nର\n \nଭ\nା\nୟ\nା\nଚ\nା\nର\nି\n \nମ\nନ\nେ\nକ\n \nଭ\nା\nବ\n \nଲ\nେ\nଇ\nକ\nେ\n \nଆ\nଚ\nା\nର\n \nକ\nେ\nର\nା\n \nଉ\nଚ\nି\nତ\n।\nସ\nଭ\nେ\n \nମ\nା\nନ\nସ\nି\n \nସ\nା\nଧ\nି\nନ\nମ\nତ\nେ\n "
}
