id: "kyw_Beng"
language: "kyw"
script: "Beng"
name: "Kudmali, Bangla"
sample_text {
  masthead_full: "সভমন"
  masthead_partial: "ধত"
  styles: "স\nভ\nে\n \nম\nা\nন\nস\nি\n \nস\nা\nধ\nি\nন\nম\nত\nে\n \nস\nম\nা\nন\n "
  tester: "স\nভ\nে\n \nম\nা\nন\nস\nি\n \nস\nা\nধ\nি\nন\nম\nত\nে\n \nস\nম\nা\nন\n \nম\nই\nর\n্\nজ\nা\nত\n \nআ\nর\n "
  poster_sm: "স\nভ\nে\n \nম\nা\nন"
  poster_md: "স\nভ\nে\n \nম"
  poster_lg: "স\nভ"
  specimen_48: "স\nভ\nে\n \nম\nা\nন\nস\nি\n \nস\nা\nধ\nি\nন\nম\nত\nে\n \nস\nম\nা\nন\n \nম\nই\nর\n্\nজ\nা\nত\n \nআ\nর\n "
  specimen_36: "স\nভ\nে\n \nম\nা\nন\nস\nি\n \nস\nা\nধ\nি\nন\nম\nত\nে\n \nস\nম\nা\nন\n \nম\nই\nর\n্\nজ\nা\nত\n \nআ\nর\n \nহ\nক\nদ\nা\nর\nি\n \nল\nে\nই\nক\nে\n \nজ\nন\nম\n \nল\nে\nত\nে\nক\n।\n "
  specimen_32: "স\nভ\nে\n \nম\nা\nন\nস\nি\n \nস\nা\nধ\nি\nন\nম\nত\nে\n \nস\nম\nা\nন\n \nম\nই\nর\n্\nজ\nা\nত\n \nআ\nর\n \nহ\nক\nদ\nা\nর\nি\n \nল\nে\nই\nক\nে\n \nজ\nন\nম\n \nল\nে\nত\nে\nক\n।\n \nত\nা\nহ\nা\nর\nা\nক\nা\nর\n \nআ\nঁ\nগ\nা\nস\n \nআ\nর\n \nব\nু\nই\nধ"
  specimen_21: "স\nভ\nে\n \nম\nা\nন\nস\nি\n \nস\nা\nধ\nি\nন\nম\nত\nে\n \nস\nম\nা\nন\n \nম\nই\nর\n্\nজ\nা\nত\n \nআ\nর\n \nহ\nক\nদ\nা\nর\nি\n \nল\nে\nই\nক\nে\n \nজ\nন\nম\n \nল\nে\nত\nে\nক\n।\n \nত\nা\nহ\nা\nর\nা\nক\nা\nর\n \nআ\nঁ\nগ\nা\nস\n \nআ\nর\n \nব\nু\nই\nধ\n \nআ\nহ\nে\nক\n \nত\nা\nহ\nে\n \nস\nভ\nে\nক\nর\n \nএ\nক\nে\n \nআ\nন\nে\nক\n \nউ\nপ\nর\n \nভ\nা\nয়\nা\nচ\nা\nর\nি\n \nম\nন\nে\nক\n \nভ\nা\nব\n \nল\nে\nই\nক\nে\n \nআ\nচ\nা\nর\n \nক\nে\nর\nা\n \nউ\nচ\nি\nত\n।\nস\nভ\nে\n \nম\nা\nন\nস\nি\n \nস\nা\nধ\nি\nন\nম\nত\nে\n \nস\nম\nা\nন\n "
  specimen_16: "স\nভ\nে\n \nম\nা\nন\nস\nি\n \nস\nা\nধ\nি\nন\nম\nত\nে\n \nস\nম\nা\nন\n \nম\nই\nর\n্\nজ\nা\nত\n \nআ\nর\n \nহ\nক\nদ\nা\nর\nি\n \nল\nে\nই\nক\nে\n \nজ\nন\nম\n \nল\nে\nত\nে\nক\n।\n \nত\nা\nহ\nা\nর\nা\nক\nা\nর\n \nআ\nঁ\nগ\nা\nস\n \nআ\nর\n \nব\nু\nই\nধ\n \nআ\nহ\nে\nক\n \nত\nা\nহ\nে\n \nস\nভ\nে\nক\nর\n \nএ\nক\nে\n \nআ\nন\nে\nক\n \nউ\nপ\nর\n \nভ\nা\nয়\nা\nচ\nা\nর\nি\n \nম\nন\nে\nক\n \nভ\nা\nব\n \nল\nে\nই\nক\nে\n \nআ\nচ\nা\nর\n \nক\nে\nর\nা\n \nউ\nচ\nি\nত\n।\nস\nভ\nে\n \nম\nা\nন\nস\nি\n \nস\nা\nধ\nি\nন\nম\nত\nে\n \nস\nম\nা\nন\n \nম\nই\nর\n্\nজ\nা\nত\n \nআ\nর\n \nহ\nক\nদ\nা\nর\nি\n \nল\nে\nই\nক\nে\n \nজ\nন\nম\n \nল\nে\nত\nে\nক\n।\n \nত\nা\nহ\nা\nর\nা\nক\nা\nর\n \nআ\nঁ\nগ\nা\nস\n \nআ\nর\n \nব\nু\nই\nধ\n \nআ\nহ\nে\nক\n \nত\nা\nহ\nে\n \nস\nভ\nে\nক\nর\n \nএ\nক\nে\n \nআ\nন\nে\nক\n \nউ\nপ\nর\n \nভ\nা\nয়\nা\nচ\nা\nর\nি\n \nম\nন\nে\nক\n \nভ\nা\nব\n \nল\nে\nই\nক\nে\n \nআ\nচ\nা\nর\n \nক\nে\nর\nা\n \nউ\nচ\nি\nত\n।\nস\nভ\nে\n \nম\nা\nন\nস\nি\n \nস\nা\nধ\nি\nন\nম\nত\nে\n "
}
