id: "kyw_Beng"
language: "kyw"
script: "Beng"
name: "Kudmali, Bangla"
region: "IN"
sample_text {
  masthead_full: "সভমন"
  masthead_partial: "ধত"
  styles: "সভে মানসি সাধিনমতে সমান মইর্জাত আর হকদারি লেইকে জনম লেতেক।"
  tester: "সভে মানসি সাধিনমতে সমান মইর্জাত আর হকদারি লেইকে জনম লেতেক। তাহারাকার আঁগাস আর বুইধ আহেক"
  poster_sm: "সভে মানসি সাধিনমতে"
  poster_md: "সভে মানসি স"
  poster_lg: "মানসি"
  specimen_48: "সভে মানসি সাধিনমতে সমান মইর্জাত আর হকদারি লেইকে জনম লেতেক। তাহারাকার আঁগাস আর বুইধ আহেক তাহে"
  specimen_36: "সভে মানসি সাধিনমতে সমান মইর্জাত আর হকদারি লেইকে জনম লেতেক। তাহারাকার আঁগাস আর বুইধ আহেক তাহে সভেকর একে আনেক উপর ভায়াচারি মনেক ভাব লেইকে আচার কেরা উচিত।"
  specimen_32: "সভে মানসি সাধিনমতে সমান মইর্জাত আর হকদারি লেইকে জনম লেতেক। তাহারাকার আঁগাস আর বুইধ আহেক তাহে সভেকর একে আনেক উপর ভায়াচারি মনেক ভাব লেইকে আচার কেরা উচিত।"
  specimen_21: "সভে মানসি সাধিনমতে সমান মইর্জাত আর হকদারি লেইকে জনম লেতেক। তাহারাকার আঁগাস আর বুইধ আহেক তাহে সভেকর একে আনেক উপর ভায়াচারি মনেক ভাব লেইকে আচার কেরা উচিত।\nসভে মানসি সাধিনমতে সমান মইর্জাত আর হকদারি লেইকে জনম লেতেক। তাহারাকার আঁগাস আর বুইধ আহেক তাহে সভেকর একে আনেক উপর ভায়াচারি মনেক ভাব লেইকে আচার কেরা উচিত।\nসভে মানসি সাধিনমতে সমান মইর্জাত আর হকদারি লেইকে জনম লেতেক। তাহারাকার আঁগাস আর বুইধ আহেক তাহে সভেকর একে আনেক উপর ভায়াচারি মনেক ভাব লেইকে আচার কেরা উচিত।"
  specimen_16: "সভে মানসি সাধিনমতে সমান মইর্জাত আর হকদারি লেইকে জনম লেতেক। তাহারাকার আঁগাস আর বুইধ আহেক তাহে সভেকর একে আনেক উপর ভায়াচারি মনেক ভাব লেইকে আচার কেরা উচিত।\nসভে মানসি সাধিনমতে সমান মইর্জাত আর হকদারি লেইকে জনম লেতেক। তাহারাকার আঁগাস আর বুইধ আহেক তাহে সভেকর একে আনেক উপর ভায়াচারি মনেক ভাব লেইকে আচার কেরা উচিত।\nসভে মানসি সাধিনমতে সমান মইর্জাত আর হকদারি লেইকে জনম লেতেক। তাহারাকার আঁগাস আর বুইধ আহেক তাহে সভেকর একে আনেক উপর ভায়াচারি মনেক ভাব লেইকে আচার কেরা উচিত।\nসভে মানসি সাধিনমতে সমান মইর্জাত আর হকদারি লেইকে জনম লেতেক। তাহারাকার আঁগাস আর বুইধ আহেক তাহে সভেকর একে আনেক উপর ভায়াচারি মনেক ভাব লেইকে আচার কেরা উচিত।\nসভে মানসি সাধিনমতে সমান মইর্জাত আর হকদারি লেইকে জনম লেতেক। তাহারাকার আঁগাস আর বুইধ আহেক তাহে সভেকর একে আনেক উপর ভায়াচারি মনেক ভাব লেইকে আচার কেরা উচিত।\nসভে মানসি সাধিনমতে সমান মইর্জাত আর হকদারি লেইকে জনম লেতেক। তাহারাকার আঁগাস আর বুইধ আহেক তাহে সভেকর একে আনেক উপর ভায়াচারি মনেক ভাব লেইকে আচার কেরা উচিত।"
}
