id: "lad"
language: "lad"
script: "Hebr"
name: "Ladino"
autonym: "ג\'ודיאו-איספאנייול"
population: 112781
region: "IL"
exemplar_chars {
  base: "א ב ׳ ג ד ה ו ז ח ט י כ ך ל מ ם נ ן ס ע פ ף צ ץ ק ר ש ת"
}
sample_text {
  masthead_full: "TtOo"
  masthead_partial: "Dd"
  styles: "Konsiderando ke la libertad, la djustisia"
  tester: "Konsiderando ke el deskonosimiento i el despresio de los derechos"
  poster_sm: "Konsiderando"
  poster_md: "La Asamblea"
  poster_lg: "Todos"
  specimen_48: "Proklama la prezente Deklarasion Universal de Derechos Umanos"
  specimen_36: "Konsiderando tambien ke es esensial de favorizar la formasion de relasiones de amistad entre las nasiones,"
  specimen_32: "Konsiderando ke una konsepsion komun de estos derechos i libertades es de la mas grande importansia para kumplir kompletamente la dicha prometa,"
  specimen_21: "Konsiderando ke la libertad, la djustisia i la paz en el mundo tienen por baza el rekonosimiento de la dinyidad propia esensial i de los derechos iguales i no violavles de todos los miembros de la famiya umana,\nKonsiderando ke es esensial ke los derechos umanos sean protejados por un rejimen de derecho, para ke el ombre no se veyga ovligado, komo ultimo remedio, de revoltarse kontra la tirania i la opresion,"
  specimen_16: "Konsiderando ke la libertad, la djustisia i la paz en el mundo tienen por baza el rekonosimiento de la dinyidad propia esensial i de los derechos iguales i no violavles de todos los miembros de la famiya umana,\nKonsiderando ke el deskonosimiento i el despresio de los derechos umanos tienen kavzado aktos de barbaridad ke solevantan la konsensia de la umanidad; i ke fue proklamado komo la aspirasion mas alta del ombre, la yegada de un mundo en el kual los umanos, liberados del espanto i de la mizeria, gozen de la libertad de la palavra i de la libertad de kreensias,"
}
