id: "lad_Latn"
language: "lad"
script: "Latn"
name: "Ladino"
region: "IL"
sample_text {
  masthead_full: "TtOo"
  masthead_partial: "Dd"
  styles: "Todos los umanos nasen libres i iguales en"
  tester: "Todos los umanos nasen libres i iguales en dinyidad i derechos"
  poster_sm: "Todos los umanos"
  poster_md: "Todos"
  poster_lg: "Todos"
  specimen_48: "Todos los umanos nasen libres i iguales en dinyidad"
  specimen_36: "Todos los umanos nasen libres i iguales en dinyidad i derechos i, komo estan ekipados de razon i konsensia, deven komportarsen kon ermandad los unos kon los otros."
  specimen_32: "Todos los umanos nasen libres i iguales en dinyidad i derechos i, komo estan ekipados de razon i konsensia, deven komportarsen kon ermandad los unos kon los otros."
  specimen_21: "Todos los umanos nasen libres i iguales en dinyidad i derechos i, komo estan ekipados de razon i konsensia, deven komportarsen kon ermandad los unos kon los otros.\nTodos los umanos nasen libres i iguales en dinyidad i derechos i, komo estan ekipados de razon i konsensia, deven komportarsen kon ermandad los unos kon los otros."
  specimen_16: "Todos los umanos nasen libres i iguales en dinyidad i derechos i, komo estan ekipados de razon i konsensia, deven komportarsen kon ermandad los unos kon los otros.\nTodos los umanos nasen libres i iguales en dinyidad i derechos i, komo estan ekipados de razon i konsensia, deven komportarsen kon ermandad los unos kon los otros.\nTodos los umanos nasen libres i iguales en dinyidad i derechos i, komo estan ekipados de razon i konsensia, deven komportarsen kon ermandad los unos kon los otros.\nTodos los umanos nasen libres i iguales en dinyidad i derechos i, komo estan ekipados de razon i konsensia, deven komportarsen kon ermandad los unos kon los otros."
}
