id: "lag"
language: "lag"
script: "Latn"
name: "Langi"
autonym: "Kɨlaangi"
population: 509409
region: "TZ"
exemplar_chars {
  base: "a á b c d e é f g h i í ɨ j k l m n o ó p q r s t u ú ʉ v w x y z"
  marks: "◌́"
  index: "A B C D E F G H I Ɨ J K L M N O P Q R S T U Ʉ V W X Y Z"
}
sample_text {
  fallback_language: "en"
}
