id: "lah"
language: "lah"
script: "Arab"
name: "Lahnda"
population: 93433552
region: "IN"
region: "PK"
sample_text {
  masthead_full: "سارے"
  masthead_partial: "نآ"
  styles: "چونکہ ہر انسان دی ذاتی عزت وقار تے ناقابل"
  tester: "چونکہ انسانی حقوق دا خیال نہ رکھن تے لوہناں دی بے حرمتی دی وجہ"
  poster_sm: "چونکہ قانون"
  poster_md: "چونکہ ساریاں"
  poster_lg: "سارے"
  specimen_48: "چونکہ رکن قوماں نے اقوم متحدہ دے منشور وچ بحیادی انسانی حقوق،"
  specimen_36: "چونکہ ایہہ عہد پورا کرن دی خاطر ایہناں آزادیاں تے حقوق نوں سب دا چنگی طر حاں سمجھ لینا بہت ضروری اے ۔ ۔"
  specimen_32: "کسے وی شخص نوں نہ تے کوئی جسمانی اذیت دتی جاسکدی اے نہ اوہدے نال کوئی ظالمانہ تے انسانیت سوز سلوک کیتا جاسکدا اے تے نہ ہی ایس طرحاں دی کوئی بھیڑی سزا دیتی جاسکدی اے ۔ ۔"
  specimen_21: "ہر شخص دا ایہہ حق اے پئی قانون ہر تھاں لوہدی شخصیت نوں تسلیم کرے ۔ ۔\nقانون دی نظر وچ سب برابر نیں تے قانون کوئی فرق رکھے بغیر ہر کسے وی حفاظت کرے گا ۔ ۔ انسانی حقوق دے ایس عالمی منشور توں ہٹ کے وکھری قسم دے کسے سلوک یا وکھرے سلوک دی ترغیب توں تحفظ دا ہر کوئی حقدار اے ۔ ۔\nہر شخص نوں بااختیار قومی عدالتاں وچ قانون تے آئین دیاں اوہناں خلاف ورزیاں دے خلاف موثر چارہ جوئی دا حق حاصل اے جنہاں دے نتیجے وچ اوہدے انسانی حقوق مارے جاندے ہون ۔ ۔"
  specimen_16: "کسے وی شخص نوں کسے دی من مرضی اُتے نہ تے گرفتار یا نظر بند کیتا جا سکدا اے تے نہ ہی وطن توں باہر کڈھیا جا سکدا اے ۔ ۔\nہر شخص نوں برابر دا حق حاصل اے پئی اوہدے حقوق تے فرائض طے کرن لئی یا ایہہ فیصلہ کرن لئی پئی اوہدے اُتے جہیڑے جرم دا الزام اے اوہ اوہنے کیتا اے کہ نہیں، کسے غیر جانبدار، آزاد تے کھلی عدالت وچ مقدمہ چلایا جائے ۔ ۔\nکسے وی شخص دی ذاتی زندگی، گھریلو زندگی، اوہدے گھر دے اندرونی معاملات تے لوہدی خط و کتابت وچ نہ تے من مرضی دا کوئی دخل دتا جا سکدا اے تے نہ ہی اوہدی عزت تے نیک نامی دل انگلی اٹھائی جا سکدی اے ۔ ۔ ہر شخص دا ایہہ حق اے پئی قانون اوہنوں ایس قسم دی دخل اندازی یا نیک نامی تے عزت دے نقصان توں محفوظ رکھے ۔ ۔"
}
