id: "lia_Latn"
language: "lia"
script: "Latn"
name: "Limba, West-Central"
sample_text {
  masthead_full: "BbIi"
  masthead_partial: "Yy"
  styles: "B\ni\ny\na\n-\nm\nɛ\nt\ni\n \nf\no\no\nm\na\n \nb\ne\n \nk\ni"
  tester: "B\ni\ny\na\n-\nm\nɛ\nt\ni\n \nf\no\no\nm\na\n \nb\ne\n \nk\ni\ny\no\n \nk\na\n \nk\nu\ny\na"
  poster_sm: "B\ni\ny\na\n-\nm"
  poster_md: "B\ni\ny\na\n-"
  poster_lg: "B\ni"
  specimen_48: "B\ni\ny\na\n-\nm\nɛ\nt\ni\n \nf\no\no\nm\na\n \nb\ne\n \nk\ni\ny\no\n \nk\na\n \nk\nu\ny\na"
  specimen_36: "B\ni\ny\na\n-\nm\nɛ\nt\ni\n \nf\no\no\nm\na\n \nb\ne\n \nk\ni\ny\no\n \nk\na\n \nk\nu\ny\na\nn\nk\na\nŋ\n \ni\nŋ\n \nk\na\ns\nɛ\nm\nb\nɛ\n \nm\nɛ\nn\nɛ"
  specimen_32: "B\ni\ny\na\n-\nm\nɛ\nt\ni\n \nf\no\no\nm\na\n \nb\ne\n \nk\ni\ny\no\n \nk\na\n \nk\nu\ny\na\nn\nk\na\nŋ\n \ni\nŋ\n \nk\na\ns\nɛ\nm\nb\nɛ\n \nm\nɛ\nn\nɛ\n \ni\nn\n \nk\na\n \ny\ni\nk\ni\n.\n \nB\ni\nn\nd\nɛ\n \nk\ni"
  specimen_21: "B\ni\ny\na\n-\nm\nɛ\nt\ni\n \nf\no\no\nm\na\n \nb\ne\n \nk\ni\ny\no\n \nk\na\n \nk\nu\ny\na\nn\nk\na\nŋ\n \ni\nŋ\n \nk\na\ns\nɛ\nm\nb\nɛ\n \nm\nɛ\nn\nɛ\n \ni\nn\n \nk\na\n \ny\ni\nk\ni\n.\n \nB\ni\nn\nd\nɛ\n \nk\ni\nŋ\n \nb\na\n \nn\ni\ny\nɔ\n \ni\nn\n \nm\na\ns\ni\nm\nɔ\nk\nɔ\n,\n \nm\na\nk\na\n \ny\ni\ni\nn\na\n \nw\no\n \nk\na\n \nh\nu\n \nw\nɛ\nn\nd\ni\n \ny\na\nn\nd\ne\n.\nB\ni\ny\na\n-\nm\nɛ\nt\ni\n \nf\no\no\nm\na\n \nb\ne\n \nk\ni\ny\no\n \nk\na"
  specimen_16: "B\ni\ny\na\n-\nm\nɛ\nt\ni\n \nf\no\no\nm\na\n \nb\ne\n \nk\ni\ny\no\n \nk\na\n \nk\nu\ny\na\nn\nk\na\nŋ\n \ni\nŋ\n \nk\na\ns\nɛ\nm\nb\nɛ\n \nm\nɛ\nn\nɛ\n \ni\nn\n \nk\na\n \ny\ni\nk\ni\n.\n \nB\ni\nn\nd\nɛ\n \nk\ni\nŋ\n \nb\na\n \nn\ni\ny\nɔ\n \ni\nn\n \nm\na\ns\ni\nm\nɔ\nk\nɔ\n,\n \nm\na\nk\na\n \ny\ni\ni\nn\na\n \nw\no\n \nk\na\n \nh\nu\n \nw\nɛ\nn\nd\ni\n \ny\na\nn\nd\ne\n.\nB\ni\ny\na\n-\nm\nɛ\nt\ni\n \nf\no\no\nm\na\n \nb\ne\n \nk\ni\ny\no\n \nk\na\n \nk\nu\ny\na\nn\nk\na\nŋ\n \ni\nŋ\n \nk\na\ns\nɛ\nm\nb\nɛ\n \nm\nɛ\nn\nɛ\n \ni\nn\n \nk\na\n \ny\ni\nk\ni\n.\n \nB\ni\nn\nd\nɛ\n \nk\ni\nŋ\n \nb\na\n \nn\ni\ny\nɔ\n \ni\nn\n \nm\na\ns\ni\nm\nɔ\nk\nɔ\n,\n \nm\na\nk\na\n \ny\ni\ni\nn\na\n \nw\no\n \nk\na\n \nh\nu\n \nw\nɛ\nn\nd\ni\n \ny\na\nn\nd\ne\n.\nB\ni\ny\na\n-\nm\nɛ\nt\ni\n \nf\no\no\nm\na\n \nb\ne\n \nk\ni\ny\no\n \nk\na"
}
