id: "ljp_Latn"
language: "ljp"
script: "Latn"
name: "Lampung Api"
population: 1842479
region: "ID"
sample_text {
  masthead_full: "UuNn"
  masthead_partial: "Yy"
  styles: "Unyin Jelema dilaheʁko merdeka jama wat pi\'il"
  tester: "Unyin Jelema dilaheʁko merdeka jama wat pi\'il ʁik hak sai gokgoh."
  poster_sm: "Unyin Jelema"
  poster_md: "Unyin"
  poster_lg: "Unyin"
  specimen_48: "Unyin Jelema dilaheʁko merdeka jama wat pi\'il ʁik hak"
  specimen_36: "Unyin Jelema dilaheʁko merdeka jama wat pi\'il ʁik hak sai gokgoh. Tiyan dikaruniako akal jama hati nurani maʁai unggal tiyan dapok nengah nyampoʁ dilom semangat muaʁiyan."
  specimen_32: "Unyin Jelema dilaheʁko merdeka jama wat pi\'il ʁik hak sai gokgoh. Tiyan dikaruniako akal jama hati nurani maʁai unggal tiyan dapok nengah nyampoʁ dilom semangat muaʁiyan."
  specimen_21: "Unyin Jelema dilaheʁko merdeka jama wat pi\'il ʁik hak sai gokgoh. Tiyan dikaruniako akal jama hati nurani maʁai unggal tiyan dapok nengah nyampoʁ dilom semangat muaʁiyan.\nUnyin Jelema dilaheʁko merdeka jama wat pi\'il ʁik hak sai gokgoh. Tiyan dikaruniako akal jama hati nurani maʁai unggal tiyan dapok nengah nyampoʁ dilom semangat muaʁiyan."
  specimen_16: "Unyin Jelema dilaheʁko merdeka jama wat pi\'il ʁik hak sai gokgoh. Tiyan dikaruniako akal jama hati nurani maʁai unggal tiyan dapok nengah nyampoʁ dilom semangat muaʁiyan.\nUnyin Jelema dilaheʁko merdeka jama wat pi\'il ʁik hak sai gokgoh. Tiyan dikaruniako akal jama hati nurani maʁai unggal tiyan dapok nengah nyampoʁ dilom semangat muaʁiyan.\nUnyin Jelema dilaheʁko merdeka jama wat pi\'il ʁik hak sai gokgoh. Tiyan dikaruniako akal jama hati nurani maʁai unggal tiyan dapok nengah nyampoʁ dilom semangat muaʁiyan.\nUnyin Jelema dilaheʁko merdeka jama wat pi\'il ʁik hak sai gokgoh. Tiyan dikaruniako akal jama hati nurani maʁai unggal tiyan dapok nengah nyampoʁ dilom semangat muaʁiyan."
}
