id: "ljp_Latn"
language: "ljp"
script: "Latn"
name: "Lampung Api"
population: 1842479
region: "ID"
sample_text {
  masthead_full: "UuNn"
  masthead_partial: "Yy"
  styles: "U\nn\ny\ni\nn\n \nJ\ne\nl\ne\nm\na\n \nd\ni\nl\na\nh\ne\nʁ\nk"
  tester: "U\nn\ny\ni\nn\n \nJ\ne\nl\ne\nm\na\n \nd\ni\nl\na\nh\ne\nʁ\nk\no\n \nm\ne\nr\nd\ne\nk\na\n "
  poster_sm: "U\nn\ny\ni\nn\n "
  poster_md: "U\nn\ny\ni\nn"
  poster_lg: "U\nn"
  specimen_48: "U\nn\ny\ni\nn\n \nJ\ne\nl\ne\nm\na\n \nd\ni\nl\na\nh\ne\nʁ\nk\no\n \nm\ne\nr\nd\ne\nk\na\n "
  specimen_36: "U\nn\ny\ni\nn\n \nJ\ne\nl\ne\nm\na\n \nd\ni\nl\na\nh\ne\nʁ\nk\no\n \nm\ne\nr\nd\ne\nk\na\n \nj\na\nm\na\n \nw\na\nt\n \np\ni\n\'\ni\nl\n \nʁ\ni\nk\n \nh"
  specimen_32: "U\nn\ny\ni\nn\n \nJ\ne\nl\ne\nm\na\n \nd\ni\nl\na\nh\ne\nʁ\nk\no\n \nm\ne\nr\nd\ne\nk\na\n \nj\na\nm\na\n \nw\na\nt\n \np\ni\n\'\ni\nl\n \nʁ\ni\nk\n \nh\na\nk\n \ns\na\ni\n \ng\no\nk\ng\no\nh\n.\n \nT\ni\ny\na\nn\n "
  specimen_21: "U\nn\ny\ni\nn\n \nJ\ne\nl\ne\nm\na\n \nd\ni\nl\na\nh\ne\nʁ\nk\no\n \nm\ne\nr\nd\ne\nk\na\n \nj\na\nm\na\n \nw\na\nt\n \np\ni\n\'\ni\nl\n \nʁ\ni\nk\n \nh\na\nk\n \ns\na\ni\n \ng\no\nk\ng\no\nh\n.\n \nT\ni\ny\na\nn\n \nd\ni\nk\na\nr\nu\nn\ni\na\nk\no\n \na\nk\na\nl\n \nj\na\nm\na\n \nh\na\nt\ni\n \nn\nu\nr\na\nn\ni\n \nm\na\nʁ\na\ni\n \nu\nn\ng\ng\na\nl\n \nt\ni\ny\na\nn\n \nd\na\np\no\nk\n \nn\ne\nn\ng\na\nh\n \nn\ny\na\nm\np\no\nʁ\n \nd\ni\nl\no\nm\n "
  specimen_16: "U\nn\ny\ni\nn\n \nJ\ne\nl\ne\nm\na\n \nd\ni\nl\na\nh\ne\nʁ\nk\no\n \nm\ne\nr\nd\ne\nk\na\n \nj\na\nm\na\n \nw\na\nt\n \np\ni\n\'\ni\nl\n \nʁ\ni\nk\n \nh\na\nk\n \ns\na\ni\n \ng\no\nk\ng\no\nh\n.\n \nT\ni\ny\na\nn\n \nd\ni\nk\na\nr\nu\nn\ni\na\nk\no\n \na\nk\na\nl\n \nj\na\nm\na\n \nh\na\nt\ni\n \nn\nu\nr\na\nn\ni\n \nm\na\nʁ\na\ni\n \nu\nn\ng\ng\na\nl\n \nt\ni\ny\na\nn\n \nd\na\np\no\nk\n \nn\ne\nn\ng\na\nh\n \nn\ny\na\nm\np\no\nʁ\n \nd\ni\nl\no\nm\n \ns\ne\nm\na\nn\ng\na\nt\n \nm\nu\na\nʁ\ni\ny\na\nn\n.\nU\nn\ny\ni\nn\n \nJ\ne\nl\ne\nm\na\n \nd\ni\nl\na\nh\ne\nʁ\nk\no\n \nm\ne\nr\nd\ne\nk\na\n \nj\na\nm\na\n \nw\na\nt\n \np\ni\n\'\ni\nl\n \nʁ\ni\nk\n \nh\na\nk\n \ns\na\ni\n \ng\no\nk\ng\no\nh\n.\n \nT\ni\ny\na\nn\n \nd\ni\nk\na\nr\nu\nn\ni\na\nk\no\n \na\nk\na\nl\n \nj\na\nm\na\n \nh\na\nt\ni\n \nn\nu\nr\na\nn\ni\n \nm\na"
}
