id: "lkt"
name: "Lakota"
preferred_name: ""
autonym: "Lakȟótiyapi"
population: 8315
region: "US"
script: "Latin"
exemplar_chars {
  base: "A B E G H I K L M N O P S T U W Y Z Á É Í Ó Ú Č Ŋ Š Ž Ǧ Ȟ a b e g h i k l m n o p s t u w y z á é í ó ú č ŋ š ž ǧ ȟ ʼ"
  auxiliary: "C D F J Q R V X c d f j q r v x"
  marks: "◌́ ◌̌"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . \" “ ” ( ) \\[ \\] @ * / \\& #"
  index: "A B Č E G Ǧ H Ȟ I K L M N Ŋ O P S Š T U W Y Z Ž"
}
sample_text {
  fallback_language: "en"
}
