id: "lld_Latn"
language: "lld"
script: "Latn"
name: "Ladin"
region: "IT"
sample_text {
  masthead_full: "DdÖö"
  masthead_partial: "Tt"
  styles: "Dötes les porsones nasc lëdies y cun la medema"
  tester: "Dötes les porsones nasc lëdies y cun la medema dignité y i medemi"
  poster_sm: "Dötes les"
  poster_md: "Dötes les"
  poster_lg: "Dötes"
  specimen_48: "Dötes les porsones nasc lëdies y cun la medema dignité y i medemi dërć."
  specimen_36: "Dötes les porsones nasc lëdies y cun la medema dignité y i medemi dërć. Ares à na rajun y na cosciënza y mëss s’incuntè öna cun l’atra te n spirit de fraternité."
  specimen_32: "Dötes les porsones nasc lëdies y cun la medema dignité y i medemi dërć. Ares à na rajun y na cosciënza y mëss s’incuntè öna cun l’atra te n spirit de fraternité."
  specimen_21: "Dötes les porsones nasc lëdies y cun la medema dignité y i medemi dërć. Ares à na rajun y na cosciënza y mëss s’incuntè öna cun l’atra te n spirit de fraternité.\nDötes les porsones nasc lëdies y cun la medema dignité y i medemi dërć. Ares à na rajun y na cosciënza y mëss s’incuntè öna cun l’atra te n spirit de fraternité."
  specimen_16: "Dötes les porsones nasc lëdies y cun la medema dignité y i medemi dërć. Ares à na rajun y na cosciënza y mëss s’incuntè öna cun l’atra te n spirit de fraternité.\nDötes les porsones nasc lëdies y cun la medema dignité y i medemi dërć. Ares à na rajun y na cosciënza y mëss s’incuntè öna cun l’atra te n spirit de fraternité.\nDötes les porsones nasc lëdies y cun la medema dignité y i medemi dërć. Ares à na rajun y na cosciënza y mëss s’incuntè öna cun l’atra te n spirit de fraternité.\nDötes les porsones nasc lëdies y cun la medema dignité y i medemi dërć. Ares à na rajun y na cosciënza y mëss s’incuntè öna cun l’atra te n spirit de fraternité."
}
