id: "lo"
language: "lo"
script: "Laoo"
name: "Lao"
autonym: "ພາສາລາວ"
population: 5138706
region: "LA"
exemplar_chars {
  base: "່ ້ ໊ ໋ ໌ ໍ ໆ ກ ຂ ຄ ງ ຈ ສ ຊ ຍ ດ ຕ ຖ ທ ນ ບ ປ ຜ ຝ ພ ຟ ມ ຢ ຣ ລ ວ ຫ ໜ ໝ ອ ຮ ຯ ະ ັ າ ຳ ິ ີ ຶ ື ຸ ູ ົ ຼ ຽ ເ ແ ໂ ໃ ໄ"
  auxiliary: "​ ໐ ໑ ໒ ໓ ໔ ໕ ໖ ໗ ໘ ໙"
  marks: "◌ັ ◌ິ ◌ີ ◌ຶ ◌ື ◌ຸ ◌ູ ◌ົ ◌ຼ ◌່ ◌້ ◌໊ ◌໋ ◌໌ ◌ໍ"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ \" “ ” ( ) [ ] § @ * / & # † ‡ ′ ″"
  index: "ກ ຂ ຄ ງ ຈ ສ ຊ ຍ ດ ຕ ຖ ທ ນ ບ ປ ຜ ຝ ພ ຟ ມ ຢ ຣ ລ ວ ຫ {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} ອ ຮ {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ}"
}
sample_text {
  masthead_full: "ມະນດ"
  masthead_partial: "ເກ"
  styles: "ດ້ວຍເຫດວ່າ: ການຮັບຮູ້ກຽດຕິສັກອັນມີປະຈຳຢູ່ຕົວບຸກຄົນໃນວົງສະກຸນຂອງມະນຸດທຸກໆຄົນ"
  tester: "ດ້ວຍເຫດວ່າ: ໃນກົດໝາຍໂລກນັ້ນປະຊາຊົນແຫ່ງສະຫະປະຊາຊາດໄດ້ປະກາດຢືນຢັນຄວາມເຊື່ອຖືຂອງຕົນອີກໃນສິດສຳຄັນຂອງມະນຸດ"
  poster_sm: "ກອງປະຊຸມໃຫຍ"
  poster_md: "ຂໍ້ 2.ອີກປະການໜື່ງ"
  poster_lg: "ແລະ"
  specimen_48: "ບໍ່ມີຜູ້ໃດເລີຍທີ່ຈະຕ້ອງຖືວ່າ:ມີອາການເປັນທາດ ແລະ ເປັນຂ້ອຍເປັນຂ້າການເປັນທາດ ແລະ ຂ້າທາດນັ້ນ"
  specimen_36: "ບຸກຄົນທຸກຄົນມີສິດທີ່ຈະມີການສະຫງົບເກີດຂື້ນໃນດ້ານສັງຄົມ ແລະ ໃນດ້ານຕ່າງປະເທດເພື່ອຈະໃຫ້ມີສິດ ແລະ ເສລີພາບທັງມວນທີ່ໄດ້ກ່າວໃນໃບປະກາດສະບັບນີ້ດຳເນີນໄປຢ່າງສັກສິດສົມບູນ."
  specimen_32: "ຂໍ້ໃດຂໍ້ໜື່ງໃນປະກາດສະບັບນີ້ບໍ່ໃຫ້ເອົາຕິດຄວາມເຂົ້າໄປໃນທາງອັນກ່ຽວແກ່ສິດໃດສິດໜື່ງສະລັບລັດໃດລັດໜື່ງ ໝູ່ຄະນະໃດຄະນະໜື່ງ ຫຼື ບຸກຄົນໃດບຸກຄົນໜື່ງທີ່ຈະດຳເນີນຫຼື ປະຕິບັດການອັນມຸ້ງທຳລາຍສິດ ແລະ ເສລີພາບທັງມວນຢູ່ໃນປະກາດສະບັບນີ້."
  specimen_21: "ດ້ວຍເຫດວ່າ: ການຮັບຮູ້ກຽດຕິສັກອັນມີປະຈຳຢູ່ຕົວບຸກຄົນໃນວົງສະກຸນຂອງມະນຸດທຸກໆຄົນ ແລະ ການຮັບຮູ້ສິດສະເໝີພາບ ແລະ ສະເຖຍລະພາບຂອງບຸກຄົນເຫຼົ່ານັ້ນ ປະກອບເປັນຮາກຖານຂອງສິດເສລີພາບ ຍຸດຕິທຳ ແລະ ສັນຕິພາບຂອງໂລກ.\nດ້ວຍເຫດວ່າ: ການບໍ່ຮັບຮູ້ ແລະ ໜີ່ນປະໝາດຕໍ່ສິດຂອງມະນຸດນັ້ນໄດ້ເປັນຕົ້ນເຫດໃຫ້ເກີດການກະທຳຢ່າງປ່າເຖື່ອນຊື່ງຈະເຮັດໃຫ້ແຄ້ນໃຈຕໍ່ມະໂນທຳຂອງມະນຸດ ແລະ ເຫັນວ່າການນຳຊື່ງໂລກມະນຸດທີ່ຈະມີອິດສະຫຼະໃນການສະແດງຄວາມເວົ້າ ແລະ ຄວາມເຊື່ອຖືຊື່ງຈະພົ້ນຈາກຄວາມຫວາດຫວັ່ນ ຢ້ານກົວ ແລະ ຍາກຈົນຂົ້ນແຄ້ນນັ້ນໄດ້ຖືກປະກາດວ່າ: ເປັນຄວາມປາຖະໜາອັນຍອດຍີ່ງຂອງມະນຸດ."
  specimen_16: "ດ້ວຍເຫດວ່າ: ການຮັບຮູ້ກຽດຕິສັກອັນມີປະຈຳຢູ່ຕົວບຸກຄົນໃນວົງສະກຸນຂອງມະນຸດທຸກໆຄົນ ແລະ ການຮັບຮູ້ສິດສະເໝີພາບ ແລະ ສະເຖຍລະພາບຂອງບຸກຄົນເຫຼົ່ານັ້ນ ປະກອບເປັນຮາກຖານຂອງສິດເສລີພາບ ຍຸດຕິທຳ ແລະ ສັນຕິພາບຂອງໂລກ.\nດ້ວຍເຫດວ່າ: ການບໍ່ຮັບຮູ້ ແລະ ໜີ່ນປະໝາດຕໍ່ສິດຂອງມະນຸດນັ້ນໄດ້ເປັນຕົ້ນເຫດໃຫ້ເກີດການກະທຳຢ່າງປ່າເຖື່ອນຊື່ງຈະເຮັດໃຫ້ແຄ້ນໃຈຕໍ່ມະໂນທຳຂອງມະນຸດ ແລະ ເຫັນວ່າການນຳຊື່ງໂລກມະນຸດທີ່ຈະມີອິດສະຫຼະໃນການສະແດງຄວາມເວົ້າ ແລະ ຄວາມເຊື່ອຖືຊື່ງຈະພົ້ນຈາກຄວາມຫວາດຫວັ່ນ ຢ້ານກົວ ແລະ ຍາກຈົນຂົ້ນແຄ້ນນັ້ນໄດ້ຖືກປະກາດວ່າ: ເປັນຄວາມປາຖະໜາອັນຍອດຍີ່ງຂອງມະນຸດ.\nດ້ວຍເຫດວ່າ: ມີຄວາມສຳຄັນທີ່ຕ້ອງລະບຽບສິດປ້ອງກັນສິດທັງຫຼາຍຂອງມະນຸດເພື່ອບໍ່ໃຫ້ບຸກຄົນຖືກບັງຄັບໃຈໃຫ້ຕໍ່ສູ້ຄວາມບຽດບຽນຂ້ຽວແຂ້ນແລະຄວາມກົດຂີ່ຂົ່ມເຫງຈົນເຫຼືອວິໃສ.\nດ້ວຍເຫດວ່າ: ເປັນຂໍ້ສຳຄັນທີ່ຕ້ອງເຊີດຊູສຳພັນທະໄມຕີລະຫວ່າງປະເທດຊາດໃຫ້ດີຍີ່ງຂື້ນ;"
}
