id: "lob_Latn"
language: "lob"
script: "Latn"
name: "Lobi"
sample_text {
  masthead_full: "TtEe"
  masthead_partial: "Hh"
  styles: "T\ne\ne\nh\nu\nu\n \ns\nʋ\nn\nɔ\n \nn\n \nt\nh\ne\nr\n \nɛ\nɛ"
  tester: "T\ne\ne\nh\nu\nu\n \ns\nʋ\nn\nɔ\n \nn\n \nt\nh\ne\nr\n \nɛ\nɛ\n \nn\nɩ\nɩ\n \nb\nʋ\nn\nɔ\n "
  poster_sm: "T\ne\ne\nh\nu\nu"
  poster_md: "T\ne\ne\nh\nu"
  poster_lg: "T\ne"
  specimen_48: "T\ne\ne\nh\nu\nu\n \ns\nʋ\nn\nɔ\n \nn\n \nt\nh\ne\nr\n \nɛ\nɛ\n \nn\nɩ\nɩ\n \nb\nʋ\nn\nɔ\n "
  specimen_36: "T\ne\ne\nh\nu\nu\n \ns\nʋ\nn\nɔ\n \nn\n \nt\nh\ne\nr\n \nɛ\nɛ\n \nn\nɩ\nɩ\n \nb\nʋ\nn\nɔ\n \nw\na\n \nn\n \nd\no\n \nd\ne\ne\na\nʔ\n \ns\nɩ\n \nw\nʋ\n "
  specimen_32: "T\ne\ne\nh\nu\nu\n \ns\nʋ\nn\nɔ\n \nn\n \nt\nh\ne\nr\n \nɛ\nɛ\n \nn\nɩ\nɩ\n \nb\nʋ\nn\nɔ\n \nw\na\n \nn\n \nd\no\n \nd\ne\ne\na\nʔ\n \ns\nɩ\n \nw\nʋ\n \nn\n \nm\na\nk\nh\na\n \ns\na\nm\nɩ\nn\nɩ\n \nn\na\n \nn\nà"
  specimen_21: "T\ne\ne\nh\nu\nu\n \ns\nʋ\nn\nɔ\n \nn\n \nt\nh\ne\nr\n \nɛ\nɛ\n \nn\nɩ\nɩ\n \nb\nʋ\nn\nɔ\n \nw\na\n \nn\n \nd\no\n \nd\ne\ne\na\nʔ\n \ns\nɩ\n \nw\nʋ\n \nn\n \nm\na\nk\nh\na\n \ns\na\nm\nɩ\nn\nɩ\n \nn\na\n \nn\nà\n \nh\nʋ\n \nt\nɩ\nn\nɛ\np\na\nr\n \nr\nà\n.\n \nT\nh\na\nn\ng\nb\na\n \nt\ni\n \ny\nɛ\nr\n \nà\n \np\nɛ\n \ny\nɛ\nr\n \nj\nɩ\nɩ\nr\n \nn\nà\n \nf\nɩ\nl\nw\nɛ\n \ns\nɩ\n \na\n \nt\ne\ne\nn\na\n \nw\na\na\nn\n \nf\nʋ\nk\nh\na\n \no\nm\nk\nh"
  specimen_16: "T\ne\ne\nh\nu\nu\n \ns\nʋ\nn\nɔ\n \nn\n \nt\nh\ne\nr\n \nɛ\nɛ\n \nn\nɩ\nɩ\n \nb\nʋ\nn\nɔ\n \nw\na\n \nn\n \nd\no\n \nd\ne\ne\na\nʔ\n \ns\nɩ\n \nw\nʋ\n \nn\n \nm\na\nk\nh\na\n \ns\na\nm\nɩ\nn\nɩ\n \nn\na\n \nn\nà\n \nh\nʋ\n \nt\nɩ\nn\nɛ\np\na\nr\n \nr\nà\n.\n \nT\nh\na\nn\ng\nb\na\n \nt\ni\n \ny\nɛ\nr\n \nà\n \np\nɛ\n \ny\nɛ\nr\n \nj\nɩ\nɩ\nr\n \nn\nà\n \nf\nɩ\nl\nw\nɛ\n \ns\nɩ\n \na\n \nt\ne\ne\nn\na\n \nw\na\na\nn\n \nf\nʋ\nk\nh\na\n \no\nm\nk\nh\na\na\n.\nT\ne\ne\nh\nu\nu\n \ns\nʋ\nn\nɔ\n \nn\n \nt\nh\ne\nr\n \nɛ\nɛ\n \nn\nɩ\nɩ\n \nb\nʋ\nn\nɔ\n \nw\na\n \nn\n \nd\no\n \nd\ne\ne\na\nʔ\n \ns\nɩ\n \nw\nʋ\n \nn\n \nm\na\nk\nh\na\n \ns\na\nm\nɩ\nn\nɩ\n \nn\na\n \nn\nà\n \nh\nʋ\n \nt\nɩ\nn\nɛ\np\na\nr\n \nr\nà\n.\n \nT\nh\na\nn\ng\nb\na\n \nt\ni\n \ny\nɛ\nr\n \nà\n \np\nɛ\n \ny\nɛ\nr\n \nj\nɩ\nɩ\nr\n \nn\nà\n \nf\nɩ\nl\nw"
}
