id: "lu"
language: "lu"
script: "Latn"
name: "Luba-Katanga"
autonym: "Kiluba"
population: 2340939
region: "CD"
exemplar_chars {
  base: "a á à b c d e é è ɛ {ɛ́} {ɛ̀} f h i í ì j k l m n {ng} {ny} o ó ò ɔ {ɔ́} {ɔ̀} p {ph} q s {shi} t u ú ù v w y z {ɛ́} {ɛ̀} {ng} {ny} {ɔ́} {ɔ̀} {ph} {shi} {ɛ́} {ɛ̀} {ng} {ny} {ɔ́} {ɔ̀} {ph} {shi} {ɛ́} {ɛ̀} {ng} {ny} {ɔ́} {ɔ̀} {ph} {shi} {ɛ́} {ɛ̀} {ng} {ny} {ɔ́} {ɔ̀} {ph} {shi} {ɛ́} {ɛ̀} {ng} {ny} {ɔ́} {ɔ̀} {ph} {shi} {ɛ́} {ɛ̀} {ng} {ny} {ɔ́} {ɔ̀} {ph} {shi} {ɛ́} {ɛ̀} {ng} {ny} {ɔ́} {ɔ̀} {ph} {shi} {ɛ́} {ɛ̀} {ng} {ny} {ɔ́} {ɔ̀} {ph} {shi} {ɛ́} {ɛ̀} {ng} {ny} {ɔ́} {ɔ̀} {ph} {shi} {ɛ́} {ɛ̀} {ng} {ny} {ɔ́} {ɔ̀} {ph} {shi} {ɛ́} {ɛ̀} {ng} {ny} {ɔ́} {ɔ̀} {ph} {shi} {ɛ́} {ɛ̀} {ng} {ny} {ɔ́} {ɔ̀} {ph} {shi} {ɛ́} {ɛ̀} {ng} {ny} {ɔ́} {ɔ̀} {ph} {shi} {ɛ́} {ɛ̀} {ng} {ny} {ɔ́} {ɔ̀} {ph} {shi} {ɛ́} {ɛ̀} {ng} {ny} {ɔ́} {ɔ̀} {ph} {shi}"
  auxiliary: "g r x"
  marks: "◌̀ ◌́"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B C D E F H I J K L M N O P Q S T U V W Y Z"
}
sample_text {
  fallback_language: "en"
}
