id: "lu"
name: "Luba-Katanga"
preferred_name: ""
autonym: "Kiluba"
population: 2340939
region: "CD"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q S T U V W Y Z À Á È É Ì Í Ò Ó Ù Ú Ɔ Ɛ a b c d e f g h i j k l m n o p q s t u v w y z à á è é ì í ò ó ù ú ɔ ɛ"
  auxiliary: "R X r x"
  marks: "◌̀ ◌́"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B C D E F H I J K L M N O P Q S T U V W Y Z"
}
sample_text {
  fallback_language: "en"
}
