id: "lua"
name: "Luba-Lulua"
preferred_name: ""
autonym: "Tshiluba"
population: 9770880
region: "CD"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P S T U V W Y Z a b c d e f g h i j k l m n o p s t u v w y z"
}
sample_text {
  masthead_full: "BbAa"
  masthead_partial: "Nn"
  tester: "Pa kumona ne, kwitaba se bantu bonsu ba pa buloba badi ne buneme"
  poster_sm: "Pa kumona ne,"
  poster_md: "Pa kumona"
  poster_lg: "Bantu"
  specimen_48: "Pa kumona ne matunga a Nsangila wa Buka-bisamba (ONU) adi mashindike"
  specimen_36: "Pa kumona ne bwa kukumbaja mapangadika aa, bidi bimpe bantu bonsu bikale ne ngumvwilu umwe wa budikadidi ne makokeshi aa;"
  specimen_32: "Bantu bonsu badi baledibwa badikadile ne badi ne makokeshi amwe. Badi ne lungenyi lwa bumuntu ne kondo ka moyo, badi ne bwa kwenzelangana malu mu buwetu."
  specimen_21: "Budikadidi ne makokeshi mafunda mu Mapangadika aa bidi bitangila muntu yonsu, kakuyi disunguluja bisamba, mubidi wa makoba a bantu, bulume anyi bukaji, mwakulu, ntendelelu, ngumvwilu wa malu a cididi anyi dyela dya meji kana onsu, ditunga dya muntu; bubanji anyi bupele, mwaba wa cilelelu ne a mishindu kana yonsu."
  specimen_16: "Kabidi kabyena bikengela kansungansunga ku malu a cididi, a bunzuji a bukwa matunga anyi a mu ditunga didi muntu ufumina, nansha dyodyo didikadile anyi dikale ku bukenji anyi ku bupika bwa dikwabu.\nMuntu yonso udi ne bukookeshi bwa kwikala ne moyo, kudiikadila ne kusoma talala mu bumuntu bwende.\nMuntu nansha umwe kena mwa kukwaciibwa ku bupika bwalu mushinga wa bapika mmukandikiibwe mu mishindu yawu yonsu.\nMuntu nansha umwe kena mwa kukengeshiibwa anyi kupeshibwa bibawu bya kanyawu bidi kabiyi byakanyina bantu anyi bidi mwa kubapwekesha mulongo.\nMuntu yonsu udi ne bukenji bwa kumanyibwa my myaba yonsu mu bumuntu bwende."
}
