id: "lue_Latn"
language: "lue"
script: "Latn"
name: "Luvale"
sample_text {
  masthead_full: "VvAa"
  masthead_partial: "Tt"
  styles: "V\na\nt\nu\n \nv\no\ns\ne\nn\na\n \nv\na\ns\ne\nm\nu\nk\na\n "
  tester: "V\na\nt\nu\n \nv\no\ns\ne\nn\na\n \nv\na\ns\ne\nm\nu\nk\na\n \ny\na\np\nw\na\n \nh\no\nh\na"
  poster_sm: "V\na\nt\nu\n \nv"
  poster_md: "V\na\nt\nu\n "
  poster_lg: "V\na"
  specimen_48: "V\na\nt\nu\n \nv\no\ns\ne\nn\na\n \nv\na\ns\ne\nm\nu\nk\na\n \ny\na\np\nw\na\n \nh\no\nh\na"
  specimen_36: "V\na\nt\nu\n \nv\no\ns\ne\nn\na\n \nv\na\ns\ne\nm\nu\nk\na\n \ny\na\np\nw\na\n \nh\no\nh\na\nm\nw\ne\n \nn\na\nk\nw\ne\ns\ne\nk\na\n \nm\nu\nk\nu\ny\no"
  specimen_32: "V\na\nt\nu\n \nv\no\ns\ne\nn\na\n \nv\na\ns\ne\nm\nu\nk\na\n \ny\na\np\nw\na\n \nh\no\nh\na\nm\nw\ne\n \nn\na\nk\nw\ne\ns\ne\nk\na\n \nm\nu\nk\nu\ny\no\ny\na\n \nc\nh\na\nv\no\n.\n \nV\na\nt\nw\na\nm\na\n \nn\na"
  specimen_21: "V\na\nt\nu\n \nv\no\ns\ne\nn\na\n \nv\na\ns\ne\nm\nu\nk\na\n \ny\na\np\nw\na\n \nh\no\nh\na\nm\nw\ne\n \nn\na\nk\nw\ne\ns\ne\nk\na\n \nm\nu\nk\nu\ny\no\ny\na\n \nc\nh\na\nv\no\n.\n \nV\na\nt\nw\na\nm\na\n \nn\na\nc\nh\ni\ny\no\ny\ne\nl\no\n \nc\nh\na\nl\nu\ns\ne\ns\na\n \nc\nh\na\nj\ni\nn\ng\no\nl\no\n \nc\nh\na\nk\nu\nz\na\nn\ng\na\n \nk\nu\nl\ni\nv\nw\na\ns\nh\na\nn\na\n \nm\nu\nc\nh\ni\ny\no\ny\ne\nl\no\n \nc\nh\na\nv\no\n.\nV\na\nt\nu\n \nv\no\ns"
  specimen_16: "V\na\nt\nu\n \nv\no\ns\ne\nn\na\n \nv\na\ns\ne\nm\nu\nk\na\n \ny\na\np\nw\na\n \nh\no\nh\na\nm\nw\ne\n \nn\na\nk\nw\ne\ns\ne\nk\na\n \nm\nu\nk\nu\ny\no\ny\na\n \nc\nh\na\nv\no\n.\n \nV\na\nt\nw\na\nm\na\n \nn\na\nc\nh\ni\ny\no\ny\ne\nl\no\n \nc\nh\na\nl\nu\ns\ne\ns\na\n \nc\nh\na\nj\ni\nn\ng\no\nl\no\n \nc\nh\na\nk\nu\nz\na\nn\ng\na\n \nk\nu\nl\ni\nv\nw\na\ns\nh\na\nn\na\n \nm\nu\nc\nh\ni\ny\no\ny\ne\nl\no\n \nc\nh\na\nv\no\n.\nV\na\nt\nu\n \nv\no\ns\ne\nn\na\n \nv\na\ns\ne\nm\nu\nk\na\n \ny\na\np\nw\na\n \nh\no\nh\na\nm\nw\ne\n \nn\na\nk\nw\ne\ns\ne\nk\na\n \nm\nu\nk\nu\ny\no\ny\na\n \nc\nh\na\nv\no\n.\n \nV\na\nt\nw\na\nm\na\n \nn\na\nc\nh\ni\ny\no\ny\ne\nl\no\n \nc\nh\na\nl\nu\ns\ne\ns\na\n \nc\nh\na\nj\ni\nn\ng\no\nl\no\n \nc\nh\na\nk\nu\nz\na\nn\ng\na\n \nk\nu\nl\ni\nv\nw\na\ns\nh\na\nn\na\n \nm\nu\nc\nh\ni\ny\no"
}
