id: "luo"
language: "luo"
script: "Latn"
name: "Luo"
autonym: "Dholuo"
population: 5245734
region: "KE"
exemplar_chars {
  base: "a b c d e f g h i j k l m n o p r s t u v w y"
  auxiliary: "q x z"
  index: "A B C D E F G H I J K L M N O P R S T U V W Y"
}
sample_text {
  fallback_language: "en"
}
