id: "lus"
language: "lus"
script: "Beng"
name: "Mizo"
preferred_name: "Mizo"
population: 0
sample_text {
  masthead_full: "MmIi"
  masthead_partial: "Zz"
  styles: "Mihring nun zahawmna inhriatsak leh mi zawng"
  tester: "Mihringte dikna chanvo (Human Rights)-in ngaihnêp leh ngaihthah"
  poster_sm: "Tharum hmanga"
  poster_md: "Ram hrang"
  poster_lg: "zawng"
  specimen_48: "UN Dânpui (Charter) hnuaiah member ram zawng zawngten mihring dikna"
  specimen_36: "Mihring dikna leh zalênna vawng him zêl tura member ram ten UN thlazâr hnuaia thawkho zêl tura thu an tiam avang te leh,"
  specimen_32: "Mi tumah sawisak leh nghaisak phal a ni lova, mihring zahawmna ti bawrhbâng zâwng leh rãwng lutuka inhremna lam chi rêng rêng phei chu tu chungah mah lekkawh tur a ni lo."
  specimen_21: "Mitinte hian khawi hmunah pawh dan hmaah chuan mi pangngai anga enkawlna dawn hi kan chanvo a ni.\nDan hmaah chuan tute pawh kan intluk tlâng vek a, thleibîk awm miah lova dan humhimna hi kan zavaia chanvo a ni. He thuthlung palzût zawnga thliarhranna awm thei lak atanga danin intluktlânga a vênhimna hi kan chanvo theuh a ni."
  specimen_16: "Ram danpuiin a pêk mimal dikna leh chanvo palzûtna avanga tawrhna chungchângah mi tupawh an ram rorelnaah an zualko thei a ni.\nMi tupawh thilsual tia puh a nihin a chungchang rel fel turin rorelna dik leh lai a chunga hlenchhuah a nih theih nan dik taka rorel saktu tur rorelna dawn chu a chanvo a ni.\nApawng atakin tu chungah mah ama mimal nun tibawrhbâng zâwng leh an chhungkua, in chhung khawsak leh midangte nena an inbiakpawh danah leh ama mimal zahawmna leh hming mawinate tihliau zâwnga inrawlh a rem lova. Mitinte hian chutianga chêtna lam chi rêng rêng lak atanga danin venhimna a pek chu an chanvo a ni."
}
