id: "lut_Latn"
language: "lut"
script: "Latn"
name: "Lushootseed"
autonym: "Dəxʷləšucid"
population: 0
region: "US"
sample_text {
  masthead_full: "SsIi"
  masthead_partial: "ʔA"
  styles: "siʔsiʔab bəkʼʷaʔkʷbixʷ ʔugʷəc. ʔəsdᶻəw\'il əlgʷəʔ"
  tester: "siʔsiʔab bəkʼʷaʔkʷbixʷ ʔugʷəc. ʔəsdᶻəw\'il əlgʷəʔ . ʔəstalx̌ əlgʷəʔ"
  poster_sm: "siʔsiʔab bəkʼʷaʔkʷbixʷ ʔugʷəc. ʔəsdᶻəw\'il əlgʷəʔ . ʔəstalx̌ əlgʷəʔ ʔəst\'ugʷud, ʔəsx̌əčbid ƛʼubexʷ əlgʷəʔ shuyils ʔalʔalš"
  poster_md: "siʔsiʔab"
  poster_lg: "siʔsiʔab"
  specimen_48: "siʔsiʔab bəkʼʷaʔkʷbixʷ ʔugʷəc. ʔəsdᶻəw\'il əlgʷəʔ . ʔəstalx̌"
  specimen_36: "siʔsiʔab bəkʼʷaʔkʷbixʷ ʔugʷəc. ʔəsdᶻəw\'il əlgʷəʔ . ʔəstalx̌ əlgʷəʔ ʔəst\'ugʷud, ʔəsx̌əčbid ƛʼubexʷ əlgʷəʔ shuyils ʔalʔalš."
  specimen_32: "siʔsiʔab bəkʼʷaʔkʷbixʷ ʔugʷəc. ʔəsdᶻəw\'il əlgʷəʔ . ʔəstalx̌ əlgʷəʔ ʔəst\'ugʷud, ʔəsx̌əčbid ƛʼubexʷ əlgʷəʔ shuyils ʔalʔalš."
  specimen_21: "siʔsiʔab bəkʼʷaʔkʷbixʷ ʔugʷəc. ʔəsdᶻəw\'il əlgʷəʔ . ʔəstalx̌ əlgʷəʔ ʔəst\'ugʷud, ʔəsx̌əčbid ƛʼubexʷ əlgʷəʔ shuyils ʔalʔalš.\nsiʔsiʔab bəkʼʷaʔkʷbixʷ ʔugʷəc. ʔəsdᶻəw\'il əlgʷəʔ . ʔəstalx̌ əlgʷəʔ ʔəst\'ugʷud, ʔəsx̌əčbid ƛʼubexʷ əlgʷəʔ shuyils ʔalʔalš.\nsiʔsiʔab bəkʼʷaʔkʷbixʷ ʔugʷəc. ʔəsdᶻəw\'il əlgʷəʔ . ʔəstalx̌ əlgʷəʔ ʔəst\'ugʷud, ʔəsx̌əčbid ƛʼubexʷ əlgʷəʔ shuyils ʔalʔalš."
  specimen_16: "siʔsiʔab bəkʼʷaʔkʷbixʷ ʔugʷəc. ʔəsdᶻəw\'il əlgʷəʔ . ʔəstalx̌ əlgʷəʔ ʔəst\'ugʷud, ʔəsx̌əčbid ƛʼubexʷ əlgʷəʔ shuyils ʔalʔalš.\nsiʔsiʔab bəkʼʷaʔkʷbixʷ ʔugʷəc. ʔəsdᶻəw\'il əlgʷəʔ . ʔəstalx̌ əlgʷəʔ ʔəst\'ugʷud, ʔəsx̌əčbid ƛʼubexʷ əlgʷəʔ shuyils ʔalʔalš.\nsiʔsiʔab bəkʼʷaʔkʷbixʷ ʔugʷəc. ʔəsdᶻəw\'il əlgʷəʔ . ʔəstalx̌ əlgʷəʔ ʔəst\'ugʷud, ʔəsx̌əčbid ƛʼubexʷ əlgʷəʔ shuyils ʔalʔalš.\nsiʔsiʔab bəkʼʷaʔkʷbixʷ ʔugʷəc. ʔəsdᶻəw\'il əlgʷəʔ . ʔəstalx̌ əlgʷəʔ ʔəst\'ugʷud, ʔəsx̌əčbid ƛʼubexʷ əlgʷəʔ shuyils ʔalʔalš.\nsiʔsiʔab bəkʼʷaʔkʷbixʷ ʔugʷəc. ʔəsdᶻəw\'il əlgʷəʔ . ʔəstalx̌ əlgʷəʔ ʔəst\'ugʷud, ʔəsx̌əčbid ƛʼubexʷ əlgʷəʔ shuyils ʔalʔalš."
}
historical: true
