id: "mag"
language: "mag"
script: "Deva"
name: "Magahi"
autonym: "मगही"
population: 15913080
region: "IN"
exemplar_chars {
  base: "अ आ इ ई उ ऊ ऋ ए ऐ ओ औ क ख ग घ ङ च छ ज झ ञ ट ठ ड ढ ण त थ द ध न प फ ब भ म य र ल व श ष स ह ऎ ऒ ॳ ॴ ॵ ʼ ‌ ‍"
  auxiliary: "ॐ"
  marks: "◌ँ ◌ं ◌ः ◌ऺ ◌ऻ ◌़ ◌ा ◌ि ◌ी ◌ु ◌ू ◌ृ ◌ॆ ◌े ◌ै ◌ॊ ◌ो ◌ौ ◌् ◌ॏ"
  numerals: "० १ २ ३ ४ ५ ६ ७ ८ ९ 0 1 2 3 4 5 6 7 8 9"
  punctuation: "। ॥ ॰"
}
sample_text {
  masthead_full: "सबलग"
  masthead_partial: "आज"
  styles: "सभे के ओकर उचित सम्मान तथा मानव परिवार के सब सदस्य के"
  tester: "मानवाधिकार के उल्लंघन हरदम से अमानवीय काम के बजह से ही होव हई। जेकरा से मानवता के अंतकरण"
  poster_sm: "यदि कोइयो तानाशाही"
  poster_md: "संयुक्त राष्ट्र"
  poster_lg: "आजादे"
  specimen_48: "साथ में सदस्य राष्ट्र सब संयुक्त राष्ट्र के मदद से मानवाधिकार और मौलिक स्वतंत्रता के प्रति"
  specimen_36: "सभे के ओकर उचित सम्मान तथा मानव परिवार के सब सदस्य के बराबरी के हक ही विश्व समुदाय के स्वतंत्रता, न्याय और शांति के बुनियाद हई।\nअब, एही से,\nमहासभा,"
  specimen_32: "मानवाधिकार के उल्लंघन हरदम से अमानवीय काम के बजह से ही होव हई। जेकरा से मानवता के अंतकरण दु:खी होव हई। एक आम आदमी के सबसे बड़ा इच्छा इहे होव हई कि ए दुनिया में ओकरा भाषण और विचार के आजादी मीले साथ ही भय और इच्छा से भी मुक्ति मीले।"
  specimen_21: "सभे के ओकर उचित सम्मान तथा मानव परिवार के सब सदस्य के बराबरी के हक ही विश्व समुदाय के स्वतंत्रता, न्याय और शांति के बुनियाद हई।\nमानवाधिकार के उल्लंघन हरदम से अमानवीय काम के बजह से ही होव हई। जेकरा से मानवता के अंतकरण दु:खी होव हई। एक आम आदमी के सबसे बड़ा इच्छा इहे होव हई कि ए दुनिया में ओकरा भाषण और विचार के आजादी मीले साथ ही भय और इच्छा से भी मुक्ति मीले।\nयदि कोइयो तानाशाही या दमन के खिलाफ बगावत करे लेले मजबूर हई त ओकरा कानून से ओकर मानवाधिकार के सुरक्षा के इंतजाम होए के चाहीं। इहो आवश्यक हई कि राष्ट्र सब के बीच दोस्ती बढ़ाएल जाए।"
  specimen_16: "सभे के ओकर उचित सम्मान तथा मानव परिवार के सब सदस्य के बराबरी के हक ही विश्व समुदाय के स्वतंत्रता, न्याय और शांति के बुनियाद हई।\nमानवाधिकार के उल्लंघन हरदम से अमानवीय काम के बजह से ही होव हई। जेकरा से मानवता के अंतकरण दु:खी होव हई। एक आम आदमी के सबसे बड़ा इच्छा इहे होव हई कि ए दुनिया में ओकरा भाषण और विचार के आजादी मीले साथ ही भय और इच्छा से भी मुक्ति मीले।\nयदि कोइयो तानाशाही या दमन के खिलाफ बगावत करे लेले मजबूर हई त ओकरा कानून से ओकर मानवाधिकार के सुरक्षा के इंतजाम होए के चाहीं। इहो आवश्यक हई कि राष्ट्र सब के बीच दोस्ती बढ़ाएल जाए।\nसंयुक्त राष्ट्र के लोग सब अपन चार्टर में मौलिक मानवाधिकार, मानव के सम्मान और उपयोगिता तथा आदमी और औरत के बराबर अधिकार के प्रति अपन विश्वास जतेलकई हन। साथ ही उ आर स्वतंत्रता के माहौल में सामाजिक प्रगति तथा जीवन के स्तर के बढ़ावे लेल भी दृढ़ निश्चय कएलकई हन।"
}
