id: "mam_Latn"
language: "mam"
script: "Latn"
name: "Mam, Northern"
sample_text {
  masthead_full: "KkYy"
  masthead_partial: "Aa"
  styles: "K\ny\na\nq\ni\ni\nl\nq\ne\n \nw\ni\nn\na\nq\n \nn\nc\nh\ni\n "
  tester: "K\ny\na\nq\ni\ni\nl\nq\ne\n \nw\ni\nn\na\nq\n \nn\nc\nh\ni\n \ni\nt\nz\n\'\na\nj\n \nt\nu\nj"
  poster_sm: "K\ny\na\nq\ni\ni"
  poster_md: "K\ny\na\nq\ni"
  poster_lg: "K\ny"
  specimen_48: "K\ny\na\nq\ni\ni\nl\nq\ne\n \nw\ni\nn\na\nq\n \nn\nc\nh\ni\n \ni\nt\nz\n\'\na\nj\n \nt\nu\nj"
  specimen_36: "K\ny\na\nq\ni\ni\nl\nq\ne\n \nw\ni\nn\na\nq\n \nn\nc\nh\ni\n \ni\nt\nz\n\'\na\nj\n \nt\nu\nj\n \nk\no\np\ni\nb\n\'\ni\nl\n,\n \nj\nu\nu\nn\nx\n \nk\ny\nc\nh"
  specimen_32: "K\ny\na\nq\ni\ni\nl\nq\ne\n \nw\ni\nn\na\nq\n \nn\nc\nh\ni\n \ni\nt\nz\n\'\na\nj\n \nt\nu\nj\n \nk\no\np\ni\nb\n\'\ni\nl\n,\n \nj\nu\nu\nn\nx\n \nk\ny\nc\nh\nu\nw\ni\ni\nn\nq\na\nl\n \nb\n\'\ni\nx\n \nk\ny\no\nk\nl\ne\ne"
  specimen_21: "K\ny\na\nq\ni\ni\nl\nq\ne\n \nw\ni\nn\na\nq\n \nn\nc\nh\ni\n \ni\nt\nz\n\'\na\nj\n \nt\nu\nj\n \nk\no\np\ni\nb\n\'\ni\nl\n,\n \nj\nu\nu\nn\nx\n \nk\ny\nc\nh\nu\nw\ni\ni\nn\nq\na\nl\n \nb\n\'\ni\nx\n \nk\ny\no\nk\nl\ne\ne\nn\n,\n \nk\ny\nj\na\n\'\nt\nz\na\nn\n \nt\nu\nj\n \nt\nb\n\'\na\na\nn\na\nl\n \nx\ni\ni\nn\nv\n\'\ni\nl\n \nt\nu\n\'\nn\n \nk\ny\na\nn\nq\n\'\ni\ni\nn\n \nt\nu\nj\n \nb\n\'\na\nn\nk\n\'\nu\n\'\nj\n \nk\ny\nx\no\no\nl\n.\nK\ny\na\nq\ni\ni\nl\nq\ne\n \nw\ni\nn\na"
  specimen_16: "K\ny\na\nq\ni\ni\nl\nq\ne\n \nw\ni\nn\na\nq\n \nn\nc\nh\ni\n \ni\nt\nz\n\'\na\nj\n \nt\nu\nj\n \nk\no\np\ni\nb\n\'\ni\nl\n,\n \nj\nu\nu\nn\nx\n \nk\ny\nc\nh\nu\nw\ni\ni\nn\nq\na\nl\n \nb\n\'\ni\nx\n \nk\ny\no\nk\nl\ne\ne\nn\n,\n \nk\ny\nj\na\n\'\nt\nz\na\nn\n \nt\nu\nj\n \nt\nb\n\'\na\na\nn\na\nl\n \nx\ni\ni\nn\nv\n\'\ni\nl\n \nt\nu\n\'\nn\n \nk\ny\na\nn\nq\n\'\ni\ni\nn\n \nt\nu\nj\n \nb\n\'\na\nn\nk\n\'\nu\n\'\nj\n \nk\ny\nx\no\no\nl\n.\nK\ny\na\nq\ni\ni\nl\nq\ne\n \nw\ni\nn\na\nq\n \nn\nc\nh\ni\n \ni\nt\nz\n\'\na\nj\n \nt\nu\nj\n \nk\no\np\ni\nb\n\'\ni\nl\n,\n \nj\nu\nu\nn\nx\n \nk\ny\nc\nh\nu\nw\ni\ni\nn\nq\na\nl\n \nb\n\'\ni\nx\n \nk\ny\no\nk\nl\ne\ne\nn\n,\n \nk\ny\nj\na\n\'\nt\nz\na\nn\n \nt\nu\nj\n \nt\nb\n\'\na\na\nn\na\nl\n \nx\ni\ni\nn\nv\n\'\ni\nl\n \nt\nu\n\'\nn\n \nk\ny\na\nn\nq\n\'\ni\ni\nn\n \nt\nu\nj\n \nb\n\'\na\nn\nk\n\'\nu\n\'\nj\n \nk\ny\nx\no\no\nl\n.\nK\ny"
}
