id: "mas"
language: "mas"
script: "Latn"
name: "Masai"
autonym: "Maa"
population: 1734738
region: "KE"
region: "TZ"
exemplar_chars {
  base: "a á à â ā b c d e é è ê ē ɛ g h i í ì î ī ɨ j k l m n {ny} ŋ o ó ò ô ō ɔ p r {rr} s {sh} t u ú ù û ū ʉ {ʉ́} w {wu} y {yi} {ny} {rr} {sh} {ʉ́} {wu} {yi} {ny} {rr} {sh} {ʉ́} {wu} {yi} {ny} {rr} {sh} {ʉ́} {wu} {yi} {ny} {rr} {sh} {ʉ́} {wu} {yi} {ny} {rr} {sh} {ʉ́} {wu} {yi} {ny} {rr} {sh} {ʉ́} {wu} {yi} {ny} {rr} {sh} {ʉ́} {wu} {yi} {ny} {rr} {sh} {ʉ́} {wu} {yi} {ny} {rr} {sh} {ʉ́} {wu} {yi} {ny} {rr} {sh} {ʉ́} {wu} {yi} {ny} {rr} {sh} {ʉ́} {wu} {yi} {ny} {rr} {sh} {ʉ́} {wu} {yi} {ny} {rr} {sh} {ʉ́} {wu} {yi} {ny} {rr} {sh} {ʉ́} {wu} {yi} {ny} {rr} {sh} {ʉ́} {wu} {yi}"
  auxiliary: "f q v x z"
  marks: "◌̀ ◌́ ◌̂"
  index: "A B C D E Ɛ G H I Ɨ J K L M N Ŋ O Ɔ P R S T U Ʉ W Y"
}
sample_text {
  fallback_language: "en"
}
