id: "mcf_Latn"
language: "mcf"
script: "Latn"
name: "Matsés, Latin, Peru"
sample_text {
  masthead_full: "CcHh"
  masthead_partial: "Ii"
  styles: "C\nh\ni\nd\no\nn\n \nt\ni\ns\nh\na\ni\nd\no\n \ny\ne\nc\n \nm"
  tester: "C\nh\ni\nd\no\nn\n \nt\ni\ns\nh\na\ni\nd\no\n \ny\ne\nc\n \nm\na\nt\ns\ne\ns\n \na\nb\ni\nt"
  poster_sm: "C\nh\ni\nd\no\nn"
  poster_md: "C\nh\ni\nd\no"
  poster_lg: "C\nh"
  specimen_48: "C\nh\ni\nd\no\nn\n \nt\ni\ns\nh\na\ni\nd\no\n \ny\ne\nc\n \nm\na\nt\ns\ne\ns\n \na\nb\ni\nt"
  specimen_36: "C\nh\ni\nd\no\nn\n \nt\ni\ns\nh\na\ni\nd\no\n \ny\ne\nc\n \nm\na\nt\ns\ne\ns\n \na\nb\ni\nt\ne\nd\ni\nm\nb\no\n \nb\në\nd\na\nm\nb\no\ne\nc\n \ni\ns\nn"
  specimen_32: "C\nh\ni\nd\no\nn\n \nt\ni\ns\nh\na\ni\nd\no\n \ny\ne\nc\n \nm\na\nt\ns\ne\ns\n \na\nb\ni\nt\ne\nd\ni\nm\nb\no\n \nb\në\nd\na\nm\nb\no\ne\nc\n \ni\ns\nn\na\nn\na\nc\n \nb\në\nd\na\nm\nb\no\n \ni\nc\nt\ns\ni\na\ns"
  specimen_21: "C\nh\ni\nd\no\nn\n \nt\ni\ns\nh\na\ni\nd\no\n \ny\ne\nc\n \nm\na\nt\ns\ne\ns\n \na\nb\ni\nt\ne\nd\ni\nm\nb\no\n \nb\në\nd\na\nm\nb\no\ne\nc\n \ni\ns\nn\na\nn\na\nc\n \nb\në\nd\na\nm\nb\no\n \ni\nc\nt\ns\ni\na\ns\nh\n.\n \nC\nh\ni\ne\ns\nh\nn\na\nn\na\nc\n \ni\nc\ns\na\nm\nb\no\n \ni\nc\nt\ns\ni\na\ns\nh\n.\n \nA\nb\ni\nt\ne\nd\ni\nm\nb\no\n \nb\në\nd\na\nm\nb\no\ne\nc\n \nt\na\nb\na\nd\na\nc\n \nb\në\nd\na\nm\nb\no\n \ni\nc\nt\ns\ni\na\ns\nh\n.\n \nS"
  specimen_16: "C\nh\ni\nd\no\nn\n \nt\ni\ns\nh\na\ni\nd\no\n \ny\ne\nc\n \nm\na\nt\ns\ne\ns\n \na\nb\ni\nt\ne\nd\ni\nm\nb\no\n \nb\në\nd\na\nm\nb\no\ne\nc\n \ni\ns\nn\na\nn\na\nc\n \nb\në\nd\na\nm\nb\no\n \ni\nc\nt\ns\ni\na\ns\nh\n.\n \nC\nh\ni\ne\ns\nh\nn\na\nn\na\nc\n \ni\nc\ns\na\nm\nb\no\n \ni\nc\nt\ns\ni\na\ns\nh\n.\n \nA\nb\ni\nt\ne\nd\ni\nm\nb\no\n \nb\në\nd\na\nm\nb\no\ne\nc\n \nt\na\nb\na\nd\na\nc\n \nb\në\nd\na\nm\nb\no\n \ni\nc\nt\ns\ni\na\ns\nh\n.\n \nS\nh\nu\nb\nu\n \na\nb\ne\nn\nt\ns\në\nc\nq\nu\ni\nd\në\nn\n \nt\na\nb\na\nd\na\nc\n \nb\ni\nr\nn\nb\no\ne\nc\n \na\nb\ni\nt\ne\nd\ni\n \nt\na\nb\na\nd\na\nc\n \nb\në\nd\na\nm\nb\no\n \ni\nc\nt\ns\ni\na\ns\nh\n,\n \nq\nu\ne\nq\nu\ni\nn\n \nc\nh\nu\ni\np\na\nn\në\nd\na\ns\nh\n \nn\ni\nd\na\ni\nd\n \na\nb\ni\nt\ne\nd\ni\nn\no\në\ns\nh\n \nc\nh\no\n-\nc\nh\no\nq\nu\ni\nd\no\nn\n.\nC"
}
