id: "mfe"
language: "mfe"
script: "Latn"
name: "Morisyen"
preferred_name: "Mauritian Creole"
autonym: "Kreol Morisien"
population: 1241433
region: "MU"
exemplar_chars {
  base: "a b c d e f g h i j k l m n o p r s t u v w x y z"
  numerals: "  - ‑ . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B C D E F G H I J K L M N O P R S T U V W X Y Z"
}
sample_text {
  fallback_language: "en"
}
