id: "mgo"
language: "mgo"
script: "Latn"
name: "Metaʼ"
preferred_name: "Meta’"
autonym: "Mɨta’"
population: 130401
region: "CM"
exemplar_chars {
  base: "a à b {ch} d e è ə {ə̀} f g {gh} i ì j k m n ŋ o ò ɔ {ɔ̀} p r s t u ù w y z ʼ {ch} {ə̀} {gh} {ɔ̀} {ch} {ə̀} {gh} {ɔ̀} {ch} {ə̀} {gh} {ɔ̀} {ch} {ə̀} {gh} {ɔ̀} {ch} {ə̀} {gh} {ɔ̀} {ch} {ə̀} {gh} {ɔ̀} {ch} {ə̀} {gh} {ɔ̀} {ch} {ə̀} {gh} {ɔ̀} {ch} {ə̀} {gh} {ɔ̀} {ch} {ə̀} {gh} {ɔ̀} {ch} {ə̀} {gh} {ɔ̀} {ch} {ə̀} {gh} {ɔ̀} {ch} {ə̀} {gh} {ɔ̀} {ch} {ə̀} {gh} {ɔ̀} {ch} {ə̀} {gh} {ɔ̀}"
  auxiliary: "c h l q v x"
  marks: "◌̀"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: ", ; : ! ? . \' ‘ ’ \" “ ”"
  index: "A B {CH} D E Ə F G {GH} I J K M N Ŋ O Ɔ P R S T U W Y Z ʼ {CH} {GH} {CH} {GH} {CH} {GH} {CH} {GH} {CH} {GH} {CH} {GH} {CH} {GH} {CH} {GH} {CH} {GH} {CH} {GH} {CH} {GH} {CH} {GH} {CH} {GH} {CH} {GH} {CH} {GH}"
}
sample_text {
  fallback_language: "en"
}
