id: "min_Arab"
language: "min"
script: "Arab"
name: "Minangkabau, Arabic"
sample_text {
  masthead_full: "سادو"
  masthead_partial: "ڽم"
  styles: "س\nا\nد\nو\nڽ\nو\n \nم\nأ\nن\nس\nي\n \nد\nل\nه\nي\nا\nك\nن\n "
  tester: "س\nا\nد\nو\nڽ\nو\n \nم\nأ\nن\nس\nي\n \nد\nل\nه\nي\nا\nك\nن\n \nم\nر\nد\nي\nك\nا\n \nد\nا\nن"
  poster_sm: "س\nا\nد\nو\nڽ\nو"
  poster_md: "س\nا\nد\nو\nڽ"
  poster_lg: "س\nا"
  specimen_48: "س\nا\nد\nو\nڽ\nو\n \nم\nأ\nن\nس\nي\n \nد\nل\nه\nي\nا\nك\nن\n \nم\nر\nد\nي\nك\nا\n \nد\nا\nن"
  specimen_36: "س\nا\nد\nو\nڽ\nو\n \nم\nأ\nن\nس\nي\n \nد\nل\nه\nي\nا\nك\nن\n \nم\nر\nد\nي\nك\nا\n \nد\nا\nن\n \nڤ\nو\nڽ\nو\n \nم\nر\nت\nب\nت\n \nس\nا\nر\nا\nت\nو\n \nح"
  specimen_32: "س\nا\nد\nو\nڽ\nو\n \nم\nأ\nن\nس\nي\n \nد\nل\nه\nي\nا\nك\nن\n \nم\nر\nد\nي\nك\nا\n \nد\nا\nن\n \nڤ\nو\nڽ\nو\n \nم\nر\nت\nب\nت\n \nس\nا\nر\nا\nت\nو\n \nح\nق\n-\nح\nق\n \nن\nن\n \nس\nا\nم\nو\n.\n \nم\nر\nي\nك\n \nد\nك"
  specimen_21: "س\nا\nد\nو\nڽ\nو\n \nم\nأ\nن\nس\nي\n \nد\nل\nه\nي\nا\nك\nن\n \nم\nر\nد\nي\nك\nا\n \nد\nا\nن\n \nڤ\nو\nڽ\nو\n \nم\nر\nت\nب\nت\n \nس\nا\nر\nا\nت\nو\n \nح\nق\n-\nح\nق\n \nن\nن\n \nس\nا\nم\nو\n.\n \nم\nر\nي\nك\n \nد\nك\nا\nر\nو\nن\nي\nا\nي\n \nا\nك\nا\n \nج\nو\n \nه\nا\nت\nي\n \nن\nو\nر\nا\nن\nي\n،\n \nس\nو\nڤ\nي\nو\n \nس\nا\nت\nو\n \nس\nا\nم\nو\n \nل\nا\nي\nن\n \nب\nا\nڬ\nا\nو\nل\n \nس\nا\nر\nو\nڤ\nو\n \nا\nو\nر\nڠ\n \nب\nا\nد\nو\nن\nس\nا\nن\nق\n.\nس\nا\nد"
  specimen_16: "س\nا\nد\nو\nڽ\nو\n \nم\nأ\nن\nس\nي\n \nد\nل\nه\nي\nا\nك\nن\n \nم\nر\nد\nي\nك\nا\n \nد\nا\nن\n \nڤ\nو\nڽ\nو\n \nم\nر\nت\nب\nت\n \nس\nا\nر\nا\nت\nو\n \nح\nق\n-\nح\nق\n \nن\nن\n \nس\nا\nم\nو\n.\n \nم\nر\nي\nك\n \nد\nك\nا\nر\nو\nن\nي\nا\nي\n \nا\nك\nا\n \nج\nو\n \nه\nا\nت\nي\n \nن\nو\nر\nا\nن\nي\n،\n \nس\nو\nڤ\nي\nو\n \nس\nا\nت\nو\n \nس\nا\nم\nو\n \nل\nا\nي\nن\n \nب\nا\nڬ\nا\nو\nل\n \nس\nا\nر\nو\nڤ\nو\n \nا\nو\nر\nڠ\n \nب\nا\nد\nو\nن\nس\nا\nن\nق\n.\nس\nا\nد\nو\nڽ\nو\n \nم\nأ\nن\nس\nي\n \nد\nل\nه\nي\nا\nك\nن\n \nم\nر\nد\nي\nك\nا\n \nد\nا\nن\n \nڤ\nو\nڽ\nو\n \nم\nر\nت\nب\nت\n \nس\nا\nر\nا\nت\nو\n \nح\nق\n-\nح\nق\n \nن\nن\n \nس\nا\nم\nو\n.\n \nم\nر\nي\nك\n \nد\nك\nا\nر\nو\nن\nي\nا\nي\n \nا\nك\nا\n \nج\nو\n \nه\nا\nت\nي\n \nن\nو\nر\nا\nن\nي\n،\n \nس\nو\nڤ\nي\nو\n \nس\nا\nت\nو\n \nس\nا\nم\nو\n \nل\nا\nي\nن\n \nب\nا\nڬ\nا\nو\nل\n \nس"
}
