id: "mis_Arab"
language: "mis"
script: "Arab"
name: "Uncoded languages, Arabic"
sample_text {
  masthead_full: "كلوا"
  masthead_partial: "نف"
  styles: "ك\nل\nو\nا\n \nن\nف\nر\n \nف\nي\n \nو\nل\nا\nد\nة\n \nح\nر\n "
  tester: "ك\nل\nو\nا\n \nن\nف\nر\n \nف\nي\n \nو\nل\nا\nد\nة\n \nح\nر\n \nو\nس\nم\nس\nم\n \nف\nي\n \nك"
  poster_sm: "ك\nل\nو\nا\n \nن"
  poster_md: "ك\nل\nو\nا\n "
  poster_lg: "ك\nل"
  specimen_48: "ك\nل\nو\nا\n \nن\nف\nر\n \nف\nي\n \nو\nل\nا\nد\nة\n \nح\nر\n \nو\nس\nم\nس\nم\n \nف\nي\n \nك"
  specimen_36: "ك\nل\nو\nا\n \nن\nف\nر\n \nف\nي\n \nو\nل\nا\nد\nة\n \nح\nر\n \nو\nس\nم\nس\nم\n \nف\nي\n \nك\nر\nا\nم\nة\n \nو\nس\nم\nس\nم\n \nف\nي\n \nح\nق\nو\nق\n.\n "
  specimen_32: "ك\nل\nو\nا\n \nن\nف\nر\n \nف\nي\n \nو\nل\nا\nد\nة\n \nح\nر\n \nو\nس\nم\nس\nم\n \nف\nي\n \nك\nر\nا\nم\nة\n \nو\nس\nم\nس\nم\n \nف\nي\n \nح\nق\nو\nق\n.\n \nا\nل\nل\nه\n \nف\nي\n \nإ\nع\nط\nى\n \nه\nو\n \nع\nق\nل\n "
  specimen_21: "ك\nل\nو\nا\n \nن\nف\nر\n \nف\nي\n \nو\nل\nا\nد\nة\n \nح\nر\n \nو\nس\nم\nس\nم\n \nف\nي\n \nك\nر\nا\nم\nة\n \nو\nس\nم\nس\nم\n \nف\nي\n \nح\nق\nو\nق\n.\n \nا\nل\nل\nه\n \nف\nي\n \nإ\nع\nط\nى\n \nه\nو\n \nع\nق\nل\n \nو\nض\nم\nي\nر\n،\n \nو\nل\nا\nز\nم\n \nه\nو\n \nس\nو\nي\n \nم\nع\n \nت\nا\nن\nي\n \nن\nف\nر\n \nس\nم\nس\nم\n \nأ\nخ\nك\nل\nو\nا\n \nن\nف\nر\n \nف\nي\n \nو\nل\nا\nد\nة\n \nح\nر\n \nو\nس\nم\nس\nم\n \nف\nي\n \nك\nر\nا\nم\nة\n \nو\nس\nم\nس\nم\n "
  specimen_16: "ك\nل\nو\nا\n \nن\nف\nر\n \nف\nي\n \nو\nل\nا\nد\nة\n \nح\nر\n \nو\nس\nم\nس\nم\n \nف\nي\n \nك\nر\nا\nم\nة\n \nو\nس\nم\nس\nم\n \nف\nي\n \nح\nق\nو\nق\n.\n \nا\nل\nل\nه\n \nف\nي\n \nإ\nع\nط\nى\n \nه\nو\n \nع\nق\nل\n \nو\nض\nم\nي\nر\n،\n \nو\nل\nا\nز\nم\n \nه\nو\n \nس\nو\nي\n \nم\nع\n \nت\nا\nن\nي\n \nن\nف\nر\n \nس\nم\nس\nم\n \nأ\nخ\nك\nل\nو\nا\n \nن\nف\nر\n \nف\nي\n \nو\nل\nا\nد\nة\n \nح\nر\n \nو\nس\nم\nس\nم\n \nف\nي\n \nك\nر\nا\nم\nة\n \nو\nس\nم\nس\nم\n \nف\nي\n \nح\nق\nو\nق\n.\n \nا\nل\nل\nه\n \nف\nي\n \nإ\nع\nط\nى\n \nه\nو\n \nع\nق\nل\n \nو\nض\nم\nي\nر\n،\n \nو\nل\nا\nز\nم\n \nه\nو\n \nس\nو\nي\n \nم\nع\n \nت\nا\nن\nي\n \nن\nف\nر\n \nس\nم\nس\nم\n \nأ\nخ\nك\nل\nو\nا\n \nن\nف\nر\n \nف\nي\n \nو\nل\nا\nد\nة\n \nح\nر\n \nو\nس\nم\nس\nم\n \nف\nي\n \nك\nر\nا\nم\nة\n \nو\nس\nم\nس\nم\n \nف\nي\n \nح\nق\nو\nق\n.\n \nا\nل\nل\nه\n \nف\nي"
}
