id: "mis_Latn"
language: "mis"
script: "Latn"
name: "Uncoded languages, Latin, World"
region: "ES"
region: "FR"
sample_text {
  masthead_full: "Hh₂Ó"
  masthead_partial: "Ll"
  styles: "hólyoes ǵʰmónes hléwdʰeroes somHóeskʷe"
  tester: "h₂ólyoes ǵʰmónes h₁léwdʰeroes somHóeskʷe gʷr̥Htóteh₂ti h₃r̥ǵtúsukʷe"
  poster_sm: "h₂ólyoes"
  poster_md: "h₂ólyoes"
  poster_lg: "h₂ólyoes"
  specimen_48: "h₂ólyoes ǵʰmónes h₁léwdʰeroes somHóeskʷe gʷr̥Htóteh₂ti h₃r̥ǵtúsukʷe ǵn"
  specimen_36: "h₂ólyoes ǵʰmónes h₁léwdʰeroes somHóeskʷe gʷr̥Htóteh₂ti h₃r̥ǵtúsukʷe ǵn̥h₁yóntor. éybʰos dh₃tóy ménos ḱḗrkʷe h₁stés h₂énteroeykʷe sm̥h₂éleyes bʰréh₂tr̥bʰos swé h₂éǵoyh₁n̥t."
  specimen_32: "h₂ólyoes ǵʰmónes h₁léwdʰeroes somHóeskʷe gʷr̥Htóteh₂ti h₃r̥ǵtúsukʷe ǵn̥h₁yóntor. éybʰos dh₃tóy ménos ḱḗrkʷe h₁stés h₂énteroeykʷe sm̥h₂éleyes bʰréh₂tr̥bʰos swé h₂éǵoyh₁n̥t."
  specimen_21: "h₂ólyoes ǵʰmónes h₁léwdʰeroes somHóeskʷe gʷr̥Htóteh₂ti h₃r̥ǵtúsukʷe ǵn̥h₁yóntor. éybʰos dh₃tóy ménos ḱḗrkʷe h₁stés h₂énteroeykʷe sm̥h₂éleyes bʰréh₂tr̥bʰos swé h₂éǵoyh₁n̥t.\nh₂ólyoes ǵʰmónes h₁léwdʰeroes somHóeskʷe gʷr̥Htóteh₂ti h₃r̥ǵtúsukʷe ǵn̥h₁yóntor. éybʰos dh₃tóy ménos ḱḗrkʷe h₁stés h₂énteroeykʷe sm̥h₂éleyes bʰréh₂tr̥bʰos swé h₂éǵoyh₁n̥t."
  specimen_16: "h₂ólyoes ǵʰmónes h₁léwdʰeroes somHóeskʷe gʷr̥Htóteh₂ti h₃r̥ǵtúsukʷe ǵn̥h₁yóntor. éybʰos dh₃tóy ménos ḱḗrkʷe h₁stés h₂énteroeykʷe sm̥h₂éleyes bʰréh₂tr̥bʰos swé h₂éǵoyh₁n̥t.\nh₂ólyoes ǵʰmónes h₁léwdʰeroes somHóeskʷe gʷr̥Htóteh₂ti h₃r̥ǵtúsukʷe ǵn̥h₁yóntor. éybʰos dh₃tóy ménos ḱḗrkʷe h₁stés h₂énteroeykʷe sm̥h₂éleyes bʰréh₂tr̥bʰos swé h₂éǵoyh₁n̥t.\nh₂ólyoes ǵʰmónes h₁léwdʰeroes somHóeskʷe gʷr̥Htóteh₂ti h₃r̥ǵtúsukʷe ǵn̥h₁yóntor. éybʰos dh₃tóy ménos ḱḗrkʷe h₁stés h₂énteroeykʷe sm̥h₂éleyes bʰréh₂tr̥bʰos swé h₂éǵoyh₁n̥t.\nh₂ólyoes ǵʰmónes h₁léwdʰeroes somHóeskʷe gʷr̥Htóteh₂ti h₃r̥ǵtúsukʷe ǵn̥h₁yóntor. éybʰos dh₃tóy ménos ḱḗrkʷe h₁stés h₂énteroeykʷe sm̥h₂éleyes bʰréh₂tr̥bʰos swé h₂éǵoyh₁n̥t."
}
