id: "mis_Nshu"
language: "mis"
script: "Nshu"
name: "Xiangnan Tuhua"
preferred_name: "Tuhua"
region: "CN"
sample_text {
  masthead_full: "𛅰𛇤𛈕𛅸"
  masthead_partial: "𛅰𛇤"
  styles: "𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕"
  tester: "𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕"
  poster_sm: "𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕"
  poster_md: "𛇤𛅰𛈕𛅸𛇃"
  poster_lg: "𛇤𛅰𛈕"
  specimen_48: "𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕"
  specimen_36: "𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕"
  specimen_32: "𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕"
  specimen_21: "𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕"
  specimen_16: "𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕\n𛇤𛅰𛈕𛅸𛇃𛆤𛈕"
}
