id: "mn_Mong"
language: "mn"
script: "Mong"
name: "Mongolian (Mongolian)"
population: 3624452
region: "CN"
sample_text {
  masthead_full: "ᠬᠦᠮᠨ"
  masthead_partial: "ᠪᠷ"
  styles: "ᠬ\nᠦ\nᠮ\nᠦ\nᠨ\n \nᠪ\nᠦ\nᠷ\n \nᠲ\nᠥ\nᠷ\nᠥ\nᠵ\nᠦ\n \nᠮ\nᠡ\nᠨ\nᠳ"
  tester: "ᠬ\nᠦ\nᠮ\nᠦ\nᠨ\n \nᠪ\nᠦ\nᠷ\n \nᠲ\nᠥ\nᠷ\nᠥ\nᠵ\nᠦ\n \nᠮ\nᠡ\nᠨ\nᠳ\nᠡ\nᠯ\nᠡ\nᠬ\nᠦ\n \nᠡ\nᠷ\nᠬ\nᠡ"
  poster_sm: "ᠬ\nᠦ\nᠮ\nᠦ\nᠨ\n "
  poster_md: "ᠬ\nᠦ\nᠮ\nᠦ\nᠨ"
  poster_lg: "ᠬ\nᠦ"
  specimen_48: "ᠬ\nᠦ\nᠮ\nᠦ\nᠨ\n \nᠪ\nᠦ\nᠷ\n \nᠲ\nᠥ\nᠷ\nᠥ\nᠵ\nᠦ\n \nᠮ\nᠡ\nᠨ\nᠳ\nᠡ\nᠯ\nᠡ\nᠬ\nᠦ\n \nᠡ\nᠷ\nᠬ\nᠡ"
  specimen_36: "ᠬ\nᠦ\nᠮ\nᠦ\nᠨ\n \nᠪ\nᠦ\nᠷ\n \nᠲ\nᠥ\nᠷ\nᠥ\nᠵ\nᠦ\n \nᠮ\nᠡ\nᠨ\nᠳ\nᠡ\nᠯ\nᠡ\nᠬ\nᠦ\n \nᠡ\nᠷ\nᠬ\nᠡ\n \nᠴ\nᠢ\nᠯ\nᠥ\nᠭ\nᠡ\n \nᠲ\nᠡ\nᠢ\n᠂\n \nᠠ\nᠳ\nᠠ\nᠯ\nᠢ\nᠬ\nᠠ"
  specimen_32: "ᠬ\nᠦ\nᠮ\nᠦ\nᠨ\n \nᠪ\nᠦ\nᠷ\n \nᠲ\nᠥ\nᠷ\nᠥ\nᠵ\nᠦ\n \nᠮ\nᠡ\nᠨ\nᠳ\nᠡ\nᠯ\nᠡ\nᠬ\nᠦ\n \nᠡ\nᠷ\nᠬ\nᠡ\n \nᠴ\nᠢ\nᠯ\nᠥ\nᠭ\nᠡ\n \nᠲ\nᠡ\nᠢ\n᠂\n \nᠠ\nᠳ\nᠠ\nᠯ\nᠢ\nᠬ\nᠠ\nᠨ\n \nᠨ\nᠡ\nᠷ\n᠎\nᠡ\n \nᠲ\nᠥ\nᠷ\nᠥ\n \nᠲ\nᠡ\nᠢ\n᠂\n \nᠢ\nᠵ\nᠢ"
  specimen_21: "ᠬ\nᠦ\nᠮ\nᠦ\nᠨ\n \nᠪ\nᠦ\nᠷ\n \nᠲ\nᠥ\nᠷ\nᠥ\nᠵ\nᠦ\n \nᠮ\nᠡ\nᠨ\nᠳ\nᠡ\nᠯ\nᠡ\nᠬ\nᠦ\n \nᠡ\nᠷ\nᠬ\nᠡ\n \nᠴ\nᠢ\nᠯ\nᠥ\nᠭ\nᠡ\n \nᠲ\nᠡ\nᠢ\n᠂\n \nᠠ\nᠳ\nᠠ\nᠯ\nᠢ\nᠬ\nᠠ\nᠨ\n \nᠨ\nᠡ\nᠷ\n᠎\nᠡ\n \nᠲ\nᠥ\nᠷ\nᠥ\n \nᠲ\nᠡ\nᠢ\n᠂\n \nᠢ\nᠵ\nᠢ\nᠯ\n \nᠡ\nᠷ\nᠬ\nᠡ\n \nᠲ\nᠡ\nᠢ\n \nᠪ\nᠠ\nᠢ\nᠠ\nᠭ\n᠃\n \nᠣ\nᠶ\nᠤ\nᠨ\n \nᠤ\nᠬ\nᠠ\nᠭ\nᠠ\nᠨ\n᠂\n \nᠨ\nᠠ\nᠨ\nᠳ\nᠢ\nᠨ\n \nᠴ\nᠢ\nᠨ\nᠠ\nᠷ\n \nᠵ\nᠠ\nᠶ\nᠠ\nᠭ\nᠠ\nᠰ\nᠠ\nᠨ\n \nᠬ\nᠦ\nᠮ\nᠦ\nᠨ\n \nᠬ\nᠡ\nᠭ\nᠴ\nᠢ\n \nᠥ\nᠭ\nᠡ\nᠷ\n᠎\nᠡ\n \nᠬ\nᠣ\nᠭ\nᠣ\nᠷ\nᠣ\nᠨ\nᠳ\nᠣ"
  specimen_16: "ᠬ\nᠦ\nᠮ\nᠦ\nᠨ\n \nᠪ\nᠦ\nᠷ\n \nᠲ\nᠥ\nᠷ\nᠥ\nᠵ\nᠦ\n \nᠮ\nᠡ\nᠨ\nᠳ\nᠡ\nᠯ\nᠡ\nᠬ\nᠦ\n \nᠡ\nᠷ\nᠬ\nᠡ\n \nᠴ\nᠢ\nᠯ\nᠥ\nᠭ\nᠡ\n \nᠲ\nᠡ\nᠢ\n᠂\n \nᠠ\nᠳ\nᠠ\nᠯ\nᠢ\nᠬ\nᠠ\nᠨ\n \nᠨ\nᠡ\nᠷ\n᠎\nᠡ\n \nᠲ\nᠥ\nᠷ\nᠥ\n \nᠲ\nᠡ\nᠢ\n᠂\n \nᠢ\nᠵ\nᠢ\nᠯ\n \nᠡ\nᠷ\nᠬ\nᠡ\n \nᠲ\nᠡ\nᠢ\n \nᠪ\nᠠ\nᠢ\nᠠ\nᠭ\n᠃\n \nᠣ\nᠶ\nᠤ\nᠨ\n \nᠤ\nᠬ\nᠠ\nᠭ\nᠠ\nᠨ\n᠂\n \nᠨ\nᠠ\nᠨ\nᠳ\nᠢ\nᠨ\n \nᠴ\nᠢ\nᠨ\nᠠ\nᠷ\n \nᠵ\nᠠ\nᠶ\nᠠ\nᠭ\nᠠ\nᠰ\nᠠ\nᠨ\n \nᠬ\nᠦ\nᠮ\nᠦ\nᠨ\n \nᠬ\nᠡ\nᠭ\nᠴ\nᠢ\n \nᠥ\nᠭ\nᠡ\nᠷ\n᠎\nᠡ\n \nᠬ\nᠣ\nᠭ\nᠣ\nᠷ\nᠣ\nᠨ\nᠳ\nᠣ\n᠎\nᠨ\n \nᠠ\nᠬ\nᠠ\nᠨ\n \nᠳ\nᠡ\nᠭ\nᠦ\nᠦ\n \nᠢ\nᠨ\n \nᠦ\nᠵ\nᠢ\nᠯ\n \nᠰ\nᠠ\nᠨ\nᠠ\nᠭ\nᠠ\n \nᠥ\nᠠ\nᠷ\n \nᠬ\nᠠ\nᠷ\nᠢ\nᠴ\nᠠ\nᠬ\nᠥ\n \nᠤ\nᠴ\nᠢ\nᠷ\n \nᠲ\nᠠ\nᠢ\n᠃\nᠬ\nᠦ\nᠮ\nᠦ\nᠨ\n \nᠪ\nᠦ\nᠷ\n \nᠲ\nᠥ\nᠷ\nᠥ\nᠵ\nᠦ\n \nᠮ\nᠡ\nᠨ\nᠳ\nᠡ\nᠯ\nᠡ\nᠬ\nᠦ\n \nᠡ\nᠷ\nᠬ\nᠡ\n \nᠴ\nᠢ\nᠯ\nᠥ\nᠭ\nᠡ\n \nᠲ\nᠡ\nᠢ\n᠂\n \nᠠ\nᠳ\nᠠ\nᠯ\nᠢ\nᠬ\nᠠ\nᠨ\n \nᠨ\nᠡ\nᠷ\n᠎\nᠡ\n \nᠲ\nᠥ\nᠷ\nᠥ\n \nᠲ\nᠡ\nᠢ\n᠂\n \nᠢ\nᠵ\nᠢ\nᠯ\n \nᠡ\nᠷ"
}
historical: true
