id: "mor_Latn"
language: "mor"
script: "Latn"
name: "Moro"
sample_text {
  masthead_full: "LlEe"
  masthead_partial: "Đđ"
  styles: "L\ne\nđ\na\n \np\nr\ne\nđ\n \nl\na\nl\nǝ\nŋ\nǝ\nn\ni\na\n \nl"
  tester: "L\ne\nđ\na\n \np\nr\ne\nđ\n \nl\na\nl\nǝ\nŋ\nǝ\nn\ni\na\n \nl\në\nb\nǝ\nr\në\ni\nn\ni\na\nl"
  poster_sm: "L\ne\nđ\na\n \np"
  poster_md: "L\ne\nđ\na\n "
  poster_lg: "L\ne"
  specimen_48: "L\ne\nđ\na\n \np\nr\ne\nđ\n \nl\na\nl\nǝ\nŋ\nǝ\nn\ni\na\n \nl\në\nb\nǝ\nr\në\ni\nn\ni\na\nl"
  specimen_36: "L\ne\nđ\na\n \np\nr\ne\nđ\n \nl\na\nl\nǝ\nŋ\nǝ\nn\ni\na\n \nl\në\nb\nǝ\nr\në\ni\nn\ni\na\nl\no\n \nn\na\n \nl\nǝ\nɽ\nǝ\nw\na\nṯ\no\n \ne\nŋ\ne\nn\n \nŋ"
  specimen_32: "L\ne\nđ\na\n \np\nr\ne\nđ\n \nl\na\nl\nǝ\nŋ\nǝ\nn\ni\na\n \nl\në\nb\nǝ\nr\në\ni\nn\ni\na\nl\no\n \nn\na\n \nl\nǝ\nɽ\nǝ\nw\na\nṯ\no\n \ne\nŋ\ne\nn\n \nŋ\nǝ\nđ\na\nm\ni\na\n \nn\na\n \ne\nŋ\ne\nn\n \np\nr\ne\nđ\n "
  specimen_21: "L\ne\nđ\na\n \np\nr\ne\nđ\n \nl\na\nl\nǝ\nŋ\nǝ\nn\ni\na\n \nl\në\nb\nǝ\nr\në\ni\nn\ni\na\nl\no\n \nn\na\n \nl\nǝ\nɽ\nǝ\nw\na\nṯ\no\n \ne\nŋ\ne\nn\n \nŋ\nǝ\nđ\na\nm\ni\na\n \nn\na\n \ne\nŋ\ne\nn\n \np\nr\ne\nđ\n \ni\nŋ\ni\n \nŋ\nǝ\nr\nc\na\nđ\na\nṯ\no\n \nṯ\na\n \nl\ne\nđ\na\n \na\nl\nǝ\nf\ni\nđ\ni\n.\n \nL\në\nn\nŋ\nu\nl\nu\n \np\nr\ne\nđ\n \nl\na\nn\na\nn\në\ni\nn\nu\n \nđ\nǝ\nn\na\nc\na\n \nđ\na\nm\ne\n \nɽ\ne\nt\nǝ\nɽ\ne\nt\no\n \nn\na\n \na\nr"
  specimen_16: "L\ne\nđ\na\n \np\nr\ne\nđ\n \nl\na\nl\nǝ\nŋ\nǝ\nn\ni\na\n \nl\në\nb\nǝ\nr\në\ni\nn\ni\na\nl\no\n \nn\na\n \nl\nǝ\nɽ\nǝ\nw\na\nṯ\no\n \ne\nŋ\ne\nn\n \nŋ\nǝ\nđ\na\nm\ni\na\n \nn\na\n \ne\nŋ\ne\nn\n \np\nr\ne\nđ\n \ni\nŋ\ni\n \nŋ\nǝ\nr\nc\na\nđ\na\nṯ\no\n \nṯ\na\n \nl\ne\nđ\na\n \na\nl\nǝ\nf\ni\nđ\ni\n.\n \nL\në\nn\nŋ\nu\nl\nu\n \np\nr\ne\nđ\n \nl\na\nn\na\nn\në\ni\nn\nu\n \nđ\nǝ\nn\na\nc\na\n \nđ\na\nm\ne\n \nɽ\ne\nt\nǝ\nɽ\ne\nt\no\n \nn\na\n \na\nr\na\n \ng\nǝ\nŋ\nǝ\nr\na\n \nŋ\ne\nn\nŋ\na\nn\nṯ\na\n \na\nl\nǝ\nɽ\nǝ\nw\na\nđ\na\nṯ\ne\n \na\nl\na\nm\nǝ\nđ\na\ni\nđ\ne\n \nb\nǝ\nɽ\na\nn\n \nu\ns\ni\nl\na\ng\na\n \ng\nǝ\nŋ\nǝ\nl\nǝ\nŋ\nǝ\nn\ni\na\n \nn\na\n \ng\nǝ\nŋ\no\nr\nb\na\n.\nL\ne\nđ\na\n \np\nr\ne\nđ\n \nl\na\nl\nǝ\nŋ\nǝ\nn\ni\na\n \nl\në\nb\nǝ\nr\në\ni\nn\ni\na\nl\no\n \nn\na\n \nl\nǝ\nɽ\nǝ\nw\na\nṯ\no\n \ne\nŋ\ne"
}
