id: "mr"
language: "mr"
script: "Deva"
name: "Marathi"
autonym: "मराठी"
population: 92826300
region: "IN"
exemplar_chars {
  base: "़ ॐ ं ँ ः अ आ इ ई उ ऊ ऋ ऌ ऍ ए ऐ ऑ ओ औ क ख ग घ ङ च छ ज झ ञ ट ठ ड ढ ण त थ द ध न प फ ब भ म य र ऱ ल व श ष स ह ळ ऽ ा ि ी ु ू ृ ॄ ॅ े ै ॉ ो ौ ्"
  auxiliary: "‌‍"
  marks: "◌ँ ◌ं ◌ः ◌़ ◌ा ◌ि ◌ी ◌ु ◌ू ◌ृ ◌े ◌ै ◌ो ◌ौ ◌्"
  numerals: "- ‑ , . % ‰ + 0० 1१ 2२ 3३ 4४ 5५ 6६ 7७ 8८ 9९"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ \" “ ” ( ) [ ] @ * / & # ′ ″"
  index: "‍ ॐ ं ः अ आ इ ई उ ऊ ऋ ऌ ए ऐ ऑ ओ औ क ख ग घ ङ च छ ज झ ञ ट ठ ड ढ ण त थ द ध न प फ ब भ म य र ल व श ष स ह ळ ऽ ॅ ्"
}
sample_text {
  masthead_full: "सरवम"
  masthead_partial: "नय"
  styles: "ज्या अर्थी मानव कुटुँवातील सर्व व्यक्तींची स्वाभाविक प्रतिष्ठा व"
  tester: "ज्या अर्थी, मानवी अधिकारांची अबहेलना व अप्रतिष्ठा झाल्याने अमानुष कृत्ये घडून आली आणि त्यायोगे"
  poster_sm: "ज्या अर्थी, जुलूम"
  poster_md: "ज्या अर्थी, राष्ट्र"
  poster_lg: "सर्व"
  specimen_48: "ज्या अर्थी, संयुक्त राष्ट्रसंघटनेतील सदस्य-राष्ट्रांनी सनदेत मूलभूत मानवी अधिकार मानवाची प्रतिष्ठा"
  specimen_36: "घटनेने किंवा कायद्याने दिलेल्या मूलभूत हक्कांचा भंग करण्यार्‍या कृत्यांच्या बाबतीत सक्षम राष्ट्रीय अधिकारणा मार्फत परिणाम-कारक उपाययोजना करण्याचा प्रत्येकास अधिकार आहे."
  specimen_32: "प्रत्येकाला समान भूमिकेवरून त्याचे अधिकार व जवाबदार्‍या निश्चित करण्याच्या संबंधात किंवा त्याच्यावरील कोणत्याहि दंडनीय आरोपाचा न्यायनिर्णय करण्याच्या संबंधात स्वतंत्र व निःपक्षपाती अधिकरणामार्फत न्याय्य व जाहीर सुनावणी केली जाण्याचा हक्क आहे."
  specimen_21: "कोणाचेहि खाजगी जीवन, त्याचे कुटुंब, घर अथवा त्याचा पत्रव्यवहार यांच्या संबंधात स्वच्छंद ढवळाढवळ होता कामा नये; त्याचप्रमाणे त्याची प्रतिष्ठा किंवा नावलौकिक यावर हल्ला होता कामा नये. अशी ढवळाढवळ किंवा हल्ला झाल्यास त्याविरुद्ध प्रत्येकास कायद्याने संरक्षण मिळण्याचा अधिकार आहे.\nप्रत्येकास विचारस्वातंत्र्य, आपल्या सदसद्विवेकबुद्धिनुसार वागण्याचे स्वातंत्र्य असण्याचा अधिकार आहे या अधिकारांत स्वतःचा धर्म अथवा श्रद्धा बदलण्याच्या स्वातंत्र्याचा आणि एकट्याने वा इतरांसह सामुदायिकरीत्या आपला धर्म अथवा श्रद्धा, शिकवणुकीत, व्यवहारात, उपासनेत व आचरणात जाहीर रीतीने अथवा खासगी रीतीने व्यक्त करण्याच्चा स्वातंत्र्याचा समावेश होतो."
  specimen_16: "प्रत्येकास मतस्वातंत्र्य व भाषणस्वातंत्र्य असण्याचा अधिकार आहे. या अधिकारात कोणतीही ढवळाढवळ न होता मत बाळगण्याच्या स्वातंत्र्याचा. तसेच कोणत्याही माध्यमातून व सीमांचा विचार न करता माहिती व विचार ग्रहण करण्याचा प्रयत्न करणे, ती मिळविणे व इतरांना ती देणे यासंबंधीच्या स्वातंत्र्याचा समावेश होतो.\nप्रत्येकास समाजाचा एक घटक या नात्याने सामाजिक सुरक्षितता प्राप्त करून घेण्याचा अधिकार आहे आणि राष्ट्रीय प्रयत्न व आंतरराष्ट्रीय सहकार्य यांच्या द्वारे व प्रत्येक राष्ट्राच्या व्यवस्थेनुसार व साधनसंमतीनुसार आपल्या प्रतिष्ठेस व आपल्या व्यक्तिमत्वाच्या मुक्त विकासासाठी अनिवार्य असलेले आर्थिक, सामाजिक व सांस्कृतिक अधिकार संपादन करण्याचा हक्क आहे.\nवाजवी मर्यांदा असलेले कामाचे तास व ठराविक मुदतीने पगारी सुट्या धरून प्रत्येकास विश्रांति व आराम मिळण्याचा अधिकार आहे.\nह्या जाहीरनाम्यात ग्रथित केलेले अधिकार व स्वातंत्र्य पूर्णपणे साध्य करता येतील अशा सामाजिक व आंतरराष्ट्रीय व्यवस्थेचा प्रत्येकास हक्क आहे."
}
