id: "mrw_Arab"
language: "mrw"
script: "Arab"
name: "Maranao, Arabic"
region: "PH"
sample_text {
  masthead_full: "لاڠو"
  masthead_partial: "نع"
  styles: "لاڠون ع تاو نا اينيمباواتا ع ندُدون سو كڤاعر"
  tester: "لاڠون ع تاو نا اينيمباواتا ع ندُدون سو كڤاعر اڬو نداتاداتار سا"
  poster_sm: "لاڠون ع تاو"
  poster_md: "لاڠون"
  poster_lg: "لاڠون"
  specimen_48: "لاڠون ع تاو نا اينيمباواتا ع ندُدون سو كڤاعر اڬو نداتاداتار سا بانتوڬان"
  specimen_36: "لاڠون ع تاو نا اينيمباواتا ع ندُدون سو كڤاعر اڬو نداتاداتار سا بانتوڬان اڬو كابنار۔ بيڬان سيران سا كابنار اڬو ڬاڬاو نا عيا ڤاتوت ع دي كاڤاكاسُسُروتا عو اوماني ايسا كو كاڤاكيڤحاڤاڬارِيا۔"
  specimen_32: "لاڠون ع تاو نا اينيمباواتا ع ندُدون سو كڤاعر اڬو نداتاداتار سا بانتوڬان اڬو كابنار۔ بيڬان سيران سا كابنار اڬو ڬاڬاو نا عيا ڤاتوت ع دي كاڤاكاسُسُروتا عو اوماني ايسا كو كاڤاكيڤحاڤاڬارِيا۔"
  specimen_21: "لاڠون ع تاو نا اينيمباواتا ع ندُدون سو كڤاعر اڬو نداتاداتار سا بانتوڬان اڬو كابنار۔ بيڬان سيران سا كابنار اڬو ڬاڬاو نا عيا ڤاتوت ع دي كاڤاكاسُسُروتا عو اوماني ايسا كو كاڤاكيڤحاڤاڬارِيا۔\nلاڠون ع تاو نا اينيمباواتا ع ندُدون سو كڤاعر اڬو نداتاداتار سا بانتوڬان اڬو كابنار۔ بيڬان سيران سا كابنار اڬو ڬاڬاو نا عيا ڤاتوت ع دي كاڤاكاسُسُروتا عو اوماني ايسا كو كاڤاكيڤحاڤاڬارِيا۔"
  specimen_16: "لاڠون ع تاو نا اينيمباواتا ع ندُدون سو كڤاعر اڬو نداتاداتار سا بانتوڬان اڬو كابنار۔ بيڬان سيران سا كابنار اڬو ڬاڬاو نا عيا ڤاتوت ع دي كاڤاكاسُسُروتا عو اوماني ايسا كو كاڤاكيڤحاڤاڬارِيا۔\nلاڠون ع تاو نا اينيمباواتا ع ندُدون سو كڤاعر اڬو نداتاداتار سا بانتوڬان اڬو كابنار۔ بيڬان سيران سا كابنار اڬو ڬاڬاو نا عيا ڤاتوت ع دي كاڤاكاسُسُروتا عو اوماني ايسا كو كاڤاكيڤحاڤاڬارِيا۔\nلاڠون ع تاو نا اينيمباواتا ع ندُدون سو كڤاعر اڬو نداتاداتار سا بانتوڬان اڬو كابنار۔ بيڬان سيران سا كابنار اڬو ڬاڬاو نا عيا ڤاتوت ع دي كاڤاكاسُسُروتا عو اوماني ايسا كو كاڤاكيڤحاڤاڬارِيا۔\nلاڠون ع تاو نا اينيمباواتا ع ندُدون سو كڤاعر اڬو نداتاداتار سا بانتوڬان اڬو كابنار۔ بيڬان سيران سا كابنار اڬو ڬاڬاو نا عيا ڤاتوت ع دي كاڤاكاسُسُروتا عو اوماني ايسا كو كاڤاكيڤحاڤاڬارِيا۔"
}
