id: "mrw_Arab"
language: "mrw"
script: "Arab"
name: "Maranao, Arabic"
sample_text {
  masthead_full: "لاڠو"
  masthead_partial: "نع"
  styles: "ل\nا\nڠ\nو\nن\n \nع\n \nت\nا\nو\n \nن\nا\n \nا\nي\nن\nي\nم\nب"
  tester: "ل\nا\nڠ\nو\nن\n \nع\n \nت\nا\nو\n \nن\nا\n \nا\nي\nن\nي\nم\nب\nا\nو\nا\nت\nا\n \nع\n \nن\nد"
  poster_sm: "ل\nا\nڠ\nو\nن\n "
  poster_md: "ل\nا\nڠ\nو\nن"
  poster_lg: "ل\nا"
  specimen_48: "ل\nا\nڠ\nو\nن\n \nع\n \nت\nا\nو\n \nن\nا\n \nا\nي\nن\nي\nم\nب\nا\nو\nا\nت\nا\n \nع\n \nن\nد"
  specimen_36: "ل\nا\nڠ\nو\nن\n \nع\n \nت\nا\nو\n \nن\nا\n \nا\nي\nن\nي\nم\nب\nا\nو\nا\nت\nا\n \nع\n \nن\nد\nُ\nد\nو\nن\n \nس\nو\n \nك\nڤ\nا\nع\nر\n \nا\nڬ\nو\n \nن\nد"
  specimen_32: "ل\nا\nڠ\nو\nن\n \nع\n \nت\nا\nو\n \nن\nا\n \nا\nي\nن\nي\nم\nب\nا\nو\nا\nت\nا\n \nع\n \nن\nد\nُ\nد\nو\nن\n \nس\nو\n \nك\nڤ\nا\nع\nر\n \nا\nڬ\nو\n \nن\nد\nا\nت\nا\nد\nا\nت\nا\nر\n \nس\nا\n \nب\nا\nن\nت\nو\nڬ\nا\nن"
  specimen_21: "ل\nا\nڠ\nو\nن\n \nع\n \nت\nا\nو\n \nن\nا\n \nا\nي\nن\nي\nم\nب\nا\nو\nا\nت\nا\n \nع\n \nن\nد\nُ\nد\nو\nن\n \nس\nو\n \nك\nڤ\nا\nع\nر\n \nا\nڬ\nو\n \nن\nد\nا\nت\nا\nد\nا\nت\nا\nر\n \nس\nا\n \nب\nا\nن\nت\nو\nڬ\nا\nن\n \nا\nڬ\nو\n \nك\nا\nب\nن\nا\nر\n۔\n \nب\nي\nڬ\nا\nن\n \nس\nي\nر\nا\nن\n \nس\nا\n \nك\nا\nب\nن\nا\nر\n \nا\nڬ\nو\n \nڬ\nا\nڬ\nا\nو\n \nن\nا\n \nع\nي\nا\n \nڤ\nا\nت\nو\nت\n \nع\n \nد\nي\n \nك\nا\nڤ\nا\nك\nا\nس\nُ\nس\nُ\nر\nو\nت\nا\n \nع\nو\n \nا"
  specimen_16: "ل\nا\nڠ\nو\nن\n \nع\n \nت\nا\nو\n \nن\nا\n \nا\nي\nن\nي\nم\nب\nا\nو\nا\nت\nا\n \nع\n \nن\nد\nُ\nد\nو\nن\n \nس\nو\n \nك\nڤ\nا\nع\nر\n \nا\nڬ\nو\n \nن\nد\nا\nت\nا\nد\nا\nت\nا\nر\n \nس\nا\n \nب\nا\nن\nت\nو\nڬ\nا\nن\n \nا\nڬ\nو\n \nك\nا\nب\nن\nا\nر\n۔\n \nب\nي\nڬ\nا\nن\n \nس\nي\nر\nا\nن\n \nس\nا\n \nك\nا\nب\nن\nا\nر\n \nا\nڬ\nو\n \nڬ\nا\nڬ\nا\nو\n \nن\nا\n \nع\nي\nا\n \nڤ\nا\nت\nو\nت\n \nع\n \nد\nي\n \nك\nا\nڤ\nا\nك\nا\nس\nُ\nس\nُ\nر\nو\nت\nا\n \nع\nو\n \nا\nو\nم\nا\nن\nي\n \nا\nي\nس\nا\n \nك\nو\n \nك\nا\nڤ\nا\nك\nي\nڤ\nح\nا\nڤ\nا\nڬ\nا\nر\nِ\nي\nا\n۔\nل\nا\nڠ\nو\nن\n \nع\n \nت\nا\nو\n \nن\nا\n \nا\nي\nن\nي\nم\nب\nا\nو\nا\nت\nا\n \nع\n \nن\nد\nُ\nد\nو\nن\n \nس\nو\n \nك\nڤ\nا\nع\nر\n \nا\nڬ\nو\n \nن\nد\nا\nت\nا\nد\nا\nت\nا\nر\n \nس\nا\n \nب\nا\nن\nت\nو\nڬ\nا\nن\n \nا\nڬ\nو\n \nك\nا\nب\nن\nا\nر\n۔\n \nب\nي\nڬ\nا\nن\n \nس\nي\nر\nا\nن"
}
