id: "mui_Latn"
language: "mui"
script: "Latn"
name: "Musi, Latin"
sample_text {
  masthead_full: "GgAa"
  masthead_partial: "Ll"
  styles: "G\na\nl\no\n-\ng\na\nl\no\n \nu\nw\no\nn\ng\n \nm\ne\nt\nu\n "
  tester: "G\na\nl\no\n-\ng\na\nl\no\n \nu\nw\no\nn\ng\n \nm\ne\nt\nu\n \nk\ne\n \nd\nu\nn\ni\no\n \nb"
  poster_sm: "G\na\nl\no\n-\ng"
  poster_md: "G\na\nl\no\n-"
  poster_lg: "G\na"
  specimen_48: "G\na\nl\no\n-\ng\na\nl\no\n \nu\nw\no\nn\ng\n \nm\ne\nt\nu\n \nk\ne\n \nd\nu\nn\ni\no\n \nb"
  specimen_36: "G\na\nl\no\n-\ng\na\nl\no\n \nu\nw\no\nn\ng\n \nm\ne\nt\nu\n \nk\ne\n \nd\nu\nn\ni\no\n \nb\ne\nb\na\ns\n,\n \nn\ng\na\nn\n \nk\ne\nh\no\nr\nm\na\nt\na\nn"
  specimen_32: "G\na\nl\no\n-\ng\na\nl\no\n \nu\nw\no\nn\ng\n \nm\ne\nt\nu\n \nk\ne\n \nd\nu\nn\ni\no\n \nb\ne\nb\na\ns\n,\n \nn\ng\na\nn\n \nk\ne\nh\no\nr\nm\na\nt\na\nn\n \nd\na\nn\n \nh\na\nk\n-\nh\na\nk\n \ny\na\nn\ng\n \ns\na"
  specimen_21: "G\na\nl\no\n-\ng\na\nl\no\n \nu\nw\no\nn\ng\n \nm\ne\nt\nu\n \nk\ne\n \nd\nu\nn\ni\no\n \nb\ne\nb\na\ns\n,\n \nn\ng\na\nn\n \nk\ne\nh\no\nr\nm\na\nt\na\nn\n \nd\na\nn\n \nh\na\nk\n-\nh\na\nk\n \ny\na\nn\ng\n \ns\na\nm\no\n \np\nu\nl\no\n.\n \nG\na\nl\no\n-\ng\na\nl\no\nn\ny\no\n \nl\na\n \nd\ni\ne\nn\nj\nu\nk\n \na\nk\na\nl\n \nu\nt\na\nk\n \nj\nu\ng\no\n \nr\na\ns\no\n \na\nt\ni\n,\n \nk\ne\nn\nd\na\nk\nn\ny\no\n \nt\nu\n \ng\na\nw\ne\n \ns\ne\ns\na\nm\no"
  specimen_16: "G\na\nl\no\n-\ng\na\nl\no\n \nu\nw\no\nn\ng\n \nm\ne\nt\nu\n \nk\ne\n \nd\nu\nn\ni\no\n \nb\ne\nb\na\ns\n,\n \nn\ng\na\nn\n \nk\ne\nh\no\nr\nm\na\nt\na\nn\n \nd\na\nn\n \nh\na\nk\n-\nh\na\nk\n \ny\na\nn\ng\n \ns\na\nm\no\n \np\nu\nl\no\n.\n \nG\na\nl\no\n-\ng\na\nl\no\nn\ny\no\n \nl\na\n \nd\ni\ne\nn\nj\nu\nk\n \na\nk\na\nl\n \nu\nt\na\nk\n \nj\nu\ng\no\n \nr\na\ns\no\n \na\nt\ni\n,\n \nk\ne\nn\nd\na\nk\nn\ny\no\n \nt\nu\n \ng\na\nw\ne\n \ns\ne\ns\na\nm\no\n \nl\na\ne\nn\nn\ny\no\n \np\ne\nc\na\nk\n \nw\no\nn\ng\n \ns\ne\nd\nu\nl\nu\nr\na\nn\n.\nG\na\nl\no\n-\ng\na\nl\no\n \nu\nw\no\nn\ng\n \nm\ne\nt\nu\n \nk\ne\n \nd\nu\nn\ni\no\n \nb\ne\nb\na\ns\n,\n \nn\ng\na\nn\n \nk\ne\nh\no\nr\nm\na\nt\na\nn\n \nd\na\nn\n \nh\na\nk\n-\nh\na\nk\n \ny\na\nn\ng\n \ns\na\nm\no\n \np\nu\nl\no\n.\n \nG\na\nl\no\n-\ng\na\nl\no\nn\ny\no\n \nl\na\n \nd"
}
