id: "mxi_Latn"
language: "mxi"
script: "Latn"
name: "Mozarabic"
sample_text {
  masthead_full: "TtOo"
  masthead_partial: "Ss"
  styles: "T\no\nt\no\ns\n \nl\ne\ns\n \ne\ns\ns\ne\nr\ne\ns\n \nh\nu\nm"
  tester: "T\no\nt\no\ns\n \nl\ne\ns\n \ne\ns\ns\ne\nr\ne\ns\n \nh\nu\nm\na\nn\no\ns\n \nn\na\ns\nc\ne"
  poster_sm: "T\no\nt\no\ns\n "
  poster_md: "T\no\nt\no\ns"
  poster_lg: "T\no"
  specimen_48: "T\no\nt\no\ns\n \nl\ne\ns\n \ne\ns\ns\ne\nr\ne\ns\n \nh\nu\nm\na\nn\no\ns\n \nn\na\ns\nc\ne"
  specimen_36: "T\no\nt\no\ns\n \nl\ne\ns\n \ne\ns\ns\ne\nr\ne\ns\n \nh\nu\nm\na\nn\no\ns\n \nn\na\ns\nc\ne\nn\nt\n \nl\ni\nb\nb\ne\nr\no\ns\n \ne\nt\n \ne\ng\nu\na\nl"
  specimen_32: "T\no\nt\no\ns\n \nl\ne\ns\n \ne\ns\ns\ne\nr\ne\ns\n \nh\nu\nm\na\nn\no\ns\n \nn\na\ns\nc\ne\nn\nt\n \nl\ni\nb\nb\ne\nr\no\ns\n \ne\nt\n \ne\ng\nu\na\nl\ne\ns\n \ni\nn\n \nd\ni\ng\nn\ni\nt\na\nt\ne\n \ne\n \nd\nr"
  specimen_21: "T\no\nt\no\ns\n \nl\ne\ns\n \ne\ns\ns\ne\nr\ne\ns\n \nh\nu\nm\na\nn\no\ns\n \nn\na\ns\nc\ne\nn\nt\n \nl\ni\nb\nb\ne\nr\no\ns\n \ne\nt\n \ne\ng\nu\na\nl\ne\ns\n \ni\nn\n \nd\ni\ng\nn\ni\nt\na\nt\ne\n \ne\n \nd\nr\ne\nt\no\ns\n \ne\n,\n \nd\no\nt\na\nt\no\ns\n \nc\no\nm\nm\no\n \ns\nt\na\nn\nt\n \nd\ne\n \nr\na\nc\ni\no\nn\ne\n \ne\n \nc\no\nn\ns\nc\ni\ne\nn\nt\ni\na\n,\n \nd\ne\nv\ne\nn\nt\n \nc\no\nm\np\no\nr\nt\na\nr\ns\ne\n \ni\nn\n \ng\ne\nr\nm\na"
  specimen_16: "T\no\nt\no\ns\n \nl\ne\ns\n \ne\ns\ns\ne\nr\ne\ns\n \nh\nu\nm\na\nn\no\ns\n \nn\na\ns\nc\ne\nn\nt\n \nl\ni\nb\nb\ne\nr\no\ns\n \ne\nt\n \ne\ng\nu\na\nl\ne\ns\n \ni\nn\n \nd\ni\ng\nn\ni\nt\na\nt\ne\n \ne\n \nd\nr\ne\nt\no\ns\n \ne\n,\n \nd\no\nt\na\nt\no\ns\n \nc\no\nm\nm\no\n \ns\nt\na\nn\nt\n \nd\ne\n \nr\na\nc\ni\no\nn\ne\n \ne\n \nc\no\nn\ns\nc\ni\ne\nn\nt\ni\na\n,\n \nd\ne\nv\ne\nn\nt\n \nc\no\nm\np\no\nr\nt\na\nr\ns\ne\n \ni\nn\n \ng\ne\nr\nm\na\nn\ni\nt\na\nt\ne\n \nl\ne\ns\n \nu\nn\no\ns\n \nc\no\nn\n \nl\ne\ns\n \na\nl\nt\nr\no\ns\n.\nT\no\nt\no\ns\n \nl\ne\ns\n \ne\ns\ns\ne\nr\ne\ns\n \nh\nu\nm\na\nn\no\ns\n \nn\na\ns\nc\ne\nn\nt\n \nl\ni\nb\nb\ne\nr\no\ns\n \ne\nt\n \ne\ng\nu\na\nl\ne\ns\n \ni\nn\n \nd\ni\ng\nn\ni\nt\na\nt\ne\n \ne\n \nd\nr\ne\nt\no\ns\n \ne\n,\n \nd\no\nt\na\nt\no\ns\n \nc\no\nm\nm\no\n \ns\nt"
}
