id: "mxv_Latn"
language: "mxv"
script: "Latn"
name: "Mixtec, Metlatónoc"
sample_text {
  masthead_full: "TtAa"
  masthead_partial: "Kk"
  styles: "T\na\nk\na\n \nm\na\n \nñ\na\ny\ni\n \nn\ng\nu\ni\na\nk\no\ni"
  tester: "T\na\nk\na\n \nm\na\n \nñ\na\ny\ni\n \nn\ng\nu\ni\na\nk\no\ni\n \nñ\na\ny\ni\nv\ni\n \nñ\na"
  poster_sm: "T\na\nk\na\n \nm"
  poster_md: "T\na\nk\na\n "
  poster_lg: "T\na"
  specimen_48: "T\na\nk\na\n \nm\na\n \nñ\na\ny\ni\n \nn\ng\nu\ni\na\nk\no\ni\n \nñ\na\ny\ni\nv\ni\n \nñ\na"
  specimen_36: "T\na\nk\na\n \nm\na\n \nñ\na\ny\ni\n \nn\ng\nu\ni\na\nk\no\ni\n \nñ\na\ny\ni\nv\ni\n \nñ\na\nt\nu\n \nn\na\n \nj\na\n\'\na\n \nt\nn\nu\n\'\nu\n \nj\na\n \nk"
  specimen_32: "T\na\nk\na\n \nm\na\n \nñ\na\ny\ni\n \nn\ng\nu\ni\na\nk\no\ni\n \nñ\na\ny\ni\nv\ni\n \nñ\na\nt\nu\n \nn\na\n \nj\na\n\'\na\n \nt\nn\nu\n\'\nu\n \nj\na\n \nk\nu\ns\na\n\'\na\n \nn\nd\ne\nv\na\n\'\nñ\na\n-\ni\n,\n \ns\nu\n\'\nu"
  specimen_21: "T\na\nk\na\n \nm\na\n \nñ\na\ny\ni\n \nn\ng\nu\ni\na\nk\no\ni\n \nñ\na\ny\ni\nv\ni\n \nñ\na\nt\nu\n \nn\na\n \nj\na\n\'\na\n \nt\nn\nu\n\'\nu\n \nj\na\n \nk\nu\ns\na\n\'\na\n \nn\nd\ne\nv\na\n\'\nñ\na\n-\ni\n,\n \ns\nu\n\'\nu\nv\na\n \nk\na\nj\ni\nt\no\n \nv\na\n\'\na\nñ\na\n-\ni\n,\n \ny\nu\nk\na\n \nk\nu\n \nj\na\n \nj\ni\nn\ni\nñ\nu\n\'\nu\n \nj\na\n \nk\nu\nk\no\nt\no\nt\nn\na\n-\ni\n.\nT\na\nk\na\n \nm\na\n \nñ\na\ny\ni\n \nn\ng\nu\ni\na\nk\no\ni\n \nñ\na\ny\ni\nv\ni"
  specimen_16: "T\na\nk\na\n \nm\na\n \nñ\na\ny\ni\n \nn\ng\nu\ni\na\nk\no\ni\n \nñ\na\ny\ni\nv\ni\n \nñ\na\nt\nu\n \nn\na\n \nj\na\n\'\na\n \nt\nn\nu\n\'\nu\n \nj\na\n \nk\nu\ns\na\n\'\na\n \nn\nd\ne\nv\na\n\'\nñ\na\n-\ni\n,\n \ns\nu\n\'\nu\nv\na\n \nk\na\nj\ni\nt\no\n \nv\na\n\'\na\nñ\na\n-\ni\n,\n \ny\nu\nk\na\n \nk\nu\n \nj\na\n \nj\ni\nn\ni\nñ\nu\n\'\nu\n \nj\na\n \nk\nu\nk\no\nt\no\nt\nn\na\n-\ni\n.\nT\na\nk\na\n \nm\na\n \nñ\na\ny\ni\n \nn\ng\nu\ni\na\nk\no\ni\n \nñ\na\ny\ni\nv\ni\n \nñ\na\nt\nu\n \nn\na\n \nj\na\n\'\na\n \nt\nn\nu\n\'\nu\n \nj\na\n \nk\nu\ns\na\n\'\na\n \nn\nd\ne\nv\na\n\'\nñ\na\n-\ni\n,\n \ns\nu\n\'\nu\nv\na\n \nk\na\nj\ni\nt\no\n \nv\na\n\'\na\nñ\na\n-\ni\n,\n \ny\nu\nk\na\n \nk\nu\n \nj\na\n \nj\ni\nn\ni\nñ\nu\n\'\nu\n \nj\na\n \nk\nu\nk\no\nt\no\nt\nn\na\n-\ni\n.\nT\na\nk\na\n \nm\na\n \nñ\na\ny\ni\n \nn\ng\nu\ni\na\nk\no\ni\n \nñ\na\ny\ni\nv\ni\n \nñ\na"
}
