id: "mzi_Latn"
language: "mzi"
script: "Latn"
name: "Mazatec, Ixcatlán"
sample_text {
  masthead_full: "NnGg"
  masthead_partial: "Aa"
  styles: "N\ng\na\n \nn\nd\ni\nn\nd\ni\ne\n \nx\nu\nt\na\n \nn\ng\na\nt"
  tester: "N\ng\na\n \nn\nd\ni\nn\nd\ni\ne\n \nx\nu\nt\na\n \nn\ng\na\nt\ns\ne\nn\n \nd\ne\n’\ne\n \nk"
  poster_sm: "N\ng\na\n \nn\nd"
  poster_md: "N\ng\na\n \nn"
  poster_lg: "N\ng"
  specimen_48: "N\ng\na\n \nn\nd\ni\nn\nd\ni\ne\n \nx\nu\nt\na\n \nn\ng\na\nt\ns\ne\nn\n \nd\ne\n’\ne\n \nk"
  specimen_36: "N\ng\na\n \nn\nd\ni\nn\nd\ni\ne\n \nx\nu\nt\na\n \nn\ng\na\nt\ns\ne\nn\n \nd\ne\n’\ne\n \nk\no\n \nn\ng\no\nn\nd\ns\ne\nj\ne\nn\n \nn\ng\na\nt\nj\ni\nn"
  specimen_32: "N\ng\na\n \nn\nd\ni\nn\nd\ni\ne\n \nx\nu\nt\na\n \nn\ng\na\nt\ns\ne\nn\n \nd\ne\n’\ne\n \nk\no\n \nn\ng\no\nn\nd\ns\ne\nj\ne\nn\n \nn\ng\na\nt\nj\ni\nn\n-\nk\nj\nu\na\n \nn\ng\na\n \nx\nc\nh\na\nn\nd\ni\nn\nk\no\nn"
  specimen_21: "N\ng\na\n \nn\nd\ni\nn\nd\ni\ne\n \nx\nu\nt\na\n \nn\ng\na\nt\ns\ne\nn\n \nd\ne\n’\ne\n \nk\no\n \nn\ng\no\nn\nd\ns\ne\nj\ne\nn\n \nn\ng\na\nt\nj\ni\nn\n-\nk\nj\nu\na\n \nn\ng\na\n \nx\nc\nh\na\nn\nd\ni\nn\nk\no\nn\n \nn\nt\n’\na\n \nn\ng\no\nn\nd\ns\ne\nj\ne\nn\n \nn\ng\na\nt\nj\ni\nn\n \nk\no\nk\nj\ni\nn\n-\nt\no\nk\no\nn\n,\nk\no\nt\nj\ni\nn\nk\nj\nu\na\n \nn\ng\na\n \nt\na\nk\ni\ne\n \ne\nn\ng\na\nj\na\nn\n \ns\nk\nu\ne\nn\nd\ni\nn\nk\no\nn\n \nx\nk"
  specimen_16: "N\ng\na\n \nn\nd\ni\nn\nd\ni\ne\n \nx\nu\nt\na\n \nn\ng\na\nt\ns\ne\nn\n \nd\ne\n’\ne\n \nk\no\n \nn\ng\no\nn\nd\ns\ne\nj\ne\nn\n \nn\ng\na\nt\nj\ni\nn\n-\nk\nj\nu\na\n \nn\ng\na\n \nx\nc\nh\na\nn\nd\ni\nn\nk\no\nn\n \nn\nt\n’\na\n \nn\ng\no\nn\nd\ns\ne\nj\ne\nn\n \nn\ng\na\nt\nj\ni\nn\n \nk\no\nk\nj\ni\nn\n-\nt\no\nk\no\nn\n,\nk\no\nt\nj\ni\nn\nk\nj\nu\na\n \nn\ng\na\n \nt\na\nk\ni\ne\n \ne\nn\ng\na\nj\na\nn\n \ns\nk\nu\ne\nn\nd\ni\nn\nk\no\nn\n \nx\nk\nj\ni\nn\n.\nN\ng\na\n \nn\nd\ni\nn\nd\ni\ne\n \nx\nu\nt\na\n \nn\ng\na\nt\ns\ne\nn\n \nd\ne\n’\ne\n \nk\no\n \nn\ng\no\nn\nd\ns\ne\nj\ne\nn\n \nn\ng\na\nt\nj\ni\nn\n-\nk\nj\nu\na\n \nn\ng\na\n \nx\nc\nh\na\nn\nd\ni\nn\nk\no\nn\n \nn\nt\n’\na\n \nn\ng\no\nn\nd\ns\ne\nj\ne\nn\n \nn\ng\na\nt\nj\ni\nn\n \nk\no\nk\nj\ni\nn\n-\nt\no\nk\no\nn\n,\nk\no\nt\nj\ni\nn\nk\nj\nu\na\n \nn\ng\na"
}
