id: "nan"
language: "nan"
script: "Hans"
name: "Min Nan Chinese"
population: 26486380
region: "CN"
sample_text {
  masthead_full: "人生而自"
  masthead_partial: "由在"
  styles: "鉴于对人类社会的成员拢固有的尊严及其平等的合无移的权利的承认，乃是世界自由、正义合和平的底置"
  tester: "鉴于对人权的勿会合创治已发展为野赤暴行，即号暴行玷污了人类的道行，而一个人人享有言论合信仰自由并无恐惧合匮乏的世界的来临，已互宣布为普通人民的最高的雄心"
  poster_sm: "发布即个世界人权宣言"
  poster_md: "人人过过有权享有生命"
  poster_lg: "人人生而自由"
  specimen_48: "法律之前人人平等，并有权享受法律的平等保庇，无受任何歧视。人人有权享受平等保庇，以无受违逆即个宣言的任何歧视行为以及煽动即款歧视的任何行为的败害"
  specimen_36: "鉴于对人类社会的成员拢固有的尊严及其平等的合无移的权利的承认，乃是世界自由、正义合和平的底置，\n鉴于对人权的勿会合创治已发展为野赤暴行，即号暴行玷污了人类的道行，而一个人人享有言论合信仰自由并无恐惧合匮乏的世界的来临，已互宣布为普通人民的最高的雄心，"
  specimen_32: "鉴于对人类社会的成员拢固有的尊严及其平等的合无移的权利的承认，乃是世界自由、正义合和平的底置，\n鉴于对人权的勿会合创治已发展为野赤暴行，即号暴行玷污了人类的道行，而一个人人享有言论合信仰自由并无恐惧合匮乏的世界的来临，已互宣布为普通人民的最高的雄心，\n鉴于为互人类勿会致到起散对杀政合创治进行反叛，有必要互人权受法治的保庇，"
  specimen_21: "鉴于对人类社会的成员拢固有的尊严及其平等的合无移的权利的承认，乃是世界自由、正义合和平的底置，\n鉴于对人权的勿会合创治已发展为野赤暴行，即号暴行玷污了人类的道行，而一个人人享有言论合信仰自由并无恐惧合匮乏的世界的来临，已互宣布为普通人民的最高的雄心，\n鉴于为互人类勿会致到起散对杀政合创治进行反叛，有必要互人权受法治的保庇，\n鉴于有必要促进各国间好斗头关系的发展，\n鉴于各联合国国家的人民已在联合国宪章中对头讲因对基本人权、人格尊严合价值以及丈夫查某平等权利的信念，并决心促成较大自由中的社会进步合生活水平的改善，\n鉴于各会员国业已咒誓同联合国合作以促进对人权合基本自由的普遍尊重合遵行，\n鉴于对即号权利合自由的普遍知空对于即个咒誓的充分实现具有设汰大的重要性，"
  specimen_16: "鉴于对人类社会的成员拢固有的尊严及其平等的合无移的权利的承认，乃是世界自由、正义合和平的底置，\n鉴于对人权的勿会合创治已发展为野赤暴行，即号暴行玷污了人类的道行，而一个人人享有言论合信仰自由并无恐惧合匮乏的世界的来临，已互宣布为普通人民的最高的雄心，\n鉴于为互人类勿会致到起散对杀政合创治进行反叛，有必要互人权受法治的保庇，\n鉴于有必要促进各国间好斗头关系的发展，\n鉴于各联合国国家的人民已在联合国宪章中对头讲因对基本人权、人格尊严合价值以及丈夫查某平等权利的信念，并决心促成较大自由中的社会进步合生活水平的改善，\n鉴于各会员国业已咒誓同联合国合作以促进对人权合基本自由的普遍尊重合遵行，\n鉴于对即号权利合自由的普遍知空对于即个咒誓的充分实现具有设汰大的重要性，\n因此即辄，\n大会，\n发布即个世界人权宣言，作为所有人民合所有国家下力实现的共同标准，以期每一个人合社会机构定定带着即个宣言，下力倚傍教诲合教育促进对权利合自由的尊重，并倚傍国家的合国际的渐进措施，互即号权利合自由在各会员国本身人民及在因管辖下地的人民中得到普遍合有效的承认合遵行；\n人人生而自由，在尊严合权利上一律平等。因赋有脾胃合道行，并着以兄弟关系的精神相对待。\n人人有资格享有即个宣言所载的一切权利合自由，无分种族、肤色、性别、语言、宗教、政治抑其他见解、国籍抑社会出身、财产、出生抑其他身分等任何区别。"
}
