id: "nan_Hant"
language: "nan"
script: "Hant"
name: "Min Nan Chinese, Traditional"
region: "AU"
region: "BN"
region: "CN"
region: "GB"
region: "GF"
region: "HK"
region: "ID"
region: "MO"
region: "MY"
region: "PA"
region: "PF"
region: "PH"
region: "SR"
region: "TH"
region: "TW"
region: "US"
region: "VN"
sample_text {
  masthead_full: "人皆生而"
  masthead_partial: "自由"
  styles: "人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦"
  tester: "人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦"
  poster_sm: "人\n皆\n生\n而\n自\n由"
  poster_md: "人\n皆\n生\n而\n自"
  poster_lg: "人\n皆"
  specimen_48: "人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦"
  specimen_36: "人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦\n相\n處\n，\n情\n同\n手\n足\n。\n人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上"
  specimen_32: "人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦\n相\n處\n，\n情\n同\n手\n足\n。\n人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦\n相\n處\n，"
  specimen_21: "人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦\n相\n處\n，\n情\n同\n手\n足\n。\n人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦\n相\n處\n，\n情\n同\n手\n足\n。\n人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦\n相\n處\n，\n情\n同\n手\n足\n。\n人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦\n相\n處\n，\n情\n同\n手\n足\n。\n人"
  specimen_16: "人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦\n相\n處\n，\n情\n同\n手\n足\n。\n人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦\n相\n處\n，\n情\n同\n手\n足\n。\n人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦\n相\n處\n，\n情\n同\n手\n足\n。\n人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦\n相\n處\n，\n情\n同\n手\n足\n。\n人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦\n相\n處\n，\n情\n同\n手\n足\n。\n人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦\n相\n處\n，\n情\n同\n手\n足\n。\n人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上\n均\n各\n平\n等\n。\n人\n各\n賦\n有\n理\n性\n良\n知\n，\n誠\n應\n和\n睦\n相\n處\n，\n情\n同\n手\n足\n。\n人\n皆\n生\n而\n自\n由\n；\n在\n尊\n嚴\n及\n權\n利\n上"
}
