id: "nap"
language: "nap"
script: "Latn"
name: "Neapolitan"
autonym: "Napulitano"
population: 605306
region: "IT"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z À Á Â È É Ê Ì Í Î Ò Ó Ô Ù Ú Û a b c d e f g h i j k l m n o p q r s t u v w x y z à á â è é ê ì í î ò ó ô ù ú û"
  marks: "◌̀ ◌́ ◌̂"
}
sample_text {
  fallback_language: "en"
}
