id: "naq"
language: "naq"
script: "Latn"
name: "Nama"
autonym: "Khoekhoe"
population: 289307
region: "NA"
exemplar_chars {
  base: "a â b c d e f g h i î k m n o ô p q r s t u û w x y z ǀ ǁ ǂ ǃ"
  auxiliary: "j l v"
  marks: "◌̀ ◌́ ◌̂ ◌̃ ◌̄ ◌̈"
  index: "A B C D E F G H I K M N O P Q R S T U W X Y Z"
}
sample_text {
  fallback_language: "en"
}
