id: "nd"
language: "nd"
script: "Latn"
name: "North Ndebele"
autonym: "isiNdebele"
population: 1745556
region: "ZW"
exemplar_chars {
  base: "a b c d e f g h i j k l m n o p q s t u v w x y z"
  auxiliary: "r"
  index: "A B C D E F G H I J K L M N O P Q S T U V W X Y Z"
}
sample_text {
  fallback_language: "en"
}
