id: "ne"
language: "ne"
script: "Deva"
name: "Nepali"
autonym: "नेपाली"
population: 20903374
region: "BT"
region: "IN"
region: "NP"
exemplar_chars {
  base: "़ ँ ं ः ॐ अ आ इ ई उ ऊ ऋ ऌ ऍ ए ऐ ऑ ओ औ क ख ग घ ङ च छ ज झ ञ ट ठ ड ढ ण त थ द ध न प फ ब भ म य र ल ळ व श ष स ह ऽ ा ि ी ु ू ृ ॄ ॅ े ै ॉ ो ौ ्"
  auxiliary: "‌‍"
  marks: "◌ँ ◌ं ◌ः ◌़ ◌ा ◌ि ◌ी ◌ु ◌ू ◌ृ ◌े ◌ै ◌ो ◌ौ ◌्"
  numerals: "- ‑ , . % ‰ + 0० 1१ 2२ 3३ 4४ 5५ 6६ 7७ 8८ 9९"
  punctuation: "- ‑ — , ; ! ? । \' ‘ ’ \" “ ” ( ) [ ] { } { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "अ आ इ ई उ ऊ ऋ ए ऐ ओ औ क ख ग घ ङ च छ ज झ ञ ट ठ ड ढ ण त थ द ध न प फ ब भ म य र ल व श ष स ह"
}
sample_text {
  masthead_full: "सबवय"
  masthead_partial: "कत"
  styles: "मानव परिवारका सबै सदस्यहरूको अन्तर्निहित मान तथा सम्मान र"
  tester: "मानव अधिकारहरू प्रति अवहेलना तथा अनादरको परिणामबाटै नै काम भड मानव जातिको अन्त स्करणमा"
  poster_sm: "अत्याचार र दमनको"
  poster_md: "राष्ट्रहरूका बीच"
  poster_lg: "व्यक्ति"
  specimen_48: "संयुक्त राष्ट्र संघका जनता हरूले मानवका मौलिक अधिकारहरू र मनुष्यको मान तथा कदर र नर"
  specimen_36: "सबै व्यक्ति हरू जन्मजात स्वतन्त्र हुन ती सबैको समान अधिकार र महत्व छ। निजहरूमा विचार शक्ति र सद्धिचार भएकोले निजहरूले आपसमा भातृत्वको भावना बाट व्यवहार गर्नु पर्छ।"
  specimen_32: "सबै व्यक्तिहरु कानूनको द्दष्टिमा समान छन् र बिना भेदमाव कानूनको समान संरक्षणको हकदार हुनेछन् । सबैलाई यस घोषणाको उल्लङ्घन गरी गरिएको भेदमान वा त्यस्तो भेदभाव गर्न गरिएको उक्साहट विरुद्ध समान संरक्षणको अधिकार छ ।"
  specimen_21: "संविधान वा कानुन द्वारा दिइएको मौलिक अधिकारहरू भङ्ग गर्ने कार्यहरूको विरुद्ध योग्य राष्ट्रिय अदालतको प्रभावोत्पादक उपचारको सबैलाई अधिकार हुनेछ।\nकसैलाई पनि मनमानी ढाँगले देश निष्कासित वा गिरफ्तार वा नजर बन्द गरिने छैन।\nकुनै व्यक्ति उपर लगाइएको फौजदारी आरोपको विरुद्ध निजको अधिकार दायित्व निरोपन गर्दै स्वतन्त्र र न्याय युक्त अदालतबाट सुनुवाइको हक प्रत्येक व्यक्ति लाइ समान रूपले हुनेछ।\nकुनैपनि व्यक्तिको गोप्यता परिवार, घर वा पत्र व्यवहारको प्रति मनमानी हस्तक्षेप गरिने छैन र कसैको सम्मान तथा ख्याति माथि चोट पुर्‍याइने छैन र त्यस्तो हस्तक्षेप वा चोटको विरुद्ध प्रत्येक व्यक्तिलाई कानुनी संरक्षणको अधिकार हुनेछ।"
  specimen_16: "प्रत्येक व्यक्तिलाई विचार, मत, धार्मिक स्वतन्त्रताको अधिकार छ। धर्म वा मत बदल्ने स्वतन्त्रता र सार्वजनिक तथा व्यक्तिगत रूपमा एकलै वा समूहमा आफ्नो धर्म वा मतलाई शिक्षा आचरण\nप्रत्येक व्यक्तिलाई विचार र अभिव्यक्ति स्वतन्त्रताको अधिकार छ । यस अधिकारमा कुनै हस्तक्षेप बिना आक्ना मतहरु अभिव्यक्त गर्ने र कुनै पनि अवरोध र सीमाहरु बिना सञ्चार माध्यमद्धारा सूचना प्रात्प गर्ने, खोज्ने र प्रसार गर्ने अधिकार समावेश छ ।\nसमाजको सदस्यको हैसियतमा प्रत्येक व्यक्तिलाई सामाजिक सुरक्षाको अधिकार छ र साथै प्रत्येक व्यक्तिलाई राज्यको राष्ट्रिय प्रयत्न वा अन्तराष्ट्रय सहयोग मार्फत तथा स्रोत र साधन अनुसार उसको प्रतिष्ठा र स्वतन्त्र व्यक्तित्व विकासको लागि अपरिहार्य आर्थिक, सामाजिक र सांस्कुतिक अधिकारहरु उपभोग गर्ने अधिकार छ ।\nप्रत्येक व्यक्तिलाई मुनासिव कार्य समय सीमा र वेतन सहितको आवधिक विदा सहित विश्राम र फुर्सतको आधिकार छ ।"
}
