id: "new_Newa"
language: "new"
script: "Newa"
name: "Newari, Newa"
region: "NP"
sample_text {
  masthead_full: "𑐳𑐎𑐮𑐩"
  masthead_partial: "𑐣𑐟"
  styles: "𑐳\n𑐎\n𑐮\n𑐾\n𑑄\n \n𑐩\n𑐣\n𑐹\n𑐟\n \n𑐳\n𑑂\n𑐰\n𑐟\n𑐣\n𑑂\n𑐟\n𑑂\n𑐬\n \n𑐰\n \n𑐖"
  tester: "𑐳\n𑐎\n𑐮\n𑐾\n𑑄\n \n𑐩\n𑐣\n𑐹\n𑐟\n \n𑐳\n𑑂\n𑐰\n𑐟\n𑐣\n𑑂\n𑐟\n𑑂\n𑐬\n \n𑐰\n \n𑐖\n𑑂\n𑐰\n𑐮\n𑐶\n𑐖\n𑑂\n𑐰\n𑑅\n \n𑐁\n𑐟\n𑑂"
  poster_sm: "𑐳\n𑐎\n𑐮\n𑐾\n𑑄\n \n𑐩"
  poster_md: "𑐳\n𑐎\n𑐮\n𑐾\n𑑄\n "
  poster_lg: "𑐳\n𑐎"
  specimen_48: "𑐳\n𑐎\n𑐮\n𑐾\n𑑄\n \n𑐩\n𑐣\n𑐹\n𑐟\n \n𑐳\n𑑂\n𑐰\n𑐟\n𑐣\n𑑂\n𑐟\n𑑂\n𑐬\n \n𑐰\n \n𑐖\n𑑂\n𑐰\n𑐮\n𑐶\n𑐖\n𑑂\n𑐰\n𑑅\n \n𑐁\n𑐟\n𑑂"
  specimen_36: "𑐳\n𑐎\n𑐮\n𑐾\n𑑄\n \n𑐩\n𑐣\n𑐹\n𑐟\n \n𑐳\n𑑂\n𑐰\n𑐟\n𑐣\n𑑂\n𑐟\n𑑂\n𑐬\n \n𑐰\n \n𑐖\n𑑂\n𑐰\n𑐮\n𑐶\n𑐖\n𑑂\n𑐰\n𑑅\n \n𑐁\n𑐟\n𑑂\n𑐩\n𑐳\n𑐩\n𑑂\n𑐩\n𑐵\n𑐣\n \n𑐰\n \n𑐰\n𑐵\n𑑄\n \n𑐡\n𑐂\n𑐎\n𑐠\n𑑄\n \n𑐧\n𑐸\n𑐂"
  specimen_32: "𑐳\n𑐎\n𑐮\n𑐾\n𑑄\n \n𑐩\n𑐣\n𑐹\n𑐟\n \n𑐳\n𑑂\n𑐰\n𑐟\n𑐣\n𑑂\n𑐟\n𑑂\n𑐬\n \n𑐰\n \n𑐖\n𑑂\n𑐰\n𑐮\n𑐶\n𑐖\n𑑂\n𑐰\n𑑅\n \n𑐁\n𑐟\n𑑂\n𑐩\n𑐳\n𑐩\n𑑂\n𑐩\n𑐵\n𑐣\n \n𑐰\n \n𑐰\n𑐵\n𑑄\n \n𑐡\n𑐂\n𑐎\n𑐠\n𑑄\n \n𑐧\n𑐸\n𑐂\n \n𑑋\n \n𑐂\n𑐥\n𑐶\n𑑄\n \n𑐳\n𑑂\n𑐰\n𑐰\n𑐶\n𑐰\n𑐾\n𑐎\n \n𑐰\n \n𑐳\n𑐡\n𑑂\n𑐧\n𑐸"
  specimen_21: "𑐳\n𑐎\n𑐮\n𑐾\n𑑄\n \n𑐩\n𑐣\n𑐹\n𑐟\n \n𑐳\n𑑂\n𑐰\n𑐟\n𑐣\n𑑂\n𑐟\n𑑂\n𑐬\n \n𑐰\n \n𑐖\n𑑂\n𑐰\n𑐮\n𑐶\n𑐖\n𑑂\n𑐰\n𑑅\n \n𑐁\n𑐟\n𑑂\n𑐩\n𑐳\n𑐩\n𑑂\n𑐩\n𑐵\n𑐣\n \n𑐰\n \n𑐰\n𑐵\n𑑄\n \n𑐡\n𑐂\n𑐎\n𑐠\n𑑄\n \n𑐧\n𑐸\n𑐂\n \n𑑋\n \n𑐂\n𑐥\n𑐶\n𑑄\n \n𑐳\n𑑂\n𑐰\n𑐰\n𑐶\n𑐰\n𑐾\n𑐎\n \n𑐰\n \n𑐳\n𑐡\n𑑂\n𑐧\n𑐸\n𑐡\n𑑂\n𑐢\n𑐶\n \n𑐡\n𑐫\n𑐵\n𑑅\n \n𑐰\n𑐶\n𑐰\n𑐾\n𑐎\n𑐱\n𑐷\n𑐮\n \n𑐖\n𑐸\n𑐂\n \n𑐀\n𑐮\n𑐾\n \n𑐠\n𑐰\n𑑄\n𑐠\n𑐰\n𑐫\n𑑂\n \n𑐡\n𑐵\n𑐖\n𑐸\n𑐎\n𑐶\n𑐖\n𑐵\n𑐎\n𑐠\n𑑄\n \n𑐴\n𑐣\n𑐵\n𑐧\n𑐣\n𑐵\n \n𑐫\n𑐵\n𑐂\n \n𑑋\n𑐳\n𑐎\n𑐮\n𑐾\n𑑄\n \n𑐩\n𑐣\n𑐹\n𑐟\n \n𑐳\n𑑂\n𑐰\n𑐟\n𑐣\n𑑂\n𑐟\n𑑂\n𑐬\n \n𑐰\n \n𑐖\n𑑂\n𑐰\n𑐮\n𑐶\n𑐖\n𑑂\n𑐰\n𑑅\n \n𑐁\n𑐟\n𑑂\n𑐩"
  specimen_16: "𑐳\n𑐎\n𑐮\n𑐾\n𑑄\n \n𑐩\n𑐣\n𑐹\n𑐟\n \n𑐳\n𑑂\n𑐰\n𑐟\n𑐣\n𑑂\n𑐟\n𑑂\n𑐬\n \n𑐰\n \n𑐖\n𑑂\n𑐰\n𑐮\n𑐶\n𑐖\n𑑂\n𑐰\n𑑅\n \n𑐁\n𑐟\n𑑂\n𑐩\n𑐳\n𑐩\n𑑂\n𑐩\n𑐵\n𑐣\n \n𑐰\n \n𑐰\n𑐵\n𑑄\n \n𑐡\n𑐂\n𑐎\n𑐠\n𑑄\n \n𑐧\n𑐸\n𑐂\n \n𑑋\n \n𑐂\n𑐥\n𑐶\n𑑄\n \n𑐳\n𑑂\n𑐰\n𑐰\n𑐶\n𑐰\n𑐾\n𑐎\n \n𑐰\n \n𑐳\n𑐡\n𑑂\n𑐧\n𑐸\n𑐡\n𑑂\n𑐢\n𑐶\n \n𑐡\n𑐫\n𑐵\n𑑅\n \n𑐰\n𑐶\n𑐰\n𑐾\n𑐎\n𑐱\n𑐷\n𑐮\n \n𑐖\n𑐸\n𑐂\n \n𑐀\n𑐮\n𑐾\n \n𑐠\n𑐰\n𑑄\n𑐠\n𑐰\n𑐫\n𑑂\n \n𑐡\n𑐵\n𑐖\n𑐸\n𑐎\n𑐶\n𑐖\n𑐵\n𑐎\n𑐠\n𑑄\n \n𑐴\n𑐣\n𑐵\n𑐧\n𑐣\n𑐵\n \n𑐫\n𑐵\n𑐂\n \n𑑋\n𑐳\n𑐎\n𑐮\n𑐾\n𑑄\n \n𑐩\n𑐣\n𑐹\n𑐟\n \n𑐳\n𑑂\n𑐰\n𑐟\n𑐣\n𑑂\n𑐟\n𑑂\n𑐬\n \n𑐰\n \n𑐖\n𑑂\n𑐰\n𑐮\n𑐶\n𑐖\n𑑂\n𑐰\n𑑅\n \n𑐁\n𑐟\n𑑂\n𑐩\n𑐳\n𑐩\n𑑂\n𑐩\n𑐵\n𑐣\n \n𑐰\n \n𑐰\n𑐵\n𑑄\n \n𑐡\n𑐂\n𑐎\n𑐠\n𑑄\n \n𑐧\n𑐸\n𑐂\n \n𑑋\n \n𑐂\n𑐥\n𑐶\n𑑄\n \n𑐳\n𑑂\n𑐰\n𑐰\n𑐶\n𑐰\n𑐾\n𑐎\n \n𑐰\n \n𑐳\n𑐡\n𑑂\n𑐧\n𑐸\n𑐡\n𑑂\n𑐢\n𑐶\n \n𑐡\n𑐫\n𑐵\n𑑅\n \n𑐰\n𑐶\n𑐰\n𑐾\n𑐎\n𑐱\n𑐷\n𑐮\n \n𑐖\n𑐸\n𑐂\n \n𑐀\n𑐮\n𑐾\n \n𑐠\n𑐰\n𑑄\n𑐠\n𑐰\n𑐫\n𑑂\n \n𑐡\n𑐵\n𑐖\n𑐸\n𑐎\n𑐶\n𑐖\n𑐵\n𑐎\n𑐠\n𑑄\n \n𑐴\n𑐣\n𑐵\n𑐧\n𑐣\n𑐵\n \n𑐫\n𑐵\n𑐂\n \n𑑋\n𑐳\n𑐎\n𑐮\n𑐾\n𑑄\n \n𑐩\n𑐣\n𑐹\n𑐟\n \n𑐳\n𑑂\n𑐰\n𑐟\n𑐣\n𑑂\n𑐟\n𑑂\n𑐬\n \n𑐰\n \n𑐖\n𑑂\n𑐰\n𑐮\n𑐶\n𑐖\n𑑂\n𑐰\n𑑅\n \n𑐁\n𑐟\n𑑂\n𑐩\n𑐳\n𑐩\n𑑂\n𑐩\n𑐵\n𑐣"
}
