id: "new_Deva"
language: "new"
script: "Deva"
name: "Newari"
population: 1000820
region: "NP"
sample_text {
  masthead_full: "सकलम"
  masthead_partial: "नत"
  styles: "स\nक\nल\nे\nं\n \nम\nन\nू\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nव\n \nज"
  tester: "स\nक\nल\nे\nं\n \nम\nन\nू\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nव\n \nज\n्\nव\nल\nि\nज\n्\nव\nः\n \nआ\nत\n्"
  poster_sm: "स\nक\nल\nे\nं\n \nम"
  poster_md: "स\nक\nल\nे\nं\n "
  poster_lg: "स\nक"
  specimen_48: "स\nक\nल\nे\nं\n \nम\nन\nू\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nव\n \nज\n्\nव\nल\nि\nज\n्\nव\nः\n \nआ\nत\n्"
  specimen_36: "स\nक\nल\nे\nं\n \nम\nन\nू\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nव\n \nज\n्\nव\nल\nि\nज\n्\nव\nः\n \nआ\nत\n्\nम\nस\nम\n्\nम\nा\nन\n \nव\n \nव\nा\nं\n \nद\nइ\nक\nथ\nं\n \nब\nु\nइ"
  specimen_32: "स\nक\nल\nे\nं\n \nम\nन\nू\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nव\n \nज\n्\nव\nल\nि\nज\n्\nव\nः\n \nआ\nत\n्\nम\nस\nम\n्\nम\nा\nन\n \nव\n \nव\nा\nं\n \nद\nइ\nक\nथ\nं\n \nब\nु\nइ\n \n।\n \nइ\nप\nि\nं\n \nस\n्\nव\nव\nि\nव\nे\nक\n \nव\n \nस\nद\n्\nब\nु"
  specimen_21: "स\nक\nल\nे\nं\n \nम\nन\nू\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nव\n \nज\n्\nव\nल\nि\nज\n्\nव\nः\n \nआ\nत\n्\nम\nस\nम\n्\nम\nा\nन\n \nव\n \nव\nा\nं\n \nद\nइ\nक\nथ\nं\n \nब\nु\nइ\n \n।\n \nइ\nप\nि\nं\n \nस\n्\nव\nव\nि\nव\nे\nक\n \nव\n \nस\nद\n्\nब\nु\nद\n्\nध\nि\n \nद\nय\nा\nः\n \nव\nि\nव\nे\nक\nश\nी\nल\n \nज\nु\nइ\n \nअ\nल\nे\n \nथ\nव\nं\nथ\nव\nय\n्\n \nद\nा\nज\nु\nक\nि\nज\nा\nक\nथ\nं\n \nह\nन\nा\nब\nन\nा\n \nय\nा\nइ\n \n।\nस\nक\nल\nे\nं\n \nम\nन\nू\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nव\n \nज\n्\nव\nल\nि\nज\n्\nव\nः\n \nआ\nत\n्\nम"
  specimen_16: "स\nक\nल\nे\nं\n \nम\nन\nू\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nव\n \nज\n्\nव\nल\nि\nज\n्\nव\nः\n \nआ\nत\n्\nम\nस\nम\n्\nम\nा\nन\n \nव\n \nव\nा\nं\n \nद\nइ\nक\nथ\nं\n \nब\nु\nइ\n \n।\n \nइ\nप\nि\nं\n \nस\n्\nव\nव\nि\nव\nे\nक\n \nव\n \nस\nद\n्\nब\nु\nद\n्\nध\nि\n \nद\nय\nा\nः\n \nव\nि\nव\nे\nक\nश\nी\nल\n \nज\nु\nइ\n \nअ\nल\nे\n \nथ\nव\nं\nथ\nव\nय\n्\n \nद\nा\nज\nु\nक\nि\nज\nा\nक\nथ\nं\n \nह\nन\nा\nब\nन\nा\n \nय\nा\nइ\n \n।\nस\nक\nल\nे\nं\n \nम\nन\nू\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nव\n \nज\n्\nव\nल\nि\nज\n्\nव\nः\n \nआ\nत\n्\nम\nस\nम\n्\nम\nा\nन\n \nव\n \nव\nा\nं\n \nद\nइ\nक\nथ\nं\n \nब\nु\nइ\n \n।\n \nइ\nप\nि\nं\n \nस\n्\nव\nव\nि\nव\nे\nक\n \nव\n \nस\nद\n्\nब\nु\nद\n्\nध\nि\n \nद\nय\nा\nः\n \nव\nि\nव\nे\nक\nश\nी\nल\n \nज\nु\nइ\n \nअ\nल\nे\n \nथ\nव\nं\nथ\nव\nय\n्\n \nद\nा\nज\nु\nक\nि\nज\nा\nक\nथ\nं\n \nह\nन\nा\nब\nन\nा\n \nय\nा\nइ\n \n।\nस\nक\nल\nे\nं\n \nम\nन\nू\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nव\n \nज\n्\nव\nल\nि\nज\n्\nव\nः\n \nआ\nत\n्\nम\nस\nम\n्\nम\nा\nन"
}
