id: "nhn_Latn"
language: "nhn"
script: "Latn"
name: "Nahuatl, Central"
sample_text {
  masthead_full: "NnOo"
  masthead_partial: "Cc"
  styles: "N\no\nc\nh\ni\n \nt\nl\na\nk\na\nm\ne\nj\n \nu\na\nn\n \ns\ni"
  tester: "N\no\nc\nh\ni\n \nt\nl\na\nk\na\nm\ne\nj\n \nu\na\nn\n \ns\ni\nu\na\nm\ne\nj\n \nk\ni\np\ni"
  poster_sm: "N\no\nc\nh\ni\n "
  poster_md: "N\no\nc\nh\ni"
  poster_lg: "N\no"
  specimen_48: "N\no\nc\nh\ni\n \nt\nl\na\nk\na\nm\ne\nj\n \nu\na\nn\n \ns\ni\nu\na\nm\ne\nj\n \nk\ni\np\ni"
  specimen_36: "N\no\nc\nh\ni\n \nt\nl\na\nk\na\nm\ne\nj\n \nu\na\nn\n \ns\ni\nu\na\nm\ne\nj\n \nk\ni\np\ni\na\nj\n \nm\na\nn\no\nj\n \nk\nu\na\nl\ni\n \nt\nl\na\nk\na"
  specimen_32: "N\no\nc\nh\ni\n \nt\nl\na\nk\na\nm\ne\nj\n \nu\na\nn\n \ns\ni\nu\na\nm\ne\nj\n \nk\ni\np\ni\na\nj\n \nm\na\nn\no\nj\n \nk\nu\na\nl\ni\n \nt\nl\na\nk\na\nt\ni\ns\ne\nj\n,\n \nn\no\nc\nh\ni\n \ns\na\nn\n \ns\ne\n "
  specimen_21: "N\no\nc\nh\ni\n \nt\nl\na\nk\na\nm\ne\nj\n \nu\na\nn\n \ns\ni\nu\na\nm\ne\nj\n \nk\ni\np\ni\na\nj\n \nm\na\nn\no\nj\n \nk\nu\na\nl\ni\n \nt\nl\na\nk\na\nt\ni\ns\ne\nj\n,\n \nn\no\nc\nh\ni\n \ns\na\nn\n \ns\ne\n \nt\no\nt\nl\na\nt\ne\nc\nh\np\no\nu\ni\nl\nt\ni\nl\ni\ns\n \nu\na\nn\n \nt\ni\nt\nl\na\nt\ne\np\na\nn\ni\nt\na\nl\no\nj\nk\ne\nj\n,\n \ny\ne\nk\na\n \nm\no\nn\ne\nk\ni\n \nk\nu\na\nl\ni\n \nm\na\n \nt\ni\nm\no\nu\ni\nk\na\nk\na\nj\n,\n \nm\na"
  specimen_16: "N\no\nc\nh\ni\n \nt\nl\na\nk\na\nm\ne\nj\n \nu\na\nn\n \ns\ni\nu\na\nm\ne\nj\n \nk\ni\np\ni\na\nj\n \nm\na\nn\no\nj\n \nk\nu\na\nl\ni\n \nt\nl\na\nk\na\nt\ni\ns\ne\nj\n,\n \nn\no\nc\nh\ni\n \ns\na\nn\n \ns\ne\n \nt\no\nt\nl\na\nt\ne\nc\nh\np\no\nu\ni\nl\nt\ni\nl\ni\ns\n \nu\na\nn\n \nt\ni\nt\nl\na\nt\ne\np\na\nn\ni\nt\na\nl\no\nj\nk\ne\nj\n,\n \ny\ne\nk\na\n \nm\no\nn\ne\nk\ni\n \nk\nu\na\nl\ni\n \nm\na\n \nt\ni\nm\no\nu\ni\nk\na\nk\na\nj\n,\n \nm\na\n \nt\ni\nm\no\ni\nk\nn\ne\nl\ni\nk\na\nj\n,\n \nm\na\n \nt\ni\nm\no\nt\nl\na\ns\no\nj\nt\nl\na\nk\na\nj\n \nu\na\nn\n \nm\na\n \nt\ni\nm\no\nt\nl\ne\np\na\nn\ni\nt\na\nk\na\nj\n.\nN\no\nc\nh\ni\n \nt\nl\na\nk\na\nm\ne\nj\n \nu\na\nn\n \ns\ni\nu\na\nm\ne\nj\n \nk\ni\np\ni\na\nj\n \nm\na\nn\no\nj\n \nk\nu\na\nl\ni\n \nt\nl\na\nk\na\nt\ni\ns\ne\nj\n,\n \nn\no\nc\nh\ni\n \ns\na\nn"
}
