id: "nku_Latn"
language: "nku"
script: "Latn"
name: "Kulango, Bouna"
sample_text {
  masthead_full: "IiGg"
  masthead_partial: "Oo"
  styles: "I\ng\no\no\ny\no\no\n \np\nɛ\nɛ\n \nh\nʋ\nn\n \nt\na\na\n.\n "
  tester: "I\ng\no\no\ny\no\no\n \np\nɛ\nɛ\n \nh\nʋ\nn\n \nt\na\na\n.\n \nB\nɔ\n \np\nɛ\nɛ\n \nj\na\nb"
  poster_sm: "I\ng\no\no\ny\no"
  poster_md: "I\ng\no\no\ny"
  poster_lg: "I\ng"
  specimen_48: "I\ng\no\no\ny\no\no\n \np\nɛ\nɛ\n \nh\nʋ\nn\n \nt\na\na\n.\n \nB\nɔ\n \np\nɛ\nɛ\n \nj\na\nb"
  specimen_36: "I\ng\no\no\ny\no\no\n \np\nɛ\nɛ\n \nh\nʋ\nn\n \nt\na\na\n.\n \nB\nɔ\n \np\nɛ\nɛ\n \nj\na\nb\na\ng\na\n \nb\nɔ\nr\nɔ\n.\n \nH\nɔ\n \ny\na\n \ng\nʋ\nʋ\nn\n’"
  specimen_32: "I\ng\no\no\ny\no\no\n \np\nɛ\nɛ\n \nh\nʋ\nn\n \nt\na\na\n.\n \nB\nɔ\n \np\nɛ\nɛ\n \nj\na\nb\na\ng\na\n \nb\nɔ\nr\nɔ\n.\n \nH\nɔ\n \ny\na\n \ng\nʋ\nʋ\nn\n’\nn\n \nb\nɔ\nɔ\n \nh\nɛ\n \np\nɛ\nɛ\n,\n \nh\nɔ\n \nh\nɛ\n \ng"
  specimen_21: "I\ng\no\no\ny\no\no\n \np\nɛ\nɛ\n \nh\nʋ\nn\n \nt\na\na\n.\n \nB\nɔ\n \np\nɛ\nɛ\n \nj\na\nb\na\ng\na\n \nb\nɔ\nr\nɔ\n.\n \nH\nɔ\n \ny\na\n \ng\nʋ\nʋ\nn\n’\nn\n \nb\nɔ\nɔ\n \nh\nɛ\n \np\nɛ\nɛ\n,\n \nh\nɔ\n \nh\nɛ\n \ng\nu\ns\nɛ\ng\nɛ\n’\nn\n.\nI\ng\no\no\ny\no\no\n \np\nɛ\nɛ\n \nh\nʋ\nn\n \nt\na\na\n.\n \nB\nɔ\n \np\nɛ\nɛ\n \nj\na\nb\na\ng\na\n \nb\nɔ\nr\nɔ\n.\n \nH\nɔ\n \ny\na\n \ng\nʋ\nʋ\nn\n’\nn\n \nb\nɔ\nɔ\n \nh\nɛ\n \np\nɛ\nɛ\n,\n \nh\nɔ\n \nh\nɛ\n \ng\nu\ns"
  specimen_16: "I\ng\no\no\ny\no\no\n \np\nɛ\nɛ\n \nh\nʋ\nn\n \nt\na\na\n.\n \nB\nɔ\n \np\nɛ\nɛ\n \nj\na\nb\na\ng\na\n \nb\nɔ\nr\nɔ\n.\n \nH\nɔ\n \ny\na\n \ng\nʋ\nʋ\nn\n’\nn\n \nb\nɔ\nɔ\n \nh\nɛ\n \np\nɛ\nɛ\n,\n \nh\nɔ\n \nh\nɛ\n \ng\nu\ns\nɛ\ng\nɛ\n’\nn\n.\nI\ng\no\no\ny\no\no\n \np\nɛ\nɛ\n \nh\nʋ\nn\n \nt\na\na\n.\n \nB\nɔ\n \np\nɛ\nɛ\n \nj\na\nb\na\ng\na\n \nb\nɔ\nr\nɔ\n.\n \nH\nɔ\n \ny\na\n \ng\nʋ\nʋ\nn\n’\nn\n \nb\nɔ\nɔ\n \nh\nɛ\n \np\nɛ\nɛ\n,\n \nh\nɔ\n \nh\nɛ\n \ng\nu\ns\nɛ\ng\nɛ\n’\nn\n.\nI\ng\no\no\ny\no\no\n \np\nɛ\nɛ\n \nh\nʋ\nn\n \nt\na\na\n.\n \nB\nɔ\n \np\nɛ\nɛ\n \nj\na\nb\na\ng\na\n \nb\nɔ\nr\nɔ\n.\n \nH\nɔ\n \ny\na\n \ng\nʋ\nʋ\nn\n’\nn\n \nb\nɔ\nɔ\n \nh\nɛ\n \np\nɛ\nɛ\n,\n \nh\nɔ\n \nh\nɛ\n \ng\nu\ns\nɛ\ng\nɛ\n’\nn\n.\nI\ng\no\no\ny\no\no\n \np\nɛ\nɛ\n \nh\nʋ\nn\n \nt\na\na\n.\n \nB\nɔ\n \np\nɛ\nɛ\n \nj\na\nb\na\ng\na\n \nb\nɔ\nr\nɔ\n.\n \nH\nɔ"
}
