id: "nl"
language: "nl"
script: "Latn"
name: "Dutch"
autonym: "Nederlands"
population: 31709104
region: "AW"
region: "BE"
region: "BQ"
region: "CW"
region: "DE"
region: "FR"
region: "NL"
region: "SR"
region: "SX"
exemplar_chars {
  base: "a á ä b c d e é ë f g h i í ï {ij} {íj́} j k l m n o ó ö p q r s t u ú ü v w x y z {ij} {íj́} {ij} {íj́} {ij} {íj́} {ij} {íj́} {ij} {íj́} {ij} {íj́} {ij} {íj́} {ij} {íj́} {ij} {íj́} {ij} {íj́} {ij} {íj́} {ij} {íj́} {ij} {íj́} {ij} {íj́} {ij} {íj́}"
  auxiliary: "à â å ã æ ç è ê î ñ ô ø œ ù û ÿ"
  marks: "◌̀ ◌́ ◌̂ ◌̈"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ \" “ ” ( ) [ ] § @ * / & # † ‡ ′ ″"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
}
sample_text {
  masthead_full: "AaLl"
  masthead_partial: "Ee"
  styles: "Overwegende, dat erkenning van de inherente"
  tester: "Overwegende, dat terzijdestelling van en minachting voor de rechten"
  poster_sm: "Overwegende,"
  poster_md: "Op grond"
  poster_lg: "Alle"
  specimen_48: "Alle mensen worden vrij en gelijk in waardigheid en rechten geboren."
  specimen_36: "Niemand zal in slavernij of horigheid gehouden worden. Slavernij en slavenhandel in iedere vorm zijn verboden."
  specimen_32: "Een ieder heeft recht op rust en op eigen vrije tijd, met inbegrip van een redelijke beperking van de arbeidstijd, en op periodieke vakanties met behoud van loon."
  specimen_21: "Een ieder heeft recht op het bestaan van een zodanige maatschappelijke en internationale orde, dat de rechten en vrijheden, in deze Verklaring genoemd, daarin ten volle kunnen worden verwezenlijkt.\nGeen bepaling in deze Verklaring zal zodanig mogen worden uitgelegd, dat welke Staat, groep of persoon dan ook, daaraan enig recht kan ontlenen om iets te ondernemen of handelingen van welke aard ook te verrichten, die vernietiging van een van de rechten en vrijheden, in deze Verkaring genoemd, ten doel hebben."
  specimen_16: "Overwegende, dat erkenning van de inherente waardigheid en van de gelijke en onvervreemdbare rechten van alle leden van de mensengemeenschap grondslag is voor de vrijheid, gerechtigheid en vrede in de wereld;\nOverwegende, dat terzijdestelling van en minachting voor de rechten van de mens geleid hebben tot barbaarse handelingen, die het geweten van de mensheid geweld hebben aangedaan en dat de komst van een wereld, waarin de mensen vrijheid van meningsuiting en geloof zullen genieten, en vrij zullen zijn van vrees en gebrek, is verkondigd als het hoogste ideaal van iedere mens;"
}
