id: "nmg"
language: "nmg"
script: "Latn"
name: "Kwasio"
autonym: "Kwasio"
population: 8878
region: "CM"
exemplar_chars {
  base: "a á â ǎ ä ā b ɓ c d e é ê ě ē ǝ {ǝ\\u0301} {ǝ\\u0302} {ǝ\\u030C} {ǝ\\u0304} ɛ {ɛ\\u0301} {ɛ\\u0302} {ɛ\\u030C} {ɛ\\u0304} f g h i í î ǐ ï ī j k l m n ń ŋ o ó ô ǒ ö ō ɔ {ɔ\\u0301} {ɔ\\u0302} {ɔ\\u030C} {ɔ\\u0304} p r ŕ s t u ú û ǔ ū v w y"
  auxiliary: "q x z"
  marks: "◌́ ◌̂ ◌̄ ◌̈ ◌̌"
  numerals: "  \\- ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B Ɓ C D E Ǝ Ɛ F G H I J K L M N Ŋ O Ɔ P R S T U V W Y"
}
sample_text {
  fallback_language: "en"
}
