id: "nn"
language: "nn"
script: "Latn"
name: "Norwegian Nynorsk"
population: 1366860
region: "NO"
exemplar_chars {
  auxiliary: "á ǎ č ç đ è ê ń ñ ŋ š ŧ ü ž ä ö"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ \" “ ” ( ) [ ] § @ * / & # † ‡ ′ ″"
}
sample_text {
  masthead_full: "AaLl"
  masthead_partial: "Ee"
  styles: "Då det å godkjenne det naturlege menneskeverdet"
  tester: "og då hån og vørdsløyse mot menneskerettane har ført til barbariske"
  poster_sm: "og då det er"
  poster_md: "og då det"
  poster_lg: "Alle"
  specimen_48: "og då folka i Dei Sameinte Nasjonane har stadfest trua si i denne"
  specimen_36: "Då det å godkjenne det naturlege menneskeverdet med like og umissande rettar for alle menneske på jorda"
  specimen_32: "Då det å godkjenne det naturlege menneskeverdet med like og umissande rettar for alle menneske på jorda er grunnlaget for fridom, rettferd og fred i verda,"
  specimen_21: "Då det å godkjenne det naturlege menneskeverdet med like og umissande rettar for alle menneske på jorda er grunnlaget for fridom, rettferd og fred i verda,\nog då hån og vørdsløyse mot menneskerettane har ført til barbariske handlingar som har skaka samvitet til menneskeretta, er framvoksteren i den verda der menneska skal ha talefridom og trusfridom og vere løyste frå otte og naud, kunngjord som det høgste målet for kvart menneske,"
  specimen_16: "Då det å godkjenne det naturlege menneskeverdet med like og umissande rettar for alle menneske på jorda er grunnlaget for fridom, rettferd og fred i verda,\nog då hån og vørdsløyse mot menneskerettane har ført til barbariske handlingar som har skaka samvitet til menneskeretta, er framvoksteren i den verda der menneska skal ha talefridom og trusfridom og vere løyste frå otte og naud, kunngjord som det høgste målet for kvart menneske,\nog då det er nødvendig at menneskerettane blir verna om av lover slik at menneska ikkje blir tvinga til å finne den siste utvegen i å gjere opprør mot tyranni og trælekår,"
}
