id: "nnh"
name: "Ngiemboon"
preferred_name: ""
autonym: "Ngyɛmbɔɔŋ"
population: 388430
region: "CM"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P S T U V W Y Z À Á Â È É Ê Ì Í Ò Ó Ô Ù Ú Û Ÿ Ě Ń Ŋ Ǎ Ǒ Ǔ Ɔ Ɛ Ʉ Ḿ Ẅ a b c d e f g h i j k l m n o p s t u v w y z à á â è é ê ì í ò ó ô ù ú û ÿ ě ń ŋ ǎ ǒ ǔ ɔ ɛ ʉ ʼ ḿ ẅ"
  auxiliary: "Q R X q r x"
  marks: "◌̀ ◌́ ◌̂ ◌̈ ◌̌"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: ", ; \\: ! ? . \' ‘ ’ « »"
  index: "A B C D E Ɛ F G H I J K L M N Ŋ O Ɔ P {Pf} R S {Sh} T {Ts} U Ʉ V W Ẅ Y Ÿ Z ʼ"
}
sample_text {
  fallback_language: "en"
}
