id: "nnp_Latn"
language: "nnp"
script: "Latn"
name: "Wancho Naga, Latin"
sample_text {
  masthead_full: "KkHh"
  masthead_partial: "Uu"
  styles: "K\nh\nu\nn\ny\ne\nk\n \nn\nu\ns\na\na\n \nk\ni\nm\n \nj\na\na"
  tester: "K\nh\nu\nn\ny\ne\nk\n \nn\nu\ns\na\na\n \nk\ni\nm\n \nj\na\na\nu\n \nk\na\nu\n \nt\na\nm\n "
  poster_sm: "K\nh\nu\nn\ny\ne"
  poster_md: "K\nh\nu\nn\ny"
  poster_lg: "K\nh"
  specimen_48: "K\nh\nu\nn\ny\ne\nk\n \nn\nu\ns\na\na\n \nk\ni\nm\n \nj\na\na\nu\n \nk\na\nu\n \nt\na\nm\n "
  specimen_36: "K\nh\nu\nn\ny\ne\nk\n \nn\nu\ns\na\na\n \nk\ni\nm\n \nj\na\na\nu\n \nk\na\nu\n \nt\na\nm\n \nh\no\nn\n \nc\na\n \nj\ne\n \nk\na\nn\n \nt\na\ni\nʔ\n \nm"
  specimen_32: "K\nh\nu\nn\ny\ne\nk\n \nn\nu\ns\na\na\n \nk\ni\nm\n \nj\na\na\nu\n \nk\na\nu\n \nt\na\nm\n \nh\no\nn\n \nc\na\n \nj\ne\n \nk\na\nn\n \nt\na\ni\nʔ\n \nm\no\nn\ng\n \nt\nh\nu\nn\ng\n \np\nh\na\n \np\nu\nʔ\n \nc\na"
  specimen_21: "K\nh\nu\nn\ny\ne\nk\n \nn\nu\ns\na\na\n \nk\ni\nm\n \nj\na\na\nu\n \nk\na\nu\n \nt\na\nm\n \nh\no\nn\n \nc\na\n \nj\ne\n \nk\na\nn\n \nt\na\ni\nʔ\n \nm\no\nn\ng\n \nt\nh\nu\nn\ng\n \np\nh\na\n \np\nu\nʔ\n \nc\na\n \nn\nu\np\nu\n,\n \nc\na\n \nc\na\na\n \nl\na\nm\n \ng\no\ni\n \nk\na\n \nc\na\ni\n \nc\na\n \nn\na\na\nu\n \nl\na\n \nt\na\ni\nʔ\n \na\na\n \np\na\nj\ni\n.\nK\nh\nu\nn\ny\ne\nk\n \nn\nu\ns\na\na\n \nk\ni\nm\n \nj\na\na\nu\n \nk\na\nu\n \nt"
  specimen_16: "K\nh\nu\nn\ny\ne\nk\n \nn\nu\ns\na\na\n \nk\ni\nm\n \nj\na\na\nu\n \nk\na\nu\n \nt\na\nm\n \nh\no\nn\n \nc\na\n \nj\ne\n \nk\na\nn\n \nt\na\ni\nʔ\n \nm\no\nn\ng\n \nt\nh\nu\nn\ng\n \np\nh\na\n \np\nu\nʔ\n \nc\na\n \nn\nu\np\nu\n,\n \nc\na\n \nc\na\na\n \nl\na\nm\n \ng\no\ni\n \nk\na\n \nc\na\ni\n \nc\na\n \nn\na\na\nu\n \nl\na\n \nt\na\ni\nʔ\n \na\na\n \np\na\nj\ni\n.\nK\nh\nu\nn\ny\ne\nk\n \nn\nu\ns\na\na\n \nk\ni\nm\n \nj\na\na\nu\n \nk\na\nu\n \nt\na\nm\n \nh\no\nn\n \nc\na\n \nj\ne\n \nk\na\nn\n \nt\na\ni\nʔ\n \nm\no\nn\ng\n \nt\nh\nu\nn\ng\n \np\nh\na\n \np\nu\nʔ\n \nc\na\n \nn\nu\np\nu\n,\n \nc\na\n \nc\na\na\n \nl\na\nm\n \ng\no\ni\n \nk\na\n \nc\na\ni\n \nc\na\n \nn\na\na\nu\n \nl\na\n \nt\na\ni\nʔ\n \na\na\n \np\na\nj\ni\n.\nK\nh\nu\nn\ny\ne\nk\n \nn\nu\ns\na\na\n \nk\ni\nm\n \nj\na\na\nu\n \nk\na\nu\n \nt\na\nm"
}
