id: "nnp_Latn"
language: "nnp"
script: "Latn"
name: "Wancho Naga, Latin"
region: "IN"
sample_text {
  masthead_full: "KkHh"
  masthead_partial: "Uu"
  styles: "Khunyek nusaa kim jaau kau tam hon ca je"
  tester: "Khunyek nusaa kim jaau kau tam hon ca je kan taiʔ mong thung"
  poster_sm: "Khunyek nusaa"
  poster_md: "Khunyek"
  poster_lg: "Khunyek"
  specimen_48: "Khunyek nusaa kim jaau kau tam hon ca je kan taiʔ mong thung pha"
  specimen_36: "Khunyek nusaa kim jaau kau tam hon ca je kan taiʔ mong thung pha puʔ ca nupu, ca caa lam goi ka cai ca naau la taiʔ aa paji."
  specimen_32: "Khunyek nusaa kim jaau kau tam hon ca je kan taiʔ mong thung pha puʔ ca nupu, ca caa lam goi ka cai ca naau la taiʔ aa paji."
  specimen_21: "Khunyek nusaa kim jaau kau tam hon ca je kan taiʔ mong thung pha puʔ ca nupu, ca caa lam goi ka cai ca naau la taiʔ aa paji.\nKhunyek nusaa kim jaau kau tam hon ca je kan taiʔ mong thung pha puʔ ca nupu, ca caa lam goi ka cai ca naau la taiʔ aa paji.\nKhunyek nusaa kim jaau kau tam hon ca je kan taiʔ mong thung pha puʔ ca nupu, ca caa lam goi ka cai ca naau la taiʔ aa paji."
  specimen_16: "Khunyek nusaa kim jaau kau tam hon ca je kan taiʔ mong thung pha puʔ ca nupu, ca caa lam goi ka cai ca naau la taiʔ aa paji.\nKhunyek nusaa kim jaau kau tam hon ca je kan taiʔ mong thung pha puʔ ca nupu, ca caa lam goi ka cai ca naau la taiʔ aa paji.\nKhunyek nusaa kim jaau kau tam hon ca je kan taiʔ mong thung pha puʔ ca nupu, ca caa lam goi ka cai ca naau la taiʔ aa paji.\nKhunyek nusaa kim jaau kau tam hon ca je kan taiʔ mong thung pha puʔ ca nupu, ca caa lam goi ka cai ca naau la taiʔ aa paji.\nKhunyek nusaa kim jaau kau tam hon ca je kan taiʔ mong thung pha puʔ ca nupu, ca caa lam goi ka cai ca naau la taiʔ aa paji."
}
