id: "nnp_Wcho"
language: "nnp"
script: "Wcho"
name: "Wancho Naga"
population: 56000
region: "IN"
sample_text {
  masthead_full: ""
  masthead_partial: ""
  styles: "𞋙\n𞋞\n𞋩\n𞋛\n𞋔\n \n𞋉\n𞋞\n𞋮\n𞋎\n𞋀\n𞋮\n \n𞋔\n𞋜\n𞋘\n𞋯\n \n𞋐\n𞋀\n𞋞"
  tester: "𞋙\n𞋞\n𞋩\n𞋛\n𞋔\n \n𞋉\n𞋞\n𞋮\n𞋎\n𞋀\n𞋮\n \n𞋔\n𞋜\n𞋘\n𞋯\n \n𞋐\n𞋀\n𞋞\n \n𞋔\n𞋁\n𞋞\n \n𞋋\n𞋁\n𞋘\n \n𞋚"
  poster_sm: "𞋙\n𞋞\n𞋩\n𞋛\n𞋔\n "
  poster_md: "𞋙\n𞋞\n𞋩\n𞋛\n𞋔"
  poster_lg: "𞋙\n𞋞"
  specimen_48: "𞋙\n𞋞\n𞋩\n𞋛\n𞋔\n \n𞋉\n𞋞\n𞋮\n𞋎\n𞋀\n𞋮\n \n𞋔\n𞋜\n𞋘\n𞋯\n \n𞋐\n𞋀\n𞋞\n \n𞋔\n𞋁\n𞋞\n \n𞋋\n𞋁\n𞋘\n \n𞋚"
  specimen_36: "𞋙\n𞋞\n𞋩\n𞋛\n𞋔\n \n𞋉\n𞋞\n𞋮\n𞋎\n𞋀\n𞋮\n \n𞋔\n𞋜\n𞋘\n𞋯\n \n𞋐\n𞋀\n𞋞\n \n𞋔\n𞋁\n𞋞\n \n𞋋\n𞋁\n𞋘\n \n𞋚\n𞋕\n𞋉\n𞋯\n \n𞋃\n𞋁\n \n𞋐\n𞋛\n𞋯\n \n𞋔\n𞋁\n𞋮\n𞋉\n \n𞋋\n𞋁\n𞋜\n𞋫"
  specimen_32: "𞋙\n𞋞\n𞋩\n𞋛\n𞋔\n \n𞋉\n𞋞\n𞋮\n𞋎\n𞋀\n𞋮\n \n𞋔\n𞋜\n𞋘\n𞋯\n \n𞋐\n𞋀\n𞋞\n \n𞋔\n𞋁\n𞋞\n \n𞋋\n𞋁\n𞋘\n \n𞋚\n𞋕\n𞋉\n𞋯\n \n𞋃\n𞋁\n \n𞋐\n𞋛\n𞋯\n \n𞋔\n𞋁\n𞋮\n𞋉\n \n𞋋\n𞋁\n𞋜\n𞋫\n \n𞋘\n𞋢\n \n𞋌\n𞋞\n𞋝\n𞋮\n \n𞋇\n𞋁\n \n𞋊\n𞋞\n𞋫\n \n𞋃\n𞋁\n \n𞋉"
  specimen_21: "𞋙\n𞋞\n𞋩\n𞋛\n𞋔\n \n𞋉\n𞋞\n𞋮\n𞋎\n𞋀\n𞋮\n \n𞋔\n𞋜\n𞋘\n𞋯\n \n𞋐\n𞋀\n𞋞\n \n𞋔\n𞋁\n𞋞\n \n𞋋\n𞋁\n𞋘\n \n𞋚\n𞋕\n𞋉\n𞋯\n \n𞋃\n𞋁\n \n𞋐\n𞋛\n𞋯\n \n𞋔\n𞋁\n𞋮\n𞋉\n \n𞋋\n𞋁\n𞋜\n𞋫\n \n𞋘\n𞋢\n \n𞋌\n𞋞\n𞋝\n𞋮\n \n𞋇\n𞋁\n \n𞋊\n𞋞\n𞋫\n \n𞋃\n𞋁\n \n𞋉\n𞋞\n𞋮\n𞋊\n𞋞\n𞋮\n,\n \n𞋃\n𞋁\n \n𞋃\n𞋀\n𞋮\n \n𞋈\n𞋁\n𞋘\n \n𞋅\n𞋕\n𞋜\n𞋮\n \n𞋔\n𞋁\n \n𞋃\n𞋁\n𞋜\n \n𞋃\n𞋁\n \n𞋉\n𞋀\n𞋞\n \n𞋈\n𞋁\n \n𞋋\n𞋁\n𞋜\n𞋫\n \n𞋀\n \n𞋊\n𞋁\n𞋐\n𞋜\n.\n𞋙\n𞋞\n𞋩\n𞋛\n𞋔\n \n𞋉\n𞋞\n𞋮\n𞋎\n𞋀\n𞋮\n \n𞋔\n𞋜\n𞋘\n𞋯\n \n𞋐\n𞋀\n𞋞\n \n𞋔\n𞋁\n𞋞\n \n𞋋\n𞋁"
  specimen_16: "𞋙\n𞋞\n𞋩\n𞋛\n𞋔\n \n𞋉\n𞋞\n𞋮\n𞋎\n𞋀\n𞋮\n \n𞋔\n𞋜\n𞋘\n𞋯\n \n𞋐\n𞋀\n𞋞\n \n𞋔\n𞋁\n𞋞\n \n𞋋\n𞋁\n𞋘\n \n𞋚\n𞋕\n𞋉\n𞋯\n \n𞋃\n𞋁\n \n𞋐\n𞋛\n𞋯\n \n𞋔\n𞋁\n𞋮\n𞋉\n \n𞋋\n𞋁\n𞋜\n𞋫\n \n𞋘\n𞋢\n \n𞋌\n𞋞\n𞋝\n𞋮\n \n𞋇\n𞋁\n \n𞋊\n𞋞\n𞋫\n \n𞋃\n𞋁\n \n𞋉\n𞋞\n𞋮\n𞋊\n𞋞\n𞋮\n,\n \n𞋃\n𞋁\n \n𞋃\n𞋀\n𞋮\n \n𞋈\n𞋁\n𞋘\n \n𞋅\n𞋕\n𞋜\n𞋮\n \n𞋔\n𞋁\n \n𞋃\n𞋁\n𞋜\n \n𞋃\n𞋁\n \n𞋉\n𞋀\n𞋞\n \n𞋈\n𞋁\n \n𞋋\n𞋁\n𞋜\n𞋫\n \n𞋀\n \n𞋊\n𞋁\n𞋐\n𞋜\n.\n𞋙\n𞋞\n𞋩\n𞋛\n𞋔\n \n𞋉\n𞋞\n𞋮\n𞋎\n𞋀\n𞋮\n \n𞋔\n𞋜\n𞋘\n𞋯\n \n𞋐\n𞋀\n𞋞\n \n𞋔\n𞋁\n𞋞\n \n𞋋\n𞋁\n𞋘\n \n𞋚\n𞋕\n𞋉\n𞋯\n \n𞋃\n𞋁\n \n𞋐\n𞋛\n𞋯\n \n𞋔\n𞋁\n𞋮\n𞋉\n \n𞋋\n𞋁\n𞋜\n𞋫\n \n𞋘\n𞋢\n \n𞋌\n𞋞\n𞋝\n𞋮\n \n𞋇\n𞋁\n \n𞋊\n𞋞\n𞋫\n \n𞋃\n𞋁\n \n𞋉\n𞋞\n𞋮\n𞋊\n𞋞\n𞋮\n,\n \n𞋃\n𞋁\n \n𞋃\n𞋀\n𞋮\n \n𞋈\n𞋁\n𞋘\n \n𞋅\n𞋕\n𞋜\n𞋮\n \n𞋔\n𞋁\n \n𞋃\n𞋁\n𞋜\n \n𞋃\n𞋁\n \n𞋉\n𞋀\n𞋞\n \n𞋈\n𞋁\n \n𞋋\n𞋁\n𞋜\n𞋫\n \n𞋀\n \n𞋊\n𞋁\n𞋐\n𞋜\n.\n𞋙\n𞋞\n𞋩\n𞋛\n𞋔\n \n𞋉\n𞋞\n𞋮\n𞋎\n𞋀\n𞋮\n \n𞋔\n𞋜\n𞋘\n𞋯\n \n𞋐\n𞋀\n𞋞\n \n𞋔\n𞋁\n𞋞\n \n𞋋\n𞋁\n𞋘\n "
}
