id: "no"
language: "no"
script: "Latn"
name: "Norwegian"
autonym: "Norsk"
population: 0
exemplar_chars {
  base: "a à b c d e é f g h i j k l m n o ó ò ô p q r s t u v w x y z æ ø å"
  auxiliary: "á ǎ ã č ç đ è ê í ń ñ ŋ š ŧ ú ü ž ä ö"
  marks: "◌̀ ◌́ ◌̂ ◌̈ ◌̊"
  numerals: "  , % ‰ + − 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‑ – , ; : ! ? . \' \" « » ( ) [ ] { } § @ * / \\ { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Æ Ø Å"
}
sample_text {
  fallback_language: "en"
}
