id: "non_Latn"
language: "non"
script: "Latn"
name: "Old Norse, Latin, Sweden"
sample_text {
  masthead_full: "AaLl"
  masthead_partial: "Ii"
  styles: "A\nl\nl\ni\nr\n \nm\næ\nn\n \næ\nr\nu\n \nf\nø\n̄\nd\nd\ni\nr"
  tester: "A\nl\nl\ni\nr\n \nm\næ\nn\n \næ\nr\nu\n \nf\nø\n̄\nd\nd\ni\nr\n \nf\nr\næ\nl\ns\ni\nr\n \no"
  poster_sm: "A\nl\nl\ni\nr\n "
  poster_md: "A\nl\nl\ni\nr"
  poster_lg: "A\nl"
  specimen_48: "A\nl\nl\ni\nr\n \nm\næ\nn\n \næ\nr\nu\n \nf\nø\n̄\nd\nd\ni\nr\n \nf\nr\næ\nl\ns\ni\nr\n \no"
  specimen_36: "A\nl\nl\ni\nr\n \nm\næ\nn\n \næ\nr\nu\n \nf\nø\n̄\nd\nd\ni\nr\n \nf\nr\næ\nl\ns\ni\nr\n \no\nk\n \nǣ\ng\nh\nu\n \ns\na\nm\na\n \nv\næ\nr\nd\nh\ne\n \no"
  specimen_32: "A\nl\nl\ni\nr\n \nm\næ\nn\n \næ\nr\nu\n \nf\nø\n̄\nd\nd\ni\nr\n \nf\nr\næ\nl\ns\ni\nr\n \no\nk\n \nǣ\ng\nh\nu\n \ns\na\nm\na\n \nv\næ\nr\nd\nh\ne\n \no\nk\n \nr\nǣ\nt\nt\n.\n \nT\nh\nē\nr\n \næ\nr\nu\n \ng\ni\nv\nn"
  specimen_21: "A\nl\nl\ni\nr\n \nm\næ\nn\n \næ\nr\nu\n \nf\nø\n̄\nd\nd\ni\nr\n \nf\nr\næ\nl\ns\ni\nr\n \no\nk\n \nǣ\ng\nh\nu\n \ns\na\nm\na\n \nv\næ\nr\nd\nh\ne\n \no\nk\n \nr\nǣ\nt\nt\n.\n \nT\nh\nē\nr\n \næ\nr\nu\n \ng\ni\nv\nn\ni\nr\n \ns\na\nm\nv\ni\nt\n \no\nk\n \ns\ni\nn\n,\n \no\nk\n \ns\nk\nu\nl\nu\n \ng\næ\nr\na\n \nh\nw\na\nr\na\nn\nn\na\nn\n \nb\nr\nō\nd\nh\nu\nr\nl\nī\nk\na\n.\nA\nl\nl\ni\nr\n \nm\næ\nn\n \næ\nr\nu\n \nf\nø\n̄\nd\nd\ni\nr\n \nf\nr\næ\nl\ns"
  specimen_16: "A\nl\nl\ni\nr\n \nm\næ\nn\n \næ\nr\nu\n \nf\nø\n̄\nd\nd\ni\nr\n \nf\nr\næ\nl\ns\ni\nr\n \no\nk\n \nǣ\ng\nh\nu\n \ns\na\nm\na\n \nv\næ\nr\nd\nh\ne\n \no\nk\n \nr\nǣ\nt\nt\n.\n \nT\nh\nē\nr\n \næ\nr\nu\n \ng\ni\nv\nn\ni\nr\n \ns\na\nm\nv\ni\nt\n \no\nk\n \ns\ni\nn\n,\n \no\nk\n \ns\nk\nu\nl\nu\n \ng\næ\nr\na\n \nh\nw\na\nr\na\nn\nn\na\nn\n \nb\nr\nō\nd\nh\nu\nr\nl\nī\nk\na\n.\nA\nl\nl\ni\nr\n \nm\næ\nn\n \næ\nr\nu\n \nf\nø\n̄\nd\nd\ni\nr\n \nf\nr\næ\nl\ns\ni\nr\n \no\nk\n \nǣ\ng\nh\nu\n \ns\na\nm\na\n \nv\næ\nr\nd\nh\ne\n \no\nk\n \nr\nǣ\nt\nt\n.\n \nT\nh\nē\nr\n \næ\nr\nu\n \ng\ni\nv\nn\ni\nr\n \ns\na\nm\nv\ni\nt\n \no\nk\n \ns\ni\nn\n,\n \no\nk\n \ns\nk\nu\nl\nu\n \ng\næ\nr\na\n \nh\nw\na\nr\na\nn\nn\na\nn\n \nb\nr\nō\nd\nh\nu\nr\nl\nī\nk\na\n.\nA\nl\nl\ni\nr\n \nm\næ\nn\n \næ\nr\nu\n \nf\nø\n̄\nd\nd\ni\nr\n \nf\nr\næ\nl\ns\ni"
}
