id: "nrf_Latn"
language: "nrf"
script: "Latn"
name: "Jèrriais, Latin"
sample_text {
  masthead_full: "TtOo"
  masthead_partial: "Uu"
  styles: "T\no\nu\no\ns\n \nl\n\'\ns\n \nh\no\nu\nm\ne\ns\n \nn\nâ\nq\nu"
  tester: "T\no\nu\no\ns\n \nl\n\'\ns\n \nh\no\nu\nm\ne\ns\n \nn\nâ\nq\nu\ni\ns\ns\ne\nn\nt\n \nl\ni\nb"
  poster_sm: "T\no\nu\no\ns\n "
  poster_md: "T\no\nu\no\ns"
  poster_lg: "T\no"
  specimen_48: "T\no\nu\no\ns\n \nl\n\'\ns\n \nh\no\nu\nm\ne\ns\n \nn\nâ\nq\nu\ni\ns\ns\ne\nn\nt\n \nl\ni\nb"
  specimen_36: "T\no\nu\no\ns\n \nl\n\'\ns\n \nh\no\nu\nm\ne\ns\n \nn\nâ\nq\nu\ni\ns\ns\ne\nn\nt\n \nl\ni\nb\ne\ns\n \ne\nt\n \np\na\nr\ne\nl\ns\n \nd\na\nu\nn\ns\n \nl"
  specimen_32: "T\no\nu\no\ns\n \nl\n\'\ns\n \nh\no\nu\nm\ne\ns\n \nn\nâ\nq\nu\ni\ns\ns\ne\nn\nt\n \nl\ni\nb\ne\ns\n \ne\nt\n \np\na\nr\ne\nl\ns\n \nd\na\nu\nn\ns\n \nl\nu\ns\n \nt\na\nê\nt\ne\n \ne\nt\n \ne\nn\n \nd\nr\ne\ni\nt"
  specimen_21: "T\no\nu\no\ns\n \nl\n\'\ns\n \nh\no\nu\nm\ne\ns\n \nn\nâ\nq\nu\ni\ns\ns\ne\nn\nt\n \nl\ni\nb\ne\ns\n \ne\nt\n \np\na\nr\ne\nl\ns\n \nd\na\nu\nn\ns\n \nl\nu\ns\n \nt\na\nê\nt\ne\n \ne\nt\n \ne\nn\n \nd\nr\ne\ni\nt\n.\n \nI\nl\n \no\nu\nn\nt\n \nb\ny\ni\nn\n \nd\ne\n \nl\n\'\no\nb\ni\nc\nh\ne\n \ne\nt\n \nd\ne\n \nl\n\'\ni\nn\ng\na\nm\no\n \ne\nt\n \nd\ne\ni\nv\ne\nn\nt\n \nf\na\ni\nr\ne\n \nd\n\'\na\nv\ne\nu\n \nl\ne\nu\ns\n \np\nr\no\nc\nh\na\nn\n \nc\no\nu"
  specimen_16: "T\no\nu\no\ns\n \nl\n\'\ns\n \nh\no\nu\nm\ne\ns\n \nn\nâ\nq\nu\ni\ns\ns\ne\nn\nt\n \nl\ni\nb\ne\ns\n \ne\nt\n \np\na\nr\ne\nl\ns\n \nd\na\nu\nn\ns\n \nl\nu\ns\n \nt\na\nê\nt\ne\n \ne\nt\n \ne\nn\n \nd\nr\ne\ni\nt\n.\n \nI\nl\n \no\nu\nn\nt\n \nb\ny\ni\nn\n \nd\ne\n \nl\n\'\no\nb\ni\nc\nh\ne\n \ne\nt\n \nd\ne\n \nl\n\'\ni\nn\ng\na\nm\no\n \ne\nt\n \nd\ne\ni\nv\ne\nn\nt\n \nf\na\ni\nr\ne\n \nd\n\'\na\nv\ne\nu\n \nl\ne\nu\ns\n \np\nr\no\nc\nh\na\nn\n \nc\no\nu\nm\ne\n \ns\ni\n \nc\nh\n\'\nt\na\ni\nt\n \np\no\nu\n \ny\ne\nu\ns\n.\nT\no\nu\no\ns\n \nl\n\'\ns\n \nh\no\nu\nm\ne\ns\n \nn\nâ\nq\nu\ni\ns\ns\ne\nn\nt\n \nl\ni\nb\ne\ns\n \ne\nt\n \np\na\nr\ne\nl\ns\n \nd\na\nu\nn\ns\n \nl\nu\ns\n \nt\na\nê\nt\ne\n \ne\nt\n \ne\nn\n \nd\nr\ne\ni\nt\n.\n \nI\nl\n \no\nu\nn\nt\n \nb\ny\ni\nn\n \nd\ne\n \nl\n\'\no\nb\ni\nc\nh\ne\n \ne\nt\n \nd\ne\n \nl"
}
