id: "nus"
language: "nus"
script: "Latn"
name: "Nuer"
autonym: "Naath"
population: 591427
region: "SS"
exemplar_chars {
  base: "a ä {a\\u0331} b c d e ë {e\\u0331} ɛ {ɛ\\u0308} {ɛ\\u0331} {ɛ\\u0331\\u0308} f g ɣ h i ï {i\\u0331} j k l m n ŋ o ö {o\\u0331} ɔ {ɔ\\u0308} {ɔ\\u0331} p q r s t u v w x y z"
  marks: "◌̈ ◌̱"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B C D E Ɛ F G Ɣ H I J K L M N Ŋ O Ɔ P Q R S T U V W X Y Z"
}
sample_text {
  fallback_language: "en"
}
