id: "nyn"
name: "Nyankole"
preferred_name: ""
autonym: "Runyankore"
population: 2724939
region: "UG"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K M N O P R S T U V W Y Z a b c d e f g h i j k m n o p r s t u v w y z"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
}
sample_text {
  masthead_full: "AaBb"
  masthead_partial: "Nn"
  tester: "Ekitiinisa ky\'omuntu ekyobuhangwa nikiingana nobushoborozi obutakabaasa"
  poster_sm: "Obutagyendera"
  poster_md: "Ekibiina"
  poster_lg: "Abantu"
  specimen_48: "Abantu boona ahu bari ahabwokugira ekyetengo kimwe ekyamahanga"
  specimen_36: "Tihariho muntu oshemereire kukwatirwa omubuhuuku. Obuhuuku, nobushubuzi bw\'abahuuku, tiburikwiikirizibwa omunsi yoona."
  specimen_32: "Buri muntu ahatari kushoroora naatekwa kuhozesibwa \"omu mushana\" omu kooti etaine kugweera orubaju rumwe kandi nokumanyisibwa omushango gwoona ogurikuba nigumutabaarizibwa."
  specimen_21: "Ekitinisa kyomuntu, amakage, ab\'eka ye, ebihandiko bye hamwe namabaruhage tibishemereire kutahirirwa narishi kuzanirwaho. Buri muntu aine obushoborozi bwokweyambisa ebiragiro kuzibira abo abarikwenda kwetasya omu nshonga ze wenka.\nBuri muntu aine obugabe okwahura ekirungi aha kibi, nokurond ediini eyi arashome kandi aine obugabe we wenka narishi nabataahibe okuteeka omu nkora ebi arikwiikirizamu."
  specimen_16: "Buri muntu aine obugabe kugira enteekateka ye kandi nokugamba narishi okuhandiika nkoku arikuteekateeka. Kandi buri muntu aine obugabe okurabya ebyarikutekyereza aha Radio, Television, empapura z\'amahurire, nemihanda endiijo.\nBuri munyansi aine obushoborozi kutuura n\'abantu bataahi be omu nisingye , eki kimbaasise kutereeza engyesho ze, nokuhika aha byaarikurubirira ebye kitiinisa nkomuntu arikuraba omu kukora kweihanga rye okurugiirira ahanteekateeka nenkozesa yobugaiga obweihanga omu byentasya, ebyemiturire ya bantu, nobuhangwa bwaabo, ebitarikubasa kunagiijurwa omu kukurakurana oku."
}
