id: "oaa_Cyrl"
language: "oaa"
script: "Cyrl"
name: "Orok"
sample_text {
  masthead_full: "ЧчИи"
  masthead_partial: "Пп"
  styles: "Ч\nи\nп\nа\n̄\nл\nи\n \nг\nу\nр\nу\nн\nн\nе\n̄\n \nб\nа\nл\nӡ\nи"
  tester: "Ч\nи\nп\nа\n̄\nл\nи\n \nг\nу\nр\nу\nн\nн\nе\n̄\n \nб\nа\nл\nӡ\nи\nч\nи\n \nг\nэ\nв\nу\nм\nэ\n,"
  poster_sm: "Ч\nи\nп\nа\n̄\nл"
  poster_md: "Ч\nи\nп\nа\n̄"
  poster_lg: "Ч\nи"
  specimen_48: "Ч\nи\nп\nа\n̄\nл\nи\n \nг\nу\nр\nу\nн\nн\nе\n̄\n \nб\nа\nл\nӡ\nи\nч\nи\n \nг\nэ\nв\nу\nм\nэ\n,"
  specimen_36: "Ч\nи\nп\nа\n̄\nл\nи\n \nг\nу\nр\nу\nн\nн\nе\n̄\n \nб\nа\nл\nӡ\nи\nч\nи\n \nг\nэ\nв\nу\nм\nэ\n,\n \nо\nм\nо\nт\nт\nо\n \nм\nэ\n̄\nн\nэ\n \nм\nө\nр\nө\nн\nӡ\nи"
  specimen_32: "Ч\nи\nп\nа\n̄\nл\nи\n \nг\nу\nр\nу\nн\nн\nе\n̄\n \nб\nа\nл\nӡ\nи\nч\nи\n \nг\nэ\nв\nу\nм\nэ\n,\n \nо\nм\nо\nт\nт\nо\n \nм\nэ\n̄\nн\nэ\n \nм\nө\nр\nө\nн\nӡ\nи\n,\n \nм\nэ\n̄\nн\nэ\n \nд\nо\nр\nо\nн\nӡ\nи\n.\n \nН\nо\n̄\nч\nи"
  specimen_21: "Ч\nи\nп\nа\n̄\nл\nи\n \nг\nу\nр\nу\nн\nн\nе\n̄\n \nб\nа\nл\nӡ\nи\nч\nи\n \nг\nэ\nв\nу\nм\nэ\n,\n \nо\nм\nо\nт\nт\nо\n \nм\nэ\n̄\nн\nэ\n \nм\nө\nр\nө\nн\nӡ\nи\n,\n \nм\nэ\n̄\nн\nэ\n \nд\nо\nр\nо\nн\nӡ\nи\n.\n \nН\nо\n̄\nч\nи\n \nи\nд\nэ\nл\nу\n,\n \nи\nр\nк\nа\nл\nу\n,\n \nм\nэ\n̄\nн\nэ\n \nм\nэ\n̄\nн\nӡ\nи\n \nн\nа\n̄\nд\nа\nк\nт\nа\nӈ\nа\nч\nи\n \nб\nu\n̄\nч\nи\n.\nЧ\nи\nп\nа\n̄\nл\nи\n \nг\nу\nр\nу\nн\nн\nе\n̄\n \nб\nа\nл\nӡ\nи\nч\nи\n \nг\nэ\nв\nу\nм\nэ\n,\n \nо\nм\nо\nт"
  specimen_16: "Ч\nи\nп\nа\n̄\nл\nи\n \nг\nу\nр\nу\nн\nн\nе\n̄\n \nб\nа\nл\nӡ\nи\nч\nи\n \nг\nэ\nв\nу\nм\nэ\n,\n \nо\nм\nо\nт\nт\nо\n \nм\nэ\n̄\nн\nэ\n \nм\nө\nр\nө\nн\nӡ\nи\n,\n \nм\nэ\n̄\nн\nэ\n \nд\nо\nр\nо\nн\nӡ\nи\n.\n \nН\nо\n̄\nч\nи\n \nи\nд\nэ\nл\nу\n,\n \nи\nр\nк\nа\nл\nу\n,\n \nм\nэ\n̄\nн\nэ\n \nм\nэ\n̄\nн\nӡ\nи\n \nн\nа\n̄\nд\nа\nк\nт\nа\nӈ\nа\nч\nи\n \nб\nu\n̄\nч\nи\n.\nЧ\nи\nп\nа\n̄\nл\nи\n \nг\nу\nр\nу\nн\nн\nе\n̄\n \nб\nа\nл\nӡ\nи\nч\nи\n \nг\nэ\nв\nу\nм\nэ\n,\n \nо\nм\nо\nт\nт\nо\n \nм\nэ\n̄\nн\nэ\n \nм\nө\nр\nө\nн\nӡ\nи\n,\n \nм\nэ\n̄\nн\nэ\n \nд\nо\nр\nо\nн\nӡ\nи\n.\n \nН\nо\n̄\nч\nи\n \nи\nд\nэ\nл\nу\n,\n \nи\nр\nк\nа\nл\nу\n,\n \nм\nэ\n̄\nн\nэ\n \nм\nэ\n̄\nн\nӡ\nи\n \nн\nа\n̄\nд\nа\nк\nт\nа\nӈ\nа\nч\nи\n \nб\nu\n̄\nч\nи\n.\nЧ\nи\nп\nа\n̄\nл\nи\n \nг\nу\nр\nу\nн\nн\nе\n̄\n \nб\nа\nл\nӡ\nи\nч\nи\n \nг\nэ\nв\nу\nм\nэ\n,\n \nо\nм\nо\nт\nт\nо\n \nм\nэ\n̄\nн\nэ\n \nм"
}
