id: "ojb_Cans"
language: "ojb"
script: "Cans"
name: "Northwestern Ojibwa, Unified Canadian Aboriginal Syllabics, Canada"
sample_text {
  masthead_full: "ᑲᐦᑭᓇ"
  masthead_partial: "ᐌᓀ"
  styles: "ᑲ\nᐦ\nᑭ\nᓇ\nᐌ\nᓀ\nᓐ\n \nᑳ\nᐱ\nᒫ\nᑎ\nᓯ\nᐙ\nᑦ\n \nᓂ\nᐦ\nᑖ\nᐎ\nᑭ"
  tester: "ᑲ\nᐦ\nᑭ\nᓇ\nᐌ\nᓀ\nᓐ\n \nᑳ\nᐱ\nᒫ\nᑎ\nᓯ\nᐙ\nᑦ\n \nᓂ\nᐦ\nᑖ\nᐎ\nᑭ\nᐗ\nᒃ\n \nᑎ\nᐯ\nᓂ\nᒥ\nᑎ\nᓱ\nᐎ"
  poster_sm: "ᑲ\nᐦ\nᑭ\nᓇ\nᐌ\nᓀ"
  poster_md: "ᑲ\nᐦ\nᑭ\nᓇ\nᐌ"
  poster_lg: "ᑲ\nᐦ"
  specimen_48: "ᑲ\nᐦ\nᑭ\nᓇ\nᐌ\nᓀ\nᓐ\n \nᑳ\nᐱ\nᒫ\nᑎ\nᓯ\nᐙ\nᑦ\n \nᓂ\nᐦ\nᑖ\nᐎ\nᑭ\nᐗ\nᒃ\n \nᑎ\nᐯ\nᓂ\nᒥ\nᑎ\nᓱ\nᐎ"
  specimen_36: "ᑲ\nᐦ\nᑭ\nᓇ\nᐌ\nᓀ\nᓐ\n \nᑳ\nᐱ\nᒫ\nᑎ\nᓯ\nᐙ\nᑦ\n \nᓂ\nᐦ\nᑖ\nᐎ\nᑭ\nᐗ\nᒃ\n \nᑎ\nᐯ\nᓂ\nᒥ\nᑎ\nᓱ\nᐎ\nᓂ\nᒃ\n \nᒦ\nᓇ\n \nᑖ\nᐱ\nᑕ\n \nᑭ\nᐦ\nᒋ\nᐃ\nᓀ\nᓐ\nᑖ\nᑯ\nᓯ\nᐎ"
  specimen_32: "ᑲ\nᐦ\nᑭ\nᓇ\nᐌ\nᓀ\nᓐ\n \nᑳ\nᐱ\nᒫ\nᑎ\nᓯ\nᐙ\nᑦ\n \nᓂ\nᐦ\nᑖ\nᐎ\nᑭ\nᐗ\nᒃ\n \nᑎ\nᐯ\nᓂ\nᒥ\nᑎ\nᓱ\nᐎ\nᓂ\nᒃ\n \nᒦ\nᓇ\n \nᑖ\nᐱ\nᑕ\n \nᑭ\nᐦ\nᒋ\nᐃ\nᓀ\nᓐ\nᑖ\nᑯ\nᓯ\nᐎ\nᓐ\n \nᑲ\nᔦ\n \nᑌ\nᐸ\nᑫ\nᓐ\nᑖ\nᑯ\nᓯ\nᐎ\nᓐ\n᙮\n \nᐅ\nᑕ\nᔮ\nᓈ"
  specimen_21: "ᑲ\nᐦ\nᑭ\nᓇ\nᐌ\nᓀ\nᓐ\n \nᑳ\nᐱ\nᒫ\nᑎ\nᓯ\nᐙ\nᑦ\n \nᓂ\nᐦ\nᑖ\nᐎ\nᑭ\nᐗ\nᒃ\n \nᑎ\nᐯ\nᓂ\nᒥ\nᑎ\nᓱ\nᐎ\nᓂ\nᒃ\n \nᒦ\nᓇ\n \nᑖ\nᐱ\nᑕ\n \nᑭ\nᐦ\nᒋ\nᐃ\nᓀ\nᓐ\nᑖ\nᑯ\nᓯ\nᐎ\nᓐ\n \nᑲ\nᔦ\n \nᑌ\nᐸ\nᑫ\nᓐ\nᑖ\nᑯ\nᓯ\nᐎ\nᓐ\n᙮\n \nᐅ\nᑕ\nᔮ\nᓈ\nᐙ\n \nᒥ\nᐦ\nᑲ\nᐎ\nᐎ\nᓐ\n \nᑲ\nᔦ\n \nᓂ\nᑆ\nᐦ\nᑳ\nᐎ\nᓐ\n \nᒦ\nᓇ\nᐙ\n \nᑕ\nᐦ\nᔥ\n \nᒋ\nᐃ\nᔑ\nᑲ\nᓇ\nᐙ\nᐸ\nᓐ\nᑎ\nᐙ\nᐸ\nᓐ\n \nᐊ\nᐦ\nᒑ\nᐦ\nᑯ\n \nᒥ\nᓄ\nᐐ\nᒋ\nᐎ\nᑎ\nᐎ\nᓂ\nᒃ\n᙮\nᑲ\nᐦ\nᑭ\nᓇ\nᐌ\nᓀ\nᓐ\n \nᑳ\nᐱ\nᒫ\nᑎ\nᓯ\nᐙ\nᑦ\n \nᓂ\nᐦ\nᑖ\nᐎ\nᑭ\nᐗ\nᒃ\n \nᑎ"
  specimen_16: "ᑲ\nᐦ\nᑭ\nᓇ\nᐌ\nᓀ\nᓐ\n \nᑳ\nᐱ\nᒫ\nᑎ\nᓯ\nᐙ\nᑦ\n \nᓂ\nᐦ\nᑖ\nᐎ\nᑭ\nᐗ\nᒃ\n \nᑎ\nᐯ\nᓂ\nᒥ\nᑎ\nᓱ\nᐎ\nᓂ\nᒃ\n \nᒦ\nᓇ\n \nᑖ\nᐱ\nᑕ\n \nᑭ\nᐦ\nᒋ\nᐃ\nᓀ\nᓐ\nᑖ\nᑯ\nᓯ\nᐎ\nᓐ\n \nᑲ\nᔦ\n \nᑌ\nᐸ\nᑫ\nᓐ\nᑖ\nᑯ\nᓯ\nᐎ\nᓐ\n᙮\n \nᐅ\nᑕ\nᔮ\nᓈ\nᐙ\n \nᒥ\nᐦ\nᑲ\nᐎ\nᐎ\nᓐ\n \nᑲ\nᔦ\n \nᓂ\nᑆ\nᐦ\nᑳ\nᐎ\nᓐ\n \nᒦ\nᓇ\nᐙ\n \nᑕ\nᐦ\nᔥ\n \nᒋ\nᐃ\nᔑ\nᑲ\nᓇ\nᐙ\nᐸ\nᓐ\nᑎ\nᐙ\nᐸ\nᓐ\n \nᐊ\nᐦ\nᒑ\nᐦ\nᑯ\n \nᒥ\nᓄ\nᐐ\nᒋ\nᐎ\nᑎ\nᐎ\nᓂ\nᒃ\n᙮\nᑲ\nᐦ\nᑭ\nᓇ\nᐌ\nᓀ\nᓐ\n \nᑳ\nᐱ\nᒫ\nᑎ\nᓯ\nᐙ\nᑦ\n \nᓂ\nᐦ\nᑖ\nᐎ\nᑭ\nᐗ\nᒃ\n \nᑎ\nᐯ\nᓂ\nᒥ\nᑎ\nᓱ\nᐎ\nᓂ\nᒃ\n \nᒦ\nᓇ\n \nᑖ\nᐱ\nᑕ\n \nᑭ\nᐦ\nᒋ\nᐃ\nᓀ\nᓐ\nᑖ\nᑯ\nᓯ\nᐎ\nᓐ\n \nᑲ\nᔦ\n \nᑌ\nᐸ\nᑫ\nᓐ\nᑖ\nᑯ\nᓯ\nᐎ\nᓐ\n᙮\n \nᐅ\nᑕ\nᔮ\nᓈ\nᐙ\n \nᒥ\nᐦ\nᑲ\nᐎ\nᐎ\nᓐ\n \nᑲ\nᔦ\n \nᓂ\nᑆ\nᐦ\nᑳ\nᐎ\nᓐ\n \nᒦ\nᓇ\nᐙ\n \nᑕ\nᐦ\nᔥ\n \nᒋ\nᐃ\nᔑ\nᑲ\nᓇ\nᐙ\nᐸ\nᓐ\nᑎ\nᐙ\nᐸ\nᓐ\n \nᐊ\nᐦ\nᒑ\nᐦ\nᑯ\n \nᒥ\nᓄ\nᐐ\nᒋ\nᐎ\nᑎ\nᐎ\nᓂ\nᒃ\n᙮\nᑲ\nᐦ\nᑭ\nᓇ\nᐌ\nᓀ\nᓐ\n \nᑳ\nᐱ\nᒫ\nᑎ\nᓯ\nᐙ\nᑦ\n \nᓂ\nᐦ\nᑖ\nᐎ\nᑭ\nᐗ\nᒃ\n "
}
