id: "or"
language: "or"
script: "Orya"
name: "Odia"
population: 42434880
region: "IN"
exemplar_chars {
  base: "଼ ଅ ଆ ଇ ଈ ଉ ଊ ଋ ଏ ଐ ଓ ଔ ଁ ଂ ଃ କ ଖ ଗ ଘ ଙ ଚ ଛ ଜ ଝ ଞ ଟ ଠ ଡ {ଡ଼} ଢ {ଢ଼} ଣ ତ ଥ ଦ ଧ ନ ପ ଫ ବ ଭ ମ ଯ ୟ ର ଲ ଳ ଵ ୱ ଶ ଷ ସ ହ ା ି ୀ ୁ ୂ ୃ େ ୈ ୋ ୌ ୍ {ଡ଼} {ଢ଼} {ଡ଼} {ଢ଼} {ଡ଼} {ଢ଼} {ଡ଼} {ଢ଼} {ଡ଼} {ଢ଼} {ଡ଼} {ଢ଼} {ଡ଼} {ଢ଼} {ଡ଼} {ଢ଼} {ଡ଼} {ଢ଼} {ଡ଼} {ଢ଼} {ଡ଼} {ଢ଼} {ଡ଼} {ଢ଼} {ଡ଼} {ଢ଼} {ଡ଼} {ଢ଼} {ଡ଼} {ଢ଼}"
  auxiliary: "‌‍"
  numerals: "- ‑ , . % ‰ + 0୦ 1୧ 2୨ 3୩ 4୪ 5୫ 6୬ 7୭ 8୮ 9୯"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ \" “ ” ( ) [ ] § @ * / & # † ‡ ′ ″"
  index: "ଅ ଆ ଇ ଈ ଉ ଊ ଋ ଏ ଐ ଓ ଔ କ ଖ ଗ ଘ ଙ ଚ ଛ ଜ ଝ ଞ ଟ ଠ ଡ ଢ ଣ ତ ଥ ଦ ଧ ନ ପ ଫ ବ ଭ ମ ଯ ର ଲ ଳ ଶ ଷ ସ ହ {କ୍ଷ} {କ୍ଷ} {କ୍ଷ} {କ୍ଷ} {କ୍ଷ} {କ୍ଷ} {କ୍ଷ} {କ୍ଷ} {କ୍ଷ} {କ୍ଷ} {କ୍ଷ} {କ୍ଷ} {କ୍ଷ} {କ୍ଷ} {କ୍ଷ} {କ୍ଷ}"
}
