id: "orh_Latn"
language: "orh"
script: "Latn"
name: "Oroqen"
sample_text {
  masthead_full: "BbEe"
  masthead_partial: "Yy"
  styles: "B\ne\ny\ne\nl\n \nb\na\nm\nb\nu\nr\n \nz\nh\ni\ny\nu\n \nb\ni"
  tester: "B\ne\ny\ne\nl\n \nb\na\nm\nb\nu\nr\n \nz\nh\ni\ny\nu\n \nb\ni\ns\nh\ni\n,\n \nz\nh\nu\nn\ny"
  poster_sm: "B\ne\ny\ne\nl\n "
  poster_md: "B\ne\ny\ne\nl"
  poster_lg: "B\ne"
  specimen_48: "B\ne\ny\ne\nl\n \nb\na\nm\nb\nu\nr\n \nz\nh\ni\ny\nu\n \nb\ni\ns\nh\ni\n,\n \nz\nh\nu\nn\ny"
  specimen_36: "B\ne\ny\ne\nl\n \nb\na\nm\nb\nu\nr\n \nz\nh\ni\ny\nu\n \nb\ni\ns\nh\ni\n,\n \nz\nh\nu\nn\ny\na\nn\n-\nd\nu\n \nb\ni\nn\ne\nk\ne\nn\n \nc\nh\nu\na\nn\nl\ni"
  specimen_32: "B\ne\ny\ne\nl\n \nb\na\nm\nb\nu\nr\n \nz\nh\ni\ny\nu\n \nb\ni\ns\nh\ni\n,\n \nz\nh\nu\nn\ny\na\nn\n-\nd\nu\n \nb\ni\nn\ne\nk\ne\nn\n \nc\nh\nu\na\nn\nl\ni\n-\nd\nu\n \nb\na\nm\nb\nu\nr\n \np\ni\nn\ng\nd\ne\nn\ng\n "
  specimen_21: "B\ne\ny\ne\nl\n \nb\na\nm\nb\nu\nr\n \nz\nh\ni\ny\nu\n \nb\ni\ns\nh\ni\n,\n \nz\nh\nu\nn\ny\na\nn\n-\nd\nu\n \nb\ni\nn\ne\nk\ne\nn\n \nc\nh\nu\na\nn\nl\ni\n-\nd\nu\n \nb\na\nm\nb\nu\nr\n \np\ni\nn\ng\nd\ne\nn\ng\n \nb\ni\ns\nh\ni\n.\n \nN\nu\ng\na\nr\nt\ni\nn\n \nl\ni\ns\nh\ni\nn\ng\n \nb\ni\nn\ne\nk\ne\nn\n \nl\ni\na\nn\ng\ns\nh\ni\nn\n \nb\ni\ns\nh\ni\n,\n \na\nk\ni\nn\n \nn\ne\nk\nu\nn\n \ng\nu\na\nn\ns\nh\ni\n-\nn\ng\ni\n \nc\nh\ni\nn\ng\ns\nh\ne\nn\n-"
  specimen_16: "B\ne\ny\ne\nl\n \nb\na\nm\nb\nu\nr\n \nz\nh\ni\ny\nu\n \nb\ni\ns\nh\ni\n,\n \nz\nh\nu\nn\ny\na\nn\n-\nd\nu\n \nb\ni\nn\ne\nk\ne\nn\n \nc\nh\nu\na\nn\nl\ni\n-\nd\nu\n \nb\na\nm\nb\nu\nr\n \np\ni\nn\ng\nd\ne\nn\ng\n \nb\ni\ns\nh\ni\n.\n \nN\nu\ng\na\nr\nt\ni\nn\n \nl\ni\ns\nh\ni\nn\ng\n \nb\ni\nn\ne\nk\ne\nn\n \nl\ni\na\nn\ng\ns\nh\ni\nn\n \nb\ni\ns\nh\ni\n,\n \na\nk\ni\nn\n \nn\ne\nk\nu\nn\n \ng\nu\na\nn\ns\nh\ni\n-\nn\ng\ni\n \nc\nh\ni\nn\ng\ns\nh\ne\nn\n-\nd\nu\n-\ni\nn\n \nd\nu\ni\nd\na\ni\n-\nm\ne\ne\nt\n-\nk\ni\n-\nt\ni\nn\n.\nB\ne\ny\ne\nl\n \nb\na\nm\nb\nu\nr\n \nz\nh\ni\ny\nu\n \nb\ni\ns\nh\ni\n,\n \nz\nh\nu\nn\ny\na\nn\n-\nd\nu\n \nb\ni\nn\ne\nk\ne\nn\n \nc\nh\nu\na\nn\nl\ni\n-\nd\nu\n \nb\na\nm\nb\nu\nr\n \np\ni\nn\ng\nd\ne\nn\ng\n \nb\ni\ns\nh\ni\n.\n \nN\nu\ng\na\nr\nt\ni\nn\n \nl\ni\ns\nh\ni\nn\ng\n \nb\ni\nn\ne\nk\ne\nn\n \nl"
}
