id: "orv_Cyrl"
language: "orv"
script: "Cyrl"
name: "Old Russian, Cyrillic"
region: "RU"
sample_text {
  masthead_full: "ВвЬь"
  masthead_partial: "Сс"
  styles: "Вьси сѧ людиѥ родѧть свободьни и ровьни въ"
  tester: "Вьси сѧ людиѥ родѧть свободьни и ровьни въ чьсти та въ правьдѣ."
  poster_sm: "Вьси сѧ людиѥ"
  poster_md: "Вьси"
  poster_lg: "Вьси"
  specimen_48: "Вьси сѧ людиѥ родѧть свободьни и ровьни въ чьсти та въ правьдѣ. Одарєни"
  specimen_36: "Вьси сѧ людиѥ родѧть свободьни и ровьни въ чьсти та въ правьдѣ. Одарєни сѫть роз​оумомь и доушєѭ, и дѣıати имъ къ собѣ ıако мєжю братъı."
  specimen_32: "Вьси сѧ людиѥ родѧть свободьни и ровьни въ чьсти та въ правьдѣ. Одарєни сѫть роз​оумомь и доушєѭ, и дѣıати имъ къ собѣ ıако мєжю братъı."
  specimen_21: "Вьси сѧ людиѥ родѧть свободьни и ровьни въ чьсти та въ правьдѣ. Одарєни сѫть роз​оумомь и доушєѭ, и дѣıати имъ къ собѣ ıако мєжю братъı.\nВьси сѧ людиѥ родѧть свободьни и ровьни въ чьсти та въ правьдѣ. Одарєни сѫть роз​оумомь и доушєѭ, и дѣıати имъ къ собѣ ıако мєжю братъı.\nВьси сѧ людиѥ родѧть свободьни и ровьни въ чьсти та въ правьдѣ. Одарєни сѫть роз​оумомь и доушєѭ, и дѣıати имъ къ собѣ ıако мєжю братъı."
  specimen_16: "Вьси сѧ людиѥ родѧть свободьни и ровьни въ чьсти та въ правьдѣ. Одарєни сѫть роз​оумомь и доушєѭ, и дѣıати имъ къ собѣ ıако мєжю братъı.\nВьси сѧ людиѥ родѧть свободьни и ровьни въ чьсти та въ правьдѣ. Одарєни сѫть роз​оумомь и доушєѭ, и дѣıати имъ къ собѣ ıако мєжю братъı.\nВьси сѧ людиѥ родѧть свободьни и ровьни въ чьсти та въ правьдѣ. Одарєни сѫть роз​оумомь и доушєѭ, и дѣıати имъ къ собѣ ıако мєжю братъı.\nВьси сѧ людиѥ родѧть свободьни и ровьни въ чьсти та въ правьдѣ. Одарєни сѫть роз​оумомь и доушєѭ, и дѣıати имъ къ собѣ ıако мєжю братъı.\nВьси сѧ людиѥ родѧть свободьни и ровьни въ чьсти та въ правьдѣ. Одарєни сѫть роз​оумомь и доушєѭ, и дѣıати имъ къ собѣ ıако мєжю братъı."
}
