id: "orv_Cyrl"
language: "orv"
script: "Cyrl"
name: "Old Russian, Cyrillic"
sample_text {
  masthead_full: "ВвЬь"
  masthead_partial: "Сс"
  styles: "В\nь\nс\nи\n \nс\nѧ\n \nл\nю\nд\nи\nѥ\n \nр\nо\nд\nѧ\nт\nь\n "
  tester: "В\nь\nс\nи\n \nс\nѧ\n \nл\nю\nд\nи\nѥ\n \nр\nо\nд\nѧ\nт\nь\n \nс\nв\nо\nб\nо\nд\nь\nн\nи\n "
  poster_sm: "В\nь\nс\nи\n \nс"
  poster_md: "В\nь\nс\nи\n "
  poster_lg: "В\nь"
  specimen_48: "В\nь\nс\nи\n \nс\nѧ\n \nл\nю\nд\nи\nѥ\n \nр\nо\nд\nѧ\nт\nь\n \nс\nв\nо\nб\nо\nд\nь\nн\nи\n "
  specimen_36: "В\nь\nс\nи\n \nс\nѧ\n \nл\nю\nд\nи\nѥ\n \nр\nо\nд\nѧ\nт\nь\n \nс\nв\nо\nб\nо\nд\nь\nн\nи\n \nи\n \nр\nо\nв\nь\nн\nи\n \nв\nъ\n \nч\nь\nс\nт\nи\n \nт\nа"
  specimen_32: "В\nь\nс\nи\n \nс\nѧ\n \nл\nю\nд\nи\nѥ\n \nр\nо\nд\nѧ\nт\nь\n \nс\nв\nо\nб\nо\nд\nь\nн\nи\n \nи\n \nр\nо\nв\nь\nн\nи\n \nв\nъ\n \nч\nь\nс\nт\nи\n \nт\nа\n \nв\nъ\n \nп\nр\nа\nв\nь\nд\nѣ\n.\n \nО\nд\nа\nр\nє\nн\nи"
  specimen_21: "В\nь\nс\nи\n \nс\nѧ\n \nл\nю\nд\nи\nѥ\n \nр\nо\nд\nѧ\nт\nь\n \nс\nв\nо\nб\nо\nд\nь\nн\nи\n \nи\n \nр\nо\nв\nь\nн\nи\n \nв\nъ\n \nч\nь\nс\nт\nи\n \nт\nа\n \nв\nъ\n \nп\nр\nа\nв\nь\nд\nѣ\n.\n \nО\nд\nа\nр\nє\nн\nи\n \nс\nѫ\nт\nь\n \nр\nо\nз\n​\nо\nу\nм\nо\nм\nь\n \nи\n \nд\nо\nу\nш\nє\nѭ\n,\n \nи\n \nд\nѣ\nı\nа\nт\nи\n \nи\nм\nъ\n \nк\nъ\n \nс\nо\nб\nѣ\n \nı\nа\nк\nо\n \nм\nє\nж\nю\n \nб\nр\nа\nт\nъ\nı\n.\nВ\nь\nс\nи\n \nс\nѧ\n \nл\nю\nд\nи\nѥ\n \nр\nо\nд"
  specimen_16: "В\nь\nс\nи\n \nс\nѧ\n \nл\nю\nд\nи\nѥ\n \nр\nо\nд\nѧ\nт\nь\n \nс\nв\nо\nб\nо\nд\nь\nн\nи\n \nи\n \nр\nо\nв\nь\nн\nи\n \nв\nъ\n \nч\nь\nс\nт\nи\n \nт\nа\n \nв\nъ\n \nп\nр\nа\nв\nь\nд\nѣ\n.\n \nО\nд\nа\nр\nє\nн\nи\n \nс\nѫ\nт\nь\n \nр\nо\nз\n​\nо\nу\nм\nо\nм\nь\n \nи\n \nд\nо\nу\nш\nє\nѭ\n,\n \nи\n \nд\nѣ\nı\nа\nт\nи\n \nи\nм\nъ\n \nк\nъ\n \nс\nо\nб\nѣ\n \nı\nа\nк\nо\n \nм\nє\nж\nю\n \nб\nр\nа\nт\nъ\nı\n.\nВ\nь\nс\nи\n \nс\nѧ\n \nл\nю\nд\nи\nѥ\n \nр\nо\nд\nѧ\nт\nь\n \nс\nв\nо\nб\nо\nд\nь\nн\nи\n \nи\n \nр\nо\nв\nь\nн\nи\n \nв\nъ\n \nч\nь\nс\nт\nи\n \nт\nа\n \nв\nъ\n \nп\nр\nа\nв\nь\nд\nѣ\n.\n \nО\nд\nа\nр\nє\nн\nи\n \nс\nѫ\nт\nь\n \nр\nо\nз\n​\nо\nу\nм\nо\nм\nь\n \nи\n \nд\nо\nу\nш\nє\nѭ\n,\n \nи\n \nд\nѣ\nı\nа\nт\nи\n \nи\nм\nъ\n \nк\nъ\n \nс\nо\nб\nѣ\n \nı\nа\nк\nо\n \nм\nє\nж\nю\n \nб\nр\nа\nт\nъ\nı\n.\nВ\nь\nс\nи\n \nс\nѧ\n "
}
