id: "os"
language: "os"
script: "Cyrl"
name: "Ossetic"
autonym: "Ирон"
population: 616987
region: "GE"
region: "RU"
exemplar_chars {
  base: "а ӕ б в г {гъ} д {дж} {дз} е ё ж з и й к {къ} л м н о п {пъ} р с т {тъ} у ф х {хъ} ц {цъ} ч {чъ} ш щ ъ ы ь э ю я {гъ} {дж} {дз} {къ} {пъ} {тъ} {хъ} {цъ} {чъ} {гъ} {дж} {дз} {къ} {пъ} {тъ} {хъ} {цъ} {чъ} {гъ} {дж} {дз} {къ} {пъ} {тъ} {хъ} {цъ} {чъ} {гъ} {дж} {дз} {къ} {пъ} {тъ} {хъ} {цъ} {чъ} {гъ} {дж} {дз} {къ} {пъ} {тъ} {хъ} {цъ} {чъ} {гъ} {дж} {дз} {къ} {пъ} {тъ} {хъ} {цъ} {чъ} {гъ} {дж} {дз} {къ} {пъ} {тъ} {хъ} {цъ} {чъ} {гъ} {дж} {дз} {къ} {пъ} {тъ} {хъ} {цъ} {чъ} {гъ} {дж} {дз} {къ} {пъ} {тъ} {хъ} {цъ} {чъ} {гъ} {дж} {дз} {къ} {пъ} {тъ} {хъ} {цъ} {чъ} {гъ} {дж} {дз} {къ} {пъ} {тъ} {хъ} {цъ} {чъ} {гъ} {дж} {дз} {къ} {пъ} {тъ} {хъ} {цъ} {чъ} {гъ} {дж} {дз} {къ} {пъ} {тъ} {хъ} {цъ} {чъ} {гъ} {дж} {дз} {къ} {пъ} {тъ} {хъ} {цъ} {чъ} {гъ} {дж} {дз} {къ} {пъ} {тъ} {хъ} {цъ} {чъ}"
  auxiliary: ""
  marks: "◌̆ ◌̈"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ‚ \" “ „ « » ( ) [ ] { } § @ * / & # { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "А Ӕ Б В Г {Гъ} Д {Дж} {Дз} Е Ё Ж З И Й К {Къ} Л М Н О П {Пъ} Р С Т {Тъ} У Ф Х {Хъ} Ц {Цъ} Ч {Чъ} Ш Щ Ы Э Ю Я {Гъ} {Дж} {Дз} {Къ} {Пъ} {Тъ} {Хъ} {Цъ} {Чъ} {Гъ} {Дж} {Дз} {Къ} {Пъ} {Тъ} {Хъ} {Цъ} {Чъ} {Гъ} {Дж} {Дз} {Къ} {Пъ} {Тъ} {Хъ} {Цъ} {Чъ} {Гъ} {Дж} {Дз} {Къ} {Пъ} {Тъ} {Хъ} {Цъ} {Чъ} {Гъ} {Дж} {Дз} {Къ} {Пъ} {Тъ} {Хъ} {Цъ} {Чъ} {Гъ} {Дж} {Дз} {Къ} {Пъ} {Тъ} {Хъ} {Цъ} {Чъ} {Гъ} {Дж} {Дз} {Къ} {Пъ} {Тъ} {Хъ} {Цъ} {Чъ} {Гъ} {Дж} {Дз} {Къ} {Пъ} {Тъ} {Хъ} {Цъ} {Чъ} {Гъ} {Дж} {Дз} {Къ} {Пъ} {Тъ} {Хъ} {Цъ} {Чъ} {Гъ} {Дж} {Дз} {Къ} {Пъ} {Тъ} {Хъ} {Цъ} {Чъ} {Гъ} {Дж} {Дз} {Къ} {Пъ} {Тъ} {Хъ} {Цъ} {Чъ} {Гъ} {Дж} {Дз} {Къ} {Пъ} {Тъ} {Хъ} {Цъ} {Чъ} {Гъ} {Дж} {Дз} {Къ} {Пъ} {Тъ} {Хъ} {Цъ} {Чъ} {Гъ} {Дж} {Дз} {Къ} {Пъ} {Тъ} {Хъ} {Цъ} {Чъ} {Гъ} {Дж} {Дз} {Къ} {Пъ} {Тъ} {Хъ} {Цъ} {Чъ}"
}
sample_text {
  masthead_full: "АаДд"
  masthead_partial: "Ӕӕ"
  styles: "Нӕй рохуаты уадзӕн ӕппӕт дзыллӕджын бинонты"
  tester: "Адӕймӕгтӕ се \'ппӕт дӕр райгуырынц сӕрибарӕй ӕмӕ ӕмхуызонӕй сӕ"
  poster_sm: "Алы адӕймагӕн"
  poster_md: "Уымӕй уӕлдай,"
  poster_lg: "\'ппӕт"
  specimen_48: "Хъуамӕ мачи уа цагъар ӕмӕ уацары; цагъар ӕмӕ цагъайрӕгты уӕйгӕнынадӕн"
  specimen_36: "Алы адӕймагӕн дӕр ис бар ӕнтысджытӕй йӕ бартӕ бахъахъӕнын тӕрхондоны, уыцы бартӕ йын лӕвӕрд сты закъон ӕмӕ конституцийӕ."
  specimen_32: "Алы адӕймагӕн дӕр ис бар йӕхи хъуыды, намыс ӕмӕ динӕн; ардӕм хауы дин ӕмӕ фӕндтӕ ивыны бар, куыд иунӕгӕй, афтӕ иннӕтимӕ бастӕй динон ӕмӕ ритуалон ӕгъдӕуттӕ ӕххӕстгӕнгӕйӕ."
  specimen_21: "Алы адӕймагӕн дӕр ис йӕхи разӕнгарддзинады бар ӕмӕ сӕ сӕрибарӕй равдисын дӕр; ацы бармӕ хауы хи разӕнгарддзинадыл хӕцын ӕмӕ хибарӕй агурын, исын ӕмӕ парахат кӕнын информаци ӕмӕ фӕндтӕ цыфӕнды мадзӕлттӕй паддзахадон арӕнтӕй хицӕнӕй.\nАлы адӕймагӕн дӕр, куыд ӕхсӕнады уӕнгӕн, ис бар социалон ӕххуысӕн, стӕй йӕ намысы, хибарӕй рӕзты экономикон ӕмӕ культурон уавӕрты национ, ӕхсӕнадӕмон ӕмӕ алы паддзахады мадзӕлтты ӕххуысы бар."
  specimen_16: "Алы адӕймагӕн дӕр ис бар улӕфынӕн ӕмӕ йӕ рӕстӕг ӕрвитынӕн, уимӕ кусӕн бон ӕмбӕлгӕ къаддӕр кӕнынӕн ӕмӕ фидгӕ ӕрвылазон улӕфӕн рӕстӕгӕн.\nАлы адӕймагӕн дӕр ис бар социалон ӕмӕ ӕхсӕнадӕмон фӕткӕн, кӕцыйы ацы Декларацийы ӕвдыст бартӕ уыдзысты ӕнӕхъӕнӕй ӕххӕстгонд.\nАцы Декларацийы фыст уацтӕ хъуамӕ ма уой ӕмбӕрст куыд лӕвӕрд бартӕ цавӕрдӕр паддзахадӕн, адӕмы къордӕн кӕнӕ хицӕн адӕймӕгтӕн исты архайд аразын, кӕцы цӕуа ацы Декларацийы ӕвдыст барты ныхмӕ.\nАдӕймӕгтӕ се \'ппӕт дӕр райгуырынц сӕрибарӕй ӕмӕ ӕмхуызонӕй сӕ барты. Уыдон ӕххӕст сты зонд ӕмӕ намысӕй, ӕмӕ кӕрӕдзийӕн хъуамӕ уой ӕфсымӕрты хуызӕн."
}
