id: "osc_Ital"
language: "osc"
script: "Ital"
name: "Oscan"
population: 0
sample_text {
  masthead_full: "𐌉𐌆𐌊𐌚"
  masthead_partial: "𐌀𐌍"
  styles: "𐌉𐌆𐌉𐌊 𐌚𐌀𐌍𐌂𐌅𐌀𐌌 𐌁𐌉𐌅𐌖𐌔 𐌀𐌀𐌐𐌀 𐌐𐌀𐌕𐌝𐌓 𐌕𐌓𐌝𐌔 𐌌𐌀𐌉𐌔 𐌔𐌅𐌀𐌝"
  tester: "𐌉𐌆𐌉𐌊 𐌚𐌀𐌍𐌂𐌅𐌀𐌌 𐌁𐌉𐌅𐌖𐌔 𐌀𐌀𐌐𐌀 𐌐𐌀𐌕𐌝𐌓 𐌕𐌓𐌝𐌔 𐌌𐌀𐌉𐌔 𐌔𐌅𐌀𐌝 𐌀𐌍𐌀𐌌𐌞𐌌 𐌀𐌍𐌕𐌄𐌓 𐌐𐌄𐌕𐌖𐌓𐌀"
  poster_sm: "𐌉𐌆𐌉𐌊 𐌚𐌀𐌍𐌂𐌅𐌀𐌌"
  poster_md: "𐌉𐌆𐌉𐌊 𐌚𐌀𐌍𐌂𐌅𐌀𐌌"
  poster_lg: "𐌉𐌆𐌉𐌊"
  specimen_48: "𐌉𐌆𐌉𐌊 𐌚𐌀𐌍𐌂𐌅𐌀𐌌 𐌁𐌉𐌅𐌖𐌔 𐌀𐌀𐌐𐌀 𐌐𐌀𐌕𐌝𐌓 𐌕𐌓𐌝𐌔 𐌌𐌀𐌉𐌔 𐌔𐌅𐌀𐌝 𐌀𐌍𐌀𐌌𐌞𐌌"
  specimen_36: "𐌉𐌆𐌉𐌊 𐌚𐌀𐌍𐌂𐌅𐌀𐌌 𐌁𐌉𐌅𐌖𐌔 𐌀𐌀𐌐𐌀 𐌐𐌀𐌕𐌝𐌓 𐌕𐌓𐌝𐌔 𐌌𐌀𐌉𐌔 𐌔𐌅𐌀𐌝 𐌀𐌍𐌀𐌌𐌞𐌌 𐌀𐌍𐌕𐌄𐌓 𐌐𐌄𐌕𐌖𐌓𐌀 𐌖𐌉𐌍𐌖𐌔 𐌍𐌉𐌉𐌓 𐌝𐌃𐌉𐌊 𐌚𐌖𐌕𐌝𐌓 𐌃𐌖𐌍𐌕𐌄 𐌀𐌊𐌓𐌉 𐌁𐌉𐌉𐌕𐌀𐌌 𐌍𐌞 𐌃𐌄𐌃𐌄𐌃 𐌃𐌄𐌝𐌊𐌖𐌌 𐌐𐌄𐌕𐌕𐌉𐌖𐌓 𐌃𐌖𐌔 "
  specimen_32: "𐌉𐌆𐌉𐌊 𐌚𐌀𐌍𐌂𐌅𐌀𐌌 𐌁𐌉𐌅𐌖𐌔 𐌀𐌀𐌐𐌀 𐌐𐌀𐌕𐌝𐌓 𐌕𐌓𐌝𐌔 𐌌𐌀𐌉𐌔 𐌔𐌅𐌀𐌝 𐌀𐌍𐌀𐌌𐌞𐌌 𐌀𐌍𐌕𐌄𐌓 𐌐𐌄𐌕𐌖𐌓𐌀 𐌖𐌉𐌍𐌖𐌔 𐌍𐌉𐌉𐌓 𐌝𐌃𐌉𐌊 𐌚𐌖𐌕𐌝𐌓 𐌃𐌖𐌍𐌕𐌄 𐌀𐌊𐌓𐌉 𐌁𐌉𐌉𐌕𐌀𐌌 𐌍𐌞 𐌃𐌄𐌃𐌄𐌃 𐌃𐌄𐌝𐌊𐌖𐌌 𐌐𐌄𐌕𐌕𐌉𐌖𐌓 𐌃𐌖𐌔 "
  specimen_21: "𐌉𐌆𐌉𐌊 𐌚𐌀𐌍𐌂𐌅𐌀𐌌 𐌁𐌉𐌅𐌖𐌔 𐌀𐌀𐌐𐌀 𐌐𐌀𐌕𐌝𐌓 𐌕𐌓𐌝𐌔 𐌌𐌀𐌉𐌔 𐌔𐌅𐌀𐌝 𐌀𐌍𐌀𐌌𐌞𐌌 𐌀𐌍𐌕𐌄𐌓 𐌐𐌄𐌕𐌖𐌓𐌀 𐌖𐌉𐌍𐌖𐌔 𐌍𐌉𐌉𐌓 𐌝𐌃𐌉𐌊 𐌚𐌖𐌕𐌝𐌓 𐌃𐌖𐌍𐌕𐌄 𐌀𐌊𐌓𐌉 𐌁𐌉𐌉𐌕𐌀𐌌 𐌍𐌞 𐌃𐌄𐌃𐌄𐌃 𐌃𐌄𐌝𐌊𐌖𐌌 𐌐𐌄𐌕𐌕𐌉𐌖𐌓 𐌃𐌖𐌔 \n𐌉𐌆𐌉𐌊 𐌚𐌀𐌍𐌂𐌅𐌀𐌌 𐌁𐌉𐌅𐌖𐌔 𐌀𐌀𐌐𐌀 𐌐𐌀𐌕𐌝𐌓 𐌕𐌓𐌝𐌔 𐌌𐌀𐌉𐌔 𐌔𐌅𐌀𐌝 𐌀𐌍𐌀𐌌𐌞𐌌 𐌀𐌍𐌕𐌄𐌓 𐌐𐌄𐌕𐌖𐌓𐌀 𐌖𐌉𐌍𐌖𐌔 𐌍𐌉𐌉𐌓 𐌝𐌃𐌉𐌊 𐌚𐌖𐌕𐌝𐌓 𐌃𐌖𐌍𐌕𐌄 𐌀𐌊𐌓𐌉 𐌁𐌉𐌉𐌕𐌀𐌌 𐌍𐌞 𐌃𐌄𐌃𐌄𐌃 𐌃𐌄𐌝𐌊𐌖𐌌 𐌐𐌄𐌕𐌕𐌉𐌖𐌓 𐌃𐌖𐌔 \n𐌉𐌆𐌉𐌊 𐌚𐌀𐌍𐌂𐌅𐌀𐌌 𐌁𐌉𐌅𐌖𐌔 𐌀𐌀𐌐𐌀 𐌐𐌀𐌕𐌝𐌓 𐌕𐌓𐌝𐌔 𐌌𐌀𐌉𐌔 𐌔𐌅𐌀𐌝 𐌀𐌍𐌀𐌌𐌞𐌌 𐌀𐌍𐌕𐌄𐌓 𐌐𐌄𐌕𐌖𐌓𐌀 𐌖𐌉𐌍𐌖𐌔 𐌍𐌉𐌉𐌓 𐌝𐌃𐌉𐌊 𐌚𐌖𐌕𐌝𐌓 𐌃𐌖𐌍𐌕𐌄 𐌀𐌊𐌓𐌉 𐌁𐌉𐌉𐌕𐌀𐌌 𐌍𐌞 𐌃𐌄𐌃𐌄𐌃 𐌃𐌄𐌝𐌊𐌖𐌌 𐌐𐌄𐌕𐌕𐌉𐌖𐌓 𐌃𐌖𐌔 "
  specimen_16: "𐌉𐌆𐌉𐌊 𐌚𐌀𐌍𐌂𐌅𐌀𐌌 𐌁𐌉𐌅𐌖𐌔 𐌀𐌀𐌐𐌀 𐌐𐌀𐌕𐌝𐌓 𐌕𐌓𐌝𐌔 𐌌𐌀𐌉𐌔 𐌔𐌅𐌀𐌝 𐌀𐌍𐌀𐌌𐌞𐌌 𐌀𐌍𐌕𐌄𐌓 𐌐𐌄𐌕𐌖𐌓𐌀 𐌖𐌉𐌍𐌖𐌔 𐌍𐌉𐌉𐌓 𐌝𐌃𐌉𐌊 𐌚𐌖𐌕𐌝𐌓 𐌃𐌖𐌍𐌕𐌄 𐌀𐌊𐌓𐌉 𐌁𐌉𐌉𐌕𐌀𐌌 𐌍𐌞 𐌃𐌄𐌃𐌄𐌃 𐌃𐌄𐌝𐌊𐌖𐌌 𐌐𐌄𐌕𐌕𐌉𐌖𐌓 𐌃𐌖𐌔 \n𐌉𐌆𐌉𐌊 𐌚𐌀𐌍𐌂𐌅𐌀𐌌 𐌁𐌉𐌅𐌖𐌔 𐌀𐌀𐌐𐌀 𐌐𐌀𐌕𐌝𐌓 𐌕𐌓𐌝𐌔 𐌌𐌀𐌉𐌔 𐌔𐌅𐌀𐌝 𐌀𐌍𐌀𐌌𐌞𐌌 𐌀𐌍𐌕𐌄𐌓 𐌐𐌄𐌕𐌖𐌓𐌀 𐌖𐌉𐌍𐌖𐌔 𐌍𐌉𐌉𐌓 𐌝𐌃𐌉𐌊 𐌚𐌖𐌕𐌝𐌓 𐌃𐌖𐌍𐌕𐌄 𐌀𐌊𐌓𐌉 𐌁𐌉𐌉𐌕𐌀𐌌 𐌍𐌞 𐌃𐌄𐌃𐌄𐌃 𐌃𐌄𐌝𐌊𐌖𐌌 𐌐𐌄𐌕𐌕𐌉𐌖𐌓 𐌃𐌖𐌔 \n𐌉𐌆𐌉𐌊 𐌚𐌀𐌍𐌂𐌅𐌀𐌌 𐌁𐌉𐌅𐌖𐌔 𐌀𐌀𐌐𐌀 𐌐𐌀𐌕𐌝𐌓 𐌕𐌓𐌝𐌔 𐌌𐌀𐌉𐌔 𐌔𐌅𐌀𐌝 𐌀𐌍𐌀𐌌𐌞𐌌 𐌀𐌍𐌕𐌄𐌓 𐌐𐌄𐌕𐌖𐌓𐌀 𐌖𐌉𐌍𐌖𐌔 𐌍𐌉𐌉𐌓 𐌝𐌃𐌉𐌊 𐌚𐌖𐌕𐌝𐌓 𐌃𐌖𐌍𐌕𐌄 𐌀𐌊𐌓𐌉 𐌁𐌉𐌉𐌕𐌀𐌌 𐌍𐌞 𐌃𐌄𐌃𐌄𐌃 𐌃𐌄𐌝𐌊𐌖𐌌 𐌐𐌄𐌕𐌕𐌉𐌖𐌓 𐌃𐌖𐌔 \n𐌉𐌆𐌉𐌊 𐌚𐌀𐌍𐌂𐌅𐌀𐌌 𐌁𐌉𐌅𐌖𐌔 𐌀𐌀𐌐𐌀 𐌐𐌀𐌕𐌝𐌓 𐌕𐌓𐌝𐌔 𐌌𐌀𐌉𐌔 𐌔𐌅𐌀𐌝 𐌀𐌍𐌀𐌌𐌞𐌌 𐌀𐌍𐌕𐌄𐌓 𐌐𐌄𐌕𐌖𐌓𐌀 𐌖𐌉𐌍𐌖𐌔 𐌍𐌉𐌉𐌓 𐌝𐌃𐌉𐌊 𐌚𐌖𐌕𐌝𐌓 𐌃𐌖𐌍𐌕𐌄 𐌀𐌊𐌓𐌉 𐌁𐌉𐌉𐌕𐌀𐌌 𐌍𐌞 𐌃𐌄𐌃𐌄𐌃 𐌃𐌄𐌝𐌊𐌖𐌌 𐌐𐌄𐌕𐌕𐌉𐌖𐌓 𐌃𐌖𐌔 \n𐌉𐌆𐌉𐌊 𐌚𐌀𐌍𐌂𐌅𐌀𐌌 𐌁𐌉𐌅𐌖𐌔 𐌀𐌀𐌐𐌀 𐌐𐌀𐌕𐌝𐌓 𐌕𐌓𐌝𐌔 𐌌𐌀𐌉𐌔 𐌔𐌅𐌀𐌝 𐌀𐌍𐌀𐌌𐌞𐌌 𐌀𐌍𐌕𐌄𐌓 𐌐𐌄𐌕𐌖𐌓𐌀 𐌖𐌉𐌍𐌖𐌔 𐌍𐌉𐌉𐌓 𐌝𐌃𐌉𐌊 𐌚𐌖𐌕𐌝𐌓 𐌃𐌖𐌍𐌕𐌄 𐌀𐌊𐌓𐌉 𐌁𐌉𐌉𐌕𐌀𐌌 𐌍𐌞 𐌃𐌄𐌃𐌄𐌃 𐌃𐌄𐌝𐌊𐌖𐌌 𐌐𐌄𐌕𐌕𐌉𐌖𐌓 𐌃𐌖𐌔 "
}
historical: true
