id: "ota_Arab"
language: "ota"
script: "Arab"
name: "Ottoman Turkish, Arabic"
sample_text {
  masthead_full: "بتون"
  masthead_partial: "اس"
  styles: "ب\nت\nو\nن\n \nا\nن\nس\nا\nن\nل\nر\n \nح\nر\n،\n \nح\nي\nش\nي"
  tester: "ب\nت\nو\nن\n \nا\nن\nس\nا\nن\nل\nر\n \nح\nر\n،\n \nح\nي\nش\nي\nت\n \nو\n \nح\nق\nل\nر\n \nب"
  poster_sm: "ب\nت\nو\nن\n \nا"
  poster_md: "ب\nت\nو\nن\n "
  poster_lg: "ب\nت"
  specimen_48: "ب\nت\nو\nن\n \nا\nن\nس\nا\nن\nل\nر\n \nح\nر\n،\n \nح\nي\nش\nي\nت\n \nو\n \nح\nق\nل\nر\n \nب"
  specimen_36: "ب\nت\nو\nن\n \nا\nن\nس\nا\nن\nل\nر\n \nح\nر\n،\n \nح\nي\nش\nي\nت\n \nو\n \nح\nق\nل\nر\n \nب\nا\nق\nم\nڭ\nد\nن\n \nا\nش\nت\n \nط\nو\nغ\nر\nل\nر\n.\n \nع\nق"
  specimen_32: "ب\nت\nو\nن\n \nا\nن\nس\nا\nن\nل\nر\n \nح\nر\n،\n \nح\nي\nش\nي\nت\n \nو\n \nح\nق\nل\nر\n \nب\nا\nق\nم\nڭ\nد\nن\n \nا\nش\nت\n \nط\nو\nغ\nر\nل\nر\n.\n \nع\nق\nل\n \nو\n \nو\nج\nد\nا\nن\nه\n \nص\nح\nب\nت\nر\nل\nر\n \nو"
  specimen_21: "ب\nت\nو\nن\n \nا\nن\nس\nا\nن\nل\nر\n \nح\nر\n،\n \nح\nي\nش\nي\nت\n \nو\n \nح\nق\nل\nر\n \nب\nا\nق\nم\nڭ\nد\nن\n \nا\nش\nت\n \nط\nو\nغ\nر\nل\nر\n.\n \nع\nق\nل\n \nو\n \nو\nج\nد\nا\nن\nه\n \nص\nح\nب\nت\nر\nل\nر\n \nو\n \nب\nر\nب\nر\nل\nر\nي\nن\nه\n \nق\nا\nر\nش\nو\n \nق\nر\nد\nا\nش\nل\nق\n \nذ\nه\nن\nي\nت\n \nا\nي\nل\nه\n \nح\nر\nك\nت\n \nا\nت\nم\nه\nل\nو\nد\nر\nل\nر\n.\nب\nت\nو\nن\n \nا\nن\nس\nا\nن\nل\nر\n \nح\nر\n،\n \nح\nي\nش\nي\nت\n \nو\n \nح\nق\nل\nر"
  specimen_16: "ب\nت\nو\nن\n \nا\nن\nس\nا\nن\nل\nر\n \nح\nر\n،\n \nح\nي\nش\nي\nت\n \nو\n \nح\nق\nل\nر\n \nب\nا\nق\nم\nڭ\nد\nن\n \nا\nش\nت\n \nط\nو\nغ\nر\nل\nر\n.\n \nع\nق\nل\n \nو\n \nو\nج\nد\nا\nن\nه\n \nص\nح\nب\nت\nر\nل\nر\n \nو\n \nب\nر\nب\nر\nل\nر\nي\nن\nه\n \nق\nا\nر\nش\nو\n \nق\nر\nد\nا\nش\nل\nق\n \nذ\nه\nن\nي\nت\n \nا\nي\nل\nه\n \nح\nر\nك\nت\n \nا\nت\nم\nه\nل\nو\nد\nر\nل\nر\n.\nب\nت\nو\nن\n \nا\nن\nس\nا\nن\nل\nر\n \nح\nر\n،\n \nح\nي\nش\nي\nت\n \nو\n \nح\nق\nل\nر\n \nب\nا\nق\nم\nڭ\nد\nن\n \nا\nش\nت\n \nط\nو\nغ\nر\nل\nر\n.\n \nع\nق\nل\n \nو\n \nو\nج\nد\nا\nن\nه\n \nص\nح\nب\nت\nر\nل\nر\n \nو\n \nب\nر\nب\nر\nل\nر\nي\nن\nه\n \nق\nا\nر\nش\nو\n \nق\nر\nد\nا\nش\nل\nق\n \nذ\nه\nن\nي\nت\n \nا\nي\nل\nه\n \nح\nر\nك\nت\n \nا\nت\nم\nه\nل\nو\nد\nر\nل\nر\n.\nب\nت\nو\nن\n \nا\nن\nس\nا\nن\nل\nر\n \nح\nر\n،\n \nح\nي\nش\nي\nت\n \nو\n \nح\nق\nل\nر\n \nب"
}
