id: "otn_Latn"
language: "otn"
script: "Latn"
name: "Tenango Otomi, Latin"
sample_text {
  masthead_full: "GgOo"
  masthead_partial: "Tt"
  styles: "G\no\nt\nh\no\n \nn\nu\n \nk\nj\na\n\'\nn\ni\n \ni\n \nm\nu\ni"
  tester: "G\no\nt\nh\no\n \nn\nu\n \nk\nj\na\n\'\nn\ni\n \ni\n \nm\nu\ni\n \nr\na\n \nz\no\no\n \ni\n "
  poster_sm: "G\no\nt\nh\no\n "
  poster_md: "G\no\nt\nh\no"
  poster_lg: "G\no"
  specimen_48: "G\no\nt\nh\no\n \nn\nu\n \nk\nj\na\n\'\nn\ni\n \ni\n \nm\nu\ni\n \nr\na\n \nz\no\no\n \ni\n "
  specimen_36: "G\no\nt\nh\no\n \nn\nu\n \nk\nj\na\n\'\nn\ni\n \ni\n \nm\nu\ni\n \nr\na\n \nz\no\no\n \ni\n \ng\no\nt\nh\no\n \nr\no\n \nk\nu\nc\nh\nt\ni\n,\n \ni\n \nt\nu"
  specimen_32: "G\no\nt\nh\no\n \nn\nu\n \nk\nj\na\n\'\nn\ni\n \ni\n \nm\nu\ni\n \nr\na\n \nz\no\no\n \ni\n \ng\no\nt\nh\no\n \nr\no\n \nk\nu\nc\nh\nt\ni\n,\n \ni\n \nt\nu\n\'\nn\ni\n \nn\nu\n \nr\no\n \nñ\na\n \np\na\nd\nä\n \nb\ni"
  specimen_21: "G\no\nt\nh\no\n \nn\nu\n \nk\nj\na\n\'\nn\ni\n \ni\n \nm\nu\ni\n \nr\na\n \nz\no\no\n \ni\n \ng\no\nt\nh\no\n \nr\no\n \nk\nu\nc\nh\nt\ni\n,\n \ni\n \nt\nu\n\'\nn\ni\n \nn\nu\n \nr\no\n \nñ\na\n \np\na\nd\nä\n \nb\ni\nn\ni\n \ni\n \nd\na\n \nb\nu\nd\ni\n,\n \nd\na\n \nm\nu\ni\n \nr\na\n \nz\no\no\n \nk\no\ny\nu\n \ng\no\nt\nh\no\n \ny\nu\n \nk\nj\na\n\'\nn\ni\n \ni\n \ny\no\n \nk\nu\na\nd\ni\n.\nG\no\nt\nh\no\n \nn\nu\n \nk\nj\na\n\'\nn\ni\n \ni\n \nm\nu\ni\n "
  specimen_16: "G\no\nt\nh\no\n \nn\nu\n \nk\nj\na\n\'\nn\ni\n \ni\n \nm\nu\ni\n \nr\na\n \nz\no\no\n \ni\n \ng\no\nt\nh\no\n \nr\no\n \nk\nu\nc\nh\nt\ni\n,\n \ni\n \nt\nu\n\'\nn\ni\n \nn\nu\n \nr\no\n \nñ\na\n \np\na\nd\nä\n \nb\ni\nn\ni\n \ni\n \nd\na\n \nb\nu\nd\ni\n,\n \nd\na\n \nm\nu\ni\n \nr\na\n \nz\no\no\n \nk\no\ny\nu\n \ng\no\nt\nh\no\n \ny\nu\n \nk\nj\na\n\'\nn\ni\n \ni\n \ny\no\n \nk\nu\na\nd\ni\n.\nG\no\nt\nh\no\n \nn\nu\n \nk\nj\na\n\'\nn\ni\n \ni\n \nm\nu\ni\n \nr\na\n \nz\no\no\n \ni\n \ng\no\nt\nh\no\n \nr\no\n \nk\nu\nc\nh\nt\ni\n,\n \ni\n \nt\nu\n\'\nn\ni\n \nn\nu\n \nr\no\n \nñ\na\n \np\na\nd\nä\n \nb\ni\nn\ni\n \ni\n \nd\na\n \nb\nu\nd\ni\n,\n \nd\na\n \nm\nu\ni\n \nr\na\n \nz\no\no\n \nk\no\ny\nu\n \ng\no\nt\nh\no\n \ny\nu\n \nk\nj\na\n\'\nn\ni\n \ni\n \ny\no\n \nk\nu\na\nd\ni\n.\nG\no\nt\nh\no\n \nn\nu\n \nk\nj\na\n\'\nn\ni\n \ni\n "
}
