id: "owl_Latn"
language: "owl"
script: "Latn"
name: "Old Welsh, Latin"
region: "GB"
sample_text {
  masthead_full: "GgEe"
  masthead_partial: "Nn"
  styles: "Genir pawb yn rugyl ac yn gydrad mewn urddas"
  tester: "Genir pawb yn rugyl ac yn gydrad mewn urddas a chyfraith. Mae"
  poster_sm: "Genir pawb"
  poster_md: "Genir"
  poster_lg: "Genir"
  specimen_48: "Genir pawb yn rugyl ac yn gydrad mewn urddas a chyfraith. Mae gaddynt"
  specimen_36: "Genir pawb yn rugyl ac yn gydrad mewn urddas a chyfraith. Mae gaddynt amgnaubot a dylyant ymddwyn y naill at y llall fel brodyr."
  specimen_32: "Genir pawb yn rugyl ac yn gydrad mewn urddas a chyfraith. Mae gaddynt amgnaubot a dylyant ymddwyn y naill at y llall fel brodyr."
  specimen_21: "Genir pawb yn rugyl ac yn gydrad mewn urddas a chyfraith. Mae gaddynt amgnaubot a dylyant ymddwyn y naill at y llall fel brodyr.\nGenir pawb yn rugyl ac yn gydrad mewn urddas a chyfraith. Mae gaddynt amgnaubot a dylyant ymddwyn y naill at y llall fel brodyr.\nGenir pawb yn rugyl ac yn gydrad mewn urddas a chyfraith. Mae gaddynt amgnaubot a dylyant ymddwyn y naill at y llall fel brodyr."
  specimen_16: "Genir pawb yn rugyl ac yn gydrad mewn urddas a chyfraith. Mae gaddynt amgnaubot a dylyant ymddwyn y naill at y llall fel brodyr.\nGenir pawb yn rugyl ac yn gydrad mewn urddas a chyfraith. Mae gaddynt amgnaubot a dylyant ymddwyn y naill at y llall fel brodyr.\nGenir pawb yn rugyl ac yn gydrad mewn urddas a chyfraith. Mae gaddynt amgnaubot a dylyant ymddwyn y naill at y llall fel brodyr.\nGenir pawb yn rugyl ac yn gydrad mewn urddas a chyfraith. Mae gaddynt amgnaubot a dylyant ymddwyn y naill at y llall fel brodyr.\nGenir pawb yn rugyl ac yn gydrad mewn urddas a chyfraith. Mae gaddynt amgnaubot a dylyant ymddwyn y naill at y llall fel brodyr."
}
