id: "pa_Arab"
name: "Punjabi (Arabic)"
preferred_name: ""
autonym: ""
population: 163450700
region: "PK"
script: "Gurmukhi"
script: "Perso-Arabic"
exemplar_chars {
  base: "\\u064F ء آ ؤ ئ ا ب پ ت ث ٹ ج چ ح خ د ذ ڈ ر ز ڑ ژ س ش ص ض ط ظ ع غ ف ق ک گ ل م ن ں ه ھ ہ و ی ے"
  auxiliary: "\\u200E\\u200F أ ٻ ة ٺ ټ ٽ"
  numerals: "\\u200E \\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "ء آ ؤ ئ ا ب پ ت ث ٹ ج چ ح خ د ذ ڈ ر ز ڑ ژ س ش ص ض ط ظ ع غ ف ق ک گ ل م ن ں ه ھ ہ و ی ے"
}
sample_text {
  fallback_language: "pa_Arab"
}
