id: "pis_Latn"
language: "pis"
script: "Latn"
name: "Pijin"
sample_text {
  masthead_full: "EeVv"
  masthead_partial: "Rr"
  styles: "E\nv\nr\ni\n \nm\na\nn\n \ne\nn\n \nm\ne\nr\ne\n \no\nl\nk\ne"
  tester: "E\nv\nr\ni\n \nm\na\nn\n \ne\nn\n \nm\ne\nr\ne\n \no\nl\nk\ne\nt\na\n \nb\no\nr\nn\n \nf\nr"
  poster_sm: "E\nv\nr\ni\n \nm"
  poster_md: "E\nv\nr\ni\n "
  poster_lg: "E\nv"
  specimen_48: "E\nv\nr\ni\n \nm\na\nn\n \ne\nn\n \nm\ne\nr\ne\n \no\nl\nk\ne\nt\na\n \nb\no\nr\nn\n \nf\nr"
  specimen_36: "E\nv\nr\ni\n \nm\na\nn\n \ne\nn\n \nm\ne\nr\ne\n \no\nl\nk\ne\nt\na\n \nb\no\nr\nn\n \nf\nr\ni\ni\n \ne\nn\n \ni\nk\nw\no\nl\n \nl\no\n \nd\ni\ng\nn\ni"
  specimen_32: "E\nv\nr\ni\n \nm\na\nn\n \ne\nn\n \nm\ne\nr\ne\n \no\nl\nk\ne\nt\na\n \nb\no\nr\nn\n \nf\nr\ni\ni\n \ne\nn\n \ni\nk\nw\no\nl\n \nl\no\n \nd\ni\ng\nn\ni\nt\ni\n \ne\nn\n \nr\na\ni\nt\ns\n \nb\nl\no\n \no\nl\nk\ne"
  specimen_21: "E\nv\nr\ni\n \nm\na\nn\n \ne\nn\n \nm\ne\nr\ne\n \no\nl\nk\ne\nt\na\n \nb\no\nr\nn\n \nf\nr\ni\ni\n \ne\nn\n \ni\nk\nw\no\nl\n \nl\no\n \nd\ni\ng\nn\ni\nt\ni\n \ne\nn\n \nr\na\ni\nt\ns\n \nb\nl\no\n \no\nl\nk\ne\nt\na\n.\n \nO\nl\nk\ne\nt\na\n \ne\nv\nr\ni\nw\na\nn\n \no\nl\nk\ne\nt\na\n \ng\na\nr\ne\nm\n \nm\na\ne\nn\ni\n \nf\no\n \nt\ni\nn\ng\nt\ni\nn\ng\n \ne\nn\n \no\nl\nk\ne\nt\na\n \ns\na\np\no\ns\n \nf\no\n \nt\nr\ne\na\nt\ni\nm\n \ni\ns\na"
  specimen_16: "E\nv\nr\ni\n \nm\na\nn\n \ne\nn\n \nm\ne\nr\ne\n \no\nl\nk\ne\nt\na\n \nb\no\nr\nn\n \nf\nr\ni\ni\n \ne\nn\n \ni\nk\nw\no\nl\n \nl\no\n \nd\ni\ng\nn\ni\nt\ni\n \ne\nn\n \nr\na\ni\nt\ns\n \nb\nl\no\n \no\nl\nk\ne\nt\na\n.\n \nO\nl\nk\ne\nt\na\n \ne\nv\nr\ni\nw\na\nn\n \no\nl\nk\ne\nt\na\n \ng\na\nr\ne\nm\n \nm\na\ne\nn\ni\n \nf\no\n \nt\ni\nn\ng\nt\ni\nn\ng\n \ne\nn\n \no\nl\nk\ne\nt\na\n \ns\na\np\no\ns\n \nf\no\n \nt\nr\ne\na\nt\ni\nm\n \ni\ns\na\nd\na\n \nw\ni\nt\nt\ni\nm\n \ns\np\ni\nr\ni\nt\n \nb\nl\no\n \nb\nr\na\nd\na\nh\no\no\nd\n.\nE\nv\nr\ni\n \nm\na\nn\n \ne\nn\n \nm\ne\nr\ne\n \no\nl\nk\ne\nt\na\n \nb\no\nr\nn\n \nf\nr\ni\ni\n \ne\nn\n \ni\nk\nw\no\nl\n \nl\no\n \nd\ni\ng\nn\ni\nt\ni\n \ne\nn\n \nr\na\ni\nt\ns\n \nb\nl\no\n \no\nl\nk\ne\nt\na\n.\n \nO\nl\nk\ne\nt\na\n \ne\nv\nr\ni\nw\na\nn\n \no\nl\nk\ne\nt"
}
