id: "piu_Latn"
language: "piu"
script: "Latn"
name: "Pintupi-Luritja"
sample_text {
  masthead_full: "NnGg"
  masthead_partial: "Aa"
  styles: "N\ng\na\nn\na\nn\na\n \nm\na\nr\nu\n \nt\nj\nu\nt\na\n,\n \nt"
  tester: "N\ng\na\nn\na\nn\na\n \nm\na\nr\nu\n \nt\nj\nu\nt\na\n,\n \nt\nj\nu\nl\nk\nu\nr\na\n \nt\nj"
  poster_sm: "N\ng\na\nn\na\nn"
  poster_md: "N\ng\na\nn\na"
  poster_lg: "N\ng"
  specimen_48: "N\ng\na\nn\na\nn\na\n \nm\na\nr\nu\n \nt\nj\nu\nt\na\n,\n \nt\nj\nu\nl\nk\nu\nr\na\n \nt\nj"
  specimen_36: "N\ng\na\nn\na\nn\na\n \nm\na\nr\nu\n \nt\nj\nu\nt\na\n,\n \nt\nj\nu\nl\nk\nu\nr\na\n \nt\nj\nu\nt\na\n,\n \nm\na\nn\nt\na\n \ny\nu\nr\nu\nn\ng\nk\na\n \np"
  specimen_32: "N\ng\na\nn\na\nn\na\n \nm\na\nr\nu\n \nt\nj\nu\nt\na\n,\n \nt\nj\nu\nl\nk\nu\nr\na\n \nt\nj\nu\nt\na\n,\n \nm\na\nn\nt\na\n \ny\nu\nr\nu\nn\ng\nk\na\n \np\na\nr\nr\na\nr\ni\n \nn\ny\ni\nn\na\np\na\ny\ni\n \nt\nj\nu"
  specimen_21: "N\ng\na\nn\na\nn\na\n \nm\na\nr\nu\n \nt\nj\nu\nt\na\n,\n \nt\nj\nu\nl\nk\nu\nr\na\n \nt\nj\nu\nt\na\n,\n \nm\na\nn\nt\na\n \ny\nu\nr\nu\nn\ng\nk\na\n \np\na\nr\nr\na\nr\ni\n \nn\ny\ni\nn\na\np\na\ny\ni\n \nt\nj\nu\nt\na\nn\ny\na\n \nl\ni\ni\np\nu\nl\na\nl\na\n \nn\ny\ni\nn\na\nn\ny\ni\n,\n \nn\ng\na\nn\na\nn\na\n \ny\na\nn\na\nn\ng\nu\n \nm\na\nr\nu\n \nt\nj\nu\nt\na\n \nw\ni\ny\na\n \nk\nu\ny\na\nk\nu\ny\na\n.\n \nY\nu\nw\na\nn\nk\na\nr\nr\na\nn\ng\nk"
  specimen_16: "N\ng\na\nn\na\nn\na\n \nm\na\nr\nu\n \nt\nj\nu\nt\na\n,\n \nt\nj\nu\nl\nk\nu\nr\na\n \nt\nj\nu\nt\na\n,\n \nm\na\nn\nt\na\n \ny\nu\nr\nu\nn\ng\nk\na\n \np\na\nr\nr\na\nr\ni\n \nn\ny\ni\nn\na\np\na\ny\ni\n \nt\nj\nu\nt\na\nn\ny\na\n \nl\ni\ni\np\nu\nl\na\nl\na\n \nn\ny\ni\nn\na\nn\ny\ni\n,\n \nn\ng\na\nn\na\nn\na\n \ny\na\nn\na\nn\ng\nu\n \nm\na\nr\nu\n \nt\nj\nu\nt\na\n \nw\ni\ny\na\n \nk\nu\ny\na\nk\nu\ny\na\n.\n \nY\nu\nw\na\nn\nk\na\nr\nr\na\nn\ng\nk\nu\ny\na\n \np\na\nl\ny\na\n \nn\ni\nn\nt\ni\nn\ng\nk\nu\n \nk\nu\nl\ni\nn\ni\n.\n \nT\nj\na\nn\na\ny\na\n \np\na\nl\ny\na\n \nk\nu\nt\nj\nu\np\na\n \nt\nj\nu\nt\na\nk\nu\n \nt\nj\nu\nk\na\nr\nu\nr\nr\nu\n \nn\ny\ni\nn\na\nn\ny\nt\nj\na\nk\nu\n,\n \nw\na\nl\ny\nt\nj\na\n \nt\nj\nu\nt\na\n \nn\ng\nu\nw\na\nn\np\na\n,\n \nm\ni\nn\ng\na\nr\nr\nt\nj\nu\nw\ni\ny\na\n.\n \nT\nj\nu\nn"
}
