id: "ps"
language: "ps"
script: "Arab"
name: "Pashto"
population: 51207631
region: "AE"
region: "AF"
region: "IR"
region: "PK"
exemplar_chars {
  base: "َ ِ ُ ً ٍ ٌ ّ ْ ٔ ٰ آ ا أ ء ب پ ت ټ ث ج ځ چ څ ح خ د ډ ذ ر ړ ز ژ ږ س ش ښ ص ض ط ظ ع غ ف ق ک ګ گ ل م ن ڼ ه ة و ؤ ی ي ې ۍ ئ"
  auxiliary: "‌ ‍ ‎‏ ے"
  numerals: "‎ - ‑ , ٫ ٬ . % ٪ ‰ ؉ + − 0۰ 1۱ 2۲ 3۳ 4۴ 5۵ 6۶ 7۷ 8۸ 9۹"
  punctuation: "، ; : ! ۔ \' ‘ ( ) [ ] { } / { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "آ ا ء ب پ ت ټ ث ج ځ چ څ ح خ د ډ ذ ر ړ ز ژ ږ س ش ښ ص ض ط ظ ع غ ف ق ک ګ ل م ن ڼ ه و ی"
}
sample_text {
  masthead_full: "دبشر"
  masthead_partial: "ټو"
  styles: "څرنګه چې دبشري کورنۍ دټولو غړو ذاتي حېثيت"
  tester: "لکه څنګه چې د بشري حقوق تحقير او د هغو نه پيژندنه په وحشيانه"
  poster_sm: "له هغه ځايه"
  poster_md: "عمومي مجمع،"
  poster_lg: "بشر"
  specimen_48: "د بشر ټول افراد ازاد نړۍ ته راځي او د حيثيت او د حقوقو له پلوه"
  specimen_36: "هر څوک حق لري چې په ټولنه کښې د داسيې نظم غوښتونکي شي چې په دې اعلاميه کښې بيان شوي حقوق او ازادي تأمين کړي۔"
  specimen_32: "له هغه ځايه چې اساساً بايد د بشري حقوقو د قانون په اجرا کولو سره حمايت وشي، چې بشر د وروستې علاج په نوم د ظلم او فشار پر ضد په قيام مجبور نه شي،"
  specimen_21: "څرنګه چې دبشري کورنۍ دټولو غړو ذاتي حېثيت پيثزندنه او دهغوي پر رنګ او انتقال نه منونکي حقوق په نړۍ کښې د ازادۍ ، عدالت او سولې اساس تشکيلوي،\nلکه څنګه چې د بشري حقوق تحقير او د هغو نه پيژندنه په وحشيانه عملونو منجر شوي چې د بشريت روح په ګناه مجبوروي او دهغې نړۍ ظهور يي چې په هغې کښې بشر په بيان او عقيده کښې ازاد اور له ويرې او فقر څخه فارغ وي، د بشر دلوړو آمالو تر سرليک لاندي اعلان کړي دي۔"
  specimen_16: "څرنګه چې دبشري کورنۍ دټولو غړو ذاتي حېثيت پيثزندنه او دهغوي پر رنګ او انتقال نه منونکي حقوق په نړۍ کښې د ازادۍ ، عدالت او سولې اساس تشکيلوي،\nلکه څنګه چې د بشري حقوق تحقير او د هغو نه پيژندنه په وحشيانه عملونو منجر شوي چې د بشريت روح په ګناه مجبوروي او دهغې نړۍ ظهور يي چې په هغې کښې بشر په بيان او عقيده کښې ازاد اور له ويرې او فقر څخه فارغ وي، د بشر دلوړو آمالو تر سرليک لاندي اعلان کړي دي۔\nله هغه ځايه چې اساساً بايد د بشري حقوقو د قانون په اجرا کولو سره حمايت وشي، چې بشر د وروستې علاج په نوم د ظلم او فشار پر ضد په قيام مجبور نه شي،\nله هغه ځايه چې اساساً لازم دي چې د ملتونو تر منځ و دوستانه اړيکو پراختيا بايد تشويق شي،"
}
