id: "pt"
language: "pt"
script: "Latn"
name: "Portuguese"
autonym: "Português"
population: 237135427
region: "AG"
region: "AO"
region: "BR"
region: "CH"
region: "CV"
region: "FR"
region: "GQ"
region: "GW"
region: "LU"
region: "MO"
region: "MZ"
region: "PT"
region: "ST"
region: "TL"
exemplar_chars {
  base: "a á à â ã b c ç d e é ê f g h i í j k l m n o ó ò ô õ p q r s t u ú v w x y z"
  auxiliary: "ª ă å ä ā æ è ĕ ë ē ì ĭ î ï ī ñ º ŏ ö ø ō œ ù ŭ û ü ū ÿ"
  marks: "◌̀ ◌́ ◌̂ ◌̃ ◌̈ ◌̧"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ \" “ ” ( ) [ ] § @ * / & # † ‡ ′ ″"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
}
sample_text {
  fallback_language: "en"
}
