id: "qud_Latn"
language: "qud"
script: "Latn"
name: "Quechua, Unified Quichua, old Hispanic orthography"
region: "PE"
sample_text {
  masthead_full: "TtUu"
  masthead_partial: "Cc"
  styles: "Tucuy runacuna quishpirihuán huiñán, pactacunahuampes,"
  tester: "Tucuy runacuna quishpirihuán huiñán, pactacunahuampes, pay pura,"
  poster_sm: "Tucuy runacuna"
  poster_md: "Tucuy"
  poster_lg: "Tucuy"
  specimen_48: "Tucuy runacuna quishpirihuán huiñán, pactacunahuampes, pay pura, umahuán,"
  specimen_36: "Tucuy runacuna quishpirihuán huiñán, pactacunahuampes, pay pura, umahuán, ayahuán chay shucuna shina, chaymantami shuclla shina causangacuna."
  specimen_32: "Tucuy runacuna quishpirihuán huiñán, pactacunahuampes, pay pura, umahuán, ayahuán chay shucuna shina, chaymantami shuclla shina causangacuna."
  specimen_21: "Tucuy runacuna quishpirihuán huiñán, pactacunahuampes, pay pura, umahuán, ayahuán chay shucuna shina, chaymantami shuclla shina causangacuna.\nTucuy runacuna quishpirihuán huiñán, pactacunahuampes, pay pura, umahuán, ayahuán chay shucuna shina, chaymantami shuclla shina causangacuna.\nTucuy runacuna quishpirihuán huiñán, pactacunahuampes, pay pura, umahuán, ayahuán chay shucuna shina, chaymantami shuclla shina causangacuna."
  specimen_16: "Tucuy runacuna quishpirihuán huiñán, pactacunahuampes, pay pura, umahuán, ayahuán chay shucuna shina, chaymantami shuclla shina causangacuna.\nTucuy runacuna quishpirihuán huiñán, pactacunahuampes, pay pura, umahuán, ayahuán chay shucuna shina, chaymantami shuclla shina causangacuna.\nTucuy runacuna quishpirihuán huiñán, pactacunahuampes, pay pura, umahuán, ayahuán chay shucuna shina, chaymantami shuclla shina causangacuna.\nTucuy runacuna quishpirihuán huiñán, pactacunahuampes, pay pura, umahuán, ayahuán chay shucuna shina, chaymantami shuclla shina causangacuna.\nTucuy runacuna quishpirihuán huiñán, pactacunahuampes, pay pura, umahuán, ayahuán chay shucuna shina, chaymantami shuclla shina causangacuna."
}
