id: "qva_Latn"
language: "qva"
script: "Latn"
name: "Quechua, Ambo-Pasco"
sample_text {
  masthead_full: "LlAa"
  masthead_partial: "Pp"
  styles: "L\na\np\na\nn\n \nr\nu\nn\na\n \nk\na\ny\n \np\na\nc\nh\na\nc"
  tester: "L\na\np\na\nn\n \nr\nu\nn\na\n \nk\na\ny\n \np\na\nc\nh\na\nc\nh\n\'\nu\n \ny\nu\nr\ni\nn\n "
  poster_sm: "L\na\np\na\nn\n "
  poster_md: "L\na\np\na\nn"
  poster_lg: "L\na"
  specimen_48: "L\na\np\na\nn\n \nr\nu\nn\na\n \nk\na\ny\n \np\na\nc\nh\na\nc\nh\n\'\nu\n \ny\nu\nr\ni\nn\n "
  specimen_36: "L\na\np\na\nn\n \nr\nu\nn\na\n \nk\na\ny\n \np\na\nc\nh\na\nc\nh\n\'\nu\n \ny\nu\nr\ni\nn\n \nl\ni\nb\nr\ni\n \nk\na\nw\na\nn\na\nn\np\na\nq\n,\n \nl\na\np"
  specimen_32: "L\na\np\na\nn\n \nr\nu\nn\na\n \nk\na\ny\n \np\na\nc\nh\na\nc\nh\n\'\nu\n \ny\nu\nr\ni\nn\n \nl\ni\nb\nr\ni\n \nk\na\nw\na\nn\na\nn\np\na\nq\n,\n \nl\na\np\na\nn\nc\nh\ni\nn\nu\ny\n \ni\nw\na\nl\n \nr\ne\ns\np\ne\nt"
  specimen_21: "L\na\np\na\nn\n \nr\nu\nn\na\n \nk\na\ny\n \np\na\nc\nh\na\nc\nh\n\'\nu\n \ny\nu\nr\ni\nn\n \nl\ni\nb\nr\ni\n \nk\na\nw\na\nn\na\nn\np\na\nq\n,\n \nl\na\np\na\nn\nc\nh\ni\nn\nu\ny\n \ni\nw\na\nl\n \nr\ne\ns\np\ne\nt\na\ns\nh\na\n \nk\na\nn\na\nn\np\na\nq\nm\ni\n,\n \nm\na\nn\na\n \np\ni\np\ni\ns\n \nj\na\nr\nu\np\nä\nn\na\nn\np\na\nq\n,\n \nl\na\np\na\nn\np\ni\ns\n \ni\nw\na\nl\n \ny\na\nr\np\na\nc\nh\n\'\na\nk\nu\ny\n \ny\na\nc\nh\n\'\na\nq\nm\ni\n,\n \na\nl"
  specimen_16: "L\na\np\na\nn\n \nr\nu\nn\na\n \nk\na\ny\n \np\na\nc\nh\na\nc\nh\n\'\nu\n \ny\nu\nr\ni\nn\n \nl\ni\nb\nr\ni\n \nk\na\nw\na\nn\na\nn\np\na\nq\n,\n \nl\na\np\na\nn\nc\nh\ni\nn\nu\ny\n \ni\nw\na\nl\n \nr\ne\ns\np\ne\nt\na\ns\nh\na\n \nk\na\nn\na\nn\np\na\nq\nm\ni\n,\n \nm\na\nn\na\n \np\ni\np\ni\ns\n \nj\na\nr\nu\np\nä\nn\na\nn\np\na\nq\n,\n \nl\na\np\na\nn\np\ni\ns\n \ni\nw\na\nl\n \ny\na\nr\np\na\nc\nh\n\'\na\nk\nu\ny\n \ny\na\nc\nh\n\'\na\nq\nm\ni\n,\n \na\nl\ni\nt\na\n \nm\na\nn\na\n \na\nl\ni\nt\na\n \nt\na\nn\nt\ni\ny\na\nr\n \nk\na\nw\na\nn\na\nn\np\na\nq\n.\n \nC\nh\na\ny\nn\nu\ny\n \nr\nu\nn\na\n \nm\na\ns\ni\nn\nw\na\nn\n \nj\nu\nk\nn\ni\nn\n \nj\nu\nk\nn\ni\nn\nw\na\nn\n \nk\nu\ny\na\nn\na\nk\nu\nr\n \nk\na\np\nä\nk\nu\nc\nh\nu\nn\nL\na\np\na\nn\n \nr\nu\nn\na\n \nk\na\ny\n \np\na\nc\nh\na\nc\nh\n\'\nu\n \ny\nu\nr\ni\nn\n "
}
