id: "qvh_Latn"
language: "qvh"
script: "Latn"
name: "Quechua, Huamalíes-Dos de Mayo Huánuco"
sample_text {
  masthead_full: "LlAa"
  masthead_partial: "Pp"
  styles: "L\na\np\na\nn\n \nr\nu\nn\na\nk\nu\nn\na\np\ni\ns\n \ny\nu\nr"
  tester: "L\na\np\na\nn\n \nr\nu\nn\na\nk\nu\nn\na\np\ni\ns\n \ny\nu\nr\ni\nk\nu\ny\na\nn\n \nl\ni\nb"
  poster_sm: "L\na\np\na\nn\n "
  poster_md: "L\na\np\na\nn"
  poster_lg: "L\na"
  specimen_48: "L\na\np\na\nn\n \nr\nu\nn\na\nk\nu\nn\na\np\ni\ns\n \ny\nu\nr\ni\nk\nu\ny\na\nn\n \nl\ni\nb"
  specimen_36: "L\na\np\na\nn\n \nr\nu\nn\na\nk\nu\nn\na\np\ni\ns\n \ny\nu\nr\ni\nk\nu\ny\na\nn\n \nl\ni\nb\nr\ni\nm\ni\n \ny\n \nw\na\nk\ni\nn\nk\na\nq\nk\nu\nn\na\nn"
  specimen_32: "L\na\np\na\nn\n \nr\nu\nn\na\nk\nu\nn\na\np\ni\ns\n \ny\nu\nr\ni\nk\nu\ny\na\nn\n \nl\ni\nb\nr\ni\nm\ni\n \ny\n \nw\na\nk\ni\nn\nk\na\nq\nk\nu\nn\na\nn\na\nw\n \nr\ni\ns\np\ni\nt\na\ns\nh\nq\na\n,\n \nm\na\nn\na"
  specimen_21: "L\na\np\na\nn\n \nr\nu\nn\na\nk\nu\nn\na\np\ni\ns\n \ny\nu\nr\ni\nk\nu\ny\na\nn\n \nl\ni\nb\nr\ni\nm\ni\n \ny\n \nw\na\nk\ni\nn\nk\na\nq\nk\nu\nn\na\nn\na\nw\n \nr\ni\ns\np\ni\nt\na\ns\nh\nq\na\n,\n \nm\na\nn\na\n \nj\na\nr\nu\nk\nu\ns\nh\nq\na\n \nk\na\ny\nä\nn\na\nn\np\na\nq\n.\n \nS\na\ny\nn\na\nw\nm\ni\n \nr\nu\nn\na\nk\nu\nn\na\nq\na\n \ny\nu\nr\ni\ny\na\nn\n \ns\nh\nu\nm\na\nq\n \ny\na\nr\np\na\ny\ny\nu\nq\n,\n \na\nl\ni\nt\na\np\ni\ns\n \nm\na"
  specimen_16: "L\na\np\na\nn\n \nr\nu\nn\na\nk\nu\nn\na\np\ni\ns\n \ny\nu\nr\ni\nk\nu\ny\na\nn\n \nl\ni\nb\nr\ni\nm\ni\n \ny\n \nw\na\nk\ni\nn\nk\na\nq\nk\nu\nn\na\nn\na\nw\n \nr\ni\ns\np\ni\nt\na\ns\nh\nq\na\n,\n \nm\na\nn\na\n \nj\na\nr\nu\nk\nu\ns\nh\nq\na\n \nk\na\ny\nä\nn\na\nn\np\na\nq\n.\n \nS\na\ny\nn\na\nw\nm\ni\n \nr\nu\nn\na\nk\nu\nn\na\nq\na\n \ny\nu\nr\ni\ny\na\nn\n \ns\nh\nu\nm\na\nq\n \ny\na\nr\np\na\ny\ny\nu\nq\n,\n \na\nl\ni\nt\na\np\ni\ns\n \nm\na\nn\na\n \na\nl\ni\nt\na\np\ni\ns\n \nr\ne\nq\ni\ny\nk\na\nr\n \ny\n \ns\ne\nq\na\ny\n \nk\nu\ny\na\np\nä\nk\nu\ny\ny\nu\nq\n.\n \nS\na\ny\nm\ni\n \nr\nu\nn\na\nk\nu\nn\na\n \na\nl\ni\n \nk\na\nw\na\nk\nu\ny\nä\nn\na\nn\n \nj\nu\nk\nn\ni\nn\nw\na\nn\n \nj\nu\nk\nn\ni\nn\nw\na\nn\np\ni\ns\n.\nL\na\np\na\nn\n \nr\nu\nn\na\nk\nu\nn\na\np\ni\ns\n \ny\nu\nr\ni\nk\nu\ny\na\nn\n \nl"
}
