id: "qvn_Latn"
language: "qvn"
script: "Latn"
name: "Quechua, North Junín"
sample_text {
  masthead_full: "LlAa"
  masthead_partial: "Pp"
  styles: "L\na\np\na\nn\n \nr\nu\nn\na\ns\n \nk\na\ny\n \np\na\nc\nh\na"
  tester: "L\na\np\na\nn\n \nr\nu\nn\na\ns\n \nk\na\ny\n \np\na\nc\nh\na\nc\nh\nr\nu\n \nn\na\ns\ni\nm"
  poster_sm: "L\na\np\na\nn\n "
  poster_md: "L\na\np\na\nn"
  poster_lg: "L\na"
  specimen_48: "L\na\np\na\nn\n \nr\nu\nn\na\ns\n \nk\na\ny\n \np\na\nc\nh\na\nc\nh\nr\nu\n \nn\na\ns\ni\nm"
  specimen_36: "L\na\np\na\nn\n \nr\nu\nn\na\ns\n \nk\na\ny\n \np\na\nc\nh\na\nc\nh\nr\nu\n \nn\na\ns\ni\nm\nu\nn\n \nj\nu\nk\n \nr\na\nn\nt\ni\ns\nh\na\n \nr\nu\nn\na"
  specimen_32: "L\na\np\na\nn\n \nr\nu\nn\na\ns\n \nk\na\ny\n \np\na\nc\nh\na\nc\nh\nr\nu\n \nn\na\ns\ni\nm\nu\nn\n \nj\nu\nk\n \nr\na\nn\nt\ni\ns\nh\na\n \nr\nu\nn\na\nn\nu\ny\n \nm\na\nn\na\n \np\ni\nt\na\ns\n \ns\ni\nr\nb\ni"
  specimen_21: "L\na\np\na\nn\n \nr\nu\nn\na\ns\n \nk\na\ny\n \np\na\nc\nh\na\nc\nh\nr\nu\n \nn\na\ns\ni\nm\nu\nn\n \nj\nu\nk\n \nr\na\nn\nt\ni\ns\nh\na\n \nr\nu\nn\na\nn\nu\ny\n \nm\na\nn\na\n \np\ni\nt\na\ns\n \ns\ni\nr\nb\ni\nn\na\nn\np\na\nq\nm\ni\n,\n \na\nl\ni\np\na\n \nr\ni\nk\na\ns\nh\na\n \nk\na\nn\na\nn\np\na\nq\nm\ni\n,\n \nw\na\ns\nh\na\ns\nh\na\n \nk\na\nn\na\nn\np\na\nq\nm\ni\n.\n \nL\na\np\na\nn\n \nr\nu\nn\na\nk\nu\nn\na\ns\n \nn\na\ns\ni\np\na\na\nk"
  specimen_16: "L\na\np\na\nn\n \nr\nu\nn\na\ns\n \nk\na\ny\n \np\na\nc\nh\na\nc\nh\nr\nu\n \nn\na\ns\ni\nm\nu\nn\n \nj\nu\nk\n \nr\na\nn\nt\ni\ns\nh\na\n \nr\nu\nn\na\nn\nu\ny\n \nm\na\nn\na\n \np\ni\nt\na\ns\n \ns\ni\nr\nb\ni\nn\na\nn\np\na\nq\nm\ni\n,\n \na\nl\ni\np\na\n \nr\ni\nk\na\ns\nh\na\n \nk\na\nn\na\nn\np\na\nq\nm\ni\n,\n \nw\na\ns\nh\na\ns\nh\na\n \nk\na\nn\na\nn\np\na\nq\nm\ni\n.\n \nL\na\np\na\nn\n \nr\nu\nn\na\nk\nu\nn\na\ns\n \nn\na\ns\ni\np\na\na\nk\na\nm\nu\nn\n \ny\na\nr\np\na\ny\nn\ni\ny\no\nq\nm\ni\n \nn\na\na\nt\na\nn\n \nt\na\nn\nt\ni\ny\na\ny\nn\ni\ny\no\nq\nm\ni\n \ni\nm\na\n \nl\nu\nt\na\nn\nt\na\n \nr\nu\nr\na\np\na\na\nk\nu\nr\nu\nr\ns\ni\n \nt\na\nn\nt\ni\ny\na\nk\nu\nn\na\nn\np\na\nq\n.\n \nL\na\np\na\nn\n \nr\nu\nn\na\nk\nu\nn\na\ns\n \nk\na\nw\na\np\na\na\nk\nu\nn\na\nm\na\nn\n \nj\nu\nk\n \nw\na\nw\nq\ne"
}
