id: "qwh_Latn"
language: "qwh"
script: "Latn"
name: "Quechua, Huaylas Ancash"
sample_text {
  masthead_full: "MmEe"
  masthead_partial: "Yy"
  styles: "M\ne\ny\nq\na\nn\n \nn\nu\nn\na\np\ni\ns\n \nm\na\nn\na\nm\n "
  tester: "M\ne\ny\nq\na\nn\n \nn\nu\nn\na\np\ni\ns\n \nm\na\nn\na\nm\n \np\ni\np\na\n \ns\ni\nr\nw\ne"
  poster_sm: "M\ne\ny\nq\na\nn"
  poster_md: "M\ne\ny\nq\na"
  poster_lg: "M\ne"
  specimen_48: "M\ne\ny\nq\na\nn\n \nn\nu\nn\na\np\ni\ns\n \nm\na\nn\na\nm\n \np\ni\np\na\n \ns\ni\nr\nw\ne"
  specimen_36: "M\ne\ny\nq\na\nn\n \nn\nu\nn\na\np\ni\ns\n \nm\na\nn\na\nm\n \np\ni\np\na\n \ns\ni\nr\nw\ne\nq\nn\ni\nn\n \nn\nu\nn\na\n \nk\na\nn\na\nn\np\na\nq\nt\ns"
  specimen_32: "M\ne\ny\nq\na\nn\n \nn\nu\nn\na\np\ni\ns\n \nm\na\nn\na\nm\n \np\ni\np\na\n \ns\ni\nr\nw\ne\nq\nn\ni\nn\n \nn\nu\nn\na\n \nk\na\nn\na\nn\np\na\nq\nt\ns\nu\n \ny\nu\nr\ni\nk\nu\ns\nh\nq\na\n.\n \nI\n \nn\nu\nn\na"
  specimen_21: "M\ne\ny\nq\na\nn\n \nn\nu\nn\na\np\ni\ns\n \nm\na\nn\na\nm\n \np\ni\np\na\n \ns\ni\nr\nw\ne\nq\nn\ni\nn\n \nn\nu\nn\na\n \nk\na\nn\na\nn\np\na\nq\nt\ns\nu\n \ny\nu\nr\ni\nk\nu\ns\nh\nq\na\n.\n \nI\n \nn\nu\nn\na\n \nk\na\nr\nn\ni\nn\nm\ni\n \nm\ne\ny\nq\na\nn\n \nn\nu\nn\na\np\ni\ns\n \nj\nu\nk\n \nl\ná\ny\na\nt\ns\nu\n \nk\na\ny\na\nn\nm\na\nn\n \nd\ne\nr\në\nc\nh\nu\nn\nk\nu\nn\na\nc\nh\no\nw\np\ni\ns\n.\n \nI\n \ny\na\nr\np\na\nc\nh\na\nk\ni\ny\nt"
  specimen_16: "M\ne\ny\nq\na\nn\n \nn\nu\nn\na\np\ni\ns\n \nm\na\nn\na\nm\n \np\ni\np\na\n \ns\ni\nr\nw\ne\nq\nn\ni\nn\n \nn\nu\nn\na\n \nk\na\nn\na\nn\np\na\nq\nt\ns\nu\n \ny\nu\nr\ni\nk\nu\ns\nh\nq\na\n.\n \nI\n \nn\nu\nn\na\n \nk\na\nr\nn\ni\nn\nm\ni\n \nm\ne\ny\nq\na\nn\n \nn\nu\nn\na\np\ni\ns\n \nj\nu\nk\n \nl\ná\ny\na\nt\ns\nu\n \nk\na\ny\na\nn\nm\na\nn\n \nd\ne\nr\në\nc\nh\nu\nn\nk\nu\nn\na\nc\nh\no\nw\np\ni\ns\n.\n \nI\n \ny\na\nr\np\na\nc\nh\na\nk\ni\ny\nt\na\n \ny\na\nc\nh\na\nr\nn\ni\nn\nm\ni\n \ni\n \na\nl\nl\ni\nt\na\n \nm\na\nn\na\n \na\nl\nl\ni\nt\na\n \ns\nh\no\nn\nq\no\nn\nk\nu\nn\na\nc\nh\no\nw\n \nm\ná\nk\nu\nr\nn\ni\nn\nm\ni\n \nn\nu\nn\na\nk\nu\nn\na\n \nj\nu\nk\nn\ni\nn\nt\na\n \nw\ni\ny\na\nn\na\nk\nu\nr\n \nk\na\ny\na\nn\nm\na\nn\n.\nM\ne\ny\nq\na\nn\n \nn\nu\nn\na\np\ni\ns\n \nm\na\nn\na\nm\n \np\ni\np\na\n "
}
