id: "qxn_Latn"
language: "qxn"
script: "Latn"
name: "Quechua, Northern Conchucos Ancash"
sample_text {
  masthead_full: "MmAa"
  masthead_partial: "Yy"
  styles: "Mayqan runapis manam pipa isklabun kananpaqtsu"
  tester: "Mayqan runapis manam pipa isklabun kananpaqtsu yurishqa. Y runa"
  poster_sm: "Mayqan runapis"
  poster_md: ""
  poster_lg: "Mayqan"
  specimen_48: ""
  specimen_36: ""
  specimen_32: ""
  specimen_21: "Mayqan runapis manam pipa isklabun kananpaqtsu yurishqa. Y runa karninmi llapan runakuna iwal kayanman dirichunkunachawpis. Y yarpayta yacharninmi y allita mana allita shunqunkunachaw makurninmi runakuna huknin hukninta rispitanakur kayanman.\nMayqan runapis manam pipa isklabun kananpaqtsu yurishqa. Y runa karninmi llapan runakuna iwal kayanman dirichunkunachawpis. Y yarpayta yacharninmi y allita mana allita shunqunkunachaw makurninmi runakuna huknin hukninta rispitanakur kayanman."
  specimen_16: "Mayqan runapis manam pipa isklabun kananpaqtsu yurishqa. Y runa karninmi llapan runakuna iwal kayanman dirichunkunachawpis. Y yarpayta yacharninmi y allita mana allita shunqunkunachaw makurninmi runakuna huknin hukninta rispitanakur kayanman.\nMayqan runapis manam pipa isklabun kananpaqtsu yurishqa. Y runa karninmi llapan runakuna iwal kayanman dirichunkunachawpis. Y yarpayta yacharninmi y allita mana allita shunqunkunachaw makurninmi runakuna huknin hukninta rispitanakur kayanman.\nMayqan runapis manam pipa isklabun kananpaqtsu yurishqa. Y runa karninmi llapan runakuna iwal kayanman dirichunkunachawpis. Y yarpayta yacharninmi y allita mana allita shunqunkunachaw makurninmi runakuna huknin hukninta rispitanakur kayanman."
}
