id: "rar"
language: "rar"
script: "Latn"
name: "Rarotongan"
preferred_name: "Cook Islands Māori"
autonym: "Māori Kūki \'Āirani"
population: 0
region: "AC"
region: "AD"
region: "AF"
region: "AG"
region: "AI"
region: "AL"
region: "AM"
region: "AO"
region: "AR"
region: "AS"
region: "AT"
region: "AU"
region: "AW"
region: "AX"
region: "AZ"
region: "BA"
region: "BB"
region: "BD"
region: "BE"
region: "BF"
region: "BG"
region: "BI"
region: "BJ"
region: "BL"
region: "BM"
region: "BN"
region: "BO"
region: "BQ"
region: "BR"
region: "BS"
region: "BT"
region: "BW"
region: "BY"
region: "BZ"
region: "CA"
region: "CC"
region: "CD"
region: "CF"
region: "CG"
region: "CH"
region: "CI"
region: "CK"
region: "CL"
region: "CM"
region: "CN"
region: "CO"
region: "CR"
region: "CU"
region: "CV"
region: "CW"
region: "CX"
region: "CY"
region: "CZ"
region: "DE"
region: "DG"
region: "DJ"
region: "DK"
region: "DM"
region: "DO"
region: "DZ"
region: "EA"
region: "EC"
region: "EE"
region: "EG"
region: "ER"
region: "ES"
region: "ET"
region: "FI"
region: "FJ"
region: "FK"
region: "FM"
region: "FO"
region: "FR"
region: "GA"
region: "GB"
region: "GD"
region: "GE"
region: "GF"
region: "GG"
region: "GH"
region: "GI"
region: "GL"
region: "GM"
region: "GN"
region: "GP"
region: "GQ"
region: "GR"
region: "GT"
region: "GU"
region: "GW"
region: "GY"
region: "HK"
region: "HN"
region: "HR"
region: "HT"
region: "HU"
region: "IC"
region: "ID"
region: "IE"
region: "IL"
region: "IM"
region: "IN"
region: "IO"
region: "IQ"
region: "IR"
region: "IS"
region: "IT"
region: "JE"
region: "JM"
region: "JO"
region: "KE"
region: "KG"
region: "KI"
region: "KM"
region: "KN"
region: "KY"
region: "KZ"
region: "LA"
region: "LB"
region: "LC"
region: "LI"
region: "LK"
region: "LR"
region: "LS"
region: "LT"
region: "LU"
region: "LV"
region: "MA"
region: "MC"
region: "MD"
region: "ME"
region: "MF"
region: "MG"
region: "MH"
region: "MK"
region: "ML"
region: "MM"
region: "MN"
region: "MO"
region: "MP"
region: "MQ"
region: "MR"
region: "MS"
region: "MT"
region: "MU"
region: "MW"
region: "MX"
region: "MY"
region: "MZ"
region: "NA"
region: "NC"
region: "NE"
region: "NF"
region: "NG"
region: "NI"
region: "NL"
region: "NO"
region: "NP"
region: "NR"
region: "NU"
region: "NZ"
region: "PA"
region: "PE"
region: "PF"
region: "PG"
region: "PH"
region: "PK"
region: "PL"
region: "PM"
region: "PN"
region: "PR"
region: "PT"
region: "PW"
region: "PY"
region: "RE"
region: "RO"
region: "RS"
region: "RU"
region: "RW"
region: "SB"
region: "SC"
region: "SD"
region: "SE"
region: "SG"
region: "SH"
region: "SI"
region: "SJ"
region: "SK"
region: "SL"
region: "SM"
region: "SN"
region: "SO"
region: "SR"
region: "SS"
region: "ST"
region: "SV"
region: "SX"
region: "SY"
region: "SZ"
region: "TA"
region: "TC"
region: "TD"
region: "TF"
region: "TG"
region: "TH"
region: "TJ"
region: "TK"
region: "TL"
region: "TM"
region: "TN"
region: "TO"
region: "TR"
region: "TT"
region: "TV"
region: "TW"
region: "TZ"
region: "UA"
region: "UG"
region: "UM"
region: "US"
region: "UY"
region: "UZ"
region: "VA"
region: "VC"
region: "VE"
region: "VG"
region: "VI"
region: "VN"
region: "VU"
region: "WF"
region: "WS"
region: "XK"
region: "YE"
region: "YT"
region: "ZA"
region: "ZM"
region: "ZW"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ā Ē Ī Ō Ū a b c d e f g h i j k l m n o p q r s t u v w x y z ā ē ī ō ū"
  auxiliary: "Á É Í Ó Ú á é í ó ú"
  marks: "◌̄ ◌́"
}
sample_text {
  masthead_full: "KkUu"
  masthead_partial: "Aa"
  styles: "I te mea oki e, ko te maramaanga e te arikianga"
  tester: "E i te mea oki e, ko te akangaropoinaanga e te akava’ava’aanga i"
  poster_sm: "E, i te mea"
  poster_md: "E,i te mea"
  poster_lg: "Kua"
  specimen_48: "E, i te mea oki e, kua akamou te au iti tangata o te Taokotaianga"
  specimen_36: "Auraka tetai uatu tangata kia akaapa taukore ia i raro ake i te ture, kia tapeka ia me kore ra akata’a ia."
  specimen_32: "E tikaanga to tetai uatu tangata ki tetai tuatau akangaroi anga e te tamataora anga, kapiti ia ki tetai au akakotinga anga tau o te ora angaanga e tetai au tuatau orote tutaki ia."
  specimen_21: "E tikaanga to tetai uatu tangata kia noo ki roto i tetai tu oraanga iti tangata e te oraanga i rotopu i te au Basileia tei akatupu ki te openga, te au tu tikaanga e te tu rangatira i tata ia i roto i teia Akakiteanga.\nI te mea oki e, ko te maramaanga e te arikianga i te tu turanga ngateitei tiratiratu tumu tikai, e te tikaanga aiteite e te mutukore o te tangata katoatoa o teianei ao, ko te tango ia o te oraanga tamanamanata kore ia, te oraanga tiratiratu e te ‘au, i roto i teianei ao,"
  specimen_16: "I te mea oki e, ko te maramaanga e te arikianga i te tu turanga ngateitei tiratiratu tumu tikai, e te tikaanga aiteite e te mutukore o te tangata katoatoa o teianei ao, ko te tango ia o te oraanga tamanamanata kore ia, te oraanga tiratiratu e te ‘au, i roto i teianei ao,\nE i te mea oki e, ko te akangaropoinaanga e te akava’ava’aanga i te au tikaanga tangata, i tupu ei te au angaanga rikarika tikai tei akatupu i te riri otooto ki te akavangakau o te tangata tini ravarai, e ko te riro anga mai o tetai ao te ka rauka i te taangaanga i to ratou tikaanga i te tuatua e te irinakianga ma te tamanamanata kore, e te oraanga mataku kore e te ngere kore, tei akakite atea ia e ko te akakoroanga puapinga maata rava atu ia o te tangata ravarai,"
}
