id: "rcf_Latn"
language: "rcf"
script: "Latn"
name: "Réunion Creole French"
population: 559184
region: "RE"
sample_text {
  masthead_full: "TtOo"
  masthead_partial: "Uu"
  styles: "T\no\nu\nt\ne\n \nb\na\nn\nn\n \nz\nu\nm\ni\nn\n \ny\n \nn\né"
  tester: "T\no\nu\nt\ne\n \nb\na\nn\nn\n \nz\nu\nm\ni\nn\n \ny\n \nn\né\n \nl\ni\nb\n \ne\nt\n \né\ng"
  poster_sm: "T\no\nu\nt\ne\n "
  poster_md: "T\no\nu\nt\ne"
  poster_lg: "T\no"
  specimen_48: "T\no\nu\nt\ne\n \nb\na\nn\nn\n \nz\nu\nm\ni\nn\n \ny\n \nn\né\n \nl\ni\nb\n \ne\nt\n \né\ng"
  specimen_36: "T\no\nu\nt\ne\n \nb\na\nn\nn\n \nz\nu\nm\ni\nn\n \ny\n \nn\né\n \nl\ni\nb\n \ne\nt\n \né\ng\no\n \nd\na\nn\n \nl\na\n \nd\ni\ng\nn\ni\nt\né\n \ne\nk\n "
  specimen_32: "T\no\nu\nt\ne\n \nb\na\nn\nn\n \nz\nu\nm\ni\nn\n \ny\n \nn\né\n \nl\ni\nb\n \ne\nt\n \né\ng\no\n \nd\na\nn\n \nl\na\n \nd\ni\ng\nn\ni\nt\né\n \ne\nk\n \nd\na\nn\ns\n \nl\ne\n \nb\na\nn\nn\n \nd\nr\no\ni\n.\n \nZ"
  specimen_21: "T\no\nu\nt\ne\n \nb\na\nn\nn\n \nz\nu\nm\ni\nn\n \ny\n \nn\né\n \nl\ni\nb\n \ne\nt\n \né\ng\no\n \nd\na\nn\n \nl\na\n \nd\ni\ng\nn\ni\nt\né\n \ne\nk\n \nd\na\nn\ns\n \nl\ne\n \nb\na\nn\nn\n \nd\nr\no\ni\n.\n \nZ\no\nt\n \nn\na\nn\na\n \nl\na\n \nr\né\nz\no\nn\n \ne\nk\n \nl\na\n \nc\no\nn\ns\nc\ni\na\nn\ns\n \ne\nt\n \nz\no\nt\n \ny\n \nd\no\ni\n \na\nj\ni\n \nl\né\n \nz\ni\nn\n \ne\nn\nv\ne\nr\n \nl\né\n \nz\no\nt\n \nd\na\nn\n \nz\ni\nn\n \nl\ne"
  specimen_16: "T\no\nu\nt\ne\n \nb\na\nn\nn\n \nz\nu\nm\ni\nn\n \ny\n \nn\né\n \nl\ni\nb\n \ne\nt\n \né\ng\no\n \nd\na\nn\n \nl\na\n \nd\ni\ng\nn\ni\nt\né\n \ne\nk\n \nd\na\nn\ns\n \nl\ne\n \nb\na\nn\nn\n \nd\nr\no\ni\n.\n \nZ\no\nt\n \nn\na\nn\na\n \nl\na\n \nr\né\nz\no\nn\n \ne\nk\n \nl\na\n \nc\no\nn\ns\nc\ni\na\nn\ns\n \ne\nt\n \nz\no\nt\n \ny\n \nd\no\ni\n \na\nj\ni\n \nl\né\n \nz\ni\nn\n \ne\nn\nv\ne\nr\n \nl\né\n \nz\no\nt\n \nd\na\nn\n \nz\ni\nn\n \nl\ne\ns\np\nr\ni\n \nd\ne\n \nf\nr\na\nt\ne\nr\nn\ni\nt\né\nT\no\nu\nt\ne\n \nb\na\nn\nn\n \nz\nu\nm\ni\nn\n \ny\n \nn\né\n \nl\ni\nb\n \ne\nt\n \né\ng\no\n \nd\na\nn\n \nl\na\n \nd\ni\ng\nn\ni\nt\né\n \ne\nk\n \nd\na\nn\ns\n \nl\ne\n \nb\na\nn\nn\n \nd\nr\no\ni\n.\n \nZ\no\nt\n \nn\na\nn\na\n \nl\na\n \nr\né\nz\no\nn\n \ne\nk\n \nl\na\n \nc\no\nn\ns\nc\ni\na\nn\ns\n \ne\nt\n \nz"
}
