id: "rej_Latn"
language: "rej"
script: "Latn"
name: "Rejang"
population: 1228319
region: "ID"
sample_text {
  masthead_full: "KkUu"
  masthead_partial: "Tt"
  styles: "K\nu\nt\nê\n \nt\nu\nn\n \nl\na\nh\ne\nr\n \nm\nê\nr\nd\ne\nk"
  tester: "K\nu\nt\nê\n \nt\nu\nn\n \nl\na\nh\ne\nr\n \nm\nê\nr\nd\ne\nk\na\n,\n \nt\nm\nu\na\nn\n \nh"
  poster_sm: "K\nu\nt\nê\n \nt"
  poster_md: "K\nu\nt\nê\n "
  poster_lg: "K\nu"
  specimen_48: "K\nu\nt\nê\n \nt\nu\nn\n \nl\na\nh\ne\nr\n \nm\nê\nr\nd\ne\nk\na\n,\n \nt\nm\nu\na\nn\n \nh"
  specimen_36: "K\nu\nt\nê\n \nt\nu\nn\n \nl\na\nh\ne\nr\n \nm\nê\nr\nd\ne\nk\na\n,\n \nt\nm\nu\na\nn\n \nh\no\nk\n-\nh\no\nk\n \nd\nê\n \ns\nr\na\ni\n.\n \nK\nu\nt\nê\n "
  specimen_32: "K\nu\nt\nê\n \nt\nu\nn\n \nl\na\nh\ne\nr\n \nm\nê\nr\nd\ne\nk\na\n,\n \nt\nm\nu\na\nn\n \nh\no\nk\n-\nh\no\nk\n \nd\nê\n \ns\nr\na\ni\n.\n \nK\nu\nt\nê\n \nn\na\ng\ni\na\nk\n-\nb\na\n \na\nk\nê\na\n \np\ne\nk\ne\nr\n "
  specimen_21: "K\nu\nt\nê\n \nt\nu\nn\n \nl\na\nh\ne\nr\n \nm\nê\nr\nd\ne\nk\na\n,\n \nt\nm\nu\na\nn\n \nh\no\nk\n-\nh\no\nk\n \nd\nê\n \ns\nr\na\ni\n.\n \nK\nu\nt\nê\n \nn\na\ng\ni\na\nk\n-\nb\na\n \na\nk\nê\na\n \np\ne\nk\ne\nr\n \nn\ng\ne\nn\n \na\nt\nê\ni\n,\n \nk\nê\nr\nn\no\n \no\n \nk\nê\nl\no\nk\n-\nn\nê\n \nb\nê\nk\nu\na\nt\n-\nb\na\n \nd\no\n \nn\ng\ne\nn\n \nl\nu\ny\nê\nn\n \nl\nê\nm\n \na\ns\na\ni\n \ns\nê\np\na\ns\nu\na\nk\n.\nK\nu\nt\nê\n \nt\nu\nn\n \nl\na\nh"
  specimen_16: "K\nu\nt\nê\n \nt\nu\nn\n \nl\na\nh\ne\nr\n \nm\nê\nr\nd\ne\nk\na\n,\n \nt\nm\nu\na\nn\n \nh\no\nk\n-\nh\no\nk\n \nd\nê\n \ns\nr\na\ni\n.\n \nK\nu\nt\nê\n \nn\na\ng\ni\na\nk\n-\nb\na\n \na\nk\nê\na\n \np\ne\nk\ne\nr\n \nn\ng\ne\nn\n \na\nt\nê\ni\n,\n \nk\nê\nr\nn\no\n \no\n \nk\nê\nl\no\nk\n-\nn\nê\n \nb\nê\nk\nu\na\nt\n-\nb\na\n \nd\no\n \nn\ng\ne\nn\n \nl\nu\ny\nê\nn\n \nl\nê\nm\n \na\ns\na\ni\n \ns\nê\np\na\ns\nu\na\nk\n.\nK\nu\nt\nê\n \nt\nu\nn\n \nl\na\nh\ne\nr\n \nm\nê\nr\nd\ne\nk\na\n,\n \nt\nm\nu\na\nn\n \nh\no\nk\n-\nh\no\nk\n \nd\nê\n \ns\nr\na\ni\n.\n \nK\nu\nt\nê\n \nn\na\ng\ni\na\nk\n-\nb\na\n \na\nk\nê\na\n \np\ne\nk\ne\nr\n \nn\ng\ne\nn\n \na\nt\nê\ni\n,\n \nk\nê\nr\nn\no\n \no\n \nk\nê\nl\no\nk\n-\nn\nê\n \nb\nê\nk\nu\na\nt\n-\nb\na\n \nd\no\n \nn\ng\ne\nn\n \nl\nu\ny\nê\nn\n \nl\nê\nm\n \na\ns\na\ni\n \ns\nê\np\na\ns\nu"
}
