id: "rgn"
language: "rgn"
script: "Latn"
name: "Romagnol"
population: 0
region: "IT"
sample_text {
  masthead_full: "TtOo"
  masthead_partial: "Jj"
  styles: "Considerèd che u riconoscimènt dla dignità"
  tester: "Considerèd che la negazioun e el disprèz di dirét umèn i à port"
  poster_sm: "Considerèd"
  poster_md: "L\'ASEMBLEA"
  poster_lg: "Tot"
  specimen_48: "la presènta dichiarazioun universèla di dirét umèn cumè ideél"
  specimen_36: "Nisuna persouna la putrà èsa sotoposta m\'la tortura o ma un tratamènt o punizioun crudeli, disumèni o degradènti."
  specimen_32: "Ogni persouna la à dirét m\'u ripos e m\'el temp lébri, tnénd count ad conseguénza d\'una giosta limitazioun dli ouri \'d lavour e ad ferie retribuidi."
  specimen_21: "Ogni persouna la à dirét m\'un ourdni suciél e internaziunèl te quale i dirét e al libertà proclamid tla presènta Dichiarazioun i posa èsa completamènt realizid.\nNisuna pèrta dla presènta Dichiarazioun la pò èsa interpretèda tu sèns da arughés, da pèrta d\'un qualsiasi Stèd o grop o persouna, un dirét da esercitè un\'atività o da mèta in at un\'azioun c\'la épa u scop da prevariché di dirét o dli libertà proclamid tla Dichiarazioun stèsa."
  specimen_16: "Considerèd che u riconoscimènt dla dignità cla riguèrda tot i mémbri dla famèia umèna e di su dirét, cumpagn e irrinunciabli, e costitués e\' fundamènt dla libertà, dla giustizia e dla pèsa te mand;\nConsiderèd che la negazioun e el disprèz di dirét umèn i à port ma gist d\'inciviltà che i ufènd la cuscinza dl\'umanità, e che la cunquésta d\'un mand duvè che al persouni al goda dla libertà at parola e at credo (foida) e dla libertà da la paura e da e\' bsagn, l\'è stè proclamèd cumè la piò granda aspirazioun dl\'om;\nConsiderèd che l\'è indispensabli che i dirét umèn i sia difois da lègi, se u s vò evitè che l\'om u sia custrèt a ricora, cumè utma pusibilità, m\'la ribelioun countra la tirania e l\'opresioun;"
}
