id: "rkt_Beng"
language: "rkt"
script: "Beng"
name: "Rangpuri"
autonym: "রংপুরী"
population: 16274502
region: "BD"
region: "IN"
exemplar_chars {
  base: "৺ অ আ ই ঈ উ ঊ ঋ এ ঐ ও ঔ ক খ গ ঘ ঙ চ ছ জ ঝ ঞ ট ঠ ড ঢ ণ ত থ দ ধ ন প ফ ব ভ ম য র ৰ ল ৱ শ ষ স হ"
  marks: "◌ঁ ◌ং ◌ঃ ◌় ◌া ◌ি ◌ী ◌ু ◌ূ ◌ৃ ◌ে ◌ৈ ◌্ ◌ৗ"
  numerals: "০ ১ ২ ৩ ৪ ৫ ৬ ৭ ৮ ৯"
}
sample_text {
  masthead_full: "गटलक"
  masthead_partial: "मन"
  styles: "ग\nट\nे\n \nल\nो\nक\nल\nा\n \nम\nा\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\nे"
  tester: "ग\nट\nे\n \nल\nो\nक\nल\nा\n \nम\nा\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\nे\nर\n \nआ\nध\nा\nर\nत\n्\n \nज\nन"
  poster_sm: "ग\nट\nे\n \nल\nो\nक"
  poster_md: "ग\nट\nे\n \nल"
  poster_lg: "ग\nट"
  specimen_48: "ग\nट\nे\n \nल\nो\nक\nल\nा\n \nम\nा\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\nे\nर\n \nआ\nध\nा\nर\nत\n्\n \nज\nन"
  specimen_36: "ग\nट\nे\n \nल\nो\nक\nल\nा\n \nम\nा\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\nे\nर\n \nआ\nध\nा\nर\nत\n्\n \nज\nन\n्\nम\nज\nा\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nआ\nर\n \nस\nम\nा\nन"
  specimen_32: "ग\nट\nे\n \nल\nो\nक\nल\nा\n \nम\nा\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\nे\nर\n \nआ\nध\nा\nर\nत\n्\n \nज\nन\n्\nम\nज\nा\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nआ\nर\n \nस\nम\nा\nन\n \nह\nच\nे\n।\n \nअ\nम\nा\nह\nा\nल\nा\nर\n \nब\nु\nद\n्\nध\nि\n \nआ\nर"
  specimen_21: "ग\nट\nे\n \nल\nो\nक\nल\nा\n \nम\nा\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\nे\nर\n \nआ\nध\nा\nर\nत\n्\n \nज\nन\n्\nम\nज\nा\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nआ\nर\n \nस\nम\nा\nन\n \nह\nच\nे\n।\n \nअ\nम\nा\nह\nा\nल\nा\nर\n \nब\nु\nद\n्\nध\nि\n \nआ\nर\n \nब\nि\nच\nा\nर\n \nल\nि\nए\n \nआ\nस\nा\nल\n \nर\nह\nच\nे\n \nआ\nर\n \nए\nक\n \nआ\nप\nस\nत\n्\n \nभ\nा\nइ\nभ\nा\nइ\nर\n \nब\n्\nय\nब\nह\nा\nर\n \nक\nर\nु\nब\nा\n \nल\nा\nग\nे\n।\nग\nट\nे\n \nल\nो\nक\nल\nा\n \nम\nा\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\nे\nर\n \nआ\nध\nा\nर\nत\n्"
  specimen_16: "ग\nट\nे\n \nल\nो\nक\nल\nा\n \nम\nा\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\nे\nर\n \nआ\nध\nा\nर\nत\n्\n \nज\nन\n्\nम\nज\nा\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nआ\nर\n \nस\nम\nा\nन\n \nह\nच\nे\n।\n \nअ\nम\nा\nह\nा\nल\nा\nर\n \nब\nु\nद\n्\nध\nि\n \nआ\nर\n \nब\nि\nच\nा\nर\n \nल\nि\nए\n \nआ\nस\nा\nल\n \nर\nह\nच\nे\n \nआ\nर\n \nए\nक\n \nआ\nप\nस\nत\n्\n \nभ\nा\nइ\nभ\nा\nइ\nर\n \nब\n्\nय\nब\nह\nा\nर\n \nक\nर\nु\nब\nा\n \nल\nा\nग\nे\n।\nग\nट\nे\n \nल\nो\nक\nल\nा\n \nम\nा\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\nे\nर\n \nआ\nध\nा\nर\nत\n्\n \nज\nन\n्\nम\nज\nा\nत\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nआ\nर\n \nस\nम\nा\nन\n \nह\nच\nे\n।\n \nअ\nम\nा\nह\nा\nल\nा\nर\n \nब\nु\nद\n्\nध\nि\n \nआ\nर\n \nब\nि\nच\nा\nर\n \nल\nि\nए\n \nआ\nस\nा\nल\n \nर\nह\nच\nे\n \nआ\nर\n \nए\nक\n \nआ\nप\nस\nत\n्\n \nभ\nा\nइ\nभ\nा\nइ\nर\n \nब\n्\nय\nब\nह\nा\nर\n \nक\nर\nु\nब\nा\n \nल\nा\nग\nे\n।\nग\nट\nे\n \nल\nो\nक\nल\nा\n \nम\nा\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\nे\nर\n \nआ\nध\nा\nर\nत\n्\n \nज"
}
