id: "rmn_Latn"
language: "rmn"
script: "Latn"
name: "Romani, Balkan"
sample_text {
  masthead_full: "SsAa"
  masthead_partial: "Vv"
  styles: "S\na\nv\no\nr\nr\ne\n \nm\na\nn\nu\nś\na\n \nb\ni\na\nn\nd\nõ"
  tester: "S\na\nv\no\nr\nr\ne\n \nm\na\nn\nu\nś\na\n \nb\ni\na\nn\nd\nõ\nn\n \nm\ne\ns\nt\ne\n \nt\nh"
  poster_sm: "S\na\nv\no\nr\nr"
  poster_md: "S\na\nv\no\nr"
  poster_lg: "S\na"
  specimen_48: "S\na\nv\no\nr\nr\ne\n \nm\na\nn\nu\nś\na\n \nb\ni\na\nn\nd\nõ\nn\n \nm\ne\ns\nt\ne\n \nt\nh"
  specimen_36: "S\na\nv\no\nr\nr\ne\n \nm\na\nn\nu\nś\na\n \nb\ni\na\nn\nd\nõ\nn\n \nm\ne\ns\nt\ne\n \nt\nh\na\nj\n \nb\na\nr\na\nb\na\nr\n \nk\n-\no\n \nd\ne\nm\nn\ni"
  specimen_32: "S\na\nv\no\nr\nr\ne\n \nm\na\nn\nu\nś\na\n \nb\ni\na\nn\nd\nõ\nn\n \nm\ne\ns\nt\ne\n \nt\nh\na\nj\n \nb\na\nr\na\nb\na\nr\n \nk\n-\no\n \nd\ne\nm\nn\ni\np\ne\nn\n \na\nj\n \nk\n-\ne\n \nh\na\nk\na\nj\na\n.\n \nS\ni"
  specimen_21: "S\na\nv\no\nr\nr\ne\n \nm\na\nn\nu\nś\na\n \nb\ni\na\nn\nd\nõ\nn\n \nm\ne\ns\nt\ne\n \nt\nh\na\nj\n \nb\na\nr\na\nb\na\nr\n \nk\n-\no\n \nd\ne\nm\nn\ni\np\ne\nn\n \na\nj\n \nk\n-\ne\n \nh\na\nk\na\nj\na\n.\n \nS\ni\n \nl\ne\nn\n \ng\no\nd\ni\n \na\nj\n \ns\no\nm\nz\na\nn\ni\np\ne\nn\n \nt\nh\na\nj\n \ns\ni\n \nl\ne\nn\n \nt\ne\n \nt\nr\ną\nd\ne\nn\n \np\ne\nn\n \nj\ne\nk\nh\n \nk\na\nr\ni\nn\ng\n \no\n \na\nv\ne\nr\n \na\nn\nd\n-\no\n \nv\no\ng\ni\n \ne"
  specimen_16: "S\na\nv\no\nr\nr\ne\n \nm\na\nn\nu\nś\na\n \nb\ni\na\nn\nd\nõ\nn\n \nm\ne\ns\nt\ne\n \nt\nh\na\nj\n \nb\na\nr\na\nb\na\nr\n \nk\n-\no\n \nd\ne\nm\nn\ni\np\ne\nn\n \na\nj\n \nk\n-\ne\n \nh\na\nk\na\nj\na\n.\n \nS\ni\n \nl\ne\nn\n \ng\no\nd\ni\n \na\nj\n \ns\no\nm\nz\na\nn\ni\np\ne\nn\n \nt\nh\na\nj\n \ns\ni\n \nl\ne\nn\n \nt\ne\n \nt\nr\ną\nd\ne\nn\n \np\ne\nn\n \nj\ne\nk\nh\n \nk\na\nr\ni\nn\ng\n \no\n \na\nv\ne\nr\n \na\nn\nd\n-\no\n \nv\no\ng\ni\n \ne\n \np\nh\nr\na\nl\ni\nm\nn\na\ns\nq\no\nr\no\n.\nS\na\nv\no\nr\nr\ne\n \nm\na\nn\nu\nś\na\n \nb\ni\na\nn\nd\nõ\nn\n \nm\ne\ns\nt\ne\n \nt\nh\na\nj\n \nb\na\nr\na\nb\na\nr\n \nk\n-\no\n \nd\ne\nm\nn\ni\np\ne\nn\n \na\nj\n \nk\n-\ne\n \nh\na\nk\na\nj\na\n.\n \nS\ni\n \nl\ne\nn\n \ng\no\nd\ni\n \na\nj\n \ns\no\nm\nz\na\nn\ni\np\ne\nn\n \nt\nh\na\nj\n \ns\ni\n \nl\ne\nn\n \nt\ne\n "
}
