id: "ro"
language: "ro"
script: "Latn"
name: "Romanian"
autonym: "Română"
population: 22085633
region: "HU"
region: "IL"
region: "MD"
region: "RO"
region: "RS"
region: "UA"
exemplar_chars {
  base: "a ă â b c d e f g h i î j k l m n o p r s ș t ț u v w x y z"
  auxiliary: "á à å ä ç é è ê ë ñ ö q ş ţ ü"
  marks: "◌̂ ◌̆ ◌̦ ◌̧"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ \" “ ” „ « » ( ) [ ] @ * /"
  index: "A Ă Â B C D E F G H I Î J K L M N O P Q R S Ș T Ț U V W X Y Z"
}
sample_text {
  masthead_full: "TtOo"
  masthead_partial: "Aa"
  styles: "Considerând că recunoașterea demnității inerente"
  tester: "Considerând că ignorarea și disprețuirea drepturilor omului au"
  poster_sm: "Considerând"
  poster_md: "ADUNAREA"
  poster_lg: "Toate"
  specimen_48: "prezenta DECLARAȚIE UNIVERSALĂ A DREPTURILOR OMULUI, ca ideal"
  specimen_36: "Nimeni nu va fi ținut în sclavie, nici în servitute; sclavajul și comerțul cu sclavi sunt interzise sub toate formele lor."
  specimen_32: "Orice persoană are dreptul la o orânduire socială și internațională în care drepturile și libertățile expuse în prezenta Declarație pot fi pe deplin înfăptuite."
  specimen_21: "Nicio dispoziție a prezentei Declarații nu poate fi interpretată ca implicând pentru vreun stat, grupare sau persoană dreptul de a se deda la vreo activitate sau de a săvârși vreun act îndreptat spre desființarea unor drepturi sau libertăți enunțate în prezenta Declarație.\nConsiderând că recunoașterea demnității inerente tuturor membrilor familiei umane și a drepturilor lor egale și inalienabile constituie fundamentul libertății, dreptății și păcii în lume,"
  specimen_16: "Considerând că recunoașterea demnității inerente tuturor membrilor familiei umane și a drepturilor lor egale și inalienabile constituie fundamentul libertății, dreptății și păcii în lume,\nConsiderând că ignorarea și disprețuirea drepturilor omului au dus la acte de barbarie care revoltă conștiința omenirii și că făurirea unei lumi în care ființele umane se vor bucura de libertatea cuvântului și a convingerilor și vor fi eliberate de teamă și mizerie a fost proclamată drept cea mai înaltă aspirație a oamenilor,\nConsiderând că este esențial ca drepturile omului să fie ocrotite de autoritatea legii pentru ca omul să nu fie silit să recurgă, ca soluție extremă, la revoltă împotriva tiraniei și asupririi,"
}
