id: "rom_Latn"
language: "rom"
script: "Latn"
name: "Romany"
autonym: "řomani ćhib"
population: 0
exemplar_chars {
  base: "A Ä B C Ć Č D E Ê F Ğ H I Î J K L M N O Ö P Ṗ Q R S Ś T U V W X Z Ź a ä b c ć č d e ê f ğ h i î j k l m n o ö p ṗ q r s ś t u v w x z ź"
  marks: "◌́ ◌̂ ◌̆ ◌̇ ◌̈ ◌̌"
}
