id: "rup"
language: "rup"
script: "Latn"
name: "Aromanian"
autonym: "Armani"
population: 0
region: "AC"
region: "AD"
region: "AF"
region: "AG"
region: "AI"
region: "AL"
region: "AM"
region: "AO"
region: "AR"
region: "AS"
region: "AT"
region: "AU"
region: "AW"
region: "AX"
region: "AZ"
region: "BA"
region: "BB"
region: "BD"
region: "BE"
region: "BF"
region: "BG"
region: "BI"
region: "BJ"
region: "BL"
region: "BM"
region: "BN"
region: "BO"
region: "BQ"
region: "BR"
region: "BS"
region: "BT"
region: "BW"
region: "BY"
region: "BZ"
region: "CA"
region: "CC"
region: "CD"
region: "CF"
region: "CG"
region: "CH"
region: "CI"
region: "CK"
region: "CL"
region: "CM"
region: "CN"
region: "CO"
region: "CR"
region: "CU"
region: "CV"
region: "CW"
region: "CX"
region: "CY"
region: "CZ"
region: "DE"
region: "DG"
region: "DJ"
region: "DK"
region: "DM"
region: "DO"
region: "DZ"
region: "EA"
region: "EC"
region: "EE"
region: "EG"
region: "ER"
region: "ES"
region: "ET"
region: "FI"
region: "FJ"
region: "FK"
region: "FM"
region: "FO"
region: "FR"
region: "GA"
region: "GB"
region: "GD"
region: "GE"
region: "GF"
region: "GG"
region: "GH"
region: "GI"
region: "GL"
region: "GM"
region: "GN"
region: "GP"
region: "GQ"
region: "GR"
region: "GT"
region: "GU"
region: "GW"
region: "GY"
region: "HK"
region: "HN"
region: "HR"
region: "HT"
region: "HU"
region: "IC"
region: "ID"
region: "IE"
region: "IL"
region: "IM"
region: "IN"
region: "IO"
region: "IQ"
region: "IR"
region: "IS"
region: "IT"
region: "JE"
region: "JM"
region: "JO"
region: "KE"
region: "KG"
region: "KI"
region: "KM"
region: "KN"
region: "KY"
region: "KZ"
region: "LA"
region: "LB"
region: "LC"
region: "LI"
region: "LK"
region: "LR"
region: "LS"
region: "LT"
region: "LU"
region: "LV"
region: "MA"
region: "MC"
region: "MD"
region: "ME"
region: "MF"
region: "MG"
region: "MH"
region: "MK"
region: "ML"
region: "MM"
region: "MN"
region: "MO"
region: "MP"
region: "MQ"
region: "MR"
region: "MS"
region: "MT"
region: "MU"
region: "MW"
region: "MX"
region: "MY"
region: "MZ"
region: "NA"
region: "NC"
region: "NE"
region: "NF"
region: "NG"
region: "NI"
region: "NL"
region: "NO"
region: "NP"
region: "NR"
region: "NU"
region: "NZ"
region: "PA"
region: "PE"
region: "PF"
region: "PG"
region: "PH"
region: "PK"
region: "PL"
region: "PM"
region: "PN"
region: "PR"
region: "PT"
region: "PW"
region: "PY"
region: "RE"
region: "RO"
region: "RS"
region: "RU"
region: "RW"
region: "SB"
region: "SC"
region: "SD"
region: "SE"
region: "SG"
region: "SH"
region: "SI"
region: "SJ"
region: "SK"
region: "SL"
region: "SM"
region: "SN"
region: "SO"
region: "SR"
region: "SS"
region: "ST"
region: "SV"
region: "SX"
region: "SY"
region: "SZ"
region: "TA"
region: "TC"
region: "TD"
region: "TF"
region: "TG"
region: "TH"
region: "TJ"
region: "TK"
region: "TL"
region: "TM"
region: "TN"
region: "TO"
region: "TR"
region: "TT"
region: "TV"
region: "TW"
region: "TZ"
region: "UA"
region: "UG"
region: "UM"
region: "US"
region: "UY"
region: "UZ"
region: "VA"
region: "VC"
region: "VE"
region: "VG"
region: "VI"
region: "VN"
region: "VU"
region: "WF"
region: "WS"
region: "XK"
region: "YE"
region: "YT"
region: "ZA"
region: "ZM"
region: "ZW"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Â Ã Ă Ș Ț a b c d e f g h i j k l m n o p q r s t u v w x y z â ã ă ș ț"
  marks: "◌̂ ◌̃ ◌̆ ◌̦"
}
sample_text {
  masthead_full: "TtUu"
  masthead_partial: "Ii"
  styles: "Ti-atsea câ pricânushtearea-a nâmuziljei nativâ"
  tester: "Ti-atsea câ nitinjisearea shi atimusearea-a-andrepturlor a omlui"
  poster_sm: "Ti-atsea câ"
  poster_md: "Adunarea"
  poster_lg: "Tuti"
  specimen_48: "Uproclameadzâ aestâ Declaratsii Universalâ ti-ndrepturli-a omlui"
  specimen_36: "Canâ nu poati s-hibâ tsânut tu sclâvilji icâ supuniri: sclâviljea shi comertslu cu sclavi s-azâptâseashti tu tuti formili."
  specimen_32: "Cafi un ari-ndreptu câ tribunalili natsionali efectiv s-lu-apurâ di frândzearea-a-ndrepturlor fundamentali cari lj-suntu pricânâscuti cu constitutsia shi nomurli."
  specimen_21: "Canâ nu poati dupâ vrearea-a vârnului s-hibâ âncljis, detsânut, niti avinat.\nCafi un ari-ndreptul egal didip la giudicarea-ndreaptâ shi publicâ dininti-a tribunalui independent shi obiectiv cari va s-detsidâ ti-ndrepturli-a lui shi obligatsiili sh-ti orighina-a cafi unlui act criminal tsi-lji si arucâ-a lui.\nCafi un ari-ndreptu la discurmari shi njirari, inclusiv shi limitarea cu chifiri-a oarâljei ti lucru shi advili perioditsi cu platâ."
  specimen_16: "Cafi un ari-ndreptu la progres sotsial shi internatsional tu cari ândrepturli spusi tu aestâ Declaratsii pot ta s-hibâ realizati complet.\nNitsi unâ determinari dit aestâ Declaratsii nu poati s-hibâ tulmâcitâ ca-ndreptul ti cafi un stat, grupâ icâ insu ta s-u facâ cari tsi s-hibâ activitati icâ s-facâ catsi s-va s-hibâ lucru shutsâtâ la câlcarea-a-ndrepturlor shi-a libertâtslor cari suntu bâgati tu ea.\nTi-atsea câ pricânushtearea-a nâmuziljei nativâ shi-ndrepturli egali shi nealienabili-a tutâlor membrilji-a taifâljei a omlui easti fimelju-a li-bertatiljei, a-ndriptatiuljei shi-a irinjiljei din lumi,"
}
