id: "sa_Ahom"
language: "sa"
script: "Ahom"
name: "Sanskrit, Ahom"
region: "IN"
sample_text {
  masthead_full: "𑜏𑜍𑜈𑜉"
  masthead_partial: "𑜃𑜑"
  styles: "𑜊𑜄𑜞 𑜊𑜕𑜄𑜣 𑜏𑜡𑜃𑜫𑜄𑜣𑜃𑜫𑜊𑜡𑜊𑜏𑜫𑜈𑜡𑜄𑜃𑜫𑜄𑜞𑜫𑜊𑜡𑜃𑜪𑜡 𑜒𑜡𑜔𑜡𑜍𑜑𑜫 𑜉𑜡𑜃𑜈𑜆𑜍𑜣𑜈𑜡𑜍𑜏𑜫𑜊 𑜏𑜍𑜫𑜈𑜦𑜧𑜏𑜡𑜉𑜆𑜣"
  tester: "𑜏𑜍𑜫𑜈𑜦𑜧 𑜉𑜡𑜃𑜈𑜡𑜑𑜫 𑜏𑜫𑜈𑜄𑜃𑜫𑜄𑜞𑜡𑜑𑜫 𑜏𑜉𑜤𑜄𑜫𑜆𑜃𑜫𑜃𑜡𑜑𑜫 𑜈𑜍𑜫𑜄𑜃𑜫𑜄𑜦𑜧 𑜒𑜆𑜣 𑜋, 𑜕𑜧𑜨𑜍𑜈𑜓𑜞𑜥𑜏𑜡 𑜒𑜔𑜣𑜀𑜡𑜍𑜓𑜞𑜥𑜏𑜡 𑜋 𑜏𑜉𑜡𑜃𑜡𑜑𑜫 𑜒𑜦𑜧𑜈 𑜈𑜍𑜫𑜄𑜃𑜫𑜄𑜦𑜧𑜼"
  poster_sm: "𑜒𑜏𑜫𑜊𑜪𑜡 𑜒𑜘𑜣𑜗𑜦𑜡𑜏𑜃𑜡𑜊𑜪𑜡"
  poster_md: "𑜒𑜦𑜧𑜄𑜓𑜄𑜣𑜍𑜢𑜀𑜫𑜄𑜉𑜫,"
  poster_lg: "𑜏𑜍𑜫𑜈𑜦𑜧"
  specimen_48: "𑜃 𑜀𑜉𑜆𑜣 𑜊𑜃𑜪 𑜓𑜡𑜏𑜄𑜫𑜈𑜦𑜧𑜃 𑜆𑜍𑜡𑜔𑜣𑜃𑜄𑜫𑜈𑜦𑜧𑜃 𑜈𑜡 𑜔𑜡𑜍𑜊𑜣𑜄𑜪𑜤 𑜒𑜃𑜤𑜊𑜫𑜐𑜡𑜏𑜫𑜊𑜄𑜦𑜧𑜼 𑜒𑜆𑜣 𑜋 𑜓𑜡𑜏𑜈𑜫𑜊𑜡𑜆𑜡𑜍𑜑𑜫 𑜆𑜤𑜍𑜫𑜃𑜍𑜥𑜆𑜦𑜧𑜃 𑜆𑜞𑜄𑜣𑜏𑜢𑜓𑜫𑜔𑜑𑜫"
  specimen_36: "𑜏𑜍𑜫𑜈𑜦𑜡\'𑜆𑜣 𑜊𑜃𑜑𑜫 𑜊𑜣𑜈𑜃𑜏𑜫𑜈𑜡𑜄𑜃𑜫𑜄𑜞𑜫𑜊𑜏𑜥𑜍𑜀𑜫𑜏𑜡𑜔𑜣𑜀𑜡𑜍𑜪 𑜏𑜪𑜔𑜄𑜫𑜄𑜦𑜧𑜼\n𑜃 𑜀𑜉𑜆𑜣 𑜊𑜃𑜪 𑜓𑜡𑜏𑜄𑜫𑜈𑜦𑜧𑜃 𑜆𑜍𑜡𑜔𑜣𑜃𑜄𑜫𑜈𑜦𑜧𑜃 𑜈𑜡 𑜔𑜡𑜍𑜊𑜣𑜄𑜪𑜤 𑜒𑜃𑜤𑜊𑜫𑜐𑜡𑜏𑜫𑜊𑜄𑜦𑜧𑜼 𑜒𑜆𑜣 𑜋 𑜓𑜡𑜏𑜈𑜫𑜊𑜡𑜆𑜡𑜍𑜑𑜫 𑜆𑜤𑜍𑜫𑜃𑜍𑜥𑜆𑜦𑜧𑜃 𑜆𑜞𑜄𑜣𑜏𑜢𑜓𑜫𑜔𑜑𑜫 𑜏𑜫𑜌𑜡𑜏𑜫𑜊𑜄𑜣𑜼"
  specimen_32: "𑜈𑜣𑜔𑜦𑜑𑜫 𑜏𑜉𑜀𑜫𑜏𑜪 𑜏𑜍𑜫𑜈𑜦𑜧\'𑜆𑜣 𑜄𑜤𑜎𑜫𑜊𑜡𑜑𑜫 𑜏𑜉𑜡𑜃𑜡𑜏𑜫𑜋 𑜈𑜍𑜫𑜄𑜃𑜫𑜄𑜦𑜧𑜼 𑜒𑜆𑜣 𑜋 𑜈𑜣𑜃𑜩𑜈 𑜀𑜉𑜆𑜣 𑜘𑜦𑜧𑜓𑜪 𑜈𑜣𑜔𑜦𑜑𑜫 𑜄𑜤𑜎𑜫𑜊𑜪 𑜏𑜪𑜍𑜀𑜫𑜏𑜃𑜉𑜈𑜡𑜆𑜫𑜄𑜪𑜤 𑜒𑜍𑜫𑜑𑜃𑜫𑜄𑜣𑜼 𑜒𑜏𑜫𑜊𑜡𑜑𑜫 𑜒𑜘𑜣𑜗𑜦𑜡𑜏𑜃𑜡𑜊𑜡𑜑𑜫 𑜒𑜥𑜎𑜝𑜪𑜗𑜃𑜦𑜧 𑜀𑜉𑜆𑜣 𑜘𑜦𑜧𑜓𑜪, 𑜒𑜦𑜧𑜄𑜡𑜓𑜞𑜤𑜕𑜫𑜘𑜦𑜧𑜓𑜪 𑜈𑜡 𑜒𑜘𑜣𑜎𑜀𑜫𑜏𑜫𑜊 𑜀𑜡𑜉𑜆𑜣 𑜋𑜦𑜏𑜫𑜄𑜪𑜡 𑜈𑜣𑜍𑜤𑜔𑜫𑜊 𑜏𑜉𑜡𑜃𑜏𑜪𑜍𑜀𑜫𑜏𑜃𑜡𑜍𑜫𑜑𑜡𑜑𑜫 𑜏𑜍𑜫𑜈𑜦𑜧\'𑜆𑜣 𑜈𑜍𑜫𑜄𑜃𑜫𑜄𑜦𑜧𑜼"
  specimen_21: "𑜏𑜍𑜫𑜈𑜦𑜧 𑜉𑜡𑜃𑜈𑜡𑜑𑜫 𑜏𑜫𑜈𑜄𑜃𑜫𑜄𑜞𑜡𑜑𑜫 𑜏𑜉𑜤𑜄𑜫𑜆𑜃𑜫𑜃𑜡𑜑𑜫 𑜈𑜍𑜫𑜄𑜃𑜫𑜄𑜦𑜧 𑜒𑜆𑜣 𑜋, 𑜕𑜧𑜨𑜍𑜈𑜓𑜞𑜥𑜏𑜡 𑜒𑜔𑜣𑜀𑜡𑜍𑜓𑜞𑜥𑜏𑜡 𑜋 𑜏𑜉𑜡𑜃𑜡𑜑𑜫 𑜒𑜦𑜧𑜈 𑜈𑜍𑜫𑜄𑜃𑜫𑜄𑜦𑜧𑜼 𑜒𑜦𑜧𑜄𑜦𑜧 𑜏𑜍𑜫𑜈𑜦𑜧 𑜋𑜦𑜧𑜄𑜃𑜡𑜄𑜍𑜫𑜀𑜏𑜀𑜫𑜄𑜢𑜘𑜫𑜊𑜪𑜡 𑜏𑜥𑜏𑜉𑜫𑜆𑜃𑜫𑜃𑜡𑜑𑜫 𑜏𑜃𑜫𑜄𑜣𑜼 𑜒𑜆𑜣 𑜋, 𑜏𑜍𑜫𑜈𑜦𑜧\'𑜆𑜣 𑜈𑜃𑜫𑜔𑜤𑜄𑜫𑜈𑜘𑜡𑜈𑜃𑜊𑜡 𑜆𑜍𑜏𑜫𑜆𑜍𑜪 𑜈𑜫𑜊𑜈𑜑𑜍𑜃𑜫𑜄𑜥𑜼\n𑜒𑜏𑜫𑜊𑜪𑜡 𑜒𑜘𑜣𑜗𑜦𑜡𑜏𑜃𑜡𑜊𑜪𑜡 𑜃𑜢𑜍𑜫𑜓𑜢𑜏𑜫𑜄𑜡𑜑𑜫 𑜏𑜍𑜫𑜈𑜦𑜧\'𑜆𑜣 𑜒𑜔𑜣𑜀𑜡𑜍𑜡𑜑𑜫 𑜏𑜍𑜫𑜈𑜡𑜃𑜫𑜊𑜆𑜣 𑜋 𑜏𑜫𑜈𑜡𑜄𑜃𑜫𑜄𑜞𑜫𑜊𑜡𑜃𑜣, 𑜈𑜣𑜃𑜩𑜈 𑜊𑜡𑜄𑜣𑜈𑜍𑜫𑜃𑜎𑜪𑜢𑜕𑜘𑜡𑜏𑜡𑜔𑜍𑜫𑜉𑜍𑜡𑜊𑜃𑜣𑜄𑜣𑜀𑜄𑜓𑜣𑜄𑜍𑜉𑜃𑜫𑜄𑜈𑜫𑜊𑜡𑜓𑜣𑜘𑜦𑜧𑜓𑜉𑜫, 𑜍𑜡𑜏𑜫𑜄𑜞𑜣𑜊𑜪 𑜏𑜡𑜉𑜡𑜊𑜣𑜀𑜡𑜔𑜡𑜍𑜪 𑜏𑜉𑜫𑜆𑜊𑜫𑜊𑜃𑜫𑜉𑜄𑜓𑜣𑜄𑜍 𑜏𑜫𑜄𑜍𑜐𑜫𑜋 𑜒𑜈𑜣𑜕𑜃𑜊𑜫𑜊, 𑜒𑜔𑜣𑜕𑜃𑜫𑜄𑜪𑜤 𑜏𑜍𑜫𑜈𑜦𑜡\'𑜆𑜣 𑜊𑜃𑜑𑜫 𑜆𑜞𑜘𑜈𑜄𑜣𑜼\n𑜒𑜦𑜧𑜄𑜓𑜄𑜣𑜍𑜢𑜀𑜫𑜄𑜉𑜫, 𑜀𑜏𑜫𑜊𑜡𑜏𑜫𑜋𑜣𑜓𑜆𑜣 𑜆𑜞𑜘𑜥𑜏𑜄𑜫𑜄𑜡𑜊𑜡𑜑𑜫 𑜃𑜣𑜊𑜉𑜃𑜡𑜃𑜫𑜄𑜍𑜫𑜕𑜄𑜉𑜫, 𑜏𑜫𑜈𑜡𑜔𑜣𑜃𑜏𑜫𑜊 𑜒𑜡𑜄𑜫𑜉𑜆𑜞𑜏𑜡𑜏𑜃𑜦𑜧𑜄𑜍𑜄𑜃𑜫𑜄𑜞𑜏𑜫𑜊, 𑜃𑜫𑜊𑜡𑜏𑜣𑜄𑜃𑜫𑜄𑜞𑜏𑜫𑜊 𑜈𑜡 𑜈𑜡𑜏𑜫𑜄𑜈𑜫𑜊𑜏𑜫𑜊 𑜆𑜞𑜓𑜦𑜧𑜏𑜏𑜫𑜊 𑜓𑜦𑜧𑜏𑜏𑜫𑜊 𑜈𑜡 𑜍𑜡𑜊𑜃𑜣𑜄𑜣𑜀𑜏𑜣𑜉𑜡𑜃𑜣𑜈𑜃𑜫𑜔𑜃𑜡𑜃𑜫𑜄𑜡𑜍𑜡𑜏𑜫𑜄𑜞𑜣𑜀𑜏𑜫𑜄𑜍𑜡𑜔𑜡𑜍𑜦𑜧𑜃 𑜃 𑜀𑜦𑜡\'𑜆𑜣 𑜘𑜦𑜧𑜓𑜦𑜡 𑜈𑜣𑜔𑜡𑜏𑜫𑜊𑜄𑜦𑜧𑜼"
  specimen_16: "𑜏𑜍𑜫𑜈𑜦𑜧 𑜉𑜡𑜃𑜈𑜡𑜑𑜫 𑜏𑜫𑜈𑜄𑜃𑜫𑜄𑜞𑜡𑜑𑜫 𑜏𑜉𑜤𑜄𑜫𑜆𑜃𑜫𑜃𑜡𑜑𑜫 𑜈𑜍𑜫𑜄𑜃𑜫𑜄𑜦𑜧 𑜒𑜆𑜣 𑜋, 𑜕𑜧𑜨𑜍𑜈𑜓𑜞𑜥𑜏𑜡 𑜒𑜔𑜣𑜀𑜡𑜍𑜓𑜞𑜥𑜏𑜡 𑜋 𑜏𑜉𑜡𑜃𑜡𑜑𑜫 𑜒𑜦𑜧𑜈 𑜈𑜍𑜫𑜄𑜃𑜫𑜄𑜦𑜧𑜼 𑜒𑜦𑜧𑜄𑜦𑜧 𑜏𑜍𑜫𑜈𑜦𑜧 𑜋𑜦𑜧𑜄𑜃𑜡𑜄𑜍𑜫𑜀𑜏𑜀𑜫𑜄𑜢𑜘𑜫𑜊𑜪𑜡 𑜏𑜥𑜏𑜉𑜫𑜆𑜃𑜫𑜃𑜡𑜑𑜫 𑜏𑜃𑜫𑜄𑜣𑜼 𑜒𑜆𑜣 𑜋, 𑜏𑜍𑜫𑜈𑜦𑜧\'𑜆𑜣 𑜈𑜃𑜫𑜔𑜤𑜄𑜫𑜈𑜘𑜡𑜈𑜃𑜊𑜡 𑜆𑜍𑜏𑜫𑜆𑜍𑜪 𑜈𑜫𑜊𑜈𑜑𑜍𑜃𑜫𑜄𑜥𑜼\n𑜒𑜏𑜫𑜊𑜪𑜡 𑜒𑜘𑜣𑜗𑜦𑜡𑜏𑜃𑜡𑜊𑜪𑜡 𑜃𑜢𑜍𑜫𑜓𑜢𑜏𑜫𑜄𑜡𑜑𑜫 𑜏𑜍𑜫𑜈𑜦𑜧\'𑜆𑜣 𑜒𑜔𑜣𑜀𑜡𑜍𑜡𑜑𑜫 𑜏𑜍𑜫𑜈𑜡𑜃𑜫𑜊𑜆𑜣 𑜋 𑜏𑜫𑜈𑜡𑜄𑜃𑜫𑜄𑜞𑜫𑜊𑜡𑜃𑜣, 𑜈𑜣𑜃𑜩𑜈 𑜊𑜡𑜄𑜣𑜈𑜍𑜫𑜃𑜎𑜪𑜢𑜕𑜘𑜡𑜏𑜡𑜔𑜍𑜫𑜉𑜍𑜡𑜊𑜃𑜣𑜄𑜣𑜀𑜄𑜓𑜣𑜄𑜍𑜉𑜃𑜫𑜄𑜈𑜫𑜊𑜡𑜓𑜣𑜘𑜦𑜧𑜓𑜉𑜫, 𑜍𑜡𑜏𑜫𑜄𑜞𑜣𑜊𑜪 𑜏𑜡𑜉𑜡𑜊𑜣𑜀𑜡𑜔𑜡𑜍𑜪 𑜏𑜉𑜫𑜆𑜊𑜫𑜊𑜃𑜫𑜉𑜄𑜓𑜣𑜄𑜍 𑜏𑜫𑜄𑜍𑜐𑜫𑜋 𑜒𑜈𑜣𑜕𑜃𑜊𑜫𑜊, 𑜒𑜔𑜣𑜕𑜃𑜫𑜄𑜪𑜤 𑜏𑜍𑜫𑜈𑜦𑜡\'𑜆𑜣 𑜊𑜃𑜑𑜫 𑜆𑜞𑜘𑜈𑜄𑜣𑜼\n𑜒𑜦𑜧𑜄𑜓𑜄𑜣𑜍𑜢𑜀𑜫𑜄𑜉𑜫, 𑜀𑜏𑜫𑜊𑜡𑜏𑜫𑜋𑜣𑜓𑜆𑜣 𑜆𑜞𑜘𑜥𑜏𑜄𑜫𑜄𑜡𑜊𑜡𑜑𑜫 𑜃𑜣𑜊𑜉𑜃𑜡𑜃𑜫𑜄𑜍𑜫𑜕𑜄𑜉𑜫, 𑜏𑜫𑜈𑜡𑜔𑜣𑜃𑜏𑜫𑜊 𑜒𑜡𑜄𑜫𑜉𑜆𑜞𑜏𑜡𑜏𑜃𑜦𑜧𑜄𑜍𑜄𑜃𑜫𑜄𑜞𑜏𑜫𑜊, 𑜃𑜫𑜊𑜡𑜏𑜣𑜄𑜃𑜫𑜄𑜞𑜏𑜫𑜊 𑜈𑜡 𑜈𑜡𑜏𑜫𑜄𑜈𑜫𑜊𑜏𑜫𑜊 𑜆𑜞𑜓𑜦𑜧𑜏𑜏𑜫𑜊 𑜓𑜦𑜧𑜏𑜏𑜫𑜊 𑜈𑜡 𑜍𑜡𑜊𑜃𑜣𑜄𑜣𑜀𑜏𑜣𑜉𑜡𑜃𑜣𑜈𑜃𑜫𑜔𑜃𑜡𑜃𑜫𑜄𑜡𑜍𑜡𑜏𑜫𑜄𑜞𑜣𑜀𑜏𑜫𑜄𑜍𑜡𑜔𑜡𑜍𑜦𑜧𑜃 𑜃 𑜀𑜦𑜡\'𑜆𑜣 𑜘𑜦𑜧𑜓𑜦𑜡 𑜈𑜣𑜔𑜡𑜏𑜫𑜊𑜄𑜦𑜧𑜼\n𑜏𑜍𑜫𑜈𑜦𑜡\'𑜆𑜣 𑜊𑜃𑜑𑜫 𑜊𑜣𑜈𑜃𑜏𑜫𑜈𑜡𑜄𑜃𑜫𑜄𑜞𑜫𑜊𑜏𑜥𑜍𑜀𑜫𑜏𑜡𑜔𑜣𑜀𑜡𑜍𑜪 𑜏𑜪𑜔𑜄𑜫𑜄𑜦𑜧𑜼\n𑜃 𑜀𑜉𑜆𑜣 𑜊𑜃𑜪 𑜓𑜡𑜏𑜄𑜫𑜈𑜦𑜧𑜃 𑜆𑜍𑜡𑜔𑜣𑜃𑜄𑜫𑜈𑜦𑜧𑜃 𑜈𑜡 𑜔𑜡𑜍𑜊𑜣𑜄𑜪𑜤 𑜒𑜃𑜤𑜊𑜫𑜐𑜡𑜏𑜫𑜊𑜄𑜦𑜧𑜼 𑜒𑜆𑜣 𑜋 𑜓𑜡𑜏𑜈𑜫𑜊𑜡𑜆𑜡𑜍𑜑𑜫 𑜆𑜤𑜍𑜫𑜃𑜍𑜥𑜆𑜦𑜧𑜃 𑜆𑜞𑜄𑜣𑜏𑜢𑜓𑜫𑜔𑜑𑜫 𑜏𑜫𑜌𑜡𑜏𑜫𑜊𑜄𑜣𑜼\n𑜃 𑜀𑜉𑜆𑜣 𑜊𑜃𑜪 𑜈𑜣𑜍𑜤𑜔𑜫𑜊 𑜒𑜈𑜉𑜡𑜃𑜃𑜡𑜄𑜫𑜉𑜀𑜪 𑜈𑜫𑜊𑜈𑜑𑜡𑜍𑜪 𑜓𑜃𑜫𑜓𑜪 𑜈𑜡 𑜀𑜞𑜥𑜍𑜪 𑜒𑜉𑜡𑜃𑜈𑜣𑜊𑜪 𑜆𑜞𑜄𑜦𑜡𑜓𑜃𑜪 𑜈𑜡 𑜆𑜞𑜈𑜍𑜫𑜄𑜊𑜣𑜄𑜪𑜤 𑜒𑜃𑜤𑜊𑜫𑜐𑜡𑜏𑜫𑜊𑜄𑜦𑜧𑜼"
}
historical: true
