id: "sa_Avst"
language: "sa"
script: "Avst"
name: "Sanskrit, Avestan"
region: "IN"
sample_text {
  masthead_full: "𐬯𐬀𐬭𐬎"
  masthead_partial: "𐬉𐬨"
  styles: "𐬫𐬀𐬙𐬭𐬀 𐬘𐬀𐬔𐬀𐬙𐬌 𐬱𐬁𐬧𐬙𐬌𐬥𐬌𐬌𐬁𐬌𐬌𐬀𐬯𐬎𐬎𐬁𐬙𐬀𐬧𐬙𐬭𐬌𐬌𐬁𐬧𐬅 𐬁𐬜𐬁𐬭𐬀𐬵"
  tester: "𐬯𐬀𐬭𐬎𐬎𐬉 𐬨𐬁𐬥𐬀𐬎𐬎𐬁𐬵 𐬯𐬎𐬎𐬀𐬙𐬀𐬧𐬙𐬭𐬁𐬵 𐬯𐬀𐬨𐬎𐬙𐬞𐬀𐬥𐬥𐬁𐬵 𐬬𐬀𐬭𐬙𐬀𐬧𐬙𐬉 𐬀𐬞𐬌 𐬗𐬀, 𐬔𐬀𐬎𐬭𐬀𐬎𐬎𐬀𐬛𐬆𐬭𐬆𐬱𐬁"
  poster_sm: "𐬉𐬙𐬀𐬛𐬀𐬙𐬌𐬭𐬌𐬐𐬙𐬆𐬨,"
  poster_md: "𐬯𐬀𐬭𐬎𐬎𐬋𐬞𐬌"
  poster_lg: "𐬯𐬀𐬭𐬎𐬎𐬉"
  specimen_48: "𐬥𐬀 𐬐𐬀𐬨𐬀𐬞𐬌 𐬘𐬀𐬥𐬄 𐬛𐬁𐬯𐬀𐬙𐬎𐬎𐬉𐬥𐬀 𐬞𐬀𐬭𐬁𐬜𐬍𐬥𐬀𐬙𐬎𐬎𐬉𐬥𐬀 𐬬𐬁 𐬜𐬁𐬭𐬀𐬌𐬌𐬌𐬙𐬎𐬩 𐬀𐬥𐬎𐬘𐬦𐬁𐬯𐬌𐬌𐬀𐬙𐬉𐬼‏"
  specimen_36: "𐬥𐬀 𐬐𐬀𐬨𐬀𐬞𐬌 𐬘𐬀𐬥𐬄 𐬬𐬌𐬭𐬎𐬜𐬌𐬌𐬀 𐬀𐬎𐬎𐬀𐬨𐬁𐬥𐬀𐬥𐬁𐬙𐬨𐬀𐬐𐬄 𐬬𐬌𐬌𐬀𐬎𐬎𐬀𐬵𐬁𐬭𐬄 𐬛𐬀𐬧𐬛𐬄 𐬬𐬁 𐬐𐬭𐬏𐬭𐬄 𐬀𐬨𐬁𐬥𐬀𐬎𐬎𐬍𐬌𐬌𐬄 𐬞𐬭𐬀𐬙𐬋𐬛𐬀𐬥𐬄 𐬬𐬁 𐬞𐬭𐬀𐬎𐬎𐬀𐬭𐬙𐬀𐬌𐬌𐬌𐬙𐬎𐬩 𐬀𐬥𐬎𐬘𐬦𐬁𐬯𐬌𐬌𐬀𐬙𐬉𐬼‏"
  specimen_32: "𐬬𐬌𐬜𐬌𐬥𐬁 𐬯𐬄𐬬𐬌𐬜𐬁𐬥𐬉𐬥𐬀 𐬬𐬁 𐬞𐬭𐬀𐬛𐬀𐬙𐬙𐬁𐬥𐬅 𐬨𐬀𐬎𐬮𐬌𐬐𐬁𐬜𐬌𐬐𐬁𐬭𐬁𐬧𐬁𐬨𐬎𐬮𐬮𐬄𐬖𐬀𐬥𐬀𐬐𐬁𐬭𐬌𐬌𐬁𐬧𐬅 𐬐𐬆𐬭𐬆𐬙𐬉, 𐬫𐬋𐬔𐬌𐬌𐬀𐬌𐬵 𐬭𐬁𐬴𐬙𐬭𐬌𐬌𐬌𐬀𐬥𐬌𐬌𐬁𐬌𐬌𐬀𐬞𐬍𐬚𐬀𐬌𐬵 𐬯𐬄𐬯𐬙𐬎𐬙𐬁𐬥𐬅 𐬞𐬭𐬀𐬠𐬁𐬎𐬎𐬌𐬥𐬅 𐬯𐬀𐬨𐬎𐬞𐬁𐬌𐬌𐬁𐬥𐬅 𐬞𐬭𐬀𐬌𐬌𐬋𐬔𐬁𐬭𐬵𐬋 𐬵𐬌 𐬯𐬀𐬭𐬎𐬎𐬋 𐬘𐬀𐬥𐬋𐬯𐬙𐬌𐬼‏"
  specimen_21: "𐬥𐬀 𐬐𐬋𐬞𐬌 𐬘𐬀𐬥𐬀𐬵 𐬯𐬎𐬎𐬉𐬗𐬗𐬀𐬌𐬌𐬁 𐬥𐬌𐬔𐬭𐬀𐬵𐬍𐬙𐬎𐬩, 𐬜𐬀𐬭𐬙𐬎𐬩, 𐬥𐬌𐬴𐬐𐬁𐬯𐬀𐬌𐬌𐬌𐬙𐬎𐬩 𐬬𐬁 𐬀𐬥𐬎𐬘𐬦𐬁𐬯𐬌𐬌𐬀𐬙𐬉𐬼‏\n𐬯𐬀𐬭𐬎𐬎𐬋𐬞𐬌 𐬘𐬀𐬥𐬀𐬵, 𐬯𐬎𐬎𐬄 𐬬𐬌𐬭𐬎𐬜𐬌𐬌𐬀 𐬞𐬭𐬀𐬎𐬎𐬀𐬭𐬙𐬙𐬌𐬙𐬀𐬯𐬌𐬌𐬀 𐬐𐬀𐬯𐬌𐬌𐬁𐬞𐬌 𐬁𐬞𐬀𐬭𐬁𐬜𐬌𐬐𐬁𐬐𐬴𐬉𐬞𐬀𐬯𐬌𐬌𐬀, 𐬯𐬎𐬎𐬍𐬌𐬌𐬁𐬜𐬌𐬐𐬁𐬭𐬁𐬧𐬅 𐬛𐬁𐬌𐬌𐬌𐬙𐬎𐬎𐬁𐬥𐬅 𐬗𐬀, 𐬬𐬌𐬥𐬌𐬭𐬜𐬁𐬭𐬀𐬧𐬀𐬯𐬌𐬌𐬀 𐬗𐬀 𐬐𐬆𐬭𐬆𐬙𐬉, 𐬯𐬎𐬎𐬁𐬜𐬍𐬥𐬉𐬥𐬀 𐬥𐬌𐬴𐬞𐬀𐬐𐬴𐬉𐬧𐬀 𐬗𐬀 𐬥𐬌𐬌𐬁𐬌𐬌𐬀𐬞𐬍𐬚𐬉𐬥𐬀 𐬬𐬌𐬜𐬍𐬌𐬌𐬀𐬨𐬁𐬥𐬀𐬯𐬌𐬌𐬀 𐬯𐬀𐬨𐬎𐬗𐬌𐬙𐬀𐬯𐬌𐬌𐬀 𐬯𐬁𐬭𐬎𐬎𐬀𐬘𐬀𐬥𐬌𐬐𐬀𐬯𐬌𐬌𐬀 𐬱𐬭𐬀𐬎𐬎𐬀𐬧𐬀𐬯𐬌𐬌𐬀 𐬗𐬀 𐬐𐬆𐬭𐬆𐬙𐬉 𐬯𐬀𐬭𐬎𐬎𐬋𐬞𐬌 𐬘𐬀𐬥𐬀𐬵 𐬞𐬏𐬭𐬧𐬅 𐬯𐬀𐬨𐬁𐬥𐬀𐬝𐬅 𐬜𐬁𐬭𐬀𐬌𐬌𐬀𐬙𐬌𐬼‏"
  specimen_16: "𐬥𐬀 𐬐𐬀𐬯𐬌𐬌𐬁𐬞𐬌 𐬬𐬌𐬌𐬀𐬐𐬙𐬌𐬔𐬀𐬙𐬉 𐬞𐬁𐬭𐬌𐬎𐬎𐬁𐬭𐬌𐬐𐬉 𐬗𐬀 𐬘𐬍𐬎𐬎𐬀𐬥𐬉, 𐬔𐬆𐬭𐬆𐬵𐬉, 𐬞𐬀𐬙𐬭𐬀𐬎𐬎𐬌𐬌𐬀𐬎𐬎𐬀𐬵𐬁𐬭𐬉 𐬗𐬀 𐬯𐬎𐬎𐬉𐬗𐬗𐬀𐬌𐬌𐬁 𐬵𐬀𐬯𐬙𐬀𐬐𐬴𐬉𐬞𐬋𐬥𐬎𐬘𐬦𐬁𐬯𐬌𐬌𐬀𐬙𐬉, 𐬥𐬀 𐬬𐬁 𐬐𐬀𐬯𐬌𐬌𐬁𐬞𐬌 𐬒𐬌𐬌𐬁𐬙𐬌𐬩 𐬯𐬀𐬨𐬨𐬁𐬥𐬄 𐬬𐬁𐬐𐬭𐬁𐬧𐬙𐬎𐬩 𐬐𐬋𐬞𐬌 𐬱𐬀𐬐𐬴𐬌𐬌𐬀𐬙𐬌𐬼‏ 𐬉𐬙𐬁𐬵𐬀𐬐𐬵𐬀𐬯𐬙𐬀𐬐𐬴𐬉𐬞𐬁𐬐𐬭𐬀𐬨𐬀𐬧𐬁𐬥𐬌 𐬬𐬌𐬭𐬎𐬜𐬌𐬌𐬀 𐬞𐬭𐬀𐬙𐬌𐬌𐬉𐬐𐬀𐬨𐬀𐬞𐬌𐬘𐬀𐬥𐬀𐬵 𐬬𐬌𐬜𐬌𐬯𐬄𐬭𐬀𐬐𐬴𐬀𐬧𐬄 𐬯𐬄𐬜𐬀𐬙𐬙𐬉𐬼‏\n𐬞𐬭𐬀𐬙𐬌𐬌𐬉𐬐𐬀𐬨𐬀𐬞𐬌 𐬬𐬌𐬗𐬁𐬭𐬁𐬧𐬅 𐬗𐬉𐬙𐬀𐬥𐬁𐬌𐬌𐬁𐬵 𐬜𐬀𐬭𐬨𐬀𐬯𐬌𐬌𐬀 𐬗𐬀𐬯𐬎𐬎𐬁𐬙𐬀𐬧𐬙𐬭𐬌𐬌𐬁𐬜𐬌𐬐𐬁𐬭𐬄 𐬯𐬄𐬜𐬀𐬙𐬙𐬉𐬼‏ 𐬀𐬯𐬨𐬌𐬥 𐬀𐬜𐬌𐬐𐬁𐬭𐬉, 𐬯𐬎𐬎𐬍𐬌𐬌𐬄 𐬜𐬀𐬭𐬨𐬄 𐬬𐬌𐬱𐬎𐬎𐬁𐬯𐬄 𐬬𐬁 𐬱𐬌𐬐𐬴𐬀𐬌𐬌𐬌𐬙𐬎𐬩 𐬀𐬠𐬌𐬌𐬀𐬯𐬙𐬎𐬩 𐬀𐬭𐬗𐬌𐬙𐬎𐬩 𐬞𐬀𐬭𐬌𐬞𐬁𐬮𐬀𐬌𐬌𐬌𐬙𐬎𐬩 𐬬𐬁, 𐬬𐬀𐬌𐬌𐬌𐬀𐬐𐬙𐬌𐬐𐬉 𐬯𐬁𐬨𐬁𐬘𐬌𐬐𐬉 𐬗𐬀 𐬘𐬍𐬎𐬎𐬀𐬥𐬉, 𐬀𐬥𐬌𐬌𐬀𐬌𐬱𐬗𐬀 𐬯𐬀𐬵𐬀 𐬯𐬁𐬨𐬎𐬛𐬁𐬌𐬌𐬌𐬐𐬀𐬘𐬍𐬎𐬎𐬀𐬥𐬉 𐬉𐬐𐬁𐬐𐬌𐬥𐬁 𐬬𐬁 𐬯𐬎𐬎𐬍𐬌𐬌𐬄 𐬜𐬀𐬭𐬨𐬄 𐬬𐬌𐬱𐬎𐬎𐬁𐬯𐬄𐬯𐬎𐬎𐬁𐬙𐬀𐬧𐬙𐬭𐬌𐬌𐬄 𐬗𐬀 𐬞𐬀𐬭𐬌𐬎𐬎𐬀𐬭𐬙𐬀𐬌𐬌𐬌𐬙𐬎𐬨𐬀𐬞𐬌 𐬞𐬭𐬀𐬙𐬌𐬌𐬉𐬐𐬄 𐬘𐬀𐬥𐬀𐬵 𐬯𐬎𐬎𐬁𐬙𐬀𐬧𐬙𐬭𐬌𐬌𐬄 𐬜𐬁𐬭𐬀𐬌𐬌𐬀𐬙𐬌𐬼‏"
}
historical: true
