id: "sa_Bugi"
language: "sa"
script: "Bugi"
name: "Sanskrit, Buginese"
region: "IN"
sample_text {
  masthead_full: "ᨔᨑᨓᨆ"
  masthead_partial: "ᨊᨖ"
  styles: "ᨐᨈᨑ ᨍᨁᨈᨗ ᨔᨊᨈᨗᨊᨐᨐᨔᨓᨈᨊᨈᨑᨐᨊᨆ ᨕᨉᨑᨖ ᨆᨊᨓᨄᨑᨗᨓᨑᨔᨐ ᨔᨑᨓᨙᨔᨆᨄᨗ"
  tester: "ᨔᨑᨓᨙ ᨆᨊᨓᨖ ᨔᨓᨈᨊᨈᨑᨖ ᨔᨆᨘᨈᨄᨊᨊᨖ ᨓᨑᨈᨊᨈᨙ ᨕᨄᨗ ᨌ, ᨁᨕᨘᨑᨓᨉᨑᨘᨔ ᨕᨉᨗᨀᨑᨉᨑᨘᨔ ᨌ ᨔᨆᨊᨖ ᨕᨙᨓ"
  poster_sm: "ᨕᨔᨐᨆ ᨕᨅᨗᨁᨚᨔᨊᨐᨆ"
  poster_md: "ᨕᨙᨈᨉᨈᨗᨑᨗᨀᨈᨆ,"
  poster_lg: "ᨔᨑᨓᨙ"
  specimen_48: "ᨊ ᨀᨆᨄᨗ ᨍᨊᨆ ᨉᨔᨈᨓᨙᨊ ᨄᨑᨉᨗᨊᨈᨓᨙᨊ ᨓ ᨉᨑᨐᨗᨈᨘᨆ ᨕᨊᨘᨍᨎᨔᨐᨈᨙ᨞ ᨕᨄᨗ ᨌ ᨉᨔᨓᨐᨄᨑᨖ ᨄᨘᨑᨊᨑᨘᨄᨙᨊ ᨄᨑᨈᨗᨔᨗᨉᨉᨖ"
  specimen_36: "ᨓᨗᨉᨗᨊ ᨔᨆᨓᨗᨉᨊᨙᨊ ᨓ ᨄᨑᨉᨈᨈᨊᨆ ᨆᨕᨘᨒᨗᨀᨉᨗᨀᨑᨊᨆᨘᨒᨒᨆᨁᨊᨀᨑᨐᨊᨆ ᨀᨑᨘᨈᨙ, ᨐᨚᨁᨐᨕᨗᨖ ᨑᨔᨈᨑᨗᨐᨊᨐᨐᨄᨗᨈᨕᨗᨖ ᨔᨆᨔᨈᨘᨈᨊᨆ ᨄᨑᨅᨓᨗᨊᨆ ᨔᨆᨘᨄᨐᨊᨆ ᨄᨑᨐᨚᨁᨑᨖᨚ ᨖᨗ ᨔᨑᨓᨚ ᨍᨊᨚᨔᨈᨗ᨞"
  specimen_32: "ᨔᨑᨓᨚᨄᨗ ᨍᨊᨖ, ᨔᨓᨆ ᨓᨗᨑᨘᨉᨐ ᨄᨑᨓᨑᨈᨈᨗᨈᨔᨐ ᨀᨔᨐᨄᨗ ᨕᨄᨑᨉᨗᨀᨀᨔᨙᨄᨔᨐ, ᨔᨓᨗᨐᨉᨗᨀᨑᨊᨆ ᨉᨐᨗᨈᨓᨊᨆ ᨌ, ᨓᨗᨊᨗᨑᨉᨑᨊᨔᨐ ᨌ ᨀᨑᨘᨈᨙ, ᨔᨓᨉᨗᨊᨙᨊ ᨊᨗᨔᨄᨀᨔᨙᨊ ᨌ ᨊᨐᨐᨄᨗᨈᨙᨊ ᨓᨗᨉᨗᨐᨆᨊᨔᨐ ᨔᨆᨘᨌᨗᨈᨔᨐ ᨔᨑᨓᨍᨊᨗᨀᨔᨐ ᨔᨑᨓᨊᨔᨐ ᨌ ᨀᨑᨘᨈᨙ ᨔᨑᨓᨚᨄᨗ ᨍᨊᨖ ᨄᨘᨑᨊᨆ ᨔᨆᨊᨈᨆ ᨉᨑᨐᨈᨗ᨞"
  specimen_21: "ᨊ ᨀᨔᨐᨄᨗ ᨓᨐᨀᨈᨗᨁᨈᨙ ᨄᨑᨗᨓᨑᨗᨀᨙ ᨌ ᨍᨗᨓᨊᨙ, ᨁᨑᨘᨖᨙ, ᨄᨈᨑᨓᨐᨓᨖᨑᨙ ᨌ ᨔᨓᨙᨌᨌᨐ ᨖᨔᨈᨀᨔᨙᨄᨚᨊᨘᨍᨎᨔᨐᨈᨙ, ᨊ ᨓ ᨀᨔᨐᨄᨗ ᨀᨐᨈᨗᨆ ᨔᨆᨆᨊᨆ ᨓᨀᨑᨊᨈᨘᨆ ᨀᨚᨄᨗ ᨔᨀᨔᨐᨈᨗ᨞ ᨕᨙᨈᨖᨀᨖᨔᨈᨀᨔᨙᨄᨀᨑᨆᨊᨊᨗ ᨓᨗᨑᨘᨉᨐ ᨄᨑᨈᨐᨙᨀᨆᨄᨗᨍᨊᨖ ᨓᨗᨉᨗᨔᨆᨑᨀᨔᨊᨆ ᨔᨆᨉᨈᨈᨙ᨞\nᨄᨑᨈᨐᨙᨀᨆᨄᨗ ᨓᨗᨌᨑᨊᨆ ᨌᨙᨈᨊᨐᨖ ᨉᨑᨆᨔᨐ ᨌᨔᨓᨈᨊᨈᨑᨐᨉᨗᨀᨑᨆ ᨔᨆᨉᨈᨈᨙ᨞ ᨕᨔᨆᨗᨊ ᨕᨉᨗᨀᨑᨙ, ᨔᨓᨗᨐᨆ ᨉᨑᨆᨆ ᨓᨗᨔᨓᨔᨆ ᨓ ᨔᨗᨀᨔᨐᨗᨈᨘᨆ ᨕᨅᨐᨔᨈᨘᨆ ᨕᨑᨌᨗᨈᨘᨆ ᨄᨑᨗᨄᨒᨐᨗᨈᨘᨆ ᨓ, ᨓᨕᨗᨐᨀᨈᨗᨀᨙ ᨔᨆᨍᨗᨀᨙ ᨌ ᨍᨗᨓᨊᨙ, ᨕᨊᨐᨕᨗᨔᨌ ᨔᨖ ᨔᨆᨘᨉᨐᨗᨀᨍᨗᨓᨊᨙ ᨕᨙᨀᨀᨗᨊ ᨓ ᨔᨓᨗᨐᨆ ᨉᨑᨆᨆ ᨓᨗᨔᨓᨔᨆᨔᨓᨈᨊᨈᨑᨐᨆ ᨌ ᨄᨑᨗᨓᨑᨈᨐᨗᨈᨘᨆᨄᨗ ᨄᨑᨈᨐᨙᨀᨆ ᨍᨊᨖ ᨔᨓᨈᨊᨈᨑᨐᨆ ᨉᨑᨐᨈᨗ᨞"
  specimen_16: "ᨄᨑᨈᨐᨙᨀᨆᨄᨗ ᨆᨊᨈᨓᨐᨅᨗᨓᨐᨀᨈᨐᨚᨖ ᨕᨉᨗᨀᨑᨆ ᨔᨆᨉᨈᨈᨙ᨞ ᨔᨗᨆᨓᨐᨓᨉᨊᨆ ᨕᨓᨗᨁᨊᨐᨐ, ᨀᨙᨊᨄᨗ ᨔᨆᨌᨑᨆᨉᨐᨆᨙᨊ ᨓᨗᨌᨑᨊᨆ ᨔᨘᨌᨊᨊᨆ ᨌ ᨕᨉᨊᨄᨑᨉᨊᨑᨈᨆ ᨓᨗᨊᨕᨗᨓ ᨖᨔᨈᨀᨔᨙᨄᨆ ᨀᨗᨔᨌᨉᨄᨗ ᨍᨊᨖ, ᨔᨓᨗᨐᨆᨊᨈᨓᨐᨔᨆᨁᨑᨊᨑᨈᨆ ᨕᨉᨗᨀᨑᨙᨔᨆᨗᨊ ᨕᨑᨖᨗᨔᨐᨈᨙ᨞\nᨄᨑᨈᨐᨙᨀᨆᨙᨓ ᨍᨊᨖ, ᨔᨆᨍᨗᨀᨈᨓᨈ, ᨔᨆᨍᨗᨀᨔᨘᨑᨀᨔᨐ ᨕᨉᨗᨀᨑᨆ ᨔᨊᨉᨑᨐᨈᨗ; ᨕᨔᨕᨘ ᨖᨗ ᨑᨔᨈᨑᨗᨐᨄᨑᨐᨔᨙᨊ ᨕᨊᨈᨑᨔᨈᨑᨗᨐᨔᨖᨐᨚᨁᨙ ᨊ ᨌ ᨄᨑᨈᨐᨙᨀᨆ ᨑᨍᨐᨔᨐ ᨔᨆᨁᨈᨊᨔᨆᨔᨉᨊᨊᨘᨑᨘᨄᨆ, ᨔᨓᨗᨐᨓᨗᨅᨍᨐᨑᨈᨗᨀᨔᨆᨍᨗᨀᨔᨆᨔᨀᨑᨘᨈᨗᨀᨉᨗᨀᨑᨊᨆ ᨄᨑᨈᨗᨔᨈᨐᨕᨗ, ᨔᨓᨗᨐᨓᨐᨀᨈᨗᨈᨓᨔᨐ ᨕᨘᨊᨆᨘᨀᨈ {ᨔᨑᨓᨆᨁᨗᨊ} ᨓᨗᨀᨔᨑᨈᨆ ᨌ ᨔᨆᨔᨗᨉᨉᨗᨆ ᨕᨑᨖᨈᨗ᨞\nᨀᨑᨐᨖᨚᨑᨊᨆ ᨔᨆᨘᨌᨗᨈᨊᨗᨐᨆᨊᨄᨘᨑᨔᨔᨑᨆ, ᨔᨓᨙᨈᨊᨆ ᨌ ᨊᨗᨐᨈᨓᨉᨗᨀᨓᨀᨔᨙᨊ ᨔᨖ ᨓᨗᨔᨑᨆᨉᨗᨀᨑᨖ ᨄᨑᨈᨐᨀᨔᨆᨕᨗ ᨄᨑᨉᨙᨐᨚᨔᨈᨗ᨞\nᨕᨔᨐᨆ ᨕᨅᨗᨁᨚᨔᨊᨐᨆ ᨊᨗᨑᨉᨗᨔᨈᨊᨆ ᨕᨉᨗᨀᨑᨊᨆ ᨔᨓᨈᨊᨈᨑᨐᨊᨆ ᨌ ᨄᨑᨄᨈᨐᨙ ᨔᨆᨍᨗᨀᨊᨈᨑᨔᨈᨑᨗᨀᨓᨐᨓᨔᨈᨐᨆ ᨌ ᨄᨘᨑᨊᨈᨐ ᨕᨙᨈᨊ ᨕᨉᨗᨁᨊᨈᨘᨆ ᨄᨑᨈᨐᨙᨀᨆᨄᨗ ᨍᨊᨚᨑᨖᨗᨔᨐᨈᨙ᨞\nᨕᨔᨐᨆ ᨕᨅᨗᨁᨚᨔᨊᨐᨆ ᨊᨗᨑᨉᨗᨔᨈᨊᨆ ᨕᨉᨗᨀᨑᨊᨆ ᨔᨓᨈᨊᨈᨑᨐᨊᨆ ᨌ ᨊ ᨀᨚᨄᨐᨆᨔᨖ, ᨄᨑᨊᨔᨒᨀᨔᨐᨉᨑᨙᨊ ᨀᨗᨆᨄᨗ ᨀᨑᨐᨆᨊᨘᨔᨈᨈᨘᨆ ᨕᨙᨈᨉᨑᨘᨀᨀᨑᨐᨊᨘᨔᨈᨊᨑᨈᨆ ᨓ ᨀᨔᨐᨌᨗᨈ ᨑᨔᨈᨑᨔᨐ ᨓᨑᨁᨔᨐ ᨍᨊᨔᨐ ᨓ ᨔᨆᨗᨖᨗᨈᨔᨗᨉᨉᨐᨑᨈᨆ ᨕᨊᨐᨈ ᨓᨐᨀᨐᨈᨘᨆ ᨊᨕᨗᨓ ᨔᨀᨔᨐᨈᨙ᨞"
}
historical: true
