id: "sa_Batk"
language: "sa"
script: "Batk"
name: "Sanskrit, Batak"
region: "IN"
sample_text {
  masthead_full: "ᯚᯒᯍᯔ"
  masthead_partial: "ᯊᯄ"
  styles: "ᯛᯖ᯲ᯒ ᯐᯎᯖᯪ ᯚᯊ᯲ᯖᯪᯊ᯲ᯛᯛᯚ᯲ᯍᯖᯊ᯲ᯖ᯲ᯒ᯲ᯛᯊᯰ ᯀᯑᯒᯄ᯲ ᯔᯊᯍᯇᯒᯪᯍᯒᯚ᯲ᯛ ᯚᯒ᯲ᯍᯩᯚᯔᯇᯪ"
  tester: "ᯚᯒ᯲ᯍᯩ ᯔᯊᯍᯄ᯲ ᯚ᯲ᯍᯖᯊ᯲ᯖ᯲ᯒᯄ᯲ ᯚᯔᯮᯖ᯲ᯇᯊ᯲ᯊᯄ᯲ ᯍᯒ᯲ᯖᯊ᯲ᯖᯩ ᯀᯇᯪ ᯚ᯦, ᯎᯥᯒᯍᯑᯒᯮᯚ ᯀᯑᯪᯄ᯦ᯒᯑᯒᯮᯚ ᯚ᯦ ᯚᯔᯊᯄ᯲ ᯤᯍ"
  poster_sm: "ᯀᯚ᯲ᯛᯰ ᯀᯅᯪᯎᯬᯚᯊᯛᯰ"
  poster_md: "ᯤᯖᯑᯖᯪᯒᯪᯄ᯦᯲ᯖᯔ᯲,"
  poster_lg: "ᯚᯒ᯲ᯍᯩ"
  specimen_48: "ᯊ ᯄ᯦ᯔᯇᯪ ᯐᯊᯰ ᯑᯚᯖ᯲ᯍᯩᯊ ᯇᯒᯑᯪᯊᯖ᯲ᯍᯩᯊ ᯍ ᯑᯒᯛᯪᯖᯮᯰ ᯀᯊᯮᯐ᯲ᯠᯚ᯲ᯛᯖᯩ. ᯀᯇᯪ ᯚ᯦ ᯑᯚᯍ᯲ᯛᯇᯒᯄ᯲ ᯇᯮᯒ᯲ᯊᯒᯮᯇᯩᯊ ᯇ᯲ᯒᯖᯪᯚᯪᯑ᯲ᯑᯄ᯲"
  specimen_36: "ᯚᯒ᯲ᯍᯬ\'ᯇᯪ ᯐᯊᯄ᯲ ᯐᯪᯍᯊᯚ᯲ᯍᯖᯊ᯲ᯖ᯲ᯒ᯲ᯛᯚᯮᯒᯄ᯦᯲ᯚᯑᯪᯄ᯦ᯒᯰ ᯚᯰᯑᯖ᯲ᯖᯩ.\nᯊ ᯄ᯦ᯔᯇᯪ ᯐᯊᯰ ᯑᯚᯖ᯲ᯍᯩᯊ ᯇᯒᯑᯪᯊᯖ᯲ᯍᯩᯊ ᯍ ᯑᯒᯛᯪᯖᯮᯰ ᯀᯊᯮᯐ᯲ᯠᯚ᯲ᯛᯖᯩ. ᯀᯇᯪ ᯚ᯦ ᯑᯚᯍ᯲ᯛᯇᯒᯄ᯲ ᯇᯮᯒ᯲ᯊᯒᯮᯇᯩᯊ ᯇ᯲ᯒᯖᯪᯚᯪᯑ᯲ᯑᯄ᯲ ᯚ᯲ᯖᯚ᯲ᯛᯖᯪ."
  specimen_32: "ᯀᯚ᯲ᯛᯰ ᯀᯅᯪᯎᯬᯚᯊᯛᯰ ᯊᯪᯒ᯲ᯑᯪᯚ᯲ᯖᯄ᯲ ᯚᯒ᯲ᯍᯩ\'ᯇᯪ ᯀᯑᯪᯄ᯦ᯒᯄ᯲ ᯚᯒ᯲ᯍᯊ᯲ᯛᯇᯪ ᯚ᯦ ᯚ᯲ᯍᯖᯊ᯲ᯖ᯲ᯒ᯲ᯛᯊᯪ, ᯍᯪᯊᯤᯍ ᯐᯖᯪᯍᯒ᯲ᯊᯞᯪᯰᯎᯅᯚᯑᯒ᯲ᯔᯒᯐᯊᯪᯖᯪᯄ᯦ᯖᯑᯪᯖᯒᯔᯊ᯲ᯖᯍ᯲ᯛᯑᯪᯅᯩᯑᯔ᯲, ᯒᯚ᯲ᯖ᯲ᯒᯪᯛᯰ ᯚᯔᯐᯪᯄ᯦ᯑᯒᯰ ᯚᯔ᯲ᯇᯐ᯲ᯐᯊ᯲ᯔᯖᯑᯪᯖᯒ ᯚ᯲ᯖᯒᯠ᯲ᯚ᯦ ᯀᯍᯪᯎᯊᯛ᯲ᯛ, ᯀᯑᯪᯎᯊ᯲ᯖᯮᯰ ᯚᯒ᯲ᯍᯬ\'ᯇᯪ ᯐᯊᯄ᯲ ᯇ᯲ᯒᯅᯍᯖᯪ."
  specimen_21: "ᯚᯒ᯲ᯍᯩ ᯔᯊᯍᯄ᯲ ᯚ᯲ᯍᯖᯊ᯲ᯖ᯲ᯒᯄ᯲ ᯚᯔᯮᯖ᯲ᯇᯊ᯲ᯊᯄ᯲ ᯍᯒ᯲ᯖᯊ᯲ᯖᯩ ᯀᯇᯪ ᯚ᯦, ᯎᯥᯒᯍᯑᯒᯮᯚ ᯀᯑᯪᯄ᯦ᯒᯑᯒᯮᯚ ᯚ᯦ ᯚᯔᯊᯄ᯲ ᯤᯍ ᯍᯒ᯲ᯖᯊ᯲ᯖᯩ. ᯤᯖᯩ ᯚᯒ᯲ᯍᯩ ᯚ᯦ᯩᯖᯊᯖᯒ᯲ᯄ᯦ᯚᯄ᯦᯲ᯖᯪᯅ᯲ᯛᯰ ᯚᯮᯚᯔ᯲ᯇᯊ᯲ᯊᯄ᯲ ᯚᯊ᯲ᯖᯪ. ᯀᯇᯪ ᯚ᯦, ᯚᯒ᯲ᯍᯩ\'ᯇᯪ ᯅᯊ᯲ᯑᯮᯖ᯲ᯍᯅᯍᯊᯛ ᯇᯒᯚ᯲ᯇᯒᯰ ᯍ᯲ᯛᯍᯄᯒᯊ᯲ᯖᯮ.\nᯀᯚ᯲ᯛᯰ ᯀᯅᯪᯎᯬᯚᯊᯛᯰ ᯊᯪᯒ᯲ᯑᯪᯚ᯲ᯖᯄ᯲ ᯚᯒ᯲ᯍᯩ\'ᯇᯪ ᯀᯑᯪᯄ᯦ᯒᯄ᯲ ᯚᯒ᯲ᯍᯊ᯲ᯛᯇᯪ ᯚ᯦ ᯚ᯲ᯍᯖᯊ᯲ᯖ᯲ᯒ᯲ᯛᯊᯪ, ᯍᯪᯊᯤᯍ ᯐᯖᯪᯍᯒ᯲ᯊᯞᯪᯰᯎᯅᯚᯑᯒ᯲ᯔᯒᯐᯊᯪᯖᯪᯄ᯦ᯖᯑᯪᯖᯒᯔᯊ᯲ᯖᯍ᯲ᯛᯑᯪᯅᯩᯑᯔ᯲, ᯒᯚ᯲ᯖ᯲ᯒᯪᯛᯰ ᯚᯔᯐᯪᯄ᯦ᯑᯒᯰ ᯚᯔ᯲ᯇᯐ᯲ᯐᯊ᯲ᯔᯖᯑᯪᯖᯒ ᯚ᯲ᯖᯒᯠ᯲ᯚ᯦ ᯀᯍᯪᯎᯊᯛ᯲ᯛ, ᯀᯑᯪᯎᯊ᯲ᯖᯮᯰ ᯚᯒ᯲ᯍᯬ\'ᯇᯪ ᯐᯊᯄ᯲ ᯇ᯲ᯒᯅᯍᯖᯪ.\nᯤᯖᯑᯖᯪᯒᯪᯄ᯦᯲ᯖᯔ᯲, ᯄ᯦ᯚ᯲ᯛᯚ᯲ᯚ᯦ᯪᯑᯇᯪ ᯇ᯲ᯒᯅᯮᯚᯖ᯲ᯖᯛᯄ᯲ ᯊᯪᯛᯔᯊᯊ᯲ᯖᯒ᯲ᯎᯖᯔ᯲, ᯚ᯲ᯍᯑᯪᯊᯚ᯲ᯛ ᯀᯖ᯲ᯔᯇ᯲ᯒᯚᯚᯊᯩᯖᯒᯖᯊ᯲ᯖ᯲ᯒᯚ᯲ᯛ, ᯊ᯲ᯛᯚᯪᯖᯊ᯲ᯖ᯲ᯒᯚ᯲ᯛ ᯍ ᯍᯚ᯲ᯖᯍ᯲ᯛᯚ᯲ᯛ ᯇ᯲ᯒᯑᯩᯚᯚ᯲ᯛ ᯑᯩᯚᯚ᯲ᯛ ᯍ ᯒᯐᯊᯪᯖᯪᯄ᯦ᯚᯪᯔᯊᯪᯅᯊ᯲ᯑᯊᯊ᯲ᯖᯒᯚ᯲ᯖ᯲ᯒᯪᯄ᯦ᯚ᯲ᯖᯒᯑᯒᯩᯊ ᯊ ᯄ᯦ᯬ\'ᯇᯪ ᯅᯩᯑᯬ ᯍᯪᯑᯚ᯲ᯛᯖᯩ."
  specimen_16: "ᯚᯒ᯲ᯍᯩ ᯔᯊᯍᯄ᯲ ᯚ᯲ᯍᯖᯊ᯲ᯖ᯲ᯒᯄ᯲ ᯚᯔᯮᯖ᯲ᯇᯊ᯲ᯊᯄ᯲ ᯍᯒ᯲ᯖᯊ᯲ᯖᯩ ᯀᯇᯪ ᯚ᯦, ᯎᯥᯒᯍᯑᯒᯮᯚ ᯀᯑᯪᯄ᯦ᯒᯑᯒᯮᯚ ᯚ᯦ ᯚᯔᯊᯄ᯲ ᯤᯍ ᯍᯒ᯲ᯖᯊ᯲ᯖᯩ. ᯤᯖᯩ ᯚᯒ᯲ᯍᯩ ᯚ᯦ᯩᯖᯊᯖᯒ᯲ᯄ᯦ᯚᯄ᯦᯲ᯖᯪᯅ᯲ᯛᯰ ᯚᯮᯚᯔ᯲ᯇᯊ᯲ᯊᯄ᯲ ᯚᯊ᯲ᯖᯪ. ᯀᯇᯪ ᯚ᯦, ᯚᯒ᯲ᯍᯩ\'ᯇᯪ ᯅᯊ᯲ᯑᯮᯖ᯲ᯍᯅᯍᯊᯛ ᯇᯒᯚ᯲ᯇᯒᯰ ᯍ᯲ᯛᯍᯄᯒᯊ᯲ᯖᯮ.\nᯀᯚ᯲ᯛᯰ ᯀᯅᯪᯎᯬᯚᯊᯛᯰ ᯊᯪᯒ᯲ᯑᯪᯚ᯲ᯖᯄ᯲ ᯚᯒ᯲ᯍᯩ\'ᯇᯪ ᯀᯑᯪᯄ᯦ᯒᯄ᯲ ᯚᯒ᯲ᯍᯊ᯲ᯛᯇᯪ ᯚ᯦ ᯚ᯲ᯍᯖᯊ᯲ᯖ᯲ᯒ᯲ᯛᯊᯪ, ᯍᯪᯊᯤᯍ ᯐᯖᯪᯍᯒ᯲ᯊᯞᯪᯰᯎᯅᯚᯑᯒ᯲ᯔᯒᯐᯊᯪᯖᯪᯄ᯦ᯖᯑᯪᯖᯒᯔᯊ᯲ᯖᯍ᯲ᯛᯑᯪᯅᯩᯑᯔ᯲, ᯒᯚ᯲ᯖ᯲ᯒᯪᯛᯰ ᯚᯔᯐᯪᯄ᯦ᯑᯒᯰ ᯚᯔ᯲ᯇᯐ᯲ᯐᯊ᯲ᯔᯖᯑᯪᯖᯒ ᯚ᯲ᯖᯒᯠ᯲ᯚ᯦ ᯀᯍᯪᯎᯊᯛ᯲ᯛ, ᯀᯑᯪᯎᯊ᯲ᯖᯮᯰ ᯚᯒ᯲ᯍᯬ\'ᯇᯪ ᯐᯊᯄ᯲ ᯇ᯲ᯒᯅᯍᯖᯪ.\nᯤᯖᯑᯖᯪᯒᯪᯄ᯦᯲ᯖᯔ᯲, ᯄ᯦ᯚ᯲ᯛᯚ᯲ᯚ᯦ᯪᯑᯇᯪ ᯇ᯲ᯒᯅᯮᯚᯖ᯲ᯖᯛᯄ᯲ ᯊᯪᯛᯔᯊᯊ᯲ᯖᯒ᯲ᯎᯖᯔ᯲, ᯚ᯲ᯍᯑᯪᯊᯚ᯲ᯛ ᯀᯖ᯲ᯔᯇ᯲ᯒᯚᯚᯊᯩᯖᯒᯖᯊ᯲ᯖ᯲ᯒᯚ᯲ᯛ, ᯊ᯲ᯛᯚᯪᯖᯊ᯲ᯖ᯲ᯒᯚ᯲ᯛ ᯍ ᯍᯚ᯲ᯖᯍ᯲ᯛᯚ᯲ᯛ ᯇ᯲ᯒᯑᯩᯚᯚ᯲ᯛ ᯑᯩᯚᯚ᯲ᯛ ᯍ ᯒᯐᯊᯪᯖᯪᯄ᯦ᯚᯪᯔᯊᯪᯅᯊ᯲ᯑᯊᯊ᯲ᯖᯒᯚ᯲ᯖ᯲ᯒᯪᯄ᯦ᯚ᯲ᯖᯒᯑᯒᯩᯊ ᯊ ᯄ᯦ᯬ\'ᯇᯪ ᯅᯩᯑᯬ ᯍᯪᯑᯚ᯲ᯛᯖᯩ.\nᯚᯒ᯲ᯍᯬ\'ᯇᯪ ᯐᯊᯄ᯲ ᯐᯪᯍᯊᯚ᯲ᯍᯖᯊ᯲ᯖ᯲ᯒ᯲ᯛᯚᯮᯒᯄ᯦᯲ᯚᯑᯪᯄ᯦ᯒᯰ ᯚᯰᯑᯖ᯲ᯖᯩ.\nᯊ ᯄ᯦ᯔᯇᯪ ᯐᯊᯰ ᯑᯚᯖ᯲ᯍᯩᯊ ᯇᯒᯑᯪᯊᯖ᯲ᯍᯩᯊ ᯍ ᯑᯒᯛᯪᯖᯮᯰ ᯀᯊᯮᯐ᯲ᯠᯚ᯲ᯛᯖᯩ. ᯀᯇᯪ ᯚ᯦ ᯑᯚᯍ᯲ᯛᯇᯒᯄ᯲ ᯇᯮᯒ᯲ᯊᯒᯮᯇᯩᯊ ᯇ᯲ᯒᯖᯪᯚᯪᯑ᯲ᯑᯄ᯲ ᯚ᯲ᯖᯚ᯲ᯛᯖᯪ.\nᯊ ᯄ᯦ᯔᯇᯪ ᯐᯊᯰ ᯍᯪᯒᯮᯑ᯲ᯛ ᯀᯍᯔᯊᯊᯖ᯲ᯔᯄ᯦ᯰ ᯍ᯲ᯛᯍᯄᯒᯰ ᯑᯊ᯲ᯑᯰ ᯍ ᯄ᯦᯲ᯒᯮᯒᯰ ᯀᯔᯊᯍᯪᯛᯰ ᯇ᯲ᯒᯖᯬᯑᯊᯰ ᯍ ᯇ᯲ᯒᯍᯒ᯲ᯖᯛᯪᯖᯮᯰ ᯀᯊᯮᯐ᯲ᯠᯚ᯲ᯛᯖᯩ."
}
historical: true
