id: "sa_Gonm"
language: "sa"
script: "Gonm"
name: "Sanskrit, Masaram Gondi"
region: "IN"
sample_text {
  masthead_full: "𑴖𑴪𑴝𑴣"
  masthead_partial: "𑴖𑴪"
  styles: "𑴥𑴰 𑴓𑴎𑴛𑴲 𑴩𑴱𑴟𑵅𑴛𑴲𑴟𑵅𑴥𑴱𑴥𑴫𑵅𑴨𑴱𑴛𑴟𑵄𑴰𑵅𑴥𑴱𑴚𑴱𑵀 𑴁𑴞𑴱𑴦𑵁"
  tester: "𑴫𑵆𑴨𑴺 𑴤𑴱𑴟𑴨𑴱𑵁 𑴫𑵅𑴨𑴛𑴟𑵄𑴰𑴱𑵁 𑴫𑴤𑴴𑴛𑵅𑴠𑴟𑵅𑴟𑴱𑵁 𑴨𑵆𑴛𑴟𑵅𑴛𑴺 𑴀𑴠𑴲 𑴑, 𑴎𑴿𑴦𑴨𑴝𑴶𑴩𑴱 𑴀𑴞𑴲𑴌𑴱𑴦𑴝𑴶𑴩𑴱"
  poster_sm: "𑴀𑴫𑵅𑴥𑴱𑵀 𑴀𑴣𑴲"
  poster_md: "𑴆𑴛𑴝𑴛𑴲𑴦𑴲𑴌"
  poster_lg: "𑴫𑵆𑴨𑴺"
  specimen_48: "𑴟 𑴌𑴤𑴠𑴲 𑴓𑴟𑵀 𑴝𑴱𑴫𑴛𑵅𑴨𑴺𑴟 𑴠𑴦𑴱𑴞𑴳𑴟𑴛𑵅𑴨𑴺𑴟 𑴨𑴱 𑴞𑴱𑴦𑴥𑴲𑴛𑴴𑵀 𑴀𑴟𑴴𑴯𑴱𑴫𑵅𑴥𑴛𑴺। 𑴀𑴠𑴲 𑴑"
  specimen_36: "𑴌𑴱𑵆𑴥𑴬𑴽𑴦𑴱𑴚𑴱𑵀 𑴫𑴤𑴴𑴑𑴲𑴛𑴟𑴲𑴥𑴤𑴟𑴠𑴴𑴦𑴫𑵅𑴫𑴦𑴤𑵄, 𑴫𑴨𑴺𑴛𑴟𑵀 𑴑 𑴟𑴲𑴥𑴛𑴱𑴨𑴞𑴲𑴌𑴱𑴨𑴌𑴱𑴩𑴺𑴟 𑴫𑴬 𑴨𑴲𑴩𑵇𑴤𑴱𑴞𑴲𑴌𑴱𑴦𑵁 𑴠𑵇𑴛𑵅𑴥𑴌𑴫𑵅𑴤𑴼 𑴠𑵇𑴝𑴺𑴥𑴽𑴫𑵅𑴛𑴲।"
  specimen_32: "𑴀𑴫𑵅𑴥𑴱𑵀 𑴀𑴣𑴲𑴏𑴽𑴪𑴚𑴱𑴥𑴱𑵀 𑴟𑴲𑵆𑴝𑴲𑴪𑵅𑴖𑴱𑴟𑴱𑵀 𑴀𑴞𑴲𑴌𑴱𑴦𑴱𑴚𑴱𑵀 𑴫𑵅𑴨𑴱𑴛𑴟𑵄𑴰𑵅𑴥𑴱𑴚𑴱𑵀 𑴑 𑴠𑵇𑴱𑴠𑵅𑴛𑴥𑴺 𑴫𑴱𑴤𑴱𑴓𑴲𑴌𑴱𑴟𑵅𑴛𑴱𑴦𑴱𑴪𑵅𑴖𑵇𑴲𑴌𑴨𑵅𑴥𑴨𑴫𑵅𑴜𑴱𑴥𑴱𑵀 𑴑 𑴠𑴵𑵆𑴚𑴛𑴥𑴱 𑴆𑴛𑴱𑴟𑵄 𑴀𑴞𑴲𑴎𑴟𑵅𑴛𑴴𑵀 𑴠𑵇𑴛𑵅𑴥𑴺𑴌𑴤𑴠𑴲 𑴓𑴟𑴽𑵆𑴬𑴲𑴪𑵅𑴥𑴛𑴺।"
  specimen_21: "𑴀𑴫𑵅𑴥𑴱𑵀 𑴀𑴣𑴲𑴏𑴽𑴪𑴚𑴱𑴥𑴱𑵀 𑴟𑴲𑵆𑴝𑴲𑴪𑵅𑴖𑴱𑴟𑴱𑵀 𑴀𑴞𑴲𑴌𑴱𑴦𑴱𑴚𑴱𑵀 𑴫𑵅𑴨𑴱𑴛𑴟𑵄𑴰𑴥𑴱𑴚𑴱𑵀 𑴑 𑴟 𑴌𑴽𑴠𑵅𑴥𑵀𑴩𑵁, 𑴠𑵇𑴚𑴱𑴩𑴧𑴮𑵅𑴥𑴱𑴞𑴱𑴦𑴺𑴚 𑴌𑴲𑴤𑴠𑴲 𑴌𑴱𑵆𑴥𑴤𑴟𑴴𑴪𑵅𑴗𑴱𑴛𑴴𑵀 𑴆𑴛𑴱𑴝𑴶𑴌𑵅𑴌𑴱𑵆𑴥𑴱𑴟𑴴𑴪𑵅𑴗𑴱𑴟𑴱𑵆𑴜𑵀 𑴨𑴱 𑴌𑴫𑵅𑴥𑴑𑴲𑴛𑵄 𑴦𑴱𑴪𑵅𑴖𑵇𑴫𑵅𑴥 𑴨𑵆𑴎𑴫𑵅𑴥 𑴓𑴟𑴫𑵅𑴥 𑴨𑴱 𑴫𑴤𑴳𑴬𑴲𑴛𑴫𑴲𑴝𑵅𑴞𑴥𑵆𑴜𑵀 𑴀𑴟𑵅𑴥𑴜𑴱 𑴨𑵅𑴥𑴱𑴍𑵅𑴥𑴱𑴛𑴴𑵀 𑴟𑴼𑴨 𑴩𑴮𑵅𑴥𑴛𑴺।\n𑴫𑵆𑴨𑴺 𑴤𑴱𑴟𑴨𑴱𑵁 𑴫𑵅𑴨𑴛𑴟𑵄𑴰𑴱𑵁 𑴫𑴤𑴴𑴛𑵅𑴠𑴟𑵅𑴟𑴱𑵁 𑴨𑵆𑴛𑴟𑵅𑴛𑴺 𑴀𑴠𑴲 𑴑, 𑴎𑴿𑴦𑴨𑴝𑴶𑴩𑴱 𑴀𑴞𑴲𑴌𑴱𑴦𑴝𑴶𑴩𑴱 𑴑 𑴫𑴤𑴱𑴟𑴱𑵁 𑴆𑴨 𑴨𑵆𑴛𑴟𑵅𑴛𑴺। 𑴆𑴛𑴺 𑴫𑵆𑴨𑴺 𑴑𑴺𑴛𑴟𑴱𑴛𑵆𑴌𑴩𑴌𑵅𑴛𑴲𑴣𑵅𑴥𑴱𑵀 𑴫𑴴𑴫𑴤𑵅𑴠𑴟𑵅𑴟𑴱𑵁 𑴫𑴟𑵅𑴛𑴲। 𑴀𑴠𑴲 𑴑, 𑴫𑵆𑴨𑴺𑴠𑴲 𑴢𑴟𑵅𑴞𑴴𑴛𑵅𑴨𑴣𑴱𑴨𑴟𑴥𑴱 𑴠𑴦𑴫𑵅𑴠𑴦𑵀 𑴨𑵅𑴥𑴨𑴬𑴦𑴟𑵅𑴛𑴴।"
  specimen_16: "𑴫𑵆𑴨𑴺 𑴤𑴱𑴟𑴨𑴱𑵁 𑴫𑵅𑴨𑴛𑴟𑵄𑴰𑴱𑵁 𑴫𑴤𑴴𑴛𑵅𑴠𑴟𑵅𑴟𑴱𑵁 𑴨𑵆𑴛𑴟𑵅𑴛𑴺 𑴀𑴠𑴲 𑴑, 𑴎𑴿𑴦𑴨𑴝𑴶𑴩𑴱 𑴀𑴞𑴲𑴌𑴱𑴦𑴝𑴶𑴩𑴱 𑴑 𑴫𑴤𑴱𑴟𑴱𑵁 𑴆𑴨 𑴨𑵆𑴛𑴟𑵅𑴛𑴺। 𑴆𑴛𑴺 𑴫𑵆𑴨𑴺 𑴑𑴺𑴛𑴟𑴱𑴛𑵆𑴌𑴩𑴌𑵅𑴛𑴲𑴣𑵅𑴥𑴱𑵀 𑴫𑴴𑴫𑴤𑵅𑴠𑴟𑵅𑴟𑴱𑵁 𑴫𑴟𑵅𑴛𑴲। 𑴀𑴠𑴲 𑴑, 𑴫𑵆𑴨𑴺𑴠𑴲 𑴢𑴟𑵅𑴞𑴴𑴛𑵅𑴨𑴣𑴱𑴨𑴟𑴥𑴱 𑴠𑴦𑴫𑵅𑴠𑴦𑵀 𑴨𑵅𑴥𑴨𑴬𑴦𑴟𑵅𑴛𑴴।\n𑴀𑴫𑵅𑴥𑴱𑵀 𑴀𑴣𑴲𑴏𑴽𑴪𑴚𑴱𑴥𑴱𑵀 𑴟𑴲𑵆𑴝𑴲𑴪𑵅𑴖𑴱𑵁 𑴫𑵆𑴨𑴺𑴠𑴲 𑴀𑴞𑴲𑴌𑴱𑴦𑴱𑵁 𑴫𑵆𑴨𑴱𑴚𑵅𑴥𑴠𑴲 𑴑 𑴫𑵅𑴨𑴱𑴛𑴟𑵄𑴰𑵅𑴥𑴱𑴚𑴲, 𑴨𑴲𑴟𑴼𑴨 𑴓𑴱𑴛𑴲𑴨𑵆𑴚𑴧𑴲𑵀𑴎𑴣𑴱𑴪𑴱𑴞𑵆𑴤𑴦𑴱𑴓𑴟𑴳𑴛𑴲𑴌𑴛𑴝𑴲𑴛𑴦𑴤𑴟𑵅𑴛𑴨𑵅𑴥𑴱𑴝𑴲𑴣𑴺𑴝𑴤𑵄, 𑴦𑴱𑴪𑵅𑴖𑵇𑴲𑴥𑵀 𑴫𑴱𑴤𑴱𑴓𑴲𑴌𑴱𑴞𑴱𑴦𑵀 𑴫𑴤𑵅𑴠𑴓𑵅𑴓𑴟𑵅𑴤𑴛𑴝𑴲𑴛𑴦 𑴫𑵅𑴛𑴦𑴕𑵅𑴑 𑴀𑴨𑴲𑴎𑴚𑴥𑵅𑴥, 𑴀𑴞𑴲𑴎𑴟𑵅𑴛𑴴𑵀 𑴫𑵆𑴨𑴽𑴠𑴲 𑴓𑴟𑵁 𑴠𑵇𑴣𑴨𑴛𑴲।\n𑴆𑴛𑴝𑴛𑴲𑴦𑴲𑴌𑵅𑴛𑴤𑵄, 𑴌𑴫𑵅𑴥𑴱𑴩𑵅𑴑𑴲𑴝𑴠𑴲 𑴠𑵇𑴣𑴴𑴫𑴛𑵅𑴛𑴱𑴥𑴱𑵁 𑴟𑴲𑴥𑴤𑴟𑴱𑴟𑵅𑴛𑵆𑴎𑴛𑴤𑵄, 𑴫𑵅𑴨𑴱𑴞𑴳𑴟𑴫𑵅𑴥 𑴁𑴛𑵅𑴤𑴠𑵇𑴩𑴱𑴫𑴟𑴺𑴛𑴦𑴛𑴟𑵄𑴰𑴫𑵅𑴥, 𑴟𑵅𑴥𑴱𑴫𑴲𑴛𑴟𑵄𑴰𑴫𑵅𑴥 𑴨𑴱 𑴨𑴱𑴫𑵅𑴛𑴨𑵅𑴥𑴫𑵅𑴥 𑴠𑵇𑴝𑴺𑴩𑴫𑵅𑴥 𑴝𑴺𑴩𑴫𑵅𑴥 𑴨𑴱 𑴦𑴱𑴓𑴟𑴳𑴛𑴲𑴌𑴫𑴳𑴤𑴱𑴟𑴲𑴢𑴟𑵅𑴞𑴟𑴱𑴟𑵅𑴛𑴱𑴦𑴱𑴪𑵅𑴖𑵇𑴲𑴌𑴫𑵅𑴛𑴦𑴱𑴞𑴱𑴦𑴺𑴚 𑴟 𑴌𑴽𑴠𑴲 𑴣𑴺𑴝𑴽 𑴨𑴲𑴞𑴱𑴫𑵅𑴥𑴛𑴺।"
}
historical: true
