id: "sa_Gran"
language: "sa"
script: "Gran"
name: "Sanskrit, Grantha"
population: 0
sample_text {
  masthead_full: "𑌸𑌰𑌵𑌮"
  masthead_partial: "𑌨𑌤"
  styles: "𑌯𑌤𑍍𑌰 𑌜𑌗𑌤𑌿 𑌶𑌾𑌨𑍍𑌤𑌿-𑌨𑍍𑌯𑌾𑌯-𑌸𑍍𑌵𑌾𑌤𑌨𑍍𑌤𑍍𑌰𑍍𑌯𑌾𑌣𑌾𑌂 𑌆𑌧𑌾𑌰𑌃 𑌮𑌾𑌨𑌵-𑌪𑌰𑌿𑌵𑌾𑌰𑌸𑍍𑌯 𑌸𑌰𑍍𑌵𑍇𑌷𑌾𑌮𑌪𑌿"
  tester: "𑌸𑌰𑍍𑌵𑍇 𑌮𑌾𑌨𑌵𑌾𑌃 𑌸𑍍𑌵𑌤𑌨𑍍𑌤𑍍𑌰𑌾𑌃 𑌸𑌮𑍁𑌤𑍍𑌪𑌨𑍍𑌨𑌾𑌃 𑌵𑌰𑍍𑌤𑌨𑍍𑌤𑍇 𑌅𑌪𑌿 𑌚, 𑌗𑍌𑌰𑌵𑌦𑍃𑌶𑌾 𑌅𑌧𑌿𑌕𑌾𑌰𑌦𑍃𑌶𑌾 𑌚 𑌸𑌮𑌾𑌨𑌾𑌃 𑌏𑌵 𑌵𑌰𑍍𑌤𑌨𑍍𑌤𑍇।"
  poster_sm: "𑌅𑌸𑍍𑌯𑌾𑌂 𑌅𑌭𑌿𑌘𑍋𑌷𑌣𑌾𑌯𑌾𑌂"
  poster_md: "𑌏𑌤𑌦𑌤𑌿𑌰𑌿𑌕𑍍𑌤𑌮𑍍,"
  poster_lg: "𑌸𑌰𑍍𑌵𑍇"
  specimen_48: "𑌨 𑌕𑌮𑌪𑌿 𑌜𑌨𑌂 𑌦𑌾𑌸𑌤𑍍𑌵𑍇𑌨 𑌪𑌰𑌾𑌧𑍀𑌨𑌤𑍍𑌵𑍇𑌨 𑌵𑌾 𑌧𑌾𑌰𑌯𑌿𑌤𑍁𑌂 𑌅𑌨𑍁𑌜𑍍𑌞𑌾𑌸𑍍𑌯𑌤𑍇। 𑌅𑌪𑌿 𑌚 𑌦𑌾𑌸𑌵𑍍𑌯𑌾𑌪𑌾𑌰𑌃 𑌪𑍂𑌰𑍍𑌣𑌰𑍂𑌪𑍇𑌣 𑌪𑍍𑌰𑌤𑌿𑌷𑌿𑌦𑍍𑌧𑌃"
  specimen_36: "𑌸𑌰𑍍𑌵𑍋𑌽𑌪𑌿 𑌜𑌨𑌃 𑌜𑍀𑌵𑌨-𑌸𑍍𑌵𑌾𑌤𑌨𑍍𑌤𑍍𑌰𑍍𑌯-𑌸𑍁𑌰𑌕𑍍𑌷𑌾𑌧𑌿𑌕𑌾𑌰𑌂 𑌸𑌂𑌧𑌤𑍍𑌤𑍇।\n𑌨 𑌕𑌮𑌪𑌿 𑌜𑌨𑌂 𑌦𑌾𑌸𑌤𑍍𑌵𑍇𑌨 𑌪𑌰𑌾𑌧𑍀𑌨𑌤𑍍𑌵𑍇𑌨 𑌵𑌾 𑌧𑌾𑌰𑌯𑌿𑌤𑍁𑌂 𑌅𑌨𑍁𑌜𑍍𑌞𑌾𑌸𑍍𑌯𑌤𑍇। 𑌅𑌪𑌿 𑌚 𑌦𑌾𑌸𑌵𑍍𑌯𑌾𑌪𑌾𑌰𑌃 𑌪𑍂𑌰𑍍𑌣𑌰𑍂𑌪𑍇𑌣 𑌪𑍍𑌰𑌤𑌿𑌷𑌿𑌦𑍍𑌧𑌃 𑌸𑍍𑌥𑌾𑌸𑍍𑌯𑌤𑌿।"
  specimen_32: "𑌵𑌿𑌧𑍇𑌃 𑌸𑌮𑌕𑍍𑌷𑌂 𑌸𑌰𑍍𑌵𑍇𑌽𑌪𑌿 𑌤𑍁𑌲𑍍𑌯𑌾𑌃 𑌸𑌮𑌾𑌨𑌾𑌶𑍍𑌚 𑌵𑌰𑍍𑌤𑌨𑍍𑌤𑍇। 𑌅𑌪𑌿 𑌚 𑌵𑌿𑌨𑍈𑌵 𑌕𑌮𑌪𑌿 𑌭𑍇𑌦𑌂 𑌵𑌿𑌧𑍇𑌃 𑌤𑍁𑌲𑍍𑌯𑌂 𑌸𑌂𑌰𑌕𑍍𑌷𑌣𑌮𑌵𑌾𑌪𑍍𑌤𑍁𑌂 𑌅𑌰𑍍𑌹𑌨𑍍𑌤𑌿। 𑌅𑌸𑍍𑌯𑌾𑌃 𑌅𑌭𑌿𑌘𑍋𑌷𑌣𑌾𑌯𑌾𑌃 𑌉𑌲𑍍𑌲𑌂𑌘𑌨𑍇 𑌕𑌮𑌪𑌿 𑌭𑍇𑌦𑌂, 𑌏𑌤𑌾𑌦𑍃𑌗𑍍𑌭𑍇𑌦𑌂 𑌵𑌾 𑌅𑌭𑌿𑌲𑌕𑍍𑌷𑍍𑌯 𑌕𑌾𑌮𑌪𑌿 𑌚𑍇𑌷𑍍𑌟𑌾𑌂 𑌵𑌿𑌰𑍁𑌧𑍍𑌯 𑌸𑌮𑌾𑌨-𑌸𑌂𑌰𑌕𑍍𑌷𑌣𑌾𑌰𑍍𑌹𑌾𑌃 𑌸𑌰𑍍𑌵𑍇𑌽𑌪𑌿 𑌵𑌰𑍍𑌤𑌨𑍍𑌤𑍇।"
  specimen_21: "𑌸𑌰𑍍𑌵𑍇 𑌮𑌾𑌨𑌵𑌾𑌃 𑌸𑍍𑌵𑌤𑌨𑍍𑌤𑍍𑌰𑌾𑌃 𑌸𑌮𑍁𑌤𑍍𑌪𑌨𑍍𑌨𑌾𑌃 𑌵𑌰𑍍𑌤𑌨𑍍𑌤𑍇 𑌅𑌪𑌿 𑌚, 𑌗𑍌𑌰𑌵𑌦𑍃𑌶𑌾 𑌅𑌧𑌿𑌕𑌾𑌰𑌦𑍃𑌶𑌾 𑌚 𑌸𑌮𑌾𑌨𑌾𑌃 𑌏𑌵 𑌵𑌰𑍍𑌤𑌨𑍍𑌤𑍇। 𑌏𑌤𑍇 𑌸𑌰𑍍𑌵𑍇 𑌚𑍇𑌤𑌨𑌾-𑌤𑌰𑍍𑌕-𑌶𑌕𑍍𑌤𑌿𑌭𑍍𑌯𑌾𑌂 𑌸𑍁𑌸𑌮𑍍𑌪𑌨𑍍𑌨𑌾𑌃 𑌸𑌨𑍍𑌤𑌿। 𑌅𑌪𑌿 𑌚, 𑌸𑌰𑍍𑌵𑍇𑌽𑌪𑌿 𑌬𑌨𑍍𑌧𑍁𑌤𑍍𑌵-𑌭𑌾𑌵𑌨𑌯𑌾 𑌪𑌰𑌸𑍍𑌪𑌰𑌂 𑌵𑍍𑌯𑌵𑌹𑌰𑌨𑍍𑌤𑍁।\n𑌅𑌸𑍍𑌯𑌾𑌂 𑌅𑌭𑌿𑌘𑍋𑌷𑌣𑌾𑌯𑌾𑌂 𑌨𑌿𑌰𑍍𑌦𑌿𑌷𑍍𑌟𑌾𑌃 𑌸𑌰𑍍𑌵𑍇𑌽𑌪𑌿 𑌅𑌧𑌿𑌕𑌾𑌰𑌾𑌃 𑌸𑌰𑍍𑌵𑌾𑌣𑍍𑌯𑌪𑌿 𑌚 𑌸𑍍𑌵𑌾𑌤𑌨𑍍𑌤𑍍𑌰𑍍𑌯𑌾𑌣𑌿, 𑌵𑌿𑌨𑍈𑌵 𑌜𑌾𑌤𑌿-𑌵𑌰𑍍𑌣-𑌲𑌿𑌂𑌗-𑌭𑌾𑌷𑌾-𑌧𑌰𑍍𑌮-𑌰𑌾𑌜𑌨𑍀𑌤𑌿𑌕-𑌤𑌦𑌿𑌤𑌰-𑌮𑌨𑍍𑌤𑌵𑍍𑌯𑌾𑌦𑌿-𑌭𑍇𑌦𑌮𑍍, 𑌰𑌾𑌷𑍍𑌟𑍍𑌰𑍀𑌯𑌂 𑌸𑌾𑌮𑌾𑌜𑌿𑌕𑌾𑌧𑌾𑌰𑌂 𑌸𑌮𑍍𑌪𑌜𑍍𑌜𑌨𑍍𑌮-𑌤𑌦𑌿𑌤𑌰 𑌸𑍍𑌤𑌰𑌞𑍍𑌚 𑌅𑌵𑌿𑌗𑌣𑌯𑍍𑌯, 𑌅𑌧𑌿𑌗𑌨𑍍𑌤𑍁𑌂 𑌸𑌰𑍍𑌵𑍋𑌽𑌪𑌿 𑌜𑌨𑌃 𑌪𑍍𑌰𑌭𑌵𑌤𑌿।\n𑌏𑌤𑌦𑌤𑌿𑌰𑌿𑌕𑍍𑌤𑌮𑍍, 𑌕𑌸𑍍𑌯𑌾𑌶𑍍𑌚𑌿𑌦𑌪𑌿 𑌪𑍍𑌰𑌭𑍁𑌸𑌤𑍍𑌤𑌾𑌯𑌾𑌃 𑌨𑌿𑌯𑌮𑌨𑌾𑌨𑍍𑌤𑌰𑍍𑌗𑌤𑌮𑍍, 𑌸𑍍𑌵𑌾𑌧𑍀𑌨𑌸𑍍𑌯 𑌆𑌤𑍍𑌮𑌪𑍍𑌰𑌶𑌾𑌸𑌨𑍇𑌤𑌰-𑌤𑌨𑍍𑌤𑍍𑌰𑌸𑍍𑌯, 𑌨𑍍𑌯𑌾𑌸𑌿𑌤𑌨𑍍𑌤𑍍𑌰𑌸𑍍𑌯 𑌵𑌾 𑌵𑌾𑌸𑍍𑌤𑌵𑍍𑌯𑌸𑍍𑌯 𑌪𑍍𑌰𑌦𑍇𑌶𑌸𑍍𑌯 𑌦𑍇𑌶𑌸𑍍𑌯 𑌵𑌾 𑌰𑌾𑌜𑌨𑍀𑌤𑌿𑌕-𑌸𑍀𑌮𑌾-𑌨𑌿𑌬𑌨𑍍𑌧𑌨𑌾𑌨𑍍𑌤𑌾𑌰𑌾𑌷𑍍𑌟𑍍𑌰𑌿𑌕-𑌸𑍍𑌤𑌰𑌾𑌧𑌾𑌰𑍇𑌣 𑌨 𑌕𑍋𑌽𑌪𑌿 𑌭𑍇𑌦𑍋 𑌵𑌿𑌧𑌾𑌸𑍍𑌯𑌤𑍇।"
  specimen_16: "𑌸𑌰𑍍𑌵𑍇 𑌮𑌾𑌨𑌵𑌾𑌃 𑌸𑍍𑌵𑌤𑌨𑍍𑌤𑍍𑌰𑌾𑌃 𑌸𑌮𑍁𑌤𑍍𑌪𑌨𑍍𑌨𑌾𑌃 𑌵𑌰𑍍𑌤𑌨𑍍𑌤𑍇 𑌅𑌪𑌿 𑌚, 𑌗𑍌𑌰𑌵𑌦𑍃𑌶𑌾 𑌅𑌧𑌿𑌕𑌾𑌰𑌦𑍃𑌶𑌾 𑌚 𑌸𑌮𑌾𑌨𑌾𑌃 𑌏𑌵 𑌵𑌰𑍍𑌤𑌨𑍍𑌤𑍇। 𑌏𑌤𑍇 𑌸𑌰𑍍𑌵𑍇 𑌚𑍇𑌤𑌨𑌾-𑌤𑌰𑍍𑌕-𑌶𑌕𑍍𑌤𑌿𑌭𑍍𑌯𑌾𑌂 𑌸𑍁𑌸𑌮𑍍𑌪𑌨𑍍𑌨𑌾𑌃 𑌸𑌨𑍍𑌤𑌿। 𑌅𑌪𑌿 𑌚, 𑌸𑌰𑍍𑌵𑍇𑌽𑌪𑌿 𑌬𑌨𑍍𑌧𑍁𑌤𑍍𑌵-𑌭𑌾𑌵𑌨𑌯𑌾 𑌪𑌰𑌸𑍍𑌪𑌰𑌂 𑌵𑍍𑌯𑌵𑌹𑌰𑌨𑍍𑌤𑍁।\n𑌅𑌸𑍍𑌯𑌾𑌂 𑌅𑌭𑌿𑌘𑍋𑌷𑌣𑌾𑌯𑌾𑌂 𑌨𑌿𑌰𑍍𑌦𑌿𑌷𑍍𑌟𑌾𑌃 𑌸𑌰𑍍𑌵𑍇𑌽𑌪𑌿 𑌅𑌧𑌿𑌕𑌾𑌰𑌾𑌃 𑌸𑌰𑍍𑌵𑌾𑌣𑍍𑌯𑌪𑌿 𑌚 𑌸𑍍𑌵𑌾𑌤𑌨𑍍𑌤𑍍𑌰𑍍𑌯𑌾𑌣𑌿, 𑌵𑌿𑌨𑍈𑌵 𑌜𑌾𑌤𑌿-𑌵𑌰𑍍𑌣-𑌲𑌿𑌂𑌗-𑌭𑌾𑌷𑌾-𑌧𑌰𑍍𑌮-𑌰𑌾𑌜𑌨𑍀𑌤𑌿𑌕-𑌤𑌦𑌿𑌤𑌰-𑌮𑌨𑍍𑌤𑌵𑍍𑌯𑌾𑌦𑌿-𑌭𑍇𑌦𑌮𑍍, 𑌰𑌾𑌷𑍍𑌟𑍍𑌰𑍀𑌯𑌂 𑌸𑌾𑌮𑌾𑌜𑌿𑌕𑌾𑌧𑌾𑌰𑌂 𑌸𑌮𑍍𑌪𑌜𑍍𑌜𑌨𑍍𑌮-𑌤𑌦𑌿𑌤𑌰 𑌸𑍍𑌤𑌰𑌞𑍍𑌚 𑌅𑌵𑌿𑌗𑌣𑌯𑍍𑌯, 𑌅𑌧𑌿𑌗𑌨𑍍𑌤𑍁𑌂 𑌸𑌰𑍍𑌵𑍋𑌽𑌪𑌿 𑌜𑌨𑌃 𑌪𑍍𑌰𑌭𑌵𑌤𑌿।\n𑌏𑌤𑌦𑌤𑌿𑌰𑌿𑌕𑍍𑌤𑌮𑍍, 𑌕𑌸𑍍𑌯𑌾𑌶𑍍𑌚𑌿𑌦𑌪𑌿 𑌪𑍍𑌰𑌭𑍁𑌸𑌤𑍍𑌤𑌾𑌯𑌾𑌃 𑌨𑌿𑌯𑌮𑌨𑌾𑌨𑍍𑌤𑌰𑍍𑌗𑌤𑌮𑍍, 𑌸𑍍𑌵𑌾𑌧𑍀𑌨𑌸𑍍𑌯 𑌆𑌤𑍍𑌮𑌪𑍍𑌰𑌶𑌾𑌸𑌨𑍇𑌤𑌰-𑌤𑌨𑍍𑌤𑍍𑌰𑌸𑍍𑌯, 𑌨𑍍𑌯𑌾𑌸𑌿𑌤𑌨𑍍𑌤𑍍𑌰𑌸𑍍𑌯 𑌵𑌾 𑌵𑌾𑌸𑍍𑌤𑌵𑍍𑌯𑌸𑍍𑌯 𑌪𑍍𑌰𑌦𑍇𑌶𑌸𑍍𑌯 𑌦𑍇𑌶𑌸𑍍𑌯 𑌵𑌾 𑌰𑌾𑌜𑌨𑍀𑌤𑌿𑌕-𑌸𑍀𑌮𑌾-𑌨𑌿𑌬𑌨𑍍𑌧𑌨𑌾𑌨𑍍𑌤𑌾𑌰𑌾𑌷𑍍𑌟𑍍𑌰𑌿𑌕-𑌸𑍍𑌤𑌰𑌾𑌧𑌾𑌰𑍇𑌣 𑌨 𑌕𑍋𑌽𑌪𑌿 𑌭𑍇𑌦𑍋 𑌵𑌿𑌧𑌾𑌸𑍍𑌯𑌤𑍇।\n𑌸𑌰𑍍𑌵𑍋𑌽𑌪𑌿 𑌜𑌨𑌃 𑌜𑍀𑌵𑌨-𑌸𑍍𑌵𑌾𑌤𑌨𑍍𑌤𑍍𑌰𑍍𑌯-𑌸𑍁𑌰𑌕𑍍𑌷𑌾𑌧𑌿𑌕𑌾𑌰𑌂 𑌸𑌂𑌧𑌤𑍍𑌤𑍇।\n𑌨 𑌕𑌮𑌪𑌿 𑌜𑌨𑌂 𑌦𑌾𑌸𑌤𑍍𑌵𑍇𑌨 𑌪𑌰𑌾𑌧𑍀𑌨𑌤𑍍𑌵𑍇𑌨 𑌵𑌾 𑌧𑌾𑌰𑌯𑌿𑌤𑍁𑌂 𑌅𑌨𑍁𑌜𑍍𑌞𑌾𑌸𑍍𑌯𑌤𑍇। 𑌅𑌪𑌿 𑌚 𑌦𑌾𑌸𑌵𑍍𑌯𑌾𑌪𑌾𑌰𑌃 𑌪𑍂𑌰𑍍𑌣𑌰𑍂𑌪𑍇𑌣 𑌪𑍍𑌰𑌤𑌿𑌷𑌿𑌦𑍍𑌧𑌃 𑌸𑍍𑌥𑌾𑌸𑍍𑌯𑌤𑌿।\n𑌨 𑌕𑌮𑌪𑌿 𑌜𑌨𑌂 𑌵𑌿𑌰𑍁𑌧𑍍𑌯 𑌅𑌵𑌮𑌾𑌨𑌨𑌾𑌤𑍍𑌮𑌕𑌂 𑌵𑍍𑌯𑌵𑌹𑌾𑌰𑌂 𑌦𑌣𑍍𑌡𑌂 𑌵𑌾 𑌕𑍍𑌰𑍂𑌰𑌂 𑌅𑌮𑌾𑌨𑌵𑍀𑌯𑌂 𑌪𑍍𑌰𑌤𑍋𑌦𑌨𑌂 𑌵𑌾 𑌪𑍍𑌰𑌵𑌰𑍍𑌤𑌯𑌿𑌤𑍁𑌂 𑌅𑌨𑍁𑌜𑍍𑌞𑌾𑌸𑍍𑌯𑌤𑍇।"
}
