id: "sa_Mtei"
language: "sa"
script: "Mtei"
name: "Sanskrit, Meetei Mayek / Meitei"
region: "IN"
sample_text {
  masthead_full: "ꯁꯔꯋꯃ"
  masthead_partial: "ꯅꯇ"
  styles: "ꯌꯠꯔ ꯖꯒꯇꯤ ꫩꯥꯟꯇꯤꯟꯌꯥꯌꯁ꯭ꯋꯥꯇꯟꯠꯔ꯭ꯌꯥꫨꯥꯪ ꯑꯥꯙꯥꯔꫵ ꯃꯥꯅꯋꯄꯔꯤꯋꯥꯔꯁ꯭ꯌ ꯁꯔ꯭ꯋꯦꫪꯥꯃꯄꯤ"
  tester: "ꯁꯔ꯭ꯋꯦ ꯃꯥꯅꯋꯥꫵ ꯁ꯭ꯋꯇꯟꯠꯔꯥꫵ ꯁꯃꯨꯠꯄꯟꯅꯥꫵ ꯋꯔ꯭ꯇꯟꯇꯦ ꯑꯄꯤ ꯆ, ꯒꯧꯔꯋꯗ꯭ꯔꯨꫩꯥ ꯑꯙꯤꯀꯥꯔꯗ꯭ꯔꯨꫩꯥ ꯆ ꯁꯃꯥꯅꯥꫵ ꯑꯦꯋ ꯋꯔ꯭ꯇꯟꯇꯦ꯫"
  poster_sm: "ꯑꯁ꯭ꯌꯥꯪ ꯑꯚꯤꯘꯣꫪꫨꯥꯌꯥꯪ"
  poster_md: "ꯑꯦꯇꯗꯇꯤꯔꯤꯛꯇꯝ,"
  poster_lg: "ꯁꯔ꯭ꯋꯦ"
  specimen_48: "ꯅ ꯀꯃꯄꯤ ꯖꯅꯪ ꯗꯥꯁꯠꯋꯦꯅ ꯄꯔꯥꯙꫫꯅꯠꯋꯦꯅ ꯋꯥ ꯙꯥꯔꯌꯤꯇꯨꯪ ꯑꯅꯨꯖ꯭ꫣꯥꯁ꯭ꯌꯇꯦ꯫ ꯑꯄꯤ ꯆ ꯗꯥꯁꯋ꯭ꯌꯥꯄꯥꯔꫵ ꯄꫬꯔ꯭ꫨꯔꫬꯄꯦꫨ ꯞꯔꯇꯤꫪꯤꯗ꯭ꯙꫵ"
  specimen_36: "ꯁꯔ꯭ꯋꯣ\'ꯄꯤ ꯖꯅꫵ ꯖꫫꯋꯅꯁ꯭ꯋꯥꯇꯟꯠꯔ꯭ꯌꯁꯨꯔꯛꫪꯥꯙꯤꯀꯥꯔꯪ ꯁꯪꯙꯠꯇꯦ꯫\nꯅ ꯀꯃꯄꯤ ꯖꯅꯪ ꯗꯥꯁꯠꯋꯦꯅ ꯄꯔꯥꯙꫫꯅꯠꯋꯦꯅ ꯋꯥ ꯙꯥꯔꯌꯤꯇꯨꯪ ꯑꯅꯨꯖ꯭ꫣꯥꯁ꯭ꯌꯇꯦ꯫ ꯑꯄꯤ ꯆ ꯗꯥꯁꯋ꯭ꯌꯥꯄꯥꯔꫵ ꯄꫬꯔ꯭ꫨꯔꫬꯄꯦꫨ ꯞꯔꯇꯤꫪꯤꯗ꯭ꯙꫵ ꯁ꯭ꯊꯥꯁ꯭ꯌꯇꯤ꯫"
  specimen_32: "ꯋꯤꯙꯦꫵ ꯁꯃꯛꫪꯪ ꯁꯔ꯭ꯋꯦ\'ꯄꯤ ꯇꯨꯜꯌꯥꫵ ꯁꯃꯥꯅꯥꫩ꯭ꯆ ꯋꯔ꯭ꯇꯟꯇꯦ꯫ ꯑꯄꯤ ꯆ ꯋꯤꯅꯩꯋ ꯀꯃꯄꯤ ꯚꯦꯗꯪ ꯋꯤꯙꯦꫵ ꯇꯨꯜꯌꯪ ꯁꯪꯔꯛꫪꫨꯃꯋꯥꯞꯇꯨꯪ ꯑꯔ꯭ꯍꯟꯇꯤ꯫ ꯑꯁ꯭ꯌꯥꫵ ꯑꯚꯤꯘꯣꫪꫨꯥꯌꯥꫵ ꯎꯜꯂꯪꯘꯅꯦ ꯀꯃꯄꯤ ꯚꯦꯗꯪ, ꯑꯦꯇꯥꯗ꯭ꯔꯨꯒ꯭ꯚꯦꯗꯪ ꯋꯥ ꯑꯚꯤꯂꯛꫪ꯭ꯌ ꯀꯥꯃꯄꯤ ꯆꯦꫪ꯭ꫤꯥꯪ ꯋꯤꯔꯨꯙ꯭ꯌ ꯁꯃꯥꯅꯁꯪꯔꯛꫪꫨꯥꯔ꯭ꯍꯥꫵ ꯁꯔ꯭ꯋꯦ\'ꯄꯤ ꯋꯔ꯭ꯇꯟꯇꯦ꯫"
  specimen_21: "ꯁꯔ꯭ꯋꯦ ꯃꯥꯅꯋꯥꫵ ꯁ꯭ꯋꯇꯟꯠꯔꯥꫵ ꯁꯃꯨꯠꯄꯟꯅꯥꫵ ꯋꯔ꯭ꯇꯟꯇꯦ ꯑꯄꯤ ꯆ, ꯒꯧꯔꯋꯗ꯭ꯔꯨꫩꯥ ꯑꯙꯤꯀꯥꯔꯗ꯭ꯔꯨꫩꯥ ꯆ ꯁꯃꯥꯅꯥꫵ ꯑꯦꯋ ꯋꯔ꯭ꯇꯟꯇꯦ꯫ ꯑꯦꯇꯦ ꯁꯔ꯭ꯋꯦ ꯆꯦꯇꯅꯥꯇꯔ꯭ꯀꫩꯛꯇꯤꯚ꯭ꯌꯥꯪ ꯁꯨꯁꯝꯄꯟꯅꯥꫵ ꯁꯟꯇꯤ꯫ ꯑꯄꯤ ꯆ, ꯁꯔ꯭ꯋꯦ\'ꯄꯤ ꯕꯟꯙꯨꯠꯋꯚꯥꯋꯅꯌꯥ ꯄꯔꯁ꯭ꯄꯔꯪ ꯋ꯭ꯌꯋꯍꯔꯟꯇꯨ꯫\nꯑꯁ꯭ꯌꯥꯪ ꯑꯚꯤꯘꯣꫪꫨꯥꯌꯥꯪ ꯅꯤꯔ꯭ꯗꯤꫪ꯭ꫤꯥꫵ ꯁꯔ꯭ꯋꯦ\'ꯄꯤ ꯑꯙꯤꯀꯥꯔꯥꫵ ꯁꯔ꯭ꯋꯥꫨ꯭ꯌꯄꯤ ꯆ ꯁ꯭ꯋꯥꯇꯟꯠꯔ꯭ꯌꯥꫨꯤ, ꯋꯤꯅꯩꯋ ꯖꯥꯇꯤꯋꯔ꯭ꫨꯂꯤꯪꯒꯚꯥꫪꯥꯙꯔ꯭ꯃꯔꯥꯖꯅꫫꯇꯤꯀꯇꯗꯤꯇꯔꯃꯟꯇꯋ꯭ꯌꯥꯗꯤꯚꯦꯗꯝ, ꯔꯥꫪ꯭ꫤ꯭ꯔꯤꯌꯪ ꯁꯥꯃꯥꯖꯤꯀꯥꯙꯥꯔꯪ ꯁꯝꯄꯖ꯭ꯖꯟꯃꯇꯗꯤꯇꯔ ꯁ꯭ꯇꯔꫣ꯭ꯆ ꯑꯋꯤꯒꫨꯢꯌ, ꯑꯙꯤꯒꯟꯇꯨꯪ ꯁꯔ꯭ꯋꯣ\'ꯄꯤ ꯖꯅꫵ ꯞꯔꯚꯋꯇꯤ꯫\nꯑꯦꯇꯗꯇꯤꯔꯤꯛꯇꯝ, ꯀꯁ꯭ꯌꯥꫩ꯭ꯆꯤꯗꯄꯤ ꯞꯔꯚꯨꯁꯠꯇꯥꯌꯥꫵ ꯅꯤꯌꯃꯅꯥꯟꯇꯔ꯭ꯒꯇꯝ, ꯁ꯭ꯋꯥꯙꫫꯅꯁ꯭ꯌ ꯑꯥꯠꯃꯞꯔꫩꯥꯁꯅꯦꯇꯔꯇꯟꯠꯔꯁ꯭ꯌ, ꯟꯌꯥꯁꯤꯇꯟꯠꯔꯁ꯭ꯌ ꯋꯥ ꯋꯥꯁ꯭ꯇꯋ꯭ꯌꯁ꯭ꯌ ꯞꯔꯗꯦꫩꯁ꯭ꯌ ꯗꯦꫩꯁ꯭ꯌ ꯋꯥ ꯔꯥꯖꯅꫫꯇꯤꯀꯁꫫꯃꯥꯅꯤꯕꯟꯙꯅꯥꯟꯇꯥꯔꯥꫪ꯭ꫤ꯭ꯔꯤꯀꯁ꯭ꯇꯔꯥꯙꯥꯔꯦꫨ ꯅ ꯀꯣ\'ꯄꯤ ꯚꯦꯗꯣ ꯋꯤꯙꯥꯁ꯭ꯌꯇꯦ꯫"
  specimen_16: "ꯁꯔ꯭ꯋꯦ ꯃꯥꯅꯋꯥꫵ ꯁ꯭ꯋꯇꯟꯠꯔꯥꫵ ꯁꯃꯨꯠꯄꯟꯅꯥꫵ ꯋꯔ꯭ꯇꯟꯇꯦ ꯑꯄꯤ ꯆ, ꯒꯧꯔꯋꯗ꯭ꯔꯨꫩꯥ ꯑꯙꯤꯀꯥꯔꯗ꯭ꯔꯨꫩꯥ ꯆ ꯁꯃꯥꯅꯥꫵ ꯑꯦꯋ ꯋꯔ꯭ꯇꯟꯇꯦ꯫ ꯑꯦꯇꯦ ꯁꯔ꯭ꯋꯦ ꯆꯦꯇꯅꯥꯇꯔ꯭ꯀꫩꯛꯇꯤꯚ꯭ꯌꯥꯪ ꯁꯨꯁꯝꯄꯟꯅꯥꫵ ꯁꯟꯇꯤ꯫ ꯑꯄꯤ ꯆ, ꯁꯔ꯭ꯋꯦ\'ꯄꯤ ꯕꯟꯙꯨꯠꯋꯚꯥꯋꯅꯌꯥ ꯄꯔꯁ꯭ꯄꯔꯪ ꯋ꯭ꯌꯋꯍꯔꯟꯇꯨ꯫\nꯑꯁ꯭ꯌꯥꯪ ꯑꯚꯤꯘꯣꫪꫨꯥꯌꯥꯪ ꯅꯤꯔ꯭ꯗꯤꫪ꯭ꫤꯥꫵ ꯁꯔ꯭ꯋꯦ\'ꯄꯤ ꯑꯙꯤꯀꯥꯔꯥꫵ ꯁꯔ꯭ꯋꯥꫨ꯭ꯌꯄꯤ ꯆ ꯁ꯭ꯋꯥꯇꯟꯠꯔ꯭ꯌꯥꫨꯤ, ꯋꯤꯅꯩꯋ ꯖꯥꯇꯤꯋꯔ꯭ꫨꯂꯤꯪꯒꯚꯥꫪꯥꯙꯔ꯭ꯃꯔꯥꯖꯅꫫꯇꯤꯀꯇꯗꯤꯇꯔꯃꯟꯇꯋ꯭ꯌꯥꯗꯤꯚꯦꯗꯝ, ꯔꯥꫪ꯭ꫤ꯭ꯔꯤꯌꯪ ꯁꯥꯃꯥꯖꯤꯀꯥꯙꯥꯔꯪ ꯁꯝꯄꯖ꯭ꯖꯟꯃꯇꯗꯤꯇꯔ ꯁ꯭ꯇꯔꫣ꯭ꯆ ꯑꯋꯤꯒꫨꯢꯌ, ꯑꯙꯤꯒꯟꯇꯨꯪ ꯁꯔ꯭ꯋꯣ\'ꯄꯤ ꯖꯅꫵ ꯞꯔꯚꯋꯇꯤ꯫\nꯑꯦꯇꯗꯇꯤꯔꯤꯛꯇꯝ, ꯀꯁ꯭ꯌꯥꫩ꯭ꯆꯤꯗꯄꯤ ꯞꯔꯚꯨꯁꯠꯇꯥꯌꯥꫵ ꯅꯤꯌꯃꯅꯥꯟꯇꯔ꯭ꯒꯇꯝ, ꯁ꯭ꯋꯥꯙꫫꯅꯁ꯭ꯌ ꯑꯥꯠꯃꯞꯔꫩꯥꯁꯅꯦꯇꯔꯇꯟꯠꯔꯁ꯭ꯌ, ꯟꯌꯥꯁꯤꯇꯟꯠꯔꯁ꯭ꯌ ꯋꯥ ꯋꯥꯁ꯭ꯇꯋ꯭ꯌꯁ꯭ꯌ ꯞꯔꯗꯦꫩꯁ꯭ꯌ ꯗꯦꫩꯁ꯭ꯌ ꯋꯥ ꯔꯥꯖꯅꫫꯇꯤꯀꯁꫫꯃꯥꯅꯤꯕꯟꯙꯅꯥꯟꯇꯥꯔꯥꫪ꯭ꫤ꯭ꯔꯤꯀꯁ꯭ꯇꯔꯥꯙꯥꯔꯦꫨ ꯅ ꯀꯣ\'ꯄꯤ ꯚꯦꯗꯣ ꯋꯤꯙꯥꯁ꯭ꯌꯇꯦ꯫\nꯁꯔ꯭ꯋꯣ\'ꯄꯤ ꯖꯅꫵ ꯖꫫꯋꯅꯁ꯭ꯋꯥꯇꯟꯠꯔ꯭ꯌꯁꯨꯔꯛꫪꯥꯙꯤꯀꯥꯔꯪ ꯁꯪꯙꯠꯇꯦ꯫\nꯅ ꯀꯃꯄꯤ ꯖꯅꯪ ꯗꯥꯁꯠꯋꯦꯅ ꯄꯔꯥꯙꫫꯅꯠꯋꯦꯅ ꯋꯥ ꯙꯥꯔꯌꯤꯇꯨꯪ ꯑꯅꯨꯖ꯭ꫣꯥꯁ꯭ꯌꯇꯦ꯫ ꯑꯄꯤ ꯆ ꯗꯥꯁꯋ꯭ꯌꯥꯄꯥꯔꫵ ꯄꫬꯔ꯭ꫨꯔꫬꯄꯦꫨ ꯞꯔꯇꯤꫪꯤꯗ꯭ꯙꫵ ꯁ꯭ꯊꯥꯁ꯭ꯌꯇꯤ꯫\nꯅ ꯀꯃꯄꯤ ꯖꯅꯪ ꯋꯤꯔꯨꯙ꯭ꯌ ꯑꯋꯃꯥꯅꯅꯥꯠꯃꯀꯪ ꯋ꯭ꯌꯋꯍꯥꯔꯪ ꯗꫨ꯭ꫦꯪ ꯋꯥ ꯛꯔꫬꯔꯪ ꯑꯃꯥꯅꯋꫫꯌꯪ ꯞꯔꯇꯣꯗꯅꯪ ꯋꯥ ꯞꯔꯋꯔ꯭ꯇꯌꯤꯇꯨꯪ ꯑꯅꯨꯖ꯭ꫣꯥꯁ꯭ꯌꯇꯦ꯫"
}
historical: true
