id: "sa_Mahj"
language: "sa"
script: "Mahj"
name: "Sanskrit, Mahajani"
region: "IN"
sample_text {
  masthead_full: "𑅰𑅭𑅯𑅓"
  masthead_partial: "𑅬𑅐"
  styles: "𑅛𑅣𑅭 𑅛𑅗𑅣𑅑 𑅰𑅳𑅐𑅧𑅣𑅑𑅧𑅛𑅐𑅛𑅰𑅯𑅐𑅣𑅧𑅣𑅭𑅛𑅐𑅢𑅐𑅧 𑅐𑅦𑅐𑅭𑅱 𑅬𑅐𑅧𑅯𑅨𑅭𑅑𑅯𑅐𑅭𑅰𑅛"
  tester: "𑅰𑅭𑅯𑅓 𑅬𑅐𑅧𑅯𑅐𑅱 𑅰𑅯𑅣𑅧𑅣𑅭𑅐𑅱 𑅰𑅬𑅒𑅣𑅨𑅧𑅧𑅐𑅱 𑅯𑅭𑅣𑅧𑅣𑅓 𑅐𑅨𑅑 𑅙, 𑅗𑅒𑅭𑅯𑅥𑅭𑅒𑅰𑅳𑅐 𑅐𑅦𑅑𑅕𑅐𑅭𑅥𑅭𑅒𑅰𑅳𑅐"
  poster_sm: "𑅐𑅰𑅛𑅐𑅧 𑅐𑅫𑅑𑅘𑅔𑅖"
  poster_md: "𑅓𑅣𑅥𑅣𑅑𑅭𑅑𑅕𑅣𑅬,"
  poster_lg: "𑅰𑅭𑅯𑅓"
  specimen_48: "𑅧 𑅕𑅬𑅨𑅑 𑅛𑅧𑅧 𑅥𑅐𑅰𑅣𑅯𑅓𑅧 𑅨𑅭𑅐𑅦𑅑𑅧𑅣𑅯𑅓𑅧 𑅯𑅐 𑅦𑅐𑅭𑅛𑅑𑅣𑅒𑅧 𑅐𑅧𑅒𑅛𑅝𑅐𑅰𑅛𑅣𑅓। 𑅐𑅨𑅑 𑅙 𑅥𑅐𑅰𑅯𑅛𑅐𑅨𑅐𑅭𑅱"
  specimen_36: "𑅰𑅭𑅯𑅔𑅨𑅑 𑅛𑅧𑅱 𑅛𑅑𑅯𑅧𑅰𑅯𑅐𑅣𑅧𑅣𑅭𑅛𑅰𑅒𑅭𑅕𑅖𑅳𑅐𑅦𑅑𑅕𑅐𑅭𑅧 𑅰𑅧𑅦𑅣𑅣𑅓।\n𑅯𑅑𑅦𑅓𑅱 𑅰𑅬𑅕𑅖𑅳𑅧 𑅰𑅭𑅯𑅔𑅨𑅑 𑅛𑅧𑅱 𑅰𑅭𑅯𑅣𑅭 𑅐𑅫𑅑𑅛𑅝𑅐𑅣𑅒𑅧 𑅐𑅦𑅑𑅕𑅐𑅭𑅧 𑅰𑅧𑅦𑅣𑅣𑅓।"
  specimen_32: "𑅰𑅭𑅯𑅓 𑅬𑅐𑅧𑅯𑅐𑅱 𑅰𑅯𑅣𑅧𑅣𑅭𑅐𑅱 𑅰𑅬𑅒𑅣𑅨𑅧𑅧𑅐𑅱 𑅯𑅭𑅣𑅧𑅣𑅓 𑅐𑅨𑅑 𑅙, 𑅗𑅒𑅭𑅯𑅥𑅭𑅒𑅰𑅳𑅐 𑅐𑅦𑅑𑅕𑅐𑅭𑅥𑅭𑅒𑅰𑅳𑅐 𑅙 𑅰𑅬𑅐𑅧𑅐𑅱 𑅓𑅯 𑅯𑅭𑅣𑅧𑅣𑅓। 𑅓𑅣𑅓 𑅰𑅭𑅯𑅓 𑅙𑅓𑅣𑅧𑅐𑅣𑅭𑅕𑅰𑅳𑅕𑅣𑅑𑅫𑅛𑅐𑅧 𑅰𑅒𑅰𑅬𑅨𑅧𑅧𑅐𑅱 𑅰𑅧𑅣𑅑। 𑅐𑅨𑅑 𑅙, 𑅰𑅭𑅯𑅓𑅨𑅑 𑅪𑅧𑅦𑅒𑅣𑅯𑅫𑅐𑅯𑅧𑅛𑅐 𑅨𑅭𑅰𑅨𑅭𑅧 𑅯𑅛𑅯𑅱𑅭𑅧𑅣𑅒।"
  specimen_21: "𑅰𑅭𑅯𑅓 𑅬𑅐𑅧𑅯𑅐𑅱 𑅰𑅯𑅣𑅧𑅣𑅭𑅐𑅱 𑅰𑅬𑅒𑅣𑅨𑅧𑅧𑅐𑅱 𑅯𑅭𑅣𑅧𑅣𑅓 𑅐𑅨𑅑 𑅙, 𑅗𑅒𑅭𑅯𑅥𑅭𑅒𑅰𑅳𑅐 𑅐𑅦𑅑𑅕𑅐𑅭𑅥𑅭𑅒𑅰𑅳𑅐 𑅙 𑅰𑅬𑅐𑅧𑅐𑅱 𑅓𑅯 𑅯𑅭𑅣𑅧𑅣𑅓। 𑅓𑅣𑅓 𑅰𑅭𑅯𑅓 𑅙𑅓𑅣𑅧𑅐𑅣𑅭𑅕𑅰𑅳𑅕𑅣𑅑𑅫𑅛𑅐𑅧 𑅰𑅒𑅰𑅬𑅨𑅧𑅧𑅐𑅱 𑅰𑅧𑅣𑅑। 𑅐𑅨𑅑 𑅙, 𑅰𑅭𑅯𑅓𑅨𑅑 𑅪𑅧𑅦𑅒𑅣𑅯𑅫𑅐𑅯𑅧𑅛𑅐 𑅨𑅭𑅰𑅨𑅭𑅧 𑅯𑅛𑅯𑅱𑅭𑅧𑅣𑅒।\n𑅐𑅰𑅛𑅐𑅧 𑅐𑅫𑅑𑅘𑅔𑅖𑅳𑅢𑅐𑅛𑅐𑅧 𑅧𑅑𑅭𑅥𑅑𑅖𑅳𑅞𑅐𑅱 𑅰𑅭𑅯𑅓𑅨𑅑 𑅐𑅦𑅑𑅕𑅐𑅭𑅐𑅱 𑅰𑅭𑅯𑅐𑅢𑅛𑅨𑅑 𑅙 𑅰𑅯𑅐𑅣𑅧𑅣𑅭𑅛𑅐𑅢𑅑, 𑅯𑅑𑅧𑅑𑅯 𑅛𑅐𑅣𑅑𑅯𑅭𑅢𑅮𑅑𑅧𑅗𑅫𑅐𑅖𑅳𑅐𑅦𑅭𑅬𑅭𑅐𑅛𑅧𑅑𑅣𑅑𑅕𑅣𑅥𑅑𑅣𑅭𑅬𑅧𑅣𑅯𑅛𑅐𑅥𑅑𑅫𑅓𑅥𑅬, 𑅭𑅐𑅖𑅳𑅞𑅭𑅑𑅛𑅧 𑅰𑅐𑅬𑅐𑅛𑅑𑅕𑅐𑅦𑅐𑅭𑅧 𑅰𑅬𑅨𑅛𑅛𑅧𑅬𑅣𑅥𑅑𑅣𑅭 𑅰𑅣𑅭𑅝𑅙 𑅐𑅯𑅑𑅗𑅢𑅛𑅛, 𑅐𑅦𑅑𑅗𑅧𑅣𑅒𑅧 𑅰𑅭𑅯𑅔𑅨𑅑 𑅛𑅧𑅱 𑅨𑅭𑅫𑅯𑅣𑅑।"
  specimen_16: "𑅰𑅭𑅯𑅓 𑅬𑅐𑅧𑅯𑅐𑅱 𑅰𑅯𑅣𑅧𑅣𑅭𑅐𑅱 𑅰𑅬𑅒𑅣𑅨𑅧𑅧𑅐𑅱 𑅯𑅭𑅣𑅧𑅣𑅓 𑅐𑅨𑅑 𑅙, 𑅗𑅒𑅭𑅯𑅥𑅭𑅒𑅰𑅳𑅐 𑅐𑅦𑅑𑅕𑅐𑅭𑅥𑅭𑅒𑅰𑅳𑅐 𑅙 𑅰𑅬𑅐𑅧𑅐𑅱 𑅓𑅯 𑅯𑅭𑅣𑅧𑅣𑅓। 𑅓𑅣𑅓 𑅰𑅭𑅯𑅓 𑅙𑅓𑅣𑅧𑅐𑅣𑅭𑅕𑅰𑅳𑅕𑅣𑅑𑅫𑅛𑅐𑅧 𑅰𑅒𑅰𑅬𑅨𑅧𑅧𑅐𑅱 𑅰𑅧𑅣𑅑। 𑅐𑅨𑅑 𑅙, 𑅰𑅭𑅯𑅓𑅨𑅑 𑅪𑅧𑅦𑅒𑅣𑅯𑅫𑅐𑅯𑅧𑅛𑅐 𑅨𑅭𑅰𑅨𑅭𑅧 𑅯𑅛𑅯𑅱𑅭𑅧𑅣𑅒।\n𑅐𑅰𑅛𑅐𑅧 𑅐𑅫𑅑𑅘𑅔𑅖𑅳𑅢𑅐𑅛𑅐𑅧 𑅧𑅑𑅭𑅥𑅑𑅖𑅳𑅞𑅐𑅱 𑅰𑅭𑅯𑅓𑅨𑅑 𑅐𑅦𑅑𑅕𑅐𑅭𑅐𑅱 𑅰𑅭𑅯𑅐𑅢𑅛𑅨𑅑 𑅙 𑅰𑅯𑅐𑅣𑅧𑅣𑅭𑅛𑅐𑅢𑅑, 𑅯𑅑𑅧𑅑𑅯 𑅛𑅐𑅣𑅑𑅯𑅭𑅢𑅮𑅑𑅧𑅗𑅫𑅐𑅖𑅳𑅐𑅦𑅭𑅬𑅭𑅐𑅛𑅧𑅑𑅣𑅑𑅕𑅣𑅥𑅑𑅣𑅭𑅬𑅧𑅣𑅯𑅛𑅐𑅥𑅑𑅫𑅓𑅥𑅬, 𑅭𑅐𑅖𑅳𑅞𑅭𑅑𑅛𑅧 𑅰𑅐𑅬𑅐𑅛𑅑𑅕𑅐𑅦𑅐𑅭𑅧 𑅰𑅬𑅨𑅛𑅛𑅧𑅬𑅣𑅥𑅑𑅣𑅭 𑅰𑅣𑅭𑅝𑅙 𑅐𑅯𑅑𑅗𑅢𑅛𑅛, 𑅐𑅦𑅑𑅗𑅧𑅣𑅒𑅧 𑅰𑅭𑅯𑅔𑅨𑅑 𑅛𑅧𑅱 𑅨𑅭𑅫𑅯𑅣𑅑।\n𑅓𑅣𑅥𑅣𑅑𑅭𑅑𑅕𑅣𑅬, 𑅕𑅰𑅛𑅐𑅰𑅳𑅙𑅑𑅥𑅨𑅑 𑅨𑅭𑅫𑅒𑅰𑅣𑅣𑅐𑅛𑅐𑅱 𑅧𑅑𑅛𑅬𑅧𑅐𑅧𑅣𑅭𑅗𑅣𑅬, 𑅰𑅯𑅐𑅦𑅑𑅧𑅰𑅛 𑅐𑅣𑅬𑅨𑅭𑅰𑅳𑅐𑅰𑅧𑅓𑅣𑅭𑅣𑅧𑅣𑅭𑅰𑅛, 𑅧𑅛𑅐𑅰𑅑𑅣𑅧𑅣𑅭𑅰𑅛 𑅯𑅐 𑅯𑅐𑅰𑅣𑅯𑅛𑅰𑅛 𑅨𑅭𑅥𑅓𑅰𑅳𑅰𑅛 𑅥𑅓𑅰𑅳𑅰𑅛 𑅯𑅐 𑅭𑅐𑅛𑅧𑅑𑅣𑅑𑅕𑅰𑅑𑅬𑅐𑅧𑅑𑅪𑅧𑅦𑅧𑅐𑅧𑅣𑅐𑅭𑅐𑅖𑅳𑅞𑅭𑅑𑅕𑅰𑅣𑅭𑅐𑅦𑅐𑅭𑅓𑅢 𑅧 𑅕𑅔𑅨𑅑 𑅫𑅓𑅥𑅔 𑅯𑅑𑅦𑅐𑅰𑅛𑅣𑅓।\n𑅰𑅭𑅯𑅔𑅨𑅑 𑅛𑅧𑅱 𑅛𑅑𑅯𑅧𑅰𑅯𑅐𑅣𑅧𑅣𑅭𑅛𑅰𑅒𑅭𑅕𑅖𑅳𑅐𑅦𑅑𑅕𑅐𑅭𑅧 𑅰𑅧𑅦𑅣𑅣𑅓।"
}
historical: true
