id: "sa_Mroo"
language: "sa"
script: "Mroo"
name: "Sanskrit, Mro"
region: "IN"
sample_text {
  masthead_full: "𖩔𖩒𖩓𖩗"
  masthead_partial: "𖩘𖩃"
  styles: "𖩂𖩒𖩀𖩓𖩒 𖩋𖩒𖩌𖩒𖩀𖩊 𖩔𖩆𖩏𖩀𖩊𖩏𖩂𖩆𖩂𖩒𖩔𖩗𖩆𖩀𖩒𖩏𖩀𖩓𖩂𖩆𖩏𖩆𖩃 𖩆𖩅𖩆𖩓𖩒𖩉"
  tester: "𖩔𖩒𖩓𖩗𖩘 𖩃𖩆𖩏𖩒𖩗𖩆𖩉 𖩔𖩗𖩒𖩀𖩒𖩏𖩀𖩓𖩆𖩉 𖩔𖩒𖩃𖩑𖩀𖩐𖩒𖩏𖩏𖩆𖩉 𖩗𖩒𖩓𖩀𖩒𖩏𖩀𖩘 𖩒𖩐𖩊 𖩋𖩒, 𖩌𖩖𖩓𖩒𖩗𖩒𖩅𖩓𖩑𖩔𖩆"
  poster_sm: "𖩘𖩀𖩒𖩅𖩒𖩀𖩊𖩓𖩊𖩌𖩀𖩒𖩃,"
  poster_md: "𖩏𖩒 𖩌𖩒𖩃𖩒𖩐𖩊"
  poster_lg: "𖩔𖩒𖩓𖩗𖩘"
  specimen_48: "𖩏𖩒 𖩌𖩒𖩃𖩒𖩐𖩊 𖩋𖩒𖩏𖩒𖩃 𖩗𖩊𖩓𖩑𖩅𖩂𖩒 𖩒𖩗𖩒𖩃𖩆𖩏𖩒𖩏𖩆𖩀𖩃𖩒𖩌𖩒𖩃 𖩗𖩂𖩒𖩗𖩒𖩉𖩆𖩓𖩒𖩃 𖩅𖩒𖩏𖩅𖩒𖩃 𖩗𖩆"
  specimen_36: "𖩌𖩆𖩓𖩂𖩒𖩉𖩑𖩓𖩆𖩏𖩆𖩃 𖩔𖩒𖩃𖩑𖩋𖩊𖩀𖩒𖩏𖩊𖩂𖩒𖩃𖩒𖩏𖩒𖩐𖩑𖩓𖩒𖩔𖩔𖩒𖩓𖩒𖩃, 𖩔𖩒𖩗𖩘𖩀𖩒𖩏𖩒𖩃 𖩋𖩒 𖩏𖩊𖩂𖩒𖩀𖩆𖩗𖩒𖩅𖩊𖩌𖩆𖩗𖩒𖩌𖩆𖩔𖩘𖩏𖩒 𖩔𖩒𖩉𖩒 𖩗𖩊𖩔𖩓𖩒𖩃𖩆𖩅𖩊𖩌𖩆𖩓𖩒𖩉 𖩐𖩓𖩒𖩀𖩂𖩒𖩌𖩒𖩔𖩃𖩆𖩂 𖩐𖩓𖩒𖩅𖩘𖩂𖩑𖩔𖩀𖩊𖩮"
  specimen_32: "𖩒𖩔𖩂𖩆𖩃 𖩒𖩄𖩊𖩈𖩑𖩔𖩒𖩏𖩆𖩂𖩆𖩃 𖩏𖩊𖩓𖩅𖩊𖩔𖩀𖩆𖩏𖩆𖩃 𖩒𖩅𖩊𖩌𖩆𖩓𖩆𖩏𖩆𖩃 𖩔𖩗𖩆𖩀𖩒𖩏𖩀𖩓𖩂𖩆𖩏𖩆𖩃 𖩋𖩒 𖩐𖩓𖩆𖩐𖩀𖩒𖩂𖩘 𖩔𖩆𖩃𖩆𖩋𖩊𖩌𖩆𖩏𖩀𖩆𖩓𖩆𖩔𖩀𖩓𖩊𖩌𖩒𖩗𖩂𖩒𖩗𖩒𖩔𖩕𖩆𖩂𖩆𖩃 𖩋𖩒 𖩐𖩑𖩓𖩏𖩒𖩀𖩒𖩂𖩆 𖩘𖩀𖩆𖩏 𖩒𖩅𖩊𖩌𖩒𖩏𖩀𖩑𖩃 𖩐𖩓𖩒𖩀𖩂𖩘𖩌𖩒𖩃𖩒𖩐𖩊 𖩋𖩒𖩏𖩑𖩓𖩉𖩊𖩔𖩂𖩒𖩀𖩘𖩮"
  specimen_21: "𖩒𖩔𖩂𖩆𖩃 𖩒𖩄𖩊𖩈𖩑𖩔𖩒𖩏𖩆𖩂𖩆𖩃 𖩏𖩊𖩓𖩅𖩊𖩔𖩀𖩆𖩏𖩆𖩃 𖩒𖩅𖩊𖩌𖩆𖩓𖩆𖩏𖩆𖩃 𖩔𖩗𖩆𖩀𖩒𖩏𖩀𖩓𖩒𖩂𖩆𖩏𖩆𖩃 𖩋𖩒 𖩏𖩒 𖩌𖩑𖩐𖩂𖩒𖩃𖩔𖩒𖩉, 𖩐𖩓𖩒𖩏𖩆𖩔𖩒𖩍𖩒𖩌𖩔𖩂𖩆𖩅𖩆𖩓𖩘𖩏𖩒 𖩌𖩊𖩃𖩒𖩐𖩊 𖩌𖩆𖩓𖩂𖩒𖩃𖩒𖩏𖩑𖩔𖩕𖩆𖩀𖩑𖩃 𖩘𖩀𖩆𖩅𖩓𖩑𖩌𖩌𖩆𖩓𖩂𖩆𖩏𖩑𖩔𖩕𖩆𖩏𖩆𖩓𖩕𖩒𖩃 𖩗𖩆 𖩌𖩒𖩔𖩂𖩒𖩋𖩊𖩀 𖩓𖩆𖩔𖩀𖩓𖩒𖩔𖩂𖩒 𖩗𖩒𖩓𖩌𖩒𖩔𖩂𖩒 𖩋𖩒𖩏𖩒𖩔𖩂𖩒 𖩗𖩆 𖩔𖩒𖩃𖩊𖩉𖩊𖩀𖩒𖩔𖩊𖩅𖩅𖩒𖩂𖩒𖩓𖩕𖩒𖩃 𖩒𖩏𖩂𖩒𖩕𖩆 𖩗𖩂𖩆𖩈𖩂𖩆𖩀𖩑𖩃 𖩏𖩆𖩂𖩗𖩒 𖩔𖩒𖩌𖩔𖩂𖩒𖩀𖩘𖩮\n𖩔𖩒𖩓𖩗𖩘 𖩃𖩆𖩏𖩒𖩗𖩆𖩉 𖩔𖩗𖩒𖩀𖩒𖩏𖩀𖩓𖩆𖩉 𖩔𖩒𖩃𖩑𖩀𖩐𖩒𖩏𖩏𖩆𖩉 𖩗𖩒𖩓𖩀𖩒𖩏𖩀𖩘 𖩒𖩐𖩊 𖩋𖩒, 𖩌𖩖𖩓𖩒𖩗𖩒𖩅𖩓𖩑𖩔𖩆 𖩒𖩅𖩊𖩌𖩆𖩓𖩒𖩅𖩓𖩑𖩔𖩆 𖩋𖩒 𖩔𖩒𖩃𖩆𖩏𖩆𖩉 𖩘𖩗𖩒 𖩗𖩒𖩓𖩀𖩒𖩏𖩀𖩘𖩮 𖩘𖩀𖩘 𖩔𖩒𖩓𖩗𖩘 𖩋𖩘𖩀𖩒𖩏𖩆𖩀𖩒𖩓𖩌𖩒𖩔𖩒𖩌𖩀𖩊𖩄𖩂𖩆𖩃 𖩔𖩑𖩔𖩒𖩃𖩐𖩒𖩏𖩏𖩆𖩉 𖩔𖩒𖩏𖩀𖩊𖩮 𖩒𖩐𖩊 𖩋𖩒, 𖩔𖩒𖩓𖩗𖩘𖩐𖩊 𖩄𖩒𖩏𖩅𖩑𖩀𖩗𖩒𖩄𖩆𖩗𖩒𖩏𖩒𖩂𖩆 𖩐𖩒𖩓𖩒𖩔𖩐𖩒𖩓𖩒𖩃 𖩗𖩂𖩒𖩗𖩒𖩉𖩒𖩓𖩒𖩏𖩀𖩑𖩮"
  specimen_16: "𖩔𖩒𖩓𖩗𖩘 𖩃𖩆𖩏𖩒𖩗𖩆𖩉 𖩔𖩗𖩒𖩀𖩒𖩏𖩀𖩓𖩆𖩉 𖩔𖩒𖩃𖩑𖩀𖩐𖩒𖩏𖩏𖩆𖩉 𖩗𖩒𖩓𖩀𖩒𖩏𖩀𖩘 𖩒𖩐𖩊 𖩋𖩒, 𖩌𖩖𖩓𖩒𖩗𖩒𖩅𖩓𖩑𖩔𖩆 𖩒𖩅𖩊𖩌𖩆𖩓𖩒𖩅𖩓𖩑𖩔𖩆 𖩋𖩒 𖩔𖩒𖩃𖩆𖩏𖩆𖩉 𖩘𖩗𖩒 𖩗𖩒𖩓𖩀𖩒𖩏𖩀𖩘𖩮 𖩘𖩀𖩘 𖩔𖩒𖩓𖩗𖩘 𖩋𖩘𖩀𖩒𖩏𖩆𖩀𖩒𖩓𖩌𖩒𖩔𖩒𖩌𖩀𖩊𖩄𖩂𖩆𖩃 𖩔𖩑𖩔𖩒𖩃𖩐𖩒𖩏𖩏𖩆𖩉 𖩔𖩒𖩏𖩀𖩊𖩮 𖩒𖩐𖩊 𖩋𖩒, 𖩔𖩒𖩓𖩗𖩘𖩐𖩊 𖩄𖩒𖩏𖩅𖩑𖩀𖩗𖩒𖩄𖩆𖩗𖩒𖩏𖩒𖩂𖩆 𖩐𖩒𖩓𖩒𖩔𖩐𖩒𖩓𖩒𖩃 𖩗𖩂𖩒𖩗𖩒𖩉𖩒𖩓𖩒𖩏𖩀𖩑𖩮\n𖩒𖩔𖩂𖩆𖩃 𖩒𖩄𖩊𖩈𖩑𖩔𖩒𖩏𖩆𖩂𖩆𖩃 𖩏𖩊𖩓𖩅𖩊𖩔𖩀𖩆𖩉 𖩔𖩒𖩓𖩗𖩘𖩐𖩊 𖩒𖩅𖩊𖩌𖩆𖩓𖩆𖩉 𖩔𖩒𖩓𖩗𖩆𖩏𖩂𖩒𖩐𖩊 𖩋𖩒 𖩔𖩗𖩆𖩀𖩒𖩏𖩀𖩓𖩂𖩆𖩏𖩊, 𖩗𖩊𖩏𖩆𖩂𖩗𖩒 𖩋𖩆𖩀𖩊𖩗𖩒𖩓𖩏𖩒𖩍𖩊𖩃𖩌𖩒𖩄𖩆𖩔𖩆𖩅𖩒𖩓𖩃𖩒𖩓𖩆𖩋𖩒𖩏𖩊𖩀𖩊𖩌𖩒𖩀𖩒𖩅𖩊𖩀𖩒𖩓𖩒𖩃𖩒𖩏𖩀𖩒𖩗𖩂𖩆𖩅𖩊𖩄𖩘𖩅𖩒𖩃, 𖩓𖩆𖩔𖩀𖩓𖩊𖩂𖩒𖩃 𖩔𖩆𖩃𖩆𖩋𖩊𖩌𖩆𖩅𖩆𖩓𖩒𖩃 𖩔𖩒𖩃𖩐𖩒𖩋𖩋𖩒𖩏𖩃𖩒𖩀𖩒𖩅𖩊𖩀𖩒𖩓𖩒 𖩔𖩀𖩒𖩓𖩒𖩏𖩋𖩒 𖩒𖩗𖩊𖩌𖩒𖩏𖩒𖩂𖩂𖩒, 𖩒𖩅𖩊𖩌𖩒𖩏𖩀𖩑𖩃 𖩔𖩒𖩓𖩗𖩑𖩐𖩊 𖩋𖩒𖩏𖩒𖩉 𖩐𖩓𖩒𖩄𖩒𖩗𖩒𖩀𖩊𖩮\n𖩘𖩀𖩒𖩅𖩒𖩀𖩊𖩓𖩊𖩌𖩀𖩒𖩃, 𖩌𖩒𖩔𖩂𖩆𖩔𖩋𖩊𖩅𖩒𖩐𖩊 𖩐𖩓𖩒𖩄𖩑𖩔𖩒𖩀𖩀𖩆𖩂𖩆𖩉 𖩏𖩊𖩂𖩒𖩃𖩒𖩏𖩆𖩏𖩀𖩒𖩓𖩌𖩒𖩀𖩒𖩃, 𖩔𖩗𖩆𖩅𖩊𖩏𖩒𖩔𖩂𖩒 𖩆𖩀𖩃𖩒𖩐𖩓𖩒𖩔𖩆𖩔𖩒𖩏𖩘𖩀𖩒𖩓𖩒𖩀𖩒𖩏𖩀𖩓𖩒𖩔𖩂𖩒, 𖩏𖩂𖩆𖩔𖩊𖩀𖩒𖩏𖩀𖩓𖩒𖩔𖩂𖩒 𖩗𖩆 𖩗𖩆𖩔𖩀𖩒𖩗𖩂𖩒𖩔𖩂𖩒 𖩐𖩓𖩒𖩅𖩘𖩔𖩒𖩔𖩂𖩒 𖩅𖩘𖩔𖩒𖩔𖩂𖩒 𖩗𖩆 𖩓𖩆𖩋𖩒𖩏𖩊𖩀𖩊𖩌𖩒𖩔𖩊𖩃𖩆𖩏𖩊𖩄𖩒𖩏𖩅𖩒𖩏𖩆𖩏𖩀𖩆𖩓𖩆𖩔𖩀𖩓𖩊𖩌𖩒𖩔𖩀𖩒𖩓𖩆𖩅𖩆𖩓𖩘𖩏𖩒 𖩏𖩒 𖩌𖩑𖩐𖩊 𖩄𖩘𖩅𖩑 𖩗𖩊𖩅𖩆𖩔𖩂𖩒𖩀𖩘𖩮"
}
historical: true
