id: "sa_Mong"
language: "sa"
script: "Mong"
name: "Sanskrit, Mongolian"
sample_text {
  masthead_full: "ᠰᠠᠷᠸ"
  masthead_partial: "ᠧᠮ"
  styles: "ᠶᠠᢐᠷᠠ᠋ ᢖᠠᠺᠠᢐᢈ ᠱᠠ᠋᠎ᠠᠨᢐᢈᠨᠶᠠ᠋᠎ᠠᠶᠠ᠋ᠰᠸᠠ᠋᠎ᠠᢐᠠᠨᢐᠷᠶᠠ᠋᠎ᠠᢀᢏᠠ᠋᠎ᠠ"
  tester: "ᠶᠠᢐᠷᠠ᠋ ᢖᠠᠺᠠᢐᢈ ᠱᠠ᠋᠎ᠠᠨᢐᢈᠨᠶᠠ᠋᠎ᠠᠶᠠ᠋ᠰᠸᠠ᠋᠎ᠠᢐᠠᠨᢐᠷᠶᠠ᠋᠎ᠠᢀᢏᠠ᠋᠎ᠠ ᠠ᠋᠎ᠠᢑᠾᠠ᠋᠎ᠠᠷᠠ᠋ᢁ ᠮᠠ᠋᠎ᠠᠨᠠᠸᠠ᠋ᢒᠠᠷᢈᠸᠠ᠋᠎ᠠᠷᠠᠰᠶᠠ᠋"
  poster_sm: "ᠶᠠᢐᠷᠠ᠋ ᢖᠠᠺᠠᢐᢈ"
  poster_md: "ᠰᠠᠷᠸᠧ ᠮᠠ᠋᠎ᠠᠨᠠᠸᠠ᠋᠎ᠠᢁ ᠰᠸᠠᢐᠠᠨᢐᠷᠠ᠋᠎ᠠᢁ ᠰᠠᠮᠦᢐᢒᠠᠨᠨᠠ᠋᠎ᠠᢁ ᠸᠠᠷᢐᠠᠨᢐᠧ ᠠᢒᢈ ᢋᠠ᠋, ᠺᠣᠸᠸᠠᠷᠠᠸᠠᢑᠷᠢᠱᠠ᠋᠎ᠠ ᠠᢑᠾᢈᢉᠠ᠋᠎ᠠᠷᠠᢑᠷᠢᠱᠠ᠋᠎ᠠ ᢋᠠ᠋ ᠰᠠᠮᠠ᠋᠎ᠠᠨᠠ᠋᠎ᠠᢁ ᠧᠸᠠ᠋ ᠸᠠᠷᢐᠠᠨᢐᠧ᠂ ᠧᢐᠧ ᠰᠠᠷᠸᠧ ᢋᠧᢐᠠᠨᠠ᠋᠎ᠠᢐᠠᠷᢉᠠ᠋ᠱᠠᢉᢀᢐᢈᠪᠾᠶᠠ᠋᠎ᠠ ᠰᠦᠰᠠᠮᢒᠠᠨᠨᠠ᠋᠎ᠠᢁ ᠰᠠᠨᢐᢈ᠂ ᠠᢒᢈ ᢋᠠ᠋, ᠰᠠᠷᠸᠧᢒᢈ ᠪᠠᠨᢑᠾᠦᢐᠸᠠ᠋ᠪᠾᠠ᠋᠎ᠠᠸᠠᠨᠠᠶᠠ᠋᠎ᠠ ᢒᠠᠷᠠᠰᢒᠠᢀᠷᠠ᠋ ᠸᠶᠠᠸᠠᡙᠠᠷᠠᠨᢐᠦ"
  poster_lg: "ᠰᠠᠷᠸᠧ"
  specimen_48: "ᠶᠠᢐᠷᠠ᠋ ᢖᠠᠺᠠᢐᢈ ᠱᠠ᠋᠎ᠠᠨᢐᢈᠨᠶᠠ᠋᠎ᠠᠶᠠ᠋ᠰᠸᠠ᠋᠎ᠠᢐᠠᠨᢐᠷᠶᠠ᠋᠎ᠠᢀᢏᠠ᠋᠎ᠠ ᠠ᠋᠎ᠠᢑᠾᠠ᠋᠎ᠠᠷᠠ᠋ᢁ"
  specimen_36: "ᠰᠠᠷᠸᠣᠸᠠᢒᢈ ᢖᠠᠨᠠ᠋ᢁ ᢖᠢᠢᠸᠠᠨᠠ᠋ᠰᠸᠠ᠋᠎ᠠᢐᠠᠨᢐᠷᠶᠠ᠋ᠰᠦᠷᠠᢉᢔᠠ᠋᠎ᠠᢑᠾᢈᢉᠠ᠋᠎ᠠᢀᠷᠠ᠋ ᢀᠰᠠ᠋ᢑᠾᠠᢐᢐᠧ᠂"
  specimen_32: "ᠰᠠᠷᠸᠣᠸᠠᢒᢈ ᢖᠠᠨᠠ᠋ᢁ ᢖᠢᠢᠸᠠᠨᠠ᠋ᠰᠸᠠ᠋᠎ᠠᢐᠠᠨᢐᠷᠶᠠ᠋ᠰᠦᠷᠠᢉᢔᠠ᠋᠎ᠠᢑᠾᢈᢉᠠ᠋᠎ᠠᢀᠷᠠ᠋ ᢀᠰᠠ᠋ᢑᠾᠠᢐᢐᠧ᠂\nᠸᢈᢑᠾᠧᢁ ᠰᠠᠮᠠᢀᢉᢔᠠ᠋ ᠰᠠᠷᠸᠣᠸᠠᢒᢈ ᢖᠠᠨᠠ᠋ᢁ ᠰᠠᠷᠸᠠᢐᠷᠠ᠋ ᠠᠪᠾᢈᢖᡛᠠ᠋᠎ᠠᢀᢐᠦ ᠠᢑᠾᢈᢉᠠ᠋᠎ᠠᢀᠷᠠ᠋ ᢀᠰᠠ᠋ᢑᠾᠠᢐᢐᠧ᠂"
  specimen_21: "ᠰᠠᠷᠸᠧ ᠮᠠ᠋᠎ᠠᠨᠠᠸᠠ᠋᠎ᠠᢁ ᠰᠸᠠᢐᠠᠨᢐᠷᠠ᠋᠎ᠠᢁ ᠰᠠᠮᠦᢐᢒᠠᠨᠨᠠ᠋᠎ᠠᢁ ᠸᠠᠷᢐᠠᠨᢐᠧ ᠠᢒᢈ ᢋᠠ᠋, ᠺᠣᠸᠸᠠᠷᠠᠸᠠᢑᠷᠢᠱᠠ᠋᠎ᠠ ᠠᢑᠾᢈᢉᠠ᠋᠎ᠠᠷᠠᢑᠷᠢᠱᠠ᠋᠎ᠠ ᢋᠠ᠋ ᠰᠠᠮᠠ᠋᠎ᠠᠨᠠ᠋᠎ᠠᢁ ᠧᠸᠠ᠋ ᠸᠠᠷᢐᠠᠨᢐᠧ᠂ ᠧᢐᠧ ᠰᠠᠷᠸᠧ ᢋᠧᢐᠠᠨᠠ᠋᠎ᠠᢐᠠᠷᢉᠠ᠋ᠱᠠᢉᢀᢐᢈᠪᠾᠶᠠ᠋᠎ᠠ ᠰᠦᠰᠠᠮᢒᠠᠨᠨᠠ᠋᠎ᠠᢁ ᠰᠠᠨᢐᢈ᠂ ᠠᢒᢈ ᢋᠠ᠋, ᠰᠠᠷᠸᠧᢒᢈ ᠪᠠᠨᢑᠾᠦᢐᠸᠠ᠋ᠪᠾᠠ᠋᠎ᠠᠸᠠᠨᠠᠶᠠ᠋᠎ᠠ ᢒᠠᠷᠠᠰᢒᠠᢀᠷᠠ᠋ ᠸᠶᠠᠸᠠᡙᠠᠷᠠᠨᢐᠦ᠂\nᠠᢀᠰᠶᠠ᠋᠎ᠠ ᠠᠪᠾᢈᠺᠾᠣᠸᠠᢔᠠᢏᠠ᠋᠎ᠠᢀᠶᠠ᠋᠎ᠠ ᠨᢈᠷᢑᢈᢔᢌᠠ᠋᠎ᠠᢁ ᠰᠠᠷᠸᠧᢒᢈ ᠠᢑᠾᢈᢉᠠ᠋᠎ᠠᠷᠠ᠋᠎ᠠᢁ ᠰᠠᠷᠸᠠ᠋᠎ᠠᢏᠶᠠᢒᢈ ᢋᠠ᠋ ᠰᠸᠠ᠋᠎ᠠᢐᠠᠨᢐᠷᠶᠠ᠋᠎ᠠᢏᢈ, ᠸᢈᠨᠧ​ᠧᠸᠠ᠋ ᢖᠠ᠋᠎ᠠᢐᢈᠸᠠᠷᢏᠠ᠋ᢀᠯᢈᠺᠠ᠋ᠪᠾᠠ᠋᠎ᠠᢔᠠ᠋᠎ᠠᢑᠾᠠᠷᠮᠠ᠋ᠷᠠ᠋᠎ᠠᢖᠠᠨᠢᠢᢐᢈᢉᠠ᠋ᢐᠠᢑᢈᢐᠠᠷᠠ᠋ᠮᠠᠨᢐᠠᠸᠶᠠ᠋᠎ᠠᢑᢈᠪᠾᠧᢑᠠᠮ, ᠷᠠ᠋᠎ᠠᢔᢌᠷᢈᢀᠶᠠ᠋ ᠰᠠ᠋᠎ᠠᠮᠠ᠋᠎ᠠᢖᢈᢉᠠ᠋᠎ᠠᢑᠾᠠ᠋᠎ᠠᢀᠷᠠ᠋ ᠰᠠᠮᢒᠠᢖᢖᠠᠨᠮᠠ᠋ᢐᠠᢑᢈᢐᠠᠷᠠ᠋ ᠰᢐᠠᠷᠠᡛᢋᠠ᠋ ᠠᠸᢈᠺᠠᢏᠠᠶᠶᠠ᠋, ᠠᢑᠾᢈᠺᠠᢀᠨᢐᠦ ᠰᠠᠷᠸᠣᠸᠠᢒᢈ ᢖᠠᠨᠠ᠋ᢁ ᢒᠷᠠᠪᠾᠠᠸᠠᢐᢈ᠂"
  specimen_16: "ᠰᠠᠷᠸᠧ ᠮᠠ᠋᠎ᠠᠨᠠᠸᠠ᠋᠎ᠠᢁ ᠰᠸᠠᢐᠠᠨᢐᠷᠠ᠋᠎ᠠᢁ ᠰᠠᠮᠦᢐᢒᠠᠨᠨᠠ᠋᠎ᠠᢁ ᠸᠠᠷᢐᠠᠨᢐᠧ ᠠᢒᢈ ᢋᠠ᠋, ᠺᠣᠸᠸᠠᠷᠠᠸᠠᢑᠷᠢᠱᠠ᠋᠎ᠠ ᠠᢑᠾᢈᢉᠠ᠋᠎ᠠᠷᠠᢑᠷᠢᠱᠠ᠋᠎ᠠ ᢋᠠ᠋ ᠰᠠᠮᠠ᠋᠎ᠠᠨᠠ᠋᠎ᠠᢁ ᠧᠸᠠ᠋ ᠸᠠᠷᢐᠠᠨᢐᠧ᠂ ᠧᢐᠧ ᠰᠠᠷᠸᠧ ᢋᠧᢐᠠᠨᠠ᠋᠎ᠠᢐᠠᠷᢉᠠ᠋ᠱᠠᢉᢀᢐᢈᠪᠾᠶᠠ᠋᠎ᠠ ᠰᠦᠰᠠᠮᢒᠠᠨᠨᠠ᠋᠎ᠠᢁ ᠰᠠᠨᢐᢈ᠂ ᠠᢒᢈ ᢋᠠ᠋, ᠰᠠᠷᠸᠧᢒᢈ ᠪᠠᠨᢑᠾᠦᢐᠸᠠ᠋ᠪᠾᠠ᠋᠎ᠠᠸᠠᠨᠠᠶᠠ᠋᠎ᠠ ᢒᠠᠷᠠᠰᢒᠠᢀᠷᠠ᠋ ᠸᠶᠠᠸᠠᡙᠠᠷᠠᠨᢐᠦ᠂\nᠠᢀᠰᠶᠠ᠋᠎ᠠ ᠠᠪᠾᢈᠺᠾᠣᠸᠠᢔᠠᢏᠠ᠋᠎ᠠᢀᠶᠠ᠋᠎ᠠ ᠨᢈᠷᢑᢈᢔᢌᠠ᠋᠎ᠠᢁ ᠰᠠᠷᠸᠧᢒᢈ ᠠᢑᠾᢈᢉᠠ᠋᠎ᠠᠷᠠ᠋᠎ᠠᢁ ᠰᠠᠷᠸᠠ᠋᠎ᠠᢏᠶᠠᢒᢈ ᢋᠠ᠋ ᠰᠸᠠ᠋᠎ᠠᢐᠠᠨᢐᠷᠶᠠ᠋᠎ᠠᢏᢈ, ᠸᢈᠨᠧ​ᠧᠸᠠ᠋ ᢖᠠ᠋᠎ᠠᢐᢈᠸᠠᠷᢏᠠ᠋ᢀᠯᢈᠺᠠ᠋ᠪᠾᠠ᠋᠎ᠠᢔᠠ᠋᠎ᠠᢑᠾᠠᠷᠮᠠ᠋ᠷᠠ᠋᠎ᠠᢖᠠᠨᠢᠢᢐᢈᢉᠠ᠋ᢐᠠᢑᢈᢐᠠᠷᠠ᠋ᠮᠠᠨᢐᠠᠸᠶᠠ᠋᠎ᠠᢑᢈᠪᠾᠧᢑᠠᠮ, ᠷᠠ᠋᠎ᠠᢔᢌᠷᢈᢀᠶᠠ᠋ ᠰᠠ᠋᠎ᠠᠮᠠ᠋᠎ᠠᢖᢈᢉᠠ᠋᠎ᠠᢑᠾᠠ᠋᠎ᠠᢀᠷᠠ᠋ ᠰᠠᠮᢒᠠᢖᢖᠠᠨᠮᠠ᠋ᢐᠠᢑᢈᢐᠠᠷᠠ᠋ ᠰᢐᠠᠷᠠᡛᢋᠠ᠋ ᠠᠸᢈᠺᠠᢏᠠᠶᠶᠠ᠋, ᠠᢑᠾᢈᠺᠠᢀᠨᢐᠦ ᠰᠠᠷᠸᠣᠸᠠᢒᢈ ᢖᠠᠨᠠ᠋ᢁ ᢒᠷᠠᠪᠾᠠᠸᠠᢐᢈ᠂\nᠧᢐᠠᢑᠠᢐᢈᠷᢈᢉᢐᠠᠮ, ᢉᠠᠰᠶᠠ᠋᠎ᠠᠱᢋᢈᢑᠠᢒᢈ ᢒᠷᠠᠪᠾᠦᠰᠠᢐᢐᠠ᠋᠎ᠠᠶᠠ᠋᠎ᠠᢁ ᠨᢈᠶᠠᠮᠠᠨᠠ᠋᠎ᠠᠨᢐᠠᠷᠺᠠᢐᠠᠮ, ᠰᠸᠠ᠋᠎ᠠᢑᠾᠢᠢᠨᠠᠰᠶᠠ᠋ ᠠ᠋᠎ᠠᢐᠮᠠᢒᠷᠠᠱᠠ᠋᠎ᠠᠰᠠᠨᠧᢐᠠᠷᠠ᠋ᢐᠠᠨᢐᠷᠠᠰᠶᠠ᠋, ᠨᠶᠠ᠋᠎ᠠᠰᢈᢐᠠᠨᢐᠷᠠᠰᠶᠠ᠋ ᠸᠠ᠋᠎ᠠ ᠸᠠ᠋᠎ᠠᠰᢐᠠᠸᠶᠠᠰᠶᠠ᠋ ᢒᠷᠠᢑᠧᠱᠠᠰᠶᠠ᠋ ᢑᠧᠱᠠᠰᠶᠠ᠋ ᠸᠠ᠋᠎ᠠ ᠷᠠ᠋᠎ᠠᢖᠠᠨᠢᠢᢐᢈᢉᠠ᠋ᠰᠢᠢᠮᠠ᠋᠎ᠠᠨᢈᠪᠠᠨᢑᠾᠠᠨᠠ᠋᠎ᠠᠨᢐᠠ᠋᠎ᠠᠷᠠ᠋᠎ᠠᢔᢌᠷᢈᢉᠠ᠋ᠰᢐᠠᠷᠠ᠋᠎ᠠᢑᠾᠠ᠋᠎ᠠᠷᠧᢏᠠ᠋ ᠨᠠ᠋ ᢉᠣᠸᠠᢒᢈ ᠪᠾᠧᢑᠣᠸᠠ ᠸᢈᢑᠾᠠ᠋᠎ᠠᠰᠶᠠᢐᠧ᠂"
}
