id: "sa_Newa"
language: "sa"
script: "Newa"
name: "Sanskrit, Newa"
region: "IN"
sample_text {
  masthead_full: "𑐳𑐬𑐰𑐩"
  masthead_partial: "𑐣𑐟"
  styles: "𑐫𑐟𑑂𑐬 𑐖𑐐𑐟𑐶 𑐱𑐵𑐣𑑂𑐟𑐶𑐣𑑂𑐫𑐵𑐫𑐳𑑂𑐰𑐵𑐟𑐣𑑂𑐟𑑂𑐬𑑂𑐫𑐵𑐞𑐵𑑄 𑐁𑐢𑐵𑐬𑑅 𑐩𑐵𑐣𑐰𑐥𑐬𑐶𑐰𑐵𑐬𑐳𑑂𑐫 𑐳𑐬𑑂𑐰𑐾𑐲𑐵𑐩𑐥𑐶"
  tester: "𑐳𑐬𑑂𑐰𑐾 𑐩𑐵𑐣𑐰𑐵𑑅 𑐳𑑂𑐰𑐟𑐣𑑂𑐟𑑂𑐬𑐵𑑅 𑐳𑐩𑐸𑐟𑑂𑐥𑐣𑑂𑐣𑐵𑑅 𑐰𑐬𑑂𑐟𑐣𑑂𑐟𑐾 𑐀𑐥𑐶 𑐔, 𑐐𑑁𑐬𑐰𑐡𑐺𑐱𑐵 𑐀𑐢𑐶𑐎𑐵𑐬𑐡𑐺𑐱𑐵 𑐔 𑐳𑐩𑐵𑐣𑐵𑑅 𑐊𑐰 𑐰𑐬𑑂𑐟𑐣𑑂𑐟𑐾𑑋"
  poster_sm: "𑐀𑐳𑑂𑐫𑐵𑑄 𑐀𑐨𑐶𑐑𑑀𑐲𑐞𑐵𑐫𑐵𑑄"
  poster_md: "𑐊𑐟𑐡𑐟𑐶𑐬𑐶𑐎𑑂𑐟𑐩𑑂,"
  poster_lg: "𑐳𑐬𑑂𑐰𑐾"
  specimen_48: "𑐣 𑐎𑐩𑐥𑐶 𑐖𑐣𑑄 𑐡𑐵𑐳𑐟𑑂𑐰𑐾𑐣 𑐥𑐬𑐵𑐢𑐷𑐣𑐟𑑂𑐰𑐾𑐣 𑐰𑐵 𑐢𑐵𑐬𑐫𑐶𑐟𑐸𑑄 𑐀𑐣𑐸𑐖𑑂𑐘𑐵𑐳𑑂𑐫𑐟𑐾𑑋 𑐀𑐥𑐶 𑐔 𑐡𑐵𑐳𑐰𑑂𑐫𑐵𑐥𑐵𑐬𑑅 𑐥𑐹𑐬𑑂𑐞𑐬𑐹𑐥𑐾𑐞 𑐥𑑂𑐬𑐟𑐶𑐲𑐶𑐡𑑂𑐢𑑅"
  specimen_36: "𑐳𑐬𑑂𑐰𑑀𑑇𑐥𑐶 𑐖𑐣𑑅 𑐖𑐷𑐰𑐣𑐳𑑂𑐰𑐵𑐟𑐣𑑂𑐟𑑂𑐬𑑂𑐫𑐳𑐸𑐬𑐎𑑂𑐲𑐵𑐢𑐶𑐎𑐵𑐬𑑄 𑐳𑑄𑐢𑐟𑑂𑐟𑐾𑑋\n𑐣 𑐎𑐩𑐥𑐶 𑐖𑐣𑑄 𑐡𑐵𑐳𑐟𑑂𑐰𑐾𑐣 𑐥𑐬𑐵𑐢𑐷𑐣𑐟𑑂𑐰𑐾𑐣 𑐰𑐵 𑐢𑐵𑐬𑐫𑐶𑐟𑐸𑑄 𑐀𑐣𑐸𑐖𑑂𑐘𑐵𑐳𑑂𑐫𑐟𑐾𑑋 𑐀𑐥𑐶 𑐔 𑐡𑐵𑐳𑐰𑑂𑐫𑐵𑐥𑐵𑐬𑑅 𑐥𑐹𑐬𑑂𑐞𑐬𑐹𑐥𑐾𑐞 𑐥𑑂𑐬𑐟𑐶𑐲𑐶𑐡𑑂𑐢𑑅 𑐳𑑂𑐠𑐵𑐳𑑂𑐫𑐟𑐶𑑋"
  specimen_32: "𑐰𑐶𑐢𑐾𑑅 𑐳𑐩𑐎𑑂𑐲𑑄 𑐳𑐬𑑂𑐰𑐾𑑇𑐥𑐶 𑐟𑐸𑐮𑑂𑐫𑐵𑑅 𑐳𑐩𑐵𑐣𑐵𑐱𑑂𑐔 𑐰𑐬𑑂𑐟𑐣𑑂𑐟𑐾𑑋 𑐀𑐥𑐶 𑐔 𑐰𑐶𑐣𑐿𑐰 𑐎𑐩𑐥𑐶 𑐨𑐾𑐡𑑄 𑐰𑐶𑐢𑐾𑑅 𑐟𑐸𑐮𑑂𑐫𑑄 𑐳𑑄𑐬𑐎𑑂𑐲𑐞𑐩𑐰𑐵𑐥𑑂𑐟𑐸𑑄 𑐀𑐬𑑂𑐴𑐣𑑂𑐟𑐶𑑋 𑐀𑐳𑑂𑐫𑐵𑑅 𑐀𑐨𑐶𑐑𑑀𑐲𑐞𑐵𑐫𑐵𑑅 𑐄𑐮𑑂𑐮𑑄𑐑𑐣𑐾 𑐎𑐩𑐥𑐶 𑐨𑐾𑐡𑑄, 𑐊𑐟𑐵𑐡𑐺𑐐𑑂𑐨𑐾𑐡𑑄 𑐰𑐵 𑐀𑐨𑐶𑐮𑐎𑑂𑐲𑑂𑐫 𑐎𑐵𑐩𑐥𑐶 𑐔𑐾𑐲𑑂𑐚𑐵𑑄 𑐰𑐶𑐬𑐸𑐢𑑂𑐫 𑐳𑐩𑐵𑐣𑐳𑑄𑐬𑐎𑑂𑐲𑐞𑐵𑐬𑑂𑐴𑐵𑑅 𑐳𑐬𑑂𑐰𑐾𑑇𑐥𑐶 𑐰𑐬𑑂𑐟𑐣𑑂𑐟𑐾𑑋"
  specimen_21: "𑐳𑐬𑑂𑐰𑐾 𑐩𑐵𑐣𑐰𑐵𑑅 𑐳𑑂𑐰𑐟𑐣𑑂𑐟𑑂𑐬𑐵𑑅 𑐳𑐩𑐸𑐟𑑂𑐥𑐣𑑂𑐣𑐵𑑅 𑐰𑐬𑑂𑐟𑐣𑑂𑐟𑐾 𑐀𑐥𑐶 𑐔, 𑐐𑑁𑐬𑐰𑐡𑐺𑐱𑐵 𑐀𑐢𑐶𑐎𑐵𑐬𑐡𑐺𑐱𑐵 𑐔 𑐳𑐩𑐵𑐣𑐵𑑅 𑐊𑐰 𑐰𑐬𑑂𑐟𑐣𑑂𑐟𑐾𑑋 𑐊𑐟𑐾 𑐳𑐬𑑂𑐰𑐾 𑐔𑐾𑐟𑐣𑐵𑐟𑐬𑑂𑐎𑐱𑐎𑑂𑐟𑐶𑐨𑑂𑐫𑐵𑑄 𑐳𑐸𑐳𑐩𑑂𑐥𑐣𑑂𑐣𑐵𑑅 𑐳𑐣𑑂𑐟𑐶𑑋 𑐀𑐥𑐶 𑐔, 𑐳𑐬𑑂𑐰𑐾𑑇𑐥𑐶 𑐧𑐣𑑂𑐢𑐸𑐟𑑂𑐰𑐨𑐵𑐰𑐣𑐫𑐵 𑐥𑐬𑐳𑑂𑐥𑐬𑑄 𑐰𑑂𑐫𑐰𑐴𑐬𑐣𑑂𑐟𑐸𑑋\n𑐀𑐳𑑂𑐫𑐵𑑄 𑐀𑐨𑐶𑐑𑑀𑐲𑐞𑐵𑐫𑐵𑑄 𑐣𑐶𑐬𑑂𑐡𑐶𑐲𑑂𑐚𑐵𑑅 𑐳𑐬𑑂𑐰𑐾𑑇𑐥𑐶 𑐀𑐢𑐶𑐎𑐵𑐬𑐵𑑅 𑐳𑐬𑑂𑐰𑐵𑐞𑑂𑐫𑐥𑐶 𑐔 𑐳𑑂𑐰𑐵𑐟𑐣𑑂𑐟𑑂𑐬𑑂𑐫𑐵𑐞𑐶, 𑐰𑐶𑐣𑐿𑐰 𑐖𑐵𑐟𑐶𑐰𑐬𑑂𑐞𑐮𑐶𑑄𑐐𑐨𑐵𑐲𑐵𑐢𑐬𑑂𑐩𑐬𑐵𑐖𑐣𑐷𑐟𑐶𑐎𑐟𑐡𑐶𑐟𑐬𑐩𑐣𑑂𑐟𑐰𑑂𑐫𑐵𑐡𑐶𑐨𑐾𑐡𑐩𑑂, 𑐬𑐵𑐲𑑂𑐚𑑂𑐬𑐶𑐫𑑄 𑐳𑐵𑐩𑐵𑐖𑐶𑐎𑐵𑐢𑐵𑐬𑑄 𑐳𑐩𑑂𑐥𑐖𑑂𑐖𑐣𑑂𑐩𑐟𑐡𑐶𑐟𑐬 𑐳𑑂𑐟𑐬𑐘𑑂𑐔 𑐀𑐰𑐶𑐐𑐞𑐫𑑂𑐫, 𑐀𑐢𑐶𑐐𑐣𑑂𑐟𑐸𑑄 𑐳𑐬𑑂𑐰𑑀𑑇𑐥𑐶 𑐖𑐣𑑅 𑐥𑑂𑐬𑐨𑐰𑐟𑐶𑑋\n𑐊𑐟𑐡𑐟𑐶𑐬𑐶𑐎𑑂𑐟𑐩𑑂, 𑐎𑐳𑑂𑐫𑐵𑐱𑑂𑐔𑐶𑐡𑐥𑐶 𑐥𑑂𑐬𑐨𑐸𑐳𑐟𑑂𑐟𑐵𑐫𑐵𑑅 𑐣𑐶𑐫𑐩𑐣𑐵𑐣𑑂𑐟𑐬𑑂𑐐𑐟𑐩𑑂, 𑐳𑑂𑐰𑐵𑐢𑐷𑐣𑐳𑑂𑐫 𑐁𑐟𑑂𑐩𑐥𑑂𑐬𑐱𑐵𑐳𑐣𑐾𑐟𑐬𑐟𑐣𑑂𑐟𑑂𑐬𑐳𑑂𑐫, 𑐣𑑂𑐫𑐵𑐳𑐶𑐟𑐣𑑂𑐟𑑂𑐬𑐳𑑂𑐫 𑐰𑐵 𑐰𑐵𑐳𑑂𑐟𑐰𑑂𑐫𑐳𑑂𑐫 𑐥𑑂𑐬𑐡𑐾𑐱𑐳𑑂𑐫 𑐡𑐾𑐱𑐳𑑂𑐫 𑐰𑐵 𑐬𑐵𑐖𑐣𑐷𑐟𑐶𑐎𑐳𑐷𑐩𑐵𑐣𑐶𑐧𑐣𑑂𑐢𑐣𑐵𑐣𑑂𑐟𑐵𑐬𑐵𑐲𑑂𑐚𑑂𑐬𑐶𑐎𑐳𑑂𑐟𑐬𑐵𑐢𑐵𑐬𑐾𑐞 𑐣 𑐎𑑀𑑇𑐥𑐶 𑐨𑐾𑐡𑑀 𑐰𑐶𑐢𑐵𑐳𑑂𑐫𑐟𑐾𑑋"
  specimen_16: "𑐳𑐬𑑂𑐰𑐾 𑐩𑐵𑐣𑐰𑐵𑑅 𑐳𑑂𑐰𑐟𑐣𑑂𑐟𑑂𑐬𑐵𑑅 𑐳𑐩𑐸𑐟𑑂𑐥𑐣𑑂𑐣𑐵𑑅 𑐰𑐬𑑂𑐟𑐣𑑂𑐟𑐾 𑐀𑐥𑐶 𑐔, 𑐐𑑁𑐬𑐰𑐡𑐺𑐱𑐵 𑐀𑐢𑐶𑐎𑐵𑐬𑐡𑐺𑐱𑐵 𑐔 𑐳𑐩𑐵𑐣𑐵𑑅 𑐊𑐰 𑐰𑐬𑑂𑐟𑐣𑑂𑐟𑐾𑑋 𑐊𑐟𑐾 𑐳𑐬𑑂𑐰𑐾 𑐔𑐾𑐟𑐣𑐵𑐟𑐬𑑂𑐎𑐱𑐎𑑂𑐟𑐶𑐨𑑂𑐫𑐵𑑄 𑐳𑐸𑐳𑐩𑑂𑐥𑐣𑑂𑐣𑐵𑑅 𑐳𑐣𑑂𑐟𑐶𑑋 𑐀𑐥𑐶 𑐔, 𑐳𑐬𑑂𑐰𑐾𑑇𑐥𑐶 𑐧𑐣𑑂𑐢𑐸𑐟𑑂𑐰𑐨𑐵𑐰𑐣𑐫𑐵 𑐥𑐬𑐳𑑂𑐥𑐬𑑄 𑐰𑑂𑐫𑐰𑐴𑐬𑐣𑑂𑐟𑐸𑑋\n𑐀𑐳𑑂𑐫𑐵𑑄 𑐀𑐨𑐶𑐑𑑀𑐲𑐞𑐵𑐫𑐵𑑄 𑐣𑐶𑐬𑑂𑐡𑐶𑐲𑑂𑐚𑐵𑑅 𑐳𑐬𑑂𑐰𑐾𑑇𑐥𑐶 𑐀𑐢𑐶𑐎𑐵𑐬𑐵𑑅 𑐳𑐬𑑂𑐰𑐵𑐞𑑂𑐫𑐥𑐶 𑐔 𑐳𑑂𑐰𑐵𑐟𑐣𑑂𑐟𑑂𑐬𑑂𑐫𑐵𑐞𑐶, 𑐰𑐶𑐣𑐿𑐰 𑐖𑐵𑐟𑐶𑐰𑐬𑑂𑐞𑐮𑐶𑑄𑐐𑐨𑐵𑐲𑐵𑐢𑐬𑑂𑐩𑐬𑐵𑐖𑐣𑐷𑐟𑐶𑐎𑐟𑐡𑐶𑐟𑐬𑐩𑐣𑑂𑐟𑐰𑑂𑐫𑐵𑐡𑐶𑐨𑐾𑐡𑐩𑑂, 𑐬𑐵𑐲𑑂𑐚𑑂𑐬𑐶𑐫𑑄 𑐳𑐵𑐩𑐵𑐖𑐶𑐎𑐵𑐢𑐵𑐬𑑄 𑐳𑐩𑑂𑐥𑐖𑑂𑐖𑐣𑑂𑐩𑐟𑐡𑐶𑐟𑐬 𑐳𑑂𑐟𑐬𑐘𑑂𑐔 𑐀𑐰𑐶𑐐𑐞𑐫𑑂𑐫, 𑐀𑐢𑐶𑐐𑐣𑑂𑐟𑐸𑑄 𑐳𑐬𑑂𑐰𑑀𑑇𑐥𑐶 𑐖𑐣𑑅 𑐥𑑂𑐬𑐨𑐰𑐟𑐶𑑋\n𑐊𑐟𑐡𑐟𑐶𑐬𑐶𑐎𑑂𑐟𑐩𑑂, 𑐎𑐳𑑂𑐫𑐵𑐱𑑂𑐔𑐶𑐡𑐥𑐶 𑐥𑑂𑐬𑐨𑐸𑐳𑐟𑑂𑐟𑐵𑐫𑐵𑑅 𑐣𑐶𑐫𑐩𑐣𑐵𑐣𑑂𑐟𑐬𑑂𑐐𑐟𑐩𑑂, 𑐳𑑂𑐰𑐵𑐢𑐷𑐣𑐳𑑂𑐫 𑐁𑐟𑑂𑐩𑐥𑑂𑐬𑐱𑐵𑐳𑐣𑐾𑐟𑐬𑐟𑐣𑑂𑐟𑑂𑐬𑐳𑑂𑐫, 𑐣𑑂𑐫𑐵𑐳𑐶𑐟𑐣𑑂𑐟𑑂𑐬𑐳𑑂𑐫 𑐰𑐵 𑐰𑐵𑐳𑑂𑐟𑐰𑑂𑐫𑐳𑑂𑐫 𑐥𑑂𑐬𑐡𑐾𑐱𑐳𑑂𑐫 𑐡𑐾𑐱𑐳𑑂𑐫 𑐰𑐵 𑐬𑐵𑐖𑐣𑐷𑐟𑐶𑐎𑐳𑐷𑐩𑐵𑐣𑐶𑐧𑐣𑑂𑐢𑐣𑐵𑐣𑑂𑐟𑐵𑐬𑐵𑐲𑑂𑐚𑑂𑐬𑐶𑐎𑐳𑑂𑐟𑐬𑐵𑐢𑐵𑐬𑐾𑐞 𑐣 𑐎𑑀𑑇𑐥𑐶 𑐨𑐾𑐡𑑀 𑐰𑐶𑐢𑐵𑐳𑑂𑐫𑐟𑐾𑑋\n𑐳𑐬𑑂𑐰𑑀𑑇𑐥𑐶 𑐖𑐣𑑅 𑐖𑐷𑐰𑐣𑐳𑑂𑐰𑐵𑐟𑐣𑑂𑐟𑑂𑐬𑑂𑐫𑐳𑐸𑐬𑐎𑑂𑐲𑐵𑐢𑐶𑐎𑐵𑐬𑑄 𑐳𑑄𑐢𑐟𑑂𑐟𑐾𑑋\n𑐣 𑐎𑐩𑐥𑐶 𑐖𑐣𑑄 𑐡𑐵𑐳𑐟𑑂𑐰𑐾𑐣 𑐥𑐬𑐵𑐢𑐷𑐣𑐟𑑂𑐰𑐾𑐣 𑐰𑐵 𑐢𑐵𑐬𑐫𑐶𑐟𑐸𑑄 𑐀𑐣𑐸𑐖𑑂𑐘𑐵𑐳𑑂𑐫𑐟𑐾𑑋 𑐀𑐥𑐶 𑐔 𑐡𑐵𑐳𑐰𑑂𑐫𑐵𑐥𑐵𑐬𑑅 𑐥𑐹𑐬𑑂𑐞𑐬𑐹𑐥𑐾𑐞 𑐥𑑂𑐬𑐟𑐶𑐲𑐶𑐡𑑂𑐢𑑅 𑐳𑑂𑐠𑐵𑐳𑑂𑐫𑐟𑐶𑑋\n𑐣 𑐎𑐩𑐥𑐶 𑐖𑐣𑑄 𑐰𑐶𑐬𑐸𑐢𑑂𑐫 𑐀𑐰𑐩𑐵𑐣𑐣𑐵𑐟𑑂𑐩𑐎𑑄 𑐰𑑂𑐫𑐰𑐴𑐵𑐬𑑄 𑐡𑐞𑑂𑐜𑑄 𑐰𑐵 𑐎𑑂𑐬𑐹𑐬𑑄 𑐀𑐩𑐵𑐣𑐰𑐷𑐫𑑄 𑐥𑑂𑐬𑐟𑑀𑐡𑐣𑑄 𑐰𑐵 𑐥𑑂𑐬𑐰𑐬𑑂𑐟𑐫𑐶𑐟𑐸𑑄 𑐀𑐣𑐸𑐖𑑂𑐘𑐵𑐳𑑂𑐫𑐟𑐾𑑋"
}
historical: true
