id: "sa_Orya"
language: "sa"
script: "Orya"
name: "Sanskrit, Odia / Oriya"
sample_text {
  masthead_full: "ସରୱମ"
  masthead_partial: "ନବ"
  styles: "ଯତ୍ର ଜଗତି ଶାନ୍ତିନ୍ୟାୟସ୍ୱାତନ୍ତ୍ର୍ୟାଣାଂ ଆଧାରଃ ମାନବପରିବାରସ୍ୟ ସର୍ୱେଷାମପି"
  tester: "ଯତ୍ର ଜଗତି ଶାନ୍ତିନ୍ୟାୟସ୍ୱାତନ୍ତ୍ର୍ୟାଣାଂ ଆଧାରଃ ମାନବପରିବାରସ୍ୟ ସର୍ୱେଷାମପି ସଦସ୍ୟାନାଂ ସାମ୍ୟାନାଂ ଅଖଣ୍ଡିତାନାଞ୍ଚ"
  poster_sm: "ଶାନ୍ତିନ୍ୟାୟସ୍ୱାତନ୍ତ୍ର୍ୟାଣାଂ"
  poster_md: "ଯତ୍ର ଜଗତି ଶ"
  poster_lg: "ସର୍ୱେ"
  specimen_48: "ଯତ୍ର ଜଗତି ଶାନ୍ତିନ୍ୟାୟସ୍ୱାତନ୍ତ୍ର୍ୟାଣାଂ ଆଧାରଃ ମାନବପରିବାରସ୍ୟ ସର୍ୱେଷାମପି ସଦସ୍ୟାନାଂ ସାମ୍ୟାନାଂ"
  specimen_36: "ସର୍ୱୋଽପି ଜନଃ ଜୀବନସ୍ୱାତନ୍ତ୍ର୍ୟସୁରକ୍ଷାଧିକାରଂ ସଂଧତ୍ତେ।\nନ କମପି ଜନଂ ଦାସତ୍ୱେନ ପରାଧୀନତ୍ୱେନ ବା ଧାରୟିତୁଂ ଅନୁଜ୍ଞାସ୍ୟତେ। ଅପି ଚ ଦାସବ୍ୟାପାରଃ ପୂର୍ଣରୂପେଣ ପ୍ରତିଷିଦ୍ଧଃ ସ୍ଥାସ୍ୟତି।"
  specimen_32: "ବିଧେଃ ସମକ୍ଷଂ ସର୍ୱେଽପି ତୁଲ୍ୟାଃ ସମାନାଶ୍ଚ ବର୍ତନ୍ତେ। ଅପି ଚ ବିନୈବ କମପି ଭେଦଂ ବିଧେଃ ତୁଲ୍ୟଂ ସଂରକ୍ଷଣମବାପ୍ତୁଂ ଅର୍ହନ୍ତି। ଅସ୍ୟାଃ ଅଭିଘୋଷଣାୟାଃ ଉଲ୍ଲଂଘନେ କମପି ଭେଦଂ, ଏତାଦୃଗ୍ଭେଦଂ ବା ଅଭିଲକ୍ଷ୍ୟ କାମପି ଚେଷ୍ଟାଂ ବିରୁଧ୍ୟ ସମାନସଂରକ୍ଷଣାର୍ହାଃ ସର୍ୱେଽପି ବର୍ତନ୍ତେ।"
  specimen_21: "ସର୍ୱେ ମାନବାଃ ସ୍ୱତନ୍ତ୍ରାଃ ସମୁତ୍ପନ୍ନାଃ ବର୍ତନ୍ତେ ଅପି ଚ, ଗୌରବଦୃଶା ଅଧିକାରଦୃଶା ଚ ସମାନାଃ ଏବ ବର୍ତନ୍ତେ। ଏତେ ସର୍ୱେ ଚେତନାତର୍କଶକ୍ତିଭ୍ୟାଂ ସୁସମ୍ପନ୍ନାଃ ସନ୍ତି। ଅପି ଚ, ସର୍ୱେଽପି ବନ୍ଧୁତ୍ୱଭାବନୟା ପରସ୍ପରଂ ବ୍ୟବହରନ୍ତୁ।\nଅସ୍ୟାଂ ଅଭିଘୋଷଣାୟାଂ ନିର୍ଦିଷ୍ଟାଃ ସର୍ୱେଽପି ଅଧିକାରାଃ ସର୍ୱାଣ୍ୟପି ଚ ସ୍ୱାତନ୍ତ୍ର୍ୟାଣି, ବିନୈବ ଜାତିବର୍ଣଲିଂଗଭାଷାଧର୍ମରାଜନୀତିକତଦିତରମନ୍ତବ୍ୟାଦିଭେଦମ୍, ରାଷ୍ଟ୍ରିୟଂ ସାମାଜିକାଧାରଂ ସମ୍ପଜ୍ଜନ୍ମତଦିତର ସ୍ତରଞ୍ଚ ଅବିଗଣୟ୍ୟ, ଅଧିଗନ୍ତୁଂ ସର୍ୱୋଽପି ଜନଃ ପ୍ରଭବତି।\nଏତଦତିରିକ୍ତମ୍, କସ୍ୟାଶ୍ଚିଦପି ପ୍ରଭୁସତ୍ତାୟାଃ ନିୟମନାନ୍ତର୍ଗତମ୍, ସ୍ୱାଧୀନସ୍ୟ ଆତ୍ମପ୍ରଶାସନେତରତନ୍ତ୍ରସ୍ୟ, ନ୍ୟାସିତନ୍ତ୍ରସ୍ୟ ବା ବାସ୍ତବ୍ୟସ୍ୟ ପ୍ରଦେଶସ୍ୟ ଦେଶସ୍ୟ ବା ରାଜନୀତିକସୀମାନିବନ୍ଧନାନ୍ତାରାଷ୍ଟ୍ରିକସ୍ତରାଧାରେଣ ନ କୋଽପି ଭେଦୋ ବିଧାସ୍ୟତେ।"
  specimen_16: "ସର୍ୱେ ମାନବାଃ ସ୍ୱତନ୍ତ୍ରାଃ ସମୁତ୍ପନ୍ନାଃ ବର୍ତନ୍ତେ ଅପି ଚ, ଗୌରବଦୃଶା ଅଧିକାରଦୃଶା ଚ ସମାନାଃ ଏବ ବର୍ତନ୍ତେ। ଏତେ ସର୍ୱେ ଚେତନାତର୍କଶକ୍ତିଭ୍ୟାଂ ସୁସମ୍ପନ୍ନାଃ ସନ୍ତି। ଅପି ଚ, ସର୍ୱେଽପି ବନ୍ଧୁତ୍ୱଭାବନୟା ପରସ୍ପରଂ ବ୍ୟବହରନ୍ତୁ।\nଅସ୍ୟାଂ ଅଭିଘୋଷଣାୟାଂ ନିର୍ଦିଷ୍ଟାଃ ସର୍ୱେଽପି ଅଧିକାରାଃ ସର୍ୱାଣ୍ୟପି ଚ ସ୍ୱାତନ୍ତ୍ର୍ୟାଣି, ବିନୈବ ଜାତିବର୍ଣଲିଂଗଭାଷାଧର୍ମରାଜନୀତିକତଦିତରମନ୍ତବ୍ୟାଦିଭେଦମ୍, ରାଷ୍ଟ୍ରିୟଂ ସାମାଜିକାଧାରଂ ସମ୍ପଜ୍ଜନ୍ମତଦିତର ସ୍ତରଞ୍ଚ ଅବିଗଣୟ୍ୟ, ଅଧିଗନ୍ତୁଂ ସର୍ୱୋଽପି ଜନଃ ପ୍ରଭବତି।\nଏତଦତିରିକ୍ତମ୍, କସ୍ୟାଶ୍ଚିଦପି ପ୍ରଭୁସତ୍ତାୟାଃ ନିୟମନାନ୍ତର୍ଗତମ୍, ସ୍ୱାଧୀନସ୍ୟ ଆତ୍ମପ୍ରଶାସନେତରତନ୍ତ୍ରସ୍ୟ, ନ୍ୟାସିତନ୍ତ୍ରସ୍ୟ ବା ବାସ୍ତବ୍ୟସ୍ୟ ପ୍ରଦେଶସ୍ୟ ଦେଶସ୍ୟ ବା ରାଜନୀତିକସୀମାନିବନ୍ଧନାନ୍ତାରାଷ୍ଟ୍ରିକସ୍ତରାଧାରେଣ ନ କୋଽପି ଭେଦୋ ବିଧାସ୍ୟତେ।\nସର୍ୱୋଽପି ଜନଃ ଜୀବନସ୍ୱାତନ୍ତ୍ର୍ୟସୁରକ୍ଷାଧିକାରଂ ସଂଧତ୍ତେ।\nନ କମପି ଜନଂ ଦାସତ୍ୱେନ ପରାଧୀନତ୍ୱେନ ବା ଧାରୟିତୁଂ ଅନୁଜ୍ଞାସ୍ୟତେ। ଅପି ଚ ଦାସବ୍ୟାପାରଃ ପୂର୍ଣରୂପେଣ ପ୍ରତିଷିଦ୍ଧଃ ସ୍ଥାସ୍ୟତି।\nନ କମପି ଜନଂ ବିରୁଧ୍ୟ ଅବମାନନାତ୍ମକଂ ବ୍ୟବହାରଂ ଦଣ୍ଡଂ ବା କ୍ରୂରଂ ଅମାନବୀୟଂ ପ୍ରତୋଦନଂ ବା ପ୍ରବର୍ତୟିତୁଂ ଅନୁଜ୍ଞାସ୍ୟତେ।"
}
