id: "sa_Olck"
language: "sa"
script: "Olck"
name: "Sanskrit, Ol Chiki"
sample_text {
  masthead_full: "ᱥᱚᱨᱣ"
  masthead_partial: "ᱮᱢ"
  styles: "ᱭᱚᱛᱨᱚ ᱡᱚᱜᱚᱛᱤ ᱥᱟᱱᱛᱤ-ᱱᱭᱟᱭᱚ-ᱥᱣᱟᱛᱚᱱᱛᱨᱭᱟᱬᱟᱝ ᱟᱫᱷᱟᱨᱚᱷ"
  tester: "ᱥᱚᱨᱣᱮ ᱢᱟᱱᱚᱣᱟᱷ ᱥᱣᱚᱛᱚᱱᱛᱨᱟᱷ ᱥᱚᱢᱩᱛᱯᱚᱱᱱᱟᱷ ᱣᱚᱨᱛᱚᱱᱛᱮ ᱚᱯᱤ ᱪᱚ, ᱜᱚᱩᱨᱚᱣᱚᱫᱨᱩᱥᱟ"
  poster_sm: "ᱮᱛᱚᱫᱚᱛᱤᱨᱤᱠᱛᱚᱢ,"
  poster_md: "ᱱᱚ ᱠᱚᱢᱚᱯᱤ"
  poster_lg: "ᱥᱚᱨᱣᱮ"
  specimen_48: "ᱱᱚ ᱠᱚᱢᱚᱯᱤ ᱡᱚᱱᱚᱝ ᱣᱤᱨᱩᱫᱷᱭᱚ ᱚᱣᱚᱢᱟᱱᱚᱱᱟᱛᱢᱚᱠᱚᱝ ᱣᱭᱚᱣᱚᱦᱟᱨᱚᱝ ᱫᱚᱬᱰᱚᱝ ᱣᱟ"
  specimen_36: "ᱠᱟᱨᱭᱚᱦᱳᱨᱟᱬᱟᱝ ᱥᱚᱢᱩᱪᱤᱛᱚ-ᱱᱤᱭᱚᱢᱚᱱᱚ-ᱯᱩᱨᱚᱥᱥᱚᱨᱚᱢ, ᱥᱚᱣᱮᱛᱚᱱᱚᱝ ᱪᱚ ᱱᱤᱭᱚᱛᱟᱣᱚᱫᱷᱤᱠᱟᱣᱚᱠᱟᱥᱮᱱᱚ ᱥᱚᱦᱚ ᱣᱤᱥᱨᱚᱢᱟᱫᱷᱤᱠᱟᱨᱚᱷ ᱯᱨᱚᱛᱭᱚᱠᱚᱥᱢᱚᱤ ᱯᱨᱚᱫᱮᱭᱳ\'ᱥᱛᱤ᱾"
  specimen_32: "ᱚᱥᱭᱟᱝ ᱚᱵᱷᱤᱜᱷᱳᱥᱚᱬᱟᱭᱟᱝ ᱱᱤᱨᱫᱤᱥᱴᱟᱱᱟᱝ ᱚᱫᱷᱤᱠᱟᱨᱟᱬᱟᱝ ᱥᱣᱟᱛᱚᱱᱛᱨᱭᱟᱬᱟᱝ ᱪᱚ ᱯᱨᱟᱯᱛᱚᱭᱮ ᱥᱟᱢᱟᱡᱤᱠᱟᱱᱛᱟᱨᱟᱥᱴᱨᱤᱠᱚ-ᱣᱭᱚᱣᱚᱥᱛᱷᱟᱭᱟᱝ ᱪᱚ ᱯᱩᱻᱨᱬᱚᱛᱚᱭᱟ ᱮᱛᱟᱱ ᱚᱫᱷᱤᱜᱚᱱᱛᱩᱝ ᱯᱨᱚᱛᱭᱮᱠᱚᱢᱚᱯᱤ ᱡᱚᱱᱳ\'ᱨᱦᱤᱥᱭᱚᱛᱮ᱾"
  specimen_21: "ᱚᱥᱭᱟᱝ ᱚᱵᱷᱤᱜᱷᱳᱥᱚᱬᱟᱭᱟᱝ ᱱᱤᱨᱫᱤᱥᱴᱟᱱᱟᱝ ᱚᱫᱷᱤᱠᱟᱨᱟᱬᱟᱝ ᱥᱣᱟᱛᱚᱱᱛᱨᱚᱭᱟᱬᱟᱝ ᱪᱚ ᱱᱚ ᱠᱳ\'ᱯᱭᱚᱝᱥᱚᱷ, ᱯᱨᱚᱬᱟᱥᱚ-ᱞᱚᱠᱥᱭᱟᱫᱷᱟᱨᱮᱬᱚ ᱠᱤᱢᱚᱯᱤ ᱠᱟᱨᱭᱚᱢᱚᱱᱩᱥᱴᱷᱟᱛᱩᱝ ᱮᱛᱟᱫᱨᱩᱠᱠᱟᱨᱭᱟᱱᱩᱥᱴᱷᱟᱱᱟᱨᱛᱷᱚᱝ ᱣᱟ ᱠᱚᱥᱭᱚᱪᱤᱛ ᱨᱟᱥᱴᱨᱚᱥᱭᱚ ᱣᱚᱨᱜᱚᱥᱭᱚ ᱡᱚᱱᱚᱥᱭᱚ ᱣᱟ ᱥᱚᱢᱤᱻᱦᱤᱛᱚ-ᱥᱤᱫᱫᱷᱚᱭᱚᱨᱛᱷᱚᱝ ᱚᱱᱭᱚᱛᱷᱟ ᱣᱭᱟᱠᱷᱭᱟᱛᱩᱝ ᱱᱚᱤᱣᱚ ᱥᱚᱠᱥᱭᱚᱛᱮ᱾\nᱥᱚᱨᱣᱮ ᱢᱟᱱᱚᱣᱟᱷ ᱥᱣᱚᱛᱚᱱᱛᱨᱟᱷ ᱥᱚᱢᱩᱛᱯᱚᱱᱱᱟᱷ ᱣᱚᱨᱛᱚᱱᱛᱮ ᱚᱯᱤ ᱪᱚ, ᱜᱚᱩᱨᱚᱣᱚᱫᱨᱩᱥᱟ ᱚᱫᱷᱤᱠᱟᱨᱚᱫᱨᱩᱥᱟ ᱪᱚ ᱥᱚᱢᱟᱱᱟᱷ ᱮᱣᱚ ᱣᱚᱨᱛᱚᱱᱛᱮ᱾ ᱮᱛᱮ ᱥᱚᱨᱣᱮ ᱪᱮᱛᱚᱱᱟ-ᱛᱚᱨᱠᱚ-ᱥᱚᱠᱛᱤᱵᱷᱭᱟᱝ ᱥᱩᱥᱚᱢᱯᱚᱱᱱᱟᱷ ᱥᱚᱱᱛᱤ᱾ ᱚᱯᱤ ᱪᱚ, ᱥᱚᱨᱣᱮ\'ᱯᱤ ᱵᱚᱱᱫᱷᱩᱛᱣᱚ-ᱵᱷᱟᱣᱚᱱᱚᱭᱟ ᱯᱚᱨᱚᱥᱯᱚᱨᱚᱝ ᱣᱭᱚᱣᱚᱦᱚᱨᱚᱱᱛᱩ᱾"
  specimen_16: "ᱥᱚᱨᱣᱮ ᱢᱟᱱᱚᱣᱟᱷ ᱥᱣᱚᱛᱚᱱᱛᱨᱟᱷ ᱥᱚᱢᱩᱛᱯᱚᱱᱱᱟᱷ ᱣᱚᱨᱛᱚᱱᱛᱮ ᱚᱯᱤ ᱪᱚ, ᱜᱚᱩᱨᱚᱣᱚᱫᱨᱩᱥᱟ ᱚᱫᱷᱤᱠᱟᱨᱚᱫᱨᱩᱥᱟ ᱪᱚ ᱥᱚᱢᱟᱱᱟᱷ ᱮᱣᱚ ᱣᱚᱨᱛᱚᱱᱛᱮ᱾ ᱮᱛᱮ ᱥᱚᱨᱣᱮ ᱪᱮᱛᱚᱱᱟ-ᱛᱚᱨᱠᱚ-ᱥᱚᱠᱛᱤᱵᱷᱭᱟᱝ ᱥᱩᱥᱚᱢᱯᱚᱱᱱᱟᱷ ᱥᱚᱱᱛᱤ᱾ ᱚᱯᱤ ᱪᱚ, ᱥᱚᱨᱣᱮ\'ᱯᱤ ᱵᱚᱱᱫᱷᱩᱛᱣᱚ-ᱵᱷᱟᱣᱚᱱᱚᱭᱟ ᱯᱚᱨᱚᱥᱯᱚᱨᱚᱝ ᱣᱭᱚᱣᱚᱦᱚᱨᱚᱱᱛᱩ᱾\nᱚᱥᱭᱟᱝ ᱚᱵᱷᱤᱜᱷᱳᱥᱚᱬᱟᱭᱟᱝ ᱱᱤᱨᱫᱤᱥᱴᱟᱷ ᱥᱚᱨᱣᱮ\'ᱯᱤ ᱚᱫᱷᱤᱠᱟᱨᱟᱷ ᱥᱚᱨᱣᱟᱬᱭᱚᱯᱤ ᱪᱚ ᱥᱣᱟᱛᱚᱱᱛᱨᱭᱟᱬᱤ, ᱣᱤᱱᱚᱤᱣᱚ ᱡᱟᱛᱤ-ᱣᱚᱨᱬᱚ-ᱞᱤᱝᱜᱚ-ᱵᱷᱟᱥᱟ-ᱫᱷᱚᱨᱢᱚ-ᱨᱟᱡᱚᱱᱤᱻᱛᱤᱠᱚ-ᱛᱚᱫᱤᱛᱚᱨᱚ-ᱢᱚᱱᱛᱚᱣᱭᱟᱫᱤ-ᱵᱷᱮᱫᱚᱢ, ᱨᱟᱥᱴᱨᱤᱭᱚᱝ ᱥᱟᱢᱟᱡᱤᱠᱟᱫᱷᱟᱨᱚᱝ ᱥᱚᱢᱯᱚᱡᱡᱚᱱᱢᱚ-ᱛᱚᱫᱤᱛᱚᱨᱚ ᱥᱛᱚᱨᱚᱧᱪᱚ ᱚᱣᱤᱜᱚᱬᱚᱭᱭᱚ, ᱚᱫᱷᱤᱜᱚᱱᱛᱩᱝ ᱥᱚᱨᱣᱳ\'ᱯᱤ ᱡᱚᱱᱚᱷ ᱯᱨᱚᱵᱷᱚᱣᱚᱛᱤ᱾\nᱮᱛᱚᱫᱚᱛᱤᱨᱤᱠᱛᱚᱢ, ᱠᱚᱥᱭᱟᱥᱪᱤᱫᱚᱯᱤ ᱯᱨᱚᱵᱷᱩᱥᱚᱛᱛᱟᱭᱟᱷ ᱱᱤᱭᱚᱢᱚᱱᱟᱱᱛᱚᱨᱜᱚᱛᱚᱢ, ᱥᱣᱟᱫᱷᱤᱻᱱᱚᱥᱭᱚ ᱟᱛᱢᱚᱯᱨᱚᱥᱟᱥᱚᱱᱮᱛᱚᱨᱚ-ᱛᱚᱱᱛᱨᱚᱥᱭᱚ, ᱱᱭᱟᱥᱤᱛᱚᱱᱛᱨᱚᱥᱭᱚ ᱣᱟ ᱣᱟᱥᱛᱚᱣᱭᱚᱥᱭᱚ ᱯᱨᱚᱫᱮᱥᱚᱥᱭᱚ ᱫᱮᱥᱚᱥᱭᱚ ᱣᱟ ᱨᱟᱡᱚᱱᱤᱻᱛᱤᱠᱚ-ᱥᱤᱻᱢᱟ-ᱱᱤᱵᱚᱱᱫᱷᱚᱱᱟᱱᱛᱟᱨᱟᱥᱴᱨᱤᱠᱚ-ᱥᱛᱚᱨᱟᱫᱷᱟᱨᱮᱬᱚ ᱱᱚ ᱠᱳ\'ᱯᱤ ᱵᱷᱮᱫᱳ ᱣᱤᱫᱷᱟᱥᱭᱚᱛᱮ᱾"
}
historical: true
