id: "sa_Rjng"
language: "sa"
script: "Rjng"
name: "Sanskrit, Rejang"
region: "IN"
sample_text {
  masthead_full: "ꤼꥀꤸꤵ"
  masthead_partial: "ꤳꤽ"
  styles: "ꤿꤳ꥓ꤽ ꤺꤱꤳꥇ ꤼꥐꤳꥇꤵ꥓ꤿꤿꤼ꥓ꥀꤳꥐꤳ꥓ꤽ꥓ꤿꤵꥏ ꥆꤴꤽꥒ ꤸꤵꥀꤶꤽꥇꥀꤽꤼ꥓ꤿ ꤼꥑꥀꥉꤼꤸꤶꥇ"
  tester: "ꤼꥑꥀꥉ ꤸꤵꥀꥒ ꤼ꥓ꥀꤳꥐꤳ꥓ꤽꥒ ꤼꤸꥈꤳ꥓ꤶꥐꤵꥒ ꥀꥑꤳꥐꤳꥉ ꥆꤶꥇ ꤹ, ꤱꥌꤽꥀꤴ꥓ꤽꥈꤼ ꥆꤴꥇꤰꤽꤴ꥓ꤽꥈꤼ ꤹ ꤼꤸꤵꥒ ꥆꥉꥀ ꥀꥑꤳꥐꤳꥉ. ꥆꥉꤳꥉ ꤼꥑꥀꥉ"
  poster_sm: "ꥆꤼ꥓ꤿꥏ ꥆꤷꥇꤱꥋꤼꤵꤿꥏ"
  poster_md: "ꥆꥉꤳꤴꤳꥇꤽꥇꤰ꥓ꤳꤸ꥓,"
  poster_lg: "ꤸꤵꥀꥒ"
  specimen_48: "ꤵ ꤰꤸꤶꥇ ꤺꤵꥏ ꤴꤼꤳ꥓ꥀꥉꤵ ꤶꤽꤴꥇꤵꤳ꥓ꥀꥉꤵ ꥀ ꤴꤽꤿꥇꤳꥈꥏ ꥆꤵꥈꤺ꥓ꤻꤼ꥓ꤿꤳꥉ. ꥆꤶꥇ ꤹ ꤴꤼꥀ꥓ꤿꤶꤽꥒ ꤶꥈꥑꤵꤽꥈꤶꥉꤵ ꤶ꥓ꤽꤳꥇꤼꥇꤴ꥓ꤴꥒ"
  specimen_36: "ꤼꥑꥀꥉ ꤸꤵꥀꥒ ꤼ꥓ꥀꤳꥐꤳ꥓ꤽꥒ ꤼꤸꥈꤳ꥓ꤶꥐꤵꥒ ꥀꥑꤳꥐꤳꥉ ꥆꤶꥇ ꤹ, ꤱꥌꤽꥀꤴ꥓ꤽꥈꤼ ꥆꤴꥇꤰꤽꤴ꥓ꤽꥈꤼ ꤹ ꤼꤸꤵꥒ ꥆꥉꥀ ꥀꥑꤳꥐꤳꥉ. ꥆꥉꤳꥉ ꤼꥑꥀꥉ ꤹꥉꤳꤵꤳꥑꤰꤼꤰ꥓ꤳꥇꤷ꥓ꤿꥏ ꤼꥈꤼꤸ꥓ꤶꥐꤵꥒ ꤼꥐꤳꥇ. ꥆꤶꥇ ꤹ, ꤼꥑꥀꥉ\'ꤶꥇ ꤷꥐꤴꥈꤳ꥓ꥀꤷꥀꤵꤿ ꤶꤽꤼ꥓ꤶꤽꥏ ꥀ꥓ꤿꥀꥁꤽꥐꤳꥈ."
  specimen_32: "ꤼꥑꥀꥋ\'ꤶꥇ ꤺꤵꥒ, ꤼ꥓ꥀꥏ ꥀꥇꤽꥈꤴ꥓ꤿ ꤶ꥓ꤽꥀꥑꤳ꥓ꤳꥇꤳꤼ꥓ꤿ ꤰꤼ꥓ꤿꤶꥇ ꥆꤶꤽꤴꥇꤰꤰ꥓ꤼꥉꤶꤼ꥓ꤿ, ꤼ꥓ꥀꥇꤿꤴꥇꤰꤽꤵꥏ ꤴꤿꥇꤳ꥓ꥀꤵꥏ ꤹ, ꥀꥇꤵꥇꥑꤴꤽꤵꤼ꥓ꤿ ꤹ ꤰ꥓ꤽꥈꤳꥉ, ꤼ꥓ꥀꤴꥇꤵꥉꤵ ꤵꥇꤼ꥓ꤶꤰ꥓ꤼꥉꤵ ꤹ ꤵ꥓ꤿꤿꤶꥇꤳꥉꤵ ꥀꥇꤴꥇꤿꤸꤵꤼ꥓ꤿ ꤼꤸꥈꤹꥇꤳꤼ꥓ꤿ ꤼꥑꥀꤺꤵꥇꤰꤼ꥓ꤿ ꤼ꥓ꤽꥀꤵꤼ꥓ꤿ ꤹ ꤰ꥓ꤽꥈꤳꥉ ꤼꥑꥀꥋ\'ꤶꥇ ꤺꤵꥒ ꤶꥈꥑꤵꥏ ꤼꤸꤵꤳꥏ ꤴꤽꤿꤳꥇ."
  specimen_21: "ꤼꥑꥀꥉ ꤸꤵꥀꥒ ꤼ꥓ꥀꤳꥐꤳ꥓ꤽꥒ ꤼꤸꥈꤳ꥓ꤶꥐꤵꥒ ꥀꥑꤳꥐꤳꥉ ꥆꤶꥇ ꤹ, ꤱꥌꤽꥀꤴ꥓ꤽꥈꤼ ꥆꤴꥇꤰꤽꤴ꥓ꤽꥈꤼ ꤹ ꤼꤸꤵꥒ ꥆꥉꥀ ꥀꥑꤳꥐꤳꥉ. ꥆꥉꤳꥉ ꤼꥑꥀꥉ ꤹꥉꤳꤵꤳꥑꤰꤼꤰ꥓ꤳꥇꤷ꥓ꤿꥏ ꤼꥈꤼꤸ꥓ꤶꥐꤵꥒ ꤼꥐꤳꥇ. ꥆꤶꥇ ꤹ, ꤼꥑꥀꥉ\'ꤶꥇ ꤷꥐꤴꥈꤳ꥓ꥀꤷꥀꤵꤿ ꤶꤽꤼ꥓ꤶꤽꥏ ꥀ꥓ꤿꥀꥁꤽꥐꤳꥈ.\nꥆꤼ꥓ꤿꥏ ꥆꤷꥇꤱꥋꤼꤵꤿꥏ ꤵꥇꥑꤴꥇꤼ꥓ꤳꥒ ꤼꥑꥀꥉ\'ꤶꥇ ꥆꤴꥇꤰꤽꥒ ꤼꥑꥀꤵ꥓ꤿꤶꥇ ꤹ ꤼ꥓ꥀꤳꥐꤳ꥓ꤽ꥓ꤿꤵꥇ, ꥀꥇꤵꥊꥀ ꤺꤳꥇꥀꥑꤵꤾꥇꥏꤱꤷꤼꤴꥑꤸꤽꤺꤵꥇꤳꥇꤰꤳꤴꥇꤳꤽꤸꥐꤳꥀ꥓ꤿꤴꥇꤷꥉꤴꤸ꥓, ꤽꤼ꥓ꤳ꥓ꤽꥇꤿꥏ ꤼꤸꤺꥇꤰꤴꤽꥏ ꤼꤸ꥓ꤶꤺ꥓ꤺꥐꤸꤳꤴꥇꤳꤽ ꤼ꥓ꤳꤽꤻ꥓ꤹ ꥆꥀꥇꤱꤵꤿ꥓ꤿ, ꥆꤴꥇꤱꥐꤳꥈꥏ ꤼꥑꥀꥋ\'ꤶꥇ ꤺꤵꥒ ꤶ꥓ꤽꤷꥀꤳꥇ.\nꥆꥉꤳꤴꤳꥇꤽꥇꤰ꥓ꤳꤸ꥓, ꤰꤼ꥓ꤿꤼ꥓ꤹꥇꤴꤶꥇ ꤶ꥓ꤽꤷꥈꤼꤳ꥓ꤳꤿꥒ ꤵꥇꤿꤸꤵꥐꤳꥑꤱꤳꤸ꥓, ꤼ꥓ꥀꤴꥇꤵꤼ꥓ꤿ ꥆꤳ꥓ꤸꤶ꥓ꤽꤼꤼꤵꥉꤳꤽꤳꥐꤳ꥓ꤽꤼ꥓ꤿ, ꤵ꥓ꤿꤼꥇꤳꥐꤳ꥓ꤽꤼ꥓ꤿ ꥀ ꥀꤼ꥓ꤳꥀ꥓ꤿꤼ꥓ꤿ ꤶ꥓ꤽꤴꥉꤼꤼ꥓ꤿ ꤴꥉꤼꤼ꥓ꤿ ꥀ ꤽꤺꤵꥇꤳꥇꤰꤼꥇꤸꤵꥇꤷꥐꤴꤵꥐꤳꤽꤼ꥓ꤳ꥓ꤽꥇꤰꤼ꥓ꤳꤽꤴꤽꥉꤵ ꤵ ꤰꥋ\'ꤶꥇ ꤷꥉꤴꥋ ꥀꥇꤴꤼ꥓ꤿꤳꥉ."
  specimen_16: "ꤼꥑꥀꥉ ꤸꤵꥀꥒ ꤼ꥓ꥀꤳꥐꤳ꥓ꤽꥒ ꤼꤸꥈꤳ꥓ꤶꥐꤵꥒ ꥀꥑꤳꥐꤳꥉ ꥆꤶꥇ ꤹ, ꤱꥌꤽꥀꤴ꥓ꤽꥈꤼ ꥆꤴꥇꤰꤽꤴ꥓ꤽꥈꤼ ꤹ ꤼꤸꤵꥒ ꥆꥉꥀ ꥀꥑꤳꥐꤳꥉ. ꥆꥉꤳꥉ ꤼꥑꥀꥉ ꤹꥉꤳꤵꤳꥑꤰꤼꤰ꥓ꤳꥇꤷ꥓ꤿꥏ ꤼꥈꤼꤸ꥓ꤶꥐꤵꥒ ꤼꥐꤳꥇ. ꥆꤶꥇ ꤹ, ꤼꥑꥀꥉ\'ꤶꥇ ꤷꥐꤴꥈꤳ꥓ꥀꤷꥀꤵꤿ ꤶꤽꤼ꥓ꤶꤽꥏ ꥀ꥓ꤿꥀꥁꤽꥐꤳꥈ.\nꥆꤼ꥓ꤿꥏ ꥆꤷꥇꤱꥋꤼꤵꤿꥏ ꤵꥇꥑꤴꥇꤼ꥓ꤳꥒ ꤼꥑꥀꥉ\'ꤶꥇ ꥆꤴꥇꤰꤽꥒ ꤼꥑꥀꤵ꥓ꤿꤶꥇ ꤹ ꤼ꥓ꥀꤳꥐꤳ꥓ꤽ꥓ꤿꤵꥇ, ꥀꥇꤵꥊꥀ ꤺꤳꥇꥀꥑꤵꤾꥇꥏꤱꤷꤼꤴꥑꤸꤽꤺꤵꥇꤳꥇꤰꤳꤴꥇꤳꤽꤸꥐꤳꥀ꥓ꤿꤴꥇꤷꥉꤴꤸ꥓, ꤽꤼ꥓ꤳ꥓ꤽꥇꤿꥏ ꤼꤸꤺꥇꤰꤴꤽꥏ ꤼꤸ꥓ꤶꤺ꥓ꤺꥐꤸꤳꤴꥇꤳꤽ ꤼ꥓ꤳꤽꤻ꥓ꤹ ꥆꥀꥇꤱꤵꤿ꥓ꤿ, ꥆꤴꥇꤱꥐꤳꥈꥏ ꤼꥑꥀꥋ\'ꤶꥇ ꤺꤵꥒ ꤶ꥓ꤽꤷꥀꤳꥇ.\nꥆꥉꤳꤴꤳꥇꤽꥇꤰ꥓ꤳꤸ꥓, ꤰꤼ꥓ꤿꤼ꥓ꤹꥇꤴꤶꥇ ꤶ꥓ꤽꤷꥈꤼꤳ꥓ꤳꤿꥒ ꤵꥇꤿꤸꤵꥐꤳꥑꤱꤳꤸ꥓, ꤼ꥓ꥀꤴꥇꤵꤼ꥓ꤿ ꥆꤳ꥓ꤸꤶ꥓ꤽꤼꤼꤵꥉꤳꤽꤳꥐꤳ꥓ꤽꤼ꥓ꤿ, ꤵ꥓ꤿꤼꥇꤳꥐꤳ꥓ꤽꤼ꥓ꤿ ꥀ ꥀꤼ꥓ꤳꥀ꥓ꤿꤼ꥓ꤿ ꤶ꥓ꤽꤴꥉꤼꤼ꥓ꤿ ꤴꥉꤼꤼ꥓ꤿ ꥀ ꤽꤺꤵꥇꤳꥇꤰꤼꥇꤸꤵꥇꤷꥐꤴꤵꥐꤳꤽꤼ꥓ꤳ꥓ꤽꥇꤰꤼ꥓ꤳꤽꤴꤽꥉꤵ ꤵ ꤰꥋ\'ꤶꥇ ꤷꥉꤴꥋ ꥀꥇꤴꤼ꥓ꤿꤳꥉ.\nꤼꥑꥀꥋ\'ꤶꥇ ꤺꤵꥒ ꤺꥇꥀꤵꤼ꥓ꥀꤳꥐꤳ꥓ꤽ꥓ꤿꤼꥈꤽꤰ꥓ꤼꤴꥇꤰꤽꥏ ꤼꥏꤴꤳ꥓ꤳꥉ.\nꤵ ꤰꤸꤶꥇ ꤺꤵꥏ ꤴꤼꤳ꥓ꥀꥉꤵ ꤶꤽꤴꥇꤵꤳ꥓ꥀꥉꤵ ꥀ ꤴꤽꤿꥇꤳꥈꥏ ꥆꤵꥈꤺ꥓ꤻꤼ꥓ꤿꤳꥉ. ꥆꤶꥇ ꤹ ꤴꤼꥀ꥓ꤿꤶꤽꥒ ꤶꥈꥑꤵꤽꥈꤶꥉꤵ ꤶ꥓ꤽꤳꥇꤼꥇꤴ꥓ꤴꥒ ꤼ꥓ꤳꤼ꥓ꤿꤳꥇ.\nꤵ ꤰꤸꤶꥇ ꤺꤵꥏ ꥀꥇꤽꥈꤴ꥓ꤿ ꥆꥀꤸꤵꤵꤳ꥓ꤸꤰꥏ ꥀ꥓ꤿꥀꥁꤽꥏ ꤴꤵ꥓ꤴꥏ ꥀ ꤰ꥓ꤽꥈꤽꥏ ꥆꤸꤵꥀꥇꤿꥏ ꤶ꥓ꤽꤳꥋꤴꤵꥏ ꥀ ꤶ꥓ꤽꥀꥑꤳꤿꥇꤳꥈꥏ ꥆꤵꥈꤺ꥓ꤻꤼ꥓ꤿꤳꥉ.\nꥀꥇꤴꥉꥒ ꤼꤸꤰ꥓ꤼꥏ ꤼꥑꥀꥋ\'ꤶꥇ ꤺꤵꥒ ꤼꥑꥀꤳ꥓ꤽ ꥆꤷꥇꤺ꥓ꤻꤳꥈꥏ ꥆꤴꥇꤰꤽꥏ ꤼꥏꤴꤳ꥓ꤳꥉ."
}
historical: true
