id: "sa_Sinh"
language: "sa"
script: "Sinh"
name: "Sanskrit, Sinhala"
population: 0
sample_text {
  masthead_full: "සරවම"
  masthead_partial: "නත"
  styles: "යත්‍ර ජගති ශාන්තින්‍යායස්වාතන්ත්‍ර්යාණාං ආධාරඃ මානවපරිවාරස්‍ය සර්වෙෂාමපි"
  tester: "යත්‍ර ජගති ශාන්තින්‍යායස්වාතන්ත්‍ර්යාණාං ආධාරඃ මානවපරිවාරස්‍ය සර්වෙෂාමපි සදස්‍යානාං සාම්‍යානාං අඛණ්ඩිතානාඤ්ච"
  poster_sm: "යත්‍ර ජගති ශාන"
  poster_md: "යත්‍ර ජගති ශ"
  poster_lg: "සර්වෙ"
  specimen_48: "යත්‍ර ජගති ශාන්තින්‍යායස්වාතන්ත්‍ර්යාණාං ආධාරඃ මානවපරිවාරස්‍ය සර්වෙෂාමපි සදස්‍යානාං සාම්‍යානාං"
  specimen_36: "සර්වො(අ)පි ජනඃ ජීවනස්වාතන්ත්‍ර්යසුරක්‍ෂාධිකාරං සංධත්තෙ.\nන කමපි ජනං දාසත්වෙන පරාධීනත්වෙන වා ධාරයිතුං අනුඥාස්‍යතෙ. අපි ච දාසව්‍යාපාරඃ පූර්ණරූපෙණ ප්‍රතිෂිද්ධඃ ස්ථාස්‍යති."
  specimen_32: "විධෙඃ සමක්‍ෂං සර්වෙ(අ)පි තුල්‍යාඃ සමානාශ්ච වර්තන්තෙ. අපි ච විනෛව කමපි භෙදං විධෙඃ තුල්‍යං සංරක්‍ෂණමවාප්තුං අර්හන්ති. අස්‍යාඃ අභිඝොෂණායාඃ උල්ලංඝනෙ කමපි භෙදං, එතාදෘග්භෙදං වා අභිලක්‍ෂ්‍ය කාමපි චෙෂ්ටාං විරුධ්‍ය සමානසංරක්‍ෂණාර්හාඃ සර්වෙ(අ)පි වර්තන්තෙ."
  specimen_21: "සර්වෙ මානවාඃ ස්වතන්ත්‍රාඃ සමුත්පන්නාඃ වර්තන්තෙ අපි ච, ගෞරවදෘශා අධිකාරදෘශා ච සමානාඃ එව වර්තන්තෙ. එතෙ සර්වෙ චෙතනාතර්කශක්තිභ්‍යාං සුසම්පන්නාඃ සන්ති. අපි ච, සර්වෙ(අ)පි බන්ධුත්වභාවනයා පරස්පරං ව්‍යවහරන්තු.\nඅස්‍යාං අභිඝොෂණායාං නිර්දිෂ්ටාඃ සර්වෙ(අ)පි අධිකාරාඃ සර්වාණ්‍යපි ච ස්වාතන්ත්‍ර්යාණි, විනෛව ජාතිවර්ණලිංගභාෂාධර්මරාජනීතිකතදිතරමන්තව්‍යාදිභෙදම්, රාෂ්ට්‍රියං සාමාජිකාධාරං සම්පජ්ජන්මතදිතර ස්තරඤ්ච අවිගණය්‍ය, අධිගන්තුං සර්වො(අ)පි ජනඃ ප්‍රභවති.\nඑතදතිරික්තම්, කස්‍යාශ්චිදපි ප්‍රභුසත්තායාඃ නියමනාන්තර්ගතම්, ස්වාධීනස්‍ය ආත්මප්‍රශාසනෙතරතන්ත්‍රස්‍ය, න්‍යාසිතන්ත්‍රස්‍ය වා වාස්තව්‍යස්‍ය ප්‍රදෙශස්‍ය දෙශස්‍ය වා රාජනීතිකසීමානිබන්ධනාන්තාරාෂ්ට්‍රිකස්තරාධාරෙණ න කො(අ)පි භෙදො විධාස්‍යතෙ."
  specimen_16: "සර්වෙ මානවාඃ ස්වතන්ත්‍රාඃ සමුත්පන්නාඃ වර්තන්තෙ අපි ච, ගෞරවදෘශා අධිකාරදෘශා ච සමානාඃ එව වර්තන්තෙ. එතෙ සර්වෙ චෙතනාතර්කශක්තිභ්‍යාං සුසම්පන්නාඃ සන්ති. අපි ච, සර්වෙ(අ)පි බන්ධුත්වභාවනයා පරස්පරං ව්‍යවහරන්තු.\nඅස්‍යාං අභිඝොෂණායාං නිර්දිෂ්ටාඃ සර්වෙ(අ)පි අධිකාරාඃ සර්වාණ්‍යපි ච ස්වාතන්ත්‍ර්යාණි, විනෛව ජාතිවර්ණලිංගභාෂාධර්මරාජනීතිකතදිතරමන්තව්‍යාදිභෙදම්, රාෂ්ට්‍රියං සාමාජිකාධාරං සම්පජ්ජන්මතදිතර ස්තරඤ්ච අවිගණය්‍ය, අධිගන්තුං සර්වො(අ)පි ජනඃ ප්‍රභවති.\nඑතදතිරික්තම්, කස්‍යාශ්චිදපි ප්‍රභුසත්තායාඃ නියමනාන්තර්ගතම්, ස්වාධීනස්‍ය ආත්මප්‍රශාසනෙතරතන්ත්‍රස්‍ය, න්‍යාසිතන්ත්‍රස්‍ය වා වාස්තව්‍යස්‍ය ප්‍රදෙශස්‍ය දෙශස්‍ය වා රාජනීතිකසීමානිබන්ධනාන්තාරාෂ්ට්‍රිකස්තරාධාරෙණ න කො(අ)පි භෙදො විධාස්‍යතෙ.\nසර්වො(අ)පි ජනඃ ජීවනස්වාතන්ත්‍ර්යසුරක්‍ෂාධිකාරං සංධත්තෙ.\nන කමපි ජනං දාසත්වෙන පරාධීනත්වෙන වා ධාරයිතුං අනුඥාස්‍යතෙ. අපි ච දාසව්‍යාපාරඃ පූර්ණරූපෙණ ප්‍රතිෂිද්ධඃ ස්ථාස්‍යති.\nන කමපි ජනං විරුධ්‍ය අවමානනාත්මකං ව්‍යවහාරං දණ්ඩං වා ක්‍රූරං අමානවීයං ප්‍රතොදනං වා ප්‍රවර්තයිතුං අනුඥාස්‍යතෙ."
}
historical: true
