id: "sa_Saur"
language: "sa"
script: "Saur"
name: "Sanskrit, Saurashtra"
region: "IN"
sample_text {
  masthead_full: "ꢱꢬꢮꢪ"
  masthead_partial: "ꢥꢡ"
  styles: "ꢫꢡ꣄ꢬ ꢙꢔꢡꢶ ꢯꢵꢥ꣄ꢡꢶꢥ꣄ꢫꢵꢫꢱ꣄ꢮꢵꢡꢥ꣄ꢡ꣄ꢬ꣄ꢫꢵꢠꢵꢀ ꢃꢤꢵꢬꢁ ꢪꢵꢥꢮꢦꢬꢶꢮꢵꢬꢱ꣄ꢫ ꢱꢬ꣄ꢮꢿꢰꢵꢪꢦꢶ"
  tester: "ꢱꢬ꣄ꢮꢿ ꢪꢵꢥꢮꢵꢁ ꢱ꣄ꢮꢡꢥ꣄ꢡ꣄ꢬꢵꢁ ꢱꢪꢸꢡ꣄ꢦꢥ꣄ꢥꢵꢁ ꢮꢬ꣄ꢡꢥ꣄ꢡꢿ ꢂꢦꢶ ꢗ, ꢔꣃꢬꢮꢣꢺꢯꢵ ꢂꢤꢶꢒꢵꢬꢣꢺꢯꢵ ꢗ ꢱꢪꢵꢥꢵꢁ ꢍꢮ ꢮꢬ꣄ꢡꢥ꣄ꢡꢿ꣎"
  poster_sm: "ꢂꢱ꣄ꢫꢵꢀ ꢂꢩꢶꢕꣂꢰꢠꢵꢫꢵꢀ"
  poster_md: "ꢍꢡꢣꢡꢶꢬꢶꢒ꣄ꢡꢪ꣄,"
  poster_lg: "ꢱꢬ꣄ꢮꢿ"
  specimen_48: "ꢥ ꢒꢪꢦꢶ ꢙꢥꢀ ꢣꢵꢱꢡ꣄ꢮꢿꢥ ꢦꢬꢵꢤꢷꢥꢡ꣄ꢮꢿꢥ ꢮꢵ ꢤꢵꢬꢫꢶꢡꢸꢀ ꢂꢥꢸꢙ꣄ꢛꢵꢱ꣄ꢫꢡꢿ꣎ ꢂꢦꢶ ꢗ ꢣꢵꢱꢮ꣄ꢫꢵꢦꢵꢬꢁ ꢦꢹꢬ꣄ꢠꢬꢹꢦꢿꢠ ꢦ꣄ꢬꢡꢶꢰꢶꢣ꣄ꢤꢁ"
  specimen_36: "ꢱꢬ꣄ꢮꣂఽꢦꢶ ꢙꢥꢁ ꢙꢷꢮꢥꢱ꣄ꢮꢵꢡꢥ꣄ꢡ꣄ꢬ꣄ꢫꢱꢸꢬꢒ꣄‍ꢰꢵꢤꢶꢒꢵꢬꢀ ꢱꢀꢤꢡ꣄ꢡꢿ꣎\nꢥ ꢒꢪꢦꢶ ꢙꢥꢀ ꢣꢵꢱꢡ꣄ꢮꢿꢥ ꢦꢬꢵꢤꢷꢥꢡ꣄ꢮꢿꢥ ꢮꢵ ꢤꢵꢬꢫꢶꢡꢸꢀ ꢂꢥꢸꢙ꣄ꢛꢵꢱ꣄ꢫꢡꢿ꣎ ꢂꢦꢶ ꢗ ꢣꢵꢱꢮ꣄ꢫꢵꢦꢵꢬꢁ ꢦꢹꢬ꣄ꢠꢬꢹꢦꢿꢠ ꢦ꣄ꢬꢡꢶꢰꢶꢣ꣄ꢤꢁ ꢱ꣄ꢢꢵꢱ꣄ꢫꢡꢶ꣎"
  specimen_32: "ꢮꢶꢤꢿꢁ ꢱꢪꢒ꣄‍ꢰꢀ ꢱꢬ꣄ꢮꢿఽꢦꢶ ꢡꢸꢭ꣄ꢫꢵꢁ ꢱꢪꢵꢥꢵꢯ꣄ꢗ ꢮꢬ꣄ꢡꢥ꣄ꢡꢿ꣎ ꢂꢦꢶ ꢗ ꢮꢶꢥꣀꢮ ꢒꢪꢦꢶ ꢩꢿꢣꢀ ꢮꢶꢤꢿꢁ ꢡꢸꢭ꣄ꢫꢀ ꢱꢀꢬꢒ꣄‍ꢰꢠꢪꢮꢵꢦ꣄ꢡꢸꢀ ꢂꢬꢴꢥ꣄ꢡꢶ꣎ ꢂꢱ꣄ꢫꢵꢁ ꢂꢩꢶꢕꣂꢰꢠꢵꢫꢵꢁ ꢆꢭ꣄ꢭꢀꢕꢥꢿ ꢒꢪꢦꢶ ꢩꢿꢣꢀ, ꢍꢡꢵꢣꢺꢔ꣄ꢩꢿꢣꢀ ꢮꢵ ꢂꢩꢶꢭꢒ꣄‍ꢰ꣄ꢫ ꢒꢵꢪꢦꢶ ꢗꢿꢰ꣄ꢜꢵꢀ ꢮꢶꢬꢸꢤ꣄ꢫ ꢱꢪꢵꢥꢱꢀꢬꢒ꣄‍ꢰꢠꢵꢬꢴꢵꢁ ꢱꢬ꣄ꢮꢿఽꢦꢶ ꢮꢬ꣄ꢡꢥ꣄ꢡꢿ꣎"
  specimen_21: "ꢱꢬ꣄ꢮꢿ ꢪꢵꢥꢮꢵꢁ ꢱ꣄ꢮꢡꢥ꣄ꢡ꣄ꢬꢵꢁ ꢱꢪꢸꢡ꣄ꢦꢥ꣄ꢥꢵꢁ ꢮꢬ꣄ꢡꢥ꣄ꢡꢿ ꢂꢦꢶ ꢗ, ꢔꣃꢬꢮꢣꢺꢯꢵ ꢂꢤꢶꢒꢵꢬꢣꢺꢯꢵ ꢗ ꢱꢪꢵꢥꢵꢁ ꢍꢮ ꢮꢬ꣄ꢡꢥ꣄ꢡꢿ꣎ ꢍꢡꢿ ꢱꢬ꣄ꢮꢿ ꢗꢿꢡꢥꢵꢡꢬ꣄ꢒꢯꢒ꣄ꢡꢶꢩ꣄ꢫꢵꢀ ꢱꢸꢱꢪ꣄ꢦꢥ꣄ꢥꢵꢁ ꢱꢥ꣄ꢡꢶ꣎ ꢂꢦꢶ ꢗ, ꢱꢬ꣄ꢮꢿఽꢦꢶ ꢨꢥ꣄ꢤꢸꢡ꣄ꢮꢩꢵꢮꢥꢫꢵ ꢦꢬꢱ꣄ꢦꢬꢀ ꢮ꣄ꢫꢮꢲꢬꢥ꣄ꢡꢸ꣎\nꢂꢱ꣄ꢫꢵꢀ ꢂꢩꢶꢕꣂꢰꢠꢵꢫꢵꢀ ꢥꢶꢬ꣄ꢣꢶꢰ꣄ꢜꢵꢁ ꢱꢬ꣄ꢮꢿఽꢦꢶ ꢂꢤꢶꢒꢵꢬꢵꢁ ꢱꢬ꣄ꢮꢵꢠ꣄ꢫꢦꢶ ꢗ ꢱ꣄ꢮꢵꢡꢥ꣄ꢡ꣄ꢬ꣄ꢫꢵꢠꢶ, ꢮꢶꢥꣀꢮ ꢙꢵꢡꢶꢮꢬ꣄ꢠꢭꢶꢀꢔꢩꢵꢰꢵꢤꢬ꣄ꢪꢬꢵꢙꢥꢷꢡꢶꢒꢡꢣꢶꢡꢬꢪꢥ꣄ꢡꢮ꣄ꢫꢵꢣꢶꢩꢿꢣꢪ꣄, ꢬꢵꢰ꣄ꢜ꣄ꢬꢶꢫꢀ ꢱꢵꢪꢵꢙꢶꢒꢵꢤꢵꢬꢀ ꢱꢪ꣄ꢦꢙ꣄ꢙꢥ꣄ꢪꢡꢣꢶꢡꢬ ꢱ꣄ꢡꢬꢛ꣄ꢗ ꢂꢮꢶꢔꢠꢫ꣄ꢫ, ꢂꢤꢶꢔꢥ꣄ꢡꢸꢀ ꢱꢬ꣄ꢮꣂఽꢦꢶ ꢙꢥꢁ ꢦ꣄ꢬꢩꢮꢡꢶ꣎\nꢍꢡꢣꢡꢶꢬꢶꢒ꣄ꢡꢪ꣄, ꢒꢱ꣄ꢫꢵꢯ꣄ꢗꢶꢣꢦꢶ ꢦ꣄ꢬꢩꢸꢱꢡ꣄ꢡꢵꢫꢵꢁ ꢥꢶꢫꢪꢥꢵꢥ꣄ꢡꢬ꣄ꢔꢡꢪ꣄, ꢱ꣄ꢮꢵꢤꢷꢥꢱ꣄ꢫ ꢃꢡ꣄ꢪꢦ꣄ꢬꢯꢵꢱꢥꢿꢡꢬꢡꢥ꣄ꢡ꣄ꢬꢱ꣄ꢫ, ꢥ꣄ꢫꢵꢱꢶꢡꢥ꣄ꢡ꣄ꢬꢱ꣄ꢫ ꢮꢵ ꢮꢵꢱ꣄ꢡꢮ꣄ꢫꢱ꣄ꢫ ꢦ꣄ꢬꢣꢿꢯꢱ꣄ꢫ ꢣꢿꢯꢱ꣄ꢫ ꢮꢵ ꢬꢵꢙꢥꢷꢡꢶꢒꢱꢷꢪꢵꢥꢶꢨꢥ꣄ꢤꢥꢵꢥ꣄ꢡꢵꢬꢵꢰ꣄ꢜ꣄ꢬꢶꢒꢱ꣄ꢡꢬꢵꢤꢵꢬꢿꢠ ꢥ ꢒꣂఽꢦꢶ ꢩꢿꢣꣂ ꢮꢶꢤꢵꢱ꣄ꢫꢡꢿ꣎"
  specimen_16: "ꢱꢬ꣄ꢮꢿ ꢪꢵꢥꢮꢵꢁ ꢱ꣄ꢮꢡꢥ꣄ꢡ꣄ꢬꢵꢁ ꢱꢪꢸꢡ꣄ꢦꢥ꣄ꢥꢵꢁ ꢮꢬ꣄ꢡꢥ꣄ꢡꢿ ꢂꢦꢶ ꢗ, ꢔꣃꢬꢮꢣꢺꢯꢵ ꢂꢤꢶꢒꢵꢬꢣꢺꢯꢵ ꢗ ꢱꢪꢵꢥꢵꢁ ꢍꢮ ꢮꢬ꣄ꢡꢥ꣄ꢡꢿ꣎ ꢍꢡꢿ ꢱꢬ꣄ꢮꢿ ꢗꢿꢡꢥꢵꢡꢬ꣄ꢒꢯꢒ꣄ꢡꢶꢩ꣄ꢫꢵꢀ ꢱꢸꢱꢪ꣄ꢦꢥ꣄ꢥꢵꢁ ꢱꢥ꣄ꢡꢶ꣎ ꢂꢦꢶ ꢗ, ꢱꢬ꣄ꢮꢿఽꢦꢶ ꢨꢥ꣄ꢤꢸꢡ꣄ꢮꢩꢵꢮꢥꢫꢵ ꢦꢬꢱ꣄ꢦꢬꢀ ꢮ꣄ꢫꢮꢲꢬꢥ꣄ꢡꢸ꣎\nꢂꢱ꣄ꢫꢵꢀ ꢂꢩꢶꢕꣂꢰꢠꢵꢫꢵꢀ ꢥꢶꢬ꣄ꢣꢶꢰ꣄ꢜꢵꢁ ꢱꢬ꣄ꢮꢿఽꢦꢶ ꢂꢤꢶꢒꢵꢬꢵꢁ ꢱꢬ꣄ꢮꢵꢠ꣄ꢫꢦꢶ ꢗ ꢱ꣄ꢮꢵꢡꢥ꣄ꢡ꣄ꢬ꣄ꢫꢵꢠꢶ, ꢮꢶꢥꣀꢮ ꢙꢵꢡꢶꢮꢬ꣄ꢠꢭꢶꢀꢔꢩꢵꢰꢵꢤꢬ꣄ꢪꢬꢵꢙꢥꢷꢡꢶꢒꢡꢣꢶꢡꢬꢪꢥ꣄ꢡꢮ꣄ꢫꢵꢣꢶꢩꢿꢣꢪ꣄, ꢬꢵꢰ꣄ꢜ꣄ꢬꢶꢫꢀ ꢱꢵꢪꢵꢙꢶꢒꢵꢤꢵꢬꢀ ꢱꢪ꣄ꢦꢙ꣄ꢙꢥ꣄ꢪꢡꢣꢶꢡꢬ ꢱ꣄ꢡꢬꢛ꣄ꢗ ꢂꢮꢶꢔꢠꢫ꣄ꢫ, ꢂꢤꢶꢔꢥ꣄ꢡꢸꢀ ꢱꢬ꣄ꢮꣂఽꢦꢶ ꢙꢥꢁ ꢦ꣄ꢬꢩꢮꢡꢶ꣎\nꢍꢡꢣꢡꢶꢬꢶꢒ꣄ꢡꢪ꣄, ꢒꢱ꣄ꢫꢵꢯ꣄ꢗꢶꢣꢦꢶ ꢦ꣄ꢬꢩꢸꢱꢡ꣄ꢡꢵꢫꢵꢁ ꢥꢶꢫꢪꢥꢵꢥ꣄ꢡꢬ꣄ꢔꢡꢪ꣄, ꢱ꣄ꢮꢵꢤꢷꢥꢱ꣄ꢫ ꢃꢡ꣄ꢪꢦ꣄ꢬꢯꢵꢱꢥꢿꢡꢬꢡꢥ꣄ꢡ꣄ꢬꢱ꣄ꢫ, ꢥ꣄ꢫꢵꢱꢶꢡꢥ꣄ꢡ꣄ꢬꢱ꣄ꢫ ꢮꢵ ꢮꢵꢱ꣄ꢡꢮ꣄ꢫꢱ꣄ꢫ ꢦ꣄ꢬꢣꢿꢯꢱ꣄ꢫ ꢣꢿꢯꢱ꣄ꢫ ꢮꢵ ꢬꢵꢙꢥꢷꢡꢶꢒꢱꢷꢪꢵꢥꢶꢨꢥ꣄ꢤꢥꢵꢥ꣄ꢡꢵꢬꢵꢰ꣄ꢜ꣄ꢬꢶꢒꢱ꣄ꢡꢬꢵꢤꢵꢬꢿꢠ ꢥ ꢒꣂఽꢦꢶ ꢩꢿꢣꣂ ꢮꢶꢤꢵꢱ꣄ꢫꢡꢿ꣎\nꢱꢬ꣄ꢮꣂఽꢦꢶ ꢙꢥꢁ ꢙꢷꢮꢥꢱ꣄ꢮꢵꢡꢥ꣄ꢡ꣄ꢬ꣄ꢫꢱꢸꢬꢒ꣄‍ꢰꢵꢤꢶꢒꢵꢬꢀ ꢱꢀꢤꢡ꣄ꢡꢿ꣎\nꢥ ꢒꢪꢦꢶ ꢙꢥꢀ ꢣꢵꢱꢡ꣄ꢮꢿꢥ ꢦꢬꢵꢤꢷꢥꢡ꣄ꢮꢿꢥ ꢮꢵ ꢤꢵꢬꢫꢶꢡꢸꢀ ꢂꢥꢸꢙ꣄ꢛꢵꢱ꣄ꢫꢡꢿ꣎ ꢂꢦꢶ ꢗ ꢣꢵꢱꢮ꣄ꢫꢵꢦꢵꢬꢁ ꢦꢹꢬ꣄ꢠꢬꢹꢦꢿꢠ ꢦ꣄ꢬꢡꢶꢰꢶꢣ꣄ꢤꢁ ꢱ꣄ꢢꢵꢱ꣄ꢫꢡꢶ꣎\nꢥ ꢒꢪꢦꢶ ꢙꢥꢀ ꢮꢶꢬꢸꢤ꣄ꢫ ꢂꢮꢪꢵꢥꢥꢵꢡ꣄ꢪꢒꢀ ꢮ꣄ꢫꢮꢲꢵꢬꢀ ꢣꢠ꣄ꢞꢀ ꢮꢵ ꢒ꣄ꢬꢹꢬꢀ ꢂꢪꢵꢥꢮꢷꢫꢀ ꢦ꣄ꢬꢡꣂꢣꢥꢀ ꢮꢵ ꢦ꣄ꢬꢮꢬ꣄ꢡꢫꢶꢡꢸꢀ ꢂꢥꢸꢙ꣄ꢛꢵꢱ꣄ꢫꢡꢿ꣎"
}
historical: true
