id: "sa_Sora"
language: "sa"
script: "Sora"
name: "Sanskrit, Sora Sompeng"
region: "IN"
sample_text {
  masthead_full: "𑃐𑃝𑃚𑃣"
  masthead_partial: "𑃖𑃢"
  styles: "𑃜𑃑𑃝 𑃠𑃕𑃑𑃤 𑃐𑃠𑃢𑃙𑃑𑃤𑃙𑃜𑃢𑃜𑃐𑃚𑃢𑃑𑃙𑃑𑃝𑃜𑃢𑃙𑃨𑃢𑃖 𑃢𑃔𑃨𑃠𑃢𑃝𑃞"
  tester: "𑃐𑃝𑃚𑃣 𑃖𑃢𑃙𑃚𑃢𑃞 𑃐𑃚𑃑𑃙𑃑𑃝𑃢𑃞 𑃐𑃖𑃥𑃑𑃛𑃙𑃙𑃢𑃞 𑃚𑃝𑃑𑃙𑃑𑃣 𑃦𑃨𑃛𑃤 𑃓, 𑃕𑃦𑃥𑃝𑃚𑃔𑃨𑃝𑃤𑃐𑃠𑃢 𑃦𑃨𑃔𑃨𑃠𑃤𑃟𑃢𑃝𑃔𑃨𑃝𑃤𑃐𑃠𑃢"
  poster_sm: "𑃣𑃑𑃔𑃨𑃑𑃤𑃝𑃤𑃟𑃑𑃖,"
  poster_md: "𑃐𑃝𑃚𑃦\'𑃛𑃤 𑃠𑃙𑃞"
  poster_lg: "𑃐𑃝𑃚𑃣"
  specimen_48: "𑃙 𑃟𑃖𑃛𑃤 𑃠𑃙𑃖 𑃔𑃨𑃢𑃐𑃑𑃚𑃣𑃙 𑃛𑃝𑃢𑃔𑃨𑃠𑃤𑃙𑃑𑃚𑃣𑃙 𑃚𑃢 𑃔𑃨𑃠𑃢𑃝𑃜𑃤𑃑𑃥𑃖 𑃦𑃨𑃙𑃥𑃠𑃡𑃢𑃐𑃜𑃑𑃣. 𑃦𑃨𑃛𑃤"
  specimen_36: "𑃙 𑃟𑃖𑃛𑃤 𑃠𑃙𑃖 𑃚𑃤𑃝𑃥𑃔𑃨𑃠𑃜 𑃦𑃨𑃚𑃖𑃢𑃙𑃙𑃢𑃑𑃖𑃟𑃖 𑃚𑃜𑃚𑃞𑃢𑃝𑃖 𑃔𑃨𑃙𑃨𑃔𑃖 𑃚𑃢 𑃟𑃝𑃥𑃝𑃖 𑃦𑃨𑃖𑃢𑃙𑃚𑃤𑃜𑃖 𑃛𑃝𑃑𑃦𑃔𑃨𑃙𑃖 𑃚𑃢 𑃛𑃝𑃚𑃝𑃑𑃜𑃤𑃑𑃥𑃖 𑃦𑃨𑃙𑃥𑃠𑃡𑃢𑃐𑃜𑃑𑃣."
  specimen_32: "𑃚𑃤𑃔𑃨𑃠𑃤𑃙𑃢 𑃐𑃖𑃚𑃤𑃔𑃨𑃠𑃢𑃙𑃣𑃙 𑃚𑃢 𑃛𑃝𑃔𑃨𑃑𑃑𑃢𑃙𑃢𑃖 𑃖𑃦𑃥𑃘𑃤𑃟𑃢𑃔𑃨𑃠𑃤𑃟𑃢𑃝𑃢𑃙𑃨𑃢𑃖𑃥𑃘𑃘𑃖𑃕𑃠𑃙𑃟𑃢𑃝𑃜𑃢𑃙𑃨𑃢𑃖 𑃟𑃝𑃤𑃑𑃣, 𑃜𑃦𑃕𑃜𑃧𑃞 𑃝𑃢𑃐𑃨𑃑𑃨𑃝𑃤𑃜𑃙𑃜𑃢𑃜𑃛𑃤𑃑𑃨𑃠𑃧𑃞 𑃐𑃖𑃐𑃑𑃥𑃑𑃢𑃙𑃢𑃖 𑃛𑃝𑃒𑃠𑃢𑃚𑃤𑃙𑃢𑃖 𑃐𑃖𑃥𑃛𑃢𑃜𑃢𑃙𑃢𑃖 𑃛𑃝𑃜𑃦𑃕𑃢𑃝𑃞𑃦 𑃞𑃤 𑃐𑃝𑃚𑃦 𑃠𑃙𑃦\'𑃐𑃑𑃤."
  specimen_21: "𑃙 𑃟𑃦\'𑃛𑃤 𑃠𑃙𑃞 𑃐𑃚𑃣𑃓𑃓𑃠𑃜𑃢 𑃙𑃤𑃕𑃝𑃞𑃤𑃑𑃥𑃖, 𑃔𑃨𑃠𑃝𑃑𑃥𑃖, 𑃙𑃤𑃐𑃨𑃟𑃢𑃐𑃜𑃤𑃑𑃥𑃖 𑃚𑃢 𑃦𑃨𑃙𑃥𑃠𑃡𑃢𑃐𑃜𑃑𑃣.\n𑃐𑃝𑃚𑃦\'𑃛𑃤 𑃠𑃙𑃞, 𑃐𑃚𑃖 𑃚𑃤𑃝𑃥𑃔𑃨𑃠𑃜 𑃛𑃝𑃚𑃝𑃑𑃑𑃤𑃑𑃐𑃜 𑃟𑃐𑃜𑃢𑃛𑃤 𑃢𑃛𑃝𑃢𑃔𑃨𑃠𑃤𑃟𑃢𑃟𑃐𑃨𑃣𑃛𑃐𑃜, 𑃐𑃚𑃤𑃜𑃢𑃔𑃨𑃠𑃤𑃟𑃢𑃝𑃢𑃙𑃨𑃢𑃖 𑃔𑃨𑃢𑃜𑃤𑃑𑃚𑃢𑃙𑃢𑃖 𑃓, 𑃚𑃤𑃙𑃤𑃝𑃔𑃨𑃠𑃢𑃝𑃙𑃨𑃐𑃜 𑃓 𑃟𑃝𑃤𑃑𑃣, 𑃐𑃚𑃢𑃔𑃨𑃠𑃤𑃙𑃣𑃙 𑃙𑃤𑃐𑃨𑃛𑃟𑃐𑃨𑃣𑃙𑃨 𑃓 𑃙𑃜𑃢𑃜𑃛𑃤𑃑𑃨𑃠𑃣𑃙 𑃚𑃤𑃔𑃨𑃠𑃤𑃜𑃖𑃢𑃙𑃐𑃜 𑃐𑃖𑃥𑃓𑃤𑃑𑃐𑃜 𑃐𑃢𑃝𑃚𑃠𑃙𑃤𑃟𑃐𑃜 𑃐𑃠𑃝𑃚𑃙𑃨𑃐𑃜 𑃓 𑃟𑃝𑃤𑃑𑃣 𑃐𑃝𑃚𑃦\'𑃛𑃤 𑃠𑃙𑃞 𑃛𑃥𑃝𑃙𑃨𑃢𑃖 𑃐𑃖𑃢𑃙𑃑𑃢𑃖 𑃔𑃨𑃠𑃢𑃝𑃜𑃑𑃤."
  specimen_16: "𑃙 𑃟𑃐𑃜𑃢𑃛𑃤 𑃚𑃜𑃟𑃑𑃤𑃕𑃑𑃣 𑃛𑃢𑃝𑃤𑃚𑃢𑃝𑃤𑃟𑃣 𑃓 𑃠𑃤𑃚𑃙𑃣, 𑃕𑃝𑃤𑃞𑃣, 𑃛𑃑𑃝𑃚𑃜𑃚𑃞𑃢𑃝𑃣 𑃓 𑃐𑃚𑃣𑃓𑃓𑃠𑃜𑃢 𑃞𑃐𑃑𑃟𑃐𑃨𑃣𑃛𑃦\'𑃙𑃥𑃠𑃡𑃢𑃐𑃜𑃑𑃣, 𑃙 𑃚𑃢 𑃟𑃐𑃜𑃢𑃛𑃤 𑃟𑃠𑃜𑃢𑃑𑃤𑃖 𑃐𑃖𑃖𑃢𑃙𑃖 𑃚𑃢𑃟𑃝𑃢𑃙𑃑𑃥𑃖 𑃟𑃦\'𑃛𑃤 𑃐𑃠𑃟𑃐𑃨𑃜𑃑𑃤. 𑃣𑃑𑃢𑃞𑃟𑃞𑃐𑃑𑃟𑃐𑃨𑃣𑃛𑃢𑃟𑃝𑃖𑃙𑃨𑃢𑃙𑃤 𑃚𑃤𑃝𑃥𑃔𑃨𑃠𑃜 𑃛𑃝𑃑𑃜𑃣𑃟𑃖𑃛𑃤𑃠𑃙𑃞 𑃚𑃤𑃔𑃨𑃠𑃤𑃐𑃖𑃝𑃟𑃐𑃨𑃙𑃨𑃖 𑃐𑃖𑃔𑃨𑃠𑃑𑃑𑃣.\n𑃛𑃝𑃑𑃜𑃣𑃟𑃖𑃛𑃤 𑃚𑃤𑃓𑃢𑃝𑃢𑃙𑃨𑃢𑃖 𑃓𑃣𑃑𑃙𑃢𑃜𑃢𑃞 𑃔𑃨𑃠𑃝𑃖𑃐𑃜 𑃓𑃐𑃚𑃢𑃑𑃙𑃑𑃝𑃜𑃢𑃔𑃨𑃠𑃤𑃟𑃢𑃝𑃖 𑃐𑃖𑃔𑃨𑃠𑃑𑃑𑃣. 𑃦𑃨𑃐𑃖𑃤𑃙 𑃦𑃨𑃔𑃨𑃠𑃤𑃟𑃢𑃝𑃣, 𑃐𑃚𑃤𑃜𑃖 𑃔𑃨𑃠𑃝𑃖𑃖 𑃚𑃤𑃐𑃠𑃚𑃢𑃐𑃖 𑃚𑃢 𑃐𑃠𑃤𑃟𑃐𑃨𑃜𑃤𑃑𑃥𑃖 𑃦𑃨𑃒𑃠𑃜𑃐𑃑𑃥𑃖 𑃦𑃨𑃝𑃓𑃤𑃑𑃥𑃖 𑃛𑃝𑃤𑃛𑃢𑃘𑃜𑃤𑃑𑃥𑃖 𑃚𑃢, 𑃚𑃧𑃜𑃟𑃑𑃤𑃟𑃣 𑃐𑃢𑃖𑃢𑃠𑃤𑃟𑃣 𑃓 𑃠𑃤𑃚𑃙𑃣, 𑃦𑃨𑃙𑃜𑃧𑃐𑃠𑃓 𑃐𑃞 𑃐𑃢𑃖𑃥𑃔𑃨𑃢𑃜𑃤𑃟𑃠𑃤𑃚𑃙𑃣 𑃣𑃟𑃢𑃟𑃤𑃙𑃢 𑃚𑃢 𑃐𑃚𑃤𑃜𑃖 𑃔𑃨𑃠𑃝𑃖𑃖 𑃚𑃤𑃐𑃠𑃚𑃢𑃐𑃖𑃐𑃚𑃢𑃑𑃙𑃑𑃝𑃜𑃖 𑃓 𑃛𑃝𑃤𑃚𑃝𑃑𑃜𑃤𑃑𑃥𑃖𑃛𑃤 𑃛𑃝𑃑𑃜𑃣𑃟𑃖 𑃠𑃙𑃞 𑃐𑃚𑃢𑃑𑃙𑃑𑃝𑃜𑃖 𑃔𑃨𑃠𑃢𑃝𑃜𑃑𑃤.\n𑃛𑃝𑃑𑃜𑃣𑃟𑃖𑃛𑃤 𑃖𑃙𑃑𑃚𑃜𑃢𑃒𑃠𑃤𑃚𑃜𑃟𑃑𑃜𑃦𑃞 𑃦𑃨𑃔𑃨𑃠𑃤𑃟𑃢𑃝𑃖 𑃐𑃖𑃔𑃨𑃠𑃑𑃑𑃣. 𑃐𑃤𑃖𑃢𑃚𑃜𑃚𑃔𑃨𑃠𑃢𑃙𑃖 𑃦𑃨𑃚𑃤𑃕𑃙𑃨𑃜𑃜, 𑃟𑃣𑃙𑃢𑃛𑃤 𑃐𑃖𑃓𑃢𑃝𑃖𑃢𑃔𑃨𑃠𑃜𑃖𑃣𑃙 𑃚𑃤𑃓𑃢𑃝𑃢𑃙𑃨𑃢𑃖 𑃐𑃥𑃓𑃙𑃢𑃙𑃢𑃖 𑃓 𑃢𑃔𑃨𑃢𑃙𑃛𑃝𑃔𑃨𑃢𑃙𑃢𑃝𑃑𑃠𑃖 𑃚𑃤𑃙𑃧𑃚 𑃞𑃐𑃑𑃟𑃐𑃨𑃣𑃛𑃖 𑃟𑃤𑃐𑃠𑃓𑃔𑃨𑃛𑃤 𑃠𑃙𑃞, 𑃐𑃚𑃤𑃜𑃖𑃙𑃑𑃚𑃜𑃐𑃖𑃕𑃠𑃢𑃝𑃙𑃨𑃢𑃝𑃑𑃠𑃖 𑃦𑃨𑃔𑃨𑃠𑃤𑃟𑃢𑃝𑃣\'𑃐𑃖𑃤𑃙 𑃦𑃨𑃝𑃞𑃤𑃐𑃨𑃜𑃑𑃣."
}
historical: true
