id: "sa_Soyo"
language: "sa"
script: "Soyo"
name: "Sanskrit, Soyombo"
region: "IN"
sample_text {
  masthead_full: "𑪁𑩖𑩥𑪖"
  masthead_partial: "𑪁𑩖"
  styles: "𑩻𑩫𑪙𑩼 𑩣𑩞𑩫𑩑 𑩿𑩛𑩯𑪙𑩫𑩑𑩯𑪙𑩻𑩛𑩻𑪁𑪙𑩾𑩛𑩫𑩯𑪙𑩫𑪙𑩼𑪙𑩻𑩛𑩪𑩛𑪖 𑩐𑩛𑩮𑩛𑩼𑪗"
  tester: "𑪁𑩼𑪙𑩾𑩔 𑩴𑩛𑩯𑩾𑩛𑪗 𑪁𑪙𑩾𑩫𑩯𑪙𑩫𑪙𑩼𑩛𑪗 𑪁𑩴𑩒𑩫𑪙𑩰𑩯𑪘𑩛𑪗 𑩾𑩼𑪙𑩫𑩯𑪙𑩫𑩔 𑩐𑩰𑩑 𑩡, 𑩞𑩘𑩼𑩾𑩭𑩙𑩿𑩛"
  poster_sm: "𑩐𑪁𑪙𑩻𑩛𑪖 𑩐𑩳𑩑"
  poster_md: "𑩐𑩔𑩫𑩭𑩫𑩑𑩼𑩑"
  poster_lg: "𑪁𑩼𑪙𑩾𑩔"
  specimen_48: "𑩯 𑩜𑩴𑩰𑩑 𑩣𑩯𑪖 𑩭𑩛𑪁𑩫𑪙𑩾𑩔𑩯 𑩰𑩼𑩛𑩮𑩑𑩛𑩯𑩫𑪙𑩾𑩔𑩯 𑩾𑩛 𑩮𑩛𑩼𑩻𑩑𑩫𑩒𑪖 𑩐𑩯𑩒𑩣𑪙𑩥𑩛𑪁𑪙𑩻𑩫𑩔𑪛 𑩐𑩰𑩑"
  specimen_36: "𑩯 𑩜𑩴𑩰𑩑 𑩣𑩯𑪖 𑩾𑩑𑩼𑩒𑩮𑪙𑩻 𑩐𑩾𑩴𑩛𑩯𑩯𑩛𑩫𑪙𑩴𑩜𑪖 𑩾𑪙𑩻𑩾𑪂𑩛𑩼𑪖 𑩭𑩪𑪙𑩨𑪖 𑩾𑩛 𑩜𑪙𑩼𑩒𑩛𑩼𑪖 𑩐𑩴𑩛𑩯𑩾𑩑𑩛𑩻𑪖 𑩰𑪙𑩼𑩫𑩖𑩭𑩯𑪖 𑩾𑩛 𑩰𑪙𑩼𑩾𑩼𑪙𑩫𑩻𑩑𑩫𑩒𑪖 𑩐𑩯𑩒𑩣𑪙𑩥𑩛𑪁𑪙𑩻𑩫𑩔𑪛"
  specimen_32: "𑩾𑩑𑩮𑩑𑩯𑩛 𑪁𑪖𑩾𑩑𑩮𑩛𑩯𑩔𑩯 𑩾𑩛 𑩰𑪙𑩼𑩭𑩫𑪘𑩛𑩯𑩛𑪖 𑩴𑩘𑩽𑩑𑩜𑩛𑩮𑩑𑩜𑩛𑩼𑩛𑩪𑩛𑩴𑩒𑩽𑪘𑪖𑩟𑩯𑩜𑩛𑩼𑪙𑩻𑩛𑩪𑩛𑪖 𑩜𑩙𑩫𑩔, 𑩻𑩖𑩞𑪙𑩻𑩗𑪗 𑩼𑩛𑪀𑪙𑩦𑪙𑩼𑩑𑩻𑩯𑪙𑩻𑩛𑩻𑩰𑩑𑩛𑩧𑩗𑪗 𑪁𑪖𑪁𑪙𑩫𑩒𑩫𑩛𑩯𑩛𑪖 𑩰𑪙𑩼𑩳𑩛𑩾𑩑𑩯𑩛𑪖 𑪁𑩴𑩒𑩰𑩛𑩻𑩛𑩯𑩛𑪖 𑩰𑪙𑩼𑩻𑩖𑩞𑩛𑩼𑪙𑪂𑩖 𑪂𑩑 𑪁𑩼𑪙𑩾𑩖 𑩣𑩯𑩖𑪁𑪙𑩫𑩑𑪛"
  specimen_21: "𑩯 𑩜𑩖𑩰𑩑 𑩣𑩯𑪗 𑪁𑪙𑩾𑩔𑩡𑪙𑩢𑩻𑩛 𑩯𑩑𑩞𑪙𑩼𑪂𑩑𑩛𑩫𑩒𑪖, 𑩮𑩼𑪙𑩫𑩒𑪖, 𑩯𑩑𑪀𑪙𑩜𑩛𑪁𑩻𑩑𑩫𑩒𑪖 𑩾𑩛 𑩐𑩯𑩒𑩣𑪙𑩥𑩛𑪁𑪙𑩻𑩫𑩔𑪛\n𑪁𑩼𑪙𑩾𑩖𑩰𑩑 𑩣𑩯𑪗, 𑪁𑪙𑩾𑪖 𑩾𑩑𑩼𑩒𑩮𑪙𑩻 𑩰𑪙𑩼𑩾𑩼𑪙𑩫𑪙𑩫𑩑𑩫𑪁𑪙𑩻 𑩜𑪁𑪙𑩻𑩛𑩰𑩑 𑩐𑩛𑩰𑩼𑩛𑩮𑩑𑩜𑩛𑪃𑩔𑩰𑪁𑪙𑩻, 𑪁𑪙𑩾𑩑𑩛𑩻𑩛𑩮𑩑𑩜𑩛𑩼𑩛𑩪𑩛𑪖 𑩭𑩛𑩻𑩑𑩫𑪙𑩾𑩛𑩯𑩛𑪖 𑩡, 𑩾𑩑𑩯𑩑𑩼𑪙𑩮𑩛𑩼𑩪𑪁𑪙𑩻 𑩡 𑩜𑩙𑩫𑩔, 𑪁𑪙𑩾𑩛𑩮𑩑𑩛𑩯𑩔𑩯 𑩯𑩑𑪀𑪙𑩰𑪃𑩔𑩪 𑩡 𑩯𑪙𑩻𑩛𑩻𑩰𑩑𑩛𑩧𑩔𑩯 𑩾𑩑𑩮𑩑𑩛𑩻𑩴𑩛𑩯𑪁𑪙𑩻 𑪁𑩴𑩒𑩡𑩑𑩫𑪁𑪙𑩻 𑪁𑩛𑩼𑪙𑩾𑩣𑩯𑩑𑩜𑪁𑪙𑩻 𑪈𑩼𑩾𑩪𑪁𑪙𑩻 𑩡 𑩜𑩙𑩫𑩔 𑪁𑩼𑪙𑩾𑩖𑩰𑩑 𑩣𑩯𑪗 𑩰𑩒𑩛𑩼𑪙𑩪𑩛𑪖 𑪁𑩴𑩛𑩯𑩫𑩛𑪖 𑩮𑩛𑩼𑩻𑩫𑩑𑪛"
  specimen_16: "𑩯 𑩜𑪁𑪙𑩻𑩛𑩰𑩑 𑩾𑪙𑩻𑩜𑪙𑩫𑩑𑩞𑩫𑩔 𑩰𑩛𑩼𑩑𑩾𑩛𑩼𑩑𑩜𑩔 𑩡 𑩣𑩑𑩛𑩾𑩯𑩔, 𑩞𑩙𑪂𑩔, 𑩰𑩫𑪙𑩼𑩾𑪙𑩻𑩾𑪂𑩛𑩼𑩔 𑩡 𑪁𑪙𑩾𑩔𑩡𑪙𑩢𑩻𑩛 𑪂𑪁𑪙𑩫𑪃𑩔𑩰𑩖𑩯𑩒𑩣𑪙𑩥𑩛𑪁𑪙𑩻𑩫𑩔, 𑩯 𑩾𑩛 𑩜𑪁𑪙𑩻𑩛𑩰𑩑 𑩝𑪙𑩻𑩛𑩫𑩑𑪖 𑪁𑩴𑪘𑩛𑩯𑪖 𑩾𑩛𑩜𑪙𑩼𑩛𑩯𑪙𑩫𑩒𑪖 𑩜𑩖𑩰𑩑 𑩿𑪃𑪙𑩻𑩫𑩑𑪛 𑩐𑩔𑩫𑩛𑪂𑩜𑪂𑪁𑪙𑩫𑪃𑩔𑩰𑩛𑩜𑪙𑩼𑩴𑩪𑩛𑩯𑩑 𑩾𑩑𑩼𑩒𑩮𑪙𑩻 𑩰𑪙𑩼𑩫𑪙𑩻𑩔𑩜𑩴𑩰𑩑𑩣𑩯𑪗 𑩾𑩑𑩮𑩑𑪁𑪖𑩼𑪃𑩪𑪖 𑪁𑪖𑩮𑩫𑪘𑩔𑪛\n𑩰𑪙𑩼𑩫𑪙𑩻𑩔𑩜𑩴𑩰𑩑 𑩾𑩑𑩡𑩛𑩼𑩛𑩪𑩛𑪖 𑩡𑩔𑩫𑩯𑩛𑩻𑩛𑪗 𑩮𑩼𑪙𑩴𑪁𑪙𑩻 𑩡𑪁𑪙𑩾𑩛𑩫𑩯𑪙𑩫𑪙𑩼𑪙𑩻𑩛𑩮𑩑𑩜𑩛𑩼𑪖 𑪁𑪖𑩮𑩫𑪘𑩔𑪛 𑩐𑪁𑪙𑩴𑩑𑩯 𑩐𑩮𑩑𑩜𑩛𑩼𑩔, 𑪁𑪙𑩾𑩑𑩛𑩻𑪖 𑩮𑩼𑪙𑩴𑪖 𑩾𑩑𑪈𑩾𑩛𑪁𑪖 𑩾𑩛 𑩿𑩑𑪃𑩻𑩑𑩫𑩒𑪖 𑩐𑩳𑪙𑩻𑪁𑪙𑩫𑩒𑪖 𑩐𑩼𑪙𑩡𑩑𑩫𑩒𑪖 𑩰𑩼𑩑𑩰𑩛𑩽𑩻𑩑𑩫𑩒𑪖 𑩾𑩛, 𑩾𑩗𑩻𑩜𑪙𑩫𑩑𑩜𑩔 𑪁𑩛𑩴𑩛𑩣𑩑𑩜𑩔 𑩡 𑩣𑩑𑩛𑩾𑩯𑩔, 𑩐𑩯𑪙𑩻𑩗𑪈𑩡 𑪁𑪂 𑪁𑩛𑩴𑩒𑩭𑩛𑩻𑩑𑩜𑩣𑩑𑩛𑩾𑩯𑩔 𑩐𑩔𑩜𑩛𑩜𑩑𑩯𑩛 𑩾𑩛 𑪁𑪙𑩾𑩑𑩛𑩻𑪖 𑩮𑩼𑪙𑩴𑪖 𑩾𑩑𑪈𑩾𑩛𑪁𑪖𑪁𑪙𑩾𑩛𑩫𑩯𑪙𑩫𑪙𑩼𑪙𑩻𑪖 𑩡 𑩰𑩼𑩑𑩾𑩼𑪙𑩫𑩻𑩑𑩫𑩒𑩴𑩰𑩑 𑩰𑪙𑩼𑩫𑪙𑩻𑩔𑩜𑪖 𑩣𑩯𑪗 𑪁𑪙𑩾𑩛𑩫𑩯𑪙𑩫𑪙𑩼𑪙𑩻𑪖 𑩮𑩛𑩼𑩻𑩫𑩑𑪛\n𑩰𑪙𑩼𑩫𑪙𑩻𑩔𑩜𑩴𑩰𑩑 𑩴𑩯𑪙𑩫𑩾𑪙𑩻𑩛𑩳𑩑𑩾𑪙𑩻𑩜𑪙𑩫𑪙𑩻𑩖𑪗 𑩐𑩮𑩑𑩜𑩛𑩼𑪖 𑪁𑪖𑩮𑩫𑪘𑩔𑪛 𑪁𑩑𑩛𑩴𑩛𑩾𑪙𑩻𑩾𑩮𑩛𑩯𑪖 𑩐𑩾𑩑𑩞𑩪𑩻𑪘, 𑩜𑩔𑩯𑩛𑩰𑩑 𑪁𑪖𑩡𑩛𑩼𑩴𑩛𑩮𑪙𑩻𑩴𑩔𑩯 𑩾𑩑𑩡𑩛𑩼𑩛𑩪𑩛𑪖 𑪁𑩒𑩛𑩡𑩯𑩛𑩯𑩛𑪖 𑩡 𑩐𑩛𑩭𑩛𑩯𑩰𑪙𑩼𑩭𑩛𑩯𑩛𑩼𑪙𑩬𑪖 𑩾𑩑𑩯𑩗𑩾 𑪂𑪁𑪙𑩫𑪃𑩔𑩰𑪖 𑩜𑩑𑪈𑩡𑩭𑩰𑩑 𑩣𑩯𑪗, 𑪁𑪙𑩾𑩑𑩛𑩻𑩴𑩯𑪙𑩫𑩾𑪙𑩻𑪁𑪖𑩟𑩛𑩼𑩪𑩛𑩼𑪙𑩬𑪖 𑩐𑩮𑩑𑩜𑩛𑩼𑩔𑪁𑪙𑩴𑩑𑩯 𑩐𑩼𑪙𑪂𑩑𑪀𑪙𑩻𑩫𑩔𑪛"
}
historical: true
