id: "sa_Sidd"
language: "sa"
script: "Sidd"
name: "Sanskrit, Siddham"
population: 0
region: "IN"
sample_text {
  masthead_full: "𑖭𑖨𑖪𑖦"
  masthead_partial: "𑖡𑖝"
  styles: "𑖧𑖝𑖿𑖨 𑖕𑖐𑖝𑖰 𑖫𑖯𑖡𑖿𑖝𑖰𑖡𑖿𑖧𑖯𑖧𑖭𑖿𑖪𑖯𑖝𑖡𑖿𑖝𑖿𑖨𑖿𑖧𑖯𑖜𑖯𑖽 𑖁𑖠𑖯𑖨𑖾 𑖦𑖯𑖡𑖪𑖢𑖨𑖰𑖪𑖯𑖨𑖭𑖿𑖧 𑖭𑖨𑖿𑖪𑖸𑖬𑖯𑖦𑖢𑖰"
  tester: "𑖭𑖨𑖿𑖪𑖸 𑖦𑖯𑖡𑖪𑖯𑖾 𑖭𑖿𑖪𑖝𑖡𑖿𑖝𑖿𑖨𑖯𑖾 𑖭𑖦𑖲𑖝𑖿𑖢𑖡𑖿𑖡𑖯𑖾 𑖪𑖨𑖿𑖝𑖡𑖿𑖝𑖸 𑖀𑖢𑖰 𑖓, 𑖐𑖻𑖨𑖪𑖟𑖴𑖫𑖯 𑖀𑖠𑖰𑖎𑖯𑖨𑖟𑖴𑖫𑖯 𑖓 𑖭𑖦𑖯𑖡𑖯𑖾 𑖊𑖪 𑖪𑖨𑖿𑖝𑖡𑖿𑖝𑖸𑗂"
  poster_sm: "𑖀𑖭𑖿𑖧𑖯𑖽 𑖀𑖥𑖰𑖑𑖺𑖬𑖜𑖯𑖧𑖯𑖽"
  poster_md: "𑖊𑖝𑖟𑖝𑖰𑖨𑖰𑖎𑖿𑖝𑖦𑖿,"
  poster_lg: "𑖭𑖨𑖿𑖪𑖸"
  specimen_48: "𑖡 𑖎𑖦𑖢𑖰 𑖕𑖡𑖽 𑖟𑖯𑖭𑖝𑖿𑖪𑖸𑖡 𑖢𑖨𑖯𑖠𑖱𑖡𑖝𑖿𑖪𑖸𑖡 𑖪𑖯 𑖠𑖯𑖨𑖧𑖰𑖝𑖲𑖽 𑖀𑖡𑖲𑖕𑖿𑖗𑖯𑖭𑖿𑖧𑖝𑖸𑗂 𑖀𑖢𑖰 𑖓 𑖟𑖯𑖭𑖪𑖿𑖧𑖯𑖢𑖯𑖨𑖾 𑖢𑖳𑖨𑖿𑖜𑖨𑖳𑖢𑖸𑖜 𑖢𑖿𑖨𑖝𑖰𑖬𑖰𑖟𑖿𑖠𑖾"
  specimen_36: "𑖭𑖨𑖿𑖪𑖺𑖢𑖰 𑖕𑖡𑖾 𑖕𑖱𑖪𑖡𑖭𑖿𑖪𑖯𑖝𑖡𑖿𑖝𑖿𑖨𑖿𑖧𑖭𑖲𑖨𑖎𑖿𑖬𑖯𑖠𑖰𑖎𑖯𑖨𑖽 𑖭𑖽𑖠𑖝𑖿𑖝𑖸𑗂\n𑖡 𑖎𑖦𑖢𑖰 𑖕𑖡𑖽 𑖟𑖯𑖭𑖝𑖿𑖪𑖸𑖡 𑖢𑖨𑖯𑖠𑖱𑖡𑖝𑖿𑖪𑖸𑖡 𑖪𑖯 𑖠𑖯𑖨𑖧𑖰𑖝𑖲𑖽 𑖀𑖡𑖲𑖕𑖿𑖗𑖯𑖭𑖿𑖧𑖝𑖸𑗂 𑖀𑖢𑖰 𑖓 𑖟𑖯𑖭𑖪𑖿𑖧𑖯𑖢𑖯𑖨𑖾 𑖢𑖳𑖨𑖿𑖜𑖨𑖳𑖢𑖸𑖜 𑖢𑖿𑖨𑖝𑖰𑖬𑖰𑖟𑖿𑖠𑖾 𑖭𑖿𑖞𑖯𑖭𑖿𑖧𑖝𑖰𑗂"
  specimen_32: "𑖪𑖰𑖠𑖸𑖾 𑖭𑖦𑖎𑖿𑖬𑖽 𑖭𑖨𑖿𑖪𑖸𑖢𑖰 𑖝𑖲𑖩𑖿𑖧𑖯𑖾 𑖭𑖦𑖯𑖡𑖯𑖫𑖿𑖓 𑖪𑖨𑖿𑖝𑖡𑖿𑖝𑖸𑗂 𑖀𑖢𑖰 𑖓 𑖪𑖰𑖡𑖹𑖪 𑖎𑖦𑖢𑖰 𑖥𑖸𑖟𑖽 𑖪𑖰𑖠𑖸𑖾 𑖝𑖲𑖩𑖿𑖧𑖽 𑖭𑖽𑖨𑖎𑖿𑖬𑖜𑖦𑖪𑖯𑖢𑖿𑖝𑖲𑖽 𑖀𑖨𑖿𑖮𑖡𑖿𑖝𑖰𑗂 𑖀𑖭𑖿𑖧𑖯𑖾 𑖀𑖥𑖰𑖑𑖺𑖬𑖜𑖯𑖧𑖯𑖾 𑖄𑖩𑖿𑖩𑖽𑖑𑖡𑖸 𑖎𑖦𑖢𑖰 𑖥𑖸𑖟𑖽, 𑖊𑖝𑖯𑖟𑖴𑖐𑖿𑖥𑖸𑖟𑖽 𑖪𑖯 𑖀𑖥𑖰𑖩𑖎𑖿𑖬𑖿𑖧 𑖎𑖯𑖦𑖢𑖰 𑖓𑖸𑖬𑖿𑖘𑖯𑖽 𑖪𑖰𑖨𑖲𑖠𑖿𑖧 𑖭𑖦𑖯𑖡𑖭𑖽𑖨𑖎𑖿𑖬𑖜𑖯𑖨𑖿𑖮𑖯𑖾 𑖭𑖨𑖿𑖪𑖸𑖢𑖰 𑖪𑖨𑖿𑖝𑖡𑖿𑖝𑖸𑗂"
  specimen_21: "𑖭𑖨𑖿𑖪𑖸 𑖦𑖯𑖡𑖪𑖯𑖾 𑖭𑖿𑖪𑖝𑖡𑖿𑖝𑖿𑖨𑖯𑖾 𑖭𑖦𑖲𑖝𑖿𑖢𑖡𑖿𑖡𑖯𑖾 𑖪𑖨𑖿𑖝𑖡𑖿𑖝𑖸 𑖀𑖢𑖰 𑖓, 𑖐𑖻𑖨𑖪𑖟𑖴𑖫𑖯 𑖀𑖠𑖰𑖎𑖯𑖨𑖟𑖴𑖫𑖯 𑖓 𑖭𑖦𑖯𑖡𑖯𑖾 𑖊𑖪 𑖪𑖨𑖿𑖝𑖡𑖿𑖝𑖸𑗂 𑖊𑖝𑖸 𑖭𑖨𑖿𑖪𑖸 𑖓𑖸𑖝𑖡𑖯𑖝𑖨𑖿𑖎𑖫𑖎𑖿𑖝𑖰𑖥𑖿𑖧𑖯𑖽 𑖭𑖲𑖭𑖦𑖿𑖢𑖡𑖿𑖡𑖯𑖾 𑖭𑖡𑖿𑖝𑖰𑗂 𑖀𑖢𑖰 𑖓, 𑖭𑖨𑖿𑖪𑖸𑖢𑖰 𑖤𑖡𑖿𑖠𑖲𑖝𑖿𑖪𑖥𑖯𑖪𑖡𑖧𑖯 𑖢𑖨𑖭𑖿𑖢𑖨𑖽 𑖪𑖿𑖧𑖪𑖮𑖨𑖡𑖿𑖝𑖲𑗂\n𑖀𑖭𑖿𑖧𑖯𑖽 𑖀𑖥𑖰𑖑𑖺𑖬𑖜𑖯𑖧𑖯𑖽 𑖡𑖰𑖨𑖿𑖟𑖰𑖬𑖿𑖘𑖯𑖾 𑖭𑖨𑖿𑖪𑖸𑖢𑖰 𑖀𑖠𑖰𑖎𑖯𑖨𑖯𑖾 𑖭𑖨𑖿𑖪𑖯𑖜𑖿𑖧𑖢𑖰 𑖓 𑖭𑖿𑖪𑖯𑖝𑖡𑖿𑖝𑖿𑖨𑖿𑖧𑖯𑖜𑖰, 𑖪𑖰𑖡𑖹𑖪 𑖕𑖯𑖝𑖰𑖪𑖨𑖿𑖜𑖩𑖰𑖽𑖐𑖥𑖯𑖬𑖯𑖠𑖨𑖿𑖦𑖨𑖯𑖕𑖡𑖱𑖝𑖰𑖎𑖝𑖟𑖰𑖝𑖨𑖦𑖡𑖿𑖝𑖪𑖿𑖧𑖯𑖟𑖰𑖥𑖸𑖟𑖦𑖿, 𑖨𑖯𑖬𑖿𑖘𑖿𑖨𑖰𑖧𑖽 𑖭𑖯𑖦𑖯𑖕𑖰𑖎𑖯𑖠𑖯𑖨𑖽 𑖭𑖦𑖿𑖢𑖕𑖿𑖕𑖡𑖿𑖦𑖝𑖟𑖰𑖝𑖨 𑖭𑖿𑖝𑖨𑖗𑖿𑖓 𑖀𑖪𑖰𑖐𑖜𑖧𑖿𑖧, 𑖀𑖠𑖰𑖐𑖡𑖿𑖝𑖲𑖽 𑖭𑖨𑖿𑖪𑖺𑖢𑖰 𑖕𑖡𑖾 𑖢𑖿𑖨𑖥𑖪𑖝𑖰𑗂\n𑖊𑖝𑖟𑖝𑖰𑖨𑖰𑖎𑖿𑖝𑖦𑖿, 𑖎𑖭𑖿𑖧𑖯𑖫𑖿𑖓𑖰𑖟𑖢𑖰 𑖢𑖿𑖨𑖥𑖲𑖭𑖝𑖿𑖝𑖯𑖧𑖯𑖾 𑖡𑖰𑖧𑖦𑖡𑖯𑖡𑖿𑖝𑖨𑖿𑖐𑖝𑖦𑖿, 𑖭𑖿𑖪𑖯𑖠𑖱𑖡𑖭𑖿𑖧 𑖁𑖝𑖿𑖦𑖢𑖿𑖨𑖫𑖯𑖭𑖡𑖸𑖝𑖨𑖝𑖡𑖿𑖝𑖿𑖨𑖭𑖿𑖧, 𑖡𑖿𑖧𑖯𑖭𑖰𑖝𑖡𑖿𑖝𑖿𑖨𑖭𑖿𑖧 𑖪𑖯 𑖪𑖯𑖭𑖿𑖝𑖪𑖿𑖧𑖭𑖿𑖧 𑖢𑖿𑖨𑖟𑖸𑖫𑖭𑖿𑖧 𑖟𑖸𑖫𑖭𑖿𑖧 𑖪𑖯 𑖨𑖯𑖕𑖡𑖱𑖝𑖰𑖎𑖭𑖱𑖦𑖯𑖡𑖰𑖤𑖡𑖿𑖠𑖡𑖯𑖡𑖿𑖝𑖯𑖨𑖯𑖬𑖿𑖘𑖿𑖨𑖰𑖎𑖭𑖿𑖝𑖨𑖯𑖠𑖯𑖨𑖸𑖜 𑖡 𑖎𑖺𑖢𑖰 𑖥𑖸𑖟𑖺 𑖪𑖰𑖠𑖯𑖭𑖿𑖧𑖝𑖸𑗂"
  specimen_16: "𑖭𑖨𑖿𑖪𑖸 𑖦𑖯𑖡𑖪𑖯𑖾 𑖭𑖿𑖪𑖝𑖡𑖿𑖝𑖿𑖨𑖯𑖾 𑖭𑖦𑖲𑖝𑖿𑖢𑖡𑖿𑖡𑖯𑖾 𑖪𑖨𑖿𑖝𑖡𑖿𑖝𑖸 𑖀𑖢𑖰 𑖓, 𑖐𑖻𑖨𑖪𑖟𑖴𑖫𑖯 𑖀𑖠𑖰𑖎𑖯𑖨𑖟𑖴𑖫𑖯 𑖓 𑖭𑖦𑖯𑖡𑖯𑖾 𑖊𑖪 𑖪𑖨𑖿𑖝𑖡𑖿𑖝𑖸𑗂 𑖊𑖝𑖸 𑖭𑖨𑖿𑖪𑖸 𑖓𑖸𑖝𑖡𑖯𑖝𑖨𑖿𑖎𑖫𑖎𑖿𑖝𑖰𑖥𑖿𑖧𑖯𑖽 𑖭𑖲𑖭𑖦𑖿𑖢𑖡𑖿𑖡𑖯𑖾 𑖭𑖡𑖿𑖝𑖰𑗂 𑖀𑖢𑖰 𑖓, 𑖭𑖨𑖿𑖪𑖸𑖢𑖰 𑖤𑖡𑖿𑖠𑖲𑖝𑖿𑖪𑖥𑖯𑖪𑖡𑖧𑖯 𑖢𑖨𑖭𑖿𑖢𑖨𑖽 𑖪𑖿𑖧𑖪𑖮𑖨𑖡𑖿𑖝𑖲𑗂\n𑖀𑖭𑖿𑖧𑖯𑖽 𑖀𑖥𑖰𑖑𑖺𑖬𑖜𑖯𑖧𑖯𑖽 𑖡𑖰𑖨𑖿𑖟𑖰𑖬𑖿𑖘𑖯𑖾 𑖭𑖨𑖿𑖪𑖸𑖢𑖰 𑖀𑖠𑖰𑖎𑖯𑖨𑖯𑖾 𑖭𑖨𑖿𑖪𑖯𑖜𑖿𑖧𑖢𑖰 𑖓 𑖭𑖿𑖪𑖯𑖝𑖡𑖿𑖝𑖿𑖨𑖿𑖧𑖯𑖜𑖰, 𑖪𑖰𑖡𑖹𑖪 𑖕𑖯𑖝𑖰𑖪𑖨𑖿𑖜𑖩𑖰𑖽𑖐𑖥𑖯𑖬𑖯𑖠𑖨𑖿𑖦𑖨𑖯𑖕𑖡𑖱𑖝𑖰𑖎𑖝𑖟𑖰𑖝𑖨𑖦𑖡𑖿𑖝𑖪𑖿𑖧𑖯𑖟𑖰𑖥𑖸𑖟𑖦𑖿, 𑖨𑖯𑖬𑖿𑖘𑖿𑖨𑖰𑖧𑖽 𑖭𑖯𑖦𑖯𑖕𑖰𑖎𑖯𑖠𑖯𑖨𑖽 𑖭𑖦𑖿𑖢𑖕𑖿𑖕𑖡𑖿𑖦𑖝𑖟𑖰𑖝𑖨 𑖭𑖿𑖝𑖨𑖗𑖿𑖓 𑖀𑖪𑖰𑖐𑖜𑖧𑖿𑖧, 𑖀𑖠𑖰𑖐𑖡𑖿𑖝𑖲𑖽 𑖭𑖨𑖿𑖪𑖺𑖢𑖰 𑖕𑖡𑖾 𑖢𑖿𑖨𑖥𑖪𑖝𑖰𑗂\n𑖊𑖝𑖟𑖝𑖰𑖨𑖰𑖎𑖿𑖝𑖦𑖿, 𑖎𑖭𑖿𑖧𑖯𑖫𑖿𑖓𑖰𑖟𑖢𑖰 𑖢𑖿𑖨𑖥𑖲𑖭𑖝𑖿𑖝𑖯𑖧𑖯𑖾 𑖡𑖰𑖧𑖦𑖡𑖯𑖡𑖿𑖝𑖨𑖿𑖐𑖝𑖦𑖿, 𑖭𑖿𑖪𑖯𑖠𑖱𑖡𑖭𑖿𑖧 𑖁𑖝𑖿𑖦𑖢𑖿𑖨𑖫𑖯𑖭𑖡𑖸𑖝𑖨𑖝𑖡𑖿𑖝𑖿𑖨𑖭𑖿𑖧, 𑖡𑖿𑖧𑖯𑖭𑖰𑖝𑖡𑖿𑖝𑖿𑖨𑖭𑖿𑖧 𑖪𑖯 𑖪𑖯𑖭𑖿𑖝𑖪𑖿𑖧𑖭𑖿𑖧 𑖢𑖿𑖨𑖟𑖸𑖫𑖭𑖿𑖧 𑖟𑖸𑖫𑖭𑖿𑖧 𑖪𑖯 𑖨𑖯𑖕𑖡𑖱𑖝𑖰𑖎𑖭𑖱𑖦𑖯𑖡𑖰𑖤𑖡𑖿𑖠𑖡𑖯𑖡𑖿𑖝𑖯𑖨𑖯𑖬𑖿𑖘𑖿𑖨𑖰𑖎𑖭𑖿𑖝𑖨𑖯𑖠𑖯𑖨𑖸𑖜 𑖡 𑖎𑖺𑖢𑖰 𑖥𑖸𑖟𑖺 𑖪𑖰𑖠𑖯𑖭𑖿𑖧𑖝𑖸𑗂\n𑖭𑖨𑖿𑖪𑖺𑖢𑖰 𑖕𑖡𑖾 𑖕𑖱𑖪𑖡𑖭𑖿𑖪𑖯𑖝𑖡𑖿𑖝𑖿𑖨𑖿𑖧𑖭𑖲𑖨𑖎𑖿𑖬𑖯𑖠𑖰𑖎𑖯𑖨𑖽 𑖭𑖽𑖠𑖝𑖿𑖝𑖸𑗂\n𑖡 𑖎𑖦𑖢𑖰 𑖕𑖡𑖽 𑖟𑖯𑖭𑖝𑖿𑖪𑖸𑖡 𑖢𑖨𑖯𑖠𑖱𑖡𑖝𑖿𑖪𑖸𑖡 𑖪𑖯 𑖠𑖯𑖨𑖧𑖰𑖝𑖲𑖽 𑖀𑖡𑖲𑖕𑖿𑖗𑖯𑖭𑖿𑖧𑖝𑖸𑗂 𑖀𑖢𑖰 𑖓 𑖟𑖯𑖭𑖪𑖿𑖧𑖯𑖢𑖯𑖨𑖾 𑖢𑖳𑖨𑖿𑖜𑖨𑖳𑖢𑖸𑖜 𑖢𑖿𑖨𑖝𑖰𑖬𑖰𑖟𑖿𑖠𑖾 𑖭𑖿𑖞𑖯𑖭𑖿𑖧𑖝𑖰𑗂\n𑖡 𑖎𑖦𑖢𑖰 𑖕𑖡𑖽 𑖪𑖰𑖨𑖲𑖠𑖿𑖧 𑖀𑖪𑖦𑖯𑖡𑖡𑖯𑖝𑖿𑖦𑖎𑖽 𑖪𑖿𑖧𑖪𑖮𑖯𑖨𑖽 𑖟𑖜𑖿𑖚𑖽 𑖪𑖯 𑖎𑖿𑖨𑖳𑖨𑖽 𑖀𑖦𑖯𑖡𑖪𑖱𑖧𑖽 𑖢𑖿𑖨𑖝𑖺𑖟𑖡𑖽 𑖪𑖯 𑖢𑖿𑖨𑖪𑖨𑖿𑖝𑖧𑖰𑖝𑖲𑖽 𑖀𑖡𑖲𑖕𑖿𑖗𑖯𑖭𑖿𑖧𑖝𑖸𑗂"
}
historical: true
