id: "sa_Sind"
language: "sa"
script: "Sind"
name: "Sanskrit, Khudawadi"
region: "IN"
sample_text {
  masthead_full: "𑋝𑋙𑋛𑋗"
  masthead_partial: "𑋑𑋞"
  styles: "𑋘𑋍𑋪𑋙 𑋂𑊼𑋍𑋡 𑋜𑋠𑋑𑋪𑋍𑋡𑋑𑋪𑋘𑋠𑋘𑋝𑋪𑋛𑋠𑋍𑋑𑋪𑋍𑋪𑋙𑋪𑋘𑋠𑋌𑋠𑋟 𑊱𑋐𑋠𑋙𑋞𑋪 𑋗𑋠𑋑𑋛𑋒𑋙𑋡𑋛𑋠𑋙𑋝𑋪𑋘 𑋝𑋙𑋪𑋛𑋥𑋜𑋩𑋠𑋗𑋒𑋡"
  tester: "𑋝𑋙𑋪𑋛𑋥 𑋗𑋠𑋑𑋛𑋠𑋞𑋪 𑋝𑋪𑋛𑋍𑋑𑋪𑋍𑋪𑋙𑋠𑋞𑋪 𑋝𑋗𑋣𑋍𑋪𑋒𑋑𑋪𑋑𑋠𑋞𑋪 𑋛𑋙𑋪𑋍𑋑𑋪𑋍𑋥 𑊰𑋒𑋡 𑋀, 𑊼𑋨𑋙𑋛𑋏𑋪𑋙𑋡𑋜𑋠 𑊰𑋐𑋡𑊺𑋠𑋙𑋏𑋪𑋙𑋡𑋜𑋠 𑋀 𑋝𑋗𑋠𑋑𑋠𑋞𑋪 𑊶𑋛"
  poster_sm: "𑊰𑋝𑋪𑋘𑋠𑋟 𑊰𑋖𑋡𑊾𑋧𑋜𑋩𑋌𑋠𑋘𑋠𑋟"
  poster_md: "𑊶𑋍𑋏𑋍𑋡𑋙𑋡𑊺𑋪𑋍𑋗𑋪,"
  poster_lg: "𑋝𑋙𑋪𑋛𑋥"
  specimen_48: "𑋑 𑊺𑋗𑋒𑋡 𑋂𑋑𑋟 𑋏𑋠𑋝𑋍𑋪𑋛𑋥𑋑 𑋒𑋙𑋠𑋐𑋢𑋑𑋍𑋪𑋛𑋥𑋑 𑋛𑋠 𑋐𑋠𑋙𑋘𑋡𑋍𑋣𑋟 𑊰𑋑𑋣𑋂𑋪𑋅𑋠𑋝𑋪𑋘𑋍𑋥। 𑊰𑋒𑋡 𑋀 𑋏𑋠𑋝𑋛𑋪𑋘𑋠𑋒𑋠𑋙𑋞𑋪 𑋒𑋤𑋙𑋪𑋌𑋙𑋤𑋒𑋥𑋌 𑋒𑋪𑋙𑋍𑋡𑋜𑋩𑋡𑋏𑋪𑋐𑋞𑋪"
  specimen_36: "𑋝𑋙𑋪𑋛𑋧ऽ𑋒𑋡 𑋂𑋑𑋞𑋪 𑋂𑋢𑋛𑋑𑋝𑋪𑋛𑋠𑋍𑋑𑋪𑋍𑋪𑋙𑋪𑋘𑋝𑋣𑋙𑊺𑋪𑋜𑋩𑋠𑋐𑋡𑊺𑋠𑋙𑋟 𑋝𑋟𑋐𑋍𑋪𑋍𑋥।\n𑋑 𑊺𑋗𑋒𑋡 𑋂𑋑𑋟 𑋏𑋠𑋝𑋍𑋪𑋛𑋥𑋑 𑋒𑋙𑋠𑋐𑋢𑋑𑋍𑋪𑋛𑋥𑋑 𑋛𑋠 𑋐𑋠𑋙𑋘𑋡𑋍𑋣𑋟 𑊰𑋑𑋣𑋂𑋪𑋅𑋠𑋝𑋪𑋘𑋍𑋥। 𑊰𑋒𑋡 𑋀 𑋏𑋠𑋝𑋛𑋪𑋘𑋠𑋒𑋠𑋙𑋞𑋪 𑋒𑋤𑋙𑋪𑋌𑋙𑋤𑋒𑋥𑋌 𑋒𑋪𑋙𑋍𑋡𑋜𑋩𑋡𑋏𑋪𑋐𑋞𑋪 𑋝𑋪𑋎𑋠𑋝𑋪𑋘𑋍𑋡।"
  specimen_32: "𑊰𑋝𑋪𑋘𑋠𑋟 𑊰𑋖𑋡𑊾𑋧𑋜𑋩𑋌𑋠𑋘𑋠𑋟 𑋑𑋡𑋙𑋪𑋏𑋡𑋜𑋩𑋪𑋆𑋠𑋞𑋪 𑋝𑋙𑋪𑋛𑋥ऽ𑋒𑋡 𑊰𑋐𑋡𑊺𑋠𑋙𑋠𑋞𑋪 𑋝𑋙𑋪𑋛𑋠𑋌𑋪𑋘𑋒𑋡 𑋀 𑋝𑋪𑋛𑋠𑋍𑋑𑋪𑋍𑋪𑋙𑋪𑋘𑋠𑋌𑋡, 𑋛𑋡𑋑𑋦𑋛 𑋂𑋠𑋍𑋡𑋛𑋙𑋪𑋌𑋚𑋡𑋟𑊼𑋖𑋠𑋜𑋩𑋠𑋐𑋙𑋪𑋗𑋙𑋠𑋂𑋑𑋢𑋍𑋡𑊺𑋍𑋏𑋡𑋍𑋙𑋗𑋑𑋪𑋍𑋛𑋪𑋘𑋠𑋏𑋡𑋖𑋥𑋏𑋗𑋪, 𑋙𑋠𑋜𑋩𑋪𑋆𑋪𑋙𑋡𑋘𑋟 𑋝𑋠𑋗𑋠𑋂𑋡𑊺𑋠𑋐𑋠𑋙𑋟 𑋝𑋗𑋪𑋒𑋂𑋪𑋂𑋑𑋪𑋗𑋍𑋏𑋡𑋍𑋙 𑋝𑋪𑋍𑋙𑋅𑋪𑋀 𑊰𑋛𑋡𑊼𑋌𑋘𑋪𑋘, 𑊰𑋐𑋡𑊼𑋑𑋪𑋍𑋣𑋟 𑋝𑋙𑋪𑋛𑋧ऽ𑋒𑋡 𑋂𑋑𑋞𑋪 𑋒𑋪𑋙𑋖𑋛𑋍𑋡।"
  specimen_21: "𑋝𑋙𑋪𑋛𑋥 𑋗𑋠𑋑𑋛𑋠𑋞𑋪 𑋝𑋪𑋛𑋍𑋑𑋪𑋍𑋪𑋙𑋠𑋞𑋪 𑋝𑋗𑋣𑋍𑋪𑋒𑋑𑋪𑋑𑋠𑋞𑋪 𑋛𑋙𑋪𑋍𑋑𑋪𑋍𑋥 𑊰𑋒𑋡 𑋀, 𑊼𑋨𑋙𑋛𑋏𑋪𑋙𑋡𑋜𑋠 𑊰𑋐𑋡𑊺𑋠𑋙𑋏𑋪𑋙𑋡𑋜𑋠 𑋀 𑋝𑋗𑋠𑋑𑋠𑋞𑋪 𑊶𑋛 𑋛𑋙𑋪𑋍𑋑𑋪𑋍𑋥। 𑊶𑋍𑋥 𑋝𑋙𑋪𑋛𑋥 𑋀𑋥𑋍𑋑𑋠𑋍𑋙𑋪𑊺𑋜𑊺𑋪𑋍𑋡𑋖𑋪𑋘𑋠𑋟 𑋝𑋣𑋝𑋗𑋪𑋒𑋑𑋪𑋑𑋠𑋞𑋪 𑋝𑋑𑋪𑋍𑋡। 𑊰𑋒𑋡 𑋀, 𑋝𑋙𑋪𑋛𑋥ऽ𑋒𑋡 𑋔𑋑𑋪𑋐𑋣𑋍𑋪𑋛𑋖𑋠𑋛𑋑𑋘𑋠 𑋒𑋙𑋝𑋪𑋒𑋙𑋟 𑋛𑋪𑋘𑋛𑋞𑋙𑋑𑋪𑋍𑋣।\n𑊰𑋝𑋪𑋘𑋠𑋟 𑊰𑋖𑋡𑊾𑋧𑋜𑋩𑋌𑋠𑋘𑋠𑋟 𑋑𑋡𑋙𑋪𑋏𑋡𑋜𑋩𑋪𑋆𑋠𑋞𑋪 𑋝𑋙𑋪𑋛𑋥ऽ𑋒𑋡 𑊰𑋐𑋡𑊺𑋠𑋙𑋠𑋞𑋪 𑋝𑋙𑋪𑋛𑋠𑋌𑋪𑋘𑋒𑋡 𑋀 𑋝𑋪𑋛𑋠𑋍𑋑𑋪𑋍𑋪𑋙𑋪𑋘𑋠𑋌𑋡, 𑋛𑋡𑋑𑋦𑋛 𑋂𑋠𑋍𑋡𑋛𑋙𑋪𑋌𑋚𑋡𑋟𑊼𑋖𑋠𑋜𑋩𑋠𑋐𑋙𑋪𑋗𑋙𑋠𑋂𑋑𑋢𑋍𑋡𑊺𑋍𑋏𑋡𑋍𑋙𑋗𑋑𑋪𑋍𑋛𑋪𑋘𑋠𑋏𑋡𑋖𑋥𑋏𑋗𑋪, 𑋙𑋠𑋜𑋩𑋪𑋆𑋪𑋙𑋡𑋘𑋟 𑋝𑋠𑋗𑋠𑋂𑋡𑊺𑋠𑋐𑋠𑋙𑋟 𑋝𑋗𑋪𑋒𑋂𑋪𑋂𑋑𑋪𑋗𑋍𑋏𑋡𑋍𑋙 𑋝𑋪𑋍𑋙𑋅𑋪𑋀 𑊰𑋛𑋡𑊼𑋌𑋘𑋪𑋘, 𑊰𑋐𑋡𑊼𑋑𑋪𑋍𑋣𑋟 𑋝𑋙𑋪𑋛𑋧ऽ𑋒𑋡 𑋂𑋑𑋞𑋪 𑋒𑋪𑋙𑋖𑋛𑋍𑋡।\n𑊶𑋍𑋏𑋍𑋡𑋙𑋡𑊺𑋪𑋍𑋗𑋪, 𑊺𑋝𑋪𑋘𑋠𑋜𑋪𑋀𑋡𑋏𑋒𑋡 𑋒𑋪𑋙𑋖𑋣𑋝𑋍𑋪𑋍𑋠𑋘𑋠𑋞𑋪 𑋑𑋡𑋘𑋗𑋑𑋠𑋑𑋪𑋍𑋙𑋪𑊼𑋍𑋗𑋪, 𑋝𑋪𑋛𑋠𑋐𑋢𑋑𑋝𑋪𑋘 𑊱𑋍𑋪𑋗𑋒𑋪𑋙𑋜𑋠𑋝𑋑𑋥𑋍𑋙𑋍𑋑𑋪𑋍𑋪𑋙𑋝𑋪𑋘, 𑋑𑋪𑋘𑋠𑋝𑋡𑋍𑋑𑋪𑋍𑋪𑋙𑋝𑋪𑋘 𑋛𑋠 𑋛𑋠𑋝𑋪𑋍𑋛𑋪𑋘𑋝𑋪𑋘 𑋒𑋪𑋙𑋏𑋥𑋜𑋝𑋪𑋘 𑋏𑋥𑋜𑋝𑋪𑋘 𑋛𑋠 𑋙𑋠𑋂𑋑𑋢𑋍𑋡𑊺𑋝𑋢𑋗𑋠𑋑𑋡𑋔𑋑𑋪𑋐𑋑𑋠𑋑𑋪𑋍𑋠𑋙𑋠𑋜𑋩𑋪𑋆𑋪𑋙𑋡𑊺𑋝𑋪𑋍𑋙𑋠𑋐𑋠𑋙𑋥𑋌 𑋑 𑊺𑋧ऽ𑋒𑋡 𑋖𑋥𑋏𑋧 𑋛𑋡𑋐𑋠𑋝𑋪𑋘𑋍𑋥।"
  specimen_16: "𑋝𑋙𑋪𑋛𑋥 𑋗𑋠𑋑𑋛𑋠𑋞𑋪 𑋝𑋪𑋛𑋍𑋑𑋪𑋍𑋪𑋙𑋠𑋞𑋪 𑋝𑋗𑋣𑋍𑋪𑋒𑋑𑋪𑋑𑋠𑋞𑋪 𑋛𑋙𑋪𑋍𑋑𑋪𑋍𑋥 𑊰𑋒𑋡 𑋀, 𑊼𑋨𑋙𑋛𑋏𑋪𑋙𑋡𑋜𑋠 𑊰𑋐𑋡𑊺𑋠𑋙𑋏𑋪𑋙𑋡𑋜𑋠 𑋀 𑋝𑋗𑋠𑋑𑋠𑋞𑋪 𑊶𑋛 𑋛𑋙𑋪𑋍𑋑𑋪𑋍𑋥। 𑊶𑋍𑋥 𑋝𑋙𑋪𑋛𑋥 𑋀𑋥𑋍𑋑𑋠𑋍𑋙𑋪𑊺𑋜𑊺𑋪𑋍𑋡𑋖𑋪𑋘𑋠𑋟 𑋝𑋣𑋝𑋗𑋪𑋒𑋑𑋪𑋑𑋠𑋞𑋪 𑋝𑋑𑋪𑋍𑋡। 𑊰𑋒𑋡 𑋀, 𑋝𑋙𑋪𑋛𑋥ऽ𑋒𑋡 𑋔𑋑𑋪𑋐𑋣𑋍𑋪𑋛𑋖𑋠𑋛𑋑𑋘𑋠 𑋒𑋙𑋝𑋪𑋒𑋙𑋟 𑋛𑋪𑋘𑋛𑋞𑋙𑋑𑋪𑋍𑋣।\n𑊰𑋝𑋪𑋘𑋠𑋟 𑊰𑋖𑋡𑊾𑋧𑋜𑋩𑋌𑋠𑋘𑋠𑋟 𑋑𑋡𑋙𑋪𑋏𑋡𑋜𑋩𑋪𑋆𑋠𑋞𑋪 𑋝𑋙𑋪𑋛𑋥ऽ𑋒𑋡 𑊰𑋐𑋡𑊺𑋠𑋙𑋠𑋞𑋪 𑋝𑋙𑋪𑋛𑋠𑋌𑋪𑋘𑋒𑋡 𑋀 𑋝𑋪𑋛𑋠𑋍𑋑𑋪𑋍𑋪𑋙𑋪𑋘𑋠𑋌𑋡, 𑋛𑋡𑋑𑋦𑋛 𑋂𑋠𑋍𑋡𑋛𑋙𑋪𑋌𑋚𑋡𑋟𑊼𑋖𑋠𑋜𑋩𑋠𑋐𑋙𑋪𑋗𑋙𑋠𑋂𑋑𑋢𑋍𑋡𑊺𑋍𑋏𑋡𑋍𑋙𑋗𑋑𑋪𑋍𑋛𑋪𑋘𑋠𑋏𑋡𑋖𑋥𑋏𑋗𑋪, 𑋙𑋠𑋜𑋩𑋪𑋆𑋪𑋙𑋡𑋘𑋟 𑋝𑋠𑋗𑋠𑋂𑋡𑊺𑋠𑋐𑋠𑋙𑋟 𑋝𑋗𑋪𑋒𑋂𑋪𑋂𑋑𑋪𑋗𑋍𑋏𑋡𑋍𑋙 𑋝𑋪𑋍𑋙𑋅𑋪𑋀 𑊰𑋛𑋡𑊼𑋌𑋘𑋪𑋘, 𑊰𑋐𑋡𑊼𑋑𑋪𑋍𑋣𑋟 𑋝𑋙𑋪𑋛𑋧ऽ𑋒𑋡 𑋂𑋑𑋞𑋪 𑋒𑋪𑋙𑋖𑋛𑋍𑋡।\n𑊶𑋍𑋏𑋍𑋡𑋙𑋡𑊺𑋪𑋍𑋗𑋪, 𑊺𑋝𑋪𑋘𑋠𑋜𑋪𑋀𑋡𑋏𑋒𑋡 𑋒𑋪𑋙𑋖𑋣𑋝𑋍𑋪𑋍𑋠𑋘𑋠𑋞𑋪 𑋑𑋡𑋘𑋗𑋑𑋠𑋑𑋪𑋍𑋙𑋪𑊼𑋍𑋗𑋪, 𑋝𑋪𑋛𑋠𑋐𑋢𑋑𑋝𑋪𑋘 𑊱𑋍𑋪𑋗𑋒𑋪𑋙𑋜𑋠𑋝𑋑𑋥𑋍𑋙𑋍𑋑𑋪𑋍𑋪𑋙𑋝𑋪𑋘, 𑋑𑋪𑋘𑋠𑋝𑋡𑋍𑋑𑋪𑋍𑋪𑋙𑋝𑋪𑋘 𑋛𑋠 𑋛𑋠𑋝𑋪𑋍𑋛𑋪𑋘𑋝𑋪𑋘 𑋒𑋪𑋙𑋏𑋥𑋜𑋝𑋪𑋘 𑋏𑋥𑋜𑋝𑋪𑋘 𑋛𑋠 𑋙𑋠𑋂𑋑𑋢𑋍𑋡𑊺𑋝𑋢𑋗𑋠𑋑𑋡𑋔𑋑𑋪𑋐𑋑𑋠𑋑𑋪𑋍𑋠𑋙𑋠𑋜𑋩𑋪𑋆𑋪𑋙𑋡𑊺𑋝𑋪𑋍𑋙𑋠𑋐𑋠𑋙𑋥𑋌 𑋑 𑊺𑋧ऽ𑋒𑋡 𑋖𑋥𑋏𑋧 𑋛𑋡𑋐𑋠𑋝𑋪𑋘𑋍𑋥।\n𑋝𑋙𑋪𑋛𑋧ऽ𑋒𑋡 𑋂𑋑𑋞𑋪 𑋂𑋢𑋛𑋑𑋝𑋪𑋛𑋠𑋍𑋑𑋪𑋍𑋪𑋙𑋪𑋘𑋝𑋣𑋙𑊺𑋪𑋜𑋩𑋠𑋐𑋡𑊺𑋠𑋙𑋟 𑋝𑋟𑋐𑋍𑋪𑋍𑋥।\n𑋑 𑊺𑋗𑋒𑋡 𑋂𑋑𑋟 𑋏𑋠𑋝𑋍𑋪𑋛𑋥𑋑 𑋒𑋙𑋠𑋐𑋢𑋑𑋍𑋪𑋛𑋥𑋑 𑋛𑋠 𑋐𑋠𑋙𑋘𑋡𑋍𑋣𑋟 𑊰𑋑𑋣𑋂𑋪𑋅𑋠𑋝𑋪𑋘𑋍𑋥। 𑊰𑋒𑋡 𑋀 𑋏𑋠𑋝𑋛𑋪𑋘𑋠𑋒𑋠𑋙𑋞𑋪 𑋒𑋤𑋙𑋪𑋌𑋙𑋤𑋒𑋥𑋌 𑋒𑋪𑋙𑋍𑋡𑋜𑋩𑋡𑋏𑋪𑋐𑋞𑋪 𑋝𑋪𑋎𑋠𑋝𑋪𑋘𑋍𑋡।\n𑋑 𑊺𑋗𑋒𑋡 𑋂𑋑𑋟 𑋛𑋡𑋙𑋣𑋐𑋪𑋘 𑊰𑋛𑋗𑋠𑋑𑋑𑋠𑋍𑋪𑋗𑊺𑋟 𑋛𑋪𑋘𑋛𑋞𑋠𑋙𑋟 𑋏𑋌𑋪𑋈𑋟 𑋛𑋠 𑊺𑋪𑋙𑋤𑋙𑋟 𑊰𑋗𑋠𑋑𑋛𑋢𑋘𑋟 𑋒𑋪𑋙𑋍𑋧𑋏𑋑𑋟 𑋛𑋠 𑋒𑋪𑋙𑋛𑋙𑋪𑋍𑋘𑋡𑋍𑋣𑋟 𑊰𑋑𑋣𑋂𑋪𑋅𑋠𑋝𑋪𑋘𑋍𑋥।"
}
historical: true
