id: "sa_Sylo"
language: "sa"
script: "Sylo"
name: "Sanskrit, Syloti Nagri"
sample_text {
  masthead_full: "ꠡꠞꠛꠝ"
  masthead_partial: "ꠘꠢ"
  styles: "ꠎꠔ꠆ꠞ ꠎꠉꠔꠤ ꠡꠣꠘ꠆ꠔꠤꠘ꠆ꠎꠣꠎꠡ꠆ꠛꠣꠔꠘ꠆ꠔ꠆ꠞ꠆ꠎꠣꠘꠣꠋ ꠀꠗꠣꠞꠢ꠆ ꠝꠣꠘꠛꠙꠞꠤꠛꠣꠞꠡ꠆ꠎ ꠡꠞ꠆ꠛꠦꠡꠣꠝꠙꠤ"
  tester: "ꠡꠞ꠆ꠛꠦ ꠝꠣꠘꠛꠣꠢ꠆ ꠡ꠆ꠛꠔꠘ꠆ꠔ꠆ꠞꠣꠢ꠆ ꠡꠝꠥꠔ꠆ꠙꠘ꠆ꠘꠣꠢ꠆ ꠛꠞ꠆ꠔꠘ꠆ꠔꠦ ꠅꠙꠤ ꠌ, ꠉꠃꠞꠛꠖ꠆ꠞꠤꠡꠣ ꠅꠗꠤꠇꠣꠞꠖ꠆ꠞꠤꠡꠣ ꠌ ꠡꠝꠣꠘꠣꠢ꠆ ꠄꠛ"
  poster_sm: "ꠅꠡ꠆ꠎꠣꠋ ꠅꠜꠤꠊꠧꠡꠘꠣꠎꠣꠋ"
  poster_md: "ꠄꠔꠖꠔꠤꠞꠤꠇ꠆ꠔꠝ꠆,"
  poster_lg: "ꠡꠞ꠆ꠛꠦ"
  specimen_48: "ꠘ ꠇꠝꠙꠤ ꠎꠘꠋ ꠖꠣꠡꠔ꠆ꠛꠦꠘ ꠙꠞꠣꠗꠤꠘꠔ꠆ꠛꠦꠘ ꠛꠣ ꠗꠣꠞꠎꠤꠔꠥꠋ ꠅꠘꠥꠎ꠆ꠘꠣꠡ꠆ꠎꠔꠦ। ꠅꠙꠤ ꠌ ꠖꠣꠡꠛ꠆ꠎꠣꠙꠣꠞꠢ꠆ ꠙꠥꠞ꠆ꠘꠞꠥꠙꠦꠘ ꠙ꠆ꠞꠔꠤꠡꠤꠖ꠆ꠗꠢ꠆"
  specimen_36: "ꠡꠞ꠆ꠛꠧঽꠙꠤ ꠎꠘꠢ꠆ ꠎꠤꠛꠘꠡ꠆ꠛꠣꠔꠘ꠆ꠔ꠆ꠞ꠆ꠎꠡꠥꠞꠇ꠆ꠡꠣꠗꠤꠇꠣꠞꠋ ꠡꠋꠗꠔ꠆ꠔꠦ।\nꠘ ꠇꠝꠙꠤ ꠎꠘꠋ ꠖꠣꠡꠔ꠆ꠛꠦꠘ ꠙꠞꠣꠗꠤꠘꠔ꠆ꠛꠦꠘ ꠛꠣ ꠗꠣꠞꠎꠤꠔꠥꠋ ꠅꠘꠥꠎ꠆ꠘꠣꠡ꠆ꠎꠔꠦ। ꠅꠙꠤ ꠌ ꠖꠣꠡꠛ꠆ꠎꠣꠙꠣꠞꠢ꠆ ꠙꠥꠞ꠆ꠘꠞꠥꠙꠦꠘ ꠙ꠆ꠞꠔꠤꠡꠤꠖ꠆ꠗꠢ꠆ ꠡ꠆ꠕꠣꠡ꠆ꠎꠔꠤ।"
  specimen_32: "ꠅꠡ꠆ꠎꠣꠋ ꠅꠜꠤꠊꠧꠡꠘꠣꠎꠣꠋ ꠘꠤꠞ꠆ꠖꠤꠡ꠆ꠐꠣꠢ꠆ ꠡꠞ꠆ꠛꠦঽꠙꠤ ꠅꠗꠤꠇꠣꠞꠣꠢ꠆ ꠡꠞ꠆ꠛꠣꠘ꠆ꠎꠙꠤ ꠌ ꠡ꠆ꠛꠣꠔꠘ꠆ꠔ꠆ꠞ꠆ꠎꠣꠘꠤ, ꠛꠤꠘꠂꠛ ꠎꠣꠔꠤꠛꠞ꠆ꠘꠟꠤꠋꠉꠜꠣꠡꠣꠗꠞ꠆ꠝꠞꠣꠎꠘꠤꠔꠤꠇꠔꠖꠤꠔꠞꠝꠘ꠆ꠔꠛ꠆ꠎꠣꠖꠤꠜꠦꠖꠝ꠆, ꠞꠣꠡ꠆ꠐ꠆ꠞꠤꠎꠋ ꠡꠣꠝꠣꠎꠤꠇꠣꠗꠣꠞꠋ ꠡꠝ꠆ꠙꠎ꠆ꠎꠘ꠆ꠝꠔꠖꠤꠔꠞ ꠡ꠆ꠔꠞꠘ꠆ꠌ ꠅꠛꠤꠉꠘꠎ꠆ꠎ, ꠅꠗꠤꠉꠘ꠆ꠔꠥꠋ ꠡꠞ꠆ꠛꠧঽꠙꠤ ꠎꠘꠢ꠆ ꠙ꠆ꠞꠜꠛꠔꠤ।"
  specimen_21: "ꠡꠞ꠆ꠛꠦ ꠝꠣꠘꠛꠣꠢ꠆ ꠡ꠆ꠛꠔꠘ꠆ꠔ꠆ꠞꠣꠢ꠆ ꠡꠝꠥꠔ꠆ꠙꠘ꠆ꠘꠣꠢ꠆ ꠛꠞ꠆ꠔꠘ꠆ꠔꠦ ꠅꠙꠤ ꠌ, ꠉꠃꠞꠛꠖ꠆ꠞꠤꠡꠣ ꠅꠗꠤꠇꠣꠞꠖ꠆ꠞꠤꠡꠣ ꠌ ꠡꠝꠣꠘꠣꠢ꠆ ꠄꠛ ꠛꠞ꠆ꠔꠘ꠆ꠔꠦ। ꠄꠔꠦ ꠡꠞ꠆ꠛꠦ ꠌꠦꠔꠘꠣꠔꠞ꠆ꠇꠡꠇ꠆ꠔꠤꠜ꠆ꠎꠣꠋ ꠡꠥꠡꠝ꠆ꠙꠘ꠆ꠘꠣꠢ꠆ ꠡꠘ꠆ꠔꠤ। ꠅꠙꠤ ꠌ, ꠡꠞ꠆ꠛꠦঽꠙꠤ ꠛꠘ꠆ꠗꠥꠔ꠆ꠛꠜꠣꠛꠘꠎꠣ ꠙꠞꠡ꠆ꠙꠞꠋ ꠛ꠆ꠎꠛꠢꠞꠘ꠆ꠔꠥ।\nꠅꠡ꠆ꠎꠣꠋ ꠅꠜꠤꠊꠧꠡꠘꠣꠎꠣꠋ ꠘꠤꠞ꠆ꠖꠤꠡ꠆ꠐꠣꠢ꠆ ꠡꠞ꠆ꠛꠦঽꠙꠤ ꠅꠗꠤꠇꠣꠞꠣꠢ꠆ ꠡꠞ꠆ꠛꠣꠘ꠆ꠎꠙꠤ ꠌ ꠡ꠆ꠛꠣꠔꠘ꠆ꠔ꠆ꠞ꠆ꠎꠣꠘꠤ, ꠛꠤꠘꠂꠛ ꠎꠣꠔꠤꠛꠞ꠆ꠘꠟꠤꠋꠉꠜꠣꠡꠣꠗꠞ꠆ꠝꠞꠣꠎꠘꠤꠔꠤꠇꠔꠖꠤꠔꠞꠝꠘ꠆ꠔꠛ꠆ꠎꠣꠖꠤꠜꠦꠖꠝ꠆, ꠞꠣꠡ꠆ꠐ꠆ꠞꠤꠎꠋ ꠡꠣꠝꠣꠎꠤꠇꠣꠗꠣꠞꠋ ꠡꠝ꠆ꠙꠎ꠆ꠎꠘ꠆ꠝꠔꠖꠤꠔꠞ ꠡ꠆ꠔꠞꠘ꠆ꠌ ꠅꠛꠤꠉꠘꠎ꠆ꠎ, ꠅꠗꠤꠉꠘ꠆ꠔꠥꠋ ꠡꠞ꠆ꠛꠧঽꠙꠤ ꠎꠘꠢ꠆ ꠙ꠆ꠞꠜꠛꠔꠤ।\nꠄꠔꠖꠔꠤꠞꠤꠇ꠆ꠔꠝ꠆, ꠇꠡ꠆ꠎꠣꠡ꠆ꠌꠤꠖꠙꠤ ꠙ꠆ꠞꠜꠥꠡꠔ꠆ꠔꠣꠎꠣꠢ꠆ ꠘꠤꠎꠝꠘꠣꠘ꠆ꠔꠞ꠆ꠉꠔꠝ꠆, ꠡ꠆ꠛꠣꠗꠤꠘꠡ꠆ꠎ ꠀꠔ꠆ꠝꠙ꠆ꠞꠡꠣꠡꠘꠦꠔꠞꠔꠘ꠆ꠔ꠆ꠞꠡ꠆ꠎ, ꠘ꠆ꠎꠣꠡꠤꠔꠘ꠆ꠔ꠆ꠞꠡ꠆ꠎ ꠛꠣ ꠛꠣꠡ꠆ꠔꠛ꠆ꠎꠡ꠆ꠎ ꠙ꠆ꠞꠖꠦꠡꠡ꠆ꠎ ꠖꠦꠡꠡ꠆ꠎ ꠛꠣ ꠞꠣꠎꠘꠤꠔꠤꠇꠡꠤꠝꠣꠘꠤꠛꠘ꠆ꠗꠘꠣꠘ꠆ꠔꠣꠞꠣꠡ꠆ꠐ꠆ꠞꠤꠇꠡ꠆ꠔꠞꠣꠗꠣꠞꠦꠘ ꠘ ꠇꠧঽꠙꠤ ꠜꠦꠖꠧ ꠛꠤꠗꠣꠡ꠆ꠎꠔꠦ।"
  specimen_16: "ꠡꠞ꠆ꠛꠦ ꠝꠣꠘꠛꠣꠢ꠆ ꠡ꠆ꠛꠔꠘ꠆ꠔ꠆ꠞꠣꠢ꠆ ꠡꠝꠥꠔ꠆ꠙꠘ꠆ꠘꠣꠢ꠆ ꠛꠞ꠆ꠔꠘ꠆ꠔꠦ ꠅꠙꠤ ꠌ, ꠉꠃꠞꠛꠖ꠆ꠞꠤꠡꠣ ꠅꠗꠤꠇꠣꠞꠖ꠆ꠞꠤꠡꠣ ꠌ ꠡꠝꠣꠘꠣꠢ꠆ ꠄꠛ ꠛꠞ꠆ꠔꠘ꠆ꠔꠦ। ꠄꠔꠦ ꠡꠞ꠆ꠛꠦ ꠌꠦꠔꠘꠣꠔꠞ꠆ꠇꠡꠇ꠆ꠔꠤꠜ꠆ꠎꠣꠋ ꠡꠥꠡꠝ꠆ꠙꠘ꠆ꠘꠣꠢ꠆ ꠡꠘ꠆ꠔꠤ। ꠅꠙꠤ ꠌ, ꠡꠞ꠆ꠛꠦঽꠙꠤ ꠛꠘ꠆ꠗꠥꠔ꠆ꠛꠜꠣꠛꠘꠎꠣ ꠙꠞꠡ꠆ꠙꠞꠋ ꠛ꠆ꠎꠛꠢꠞꠘ꠆ꠔꠥ।\nꠅꠡ꠆ꠎꠣꠋ ꠅꠜꠤꠊꠧꠡꠘꠣꠎꠣꠋ ꠘꠤꠞ꠆ꠖꠤꠡ꠆ꠐꠣꠢ꠆ ꠡꠞ꠆ꠛꠦঽꠙꠤ ꠅꠗꠤꠇꠣꠞꠣꠢ꠆ ꠡꠞ꠆ꠛꠣꠘ꠆ꠎꠙꠤ ꠌ ꠡ꠆ꠛꠣꠔꠘ꠆ꠔ꠆ꠞ꠆ꠎꠣꠘꠤ, ꠛꠤꠘꠂꠛ ꠎꠣꠔꠤꠛꠞ꠆ꠘꠟꠤꠋꠉꠜꠣꠡꠣꠗꠞ꠆ꠝꠞꠣꠎꠘꠤꠔꠤꠇꠔꠖꠤꠔꠞꠝꠘ꠆ꠔꠛ꠆ꠎꠣꠖꠤꠜꠦꠖꠝ꠆, ꠞꠣꠡ꠆ꠐ꠆ꠞꠤꠎꠋ ꠡꠣꠝꠣꠎꠤꠇꠣꠗꠣꠞꠋ ꠡꠝ꠆ꠙꠎ꠆ꠎꠘ꠆ꠝꠔꠖꠤꠔꠞ ꠡ꠆ꠔꠞꠘ꠆ꠌ ꠅꠛꠤꠉꠘꠎ꠆ꠎ, ꠅꠗꠤꠉꠘ꠆ꠔꠥꠋ ꠡꠞ꠆ꠛꠧঽꠙꠤ ꠎꠘꠢ꠆ ꠙ꠆ꠞꠜꠛꠔꠤ।\nꠄꠔꠖꠔꠤꠞꠤꠇ꠆ꠔꠝ꠆, ꠇꠡ꠆ꠎꠣꠡ꠆ꠌꠤꠖꠙꠤ ꠙ꠆ꠞꠜꠥꠡꠔ꠆ꠔꠣꠎꠣꠢ꠆ ꠘꠤꠎꠝꠘꠣꠘ꠆ꠔꠞ꠆ꠉꠔꠝ꠆, ꠡ꠆ꠛꠣꠗꠤꠘꠡ꠆ꠎ ꠀꠔ꠆ꠝꠙ꠆ꠞꠡꠣꠡꠘꠦꠔꠞꠔꠘ꠆ꠔ꠆ꠞꠡ꠆ꠎ, ꠘ꠆ꠎꠣꠡꠤꠔꠘ꠆ꠔ꠆ꠞꠡ꠆ꠎ ꠛꠣ ꠛꠣꠡ꠆ꠔꠛ꠆ꠎꠡ꠆ꠎ ꠙ꠆ꠞꠖꠦꠡꠡ꠆ꠎ ꠖꠦꠡꠡ꠆ꠎ ꠛꠣ ꠞꠣꠎꠘꠤꠔꠤꠇꠡꠤꠝꠣꠘꠤꠛꠘ꠆ꠗꠘꠣꠘ꠆ꠔꠣꠞꠣꠡ꠆ꠐ꠆ꠞꠤꠇꠡ꠆ꠔꠞꠣꠗꠣꠞꠦꠘ ꠘ ꠇꠧঽꠙꠤ ꠜꠦꠖꠧ ꠛꠤꠗꠣꠡ꠆ꠎꠔꠦ।\nꠡꠞ꠆ꠛꠧঽꠙꠤ ꠎꠘꠢ꠆ ꠎꠤꠛꠘꠡ꠆ꠛꠣꠔꠘ꠆ꠔ꠆ꠞ꠆ꠎꠡꠥꠞꠇ꠆ꠡꠣꠗꠤꠇꠣꠞꠋ ꠡꠋꠗꠔ꠆ꠔꠦ।\nꠘ ꠇꠝꠙꠤ ꠎꠘꠋ ꠖꠣꠡꠔ꠆ꠛꠦꠘ ꠙꠞꠣꠗꠤꠘꠔ꠆ꠛꠦꠘ ꠛꠣ ꠗꠣꠞꠎꠤꠔꠥꠋ ꠅꠘꠥꠎ꠆ꠘꠣꠡ꠆ꠎꠔꠦ। ꠅꠙꠤ ꠌ ꠖꠣꠡꠛ꠆ꠎꠣꠙꠣꠞꠢ꠆ ꠙꠥꠞ꠆ꠘꠞꠥꠙꠦꠘ ꠙ꠆ꠞꠔꠤꠡꠤꠖ꠆ꠗꠢ꠆ ꠡ꠆ꠕꠣꠡ꠆ꠎꠔꠤ।\nꠘ ꠇꠝꠙꠤ ꠎꠘꠋ ꠛꠤꠞꠥꠗ꠆ꠎ ꠅꠛꠝꠣꠘꠘꠣꠔ꠆ꠝꠇꠋ ꠛ꠆ꠎꠛꠢꠣꠞꠋ ꠖꠘ꠆ꠒꠋ ꠛꠣ ꠇ꠆ꠞꠥꠞꠋ ꠅꠝꠣꠘꠛꠤꠎꠋ ꠙ꠆ꠞꠔꠧꠖꠘꠋ ꠛꠣ ꠙ꠆ꠞꠛꠞ꠆ꠔꠎꠤꠔꠥꠋ ꠅꠘꠥꠎ꠆ꠘꠣꠡ꠆ꠎꠔꠦ।"
}
historical: true
