id: "sa_Wcho"
language: "sa"
script: "Wcho"
name: "Sanskrit, Wancho"
region: "IN"
sample_text {
  masthead_full: "𞋃𞋁𞋆𞋀"
  masthead_partial: "𞋆𞋀"
  styles: "𞋆𞋁𞋡𞋁 𞋐𞋁𞋅𞋁𞋋𞋜 𞋏𞋀𞋉𞋋𞋜𞋉𞋆𞋀𞋆𞋁𞋎𞋓𞋀𞋋𞋁𞋉𞋡𞋆𞋀𞋉𞋣 𞋀𞋄𞋀𞋗𞋁𞋫"
  tester: "𞋎𞋁𞋗𞋓𞋛 𞋘𞋀𞋉𞋁𞋓𞋀𞋫 𞋎𞋓𞋁𞋋𞋁𞋉𞋡𞋀𞋫 𞋎𞋁𞋘𞋞𞋋𞋊𞋁𞋉𞋉𞋀𞋫 𞋓𞋁𞋗𞋋𞋁𞋉𞋋𞋛 𞋁𞋊𞋜 𞋃𞋁, 𞋅𞋖𞋗𞋁𞋓𞋁𞋄𞋗𞋞𞋏𞋀"
  poster_sm: "𞋁𞋎𞋆𞋣 𞋁𞋂𞋜𞋅𞋕"
  poster_md: "𞋛𞋋𞋁𞋄𞋁𞋋𞋜𞋗"
  poster_lg: "𞋎𞋁𞋗𞋓𞋛"
  specimen_48: "𞋉𞋁 𞋔𞋁𞋘𞋁𞋊𞋜 𞋐𞋁𞋉𞋤 𞋄𞋀𞋎𞋁𞋋𞋓𞋛𞋉𞋁 𞋊𞋁𞋗𞋀𞋄𞋜𞋉𞋁𞋋𞋓𞋛𞋉𞋁 𞋓𞋀 𞋄𞋀𞋗𞋁𞋆𞋜𞋋𞋞𞋝 𞋁𞋉𞋞𞋐𞋩𞋀𞋎𞋆𞋁𞋋𞋛."
  specimen_36: "𞋉𞋁 𞋔𞋁𞋘𞋁𞋊𞋜 𞋐𞋁𞋉𞋤 𞋓𞋜𞋗𞋞𞋄𞋆𞋁 𞋁𞋓𞋁𞋘𞋀𞋉𞋁𞋉𞋀𞋋𞋘𞋁𞋔𞋤 𞋓𞋆𞋁𞋓𞋁𞋚𞋀𞋗𞋤 𞋄𞋁𞋉𞋄𞋤 𞋓𞋀 𞋔𞋗𞋞𞋗𞋤 𞋁𞋘𞋀𞋉𞋁𞋓𞋜𞋆𞋤 𞋊𞋗𞋁𞋋𞋕𞋄𞋁𞋉𞋤 𞋓𞋀 𞋊𞋗𞋁𞋓𞋁𞋗𞋋𞋁𞋆𞋜𞋋𞋞𞋝 𞋁𞋉𞋞𞋐𞋩𞋀𞋎𞋆𞋁𞋋𞋛."
  specimen_32: "𞋓𞋜𞋄𞋜𞋉𞋀 𞋎𞋤𞋓𞋜𞋄𞋀𞋉𞋛𞋉𞋁 𞋓𞋀 𞋊𞋗𞋁𞋄𞋁𞋋𞋋𞋀𞋉𞋣 𞋘𞋖𞋈𞋜𞋔𞋀𞋄𞋜𞋔𞋀𞋗𞋀𞋉𞋀𞋘𞋞𞋈𞋈𞋤𞋅𞋁𞋉𞋁𞋔𞋀𞋗𞋆𞋀𞋉𞋣 𞋔𞋗𞋞𞋋𞋛, 𞋆𞋕𞋅𞋆𞋀𞋜𞋫 𞋗𞋀𞋏𞋡𞋜𞋆𞋁𞋉𞋆𞋀𞋆𞋁𞋊𞋜𞋌𞋀𞋜𞋫 𞋎𞋤𞋎𞋋𞋞𞋋𞋀𞋉𞋣 𞋊𞋗𞋁𞋂𞋀𞋓𞋜𞋉𞋣 𞋎𞋁𞋘𞋞𞋊𞋀𞋆𞋀𞋉𞋣 𞋊𞋗𞋁𞋆𞋕𞋅𞋀𞋗𞋚𞋕 𞋚𞋜 𞋎𞋁𞋗𞋓𞋕 𞋐𞋁𞋉𞋕𞋎𞋋𞋜."
  specimen_21: "𞋉𞋁 𞋔𞋕𞋊𞋜 𞋐𞋁𞋉𞋁𞋫 𞋎𞋓𞋛𞋃𞋃𞋁𞋆𞋀 𞋉𞋜𞋅𞋗𞋁𞋚𞋜𞋋𞋞𞋝, 𞋄𞋁𞋗𞋋𞋞𞋝, 𞋉𞋜𞋏𞋔𞋀𞋎𞋁𞋆𞋜𞋋𞋞𞋝 𞋓𞋀 𞋁𞋉𞋞𞋐𞋩𞋀𞋎𞋆𞋁𞋋𞋛.\n𞋎𞋁𞋗𞋓𞋕𞋊𞋜 𞋐𞋁𞋉𞋁𞋫, 𞋎𞋓𞋤 𞋓𞋜𞋗𞋞𞋄𞋆𞋁 𞋊𞋗𞋁𞋓𞋁𞋗𞋋𞋋𞋜𞋋𞋁𞋎𞋆𞋁 𞋔𞋁𞋎𞋆𞋀𞋊𞋜 𞋀𞋊𞋁𞋗𞋀𞋄𞋜𞋔𞋀𞋔𞋏𞋛𞋊𞋁𞋎𞋆𞋁, 𞋎𞋓𞋜𞋆𞋀𞋄𞋜𞋔𞋀𞋗𞋀𞋉𞋣 𞋄𞋀𞋆𞋜𞋋𞋓𞋀𞋉𞋣 𞋃𞋁, 𞋓𞋜𞋉𞋜𞋗𞋄𞋀𞋗𞋁𞋉𞋁𞋎𞋆𞋁 𞋃𞋁 𞋔𞋗𞋞𞋋𞋛, 𞋎𞋓𞋀𞋄𞋜𞋉𞋛𞋉𞋁 𞋉𞋜𞋏𞋊𞋁𞋔𞋏𞋛𞋉𞋁 𞋃𞋁 𞋉𞋆𞋀𞋆𞋁𞋊𞋜𞋌𞋛𞋉𞋁 𞋓𞋜𞋄𞋜𞋆𞋁𞋘𞋀𞋉𞋁𞋎𞋆𞋁 𞋎𞋁𞋘𞋞𞋃𞋜𞋋𞋁𞋎𞋆𞋁 𞋎𞋀𞋗𞋓𞋁𞋐𞋁𞋉𞋜𞋔𞋁𞋎𞋆𞋁 𞋏𞋗𞋁𞋓𞋁𞋉𞋁𞋎𞋆𞋁 𞋃𞋁 𞋔𞋗𞋞𞋋𞋛 𞋎𞋁𞋗𞋓𞋕𞋊𞋜 𞋐𞋁𞋉𞋁𞋫 𞋊𞋞𞋗𞋉𞋣 𞋎𞋁𞋘𞋀𞋉𞋁𞋋𞋣 𞋄𞋀𞋗𞋁𞋆𞋁𞋋𞋜."
  specimen_16: "𞋉𞋁 𞋔𞋁𞋎𞋆𞋀𞋊𞋜 𞋓𞋆𞋁𞋔𞋋𞋜𞋅𞋁𞋋𞋛 𞋊𞋀𞋗𞋜𞋓𞋀𞋗𞋜𞋔𞋛 𞋃𞋁 𞋐𞋜𞋓𞋁𞋉𞋛, 𞋅𞋗𞋞𞋚𞋛, 𞋊𞋁𞋡𞋁𞋓𞋆𞋁𞋓𞋁𞋚𞋀𞋗𞋛 𞋃𞋁 𞋎𞋓𞋛𞋃𞋃𞋁𞋆𞋀 𞋚𞋁𞋎𞋋𞋁𞋔𞋏𞋛𞋊𞋕𞋉𞋞𞋐𞋩𞋀𞋎𞋆𞋁𞋋𞋛, 𞋉𞋁 𞋓𞋀 𞋔𞋁𞋎𞋆𞋀𞋊𞋜 𞋙𞋆𞋀𞋋𞋥 𞋎𞋁𞋘𞋘𞋀𞋉𞋤 𞋓𞋀𞋔𞋗𞋀𞋉𞋋𞋞𞋝 𞋔𞋕𞋊𞋜 𞋏𞋁𞋔𞋏𞋆𞋁𞋋𞋜. 𞋛𞋋𞋀𞋚𞋁𞋔𞋚𞋁𞋎𞋋𞋁𞋔𞋏𞋛𞋊𞋀𞋔𞋗𞋁𞋘𞋁𞋉𞋀𞋉𞋜 𞋓𞋜𞋗𞋞𞋄𞋆𞋁 𞋊𞋗𞋁𞋋𞋆𞋛𞋔𞋁𞋘𞋁𞋊𞋜𞋐𞋁𞋉𞋁𞋫 𞋓𞋜𞋄𞋜𞋎𞋤𞋗𞋁𞋔𞋏𞋁𞋉𞋤 𞋎𞋤𞋄𞋁𞋋𞋋𞋛.\n𞋊𞋗𞋁𞋋𞋆𞋛𞋔𞋁𞋘𞋁𞋊𞋜 𞋓𞋜𞋃𞋀𞋗𞋀𞋉𞋣 𞋃𞋛𞋋𞋁𞋉𞋀𞋆𞋀𞋫 𞋄𞋁𞋗𞋘𞋁𞋎𞋆𞋁 𞋃𞋁𞋎𞋓𞋀𞋋𞋁𞋉𞋡𞋆𞋀𞋄𞋜𞋔𞋀𞋗𞋤 𞋎𞋤𞋄𞋁𞋋𞋋𞋛. 𞋁𞋎𞋘𞋜𞋉 𞋁𞋄𞋜𞋔𞋀𞋗𞋛, 𞋎𞋓𞋜𞋆𞋤 𞋄𞋁𞋗𞋘𞋤 𞋓𞋜𞋏𞋓𞋀𞋎𞋤 𞋓𞋀 𞋏𞋜𞋔𞋏𞋁𞋆𞋜𞋋𞋞𞋝 𞋁𞋂𞋆𞋁𞋎𞋋𞋞𞋝 𞋁𞋗𞋃𞋜𞋋𞋞𞋝 𞋊𞋁𞋗𞋜𞋊𞋀𞋈𞋁𞋆𞋜𞋋𞋞𞋝 𞋓𞋀, 𞋓𞋀𞋜𞋆𞋁𞋔𞋋𞋜𞋔𞋛 𞋎𞋀𞋘𞋀𞋐𞋜𞋔𞋛 𞋃𞋁 𞋐𞋜𞋓𞋁𞋉𞋛, 𞋁𞋉𞋆𞋀𞋜𞋏𞋃𞋁 𞋎𞋁𞋚𞋁 𞋎𞋀𞋘𞋞𞋄𞋀𞋆𞋜𞋔𞋁𞋐𞋜𞋓𞋁𞋉𞋛 𞋛𞋔𞋀𞋔𞋜𞋉𞋀 𞋓𞋀 𞋎𞋓𞋜𞋆𞋤 𞋄𞋁𞋗𞋘𞋤 𞋓𞋜𞋏𞋓𞋀𞋎𞋤𞋎𞋓𞋀𞋋𞋁𞋉𞋡𞋆𞋤 𞋃𞋁 𞋊𞋁𞋗𞋜𞋓𞋁𞋗𞋋𞋁𞋆𞋜𞋋𞋞𞋘𞋁𞋊𞋜 𞋊𞋗𞋁𞋋𞋆𞋛𞋔𞋤 𞋐𞋁𞋉𞋁𞋫 𞋎𞋓𞋀𞋋𞋁𞋉𞋡𞋆𞋤 𞋄𞋀𞋗𞋁𞋆𞋁𞋋𞋜.\n𞋔𞋀𞋗𞋆𞋁𞋚𞋕𞋗𞋀𞋉𞋣 𞋎𞋁𞋘𞋞𞋃𞋜𞋋𞋁𞋉𞋜𞋆𞋁𞋘𞋁𞋉𞋁𞋊𞋞𞋗𞋁𞋎𞋎𞋁𞋗𞋁𞋘, 𞋎𞋁𞋓𞋛𞋋𞋁𞋉𞋤 𞋃𞋁 𞋉𞋜𞋆𞋁𞋋𞋀𞋓𞋁𞋄𞋜𞋔𞋀𞋓𞋁𞋔𞋀𞋏𞋛𞋉𞋁 𞋎𞋁𞋚𞋁 𞋓𞋜𞋏𞋗𞋁𞋘𞋀𞋄𞋜𞋔𞋀𞋗𞋁𞋫 𞋊𞋗𞋁𞋋𞋆𞋁𞋔𞋁𞋎𞋘𞋀𞋜 𞋊𞋗𞋁𞋄𞋛𞋆𞋕𞋎𞋋𞋜."
}
historical: true
