id: "saq"
language: "saq"
script: "Latn"
name: "Samburu"
autonym: "Sampur"
population: 246228
region: "KE"
exemplar_chars {
  base: "a b c d e g h i j k l m n o p r s t u v w y"
  auxiliary: "f q x z"
  index: "A B C D E G H I J K L M N O P R S T U V W Y"
}
sample_text {
  fallback_language: "en"
}
