id: "sat_Deva"
language: "sat"
script: "Deva"
name: "Santali, Devanagari"
population: 0
region: "NP"
sample_text {
  masthead_full: "जतलक"
  masthead_partial: "नम"
  styles: "जत लेकान मोन आर अधिकार रेयाक आधार रे मुचोत धाबिच स्वतन्त्र"
  tester: "जत लेकान मोन आर अधिकार रेयाक आधार रे मुचोत धाबिच स्वतन्त्र आर सुमान को हुयुकआ। उनको"
  poster_sm: "जत लेकान मोन आर"
  poster_md: "जत लेकान"
  poster_lg: "लेकान"
  specimen_48: "जत लेकान मोन आर अधिकार रेयाक आधार रे मुचोत धाबिच स्वतन्त्र आर सुमान को"
  specimen_36: "जत लेकान मोन आर अधिकार रेयाक आधार रे मुचोत धाबिच स्वतन्त्र आर सुमान को हुयुकआ। उनको हो बुद्धि आर बुझहौ को आगु तोरा बाका दानेच आर मिक हड आर दोसार हड र आप्नार रेयाक व्यवहार हुयुक जोरुडा।"
  specimen_32: "जत लेकान मोन आर अधिकार रेयाक आधार रे मुचोत धाबिच स्वतन्त्र आर सुमान को हुयुकआ। उनको हो बुद्धि आर बुझहौ को आगु तोरा बाका दानेच आर मिक हड आर दोसार हड र आप्नार रेयाक व्यवहार हुयुक जोरुडा।"
  specimen_21: "जत लेकान मोन आर अधिकार रेयाक आधार रे मुचोत धाबिच स्वतन्त्र आर सुमान को हुयुकआ। उनको हो बुद्धि आर बुझहौ को आगु तोरा बाका दानेच आर मिक हड आर दोसार हड र आप्नार रेयाक व्यवहार हुयुक जोरुडा।\nजत लेकान मोन आर अधिकार रेयाक आधार रे मुचोत धाबिच स्वतन्त्र आर सुमान को हुयुकआ। उनको हो बुद्धि आर बुझहौ को आगु तोरा बाका दानेच आर मिक हड आर दोसार हड र आप्नार रेयाक व्यवहार हुयुक जोरुडा।\nजत लेकान मोन आर अधिकार रेयाक आधार रे मुचोत धाबिच स्वतन्त्र आर सुमान को हुयुकआ। उनको हो बुद्धि आर बुझहौ को आगु तोरा बाका दानेच आर मिक हड आर दोसार हड र आप्नार रेयाक व्यवहार हुयुक जोरुडा।"
  specimen_16: "जत लेकान मोन आर अधिकार रेयाक आधार रे मुचोत धाबिच स्वतन्त्र आर सुमान को हुयुकआ। उनको हो बुद्धि आर बुझहौ को आगु तोरा बाका दानेच आर मिक हड आर दोसार हड र आप्नार रेयाक व्यवहार हुयुक जोरुडा।\nजत लेकान मोन आर अधिकार रेयाक आधार रे मुचोत धाबिच स्वतन्त्र आर सुमान को हुयुकआ। उनको हो बुद्धि आर बुझहौ को आगु तोरा बाका दानेच आर मिक हड आर दोसार हड र आप्नार रेयाक व्यवहार हुयुक जोरुडा।\nजत लेकान मोन आर अधिकार रेयाक आधार रे मुचोत धाबिच स्वतन्त्र आर सुमान को हुयुकआ। उनको हो बुद्धि आर बुझहौ को आगु तोरा बाका दानेच आर मिक हड आर दोसार हड र आप्नार रेयाक व्यवहार हुयुक जोरुडा।\nजत लेकान मोन आर अधिकार रेयाक आधार रे मुचोत धाबिच स्वतन्त्र आर सुमान को हुयुकआ। उनको हो बुद्धि आर बुझहौ को आगु तोरा बाका दानेच आर मिक हड आर दोसार हड र आप्नार रेयाक व्यवहार हुयुक जोरुडा।\nजत लेकान मोन आर अधिकार रेयाक आधार रे मुचोत धाबिच स्वतन्त्र आर सुमान को हुयुकआ। उनको हो बुद्धि आर बुझहौ को आगु तोरा बाका दानेच आर मिक हड आर दोसार हड र आप्नार रेयाक व्यवहार हुयुक जोरुडा।"
}
historical: true
