id: "sat_Deva"
language: "sat"
script: "Deva"
name: "Santali, Devanagari"
population: 0
region: "BT"
region: "FJ"
region: "IN"
region: "MU"
region: "NP"
region: "PK"
region: "UG"
region: "ZA"
sample_text {
  masthead_full: "जतलक"
  masthead_partial: "नम"
  styles: "ज\nत\n \nल\nे\nक\nा\nन\n \nम\nो\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\n "
  tester: "ज\nत\n \nल\nे\nक\nा\nन\n \nम\nो\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\n \nर\nे\nय\nा\nक\n \nआ\nध\nा\nर\n \nर"
  poster_sm: "ज\nत\n \nल\nे\nक"
  poster_md: "ज\nत\n \nल\nे"
  poster_lg: "ज\nत"
  specimen_48: "ज\nत\n \nल\nे\nक\nा\nन\n \nम\nो\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\n \nर\nे\nय\nा\nक\n \nआ\nध\nा\nर\n \nर"
  specimen_36: "ज\nत\n \nल\nे\nक\nा\nन\n \nम\nो\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\n \nर\nे\nय\nा\nक\n \nआ\nध\nा\nर\n \nर\nे\n \nम\nु\nच\nो\nत\n \nध\nा\nब\nि\nच\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n "
  specimen_32: "ज\nत\n \nल\nे\nक\nा\nन\n \nम\nो\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\n \nर\nे\nय\nा\nक\n \nआ\nध\nा\nर\n \nर\nे\n \nम\nु\nच\nो\nत\n \nध\nा\nब\nि\nच\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nआ\nर\n \nस\nु\nम\nा\nन\n \nक\nो\n \nह\nु\nय\nु\nक\nआ\n।\n \nउ\nन\nक"
  specimen_21: "ज\nत\n \nल\nे\nक\nा\nन\n \nम\nो\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\n \nर\nे\nय\nा\nक\n \nआ\nध\nा\nर\n \nर\nे\n \nम\nु\nच\nो\nत\n \nध\nा\nब\nि\nच\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nआ\nर\n \nस\nु\nम\nा\nन\n \nक\nो\n \nह\nु\nय\nु\nक\nआ\n।\n \nउ\nन\nक\nो\n \nह\nो\n \nब\nु\nद\n्\nध\nि\n \nआ\nर\n \nब\nु\nझ\nह\nौ\n \nक\nो\n \nआ\nग\nु\n \nत\nो\nर\nा\n \nब\nा\nक\nा\n \nद\nा\nन\nे\nच\n \nआ\nर\n \nम\nि\nक\n \nह\nड\n \nआ\nर\n \nद\nो\nस\nा\nर\n \nह\nड\n \nर\n \nआ\nप\n्\nन\nा\nर\n \nर\nे\nय\nा\nक\n \nव\n्\nय\nव\nह\nा\nर\n \nह\nु\nय"
  specimen_16: "ज\nत\n \nल\nे\nक\nा\nन\n \nम\nो\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\n \nर\nे\nय\nा\nक\n \nआ\nध\nा\nर\n \nर\nे\n \nम\nु\nच\nो\nत\n \nध\nा\nब\nि\nच\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nआ\nर\n \nस\nु\nम\nा\nन\n \nक\nो\n \nह\nु\nय\nु\nक\nआ\n।\n \nउ\nन\nक\nो\n \nह\nो\n \nब\nु\nद\n्\nध\nि\n \nआ\nर\n \nब\nु\nझ\nह\nौ\n \nक\nो\n \nआ\nग\nु\n \nत\nो\nर\nा\n \nब\nा\nक\nा\n \nद\nा\nन\nे\nच\n \nआ\nर\n \nम\nि\nक\n \nह\nड\n \nआ\nर\n \nद\nो\nस\nा\nर\n \nह\nड\n \nर\n \nआ\nप\n्\nन\nा\nर\n \nर\nे\nय\nा\nक\n \nव\n्\nय\nव\nह\nा\nर\n \nह\nु\nय\nु\nक\n \nज\nो\nर\nु\nड\nा\n।\nज\nत\n \nल\nे\nक\nा\nन\n \nम\nो\nन\n \nआ\nर\n \nअ\nध\nि\nक\nा\nर\n \nर\nे\nय\nा\nक\n \nआ\nध\nा\nर\n \nर\nे\n \nम\nु\nच\nो\nत\n \nध\nा\nब\nि\nच\n \nस\n्\nव\nत\nन\n्\nत\n्\nर\n \nआ\nर\n \nस\nु\nम\nा\nन\n \nक\nो\n \nह\nु\nय\nु\nक\nआ\n।\n \nउ\nन\nक\nो\n \nह\nो\n \nब\nु\nद\n्\nध\nि\n \nआ\nर\n \nब\nु\nझ\nह\nौ\n \nक\nो\n \nआ\nग\nु\n \nत\nो\nर\nा\n \nब\nा\nक\nा\n \nद\nा\nन\nे\nच\n \nआ\nर\n \nम\nि\nक\n \nह\nड\n \nआ"
}
historical: true
