id: "sbp"
language: "sbp"
script: "Latn"
name: "Sangu"
autonym: "Shisango"
population: 117105
region: "TZ"
exemplar_chars {
  base: "a b c d e f g h i j k l m n o p s t u v w y"
  auxiliary: "q r x z"
  marks: "◌̀ ◌́ ◌̂ ◌̈"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B C D E F G H I J K L M N O P S T U V W Y"
}
sample_text {
  fallback_language: "en"
}
