id: "scn_Latn"
language: "scn"
script: "Latn"
name: "Sicilian"
autonym: "Sicilianu"
population: 511702
region: "IT"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z À Â È Ì Ò Ù a b c d e f g h i j k l m n o p q r s t u v w x y z à â è ì ò ù"
  marks: "◌̀ ◌̂"
}
sample_text {
  masthead_full: "TtUu"
  masthead_partial: "Ii"
  styles: "Tutti i cristiàni nàsciunu libberi e ntâ"
  tester: "Tutti i cristiàni nàsciunu libberi e ntâ stessa manèra ill\'authri"
  poster_sm: "Tutti i cristiàni"
  poster_md: "Tutti"
  poster_lg: "Tutti"
  specimen_48: "Tutti i cristiàni nàsciunu libberi e ntâ stessa manèra"
  specimen_36: "Tutti i cristiàni nàsciunu libberi e ntâ stessa manèra ill\'authri pi dignità e diritti. Iddhi ndànnu ognunu u so ciriveddhu mi \'rraggiùnunu e \'ndannu mi càmpunu unu cull\'authru comu mi sùnnu fràti râ stessa matri."
  specimen_32: "Tutti i cristiàni nàsciunu libberi e ntâ stessa manèra ill\'authri pi dignità e diritti. Iddhi ndànnu ognunu u so ciriveddhu mi \'rraggiùnunu e \'ndannu mi càmpunu unu cull\'authru comu mi sùnnu fràti râ stessa matri."
  specimen_21: "Tutti i cristiàni nàsciunu libberi e ntâ stessa manèra ill\'authri pi dignità e diritti. Iddhi ndànnu ognunu u so ciriveddhu mi \'rraggiùnunu e \'ndannu mi càmpunu unu cull\'authru comu mi sùnnu fràti râ stessa matri.\nTutti i cristiàni nàsciunu libberi e ntâ stessa manèra ill\'authri pi dignità e diritti. Iddhi ndànnu ognunu u so ciriveddhu mi \'rraggiùnunu e \'ndannu mi càmpunu unu cull\'authru comu mi sùnnu fràti râ stessa matri."
  specimen_16: "Tutti i cristiàni nàsciunu libberi e ntâ stessa manèra ill\'authri pi dignità e diritti. Iddhi ndànnu ognunu u so ciriveddhu mi \'rraggiùnunu e \'ndannu mi càmpunu unu cull\'authru comu mi sùnnu fràti râ stessa matri.\nTutti i cristiàni nàsciunu libberi e ntâ stessa manèra ill\'authri pi dignità e diritti. Iddhi ndànnu ognunu u so ciriveddhu mi \'rraggiùnunu e \'ndannu mi càmpunu unu cull\'authru comu mi sùnnu fràti râ stessa matri.\nTutti i cristiàni nàsciunu libberi e ntâ stessa manèra ill\'authri pi dignità e diritti. Iddhi ndànnu ognunu u so ciriveddhu mi \'rraggiùnunu e \'ndannu mi càmpunu unu cull\'authru comu mi sùnnu fràti râ stessa matri."
}
