id: "sd"
language: "sd"
script: "Arab"
name: "Sindhi"
population: 31467954
region: "IN"
region: "PK"
exemplar_chars {
  base: "ء آ ا ب ٻ پ ڀ ت ث ٺ ٽ ٿ ج {جھ} ڃ ڄ چ ڇ ح خ د ذ ڊ ڌ ڍ ڏ ر ز ڙ س ش ص ض ط ظ ع غ ف ڦ ق ک ڪ گ {گھ} ڱ ڳ ل م ن ڻ ه ھ و ي {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ}"
  auxiliary: "َ ُ ِ ئ"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "⹁ ⁏ : ! ۔ ‘ ( ) [ ] { } / { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "ا ب ٻ پ ڀ ت ث ٺ ٽ ٿ ج {جھ} ڃ ڄ چ ڇ ح خ د ذ ڊ ڌ ڍ ڏ ر ز ڙ س ش ص ض ط ظ ع غ ف ڦ ق ک ڪ گ {گھ} ڱ ڳ ل م ن ڻ ه ھ و ي {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ} {جھ} {گھ}"
}
sample_text {
  fallback_language: "ar"
}
