id: "sdc"
language: "sdc"
script: "Latn"
name: "Sassarese Sardinian"
autonym: "Sardu"
population: 106084
region: "IT"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z À Ç È Ì Ò Ù a b c d e f g h i j k l m n o p q r s t u v w x y z à ç è ì ò ù"
  marks: "◌̀ ◌̧"
}
sample_text {
  fallback_language: "en"
}
