id: "seh"
language: "seh"
script: "Latn"
name: "Sena"
autonym: "Cisena"
population: 1384517
region: "MZ"
exemplar_chars {
  base: "a á à â ã b c ç d e é ê f g h i í j k l m n o ó ò ô õ p q r s t u ú v w x y z"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
}
sample_text {
  fallback_language: "en"
}
