id: "shi_Latn"
language: "shi"
script: "Latn"
name: "Tachelhit (Latin)"
autonym: "Tachelhit"
population: 3093867
region: "MA"
exemplar_chars {
  base: "a b c d ḍ e ɛ f g {gʷ} ɣ h ḥ i j k {kʷ} l m n q r ṛ s ṣ t ṭ u w x y z {gʷ} {kʷ} {gʷ} {kʷ} {gʷ} {kʷ} {gʷ} {kʷ} {gʷ} {kʷ} {gʷ} {kʷ} {gʷ} {kʷ} {gʷ} {kʷ} {gʷ} {kʷ} {gʷ} {kʷ} {gʷ} {kʷ} {gʷ} {kʷ} {gʷ} {kʷ} {gʷ} {kʷ} {gʷ} {kʷ}"
  auxiliary: "o p v"
  marks: "◌̌ ◌̣"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B C D Ḍ E Ɛ F G {Gʷ} Ɣ H Ḥ I J K {Kʷ} L M N Q R Ṛ S Ṣ T Ṭ U W X Y Z {Gʷ} {Kʷ} {Gʷ} {Kʷ} {Gʷ} {Kʷ} {Gʷ} {Kʷ} {Gʷ} {Kʷ} {Gʷ} {Kʷ} {Gʷ} {Kʷ} {Gʷ} {Kʷ} {Gʷ} {Kʷ} {Gʷ} {Kʷ} {Gʷ} {Kʷ} {Gʷ} {Kʷ} {Gʷ} {Kʷ} {Gʷ} {Kʷ} {Gʷ} {Kʷ}"
}
sample_text {
  fallback_language: "en"
}
