id: "shk_Latn"
language: "shk"
script: "Latn"
name: "Shilluk"
sample_text {
  masthead_full: "DdHh"
  masthead_partial: "Aa"
  styles: "D\nh\na\nn\nh\nø\n \nb\në\nn\ne\n \nb\na\n \na\nn\ny\nw\nø\nl"
  tester: "D\nh\na\nn\nh\nø\n \nb\në\nn\ne\n \nb\na\n \na\nn\ny\nw\nø\nl\nø\n \ne\n \np\na\nt\nh\n \nk"
  poster_sm: "D\nh\na\nn\nh\nø"
  poster_md: "D\nh\na\nn\nh"
  poster_lg: "D\nh"
  specimen_48: "D\nh\na\nn\nh\nø\n \nb\në\nn\ne\n \nb\na\n \na\nn\ny\nw\nø\nl\nø\n \ne\n \np\na\nt\nh\n \nk"
  specimen_36: "D\nh\na\nn\nh\nø\n \nb\në\nn\ne\n \nb\na\n \na\nn\ny\nw\nø\nl\nø\n \ne\n \np\na\nt\nh\n \nk\ni\n \nb\nä\nn\ng\n,\n \ng\ne\n \np\nä\nr\n \nk\ni\n \ny\ni"
  specimen_32: "D\nh\na\nn\nh\nø\n \nb\në\nn\ne\n \nb\na\n \na\nn\ny\nw\nø\nl\nø\n \ne\n \np\na\nt\nh\n \nk\ni\n \nb\nä\nn\ng\n,\n \ng\ne\n \np\nä\nr\n \nk\ni\n \ny\ni\nj\n \nb\në\në\nd\nø\n \ng\ne\nk\ni\n \nd\ny\në\nr\nø\n.\n \ng"
  specimen_21: "D\nh\na\nn\nh\nø\n \nb\në\nn\ne\n \nb\na\n \na\nn\ny\nw\nø\nl\nø\n \ne\n \np\na\nt\nh\n \nk\ni\n \nb\nä\nn\ng\n,\n \ng\ne\n \np\nä\nr\n \nk\ni\n \ny\ni\nj\n \nb\në\në\nd\nø\n \ng\ne\nk\ni\n \nd\ny\në\nr\nø\n.\n \ng\nï\nn\n-\na\n \nd\nw\na\nd\nd\ni\n \nk\ni\np\ne\nr\n \ng\ne\nn\n \ny\nï\n \ng\ne\nn\n \nd\na\n \nr\nu\nm\ni\n \nk\ni\n \nb\në\në\nd\nø\n \nm\nø\n \ng\nö\nö\ng\n \ng\ne\nn\n \nk\ni\n \np\ny\në\nw\n \na\nk\ny\ne\nl\n \ng\na\n \nn\ny\ni\nm\në"
  specimen_16: "D\nh\na\nn\nh\nø\n \nb\në\nn\ne\n \nb\na\n \na\nn\ny\nw\nø\nl\nø\n \ne\n \np\na\nt\nh\n \nk\ni\n \nb\nä\nn\ng\n,\n \ng\ne\n \np\nä\nr\n \nk\ni\n \ny\ni\nj\n \nb\në\në\nd\nø\n \ng\ne\nk\ni\n \nd\ny\në\nr\nø\n.\n \ng\nï\nn\n-\na\n \nd\nw\na\nd\nd\ni\n \nk\ni\np\ne\nr\n \ng\ne\nn\n \ny\nï\n \ng\ne\nn\n \nd\na\n \nr\nu\nm\ni\n \nk\ni\n \nb\në\në\nd\nø\n \nm\nø\n \ng\nö\nö\ng\n \ng\ne\nn\n \nk\ni\n \np\ny\në\nw\n \na\nk\ny\ne\nl\n \ng\na\n \nn\ny\ni\nm\në\ng\ng\n.\nD\nh\na\nn\nh\nø\n \nb\në\nn\ne\n \nb\na\n \na\nn\ny\nw\nø\nl\nø\n \ne\n \np\na\nt\nh\n \nk\ni\n \nb\nä\nn\ng\n,\n \ng\ne\n \np\nä\nr\n \nk\ni\n \ny\ni\nj\n \nb\në\në\nd\nø\n \ng\ne\nk\ni\n \nd\ny\në\nr\nø\n.\n \ng\nï\nn\n-\na\n \nd\nw\na\nd\nd\ni\n \nk\ni\np\ne\nr\n \ng\ne\nn\n \ny\nï\n \ng\ne\nn\n \nd\na\n \nr\nu\nm\ni\n \nk\ni\n \nb\në\në\nd\nø\n \nm\nø\n \ng\nö\nö"
}
