id: "si"
language: "si"
script: "Sinh"
name: "Sinhala"
autonym: "සිංහල"
population: 15564656
region: "LK"
exemplar_chars {
  base: "අ ආ ඇ ඈ ඉ ඊ උ ඌ ඍ එ ඒ ඓ ඔ ඕ ඖ ං ඃ ක ඛ ග ඝ ඞ ඟ ච ඡ ජ ඣ ඥ ඤ ට ඨ ඩ ඪ ණ ඬ ත ථ ද ධ න ඳ ප ඵ බ භ ම ඹ ය ර ල ව ශ ෂ ස හ ළ ෆ ා ැ ෑ ි ී ු ූ ෘ ෲ ෟ ෙ ේ ෛ ො ෝ ෞ ්"
  auxiliary: "​‌‍ ඎ ඏ ඐ ඦ ෳ"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ \" “ ” ( ) [ ] § @ * / & # † ‡ ′ ″"
  index: "අ ආ ඇ ඈ ඉ ඊ උ ඌ ඍ එ ඒ ඓ ඔ ඕ ඖ ක ඛ ග ඝ ඞ ඟ ච ඡ ජ ඣ ඥ ඤ ට ඨ ඩ ඪ ණ ඬ ත ථ ද ධ න ඳ ප ඵ බ භ ම ඹ ය ර ල ව ශ ෂ ස හ ළ ෆ"
}
sample_text {
  masthead_full: "සයලම"
  masthead_partial: "නෂ"
  styles: "ලෝකයේ පවත්නා නිදහස, යුක්තිය සහ සාමය යන්නෙහි පදනම මිනිස් පවුලේ"
  tester: "මානව අයිතිවාසිකම් නොතැකීම හා අවඥාවට ලක්කිරීමේ ප්‍රතිඵලයක් වශයෙන් මිනිස් වර්ගයාගේ හෘදය සාක්ෂිය"
  poster_sm: "දුෂ්ඨ පාලකයන්ට"
  poster_md: "ජාතීන් අතර මිත්‍ර"
  poster_lg: "සියලු"
  specimen_48: "මූලික මානව අයිතිවාසිකම් කෙරෙහිත්, මිනිසාගේ ගරුත්වය හා අගය කෙරෙහිත්, ස්ත්‍රී පුරුෂ දෙපක්ෂයේ සමාන"
  specimen_36: "මානව අයිතිවාසිකම් හා මූලික ස්වාධීනත්වයන් කෙරෙහි විශ්ව ගරුත්වයත්, ඒවා රැක දීමත් එක්සත් ජාතීන්ගේ සංවිධානයේ සහයෝගිත්වයෙන් වර්ධනය කිරීමට සාමාජික රාජ්‍ය ප්‍රතිඥා දී ඇති හෙයින් ද,"
  specimen_32: "ජාති, වංශ, වර්ණ, ස්ත්‍රී පුරුෂ භාවය, භාෂාව, ආගම්, දේශපාලන ආදී කවර බේදයක් හෝ සමාජ, ජාතික, දේපළ, උපත ආදී කවර තත්ත්වයක විශේෂයක් හෝ නොමැතිව මේ ප්‍රකාශනයේ සඳහන් සියලු හිමිකම්වලට හා ස්වාධීනත්වයන්ට සෑම පුද්ගලයකුම උරුම වන්නේය."
  specimen_21: "තවද යම් පුද්ගලයකු අයත්වන රටේ දේශපාලන, නීතිමය හෝ ජාත්‍යන්තර තත්ත්වයන් පිළිබඳ කිසිදු විශේෂයක් ද ඒ රටේ ස්වාධීන, භාරකාර, අස්වාධීන ආදී කවර තත්ත්වයක් පිළිබඳ විශේෂයක් ද නොමැතිව මේ හිමිකම් ඔහු සතු වන්නේය.\nසෑම පුද්ගලයෙකුටම ජීවත්වීමටත් නිදහස්ව සිතීමටත් පෞද්ගලික ආරක්ෂාවටත් හිමිකම් ඇත්තේය.\nකිසිම පුද්ගලයෙකු වහල් කමෙහි හෝ බන්ධනයෙහි (දාසත්වයෙහි) නොරැඳවිය යුතුය. සෑම ආකාරයකම වහල් වෙළඳාම හා වහල්කම තහනම් වන්නේය.\nකිසිම පුද්ගලයකු වධ හිංසාවට හෝ කෲර, අමානුෂික පහත් සැළකිල්ලකට හෝ දඬුවමකට හෝ භාජනය නොකළ යුතුය."
  specimen_16: "සෑම අවස්ථාවකදී ම නීතිය ඉදිරියේ පුද්ගලයකු වශයෙන් පිළිගනු ලැබීමේ අයිතිය සෑම කෙනෙකුම සතුය.\nසියල්ලන්ම නීතිය ඉදිරියෙහි එකිනෙකාට සමාන වන අතර, නීතීයේ ආරක්ෂාව ලැබීමට කිසිදු විශේෂයක් නොමැතිව, සියල්ලෝම හිමිකම් ලබති, මේ ප්‍රකාශනයට පටහැනි ලෙස කෙරෙන ඕනෑම අසාධාරණයකින් ආරක්ෂා වීමේ අයිතියත් එබඳු අසාධාරණයන්ට පෙළඹවීමෙන් ආරක්ෂාවීමේ අයිතියත් සියල්ලන්ටම හිමි වේ.\nආණ්ඩුක්‍රම ව්‍යවස්ථාවලින් හෝ නීතියෙන් හෝ ප්‍රදානය වී ඇති මූලික මිනිස් අයිතිවාසිකම් උල්ලංඝනය කිරීමකදී බලධාරී ජාතික අධිකරණයකින් ප්‍රතිකර්ම යොදා ගැනීමේ හිමිකම් සෑම පුද්ගලයකු සතු වේ.\nබලහත්කාරයෙන් අත් අඩංගුවට ගැනීමට හෝ අත් අඩංගුවේ රඳා තැබීමට හෝ පිටුවහල් කිරීමට හෝ කිසිම පුද්ගලයකු භාජනය නොකළ යුතුය.\nතමන්ගේ අයිතිවාසිකම් හා යුතුකම් පිළිබඳව හෝ තම්න්ට විරුද්ධව යම් අපරාධ චෝදනාවක් පිළිබඳව හෝ නිශ්චය කිරීම සඳහා සාධාරණ වූත්, විවෘත වුත්, ස්වාධීන අපක්ෂපාත නඩු විභාගයකට සෑම තැනැත්තකුම පූර්ණ සමානත්වයෙන් යුක්තව හිමිකම් ලබයි."
}
