id: "sja_Latn"
language: "sja"
script: "Latn"
name: "Epena, Latin"
sample_text {
  masthead_full: "ŨũMm"
  masthead_partial: "Aa"
  styles: "Ũ\nm\na\n \nt\na\nc\nh\ni\n \ne\np\ne\nr\na\nr\nã\n \nt\n’\no"
  tester: "Ũ\nm\na\n \nt\na\nc\nh\ni\n \ne\np\ne\nr\na\nr\nã\n \nt\n’\no\np\na\nt\na\n \na\np\ne\nn\na"
  poster_sm: "Ũ\nm\na\n \nt\na"
  poster_md: "Ũ\nm\na\n \nt"
  poster_lg: "Ũ\nm"
  specimen_48: "Ũ\nm\na\n \nt\na\nc\nh\ni\n \ne\np\ne\nr\na\nr\nã\n \nt\n’\no\np\na\nt\na\n \na\np\ne\nn\na"
  specimen_36: "Ũ\nm\na\n \nt\na\nc\nh\ni\n \ne\np\ne\nr\na\nr\nã\n \nt\n’\no\np\na\nt\na\n \na\np\ne\nn\na\na\nr\nã\n \no\nm\ne\n \na\nu\nk\n’\na\n \nt\na\nc\nh\ni\n \nc"
  specimen_32: "Ũ\nm\na\n \nt\na\nc\nh\ni\n \ne\np\ne\nr\na\nr\nã\n \nt\n’\no\np\na\nt\na\n \na\np\ne\nn\na\na\nr\nã\n \no\nm\ne\n \na\nu\nk\n’\na\n \nt\na\nc\nh\ni\n \nc\nr\ne\ne\nn\nc\ni\na\n \no\nm\ne\n \nɨ\nc\nh\ni\na\nv\na\n "
  specimen_21: "Ũ\nm\na\n \nt\na\nc\nh\ni\n \ne\np\ne\nr\na\nr\nã\n \nt\n’\no\np\na\nt\na\n \na\np\ne\nn\na\na\nr\nã\n \no\nm\ne\n \na\nu\nk\n’\na\n \nt\na\nc\nh\ni\n \nc\nr\ne\ne\nn\nc\ni\na\n \no\nm\ne\n \nɨ\nc\nh\ni\na\nv\na\n \na\nu\nk\n’\na\n \n–\n \nk\ni\nn\nc\ni\na\n \nk\n’\na\nw\na\na\n-\n \nk\n’\no\n \np\n’\na\nn\no\nr\na\n \no\nm\ne\n \na\n \np\ne\nn\na\na\nr\nã\n \nm\na\na\n.\nŨ\nm\na\n \nt\na\nc\nh\ni\n \ne\np\ne\nr\na\nr\nã\n \nt\n’\no\np\na\nt\na\n \na\np\ne\nn\na"
  specimen_16: "Ũ\nm\na\n \nt\na\nc\nh\ni\n \ne\np\ne\nr\na\nr\nã\n \nt\n’\no\np\na\nt\na\n \na\np\ne\nn\na\na\nr\nã\n \no\nm\ne\n \na\nu\nk\n’\na\n \nt\na\nc\nh\ni\n \nc\nr\ne\ne\nn\nc\ni\na\n \no\nm\ne\n \nɨ\nc\nh\ni\na\nv\na\n \na\nu\nk\n’\na\n \n–\n \nk\ni\nn\nc\ni\na\n \nk\n’\na\nw\na\na\n-\n \nk\n’\no\n \np\n’\na\nn\no\nr\na\n \no\nm\ne\n \na\n \np\ne\nn\na\na\nr\nã\n \nm\na\na\n.\nŨ\nm\na\n \nt\na\nc\nh\ni\n \ne\np\ne\nr\na\nr\nã\n \nt\n’\no\np\na\nt\na\n \na\np\ne\nn\na\na\nr\nã\n \no\nm\ne\n \na\nu\nk\n’\na\n \nt\na\nc\nh\ni\n \nc\nr\ne\ne\nn\nc\ni\na\n \no\nm\ne\n \nɨ\nc\nh\ni\na\nv\na\n \na\nu\nk\n’\na\n \n–\n \nk\ni\nn\nc\ni\na\n \nk\n’\na\nw\na\na\n-\n \nk\n’\no\n \np\n’\na\nn\no\nr\na\n \no\nm\ne\n \na\n \np\ne\nn\na\na\nr\nã\n \nm\na\na\n.\nŨ\nm\na\n \nt\na\nc\nh\ni\n \ne\np\ne\nr\na\nr\nã\n \nt\n’\no\np\na\nt\na\n \na\np\ne\nn\na\na\nr\nã\n "
}
