id: "skr"
name: "Saraiki"
preferred_name: ""
autonym: "سرائیکی"
population: 21248591
region: "PK"
script: "Perso-Arabic"
exemplar_chars {
  base: "ا ب ٻ پ ت ٹ ث ج ڄ چ ح خ د ڊ ڈ ݙ ذ ر ڑ ز ژ س ش ص ض ط ظ ع غ ف ق ک گ ڳ ل م ن ݨ و ہ ھ ء ی ے ي"
  marks: "◌ٔ"
}
sample_text {
  masthead_full: "سارے"
  masthead_partial: "نز"
  tester: "دنیا دے سارے انسان ہکو ڄئے تے نہ مکڻ والے حقوق تے ازادیاں گھن"
  poster_sm: "اقوام متحدہ"
  poster_md: "منشور اچ"
  poster_lg: "سارے"
  specimen_48: "ایں تر یخی کار نامے دے بعد اسمبلی نے سارے شریک ملکاں تے زور ڋتاجوایں"
  specimen_36: "کیوں جو ہر انسان دی ذاتی عزت تے انساناں دے ہکو ڄئے تے نہ مکڻ وا لے حقوق کوں منڑاں دنیا وچ ازادی، انصاف تے امن دی جیاد ہے ۔"
  specimen_32: "کیوں جو ظلم تے زیادتی دے خلاف انسان کوں بغاوت تے مجبور تھیوڻ کنوں بچاوڻ کیتے ضروری ہے جو قنون دی بالاد ستی دے ذریعے انسانی حقوق دا بچئو کیتاو بڄے"
  specimen_21: "کیوں جواے ضروری ہے جو قوماں تے ملکاں دے درمیان دوستانہ تعلقات کوں ودھایا ونڄے ۔\nکیوں جور کن ملکاں نے اقوام متحدہ دے چارٹر وچ جیادی انسانی حقوق، انسانی عزت تے وقار، عزت نفس اتے مرداں تے عورتاں دے ہکو ڄئے حقوق اُتے آپڻے یقین دا اقرار کیتے اتے زیادہ ازادی دے محول وچ وسیب دی ترقی تے چنگے معیار زندگی دے ودھارے دا ارادہ ظاہر کیتے ۔"
  specimen_16: "کیوں جور کن ملکاں نے اے دی وعدہ کیتے جو اقوام متحدہ دے تعاون نال پوری دنیا وچ انسانی حقوق منویسن تے جیادی ازادیاں ڋویسن ۔\nکیوں جو انہاں و عدیاں کوں پورا کرڻ کیتے ضروری ہے جو اساں حقوق تے ازادیاں کو سمجھوں ۔\nہیں کیتے ة ۔\nجنرل اسمبلی اعلان کریندی ہے جو\nانسانی حقوق دا اے عالمی منشور ساریاں قوماں تے ملکاں کیتے این مقصد دے حصول داہکو ڄیاں معیار ہو سی تاں جو ہر بندہ تے وسیب دا ہر طبقہ ایکوں آپڻے سامڻے رکھیندے ہوے تعلیم تے تدریں دے ذریعے حقوق تے ازادیاں دا احترام پیدا کرے اتے قومی تے بین الا قوامی کار گزاری دے ذریعے رکن ملکاں تے انہاں دے ماتحت علا قیاں وچ انہاں کوں منولوڻ دیاں کوششاں کرے ۔"
}
