id: "sla_Latn"
language: "sla"
script: "Latn"
name: "Slavic languages, Latin"
sample_text {
  masthead_full: "VvЬь"
  masthead_partial: "Śś"
  styles: "V\nь\nś\ni\n \nľ\nu\nd\nь\nj\ne\n \nr\no\nd\nę\nt\nь\n \ns\nę"
  tester: "V\nь\nś\ni\n \nľ\nu\nd\nь\nj\ne\n \nr\no\nd\nę\nt\nь\n \ns\nę\n \ns\nv\no\nb\no\nd\nь\nn\ni"
  poster_sm: "V\nь\nś\ni\n \nľ"
  poster_md: "V\nь\nś\ni\n "
  poster_lg: "V\nь"
  specimen_48: "V\nь\nś\ni\n \nľ\nu\nd\nь\nj\ne\n \nr\no\nd\nę\nt\nь\n \ns\nę\n \ns\nv\no\nb\no\nd\nь\nn\ni"
  specimen_36: "V\nь\nś\ni\n \nľ\nu\nd\nь\nj\ne\n \nr\no\nd\nę\nt\nь\n \ns\nę\n \ns\nv\no\nb\no\nd\nь\nn\ni\n \ni\n \no\nr\nv\nь\nn\ni\n \nv\nъ\n \nd\no\ns\nt\no\nj\nь"
  specimen_32: "V\nь\nś\ni\n \nľ\nu\nd\nь\nj\ne\n \nr\no\nd\nę\nt\nь\n \ns\nę\n \ns\nv\no\nb\no\nd\nь\nn\ni\n \ni\n \no\nr\nv\nь\nn\ni\n \nv\nъ\n \nd\no\ns\nt\no\nj\nь\nn\nь\ns\nt\nv\ně\n \ni\n \nz\na\nk\no\nn\ně\n.\n \nO\nn\ni"
  specimen_21: "V\nь\nś\ni\n \nľ\nu\nd\nь\nj\ne\n \nr\no\nd\nę\nt\nь\n \ns\nę\n \ns\nv\no\nb\no\nd\nь\nn\ni\n \ni\n \no\nr\nv\nь\nn\ni\n \nv\nъ\n \nd\no\ns\nt\no\nj\nь\nn\nь\ns\nt\nv\ně\n \ni\n \nz\na\nk\no\nn\ně\n.\n \nO\nn\ni\n \ns\nǫ\nt\nь\n \no\nd\na\nř\ne\nn\ni\n \no\nr\nz\nu\nm\no\nm\nь\n \ni\n \ns\nъ\nv\ně\ns\nt\nь\nj\nǫ\n \ni\n \nd\nъ\nl\nž\nь\nn\ni\n \nv\ne\ns\nt\ni\n \ns\nę\n \nd\nr\nu\ng\nъ\n \nk\nъ\n \nd\nr\nu\ng\nu\n \nv\nъ\n \nd\nu\nś\ně\n \nb\nr\na"
  specimen_16: "V\nь\nś\ni\n \nľ\nu\nd\nь\nj\ne\n \nr\no\nd\nę\nt\nь\n \ns\nę\n \ns\nv\no\nb\no\nd\nь\nn\ni\n \ni\n \no\nr\nv\nь\nn\ni\n \nv\nъ\n \nd\no\ns\nt\no\nj\nь\nn\nь\ns\nt\nv\ně\n \ni\n \nz\na\nk\no\nn\ně\n.\n \nO\nn\ni\n \ns\nǫ\nt\nь\n \no\nd\na\nř\ne\nn\ni\n \no\nr\nz\nu\nm\no\nm\nь\n \ni\n \ns\nъ\nv\ně\ns\nt\nь\nj\nǫ\n \ni\n \nd\nъ\nl\nž\nь\nn\ni\n \nv\ne\ns\nt\ni\n \ns\nę\n \nd\nr\nu\ng\nъ\n \nk\nъ\n \nd\nr\nu\ng\nu\n \nv\nъ\n \nd\nu\nś\ně\n \nb\nr\na\nt\nr\nь\ns\nt\nv\na\n.\nV\nь\nś\ni\n \nľ\nu\nd\nь\nj\ne\n \nr\no\nd\nę\nt\nь\n \ns\nę\n \ns\nv\no\nb\no\nd\nь\nn\ni\n \ni\n \no\nr\nv\nь\nn\ni\n \nv\nъ\n \nd\no\ns\nt\no\nj\nь\nn\nь\ns\nt\nv\ně\n \ni\n \nz\na\nk\no\nn\ně\n.\n \nO\nn\ni\n \ns\nǫ\nt\nь\n \no\nd\na\nř\ne\nn\ni\n \no\nr\nz\nu\nm\no\nm\nь\n \ni\n \ns\nъ\nv\ně\ns\nt\nь\nj\nǫ\n \ni\n \nd\nъ\nl\nž\nь\nn\ni\n \nv\ne"
}
