id: "slr_Latn"
language: "slr"
script: "Latn"
name: "Salar"
sample_text {
  masthead_full: "HhEe"
  masthead_partial: "Mm"
  styles: "H\ne\nm\ne\n \nk\ni\ns\nh\nl\ne\nr\n \nh\nü\nr\n \nd\ne\nr\n,"
  tester: "H\ne\nm\ne\n \nk\ni\ns\nh\nl\ne\nr\n \nh\nü\nr\n \nd\ne\nr\n,\n \nh\na\ny\ns\ni\ny\ne\nt\n "
  poster_sm: "H\ne\nm\ne\n \nk"
  poster_md: "H\ne\nm\ne\n "
  poster_lg: "H\ne"
  specimen_48: "H\ne\nm\ne\n \nk\ni\ns\nh\nl\ne\nr\n \nh\nü\nr\n \nd\ne\nr\n,\n \nh\na\ny\ns\ni\ny\ne\nt\n "
  specimen_36: "H\ne\nm\ne\n \nk\ni\ns\nh\nl\ne\nr\n \nh\nü\nr\n \nd\ne\nr\n,\n \nh\na\ny\ns\ni\ny\ne\nt\n \nm\na\n \nh\na\nk\nl\na\nr\nd\ne\n \na\nd\ni\nl\n \nd\ne\nr"
  specimen_32: "H\ne\nm\ne\n \nk\ni\ns\nh\nl\ne\nr\n \nh\nü\nr\n \nd\ne\nr\n,\n \nh\na\ny\ns\ni\ny\ne\nt\n \nm\na\n \nh\na\nk\nl\na\nr\nd\ne\n \na\nd\ni\nl\n \nd\ne\nr\n,\n \nm\na\nn\nt\ni\nk\n \nm\na\n \nv\ni\nc\nd\na\nn\n \nv\na"
  specimen_21: "H\ne\nm\ne\n \nk\ni\ns\nh\nl\ne\nr\n \nh\nü\nr\n \nd\ne\nr\n,\n \nh\na\ny\ns\ni\ny\ne\nt\n \nm\na\n \nh\na\nk\nl\na\nr\nd\ne\n \na\nd\ni\nl\n \nd\ne\nr\n,\n \nm\na\nn\nt\ni\nk\n \nm\na\n \nv\ni\nc\nd\na\nn\n \nv\na\nr\n,\n \nk\na\nr\nd\ne\ns\nh\nl\ni\nk\nd\ne\nn\n \nd\na\nv\nr\na\nn\ne\ns\nh\ng\ne\n.\nH\ne\nm\ne\n \nk\ni\ns\nh\nl\ne\nr\n \nh\nü\nr\n \nd\ne\nr\n,\n \nh\na\ny\ns\ni\ny\ne\nt\n \nm\na\n \nh\na\nk\nl\na\nr\nd\ne\n \na\nd\ni\nl\n \nd\ne\nr\n,\n "
  specimen_16: "H\ne\nm\ne\n \nk\ni\ns\nh\nl\ne\nr\n \nh\nü\nr\n \nd\ne\nr\n,\n \nh\na\ny\ns\ni\ny\ne\nt\n \nm\na\n \nh\na\nk\nl\na\nr\nd\ne\n \na\nd\ni\nl\n \nd\ne\nr\n,\n \nm\na\nn\nt\ni\nk\n \nm\na\n \nv\ni\nc\nd\na\nn\n \nv\na\nr\n,\n \nk\na\nr\nd\ne\ns\nh\nl\ni\nk\nd\ne\nn\n \nd\na\nv\nr\na\nn\ne\ns\nh\ng\ne\n.\nH\ne\nm\ne\n \nk\ni\ns\nh\nl\ne\nr\n \nh\nü\nr\n \nd\ne\nr\n,\n \nh\na\ny\ns\ni\ny\ne\nt\n \nm\na\n \nh\na\nk\nl\na\nr\nd\ne\n \na\nd\ni\nl\n \nd\ne\nr\n,\n \nm\na\nn\nt\ni\nk\n \nm\na\n \nv\ni\nc\nd\na\nn\n \nv\na\nr\n,\n \nk\na\nr\nd\ne\ns\nh\nl\ni\nk\nd\ne\nn\n \nd\na\nv\nr\na\nn\ne\ns\nh\ng\ne\n.\nH\ne\nm\ne\n \nk\ni\ns\nh\nl\ne\nr\n \nh\nü\nr\n \nd\ne\nr\n,\n \nh\na\ny\ns\ni\ny\ne\nt\n \nm\na\n \nh\na\nk\nl\na\nr\nd\ne\n \na\nd\ni\nl\n \nd\ne\nr\n,\n \nm\na\nn\nt\ni\nk\n \nm\na\n \nv\ni\nc\nd\na\nn\n \nv\na\nr\n,\n \nk\na\nr\nd"
}
