id: "smn_Latn"
language: "smn"
script: "Latn"
name: "Inari Sami"
autonym: "Anarâškielâ"
population: 612
region: "FI"
exemplar_chars {
  base: "a â b c č d đ e f g h i j k l m n ŋ o p r s š t u v y z ž ä á"
  auxiliary: "à ç é è í ñ ń ó ò q ú ü w x æ ø å ã ö"
  marks: "◌́ ◌̂ ◌̈ ◌̊ ◌̌"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A Â B C Č D Đ E F G H I J K L M N Ŋ O P R S Š T U V Y Z Ž Ä Á"
}
sample_text {
  masthead_full: "BbUu"
  masthead_partial: "Oo"
  styles: "B\nu\no\nt\n \no\nl\nb\nm\no\nt\n \nl\ne\na\nt\n \nr\ni\ne\ng"
  tester: "B\nu\no\nt\n \no\nl\nb\nm\no\nt\n \nl\ne\na\nt\n \nr\ni\ne\ng\ná\nd\na\nn\n \nf\nr\ni\nd\nd"
  poster_sm: "B\nu\no\nt\n \no"
  poster_md: "B\nu\no\nt\n "
  poster_lg: "B\nu"
  specimen_48: "B\nu\no\nt\n \no\nl\nb\nm\no\nt\n \nl\ne\na\nt\n \nr\ni\ne\ng\ná\nd\na\nn\n \nf\nr\ni\nd\nd"
  specimen_36: "B\nu\no\nt\n \no\nl\nb\nm\no\nt\n \nl\ne\na\nt\n \nr\ni\ne\ng\ná\nd\na\nn\n \nf\nr\ni\nd\nd\nj\na\nn\n \nj\na\n \no\nl\nm\nm\no\nš\ná\nr\nv\nv\nu\n \nj"
  specimen_32: "B\nu\no\nt\n \no\nl\nb\nm\no\nt\n \nl\ne\na\nt\n \nr\ni\ne\ng\ná\nd\na\nn\n \nf\nr\ni\nd\nd\nj\na\nn\n \nj\na\n \no\nl\nm\nm\no\nš\ná\nr\nv\nv\nu\n \nj\na\n \no\nl\nm\nm\no\nš\nv\nu\no\ni\ng\na\nt\nv\nu\no\nđ\na"
  specimen_21: "B\nu\no\nt\n \no\nl\nb\nm\no\nt\n \nl\ne\na\nt\n \nr\ni\ne\ng\ná\nd\na\nn\n \nf\nr\ni\nd\nd\nj\na\nn\n \nj\na\n \no\nl\nm\nm\no\nš\ná\nr\nv\nv\nu\n \nj\na\n \no\nl\nm\nm\no\nš\nv\nu\no\ni\ng\na\nt\nv\nu\no\nđ\na\ni\nd\n \nd\ná\nf\nu\ns\n \n.\n \nS\ni\ni\n \nl\ne\na\nt\n \nj\ni\ne\nr\nb\nm\na\nl\na\nš\n \no\nl\nb\nm\no\nt\n \ng\ne\na\ni\nn\n \nl\ne\na\n \no\na\nm\ne\nd\no\nv\nd\nu\n \nj\na\n \ns\ni\ni\n \ng\ná\nl\ng\ng\na\nš\ne\n \nl\ne\na\nt\n \nd"
  specimen_16: "B\nu\no\nt\n \no\nl\nb\nm\no\nt\n \nl\ne\na\nt\n \nr\ni\ne\ng\ná\nd\na\nn\n \nf\nr\ni\nd\nd\nj\na\nn\n \nj\na\n \no\nl\nm\nm\no\nš\ná\nr\nv\nv\nu\n \nj\na\n \no\nl\nm\nm\no\nš\nv\nu\no\ni\ng\na\nt\nv\nu\no\nđ\na\ni\nd\n \nd\ná\nf\nu\ns\n \n.\n \nS\ni\ni\n \nl\ne\na\nt\n \nj\ni\ne\nr\nb\nm\na\nl\na\nš\n \no\nl\nb\nm\no\nt\n \ng\ne\na\ni\nn\n \nl\ne\na\n \no\na\nm\ne\nd\no\nv\nd\nu\n \nj\na\n \ns\ni\ni\n \ng\ná\nl\ng\ng\na\nš\ne\n \nl\ne\na\nt\n \nd\ne\ng\no\n \nv\ni\ne\nl\nj\na\nč\na\ng\na\nt\n.\nB\nu\no\nt\n \no\nl\nb\nm\no\nt\n \nl\ne\na\nt\n \nr\ni\ne\ng\ná\nd\na\nn\n \nf\nr\ni\nd\nd\nj\na\nn\n \nj\na\n \no\nl\nm\nm\no\nš\ná\nr\nv\nv\nu\n \nj\na\n \no\nl\nm\nm\no\nš\nv\nu\no\ni\ng\na\nt\nv\nu\no\nđ\na\ni\nd\n \nd\ná\nf\nu\ns\n \n.\n \nS\ni\ni\n \nl\ne\na\nt\n \nj\ni\ne\nr\nb\nm\na\nl\na\nš\n \no\nl\nb\nm\no\nt\n \ng"
}
