id: "sms"
language: "sms"
script: "Latn"
name: "Skolt Sami"
autonym: "Nuõrttsääʼmǩiõll"
population: 612
region: "FI"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V X Y Z Â Ä Å Ö Õ Č Đ Ŋ Š Ž Ǥ Ǧ Ǩ Ǯ Ʒ a b c d e f g h i j k l m n o p q r s t u v x y z â ä å ö õ č đ ŋ š ž ǥ ǧ ǩ ǯ ʒ ʼ"
  auxiliary: "Å Ö Ø å ö ø"
  marks: "◌̂ ◌̃ ◌̈ ◌̊ ◌̌"
}
sample_text {
  fallback_language: "en"
}
