id: "snn_Latn"
language: "snn"
script: "Latn"
name: "Siona"
sample_text {
  masthead_full: "SsIi"
  masthead_partial: "Aa"
  styles: "S\ni\na\n\'\nb\na\ni\ṉ\n \na\ni\nd\ne\no\n\'\ny\në\n \ng\no\na\n\'\ny"
  tester: "S\ni\na\n\'\nb\na\ni\ṉ\n \na\ni\nd\ne\no\n\'\ny\në\n \ng\no\na\n\'\ny\ne\n \nb\ne\no\ny\ne\n \ng\nu"
  poster_sm: "S\ni\na\n\'\nb\na"
  poster_md: "S\ni\na\n\'\nb"
  poster_lg: "S\ni"
  specimen_48: "S\ni\na\n\'\nb\na\ni\ṉ\n \na\ni\nd\ne\no\n\'\ny\në\n \ng\no\na\n\'\ny\ne\n \nb\ne\no\ny\ne\n \ng\nu"
  specimen_36: "S\ni\na\n\'\nb\na\ni\ṉ\n \na\ni\nd\ne\no\n\'\ny\në\n \ng\no\na\n\'\ny\ne\n \nb\ne\no\ny\ne\n \ng\nu\ṉ\ni\n\'\nn\ne\n \ns\ni\na\n\'\ny\në\n\'\nq\nu\në\n \nm\na\nc\na\n "
  specimen_32: "S\ni\na\n\'\nb\na\ni\ṉ\n \na\ni\nd\ne\no\n\'\ny\në\n \ng\no\na\n\'\ny\ne\n \nb\ne\no\ny\ne\n \ng\nu\ṉ\ni\n\'\nn\ne\n \ns\ni\na\n\'\ny\në\n\'\nq\nu\në\n \nm\na\nc\na\n \nb\na\ni\n\'\ny\ne\n \ng\nu\ṉ\ni\n\'\nn\ne\n \nq\nu\në\nc\no\n "
  specimen_21: "S\ni\na\n\'\nb\na\ni\ṉ\n \na\ni\nd\ne\no\n\'\ny\në\n \ng\no\na\n\'\ny\ne\n \nb\ne\no\ny\ne\n \ng\nu\ṉ\ni\n\'\nn\ne\n \ns\ni\na\n\'\ny\në\n\'\nq\nu\në\n \nm\na\nc\na\n \nb\na\ni\n\'\ny\ne\n \ng\nu\ṉ\ni\n\'\nn\ne\n \nq\nu\në\nc\no\n \nb\na\ny\ne\n \nc\no\ṉ\nn\ni\n,\n \nj\na\ṉ\nj\ne\ṉ\n \ng\no\na\nc\nh\na\ns\ne\n\'\ns\në\nt\ne\n \ng\no\na\n\'\nj\nu\ṉ\ni\n\'\nñ\ne\n \nb\ne\no\ny\ne\n \nñ\ne\ns\ne\n \ns\na\ni\ny\ne\n \nb\na\ni\n\'\nj\ni\n \nc\no\ṉ\nc\na\ni\nj\në\n \ny\ne\nq\nu\në\n \nb"
  specimen_16: "S\ni\na\n\'\nb\na\ni\ṉ\n \na\ni\nd\ne\no\n\'\ny\në\n \ng\no\na\n\'\ny\ne\n \nb\ne\no\ny\ne\n \ng\nu\ṉ\ni\n\'\nn\ne\n \ns\ni\na\n\'\ny\në\n\'\nq\nu\në\n \nm\na\nc\na\n \nb\na\ni\n\'\ny\ne\n \ng\nu\ṉ\ni\n\'\nn\ne\n \nq\nu\në\nc\no\n \nb\na\ny\ne\n \nc\no\ṉ\nn\ni\n,\n \nj\na\ṉ\nj\ne\ṉ\n \ng\no\na\nc\nh\na\ns\ne\n\'\ns\në\nt\ne\n \ng\no\na\n\'\nj\nu\ṉ\ni\n\'\nñ\ne\n \nb\ne\no\ny\ne\n \nñ\ne\ns\ne\n \ns\na\ni\ny\ne\n \nb\na\ni\n\'\nj\ni\n \nc\no\ṉ\nc\na\ni\nj\në\n \ny\ne\nq\nu\në\n \nb\na\ni\ṉ\nr\ne\nj\ne\n.\nS\ni\na\n\'\nb\na\ni\ṉ\n \na\ni\nd\ne\no\n\'\ny\në\n \ng\no\na\n\'\ny\ne\n \nb\ne\no\ny\ne\n \ng\nu\ṉ\ni\n\'\nn\ne\n \ns\ni\na\n\'\ny\në\n\'\nq\nu\në\n \nm\na\nc\na\n \nb\na\ni\n\'\ny\ne\n \ng\nu\ṉ\ni\n\'\nn\ne\n \nq\nu\në\nc\no\n \nb\na\ny\ne\n \nc\no\ṉ\nn\ni\n,\n \nj\na\ṉ\nj\ne\ṉ\n \ng\no\na\nc\nh\na\ns\ne\n\'\ns\në\nt\ne\n \ng\no\na\n\'\nj\nu\ṉ\ni\n\'\nñ\ne\n \nb\ne\no\ny\ne\n \nñ"
}
