id: "sq_Elba"
language: "sq"
script: "Elba"
name: "Albanian, Elbasan"
population: 0
sample_text {
  masthead_full: "𐔟𐔁𐔀𐔒"
  masthead_partial: "𐔎𐔇"
  styles: "𐔟 𐔁𐔀 𐔒𐔎𐔇𐔔 𐔏𐔇 𐔠𐔖 𐔀𐔝𐔎𐔇 𐔟 𐔒𐔁𐔟𐔛𐔌𐔔𐔈 𐔄𐔍𐔝𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈"
  tester: "𐔟 𐔁𐔀 𐔒𐔎𐔇𐔔 𐔏𐔇 𐔠𐔖 𐔀𐔝𐔎𐔇 𐔟 𐔒𐔁𐔟𐔛𐔌𐔔𐔈 𐔄𐔍𐔝𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈 𐔀𐔝𐔈. 𐔇 𐔗𐔟𐔀𐔐𐔐 𐔝𐔈"
  poster_sm: "𐔟 𐔁𐔀 𐔒𐔎𐔇𐔔 𐔏𐔇"
  poster_md: "𐔟 𐔁𐔀 𐔒𐔎𐔇𐔔"
  poster_lg: "𐔒𐔎𐔇𐔔"
  specimen_48: "𐔟 𐔁𐔀 𐔒𐔎𐔇𐔔 𐔏𐔇 𐔠𐔖 𐔀𐔝𐔎𐔇 𐔟 𐔒𐔁𐔟𐔛𐔌𐔔𐔈 𐔄𐔍𐔝𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈 𐔀𐔝𐔈. 𐔇"
  specimen_36: "𐔟 𐔁𐔀 𐔒𐔎𐔇𐔔 𐔏𐔇 𐔠𐔖 𐔀𐔝𐔎𐔇 𐔟 𐔒𐔁𐔟𐔛𐔌𐔔𐔈 𐔄𐔍𐔝𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈 𐔀𐔝𐔈. 𐔇 𐔗𐔟𐔀𐔐𐔐 𐔝𐔈 𐔁𐔍𐔙𐔔 𐔇 𐔛𐔀𐔎 𐔝𐔈 𐔗𐔀 𐔙𐔈𐔔𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈, 𐔇 𐔇 𐔛𐔌𐔗𐔈𐔙𐔊𐔀 𐔔𐔍𐔛𐔍 𐔀𐔝𐔈 𐔇 𐔇 𐔒𐔁𐔟𐔐𐔖𐔍 𐔀𐔝𐔈 𐔔𐔄𐔈 𐔏𐔀𐔛𐔌𐔝𐔈 𐔛𐔇 𐔔𐔟𐔏𐔟 𐔍𐔛𐔌𐔝𐔇 𐔠𐔇𐔔𐔄𐔈 𐔗𐔙𐔇𐔎 𐔗𐔢𐔐𐔍𐔝."
  specimen_32: "𐔟 𐔁𐔀 𐔒𐔎𐔇𐔔 𐔏𐔇 𐔠𐔖 𐔀𐔝𐔎𐔇 𐔟 𐔒𐔁𐔟𐔛𐔌𐔔𐔈 𐔄𐔍𐔝𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈 𐔀𐔝𐔈. 𐔇 𐔗𐔟𐔀𐔐𐔐 𐔝𐔈 𐔁𐔍𐔙𐔔 𐔇 𐔛𐔀𐔎 𐔝𐔈 𐔗𐔀 𐔙𐔈𐔔𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈, 𐔇 𐔇 𐔛𐔌𐔗𐔈𐔙𐔊𐔀 𐔔𐔍𐔛𐔍 𐔀𐔝𐔈 𐔇 𐔇 𐔒𐔁𐔟𐔐𐔖𐔍 𐔀𐔝𐔈 𐔔𐔄𐔈 𐔏𐔀𐔛𐔌𐔝𐔈 𐔛𐔇 𐔔𐔟𐔏𐔟 𐔍𐔛𐔌𐔝𐔇 𐔠𐔇𐔔𐔄𐔈 𐔗𐔙𐔇𐔎 𐔗𐔢𐔐𐔍𐔝."
  specimen_21: "𐔟 𐔁𐔀 𐔒𐔎𐔇𐔔 𐔏𐔇 𐔠𐔖 𐔀𐔝𐔎𐔇 𐔟 𐔒𐔁𐔟𐔛𐔌𐔔𐔈 𐔄𐔍𐔝𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈 𐔀𐔝𐔈. 𐔇 𐔗𐔟𐔀𐔐𐔐 𐔝𐔈 𐔁𐔍𐔙𐔔 𐔇 𐔛𐔀𐔎 𐔝𐔈 𐔗𐔀 𐔙𐔈𐔔𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈, 𐔇 𐔇 𐔛𐔌𐔗𐔈𐔙𐔊𐔀 𐔔𐔍𐔛𐔍 𐔀𐔝𐔈 𐔇 𐔇 𐔒𐔁𐔟𐔐𐔖𐔍 𐔀𐔝𐔈 𐔔𐔄𐔈 𐔏𐔀𐔛𐔌𐔝𐔈 𐔛𐔇 𐔔𐔟𐔏𐔟 𐔍𐔛𐔌𐔝𐔇 𐔠𐔇𐔔𐔄𐔈 𐔗𐔙𐔇𐔎 𐔗𐔢𐔐𐔍𐔝.\n𐔟 𐔁𐔀 𐔒𐔎𐔇𐔔 𐔏𐔇 𐔠𐔖 𐔀𐔝𐔎𐔇 𐔟 𐔒𐔁𐔟𐔛𐔌𐔔𐔈 𐔄𐔍𐔝𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈 𐔀𐔝𐔈. 𐔇 𐔗𐔟𐔀𐔐𐔐 𐔝𐔈 𐔁𐔍𐔙𐔔 𐔇 𐔛𐔀𐔎 𐔝𐔈 𐔗𐔀 𐔙𐔈𐔔𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈, 𐔇 𐔇 𐔛𐔌𐔗𐔈𐔙𐔊𐔀 𐔔𐔍𐔛𐔍 𐔀𐔝𐔈 𐔇 𐔇 𐔒𐔁𐔟𐔐𐔖𐔍 𐔀𐔝𐔈 𐔔𐔄𐔈 𐔏𐔀𐔛𐔌𐔝𐔈 𐔛𐔇 𐔔𐔟𐔏𐔟 𐔍𐔛𐔌𐔝𐔇 𐔠𐔇𐔔𐔄𐔈 𐔗𐔙𐔇𐔎 𐔗𐔢𐔐𐔍𐔝."
  specimen_16: "𐔟 𐔁𐔀 𐔒𐔎𐔇𐔔 𐔏𐔇 𐔠𐔖 𐔀𐔝𐔎𐔇 𐔟 𐔒𐔁𐔟𐔛𐔌𐔔𐔈 𐔄𐔍𐔝𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈 𐔀𐔝𐔈. 𐔇 𐔗𐔟𐔀𐔐𐔐 𐔝𐔈 𐔁𐔍𐔙𐔔 𐔇 𐔛𐔀𐔎 𐔝𐔈 𐔗𐔀 𐔙𐔈𐔔𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈, 𐔇 𐔇 𐔛𐔌𐔗𐔈𐔙𐔊𐔀 𐔔𐔍𐔛𐔍 𐔀𐔝𐔈 𐔇 𐔇 𐔒𐔁𐔟𐔐𐔖𐔍 𐔀𐔝𐔈 𐔔𐔄𐔈 𐔏𐔀𐔛𐔌𐔝𐔈 𐔛𐔇 𐔔𐔟𐔏𐔟 𐔍𐔛𐔌𐔝𐔇 𐔠𐔇𐔔𐔄𐔈 𐔗𐔙𐔇𐔎 𐔗𐔢𐔐𐔍𐔝.\n𐔟 𐔁𐔀 𐔒𐔎𐔇𐔔 𐔏𐔇 𐔠𐔖 𐔀𐔝𐔎𐔇 𐔟 𐔒𐔁𐔟𐔛𐔌𐔔𐔈 𐔄𐔍𐔝𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈 𐔀𐔝𐔈. 𐔇 𐔗𐔟𐔀𐔐𐔐 𐔝𐔈 𐔁𐔍𐔙𐔔 𐔇 𐔛𐔀𐔎 𐔝𐔈 𐔗𐔀 𐔙𐔈𐔔𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈, 𐔇 𐔇 𐔛𐔌𐔗𐔈𐔙𐔊𐔀 𐔔𐔍𐔛𐔍 𐔀𐔝𐔈 𐔇 𐔇 𐔒𐔁𐔟𐔐𐔖𐔍 𐔀𐔝𐔈 𐔔𐔄𐔈 𐔏𐔀𐔛𐔌𐔝𐔈 𐔛𐔇 𐔔𐔟𐔏𐔟 𐔍𐔛𐔌𐔝𐔇 𐔠𐔇𐔔𐔄𐔈 𐔗𐔙𐔇𐔎 𐔗𐔢𐔐𐔍𐔝.\n𐔟 𐔁𐔀 𐔒𐔎𐔇𐔔 𐔏𐔇 𐔠𐔖 𐔀𐔝𐔎𐔇 𐔟 𐔒𐔁𐔟𐔛𐔌𐔔𐔈 𐔄𐔍𐔝𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈 𐔀𐔝𐔈. 𐔇 𐔗𐔟𐔀𐔐𐔐 𐔝𐔈 𐔁𐔍𐔙𐔔 𐔇 𐔛𐔀𐔎 𐔝𐔈 𐔗𐔀 𐔙𐔈𐔔𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈, 𐔇 𐔇 𐔛𐔌𐔗𐔈𐔙𐔊𐔀 𐔔𐔍𐔛𐔍 𐔀𐔝𐔈 𐔇 𐔇 𐔒𐔁𐔟𐔐𐔖𐔍 𐔀𐔝𐔈 𐔔𐔄𐔈 𐔏𐔀𐔛𐔌𐔝𐔈 𐔛𐔇 𐔔𐔟𐔏𐔟 𐔍𐔛𐔌𐔝𐔇 𐔠𐔇𐔔𐔄𐔈 𐔗𐔙𐔇𐔎 𐔗𐔢𐔐𐔍𐔝.\n𐔟 𐔁𐔀 𐔒𐔎𐔇𐔔 𐔏𐔇 𐔠𐔖 𐔀𐔝𐔎𐔇 𐔟 𐔒𐔁𐔟𐔛𐔌𐔔𐔈 𐔄𐔍𐔝𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈 𐔀𐔝𐔈. 𐔇 𐔗𐔟𐔀𐔐𐔐 𐔝𐔈 𐔁𐔍𐔙𐔔 𐔇 𐔛𐔀𐔎 𐔝𐔈 𐔗𐔀 𐔙𐔈𐔔𐔈 𐔝𐔈 𐔗𐔎𐔇𐔐𐔐𐔈, 𐔇 𐔇 𐔛𐔌𐔗𐔈𐔙𐔊𐔀 𐔔𐔍𐔛𐔍 𐔀𐔝𐔈 𐔇 𐔇 𐔒𐔁𐔟𐔐𐔖𐔍 𐔀𐔝𐔈 𐔔𐔄𐔈 𐔏𐔀𐔛𐔌𐔝𐔈 𐔛𐔇 𐔔𐔟𐔏𐔟 𐔍𐔛𐔌𐔝𐔇 𐔠𐔇𐔔𐔄𐔈 𐔗𐔙𐔇𐔎 𐔗𐔢𐔐𐔍𐔝."
}
historical: true
