id: "sr_Latn"
name: "Serbian (Latin)"
preferred_name: ""
autonym: ""
population: 8085593
region: "BA"
region: "ME"
region: "RO"
region: "RS"
region: "RU"
region: "TR"
region: "XK"
script: "Cyrillic"
script: "Latin"
exemplar_chars {
  base: "a b c č ć d {dž} đ e f g h i j k l {lj} m n {nj} o p r s š t u v z ž"
  auxiliary: "å q w x y"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – , ; \\: ! ? . … ‘ ‚ “ „ ( ) \\[ \\] \\{ \\} * #"
  index: "A B C Č Ć D {DŽ} E F G H I J K L {LJ} M N {NJ} O P Q R S Š T U V W X Y Z Ž"
}
sample_text {
  fallback_language: "uz"
}
