id: "sr_Latn"
language: "sr"
script: "Latn"
name: "Serbian (Latin)"
population: 8085593
region: "BA"
region: "ME"
region: "RO"
region: "RS"
region: "RU"
region: "TR"
region: "XK"
exemplar_chars {
  base: "a b c č ć d {dž} đ e f g h i j k l {lj} m n {nj} o p r s š t u v z ž {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj} {dž} {lj} {nj}"
  auxiliary: "å q w x y"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – , ; : ! ? . … ‘ ‚ “ „ ( ) [ ] { } * # { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "A B C Č Ć D {DŽ} E F G H I J K L {LJ} M N {NJ} O P Q R S Š T U V W X Y Z Ž {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ} {DŽ} {LJ} {NJ}"
}
sample_text {
  masthead_full: "SsVv"
  masthead_partial: "Aa"
  styles: "Pošto je priznavanje urođenog dostojanstva"
  tester: "pošto je nepoštovanje i preziranje prava čoveka vodilo varvarskim"
  poster_sm: "pošto je bitno"
  poster_md: "pošto je"
  poster_lg: "Sva"
  specimen_48: "pošto su narodi Ujedinjenih nacija u Povelji ponovo proglasili"
  specimen_36: "Niko se ne sme držati u ropstvu ili potčinjenosti: ropstvo i trgovina robljem zabranjeni su u svim oblicima."
  specimen_32: "pošto je bitno da prava čoveka budu zaštićena pravnim sistemom kako čovek ne bi bio primoran da kao krajnjem izlazu pribegne pobuni protiv tiranije i ugnjetavanja;"
  specimen_21: "Pošto je priznavanje urođenog dostojanstva i jednakih i neotuđivih prava svih članova ljudske porodice temelj slobode, pravde i mira u svetu;\npošto je nepoštovanje i preziranje prava čoveka vodilo varvarskim postupcima, koji su vređali savest čovečanstva, i pošto je stvaranje sveta u kojem će ljudska bića uživati slobodu govora i verovanja i biti slobodna od straha i nemaštine proglašeno kao najviša težnja svakog čoveka;"
  specimen_16: "Pošto je priznavanje urođenog dostojanstva i jednakih i neotuđivih prava svih članova ljudske porodice temelj slobode, pravde i mira u svetu;\npošto je nepoštovanje i preziranje prava čoveka vodilo varvarskim postupcima, koji su vređali savest čovečanstva, i pošto je stvaranje sveta u kojem će ljudska bića uživati slobodu govora i verovanja i biti slobodna od straha i nemaštine proglašeno kao najviša težnja svakog čoveka;\npošto je bitno da prava čoveka budu zaštićena pravnim sistemom kako čovek ne bi bio primoran da kao krajnjem izlazu pribegne pobuni protiv tiranije i ugnjetavanja;"
}
