id: "str_Latn"
language: "str"
script: "Latn"
name: "Straits Salish, Latin"
sample_text {
  masthead_full: "SsIi"
  masthead_partial: "Oo"
  styles: "S\nI\n,\nS\nI\n,\nO\nB\n \nB\nE\n₭\nO\nȻ\nB\nI\nX\n̲\n \n,\nU\nQ\nE"
  tester: "S\nI\n,\nS\nI\n,\nO\nB\n \nB\nE\n₭\nO\nȻ\nB\nI\nX\n̲\n \n,\nU\nQ\nE\nȾ\n.\n \n,\nE\nS\nZ\nU\nW\n̲\nI\nL"
  poster_sm: "S\nI\n,\nS\nI\n,\nO"
  poster_md: "S\nI\n,\nS\nI"
  poster_lg: "S\nI"
  specimen_48: "S\nI\n,\nS\nI\n,\nO\nB\n \nB\nE\n₭\nO\nȻ\nB\nI\nX\n̲\n \n,\nU\nQ\nE\nȾ\n.\n \n,\nE\nS\nZ\nU\nW\n̲\nI\nL"
  specimen_36: "S\nI\n,\nS\nI\n,\nO\nB\n \nB\nE\n₭\nO\nȻ\nB\nI\nX\n̲\n \n,\nU\nQ\nE\nȾ\n.\n \n,\nE\nS\nZ\nU\nW\n̲\nI\nL\n \nE\nL\nQ\nE\n,\n.\n \n,\nE\nS\nT\nO\nL\nX\n \nE\nL\nQ\nE\n,\n "
  specimen_32: "S\nI\n,\nS\nI\n,\nO\nB\n \nB\nE\n₭\nO\nȻ\nB\nI\nX\n̲\n \n,\nU\nQ\nE\nȾ\n.\n \n,\nE\nS\nZ\nU\nW\n̲\nI\nL\n \nE\nL\nQ\nE\n,\n.\n \n,\nE\nS\nT\nO\nL\nX\n \nE\nL\nQ\nE\n,\n \nE\nS\nD\nU\nQ\nU\nD\n \n,\nE\nS\nX\nE\nĆ\nB\nI\nD\n \nȽ\nṮ"
  specimen_21: "S\nI\n,\nS\nI\n,\nO\nB\n \nB\nE\n₭\nO\nȻ\nB\nI\nX\n̲\n \n,\nU\nQ\nE\nȾ\n.\n \n,\nE\nS\nZ\nU\nW\n̲\nI\nL\n \nE\nL\nQ\nE\n,\n.\n \n,\nE\nS\nT\nO\nL\nX\n \nE\nL\nQ\nE\n,\n \nE\nS\nD\nU\nQ\nU\nD\n \n,\nE\nS\nX\nE\nĆ\nB\nI\nD\n \nȽ\nṮ\nU\nB\nE\nX\n̲\n \nE\nL\nQ\nE\n,\n \nŚ\nÍ\nI\nS\nȽ\n \n,\nÁ\nL\n,\nÁ\nL\nŦ\n.\nS\nI\n,\nS\nI\n,\nO\nB\n \nB\nE\n₭\nO\nȻ\nB\nI\nX\n̲\n \n,\nU\nQ\nE\nȾ\n.\n \n,\nE\nS\nZ\nU\nW\n̲\nI\nL\n \nE\nL\nQ\nE\n,\n.\n \n,\nE\nS\nT\nO\nL\nX\n \nE\nL\nQ\nE\n,\n \nE\nS\nD\nU\nQ\nU"
  specimen_16: "S\nI\n,\nS\nI\n,\nO\nB\n \nB\nE\n₭\nO\nȻ\nB\nI\nX\n̲\n \n,\nU\nQ\nE\nȾ\n.\n \n,\nE\nS\nZ\nU\nW\n̲\nI\nL\n \nE\nL\nQ\nE\n,\n.\n \n,\nE\nS\nT\nO\nL\nX\n \nE\nL\nQ\nE\n,\n \nE\nS\nD\nU\nQ\nU\nD\n \n,\nE\nS\nX\nE\nĆ\nB\nI\nD\n \nȽ\nṮ\nU\nB\nE\nX\n̲\n \nE\nL\nQ\nE\n,\n \nŚ\nÍ\nI\nS\nȽ\n \n,\nÁ\nL\n,\nÁ\nL\nŦ\n.\nS\nI\n,\nS\nI\n,\nO\nB\n \nB\nE\n₭\nO\nȻ\nB\nI\nX\n̲\n \n,\nU\nQ\nE\nȾ\n.\n \n,\nE\nS\nZ\nU\nW\n̲\nI\nL\n \nE\nL\nQ\nE\n,\n.\n \n,\nE\nS\nT\nO\nL\nX\n \nE\nL\nQ\nE\n,\n \nE\nS\nD\nU\nQ\nU\nD\n \n,\nE\nS\nX\nE\nĆ\nB\nI\nD\n \nȽ\nṮ\nU\nB\nE\nX\n̲\n \nE\nL\nQ\nE\n,\n \nŚ\nÍ\nI\nS\nȽ\n \n,\nÁ\nL\n,\nÁ\nL\nŦ\n.\nS\nI\n,\nS\nI\n,\nO\nB\n \nB\nE\n₭\nO\nȻ\nB\nI\nX\n̲\n \n,\nU\nQ\nE\nȾ\n.\n \n,\nE\nS\nZ\nU\nW\n̲\nI\nL\n \nE\nL\nQ\nE\n,\n.\n \n,\nE\nS\nT\nO\nL\nX\n \nE\nL\nQ\nE\n,\n \nE\nS\nD\nU\nQ\nU\nD\n \n,\nE\nS\nX\nE\nĆ\nB\nI\nD\n \nȽ\nṮ\nU\nB\nE\nX\n̲\n \nE\nL\nQ\nE\n,\n \nŚ\nÍ\nI\nS\nȽ\n "
}
