id: "suk"
language: "suk"
script: "Latn"
name: "Sukuma"
autonym: "Kɪsukuma"
population: 5094093
region: "TZ"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P R S T U V W Y Z Ɪ a b c d e f g h i j k l m n o p r s t u v w y z \' ɪ"
}
sample_text {
  masthead_full: "BbAa"
  masthead_partial: "Nn"
  styles: "GUNGUNO yimanyikile giki ikujo lya ng’wa munhu"
  tester: "GUNGUNO ubudalahi bo sekge ya banhu hi jile jandije ja shitwa"
  poster_sm: "GUNGUNO nsi"
  poster_md: "HUNA LULU"
  poster_lg: "Banhu"
  specimen_48: "Il’Ibilinga lya Mahanga lyayomba giki, buli munhu alimane, alikuje"
  specimen_36: "Nduhu munhu adakilililwe kusolwa busese; ubusese nu Busuluja bo basese bo mbika jose bulemegije gete umumahanga agose."
  specimen_32: "Buli munhu adakililwe gwambilijiwa mu kajile k ‘ Ilagilo lihanga lyakwe mu shito josejose ishoshiling’wima mhangilo jakwe ijifumile ngw’Ihane na Jilagilo ja nsi."
  specimen_21: "Nduhu munhu uyo adugije gutung’wa (gutulwa mkandulumu) ku nzila yoseyose hanze ya Jilagilo ja nsi.\nBuli munhu adakililwe gudegelekwa mu mhangilo na bulenganila habutongi ya kajile ka nsi akatinabusolonhya umukajile kabo nulu umu mihayo ya minala.\nNduhu munhu uyo adakililwe kwingililwa sagala mu mbisila yakwe yoseyose, budugu, kaya yakwe na nduhu munhu uyo adugije kwingijiwa ikujo lyakwe ilo alinalyo. Buli munhu adakililwe gulanghanwa na Jilagilo ja nsi atizingililwa sheniko."
  specimen_16: "Buli munhu alinayo Sekge ya gwiganika na gubi na kiganikile ga miganiko ayo alikola g’wenekili nulu mu Luganda. Alinayo Sekge ya gugalucha wiganiki bokwe munhu alinayo Sekge ya guleka wiganiki nulu kahayile kakwe na buzunya bokwe, yaya gwingililwa.\nBuli munhu alinayo Sekge ya kubi na gufunya miganiko gakwe na gugayomba miganiko genayo na nduhu gwingililwa. Munhu alinayo Sekge ya gwinhwa miganiko ga bangi gubitila mu bandiki na bahayi ba mihayo.\nBuli munhu abize na wisunhya mu milimo yakwe na manongho gakwe apandike mu wisunhya bokwe.\nbuli munhu alinyo Sekge ya sele mu Luganda lokwe na mahanga agose."
}
