id: "sw"
language: "sw"
script: "Latn"
name: "Swahili"
preferred_name: "Swahili"
autonym: "Kiswahili"
population: 171610296
region: "BI"
region: "CD"
region: "KE"
region: "MZ"
region: "SO"
region: "TZ"
region: "UG"
region: "YT"
region: "ZA"
exemplar_chars {
  base: "a b {ch} d e f g h i j k l m n o p r s t u v w y z {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch} {ch}"
  auxiliary: "c q x"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‑ , ; : ! ? . \' \" ( ) [ ] { } { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "A B {CH} D E F G H I J K L M N O P R S T U V W Y Z {CH} {CH} {CH} {CH} {CH} {CH} {CH} {CH} {CH} {CH} {CH} {CH} {CH} {CH} {CH}"
}
sample_text {
  masthead_full: "WwAa"
  masthead_partial: "Tt"
  styles: "Kwa kuwa kukiri heshima ya asili na haki"
  tester: "Kwa kuwa kutojali na kudharau haki za binadamu kumeletea vitendo"
  poster_sm: "Kwa kuwa ni"
  poster_md: "Kwa kuwa"
  poster_lg: "Watu"
  specimen_48: "Kwa kuwa watu wa Umoja wa Mataifa wamethibitisha tena katika"
  specimen_36: "Watu wote wamezaliwa huru, hadhi na haki zao ni sawa. Wote wamejaliwa akili na dhamiri, hivyo yapasa watendeane kindugu."
  specimen_32: "Kila mtu ana haki ya kupumzika na kufanya kazi kwa kiasi cha saa zinazostahili. Pia ana haki ya kupata likizo, kwa vipindi, na kupokea mshahara kama vile angekuwa kazini."
  specimen_21: "Ni haki kila mtu alindwe na taratibu au kanuni za jamii na zinazohusu mataifa mbalimbali ambazo ndani yake uhuru na haki zilizoelezwa katika Taarifa hii zinaweza kuhifadhiwa barabara.\nHakuna maneno yo yote katika Taarifa hii yanayoweza kubashiriwa kwamba yanaruhusu nchi yo yote, kikundi cha watu au mtu fulani kufanya au kushughulika na jambo lo lote ambalo nia yake ni kuharibu uhuru haki zilizoelezwa humu."
  specimen_16: "Kwa kuwa kukiri heshima ya asili na haki sawa kwa binadamu wote ndio msingi wa uhuru, haki na amani duniani,\nKwa kuwa kutojali na kudharau haki za binadamu kumeletea vitendo vya kishenzi ambavyo vimeharibu dhamiri ya binadamu na kwa sababu taarifa ya ulimwengu ambayo itawafanya binadamu wafurahie uhuru wao wa kusema, kusadiki na wa kutoogopa cho chote imekwisha kutangazwa kwamba ndio hamu kuu ya watu wote,\nKwa kuwa ni lazima, ili mtu asishurutizwe kuomba msaada kutokana na maasi ya kupinga dhuluma na uonevu, kwamba haki za binadamu ziwe chini ya ulinzi wa sheria,"
}
