id: "swb"
language: "swb"
script: "Arab"
name: "Comorian"
population: 170720
region: "YT"
sample_text {
  masthead_full: "WwAa"
  masthead_partial: "Nn"
  styles: "Ha uwafiki amba mukuɓalio wa sheo wahuswiana"
  tester: "Ha uwafiki amba muharalio na mupuzisio wa zihaki za mwanadamu"
  poster_sm: "Ha uwafiki"
  poster_md: "Liɓaraza"
  poster_lg: "Wanadamu"
  specimen_48: "Wanadamu piya udzalwa huru tsena sawa ha ufahari na ha haki. Na"
  specimen_36: "Kavhusi mutru atsopatsiwawo zitriko, wala udziro au maendreleo mbovu, maendreleo tsi ya shi ɓinadamu au ya udili."
  specimen_32: "Kula mutru ana haki ya uvumuzi na ya malangadzo,  hususwani haki ya mupaka wasitahiki wapatana  nyakati za hazi, na haki ya uvumuzi wa muda ulivishihao."
  specimen_21: "Kula mutru ana haki ya ufanya namna ata vhuɓuhe maendreleo yatsotawalao, hari mwa uvhandre wa  udjama, na uvhandre wa shi ulemengu, ile zihaki  zinafasi zavumbulwa hari mwa Mutekelezeo unu zishindre zipare ɓandza.\nKavhusi ata tartiɓu moja ya Mutekelezeo unu  ifasiriwe uvandre wa Daula, shikao, au  mauri idzitria hari mwa haki itsokao yotsi ya udzivha  hazi au ya ufanya shitendrwa ikao amba  yayo ɗe ukomoa zihaki na zinafasi zadhukurulwa moni vhanu."
  specimen_16: "Ha uwafiki amba mukuɓalio wa sheo wahuswiana na watru piya wapanga udjama wa shi ɓinadamu, na wa zihaki zao zilio sawa wala kazitriliha rahani, urendreha ɗe musingi wa unafasi,na wa haki, na wa amani hari mwa lidunia ;\nHa uwafiki amba muharalio na mupuzisio wa zihaki za mwanadamu zitsongesha mufanyishio wa zitrendrwa za shi ukatili zikao amba zitsotso fikira ya unadamu, arudi mujilio wa ulemengu ukao amba ziumbe ɓinadamu watsokana nafasi ya ulagua na ya uamini, amba wapukamana na trisidzo na usikini, ɓasi mujilio uwo utrangiziwa mauri ɗe mataradjio maɓole kaɓisa ya mwanadamu ;"
}
