id: "syl_Beng"
language: "syl"
script: "Beng"
name: "Sylheti"
population: 8467931
region: "BD"
region: "GB"
sample_text {
  masthead_full: "শবমই"
  masthead_partial: "নর"
  styles: "শ\nব\n \nম\nা\nই\nন\nশ\nর\n \nআ\nজ\nা\nদ\nি\n \nজ\nন\nম\n \nও\nএ"
  tester: "শ\nব\n \nম\nা\nই\nন\nশ\nর\n \nআ\nজ\nা\nদ\nি\n \nজ\nন\nম\n \nও\nএ\n \nই\nজ\n্\nজ\nত\n \nআ\nর\n \nহ"
  poster_sm: "শ\nব\n \nম\nা\nই"
  poster_md: "শ\nব\n \nম\nা"
  poster_lg: "শ\nব"
  specimen_48: "শ\nব\n \nম\nা\nই\nন\nশ\nর\n \nআ\nজ\nা\nদ\nি\n \nজ\nন\nম\n \nও\nএ\n \nই\nজ\n্\nজ\nত\n \nআ\nর\n \nহ"
  specimen_36: "শ\nব\n \nম\nা\nই\nন\nশ\nর\n \nআ\nজ\nা\nদ\nি\n \nজ\nন\nম\n \nও\nএ\n \nই\nজ\n্\nজ\nত\n \nআ\nর\n \nহ\nক\n \nল\nৈ\nআ\n।\n \nত\nা\nর\nা\nর\n \nহ\nু\nশ\n \nআ\nর\n \nআ\nক"
  specimen_32: "শ\nব\n \nম\nা\nই\nন\nশ\nর\n \nআ\nজ\nা\nদ\nি\n \nজ\nন\nম\n \nও\nএ\n \nই\nজ\n্\nজ\nত\n \nআ\nর\n \nহ\nক\n \nল\nৈ\nআ\n।\n \nত\nা\nর\nা\nর\n \nহ\nু\nশ\n \nআ\nর\n \nআ\nক\nল\n-\nব\nু\nদ\n্\nধ\nি\n \nআ\nছ\nে\n \nআ\nর\n \nত\nা\nর\nা\n \nএ\nক\nজ"
  specimen_21: "শ\nব\n \nম\nা\nই\nন\nশ\nর\n \nআ\nজ\nা\nদ\nি\n \nজ\nন\nম\n \nও\nএ\n \nই\nজ\n্\nজ\nত\n \nআ\nর\n \nহ\nক\n \nল\nৈ\nআ\n।\n \nত\nা\nর\nা\nর\n \nহ\nু\nশ\n \nআ\nর\n \nআ\nক\nল\n-\nব\nু\nদ\n্\nধ\nি\n \nআ\nছ\nে\n \nআ\nর\n \nত\nা\nর\nা\n \nএ\nক\nজ\nন\n \nআ\nর\nক\nজ\nন\nর\n \nল\nগ\nে\n \nর\nু\nহ\nা\nন\nি\n \nভ\nা\nই\nট\n্\nট\nা\n \nব\nে\nব\nহ\nা\nর\n \nথ\nা\nক\nত\n।\nশ\nব\n \nম\nা\nই\nন\nশ\nর\n \nআ\nজ\nা\nদ\nি\n \nজ\nন\nম\n \nও\nএ\n \nই\nজ\n্\nজ\nত\n \nআ\nর\n \nহ\nক\n \nল\nৈ\nআ\n।\n \nত\nা\nর\nা\nর\n \nহ\nু\nশ\n "
  specimen_16: "শ\nব\n \nম\nা\nই\nন\nশ\nর\n \nআ\nজ\nা\nদ\nি\n \nজ\nন\nম\n \nও\nএ\n \nই\nজ\n্\nজ\nত\n \nআ\nর\n \nহ\nক\n \nল\nৈ\nআ\n।\n \nত\nা\nর\nা\nর\n \nহ\nু\nশ\n \nআ\nর\n \nআ\nক\nল\n-\nব\nু\nদ\n্\nধ\nি\n \nআ\nছ\nে\n \nআ\nর\n \nত\nা\nর\nা\n \nএ\nক\nজ\nন\n \nআ\nর\nক\nজ\nন\nর\n \nল\nগ\nে\n \nর\nু\nহ\nা\nন\nি\n \nভ\nা\nই\nট\n্\nট\nা\n \nব\nে\nব\nহ\nা\nর\n \nথ\nা\nক\nত\n।\nশ\nব\n \nম\nা\nই\nন\nশ\nর\n \nআ\nজ\nা\nদ\nি\n \nজ\nন\nম\n \nও\nএ\n \nই\nজ\n্\nজ\nত\n \nআ\nর\n \nহ\nক\n \nল\nৈ\nআ\n।\n \nত\nা\nর\nা\nর\n \nহ\nু\nশ\n \nআ\nর\n \nআ\nক\nল\n-\nব\nু\nদ\n্\nধ\nি\n \nআ\nছ\nে\n \nআ\nর\n \nত\nা\nর\nা\n \nএ\nক\nজ\nন\n \nআ\nর\nক\nজ\nন\nর\n \nল\nগ\nে\n \nর\nু\nহ\nা\nন\nি\n \nভ\nা\nই\nট\n্\nট\nা\n \nব\nে\nব\nহ\nা\nর\n \nথ\nা\nক\nত\n।\nশ\nব\n \nম\nা\nই\nন\nশ\nর\n \nআ\nজ\nা\nদ\nি\n \nজ\nন\nম\n \nও\nএ\n \nই\nজ\n্\nজ\nত\n \nআ\nর\n \nহ\nক\n \nল\nৈ\nআ\n।\n \nত\nা\nর\nা\nর\n \nহ\nু\nশ\n \nআ\nর\n \nআ\nক\nল\n-\nব\nু\nদ\n্\nধ\nি\n \nআ\nছ\nে\n \nআ\nর\n \nত"
}
