id: "syl_Beng"
language: "syl"
script: "Beng"
name: "Sylheti"
population: 8467931
region: "BD"
region: "GB"
sample_text {
  masthead_full: "শবমই"
  masthead_partial: "নর"
  styles: "শব মাইনশর আজাদি জনম ওএ ইজ্জত আর হক লৈআ। তারার হুশ"
  tester: "শব মাইনশর আজাদি জনম ওএ ইজ্জত আর হক লৈআ। তারার হুশ আর আকলবুদ্ধি আছে আর তারা একজন"
  poster_sm: "শব মাইনশর আজাদি"
  poster_md: "শব মাইনশর"
  poster_lg: "মাইনশর"
  specimen_48: "শব মাইনশর আজাদি জনম ওএ ইজ্জত আর হক লৈআ। তারার হুশ আর আকলবুদ্ধি"
  specimen_36: "শব মাইনশর আজাদি জনম ওএ ইজ্জত আর হক লৈআ। তারার হুশ আর আকলবুদ্ধি আছে আর তারা একজন আরকজনর লগে রুহানি ভাইট্টা বেবহার থাকত।"
  specimen_32: "শব মাইনশর আজাদি জনম ওএ ইজ্জত আর হক লৈআ। তারার হুশ আর আকলবুদ্ধি আছে আর তারা একজন আরকজনর লগে রুহানি ভাইট্টা বেবহার থাকত।"
  specimen_21: "শব মাইনশর আজাদি জনম ওএ ইজ্জত আর হক লৈআ। তারার হুশ আর আকলবুদ্ধি আছে আর তারা একজন আরকজনর লগে রুহানি ভাইট্টা বেবহার থাকত।\nশব মাইনশর আজাদি জনম ওএ ইজ্জত আর হক লৈআ। তারার হুশ আর আকলবুদ্ধি আছে আর তারা একজন আরকজনর লগে রুহানি ভাইট্টা বেবহার থাকত।\nশব মাইনশর আজাদি জনম ওএ ইজ্জত আর হক লৈআ। তারার হুশ আর আকলবুদ্ধি আছে আর তারা একজন আরকজনর লগে রুহানি ভাইট্টা বেবহার থাকত।\nশব মাইনশর আজাদি জনম ওএ ইজ্জত আর হক লৈআ। তারার হুশ আর আকলবুদ্ধি আছে আর তারা একজন আরকজনর লগে রুহানি ভাইট্টা বেবহার থাকত।"
  specimen_16: "শব মাইনশর আজাদি জনম ওএ ইজ্জত আর হক লৈআ। তারার হুশ আর আকলবুদ্ধি আছে আর তারা একজন আরকজনর লগে রুহানি ভাইট্টা বেবহার থাকত।\nশব মাইনশর আজাদি জনম ওএ ইজ্জত আর হক লৈআ। তারার হুশ আর আকলবুদ্ধি আছে আর তারা একজন আরকজনর লগে রুহানি ভাইট্টা বেবহার থাকত।\nশব মাইনশর আজাদি জনম ওএ ইজ্জত আর হক লৈআ। তারার হুশ আর আকলবুদ্ধি আছে আর তারা একজন আরকজনর লগে রুহানি ভাইট্টা বেবহার থাকত।\nশব মাইনশর আজাদি জনম ওএ ইজ্জত আর হক লৈআ। তারার হুশ আর আকলবুদ্ধি আছে আর তারা একজন আরকজনর লগে রুহানি ভাইট্টা বেবহার থাকত।\nশব মাইনশর আজাদি জনম ওএ ইজ্জত আর হক লৈআ। তারার হুশ আর আকলবুদ্ধি আছে আর তারা একজন আরকজনর লগে রুহানি ভাইট্টা বেবহার থাকত।\nশব মাইনশর আজাদি জনম ওএ ইজ্জত আর হক লৈআ। তারার হুশ আর আকলবুদ্ধি আছে আর তারা একজন আরকজনর লগে রুহানি ভাইট্টা বেবহার থাকত।"
}
