id: "taj_Deva"
language: "taj"
script: "Deva"
name: "Eastern Tamang"
autonym: "तामाङ‎"
population: 130409
region: "NP"
exemplar_chars {
  base: "अ आ इ ई उ ऊ ऋ ए ऐ ओ औ क ख ग घ ङ च छ ज झ ञ ट ठ ड ढ ण त थ द ध न प फ ब भ म य र ल व श ष स ह ‌ ‍"
  auxiliary: "ॐ"
  marks: "◌ँ ◌ं ◌ः ◌़ ◌ा ◌ि ◌ी ◌ु ◌ू ◌ृ ◌े ◌ै ◌ो ◌ौ ◌्"
  numerals: "० १ २ ३ ४ ५ ६ ७ ८ ९ 0 1 2 3 4 5 6 7 8 9"
  punctuation: "। ॥ ॰"
}
sample_text {
  masthead_full: "बनमह"
  masthead_partial: "कद"
  styles: "बेनान म्हीकादे प्रतिष्ठा थेन याङतामला आधाररी केमाहेन्सेन स्वतन्त्र"
  tester: "बेनान म्हीकादे प्रतिष्ठा थेन याङतामला आधाररी केमाहेन्सेन स्वतन्त्र थेन च्योच्यो ताला। थेनीकादे बुद्धि"
  poster_sm: "बेनान म्हीकादे प्रतिष्ठा"
  poster_md: "बेनान म्हीकादे"
  poster_lg: "बेनान"
  specimen_48: "बेनान म्हीकादे प्रतिष्ठा थेन याङतामला आधाररी केमाहेन्सेन स्वतन्त्र थेन च्योच्यो"
  specimen_36: "बेनान म्हीकादे प्रतिष्ठा थेन याङतामला आधाररी केमाहेन्सेन स्वतन्त्र थेन च्योच्यो ताला। थेनीकादे बुद्धि थेन विवेक किन्दासी खाबा ताला ओम गीसेमगीला गुङरी डीक्पा ह्रिक्पा लातोसेदा मुला।"
  specimen_32: "बेनान म्हीकादे प्रतिष्ठा थेन याङतामला आधाररी केमाहेन्सेन स्वतन्त्र थेन च्योच्यो ताला। थेनीकादे बुद्धि थेन विवेक किन्दासी खाबा ताला ओम गीसेमगीला गुङरी डीक्पा ह्रिक्पा लातोसेदा मुला।"
  specimen_21: "बेनान म्हीकादे प्रतिष्ठा थेन याङतामला आधाररी केमाहेन्सेन स्वतन्त्र थेन च्योच्यो ताला। थेनीकादे बुद्धि थेन विवेक किन्दासी खाबा ताला ओम गीसेमगीला गुङरी डीक्पा ह्रिक्पा लातोसेदा मुला।\nबेनान म्हीकादे प्रतिष्ठा थेन याङतामला आधाररी केमाहेन्सेन स्वतन्त्र थेन च्योच्यो ताला। थेनीकादे बुद्धि थेन विवेक किन्दासी खाबा ताला ओम गीसेमगीला गुङरी डीक्पा ह्रिक्पा लातोसेदा मुला।\nबेनान म्हीकादे प्रतिष्ठा थेन याङतामला आधाररी केमाहेन्सेन स्वतन्त्र थेन च्योच्यो ताला। थेनीकादे बुद्धि थेन विवेक किन्दासी खाबा ताला ओम गीसेमगीला गुङरी डीक्पा ह्रिक्पा लातोसेदा मुला।"
  specimen_16: "बेनान म्हीकादे प्रतिष्ठा थेन याङतामला आधाररी केमाहेन्सेन स्वतन्त्र थेन च्योच्यो ताला। थेनीकादे बुद्धि थेन विवेक किन्दासी खाबा ताला ओम गीसेमगीला गुङरी डीक्पा ह्रिक्पा लातोसेदा मुला।\nबेनान म्हीकादे प्रतिष्ठा थेन याङतामला आधाररी केमाहेन्सेन स्वतन्त्र थेन च्योच्यो ताला। थेनीकादे बुद्धि थेन विवेक किन्दासी खाबा ताला ओम गीसेमगीला गुङरी डीक्पा ह्रिक्पा लातोसेदा मुला।\nबेनान म्हीकादे प्रतिष्ठा थेन याङतामला आधाररी केमाहेन्सेन स्वतन्त्र थेन च्योच्यो ताला। थेनीकादे बुद्धि थेन विवेक किन्दासी खाबा ताला ओम गीसेमगीला गुङरी डीक्पा ह्रिक्पा लातोसेदा मुला।\nबेनान म्हीकादे प्रतिष्ठा थेन याङतामला आधाररी केमाहेन्सेन स्वतन्त्र थेन च्योच्यो ताला। थेनीकादे बुद्धि थेन विवेक किन्दासी खाबा ताला ओम गीसेमगीला गुङरी डीक्पा ह्रिक्पा लातोसेदा मुला।\nबेनान म्हीकादे प्रतिष्ठा थेन याङतामला आधाररी केमाहेन्सेन स्वतन्त्र थेन च्योच्यो ताला। थेनीकादे बुद्धि थेन विवेक किन्दासी खाबा ताला ओम गीसेमगीला गुङरी डीक्पा ह्रिक्पा लातोसेदा मुला।"
}
