id: "taj_Tibt"
language: "taj"
script: "Tibt"
name: "Eastern Tamang, Tibetan"
autonym: "རྟ་དམག‎"
population: 0
region: "BT"
region: "CN"
region: "IN"
region: "NP"
exemplar_chars {
  base: "ཀ ཁ ག ང ཅ ཆ ཇ ཉ ཏ ཐ ད ན པ ཕ བ མ ཙ ཚ ཛ ཝ ཞ ཟ འ ཡ ར ལ ཤ ས ཧ ཨ"
  marks: "◌ི ◌ུ ◌ེ ◌ོ"
  numerals: "༠ ༡ ༢ ༣ ༤ ༥ ༦ ༧ ༨ ༩"
  punctuation: "༄ ༈ ་ ། ༎ ༔ ༺ ༻"
}
sample_text {
  fallback_language: "bo"
}
