id: "taq_Latn"
language: "taq"
script: "Latn"
name: "Tamasheq, Latin"
sample_text {
  masthead_full: "MmDd"
  masthead_partial: "Aa"
  styles: "M\nd\na\nn\n \nd\nd\nu\nn\nt\n \nt\ni\nw\ne\nn\n \nl\nl\nu\nl"
  tester: "M\nd\na\nn\n \nd\nd\nu\nn\nt\n \nt\ni\nw\ne\nn\n \nl\nl\nu\nl\nl\ni\nn\n,\n \nu\nl\na\nn\n "
  poster_sm: "M\nd\na\nn\n \nd"
  poster_md: "M\nd\na\nn\n "
  poster_lg: "M\nd"
  specimen_48: "M\nd\na\nn\n \nd\nd\nu\nn\nt\n \nt\ni\nw\ne\nn\n \nl\nl\nu\nl\nl\ni\nn\n,\n \nu\nl\na\nn\n "
  specimen_36: "M\nd\na\nn\n \nd\nd\nu\nn\nt\n \nt\ni\nw\ne\nn\n \nl\nl\nu\nl\nl\ni\nn\n,\n \nu\nl\na\nn\n \ns\n \nl\nh\nə\nq\n.\n \nǦ\nr\na\nw\nə\nn\n \nt\na\ny\nə\nt\nt"
  specimen_32: "M\nd\na\nn\n \nd\nd\nu\nn\nt\n \nt\ni\nw\ne\nn\n \nl\nl\nu\nl\nl\ni\nn\n,\n \nu\nl\na\nn\n \ns\n \nl\nh\nə\nq\n.\n \nǦ\nr\na\nw\nə\nn\n \nt\na\ny\nə\nt\nt\ne\n \nd\n \nm\na\nn\n \nf\nu\nl\nl\n \ne\nd\n \nn\nm\nə\nr"
  specimen_21: "M\nd\na\nn\n \nd\nd\nu\nn\nt\n \nt\ni\nw\ne\nn\n \nl\nl\nu\nl\nl\ni\nn\n,\n \nu\nl\na\nn\n \ns\n \nl\nh\nə\nq\n.\n \nǦ\nr\na\nw\nə\nn\n \nt\na\ny\nə\nt\nt\ne\n \nd\n \nm\na\nn\n \nf\nu\nl\nl\n \ne\nd\n \nn\nm\nə\nr\nt\na\ny\nə\nn\n \ns\n \nt\na\nñ\nñ\nə\nt\n.\nM\nd\na\nn\n \nd\nd\nu\nn\nt\n \nt\ni\nw\ne\nn\n \nl\nl\nu\nl\nl\ni\nn\n,\n \nu\nl\na\nn\n \ns\n \nl\nh\nə\nq\n.\n \nǦ\nr\na\nw\nə\nn\n \nt\na\ny\nə\nt\nt\ne\n \nd\n \nm\na\nn\n \nf\nu\nl\nl\n \ne"
  specimen_16: "M\nd\na\nn\n \nd\nd\nu\nn\nt\n \nt\ni\nw\ne\nn\n \nl\nl\nu\nl\nl\ni\nn\n,\n \nu\nl\na\nn\n \ns\n \nl\nh\nə\nq\n.\n \nǦ\nr\na\nw\nə\nn\n \nt\na\ny\nə\nt\nt\ne\n \nd\n \nm\na\nn\n \nf\nu\nl\nl\n \ne\nd\n \nn\nm\nə\nr\nt\na\ny\nə\nn\n \ns\n \nt\na\nñ\nñ\nə\nt\n.\nM\nd\na\nn\n \nd\nd\nu\nn\nt\n \nt\ni\nw\ne\nn\n \nl\nl\nu\nl\nl\ni\nn\n,\n \nu\nl\na\nn\n \ns\n \nl\nh\nə\nq\n.\n \nǦ\nr\na\nw\nə\nn\n \nt\na\ny\nə\nt\nt\ne\n \nd\n \nm\na\nn\n \nf\nu\nl\nl\n \ne\nd\n \nn\nm\nə\nr\nt\na\ny\nə\nn\n \ns\n \nt\na\nñ\nñ\nə\nt\n.\nM\nd\na\nn\n \nd\nd\nu\nn\nt\n \nt\ni\nw\ne\nn\n \nl\nl\nu\nl\nl\ni\nn\n,\n \nu\nl\na\nn\n \ns\n \nl\nh\nə\nq\n.\n \nǦ\nr\na\nw\nə\nn\n \nt\na\ny\nə\nt\nt\ne\n \nd\n \nm\na\nn\n \nf\nu\nl\nl\n \ne\nd\n \nn\nm\nə\nr\nt\na\ny\nə\nn\n \ns\n \nt\na\nñ\nñ\nə\nt\n.\nM\nd\na\nn\n \nd\nd\nu\nn\nt\n \nt\ni\nw\ne\nn\n \nl\nl"
}
