id: "tbz_Latn"
language: "tbz"
script: "Latn"
name: "Ditammari"
sample_text {
  masthead_full: "OoNn"
  masthead_partial: "Ii"
  styles: "O\nn\ni\nt\ni\n \nt\ni\n \np\nɛ\ni\n \nn\nɖ\nɛ\n \no\nm\nɔ\nũ"
  tester: "O\nn\ni\nt\ni\n \nt\ni\n \np\nɛ\ni\n \nn\nɖ\nɛ\n \no\nm\nɔ\nũ\n \ny\ni\n \nk\np\na\na\nt\nr"
  poster_sm: "O\nn\ni\nt\ni\n "
  poster_md: "O\nn\ni\nt\ni"
  poster_lg: "O\nn"
  specimen_48: "O\nn\ni\nt\ni\n \nt\ni\n \np\nɛ\ni\n \nn\nɖ\nɛ\n \no\nm\nɔ\nũ\n \ny\ni\n \nk\np\na\na\nt\nr"
  specimen_36: "O\nn\ni\nt\ni\n \nt\ni\n \np\nɛ\ni\n \nn\nɖ\nɛ\n \no\nm\nɔ\nũ\n \ny\ni\n \nk\np\na\na\nt\nr\ni\n \no\nt\nɔ\nu\n,\n \nk\nɛ\n \ny\nɛ\ñ\n \no\nn\ni\nt\ni\n "
  specimen_32: "O\nn\ni\nt\ni\n \nt\ni\n \np\nɛ\ni\n \nn\nɖ\nɛ\n \no\nm\nɔ\nũ\n \ny\ni\n \nk\np\na\na\nt\nr\ni\n \no\nt\nɔ\nu\n,\n \nk\nɛ\n \ny\nɛ\ñ\n \no\nn\ni\nt\ni\n \nb\na\n \nw\ne\n,\n \no\n \ny\ni\n \nɖ\no\n \nn\nn\nɛ\n \nf"
  specimen_21: "O\nn\ni\nt\ni\n \nt\ni\n \np\nɛ\ni\n \nn\nɖ\nɛ\n \no\nm\nɔ\nũ\n \ny\ni\n \nk\np\na\na\nt\nr\ni\n \no\nt\nɔ\nu\n,\n \nk\nɛ\n \ny\nɛ\ñ\n \no\nn\ni\nt\ni\n \nb\na\n \nw\ne\n,\n \no\n \ny\ni\n \nɖ\no\n \nn\nn\nɛ\n \nf\nɛ\nh\nɔ\ñ\nf\nɛ\n;\n \no\n \nm\nɔ\nk\nɛ\nm\nu\n \nm\nɛ\nc\ni\ni\n \nk\nɛ\nh\nã\n \nm\nɛ\ny\nɛ\nm\nm\nɛ\n.\n \nT\ni\n \nt\nú\n \nn\nɛ\n \nɖ\no\n \nk\ne\nn\ny\na\nr\ni\n \nt\ni\n \nt\nɔ\nb\nɛ\n \nm\nb\nɛ\n \nk\nɛ\n \ny\ni\ne\n \nm\ni\ni\n \nb\na"
  specimen_16: "O\nn\ni\nt\ni\n \nt\ni\n \np\nɛ\ni\n \nn\nɖ\nɛ\n \no\nm\nɔ\nũ\n \ny\ni\n \nk\np\na\na\nt\nr\ni\n \no\nt\nɔ\nu\n,\n \nk\nɛ\n \ny\nɛ\ñ\n \no\nn\ni\nt\ni\n \nb\na\n \nw\ne\n,\n \no\n \ny\ni\n \nɖ\no\n \nn\nn\nɛ\n \nf\nɛ\nh\nɔ\ñ\nf\nɛ\n;\n \no\n \nm\nɔ\nk\nɛ\nm\nu\n \nm\nɛ\nc\ni\ni\n \nk\nɛ\nh\nã\n \nm\nɛ\ny\nɛ\nm\nm\nɛ\n.\n \nT\ni\n \nt\nú\n \nn\nɛ\n \nɖ\no\n \nk\ne\nn\ny\na\nr\ni\n \nt\ni\n \nt\nɔ\nb\nɛ\n \nm\nb\nɛ\n \nk\nɛ\n \ny\ni\ne\n \nm\ni\ni\n \nb\na\n \nn\nk\nw\nu\nɔ\n \nk\no\n \no\nt\nɔ\nu\n \nɖ\na\nu\n.\nO\nn\ni\nt\ni\n \nt\ni\n \np\nɛ\ni\n \nn\nɖ\nɛ\n \no\nm\nɔ\nũ\n \ny\ni\n \nk\np\na\na\nt\nr\ni\n \no\nt\nɔ\nu\n,\n \nk\nɛ\n \ny\nɛ\ñ\n \no\nn\ni\nt\ni\n \nb\na\n \nw\ne\n,\n \no\n \ny\ni\n \nɖ\no\n \nn\nn\nɛ\n \nf\nɛ\nh\nɔ\ñ\nf\nɛ\n;\n \no\n \nm\nɔ\nk\nɛ\nm\nu\n \nm\nɛ\nc\ni\ni\n \nk\nɛ\nh\nã\n \nm\nɛ\ny\nɛ\nm\nm\nɛ\n.\n "
}
