id: "tca_Latn"
language: "tca"
script: "Latn"
name: "Ticuna"
sample_text {
  masthead_full: "NnGg"
  masthead_partial: "Ẽẽ"
  styles: "N\ng\nẽ\nx\ng\nu\nm\na\n \nn\na\nb\nu\nx\ng\nu\n \ni\n \nd\nu"
  tester: "N\ng\nẽ\nx\ng\nu\nm\na\n \nn\na\nb\nu\nx\ng\nu\n \ni\n \nd\nu\nü\ñ\nx\nü\ñ\ng\nü\n \nr\nü\n "
  poster_sm: "N\ng\nẽ\nx\ng\nu"
  poster_md: "N\ng\nẽ\nx\ng"
  poster_lg: "N\ng"
  specimen_48: "N\ng\nẽ\nx\ng\nu\nm\na\n \nn\na\nb\nu\nx\ng\nu\n \ni\n \nd\nu\nü\ñ\nx\nü\ñ\ng\nü\n \nr\nü\n "
  specimen_36: "N\ng\nẽ\nx\ng\nu\nm\na\n \nn\na\nb\nu\nx\ng\nu\n \ni\n \nd\nu\nü\ñ\nx\nü\ñ\ng\nü\n \nr\nü\n \ng\nu\nx\nü\ñ\nm\na\n \nn\na\nw\nü\nx\ni\ng\nu\n,\n \nr\nü\n "
  specimen_32: "N\ng\nẽ\nx\ng\nu\nm\na\n \nn\na\nb\nu\nx\ng\nu\n \ni\n \nd\nu\nü\ñ\nx\nü\ñ\ng\nü\n \nr\nü\n \ng\nu\nx\nü\ñ\nm\na\n \nn\na\nw\nü\nx\ni\ng\nu\n,\n \nr\nü\n \nt\na\nt\na\nx\nu\nm\na\n \ny\na\n \nt\ne\nx\né\n \ny\na\n "
  specimen_21: "N\ng\nẽ\nx\ng\nu\nm\na\n \nn\na\nb\nu\nx\ng\nu\n \ni\n \nd\nu\nü\ñ\nx\nü\ñ\ng\nü\n \nr\nü\n \ng\nu\nx\nü\ñ\nm\na\n \nn\na\nw\nü\nx\ni\ng\nu\n,\n \nr\nü\n \nt\na\nt\na\nx\nu\nm\na\n \ny\na\n \nt\ne\nx\né\n \ny\na\n \nt\no\ng\nü\na\nr\nü\n \ny\ne\nx\ne\nr\na\n \ni\nx\nĩ\ns\nẽ\n.\n \nR\nü\n \ng\nu\nx\nü\ñ\nm\na\n \nn\na\nx\nã\nã\nẽ\ng\nü\n \nr\nü\n \nn\ng\nẽ\nm\na\nc\na\ṉ\nx\n \nr\nü\n \nn\na\nm\ne\n \nn\ni\nx\nĩ\n \nn\na\n \nn\nü\ng\nü\nm\na\nã\n \nn\na"
  specimen_16: "N\ng\nẽ\nx\ng\nu\nm\na\n \nn\na\nb\nu\nx\ng\nu\n \ni\n \nd\nu\nü\ñ\nx\nü\ñ\ng\nü\n \nr\nü\n \ng\nu\nx\nü\ñ\nm\na\n \nn\na\nw\nü\nx\ni\ng\nu\n,\n \nr\nü\n \nt\na\nt\na\nx\nu\nm\na\n \ny\na\n \nt\ne\nx\né\n \ny\na\n \nt\no\ng\nü\na\nr\nü\n \ny\ne\nx\ne\nr\na\n \ni\nx\nĩ\ns\nẽ\n.\n \nR\nü\n \ng\nu\nx\nü\ñ\nm\na\n \nn\na\nx\nã\nã\nẽ\ng\nü\n \nr\nü\n \nn\ng\nẽ\nm\na\nc\na\ṉ\nx\n \nr\nü\n \nn\na\nm\ne\n \nn\ni\nx\nĩ\n \nn\na\n \nn\nü\ng\nü\nm\na\nã\n \nn\na\nm\ne\nc\nü\nm\na\nx\nü\ñ\n \nĩ\n \ng\nu\nx\nü\ñ\nm\na\n \nĩ\n \nd\nu\nü\ñ\nx\nü\ñ\ng\nü\n.\nN\ng\nẽ\nx\ng\nu\nm\na\n \nn\na\nb\nu\nx\ng\nu\n \ni\n \nd\nu\nü\ñ\nx\nü\ñ\ng\nü\n \nr\nü\n \ng\nu\nx\nü\ñ\nm\na\n \nn\na\nw\nü\nx\ni\ng\nu\n,\n \nr\nü\n \nt\na\nt\na\nx\nu\nm\na\n \ny\na\n \nt\ne\nx\né\n \ny\na\n \nt\no\ng\nü\na\nr\nü\n \ny\ne\nx\ne\nr\na\n \ni\nx\nĩ\ns\nẽ\n.\n \nR\nü\n "
}
