id: "te"
language: "te"
script: "Telu"
name: "Telugu"
autonym: "తెలుగు"
population: 95478480
region: "IN"
exemplar_chars {
  base: "అ ఆ ఇ ఈ ఉ ఊ ఋ ౠ ఌ ౡ ఎ ఏ ఐ ఒ ఓ ఔ ఁ ం ః క ఖ గ ఘ ఙ చ ఛ జ ఝ ఞ ట ఠ డ ఢ ణ త థ ద ధ న ప ఫ బ భ మ య ర ఱ ల వ శ ష స హ ళ ా ి ీ ు ూ ృ ౄ ె ే ై ొ ో ౌ ్ ౕ ౖ"
  auxiliary: "‌‍ ౦ ౧ ౨ ౩ ౪ ౫ ౬ ౭ ౮ ౯"
  marks: "◌ఁ ◌ం ◌ః ◌ా ◌ి ◌ీ ◌ు ◌ూ ◌ృ ◌ౄ ◌ె ◌ే ◌ొ ◌ో ◌ౌ ◌్ ◌ౖ ◌ౢ ◌ౣ"
  numerals: "- ‑ , . % ‰ + 0౦ 1౧ 2౨ 3౩ 4౪ 5౫ 6౬ 7౭ 8౮ 9౯"
  punctuation: "- ‑ , ; : ! ? . \' ‘ ’ \" “ ” ( ) [ ] { } { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "అ ఆ ఇ ఈ ఉ ఊ ఋ ౠ ఎ ఏ ఐ ఒ ఓ ఔ క ఖ గ ఘ ఙ చ ఛ జ ఝ ఞ ట ఠ డ ఢ ణ త థ ద ధ న ప ఫ బ భ మ య ర ఱ ల వ శ ష స హ ళ"
}
sample_text {
  masthead_full: "పరతస"
  masthead_partial: "వమ"
  styles: "మానవకుటంబమునందలి వ్యక్తులందరికిని గల ఆజన్మసిద్ధమైన ప్రతిపత్తిని,"
  tester: "మానవజాతి అంతఃకరణమును క్షోభపెట్టిన ఘోరచర్యలు, మానవస్వత్వములయెడ గలిగిన అవజ్ఞా నిరసన భావముల"
  poster_sm: "రాష్ట్రముల మధ్య"
  poster_md: "ఈ స్వత్వములను"
  poster_lg: "విషయమున"
  specimen_48: "సమాజమునకు చెందిన ప్రతివ్యక్తియు, సమాజము యొక్క ప్రత్యంగమును, ఈ స్వత్వముల ప్రకటనను సదా మనసునందుంచుకొని,"
  specimen_36: "సంవిధానముచే గాని విధిచే గాని యోసగబడిన మూలస్వత్వములను వ్యతిక్రమించు కార్యముల విషయమున, సమర్థమగు రాష్ట్రీయ న్యాయాధికరణ సభచే ఫలప్రదమగు ప్రతిక్రియను పొందుటకు, ప్రతి వ్యక్తికిని హక్కు గలదు."
  specimen_32: "ప్రతి వ్యక్తికిని, అతని స్వత్వములయోక్కయు ఆభారముయొక్కయు నిర్ణయమునందును, అతనిపైనున్న ఏ దోషారోపణయొక్క నిర్ణయమునందును, స్వతంత్రము, నిష్పక్షపాతమునగు న్యాయాధికరణ సభ యెదుట, న్యాయము, బహిరంగము నగు విచారణను పొందుటకు సమానమగు సమగ్రస్వత్వము కలదు."
  specimen_21: "ఆంతరంగిక, కుటుంబ, గృహ, లేఖావ్యవహారములలో, విధి విరుద్ధమయిన జోక్యమునకుగాని, గౌరవప్రతిష్థలను భంగపరచు ప్రచారములకుగాని యెవరిని గురిచేయరాదు. అట్టి జోక్యము నుండియు, ఆ ప్రచారముల నుండియు విధి ద్వారా పరిరక్షింపబడుటకు ప్రతి యొక్కరికిని హక్కు గలదు.\nప్రతి వ్యక్తికిని భావస్వాతంత్ర్య, అంతఃకరణస్వాతంత్ర్య, మతస్వాతంత్ర్యములకు హక్కు గలదు. తన మతమును ప్రత్యయమును మార్చుకొనుటయును, ఒంటరిగ గాని, సాంఘికముగ గాని, బహిరంగముగను, ఆంతరంగికముగను ఉపదేశ, అనుష్ఠాన, ఆరాధన, ఆచరణలచే తన మతప్రత్యయములను వ్యక్తీకరించుటయును, ఈ హక్కులో నిమిదియున్నవి."
  specimen_16: "ప్రతి వ్యక్తికిని అభిప్రాయస్వాతంత్ర్యమునకును, భావ ప్రకటన స్వాతంత్ర్యమునకును, హక్కు గలదు. పరుల జోక్యము లేక, స్వాభిప్రాయమును గలిగియుండుటకు స్వాతంత్ర్యమును, రాజ్యసీమానిరపేక్షముగా, నెట్టి మధ్యస్థ మార్గముననైన సమాచార, సంసూచనలను అన్వేషించుటకు, పొందుటకు, ఉపపాదించుటకు, స్వాతంత్ర్యమును ఈ హక్కులో నిమిదియున్నవి.\nసంఘమునందలి సభ్యుడుగా, ప్రతి వ్యక్తికిని సామాజిక రక్షకు హక్కు గలదు. రాష్ట్రీయ ప్రయత్న, అంతర్ రాష్ట్రీయ సహకారముల ద్వారా, ప్రతి రాజ్యముయొక్కయు వ్యవస్థాపనా సాధన సామగ్రి ననుసరించి, తన ప్రతిపత్తికిని తన వ్యక్తిత్వముయొక్క స్వేచ్ఛాభివృద్ధికిని అత్యావశ్యకములయిన, ఆర్థిక , సాంఘిక, సాంస్కృతిక స్వత్వముల సంపాదనకు అతనికి అధికారము గలదు.\nపని కాలము యొక్క యుక్తపరిమితత్వమునకును, వేతన సహితములగు నియతకాలికములయిన సెలవు దినములకును, విశ్రాంతి విరామములకును, ప్రతి వ్యక్తికిని హక్కు గలదు.\nఈ ప్రకటన యందు పొందుపరుపబడియున్న స్వత్వ స్వాతంత్ర్యములు సంపూర్ణముగా సిద్ధింపగల ఒక సాంఘిక అంతర్ -రాష్ట్రీయవ్యవస్థకు, ప్రతి వ్యక్తికి నధికారము గలదు."
}
