id: "tem"
language: "tem"
script: "Latn"
name: "Timne"
autonym: "KʌThemnɛ"
population: 1722481
region: "SL"
exemplar_chars {
  base: "A Ʌ B D E Ɛ Ə F G H I K L M N Ŋ O Ɔ P R S T U W a ʌ b d e ɛ ə f g h i k l m n ŋ o ɔ p r s t u w"
}
sample_text {
  masthead_full: "AaKk"
  masthead_partial: "Oo"
  styles: "Ɔwa ta salata kʌsɔthnɛ ʌyiki a komʌnɛ aŋ"
  tester: "Ɔwa, kʌ kʌlʌ agbʌp yi kʌsay ʌmari ma aŋfəm akəpet mʌ po kʌrʌ kʌdifəthʌnɛ"
  poster_sm: "Ɔwa a yi təkə"
  poster_md: "Ɔwa rokɔm"
  poster_lg: "kom"
  specimen_48: "Ɔwa aŋpo bɛŋ tə kəyi kʌsɔthnɛ ʌmari ʌme yi rʌwankom ʌre, yʌ yi"
  specimen_36: "Wuni o wuni ɔ ba ʌmari kʌmʌ a thonkanɛ kɔ ta bepi wuni o wuni ɔ kʌthi kɔ ʌmari mɔŋ ka rəwuni kəpet kətaŋʌnɛ ka ʌŋ thɔ."
  specimen_32: "A yi təkə sɔŋ wuni o wuni ʌfɛrɛ ʌthənʌnɛ suʌ kɔ ɛləŋs ka ʌŋbare ŋa ʌŋthonkas gberkethe mə te yɔ ʌgbʌy ka kʌgbɛngbɛn ʌmari mɔŋ yi ʌŋgbɛthɛ ŋɔŋ, yi mʌləs thalɔm tʌləs a pa tɔ yɔ‐e."
  specimen_21: "A yɛ təkə bot kəsəŋ ka ʌŋgbundu, ʌŋbɔnshɔ, mʌyirʌ thalɔm ʌte mɔ gbal, ɔwa kəsambos ayiki tɔŋ yi ʌŋes ŋɔ ʌfinɔ. Ɔwa wuni o wuni ba ʌmari ma kʌ yɔ ʌŋthɔ ʌŋ chimʌ kɔ ka ʌŋe mə bot kɔ kəsəŋ‐e.\nWuni o wuni ɔ ba ʌmari ma rʌwankom ra kʌtəmtəmnɛ to ɔ yema, ɛnanɛ yɔŋ yi ʌŋdina ɔ yema wop‐e. Wa ɔ ba ʌmari ma kʌshinkar ʌŋdina ɔ yema, yi mʌlanɛ mɔŋ. Ɔwa ɔ ba rʌwankom ra kʌthəksʌ, kʌbʌtho, kʌtaŋʌŋɛ yi kəthəksʌ mʌlanɛ mɔŋ pəyi kɔŋ son‐o, ka ʌkələŋ kələŋ yi afəm alɔm‐o, dɛr ɔgberkethe‐o, thalɔm ka ʌŋ gbundu ŋɔŋ."
  specimen_16: "Wuni o wuni ɔ ba rʌwankom ra ʌte ɔ təmʌ yi kʌfɔf ʌte ɔ yema‐e. Ɔwa rʌwankom ʌre ɔ ba ri təkə bət ʌte ɔ nanɛ kə tə bot kɔ kə səŋ yi kəthɛns, thalɔm kəsakəthi təra yi ɛtəmtəmnɛ də roŋ o roŋ kə təkəlɛnɛ ro ɔ yi‐e.\nƆwa mʌ pəyi wuni o wuni ɔ yi kətɔŋ ka aŋfəm ʌkəpet‐e, ɔ ba ʌmari ma kʌmʌranɛ kɔ kʌmʌ pəfisa kɔ kətʌŋ ka ɛmar ya aŋthɔf, ɛmar ya tʌthɔf tətel, kətʌŋʌnɛ ka mɔ to ɔ gbəli təmʌ ukolo yi yiki kətɔŋ ka aŋkos ŋɔŋ.\nWuni o wuni ɔ ba ʌmari ma kʌfothanɛ kəwur kʌyɔ mʌpanth to ɔ yema. Ɔwa ɔ ba ʌmari ma kʌsɔŋ kɔ ʌlɔkɔ mɔ fothanɛ ʌlɔkɔ o lɔkɔ.\nƆwa wuni o wuni ɔ ba ʌmari ma kʌtʌŋʌnɛ ʌŋe ɔ yema pəyi ka aŋthɔf ŋɔŋ rəkor‐o, thaɔm rə təthof tətel ro mɔ gbəli sɔthɔ ʌŋfɛrɛ ŋa ka sɔthɔ mʌtʌy ʌme bɛ a gbal ka mʌsekrʌnɛ ʌme ka rʌwʌnkom rɔŋ kəyankaŋ."
}
