id: "teo"
language: "teo"
script: "Latn"
name: "Teso"
autonym: "Ateso"
population: 2082973
region: "KE"
region: "UG"
exemplar_chars {
  base: "a b c d e g h i j k l m n o p r s t u v w x y"
  auxiliary: "f q z"
  index: "A B C D E G H I J K L M N O P R S T U V W X Y"
}
sample_text {
  fallback_language: "en"
}
