id: "tg"
language: "tg"
script: "Cyrl"
name: "Tajik"
autonym: "Тоҷикӣ"
population: 8873670
region: "TJ"
exemplar_chars {
  base: "а б в г ғ д е ё ж з и ӣ й к қ л м н о п р с т у ӯ ф х ҳ ч ҷ ш ъ э ю я"
  auxiliary: "ц щ ы ь"
  marks: "◌̄ ◌̆ ◌̈"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ \" “ ” ( ) [ ] § @ * / & # † ‡ ′ ″"
  index: "А Б В Г Ғ Д Е Ё Ж З И Ӣ Й К Қ Л М Н О П Р С Т У Ӯ Ф Х Ҳ Ч Ҷ Ш Ъ Э Ю Я"
}
sample_text {
  masthead_full: "ТтАа"
  masthead_partial: "Мм"
  styles: "Бо дарназардошти ин, ки этирофи қадру қимат"
  tester: "бо дарназардошти ин, ки таҳкиру беэътиноӣ ба ҳуқуқи башар боиси"
  poster_sm: "Ассамблеяи"
  poster_md: "давлатҳо"
  poster_lg: "Тамоми"
  specimen_48: "Тамоми одамон озод ва аз лиҳози шарафу ҳуқуқ ба ҳам баробар ба"
  specimen_36: "Ҳеҷ кас набояд дар ғуломӣ ё ҳолати маҷбурӣ нигоҳ дошта шавад; ғуломӣ ва ғуломфурӯшӣ дар ҳамаи навъҳои онҳо маън аст."
  specimen_32: "Ҳар як инсон дар сурати поймол гардидани ҳуқуқҳои асосии ӯ, ки бо Конститутсия ё қонун пешбинӣ шудаанд, барои барқарорсозии пурраи онҳо аз тарафи судҳои босалоҳияти миллӣ ҳақ дорад."
  specimen_21: "Ҳеҷ касро худсарона дастгир, ҳабс ё бадарға кардан мумкин нест.\nҲар як инсон барои муайян намудани ҳуқуқу ӯхдадориҳояш ва муқаррар кардани асоснокии айбномаи ҷинояте, ки ба дӯши ӯ гузошта шудааст, ба таври баробарии комил ҳуқуқ дорад, ки парванди ӯро суди мустақилу бетараф ошкоро ва бо риояи талаботи адолат баррасӣ намояд."
  specimen_16: "Ба ҳаёти шахсӣ ва оилавии ҳеҷ як фард дахолати худсарона намудан ва ба дахлнопазирии манзил, сирри мукотибот, шараф ва обрӯи ӯ худсарона сӯиқасд кардан мумкин нест. Ҳар як инсон ҳуқуқ дорад, ки дар мавриди чунин мудохила ё сӯиқасд аз ҳимояи қонун истифода намояд.\nҲар як инсон ба озодии фикр, виҷдон ва дин ҳуқуқ дорад; ин ҳуқуқ аз тағйири озодонаи дин ва эътиқод, пайравии озодонаи дин ё эътиқоди худ чи бо тартиби инфиродӣ ва чи якҷоя бо дигарон, ба таври оммавӣ ё хусусӣ, дар таълим гирифтан, ибодат намудан ва расму оинҳои динӣ ва маросимиро иҷро кардан иборат аст."
}
