id: "th"
name: "Thai"
preferred_name: ""
autonym: "ภาษาไทย"
population: 55181920
region: "TH"
script: "Thai"
exemplar_chars {
  base: "ก ข ฃ ค ฅ ฆ ง จ ฉ ช ซ ฌ ญ ฎ ฏ ฐ ฑ ฒ ณ ด ต ถ ท ธ น บ ป ผ ฝ พ ฟ ภ ม ย ร ล ว ศ ษ ส ห ฬ อ ฮ ะ า เ โ ใ ไ ฤ ๅ ฦ"
  auxiliary: "\\u200B"
  marks: "◌̍ ◌̎ ◌ั ◌ิ ◌ุ ◌ู ◌็ ◌ํ"
  numerals: "๐ ๑ ๒ ๓ ๔ ๕ ๖ ๗ ๘ ๙ 0 1 2 3 4 5 6 7 8 9"
  punctuation: "๏ ๛"
  index: "ก ข ฃ ค ฅ ฆ ง จ ฉ ช ซ ฌ ญ ฎ ฏ ฐ ฑ ฒ ณ ด ต ถ ท ธ น บ ป ผ ฝ พ ฟ ภ ม ย ร ฤ ล ฦ ว ศ ษ ส ห ฬ อ ฮ"
}
sample_text {
  masthead_full: "มนษย"
  masthead_partial: "ทง"
  tester: "โดยที่การยอมรับศักดิ์ศรีแต่กำเนิด และสิทธิที่เท่าเทียมกันและที่ไม่อาจเพิกถอนได้ของสมาชิกทั้งมวลแห่งครอบครัวมนุษยชาติ"
  poster_sm: "โดยที่เป็นการจำเป"
  poster_md: "ฉะนั้น บัดนี้"
  poster_lg: "อาทิ"
  specimen_48: "มนุษย์ทั้งปวงเกิดมามีอิสระและเสมอภาคกันในศักดิ์ศรีและสิทธิ ต่างในตนมีเหตุผลและมโนธรรม"
  specimen_36: "ทุกคนมีสิทธิที่จะได้รับการเยียวยาอันมีประสิทธิผลจากศาลที่มีอำนาจแห่งรัฐต่อการกระทำอันล่วงละเมิดสิทธิขั้นพื้นฐาน ซึ่งตนได้รับตามรัฐธรรมนูญหรือกฎหมาย"
  specimen_32: "ทุกคนย่อมมีสิทธิในความเสมอภาคอย่างเต็มที่ในการได้รับการพิจารณาคดีที่เป็นธรรมและเปิดเผยจากศาลที่อิสระและไม่ลำเอียง ในการพิจารณากำหนดสิทธิและหน้าที่ของตนและข้อกล่าวหาอาญาใดต่อตน"
  specimen_21: "บุคคลใดจะถูกแทรกแซงตามอำเภอใจในความเป็นส่วนตัว ครอบครัว ที่อยู่อาศัย หรือการสื่อสาร หรือจะถูกลบหลู่เกียรติยศและชื่อเสียงไม่ได้ ทุกคนมีสิทธิที่จะได้รับความคุ้มครองของกฎหมายต่อการแทรกแซงสิทธิหรือการลบหลู่ดังกล่าวนั้น\nทุกคนมีสิทธิในอิสรภาพแห่งความคิด มโนธรรม และศาสนา ทั้งนี้ สิทธินี้รวมถึงอิสรภาพในการเปลี่ยนศาสนาหรือความเชื่อ และอิสรภาพในการแสดงออกทางศาสนาหรือความเชื่อถือของตนในการสอน การปฏิบัติ การสักการะบูชา และการประกอบพิธีกรรม ไม่ว่าจะโดยลำพังหรือในชุมชนร่วมกับผู้อื่น และในที่สาธารณะหรือส่วนบุคคล"
  specimen_16: "ทุกคนมีสิทธิในอิสรภาพแห่งความเห็นและการแสดงออก ทั้งนี้ สิทธินี้รวมถึงอิสรภาพที่จะถือเอาความเห็นโดยปราศจากการแทรกแซง และที่จะแสวงหา รับและส่งข้อมูลข่าวสารและข้อคิดผ่านสื่อใด และโดยไม่คำนึงถึงพรมแดน\nทุกคน ในฐานะสมาชิกของสังคม มีสิทธิในหลักประกันทางสังคม และย่อมมีสิทธิในการบรรลุสิทธิทางเศรษฐกิจ สังคม และวัฒนธรรม อันจำเป็นยิ่งสำหรับศักดิ์ศรีของตน และการพัฒนาบุคลิกภาพของตนอย่างอิสระ ผ่านความพยายามของรัฐและความร่วมมือระหว่างประเทศ และตามการจัดการและทรัพยากรของแต่ละรัฐ\nทุกคนมีสิทธิในการพักผ่อนและการผ่อนคลายยามว่าง รวมทั้งจำกัดเวลาทำงานตามสมควร และวันหยุดเป็นครั้งคราวโดยได้รับค่าจ้าง\nทุกคนย่อมมีสิทธิในระเบียบทางสังคมและระหว่างประเทศ ซึ่งจะเป็นกรอบให้บรรลุสิทธิและอิสรภาพที่กำหนดไว้ในปฏิญญานี้อย่างเต็มที่"
}
