id: "thf_Deva"
language: "thf"
script: "Deva"
name: "Thangmi, Devanagari"
region: "NP"
sample_text {
  masthead_full: "सकखम"
  masthead_partial: "पर"
  styles: "साक्खा मि प्रतिष्ठा ङा हिक्काको आधारङा नि वित्तिकाई स्वतन्त्र ङा"
  tester: "साक्खा मि प्रतिष्ठा ङा हिक्काको आधारङा नि वित्तिकाई स्वतन्त्र ङा थादु। तोबाङ बुद्धि ङा विवेक नामा"
  poster_sm: "साक्खा मि प्रतिष्ठा"
  poster_md: "साक्खा मि प्रत"
  poster_lg: "साक्खा"
  specimen_48: "साक्खा मि प्रतिष्ठा ङा हिक्काको आधारङा नि वित्तिकाई स्वतन्त्र ङा थादु। तोबाङ बुद्धि ङा विवेक नामा केल्योङ्दु"
  specimen_36: "साक्खा मि प्रतिष्ठा ङा हिक्काको आधारङा नि वित्तिकाई स्वतन्त्र ङा थादु। तोबाङ बुद्धि ङा विवेक नामा केल्योङ्दु थादु ङा दि बेगाले नामा हु हु को व्यवहार नोङ्को माईदु।"
  specimen_32: "साक्खा मि प्रतिष्ठा ङा हिक्काको आधारङा नि वित्तिकाई स्वतन्त्र ङा थादु। तोबाङ बुद्धि ङा विवेक नामा केल्योङ्दु थादु ङा दि बेगाले नामा हु हु को व्यवहार नोङ्को माईदु।"
  specimen_21: "साक्खा मि प्रतिष्ठा ङा हिक्काको आधारङा नि वित्तिकाई स्वतन्त्र ङा थादु। तोबाङ बुद्धि ङा विवेक नामा केल्योङ्दु थादु ङा दि बेगाले नामा हु हु को व्यवहार नोङ्को माईदु।\nसाक्खा मि प्रतिष्ठा ङा हिक्काको आधारङा नि वित्तिकाई स्वतन्त्र ङा थादु। तोबाङ बुद्धि ङा विवेक नामा केल्योङ्दु थादु ङा दि बेगाले नामा हु हु को व्यवहार नोङ्को माईदु।\nसाक्खा मि प्रतिष्ठा ङा हिक्काको आधारङा नि वित्तिकाई स्वतन्त्र ङा थादु। तोबाङ बुद्धि ङा विवेक नामा केल्योङ्दु थादु ङा दि बेगाले नामा हु हु को व्यवहार नोङ्को माईदु।"
  specimen_16: "साक्खा मि प्रतिष्ठा ङा हिक्काको आधारङा नि वित्तिकाई स्वतन्त्र ङा थादु। तोबाङ बुद्धि ङा विवेक नामा केल्योङ्दु थादु ङा दि बेगाले नामा हु हु को व्यवहार नोङ्को माईदु।\nसाक्खा मि प्रतिष्ठा ङा हिक्काको आधारङा नि वित्तिकाई स्वतन्त्र ङा थादु। तोबाङ बुद्धि ङा विवेक नामा केल्योङ्दु थादु ङा दि बेगाले नामा हु हु को व्यवहार नोङ्को माईदु।\nसाक्खा मि प्रतिष्ठा ङा हिक्काको आधारङा नि वित्तिकाई स्वतन्त्र ङा थादु। तोबाङ बुद्धि ङा विवेक नामा केल्योङ्दु थादु ङा दि बेगाले नामा हु हु को व्यवहार नोङ्को माईदु।\nसाक्खा मि प्रतिष्ठा ङा हिक्काको आधारङा नि वित्तिकाई स्वतन्त्र ङा थादु। तोबाङ बुद्धि ङा विवेक नामा केल्योङ्दु थादु ङा दि बेगाले नामा हु हु को व्यवहार नोङ्को माईदु।\nसाक्खा मि प्रतिष्ठा ङा हिक्काको आधारङा नि वित्तिकाई स्वतन्त्र ङा थादु। तोबाङ बुद्धि ङा विवेक नामा केल्योङ्दु थादु ङा दि बेगाले नामा हु हु को व्यवहार नोङ्को माईदु।\nसाक्खा मि प्रतिष्ठा ङा हिक्काको आधारङा नि वित्तिकाई स्वतन्त्र ङा थादु। तोबाङ बुद्धि ङा विवेक नामा केल्योङ्दु थादु ङा दि बेगाले नामा हु हु को व्यवहार नोङ्को माईदु।"
}
