id: "tiw_Latn"
language: "tiw"
script: "Latn"
name: "Tiwi, Latin"
sample_text {
  masthead_full: "TtAa"
  masthead_partial: "Yy"
  styles: "Tayikuwapimulungurrumi wutailapwarrigi-jiki"
  tester: "Tayikuwapimulungurrumi wutailapwarrigi-jiki arnuka kiyi wutaakiyamama"
  poster_sm: ""
  poster_md: ""
  poster_lg: "arnuka"
  specimen_48: ""
  specimen_36: ""
  specimen_32: "Tayikuwapimulungurrumi wutailapwarrigi-jiki arnuka kiyi wutaakiyamama kwiyi tiwi-ma kiyi rayit. Wuta-wurlimi pungintaga kiyi punyipunyi kiyi wiyi tuwim-ajirri nginingaji pirajuwi."
  specimen_21: "Tayikuwapimulungurrumi wutailapwarrigi-jiki arnuka kiyi wutaakiyamama kwiyi tiwi-ma kiyi rayit. Wuta-wurlimi pungintaga kiyi punyipunyi kiyi wiyi tuwim-ajirri nginingaji pirajuwi.\nTayikuwapimulungurrumi wutailapwarrigi-jiki arnuka kiyi wutaakiyamama kwiyi tiwi-ma kiyi rayit. Wuta-wurlimi pungintaga kiyi punyipunyi kiyi wiyi tuwim-ajirri nginingaji pirajuwi."
  specimen_16: "Tayikuwapimulungurrumi wutailapwarrigi-jiki arnuka kiyi wutaakiyamama kwiyi tiwi-ma kiyi rayit. Wuta-wurlimi pungintaga kiyi punyipunyi kiyi wiyi tuwim-ajirri nginingaji pirajuwi.\nTayikuwapimulungurrumi wutailapwarrigi-jiki arnuka kiyi wutaakiyamama kwiyi tiwi-ma kiyi rayit. Wuta-wurlimi pungintaga kiyi punyipunyi kiyi wiyi tuwim-ajirri nginingaji pirajuwi.\nTayikuwapimulungurrumi wutailapwarrigi-jiki arnuka kiyi wutaakiyamama kwiyi tiwi-ma kiyi rayit. Wuta-wurlimi pungintaga kiyi punyipunyi kiyi wiyi tuwim-ajirri nginingaji pirajuwi.\nTayikuwapimulungurrumi wutailapwarrigi-jiki arnuka kiyi wutaakiyamama kwiyi tiwi-ma kiyi rayit. Wuta-wurlimi pungintaga kiyi punyipunyi kiyi wiyi tuwim-ajirri nginingaji pirajuwi."
}
