id: "tjs_Latn"
language: "tjs"
script: "Latn"
name: "(Bizisa"
sample_text {
  masthead_full: "NnOo"
  masthead_partial: "Vv"
  styles: "N\no\nv\nd\ni\ne\nx\n \nn\no\nn\ng\nv\n \nl\ni\ne\nx\n \nh\nu"
  tester: "N\no\nv\nd\ni\ne\nx\n \nn\no\nn\ng\nv\n \nl\ni\ne\nx\n \nh\nu\nf\nn\ni\nv\n \nd\na\nv\n \nz"
  poster_sm: "N\no\nv\nd\ni\ne"
  poster_md: "N\no\nv\nd\ni"
  poster_lg: "N\no"
  specimen_48: "N\no\nv\nd\ni\ne\nx\n \nn\no\nn\ng\nv\n \nl\ni\ne\nx\n \nh\nu\nf\nn\ni\nv\n \nd\na\nv\n \nz"
  specimen_36: "N\no\nv\nd\ni\ne\nx\n \nn\no\nn\ng\nv\n \nl\ni\ne\nx\n \nh\nu\nf\nn\ni\nv\n \nd\na\nv\n \nz\ne\nr\n \nn\ni\ne\nr\n,\n \nz\nu\nn\nx\ny\na\nn\nr\n \nn\ni"
  specimen_32: "N\no\nv\nd\ni\ne\nx\n \nn\no\nn\ng\nv\n \nl\ni\ne\nx\n \nh\nu\nf\nn\ni\nv\n \nd\na\nv\n \nz\ne\nr\n \nn\ni\ne\nr\n,\n \nz\nu\nn\nx\ny\na\nn\nr\n \nn\ni\ne\nx\n \nq\ni\na\nn\nr\nl\ni\nr\n \ng\na\nr\nh\na\nf\n \nh"
  specimen_21: "N\no\nv\nd\ni\ne\nx\n \nn\no\nn\ng\nv\n \nl\ni\ne\nx\n \nh\nu\nf\nn\ni\nv\n \nd\na\nv\n \nz\ne\nr\n \nn\ni\ne\nr\n,\n \nz\nu\nn\nx\ny\na\nn\nr\n \nn\ni\ne\nx\n \nq\ni\na\nn\nr\nl\ni\nr\n \ng\na\nr\nh\na\nf\n \nh\nu\nf\nn\ni\nv\n \nd\na\nv\n \nz\ne\nr\n \nn\ni\ne\nr\n.\n \nG\ni\nx\nz\ne\nx\n \nl\ni\nv\nx\ni\nn\nf\n \nn\ni\ne\nx\n \nl\ni\na\nn\nr\nx\ni\nn\nx\n \nx\ni\ne\nf\n,\n \nx\ni\no\nn\ng\nx\nd\ni\nf\n \ng\nu\na\nn\nx\nx\ni\nf\n \nn\ni\ne\nr\n \nj"
  specimen_16: "N\no\nv\nd\ni\ne\nx\n \nn\no\nn\ng\nv\n \nl\ni\ne\nx\n \nh\nu\nf\nn\ni\nv\n \nd\na\nv\n \nz\ne\nr\n \nn\ni\ne\nr\n,\n \nz\nu\nn\nx\ny\na\nn\nr\n \nn\ni\ne\nx\n \nq\ni\na\nn\nr\nl\ni\nr\n \ng\na\nr\nh\na\nf\n \nh\nu\nf\nn\ni\nv\n \nd\na\nv\n \nz\ne\nr\n \nn\ni\ne\nr\n.\n \nG\ni\nx\nz\ne\nx\n \nl\ni\nv\nx\ni\nn\nf\n \nn\ni\ne\nx\n \nl\ni\na\nn\nr\nx\ni\nn\nx\n \nx\ni\ne\nf\n,\n \nx\ni\no\nn\ng\nx\nd\ni\nf\n \ng\nu\na\nn\nx\nx\ni\nf\n \nn\ni\ne\nr\n \nj\ni\nn\nx\ns\ne\nn\nr\n \ng\no\nf\n \nd\na\nv\n \nd\nu\ni\nf\nd\na\ni\nf\n \nd\no\nr\n.\nN\no\nv\nd\ni\ne\nx\n \nn\no\nn\ng\nv\n \nl\ni\ne\nx\n \nh\nu\nf\nn\ni\nv\n \nd\na\nv\n \nz\ne\nr\n \nn\ni\ne\nr\n,\n \nz\nu\nn\nx\ny\na\nn\nr\n \nn\ni\ne\nx\n \nq\ni\na\nn\nr\nl\ni\nr\n \ng\na\nr\nh\na\nf\n \nh\nu\nf\nn\ni\nv\n \nd\na\nv\n \nz\ne\nr\n \nn\ni\ne\nr\n.\n \nG\ni\nx\nz\ne\nx\n "
}
