id: "tk"
language: "tk"
script: "Arab"
name: "Turkmen"
population: 6870838
region: "AF"
region: "IR"
region: "TM"
exemplar_chars {
  base: "a b ç d e ä f g h i j ž k l m n ň o ö p r s ş t u ü w y ý z"
  auxiliary: "c q v x"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‑ – — , ; : ! ? . … \" “ ” ( ) [ ] { } § @ * # { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "A B Ç D E Ä F G H I J Ž K L M N Ň O Ö P R S Ş T U Ü W Y Ý Z"
}
sample_text {
  fallback_language: "ar"
}
