id: "tly"
name: "Talysh"
preferred_name: ""
autonym: "Tolışi"
population: 1000168
region: "AZ"
script: "Cyrillic"
script: "Latin"
script: "Perso-Arabic"
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Ј Ғ Ҹ Ҝ Һ Ә Ы а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш ј ғ ҹ ҝ һ ә ы"
  auxiliary: "Ä ä"
  marks: "◌̆"
  numerals: "۰ ۱ ۲ ۳ ۴ ۵ ۶ ۷ ۸ ۹ 0 1 2 3 4 5 6 7 8 9"
}
sample_text {
  masthead_full: "HhƏə"
  masthead_partial: "Mm"
  tester: "Bə insoni avlodon həmməy xasbıə ləyoğətə fikfamon iyən çəvon"
  poster_sm: "Bə insoni həxon"
  poster_md: "İnsoni bə"
  poster_lg: "Həmmə"
  specimen_48: "Xəlğon arədə mehribanə munasibəton oko dastək doy vacibəti bə"
  specimen_36: "Hiç kəs bənə kolə (nokə) ya şıkrə vəziyyətədə oğəte əbıni; ğuldorəti iyən ğulə hıriyemon həmməy formondə ğədəğən kardə bedə."
  specimen_32: "Har qılə şəxsi Konstitusiyə ya ğanuni bəy doə həxon dəcvoniyə vaxtədə səlohiyətinə milliyə məhkəmon tərəfiku ıştə həxon mıdafıə karde həxış heste."
  specimen_21: "Hiç kəs ıştənbəsə bə həbs, bo qəte ya bə kuçovnə məruz mande əzıni.\nHar qılə şəxsi çəy həx iyən vəzlfon təyin kardeyo iyən bəyo handə bıə cinoyətə ittihomon əsosin be mıəyyən kardeyo, bəçəy koy mıstəğılə, bitərəfə məhkəmədə tam bərobərəti əsasədə, de oşkoəti iyən çı ədoləti həmməy tələbon çəş karde şəraitədə diyə kay həxış heste."
  specimen_16: "Hiç qılə şəxs bə şəxsiyə, xeyzonə mıdaxilə, kə-bə ənəqıniyəti, bəyəndı məktub nıvışte nunəkıliyəti, bəştə şərəfi iyən nufuzi ıştənbəsə ğəsdi məruz be əzıni. Har kəsi bə joğo mıdaxilə iyən ğəsdi çı ğanuni tərəfiku mıdafiə bey həxış heste.\nHar qılə şəxsi fikir, vicdon iyən din ozodəti həxış heste. Bı həxe ıştə dini iyən etiğati dəqış karde ozodəti, bəştə dini iyən bovə kardəyon təhsil, dıvo kay, dini iyən ritualə ayinon icro kay vaxti colinə, ya de cokəson bə ico, oşko ya fərdi şikilədə etiğad kay daxile.\nHar qılə şəxsi əğıdə iyən əy sərbəst ifadə karde ozodətiş heste; bı həxe be maneə bə əğıdə malikbe iyən informasiyon ya ideyaon devləti sərhədiku bə şıkrə nıbə de dılipiyə vasitəon nəve, ya bə dast varde, pevılo kay ozodəti daxile."
}
