id: "tly_Latn"
language: "tly"
script: "Latn"
name: "Talysh, Latin"
autonym: "Tolışi"
population: 0
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V X Y Z Ç Ö Ü Ğ Ş Ə a b c d e f g h i j k l m n o p q r s t u v x y z ç ö ü ğ İ ı ş ə ʼ"
  auxiliary: "Ä ä"
  marks: "◌̆ ◌̇ ◌̈ ◌̧"
}
sample_text {
  masthead_full: "HhƏə"
  masthead_partial: "Mm"
  styles: "Həmmə insonon bəştə ləyoğəti iyən həxonro"
  tester: "Həmmə insonon bəştə ləyoğəti iyən həxonro ozod iyən bərobər movardə"
  poster_sm: "Həmmə insonon"
  poster_md: "Həmmə"
  poster_lg: "Həmmə"
  specimen_48: "Həmmə insonon bəştə ləyoğəti iyən həxonro ozod iyən"
  specimen_36: "Həmmə insonon bəştə ləyoğəti iyən həxonro ozod iyən bərobər movardə bedən. Çəvon şuur iyən vicdon hese, əve ki, deyəndı mınasibətədə bənə bıvə rəftor kardəninin."
  specimen_32: "Həmmə insonon bəştə ləyoğəti iyən həxonro ozod iyən bərobər movardə bedən. Çəvon şuur iyən vicdon hese, əve ki, deyəndı mınasibətədə bənə bıvə rəftor kardəninin."
  specimen_21: "Həmmə insonon bəştə ləyoğəti iyən həxonro ozod iyən bərobər movardə bedən. Çəvon şuur iyən vicdon hese, əve ki, deyəndı mınasibətədə bənə bıvə rəftor kardəninin.\nHəmmə insonon bəştə ləyoğəti iyən həxonro ozod iyən bərobər movardə bedən. Çəvon şuur iyən vicdon hese, əve ki, deyəndı mınasibətədə bənə bıvə rəftor kardəninin."
  specimen_16: "Həmmə insonon bəştə ləyoğəti iyən həxonro ozod iyən bərobər movardə bedən. Çəvon şuur iyən vicdon hese, əve ki, deyəndı mınasibətədə bənə bıvə rəftor kardəninin.\nHəmmə insonon bəştə ləyoğəti iyən həxonro ozod iyən bərobər movardə bedən. Çəvon şuur iyən vicdon hese, əve ki, deyəndı mınasibətədə bənə bıvə rəftor kardəninin.\nHəmmə insonon bəştə ləyoğəti iyən həxonro ozod iyən bərobər movardə bedən. Çəvon şuur iyən vicdon hese, əve ki, deyəndı mınasibətədə bənə bıvə rəftor kardəninin.\nHəmmə insonon bəştə ləyoğəti iyən həxonro ozod iyən bərobər movardə bedən. Çəvon şuur iyən vicdon hese, əve ki, deyəndı mınasibətədə bənə bıvə rəftor kardəninin."
}
