id: "tob_Latn"
language: "tob"
script: "Latn"
name: "Toba"
sample_text {
  masthead_full: "EeNn"
  masthead_partial: "Aa"
  styles: "\'\nE\nn\na\nu\na\nc\n \nn\na\n \nn\na\na\nx\na\nt\n \ns\nh\ni"
  tester: "\'\nE\nn\na\nu\na\nc\n \nn\na\n \nn\na\na\nx\na\nt\n \ns\nh\ni\nỹ\na\nx\na\nu\na\np\ni\n \nn"
  poster_sm: "\'\nE\nn\na\nu\na"
  poster_md: "\'\nE\nn\na\nu"
  poster_lg: "\'\nE\nn"
  specimen_48: "\'\nE\nn\na\nu\na\nc\n \nn\na\n \nn\na\na\nx\na\nt\n \ns\nh\ni\nỹ\na\nx\na\nu\na\np\ni\n \nn"
  specimen_36: "\'\nE\nn\na\nu\na\nc\n \nn\na\n \nn\na\na\nx\na\nt\n \ns\nh\ni\nỹ\na\nx\na\nu\na\np\ni\n \nn\na\n \nm\na\ny\ni\np\ni\n \nh\nu\ne\ns\no\nc\nh\ni\ng\nu\ni"
  specimen_32: "\'\nE\nn\na\nu\na\nc\n \nn\na\n \nn\na\na\nx\na\nt\n \ns\nh\ni\nỹ\na\nx\na\nu\na\np\ni\n \nn\na\n \nm\na\ny\ni\np\ni\n \nh\nu\ne\ns\no\nc\nh\ni\ng\nu\ni\ni\n \nq\na\nt\na\nq\n \n\'\ne\ne\nt\na\n\'\na\n\'\nt\n \nd\na\n \nl"
  specimen_21: "\'\nE\nn\na\nu\na\nc\n \nn\na\n \nn\na\na\nx\na\nt\n \ns\nh\ni\nỹ\na\nx\na\nu\na\np\ni\n \nn\na\n \nm\na\ny\ni\np\ni\n \nh\nu\ne\ns\no\nc\nh\ni\ng\nu\ni\ni\n \nq\na\nt\na\nq\n \n\'\ne\ne\nt\na\n\'\na\n\'\nt\n \nd\na\n \nl\n\'\na\nm\na\nq\nc\nh\ni\nc\n \nq\na\nt\na\nq\n \nd\na\n \n\'\ne\nn\ne\nc\n \nq\na\nt\na\nq\n \nỹ\na\nt\na\nq\nt\na\n \nỹ\na\nỹ\na\nt\ne\n\'\nn\n \nn\na\nu\na\n \nl\na\nt\na\nx\na\nc\no\n \nq\na\nt\na\nq\n \nn\nu\na\n \nn\no\n\'\no\n\'\nn\n \nn\nv\ni"
  specimen_16: "\'\nE\nn\na\nu\na\nc\n \nn\na\n \nn\na\na\nx\na\nt\n \ns\nh\ni\nỹ\na\nx\na\nu\na\np\ni\n \nn\na\n \nm\na\ny\ni\np\ni\n \nh\nu\ne\ns\no\nc\nh\ni\ng\nu\ni\ni\n \nq\na\nt\na\nq\n \n\'\ne\ne\nt\na\n\'\na\n\'\nt\n \nd\na\n \nl\n\'\na\nm\na\nq\nc\nh\ni\nc\n \nq\na\nt\na\nq\n \nd\na\n \n\'\ne\nn\ne\nc\n \nq\na\nt\na\nq\n \nỹ\na\nt\na\nq\nt\na\n \nỹ\na\nỹ\na\nt\ne\n\'\nn\n \nn\na\nu\na\n \nl\na\nt\na\nx\na\nc\no\n \nq\na\nt\na\nq\n \nn\nu\na\n \nn\no\n\'\no\n\'\nn\n \nn\nv\ni\nl\nỹ\na\nx\na\nc\no\n,\n \nq\na\nq\n \nỹ\no\nq\no\n\'\no\ny\ni\n \ni\nu\ne\nn\n \nd\na\n \ni\n \n\'\no\no\nn\no\nl\ne\nc\n \nỹ\na\nt\na\nq\nt\na\n \ni\nt\na\nu\na\nn\n \ni\nc\nh\no\nx\no\nd\ne\nn\n \nc\na\n \nl\nỹ\na\n\'\nE\nn\na\nu\na\nc\n \nn\na\n \nn\na\na\nx\na\nt\n \ns\nh\ni\nỹ\na\nx\na\nu\na\np\ni\n \nn\na\n \nm\na\ny\ni\np\ni\n \nh\nu\ne\ns\no\nc\nh\ni\ng\nu\ni\ni\n \nq\na"
}
