id: "top_Latn"
language: "top"
script: "Latn"
name: "Totonac, Papantla"
sample_text {
  masthead_full: "WwAa"
  masthead_partial: "Kk"
  styles: "W\na\nk\ng\n \nl\na\nk\nc\nh\n\'\ni\nx\nk\nu\nw\ni\nn\n \nt\na"
  tester: "W\na\nk\ng\n \nl\na\nk\nc\nh\n\'\ni\nx\nk\nu\nw\ni\nn\n \nt\na\nl\na\nk\ng\na\nw\na\nn\n \nn"
  poster_sm: "W\na\nk\ng\n \nl"
  poster_md: "W\na\nk\ng\n "
  poster_lg: "W\na"
  specimen_48: "W\na\nk\ng\n \nl\na\nk\nc\nh\n\'\ni\nx\nk\nu\nw\ni\nn\n \nt\na\nl\na\nk\ng\na\nw\na\nn\n \nn"
  specimen_36: "W\na\nk\ng\n \nl\na\nk\nc\nh\n\'\ni\nx\nk\nu\nw\ni\nn\n \nt\na\nl\na\nk\ng\na\nw\na\nn\n \nn\na\nk\n \nk\na\n\'\nu\nn\ni\nn\n \nn\ni\nt\ni\n \nk\na\n\'\na\nk"
  specimen_32: "W\na\nk\ng\n \nl\na\nk\nc\nh\n\'\ni\nx\nk\nu\nw\ni\nn\n \nt\na\nl\na\nk\ng\na\nw\na\nn\n \nn\na\nk\n \nk\na\n\'\nu\nn\ni\nn\n \nn\ni\nt\ni\n \nk\na\n\'\na\nk\ng\nc\nh\n\'\na\np\na\nw\na\nl\ni\nn\ni\nt\n \nn\na\nc\nh\nu\nn"
  specimen_21: "W\na\nk\ng\n \nl\na\nk\nc\nh\n\'\ni\nx\nk\nu\nw\ni\nn\n \nt\na\nl\na\nk\ng\na\nw\na\nn\n \nn\na\nk\n \nk\na\n\'\nu\nn\ni\nn\n \nn\ni\nt\ni\n \nk\na\n\'\na\nk\ng\nc\nh\n\'\na\np\na\nw\na\nl\ni\nn\ni\nt\n \nn\na\nc\nh\nu\nn\na\n \nw\na\nk\ng\n \nt\na\nk\ng\n\'\na\nl\nh\ni\n \ni\nx\nt\na\nm\na\nx\na\nn\na\nt\nk\na\nn\n \nc\nh\nu\n \nt\nu\n \nk\na\nm\ni\nn\ni\nn\ni\n,\n \nj\ne\n\'\ne\n \nw\na\nn\np\n\'\nu\nt\nu\nn\n \nx\nl\na\nk\na\nt\na\n \nw\na\nk\ng\n \nt\na\nl\na\nk"
  specimen_16: "W\na\nk\ng\n \nl\na\nk\nc\nh\n\'\ni\nx\nk\nu\nw\ni\nn\n \nt\na\nl\na\nk\ng\na\nw\na\nn\n \nn\na\nk\n \nk\na\n\'\nu\nn\ni\nn\n \nn\ni\nt\ni\n \nk\na\n\'\na\nk\ng\nc\nh\n\'\na\np\na\nw\na\nl\ni\nn\ni\nt\n \nn\na\nc\nh\nu\nn\na\n \nw\na\nk\ng\n \nt\na\nk\ng\n\'\na\nl\nh\ni\n \ni\nx\nt\na\nm\na\nx\na\nn\na\nt\nk\na\nn\n \nc\nh\nu\n \nt\nu\n \nk\na\nm\ni\nn\ni\nn\ni\n,\n \nj\ne\n\'\ne\n \nw\na\nn\np\n\'\nu\nt\nu\nn\n \nx\nl\na\nk\na\nt\na\n \nw\na\nk\ng\n \nt\na\nl\na\nk\np\nu\nw\na\nn\na\nn\n,\n \nt\na\nl\na\nl\na\nk\ng\nk\n\'\na\nt\ns\na\nn\n \nl\ni\nw\na\nk\ng\n,\n \nt\na\nl\na\nk\na\ns\nk\n\'\ni\nn\ni\n \nx\nl\na\nk\na\nt\na\n \nw\na\nk\ng\n \nn\na\nt\na\nl\na\nm\na\nk\ng\nt\na\ny\na\n.\nW\na\nk\ng\n \nl\na\nk\nc\nh\n\'\ni\nx\nk\nu\nw\ni\nn\n \nt\na\nl\na\nk\ng\na\nw\na\nn\n \nn\na\nk\n \nk\na\n\'\nu\nn\ni\nn\n \nn\ni\nt\ni\n \nk\na\n\'\na\nk\ng\nc\nh"
}
