id: "tr"
language: "tr"
script: "Latn"
name: "Turkish"
autonym: "Türkçe"
population: 80191488
region: "BG"
region: "CY"
region: "DE"
region: "GR"
region: "MK"
region: "NL"
region: "RO"
region: "TR"
region: "UA"
region: "UZ"
exemplar_chars {
  base: "a b c ç d e f g ğ h ı i İ j k l m n o ö p r s ş t u ü v y z"
  auxiliary: "á à ă â å ä ã ā æ é è ĕ ê ë ē í ì ĭ î ï ī ñ ó ò ŏ ô ø ō œ q ß ú ù ŭ û ū w x ÿ"
  marks: "◌̂ ◌̆ ◌̇ ◌̈ ◌̦ ◌̧"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ \" “ ” ( ) [ ] § @ * / & # † ‡ ′ ″"
  index: "A B C Ç D E F G H I İ J K L M N O Ö P Q R S Ş T U Ü V W X Y Z"
}
sample_text {
  masthead_full: "BbÜü"
  masthead_partial: "Tt"
  styles: "İnsanlık ailesinin bütün üyelerinde bulunan"
  tester: "İnsan haklarının tanınmaması ve hor görülmesinin insanlık vicdanını"
  poster_sm: "İnsanin zulüm"
  poster_md: "Birleşmiş"
  poster_lg: "Bütün"
  specimen_48: "Üye devletlerin, Birleşmiş Milletler Teşkilatı ile işbirliği ederek"
  specimen_36: "Hiç kimse kölelik veya kulluk altında bulundurulamaz; kölelik ve köle ticareti her türlü şekliyle yasaktır."
  specimen_32: "Her şahsın kendine anayasa veya kanun ile tanınan ana haklara aykırı muamelelere karşı fiilli netice verecek şekilde milli mahkemelere müracaat hakkı vardır."
  specimen_21: "Hiç kimse keyfi olarak tutuklanamaz, alıkonulanamaz veya sürülemez.\nHerkes, haklarının, vecibelerinin veya kendisine karşı cezai mahiyette herhangi bir isnadın tespitinde, tam bir eşitlikle, davasının bağımsız ve tarafsız bir mahkeme tarafından adil bir şekilde ve açık olarak görülmesi hakkına sahiptir.\nHer şahsın dinlenmeye, eğlenmeye, bilhassa çalışma müddetinin makul surette sınırlandırılmasına ve muayyen devrelerde ücretli tatillere hakkı vardır."
  specimen_16: "Herkesin, işbu Beyannamede derpiş edilen hak ve hürriyetlerin tam tatbikini sağlayacak bir sosyal ve milletlerarası nizama hakkı vardır.\nİşbu Beyannamenin hiçbir hükmü, herhangi bir devlete, zümreye ya da ferde, bu Beyannamede ilan olunan hak ve hürriyetleri yoketmeye yönelik bir faaliyete girişme ya da eylemde bulunma hakkını verir şekilde yorumlanamaz.\nİnsanlık ailesinin bütün üyelerinde bulunan haysiyetin ve bunların eşit ve devir kabul etmez haklarının tanınması hususunun, hürriyetin, adaletin ve dünya barışının temeli olmasına,\nİnsanin zulüm ve baskıya karşı son çare olarak ayaklanmaya mecbur kalmaması için insan haklarının bir hukuk rejimi ile korunmasının esaslı bir zaruret olmasına,"
}
