id: "tr_Arab"
language: "tr"
script: "Arab"
name: "Turkish, Perso-Arabic"
population: 0
region: "AE"
region: "AF"
region: "BH"
region: "BN"
region: "CC"
region: "CM"
region: "CN"
region: "CY"
region: "DJ"
region: "DZ"
region: "EG"
region: "EH"
region: "ER"
region: "GB"
region: "ID"
region: "IL"
region: "IN"
region: "IQ"
region: "IR"
region: "JO"
region: "KE"
region: "KH"
region: "KM"
region: "KW"
region: "LB"
region: "LY"
region: "MA"
region: "ML"
region: "MN"
region: "MR"
region: "MU"
region: "NE"
region: "NG"
region: "OM"
region: "PK"
region: "PS"
region: "QA"
region: "SA"
region: "SD"
region: "SO"
region: "SS"
region: "SY"
region: "TD"
region: "TH"
region: "TJ"
region: "TN"
region: "TR"
region: "YE"
region: "YT"
sample_text {
  fallback_language: "ar"
}
