id: "tsf"
language: "tsf"
script: "Deva"
name: "Southwestern Tamang"
region: "BT"
region: "FJ"
region: "IN"
region: "MU"
region: "NP"
region: "PK"
region: "UG"
region: "ZA"
sample_text {
  fallback_language: "hi"
}
