id: "tsz_Latn"
language: "tsz"
script: "Latn"
name: "Purepecha"
sample_text {
  masthead_full: "IiAa"
  masthead_partial: "Mm"
  styles: "I\na\nm\ne\nn\nd\nu\n \nk\n\'\nu\ni\nr\ni\np\nu\ne\nc\nh\na\n "
  tester: "I\na\nm\ne\nn\nd\nu\n \nk\n\'\nu\ni\nr\ni\np\nu\ne\nc\nh\na\n \nj\na\nn\ng\nu\na\nr\nh\ni\np"
  poster_sm: "I\na\nm\ne\nn\nd"
  poster_md: "I\na\nm\ne\nn"
  poster_lg: "I\na"
  specimen_48: "I\na\nm\ne\nn\nd\nu\n \nk\n\'\nu\ni\nr\ni\np\nu\ne\nc\nh\na\n \nj\na\nn\ng\nu\na\nr\nh\ni\np"
  specimen_36: "I\na\nm\ne\nn\nd\nu\n \nk\n\'\nu\ni\nr\ni\np\nu\ne\nc\nh\na\n \nj\na\nn\ng\nu\na\nr\nh\ni\np\na\nr\ni\nn\ni\n \nk\na\n \nm\na\nj\nk\nu\n \nj\na\nr\nh\na"
  specimen_32: "I\na\nm\ne\nn\nd\nu\n \nk\n\'\nu\ni\nr\ni\np\nu\ne\nc\nh\na\n \nj\na\nn\ng\nu\na\nr\nh\ni\np\na\nr\ni\nn\ni\n \nk\na\n \nm\na\nj\nk\nu\n \nj\na\nr\nh\na\nt\ni\n \nk\na\n \nj\nu\nr\nh\ni\nm\nb\ne\nk\nu\ne\nc\nh\na"
  specimen_21: "I\na\nm\ne\nn\nd\nu\n \nk\n\'\nu\ni\nr\ni\np\nu\ne\nc\nh\na\n \nj\na\nn\ng\nu\na\nr\nh\ni\np\na\nr\ni\nn\ni\n \nk\na\n \nm\na\nj\nk\nu\n \nj\na\nr\nh\na\nt\ni\n \nk\na\n \nj\nu\nr\nh\ni\nm\nb\ne\nk\nu\ne\nc\nh\na\n \nj\ni\nn\ng\no\nn\ni\n \nk\nu\ne\nr\na\na\nŋ\na\ns\no\nn\nd\ni\nk\ns\no\n \nk\na\n,\n \nj\nu\na\nj\nt\na\nk\nu\na\nr\nh\ni\ns\nï\nn\nd\ni\nk\ns\nï\n \na\nm\nb\na\nk\ni\nt\ni\n \ne\nr\na\nt\ns\ne\nk\nu\na\n \nk\na\n \nk\na\nx\nu\nm\nb\ni\nk"
  specimen_16: "I\na\nm\ne\nn\nd\nu\n \nk\n\'\nu\ni\nr\ni\np\nu\ne\nc\nh\na\n \nj\na\nn\ng\nu\na\nr\nh\ni\np\na\nr\ni\nn\ni\n \nk\na\n \nm\na\nj\nk\nu\n \nj\na\nr\nh\na\nt\ni\n \nk\na\n \nj\nu\nr\nh\ni\nm\nb\ne\nk\nu\ne\nc\nh\na\n \nj\ni\nn\ng\no\nn\ni\n \nk\nu\ne\nr\na\na\nŋ\na\ns\no\nn\nd\ni\nk\ns\no\n \nk\na\n,\n \nj\nu\na\nj\nt\na\nk\nu\na\nr\nh\ni\ns\nï\nn\nd\ni\nk\ns\nï\n \na\nm\nb\na\nk\ni\nt\ni\n \ne\nr\na\nt\ns\ne\nk\nu\na\n \nk\na\n \nk\na\nx\nu\nm\nb\ni\nk\nu\na\n,\n \nj\na\nt\ns\ni\ns\nt\ni\nk\ns\nï\n \ne\ns\nk\na\nk\ns\nï\n \ns\ne\ns\ni\n \na\nr\nh\ni\nj\np\ne\nr\na\na\nk\na\n.\nI\na\nm\ne\nn\nd\nu\n \nk\n\'\nu\ni\nr\ni\np\nu\ne\nc\nh\na\n \nj\na\nn\ng\nu\na\nr\nh\ni\np\na\nr\ni\nn\ni\n \nk\na\n \nm\na\nj\nk\nu\n \nj\na\nr\nh\na\nt\ni\n \nk\na\n \nj\nu\nr\nh\ni\nm\nb\ne\nk\nu\ne\nc\nh\na\n \nj\ni\nn\ng\no\nn\ni\n \nk\nu\ne\nr"
}
