id: "tt"
language: "tt"
script: "Cyrl"
name: "Tatar"
autonym: "Татарча"
population: 1984108
region: "RU"
exemplar_chars {
  base: "а ә б в г д е ё ж җ з и й к л м н ң о ө п р с т у ү ф х һ ц ч ш щ ъ ы ь э ю я"
  auxiliary: "ғ қ"
  marks: "◌̆ ◌̈"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ \" “ ” ( ) [ ] § @ * / & # ′ ″"
  index: "А Ә Б В Г Д Е Ё Ж Җ З И Й К Л М Н Ң О Ө П Р С Т У Ү Ф Х Һ Ц Ч Ш Щ Ъ Ы Ь Э Ю Я"
}
sample_text {
  masthead_full: "БбАа"
  masthead_partial: "Рр"
  styles: "Кешелек гаиләсенең бөтен әгъзаларына хас"
  tester: "кеше хокукларына кимсетеп һәм җирәнеп каруның вәхшилеккә китерүен,"
  poster_sm: "җәберләүгә"
  poster_md: "Кешенең төп"
  poster_lg: "Барлык"
  specimen_48: "Берләшкен Милләтләр Оешмасы әгъзасы булган дәүләтләрнең кеше"
  specimen_36: "әлеге хокукларны һәм ирекләрне анлау бу йөкләмәләрне тулысынча үтәүдә бик зур әһәмияткә ия булуын истә тотып,"
  specimen_32: "Конституция яки закон биргән тон хокуклардан мәхрүм ителгән очракта, һәр кешенең ул хокукларын компетентлы милли судлар аша кире кайтарылып бирелүен таләп итәргә хокукы бар."
  specimen_21: "Беркем дә нигезсез рәвештә кулга алынуга, тоткарлануга, куылуга дучар ителергә тиеш түгел.\nҺәр кешенең үз хокукларын һәм бурычларын билгеләр очен һәм аны җинаять җаваплылыгына тартуның нигезле булуын ачыклар очен, туды титезлелек нигезендә үз эшенең ачык рәвештә, мөстәкыйль, гадел һәм бәйсез суд аша каралуын таләп итәргә хокукы бар."
  specimen_16: "Бер кеше дә шәхси һәм гаилә тормышына, торак иминлегенә кагылуга, язышү, хәбәрләшү серенә, абруена һәм намусына нигезсез катиашуга дучар ителергә тиеш түгел.  Шундый кысулардан, яисә дучар ителүләрдән һәр кешенең закон белән якланырга хокукы бар.\nҺәр кешенең фикер, вөҗдан һәм дин ирегенә хокукы бар; бу хокук Аллага табынуны, йола куша торган дини тәртипләрне үгәүне эченә ала, һәр кешенең бер үзе генә яисә башкалар белән бергәлән аерым рәвештә яки ачыктан-ачык үз карашларын, үз динен алыштырырга аки тотарга хокукы бар.\nҺәр кеше ялга хокуклы һәм эш көнең тиешле чикләрдә кыскартуны да кертен, ел саси түләүле ял алырга, эштән буш вакытка хокукы бар."
}
