id: "tt_Arab"
language: "tt"
script: "Arab"
name: "Tatar, Arabic"
sample_text {
  masthead_full: "نارل"
  masthead_partial: "ىق"
  styles: "ن\nا\nر\nل\nى\nق\n \nك\nه\nش\nه\nل\nا\nر\n \nد\nا\n \nآ\nز\nا"
  tester: "ن\nا\nر\nل\nى\nق\n \nك\nه\nش\nه\nل\nا\nر\n \nد\nا\n \nآ\nز\nا\nت\n \nح\nا\nم\n \nو\nز\n \nآ"
  poster_sm: "ن\nا\nر\nل\nى\nق"
  poster_md: "ن\nا\nر\nل\nى"
  poster_lg: "ن\nا"
  specimen_48: "ن\nا\nر\nل\nى\nق\n \nك\nه\nش\nه\nل\nا\nر\n \nد\nا\n \nآ\nز\nا\nت\n \nح\nا\nم\n \nو\nز\n \nآ"
  specimen_36: "ن\nا\nر\nل\nى\nق\n \nك\nه\nش\nه\nل\nا\nر\n \nد\nا\n \nآ\nز\nا\nت\n \nح\nا\nم\n \nو\nز\n \nآ\nب\nر\nو\nب\nل\nا\nر\nى\n \nح\nا\nم\n \nخ\nة\nق\nو\nق\nل\nا"
  specimen_32: "ن\nا\nر\nل\nى\nق\n \nك\nه\nش\nه\nل\nا\nر\n \nد\nا\n \nآ\nز\nا\nت\n \nح\nا\nم\n \nو\nز\n \nآ\nب\nر\nو\nب\nل\nا\nر\nى\n \nح\nا\nم\n \nخ\nة\nق\nو\nق\nل\nا\nر\nى\n \nي\nا\nع\nى\nن\nن\nا\nن\n \nت\nي\nن\nك\n \nب\nو\nل"
  specimen_21: "ن\nا\nر\nل\nى\nق\n \nك\nه\nش\nه\nل\nا\nر\n \nد\nا\n \nآ\nز\nا\nت\n \nح\nا\nم\n \nو\nز\n \nآ\nب\nر\nو\nب\nل\nا\nر\nى\n \nح\nا\nم\n \nخ\nة\nق\nو\nق\nل\nا\nر\nى\n \nي\nا\nع\nى\nن\nن\nا\nن\n \nت\nي\nن\nك\n \nب\nو\nل\nى\nﭖ\nت\nو\nا\nل\nا\nر\n,\n \nآ\nل\nا\nر\nع\nآ\n \nآ\nق\nى\nل\n \nح\nا\nم\n \nو\nة\nج\nل\nا\nي\n \nب\nى\nر\nه\nل\nك\nا\nن\n \nح\nا\nم\n \nب\nه\nر\n \nـ\nب\nه\nر\n \nس\nه\nن\nا\n \nق\nا\nر\nا\nت\nا\n \nت\nو\nع\nآ\nن\nا\nر\nﭺ\nآ\n \nم\nة\nن"
  specimen_16: "ن\nا\nر\nل\nى\nق\n \nك\nه\nش\nه\nل\nا\nر\n \nد\nا\n \nآ\nز\nا\nت\n \nح\nا\nم\n \nو\nز\n \nآ\nب\nر\nو\nب\nل\nا\nر\nى\n \nح\nا\nم\n \nخ\nة\nق\nو\nق\nل\nا\nر\nى\n \nي\nا\nع\nى\nن\nن\nا\nن\n \nت\nي\nن\nك\n \nب\nو\nل\nى\nﭖ\nت\nو\nا\nل\nا\nر\n,\n \nآ\nل\nا\nر\nع\nآ\n \nآ\nق\nى\nل\n \nح\nا\nم\n \nو\nة\nج\nل\nا\nي\n \nب\nى\nر\nه\nل\nك\nا\nن\n \nح\nا\nم\n \nب\nه\nر\n \nـ\nب\nه\nر\n \nس\nه\nن\nا\n \nق\nا\nر\nا\nت\nا\n \nت\nو\nع\nآ\nن\nا\nر\nﭺ\nآ\n \nم\nة\nن\nا\nس\nا\nب\nا\nت\nت\nا\n \nب\nو\nل\nى\nر\nع\nآ\n \nت\nى\nه\nش\nل\nا\nر\n.\nن\nا\nر\nل\nى\nق\n \nك\nه\nش\nه\nل\nا\nر\n \nد\nا\n \nآ\nز\nا\nت\n \nح\nا\nم\n \nو\nز\n \nآ\nب\nر\nو\nب\nل\nا\nر\nى\n \nح\nا\nم\n \nخ\nة\nق\nو\nق\nل\nا\nر\nى\n \nي\nا\nع\nى\nن\nن\nا\nن\n \nت\nي\nن\nك\n \nب\nو\nل\nى\nﭖ\nت\nو\nا\nل\nا\nر\n,\n \nآ\nل\nا\nر\nع\nآ\n \nآ\nق\nى\nل\n \nح\nا\nم\n \nو\nة\nج\nل"
}
