id: "tyv"
language: "tyv"
script: "Cyrl"
name: "Tuvinian"
autonym: "Тыва"
population: 184238
region: "RU"
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я Ё Ң Ү Ө а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я ё ң ү ө"
  marks: "◌̆ ◌̈"
}
sample_text {
  masthead_full: "БбҮү"
  masthead_partial: "Гг"
  styles: "Кижи төрелгетен аймааның бүгү кежигүннериниң"
  tester: "кижиниң эргелеринге тоомча чок болгаш көөр хөөн чок чоруктуң"
  poster_sm: "чоннар аразынга"
  poster_md: "Каттышкан"
  poster_lg: "Бүгү"
  specimen_48: "кежигүн-күрүнелерниң Каттышкан Нациялар Организациязы-биле кады"
  specimen_36: "Кым-даа кулданыгга азы хостуг эвес байдалга туттунмас ужурлуг; кулданыгның болгаш кул садарының бүгү хевирлери хоруглуг."
  specimen_32: "Кижи бүрүзү дыштанылгага база хостуг үеге эргелиг, ооң иштинде  ажыл хүнүн  шын кызыгаарлаарынга база  өйлеп-өйлеп  бээр төлевирлиг  шөлээге  эргелиг."
  specimen_21: "Кижи бүрүзү ук Угуулгада айыттынган эргелер болгаш хосталгаларны долузу-биле хандырып турар социал болгаш улустар аразының корум-чурумунга эргелиг.\nУк Угуулгада чүү-даа чүве кайы-бир күрүнеге, бөлүкке азы тус кижилерге ук Угуулгада айыттынган эргелер болгаш хосталгаларны узуткаарынче угланган ажылдар чорударынга азы кылдыныглар кылырынга эрге берип турар деп  тайылбырлаттынып болбас."
  specimen_16: "Кижи төрелгетен аймааның бүгү кежигүннериниң  кижи мөзүзүн, оларның дең болгаш казып болбас эргелерин хүлээп көөрү хосталганың, чөптүг чоруктуң база бүгү-ниити тайбыңның үндезини болурун кичээнгейге албышаан; база\nкижиниң эргелеринге тоомча чок болгаш көөр хөөн чок чоруктуң кижи төрелгетенниң сагыжын аартып дүвүреткен дерзии үүлгедиглерге чедиргенин база кижилер  сөстүң болгаш үзелдерниң   хосталгазынга эргелиг, коргуушкун болгаш түрегделден хостуг  делегейни тургузары кижилерниң бедик чүткүлү кылдыр чарлаттынганын  кичээнгейге албышаан; база\nчоннар аразынга эп-найыралдыг харылзааларның сайзыралын деткиириниң эргежок чугулазын кичээнгейге албышаан; база"
}
