id: "tzh_Latn"
language: "tzh"
script: "Latn"
name: "Tzeltal, Oxchuc"
sample_text {
  masthead_full: "SsPp"
  masthead_partial: "Ii"
  styles: "Spisil winiketik te ya xbejk´ajik ta k´inalil"
  tester: "Spisil winiketik te ya xbejk´ajik ta k´inalil ay jrerechotik, mayuk"
  poster_sm: ""
  poster_md: ""
  poster_lg: "Spisil"
  specimen_48: "Spisil winiketik te ya xbejk´ajik ta k´inalil ay jrerechotik, mayuk mach´a"
  specimen_36: ""
  specimen_32: ""
  specimen_21: "Spisil winiketik te ya xbejk´ajik ta k´inalil ay jrerechotik, mayuk mach´a chukul ya xbejka, ya jnatik stojol te jpisiltik ay snopibal sok sbijil joltik, ja´ me k´ux ya kaibatik ta jujun tul.\nSpisil winiketik te ya xbejk´ajik ta k´inalil ay jrerechotik, mayuk mach´a chukul ya xbejka, ya jnatik stojol te jpisiltik ay snopibal sok sbijil joltik, ja´ me k´ux ya kaibatik ta jujun tul."
  specimen_16: "Spisil winiketik te ya xbejk´ajik ta k´inalil ay jrerechotik, mayuk mach´a chukul ya xbejka, ya jnatik stojol te jpisiltik ay snopibal sok sbijil joltik, ja´ me k´ux ya kaibatik ta jujun tul.\nSpisil winiketik te ya xbejk´ajik ta k´inalil ay jrerechotik, mayuk mach´a chukul ya xbejka, ya jnatik stojol te jpisiltik ay snopibal sok sbijil joltik, ja´ me k´ux ya kaibatik ta jujun tul.\nSpisil winiketik te ya xbejk´ajik ta k´inalil ay jrerechotik, mayuk mach´a chukul ya xbejka, ya jnatik stojol te jpisiltik ay snopibal sok sbijil joltik, ja´ me k´ux ya kaibatik ta jujun tul.\nSpisil winiketik te ya xbejk´ajik ta k´inalil ay jrerechotik, mayuk mach´a chukul ya xbejka, ya jnatik stojol te jpisiltik ay snopibal sok sbijil joltik, ja´ me k´ux ya kaibatik ta jujun tul."
}
