id: "tzo_Latn"
language: "tzo"
script: "Latn"
name: "Tzotzil, Chamula"
sample_text {
  masthead_full: "SsKk"
  masthead_partial: "Oo"
  styles: "S\nk\no\nt\no\nl\n \nv\ni\nn\ni\nk\n \no\n \na\nn\nt\ns\n \nt"
  tester: "S\nk\no\nt\no\nl\n \nv\ni\nn\ni\nk\n \no\n \na\nn\nt\ns\n \nt\na\n \ns\np\ne\nj\ne\nl\n \nb"
  poster_sm: "S\nk\no\nt\no\nl"
  poster_md: "S\nk\no\nt\no"
  poster_lg: "S\nk"
  specimen_48: "S\nk\no\nt\no\nl\n \nv\ni\nn\ni\nk\n \no\n \na\nn\nt\ns\n \nt\na\n \ns\np\ne\nj\ne\nl\n \nb"
  specimen_36: "S\nk\no\nt\no\nl\n \nv\ni\nn\ni\nk\n \no\n \na\nn\nt\ns\n \nt\na\n \ns\np\ne\nj\ne\nl\n \nb\na\nl\nu\nm\ni\nl\ne\n \nk\n’\no\nl\ne\nm\n \nx\n-\nh\na\ny\na"
  specimen_32: "S\nk\no\nt\no\nl\n \nv\ni\nn\ni\nk\n \no\n \na\nn\nt\ns\n \nt\na\n \ns\np\ne\nj\ne\nl\n \nb\na\nl\nu\nm\ni\nl\ne\n \nk\n’\no\nl\ne\nm\n \nx\n-\nh\na\ny\na\nn\n \ni\n \nk\no\n’\no\nl\n \nt\na\n \ns\nc\nh\n’\nu\nl\na\nl"
  specimen_21: "S\nk\no\nt\no\nl\n \nv\ni\nn\ni\nk\n \no\n \na\nn\nt\ns\n \nt\na\n \ns\np\ne\nj\ne\nl\n \nb\na\nl\nu\nm\ni\nl\ne\n \nk\n’\no\nl\ne\nm\n \nx\n-\nh\na\ny\na\nn\n \ni\n \nk\no\n’\no\nl\n \nt\na\n \ns\nc\nh\n’\nu\nl\na\nl\n \ni\n \ns\nd\ne\nr\ne\nc\nh\no\ne\nt\ni\nk\n \ni\n,\n \ns\nk\no\nt\no\nl\n \nk\n’\nu\nx\n-\ne\nl\na\nn\n \no\ny\ni\nk\ne\n \no\ny\n \ns\nr\na\ns\no\nn\ni\nk\n \ny\n \ns\nl\ne\nk\ni\nl\na\nl\ni\nk\n,\n \ns\nv\ne\nn\nt\na\n \ns\nk\nu\nx\ni\nj\ni"
  specimen_16: "S\nk\no\nt\no\nl\n \nv\ni\nn\ni\nk\n \no\n \na\nn\nt\ns\n \nt\na\n \ns\np\ne\nj\ne\nl\n \nb\na\nl\nu\nm\ni\nl\ne\n \nk\n’\no\nl\ne\nm\n \nx\n-\nh\na\ny\na\nn\n \ni\n \nk\no\n’\no\nl\n \nt\na\n \ns\nc\nh\n’\nu\nl\na\nl\n \ni\n \ns\nd\ne\nr\ne\nc\nh\no\ne\nt\ni\nk\n \ni\n,\n \ns\nk\no\nt\no\nl\n \nk\n’\nu\nx\n-\ne\nl\na\nn\n \no\ny\ni\nk\ne\n \no\ny\n \ns\nr\na\ns\no\nn\ni\nk\n \ny\n \ns\nl\ne\nk\ni\nl\na\nl\ni\nk\n,\n \ns\nv\ne\nn\nt\na\n \ns\nk\nu\nx\ni\nj\ni\nk\n \nl\ne\nk\nn\nó\no\n \nt\na\n \nj\nu\n \nj\nu\nn\n \nj\nu\n \nj\nu\n \nv\no\n.\nS\nk\no\nt\no\nl\n \nv\ni\nn\ni\nk\n \no\n \na\nn\nt\ns\n \nt\na\n \ns\np\ne\nj\ne\nl\n \nb\na\nl\nu\nm\ni\nl\ne\n \nk\n’\no\nl\ne\nm\n \nx\n-\nh\na\ny\na\nn\n \ni\n \nk\no\n’\no\nl\n \nt\na\n \ns\nc\nh\n’\nu\nl\na\nl\n \ni\n \ns\nd\ne\nr\ne\nc\nh\no\ne\nt\ni\nk\n \ni\n,\n \ns\nk\no\nt\no\nl\n \nk"
}
