id: "ug"
language: "ug"
script: "Arab"
name: "Uyghur"
population: 7670114
region: "AF"
region: "CN"
exemplar_chars {
  base: "{ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} ا ە ب پ ت ج چ خ د ر ز ژ س ش غ ف ق ك گ ڭ ل م ن ھ و ۇ ۆ ۈ ۋ ې ى ي {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى}"
  auxiliary: "‎‏ ئ"
  numerals: "- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "{ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} ا ە ب پ ت ج چ خ د ر ز ژ س ش غ ف ق ك گ ڭ ل م ن ھ و ۇ ۆ ۈ ۋ ې ى ي {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى} {ئا} {ئه} {ئو} {ئۇ} {ئۆ} {ئۈ} {ئې} {ئى}"
}
sample_text {
  masthead_full: "ھەمئ"
  masthead_partial: "اد"
  styles: "ئىنسانلار ئائىلىسىنىڭ بارلىق ئەزالىرنىڭ ئۆزىگە"
  tester: "كىشىلىك ھوقۇقىغا ئېتىبارسىز قاراش ۋە ھاقارەت كەلتۈرۈش ئەۋج ئېلىپ"
  poster_sm: "ئىنسانلانىڭ"
  poster_md: "دۆلەتلەر"
  poster_lg: "ھەممە"
  specimen_48: "بىرلەشكەن دۆلەتلەر تەشكىلارتىغا ئەزا دۆلەتلەر خەلقىنىڭ بىرلەشكەن"
  specimen_36: "دۆلەتلەر ئارا دوستلۇق مۈناسىۋىتىنىڭ تەرەققىياتىنى ئالغا سۈرۇش زۆرۈرلۇكى،\nكۆزدە تۇتۇلغاچقا، ھازىر\nيىغىن،"
  specimen_32: "ھەرقانداق ئادەمنى قۇل قىلىشقا ياكى قۇل قاتارىدا ئىشلىتىشكە بولمايدۇ. ھەرقاندقاق شەكىلدىكى قۇللۇق توزۇمنىمۇ، قۇللارنى ئېلىپ-سېتىشنىمۇ مەنئى قىلىش كېرەك. "
  specimen_21: "ئىنسانلار ئائىلىسىنىڭ بارلىق ئەزالىرنىڭ ئۆزىگە خاس ئىززەت-ھۆرمىتىنى شۇنىڭدەك ئۇلارنىڭ باراۋەر ۋە تەۋرەنمەس ھوقۇقىنى ئەتراپ قىلىشنىڭ دۇنياۋى ئەركىنلىك، ھەققانىيەت ۋە تىنچلىقنىڭ ئاساسى ئىكەنلىكى،\nئىنسانلانىڭ ئىلاجىسىزلىقتىن زوراۋانلىق ۋە زۇلۇم ئۈستىدە ئىسيان كۆتۈرىمىز دەپ تەۋەككۇلىگە ھەرىكەت قىلىپ يۇرمەسلىكى ئۈچۈن، كىشىلىك ھوقۇقىنى قانۇن ئارقىلىق ئىدارە قىلىش يولى بىلەن قوغداش زۆرۈر بولغانلىقى،"
  specimen_16: "ئىنسانلار ئائىلىسىنىڭ بارلىق ئەزالىرنىڭ ئۆزىگە خاس ئىززەت-ھۆرمىتىنى شۇنىڭدەك ئۇلارنىڭ باراۋەر ۋە تەۋرەنمەس ھوقۇقىنى ئەتراپ قىلىشنىڭ دۇنياۋى ئەركىنلىك، ھەققانىيەت ۋە تىنچلىقنىڭ ئاساسى ئىكەنلىكى،\nكىشىلىك ھوقۇقىغا ئېتىبارسىز قاراش ۋە ھاقارەت كەلتۈرۈش ئەۋج ئېلىپ كىشىلەرنىڭ ۋىجدانىنى بولغايدىغان ياۋۇز زوراۋانلىققا ئايلانغانلىقى، ھەممە ئادەم سۆز ئەركىنلىكى ۋە ئېتىقاد ئەركىنلىكىدىن بەھرىمەن بولىدىغان ھەمدە ۋەھىمە ۋە نامراتلىقتىن خالىي بولىدىغان دۇنيانىڭ يېتىپ كېلىشى ئاددىي خەلقنىڭ ئالىي ئارزۇسى دەپ ئېلان قىلىنغانلىقى،\nئىنسانلانىڭ ئىلاجىسىزلىقتىن زوراۋانلىق ۋە زۇلۇم ئۈستىدە ئىسيان كۆتۈرىمىز دەپ تەۋەككۇلىگە ھەرىكەت قىلىپ يۇرمەسلىكى ئۈچۈن، كىشىلىك ھوقۇقىنى قانۇن ئارقىلىق ئىدارە قىلىش يولى بىلەن قوغداش زۆرۈر بولغانلىقى،"
}
