id: "ug_Cyrl"
language: "ug"
script: "Cyrl"
name: "Uyghur (Cyrillic)"
autonym: "Уйғур"
population: 382851
region: "KZ"
region: "MN"
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Ю Я Ғ Җ Қ Ң Ү Һ Ә Ө а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш ю я ғ җ қ ң ү һ ә ө"
  marks: "◌̆"
}
sample_text {
  masthead_full: "ҺһЕе"
  masthead_partial: "Мм"
  styles: "Һемме адем занидинла еркин, иззетһөрмет ве"
  tester: "Һемме адем занидинла еркин, иззетһөрмет ве һоқуқта бапбаравер"
  poster_sm: "Һемме адем"
  poster_md: "Һемме"
  poster_lg: "Һемме"
  specimen_48: "Һемме адем занидинла еркин, иззетһөрмет ве һоқуқта бапбаравер"
  specimen_36: "Һемме адем занидинла еркин, иззетһөрмет ве һоқуқта бапбаравер болуп туғулған. Улар еқилге ве вийдан\'ға иге һемде бирбириге қэриндашлиқ мунасивитиге хас роһ билен билен муамил қилиши кэрек."
  specimen_32: "Һемме адем занидинла еркин, иззетһөрмет ве һоқуқта бапбаравер болуп туғулған. Улар еқилге ве вийдан\'ға иге һемде бирбириге қэриндашлиқ мунасивитиге хас роһ билен билен муамил қилиши кэрек."
  specimen_21: "Һемме адем занидинла еркин, иззетһөрмет ве һоқуқта бапбаравер болуп туғулған. Улар еқилге ве вийдан\'ға иге һемде бирбириге қэриндашлиқ мунасивитиге хас роһ билен билен муамил қилиши кэрек.\nҺемме адем занидинла еркин, иззетһөрмет ве һоқуқта бапбаравер болуп туғулған. Улар еқилге ве вийдан\'ға иге һемде бирбириге қэриндашлиқ мунасивитиге хас роһ билен билен муамил қилиши кэрек."
  specimen_16: "Һемме адем занидинла еркин, иззетһөрмет ве һоқуқта бапбаравер болуп туғулған. Улар еқилге ве вийдан\'ға иге һемде бирбириге қэриндашлиқ мунасивитиге хас роһ билен билен муамил қилиши кэрек.\nҺемме адем занидинла еркин, иззетһөрмет ве һоқуқта бапбаравер болуп туғулған. Улар еқилге ве вийдан\'ға иге һемде бирбириге қэриндашлиқ мунасивитиге хас роһ билен билен муамил қилиши кэрек.\nҺемме адем занидинла еркин, иззетһөрмет ве һоқуқта бапбаравер болуп туғулған. Улар еқилге ве вийдан\'ға иге һемде бирбириге қэриндашлиқ мунасивитиге хас роһ билен билен муамил қилиши кэрек."
}
