id: "ug_Latn"
language: "ug"
script: "Latn"
name: "Uyghur, Latin"
autonym: "Uighur"
population: 0
region: "AC"
region: "AD"
region: "AF"
region: "AG"
region: "AI"
region: "AL"
region: "AM"
region: "AO"
region: "AR"
region: "AS"
region: "AT"
region: "AU"
region: "AW"
region: "AX"
region: "AZ"
region: "BA"
region: "BB"
region: "BD"
region: "BE"
region: "BF"
region: "BG"
region: "BI"
region: "BJ"
region: "BL"
region: "BM"
region: "BN"
region: "BO"
region: "BQ"
region: "BR"
region: "BS"
region: "BT"
region: "BW"
region: "BY"
region: "BZ"
region: "CA"
region: "CC"
region: "CD"
region: "CF"
region: "CG"
region: "CH"
region: "CI"
region: "CK"
region: "CL"
region: "CM"
region: "CN"
region: "CO"
region: "CR"
region: "CU"
region: "CV"
region: "CW"
region: "CX"
region: "CY"
region: "CZ"
region: "DE"
region: "DG"
region: "DJ"
region: "DK"
region: "DM"
region: "DO"
region: "DZ"
region: "EA"
region: "EC"
region: "EE"
region: "EG"
region: "ER"
region: "ES"
region: "ET"
region: "FI"
region: "FJ"
region: "FK"
region: "FM"
region: "FO"
region: "FR"
region: "GA"
region: "GB"
region: "GD"
region: "GE"
region: "GF"
region: "GG"
region: "GH"
region: "GI"
region: "GL"
region: "GM"
region: "GN"
region: "GP"
region: "GQ"
region: "GR"
region: "GT"
region: "GU"
region: "GW"
region: "GY"
region: "HK"
region: "HN"
region: "HR"
region: "HT"
region: "HU"
region: "IC"
region: "ID"
region: "IE"
region: "IL"
region: "IM"
region: "IN"
region: "IO"
region: "IQ"
region: "IR"
region: "IS"
region: "IT"
region: "JE"
region: "JM"
region: "JO"
region: "KE"
region: "KG"
region: "KI"
region: "KM"
region: "KN"
region: "KY"
region: "KZ"
region: "LA"
region: "LB"
region: "LC"
region: "LI"
region: "LK"
region: "LR"
region: "LS"
region: "LT"
region: "LU"
region: "LV"
region: "MA"
region: "MC"
region: "MD"
region: "ME"
region: "MF"
region: "MG"
region: "MH"
region: "MK"
region: "ML"
region: "MM"
region: "MN"
region: "MO"
region: "MP"
region: "MQ"
region: "MR"
region: "MS"
region: "MT"
region: "MU"
region: "MW"
region: "MX"
region: "MY"
region: "MZ"
region: "NA"
region: "NC"
region: "NE"
region: "NF"
region: "NG"
region: "NI"
region: "NL"
region: "NO"
region: "NP"
region: "NR"
region: "NU"
region: "NZ"
region: "PA"
region: "PE"
region: "PF"
region: "PG"
region: "PH"
region: "PK"
region: "PL"
region: "PM"
region: "PN"
region: "PR"
region: "PT"
region: "PW"
region: "PY"
region: "RE"
region: "RO"
region: "RS"
region: "RU"
region: "RW"
region: "SB"
region: "SC"
region: "SD"
region: "SE"
region: "SG"
region: "SH"
region: "SI"
region: "SJ"
region: "SK"
region: "SL"
region: "SM"
region: "SN"
region: "SO"
region: "SR"
region: "SS"
region: "ST"
region: "SV"
region: "SX"
region: "SY"
region: "SZ"
region: "TA"
region: "TC"
region: "TD"
region: "TF"
region: "TG"
region: "TH"
region: "TJ"
region: "TK"
region: "TL"
region: "TM"
region: "TN"
region: "TO"
region: "TR"
region: "TT"
region: "TV"
region: "TW"
region: "TZ"
region: "UA"
region: "UG"
region: "UM"
region: "US"
region: "UY"
region: "UZ"
region: "VA"
region: "VC"
region: "VE"
region: "VG"
region: "VI"
region: "VN"
region: "VU"
region: "WF"
region: "WS"
region: "XK"
region: "YE"
region: "YT"
region: "ZA"
region: "ZM"
region: "ZW"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U W X Y Z Ë Ö Ü a b c d e f g h i j k l m n o p q r s t u w x y z ë ö ü"
  marks: "◌̈"
}
sample_text {
  masthead_full: "HhEe"
  masthead_partial: "Mm"
  styles: "insanlar ailisining barliq ezalirining özige"
  tester: "kixilik hoquqigha étibarsiz qarash we haqaret kelturush ewj élip"
  poster_sm: "insanlarning"
  poster_md: "döletler"
  poster_lg: "hemme"
  specimen_48: "birleshken döletler teshkilatigha eza döletler xelqining birleshken"
  specimen_36: "herqandaq ademini herqandaq shekilde qolgha élishqa, nezer bent qilishqa yaki sürgün qilishqa bolmaydu."
  specimen_32: "hemme adem dem élish we bikar yürüsh hoquqidin, jumlidin ish waqtining chekini eqilge muwapiqlashturush hemde qerellik, maashliq dem élish hoquqidin behrimen bolidu."
  specimen_21: "hemme adem mushu xitabnamide qeyt qilinghan hoquq we erkinlikning toluq ré\'allishishigha imkan béridighan bir xil ijtimaiy we xelq\'ara tertipni telep qilishqa hoquqluq.\nbu xitabnamining herqandaq bir maddisini herqandaq dölet, guruh yaki shexs mushu xitabnamide qeyt qilinghan herqandaq hoquq we erkinlikni buzush meqsitidiki pa\'aliyet yaki heriketlerni élip bérishqa hoquqluq dep sukut qilidighan menide chushendurushke bolmaydu."
  specimen_16: "insanlar ailisining barliq ezalirining özige xas izzet-hörmitini shuningdek ularning barwer we tewrenmes hoquqini etrap qilishning dunyawi erkinlik, heqqaniyet we tinchliqning asasi ikenliki.\nkixilik hoquqigha étibarsiz qarash we haqaret kelturush ewj élip kixilerning wijdanini bulghaydighan yawuz zorawanliqqa aylan\'ghanliqi, hemme adem söz erkinliki we étikad erkinlikidin behrimen bolidighan hemde wehime we namratliqtin xaliy bolidighan dunyaning yetip kélishi addiy xelqning aliy arzusi dep élan qilin\'ghanliqi.\ninsanlarning ilajisizliqtin zorawanliq we zulum ustide isyan köturimiz dep tewekkulige heriket qilip yurmesliki üchün, kishilik hoquqini qanun arqiliq idare qilish yoli bilen qoghdash zörür bolghanliqi,"
}
