id: "uk"
language: "uk"
script: "Cyrl"
name: "Ukrainian"
autonym: "Українська"
population: 29273587
region: "MD"
region: "PL"
region: "RS"
region: "SK"
region: "UA"
exemplar_chars {
  base: "а б в г ґ д е є ж з и і ї й к л м н о п р с т у ф х ц ч ш щ ь ю я ʼ"
  auxiliary: "{а́} {е́} ё {є́} {и́} {і́} {ї́} {о́} {у́} ъ ы э {ю́} {я́} {а́} {е́} {є́} {и́} {і́} {ї́} {о́} {у́} {ю́} {я́} {а́} {е́} {є́} {и́} {і́} {ї́} {о́} {у́} {ю́} {я́} {а́} {е́} {є́} {и́} {і́} {ї́} {о́} {у́} {ю́} {я́} {а́} {е́} {є́} {и́} {і́} {ї́} {о́} {у́} {ю́} {я́} {а́} {е́} {є́} {и́} {і́} {ї́} {о́} {у́} {ю́} {я́} {а́} {е́} {є́} {и́} {і́} {ї́} {о́} {у́} {ю́} {я́} {а́} {е́} {є́} {и́} {і́} {ї́} {о́} {у́} {ю́} {я́} {а́} {е́} {є́} {и́} {і́} {ї́} {о́} {у́} {ю́} {я́} {а́} {е́} {є́} {и́} {і́} {ї́} {о́} {у́} {ю́} {я́} {а́} {е́} {є́} {и́} {і́} {ї́} {о́} {у́} {ю́} {я́} {а́} {е́} {є́} {и́} {і́} {ї́} {о́} {у́} {ю́} {я́} {а́} {е́} {є́} {и́} {і́} {ї́} {о́} {у́} {ю́} {я́} {а́} {е́} {є́} {и́} {і́} {ї́} {о́} {у́} {ю́} {я́} {а́} {е́} {є́} {и́} {і́} {ї́} {о́} {у́} {ю́} {я́} {а́} {е́} {є́} {и́} {і́} {ї́} {о́} {у́} {ю́} {я́}"
  marks: "◌̆ ◌̈ ◌́"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "- ‑ – , ; : ! ? . \' ’ \" “ „ « » ( ) [ ] { } § @ * / \\ № { } { } { } { } { } { } { } { } { } { } { } { } { } { } { }"
  index: "А Б В Г Ґ Д Е Є Ж З И І Ї Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ю Я"
}
sample_text {
  masthead_full: "ВвСс"
  masthead_partial: "Іі"
  styles: "Беручи до уваги, що визнання гідності, яка"
  tester: "беручи до уваги, що зневажання і нехтування правами людини призвели"
  poster_sm: "беручи до уваги,"
  poster_md: "беручи до"
  poster_lg: "Всі"
  specimen_48: "беручи до уваги, що народи Об\'єднаних Націй підтвердили в Статуті"
  specimen_36: "Ніхто не повинен бути в рабстві або у підневільному стані; рабство і работоргівля забороняються в усіх їх видах."
  specimen_32: "Кожна людина має право на ефективне поновлення у правах компетентними національними судами в разі порушення її основних прав, наданих їй конституцією або законом."
  specimen_21: "Ніхто не може зазнавати безпідставного арешту, затримання або вигнання.\nКожна людина, для визначення її прав і обов\'язків і для встановлення обґрунтованості пред\'явленого їй кримінального обвинувачення, має право, на основі повної рівності, на те, щоб її справа була розглянута прилюдно і з додержанням усіх вимог справедливості незалежним і безстороннім судом."
  specimen_16: "Ніхто не може зазнавати безпідставного втручання у його особисте і сімейне життя, безпідставного посягання на недоторканність його житла, таємницю його кореспонденції або на його честь і репутацію. Кожна людина має право на захист закону від такого втручання або таких посягань.\nКожна людина має право на свободу думки, совісті і релігії; це право включає свободу змінювати свою релігію або переконання і свободу сповідувати свою релігію або переконання як одноособово, так і разом з іншими, прилюдним або приватним порядком в ученні, богослужінні і виконанні релігійних та ритуальних обрядів."
}
