id: "und"
name: "Unknown language"
preferred_name: ""
autonym: ""
population: 323
region: "AQ"
region: "BV"
region: "CP"
region: "GS"
region: "HM"
exemplar_chars {
}
sample_text {
  masthead_full: "사람들이"
  masthead_partial: "세계"
  tester: "인권을 무시함과 모욕함이 야만은 극악으로 되였고, 이 극악들이 인류의 양심을 오염 하였고, 전체 사람 모두 연설과"
  poster_sm: "사람들이 폭력과 억압으로"
  poster_md: "모든 나라의 좋은"
  poster_lg: "사람들이"
  specimen_48: "련합국의 모든 회원국의 인민이 련합국헌장에서 기본인권, 사람의 존엄과 가치하고 남녀평등권에 신념을 중신하였고, 큰"
  specimen_36: "사람들이 법으로 평등하고, 법의 평등하는 보호를 받고, 모든 차별을 받않는권리가 있는다, 이 선언을 위반하는 모든 차별과 이 차별을 선동하는 행동의 위험을 피로 사람들이 평등하는 보호를 받는 권리가 있는다."
  specimen_32: "인류의 전체 성원의 고윤 존엄과 평등과 변하지 않는 권리를 승인함이 세계의 자유, 정의하고 화평의 기초이다,\n인권을 무시함과 모욕함이 야만은 극악으로 되였고, 이 극악들이 인류의 양심을 오염 하였고, 전체 사람 모두 연설과 신앙자유가 있고 공구하고 빈곤이 없는 세계 옴이 보통은 인민의 가장 높은 소원으로 발표받였다,"
  specimen_21: "인류의 전체 성원의 고윤 존엄과 평등과 변하지 않는 권리를 승인함이 세계의 자유, 정의하고 화평의 기초이다,\n인권을 무시함과 모욕함이 야만은 극악으로 되였고, 이 극악들이 인류의 양심을 오염 하였고, 전체 사람 모두 연설과 신앙자유가 있고 공구하고 빈곤이 없는 세계 옴이 보통은 인민의 가장 높은 소원으로 발표받였다,\n사람들이 폭력과 억압으로 반변으로 끝의 수단을 하지 않으러, 법치로 언권을 보호하는 필요함이 있는다,\n모든 나라의 좋은 관계의 개발을 촉진하는 필요함이 있는다,\n련합국의 모든 회원국의 인민이 련합국헌장에서 기본인권, 사람의 존엄과 가치하고 남녀평등권에 신념을 중신하였고, 큰 자유에서 사회진보하고 살는 수평의 개선 함을 촉진하기로 결심하였다,"
  specimen_16: "인류의 전체 성원의 고윤 존엄과 평등과 변하지 않는 권리를 승인함이 세계의 자유, 정의하고 화평의 기초이다,\n인권을 무시함과 모욕함이 야만은 극악으로 되였고, 이 극악들이 인류의 양심을 오염 하였고, 전체 사람 모두 연설과 신앙자유가 있고 공구하고 빈곤이 없는 세계 옴이 보통은 인민의 가장 높은 소원으로 발표받였다,\n사람들이 폭력과 억압으로 반변으로 끝의 수단을 하지 않으러, 법치로 언권을 보호하는 필요함이 있는다,\n모든 나라의 좋은 관계의 개발을 촉진하는 필요함이 있는다,\n련합국의 모든 회원국의 인민이 련합국헌장에서 기본인권, 사람의 존엄과 가치하고 남녀평등권에 신념을 중신하였고, 큰 자유에서 사회진보하고 살는 수평의 개선 함을 촉진하기로 결심하였다,\n모든 회원국이 련합국과 협력함으로 인원과 기본자유에 보편존중과 준행을 촉진함을 맹세하였다,\n이 권리들과 자유들을 보편으로 알음이 이 맹세를 충분으로 실현음에 큰 중요성이 있는다,\n이에 지금,\n련합국대회,\n모든 사람과 모든 나라가 노력으로 실현는 공동표준을 하고, 모든 사람과 사회기구가 늘 이 선언을 기억하고, 노력으로 교회하고 교육으로 권리하고 자유에 존중을 족진하고, 나라의하고 국제의 점진하는 조시로, 이 권리들과 자유들에 모든 회원국 자신의 인민과 관할하받는 땅의 인민에게서 보변과 효과이 있는 승인과 준행을 얻게 한으로, 이 세계인권선언을 발 포하는다,"
}
