id: "und_Latn"
language: "und"
script: "Latn"
name: "(Muzzi"
sample_text {
  masthead_full: "NnIi"
  masthead_partial: "Aa"
  styles: "N\ni\na\n \nn\ng\ni\nr\n \nn\ng\ni\nr\n \ny\nm\n \nm\ne\nx\nk"
  tester: "N\ni\na\n \nn\ng\ni\nr\n \nn\ng\ni\nr\n \ny\nm\n \nm\ne\nx\nk\ne\nr\n \nb\nb\nu\nm\nl\ni\nx"
  poster_sm: "N\ni\na\n \nn\ng"
  poster_md: "N\ni\na\n \nn"
  poster_lg: "N\ni"
  specimen_48: "N\ni\na\n \nn\ng\ni\nr\n \nn\ng\ni\nr\n \ny\nm\n \nm\ne\nx\nk\ne\nr\n \nb\nb\nu\nm\nl\ni\nx"
  specimen_36: "N\ni\na\n \nn\ng\ni\nr\n \nn\ng\ni\nr\n \ny\nm\n \nm\ne\nx\nk\ne\nr\n \nb\nb\nu\nm\nl\ni\nx\n \nz\ni\nf\ny\ni\ny\nr\n,\n \nz\nu\nn\ny\na\nn\nr\n \ng\ni"
  specimen_32: "N\ni\na\n \nn\ng\ni\nr\n \nn\ng\ni\nr\n \ny\nm\n \nm\ne\nx\nk\ne\nr\n \nb\nb\nu\nm\nl\ni\nx\n \nz\ni\nf\ny\ni\ny\nr\n,\n \nz\nu\nn\ny\na\nn\nr\n \ng\ni\nx\n \nj\nj\nu\na\nn\nl\ni\nf\n \na\nl\ny\nf\n \nb\nb\nu\nm"
  specimen_21: "N\ni\na\n \nn\ng\ni\nr\n \nn\ng\ni\nr\n \ny\nm\n \nm\ne\nx\nk\ne\nr\n \nb\nb\nu\nm\nl\ni\nx\n \nz\ni\nf\ny\ni\ny\nr\n,\n \nz\nu\nn\ny\na\nn\nr\n \ng\ni\nx\n \nj\nj\nu\na\nn\nl\ni\nf\n \na\nl\ny\nf\n \nb\nb\nu\nm\nl\ni\nx\n \nz\nz\ni\nf\ns\no\nf\n \nw\nu\nr\n.\n \nG\na\nr\nx\ni\ne\nr\n \nl\ni\nx\nx\ni\nn\nf\n \ng\ni\nx\n \nx\ni\ne\nr\nf\nu\nx\n \nc\no\nr\n \ny\ni\nf\n,\n \nx\ni\no\nn\ng\nx\nd\ni\nf\n \ng\nu\na\nn\nx\ni\nf\n \nw\nu\nr\n \nj\ni\nn\ns\ne"
  specimen_16: "N\ni\na\n \nn\ng\ni\nr\n \nn\ng\ni\nr\n \ny\nm\n \nm\ne\nx\nk\ne\nr\n \nb\nb\nu\nm\nl\ni\nx\n \nz\ni\nf\ny\ni\ny\nr\n,\n \nz\nu\nn\ny\na\nn\nr\n \ng\ni\nx\n \nj\nj\nu\na\nn\nl\ni\nf\n \na\nl\ny\nf\n \nb\nb\nu\nm\nl\ni\nx\n \nz\nz\ni\nf\ns\no\nf\n \nw\nu\nr\n.\n \nG\na\nr\nx\ni\ne\nr\n \nl\ni\nx\nx\ni\nn\nf\n \ng\ni\nx\n \nx\ni\ne\nr\nf\nu\nx\n \nc\no\nr\n \ny\ni\nf\n,\n \nx\ni\no\nn\ng\nx\nd\ni\nf\n \ng\nu\na\nn\nx\ni\nf\n \nw\nu\nr\n \nj\ni\nn\ns\ne\nn\nr\n \nl\na\n \nl\no\n \nr\ni\nm\n \nh\ni\nx\n.\nN\ni\na\n \nn\ng\ni\nr\n \nn\ng\ni\nr\n \ny\nm\n \nm\ne\nx\nk\ne\nr\n \nb\nb\nu\nm\nl\ni\nx\n \nz\ni\nf\ny\ni\ny\nr\n,\n \nz\nu\nn\ny\na\nn\nr\n \ng\ni\nx\n \nj\nj\nu\na\nn\nl\ni\nf\n \na\nl\ny\nf\n \nb\nb\nu\nm\nl\ni\nx\n \nz\nz\ni\nf\ns\no\nf\n \nw\nu\nr\n.\n \nG\na\nr\nx\ni\ne\nr\n \nl\ni\nx\nx\ni\nn\nf\n \ng\ni\nx\n \nx\ni"
}
