id: "und_Hans"
language: "und"
script: "Hans"
name: "(Jinan"
sample_text {
  masthead_full: "是人都生"
  masthead_partial: "而自"
  styles: "是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们"
  tester: "是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n并\n应"
  poster_sm: "是\n人\n都\n生\n而\n自"
  poster_md: "是\n人\n都\n生\n而"
  poster_lg: "是\n人"
  specimen_48: "是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n并\n应"
  specimen_36: "是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n并\n应\n以\n弟\n兄\n关\n系\n的\n精\n神\n相\n对\n待\n。\n是\n人\n都\n生\n而\n自\n由\n，\n在"
  specimen_32: "是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n并\n应\n以\n弟\n兄\n关\n系\n的\n精\n神\n相\n对\n待\n。\n是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，"
  specimen_21: "是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n并\n应\n以\n弟\n兄\n关\n系\n的\n精\n神\n相\n对\n待\n。\n是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n并\n应\n以\n弟\n兄\n关\n系\n的\n精\n神\n相\n对\n待\n。\n是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n并\n应\n以\n弟\n兄\n关\n系\n的\n精\n神\n相\n对\n待\n。\n是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性"
  specimen_16: "是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n并\n应\n以\n弟\n兄\n关\n系\n的\n精\n神\n相\n对\n待\n。\n是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n并\n应\n以\n弟\n兄\n关\n系\n的\n精\n神\n相\n对\n待\n。\n是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n并\n应\n以\n弟\n兄\n关\n系\n的\n精\n神\n相\n对\n待\n。\n是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n并\n应\n以\n弟\n兄\n关\n系\n的\n精\n神\n相\n对\n待\n。\n是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n并\n应\n以\n弟\n兄\n关\n系\n的\n精\n神\n相\n对\n待\n。\n是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理\n性\n和\n良\n心\n，\n并\n应\n以\n弟\n兄\n关\n系\n的\n精\n神\n相\n对\n待\n。\n是\n人\n都\n生\n而\n自\n由\n，\n在\n尊\n严\n和\n权\n利\n上\n一\n律\n平\n等\n。\n他\n们\n赋\n有\n理"
}
