id: "unr_Beng"
language: "unr"
script: "Beng"
name: "Mundari"
population: 1246524
region: "IN"
sample_text {
  masthead_full: "সবনহ"
  masthead_partial: "ড়ক"
  styles: "সোবেন হোড়োকো কে মনরংগ ওড়োও অক্তিয়ার কো রেঅ͚ পইতিবাবত রে জনম"
  tester: "সোবেন হোড়োকো কে মনরংগ ওড়োও অক্তিয়ার কো রেঅ͚ পইতিবাবত রে জনম জোরোংগ্এতে অহ্ডানড ওড়োও বরাবরী"
  poster_sm: "সোবেন হোড়োকো কে মনরংগ"
  poster_md: "সোবেন হোড়োকো"
  poster_lg: "সোবেন"
  specimen_48: "সোবেন হোড়োকো কে মনরংগ ওড়োও অক্তিয়ার কো রেঅ͚ পইতিবাবত রে জনম জোরোংগ্এতে অহ্ডানড"
  specimen_36: "সোবেন হোড়োকো কে মনরংগ ওড়োও অক্তিয়ার কো রেঅ͚ পইতিবাবত রে জনম জোরোংগ্এতে অহ্ডানড ওড়োও বরাবরী নমা কনা। ইনকু কে সেংড়াঁ ওড়োওজী পেডেঃ, জীউ রেঅ͚ এনেমকো নমা কনা ওড়োও ইনকু লোওঃতে হগেয়াওয়োয়া লেকা জগর বকড় লগাতিংগ্অ͚ ।"
  specimen_32: "সোবেন হোড়োকো কে মনরংগ ওড়োও অক্তিয়ার কো রেঅ͚ পইতিবাবত রে জনম জোরোংগ্এতে অহ্ডানড ওড়োও বরাবরী নমা কনা। ইনকু কে সেংড়াঁ ওড়োওজী পেডেঃ, জীউ রেঅ͚ এনেমকো নমা কনা ওড়োও ইনকু লোওঃতে হগেয়াওয়োয়া লেকা জগর বকড় লগাতিংগ্অ͚ ।"
  specimen_21: "সোবেন হোড়োকো কে মনরংগ ওড়োও অক্তিয়ার কো রেঅ͚ পইতিবাবত রে জনম জোরোংগ্এতে অহ্ডানড ওড়োও বরাবরী নমা কনা। ইনকু কে সেংড়াঁ ওড়োওজী পেডেঃ, জীউ রেঅ͚ এনেমকো নমা কনা ওড়োও ইনকু লোওঃতে হগেয়াওয়োয়া লেকা জগর বকড় লগাতিংগ্অ͚ ।\nসোবেন হোড়োকো কে মনরংগ ওড়োও অক্তিয়ার কো রেঅ͚ পইতিবাবত রে জনম জোরোংগ্এতে অহ্ডানড ওড়োও বরাবরী নমা কনা। ইনকু কে সেংড়াঁ ওড়োওজী পেডেঃ, জীউ রেঅ͚ এনেমকো নমা কনা ওড়োও ইনকু লোওঃতে হগেয়াওয়োয়া লেকা জগর বকড় লগাতিংগ্অ͚ ।\nসোবেন হোড়োকো কে মনরংগ ওড়োও অক্তিয়ার কো রেঅ͚ পইতিবাবত রে জনম জোরোংগ্এতে অহ্ডানড ওড়োও বরাবরী নমা কনা। ইনকু কে সেংড়াঁ ওড়োওজী পেডেঃ, জীউ রেঅ͚ এনেমকো নমা কনা ওড়োও ইনকু লোওঃতে হগেয়াওয়োয়া লেকা জগর বকড় লগাতিংগ্অ͚ ।"
  specimen_16: "সোবেন হোড়োকো কে মনরংগ ওড়োও অক্তিয়ার কো রেঅ͚ পইতিবাবত রে জনম জোরোংগ্এতে অহ্ডানড ওড়োও বরাবরী নমা কনা। ইনকু কে সেংড়াঁ ওড়োওজী পেডেঃ, জীউ রেঅ͚ এনেমকো নমা কনা ওড়োও ইনকু লোওঃতে হগেয়াওয়োয়া লেকা জগর বকড় লগাতিংগ্অ͚ ।\nসোবেন হোড়োকো কে মনরংগ ওড়োও অক্তিয়ার কো রেঅ͚ পইতিবাবত রে জনম জোরোংগ্এতে অহ্ডানড ওড়োও বরাবরী নমা কনা। ইনকু কে সেংড়াঁ ওড়োওজী পেডেঃ, জীউ রেঅ͚ এনেমকো নমা কনা ওড়োও ইনকু লোওঃতে হগেয়াওয়োয়া লেকা জগর বকড় লগাতিংগ্অ͚ ।\nসোবেন হোড়োকো কে মনরংগ ওড়োও অক্তিয়ার কো রেঅ͚ পইতিবাবত রে জনম জোরোংগ্এতে অহ্ডানড ওড়োও বরাবরী নমা কনা। ইনকু কে সেংড়াঁ ওড়োওজী পেডেঃ, জীউ রেঅ͚ এনেমকো নমা কনা ওড়োও ইনকু লোওঃতে হগেয়াওয়োয়া লেকা জগর বকড় লগাতিংগ্অ͚ ।\nসোবেন হোড়োকো কে মনরংগ ওড়োও অক্তিয়ার কো রেঅ͚ পইতিবাবত রে জনম জোরোংগ্এতে অহ্ডানড ওড়োও বরাবরী নমা কনা। ইনকু কে সেংড়াঁ ওড়োওজী পেডেঃ, জীউ রেঅ͚ এনেমকো নমা কনা ওড়োও ইনকু লোওঃতে হগেয়াওয়োয়া লেকা জগর বকড় লগাতিংগ্অ͚ ।"
}
