id: "unr_Deva"
name: "Mundari (Devanagari)"
preferred_name: ""
autonym: ""
population: 5762
region: "NP"
script: "Bangla"
script: "Devanagari"
exemplar_chars {
}
sample_text {
  fallback_language: "unr"
}
