id: "unx_Deva"
language: "unx"
script: "Deva"
name: "Munda, Devanagari"
population: 0
region: "BT"
region: "FJ"
region: "IN"
region: "MU"
region: "NP"
region: "PK"
region: "UG"
region: "ZA"
sample_text {
  masthead_full: "जतहड़"
  masthead_partial: "कम"
  styles: "जोतो होड़ोको के मान् आर अधिकार रेया पाईटी रे जन्मजुग आते नवारी"
  tester: "जोतो होड़ोको के मान् आर अधिकार रेया पाईटी रे जन्मजुग आते नवारी ओडोअ् बाराबारी नाम आकाना। आजके"
  poster_sm: "जोतो होड़ोको के मान्"
  poster_md: "जोतो होड़ोको"
  poster_lg: "होड़ोको"
  specimen_48: "जोतो होड़ोको के मान् आर अधिकार रेया पाईटी रे जन्मजुग आते नवारी ओडोअ् बाराबारी"
  specimen_36: "जोतो होड़ोको के मान् आर अधिकार रेया पाईटी रे जन्मजुग आते नवारी ओडोअ् बाराबारी नाम आकाना। आजके बुद्धि ओडोअ् अन्तर आत्मा आते नाम आकाना ओडोअ् सोंगेरे आजके दादा भाई रूपते मान्ती दरकार।"
  specimen_32: "जोतो होड़ोको के मान् आर अधिकार रेया पाईटी रे जन्मजुग आते नवारी ओडोअ् बाराबारी नाम आकाना। आजके बुद्धि ओडोअ् अन्तर आत्मा आते नाम आकाना ओडोअ् सोंगेरे आजके दादा भाई रूपते मान्ती दरकार।"
  specimen_21: "जोतो होड़ोको के मान् आर अधिकार रेया पाईटी रे जन्मजुग आते नवारी ओडोअ् बाराबारी नाम आकाना। आजके बुद्धि ओडोअ् अन्तर आत्मा आते नाम आकाना ओडोअ् सोंगेरे आजके दादा भाई रूपते मान्ती दरकार।\nजोतो होड़ोको के मान् आर अधिकार रेया पाईटी रे जन्मजुग आते नवारी ओडोअ् बाराबारी नाम आकाना। आजके बुद्धि ओडोअ् अन्तर आत्मा आते नाम आकाना ओडोअ् सोंगेरे आजके दादा भाई रूपते मान्ती दरकार।\nजोतो होड़ोको के मान् आर अधिकार रेया पाईटी रे जन्मजुग आते नवारी ओडोअ् बाराबारी नाम आकाना। आजके बुद्धि ओडोअ् अन्तर आत्मा आते नाम आकाना ओडोअ् सोंगेरे आजके दादा भाई रूपते मान्ती दरकार।"
  specimen_16: "जोतो होड़ोको के मान् आर अधिकार रेया पाईटी रे जन्मजुग आते नवारी ओडोअ् बाराबारी नाम आकाना। आजके बुद्धि ओडोअ् अन्तर आत्मा आते नाम आकाना ओडोअ् सोंगेरे आजके दादा भाई रूपते मान्ती दरकार।\nजोतो होड़ोको के मान् आर अधिकार रेया पाईटी रे जन्मजुग आते नवारी ओडोअ् बाराबारी नाम आकाना। आजके बुद्धि ओडोअ् अन्तर आत्मा आते नाम आकाना ओडोअ् सोंगेरे आजके दादा भाई रूपते मान्ती दरकार।\nजोतो होड़ोको के मान् आर अधिकार रेया पाईटी रे जन्मजुग आते नवारी ओडोअ् बाराबारी नाम आकाना। आजके बुद्धि ओडोअ् अन्तर आत्मा आते नाम आकाना ओडोअ् सोंगेरे आजके दादा भाई रूपते मान्ती दरकार।\nजोतो होड़ोको के मान् आर अधिकार रेया पाईटी रे जन्मजुग आते नवारी ओडोअ् बाराबारी नाम आकाना। आजके बुद्धि ओडोअ् अन्तर आत्मा आते नाम आकाना ओडोअ् सोंगेरे आजके दादा भाई रूपते मान्ती दरकार।\nजोतो होड़ोको के मान् आर अधिकार रेया पाईटी रे जन्मजुग आते नवारी ओडोअ् बाराबारी नाम आकाना। आजके बुद्धि ओडोअ् अन्तर आत्मा आते नाम आकाना ओडोअ् सोंगेरे आजके दादा भाई रूपते मान्ती दरकार।"
}
