id: "uz_Arab"
language: "uz"
script: "Arab"
name: "Uzbek (Arabic)"
population: 1722258
region: "AF"
exemplar_chars {
  base: "ً ٌ ٍ َ ُ ِ ّ ْ ٔ ٰ ء آ أ ؤ ئ ا ب پ ة ت ث ج چ ح خ د ذ ر ز ژ س ش ص ض ط ظ ع غ ف ق ک گ ل م ن ه و ۇ ۉ ی"
  auxiliary: "‌‍‎‏ ټ ځ څ ډ ړ ږ ښ ګ ڼ ي ۍ ې"
  numerals: "‎ - ‑ , ٫ ٬ . % ٪ ‰ ؉ + − 0۰ 1۱ 2۲ 3۳ 4۴ 5۵ 6۶ 7۷ 8۸ 9۹"
  index: "ء آ أ ؤ ئ ا ب پ ة ت ث ټ ج چ ح خ ځ څ د ذ ډ ر ز ړ ږ ژ س ش ښ ص ض ط ظ ع غ ف ق ک ګ گ ل م ن ڼ ه و ۇ ۉ ي ی ۍ ې"
}
sample_text {
  fallback_language: "ar"
}
