id: "uz_Cyrl"
name: "Uzbek (Cyrillic)"
preferred_name: ""
autonym: ""
population: 4590386
region: "CN"
region: "UZ"
script: "Cyrillic"
script: "Latin"
script: "Perso-Arabic"
exemplar_chars {
  base: "а б в г ғ д е ё ж з и й к қ л м н о п р с т у ў ф х ҳ ч ш ъ э ю я"
  auxiliary: "ц щ ы ь"
  numerals: "  \\- ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "А Б В Г Ғ Д Е Ж З И Й К Қ Л М Н О П Р С Т У Ў Ф Х Ҳ Ч Ш Ъ Э Ю Я"
}
sample_text {
  fallback_language: "uz"
}
