id: "vi_Hani"
language: "vi"
script: "Hani"
name: "Vietnamese, Han"
population: 0
sample_text {
  masthead_full: "畢哿每𠊛"
  masthead_partial: "生𠚢"
  styles: "事侵犯吧䁛常人權㐌引𦤾仍行動殘暴侵犯𬧐良心𧵑人類、吧役𡏦𥩯𠬠世界𥪝𪦆𡥵𠊛得自由言論吧信仰"
  tester: "人民各渃成員聯合國𥪝本憲章㐌𠬠吝姅肯定念信𧵑𨉟𠓨仍權基本𧵑𡥵𠊛、𠓨人品、𠓨價值𧵑每𠊛、𠓨權平等男女、吧㐌𠍣𤍊決心促𢱜進步社會拱如𡏦𥩯各條件𤯨𡄰欣"
  poster_sm: "每𠊛調𣎏權𤯨、自由吧安全個人"
  poster_md: "空埃被查訊咍被對處"
  poster_lg: "空分別種族"
  specimen_48: "畢哿每𠊛調平等𠓀法律吧得法律保衞如饒空𣎏不據事分別芇。畢哿每𠊛調得保衞如饒𢶢吏每形式分別對處違犯本宣言呢共如𢶢吏每行爲驅𠽖分別對處如丕"
  specimen_36: "𢭲認識哴：\n役承認人品本𣎏、各權平等吧空體㳻𢴐𧵑每成員𥪝家庭人類羅基礎朱自由、公平吧和平𨕭世界、\n事侵犯吧䁛常人權㐌引𦤾仍行動殘暴侵犯𬧐良心𧵑人類、吧役𡏦𥩯𠬠世界𥪝𪦆𡥵𠊛得自由言論吧信仰、空群沛𠹾餒𢜝駭吧窮極得䁛羅願望高哿一𧵑類𠊛、"
  specimen_32: "版宣言全世界𧗱人權呢羅𡱩都終朱畢哿各渃吧畢哿各民族打價役實現目標𦓡每個人吧每組織𥪝社會、𨕭基礎㫻記𢖵版宣言呢、𠱊奮鬥促𢱜事尊重各權吧自由基本𧵑𡥵𠊛通過傳播吧教育、拱如𠱊奮鬥擔保朱 每𠊛民、於正各渃成員𧵑聯合國吧於各領土屬權管理𧵑𨉟、公認吧實現仍權吧自由𪦆𠬠格𣎏效果通過仍辦法積極、𥪝範圍國家咍國際。"
  specimen_21: "𢭲認識哴：\n役承認人品本𣎏、各權平等吧空體㳻𢴐𧵑每成員𥪝家庭人類羅基礎朱自由、公平吧和平𨕭世界、\n事侵犯吧䁛常人權㐌引𦤾仍行動殘暴侵犯𬧐良心𧵑人類、吧役𡏦𥩯𠬠世界𥪝𪦆𡥵𠊛得自由言論吧信仰、空群沛𠹾餒𢜝駭吧窮極得䁛羅願望高哿一𧵑類𠊛、\n人權沛得法律保衞抵每𠊛空𦄾沛浽亂如羅辦法𡳳窮抵挵吏制度強權吧壓逼、\n勤沛勸激役發展關係朋友𡧲各民族、\n人民各渃成員聯合國𥪝本憲章㐌𠬠吝姅肯定念信𧵑𨉟𠓨仍權基本𧵑𡥵𠊛、𠓨人品、𠓨價值𧵑每𠊛、𠓨權平等男女、吧㐌𠍣𤍊決心促𢱜進步社會拱如𡏦𥩯各條件𤯨𡄰欣、自由欣。\n    各渃成員㐌甘結、共𢭲組織聯合國、奮鬥促𢱜每𠊛尊重吧實現各權拱如仍自由基本𧵑𡥵𠊛。 \n\n    認識統一𧗱仍權吧自由𪦆𧵑𡥵𠊛羅要素關重一朱役實現𠫆踷甘結呢。"
  specimen_16: "𢭲認識哴：\n役承認人品本𣎏、各權平等吧空體㳻𢴐𧵑每成員𥪝家庭人類羅基礎朱自由、公平吧和平𨕭世界、\n事侵犯吧䁛常人權㐌引𦤾仍行動殘暴侵犯𬧐良心𧵑人類、吧役𡏦𥩯𠬠世界𥪝𪦆𡥵𠊛得自由言論吧信仰、空群沛𠹾餒𢜝駭吧窮極得䁛羅願望高哿一𧵑類𠊛、\n人權沛得法律保衞抵每𠊛空𦄾沛浽亂如羅辦法𡳳窮抵挵吏制度強權吧壓逼、\n勤沛勸激役發展關係朋友𡧲各民族、\n人民各渃成員聯合國𥪝本憲章㐌𠬠吝姅肯定念信𧵑𨉟𠓨仍權基本𧵑𡥵𠊛、𠓨人品、𠓨價值𧵑每𠊛、𠓨權平等男女、吧㐌𠍣𤍊決心促𢱜進步社會拱如𡏦𥩯各條件𤯨𡄰欣、自由欣。\n    各渃成員㐌甘結、共𢭲組織聯合國、奮鬥促𢱜每𠊛尊重吧實現各權拱如仍自由基本𧵑𡥵𠊛。 \n\n    認識統一𧗱仍權吧自由𪦆𧵑𡥵𠊛羅要素關重一朱役實現𠫆踷甘結呢。\n𠉞、大會同聯合國宣布：\n版宣言全世界𧗱人權呢羅𡱩都終朱畢哿各渃吧畢哿各民族打價役實現目標𦓡每個人吧每組織𥪝社會、𨕭基礎㫻記𢖵版宣言呢、𠱊奮鬥促𢱜事尊重各權吧自由基本𧵑𡥵𠊛通過傳播吧教育、拱如𠱊奮鬥擔保朱 每𠊛民、於正各渃成員𧵑聯合國吧於各領土屬權管理𧵑𨉟、公認吧實現仍權吧自由𪦆𠬠格𣎏效果通過仍辦法積極、𥪝範圍國家咍國際。\n畢哿每𠊛生𠚢調得自由吧平等𧗱人品吧權。每𡥵𠊛調得造化頒朱理智吧良心吧勤沛對處𢭲膮𥪝情朋友。\n每𠊛調得享畢哿仍權吧自由標𥪝版宣言呢、空分別種族、𬜝䏧、界性、言語、宗教、觀點政治咍各觀點恪、源㭲國家咍社會、財產、成分出身咍地位社會。"
}
