id: "wls"
language: "wls"
script: "Latn"
name: "Wallisian"
autonym: "Fakaʻuvea"
population: 9512
region: "WF"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ā Ē Ī Ō Ū a b c d e f g h i j k l m n o p q r s t u v w x y z ā ē ī ō ū ʻ"
  marks: "◌̄"
}
sample_text {
  fallback_language: "en"
}
