id: "wuu"
language: "wuu"
script: "Hans"
name: "Wu Chinese"
population: 83641200
region: "CN"
sample_text {
  masthead_full: "人生而自"
  masthead_partial: "由拉"
  styles: "鉴于人类社会个成员侪有个固有尊严脱仔平等个脱仔勿移个权利承认，是世界自由、正义脱仔和平个基础"
  tester: "鉴于人权个无视脱仔侮蔑已发展为野蛮暴行，掰眼暴行玷污了人类个良心，而一个人人侪有言论脱仔信仰自由并勿有恐惧脱匮乏个世界个来临"
  poster_sm: "发布掰个世界人权宣言"
  poster_md: "人人有权享有生命"
  poster_lg: "人人生而自由"
  specimen_48: "法律之前人人平等，并有权享受法律个平等保护，勿受任何歧视。人人有权享受平等保护，以免受违反掰个宣言个任何歧视行为脱仔煽动掰排里歧视个任何行为个害"
  specimen_36: "鉴于人类社会个成员侪有个固有尊严脱仔平等个脱仔勿移个权利承认，是世界自由、正义脱仔和平个基础，\n鉴于人权个无视脱仔侮蔑已发展为野蛮暴行，掰眼暴行玷污了人类个良心，而一个人人侪有言论脱仔信仰自由并勿有恐惧脱匮乏个世界个来临，已被宣布为普通人民个着着高愿望，"
  specimen_32: "鉴于人类社会个成员侪有个固有尊严脱仔平等个脱仔勿移个权利承认，是世界自由、正义脱仔和平个基础，\n鉴于人权个无视脱仔侮蔑已发展为野蛮暴行，掰眼暴行玷污了人类个良心，而一个人人侪有言论脱仔信仰自由并勿有恐惧脱匮乏个世界个来临，已被宣布为普通人民个着着高愿望，\n鉴于为使人类勿至于迫勿得已铤而走险暴政脱仔压迫进行反叛，有必要使人权受法治个保护，"
  specimen_21: "鉴于人类社会个成员侪有个固有尊严脱仔平等个脱仔勿移个权利承认，是世界自由、正义脱仔和平个基础，\n鉴于人权个无视脱仔侮蔑已发展为野蛮暴行，掰眼暴行玷污了人类个良心，而一个人人侪有言论脱仔信仰自由并勿有恐惧脱匮乏个世界个来临，已被宣布为普通人民个着着高愿望，\n鉴于为使人类勿至于迫勿得已铤而走险暴政脱仔压迫进行反叛，有必要使人权受法治个保护，\n鉴于有必要促进各国间友好关系个发展，\n鉴于各联合国国家个人民已拉联合国宪章中重申伊拉对基本人权、人格尊严和价值以及男女平等权利个信念，并决心促成较大自由中个社会进步脱仔生活水平个改善，\n鉴于各会员国业已誓愿同联合国合作以促进对人权脱仔基本自由个普遍尊重脱仔遵行，\n鉴于对掰眼权利脱仔自由个普遍了解对于掰个誓愿个充分实现有蛮大个重要性，"
  specimen_16: "鉴于人类社会个成员侪有个固有尊严脱仔平等个脱仔勿移个权利承认，是世界自由、正义脱仔和平个基础，\n鉴于人权个无视脱仔侮蔑已发展为野蛮暴行，掰眼暴行玷污了人类个良心，而一个人人侪有言论脱仔信仰自由并勿有恐惧脱匮乏个世界个来临，已被宣布为普通人民个着着高愿望，\n鉴于为使人类勿至于迫勿得已铤而走险暴政脱仔压迫进行反叛，有必要使人权受法治个保护，\n鉴于有必要促进各国间友好关系个发展，\n鉴于各联合国国家个人民已拉联合国宪章中重申伊拉对基本人权、人格尊严和价值以及男女平等权利个信念，并决心促成较大自由中个社会进步脱仔生活水平个改善，\n鉴于各会员国业已誓愿同联合国合作以促进对人权脱仔基本自由个普遍尊重脱仔遵行，\n鉴于对掰眼权利脱仔自由个普遍了解对于掰个誓愿个充分实现有蛮大个重要性，\n因此葛歇，\n大会，\n发布掰个世界人权宣言，作为所有人民脱仔所有国家努力实现个共同标准，以期每一个人脱仔社会机构经常思量掰个宣言，努力通过教诲脱仔教育促进对权利脱仔自由个尊重，并通过国家个脱仔国际个渐进措施，使掰眼权利脱仔自由拉各会员国本身人民脱仔拉伊拉管辖下领土个人民中得到普遍脱仔有效个承认脱仔遵行；\n人人生而自由，拉尊严脱仔权利上一律平等。伊拉有理性脱仔良心，并应以兄弟关系个精神相对待。\n人人有资格享有本宣言所载个一切权利脱仔自由，勿分种族、肤色、性别、语言、宗教、政治或其他见解、国籍或社会出身、财产、出生或其他身分等任何区别。"
}
