id: "wwa_Latn"
language: "wwa"
script: "Latn"
name: "Waama"
sample_text {
  masthead_full: "YyIi"
  masthead_partial: "Rr"
  styles: "Y\ni\nr\ni\nb\na\n \nn\na\n \nb\nà\n \ns\ni\nk\ni\nn\nd\no\n "
  tester: "Y\ni\nr\ni\nb\na\n \nn\na\n \nb\nà\n \ns\ni\nk\ni\nn\nd\no\n \nd\na\nr\ne\n \nb\nà\n \nm\nɛ"
  poster_sm: "Y\ni\nr\ni\nb\na"
  poster_md: "Y\ni\nr\ni\nb"
  poster_lg: "Y\ni"
  specimen_48: "Y\ni\nr\ni\nb\na\n \nn\na\n \nb\nà\n \ns\ni\nk\ni\nn\nd\no\n \nd\na\nr\ne\n \nb\nà\n \nm\nɛ"
  specimen_36: "Y\ni\nr\ni\nb\na\n \nn\na\n \nb\nà\n \ns\ni\nk\ni\nn\nd\no\n \nd\na\nr\ne\n \nb\nà\n \nm\nɛ\nɛ\nr\ni\n,\n \nd\na\n \ns\ne\ne\nn\na\n \ny\ni\nr\ni\nm\nm"
  specimen_32: "Y\ni\nr\ni\nb\na\n \nn\na\n \nb\nà\n \ns\ni\nk\ni\nn\nd\no\n \nd\na\nr\ne\n \nb\nà\n \nm\nɛ\nɛ\nr\ni\n,\n \nd\na\n \ns\ne\ne\nn\na\n \ny\ni\nr\ni\nm\nm\na\n \nm\ni\ni\n \nb\nà\n \nt\na\n \nd\na\n \ni\n \nn\nɛ\nk"
  specimen_21: "Y\ni\nr\ni\nb\na\n \nn\na\n \nb\nà\n \ns\ni\nk\ni\nn\nd\no\n \nd\na\nr\ne\n \nb\nà\n \nm\nɛ\nɛ\nr\ni\n,\n \nd\na\n \ns\ne\ne\nn\na\n \ny\ni\nr\ni\nm\nm\na\n \nm\ni\ni\n \nb\nà\n \nt\na\n \nd\na\n \ni\n \nn\nɛ\nk\ni\n \nb\nà\n \nt\nɔ\nɔ\nb\na\n.\nY\ni\nr\ni\nb\na\n \nn\na\n \nb\nà\n \ns\ni\nk\ni\nn\nd\no\n \nd\na\nr\ne\n \nb\nà\n \nm\nɛ\nɛ\nr\ni\n,\n \nd\na\n \ns\ne\ne\nn\na\n \ny\ni\nr\ni\nm\nm\na\n \nm\ni\ni\n \nb\nà\n \nt\na\n \nd\na\n \ni\n \nn\nɛ"
  specimen_16: "Y\ni\nr\ni\nb\na\n \nn\na\n \nb\nà\n \ns\ni\nk\ni\nn\nd\no\n \nd\na\nr\ne\n \nb\nà\n \nm\nɛ\nɛ\nr\ni\n,\n \nd\na\n \ns\ne\ne\nn\na\n \ny\ni\nr\ni\nm\nm\na\n \nm\ni\ni\n \nb\nà\n \nt\na\n \nd\na\n \ni\n \nn\nɛ\nk\ni\n \nb\nà\n \nt\nɔ\nɔ\nb\na\n.\nY\ni\nr\ni\nb\na\n \nn\na\n \nb\nà\n \ns\ni\nk\ni\nn\nd\no\n \nd\na\nr\ne\n \nb\nà\n \nm\nɛ\nɛ\nr\ni\n,\n \nd\na\n \ns\ne\ne\nn\na\n \ny\ni\nr\ni\nm\nm\na\n \nm\ni\ni\n \nb\nà\n \nt\na\n \nd\na\n \ni\n \nn\nɛ\nk\ni\n \nb\nà\n \nt\nɔ\nɔ\nb\na\n.\nY\ni\nr\ni\nb\na\n \nn\na\n \nb\nà\n \ns\ni\nk\ni\nn\nd\no\n \nd\na\nr\ne\n \nb\nà\n \nm\nɛ\nɛ\nr\ni\n,\n \nd\na\n \ns\ne\ne\nn\na\n \ny\ni\nr\ni\nm\nm\na\n \nm\ni\ni\n \nb\nà\n \nt\na\n \nd\na\n \ni\n \nn\nɛ\nk\ni\n \nb\nà\n \nt\nɔ\nɔ\nb\na\n.\nY\ni\nr\ni\nb\na\n \nn\na\n \nb\nà\n \ns\ni\nk\ni\nn\nd\no\n \nd\na\nr\ne\n \nb\nà\n \nm\nɛ\nɛ\nr"
}
