id: "xh"
language: "xh"
script: "Latn"
name: "Xhosa"
autonym: "isiXhosa"
population: 10182944
region: "LS"
region: "ZA"
exemplar_chars {
  base: "a b c d e f g h i j k l m n o p q r s t u v w x y z"
  auxiliary: ""
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
}
sample_text {
  masthead_full: "BbOo"
  masthead_partial: "Nn"
  styles: "Njengoko iimfanelo zesidima soluntu semvelo"
  tester: "Njengoko ukungananzi nokudelelwa kweemfanelo zoluntu ezingunobangela"
  poster_sm: "Kwananjalo"
  poster_md: "Njengokuba"
  poster_lg: "Bonke"
  specimen_48: "Njengoko uluntu Lwezizwe Ezimanyeneyo luthe lwaqinisekisa kukubaluleka"
  specimen_36: "Njengoko iimvisiswano zesidima soluntu nenkululeko yoluntu zibalulekile ukuze kuzuzwe esi sithembiso,"
  specimen_32: "Bonke abantu bazalwa bekhululekile belingana ngesidima nangokweemfanelo. Bonke abantu banesiphiwo sesazela nesizathu sokwenza isenzo ongathanda ukuba senziwe kumzalwane wakho."
  specimen_21: "Wonke umntu unamalungelo kwiimfanelo nenkululeko eziqulathwe kule nkcazelo, ngaphandle kokwahlulwa ngobuhlanga, ibala, ubuni, ulwimi, inkolo, ezopolitiko nezinye izimvo, ezesizwe okanye ezentlalo, ezokuzalwa okanye namanye amawonga.\nNgaphezu koko, akukho mahluko unokwenziwa usekelwe kwezopolitiko, ulawulo lwezobulungisa okanye amawonga ezizwe nezizwana okanye ummandla apho umntu akhoyo, nokuba uzimele, ukuthembeka, urhulumente ongazimelanga okanye nokuba zeziphi indlela zokunciphisa ulawulo lobukumkani."
  specimen_16: "Wonke umntu unelungelo lokuphila, inkululeko kunye nokhuseleko.\nAkukho namnye oya kugcinwa ebukhobokeni nakukhuselo lomnye umntu, kanti urhwebo ngamakhoboka aluvumelekanga nangayiphina indlela.\nAkukho namnye oyakuphathwa gadalala, ngenkohlakalo, ngokungenabuntu okanye ngempatho eluhlazo okanye isohlwayo.\nWonke umntu unelungelo lokwamkelwa yonke indawo njengomntu phambi komthetho.\nBonke abantu bayalingana phambi komthetho kwaye benamalungelo ngaphandle kocalu‐calulo ngokulinganayo kukhuseleko lomthetho. Bonke abantu banelungelo lokhuselo olulinganayo oluchasene naluphina ucalu‐calulo olwaphula le nkcazelo, nangokuchasene neendlela zothelekiso kucalu‐calulo."
}
