id: "xmn_Mani"
language: "xmn"
script: "Mani"
name: "Manichaean Middle Persian"
population: 0
sample_text {
  masthead_full: "𐫀𐫁𐫡𐫅"
  masthead_partial: "𐫖𐫍"
  styles: "𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓"
  tester: "𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓"
  poster_sm: "𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅"
  poster_md: "𐫀𐫁𐫡𐫅𐫡"
  poster_lg: "𐫀𐫁𐫡𐫅𐫡"
  specimen_48: "𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓"
  specimen_36: "𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓"
  specimen_32: "𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓"
  specimen_21: "𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓"
  specimen_16: "𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓\n𐫀𐫁𐫡𐫅𐫡 𐫖𐫍𐫏 𐫀𐫇𐫅 𐫇𐫏𐫍𐫖𐫅𐫡 𐫀𐫝 𐫶𐫶𐫶𐫶 𐫀𐫁𐫀𐫡𐫏𐫃𐫀𐫗 𐫀𐫇𐫓"
}
historical: true
