id: "xsr_Deva"
language: "xsr"
script: "Deva"
name: "Sherpa"
population: 157705
region: "NP"
sample_text {
  masthead_full: "तरमङ"
  masthead_partial: "गच"
  styles: "तेरी मिमाङगी चिजिन तङ ओछाकी ग्युला क्येने ज्युन कुन्ङ्यम गिवी। खोङ"
  tester: "तेरी मिमाङगी चिजिन तङ ओछाकी ग्युला क्येने ज्युन कुन्ङ्यम गिवी। खोङ तिवा तेरीकी रिक्पा ल्येमो खुर्ने"
  poster_sm: "तेरी मिमाङगी चिजिन"
  poster_md: "तेरी मिमाङगी"
  poster_lg: "मिमाङगी"
  specimen_48: "तेरी मिमाङगी चिजिन तङ ओछाकी ग्युला क्येने ज्युन कुन्ङ्यम गिवी। खोङ तिवा तेरीकी रिक्पा"
  specimen_36: "तेरी मिमाङगी चिजिन तङ ओछाकी ग्युला क्येने ज्युन कुन्ङ्यम गिवी। खोङ तिवा तेरीकी रिक्पा ल्येमो खुर्ने हुङगु यिन तङ तेरीकी पर्ला चिग्डील हुङगु लाका कि गोकी।"
  specimen_32: "तेरी मिमाङगी चिजिन तङ ओछाकी ग्युला क्येने ज्युन कुन्ङ्यम गिवी। खोङ तिवा तेरीकी रिक्पा ल्येमो खुर्ने हुङगु यिन तङ तेरीकी पर्ला चिग्डील हुङगु लाका कि गोकी।"
  specimen_21: "तेरी मिमाङगी चिजिन तङ ओछाकी ग्युला क्येने ज्युन कुन्ङ्यम गिवी। खोङ तिवा तेरीकी रिक्पा ल्येमो खुर्ने हुङगु यिन तङ तेरीकी पर्ला चिग्डील हुङगु लाका कि गोकी।\nतेरी मिमाङगी चिजिन तङ ओछाकी ग्युला क्येने ज्युन कुन्ङ्यम गिवी। खोङ तिवा तेरीकी रिक्पा ल्येमो खुर्ने हुङगु यिन तङ तेरीकी पर्ला चिग्डील हुङगु लाका कि गोकी।\nतेरी मिमाङगी चिजिन तङ ओछाकी ग्युला क्येने ज्युन कुन्ङ्यम गिवी। खोङ तिवा तेरीकी रिक्पा ल्येमो खुर्ने हुङगु यिन तङ तेरीकी पर्ला चिग्डील हुङगु लाका कि गोकी।\nतेरी मिमाङगी चिजिन तङ ओछाकी ग्युला क्येने ज्युन कुन्ङ्यम गिवी। खोङ तिवा तेरीकी रिक्पा ल्येमो खुर्ने हुङगु यिन तङ तेरीकी पर्ला चिग्डील हुङगु लाका कि गोकी।"
  specimen_16: "तेरी मिमाङगी चिजिन तङ ओछाकी ग्युला क्येने ज्युन कुन्ङ्यम गिवी। खोङ तिवा तेरीकी रिक्पा ल्येमो खुर्ने हुङगु यिन तङ तेरीकी पर्ला चिग्डील हुङगु लाका कि गोकी।\nतेरी मिमाङगी चिजिन तङ ओछाकी ग्युला क्येने ज्युन कुन्ङ्यम गिवी। खोङ तिवा तेरीकी रिक्पा ल्येमो खुर्ने हुङगु यिन तङ तेरीकी पर्ला चिग्डील हुङगु लाका कि गोकी।\nतेरी मिमाङगी चिजिन तङ ओछाकी ग्युला क्येने ज्युन कुन्ङ्यम गिवी। खोङ तिवा तेरीकी रिक्पा ल्येमो खुर्ने हुङगु यिन तङ तेरीकी पर्ला चिग्डील हुङगु लाका कि गोकी।\nतेरी मिमाङगी चिजिन तङ ओछाकी ग्युला क्येने ज्युन कुन्ङ्यम गिवी। खोङ तिवा तेरीकी रिक्पा ल्येमो खुर्ने हुङगु यिन तङ तेरीकी पर्ला चिग्डील हुङगु लाका कि गोकी।\nतेरी मिमाङगी चिजिन तङ ओछाकी ग्युला क्येने ज्युन कुन्ङ्यम गिवी। खोङ तिवा तेरीकी रिक्पा ल्येमो खुर्ने हुङगु यिन तङ तेरीकी पर्ला चिग्डील हुङगु लाका कि गोकी।\nतेरी मिमाङगी चिजिन तङ ओछाकी ग्युला क्येने ज्युन कुन्ङ्यम गिवी। खोङ तिवा तेरीकी रिक्पा ल्येमो खुर्ने हुङगु यिन तङ तेरीकी पर्ला चिग्डील हुङगु लाका कि गोकी।"
}
