id: "yad_Latn"
language: "yad"
script: "Latn"
name: "Yagua"
sample_text {
  masthead_full: "NnEe"
  masthead_partial: "Ss"
  styles: "N\ne\n \ns\na\nr\nu\np\na\ny\n \nn\ni\nj\ny\na\nm\ni\n \nc\nu"
  tester: "N\ne\n \ns\na\nr\nu\np\na\ny\n \nn\ni\nj\ny\na\nm\ni\n \nc\nu\nm\nu\nd\ne\nj\nu\n \nd\na\nr"
  poster_sm: "N\ne\n \ns\na\nr"
  poster_md: "N\ne\n \ns\na"
  poster_lg: "N\ne"
  specimen_48: "N\ne\n \ns\na\nr\nu\np\na\ny\n \nn\ni\nj\ny\na\nm\ni\n \nc\nu\nm\nu\nd\ne\nj\nu\n \nd\na\nr"
  specimen_36: "N\ne\n \ns\na\nr\nu\np\na\ny\n \nn\ni\nj\ny\na\nm\ni\n \nc\nu\nm\nu\nd\ne\nj\nu\n \nd\na\nr\nv\na\nn\nt\ny\na\nm\nu\ny\n \nj\na\nv\na\nt\ny\na\ns\nj\ni"
  specimen_32: "N\ne\n \ns\na\nr\nu\np\na\ny\n \nn\ni\nj\ny\na\nm\ni\n \nc\nu\nm\nu\nd\ne\nj\nu\n \nd\na\nr\nv\na\nn\nt\ny\na\nm\nu\ny\n \nj\na\nv\na\nt\ny\na\ns\nj\ni\nu\n.\n \nJ\na\nc\nh\ni\np\ni\ny\na\nd\na\nt\ni\n \nm\ni\nr"
  specimen_21: "N\ne\n \ns\na\nr\nu\np\na\ny\n \nn\ni\nj\ny\na\nm\ni\n \nc\nu\nm\nu\nd\ne\nj\nu\n \nd\na\nr\nv\na\nn\nt\ny\na\nm\nu\ny\n \nj\na\nv\na\nt\ny\na\ns\nj\ni\nu\n.\n \nJ\na\nc\nh\ni\np\ni\ny\na\nd\na\nt\ni\n \nm\ni\nr\nv\na\nr\na\n \ns\na\nm\ni\nr\nv\na\n,\n \nm\ni\nr\nv\na\nm\nu\ny\n \nn\ne\n \ns\na\nm\ni\nr\nv\na\n.\n \nR\na\nm\nu\nn\nl\nt\ni\ny\n \ns\na\nr\ni\nv\ni\nc\nh\na\nn\ni\nc\nh\na\nr\na\n \ns\na\nm\ni\nr\nv\na\nr\ni\ny\n \nj\ni\nt\ny\nu\nn\nu\n "
  specimen_16: "N\ne\n \ns\na\nr\nu\np\na\ny\n \nn\ni\nj\ny\na\nm\ni\n \nc\nu\nm\nu\nd\ne\nj\nu\n \nd\na\nr\nv\na\nn\nt\ny\na\nm\nu\ny\n \nj\na\nv\na\nt\ny\na\ns\nj\ni\nu\n.\n \nJ\na\nc\nh\ni\np\ni\ny\na\nd\na\nt\ni\n \nm\ni\nr\nv\na\nr\na\n \ns\na\nm\ni\nr\nv\na\n,\n \nm\ni\nr\nv\na\nm\nu\ny\n \nn\ne\n \ns\na\nm\ni\nr\nv\na\n.\n \nR\na\nm\nu\nn\nl\nt\ni\ny\n \ns\na\nr\ni\nv\ni\nc\nh\na\nn\ni\nc\nh\na\nr\na\n \ns\na\nm\ni\nr\nv\na\nr\ni\ny\n \nj\ni\nt\ny\nu\nn\nu\n \nv\ni\nc\nh\na\nv\na\ny\n.\nN\ne\n \ns\na\nr\nu\np\na\ny\n \nn\ni\nj\ny\na\nm\ni\n \nc\nu\nm\nu\nd\ne\nj\nu\n \nd\na\nr\nv\na\nn\nt\ny\na\nm\nu\ny\n \nj\na\nv\na\nt\ny\na\ns\nj\ni\nu\n.\n \nJ\na\nc\nh\ni\np\ni\ny\na\nd\na\nt\ni\n \nm\ni\nr\nv\na\nr\na\n \ns\na\nm\ni\nr\nv\na\n,\n \nm\ni\nr\nv\na\nm\nu\ny\n \nn\ne\n \ns\na\nm\ni\nr\nv\na\n.\n \nR\na\nm\nu\nn\nl\nt\ni\ny\n \ns\na"
}
