id: "yav"
language: "yav"
script: "Latn"
name: "Yangben"
autonym: "Nuasue"
population: 2302
region: "CM"
exemplar_chars {
  base: "a á à â ǎ ā b c d e é è ɛ {ɛ́} {ɛ̀} f h i í ì î ī k l m {mb} n {ny} ŋ {ŋg} o ó ò ô ǒ ō ɔ {ɔ́} {ɔ̀} p s t u ú ù û ǔ ū v w y {ɛ́} {ɛ̀} {mb} {ny} {ŋg} {ɔ́} {ɔ̀} {ɛ́} {ɛ̀} {mb} {ny} {ŋg} {ɔ́} {ɔ̀} {ɛ́} {ɛ̀} {mb} {ny} {ŋg} {ɔ́} {ɔ̀} {ɛ́} {ɛ̀} {mb} {ny} {ŋg} {ɔ́} {ɔ̀} {ɛ́} {ɛ̀} {mb} {ny} {ŋg} {ɔ́} {ɔ̀} {ɛ́} {ɛ̀} {mb} {ny} {ŋg} {ɔ́} {ɔ̀} {ɛ́} {ɛ̀} {mb} {ny} {ŋg} {ɔ́} {ɔ̀} {ɛ́} {ɛ̀} {mb} {ny} {ŋg} {ɔ́} {ɔ̀} {ɛ́} {ɛ̀} {mb} {ny} {ŋg} {ɔ́} {ɔ̀} {ɛ́} {ɛ̀} {mb} {ny} {ŋg} {ɔ́} {ɔ̀} {ɛ́} {ɛ̀} {mb} {ny} {ŋg} {ɔ́} {ɔ̀} {ɛ́} {ɛ̀} {mb} {ny} {ŋg} {ɔ́} {ɔ̀} {ɛ́} {ɛ̀} {mb} {ny} {ŋg} {ɔ́} {ɔ̀} {ɛ́} {ɛ̀} {mb} {ny} {ŋg} {ɔ́} {ɔ̀} {ɛ́} {ɛ̀} {mb} {ny} {ŋg} {ɔ́} {ɔ̀}"
  auxiliary: "g j q r x z"
  marks: "◌̀ ◌́ ◌̂ ◌̄ ◌̌"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B C D E Ɛ F H I K L M N Ŋ O Ɔ P S T U V W Y"
}
sample_text {
  fallback_language: "en"
}
