id: "ykg_Cyrl"
language: "ykg"
script: "Cyrl"
name: "Yukaghir, Northern"
sample_text {
  masthead_full: "КкӨө"
  masthead_partial: "Дд"
  styles: "К\nө\nд\nэ\nҥ\n \nт\nэ\nн\n \n-\n \nн\nь\nи\nд\nи\nт\nэ\n \nб"
  tester: "К\nө\nд\nэ\nҥ\n \nт\nэ\nн\n \n-\n \nн\nь\nи\nд\nи\nт\nэ\n \nб\nа\nн\nд\nь\nэ\n \nп\nа\nр\nа"
  poster_sm: "К\nө\nд\nэ\nҥ\n "
  poster_md: "К\nө\nд\nэ\nҥ"
  poster_lg: "К\nө"
  specimen_48: "К\nө\nд\nэ\nҥ\n \nт\nэ\nн\n \n-\n \nн\nь\nи\nд\nи\nт\nэ\n \nб\nа\nн\nд\nь\nэ\n \nп\nа\nр\nа"
  specimen_36: "К\nө\nд\nэ\nҥ\n \nт\nэ\nн\n \n-\n \nн\nь\nи\nд\nи\nт\nэ\n \nб\nа\nн\nд\nь\nэ\n \nп\nа\nр\nа\nw\nа\nа\nн\nь\nэ\nр\nэ\nҥ\n \nт\nу\nд\nэ\n \nч\nу\nҥ\nд\nэ"
  specimen_32: "К\nө\nд\nэ\nҥ\n \nт\nэ\nн\n \n-\n \nн\nь\nи\nд\nи\nт\nэ\n \nб\nа\nн\nд\nь\nэ\n \nп\nа\nр\nа\nw\nа\nа\nн\nь\nэ\nр\nэ\nҥ\n \nт\nу\nд\nэ\n \nч\nу\nҥ\nд\nэ\nн\n \nн\nь\nи\nл\nд\nь\nи\nл\nэ\nк\n \nэ\nн\nн\nу\nл\nҥ\nи"
  specimen_21: "К\nө\nд\nэ\nҥ\n \nт\nэ\nн\n \n-\n \nн\nь\nи\nд\nи\nт\nэ\n \nб\nа\nн\nд\nь\nэ\n \nп\nа\nр\nа\nw\nа\nа\nн\nь\nэ\nр\nэ\nҥ\n \nт\nу\nд\nэ\n \nч\nу\nҥ\nд\nэ\nн\n \nн\nь\nи\nл\nд\nь\nи\nл\nэ\nк\n \nэ\nн\nн\nу\nл\nҥ\nи\nн\nь\n-\nм\nэ\nд\nь\nу\nо\nл\nн\nу\nн\nи\n.\n \nК\nө\nд\nэ\nҥ\n \nэ\nн\nм\nу\nн\n \nч\nу\nн\nд\nэ\n \nм\nэ\n \nл\nь\nэ\nй\n,\n \nт\nа\nа\nт\nл\nь\nэ\nр\n \nл\nу\nк\nу\nн\nд\nь\nи\nи\n \nн\nь\nи\nн\nэ\nм\nд\nь\nи\nй\nи\nл\nп\nэ\n \nд\nи\nт\nэ\n "
  specimen_16: "К\nө\nд\nэ\nҥ\n \nт\nэ\nн\n \n-\n \nн\nь\nи\nд\nи\nт\nэ\n \nб\nа\nн\nд\nь\nэ\n \nп\nа\nр\nа\nw\nа\nа\nн\nь\nэ\nр\nэ\nҥ\n \nт\nу\nд\nэ\n \nч\nу\nҥ\nд\nэ\nн\n \nн\nь\nи\nл\nд\nь\nи\nл\nэ\nк\n \nэ\nн\nн\nу\nл\nҥ\nи\nн\nь\n-\nм\nэ\nд\nь\nу\nо\nл\nн\nу\nн\nи\n.\n \nК\nө\nд\nэ\nҥ\n \nэ\nн\nм\nу\nн\n \nч\nу\nн\nд\nэ\n \nм\nэ\n \nл\nь\nэ\nй\n,\n \nт\nа\nа\nт\nл\nь\nэ\nр\n \nл\nу\nк\nу\nн\nд\nь\nи\nи\n \nн\nь\nи\nн\nэ\nм\nд\nь\nи\nй\nи\nл\nп\nэ\n \nд\nи\nт\nэ\n \nэ\nн\nн\nу\nй\nу\nо\nл\n-\nм\nо\nр\nа\nw\nн\nь\nэ\nҥ\nи\n.\nК\nө\nд\nэ\nҥ\n \nт\nэ\nн\n \n-\n \nн\nь\nи\nд\nи\nт\nэ\n \nб\nа\nн\nд\nь\nэ\n \nп\nа\nр\nа\nw\nа\nа\nн\nь\nэ\nр\nэ\nҥ\n \nт\nу\nд\nэ\n \nч\nу\nҥ\nд\nэ\nн\n \nн\nь\nи\nл\nд\nь\nи\nл\nэ\nк\n \nэ\nн\nн\nу\nл\nҥ\nи\nн\nь\n-\nм\nэ\nд\nь\nу\nо\nл\nн\nу\nн\nи\n.\n \nК\nө\nд\nэ\nҥ\n \nэ\nн\nм\nу\nн\n \nч\nу\nн\nд\nэ\n \nм\nэ"
}
