id: "ykg_Cyrl"
language: "ykg"
script: "Cyrl"
name: "Yukaghir, Northern"
sample_text {
  masthead_full: "КкӨө"
  masthead_partial: "Дд"
  styles: "Көдэҥ тэн - ньидитэ бандьэ параwааньэрэҥ тудэ"
  tester: "Көдэҥ тэн - ньидитэ бандьэ параwааньэрэҥ тудэ чуҥдэн ньилдьилэк"
  poster_sm: "Көдэҥ тэн -"
  poster_md: "Көдэҥ тэн"
  poster_lg: "Көдэҥ"
  specimen_48: ""
  specimen_36: ""
  specimen_32: "Көдэҥ тэн - ньидитэ бандьэ параwааньэрэҥ тудэ чуҥдэн ньилдьилэк эннулҥинь-мэдьуолнуни. Көдэҥ энмун чундэ мэ льэй, таатльэр лукундьии ньинэмдьийилпэ дитэ эннуйуол-мораwньэҥи."
  specimen_21: "Көдэҥ тэн - ньидитэ бандьэ параwааньэрэҥ тудэ чуҥдэн ньилдьилэк эннулҥинь-мэдьуолнуни. Көдэҥ энмун чундэ мэ льэй, таатльэр лукундьии ньинэмдьийилпэ дитэ эннуйуол-мораwньэҥи.\nКөдэҥ тэн - ньидитэ бандьэ параwааньэрэҥ тудэ чуҥдэн ньилдьилэк эннулҥинь-мэдьуолнуни. Көдэҥ энмун чундэ мэ льэй, таатльэр лукундьии ньинэмдьийилпэ дитэ эннуйуол-мораwньэҥи."
  specimen_16: "Көдэҥ тэн - ньидитэ бандьэ параwааньэрэҥ тудэ чуҥдэн ньилдьилэк эннулҥинь-мэдьуолнуни. Көдэҥ энмун чундэ мэ льэй, таатльэр лукундьии ньинэмдьийилпэ дитэ эннуйуол-мораwньэҥи.\nКөдэҥ тэн - ньидитэ бандьэ параwааньэрэҥ тудэ чуҥдэн ньилдьилэк эннулҥинь-мэдьуолнуни. Көдэҥ энмун чундэ мэ льэй, таатльэр лукундьии ньинэмдьийилпэ дитэ эннуйуол-мораwньэҥи.\nКөдэҥ тэн - ньидитэ бандьэ параwааньэрэҥ тудэ чуҥдэн ньилдьилэк эннулҥинь-мэдьуолнуни. Көдэҥ энмун чундэ мэ льэй, таатльэр лукундьии ньинэмдьийилпэ дитэ эннуйуол-мораwньэҥи.\nКөдэҥ тэн - ньидитэ бандьэ параwааньэрэҥ тудэ чуҥдэн ньилдьилэк эннулҥинь-мэдьуолнуни. Көдэҥ энмун чундэ мэ льэй, таатльэр лукундьии ньинэмдьийилпэ дитэ эннуйуол-мораwньэҥи."
}
