id: "yo"
language: "yo"
script: "Latn"
name: "Yoruba"
autonym: "Èdè Yorùbá"
population: 28685568
region: "BJ"
region: "NG"
exemplar_chars {
  base: "a á à b d e é è ẹ {ẹ́} {ẹ̀} f g {gb} h i í ì j k l m ḿ {m̀} n ń ǹ o ó ò ọ {ọ́} {ọ̀} p r s ṣ t u ú ù w y {ẹ́} {ẹ̀} {gb} {m̀} {ọ́} {ọ̀} {ẹ́} {ẹ̀} {gb} {m̀} {ọ́} {ọ̀} {ẹ́} {ẹ̀} {gb} {m̀} {ọ́} {ọ̀} {ẹ́} {ẹ̀} {gb} {m̀} {ọ́} {ọ̀} {ẹ́} {ẹ̀} {gb} {m̀} {ọ́} {ọ̀} {ẹ́} {ẹ̀} {gb} {m̀} {ọ́} {ọ̀} {ẹ́} {ẹ̀} {gb} {m̀} {ọ́} {ọ̀} {ẹ́} {ẹ̀} {gb} {m̀} {ọ́} {ọ̀} {ẹ́} {ẹ̀} {gb} {m̀} {ọ́} {ọ̀} {ẹ́} {ẹ̀} {gb} {m̀} {ọ́} {ọ̀} {ẹ́} {ẹ̀} {gb} {m̀} {ọ́} {ọ̀} {ẹ́} {ẹ̀} {gb} {m̀} {ọ́} {ọ̀} {ẹ́} {ẹ̀} {gb} {m̀} {ọ́} {ọ̀} {ẹ́} {ẹ̀} {gb} {m̀} {ọ́} {ọ̀} {ẹ́} {ẹ̀} {gb} {m̀} {ọ́} {ọ̀}"
  auxiliary: "c q v x z"
  marks: "◌̀ ◌́ ◌̄ ◌̣"
  punctuation: "- ‐ ‑ – — , ; : ! ? . … \' ‘ ’ \" “ ” ( ) @ * / & # † ‡ ′ ″"
  index: "A B D E F G H I J K L M N O P R S T U W Y"
}
sample_text {
  masthead_full: "GgBb"
  masthead_partial: "Oo"
  styles: "Bí ó ti jé̩ pé s̩ís̩e àkíyèsí iyì tó jé̩ àbímó̩"
  tester: "Bí ó ti jé̩ pé àìka àwo̩n è̩tó̩ o̩mo̩nìyàn sí àti ìké̩gàn àwo̩n è̩tó̩ wò̩nyí"
  poster_sm: "Bí ó ti jé̩"
  poster_md: "Àpapò̩ ìgbìmò̩"
  poster_lg: "Gbogbo"
  specimen_48: "Gbogbo ènìyàn ni a bí ní òmìnira; iyì àti è̩tó̩ kò̩ò̩kan sì dó̩gba."
  specimen_36: "A kò gbo̩dò̩ mú e̩niké̩ni ní e̩rú tàbí kí a mú un sìn; e̩rú níní àti ò wò e̩rú ni a gbo̩dò̩ fi òfin dè ní gbogbo ò̩nà."
  specimen_32: "E̩nì kò̩ò̩kan lórílè̩‐èdè, ló ní è̩tó̩ sí àtúns̩e tó jo̩jú ní ilé‐e̩jó̩ fún ìwà tó lòdì sí è̩tó̩ o̩mo̩nìyàn, tó jé̩ kò‐s̩eé‐má‐nìí gé̩gé̩ bó s̩e wà lábé̩ òfin àti bí òfin‐ìpìlè̩ s̩e là á sílè̩."
  specimen_21: "A kò gbo̩dò̩ s̩àdédé fi òfin mú ènìyàn tàbí kí a kàn gbé ènìyàn tì mó̩lé, tàbí kí a lé ènìyàn jáde ní ìlú láìnídìí.\nE̩nì kò̩ò̩kan tí a bá fi è̩sùn kàn ló ní è̩tó̩ tó dó̩gba, tó sì kún, láti s̩àlàyé ara rè̩ ní gban̄gba, níwájú ilé‐e̩jó̩ tí kò s̩ègbè, kí wo̩n lè s̩e ìpinnu lórí è̩tó̩ àti ojús̩e rè̩ nípa irú è̩sùn ò̩ràn dídá tí a fi kàn án."
  specimen_16: "E̩nì kò̩ò̩kan ló ní è̩tó̩ pé kí a má s̩àdédé s̩e àyo̩júràn sí ò̩rò̩ ìgbésí ayé rè̩, tàbí sí ò̩rò̩e̩bí rè̩ tàbí sí ò̩rò̩ ìdílé rè̩ tàbí ìwé tí a ko̩ sí i; a kò sì gbo̩dò̩ ba iyì àti orúko̩ rè̩ jé̩. E̩nì kò̩ò̩kan ló ní è̩tó̩ sí ààbò lábé̩ òfin kúrò ló̩wó̩ irú àyo̩júràn tàbí ìbanijé̩ bé̩è̩.\nE̩nì kò̩ò̩kan ló ní è̩tó̩ sí òmìnira èrò, òmìnira è̩rí‐o̩kàn àti òmìnira e̩ sìn. E̩tó̩ yìí sì gbani láàyè láti pààrò̩ e̩ sìn tàbí ìgbàgbó̩ e̩ni. Ó sì fún e̩yo̩ e̩nì kan tàbí àkójo̩pò̩ ènìyàn láàyè láti s̩e è̩sìn wo̩n àti ìgbàgbó̩ wo̩n bó s̩e je̩ mó̩ ti ìkó̩ni, ìs̩esí, ìjó̩sìn àti ìmús̩e ohun tí wó̩n gbàgbó̩ yálà ní ìkò̩kò̩ tàbí ní gban̄gba.\nE̩nì kò̩ò̩kan ló ní è̩tó̩ sí ìsinmi àti fàájì pè̩lú àkókò tí kò pò̩ jù lé̩nu is̩é̩ àti àsìkò ìsinmi lé̩nu is̩é̩ láti ìgbà dé ìgbà tí a ó sanwó fún."
}
