id: "yue_Hani"
language: "yue"
script: "Hani"
name: "Chinese, Yue"
region: "HK"
sample_text {
  masthead_full: "生而平等"
  masthead_partial: "平等"
  styles: "鉴于对人类家庭所有嘅成员固有尊严同埋佢哋嘅平等嘅兼不移嘅权利嘅承认，係世界自由、正义同埋和平嘅基础"
  tester: "鉴于对人权嘅无视同埋侮蔑经已发展成为野蛮暴行，呢些暴行玷污咗人类嘅良心，而一个人人都有言论同埋信仰自由而且冇惊冇穷嘅世界嘅嚟临"
  poster_sm: "发布呢个世界人权宣言"
  poster_md: "人人有权享有生命"
  poster_lg: "人人生而平等"
  specimen_48: "法律嘅前人人平等，并有权享受法律嘅平等保护，唔受任何歧视。人人有权享受平等保护，以免受违反本宣言嘅任何歧视行为同埋煽动呢种歧视嘅任何行为嘅害"
  specimen_36: "鉴于对人类家庭所有嘅成员固有尊严同埋佢哋嘅平等嘅兼不移嘅权利嘅承认，係世界自由、正义同埋和平嘅基础，\n鉴于为咗使人类唔至迫不得已铤而走险对暴政同埋迫害进行反叛，有必要使人权受到法治嘅保护，\n鉴于有必要促进各国友好关系嘅发展，"
  specimen_32: "鉴于对人类家庭所有嘅成员固有尊严同埋佢哋嘅平等嘅兼不移嘅权利嘅承认，係世界自由、正义同埋和平嘅基础，\n鉴于对人权嘅无视同埋侮蔑经已发展成为野蛮暴行，呢些暴行玷污咗人类嘅良心，而一个人人都有言论同埋信仰自由而且冇惊冇穷嘅世界嘅嚟临，经已俾宣布係普通人民嘅最高心愿，\n鉴于为咗使人类唔至迫不得已铤而走险对暴政同埋迫害进行反叛，有必要使人权受到法治嘅保护，"
  specimen_21: "鉴于对人类家庭所有嘅成员固有尊严同埋佢哋嘅平等嘅兼不移嘅权利嘅承认，係世界自由、正义同埋和平嘅基础，\n鉴于对人权嘅无视同埋侮蔑经已发展成为野蛮暴行，呢些暴行玷污咗人类嘅良心，而一个人人都有言论同埋信仰自由而且冇惊冇穷嘅世界嘅嚟临，经已俾宣布係普通人民嘅最高心愿，\n鉴于为咗使人类唔至迫不得已铤而走险对暴政同埋迫害进行反叛，有必要使人权受到法治嘅保护，\n鉴于有必要促进各国友好关系嘅发展，\n鉴于各联合国国家嘅人民经已喺联合国宪章内重申佢哋对基本人权、人格尊严同埋价值同埋男女平等嘅信念，而且决定促成较大自由内嘅社会进步同埋生活水平嘅改善，\n鉴于各会员国经已誓愿共联合国合作以促进对人权同埋基本自由嘅普遍尊重兼遵行，\n鉴于对呢啲权利兼自由嘅普遍了解对于呢个誓愿嘅充分实现有好大嘅重要性，"
  specimen_16: "鉴于对人类家庭所有嘅成员固有尊严同埋佢哋嘅平等嘅兼不移嘅权利嘅承认，係世界自由、正义同埋和平嘅基础，\n鉴于对人权嘅无视同埋侮蔑经已发展成为野蛮暴行，呢些暴行玷污咗人类嘅良心，而一个人人都有言论同埋信仰自由而且冇惊冇穷嘅世界嘅嚟临，经已俾宣布係普通人民嘅最高心愿，\n鉴于为咗使人类唔至迫不得已铤而走险对暴政同埋迫害进行反叛，有必要使人权受到法治嘅保护，\n鉴于有必要促进各国友好关系嘅发展，\n鉴于各联合国国家嘅人民经已喺联合国宪章内重申佢哋对基本人权、人格尊严同埋价值同埋男女平等嘅信念，而且决定促成较大自由内嘅社会进步同埋生活水平嘅改善，\n鉴于各会员国经已誓愿共联合国合作以促进对人权同埋基本自由嘅普遍尊重兼遵行，\n鉴于对呢啲权利兼自由嘅普遍了解对于呢个誓愿嘅充分实现有好大嘅重要性，\n因此依家，\n大会，\n发布呢个世界人权宣言，作为所有人民共所有国家努力实现嘅共同标准，希望每一个人共社会机构成日谂起呢个宣言，努力通过教诲同埋教育促进对权利同埋自由嘅尊重，并通过国家嘅共国际嘅渐进措施，使呢啲权利同埋自由喺各会员国本身人民共佢哋管辖下嘅人民中得到普遍共有效嘅承认共遵行：\n人人生而平等，喺尊严同埋权利上一律平等。佢哋有理性同埋良心，而且应当以兄弟关系嘅精神相对待。\n人人有资格享有呢宣言所载嘅一切权利同埋自由，唔分种族、肤色、性别、语言、宗教、政治或其他见解、国籍或社会出身、财产、出生或其他身分等任何区别。"
}
