id: "yue_Hani"
language: "yue"
script: "Hani"
name: "Chinese, Yue"
sample_text {
  masthead_full: "人生而平"
  masthead_partial: "等喺"
  styles: "人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等\n。\n佢\n哋"
  tester: "人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等\n。\n佢\n哋\n有\n理\n性\n同\n埋\n良\n心\n，\n而\n且"
  poster_sm: "人\n人\n生\n而\n平\n等"
  poster_md: "人\n人\n生\n而\n平"
  poster_lg: "人\n人"
  specimen_48: "人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等\n。\n佢\n哋\n有\n理\n性\n同\n埋\n良\n心\n，\n而\n且"
  specimen_36: "人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等\n。\n佢\n哋\n有\n理\n性\n同\n埋\n良\n心\n，\n而\n且\n应\n当\n以\n兄\n弟\n关\n系\n嘅\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n平\n等\n，"
  specimen_32: "人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等\n。\n佢\n哋\n有\n理\n性\n同\n埋\n良\n心\n，\n而\n且\n应\n当\n以\n兄\n弟\n关\n系\n嘅\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等\n。\n佢\n哋\n有\n理\n性\n同\n埋\n良"
  specimen_21: "人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等\n。\n佢\n哋\n有\n理\n性\n同\n埋\n良\n心\n，\n而\n且\n应\n当\n以\n兄\n弟\n关\n系\n嘅\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等\n。\n佢\n哋\n有\n理\n性\n同\n埋\n良\n心\n，\n而\n且\n应\n当\n以\n兄\n弟\n关\n系\n嘅\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等\n。\n佢\n哋\n有\n理\n性\n同\n埋\n良\n心\n，\n而\n且\n应\n当\n以\n兄\n弟\n关\n系\n嘅\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等"
  specimen_16: "人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等\n。\n佢\n哋\n有\n理\n性\n同\n埋\n良\n心\n，\n而\n且\n应\n当\n以\n兄\n弟\n关\n系\n嘅\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等\n。\n佢\n哋\n有\n理\n性\n同\n埋\n良\n心\n，\n而\n且\n应\n当\n以\n兄\n弟\n关\n系\n嘅\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等\n。\n佢\n哋\n有\n理\n性\n同\n埋\n良\n心\n，\n而\n且\n应\n当\n以\n兄\n弟\n关\n系\n嘅\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等\n。\n佢\n哋\n有\n理\n性\n同\n埋\n良\n心\n，\n而\n且\n应\n当\n以\n兄\n弟\n关\n系\n嘅\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等\n。\n佢\n哋\n有\n理\n性\n同\n埋\n良\n心\n，\n而\n且\n应\n当\n以\n兄\n弟\n关\n系\n嘅\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋\n权\n利\n上\n一\n律\n平\n等\n。\n佢\n哋\n有\n理\n性\n同\n埋\n良\n心\n，\n而\n且\n应\n当\n以\n兄\n弟\n关\n系\n嘅\n精\n神\n相\n对\n待\n。\n人\n人\n生\n而\n平\n等\n，\n喺\n尊\n严\n同\n埋"
}
