id: "za"
language: "za"
script: "Latn"
name: "Zhuang"
population: 4321462
region: "CN"
sample_text {
  masthead_full: "BbOo"
  masthead_partial: "Uu"
  styles: "Aenvih roxnyinh vunz lajmbwn bonilaiz couh"
  tester: "Aenvih yawjsiuj vuhmez yinzgenz fazcanj baenz yejmanz bauhingz,"
  poster_sm: "Aenvih bwh"
  poster_md: "Aenvih aeu"
  poster_lg: "Boux"
  specimen_48: "Aenvih daengx lenzhozgoz guekgya dih yinzminz gaenq youq ndaw"
  specimen_36: "Aenvih gak veiyenzgoz gaenq siq nyuenh caeuq lenzhozgoz hozcoz, cuzcin yawjnaek, cinhhingz yinzgenz caeuq gijbwnj cwyouz,"
  specimen_32: "Boux boux ma daengz lajmbwn couh miz cwyouz, cinhyenz caeuq genzli bouxboux Bingzdaengj. gyoengq vunz miz lijsing caeuq liengzsim, wngdang daih gyoengq de lumj beixnuengx ityiengh."
  specimen_21: "Boux boux miz cwhgwz yiengjsou Seiqgyaiq Senhyenz senhbu dih genzli caeuq cwyouz, mboujlwnh cungjcuz, fuhswz, singbez, yijyenz,cunghgyau,cingci roxnaeuz gengaij gijwnq,gozciz roxnaeuz sevei cuzsinh,caizcanj, cuzsaengh roxnaeuz gizdah sinhfwn.\nLij mbouj ndeij aenvih boux vunz guekgya roxnaeuz lingjduj di cingqciq, hingz cingq roxnaeuz gozci mbouj ityiengh couh yawjsiuj de, hix mboujlwnh gaiq lingjduj neix duzliz lingjduj, dozguenj lingjdu, feih cwci lingjdu roxnaeuz cijgenz gij wnq."
  specimen_16: "Boux boux miz sengmingh, cwyouz caeuq yinzsinh nganhcienz.\nBoux lawz hix mbouj ndeij deng bienqbaenz noz baenz hoiq, gakcungj nuzli cidu caeuq nuzli gaicawx, hix wngqdang gingcij.\nBoux lawz hix mbouj ndeij deng yoengh guzhingz, roxnaeuz yoengh canznyinj , mbouj yinzdau roxnaeuz ujyuz dih daiyi roxnaeuz hingzfaz.\nBoux boux youq gizlawz cungj miz naj fazliz dih yinzgwz.\nYouq naj fazliz vunzvunz bingzdaengj,lij miz genz yiengjsou fazliz dih bingzdaengj baujhu, mbouj deng gijmaz yawjsiuj. vunzvunz miz genz yiengjsou bingzdaengj baujhu, mienx deng veizfanj bwnj senhyenz dih yinhoz gizsi hingzveiz caeuq yaekyoux gij gizsi haenx sienghaih."
}
