id: "zam_Latn"
language: "zam"
script: "Latn"
name: "Zapotec, Miahuatlán"
sample_text {
  masthead_full: "DdIi"
  masthead_partial: "Tt"
  styles: "D\ni\nt\ni\n \nm\ni\ne\nn\n \nn\nd\ni\ne\nd\n \nx\na\n \ny\ne"
  tester: "D\ni\nt\ni\n \nm\ni\ne\nn\n \nn\nd\ni\ne\nd\n \nx\na\n \ny\ne\nn\nt\n \nk\nu\na\nn\n \nn\nk"
  poster_sm: "D\ni\nt\ni\n \nm"
  poster_md: "D\ni\nt\ni\n "
  poster_lg: "D\ni"
  specimen_48: "D\ni\nt\ni\n \nm\ni\ne\nn\n \nn\nd\ni\ne\nd\n \nx\na\n \ny\ne\nn\nt\n \nk\nu\na\nn\n \nn\nk"
  specimen_36: "D\ni\nt\ni\n \nm\ni\ne\nn\n \nn\nd\ni\ne\nd\n \nx\na\n \ny\ne\nn\nt\n \nk\nu\na\nn\n \nn\nk\ni\ne\n \nx\na\n \nn\na\nk\n \nr\ni\ne\nt\ni\n \nx\na\n \nd"
  specimen_32: "D\ni\nt\ni\n \nm\ni\ne\nn\n \nn\nd\ni\ne\nd\n \nx\na\n \ny\ne\nn\nt\n \nk\nu\na\nn\n \nn\nk\ni\ne\n \nx\na\n \nn\na\nk\n \nr\ni\ne\nt\ni\n \nx\na\n \nd\ni\nb\na\n \nx\na\n \nr\no\nl\na\n.\nD\ni\nt\ni\n \nm\ni\ne"
  specimen_21: "D\ni\nt\ni\n \nm\ni\ne\nn\n \nn\nd\ni\ne\nd\n \nx\na\n \ny\ne\nn\nt\n \nk\nu\na\nn\n \nn\nk\ni\ne\n \nx\na\n \nn\na\nk\n \nr\ni\ne\nt\ni\n \nx\na\n \nd\ni\nb\na\n \nx\na\n \nr\no\nl\na\n.\nD\ni\nt\ni\n \nm\ni\ne\nn\n \nn\nd\ni\ne\nd\n \nx\na\n \ny\ne\nn\nt\n \nk\nu\na\nn\n \nn\nk\ni\ne\n \nx\na\n \nn\na\nk\n \nr\ni\ne\nt\ni\n \nx\na\n \nd\ni\nb\na\n \nx\na\n \nr\no\nl\na\n.\nD\ni\nt\ni\n \nm\ni\ne\nn\n \nn\nd\ni\ne\nd\n \nx\na\n \ny\ne\nn\nt\n \nk\nu"
  specimen_16: "D\ni\nt\ni\n \nm\ni\ne\nn\n \nn\nd\ni\ne\nd\n \nx\na\n \ny\ne\nn\nt\n \nk\nu\na\nn\n \nn\nk\ni\ne\n \nx\na\n \nn\na\nk\n \nr\ni\ne\nt\ni\n \nx\na\n \nd\ni\nb\na\n \nx\na\n \nr\no\nl\na\n.\nD\ni\nt\ni\n \nm\ni\ne\nn\n \nn\nd\ni\ne\nd\n \nx\na\n \ny\ne\nn\nt\n \nk\nu\na\nn\n \nn\nk\ni\ne\n \nx\na\n \nn\na\nk\n \nr\ni\ne\nt\ni\n \nx\na\n \nd\ni\nb\na\n \nx\na\n \nr\no\nl\na\n.\nD\ni\nt\ni\n \nm\ni\ne\nn\n \nn\nd\ni\ne\nd\n \nx\na\n \ny\ne\nn\nt\n \nk\nu\na\nn\n \nn\nk\ni\ne\n \nx\na\n \nn\na\nk\n \nr\ni\ne\nt\ni\n \nx\na\n \nd\ni\nb\na\n \nx\na\n \nr\no\nl\na\n.\nD\ni\nt\ni\n \nm\ni\ne\nn\n \nn\nd\ni\ne\nd\n \nx\na\n \ny\ne\nn\nt\n \nk\nu\na\nn\n \nn\nk\ni\ne\n \nx\na\n \nn\na\nk\n \nr\ni\ne\nt\ni\n \nx\na\n \nd\ni\nb\na\n \nx\na\n \nr\no\nl\na\n.\nD\ni\nt\ni\n \nm\ni\ne\nn\n \nn\nd\ni\ne\nd\n \nx\na\n \ny\ne\nn\nt\n \nk\nu"
}
