id: "zdj"
language: "zdj"
script: "Arab"
name: "Ngazidja Comorian"
population: 313123
region: "KM"
sample_text {
  masthead_full: "WwOo"
  masthead_partial: "Aa"
  styles: "1- Ha mwakinisho ukaya ho ukubali ye sheo"
  tester: "2- Ha mwakinisho ukaya wo upuzi no uwoneya ze haki zaki binadamu"
  poster_sm: "3- Ha mwakinisho"
  poster_md: "Wo wanadamu"
  poster_lg: "wanadamu"
  specimen_48: "Hayna mwanadamu gudjo djuwa udjinasbisha ne zehaki ne ze nyihuria"
  specimen_36: "Kapvatsi ruhusa ya wu uonndowa mwanadamu, hau umfanyiliya zitrendwa zapewu zakinyama hau za upvanguwa wo ubinadamu hahahe."
  specimen_32: "Haina mwanadamu ngena haki yauhundra maredjeyi yakweli usoni mwa yeze mahakama zalazimu haudayi zehaki mshindzi yakubaliwa zo ne shariya mshindzi hau ze shariya mbali na mbali."
  specimen_21: "Kapvatsi mwanadamu udjodjuwa ubaliliwa, ya fungwa hau yatolwa sistani hadji layezi.\nHaina mdru ngena haki, harumwa usawa watimiya yayishiliwa ha uandilifu harumwa trengwe ni mahakama yalona uhuriya pvatisna pendzeleya. Mahakama yadjo utekeleza yese haki ne ze wadjibu zahahe, hau yadjo uwonesa wo ukweli wahe yizo yatuhumlwa nizo harumwa upande wamahakama ya zitrendwa zidziro."
  specimen_16: "Kapvatsi ruhusa ya mwnadamu udjilwa kiyigozi sha mvuu harumwa yemayesha ya ndani yahahe, yahe fami yahahe ne ledaho lahahe hau yemawaswiliyano yahahe ha upulwa sheo na sharafu. Haina mdru ngena haki ya hifadhwilwa ne shariya ha upukana na zitrendwa djezi.\nHaina mwanadamu ngena uhuriya wa fikira, na hisi, na wa dini. Wo uhuriya uwo utsanganya wo mdru udjuwa ubadili dini hau yakini pvamwedja na utekeleza yedini hau ye yakini yahahe wayetche hau pvamwedja na wandru, harumwa trengwe hau ho ndani hahe, msomo na zitrendwa, na utekeleza ze nguzo zahayo na ne zedasturi."
}
