id: "zdj_Latn"
language: "zdj"
script: "Latn"
name: "Comorian, Ngazidja"
sample_text {
  masthead_full: "WwOo"
  masthead_partial: "Aa"
  styles: "Wo wanadamu piya wo uzalwa na uhuriya na"
  tester: "Wo wanadamu piya wo uzalwa na uhuriya na usawa waki undru na"
  poster_sm: "Wo wanadamu"
  poster_md: ""
  poster_lg: "wanadamu"
  specimen_48: "Wo wanadamu piya wo uzalwa na uhuriya na usawa waki undru na uhaki."
  specimen_36: ""
  specimen_32: "Wo wanadamu piya wo uzalwa na uhuriya na usawa waki undru na uhaki. Wo upwawa ankili na urambuzi hayizo yilazimu warwaliyane hazitrendwa na fikira zaki unanya."
  specimen_21: "Wo wanadamu piya wo uzalwa na uhuriya na usawa waki undru na uhaki. Wo upwawa ankili na urambuzi hayizo yilazimu warwaliyane hazitrendwa na fikira zaki unanya.\nWo wanadamu piya wo uzalwa na uhuriya na usawa waki undru na uhaki. Wo upwawa ankili na urambuzi hayizo yilazimu warwaliyane hazitrendwa na fikira zaki unanya."
  specimen_16: "Wo wanadamu piya wo uzalwa na uhuriya na usawa waki undru na uhaki. Wo upwawa ankili na urambuzi hayizo yilazimu warwaliyane hazitrendwa na fikira zaki unanya.\nWo wanadamu piya wo uzalwa na uhuriya na usawa waki undru na uhaki. Wo upwawa ankili na urambuzi hayizo yilazimu warwaliyane hazitrendwa na fikira zaki unanya.\nWo wanadamu piya wo uzalwa na uhuriya na usawa waki undru na uhaki. Wo upwawa ankili na urambuzi hayizo yilazimu warwaliyane hazitrendwa na fikira zaki unanya.\nWo wanadamu piya wo uzalwa na uhuriya na usawa waki undru na uhaki. Wo upwawa ankili na urambuzi hayizo yilazimu warwaliyane hazitrendwa na fikira zaki unanya."
}
