id: "zdj_Latn"
language: "zdj"
script: "Latn"
name: "Comorian, Ngazidja"
sample_text {
  masthead_full: "WwOo"
  masthead_partial: "Aa"
  styles: "W\no\n \nw\na\nn\na\nd\na\nm\nu\n \np\ni\ny\na\n \nw\no\n \nu"
  tester: "W\no\n \nw\na\nn\na\nd\na\nm\nu\n \np\ni\ny\na\n \nw\no\n \nu\nz\na\nl\nw\na\n \nn\na\n \nu"
  poster_sm: "W\no\n \nw\na\nn"
  poster_md: "W\no\n \nw\na"
  poster_lg: "W\no"
  specimen_48: "W\no\n \nw\na\nn\na\nd\na\nm\nu\n \np\ni\ny\na\n \nw\no\n \nu\nz\na\nl\nw\na\n \nn\na\n \nu"
  specimen_36: "W\no\n \nw\na\nn\na\nd\na\nm\nu\n \np\ni\ny\na\n \nw\no\n \nu\nz\na\nl\nw\na\n \nn\na\n \nu\nh\nu\nr\ni\ny\na\n \nn\na\n \nu\ns\na\nw\na\n \nw\na\nk\ni"
  specimen_32: "W\no\n \nw\na\nn\na\nd\na\nm\nu\n \np\ni\ny\na\n \nw\no\n \nu\nz\na\nl\nw\na\n \nn\na\n \nu\nh\nu\nr\ni\ny\na\n \nn\na\n \nu\ns\na\nw\na\n \nw\na\nk\ni\n \nu\nn\nd\nr\nu\n \nn\na\n \nu\nh\na\nk\ni\n.\n \nW\no\n "
  specimen_21: "W\no\n \nw\na\nn\na\nd\na\nm\nu\n \np\ni\ny\na\n \nw\no\n \nu\nz\na\nl\nw\na\n \nn\na\n \nu\nh\nu\nr\ni\ny\na\n \nn\na\n \nu\ns\na\nw\na\n \nw\na\nk\ni\n \nu\nn\nd\nr\nu\n \nn\na\n \nu\nh\na\nk\ni\n.\n \nW\no\n \nu\np\nw\na\nw\na\n \na\nn\nk\ni\nl\ni\n \nn\na\n \nu\nr\na\nm\nb\nu\nz\ni\n \nh\na\ny\ni\nz\no\n \ny\ni\nl\na\nz\ni\nm\nu\n \nw\na\nr\nw\na\nl\ni\ny\na\nn\ne\n \nh\na\nz\ni\nt\nr\ne\nn\nd\nw\na\n \nn\na\n \nf\ni\nk\ni\nr\na\n \nz\na\nk\ni"
  specimen_16: "W\no\n \nw\na\nn\na\nd\na\nm\nu\n \np\ni\ny\na\n \nw\no\n \nu\nz\na\nl\nw\na\n \nn\na\n \nu\nh\nu\nr\ni\ny\na\n \nn\na\n \nu\ns\na\nw\na\n \nw\na\nk\ni\n \nu\nn\nd\nr\nu\n \nn\na\n \nu\nh\na\nk\ni\n.\n \nW\no\n \nu\np\nw\na\nw\na\n \na\nn\nk\ni\nl\ni\n \nn\na\n \nu\nr\na\nm\nb\nu\nz\ni\n \nh\na\ny\ni\nz\no\n \ny\ni\nl\na\nz\ni\nm\nu\n \nw\na\nr\nw\na\nl\ni\ny\na\nn\ne\n \nh\na\nz\ni\nt\nr\ne\nn\nd\nw\na\n \nn\na\n \nf\ni\nk\ni\nr\na\n \nz\na\nk\ni\n \nu\nn\na\nn\ny\na\n.\nW\no\n \nw\na\nn\na\nd\na\nm\nu\n \np\ni\ny\na\n \nw\no\n \nu\nz\na\nl\nw\na\n \nn\na\n \nu\nh\nu\nr\ni\ny\na\n \nn\na\n \nu\ns\na\nw\na\n \nw\na\nk\ni\n \nu\nn\nd\nr\nu\n \nn\na\n \nu\nh\na\nk\ni\n.\n \nW\no\n \nu\np\nw\na\nw\na\n \na\nn\nk\ni\nl\ni\n \nn\na\n \nu\nr\na\nm\nb\nu\nz\ni\n \nh\na\ny\ni\nz\no\n \ny\ni\nl\na\nz\ni\nm\nu\n \nw\na\nr\nw\na"
}
