id: "zgh"
language: "zgh"
script: "Tfng"
name: "Standard Moroccan Tamazight"
autonym: "ⵜⴰⵎⴰⵣⵉⵖⵜ"
population: 7823574
region: "MA"
exemplar_chars {
  base: "ⴰ ⴱ ⴳ {ⴳⵯ} ⴷ ⴹ ⴻ ⴼ ⴽ {ⴽⵯ} ⵀ ⵃ ⵄ ⵅ ⵇ ⵉ ⵊ ⵍ ⵎ ⵏ ⵓ ⵔ ⵕ ⵖ ⵙ ⵚ ⵛ ⵜ ⵟ ⵡ ⵢ ⵣ ⵥ {ⴳⵯ} {ⴽⵯ} {ⴳⵯ} {ⴽⵯ} {ⴳⵯ} {ⴽⵯ} {ⴳⵯ} {ⴽⵯ} {ⴳⵯ} {ⴽⵯ} {ⴳⵯ} {ⴽⵯ} {ⴳⵯ} {ⴽⵯ} {ⴳⵯ} {ⴽⵯ} {ⴳⵯ} {ⴽⵯ} {ⴳⵯ} {ⴽⵯ} {ⴳⵯ} {ⴽⵯ} {ⴳⵯ} {ⴽⵯ} {ⴳⵯ} {ⴽⵯ} {ⴳⵯ} {ⴽⵯ} {ⴳⵯ} {ⴽⵯ}"
  numerals: "  - ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "ⴰ ⴱ ⴳ ⴷ ⴹ ⴻ ⴼ ⴽ ⵀ ⵃ ⵄ ⵅ ⵇ ⵉ ⵊ ⵍ ⵎ ⵏ ⵓ ⵔ ⵕ ⵖ ⵙ ⵚ ⵛ ⵜ ⵟ ⵡ ⵢ ⵣ ⵥ"
}
sample_text {
  masthead_full: "ⴰⵔⴷⵜ"
  masthead_partial: "ⵍⵏ"
  styles: "ⵍⵍⵉⵖ ⵜⴳⴰ ⵜⵓⴽⵣⴰ ⵏ ⵓⵍⵍⴰⵍⵓ ⵏ ⴽⴰⵢⴳⴰⵜ ⵢⴰⵏ ⵖ ⵜⴰⵡⵊⴰ"
  tester: "ⵜⴳ ⵜⴰⵎⵜⵜⴰⵡⵜ ⵏ ⵉⵣⵔⴼⴰⵏ ⵏ ⵓⴼⴳⴰⵏ ⴰⴷ ⵉⵜⵜⴰⵡⵉⵏ ⵜⵓⴳⵜⵜ ⵏ ⵎⴰⴷ ⵉⵀⵔⵛⵏ ⴰⵔ"
  poster_sm: "ⴷ ⵍⵍⵉⵖ ⵉⴳⴰ"
  poster_md: "ⴷ ⵍⵍⵉⵖ ⵉⵍⵍⴰ"
  poster_lg: "ⵜⵜⵍⴰⵍⴰⵏ"
  specimen_48: "ⴷ ⵍⵍⵉⵖ ⵎⵙⵓⵛⴽⴰⵏ ⵉⵡⴰⵏⴽⵏ ⵉⴳⵎⴰⵎⵏ, ⵙ ⵜⵡⵙⵉⵏ ⵏ ⵜⵎⴰⴷⴷⴰⵙⵜ ⵏ ⵜⵎⵜⵜⴰ ⵉⵎⵓⵏⵏ,"
  specimen_36: "ⴽⵓ ⵢⴰⵏ ⵉⵍⵍⴰ ⴷⴰⵔⵙ ⵓⵣⵔⴼ ⴰⴷ ⵉⴼⵜⵓ ⵙ ⵜⵉⵏⴼⴳⴰⵔⵉⵏ ⵜⵉⵏⴰⵎⵓⵔⵉⵏ ⵉⵖ ⵉⵍⵍⴰ ⴽⵔⴰ ⵓⵣⴳⴳⴰⵍ ⵖ ⵉⵣⵔⴼⴰⵏ ⵏⵏⵙ ⵍⵍⵉ ⵢⴰⵙ ⵉⴼⴽⴰ ⵓⵍⵓⴳⵏ."
  specimen_32: "ⵓⵔ ⵉⵅⵚⵚⴰ ⴰⴷ ⵢⵉⵍⵉ ⴽⵔⴰ ⵓⴽⵛⵛⵎ ⵉⵅⵛⵛⵏ ⵖ ⵜⵓⴷⵔⵜ ⵉⵥⵍⵉⵏ ⵙ ⴽⵔⴰ ⵏ ⵢⴰⵏ ⵏⵖⴷ ⵜⵉⵏ ⵜⵡⵊⴰ ⵏⵏⵙ ⵏⵖⴷ ⴰⵣⴷⴷⵓⵖ ⵏⵏⵙ ⵏⵖⴷ ⵉⵎⵢⴰⵡⴰⴹⵏ ⵏⵏⵙ ⵖⴷ ⴰⴷⴷⵓⵔ ⵏⵏⵙ. ⵢⵉⵍⵉ ⴷⴰⵔ ⴽⵓ ⵢⴰⵏ ⵓⵣⵔⴼ ⵏ ⵓⵃⵟⵟⵓ ⵏ ⵓⵍⵓⴳⵏ ⵖ ⵣⵓⵏⴷ ⴰⴽⵛⵛⵓⵎ ⴰⴷ."
  specimen_21: "ⴽⵓ ⵢⴰⵏ ⵉⵍⵍⴰ ⴷⴰⵔⵙ ⵓⵣⵔⴼ ⵏ ⴳ ⵜⴷⵔⴼⵉⵜ ⵏ ⵓⵙⵡⵉⵏⴳⵎ ⴷ ⵜⵉⵏ ⵜⴰⵏⵏⴰⵢⵜ, ⴷ ⵜⵉⵏ ⵓⵙⴳⴷ ⵖⵉⵍⵍⴰ ⵉⵍⵍⴰ ⵓⵣⵔⴼ ⴰⴷ ⵉⵙⵏⴼ ⴰⵙⴳⵖⵏⵏⵙ, ⵢⵉⵍⵍⵉ ⴷⴰⵔⵙ ⴰⵡⴷ ⵓⵣⵔⴼ ⵏ ⵜⵡⵏⵏⵉⵜ ⵜⴰⵏⴼⵔⵓⵜ ⵙ ⴽⵔⴰ ⵉⴳⴰⵜ ⴰⵏⴰ ⵏⵏⵙ.\nⴽⵓ ⵢⴰⵏ ⵉⵍⵍⴰ ⴷⴰⵔⵙ ⵓⵣⵔⴼ ⵏ ⵜⴷⵔⴼⵉⵜ ⵏ ⵜⴰⵏⵏⴰⵢⵜ ⴷ ⵜⵡⵏⵏⵉⵜ, ⴰⴷ ⵉⵜⵜⵉⴽⵚⵓⴹ ⵅⴼ ⵜⴰⵏⵏⴰⵢⵉⵏ ⵏⵏⵙ ⵓⵍⴰ ⴰⵔⵣⵣⵓ ⵏⵏⵙ ⴰⴷ ⵢⴰⵎⵥ ⵏⵖ ⴰⴷ ⵉⵣⵓⵣⵣⵔ, ⴰⴱⵍⴰ ⵉⵡⵜⵜⴰ, ⵉⵏⵖⵎⵉⵙⵏ ⴷ ⵜⵡⵏⴳⵉⵎⵉⵏ ⵙ ⴰⴽⵯ ⵉⵎⴰⵙⵙⵏ  ⵓⵙⵓⵙⵙⵏ."
  specimen_16: "ⴽⵓ ⵢⴰⵏ ⵉⵍⵍⴰ, ⵖⵉⴽⵍⵍⵉ ⵉⴳⴰ ⵢⴰⵏ ⵓⴼⵔⴷⵉⵙ ⵖ ⵡⴰⵎⵓⵏ, ⴷⴰⵔⵙ ⴰⵣⵔⴼ ⵖ ⵓⵏⴼⵔⵓ ⴰⵏⴰⵎⵓⵏ :ⴰⵣⵔⴼ ⴰⴷ ⵉⴱⴷⴷⴰ ⵅⴼ ⵃⵎⴰ ⴰⴷ ⵜⵉⵍⵉ ⵜⵓⵎⵔⵜ ⵏ ⵉⵣⵔⴼⴰⵏ ⵉⴷⴰⵎⵙⴰⵏⵏ, ⵉⵏⴰⵎⵓⵏⵏ ⴷ ⵉⴷⵍⵙⴰⵏⵏ ⵉⵥⵍⵉⵏ ⵙ ⴰⴷⴷⵓⵔ ⵏⵏⵙ ⴷ ⵓⵙⴱⵓⵖⵍⵓ ⵏ ⵡⵓⴷⵎ ⵏⵏⵙ, ⴰⵢⴰⴷ ⵙ ⵜⴷⵓⵙⵉ ⵜⴰⵏⴰⵎⵓⵔⵜ ⴷ ⵜⵡⵉⵙⵉ ⵜⴰⴳⵔⴰⵖⵍⴰⵏⵜ, ⵏⵏⴰ ⵉⵙⵏⵏⴷⵏ ⵅⴼ ⵓⵙⵏⵎⴰⵍⴰ ⴷ ⵉⵙⵓⴳⵉⵎ ⵏ ⴽⵓ ⵜⴰⵎⵓⵔⵜ.\nⴽⵓ ⵢⴰⵏ ⵉⵍⵍⴰ ⴷⴰⵔⵙ ⵓⵣⵔⴼ ⵏ ⵓⵙⵙⵓⵏⴼⵓ, ⵖ ⵜⵉⵣⵉ ⵍⵍⵉ ⵉⵅⵡⴰⵏ, ⴷ ⵎⵏⵛⴽ ⵏ ⵜⵙⵔⴰⴳⵉⵏ ⵏ ⵜⵡⵓⵔⵉ ⴷ ⵓⵙⵙⵏⴼⵓ ⵉⵎⵓⵏ ⴷ ⵜⵖⵔⴰⴷ.\nⴽⵓ ⵢⴰⵏ ⵉⵍⵍⴰ ⴷⴰⵔⵙ ⵓⵣⵔⴼ ⴰⴷ ⵉⵙⴼⴰⵢⴷ ⵖ ⵓⵖⴰⵡⴰⵙ ⴰⵏⴰⵎⵓⵏ ⴰⴳⵔⴰⵖⵍⴰⵏ ⵍⵍⵉⵖ ⵍⵍⴰⵏ ⵉⵣⵔⴼⴰⵏ ⴷ ⵜⴷⵔⴼⵉⵢⵉⵏ ⵍⵍⵉ ⴷ ⵢⵓⵛⴽⴰⵏ ⵖ ⴰⵍⵖⵓ ⴰⴷ.\nⵓⵔ ⵉⵍⵍⵉ ⵖ ⵓⵍⵖⵓ ⴰⴷ ⴽⵔⴰ ⵏ ⵓⴹⵕⵉⵚ ⴰⴼⴰⴷ ⴰⴷ ⵉⵙⵎⴷⵢⴰ ⴽⵔⴰ ⵏ ⵓⵡⴰⵏⴽ ⵏⵖⴷ ⴽⵔⴰ ⵏ ⵓⴳⴷⵓⴷ ⵏⵖⴷ ⵓⴼⴳⴰⵏ ⵙ ⵖⵉⴽⵍⵍⵉ ⵉⵔⴰ ⴷ ⵓⵔ ⴷⴰⵔⵙ ⴽⵔⴰ ⵏ ⵓⵣⵔⴼ ⴰⴼⴰⴷ ⵉⵙⴽⵔ ⵜⴰⵡⵔⵉ ⵏⵏⴰ ⵉⵔⴰ ⵍⵍⵉ ⵉⵜⵜⵔⵥⵥⴰⵏ ⵉⵣⵔⴼⴰⵏ ⴷ ⵜⴷⵔⴼⵢⵉⵏ ⵍⵍⵉ ⴷ ⵢⵉⵡⵉ ⵖ ⵓⵍⵖⵓ ⴰⴷ."
}
