id: "zlm_Arab"
language: "zlm"
script: "Arab"
name: "Malay, Arabic"
sample_text {
  masthead_full: "سموا"
  masthead_partial: "أن"
  styles: "س\nم\nو\nا\n \nم\nأ\nن\nس\nي\n \nد\nل\nا\nه\nي\nر\nك\nن\n \nب"
  tester: "س\nم\nو\nا\n \nم\nأ\nن\nس\nي\n \nد\nل\nا\nه\nي\nر\nك\nن\n \nب\nي\nب\nس\n \nد\nا\nن\n \nس\nا"
  poster_sm: "س\nم\nو\nا\n \nم"
  poster_md: "س\nم\nو\nا\n "
  poster_lg: "س\nم"
  specimen_48: "س\nم\nو\nا\n \nم\nأ\nن\nس\nي\n \nد\nل\nا\nه\nي\nر\nك\nن\n \nب\nي\nب\nس\n \nد\nا\nن\n \nس\nا"
  specimen_36: "س\nم\nو\nا\n \nم\nأ\nن\nس\nي\n \nد\nل\nا\nه\nي\nر\nك\nن\n \nب\nي\nب\nس\n \nد\nا\nن\n \nس\nا\nم\nر\nا\nت\n \nد\nر\nي\n \nس\nڬ\nي\n \nك\nم\nو\nل\nي\nأ\nن"
  specimen_32: "س\nم\nو\nا\n \nم\nأ\nن\nس\nي\n \nد\nل\nا\nه\nي\nر\nك\nن\n \nب\nي\nب\nس\n \nد\nا\nن\n \nس\nا\nم\nر\nا\nت\n \nد\nر\nي\n \nس\nڬ\nي\n \nك\nم\nو\nل\nي\nأ\nن\n \nد\nا\nن\n \nح\nق\n٢\n.\n \nم\nر\nي\nك\n \nم\nم\nڤ\nو\nڽ"
  specimen_21: "س\nم\nو\nا\n \nم\nأ\nن\nس\nي\n \nد\nل\nا\nه\nي\nر\nك\nن\n \nب\nي\nب\nس\n \nد\nا\nن\n \nس\nا\nم\nر\nا\nت\n \nد\nر\nي\n \nس\nڬ\nي\n \nك\nم\nو\nل\nي\nأ\nن\n \nد\nا\nن\n \nح\nق\n٢\n.\n \nم\nر\nي\nك\n \nم\nم\nڤ\nو\nڽ\nا\nي\n \nڤ\nم\nي\nك\nي\nر\nن\n \nد\nا\nن\n \nڤ\nر\nا\nس\nأ\nن\n \nه\nا\nت\nي\n \nد\nا\nن\n \nه\nن\nد\nق\nل\nه\n \nب\nر\nت\nي\nن\nد\nق\n \nد\n \nا\nن\nت\nا\nر\nا\n \nس\nا\nت\nو\n \nس\nا\nم\n \nل\nا\nئ\nن\n \nد\nڠ\nن\n \nس\nم\nا\nڠ\nت\n \nڤ"
  specimen_16: "س\nم\nو\nا\n \nم\nأ\nن\nس\nي\n \nد\nل\nا\nه\nي\nر\nك\nن\n \nب\nي\nب\nس\n \nد\nا\nن\n \nس\nا\nم\nر\nا\nت\n \nد\nر\nي\n \nس\nڬ\nي\n \nك\nم\nو\nل\nي\nأ\nن\n \nد\nا\nن\n \nح\nق\n٢\n.\n \nم\nر\nي\nك\n \nم\nم\nڤ\nو\nڽ\nا\nي\n \nڤ\nم\nي\nك\nي\nر\nن\n \nد\nا\nن\n \nڤ\nر\nا\nس\nأ\nن\n \nه\nا\nت\nي\n \nد\nا\nن\n \nه\nن\nد\nق\nل\nه\n \nب\nر\nت\nي\nن\nد\nق\n \nد\n \nا\nن\nت\nا\nر\nا\n \nس\nا\nت\nو\n \nس\nا\nم\n \nل\nا\nئ\nن\n \nد\nڠ\nن\n \nس\nم\nا\nڠ\nت\n \nڤ\nر\nس\nا\nو\nد\nا\nر\nأ\nن\n.\nس\nم\nو\nا\n \nم\nأ\nن\nس\nي\n \nد\nل\nا\nه\nي\nر\nك\nن\n \nب\nي\nب\nس\n \nد\nا\nن\n \nس\nا\nم\nر\nا\nت\n \nد\nر\nي\n \nس\nڬ\nي\n \nك\nم\nو\nل\nي\nأ\nن\n \nد\nا\nن\n \nح\nق\n٢\n.\n \nم\nر\nي\nك\n \nم\nم\nڤ\nو\nڽ\nا\nي\n \nڤ\nم\nي\nك\nي\nر\nن\n \nد\nا\nن\n \nڤ\nر\nا\nس\nأ\nن\n \nه\nا\nت\nي\n \nد\nا\nن\n \nه\nن\nد\nق\nل\nه\n \nب\nر\nت\nي\nن\nد\nق"
}
