id: "zlm_Latn"
language: "zlm"
script: "Latn"
name: "Malay, Latin"
sample_text {
  masthead_full: "SsEe"
  masthead_partial: "Mm"
  styles: "S\ne\nm\nu\na\n \nm\na\nn\nu\ns\ni\na\n \nd\ni\nl\na\nh\ni\nr"
  tester: "S\ne\nm\nu\na\n \nm\na\nn\nu\ns\ni\na\n \nd\ni\nl\na\nh\ni\nr\nk\na\nn\n \nb\ne\nb\na\ns\n "
  poster_sm: "S\ne\nm\nu\na\n "
  poster_md: "S\ne\nm\nu\na"
  poster_lg: "S\ne"
  specimen_48: "S\ne\nm\nu\na\n \nm\na\nn\nu\ns\ni\na\n \nd\ni\nl\na\nh\ni\nr\nk\na\nn\n \nb\ne\nb\na\ns\n "
  specimen_36: "S\ne\nm\nu\na\n \nm\na\nn\nu\ns\ni\na\n \nd\ni\nl\na\nh\ni\nr\nk\na\nn\n \nb\ne\nb\na\ns\n \nd\na\nn\n \ns\na\nm\na\nr\na\nt\na\n \nd\na\nr\ni\n \ns\ne"
  specimen_32: "S\ne\nm\nu\na\n \nm\na\nn\nu\ns\ni\na\n \nd\ni\nl\na\nh\ni\nr\nk\na\nn\n \nb\ne\nb\na\ns\n \nd\na\nn\n \ns\na\nm\na\nr\na\nt\na\n \nd\na\nr\ni\n \ns\ne\ng\ni\n \nk\ne\nm\nu\nl\ni\na\na\nn\n \nd\na\nn\n \nh\na\nk"
  specimen_21: "S\ne\nm\nu\na\n \nm\na\nn\nu\ns\ni\na\n \nd\ni\nl\na\nh\ni\nr\nk\na\nn\n \nb\ne\nb\na\ns\n \nd\na\nn\n \ns\na\nm\na\nr\na\nt\na\n \nd\na\nr\ni\n \ns\ne\ng\ni\n \nk\ne\nm\nu\nl\ni\na\na\nn\n \nd\na\nn\n \nh\na\nk\n-\nh\na\nk\n.\n \nM\ne\nr\ne\nk\na\n \nm\ne\nm\np\nu\nn\ny\na\ni\n \np\ne\nm\ni\nk\ni\nr\na\nn\n \nd\na\nn\n \np\ne\nr\na\ns\na\na\nn\n \nh\na\nt\ni\n \nd\na\nn\n \nh\ne\nn\nd\na\nk\nl\na\nh\n \nb\ne\nr\nt\ni\nn\nd\na\nk\n \nd\ni\n \na\nn\nt"
  specimen_16: "S\ne\nm\nu\na\n \nm\na\nn\nu\ns\ni\na\n \nd\ni\nl\na\nh\ni\nr\nk\na\nn\n \nb\ne\nb\na\ns\n \nd\na\nn\n \ns\na\nm\na\nr\na\nt\na\n \nd\na\nr\ni\n \ns\ne\ng\ni\n \nk\ne\nm\nu\nl\ni\na\na\nn\n \nd\na\nn\n \nh\na\nk\n-\nh\na\nk\n.\n \nM\ne\nr\ne\nk\na\n \nm\ne\nm\np\nu\nn\ny\na\ni\n \np\ne\nm\ni\nk\ni\nr\na\nn\n \nd\na\nn\n \np\ne\nr\na\ns\na\na\nn\n \nh\na\nt\ni\n \nd\na\nn\n \nh\ne\nn\nd\na\nk\nl\na\nh\n \nb\ne\nr\nt\ni\nn\nd\na\nk\n \nd\ni\n \na\nn\nt\na\nr\na\n \ns\na\nt\nu\n \ns\na\nm\na\n \nl\na\ni\nn\n \nd\ne\nn\ng\na\nn\n \ns\ne\nm\na\nn\ng\na\nt\n \np\ne\nr\ns\na\nu\nd\na\nr\na\na\nn\n.\nS\ne\nm\nu\na\n \nm\na\nn\nu\ns\ni\na\n \nd\ni\nl\na\nh\ni\nr\nk\na\nn\n \nb\ne\nb\na\ns\n \nd\na\nn\n \ns\na\nm\na\nr\na\nt\na\n \nd\na\nr\ni\n \ns\ne\ng\ni\n \nk\ne\nm\nu\nl\ni\na\na\nn\n \nd\na\nn\n \nh\na\nk\n-\nh\na\nk\n.\n \nM"
}
