id: "zro_Latn"
language: "zro"
script: "Latn"
name: "Záparo"
sample_text {
  masthead_full: "KkAa"
  masthead_partial: "Ww"
  styles: "K\na\nw\ni\nr\ni\na\nj\na\n \nk\na\ny\na\np\nu\ni\nn\na\n \ni"
  tester: "K\na\nw\ni\nr\ni\na\nj\na\n \nk\na\ny\na\np\nu\ni\nn\na\n \ni\nc\nh\na\nu\nk\nu\ni\n \nt\na"
  poster_sm: "K\na\nw\ni\nr\ni"
  poster_md: "K\na\nw\ni\nr"
  poster_lg: "K\na"
  specimen_48: "K\na\nw\ni\nr\ni\na\nj\na\n \nk\na\ny\na\np\nu\ni\nn\na\n \ni\nc\nh\na\nu\nk\nu\ni\n \nt\na"
  specimen_36: "K\na\nw\ni\nr\ni\na\nj\na\n \nk\na\ny\na\np\nu\ni\nn\na\n \ni\nc\nh\na\nu\nk\nu\ni\n \nt\na\n \nn\nu\nk\na\n \np\nu\nc\nh\na\n \np\na\nn\ni\nc\nh\na\n "
  specimen_32: "K\na\nw\ni\nr\ni\na\nj\na\n \nk\na\ny\na\np\nu\ni\nn\na\n \ni\nc\nh\na\nu\nk\nu\ni\n \nt\na\n \nn\nu\nk\na\n \np\nu\nc\nh\na\n \np\na\nn\ni\nc\nh\na\n \nk\nu\np\na\nn\ni\nm\na\nj\ni\nc\nh\na\n \nc\nh\na\n \nn\nu"
  specimen_21: "K\na\nw\ni\nr\ni\na\nj\na\n \nk\na\ny\na\np\nu\ni\nn\na\n \ni\nc\nh\na\nu\nk\nu\ni\n \nt\na\n \nn\nu\nk\na\n \np\nu\nc\nh\na\n \np\na\nn\ni\nc\nh\na\n \nk\nu\np\na\nn\ni\nm\na\nj\ni\nc\nh\na\n \nc\nh\na\n \nn\nu\nk\na\n \nn\ni\ns\nh\ni\nm\na\n \ni\nk\ni\nc\nh\na\n \nk\ni\nn\ni\na\nn\na\n \np\na\nn\ni\nc\nh\na\n \nt\na\nm\na\nn\nu\nk\na\n \nk\na\nn\na\nt\na\n \ni\nk\ni\nm\na\nj\ni\nc\nh\na\n.\nK\na\nw\ni\nr\ni\na\nj\na\n \nk\na\ny\na\np\nu\ni\nn\na"
  specimen_16: "K\na\nw\ni\nr\ni\na\nj\na\n \nk\na\ny\na\np\nu\ni\nn\na\n \ni\nc\nh\na\nu\nk\nu\ni\n \nt\na\n \nn\nu\nk\na\n \np\nu\nc\nh\na\n \np\na\nn\ni\nc\nh\na\n \nk\nu\np\na\nn\ni\nm\na\nj\ni\nc\nh\na\n \nc\nh\na\n \nn\nu\nk\na\n \nn\ni\ns\nh\ni\nm\na\n \ni\nk\ni\nc\nh\na\n \nk\ni\nn\ni\na\nn\na\n \np\na\nn\ni\nc\nh\na\n \nt\na\nm\na\nn\nu\nk\na\n \nk\na\nn\na\nt\na\n \ni\nk\ni\nm\na\nj\ni\nc\nh\na\n.\nK\na\nw\ni\nr\ni\na\nj\na\n \nk\na\ny\na\np\nu\ni\nn\na\n \ni\nc\nh\na\nu\nk\nu\ni\n \nt\na\n \nn\nu\nk\na\n \np\nu\nc\nh\na\n \np\na\nn\ni\nc\nh\na\n \nk\nu\np\na\nn\ni\nm\na\nj\ni\nc\nh\na\n \nc\nh\na\n \nn\nu\nk\na\n \nn\ni\ns\nh\ni\nm\na\n \ni\nk\ni\nc\nh\na\n \nk\ni\nn\ni\na\nn\na\n \np\na\nn\ni\nc\nh\na\n \nt\na\nm\na\nn\nu\nk\na\n \nk\na\nn\na\nt\na\n \ni\nk\ni\nm\na\nj\ni\nc\nh\na\n.\nK\na\nw\ni\nr\ni\na\nj\na\n \nk\na\ny"
}
