id: "ztu_Latn"
language: "ztu"
script: "Latn"
name: "Zapotec, Güilá"
sample_text {
  masthead_full: "RrAa"
  masthead_partial: "Tt"
  styles: "R\na\n\'\nt\na\n \nr\na\n \nb\nu\n:\nu\nn\nn\ny\n \nr\na\n:\na\na"
  tester: "R\na\n\'\nt\na\n \nr\na\n \nb\nu\n:\nu\nn\nn\ny\n \nr\na\n:\na\na\nl\ny\n \nl\ni\ne\nb\nr\n \nc"
  poster_sm: "R\na\n\'\nt\na\n "
  poster_md: "R\na\n\'\nt\na"
  poster_lg: "R\na"
  specimen_48: "R\na\n\'\nt\na\n \nr\na\n \nb\nu\n:\nu\nn\nn\ny\n \nr\na\n:\na\na\nl\ny\n \nl\ni\ne\nb\nr\n \nc"
  specimen_36: "R\na\n\'\nt\na\n \nr\na\n \nb\nu\n:\nu\nn\nn\ny\n \nr\na\n:\na\na\nl\ny\n \nl\ni\ne\nb\nr\n \nc\në\nh\nn\nn\n \nt\ne\n\'\nb\nl\no\nh\n \nd\ne\nr\ne\ne\n\'\nc\nh"
  specimen_32: "R\na\n\'\nt\na\n \nr\na\n \nb\nu\n:\nu\nn\nn\ny\n \nr\na\n:\na\na\nl\ny\n \nl\ni\ne\nb\nr\n \nc\në\nh\nn\nn\n \nt\ne\n\'\nb\nl\no\nh\n \nd\ne\nr\ne\ne\n\'\nc\nh\n \nc\në\nh\nn\nn\n \nd\ni\ng\nn\ni\nd\na\na\n.\n \nR\na\n:\na"
  specimen_21: "R\na\n\'\nt\na\n \nr\na\n \nb\nu\n:\nu\nn\nn\ny\n \nr\na\n:\na\na\nl\ny\n \nl\ni\ne\nb\nr\n \nc\në\nh\nn\nn\n \nt\ne\n\'\nb\nl\no\nh\n \nd\ne\nr\ne\ne\n\'\nc\nh\n \nc\në\nh\nn\nn\n \nd\ni\ng\nn\ni\nd\na\na\n.\n \nR\na\n:\na\nl\ny\nn\ne\n:\ne\nr\ni\nh\n \ng\na\nh\nl\nl\n \nr\ni\n:\ne\n:\ne\nn\ny\n \nc\në\nh\nn\nn\n \ns\na\na\nl\ny\nb\n,\n \nc\nh\ni\nr\nu\n\'\n \nn\na\n:\na\n \np\na\nh\nr\n \ng\na\n:\na\nn\nn\nz\na\n\'\nc\nr\ni\nh\n \nl\no\nh\n \ns\na\n\'\nr\ni\nh\n.\nR\na\n\'\nt\na"
  specimen_16: "R\na\n\'\nt\na\n \nr\na\n \nb\nu\n:\nu\nn\nn\ny\n \nr\na\n:\na\na\nl\ny\n \nl\ni\ne\nb\nr\n \nc\në\nh\nn\nn\n \nt\ne\n\'\nb\nl\no\nh\n \nd\ne\nr\ne\ne\n\'\nc\nh\n \nc\në\nh\nn\nn\n \nd\ni\ng\nn\ni\nd\na\na\n.\n \nR\na\n:\na\nl\ny\nn\ne\n:\ne\nr\ni\nh\n \ng\na\nh\nl\nl\n \nr\ni\n:\ne\n:\ne\nn\ny\n \nc\në\nh\nn\nn\n \ns\na\na\nl\ny\nb\n,\n \nc\nh\ni\nr\nu\n\'\n \nn\na\n:\na\n \np\na\nh\nr\n \ng\na\n:\na\nn\nn\nz\na\n\'\nc\nr\ni\nh\n \nl\no\nh\n \ns\na\n\'\nr\ni\nh\n.\nR\na\n\'\nt\na\n \nr\na\n \nb\nu\n:\nu\nn\nn\ny\n \nr\na\n:\na\na\nl\ny\n \nl\ni\ne\nb\nr\n \nc\në\nh\nn\nn\n \nt\ne\n\'\nb\nl\no\nh\n \nd\ne\nr\ne\ne\n\'\nc\nh\n \nc\në\nh\nn\nn\n \nd\ni\ng\nn\ni\nd\na\na\n.\n \nR\na\n:\na\nl\ny\nn\ne\n:\ne\nr\ni\nh\n \ng\na\nh\nl\nl\n \nr\ni\n:\ne\n:\ne\nn\ny\n \nc\në\nh\nn\nn\n \ns\na\na\nl\ny\nb\n,\n \nc\nh\ni\nr\nu\n\'\n \nn\na\n:\na\n \np\na\nh\nr\n \ng\na\n:\na\nn\nn"
}
