name: "OpenType features in practice"
authors: "Elliot Jay Stocks"
reviewers: "Doug Wilson"
reviewers: "Ellen Lupton"
reviewers: "Laurence Penney"
reviewers: "Micah Rich"
reviewers: "Thomas Phinney"
reviewers: "Tyler Finck"
reviewers: "Viviana Monsalve"
topics: "open_type"
prev_lessons: "introducing_alternate_glyphs"
next_lessons: "introducing_variable_fonts"
related_terms: "open_type"
related_terms: "glyph"
related_terms: "web_font"
related_terms: "file_size"
excerpt: "When attempting to implement any OpenType feature, it’s important to ensure that it’s actually doable."
