name: "Optimizing typographic space with variable fonts"
authors: "Nick Sherman"
reviewers: "Laurence Penney"
reviewers: "Piper Haywood"
topics: "variable_fonts"
related_terms: "variable_fonts"
prev_lessons: "web_font_comparisons_variable_vs_static"
next_lessons: "interactive_animations_with_variable_fonts"
excerpt: "Variable fonts offer much more flexibility for typesetting in both printed and digital media, and this flexibility is especially beneficial in the context of responsive design."
