name: "Vertical spacing & line-height in design systems"
authors: "Sebastian Bailey"
reviewers: "Laurence Penney"
topics: "INSERT_TOPIC"
related_terms: "INSERT_RELATED_TERMS"
prev_lessons: "from_type_to_logotype"
next_lessons: "adding_an_authentic_natural_touch_to_type
excerpt: "INSERT_EXCERPT"
