name: "INSERT_TITLE"
authors: "INSERT_AUTHOR"
reviewers: "INSERT_REVIEWER"
topics: "INSERT_TOPIC"
related_terms: "INSERT_RELATED_TERMS"
prev_lessons: "from_type_to_logotype"
next_lessons: "adding_an_authentic_natural_touch_to_type
excerpt: "INSERT_EXCERPT"
