name: "Script (writing system)"
excerpt: "A collective way of describing a writing system used by multiple languages, not to be confused with the “script” classification of typefaces."
related_lessons: "INSERT_RELATED_LESSONS_AS_MANY_AS_NEEDED"
