id: "yua"
name: "Yucateco"
preferred_name: ""
autonym: "Màaya t\'àan"
population: 861955
region: "MX"
script: "Latin"
exemplar_chars {
  base: "A B C D E I J K L M N O P R S T U W X Y Á À É È Ó Ò Ú Ù a b c d e i j k l m n o p r s t u w x y \' á à é è ó ò ú ù"
  marks: "◌̀ ◌́"
}
