name: "What have the Romans ever done for us?"
authors: "John Boardley"
reviewers: "Gerry Leonidas"
reviewers: "Ben Weiner"
topics: "type_history"
prev_lessons: "the_invention_of_type"
next_lessons: "transitional_faces"
related_terms: "blackletter"
related_terms: "color"
related_terms: "calligraphy"
related_terms: "greek_script"
related_terms: "latin"
related_terms: "letterform"
excerpt: "How roman fonts overtook blackletter to dominate European typography."
