version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /axisregistry
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /lang
    schedule:
      interval: daily
