name: "Grape Nuts"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2022-02-17"
fonts {
  name: "Grape Nuts"
  style: "normal"
  weight: 400
  filename: "GrapeNuts-Regular.ttf"
  post_script_name: "GrapeNuts-Regular"
  full_name: "Grape Nuts Regular"
  copyright: "Copyright 2003 The Grape Nuts Project Authors (https://github.com/googlefonts/grapenuts)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
