name: "Dakelh (Carrier) Syllabics"
authors: "Kevin King"
reviewers: "Elliot Jay Stocks"
reviewers: "Peter Biľak"
topics: "language_support"
topics: "syllabics"
prev_lessons: "dene_syllabics"
related_terms: "contrast"
related_terms: "alternates"
related_terms: "readability"
related_terms: "shaping"
related_terms: "typsetting"
excerpt: "This article presents and describes the local orthographic requirements and typographic preferences for the Dakelh (Carrier) Syllabics-using communities."
