name: "Vujahday Script"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-11-18"
fonts {
  name: "Vujahday Script"
  style: "normal"
  weight: 400
  filename: "VujahdayScript-Regular.ttf"
  post_script_name: "VujahdayScript-Regular"
  full_name: "Vujahday Script Regular"
  copyright: "Copyright 2003 The Vujahday Script Project Authors (https://github.com/googlefonts/vujahday)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
