id: "sw"
name: "Swahili"
preferred_name: "Swahili"
autonym: "Kiswahili"
population: 171610296
region: "UG"
region: "SO"
region: "KE"
region: "TZ"
region: "BI"
region: "MZ"
region: "YT"
region: "ZA"
region: "CD"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P R S T U V W Y Z a b c d e f g h i j k l m n o p r s t u v w y z"
  auxiliary: "c q x"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‑ , ; \\: ! ? . \' \" ( ) \\[ \\] \\{ \\}"
  index: "A B {CH} D E F G H I J K L M N O P R S T U V W Y Z"
}
