name: "Grechen Fuemen"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-09-02"
fonts {
  name: "Grechen Fuemen"
  style: "normal"
  weight: 400
  filename: "GrechenFuemen-Regular.ttf"
  post_script_name: "GrechenFuemen-Regular"
  full_name: "Grechen Fuemen Regular"
  copyright: "Copyright 2003-2021 The Grechen Fuemen Project Authors (https://github.com/googlefonts/grechen-fuemen)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
