name: "Alternates"
excerpt: "Alternates (also known as alternate characters or alternate glyphs) are substitute letterforms that supplement the default character set."
related_lessons: "introducing_alternate_glyphs"
