name: "Yomogi"
designer: "Satsuyako"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-04-14"
fonts {
  name: "Yomogi"
  style: "normal"
  weight: 400
  filename: "Yomogi-Regular.ttf"
  post_script_name: "Yomogi-Regular"
  full_name: "Yomogi Regular"
  copyright: "Copyright 2020 The Yomogi Project Authors (https://github.com/satsuyako/YomogiFont), all rights reserved."
}
subsets: "cyrillic"
subsets: "japanese"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
primary_script: "Hira"
