name: "Unicode"
excerpt: "Every single glyph in a font has an associated unicode reference: a unique identifier that corresponds with the same character in other typefaces."
related_lessons: "choosing_reliable_typefaces"
related_lessons: "using_web_fonts"
