name: "Modern type"
authors: "John Boardley"
reviewers: "Gerry Leonidas"
reviewers: "Ben Weiner"
topics: "type_history"
related_terms: "typeface"
related_terms: "transitional_neo_classical"
related_terms: "counter"
prev_lessons: "transitional_faces"
next_lessons: "display_type"
excerpt: "Bodoni and Didot, and the rise of the Modern high contrast style."
