name: "The foundations of web typography"
authors: "Elliot Jay Stocks"
reviewers: "Doug Wilson"
reviewers: "Ellen Lupton"
reviewers: "Frank Rausch"
reviewers: "Gerry Leonidas"
reviewers: "Laurence Penney"
reviewers: "Richard Rutter"
reviewers: "Thomas Phinney"
topics: "essentials"
topics: "families"
prev_lessons: "using_web_fonts"
next_lessons: "using_web_fonts_from_a_font_delivery_service"
next_lessons: "styling_type_on_the_web_with_variable_fonts"
related_terms: "measure_line_length"
related_terms: "web_font"
excerpt: "An absolute beginner’s guide to setting type on the web, from CSS basics to implementing web fonts."
