language: python

dist: xenial 

python:
  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y jq
  - sudo apt-get install -y libfreetype6-dev libglib2.0-dev libcairo2-dev libharfbuzz-dev libharfbuzz-bin

install:
  - pip install git+https://github.com/googlefonts/gftools

script:
  - python viz_pr.py
  - sh run_fb.sh

