language: python

dist: xenial 

python:
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y jq
  - sudo apt-get install -y libfreetype6-dev libglib2.0-dev libcairo2-dev
  - curl -O "https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-2.3.0.tar.bz2"
  - tar -xjvf "harfbuzz-2.3.0.tar.bz2"
  - cd harfbuzz-2.3.0
  - ./configure --with-cairo=yes
  - make
  - cd util
  - PATH=$(pwd):$PATH
  - cd ../..

install:
  - pip install git+https://github.com/googlefonts/gftools

script:
  - gftools qa -pr https://github.com/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST -gfb -a -o qa -ogh

