language: python

dist: focal

python:
  - "3.8"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y jq
  - sudo apt-get install -y libharfbuzz-dev libfreetype6-dev libglib2.0-dev libcairo2-dev

install:
  - pip install gftools[qa]

script:
  - bash .ci/run.sh

