name: "File size"
excerpt: "A key consideration for web typography: Font files, like all website assets, are resources that need downloading—this affects overall loading times."
related_lessons: "using_web_fonts"
related_lessons: "open_type_features_in_practice"
