name: "Kurale"
designer: "Eduardo Tunni"
license: "OFL"
category: "SERIF"
date_added: "2015-05-14"
fonts {
  name: "Kurale"
  style: "normal"
  weight: 400
  filename: "Kurale-Regular.ttf"
  post_script_name: "Kurale-Regular"
  full_name: "Kurale Regular"
  copyright: "Copyright 2013 The Kurale Project Authors (edu@tipo.net.ar)"
}
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "devanagari"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
