name: "Interpolation"
excerpt: "The use of software to populate intermediate instances of a font between two masters."
related_lessons: "how_typefaces_are_designed_and_fonts_are_made"
related_lessons: "introducing_weights_styles"
related_lessons: "introducing_variable_fonts"
