name: "Weight? Wait, don’t tell me, make me look for myself"
authors: "David Berlow"
topics: "type_design"
topics: "weight"
topics: "variable_fonts"
prev_lessons: "size"
related_terms: "weight"
related_terms: "variable_fonts"
related_terms: "optical_sizes"
related_terms: "glyph"
excerpt: "The weight of a typeface has long been expressed by names, like Regular, Bold, Light or Thin, which later called for standard numbers. Today these numbers are represented by the OpenType and CSS range from 100 to 1,000, typically assigned in 100’s, with 400 being the “text” weight and 700 the Bold weight of that."
