id: "tiv"
name: "Tiv"
preferred_name: ""
autonym: "Tiv"
population: 3424448
region: "NG"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O Ô P R S T U V W Y Z a b c d e f g h i j k l m n o ô p r s t u v w y z"
  marks: "◌̂"
}
