name: "Introducing alternate glyphs"
authors: "Elliot Jay Stocks"
reviewers: "Bram Stein"
reviewers: "Doug Wilson"
reviewers: "Erik Spiekermann"
reviewers: "Frank Rausch"
reviewers: "Jamie Clarke"
reviewers: "Laurence Penney"
reviewers: "Mark Boulton"
reviewers: "Richard Rutter"
reviewers: "Santiago Orozco"
reviewers: "Thomas Phinney"
topics: "open_type"
prev_lessons: "introducing_weights_styles"
next_lessons: "understanding_numerals"
next_lessons: "open_type_features_in_practice"
related_terms: "open_type"
related_terms: "ligature"
related_terms: "swash_glyph"
related_terms: "numerals_figures"
related_terms: "fractions"
related_terms: "stylistic_sets"
related_terms: "alternates"
related_terms: "small_caps"
excerpt: "The default characters we see in a typeface aren’t necessarily the only options available to us."
