name: "Type"
excerpt: "The mechanized and consistent reproduction of letterforms that make up written language."
related_lessons: "why_care_about_typography"
related_lessons: "choosing_reliable_typefaces"
