name: "Type classification in CJK: Chinese"
authors: "Lisa Huang"
reviewers: "Min-Young Kim"
reviewers: "Minjoo Ham"
reviewers: "Shoko Mugikura"
topics: "cjk"
related_terms: "cjk"
related_terms: "script_writing_system"
next_lessons: "type_classification_in_cjk_japanese"
excerpt: "Here, we look at how CJK scripts are classified differently from Latin, and also from each other, with a focus on Chinese."
