"""
Catalog-wide audit script for scanning full Google Fonts repository.
Features real-time progress tracking, ETA calculation, and human-readable Markdown/JSON/CSV report exports.
Located internally within google/fonts at .ci/autoupdater/catalog_audit.py.
"""

import sys
import os
import glob
import json
import csv
import time
import threading
import concurrent.futures
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any, List

# Ensure .ci is in sys.path
ci_dir = str(Path(__file__).parent.parent)
if ci_dir not in sys.path:
    sys.path.insert(0, ci_dir)

from autoupdater.orchestrator import AutoUpdatePipeline
from autoupdater.metadata_parser import load_metadata_pb

pr_lock = threading.Lock()


def format_eta(seconds: float) -> str:
    """Format seconds into HH:MM:SS string."""
    if seconds <= 0 or seconds > 86400:
        return "--:--:--"
    m, s = divmod(int(seconds), 60)
    h, m = divmod(m, 60)
    return f"{h:02d}:{m:02d}:{s:02d}"


def make_progress_bar(pct: float, width: int = 20) -> str:
    """Generate ASCII progress bar string."""
    filled = int(round(width * pct / 100))
    bar = "█" * filled + "░" * (width - filled)
    return bar


def generate_markdown_report(report: Dict[str, Any], results: List[Dict[str, Any]], output_filepath: str = "catalog_audit_report.md") -> str:
    """Generate human-readable Markdown audit report."""
    summary = report.get("catalog_summary", {})
    breakdown = report.get("update_breakdown", {})
    pcts = report.get("percentages", {})

    lines = []
    lines.append("# 📊 Google Fonts Upstream Auto-Update Audit Report")
    lines.append("")
    lines.append(f"**Date:** `{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}`")
    lines.append(f"**Families Audited:** `{summary.get('families_audited', 0)}` (out of `{summary.get('total_families_in_repo', 0)}` total in catalog)")
    lines.append(f"**Audit Speed:** `{summary.get('average_rate_per_sec', 0)}` families/sec | **Elapsed:** `{summary.get('elapsed_time_seconds', 0)}` seconds")
    lines.append("")

    lines.append("## 📈 Audit Summary & Decision Tiers")
    lines.append("")
    lines.append("| Metric Category | Count | Percentage |")
    lines.append("| :--- | :--- | :--- |")
    lines.append(f"| **Total Upstream Updates Detected** | **{breakdown.get('total_updated', 0)}** | **{pcts.get('update_rate', 0)}%** |")
    lines.append(f"| 🟢 **AUTO_APPROVE (Safe to Auto-Merge)** | **{breakdown.get('safe_to_update_automatically', 0)}** | **{pcts.get('safe_auto_update_pct', 0)}%** of updates |")
    lines.append(f"| 🟡 **NEEDS_REVIEW (Maintainer Attention)** | **{breakdown.get('needs_review_count', 0)}** | - |")
    lines.append(f"| 🔴 **BLOCKED (Breaking / Regressed)** | **{breakdown.get('blocked_count', 0)}** | - |")
    lines.append(f"| ⚪ **Up-to-Date (No Action Required)** | {breakdown.get('no_update', 0)} | - |")
    lines.append(f"| ⚠️ **API Errors / Rate Limited** | {breakdown.get('api_rate_limited_or_error', 0)} | - |")
    lines.append("")

    updated_results = [r for r in results if r.get("has_update")]
    if updated_results:
        lines.append("## 🚀 Detected Upstream Font Updates")
        lines.append("")
        lines.append("| Family Name | Installed Version | Upstream Version | STU Score | Decision Tier | Scoring Rationale | Status |")
        lines.append("| :--- | :--- | :--- | :--- | :--- | :--- | :--- |")

        for r in updated_results:
            fam = r.get("family_name", "Unknown")
            cur_v = r.get("current_version", "N/A") or "N/A"
            up_v = r.get("upstream_version", "N/A") or "N/A"
            score = r.get("safety_score", 0.0)
            tier = r.get("safety_tier", "UNKNOWN")
            status = r.get("status", "CHECKED")

            tier_badge = {
                "AUTO_APPROVE": "🟢 AUTO_APPROVE",
                "NEEDS_REVIEW": "🟡 NEEDS_REVIEW",
                "BLOCKED": "🔴 BLOCKED",
            }.get(tier, tier)

            rationale = {
                "AUTO_APPROVE": "High confidence: zero visual regressions, stable metrics & clean QA",
                "NEEDS_REVIEW": "Review needed: minor rendering shift or QA check warning detected",
                "BLOCKED": "Hard-blocked: visual rendering regression or fatal QA error detected",
            }.get(tier, "Evaluated")

            lines.append(f"| **{fam}** | `{cur_v}` | `{up_v}` | `{score} / 100` | {tier_badge} | {rationale} | `{status}` |")
        lines.append("")

    lines.append("---")
    lines.append("*Report generated by Google Fonts Automated Upstream Update System (GFAU)*")

    content = "\n".join(lines)
    Path(output_filepath).write_text(content, encoding="utf-8")
    return content


def export_csv_report(results: List[Dict[str, Any]], output_filepath: str = "catalog_audit_report.csv") -> None:
    """Export audit results table to CSV file."""
    fieldnames = [
        "family_name",
        "has_update",
        "update_type",
        "current_version",
        "upstream_version",
        "safety_score",
        "safety_tier",
        "auto_merge_qualified",
        "status",
        "error",
    ]

    with open(output_filepath, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for r in results:
            writer.writerow(r)


def process_single_family(item):
    filepath, meta, pipeline, max_prs, pr_counter, base_branch = item

    try:
        # Step 1: Run standard pipeline check in-memory without disk mutations
        res = pipeline.process_family(filepath, create_pr=False, base_branch=base_branch)

        # Step 2: If an update is available, claim PR slot if under max_prs limit
        if res.get("has_update") and max_prs > 0:
            should_create_pr = False
            with pr_lock:
                if pr_counter[0] < max_prs:
                    pr_counter[0] += 1
                    should_create_pr = True

            if should_create_pr:
                version_str = res.get("upstream_version") or (res.get("upstream_commit")[:7] if res.get("upstream_commit") else "update")
                pr_title = f"🤖 Update upstream font: {meta.name} v{version_str}"
                pr_info = pipeline.pr_creator.create_pull_request(
                    family_name=meta.name,
                    metadata_filepath=filepath,
                    updated_pb_content=res.get("updated_pb_content", ""),
                    pr_title=pr_title,
                    pr_body=res.get("pr_body", ""),
                    candidate_ttf_fonts=res.get("candidate_ttf_fonts"),
                    upstream_version=res.get("upstream_version"),
                    upstream_commit=res.get("upstream_commit"),
                    base_branch=base_branch,
                )
                res["pr_info"] = pr_info
                if pr_info and pr_info.get("created"):
                    res["status"] = "PR_CREATED"
                else:
                    # Release slot if PR creation failed so another family can try
                    with pr_lock:
                        pr_counter[0] = max(0, pr_counter[0] - 1)

        return res
    except Exception as e:
        return {
            "family_name": meta.name if meta else Path(filepath).parent.name,
            "has_update": False,
            "error": str(e),
            "status": "ERROR",
        }




def run_full_catalog_audit(
    fonts_repo_path: str = ".",
    max_families: int = 0,
    max_workers: int = 10,
    db_path: str = "gf_catalog_full_audit.db",
    progress_file: str = "gf_audit_progress.json",
    log_interval: int = 50,
    max_prs: int = 1,
    base_branch: str = "main",
) -> Dict[str, Any]:
    pattern = os.path.join(fonts_repo_path, "*", "*", "METADATA.pb")
    pb_files = glob.glob(pattern)

    print(f"🔍 Discovered {len(pb_files)} total font families in '{fonts_repo_path}'.")
    pipeline = AutoUpdatePipeline(state_db_path=db_path)

    valid_families = []
    for f in pb_files:
        try:
            meta = load_metadata_pb(f)
            if meta.source and meta.source.repository_url:
                valid_families.append((f, meta))
        except Exception:
            pass

    print(f"🌐 Found {len(valid_families)} families with valid upstream repository URLs.")
    target_families = valid_families[:max_families] if (max_families and max_families > 0) else valid_families

    total_count = len(target_families)

    if total_count == 0:
        print("⚠️ No valid font families to process.")
        return {"catalog_summary": {"total_audited": 0}}

    pr_counter = [0]
    work_items = [(f, meta, pipeline, max_prs, pr_counter, base_branch) for f, meta in target_families]
    results = []

    print(f"\n🚀 Launching multi-threaded GFAU audit sweep ({total_count} families, {max_workers} worker threads, max PRs: {max_prs})...")
    print("=" * 95)

    start_time = time.time()
    completed = 0
    updated_count = 0
    auto_approve_count = 0
    needs_review_count = 0
    blocked_count = 0
    error_count = 0

    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(process_single_family, item): item for item in work_items}

        for future in concurrent.futures.as_completed(futures):
            res = future.result()
            results.append(res)
            completed += 1

            status = res.get("status")
            has_up = res.get("has_update", False)
            tier = res.get("safety_tier")

            if status == "ERROR":
                error_count += 1
            elif has_up:
                updated_count += 1
                if tier == "AUTO_APPROVE":
                    auto_approve_count += 1
                elif tier == "NEEDS_REVIEW":
                    needs_review_count += 1
                elif tier == "BLOCKED":
                    blocked_count += 1

            elapsed = time.time() - start_time
            pct = (completed / total_count) * 100
            rate = completed / elapsed if elapsed > 0 else 0
            remaining_sec = (total_count - completed) / rate if rate > 0 else 0
            eta_str = format_eta(remaining_sec)
            bar = make_progress_bar(pct, width=15)

            family_name = res.get("family_name", "Unknown")

            progress_snap = {
                "completed": completed,
                "total": total_count,
                "pct_complete": round(pct, 2),
                "rate_per_sec": round(rate, 2),
                "elapsed_sec": round(elapsed, 1),
                "eta_formatted": eta_str,
                "updated_count": updated_count,
                "auto_approve_count": auto_approve_count,
                "needs_review_count": needs_review_count,
                "blocked_count": blocked_count,
                "error_count": error_count,
                "prs_created": pr_counter[0],
                "last_processed": family_name,
                "last_status": "UPDATED" if has_up else status,
            }
            try:
                Path(progress_file).write_text(json.dumps(progress_snap, indent=2))
            except Exception:
                pass

            if completed % log_interval == 0 or completed == total_count or has_up:
                print(
                    f"[{completed:4d}/{total_count:4d} | {pct:5.1f}%] {bar} | "
                    f"🟢 Auto:{auto_approve_count:2d} | 🟡 Review:{needs_review_count:2d} | 🔴 Block:{blocked_count:2d} | "
                    f"⚡ {rate:4.1f}/s | ⌛ ETA:{eta_str} | Last: {family_name}"
                )
                sys.stdout.flush()

    print("=" * 95)
    print(f"✅ Catalog audit sweep completed! Created {pr_counter[0]} PR(s).")

    not_safe_count = needs_review_count + blocked_count
    total_elapsed = round(time.time() - start_time, 2)

    updated_families = [
        {"family": r.get("family_name"), "score": r.get("safety_score"), "tier": r.get("safety_tier")}
        for r in results if r.get("has_update")
    ]

    report = {
        "catalog_summary": {
            "total_families_in_repo": len(pb_files),
            "families_with_source_repo": len(valid_families),
            "families_audited": total_count,
            "elapsed_time_seconds": total_elapsed,
            "average_rate_per_sec": round(total_count / total_elapsed, 2) if total_elapsed > 0 else 0,
            "prs_created": pr_counter[0],
        },
        "update_breakdown": {
            "total_updated": updated_count,
            "no_update": completed - updated_count - error_count,
            "safe_to_update_automatically": auto_approve_count,
            "not_safe_to_update_automatically": not_safe_count,
            "needs_review_count": needs_review_count,
            "blocked_count": blocked_count,
            "api_rate_limited_or_error": error_count,
        },
        "percentages": {
            "update_rate": round((updated_count / (total_count - error_count)) * 100, 2) if (total_count - error_count) > 0 else 0,
            "safe_auto_update_pct": round((auto_approve_count / updated_count) * 100, 2) if updated_count else 0,
            "not_safe_auto_update_pct": round((not_safe_count / updated_count) * 100, 2) if updated_count else 0,
        },
        "updated_families_list": updated_families[:25],
    }

    generate_markdown_report(report, results, output_filepath="catalog_audit_report.md")
    export_csv_report(results, output_filepath="catalog_audit_report.csv")
    Path("catalog_audit_report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")

    print("📄 Generated human-readable report exports:")
    print("  - Markdown: catalog_audit_report.md")
    print("  - CSV Table: catalog_audit_report.csv")
    print("  - JSON Data: catalog_audit_report.json")

    return report


if __name__ == "__main__":
    fonts_repo = "."
    if len(sys.argv) > 1:
        fonts_repo = sys.argv[1]

    max_families = 0
    if len(sys.argv) > 2:
        max_families = int(sys.argv[2])


    max_workers = 10
    if len(sys.argv) > 3:
        max_workers = int(sys.argv[3])

    log_interval = 50
    if len(sys.argv) > 4:
        log_interval = int(sys.argv[4])

    max_prs = 1
    if len(sys.argv) > 5:
        max_prs = int(sys.argv[5])

    base_branch = "main"
    if len(sys.argv) > 6:
        base_branch = sys.argv[6]

    report = run_full_catalog_audit(
        fonts_repo,
        max_families=max_families,
        max_workers=max_workers,
        log_interval=log_interval,
        max_prs=max_prs,
        base_branch=base_branch,
    )
    print("\n=================== FULL CATALOG AUDIT REPORT ===================")
    print(json.dumps(report, indent=2))
