name: "Masters"
excerpt: "A complete set of glyphs designed in one particular style within a type family, used to create intermediate weights."
related_lessons: "introducing_weights_styles"
related_lessons: "exploring_typefaces_with_multiple_weights_or_grades"
related_lessons: "introducing_variable_fonts"
