name: "Masters"
excerpt: "A complete set of glyphs designed in one particular style within a type family, used to create intermediate weights."
related_lessons: "INSERT_RELATED_LESSONS_AS_MANY_AS_NEEDED"
