name: "Working with hanging punctuation"
authors: "Elliot Jay Stocks"
reviewers: "Doug Wilson"
reviewers: "Frank Rausch"
reviewers: "Jessica Hische"
reviewers: "John Boardley"
reviewers: "Mark Boulton"
reviewers: "Yves Peters"
topics: "systems"
prev_lessons: "avoiding_widows_orphans"
prev_lessons: "exploring_punctuation"
next_lessons: "breaking_the_rules"
related_terms: "quotation_mark"
excerpt: "Because punctuation takes up a space but does not usually fill that space, such marks can create unintended optical indentations."
