name: "Track carefully or not at all"
authors: "Elliot Jay Stocks"
reviewers: "David Brezina"
reviewers: "Doug Wilson"
reviewers: "Frank Rausch"
reviewers: "Laurence Penney"
reviewers: "Yves Peters"
topics: "essentials"
prev_lessons: "understanding_measure_line_length"
next_lessons: "manual_kerning_is_rarely_required"
related_terms: "tracking_letter_spacing"
related_terms: "ligature"
excerpt: "Because tracking is a manual adjustment made to type, it should be approached with a great deal of caution."
