tag: "FLAR"
display_name: "Flair"
min_value: 0.0
default_value: 0.0
max_value: 100.0
precision: 1
fallback {
  name: "Normal"
  value: 0.0
}
fallback {
  name: "Flair"
  value: 100.0
}
description: 
  "As the flair axis grows, the straight sans serif terminals develop"
  " a swelling, and joints become more idiosyncratic. Originally referring"
  " to the flaring of the stems, Flair stands for style and panache."
