# FOR TESTING ONLY [for now anyway]
# MONO based on https://github.com/arrowtype/Recursive#variable-axes
tag: "MONO"
display_name: "Monospace"
min_value: 0
max_value: 1
default_value: 0
precision: -2
fallback {
  name: "Proportional"
  value: 0
}
fallback {
  name: "Monospace"
  value: 1
}
description:
  "Adjust the style from proportional (natural widths, default) to"
  " monospace (fixed width). Monospace is when all glyphs have the same"
  " total character width, and more wide or narrow letter proportions to fill"
  " the space such as a narrower 'w' or wider 'r.' Proportionally spaced"
  "fonts have letters drawn with more typical proportions, and each glyph"
  "takes up a unique amount of space on a line."
