# wght based on https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_wght
tag: "wght"
display_name: "Weight"
min_value: 1
max_value: 1000
default_value: 400
precision: 0
fallback {
  name: "Thin"
  value: 100
}
fallback {
  name: "Extra Light"
  value: 200
}
fallback {
  name: "Light"
  value: 300
}
fallback {
  name: "Regular"
  value: 400
}
fallback {
  name: "Medium"
  value: 500
}
fallback {
  name: "Semi Bold"
  value: 600
}
fallback {
  name: "Bold"
  value: 700
}
fallback {
  name: "Extra Bold"
  value: 800
}
fallback {
  name: "Black"
  value: 900
}
description:
  "Adjust the style from lighter to bolder in typographic color, by varying"
  " stroke thicknesses or other forms. This typically changes overall width,"
  " and so may be used in conjunction with axes for Width and Grade (if"
  " present)."
