# WONK based on https://github.com/undercasetype/Fraunces#variable-axes
tag: "WONK"
display_name: "Wonky"
min_value: 0
max_value: 1
default_value: 0
precision: 0
fallback {
  name: "Non Wonky"
  value: 0
}
fallback {
  name: "Wonky"
  value: 1
}
description:
  "Binary axis to control the subsitution of wonky forms along the"
  " optical size axis. 'Off' (0) maintains more normalized letterforms,"
  " such as the leaning n/m/h in roman, or the bulbous flags in the"
  " b/d/h/k/l of the italic."
  " In static fonts, this is also available as an OpenType Stylistic Set."
