# XTRA based on https://variationsguide.typenetwork.com/#xtra
tag: "XTRA"
display_name: "X transparent"
min_value: -1000
max_value: 2000
default_value: 400
precision: 0
fallback {
  name: "Normal"
  value: 400
}
description:
  "Assigns a 'white'”' per mille value to each instance of the design space."
