# YTLC based on https://variationsguide.typenetwork.com/#ytlc
tag: "YTLC"
display_name: "Y transparent lowercase"
min_value: 0
max_value: 1000
default_value: 500
precision: 0
fallback {
  name: "Normal"
  value: 500
}
description:
  "Assigns a 'white' per mille value to each instance of the design space."
