# YTUC based on https://variationsguide.typenetwork.com/#ytuc
tag: "YTUC"
display_name: "Y transparent uppercase"
min_value: 0
max_value: 1000
default_value: 725
precision: 0
fallback {
  name: "Normal"
  value: 725
}
fallback_only: false
description:
  "Assigns a 'white' per mille value to each instance of the design space."
