name: "Counter"
excerpt: "The transparent space enclosed inside a letterform. Counters can be closed, as in “o” and “d”, or open, as in “c” and “u.”"
related_lessons: "an_overview_of_latin_type_anatomy"
