name: "Fuggles"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-04-29"
fonts {
  name: "Fuggles"
  style: "normal"
  weight: 400
  filename: "Fuggles-Regular.ttf"
  post_script_name: "Fuggles-Regular"
  full_name: "Fuggles Regular"
  copyright: "Copyright 2021 The Fuggles Pro Project Authors (https://github.com/googlefonts/fuggles)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
