id: "wa"
name: "Walloon"
preferred_name: ""
autonym: "Walon"
population: 679800
region: "BE"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Â Å Ç È É Ê Î Ô Û a b c d e f g h i j k l m n o p q r s t u v w x y z â å ç è é ê î ô û"
  marks: "◌̀ ◌́ ◌̂ ◌̊ ◌̧"
}
