name: "Stylistic sets"
excerpt: "Groupings of alternate glyphs that allow the user to switch on (via OpenType) sets of related alternate glyphs one at a time."
related_lessons: "introducing_alternate_glyphs"
related_lessons: "open_type_features_in_practice"
related_lessons: "implementing_open_type_features_on_the_web"
