name: "Darumadrop One"
designer: "Maniackers Design"
license: "OFL"
category: "DISPLAY"
date_added: "2020-12-14"
fonts {
  name: "Darumadrop One"
  style: "normal"
  weight: 400
  filename: "DarumadropOne-Regular.ttf"
  post_script_name: "DarumadropOne-Regular"
  full_name: "Darumadrop One Regular"
  copyright: "Copyright 2020 The Darumadrop Project Authors (https://github.com/ManiackersDesign/darumadrop), all rights reserved."
}
subsets: "japanese"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
languages: "ja_Kana"
languages: "ja_Hira"
primary_script: "Hira"
stroke: "SANS_SERIF"
classifications: "DISPLAY"
