name: "How typefaces are designed & fonts are made"
authors: "Jamie Clarke"
reviewers: "Thomas Phinney"
reviewers: "Gerry Leonidas"
topics: "type_design"
topics: "essentials"
topics: "open_type"
related_terms: "typeface"
related_terms: "character"
related_terms: "style"
related_terms: "spaces"
related_terms: "masters"
related_terms: "licensing"
prev_lessons: "introducing_color_fonts"
excerpt: "An overview of the type design process, from ideation and sketching right through to making fonts and releasing them."
