name: "Adding fonts to Google Docs and Slides"
authors: "Elliot Jay Stocks"
reviewers: "Thomas Phinney"
topics: "essentials"
related_terms: "typeface"
related_terms: "italic"
related_terms: "weight"
excerpt: "INSERT_EXCERPT"
