name: "Tenor Sans"
designer: "Denis Masharov"
license: "OFL"
category: "SANS_SERIF"
date_added: "2011-05-25"
fonts {
  name: "Tenor Sans"
  style: "normal"
  weight: 400
  filename: "TenorSans-Regular.ttf"
  post_script_name: "TenorSans"
  full_name: "Tenor Sans"
  copyright: "Copyright (c) 2010, 2011, Denis Masharov <denis.masharov@gmail.com>. This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL"
}
subsets: "menu"
subsets: "cyrillic"
subsets: "latin"
subsets: "latin-ext"
stroke: "SANS_SERIF"
classifications: "DISPLAY"
