name: "Praise"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-10-13"
fonts {
  name: "Praise"
  style: "normal"
  weight: 400
  filename: "Praise-Regular.ttf"
  post_script_name: "Praise-Regular"
  full_name: "Praise Regular"
  copyright: "Copyright 2014 The Praise Project Authors (https://github.com/googlefonts/praise-script)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
