id: "gu"
name: "Gujarati"
preferred_name: ""
autonym: "ગુજરાતી"
population: 59679028
region: "KE"
region: "IN"
script: "Gujarati"
exemplar_chars {
  base: "અ આ ઇ ઈ ઉ ઊ ઋ પ એ ઐ ઓ ઔ ક ખ ગ ઘ ઙ ચ છ જ ઝ ઞ ટ ઠ ડ ઢ ણ ત થ દ ધ ન ફ બ ભ મ ય ર લ વ શ ષ સ હ ળ"
  auxiliary: "ॐ"
  marks: "◌ં ◌ઃ ◌ા ◌િ ◌ી ◌ુ ◌ૂ ◌ૃ ◌ે ◌ૈ ◌ો ◌ૌ ◌્"
  numerals: "૦ ૧ ૨ ૩ ૪ ૫ ૬ ૭ ૮ ૯ 0 1 2 3 4 5 6 7 8 9"
  punctuation: "। ॥ ॰"
  index: "અ {અ\\u0A82} {અઃ} આ ઇ ઈ ઉ ઊ ઋ ઍ એ ઐ ઑ ઓ ઔ ક {ક\\u0ACDષ} ખ ગ ઘ ઙ ચ છ જ {જ\\u0ACDઞ} ઝ ઞ ટ ઠ ડ ઢ ણ ત {ત\\u0ACDર} થ દ ધ ન પ ફ બ ભ મ ય ર લ વ શ ષ સ હ ળ"
}
