id: "fon"
name: "Fon"
preferred_name: ""
autonym: "fɔ̀ngbè"
population: 3216150
region: "BJ"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G I J K L M N O P R S T U V W X Y Z Ɖ Ɛ Ɔ À Á È É Ì Í Ò Ó Ù Ú a b c d e f g i j k l m n o p r s t u v w x y z ɖ ɛ ɔ à á è é ì í ò ó ù ú"
  marks: "◌̀ ◌́"
}
