name: "Explora"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-08-10"
fonts {
  name: "Explora"
  style: "normal"
  weight: 400
  filename: "Explora-Regular.ttf"
  post_script_name: "Explora-Regular"
  full_name: "Explora Regular"
  copyright: "Copyright 2011 The Explora Project Authors (https://github.com/googlefonts/explora)"
}
subsets: "cherokee"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
stroke: "SERIF"
classifications: "DISPLAY"
