id: "man"
name: "Mandingo"
preferred_name: ""
autonym: "Maninkakan"
population: 630460
region: "GM"
script: "Latin"
script: "N’Ko"
exemplar_chars {
  base: "ߐ ߏ ߎ ߍ ߌ ߋ ߊ ߙ ߘ ߗ ߖ ߕ ߔ ߓ ߡ ߟ ߞ ߝ ߜ ߛ ߚ ߒ ߦ ߥ ߤ ߣ ߢ"
  marks: "◌߫ ◌߬ ◌߭ ◌߮ ◌߯ ◌߰ ◌߱"
  numerals: "߀ ߁ ߂ ߃ ߄ ߅ ߆ ߇ ߈ ߉"
}
