id: "ak"
name: "Akan"
preferred_name: ""
autonym: "Twi"
population: 11442678
region: "GH"
script: "Latin"
exemplar_chars {
  base: "A B D E F G H I K L M N O P R S T U W Y Ɛ Ɔ a b d e f g h i k l m n o p r s t u w y ɛ ɔ"
  auxiliary: "c j q v z"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B C D E Ɛ F G H I J K L M N O Ɔ P Q R S T U V W X Y Z"
}
