id: "pam"
name: "Pampanga"
preferred_name: ""
autonym: "Kapampangan"
population: 2511162
region: "PH"
script: "Latin"
exemplar_chars {
  base: "A B D E G H I K L M N O P Q R S T U W Y a b d e g h i k l m n o p r s t u w y"
  auxiliary: "C F J V X Z c f j q v x z"
}
