name: "Alignment & justification"
excerpt: "In paragraphs of (western) text, alignment refers to the invisible vertical line implied by a block of type. Justified text is aligned to both left and right margins."
related_lessons: "working_with_hanging_punctuation"
related_lessons: "understanding_measure_line_length"
related_lessons: "avoiding_widows_orphans"
