name: "Parametric Uppercase Height axis (YTUC)"
excerpt: "A parametric axis for varying the heights of uppercase letterforms."
related_lessons: "introducing_variable_fonts"
related_lessons: "introducing_parametric_axes"
