id: "pau"
name: "Palauan"
preferred_name: ""
autonym: "a tekoi er a Belau"
population: 16046
region: "PW"
script: "Latin"
exemplar_chars {
  base: "A B C D E Ę F I K L M N O P R S T U Z a b c d e ę f i k l m n o p r s t u z"
  marks: "◌̨"
}
