name: "Birthstone"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-08-06"
fonts {
  name: "Birthstone"
  style: "normal"
  weight: 400
  filename: "Birthstone-Regular.ttf"
  post_script_name: "Birthstone-Regular"
  full_name: "Birthstone Regular"
  copyright: "Copyright 2019 The Birthstone Project Authors (https://github.com/googlefonts/birthstone)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
