id: "kmb"
name: "Kimbundu"
preferred_name: ""
autonym: ""
population: 8130575
region: "AO"
script: "Latin"
exemplar_chars {
  base: "A B D E F H I J K L M N O P S T U V X Z a b d e f h i j k l m n o p s t u v x z"
}
