name: "Exploring x-height & the em square"
authors: "Elliot Jay Stocks"
reviewers: "Bram Stein"
reviewers: "Bruce Willen"
reviewers: "Doug Wilson"
reviewers: "Ellen Lupton"
reviewers: "Frank Rausch"
reviewers: "Mark Boulton"
reviewers: "Santiago Orozco"
reviewers: "Thomas Phinney"
reviewers: "Yves Peters"
topics: "essentials"
topics: "pairing_type"
topics: "systems"
prev_lessons: "emotive_considerations_for_choosing_typefaces"
next_lessons: "choosing_a_suitable_line_height"
related_terms: "x_height"
related_terms: "em"
related_terms: "line_height_leading"
excerpt: "When we swap fonts, or we introduce another font, there’s very often a slight change in layout. Let’s explore what’s going on."
