name: "Exploring typefaces with multiple weights or grades"
authors: "Elliot Jay Stocks"
topics: "choosing_type"
topics: "weight"
prev_lessons: "choosing_reliable_typefaces"
prev_lessons: "introducing_weights_styles"
next_lessons: "exploring_width_in_type"
next_lessons: "styling_type_on_the_web_with_variable_fonts"
related_terms: "weight"
related_terms: "optical_sizes"
excerpt: "There are many scenarios where multiple weights—if not multiple styles—are not just desired, but essential."
