id: "se"
name: "Northern Sami"
preferred_name: ""
autonym: "Sámegiella"
population: 51529
region: "SE"
region: "NO"
region: "FI"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Á Ä Å Æ Ö Ø Č Đ Ŋ Š Ŧ Ž a b c d e f g h i j k l m n o p q r s t u v w x y z á ä å æ ö ø č đ ŋ š ŧ ž"
  auxiliary: "à ç é è í ń ñ ó ò q ú w x y ü ø æ å ä ã ö"
  marks: "◌́ ◌̈ ◌̊ ◌̌"
  numerals: "  , % ‰ + − 0 1 2 3 4 5 6 7 8 9"
  index: "A Á B C Č D Đ E É F G H I J K L M N Ŋ O P Q R S Š T Ŧ U V W X Y Z Ž Ø Æ Å Ä Ö"
}
