name: "Passions Conflict"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-10-08"
fonts {
  name: "Passions Conflict"
  style: "normal"
  weight: 400
  filename: "PassionsConflict-Regular.ttf"
  post_script_name: "PassionsConflict-Regular"
  full_name: "Passions Conflict Regular"
  copyright: "Copyright 2004 The Hurricane Project Authors (https://github.com/googlefonts/passions-conflict)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
