id: "fr"
name: "French"
preferred_name: ""
autonym: "Français"
population: 272965534
region: "HU"
region: "CF"
region: "GQ"
region: "BF"
region: "US"
region: "NE"
region: "PM"
region: "GB"
region: "TN"
region: "RO"
region: "WF"
region: "SC"
region: "AT"
region: "CI"
region: "MA"
region: "VU"
region: "MC"
region: "GP"
region: "IE"
region: "MT"
region: "RE"
region: "RW"
region: "BJ"
region: "PT"
region: "CM"
region: "GF"
region: "DJ"
region: "FR"
region: "LU"
region: "PF"
region: "MF"
region: "MU"
region: "CG"
region: "LB"
region: "BL"
region: "BI"
region: "CY"
region: "NC"
region: "BE"
region: "CA"
region: "KM"
region: "YT"
region: "NL"
region: "CH"
region: "IT"
region: "MQ"
region: "ML"
region: "GR"
region: "TG"
region: "DZ"
region: "GA"
region: "SN"
region: "GN"
region: "MR"
region: "SY"
region: "HT"
region: "MG"
region: "AD"
region: "TF"
region: "TD"
region: "DE"
region: "CD"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z À Â Æ Ç È É Ê Ë Î Ï Ô Ù Û Ü Ÿ Œ a b c d e f g h i j k l m n o p q r s t u v w x y z à â æ ç è é ê ë î ï ô ù û ü ÿ œ"
  auxiliary: "á å ä ã ā ć ē í ì ī ĳ ñ ó ò ö õ ø ř š ſ ß ú ǔ"
  marks: "◌̀ ◌́ ◌̂ ◌̈ ◌̧"
  numerals: "  \\- ‑ , . % ‰ + − 0 1 2 ² 3 ³ 4 5 6 7 8 9 ᵈ ᵉ ʳ ˢ"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … ’ \" “ ” « » ( ) \\[ \\] § @ * / \\& # † ‡"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
}
