name: "Ruge Boogie"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2011-12-19"
fonts {
  name: "Ruge Boogie"
  style: "normal"
  weight: 400
  filename: "RugeBoogie-Regular.ttf"
  post_script_name: "RugeBoogie-Regular"
  full_name: "Ruge Boogie Regular"
  copyright: "Copyright 2015 The Ruge Boogie Project Authors (https://github.com/googlefonts/ruge-boogie)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
