name: "Font picker"
excerpt: "The part of a user interface that specifically allows the user to choose a font."
related_lessons: "installing_and_managing_fonts"
related_lessons: "adding_fonts_to_google_docs"