name: "Pattaya"
designer: "Cadson Demak"
license: "OFL"
category: "SANS_SERIF"
date_added: "2016-06-20"
fonts {
  name: "Pattaya"
  style: "normal"
  weight: 400
  filename: "Pattaya-Regular.ttf"
  post_script_name: "Pattaya-Regular"
  full_name: "Pattaya Regular"
  copyright: "Copyright (c) 2015, Cadson Demak (info@cadsondemak.com), Copyright (c) 2010, Pablo Impallari (www.impallari.com|impallari@gmail.com), Copyright (c) 2010, 2011, Alexei Vanyashin (www.cyreal.org|a@cyreal.org), with Reserved Font Name Lobster."
}
subsets: "cyrillic"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "thai"
subsets: "vietnamese"
