id: "ms"
name: "Malay"
preferred_name: ""
autonym: "Malaysia"
population: 34869275
region: "ID"
region: "SG"
region: "MY"
region: "BN"
script: "Perso-Arabic"
script: "Latin"
exemplar_chars {
  base: "ء ‎ ا ب ة ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ ف ق ل م ن ه و ى ي چ ڠ ڤ ک ڽ ۏ ݢ"
  numerals: "٠ ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … \' ‘ ’ \" “ ” ( ) \\[ \\] § @ * / \\& # † ‡ ′ ″"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
}
