name: "Geometric"
excerpt: "A genre classification of typefaces—almost always sans serifs—so called because of their geometric construction."
related_lessons: "making_sense_of_typographic_classifications"
