name: "Faux, fake, pseudo, or synthesized"
excerpt: "The attempt by software to emulate an italic style, bold (or other) weight, or small caps in lieu of actual font files for those variants."
related_lessons: "introducing_weights_styles"
related_lessons: "exploring_typefaces_with_multiple_weights_or_grades"
related_lessons: "using_web_fonts"
