id: "pcd"
name: "Picard"
preferred_name: ""
autonym: "Picard"
population: 746330
region: "FR"
script: "Latin"
exemplar_chars {
  base: "A Â Å B C Ç D E Ê É È F G I Î Ï K L H J M N O Ô P Q R S T U Û V W Y Ŷ Z Æ Œ a â å b c ç d e ê é è f g i î ï k l h j m n o ô p q r s t u û v w y ŷ z æ œ"
  marks: "◌̀ ◌́ ◌̂ ◌̈ ◌̊ ◌̧"
}
