name: "Introducing color fonts"
authors: "Rod Sheeter"
reviewers: "Elliot Jay Stocks"
reviewers: "Cosimo Lupo"
topics: "color_fonts"
prev_lessons: "introducing_variable_fonts"
next_lessons: "how_typefaces_are_designed_and_fonts_are_made"
related_terms: "color_fonts"
related_terms: "variable_fonts"
excerpt: "Color fonts allow the font to use many colors and to have an opinion about what those colors should be."
