name: "Introducing color fonts"
authors: "Roderick Sheeter"
reviewers: "Elliot Jay Stocks"
reviewers: "Cosimo Lupo"
topics: "color_fonts"
# TODO do we have prev_lessons, next_lessons, or related_terms?
excerpt: "Color fonts allow the font to use many colors and to have an opinion about what those colors should be."
