id: "iu"
name: "Inuktitut"
preferred_name: ""
autonym: "ᐃᓄᒃᑎᑐᑦ"
population: 15831
region: "CA"
script: "UCAS"
script: "Latin"
exemplar_chars {
  base: "ᐃ ᐄ ᐅ ᐆ ᐊ ᐋ ᐦ ᐱ ᐲ ᐳ ᐴ ᐸ ᐹ ᑉ ᑎ ᑏ ᑐ ᑑ ᑕ ᑖ ᑦ ᑭ ᑮ ᑯ ᑰ ᑲ ᑳ ᒃ ᒋ ᒌ ᒍ ᒎ ᒐ ᒑ ᒡ ᒥ ᒦ ᒧ ᒨ ᒪ ᒫ ᒻ ᓂ ᓃ ᓄ ᓅ ᓇ ᓈ ᓐ ᓯ ᓰ ᓱ ᓲ ᓴ ᓵ ᔅ ᓕ ᓖ ᓗ ᓘ ᓚ ᓛ ᓪ ᔨ ᔩ ᔪ ᔫ ᔭ ᔮ ᔾ ᕕ ᕖ ᕗ ᕘ ᕙ ᕚ ᕝ ᕆ ᕇ ᕈ ᕉ ᕋ ᕌ ᕐ ᕿ ᖀ ᖁ ᖂ ᖃ ᖄ ᖅ ᖏ ᖐ ᖑ ᖒ ᖓ ᖔ ᖕ ᖠ ᖡ ᖢ ᖣ ᖤ ᖥ ᖦ"
}
