alt_ids: "axis_in_type_design"
name: "Stress"
excerpt: "The angle of the “pen” in a letterform, usually implied by the contrast of a stroke."
related_lessons: "making_sense_of_typographic_classifications"
