name: "Wide, or extended"
excerpt: "Typefaces with characters that typically take up a great deal of horizontal space, sitting at the opposite end of “condensed” or “compressed” type."
related_lessons: "making_sense_of_typographic_classifications"
related_lessons: "exploring_width_in_type"
related_lessons: "pairing_typefaces_within_a_family_superfamily"
