name: "Vertical spacing & line-height in design systems"
authors: "Sebastian Bailey"
reviewers: "Laurence Penney"
topics: "systems"
related_terms: "line_height_leading"
related_terms: "rhythm"
related_terms: "cap_height"
related_terms: "x_height"
related_terms: "baseline"
prev_lessons: "from_type_to_logotype"
next_lessons: "how_to_make_type_feel_authentic"
excerpt: "Discover how inconcistencies in the way that line height is calculated can lead to some headaches when maintaining a design system—and learn how to potentially overcome them."
