name: "Vertical spacing & line-height in design systems"
authors: "Sebastian Bailey"
reviewers: "Laurence Penney"
topics: "systems"
related_terms: "line_height_leading"
related_terms: "rhythm"
related_terms: "cap_height"
related_terms: "x_height"
related_terms: "baseline"
prev_lessons: "from_type_to_logotype"
next_lessons: "adding_an_authentic_natural_touch_to_type
excerpt: "INSERT_EXCERPT"
