name: "Writing system"
excerpt: "The combination of a script and a set of usage conventions."
related_lessons: "language_support_in_fonts"
related_lessons: "choosing_reliable_typefaces"
related_lessons: "an_overview_of_latin_type_anatomy"
related_lessons: "cjk_typesetting_rules"
related_content_urls: "https://www.youtube.com/embed/ro6XnC_U-I8"
