name: "Love Light"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-12-02"
fonts {
  name: "Love Light"
  style: "normal"
  weight: 400
  filename: "LoveLight-Regular.ttf"
  post_script_name: "LoveLight-Regular"
  full_name: "Love Light Regular"
  copyright: "Copyright 2003 The Love Light Project Authors (https://github.com/googlefonts/love-light)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
