name: "Icon & symbol"
excerpt: "An icon is a literal, visual representation of the thing it represents, whereas a symbol can be a more abstract representation of something."
related_lessons: "making_sense_of_typographic_classifications"
