id: "fi"
name: "Finnish"
preferred_name: ""
autonym: "Suomi"
population: 5736841
region: "EE"
region: "RU"
region: "SE"
region: "FI"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ä Ö Å a b c d e f g h i j k l m n o p q r s t u v w x y z ä ö å"
  auxiliary: "Æ Õ Ø Ü Š Ž æ õ ø ü š ž"
  marks: "◌̈ ◌̊ ◌̃ ◌̌"
  numerals: "  , % ‰ + − 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – , ; \\: ! ? . … ’ ” » ( ) \\[ \\] § @ * / \\\\ \\& #"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Å Ä Ö"
}
