name: "Monospace axis (MONO)"
excerpt: "An axis found in some variable fonts that adjusts the glyphs from a proportional width to a fixed width."
related_lessons: "INSERT_RELATED_LESSONS_AS_MANY_AS_NEEDED"
