name: "Designing Hangeul"
lessons: "an_introduction_to_hangeul"
lessons: "designing_for_learnability"
lessons: "making_the_details_matter"
lessons: "an_alphabet_for_reading_and_writing"
lessons: "lessons_from_hangeul"
excerpt: "In designing Hangeul, the Korean alphabet, King Sejong the Great of Korea (1397–1450) broke from thousands of years of tradition by purposefully creating an alphabet that was easy to learn, easy to read, and easy to write—and he defied the strict societal norms of his day by using his creation to help common citizens become literate."
