name: "Reflow"
excerpt: "The act of words, or parts of words, moving from one line of type to the line above or below because of a typographic change."
related_lessons: "breaking_the_rules"
related_lessons: "the_foundations_of_web_typography"
