name: "Making the Details Matter"
authors: "Darrell Penta"
reviewers: "Cassidy Curtis"
reviewers: "Minjoo Ham"
reviewers: "Min-Young Kim"
reviewers: "SeHee Lee"
topics: "hangeul"
prev_lessons: "designing_for_learnability"
next_lessons: "an_alphabet_for_reading_and_writing"
related_terms: "alternates"
related_terms: "legibility"
related_terms: "readability"
related_terms: "type_designer"
related_terms: "typographer"
related_terms: "uppercase_lowercase"
excerpt: "INSERT"
