name: "Rozha One"
designer: "Indian Type Foundry"
license: "OFL"
category: "SERIF"
date_added: "2014-08-13"
fonts {
  name: "Rozha One"
  style: "normal"
  weight: 400
  filename: "RozhaOne-Regular.ttf"
  post_script_name: "RozhaOne-Regular"
  full_name: "Rozha One Regular"
  copyright: "Copyright (c) 2014 Indian Type Foundry (info@indiantypefoundry.com)"
}
subsets: "devanagari"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
stroke: "SERIF"
classifications: "DISPLAY"
