name: "Grotesque & Neo-grotesque"
excerpt: "The first form of sans serif type (which appeared in the early 19th century [Grotesque]) and the subsequent evolution of this style (Neo-grotesque)."
related_lessons: "making_sense_of_typographic_classifications"
