name: "Using variable fonts on the web"
lessons: "variable_fonts_are_here"
lessons: "web_font_comparisons_variable_vs_static"
lessons: "optimizing_typographic_space_with_variable_fonts"
lessons: "interactive_animations_with_variable_fonts"
lessons: "factors_that_influence_the_efficiency_of_variable_web_fonts"
excerpt: "INSERT_EXCERPT"
