id: "maz"
name: "Central Mazahua"
preferred_name: ""
autonym: "Jñatrjo"
population: 437410
region: "MX"
script: "Latin"
exemplar_chars {
  base: "A B C D E G H I J L M N Ñ O P R S T U V X Z Ⱥ Ɇ Ʉ a b c d e g h i j l m n ñ o p r s t u v x z \' ⱥ ɇ ʉ"
  marks: "◌̃ ◌̱ ◌̵"
}
