name: "Type selection for AR/VR"
authors: "Niteesh Yadav"
reviewers: "Andrew Johnson"
reviewers: "Gerry Leonidas"
topics: "ar_vr"
prev_lessons: "designing_for_ar_vr"
next_lessons: "spatial_classification_of_typography_in_ar_vr"
related_terms: "font"
related_terms: "glyph"
related_terms: "legibility"
related_terms: "width"
related_terms: "weight"
excerpt: "EXCERPT_TBC"
