name: "Type selection for AR/VR"
authors: "Niteesh Yadav"
reviewers: "Andrew Johnson"
reviewers: "Gerry Leonidas"
topics: "ar_vr"
topics: "weight"
topics: "width"
prev_lessons: "designing_for_ar_vr"
next_lessons: "spatial_classification_of_typography_in_ar_vr"
related_terms: "font"
related_terms: "glyph"
related_terms: "legibility"
related_terms: "width"
related_terms: "weight"
excerpt: "Let's focus on considerations to keep in mind when selecting Latin typefaces and setting type in AR/VR applications. This information can also feed into the design of new typefaces that are better suited for AR/VR."
