name: "Type selection for AR/VR"
authors: "Niteesh Yadav"
reviewers: "Andrew Johnson"
reviewers: "Gerry Leonidas"
topics: "ar_vr"
prev_lessons: "designing_for_ar_vr"
next_lessons: "spatial_classification_of_typography_in_ar_vr"
related_terms: "TBC"
excerpt: "EXCERPT_TBC"
