id: "nyn"
name: "Nyankole"
preferred_name: ""
autonym: "Runyankore"
population: 2724939
region: "UG"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K M N O P R S T U V W Y Z a b c d e f g h i j k m n o p r s t u v w y z"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
}
