name: "Hinting"
excerpt: "The process of including programmatic “hints” in a font file to help text rendering software accurately recreate a typeface’s design at a low resolution."
related_lessons: "why_care_about_typography"
