name: "PT Root UI"
designer: "ParaType"
license: "OFL"
category: "SANS_SERIF"
date_added: "2018-12-28"
fonts {
  name: "PT Root UI"
  style: "normal"
  weight: 300
  filename: "PTRootUI-Light.ttf"
  post_script_name: "PTRootUI-Light"
  full_name: "PT Root UI Light"
  copyright: "Copyright © 2018 ParaType Inc. All rights reserved."
}
fonts {
  name: "PT Root UI"
  style: "normal"
  weight: 400
  filename: "PTRootUI-Regular.ttf"
  post_script_name: "PTRootUI-Regular"
  full_name: "PT Root UI"
  copyright: "Copyright © 2018 ParaType Inc. All rights reserved."
}
fonts {
  name: "PT Root UI"
  style: "normal"
  weight: 500
  filename: "PTRootUI-Medium.ttf"
  post_script_name: "PTRootUI-Medium"
  full_name: "PT Root UI Medium"
  copyright: "Copyright © 2018 ParaType Inc. All rights reserved."
}
fonts {
  name: "PT Root UI"
  style: "normal"
  weight: 700
  filename: "PTRootUI-Bold.ttf"
  post_script_name: "PTRootUI-Bold"
  full_name: "PT Root UI Bold"
  copyright: "Copyright © 2018 ParaType Inc. All rights reserved."
}
subsets: "menu"
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "latin"
subsets: "latin-ext"
