modules: "using_variable_fonts_on_the_web"
modules: "history_of_type"
modules: "type_in_china_japan_and_korea"
modules: "readability_and_accessibility"
modules: "designing_hangeul"
modules: "introducing_type"
modules: "choosing_type"
modules: "using_type"
modules: "using_type_in_ar_and_vr"
