id: "mg"
name: "Malagasy"
preferred_name: ""
autonym: "Malagasy"
population: 24260130
region: "MG"
script: "Latin"
exemplar_chars {
  base: "A B D E F G H I J K L M N O P R S T V Y Z À Â È É Ê Ë Ì Î Ï Ô a b d e f g h i j k l m n o p r s t v y z à â è é ê ë ì î ï ô"
  auxiliary: "c q u w x"
  marks: "◌̀ ◌́ ◌̂ ◌̈"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B D E F G H I J K L M N O P R S T V Y Z"
}
