name: "Gideon Roman"
designer: "Robert Leuschke"
license: "OFL"
category: "DISPLAY"
date_added: "2021-08-26"
fonts {
  name: "Gideon Roman"
  style: "normal"
  weight: 400
  filename: "GideonRoman-Regular.ttf"
  post_script_name: "GideonRoman-Regular"
  full_name: "Gideon Roman Regular"
  copyright: "Copyright 2009-2021 The Gideon Roman Project Authors (https://github.com/googlefonts/gideon)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
stroke: "SERIF"
classifications: "DISPLAY"
