id: "nds"
name: "Low German"
preferred_name: ""
autonym: "Niedersächsisch"
population: 11520008
region: "NL"
region: "DE"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ä Ë Ï Ö Ü a b c d e f g h i j k l m n o p q r s t u v w x y z ß ä ë ï ö ü"
  auxiliary: "ẞ"
  marks: "◌̈"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … \' ‘ ‚ \" “ „ « » ( ) \\[ \\] \\{ \\} § @ * / \\& #"
  index: "A B C D E F G H I J K L M N O P Q R S ẞ T U V W X Y Z"
}
