id: "pap"
name: "Papiamento"
preferred_name: ""
autonym: "Papiamentu"
population: 211640
region: "CW"
region: "BQ"
region: "AW"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z È Ò Ù Ü Ñ a b c d e f g h i j k l m n o p q r s t u v w x y z è ò ù ü ñ"
  marks: "◌̀ ◌̃ ◌̈"
}
