name: "Pairing typefaces using the font matrix"
authors: "Oliver Schöndorfer"
reviewers: "Indra Kupferschmid"
topics: "choosing_type"
topics: "pairing_type"
related_terms: "axis_in_type_design"
related_terms: "sans_serif"
related_terms: "serif"
related_terms: "contrast"
related_terms: "monolinear"
related_terms: "geometric"
related_terms: "humanist_old_style"
related_terms: "text_copy"
related_terms: "monospaced"
related_terms: "x_height"
related_terms: "width"
related_terms: "weight"
related_terms: "style"
prev_lessons: "pairing_typefaces_by_the_same_type_designer_or_type_foundry"
next_lessons: "exploring_x_height_the_em_square"
excerpt: "A detailed approach to combining typefaces based on their construction."
