name: "Designing for AR/VR"
authors: "Niteesh Yadav"
reviewers: "Andrew Johnson"
reviewers: "Gerry Leonidas"
topics: "ar_vr"
prev_lessons: "introducing_ar_vr"
next_lessons: "type_selection_for_ar_vr"
related_terms: "font"
related_terms: "glyph"
related_terms: "legibility"
related_terms: "weight"
related_terms: "grade"
excerpt: "As we develop and experience more sophisticated augmented reality and virtual reality (AR/VR) applications, the introduction of more features and functions increases the complexity of information in front of the reader. Our existing typographic rules are not sufficient to address these new variables."
