id: "arn"
name: "Mapuche"
preferred_name: ""
autonym: "Mapudungun"
population: 272802
region: "CL"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G I J K L M N O P Q R S T U W X Y Z Ü Ñ a b c d e f g i j k l m n o p q r s t u w x y z ü ñ"
  marks: "◌̃ ◌̈"
}
