name: "Type in China, Japan, and Korea"
lessons: "type_classification_in_cjk"
lessons: "cjk_typesetting_rules"
lessons: "japanese_typography_basics"
lessons: "the_evolution_of_hangeul_type_design"
excerpt: "CJK is the shorthand term for Chinese, Japanese, and Korean scripts. Although they share many common traits, all are all distinctively different. In these articles, we’ll look the background and characteristics of each CJK script, and the many considerations for setting type in these languages."
