name: "Type in China, Japan, and Korea"
lessons: "type_classification_in_cjk_chinese"
lessons: "type_classification_in_cjk_japanese"
lessons: "type_classification_in_cjk_korean"
lessons: "cjk_typesetting_rules"
lessons: "japanese_typography_basics"
lessons: "the_evolution_of_hangeul_type_design"
excerpt: "CJK is an acronym for Chinese, Japanese, and Korean scripts. These articles cover the characteristics and how to set type in each. Latin classifications (serif, humanist, geometric, etc.) do not apply directly: In Japan, “Mincho” is similar to serif, while in Korea, it’s “Myeongjo;” “Gothic” is used for sans serif in both Japanese and Korean. In China, serif-like designs are “Song Ti (宋体),” or sometimes “Mingchao Ti” or “Ming Ti (明朝体 or 明体),” to go together with the Japanese and Korean names. The sans are called “Hei Ti (黑体).” All CJK fonts also have a miscellaneous display classification: In Japan and Korea, it’s “design fonts” and in China, “decorative” fonts."