name: "Type in China, Japan, and Korea"
lessons: "type_classification_in_cjk"
lessons: "cjk_typesetting_rules"
lessons: "japanese_typography_basics"
lessons: "the_evolution_of_hangeul_type_design"
excerpt: "CJK is the shorthand term for Chinese, Japanese, and Korean scripts. In these articles, we’ll look the background and characteristics of each one, and the many considerations for setting type in these languages. In terms of classification, Latin groupings such as serif, sans serif, rounded, humanist, geometric, etc. do not apply directly. In Japan, “Mincho” is a grouping similar to serif; in Korea, it’s “Myeongjo;” “Gothic” is used for sans serif in both Japanese and Korean. In China, the situation is a little different, where the serif is called “Song Ti (宋体),” or sometimes “Mingchao Ti” or “Ming Ti (明朝体 or 明体),” to go together with the Japanese and Korean names. The sans is called “Hei Ti (黑体).” All CJK fonts also have display style as one of the classifications, but in Japan and Korea, this style is know as “design fonts” and in China as “decorative fonts.”