name: "Rampart One"
designer: "Fontworks Inc."
license: "OFL"
category: "DISPLAY"
date_added: "2021-06-08"
fonts {
  name: "Rampart One"
  style: "normal"
  weight: 400
  filename: "RampartOne-Regular.ttf"
  post_script_name: "RampartOne-Regular"
  full_name: "Rampart One Regular"
  copyright: "Copyright 2020 The Rampart Project Authors (https://github.com/fontworks-fonts/Rampart/)"
}
subsets: "cyrillic"
subsets: "japanese"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
stroke: "SANS_SERIF"
classifications: "DISPLAY"
