name: "Shaping"
excerpt: "The automatic process of combining plain text with a font, according to rules supplied by the shaping engine and the font itself."
related_lessons: "introducing_alternate_glyphs"
