id: "kw"
name: "Cornish"
preferred_name: ""
autonym: "Kernewek"
population: 1972
region: "GB"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Â Ê Î Ô À È Ì Ò a b c d e f g h i j k l m n o p q r s t u v w x y z â ê î ô à è ì ò"
  marks: "◌̀ ◌̂"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
}
