name: "Contrast"
excerpt: "The difference between the thick and thin parts of a stroke. A monolinear typeface has low stroke contrast, and is the opposite of a high contrast face."
related_lessons: "choosing_typefaces_that_have_optical_sizes"
