name: "Pairing typefaces within a family & superfamily"
authors: "Elliot Jay Stocks"
reviewers: "Doug Wilson"
reviewers: "Ellen Lupton"
reviewers: "Thomas Phinney"
topics: "choosing_type"
topics: "families"
topics: "pairing_type"
topics: "weight"
topics: "width"
prev_lessons: "pairing_typefaces"
next_lessons: "pairing_typefaces_by_the_same_type_designer_or_type_foundry"
related_terms: "serif"
related_terms: "sans_serif"
excerpt: "The advantage of staying within the family means there’s a shared consistency across every variation."
