id: "de"
name: "German"
preferred_name: ""
autonym: "Deutsch"
population: 134799567
region: "HU"
region: "US"
region: "GB"
region: "RO"
region: "KZ"
region: "DK"
region: "AT"
region: "LT"
region: "LI"
region: "BR"
region: "LU"
region: "FR"
region: "CZ"
region: "SK"
region: "NA"
region: "BE"
region: "CA"
region: "SI"
region: "NL"
region: "IT"
region: "CH"
region: "PY"
region: "FI"
region: "GR"
region: "BG"
region: "PL"
region: "DE"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ä Ö Ü a b c d e f g h i j k l m n o p q r s t u v w x y z ß ä ö ü"
  auxiliary: "À É à é"
  marks: "◌̈ ◌̀ ◌́"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … \' ‘ ‚ \" “ „ « » ( ) \\[ \\] \\{ \\} § @ * / \\& #"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
}
