name: "Guides Opacity axis (GDOP)"
excerpt: "An axis found in some variable fonts that can be used to adjust the visibility of handwriting guides built into the glyphs, from fully visible to fully invisible."
related_lessons: "introducing_variable_fonts"
related_lessons: "designing_with_variable_fonts_in_desktop_apps"
related_lessons: "styling_type_on_the_web_with_variable_fonts"
