name: "Manual kerning is rarely required"
authors: "Elliot Jay Stocks"
reviewers: "Bram Stein"
reviewers: "Bruce Willen"
reviewers: "Doug Wilson"
reviewers: "Frank Rausch"
reviewers: "Jamie Clarke"
reviewers: "John Boardley"
reviewers: "Thomas Phinney"
reviewers: "Trent Walton"
reviewers: "Yves Peters"
topics: "essentials"
prev_lessons: "track_carefully_or_not_at_all"
next_lessons: "avoiding_widows_orphans"
next_lessons: "implementing_open_type_features_on_the_web"
related_terms: "kerning_kerning_pairs"
related_terms: "tracking_letter_spacing"
excerpt: "The need for us designers to kern is actually quite rare, thanks to the diligent work of professional type designers."
