name: "Luxurious Roman"
designer: "Robert Leuschke"
license: "OFL"
category: "DISPLAY"
date_added: "2021-11-18"
fonts {
  name: "Luxurious Roman"
  style: "normal"
  weight: 400
  filename: "LuxuriousRoman-Regular.ttf"
  post_script_name: "LuxuriousRoman-Regular"
  full_name: "Luxurious Roman Regular"
  copyright: "Copyright 2015-2021 The Luxurious Roman Project Authors (https://github.com/googlefonts/luxurious-roman)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
stroke: "SERIF"
classifications: "DISPLAY"
