name: "Classification"
excerpt: "The act of dividing up different styles of type design, usually by genre or historical period, for more meaningful description and/or browsing."
related_lessons: "making_sense_of_typographic_classifications"
