name: "Zen Kurenaido"
designer: "Yoshimichi Ohira"
license: "OFL"
category: "SANS_SERIF"
date_added: "2021-10-22"
fonts {
  name: "Zen Kurenaido"
  style: "normal"
  weight: 400
  filename: "ZenKurenaido-Regular.ttf"
  post_script_name: "ZenKurenaido-Regular"
  full_name: "Zen Kurenaido Regular"
  copyright: "Copyright 2021 The Zen Kurenaido Project Authors (https://github.com/googlefonts/zen-kurenaido)"
}
subsets: "cyrillic"
subsets: "greek"
subsets: "japanese"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
primary_script: "Jpan"
