name: "Readability & accessibility"
lessons: "how_type_influences_readability"
lessons: "introducing_accessibility_in_typography"
excerpt: "Making our text readable should be our primary goal when setting and manipulating type. Readability—along with the closely related concepts of legibility and accessibility—is at the core of typography, and yet it’s rarely discussed thoroughly in typographic contexts. In these articles, we examine the qualities of type and typography that make reading easier."
