id: "ku"
name: "Kurdish"
preferred_name: ""
autonym: "Kurmancî"
population: 6773773
region: "GE"
region: "TR"
region: "AZ"
region: "SY"
region: "AM"
region: "DE"
region: "TM"
script: "Perso-Arabic"
script: "Cyrillic"
script: "Latin"
exemplar_chars {
  base: "А Б В Г Д Е Ә Ж З Й К Л М Н О Ӧ П Р С Т У Ф Х Һ Ч Ш Щ Ь Э Ԛ Ԝ а б в г д е ә ж з й к л м н о ӧ п р с т у ф х һ ч ш щ ь э ԛ ԝ \'"
  auxiliary: "Ḧ Ẍ ḧ ẍ \'"
  marks: "◌̆ ◌̈"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … \' ‘ ’ \" “ ” ( ) \\[ \\] § @ * / \\& # † ‡ ′ ″"
  index: "A B C Ç D E Ê F G H I Î J K L M N O P Q R S Ş T U Û V W X Y Z"
}
