name: "Parametric Figure Height axis (YTFI)"
excerpt: "A parametric axis for varying the height of figures."
related_lessons: "introducing_variable_fonts"
related_lessons: "introducing_parametric_axes"
