id: "srr"
name: "Serer"
preferred_name: ""
autonym: "Seereer"
population: 1731004
region: "SN"
script: "Latin"
exemplar_chars {
  base: "A B Ɓ C Ƈ D Ɗ E F G H I J K L M N Ñ Ŋ O P Ƥ Q R S T Ƭ U W X Y Ƴ a b ɓ c ƈ d ɗ e f g h i j k l m n ñ ŋ o p ƥ q r s t ƭ u w x y ƴ \'"
  marks: "◌̃"
}
