name: "Abugidas & alphasyllabary"
excerpt: "A writing system that combines consonants and vowels into a singular unit, with the consonant being the primary element, and the vowel secondary."
related_lessons: "an_introduction_to_syllabics_typography"
