name: "Ampersand (&)"
excerpt: "A character for “and,“ originally serving as a ligature for “et“ (the Latin word for “and”). Its name is derived from the phrase “and per se and”."
related_lessons: "choosing_reliable_typefaces"
