name: "Understanding numerals"
authors: "Elliot Jay Stocks"
reviewers: "Doug Wilson"
reviewers: "Jessica Hische"
reviewers: "Laurence Penney"
reviewers: "Mark Boulton"
reviewers: "Thomas Phinney"
reviewers: "Yves Peters"
topics: "essentials"
topics: "open_type"
prev_lessons: "introducing_alternate_glyphs"
next_lessons: "open_type_features_in_practice"
related_terms: "numerals_figures"
related_terms: "open_type"
related_terms: "monospaced"
excerpt: "Numbers, like letters, can be conveyed in different ways with typography to communicate meaning."
