id: "twq"
name: "Tasawaq"
preferred_name: ""
autonym: "Ingalkoyyu’"
population: 7970
region: "NE"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U W X Y Z Ã Õ Ŋ Š Ž Ɲ Ẽ a b c d e f g h i j k l m n o p q r s t u w x y z ã õ ŋ š ž ɲ ẽ ’"
  auxiliary: "V v"
  marks: "◌̃ ◌̌"
  numerals: "  \\- ‑ . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A B C D E F G H I J K L M N O P Q R S T U W X Y Z"
}
