id: "ht"
name: "Haitian Creole"
preferred_name: ""
autonym: "Kreyòl Ayisyen"
population: 8964918
region: "HT"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P R S T U V W Y Z È Ò a b c d e f g h i j k l m n o p r s t u v w y z è ò"
  auxiliary: "Q X À Á É Ó q x à á é ó"
  marks: "◌̀ ◌́"
}
