name: "Chonburi"
designer: "Cadson Demak"
license: "OFL"
category: "DISPLAY"
date_added: "2015-07-08"
fonts {
  name: "Chonburi"
  style: "normal"
  weight: 400
  filename: "Chonburi-Regular.ttf"
  post_script_name: "Chonburi-Regular"
  full_name: "Chonburi"
  copyright: "Copyright (c) 2015, Cadson Demak (info@cadsondemak.com)"
}
subsets: "menu"
subsets: "latin"
subsets: "latin-ext"
subsets: "thai"
subsets: "vietnamese"
stroke: "SERIF"
classifications: "DISPLAY"
