id: "te"
name: "Telugu"
preferred_name: ""
autonym: "తెలుగు"
population: 95478480
region: "IN"
script: "Telugu"
exemplar_chars {
  base: "అ భ ఇ ఉ ఋ ఌ ఎ ఐ ఒ ఔ ఆ ఈ ఊ ౠ ౡ ఏ ఓ క ఖ గ ఘ ఙ చ ఛ జ ఝ ఞ ట ఠ డ ఢ ణ త థ ద ధ న ప ఫ బ మ య ర ల వ ళ శ ష స హ ఱ"
  auxiliary: "\\u200C\\u200D ౦ ౧ ౨ ౩ ౪ ౫ ౬ ౭ ౮ ౯"
  marks: "◌ఁ ◌ం ◌ః ◌ా ◌ి ◌ీ ◌ు ◌ూ ◌ృ ◌ౄ ◌ె ◌ే ◌ొ ◌ో ◌ౌ ◌్ ◌ౖ ◌ౢ ◌ౣ"
  numerals: "౦ ౧ ౨ ౩ ౪ ౫ ౬ ౭ ౮ ౯ ౸ ౹ ౺ ౻ ౼ ౽ ౾"
  punctuation: "\\- ‑ , ; \\: ! ? . \' ‘ ’ \" “ ” ( ) \\[ \\] \\{ \\}"
  index: "అ ఆ ఇ ఈ ఉ ఊ ఋ ౠ ఎ ఏ ఐ ఒ ఓ ఔ క ఖ గ ఘ ఙ చ ఛ జ ఝ ఞ ట ఠ డ ఢ ణ త థ ద ధ న ప ఫ బ భ మ య ర ఱ ల వ శ ష స హ ళ"
}
