alt_ids: "legibility_readability"
name: "Legibility"
excerpt: "EXCERPT_TBC"
related_lessons: "why_care_about_typography"
related_lessons: "choosing_reliable_typefaces"
related_lessons: "exploring_typefaces_with_multiple_weights_or_grades"
