name: "Patrick Hand"
designer: "Patrick Wagesreiter"
license: "OFL"
category: "HANDWRITING"
date_added: "2011-07-06"
fonts {
  name: "Patrick Hand"
  style: "normal"
  weight: 400
  filename: "PatrickHand-Regular.ttf"
  post_script_name: "PatrickHand-Regular"
  full_name: "Patrick Hand"
  copyright: "Copyright (c) 2010-2012 Patrick Wagesreiter (mail@patrickwagesreiter.at)"
}
subsets: "menu"
subsets: "latin"
subsets: "latin-ext"
subsets: "vietnamese"
stroke: "SANS_SERIF"
classifications: "HANDWRITING"
