name: "Island Moments"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-11-18"
fonts {
  name: "Island Moments"
  style: "normal"
  weight: 400
  filename: "IslandMoments-Regular.ttf"
  post_script_name: "IslandMoments-Regular"
  full_name: "Island Moments Regular"
  copyright: "Copyright 2013-2021 The Island Moments Project Authors (https://github.com/googlefonts/island-moments)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
