id: "ar"
name: "Arabic"
preferred_name: ""
autonym: "العربية"
population: 350901500
region: "SA"
region: "LY"
region: "NE"
region: "TN"
region: "AE"
region: "SS"
region: "MA"
region: "YE"
region: "NG"
region: "OM"
region: "ER"
region: "CM"
region: "EH"
region: "BH"
region: "DJ"
region: "IQ"
region: "TJ"
region: "JO"
region: "LB"
region: "KE"
region: "CY"
region: "TR"
region: "KM"
region: "SD"
region: "EG"
region: "ML"
region: "SO"
region: "KW"
region: "DZ"
region: "MR"
region: "QA"
region: "SY"
region: "PS"
region: "IR"
region: "TD"
region: "IL"
script: "Perso-Arabic"
exemplar_chars {
  base: "ي و ه ن م ل ك ق ف غ ع ظ ط ض ص ش س ز ر ذ د خ ح ج ث ت ب ا ة"
  auxiliary: "ڛ ڢ ٯ ڧ ک ی ڤ ڥ پ چ گ ڨ ڭ ڠ"
  marks: "◌َ ◌ُ ◌ِ ◌ْ ◌ٰ"
  numerals: "٠ ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨ ٩"
  punctuation: "\\- ‐ ‑ – — ، ؛ \\: ! ؟ . … \' \" « » ( ) \\[ \\]"
  index: "ا ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ ف ق ك ل م ن ه و ي"
}
