id: "lij"
name: "Ligurian"
preferred_name: ""
autonym: "Ligure"
population: 536663
region: "IT"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z À Á Â Ä Æ È É Ê Ë Ì Í Î Ï Ò Ó Ô Ö Ù Ú a b c d e f g h i j k l m n o p q r s t u v w x y z à á â ä æ è é ê ë ì í î ï ò ó ô ö ù ú"
  marks: "◌̀ ◌́ ◌̂ ◌̈"
}
