name: "Style"
excerpt: "Regular, italic, oblique, and small caps are all examples of styles that can exist within a single typeface. See also: Stylistic sets."
related_lessons: "introducing_weights_styles"
related_lessons: "exploring_typefaces_with_multiple_weights_or_grades"
related_lessons: "introducing_alternate_glyphs"
related_lessons: "introducing_variable_fonts"
