name: "An introduction to Hangeul, the Korean alphabet"
authors: "Darrell Penta"
reviewers: "Cassidy Curtis"
reviewers: "Minjoo Ham"
reviewers: "Min-Young Kim"
reviewers: "SeHee Lee"
topics: "hangeul"
topics: "type_history"
next_lessons: "designing_for_learnability"
related_terms: "alphabet"
related_terms: "letters"
related_terms: "script_writing_system"
excerpt: "Part 1 in our in-depth look at the creation of Hangeul, the Korean alphabet."
