id: "pcm"
name: "Nigerian Pidgin"
preferred_name: ""
autonym: ""
population: 44945880
region: "NG"
script: "Latin"
exemplar_chars {
  base: "a á b {ch} d e é ẹ {ẹ\\u0301} f g {gb} h i í j k {kp} l m n o ó ọ {ọ\\u0301} p r s {sh} t u ú v w y z {zh}"
  auxiliary: "à c è {ẹ\\u0300} ì ò {ọ\\u0300} q ù x"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … \' ‘ ’ \" “ ” ( ) \\[ \\] § @ * / \\& # † ‡ ′ ″"
  index: "A B {CH} D E F G H I J K L M N O P R S T U V W Y Z"
}
