name: "Festive"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-04-23"
fonts {
  name: "Festive"
  style: "normal"
  weight: 400
  filename: "Festive-Regular.ttf"
  post_script_name: "Festive-Regular"
  full_name: "Festive Regular"
  copyright: "Copyright 2015 The Festive Pro Project Authors (https://github.com/googlefonts/festive)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
