name: "How type influences readability"
authors: "Hilary Palmen"
reviewers: "Bonnie Shaver-Troup"
reviewers: "Susanna Zaraysky"
topics: "accessibility"
topics: "readability"
related_terms: "INSERT_RELATED_TERMS"
prev_lessons: "INSERT_PREV"
next_lessons: "INSERT_NEXT
excerpt: "INSERT_EXCERPT"
