id: "gl"
name: "Galician"
preferred_name: ""
autonym: "Galego"
population: 3515529
region: "PT"
region: "ES"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Á É Í Ñ Ó Ú Ü a b c d e f g h i j k l m n o p q r s t u v w x y z á é í ñ ó ú ü"
  auxiliary: "ª à ă â å ä ã ā æ ɑ ç è ĕ ê ë ē ì ĭ î ī º ò ŏ ô ö õ ø ō œ ù ŭ û ū"
  marks: "◌́ ◌̃ ◌̈"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ¡ ? ¿ . … \' ‘ ’ \" “ ” « » ( ) \\[ \\] § @ * / \\\\ \\& # † ‡ ′ ″"
  index: "A B C D E F G H I J K L M N Ñ O P Q R S T U V W X Y Z"
}
