name: "Text, or copy"
excerpt: "The content itself—the thing we set in type. However, the word “text” can also imply the text size, which is then interchangeable with the term “body”."
related_lessons: "why_care_about_typography"
related_lessons: "choosing_typefaces_that_have_optical_sizes"
