name: "Parametric axis"
excerpt: "A high-precision tool, intended only for expert use, that enables finessing of strokes, counters and vertical alignments. Parametric axes can be used to address many typographic challenges."
related_lessons: "introducing_variable_fonts"
related_lessons: "introducing_parametric_axes"
