id: "kea"
name: "Kabuverdianu"
preferred_name: ""
autonym: "Kabuverdianu"
population: 530762
region: "CV"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z À Á Â Ã Ç È É Ê Í Ò Ó Ô Õ Ú Ü a b c d e f g h i j k l m n o p q r s t u v w x y z à á â ã ç è é ê í ò ó ô õ ú ü"
  auxiliary: "ª á à ă â å ä ã ā æ c ç é è ĕ ê ë ẽ ē í ì ĭ î ï ĩ ī {n\\u0308} º ó ò ŏ ô ö õ ø ō œ q {rr} ú ù ŭ û ü ũ ū w ÿ"
  marks: "◌̀ ◌́ ◌̂ ◌̃ ◌̈ ◌̧"
  numerals: "  \\- ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … \' ‘ ’ \" “ ” « » ( ) \\[ \\] § @ * / \\& # † ‡"
  index: "A B D E F G H I J K L M N O P R S T U V X Z"
}
