id: "lg"
name: "Ganda"
preferred_name: ""
autonym: "Luganda"
population: 5622890
region: "UG"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G I J K L M N O P R S T U V W Y Z Ŋ a b c d e f g i j k l m n o p r s t u v w y z ŋ"
  auxiliary: "H Q X h q x"
  index: "A B C D E F G I J K L M N Ŋ O P R S T U V W Y Z"
}
