name: "Cap height"
excerpt: "The height of a typeface’s uppercase letters, measured from the baseline to the top of the glyph. This is usually slightly lower than the ascender height."
related_lessons: "exploring_x_height_the_em_square"
