name: "Spacing"
excerpt: "In type design, the act of setting the horizontal space around each glyph."
related_lessons: "how_typefaces_are_designed_and_fonts_are_made"
related_lessons: "track_carefully_or_not_at_all"
