id: "zdj"
name: "Ngazidja Comorian"
preferred_name: ""
autonym: "شِكُمُرِ"
population: 313123
region: "KM"
script: "Perso-Arabic"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P R S T U V W Y Z a b c d e f g h i j k l m n o p r s t u v w y z"
  marks: "◌َ ◌ُ ◌ِ ◌ّ"
}
