id: "pon"
name: "Pohnpeian"
preferred_name: ""
autonym: "Pohnpei"
population: 23560
region: "FM"
script: "Latin"
exemplar_chars {
  base: "A D E H I K L M N O P R S T U W a d e h i k l m n o p r s t u w"
}
