id: "quc"
name: "Kʼicheʼ"
preferred_name: ""
autonym: "Qatzijob\'al"
population: 1200731
region: "GT"
script: "Latin"
exemplar_chars {
  base: "A B C E H I J K L M N O P Q R S T U W X Y Z a b c e h i j k l m n o p q r s t u w x y z \'"
}
