name: "Type designer"
excerpt: "Someone who designs typefaces. Not to be confused with a typographer (someone who designs with typefaces)."
related_lessons: "pairing_typefaces_by_the_same_type_designer_or_type_foundry"
