id: "ng"
name: "Ndonga"
preferred_name: ""
autonym: ""
population: 552314
region: "NA"
script: "Latin"
exemplar_chars {
  base: "A B D E F G H I J K L M N O P R S T U V W Y Z a b d e f g h i j k l m n o p r s t u v w y z"
}
