name: "Mea Culpa"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-12-02"
fonts {
  name: "Mea Culpa"
  style: "normal"
  weight: 400
  filename: "MeaCulpa-Regular.ttf"
  post_script_name: "MeaCulpa-Regular"
  full_name: "Mea Culpa Regular"
  copyright: "Copyright 2003-2021 The Mea Culpa Project Authors (https://github.com/googlefonts/mea-culpa)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
