id: "hy"
name: "Armenian"
preferred_name: "Eastern Armenian"
autonym: "Հայերեն"
population: 5317271
region: "LB"
region: "GE"
region: "RU"
region: "CY"
region: "TR"
region: "SY"
region: "AM"
region: "IR"
script: "Armenian"
exemplar_chars {
  base: "Ա Բ Գ Դ Ե Զ Է Ը Թ Ժ Ի Լ Խ Ծ Կ Հ Ձ Ղ Ճ Մ Յ Ն Շ Ո Չ Պ Ջ Ռ Ս Վ Տ Ր Ց Ւ Փ Ք Օ Ֆ ա բ գ դ ե զ է ը թ ժ ի լ խ ծ կ հ ձ ղ ճ մ յ ն շ ո չ պ ջ ռ ս վ տ ր ց ւ փ ք օ ֆ և"
  auxiliary: "և"
  numerals: "  \\- ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "՛ ՜ ՝ ՞ ։"
  index: "Ա Բ Գ Դ Ե Զ Է Ը Թ Ժ Ի Լ Խ Ծ Կ Հ Ձ Ղ Ճ Մ Յ Ն Շ Ո Չ Պ Ջ Ռ Ս Վ Տ Ր Ց Ւ Փ Ք Օ Ֆ"
}
