name: "Parametric Thin Stroke axis (YOPQ)"
excerpt: "A parametric axis for varying thin stroke weights, such as bars and hairlines."
related_lessons: "introducing_variable_fonts"
related_lessons: "introducing_parametric_axes"
