name: "Homoglyph"
excerpt: "A glyph with a design that can appear indistinguishable from—or least very similar to—another glyph with a separate meaning."
related_lessons: "choosing_reliable_typefaces"
