name: "FOUT"
excerpt: "An acronym for “flash of unstyled text”—a phenomenon experienced when a web page loads with the type set using system fonts before switching to the intended typeface(s)."
related_lessons: "using_web_fonts"
