name: "Fitting the line"
authors: "Micah Rich"
authors: "Thomas Jockin"
topics: "width"
next_lessons: "justification_hyphenation"
related_terms: "width"
excerpt: "Type designers have long created complex typeface families of various weights and widths that allow a word of almost any length to fit on the same text line (i.e.; to “fit the line”). But only recently have we also had the benefit of variable fonts to make the task easier."