id: "ro"
name: "Romanian"
preferred_name: ""
autonym: "Молдовеняскэ"
population: 22085633
region: "HU"
region: "MD"
region: "RO"
region: "UA"
region: "RS"
region: "IL"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Â Î Ă Ș Ț a b c d e f g h i j k l m n o p q r s t u v w x y z â î ă ș ț"
  auxiliary: "Ş Ţ ş ţ"
  marks: "◌̂ ◌̆ ◌̦ ◌̧"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … \' ‘ \" “ ” „ « » ( ) \\[ \\] @ * /"
  index: "A Ă Â B C D E F G H I Î J K L M N O P Q R S Ș T Ț U V W X Y Z"
}
