name: "Script (writing system)"
excerpt: "A collective way of describing a writing system used by multiple languages, not to be confused with the “script” classification of typefaces."
related_lessons: "language_support_in_fonts"
related_lessons: "choosing_reliable_typefaces"
related_lessons: "an_overview_of_latin_type_anatomy"
