name: "Type classification in CJK"
authors: "Min-Young Kim"
authors: "Lisa Huang"
reviewers: "Minjoo Ham"
reviewers: "Shoko Mugikura"
topics: "cjk"
related_terms: "INSERT"
next_lessons: "INSERT"
excerpt: "INSERT_EXCERPT"
