name: "Softness axis (SOFT)"
excerpt: "An axis found in some variable fonts. At the end of this axis, letterforms become more soft and rounded."
related_lessons: "introducing_variable_fonts"
related_lessons: "designing_with_variable_fonts_in_desktop_apps"
related_lessons: "styling_type_on_the_web_with_variable_fonts"
