id: "ne"
name: "Nepali"
preferred_name: ""
autonym: ""
population: 20903374
region: "NP"
region: "BT"
region: "IN"
script: "Devanagari"
exemplar_chars {
  base: "\\u093C \\u0901 \\u0902 ः ॐ अ आ इ ई उ ऊ ऋ ऌ ऍ ए ऐ ऑ ओ औ क ख ग घ ङ च छ ज झ ञ ट ठ ड ढ ण त थ द ध न प फ ब भ म य र ल ळ व श ष स ह ऽ ा ि ी \\u0941 \\u0942 \\u0943 \\u0944 \\u0945 \\u0947 \\u0948 ॉ ो ौ \\u094D"
  auxiliary: "\\u200C\\u200D"
  numerals: "\\- ‑ , . % ‰ + 0० 1१ 2२ 3३ 4४ 5५ 6६ 7७ 8८ 9९"
  punctuation: "\\- ‑ — , ; ! ? । \' ‘ ’ \" “ ” ( ) \\[ \\] \\{ \\}"
  index: "अ आ इ ई उ ऊ ऋ ए ऐ ओ औ क ख ग घ ङ च छ ज झ ञ ट ठ ड ढ ण त थ द ध न प फ ब भ म य र ल व श ष स ह"
}
