name: "OpenType"
excerpt: "A font technology and associated font format, developed by Microsoft and Adobe, which allows the end user to access additional features in a font."
related_lessons: "introducing_alternate_glyphs"
related_lessons: "open_type_features_in_practice"
related_lessons: "implementing_open_type_features_on_the_web"
