name: "Using type in AR & VR"
lessons: introducing_ar_vr"
lessons: "designing_for_ar_vr"
lessons: "type_selection_for_ar_vr"
lessons: "spatial_classification_of_typography_in_ar_vr"
lessons: "technical_challenges_for_typography_in_ar_vr"
excerpt: "EXCERPT_TBC"
