name: "Using type in AR & VR"
lessons: "introducing_ar_vr"
lessons: "designing_for_ar_vr"
lessons: "type_selection_for_ar_vr"
lessons: "spatial_classification_of_typography_in_ar_vr"
lessons: "technical_challenges_for_typography_in_ar_vr"
excerpt: "Augmented reality and virtual reality offer new and exciting experiences, and—for the typographer—a whole new set of challenges. This section explores the current limitations of setting type in AR/VR environments, the differences from using type elsewhere, and the best typesetting practices for this young and powerful medium."
