name: "Patrick Hand SC"
designer: "Patrick Wagesreiter"
license: "OFL"
category: "HANDWRITING"
date_added: "2013-02-27"
fonts {
  name: "Patrick Hand SC"
  style: "normal"
  weight: 400
  filename: "PatrickHandSC-Regular.ttf"
  post_script_name: "PatrickHandSC-Regular"
  full_name: "Patrick Hand SC Regular"
  copyright: "Copyright 2012 The Patrick Hand Authors (mail@patrickwagesreiter.at)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
stroke: "SANS_SERIF"
classifications: "HANDWRITING"
