name: "Color fonts"
excerpt: "A font that can use multiple colors in a single glyph, rather than a flat single color used by non-color (monochromatic) fonts."
related_lessons: "introducing_color_fonts"
