name: "Color fonts"
excerpt: "A font that can use multiple colors and specifies what they should be, as opposed to just specifying where 'ink' in the foreground color should go but not what that color should be."
related_lessons: "introducing_color_fonts"
related_content_urls: "https://www.youtube.com/watch?v=uaihftkZc68"
