name: "Algonquian Syllabics"
authors: "Kevin King"
reviewers: "Elliot Jay Stocks"
reviewers: "Peter Biľak"
topics: "language_support"
topics: "syllabics"
prev_lessons: "an_introduction_to_syllabics_typography"
next_lessons: "inuktut_syllabics"
related_terms: "contrast"
related_terms: "alternates"
related_terms: "readability"
related_terms: "typesetting"
excerpt: "This article presents and describes the local orthographic requirements and typographic preferences for the nêhiyawêwin (Cree), Anishinaabemowin (Ojibwe), and iyuw iyimuun (Naskapi) Syllabics-using communities."
