name: "Bakbak One"
designer: "Saumya Kishore, Sanchit Sawaria"
license: "OFL"
category: "DISPLAY"
date_added: "2021-09-10"
fonts {
  name: "Bakbak One"
  style: "normal"
  weight: 400
  filename: "BakbakOne-Regular.ttf"
  post_script_name: "BakbakOne-Regular"
  full_name: "Bakbak One Regular"
  copyright: "Copyright 2021 The Bakbak One Project Authors (https://github.com/googlefonts/bakbak)"
}
subsets: "devanagari"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
stroke: "SANS_SERIF"
classifications: "DISPLAY"
