name: "Rhythm"
excerpt: "The perceived movement that flows through text, whether that’s through the letterforms of one word, or through a whole block of text."
related_lessons: "choosing_a_suitable_line_height"
