name: "From metal to digital"
authors: "John Boardley"
reviewers: "Gerry Leonidas"
reviewers: "Ben Weiner"
topics: "type_history"
related_terms: "INSERT_RELATED_TERMS"
prev_lessons: "INSERT_PREV"
next_lessons: "INSERT_NEXT
excerpt: "INSERT_EXCERPT"
