name: "Designing for Learnability"
authors: "Darrell Penta"
reviewers: "Cassidy Curtis"
reviewers: "Minjoo Ham"
reviewers: "Min-Young Kim"
reviewers: "SeHee Lee"
topics: "hangeul"
prev_lessons: "an_introduction_to_hangeul"
next_lessons: "making_the_details_matter"
related_terms: "alphabet"
related_terms: "letters"
related_terms: "script_writing_system"
excerpt: "INSERT"
