name: "Designing for Learnability"
authors: "Darrell Penta"
reviewers: "Cassidy Curtis"
reviewers: "Minjoo Ham"
reviewers: "Min-Young Kim"
reviewers: "SeHee Lee"
topics: "hangeul"
prev_lessons: "introduction_to_hangeul"
next_lessons: "making_the_details_matter"
related_terms: "geometric"
related_terms: "monospaced"
related_terms: "diacritic_accent_marks"
related_terms: "uppercase_lowercase"
related_terms: "letters"
excerpt: "INSERT"
