name: "Subsetting"
excerpt: "The practice of creating a “subset” of a font—a file that contains a custom (and usually limited) collection of glyphs."
related_lessons: "using_web_fonts_from_a_font_delivery_service"
