id: "bho"
name: "Bhojpuri"
preferred_name: ""
autonym: "भोजपुरी"
population: 32934797
region: "MU"
region: "NP"
region: "IN"
script: "Devanagari"
exemplar_chars {
  base: "𑂃 𑂄 𑂅 𑂆 𑂇 𑂈 𑂉 𑂊 𑂋 𑂌 𑂍 𑂎 𑂏 𑂐 𑂑 𑂒 𑂓 𑂔 𑂕 𑂖 𑂗 𑂘 𑂙 𑂚 𑂛 𑂜 𑂝 𑂞 𑂟 𑂠 𑂡 𑂢 𑂣 𑂤 𑂥 𑂦 𑂧 𑂨 𑂩 𑂪 𑂫 𑂬 𑂭 𑂮 𑂯"
  auxiliary: "ॐ"
  marks: "◌𑂀 ◌𑂂 ◌𑂰 ◌𑂲 ◌𑂳 ◌𑂴 ◌𑂵 ◌𑂶 ◌𑂸 ◌𑂺"
  numerals: "० १ २ ३ ४ ५ ६ ७ ८ ९ 0 1 2 3 4 5 6 7 8 9"
  punctuation: "। ॥ ॰"
}
