id: "en"
name: "English"
preferred_name: ""
autonym: "English"
population: 1636848718
region: "SL"
region: "TC"
region: "AE"
region: "NU"
region: "AT"
region: "SS"
region: "MA"
region: "SH"
region: "ZA"
region: "PW"
region: "CN"
region: "IE"
region: "TK"
region: "DM"
region: "BZ"
region: "CL"
region: "ER"
region: "ZW"
region: "RW"
region: "CM"
region: "BR"
region: "IQ"
region: "BT"
region: "IN"
region: "KN"
region: "SZ"
region: "WS"
region: "BI"
region: "DO"
region: "BS"
region: "AU"
region: "CX"
region: "PA"
region: "TA"
region: "JE"
region: "HU"
region: "US"
region: "LK"
region: "NR"
region: "KZ"
region: "AC"
region: "AG"
region: "MW"
region: "HR"
region: "CK"
region: "PT"
region: "BM"
region: "FK"
region: "GY"
region: "KE"
region: "TR"
region: "VG"
region: "SI"
region: "NL"
region: "LC"
region: "FI"
region: "NZ"
region: "LS"
region: "AI"
region: "DZ"
region: "PL"
region: "AW"
region: "TV"
region: "EE"
region: "NF"
region: "PM"
region: "GG"
region: "SG"
region: "GB"
region: "MP"
region: "MX"
region: "DK"
region: "PK"
region: "GI"
region: "MO"
region: "VU"
region: "GM"
region: "HN"
region: "JM"
region: "MS"
region: "TH"
region: "TT"
region: "CY"
region: "GH"
region: "CH"
region: "VC"
region: "BB"
region: "UG"
region: "NP"
region: "MY"
region: "GR"
region: "GD"
region: "CC"
region: "KI"
region: "IL"
region: "NG"
region: "PN"
region: "BA"
region: "ET"
region: "TZ"
region: "AS"
region: "TO"
region: "RO"
region: "SC"
region: "PG"
region: "AR"
region: "VI"
region: "IM"
region: "HK"
region: "LT"
region: "YE"
region: "BN"
region: "MH"
region: "MT"
region: "ZM"
region: "SB"
region: "FR"
region: "LU"
region: "PH"
region: "ES"
region: "JO"
region: "CZ"
region: "MU"
region: "KY"
region: "DG"
region: "LB"
region: "NA"
region: "SK"
region: "UM"
region: "BE"
region: "CA"
region: "SD"
region: "LV"
region: "LR"
region: "IT"
region: "BW"
region: "EG"
region: "BD"
region: "FJ"
region: "FM"
region: "IO"
region: "PR"
region: "SX"
region: "BG"
region: "GU"
region: "SE"
region: "MG"
region: "DE"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Æ Œ a b c d e f g h i j k l m n o p q r s t u v w x y z æ œ"
  auxiliary: "Á Ç È É Ê Ë Ï Ñ Ô Ö á ç è é ê ë ï ñ ô ö"
  marks: "◌̀ ◌́ ◌̂ ◌̃ ◌̈ ◌̧"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … \' ‘ ’ \" “ ” ( ) \\[ \\] § @ * / \\& # † ‡ ′ ″"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"
}
