name: "Licorice"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-11-18"
fonts {
  name: "Licorice"
  style: "normal"
  weight: 400
  filename: "Licorice-Regular.ttf"
  post_script_name: "Licorice-Regular"
  full_name: "Licorice Regular"
  copyright: "Copyright 2004 The Licorice Project Authors (https://github.com/googlefonts/licorice)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
