name: "Comforter"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-09-29"
fonts {
  name: "Comforter"
  style: "normal"
  weight: 400
  filename: "Comforter-Regular.ttf"
  post_script_name: "Comforter-Regular"
  full_name: "Comforter Regular"
  copyright: "Copyright 2015 The Comforter Project Authors (https://github.com/googlefonts/comforter)"
}
subsets: "cyrillic"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
