name: "Slab serif, Egyptian, or Clarendon"
excerpt: "A group of typefaces close to sans serifs in their construction—including their generally low contrast—but possessing serifs that match the overall stroke."
related_lessons: "making_sense_of_typographic_classifications"
related_lessons: "pairing_typefaces_within_a_family_superfamily"
