name: "Humanist, or Old Style"
excerpt: "A historical classification for typefaces that draws inspiration from Roman lettering and calligraphy to include forms that reference the stroke of a pen."
related_lessons: "making_sense_of_typographic_classifications"
