name: "Letters"
excerpt: "The set of graphical symbols used to represent speech sounds in an alphabetic writing system."
related_lessons: "an_alphabet_for_reading_and_writing"
related_lessons: "designing_for_learnability"
