name: "Display"
excerpt: "When referring to optical sizing, “display” is a counterpart to “body,” representing stylistic differences that make the variant more suitable to being set at large sizes."
related_lessons: "choosing_typefaces_that_have_optical_sizes"
