name: "Marck Script"
designer: "Denis Masharov"
license: "OFL"
category: "HANDWRITING"
date_added: "2011-10-12"
fonts {
  name: "Marck Script"
  style: "normal"
  weight: 400
  filename: "MarckScript-Regular.ttf"
  post_script_name: "MarckScript-Regular"
  full_name: "Marck Script"
  copyright: "Copyright (c) 2011, Denis Masharov <denis.masharov@gmail.com>, Marck Fogel, with Reserved Font Names \"Marck Script\"."
}
subsets: "menu"
subsets: "cyrillic"
subsets: "latin"
subsets: "latin-ext"
classifications: "DISPLAY"
classifications: "HANDWRITING"
