name: "How I discovered Afrikan writing systems"
authors: "INSERT_AUTHOR"
reviewers: "INSERT_REVIEWER"
topics: "INSERT_TOPIC"
related_terms: "INSERT_RELATED_TERMS"
prev_lessons: "INSERT_PREV"
next_lessons: "INSERT_NEXT
excerpt: "INSERT_EXCERPT"
