id: "umb"
name: "Umbundu"
preferred_name: ""
autonym: "Úmbúndú"
population: 9431467
region: "AO"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P R S T U V W Y Ã Ẽ Õ Ú Ũ a b c d e f g h i j k l m n o p r s t u v w y ã ẽ õ ú ũ"
  marks: "◌́ ◌̃"
}
