name: "En"
excerpt: "A unit of measurement based on half the width of the capital M in a particular typeface. The en dash takes up approximately half the width of an em."
related_lessons: "exploring_x_height_the_em_square"
related_lessons: "exploring_punctuation"
