name: "Kolker Brush"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-11-26"
fonts {
  name: "Kolker Brush"
  style: "normal"
  weight: 400
  filename: "KolkerBrush-Regular.ttf"
  post_script_name: "KolkerBrush-Regular"
  full_name: "Kolker Brush Regular"
  copyright: "Copyright 2004 The Kolker Brush Project Authors (https://github.com/googlefonts/kolker-brush)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
