name: "Bad Script"
designer: "Gaslight"
license: "OFL"
category: "HANDWRITING"
date_added: "2011-12-13"
fonts {
  name: "Bad Script"
  style: "normal"
  weight: 400
  filename: "BadScript-Regular.ttf"
  post_script_name: "BadScript-Regular"
  full_name: "Bad Script Regular"
  copyright: "Copyright 2011 The Bad Script Project Authors (gaslighttypefoundry@gmail.com)"
}
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
