name: "Allison"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-07-02"
fonts {
  name: "Allison"
  style: "normal"
  weight: 400
  filename: "Allison-Regular.ttf"
  post_script_name: "Allison-Regular"
  full_name: "Allison Regular"
  copyright: "Copyright 2020 The Allison Project Authors (https://github.com/googlefonts/allison)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
