name: "Shalimar"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-10-15"
fonts {
  name: "Shalimar"
  style: "normal"
  weight: 400
  filename: "Shalimar-Regular.ttf"
  post_script_name: "Shalimar-Regular"
  full_name: "Shalimar Regular"
  copyright: "Copyright 2004-2021 The Shalimar Project Authors (https://github.com/googlefonts/shalimar)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
