id: "bci"
name: "Baoulé"
preferred_name: ""
autonym: ""
population: 3022921
region: "CI"
script: "Latin"
exemplar_chars {
  base: "A B C D E Ɛ F G I J K L M N O Ɔ P R S T U V W Y Z a b c d e ɛ f g i j k l m n o ɔ p r s t u v w y z"
}
