name: "Alphabet"
excerpt: "A writing system in which the elemental speech sounds of a language are represented by a set of graphical units, called letters."
related_lessons: "an_alphabet_for_reading_and_writing"
