name: "Estonia"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-08-26"
fonts {
  name: "Estonia"
  style: "normal"
  weight: 400
  filename: "Estonia-Regular.ttf"
  post_script_name: "Estonia-Regular"
  full_name: "Estonia Regular"
  copyright: "Copyright 2010-2021 The Estonia Project Authors (https://github.com/googlefonts/estonia)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
