name: "Typographer"
excerpt: "Someone who designs with type and practices typography. Not to be confused with a type designer (someone who designs typefaces)."
related_lessons: "why_care_about_typography"
related_lessons: "choosing_reliable_typefaces"
