name: "Suez One"
designer: "Michal Sahar"
license: "OFL"
category: "SERIF"
date_added: "2016-06-20"
fonts {
  name: "Suez One"
  style: "normal"
  weight: 400
  filename: "SuezOne-Regular.ttf"
  post_script_name: "SuezOne-Regular"
  full_name: "Suez One Regular"
  copyright: "Copyright 2016 Michal Sahar. All rights reserved."
}
subsets: "hebrew"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
stroke: "SERIF"
classifications: "DISPLAY"
