name: "Exploring punctuation"
authors: "Elliot Jay Stocks"
reviewers: "Bram Stein"
reviewers: "Doug Wilson"
reviewers: "Ellen Lupton"
reviewers: "Erik Spiekermann"
reviewers: "Frank Rausch"
reviewers: "Gerry Leonidas"
reviewers: "Jamie Clarke"
reviewers: "Jessica Hische"
reviewers: "Richard Rutter"
reviewers: "Thomas Phinney"
reviewers: "Trent Walton"
reviewers: "Yves Peters"
topics: "essentials"
topics: "language_support"
prev_lessons: "making_sense_of_typographic_classifications"
next_lessons: "introducing_weights_styles"
related_terms: "glyph"
related_terms: "spaces"
related_terms: "dashes"
excerpt: "Punctuation matters: It conveys pause and effect to the reader, and designers should ensure the correct glyphs are rendered as—and when—required."
