name: "Stick"
designer: "Fontworks Inc."
license: "OFL"
category: "SANS_SERIF"
date_added: "2020-12-15"
fonts {
  name: "Stick"
  style: "normal"
  weight: 400
  filename: "Stick-Regular.ttf"
  post_script_name: "Stick-Regular"
  full_name: "Stick Regular"
  copyright: "Copyright 2020 The Stick Project Authors (https://github.com/fontworks-fonts/Stick/)"
}
subsets: "cyrillic"
subsets: "japanese"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
stroke: "SANS_SERIF"
classifications: "DISPLAY"
