name: "Ruslan Display"
designer: "Oleg Snarsky, Denis Masharov, Vladimir Rabdu"
license: "OFL"
category: "DISPLAY"
date_added: "2011-05-18"
fonts {
  name: "Ruslan Display"
  style: "normal"
  weight: 400
  filename: "RuslanDisplay.ttf"
  post_script_name: "RuslanDisplay"
  full_name: "Ruslan Display"
  copyright: "Copyright (c) 2010, 2011, Denis Masharov <denis.masharov@gmail.com>, Vladimir Rabdu. This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL"
}
subsets: "menu"
subsets: "cyrillic"
subsets: "latin"
subsets: "latin-ext"
stroke: "SANS_SERIF"
classifications: "DISPLAY"
