name: "Language support in fonts"
authors: "Elliot Jay Stocks"
reviewers: "Doug Wilson"
reviewers: "Frank Rausch"
reviewers: "Gerry Leonidas"
reviewers: "Laurence Penney"
reviewers: "Richard Rutter"
reviewers: "Thomas Phinney"
topics: "essentials"
topics: "families"
prev_lessons: "choosing_reliable_typefaces"
next_lessons: "choosing_a_suitable_line_height"
related_terms: "script_writing_system"
related_terms: "glyph"
related_terms: "line_height_leading"
related_terms: "unicode"
excerpt: "Each language has its own nuances, and when we use different scripts, there are further typographic considerations to keep in mind."
