id: "gd"
name: "Scottish Gaelic"
preferred_name: ""
autonym: "Gàidhlig"
population: 65103
region: "GB"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z À È É Ì Ò Ó Ù a b c d e f g h i j k l m n o p q r s t u v w x y z à è é ì ò ó ù"
  auxiliary: "á ă â å ä ã ā æ ċ ç ḋ é ĕ ê ë ē ḟ ġ í ĭ î ï ī ı j k ł ṁ ñ ó ŏ ô ö ø ō œ ṗ q ṡ ş ș ṫ ú ŭ û ü ū v w x y ÿ z"
  marks: "◌̀ ◌́"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ¡ ? . … · \' ‘ ’ \" “ ” ( ) \\[ \\] \\{ \\} § ¶ @ * / \\& ⁊ # % † ‡ ‧ ° © ® ™"
  index: "A B C D E F G H I L M N O P R S T U"
}
