name: "UD PMincho"
designer: "Type Bank Co., Morisawa Inc."
license: "OFL"
category: "SERIF"
date_added: "2022-03-15"
fonts {
  name: "UD PMincho"
  style: "normal"
  weight: 400
  filename: "BIZUDPMincho-Regular.ttf"
  post_script_name: "BIZUDPMincho-Regular"
  full_name: "BIZ UDPMincho "
  copyright: "Copyright 2022 The BIZ UDMincho Project Authors (https://github.com/googlefonts/morisawa-biz-ud-mincho)"
}
subsets: "cyrillic"
subsets: "greek-ext"
subsets: "japanese"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
