id: "skr"
name: "Saraiki"
preferred_name: ""
autonym: "سرائیکی"
population: 21248591
region: "PK"
script: "Perso-Arabic"
exemplar_chars {
  base: "ا ب ٻ پ ت ٹ ث ج ڄ چ ح خ د ڊ ڈ ݙ ذ ر ڑ ز ژ س ش ص ض ط ظ ع غ ف ق ک گ ڳ ل م ن ݨ و ہ ھ ء ی ے ي"
  marks: "◌ٔ"
}
