name: "Prosto One"
designer: "Jovanny Lemonad, Pavel Emelyanov"
license: "OFL"
category: "DISPLAY"
date_added: "2012-02-29"
fonts {
  name: "Prosto One"
  style: "normal"
  weight: 400
  filename: "ProstoOne-Regular.ttf"
  post_script_name: "ProstoOne-Regular"
  full_name: "Prosto One"
  copyright: "Copyright (c) 2012, Jovanny Lemonad (http://www.jovanny.ru), Copyright (c) 2012, Pavel Emelyanov (zakachka2006@mail.ru), with Reserved Font Name \"Prosto\" and \"Prosto One\"."
}
subsets: "menu"
subsets: "cyrillic"
subsets: "latin"
subsets: "latin-ext"
stroke: "SANS_SERIF"
classifications: "DISPLAY"
