id: "bg"
name: "Bulgarian"
preferred_name: ""
autonym: "Български"
population: 7878314
region: "GR"
region: "MD"
region: "TR"
region: "RO"
region: "BG"
region: "UA"
script: "Cyrillic"
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ь Ю Я Ѐ Ѝ а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ь ю я ѐ ѝ"
  auxiliary: "А̀ О̀ У̀ Ъ̀ Ю̀ Я̀ а̀ о̀ у̀ ъ̀ ю̀ я̀"
  marks: "◌̀ ◌̆"
  numerals: "  \\- ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … \' ‘ ‚ \" “ „ ( ) \\[ \\] § @ * / ″ №"
  index: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ю Я"
}
