name: "Ephesis"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-08-06"
fonts {
  name: "Ephesis"
  style: "normal"
  weight: 400
  filename: "Ephesis-Regular.ttf"
  post_script_name: "Ephesis-Regular"
  full_name: "Ephesis Regular"
  copyright: "Copyright 2004-2021 The Ephesis Project Authors (https://github.com/googlefonts/ephesis)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
