name: "Orelega One"
designer: "Haruki Wakamatsu"
license: "OFL"
category: "DISPLAY"
date_added: "2021-03-12"
fonts {
  name: "Orelega One"
  style: "normal"
  weight: 400
  filename: "OrelegaOne-Regular.ttf"
  post_script_name: "OrelegaOne-Regular"
  full_name: "Orelega One Regular"
  copyright: "Copyright 2021 The Orelega One Project Authors (https://github.com/JapanYoshi/Orelega)"
}
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
stroke: "SERIF"
classifications: "DISPLAY"
