name: "The invention of type"
authors: "John Boardley"
reviewers: "Gerry Leonidas"
reviewers: "Ben Weiner"
topics: "type history"
prev_lessons: ""
next_lessons: "history_of_type_2"
related_terms: "blackletter"
related_terms: "calligraphy"
related_terms: "latin"
related_terms: "letterform"
related_terms: "type_design"
excerpt: "INSERT_EXCERPT"
