name: "Family, type family, or font family"
excerpt: "A collection of variations on a typeface design. Each instance (usually a weight or style) forms part of the family."
related_lessons: "exploring_typefaces_with_multiple_weights_or_grades"
related_lessons: "exploring_width_in_type"
related_lessons: "introducing_variable_fonts"
related_lessons: "pairing_typefaces_within_a_family_superfamily"
