id: "az_Arab"
name: "Azerbaijani (Arabic)"
preferred_name: ""
autonym: ""
population: 21614414
region: "IQ"
region: "TR"
region: "IR"
script: "Perso-Arabic"
script: "Cyrillic"
script: "Latin"
exemplar_chars {
}
