id: "men"
name: "Mende"
preferred_name: ""
autonym: "Mɛnde yia"
population: 1813082
region: "SL"
region: "LR"
script: "Latin"
exemplar_chars {
  base: "A B D E Ɛ F G H I J K L M N O Ɔ P S T U V W Y a b d e ɛ f g h i j k l m n o ɔ p s t u v w y"
}
