name: "Great Vibes"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2012-03-29"
fonts {
  name: "Great Vibes"
  style: "normal"
  weight: 400
  filename: "GreatVibes-Regular.ttf"
  post_script_name: "GreatVibes-Regular"
  full_name: "Great Vibes Regular"
  copyright: "Copyright 2010 The Great Vibes Pro Project Authors (https://github.com/googlefonts/great-vibes)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
