name: "Space—where typography begins"
authors: "David Berlow"
reviewers: "TBC"
topics: "type_design"
topics: "optical_size"
topics: "variable_fonts"
prev_lessons: "size"
related_terms: "weight"
related_terms: "variable_fonts"
related_terms: "optical_sizes"
related_terms: "glyph"
excerpt: "Type is, in essence,  a series of shapes, in various combinations, hanging onto a framework of rectangles. Typography can contain a lot of different elements, beyond text and space, like symbols, icons, rules, ornaments, and effects. But for the most part, it contains just the marks of glyphs and the spaces within and around them. And the majority of the fonts we use today contain mostly space."
