name: "Shrikhand"
designer: "Jonny Pinhorn"
license: "OFL"
category: "DISPLAY"
date_added: "2016-06-20"
fonts {
  name: "Shrikhand"
  style: "normal"
  weight: 400
  filename: "Shrikhand-Regular.ttf"
  post_script_name: "Shrikhand-Regular"
  full_name: "Shrikhand Regular"
  copyright: "Copyright (c) 2015 Jonny Pinhorn (jonpinhorn.typedesign@gmail.com)"
}
subsets: "gujarati"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
stroke: "SERIF"
classifications: "DISPLAY"
