name: "Switching from static to variable fonts"
authors: "Elliot Jay Stocks"
reviewers: "Laurence Penney"
topics: "variable_fonts"
topics: "web_fonts"
prev_lessons: "the_foundations_of_web_typography"
next_lessons: "using_web_fonts_from_a_font_delivery_service"
next_lessons: "self_hosting_web_fonts"
related_terms: "web_font"
related_terms: "weight_axis"
related_terms: "width_axis"
related_terms: "variable_fonts"
excerpt: "INSERT_EXCERPT"
