name: "Switching from static to variable fonts"
authors: "Elliot Jay Stocks"
reviewers: "Laurence Penney"
topics: "variable_fonts"
topics: "web_fonts"
prev_lessons: "styling_type_on_the_web_with_variable_fonts"
next_lessons: "introducing_parametric_axes"
related_terms: "web_font"
related_terms: "weight_axis"
related_terms: "width_axis"
related_terms: "variable_fonts"
excerpt: "Swapping out our static fonts for variable ones can be a useful way of dipping your toes into this new world. With the overall typographic system tried and tested, it’s just of a case of finessing our typography—and saving some data while we’re at it."
