name: "Pairing typefaces"
authors: "Elliot Jay Stocks"
reviewers: "Bruce Willen"
reviewers: "Frank Rausch"
reviewers: "Jason Santa Maria"
reviewers: "Matthew Smith"
reviewers: "Micah Rich"
reviewers: "Mike Kus"
reviewers: "Thomas Jockin"
reviewers: "Tyler Finck"
topics: "choosing_type"
topics: "language_support"
topics: "pairing_type"
prev_lessons: "choosing_typefaces_that_have_optical_sizes"
next_lessons: "pairing_typefaces_within_a_family_superfamily"
next_lessons: "pairing_typefaces_by_the_same_type_designer_or_type_foundry"
related_terms: "weight"
related_terms: "style"
excerpt: "Once we’ve spent all that time and effort choosing a primary typeface for our project, we get to do it all over again for a secondary typeface."
