name: "Qwigley"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2011-12-19"
fonts {
  name: "Qwigley"
  style: "normal"
  weight: 400
  filename: "Qwigley-Regular.ttf"
  post_script_name: "Qwigley-Regular"
  full_name: "Qwigley Regular"
  copyright: "Copyright 2011 The Qwigley Project Authors (https://github.com/googlefonts/qwigley)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
