name: "Greek script"
excerpt: "The writing system used for the Greek language, not be confused with the erroneously used “Greek” placeholder text."
related_lessons: "language_support_in_fonts"
related_lessons: "choosing_reliable_typefaces"
