name: "Flow Block"
designer: "Dan Ross"
license: "OFL"
category: "DISPLAY"
date_added: "2021-10-22"
fonts {
  name: "Flow Block"
  style: "normal"
  weight: 400
  filename: "FlowBlock-Regular.ttf"
  post_script_name: "FlowBlock-Regular"
  full_name: "Flow Block Regular"
  copyright: "Copyright 2020 The Flow Project Authors (https://github.com/HYPD/flow-typeface)"
}
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "SYMBOLS"
