name: "Miama"
designer: "Linus Romer"
license: "OFL"
category: "HANDWRITING"
date_added: "2012-05-09"
fonts {
  name: "Miama"
  style: "normal"
  weight: 400
  filename: "Miama-Regular.ttf"
  post_script_name: "Miama-Regular"
  full_name: "Miama"
  copyright: "Copyright (c) 2008-2011, Linus Romer, with Reserved Font Name Miama.\n\nThis Font Software is licensed under the SIL Open Font License, Version 1.1."
}
subsets: "greek"
subsets: "greek-ext"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
