name: "Slackside One"
designer: "Maniackers Design"
license: "OFL"
category: "HANDWRITING"
date_added: "2020-12-14"
fonts {
  name: "Slackside One"
  style: "normal"
  weight: 400
  filename: "SlacksideOne-Regular.ttf"
  post_script_name: "SlacksideOne-Regular"
  full_name: "Slackside One Regular"
  copyright: "Copyright 2020 The Slackside One Project Authors (https://github.com/ManiackersDesign/slackside), all rights reserved."
}
subsets: "japanese"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
languages: "ja_Kana"
languages: "ja_Hira"
primary_script: "Hira"
classifications: "DISPLAY"
classifications: "HANDWRITING"
