id: "dyu"
name: "Dyula"
preferred_name: ""
autonym: "Julakan"
population: 6667328
region: "BF"
script: "Latin"
exemplar_chars {
  base: "ߐ ߏ ߎ ߍ ߌ ߋ ߊ ߙ ߘ ߗ ߖ ߕ ߔ ߓ ߡ ߟ ߞ ߝ ߜ ߛ ߚ ߒ ߦ ߥ ߤ ߣ ߢ"
  marks: "◌߫ ◌߬ ◌߭ ◌߮ ◌߯ ◌߰ ◌߱"
  numerals: "߀ ߁ ߂ ߃ ߄ ߅ ߆ ߇ ߈ ߉"
}
