name: "Introducing accessibility in typography"
authors: "Susanna Zaraysky"
reviewers: "Bonnie Shaver-Troup"
reviewers: "Hilary Palmen"
reviewers: "Rain Michaels"
topics: "accessibility"
topics: "readability"
related_terms: "legibility"
related_terms: "readability"
prev_lessons: "how_type_influences_readability"
excerpt: "Making text accessible should be part of everyday practice. However, general typographic practices of optimizing legibility and readability don’t necessarily go all the way towards making text accessible."
