name: "Tofu"
excerpt: "A symbol that has come to be known as “tofu”, displayed when a character is not present in a font and no fallback option is available."
related_lessons: "language_support_in_fonts"
