name: "Superscript & subscript"
excerpt: "Text formatted to appear smaller than the surrounding text, usually aligned slightly above the top (super) or bottom (sub) of regular type."
related_lessons: "INSERT_RELATED_LESSONS_AS_MANY_AS_NEEDED"
