name: "Unit"
excerpt: "A way of measuring font size, line height, line-length, margins, etc. Points, pixels, and ems (or rems) are the units most relevant to today’s typesetting needs."
related_lessons: "choosing_a_suitable_line_height"
related_lessons: "understanding_measure_line_length"
