name: "Axis (in variable fonts)"
excerpt: "A single aspect of a typeface’s design that can be altered by the user, such as weight, width, slant, or optical size."
related_lessons: "introducing_variable_fonts"
related_lessons: "designing_with_variable_fonts_in_desktop_apps"
related_lessons: "loading_variable_fonts_on_the_web"
related_lessons: "styling_type_on_the_web_with_variable_fonts"
