id: "kk_Arab"
name: "Kazakh (Arabic)"
preferred_name: ""
autonym: ""
population: 1418002
region: "AF"
region: "MN"
region: "IR"
region: "CN"
script: "Perso-Arabic"
script: "Cyrillic"
exemplar_chars {
}
