name: "STIX Two Math"
designer: "Tiro Typeworks, Ross Mills, John Hudson, Paul Hanslow"
license: "OFL"
category: "SERIF"
date_added: "2021-04-15"
fonts {
  name: "STIX Two Math"
  style: "normal"
  weight: 400
  filename: "STIXTwoMath-Regular.ttf"
  post_script_name: "STIXTwoMath-Regular"
  full_name: "STIX Two Math Regular"
  copyright: "Copyright 2001-2021 The STIX Fonts Project Authors (https://github.com/stipub/stixfonts)"
}
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "greek"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
