name: "The Canadian Syllabics"
lessons: "an_introduction_to_syllabics_typography"
lessons: "algonquian_syllabics"
lessons: "inuktut_syllabics"
lessons: "dene_syllabics"
lessons: "dakelh_carrier_syllabics"
excerpt: "The Canadian Syllabics (often referred to simply as the “Syllabics”) is a writing system used by many different Indigenous language communities throughout Canada and parts of the United States. The Syllabics are unique in how they represent written language, and many communities have local requirements and preferences in how their Syllabics should appear and function as text. This module outlines the general principles used by all, as well as specific recommendations that address the requirements and preferences of specific language communities."
