name: "Yuji Hentaigana Akebono"
designer: "Kinuta Font Factory"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-06-10"
fonts {
  name: "Yuji Hentaigana Akebono"
  style: "normal"
  weight: 400
  filename: "YujiHentaiganaAkebono-Regular.ttf"
  post_script_name: "YujiHentaiganaAkebono-Regular"
  full_name: "Yuji Hentaigana Akebono Regular"
  copyright: "Copyright 2021 The Yuji Project Authors (https://github.com/Kinutafontfactory/Yuji)"
}
subsets: "japanese"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
primary_script: "Hira"
languages: "ja_Kana"
languages: "ja_Hira"
