name: "Designspace"
excerpt: "A system specified during the type design process that controls how a variable font’s appearance changes, via interpolation from the master designs."
related_lessons: "factors_that_influence_the_efficiency_of_variable_web_fonts"
