id: "rm"
name: "Romansh"
preferred_name: ""
autonym: "Rumantsch"
population: 42019
region: "CH"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z À Â È É Ê Î Ò Ô Ö Ü a b c d e f g h i j k l m n o p q r s t u v w x y z à â è é ê î ò ô ö ü"
  auxiliary: "á ă â å ä ā æ ç ĕ ê ë ē í ĭ î ï ī ñ ó ŏ ô ö ø ō œ ú ŭ û ü ū ÿ"
  marks: "◌̀ ◌́ ◌̂ ◌̈"
  numerals: ". ’ % ‰ + − 0 1 2 3 4 5 6 7 8 9"
  index: "A À B C D E É È F G H I Ì J K L M N O Ò P Q R S T U Ù V W X Y Z"
}
