name: "History of type"
lessons: "TBC1"
lessons: "TBC2"
lessons: "TBC3"
excerpt: "The rich history of type design and the technical evolution of typesetting are woven into our everyday practice of typography, from how we select fonts to how we use spacing. Today, when setting type has arguably never been easier, and with variable font technology allowing us unprecedented typographic control, looking to the challenges and solutions from the past can help us optimize the modern reading experience."
