name: "History of Latin type"
lessons: "the_invention_of_type"
lessons: "what_have_the_romans_ever_done_for_us"
lessons: "transitional_faces"
lessons: "modern_type"
lessons: "display_type"
lessons: "from_metal_to_digital"
lessons: "fitting_the_line"
lessons: "justification_hyphenation"
lessons: "the_tight_not_touching_style"
excerpt: "The rich history of type design and the technical evolution of typesetting are woven into our everyday practice of typography, from how we select fonts to how we use spacing. And while the tools we have today are more capable than ever, designing is still about problem solving. Looking to the challenges and solutions from the past helps give us a deeper understanding of how type works."
