name: "From type to logotype"
authors: "Tom Muller"
reviewers: "Emma Price"
topics: "branding"
related_terms: "bespoke_custom_type"
related_terms: "icon_symbol"
related_terms: "sans_serif"
related_terms: "typeface"
related_terms: "monospaced"
prev_lessons: "a_checklist_for_choosing_type"
next_lessons: "vertical_spacing_and_line_height_in_design_systems"
excerpt: "From a sketch, to typeface selection, to incorporating a mark, to finalizing a full logo, let’s look at every step in the process."
