name: "From type to logotype"
authors: "Tom Muller"
reviewers: "Emma Price"
topics: "branding"
related_terms: "bespoke_custom_type"
related_terms: "icon_symbol"
related_terms: "sans_serif"
related_terms: "typeface"
related_terms: "monospaced"
next_lessons: "vertical"
excerpt: "INSERT_EXCERPT"
