name: "Sassy Frass"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-10-13"
fonts {
  name: "Sassy Frass"
  style: "normal"
  weight: 400
  filename: "SassyFrass-Regular.ttf"
  post_script_name: "SassyFrass-Regular"
  full_name: "Sassy Frass Regular"
  copyright: "Copyright 2008 The Sassy Frass Project Authors (https://github.com/googlefonts/sassy-frass)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
