name: "Viewport"
excerpt: "The size of the browser window, or any area that a website or app uses as its display surface, not including any “chrome”."
related_lessons: "the_foundations_of_web_typography"
