name: "Bungee Spice"
designer: "David Jonathan Ross"
license: "OFL"
category: "DISPLAY"
date_added: "2022-04-05"
fonts {
  name: "Bungee Spice"
  style: "normal"
  weight: 400
  filename: "BungeeSpice-Regular.ttf"
  post_script_name: "BungeeSpice-Regular"
  full_name: "Bungee Spice Regular"
  copyright: "Copyright 2021 Roderick Sheeter"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
stroke: "SANS_SERIF"
classifications: "DISPLAY"
