id: "ny"
name: "Nyanja"
preferred_name: ""
autonym: "Chicheŵa"
population: 17026780
region: "MW"
region: "MZ"
region: "ZW"
region: "ZM"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ŋ Ŵ a b c d e f g h i j k l m n o p q r s t u v w x y z ŋ ŵ"
  marks: "◌̂"
}
