name: "Dela Gothic One"
designer: "aratakana"
license: "OFL"
category: "DISPLAY"
date_added: "2020-12-14"
fonts {
  name: "Dela Gothic One"
  style: "normal"
  weight: 400
  filename: "DelaGothicOne-Regular.ttf"
  post_script_name: "DelaGothicOne-Regular"
  full_name: "Dela Gothic One Regular"
  copyright: "Copyright 2020 The Dela Gothic Project Authors (https://github.com/syakuzen/DelaGothic)"
}
subsets: "cyrillic"
subsets: "greek"
subsets: "japanese"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
