name: "Zen Antique"
designer: "Yoshimichi Ohira"
license: "OFL"
category: "SERIF"
date_added: "2021-10-22"
fonts {
  name: "Zen Antique"
  style: "normal"
  weight: 400
  filename: "ZenAntique-Regular.ttf"
  post_script_name: "ZenAntique-Regular"
  full_name: "Zen Antique Regular"
  copyright: "Copyright 2021 The Zen Antique Project Authors (https://github.com/googlefonts/zen-antique)"
}
subsets: "cyrillic"
subsets: "greek"
subsets: "japanese"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
primary_script: "Jpan"
