sources:
    - ../Big-Shoulders-Stencil/sources/BigShouldersStencil.glyphs
recipe:
  ../Big-Shoulders-Stencil/fonts/variable/display/BigShouldersStencilDisplay[wght].ttf:
    - source: ../Big-Shoulders-Stencil/sources/BigShouldersStencil.glyphs
    - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
      operation: buildVariable
    - operation: subspace
      axes: opsz=72
    - operation: rename
      name: Big Shoulders Stencil Display
      args: --just-family
    - operation: fix
    - postprocess: buildStat
  # And now the small caps family
  ../Big-Shoulders-Stencil/fonts/variable/display/BigShouldersStencilDisplaySC[wght].ttf:
    - source: ../Big-Shoulders-Stencil/sources/BigShouldersStencil.glyphs
    - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
      operation: buildVariable
    - operation: subspace
      axes: opsz=72
    - args: '''smcp -> ccmp'''
      operation: remapLayout
    - operation: rename
      name: Big Shoulders Stencil Display SC
      args: --just-family
    - operation: fix
    - postprocess: buildStat
