name: "Transitional, or Neo-classical"
excerpt: "A historical classification for typefaces that reference elements of human penmanship, but do so in a more ordered and structured form."
related_lessons: "making_sense_of_typographic_classifications"
