name: "Hanging punctuation"
excerpt: "Punctuation marks that appear outside of a text frame (usually to the left in left-aligned, left-to-right text) to create a more pleasing vertical rhythm."
related_lessons: "working_with_hanging_punctuation"
