id: "th"
name: "Thai"
preferred_name: ""
autonym: "ภาษาไทย"
population: 55181920
region: "TH"
script: "Thai"
exemplar_chars {
  base: "ก ข ฃ ค ฅ ฆ ง จ ฉ ช ซ ฌ ญ ฎ ฏ ฐ ฑ ฒ ณ ด ต ถ ท ธ น บ ป ผ ฝ พ ฟ ภ ม ย ร ล ว ศ ษ ส ห ฬ อ ฮ ะ า เ โ ใ ไ ฤ ๅ ฦ"
  auxiliary: "\\u200B"
  marks: "◌̍ ◌̎ ◌ั ◌ิ ◌ุ ◌ู ◌็ ◌ํ"
  numerals: "๐ ๑ ๒ ๓ ๔ ๕ ๖ ๗ ๘ ๙ 0 1 2 3 4 5 6 7 8 9"
  punctuation: "๏ ๛"
  index: "ก ข ฃ ค ฅ ฆ ง จ ฉ ช ซ ฌ ญ ฎ ฏ ฐ ฑ ฒ ณ ด ต ถ ท ธ น บ ป ผ ฝ พ ฟ ภ ม ย ร ฤ ล ฦ ว ศ ษ ส ห ฬ อ ฮ"
}
