name: "Introducing variable fonts"
authors: "Elliot Jay Stocks"
reviewers: "Micah Rich"
reviewers: "Thomas Jockin"
topics: "optical_size"
topics: "variable_fonts"
topics: "weight"
topics: "width"
prev_lessons: "introducing_weights_styles"
prev_lessons: "introducing_alternate_glyphs"
next_lessons: "styling_type_on_the_web_with_variable_fonts"
related_terms: "variable_fonts"
related_terms: "weight"
related_terms: "style"
related_terms: "width"
related_terms: "optical_sizes"
excerpt: "Variable fonts remove the explicit distinctions between different weights and styles, and put more typographic control in the hands of the user."
