name: "Rubik Mono One"
designer: "Hubert and Fischer"
license: "OFL"
category: "SANS_SERIF"
date_added: "2014-05-05"
fonts {
  name: "Rubik Mono One"
  style: "normal"
  weight: 400
  filename: "RubikMonoOne-Regular.ttf"
  post_script_name: "RubikMonoOne-Regular"
  full_name: "Rubik Mono One Regular"
  copyright: "Copyright 2015 The Rubik Project Authors (mail@hubertfischer.com)"
}
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "hebrew"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
stroke: "SANS_SERIF"
classifications: "MONOSPACE"
