id: "bez"
name: "Bena"
preferred_name: ""
autonym: "Ekibena"
population: 995397
region: "TZ"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W Y Z a b c d e f g h i j k l m n o p q r s t u v w y z"
  auxiliary: "x"
  index: "A B C D E F G H I J K L M N O P Q R S T U V W Y Z"
}
