name: "Introducing accessibility in typography"
authors: "Susanna Zaraysky"
reviewers: "Bonnie Shaver-Troup"
topics: "INSERT_TOPIC"
related_terms: "INSERT_RELATED_TERMS"
prev_lessons: "INSERT_PREV"
next_lessons: "INSERT_NEXT
excerpt: "INSERT_EXCERPT"
