name: "Introducing accessibility in typography"
authors: "Susanna Zaraysky"
reviewers: "Bonnie Shaver-Troup"
topics: "legibility"
topics: "readability"
related_terms: "legibility"
related_terms: "readability"
prev_lessons: "how_type_influences_readability"
excerpt: "INSERT_EXCERPT"
