name: "Handwriting"
excerpt: "The act of writing by the human hand, usually with a pen or pencil, in a casual manner; or: a genre classification of type."
related_lessons: "making_sense_of_typographic_classifications"
