id: "my"
name: "Burmese"
preferred_name: ""
autonym: "မြန်မာစာ / မြန်မာစကား"
population: 36559231
region: "MM"
region: "BD"
script: "Myanmar"
exemplar_chars {
  base: "က ခ ဂ ဃ င စ ဆ ဇ ဈ ဉ ည ဋ ဌ ဍ ဎ ဏ တ ထ ဒ ဓ န ပ ဖ ဗ ဘ မ ယ ရ လ ဝ သ ဣ ဤ ဥ ဦ ဧ ဩ ဪ"
  auxiliary: "၀႐ ၁႑ ၂႒ ၃႓ ၄႔ ၅႕ ၆႖ ၇႗ ၈႘ ၉႙ ၵ ၚ ၽ ၾ ၐ ၑ ၥ ဨ ဢ ၒ ၓ ၔ ၕ \\u1033 ၖ ၗ \\u1058 \\u1059 \\u1034 ၢ \\u1086 ၤ ႈ ႊ ႏ"
  marks: "◌ါ ◌ာ ◌ိ ◌ီ ◌ု ◌ူ ◌ေ ◌ဲ ◌ံ ◌့ ◌း ◌္ ◌် ◌ျ ◌ြ ◌ွ ◌ှ ◌ၖ ◌ၗ"
  numerals: "\\- ‑ , . % ‰ + 0၀ 1၁ 2၂ 3၃ 4၄ 5၅ 6၆ 7၇ 8၈ 9၉"
  punctuation: "၊ ။ ‘ ’ “ ”"
  index: "က ခ ဂ ဃ င စ ဆ ဇ ဈ ဉ ည ဋ ဌ ဍ ဎ ဏ တ ထ ဒ ဓ န ပ ဖ ဗ ဘ မ ယ ရ လ ဝ သ ဟ ဠ အ"
}
