name: "Using type"
lessons: "language_support_in_fonts"
lessons: "choosing_a_suitable_line_height"
lessons: "understanding_measure_line_length"
lessons: "track_carefully_or_not_at_all"
lessons: "manual_kerning_is_rarely_required"
lessons: "avoiding_widows_orphans"
lessons: "working_with_hanging_punctuation"
lessons: "breaking_the_rules"
lessons: "designing_with_variable_fonts_in_desktop_apps"
lessons: "using_web_fonts"
lessons: "the_foundations_of_web_typography"
lessons: "using_web_fonts_from_a_font_delivery_service"
lessons: "self_hosting_web_fonts"
lessons: "implementing_open_type_features_on_the_web"
lessons: "loading_variable_fonts_on_the_web"
lessons: "styling_type_on_the_web_with_variable_fonts"
excerpt: "When you have a typeface, how can you use it with purpose? Equip yourself with the tools and processes needed to most meaningfully work with type, from setting appropriate measures and considered line heights, to working with web fonts and implementing variable fonts."
