name: "Waterfall"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-11-18"
fonts {
  name: "Waterfall"
  style: "normal"
  weight: 400
  filename: "Waterfall-Regular.ttf"
  post_script_name: "Waterfall-Regular"
  full_name: "Waterfall Regular"
  copyright: "Copyright 2011 The Waterfall Project Authors (https://github.com/googlefonts/waterfall)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
