id: "lag"
name: "Langi"
preferred_name: ""
autonym: "Kɨlaangi"
population: 509409
region: "TZ"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Á É Í Ó Ú Ɨ Ʉ a b c d e f g h i j k l m n o p q r s t u v w x y z á é í ó ú ɨ ʉ"
  marks: "◌́"
  index: "A B C D E F G H I Ɨ J K L M N O P Q R S T U Ʉ V W X Y Z"
}
