name: "Loading variable fonts on the web"
authors: "Elliot Jay Stocks"
reviewers: "Bram Stein"
reviewers: "Laurence Penney"
topics: "variable_fonts"
topics: "web_fonts"
prev_lessons: "using_web_fonts"
prev_lessons: "using_web_fonts_from_a_font_delivery_service"
prev_lessons: "self_hosting_web_fonts"
prev_lessons: "implementing_open_type_features_on_the_web"
next_lessons: "styling_type_on_the_web_with_variable_fonts"
related_terms: "variable_fonts"
related_terms: "web_font"
excerpt: "Using a variable font on our website is straightforward, but let’s break down each step in the process so we can see how it differs from using traditional web fonts."
