name: "Font format"
excerpt: "The specific file type(s) designated for font data, with a font itself being the manifestation of a typeface."
related_lessons: "using_web_fonts"
related_lessons: "introducing_alternate_glyphs"
