name: "Grey Qo"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-09-02"
fonts {
  name: "Grey Qo"
  style: "normal"
  weight: 400
  filename: "GreyQo-Regular.ttf"
  post_script_name: "GreyQo-Regular"
  full_name: "Grey Qo Regular"
  copyright: "Copyright 2008-2021 The Grey Qo Project Authors (https://github.com/googlefonts/grey-qo)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
