name: "Pushster"
designer: "Sir Andyj"
license: "OFL"
category: "DISPLAY"
date_added: "2019-04-01"
fonts {
  name: "Pushster"
  style: "normal"
  weight: 400
  filename: "Pushster-Regular.ttf"
  post_script_name: "Pushster-Regular"
  full_name: "Pushster Regular"
  copyright: "Copyright 2010 xyz The Lobster Project Authors (https://github.com/impallari/The-Lobster-Font), with Reserved Font Name \"Lobster\".4"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
languages: "en_Latn"
languages: "eo_Latn"
minisite_url: "https://fonts.google.com/icons"
primary_script: "Thai"
primary_language: "en_Latn"
classifications: "DISPLAY"
classifications: "HANDWRITING"
