contributors {
  name: "Bram Stein"
  personal_site: "https://www.bramstein.com"
}
contributors {
  name: "Bruce Willen"
  personal_site: "https://publicmechanics.com"
}
contributors {
  name: "David Brezina"
  personal_site: "https://rosettatype.com"
}
contributors {
  name: "Doug Wilson"
  personal_site: "https://realdougwilson.com"
}
contributors {
  name: "Ellen Lupton"
  personal_site: "https://ellenlupton.com"
}
contributors {
  name: "Elliot Jay Stocks"
  personal_site: "https://elliotjaystocks.com"
}
contributors {
  name: "Erik Spiekermann"
  personal_site: "https://spiekileaks.com"
}
contributors {
  name: "Frank Rausch"
  personal_site: "https://frankrausch.com"
}
contributors {
  name: "Gerry Leonidas"
  personal_site: "https://leonidas.net"
}
contributors {
  name: "Jamie Clarke"
  personal_site: "https://www.jamieclarketype.com"
}
contributors {
  name: "Jason Pamental"
  personal_site: "https://rwt.io"
}
contributors {
  name: "Jason Santa Maria"
  personal_site: "https://jasonsantamaria.com"
}
contributors {
  name: "Jessica Hische"
  personal_site: "https://jessicahische.is"
}
contributors {
  name: "John Boardley"
  personal_site: "https://ilovetypography.com/about"
}
contributors {
  name: "Laurence Penney"
  personal_site: "https://lorp.org"
}
contributors {
  name: "Mark Boulton"
  personal_site: "https://markboulton.co.uk"
}
contributors {
  name: "Matthew Smith"
  personal_site: "https://matthewsmith.website"
}
contributors {
  name: "Micah Rich"
  personal_site: "https://micahrich.com"
}
contributors {
  name: "Mike Kus"
  personal_site: "https://www.mikekus.com/"
}
contributors {
  name: "Richard Rutter"
  personal_site: "https://clagnut.com"
}
contributors {
  name: "Rosalie Wagner"
  personal_site: "http://rosaliewagner.com"
}
contributors {
  name: "Santiago Orozco"
  personal_site: "http://typemade.com"
}
contributors {
  name: "Sam Berlow"
  personal_site: "https://twitter.com/sberlow"
}
contributors {
  name: "Thomas Jockin"
  personal_site: "http://thomasjockin.com"
}
contributors {
  name: "Thomas Phinney"
  personal_site: "https://twitter.com/thomasphinney"
}
contributors {
  name: "Trent Walton"
  personal_site: "https://trentwalton.com"
}
contributors {
  name: "Tyler Finck"
  personal_site: "https://www.tylerfinck.com"
}
contributors {
  name: "Yves Peters"
  personal_site: "https://twitter.com/baldcondensed"
}
contributors {
  name: "Viviana Monsalve"
  personal_site: "https://www.instagram.com/_vv_monsalve_"
}
