id: "haw"
name: "Hawaiian"
preferred_name: ""
autonym: "’Olelo Hawai’i"
population: 29604
region: "US"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ā Ē Ī Ō Ū a b c d e f g h i j k l m n o p q r s t u v w x y z ā ē ī ō ū ’"
  auxiliary: "b c d f g j q r s t v x y z"
  marks: "◌̄"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  index: "A E I O U B C D F G H J K L M N P Q R S T V W ʻ X Y Z"
}
