name: "Variable fonts are here. Now what?"
authors: "Nick Sherman"
reviewers: "Laurence Penney"
reviewers: "Piper Haywood"
topics: "variable_fonts"
related_terms: "variable_fonts"
next_lessons: "web_font_comparisons_variable_vs_static"
excerpt: "What are the practical benefits of variable fonts in real-world design projects? And what are the implications of variable fonts’ flexibility in day-to-day design work?"
