name: "Introducing type"
lessons: "why_care_about_typography"
lessons: "an_overview_of_latin_type_anatomy"
lessons: "making_sense_of_typographic_classifications"
lessons: "exploring_punctuation"
lessons: "introducing_weights_styles"
lessons: "introducing_alternate_glyphs"
lessons: "understanding_numerals"
lessons: "open_type_features_in_practice"
lessons: "introducing_variable_fonts"
excerpt: "We all use type every day, from word processors and social media graphic apps to professional desktop design software and hand-coded websites. Good typography is within everyone’s reach, and it starts with the fundamentals. This module acts as an accessible primer for anyone to build confidence and skills, and is also a solid foundation for experienced designers looking to deepen their understanding of the basics."
