name: "Bahianita"
designer: "Omnibus-Type"
license: "OFL"
category: "DISPLAY"
date_added: "2019-06-12"
fonts {
  name: "Bahianita"
  style: "normal"
  weight: 400
  filename: "Bahianita-Regular.ttf"
  post_script_name: "Bahianita-Regular"
  full_name: "Bahianita Regular"
  copyright: "Copyright 2018 The Bahianita Project Authors (https://github.com/Omnibus-Type/Bahiana/tree/master/Bahianita)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
stroke: "SANS_SERIF"
classifications: "DISPLAY"
