name: "Installing & managing fonts—including variable fonts"
authors: "Elliot Jay Stocks"
reviewers: "Laurence Penney"
reviewers: "Thomas Phinney"
topics: "variable_fonts"
prev_lessons: "TBC"
next_lessons: "TBC"
related_terms: "variable_fonts"
excerpt: "TBC"
