name: "Installing & managing fonts—including variable fonts"
authors: "Elliot Jay Stocks"
reviewers: "Laurence Penney"
reviewers: "Thomas Phinney"
topics: "variable_fonts"
next_lessons: "language_support_in_fonts"
related_terms: "variable_fonts"
excerpt: "TBC"
