name: "Installing & managing fonts—including variable fonts"
authors: "Elliot Jay Stocks"
reviewers: "Laurence Penney"
reviewers: "Thomas Phinney"
topics: "variable_fonts"
prev_lessons: "how_to_make_type_feel_authentic"
next_lessons: "language_support_in_fonts"
related_terms: "variable_fonts"
excerpt: "Building and maintaining a font collection on the computer you use for design work is an important part of life as a designer. However, there are a number of ways this process can be optimized—primarily by understanding where font files live, but also by proactively organizing your collection with font management software."
