id: "mi"
name: "Maori"
preferred_name: ""
autonym: "Māori"
population: 137913
region: "NZ"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ā Ē Ī Ō Ū a b c d e f g h i j k l m n o p q r s t u v w x y z ā ē ī ō ū"
  auxiliary: "b c d f g j l q s v x y z"
  marks: "◌̄"
  index: "A E H I K M N O P R T U W"
}
