name: "Adding an authentic, natural touch to type"
authors: "Elliot Jay Stocks"
reviewers: "Laurence Penney"
reviewers: "Gerry Leonidas"
topics: "open_type"
topics: "families"
related_terms: "INSERT_RELATED_TERMS"
prev_lessons: "INSERT_PREV"
next_lessons: "INSERT_NEXT
excerpt: "INSERT_EXCERPT"
