name: "Adding an authentic, natural touch to type"
authors: "Elliot Jay Stocks"
reviewers: "Laurence Penney"
reviewers: "Gerry Leonidas"
topics: "open_type"
topics: "families"
related_terms: "open_type"
prev_lessons: "vertical"
next_lessons: "installing_and_managing_fonts"
excerpt: "INSERT_EXCERPT"
