name: "Are You Serious"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-08-27"
fonts {
  name: "Are You Serious"
  style: "normal"
  weight: 400
  filename: "AreYouSerious-Regular.ttf"
  post_script_name: "AreYouSerious-Regular"
  full_name: "Are You Serious Regular"
  copyright: "Copyright 2004 The RU Serius Project Authors (https://github.com/googlefonts/are-you-serious)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
