name: "X-height"
excerpt: "The height of the lowercase characters that have no ascenders nor descenders, which indicates how tall or short the type appears."
related_lessons: "exploring_x_height_the_em_square"
related_lessons: "choosing_typefaces_that_have_optical_sizes"
