name: "Size wise"
authors: "David Berlow"
reviewers: "TBC"
topics: "type_design"
topics: "optical_size"
topics: "variable_fonts"
prev_lessons: "size"
related_terms: "weight"
related_terms: "variable_fonts"
related_terms: "optical_sizes"
related_terms: "glyph"
excerpt: "Size wise, typefaces have a long history of small families: Style-wise, many sizes of metal type gave way to digital systems of multiple masters for various resolutions. Then came a flourishing of families with a broad range of styles and few size masters in PostScript, followed by OpenType continuing the PostScript tradition. And then, finally, variable fonts."
