name: "Inspiration"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-11-26"
fonts {
  name: "Inspiration"
  style: "normal"
  weight: 400
  filename: "Inspiration-Regular.ttf"
  post_script_name: "Inspiration-Regular"
  full_name: "Inspiration Regular"
  copyright: "Copyright 2004 The Inspiration Project Authors (https://github.com/googlefonts/inspiration)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
