name: "Contrast axis (CTRS)"
excerpt: "An axis in some variable fonts that controls the difference between thick and thin strokes, from no contrast to extreme or reversed contrast."
related_lessons: "introducing_variable_fonts"
related_lessons: "designing_with_variable_fonts_in_desktop_apps"
related_lessons: "styling_type_on_the_web_with_variable_fonts"
