id: "wo"
name: "Wolof"
preferred_name: ""
autonym: "Wolof"
population: 11025493
region: "SN"
region: "MR"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z À Ã É Ë Ñ Ó Ŋ a b c d e f g h i j k l m n o p q r s t u v w x y z à ã é ë ñ ó ŋ"
  auxiliary: "ã h v z"
  marks: "◌̀ ◌́ ◌̃ ◌̈"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‑ , ; \\: ! ? . ( ) \\[ \\] \\{ \\}"
  index: "A B C D E F G H I J K L M N Ŋ O P Q R S T U V W X Y Z"
}
