name: "Styling type on the web with variable fonts"
authors: "Elliot Jay Stocks"
reviewers: "Erik Spiekermann"
reviewers: "Laurence Penney"
reviewers: "Rosalie Wagner"
reviewers: "Tyler Finck"
topics: "optical_size"
topics: "style"
topics: "variable_fonts"
topics: "web_fonts"
topics: "weight"
topics: "width"
prev_lessons: "introducing_variable_fonts"
prev_lessons: "using_web_fonts"
prev_lessons: "loading_variable_fonts_on_the_web"
related_terms: "variable_fonts"
related_terms: "weight"
related_terms: "optical_sizes"
excerpt: "Whether loading variable fonts from a font delivery service or our own server, the actual styling of them via CSS is the same as standard, non-variable fonts."
