name: "Homoglyphs"
excerpt: "A glyph with a design that can appear indistinguishable from—or least very similar to—another glyph with a separate meaning."
related_lessons: "INSERT_RELATED_LESSONS_AS_MANY_AS_NEEDED"
