name: "Marmelad"
designer: "Cyreal"
license: "OFL"
category: "SANS_SERIF"
date_added: "2011-12-07"
fonts {
  name: "Marmelad"
  style: "normal"
  weight: 400
  filename: "Marmelad-Regular.ttf"
  post_script_name: "Marmelad-Regular"
  full_name: "Marmelad Regular"
  copyright: "Copyright 2016 The Marmelad Project Authors (manveltype@gmail.com), with Reserved Font Name \"Marmelad\"."
}
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
