name: "Understanding measure/line length"
authors: "Elliot Jay Stocks"
reviewers: "David Brezina"
reviewers: "Doug Wilson"
reviewers: "Frank Rausch"
reviewers: "Jessica Hische"
reviewers: "Santiago Orozco"
reviewers: "Tyler Finck"
topics: "essentials"
prev_lessons: "choosing_a_suitable_line_height"
next_lessons: "track_carefully_or_not_at_all"
related_terms: "measure_line_length"
excerpt: "There are certain things we can do as typographers to tame potentially chaotic re-flows, and offer users an optimal reading experience."
