name: "Using web fonts"
authors: "Elliot Jay Stocks"
reviewers: "Bram Stein"
reviewers: "Doug Wilson"
reviewers: "Laurence Penney"
topics: "essentials"
topics: "web_fonts"
prev_lessons: "the_foundations_of_web_typography"
# next_lessons: "to_do_styling_type_on_the_web"
next_lessons: "using_web_fonts_from_a_font_delivery_service"
next_lessons: "self_hosting_web_fonts"
related_terms: "web_font"
related_terms: "variable_fonts"
excerpt: "Loading font files, referencing them, and assigning weights and styles. Plus, some optimization techniques."
