name: "Type classification in CJK: Japanese"
authors: "Min-Young Kim"
reviewers: "Lisa Huang"
reviewers: "Minjoo Ham"
reviewers: "Shoko Mugikura"
topics: "cjk"
related_terms: "cjk"
related_terms: "script_writing_system"
prev_lessons: "type_classification_in_cjk_chinese"
next_lessons: "type_classification_in_cjk_korean"
excerpt: "Here, we look at how CJK scripts are classified differently from Latin, and also from each other, with a focus on Japanese."
