name: "How type influences readability"
authors: "Hilary Palmen"
reviewers: "Bonnie Shaver-Troup"
reviewers: "Susanna Zaraysky"
topics: "accessibility"
topics: "readability"
related_terms: "legibility"
related_terms: "readability"
next_lessons: "introducing_accessibility_in_typography"
excerpt: "INSERT_EXCERPT"
