name: "How type influences readability"
authors: "Hilary Palmen"
reviewers: "Ben D. Sawyer"
reviewers: "Bonnie Shaver-Troup"
reviewers: "Susanna Zaraysky"
topics: "accessibility"
topics: "readability"
related_terms: "legibility"
related_terms: "readability"
next_lessons: "introducing_accessibility_in_typography"
excerpt: "Reading is what we do, and readability refers to qualities of a text that make reading easier. This includes content decisions, or format decisions, which help a reader to easily engage with and comprehend the message intended by the author."
