name: "Road Rage"
designer: "Robert Leuschke"
license: "OFL"
category: "DISPLAY"
date_added: "2021-10-22"
fonts {
  name: "Road Rage"
  style: "normal"
  weight: 400
  filename: "RoadRage-Regular.ttf"
  post_script_name: "RoadRage-Regular"
  full_name: "Road Rage Regular"
  copyright: "Copyright 2010 The Road Rage Project Authors (https://github.com/googlefonts/road-rage)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
stroke: "SANS_SERIF"
classifications: "DISPLAY"
