name: "Choosing typefaces that have optical sizes"
authors: "Elliot Jay Stocks"
reviewers: "Micah Rich"
reviewers: "Thomas Jockin"
topics: "choosing_type"
topics: "optical_size"
topics: "variable_fonts"
prev_lessons: "exploring_width_in_type"
next_lessons: "pairing_typefaces"
related_terms: "optical_sizes"
related_terms: "body"
related_terms: "display"
related_terms: "variable_fonts"
excerpt: "Optical sizing refers to the practice of type foundries creating slightly different versions of a typeface intended to be used at different sizes."
