name: "The evolution of Hangeul type design"
authors: "Min-Young Kim"
reviewers: "Lisa Huang"
reviewers: "Minjoo Ham"
reviewers: "Shoko Mugikura"
topics: "cjk"
related_terms: "cjk"
related_terms: "script_writing_system"
prev_lessons: "japanese_typography_basics"
next_lessons: "an_introduction_to_hangeul"
excerpt: "The Korean script Hangeul is one of the youngest scripts, but the evolution was so fast and unique from other scripts. Let’s look at how Hangeul design was developed over the years."
