name: "Typography"
excerpt: "The practice of making informed decisions about the setting of type. Not to be confused with type design."
related_lessons: "why_care_about_typography"
related_lessons: "choosing_reliable_typefaces"
