name: "An Alphabet for Reading and Writing"
authors: "Darrell Penta"
reviewers: "Cassidy Curtis"
reviewers: "Minjoo Ham"
reviewers: "Min-Young Kim"
reviewers: "SeHee Lee"
topics: "hangeul"
prev_lessons: "making_the_details_matter"
next_lessons: "lessons_from_hangeul"
related_terms: "script_writing_system"
excerpt: "INSERT"
