id: "ibb"
name: "Ibibio"
preferred_name: ""
autonym: ""
population: 2996392
region: "NG"
script: "Latin"
exemplar_chars {
  base: "A B D E F G H I Ị K M N Ñ O Ọ P R S T U Ʌ W Y a b d e f g h i ị k m n ñ o ọ p r s t u ʌ w y"
  marks: "◌̃ ◌̣"
}
