id: "jv"
name: "Javanese"
preferred_name: ""
autonym: "Jawa"
population: 91180665
region: "ID"
region: "MY"
script: "Latin"
exemplar_chars {
  base: "ꦄ ꦅ ꦆ ꦇ ꦈ ꦉ ꦊ ꦋ ꦌ ꦍ ꦎ ꦏ ꦐ ꦒ ꦓ ꦔ ꦕ ꦗ ꦚ ꦛ ꦝ ꦞ ꦟ ꦠ ꦢ ꦣ ꦤ ꦥ ꦦ ꦧ ꦨ ꦩ ꦪ ꦫ ꦭ ꦮ ꦯ ꦱ ꦲ"
  auxiliary: "ꦑ ꦖ ꦘ ꦙ ꦜ ꦡ ꦬ ꦰ"
  marks: "◌ꦀ ◌ꦁ ◌ꦂ ◌ꦃ ◌꦳ ◌ꦴ ◌ꦵ ◌ꦶ ◌ꦷ ◌ꦸ ◌ꦹ ◌ꦺ ◌ꦻ ◌ꦼ ◌ꦽ ◌ꦾ ◌ꦿ ◌꧀"
  numerals: "꧐ ꧑ ꧒ ꧓ ꧔ ꧕ ꧖ ꧗ ꧘ ꧙ 0 1 2 3 4 5 6 7 8 9"
  punctuation: "ꧏ ꧞ ꧟ ꧁ ꧂ ꧃ ꧄ ꧅ ꧆ ꧇ ꧈ ꧉ ꧊ ꧋ ꧌ ꧍"
  index: "A Â Å B C D E É È Ê G H I Ì J K L M N O Ò P R S T U Ù W Y"
}
