name: "Type classification in CJK"
authors: "Min-Young Kim"
reviewers: "Lisa Huang"
reviewers: "Minjoo Ham"
reviewers: "Shoko Mugikura"
topics: "cjk"
related_terms: "cjk"
next_lessons: "cjk_typesetting_rules"
excerpt: "INSERT_EXCERPT"
