name: "Using web fonts from a font delivery service"
authors: "Elliot Jay Stocks"
reviewers: "Bram Stein"
reviewers: "Doug Wilson"
reviewers: "Erik Spiekermann"
reviewers: "Frank Rausch"
topics: "web_fonts"
prev_lessons: "the_foundations_of_web_typography"
prev_lessons: "using_web_fonts"
next_lessons: "self_hosting_web_fonts"
related_terms: "web_font"
excerpt: "The easiest way to implement web fonts on a website is to use a font delivery service, so that most of the heavy lifting is done for us."
