name: "Hierarchy"
excerpt: "The overall structure of a document and the relationship between elements within the text."
related_lessons: "introducing_weights_styles"
related_lessons: "the_foundations_of_web_typography"
