id: "tk"
name: "Turkmen"
preferred_name: ""
autonym: "Түркменче"
population: 6870838
region: "AF"
region: "IR"
region: "TM"
script: "Perso-Arabic"
script: "Cyrillic"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ä Ç Ö Ü Ý Ň Ş Ž Ș a b c d e f g h i j k l m n o p q r s t u v w x y z ä ç ö ü ý ň ş ž ș"
  auxiliary: "c q v x"
  marks: "◌́ ◌̈ ◌̌ ◌̦ ◌̧"
  numerals: "  \\- ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‑ – — , ; \\: ! ? . … \" “ ” ( ) \\[ \\] \\{ \\} § @ * #"
  index: "A B Ç D E Ä F G H I J Ž K L M N Ň O Ö P R S Ş T U Ü W Y Ý Z"
}
