name: "The “tight not touching” style"
authors: "Micah Rich"
authors: "Thomas Jockin"
topics: "systems"
prev_lessons: "justification_hyphenation"
related_terms: "tracking_letter_spacing"
excerpt: "In the 1960s, the introduction of photo-typesetting made it possible to set type tighter than ever before. Over the next two decades, designers like Herb Lubalin and Tom Carnase used this new ability in letter spacing to create a (very cool) new aesthetic called tight-not-touching."
