name: "The “tight not touching” style"
authors: "Micah Rich"
authors: "Thomas Jockin"
reviewers: "TBC"
topics: "TBC"
prev_lessons: "TBC"
next_lessons: "TBC"
related_terms: "TBC"
excerpt: "EXCERPT_TBC"
