name: "The “tight not touching” style"
authors: "Micah Rich"
authors: "Thomas Jockin"
topics: "systems"
prev_lessons: "justification_hyphenation"
related_terms: "tracking_letter_spacing"
excerpt: "EXCERPT_TBC"
