name: "Choosing type"
lessons: "a_checklist_for_choosing_type"
lessons: "emotive_considerations_for_choosing_typefaces"
lessons: "choosing_reliable_typefaces"
lessons: "exploring_typefaces_with_multiple_weights_or_grades"
lessons: "exploring_width_in_type"
lessons: "choosing_typefaces_that_have_optical_sizes"
lessons: "pairing_typefaces"
lessons: "pairing_typefaces_within_a_family_superfamily"
lessons: "pairing_typefaces_by_the_same_type_designer_or_type_foundry"
lessons: "pairing_typefaces_based_on_their_construction_using_the_font_matrix"
lessons: "exploring_x_height_the_em_square"
lessons: "adding_fonts_to_google_docs"
excerpt: "When you have some text, how can you choose a typeface? Many people—professional designers included—go through an app’s font menu until we find one we like. But the aim of this Google Fonts Knowledge module is to show that there are many considerations that can improve our type choices. By setting some useful constraints to aid our type selection, we can also develop a critical eye for analyzing type along the way."
