name: "Sedgwick Ave Display"
designer: "Pedro Vergani, Kevin Burke"
license: "OFL"
category: "HANDWRITING"
date_added: "2017-08-01"
fonts {
  name: "Sedgwick Ave Display"
  style: "normal"
  weight: 400
  filename: "SedgwickAveDisplay-Regular.ttf"
  post_script_name: "SedgwickAveDisplay-Regular"
  full_name: "Sedgwick Ave Display Regular"
  copyright: "Copyright 2017 The Sedgwick Ave Project Authors (https://github.com/googlefonts/sedgwickave)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
