name: "Imperial Script"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-11-18"
fonts {
  name: "Imperial Script"
  style: "normal"
  weight: 400
  filename: "ImperialScript-Regular.ttf"
  post_script_name: "ImperialScript-Regular"
  full_name: "Imperial Script Regular"
  copyright: "Copyright 2008 The Imperial Script Project Authors (https://github.com/googlefonts/imperial-script)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
