name: "Optical sizes"
excerpt: "Different versions of a typeface optimized for use at specific sizes or size ranges."
related_lessons: "choosing_typefaces_that_have_optical_sizes"
related_lessons: "choosing_reliable_typefaces"
related_lessons: "exploring_typefaces_with_multiple_weights_or_grades"
related_lessons: "introducing_variable_fonts"
