name: "Casual axis (CASL)"
excerpt: "An axis found in some variable fonts. Along this axis, letterforms adjust from a more serious style to a more casual style."
related_lessons: "INSERT_RELATED_LESSONS_AS_MANY_AS_NEEDED"