name: "Viaoda Libre"
designer: "Gydient, Vietanh Nguyen"
license: "OFL"
category: "DISPLAY"
date_added: "2019-11-05"
fonts {
  name: "Viaoda Libre"
  style: "normal"
  weight: 400
  filename: "ViaodaLibre-Regular.ttf"
  post_script_name: "ViaodaLibre-Regular"
  full_name: "Viaoda Libre Regular"
  copyright: "Copyright 2020 The Viaodalibre Project Authors (https://github.com/bettergui/ViaodaLibre)"
}
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
