name: "Making the details matter"
authors: "Darrell Penta"
reviewers: "Cassidy Curtis"
reviewers: "Minjoo Ham"
reviewers: "Min-Young Kim"
reviewers: "SeHee Lee"
topics: "hangeul"
topics: "type_history"
prev_lessons: "designing_for_learnability"
next_lessons: "an_alphabet_for_reading_and_writing"
related_terms: "alphabet"
related_terms: "letters"
related_terms: "script_writing_system"
excerpt: "Part 3 in our in-depth look at the creation of Hangeul, the Korean alphabet."
