name: "Bonheur Royale"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-08-06"
fonts {
  name: "Bonheur Royale"
  style: "normal"
  weight: 400
  filename: "BonheurRoyale-Regular.ttf"
  post_script_name: "BonheurRoyale-Regular"
  full_name: "Bonheur Royale Regular"
  copyright: "Copyright 2005-2021 The Bonheur Royale Project Authors (https://github.com/googlefonts/bonheur-royale)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
