name: "Implementing OpenType features on the web"
authors: "Elliot Jay Stocks"
reviewers: "Bram Stein"
reviewers: "Doug Wilson"
reviewers: "Gerry Leonidas"
reviewers: "Jessica Hische"
reviewers: "Laurence Penney"
reviewers: "Rosalie Wagner"
topics: "open_type"
topics: "web_fonts"
prev_lessons: "introducing_alternate_glyphs"
prev_lessons: "open_type_features_in_practice"
prev_lessons: "using_web_fonts"
next_lessons: "loading_variable_fonts_on_the_web"
related_terms: "open_type"
excerpt: "Once we’re ready to add OpenType features to our web typography, implementing them via CSS is a relatively straightforward affair."
