name: "Didact Gothic"
designer: "Daniel Johnson, Cyreal"
license: "OFL"
category: "SANS_SERIF"
date_added: "2011-05-04"
fonts {
  name: "Didact Gothic"
  style: "normal"
  weight: 400
  filename: "DidactGothic-Regular.ttf"
  post_script_name: "DidactGothic-Regular"
  full_name: "Didact Gothic Regular"
  copyright: "Copyright 2016 The Didact Gothic Project Authors (il.basso.buffo@gmail.com)"
}
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "greek"
subsets: "greek-ext"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
