name: "Nova Mono"
designer: "Wojciech Kalinowski"
license: "OFL"
category: "MONOSPACE"
date_added: "2011-03-23"
fonts {
  name: "Nova Mono"
  style: "normal"
  weight: 400
  filename: "NovaMono.ttf"
  post_script_name: "NovaMono"
  full_name: "NovaMono"
  copyright: "Copyright (c) 2011, Wojciech \'wmk69\' Kalinowski (wmk69@o2.pl)"
}
subsets: "menu"
subsets: "greek"
subsets: "latin"
subsets: "latin-ext"
classifications: "DISPLAY"
classifications: "MONOSPACE"
