name: "Bold"
excerpt: "A common weight of a typeface—one that’s heavier than a Regular, but not as heavy as an Extra Bold or Black."
related_lessons: "introducing_weights_styles"
related_lessons: "exploring_typefaces_with_multiple_weights_or_grades"
related_lessons: "introducing_variable_fonts"
