name: "Designing with variable fonts in desktop apps"
authors: "Elliot Jay Stocks"
topics: "variable_fonts"
prev_lessons: "breaking_the_rules"
prev_lessons: "introducing_variable_fonts"
next_lessons: "using_web_fonts"
next_lessons: "styling_type_on_the_web_with_variable_fonts"
related_terms: "variable_fonts"
related_terms: "weight"
related_terms: "style"
excerpt: "Most desktop design apps’ implementation of variable fonts is fairly consistent, even across different developers."
