name: "Syllabics"
lessons: "an_introduction_to_syllabics_typography"
lessons: "algonquian_syllabics"
lessons: "inuktut_syllabics"
lessons: "dene_syllabics"
lessons: "dakelh_carrier_syllabics"
excerpt: "The Canadian Syllabics (often referred to simply as the “Syllabics”) is a writing system used by many different Indigenous language communities throughout Canada. The Syllabics are unique in how they represent written language, and many communities have local requirements and preferences in how their Syllabics should appear and function as text. This module presents both an overview of Syllabics typography to provide an overview of general principles used by all communities, as well as specific recommendations to address the local typographic and orthographic requirements and preferences of specific language communities."
