name: "Grade"
excerpt: "An attempt to keep type appearing consistent across different media, or in certain contexts."
related_lessons: "exploring_typefaces_with_multiple_weights_or_grades"
related_lessons: "choosing_typefaces_that_have_optical_sizes"
