id: "aii_Hatr"
language: "aii"
script: "Hatr"
name: "Assyrian Neo-Aramaic, Hatran"
sample_text {
  masthead_full: "𐣪𐣫𐣡𐣣"
  masthead_partial: "𐣭𐣴"
  styles: "𐣬𐣭 𐣮𐣡𐣡 𐣬𐣥𐣣𐣩𐣵𐣠 𐣡𐣠𐣩𐣲𐣣𐣠 𐣴𐣣𐣴𐣭𐣩𐣠 𐣫𐣪𐣫𐣤 𐣤𐣣𐣬𐣠 𐣣𐣪"
  tester: "𐣬𐣭 𐣮𐣡𐣡 𐣰𐣫𐣨𐣠 𐣣𐣫𐣠 𐣬𐣩𐣲𐣣𐣵𐣠 𐣥𐣬𐣮𐣫𐣩𐣵𐣠 𐣣𐣦𐣣𐣲𐣠 𐣠𐣭𐣴𐣩𐣠 𐣩𐣡𐣣𐣯𐣭𐣠 𐣫𐣯𐣡𐣣𐣥𐣩𐣵𐣠 𐣡"
  poster_sm: "𐣬𐣭 𐣮𐣡𐣡 𐣠𐣭𐣭"
  poster_md: "𐣬𐣭 𐣮𐣡𐣡"
  poster_lg: "𐣡𐣣𐣭𐣴𐣠"
  specimen_48: "𐣥𐣬𐣭 𐣮𐣡𐣡 𐣣𐣠𐣵𐣣𐣥𐣵𐣠 𐣤𐣣𐣬𐣠 𐣲𐣡𐣥𐣫𐣭𐣠 𐣣𐣤𐣩𐣣𐣠 𐣯𐣬 𐣠𐣬𐣥𐣵𐣠 𐣬𐣧𐣩𐣣𐣠 𐣫"
  specimen_36: "𐣪𐣫 𐣡𐣣𐣭𐣴𐣠 𐣡𐣣𐣩𐣫𐣤 𐣧𐣠𐣣𐣠 𐣥𐣡𐣣𐣡𐣣 𐣢𐣥 𐣠𐣩𐣲𐣣𐣠 𐣥𐣦𐣣𐣲𐣠. 𐣥𐣰𐣩𐣴𐣩𐣫𐣤 𐣩𐣤𐣡𐣠 𐣤𐣥𐣭𐣠 𐣥𐣠𐣭𐣩𐣵. 𐣡𐣥𐣣 𐣣𐣠𐣤𐣠 𐣢𐣴𐣲𐣵𐣩 𐣯𐣫 𐣠𐣧𐣣𐣭𐣠 𐣢𐣣𐣢 𐣤𐣥𐣩𐣠 𐣡𐣧𐣣 𐣣𐣥𐣧𐣠 𐣣𐣠𐣧𐣭𐣥𐣵𐣠."
  specimen_32: "𐣪𐣫 𐣠𐣭𐣴𐣠 𐣩𐣫𐣤 𐣡𐣣𐣡𐣣 𐣲𐣬 𐣲𐣠𐣭𐣥𐣭 𐣥𐣢𐣣𐣢 𐣰𐣠𐣴 𐣭𐣨𐣩𐣣𐣠 𐣡𐣩𐣣 𐣲𐣠𐣭𐣥𐣭 𐣣𐣫𐣠 𐣬𐣵𐣥𐣵𐣠 𐣣𐣰𐣥𐣣𐣴𐣥𐣭𐣩𐣠 𐣡𐣫𐣩𐣤𐣩. 𐣥𐣪𐣫 𐣠𐣭𐣴𐣠 𐣢𐣣𐣢 𐣰𐣩𐣴𐣩 𐣭𐣨𐣩𐣣𐣠 𐣡𐣣𐣡𐣣 𐣲𐣬 𐣪𐣫 𐣰𐣥𐣣𐣴𐣥𐣭𐣩𐣠 𐣣𐣴𐣬𐣨𐣵𐣠 𐣣𐣴𐣣𐣯𐣵 𐣣𐣠𐣤𐣠 𐣡𐣥𐣣𐣲𐣠."
  specimen_21: "𐣪𐣫 𐣧𐣣 𐣠𐣩𐣵𐣫𐣤 𐣤𐣲𐣥𐣵𐣠 𐣣𐣰𐣠𐣴 𐣰𐣥𐣣𐣯𐣩𐣠 𐣡𐣩𐣣 𐣧𐣣 𐣡𐣩𐣵 𐣣𐣩𐣭𐣠 𐣲𐣠 𐣯𐣡𐣣𐣥𐣩𐣵𐣠 𐣫𐣠 𐣠𐣭𐣴𐣩𐣠 𐣣𐣰𐣩𐣴𐣩 𐣥𐣩𐣣𐣠 𐣣𐣣𐣲𐣡𐣫 𐣣𐣦𐣣𐣲𐣠 𐣴𐣣𐣴𐣭𐣩𐣠 𐣣𐣭𐣨𐣩𐣣𐣭𐣠 𐣡𐣩𐣣 𐣲𐣭𐣥𐣭𐣠 𐣴𐣵𐣮𐣩𐣠 𐣩𐣭 𐣡𐣩𐣣 𐣲𐣠𐣭𐣥𐣭.\n𐣢𐣣𐣢 𐣤𐣪 𐣧𐣣 𐣫𐣠 𐣰𐣠𐣴 𐣣𐣡𐣩𐣲𐣠 𐣩𐣭 𐣬𐣥𐣵𐣡𐣠 𐣢𐣥 𐣡𐣩𐣵 𐣠𐣮𐣩𐣣𐣠 𐣩𐣭 𐣨𐣣𐣩𐣣𐣠 𐣬𐣭 𐣠𐣵𐣣𐣠 𐣣𐣫𐣠 𐣲𐣠𐣭𐣥𐣭.\n𐣪𐣫 𐣧𐣣 𐣠𐣩𐣫𐣤 𐣡𐣣𐣡𐣣 𐣲𐣬 𐣡𐣩𐣵 𐣣𐣩𐣭𐣠 𐣧𐣠𐣣𐣠 𐣥𐣫𐣠 𐣬𐣵𐣢𐣭𐣩𐣭𐣠 𐣢𐣥 𐣲𐣨𐣩𐣵𐣠 𐣣𐣤𐣲𐣥𐣵𐣠 𐣥𐣢𐣡𐣥𐣩𐣵𐣠 𐣥𐣪𐣫 𐣢𐣥𐣭𐣧𐣠 𐣣𐣣𐣲𐣥𐣫𐣤.\n𐣢𐣣𐣢 𐣫𐣠 𐣯𐣥𐣣𐣩 𐣢𐣥 𐣧𐣩𐣠 𐣣𐣩𐣫𐣭𐣩𐣠 𐣣𐣧𐣣 𐣰𐣣𐣮𐣥𐣰𐣠 𐣩𐣭 𐣡𐣩𐣵𐣠 𐣩𐣭 𐣠𐣢𐣣𐣩𐣵𐣠 𐣩𐣭 𐣠𐣩𐣲𐣣𐣠 𐣩𐣭 𐣴𐣬𐣠 𐣨𐣡𐣠 𐣬𐣴𐣬𐣤𐣥𐣵𐣠. 𐣪𐣫 𐣧𐣣 𐣰𐣣𐣮𐣥𐣰𐣠 𐣠𐣩𐣵𐣫𐣤 𐣤𐣲𐣥𐣵𐣠 𐣣𐣰𐣠𐣴 𐣭𐣨𐣩𐣣𐣠 𐣡𐣩𐣣 𐣲𐣠𐣭𐣥𐣭 𐣣𐣣𐣲𐣥𐣡𐣫 𐣤𐣣𐣧𐣠 𐣱𐣰𐣧𐣩𐣵𐣠."
  specimen_16: "𐣪𐣫 𐣧𐣣 𐣠𐣩𐣵𐣫𐣤 𐣤𐣲𐣥𐣵𐣠 𐣣𐣵𐣧𐣬𐣭𐣵𐣠 𐣥𐣣𐣠𐣭𐣩𐣵 𐣥𐣵𐣥𐣣𐣩𐣵𐣠. 𐣠𐣤𐣠 𐣤𐣲𐣥𐣵𐣠 𐣡𐣧𐣡𐣴𐣩𐣫𐣠 𐣤𐣲𐣥𐣵𐣠 𐣣𐣴𐣧𐣫𐣰𐣵𐣠 𐣣𐣵𐣥𐣣𐣩𐣵𐣠 𐣩𐣭 𐣤𐣩𐣬𐣭𐣥𐣵𐣠 𐣥𐣧𐣠𐣣𐣥𐣵𐣠 𐣡𐣭𐣥𐣰𐣴𐣠 𐣩𐣭 𐣯𐣬 𐣢𐣥 𐣴𐣥𐣵𐣰𐣥𐣵𐣠 𐣯𐣬 𐣠𐣧𐣣𐣭𐣠.\n𐣪𐣫 𐣧𐣣 𐣠𐣩𐣵𐣫𐣤 𐣤𐣲𐣥𐣵𐣠 𐣣𐣣𐣯𐣩𐣭𐣠 𐣥𐣤𐣬𐣦𐣬𐣵𐣠. 𐣠𐣤𐣠 𐣧𐣠𐣣𐣥𐣵𐣠 𐣡𐣧𐣡𐣴𐣩𐣫𐣠 𐣧𐣠𐣣𐣥𐣵𐣠 𐣣𐣣𐣯𐣩𐣭𐣠 𐣣𐣫𐣠 𐣥𐣣𐣵𐣠 𐣣𐣢𐣥𐣩 𐣬𐣭 𐣤𐣪 𐣠𐣭𐣴𐣠 𐣥𐣨𐣯𐣥𐣩𐣠 𐣡𐣵𐣣 𐣥𐣲𐣡𐣫𐣵𐣠 𐣬𐣣𐣯𐣭𐣥𐣵𐣠 𐣡𐣪𐣫 𐣠𐣥𐣣𐣧𐣠 𐣣𐣤𐣥𐣩𐣠 𐣣𐣫𐣠 𐣲𐣩𐣣𐣠 𐣣𐣵𐣧𐣥𐣡𐣠.\n𐣪𐣫 𐣧𐣣 𐣰𐣣𐣮𐣥𐣰𐣠 𐣠𐣩𐣪 𐣧𐣣 𐣤𐣣𐣬𐣠 𐣢𐣥 𐣴𐣥𐣵𐣰𐣥𐣵𐣠 𐣠𐣩𐣵𐣫𐣤 𐣤𐣲𐣥𐣵𐣠 𐣫𐣧𐣵𐣣𐣢𐣬𐣯𐣥𐣵𐣠 𐣴𐣥𐣵𐣰𐣵𐣠 𐣢𐣥 𐣵𐣬𐣬𐣵𐣠 𐣡𐣠𐣥𐣣𐣧𐣠 𐣯𐣡𐣣𐣥𐣵𐣠 𐣠𐣵𐣣𐣩𐣵𐣠 𐣥𐣤𐣩𐣣𐣵𐣠 𐣵𐣡𐣫𐣩𐣵𐣠. 𐣥𐣪𐣫 𐣧𐣣 𐣠𐣩𐣪 𐣬𐣡𐣥𐣯𐣠 𐣣𐣠𐣵𐣣𐣠 𐣠𐣩𐣵𐣫𐣤 𐣤𐣲𐣥𐣵𐣠 𐣫𐣤𐣩𐣣𐣵𐣠 𐣠𐣲𐣭𐣥𐣬𐣩𐣵𐣠 𐣥𐣴𐣥𐣵𐣰𐣩𐣵𐣠 𐣥𐣬𐣣𐣣𐣥𐣵𐣭𐣩𐣵𐣠 𐣣𐣥𐣲𐣠 𐣯𐣬 𐣠𐣩𐣲𐣣𐣠 𐣥𐣬𐣨𐣥𐣣𐣵𐣠 𐣰𐣣𐣮𐣥𐣰𐣩𐣵𐣠.\n𐣪𐣫 𐣧𐣣 𐣠𐣩𐣵𐣫𐣤 𐣤𐣲𐣥𐣵𐣠 𐣲𐣠 𐣬𐣭𐣩𐣧𐣵𐣠 𐣥𐣡𐣥𐣮𐣬𐣠 𐣥𐣡𐣧𐣡𐣴𐣠 𐣬𐣵𐣧𐣬𐣵𐣠 𐣮𐣯𐣵𐣠 𐣣𐣰𐣥𐣫𐣧𐣭𐣠 𐣥𐣩𐣥𐣬𐣠 𐣣𐣬𐣭𐣩𐣧𐣵𐣠 𐣡𐣰𐣥𐣣𐣯𐣭𐣠."
}
