id: "csw_Cans"
language: "csw"
script: "Cans"
name: "Swampy Cree"
population: 4900
region: "CA"
sample_text {
  masthead_full: "ᒥᓯᐌᐃ"
  masthead_partial: "ᓂᐤ"
  styles: "ᐃᑕ ᐁ ᐃᔑ ᓂᓯᑕᐎᓂᒋᑲᑌᐠ ᒥᓯᐌ ᑲ ᑕᔑᐟ ᐎᒋᔕᓂᑐᐎᓂᐠ ᑭᐡᑌᓂᑕᑯᓯᐎᓂᐠ"
  tester: "ᐁᑯ ᒪᑲ ᐁᑲ ᐁ ᐱᓯᐢᑫᓂᒋᑲᑌᐠ ᓀᐢᑕ ᐁ ᐱᑯᓂᑲᑌᑭ ᐃᓂᓂᐎ ᒥᓂᑯᐎᓯᐎᓇ ᐁ ᑲᑾᑕᑭᐃᒋᐠ ᐃᓂᓂᐗᐠ"
  poster_sm: "ᐁ ᑭᐢᑌᓂᑕᑾᐠ ᒪᑲ"
  poster_md: "ᐁᑯ ᓀᐢᑕ ᐊᓂᑭ"
  poster_lg: "ᒥᓯᐌ"
  specimen_48: "ᐁᑯ ᓀᐢᑕ ᐯᔭᑾᐣ ᐁ ᓂᓯᑐᒋᑲᑌᑭ ᐊᓂᐃ ᒥᓂᑯᐎᓯᐎᓇ ᓀᐢᑕ ᑎᐯᓂᒥᑎᓯᐎᓇ ᒪᐗᐨ ᐁ ᑭᐢᑌᓂᑕᑾᑭ"
  specimen_36: "ᓀᐢᑕ ᐁ ᑭᐢᑌᓂᑕᑾᐠ ᑭᒋ ᔑᑭᑕᓂᐗᐠ ᐅᑐᑌᒥᒥᑐᐎᓂᐠ ᑭᒋ ᐃᔑ ᑲᓇᐗᐸᒥᑐᒋᐠ ᐃᑕᐢᑲᓀᓯᐎᓇ᙮\nᒥᓯᐌ ᐊᐌᓇ ᐃᔑ ᒥᓂᑯᐎᓯᐤ ᑭᒋ ᐱᒪᑎᓯᐟ ᓀᐢᑕ ᑎᐯᓂᒥᑎᓱᐎᓂᓂᐤ ᓀᐢᑕ ᐁᑲ ᑭᒋ ᐅᒋ ᓇᓂᓴᓂᓯᐟ᙮"
  specimen_32: "ᐁ ᑭᐢᑌᓂᑕᑾᐠ ᒪᑲ ᐃᓂᓂᐎ ᒥᓂᑯᐎᓯᐎᐣ ᑭᒋ ᑲᓇᐌᓂᒋᑲᑌᐠ ᐱᒋ ᐅᓇᔓᐌᐎᓂᐠ ᒪᑲ ᑭᔕᐢᐱᐣ ᐃᓂᓂᐤ ᐁᑲ ᑲ ᐸᑭᑎᓂᐟ ᑭᒋ ᐊᔭᐢᐸᐣ ᐱᑐᐡ ᑫᑾᓂᐤ ᑫ ᑭᑐᑕᐠ ᑲᓇᑫ ᒪᒋᐨ ᑫ ᐅᒋ ᒪᔑᑕᐟ ᐅᑭᒪᐎᐎᓂᓂᐤ ᐯᔭᐠ ᑭᒋ ᐅᑭᒪᐤ ᐁ ᑎᐯᐣᒋᑫᐟ ᓀᐢᑕ ᐁ ᐸᑕᑯᓄᐌᐟ᙮"
  specimen_21: "ᐃᑕ ᐁ ᐃᔑ ᓂᓯᑕᐎᓂᒋᑲᑌᐠ ᒥᓯᐌ ᑲ ᑕᔑᐟ ᐎᒋᔕᓂᑐᐎᓂᐠ ᑭᐡᑌᓂᑕᑯᓯᐎᓂᐠ ᐁᑭ ᐃᔑ ᓂᑕᐎᑭᐟ ᓀᐢᑕ ᐊᓂᐃ ᒥᓂᑯᐎᓯᐎᓇ ᐯᔭᑾᓄᐠ ᐁ ᐃᔑ ᒥᓂᑯᐎᓯᐟ ᓀᐢᑕ ᐁᑲ ᒋᑭ ᐊᓂᐢᑫᐸᓂᓂᐠ ᐎᓇ ᐱᑯ ᑲ ᑭ ᐃᔑ ᒥᓂᑯᐎᓯᐟ ᐁᑯᑕ ᐌᒋ ᓂᐸᐎᒪᑲᐠ ᑎᐯᓂᒥᑎᓱᐎᐣ ᓀᐢᑕ ᑾᔭᐢᑭᑕᑎᓯᐎᐣ ᓀᐢᑕ ᑲᔭᒣᓂᑕᒧᐎᐣ ᐅᑕ ᐊᐢᑭᐠ᙮\nᐁᑯ ᒪᑲ ᐁᑲ ᐁ ᐱᓯᐢᑫᓂᒋᑲᑌᐠ ᓀᐢᑕ ᐁ ᐱᑯᓂᑲᑌᑭ ᐃᓂᓂᐎ ᒥᓂᑯᐎᓯᐎᓇ ᐁ ᑲᑾᑕᑭᐃᒋᐠ ᐃᓂᓂᐗᐠ ᐁ ᑭᔑᐗᐃᑯᓇᓂᐗᐠ ᓀᐢᑕ ᐁ ᐊᑎ ᓄᑾᐠ ᐊᐢᑭᐠ ᐃᓂᓂᐤ ᐁ ᐸᑭᑎᓇᒪᑯᐎᓯᐟ ᑭᒋ ᒥᓉᓂᑕᐠ ᐗᐃᑗᐟ ᐱᑯ ᑫᑾᓂᐤ ᑭᒋ ᐃᑗᐟ ᓀᐢᑕ ᐅᑕᐺᔦᓂᑕᒧᐎᐣ ᓀᐢᑕ ᐅᑎᐯᓂᒥᑎᓱᐎᐣ ᐁᑲ ᑭᒋ ᓇᓂᒋᐟ ᓀᐢᑕ ᐱᑯ ᑭᒋ ᓄᑌᐸᓂᐟ ᐁ ᑭᒋ ᐃᑡᓂᐗᐠ ᐅᑕ ᐁ ᐅᑯᒪ ᒪᐗᐨ ᑲ ᐃᔑ ᒧᐡᑌᔦᓂᑕᐠ ᐃᓂᓂᐤ᙮"
  specimen_16: "ᐃᑕ ᐁ ᐃᔑ ᓂᓯᑕᐎᓂᒋᑲᑌᐠ ᒥᓯᐌ ᑲ ᑕᔑᐟ ᐎᒋᔕᓂᑐᐎᓂᐠ ᑭᐡᑌᓂᑕᑯᓯᐎᓂᐠ ᐁᑭ ᐃᔑ ᓂᑕᐎᑭᐟ ᓀᐢᑕ ᐊᓂᐃ ᒥᓂᑯᐎᓯᐎᓇ ᐯᔭᑾᓄᐠ ᐁ ᐃᔑ ᒥᓂᑯᐎᓯᐟ ᓀᐢᑕ ᐁᑲ ᒋᑭ ᐊᓂᐢᑫᐸᓂᓂᐠ ᐎᓇ ᐱᑯ ᑲ ᑭ ᐃᔑ ᒥᓂᑯᐎᓯᐟ ᐁᑯᑕ ᐌᒋ ᓂᐸᐎᒪᑲᐠ ᑎᐯᓂᒥᑎᓱᐎᐣ ᓀᐢᑕ ᑾᔭᐢᑭᑕᑎᓯᐎᐣ ᓀᐢᑕ ᑲᔭᒣᓂᑕᒧᐎᐣ ᐅᑕ ᐊᐢᑭᐠ᙮\nᐁᑯ ᒪᑲ ᐁᑲ ᐁ ᐱᓯᐢᑫᓂᒋᑲᑌᐠ ᓀᐢᑕ ᐁ ᐱᑯᓂᑲᑌᑭ ᐃᓂᓂᐎ ᒥᓂᑯᐎᓯᐎᓇ ᐁ ᑲᑾᑕᑭᐃᒋᐠ ᐃᓂᓂᐗᐠ ᐁ ᑭᔑᐗᐃᑯᓇᓂᐗᐠ ᓀᐢᑕ ᐁ ᐊᑎ ᓄᑾᐠ ᐊᐢᑭᐠ ᐃᓂᓂᐤ ᐁ ᐸᑭᑎᓇᒪᑯᐎᓯᐟ ᑭᒋ ᒥᓉᓂᑕᐠ ᐗᐃᑗᐟ ᐱᑯ ᑫᑾᓂᐤ ᑭᒋ ᐃᑗᐟ ᓀᐢᑕ ᐅᑕᐺᔦᓂᑕᒧᐎᐣ ᓀᐢᑕ ᐅᑎᐯᓂᒥᑎᓱᐎᐣ ᐁᑲ ᑭᒋ ᓇᓂᒋᐟ ᓀᐢᑕ ᐱᑯ ᑭᒋ ᓄᑌᐸᓂᐟ ᐁ ᑭᒋ ᐃᑡᓂᐗᐠ ᐅᑕ ᐁ ᐅᑯᒪ ᒪᐗᐨ ᑲ ᐃᔑ ᒧᐡᑌᔦᓂᑕᐠ ᐃᓂᓂᐤ᙮\nᐁ ᑭᐢᑌᓂᑕᑾᐠ ᒪᑲ ᐃᓂᓂᐎ ᒥᓂᑯᐎᓯᐎᐣ ᑭᒋ ᑲᓇᐌᓂᒋᑲᑌᐠ ᐱᒋ ᐅᓇᔓᐌᐎᓂᐠ ᒪᑲ ᑭᔕᐢᐱᐣ ᐃᓂᓂᐤ ᐁᑲ ᑲ ᐸᑭᑎᓂᐟ ᑭᒋ ᐊᔭᐢᐸᐣ ᐱᑐᐡ ᑫᑾᓂᐤ ᑫ ᑭᑐᑕᐠ ᑲᓇᑫ ᒪᒋᐨ ᑫ ᐅᒋ ᒪᔑᑕᐟ ᐅᑭᒪᐎᐎᓂᓂᐤ ᐯᔭᐠ ᑭᒋ ᐅᑭᒪᐤ ᐁ ᑎᐯᐣᒋᑫᐟ ᓀᐢᑕ ᐁ ᐸᑕᑯᓄᐌᐟ᙮"
}
