id: "dar_Cyrl"
language: "dar"
script: "Cyrl"
name: "Dargwa"
autonym: "Дарган"
population: 368477
region: "RU"
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я Ё Ӏ а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я ё ӏ"
  marks: "◌̆ ◌̈"
}
