id: "nqo_Nkoo"
language: "nqo"
script: "Nkoo"
name: "N’Ko"
population: 626370
region: "GN"
sample_text {
  masthead_full: "ߞߣߐߛ"
  masthead_partial: "ߓߍ"
  styles: "ߞߣߐ߫ ߛߓߍߟߌ߫ ߞߊߡߊ߬ ߞߊ߬ ߞߐߕߐ߮ ߞߎߘߊ ߘߏ߫ ߘߊߦߟߍ߬ ߸ ߏ߬ ߞߐ߫"
  tester: "ߞߣߐ߫ ߛߓߍߟߌ߫ ߞߊߡߊ߬ ߞߊ߬ ߞߐߕߐ߮ ߞߎߘߊ ߘߏ߫ ߘߊߦߟߍ߬ ߸ ߏ߬ ߞߐ߫ ߞߊ߬ ߛߓߍߛߋ߲ ߠߎ߬ ߦߪߐ ߟߊߞߊ߬"
  poster_sm: "ߞߣߐ߫ ߛߓߍߟߌ߫ ߞߊߡߊ߬"
  poster_md: "ߞߣߐ߫ ߛߓߍߟߌ߫"
  poster_lg: "ߞߣߐ߫"
  specimen_48: "ߞߣߐ߫ ߛߓߍߟߌ߫ ߞߊߡߊ߬ ߞߊ߬ ߞߐߕߐ߮ ߞߎߘߊ ߘߏ߫ ߘߊߦߟߍ߬ ߸ ߏ߬ ߞߐ߫ ߞߊ߬ ߛߓߍߛߋ߲"
  specimen_36: "ߞߣߐ߫ ߛߓߍߟߌ߫ ߞߊߡߊ߬ ߞߊ߬ ߞߐߕߐ߮ ߞߎߘߊ ߘߏ߫ ߘߊߦߟߍ߬ ߸ ߏ߬ ߞߐ߫ ߞߊ߬ ߛߓߍߛߋ߲ ߠߎ߬ ߦߪߐ ߟߊߞߊ߬ ߞߊ߬ ߒߞߏ ߕߊ ߛߎߥߊ߲ߘߌ߫ ߸ ߞߺߵߊ߬ ߕߘߍ߬ ߓߘߊ߫ ߓߊ߲߫ ߖߊ߬ߕߋߛߌ߰ߟߴߌߓߟߏ߫ ߏ߬ ߓߊ߫ ߞߍ߫ ߸"
  specimen_32: "ߞߣߐ߫ ߛߓߍߟߌ߫ ߞߊߡߊ߬ ߞߊ߬ ߞߐߕߐ߮ ߞߎߘߊ ߘߏ߫ ߘߊߦߟߍ߬ ߸ ߏ߬ ߞߐ߫ ߞߊ߬ ߛߓߍߛߋ߲ ߠߎ߬ ߦߪߐ ߟߊߞߊ߬ ߞߊ߬ ߒߞߏ ߕߊ ߛߎߥߊ߲ߘߌ߫ ߸ ߞߺߵߊ߬ ߕߘߍ߬ ߓߘߊ߫ ߓߊ߲߫ ߖߊ߬ߕߋߛߌ߰ߟߴߌߓߟߏ߫ ߏ߬ ߓߊ߫ ߞߍ߫ ߸"
  specimen_21: "ߞߣߐ߫ ߛߓߍߟߌ߫ ߞߊߡߊ߬ ߞߊ߬ ߞߐߕߐ߮ ߞߎߘߊ ߘߏ߫ ߘߊߦߟߍ߬ ߸ ߏ߬ ߞߐ߫ ߞߊ߬ ߛߓߍߛߋ߲ ߠߎ߬ ߦߪߐ ߟߊߞߊ߬ ߞߊ߬ ߒߞߏ ߕߊ ߛߎߥߊ߲ߘߌ߫ ߸ ߞߺߵߊ߬ ߕߘߍ߬ ߓߘߊ߫ ߓߊ߲߫ ߖߊ߬ߕߋߛߌ߰ߟߴߌߓߟߏ߫ ߏ߬ ߓߊ߫ ߞߍ߫ ߸\nߞߣߐ߫ ߛߓߍߟߌ߫ ߞߊߡߊ߬ ߞߊ߬ ߞߐߕߐ߮ ߞߎߘߊ ߘߏ߫ ߘߊߦߟߍ߬ ߸ ߏ߬ ߞߐ߫ ߞߊ߬ ߛߓߍߛߋ߲ ߠߎ߬ ߦߪߐ ߟߊߞߊ߬ ߞߊ߬ ߒߞߏ ߕߊ ߛߎߥߊ߲ߘߌ߫ ߸ ߞߺߵߊ߬ ߕߘߍ߬ ߓߘߊ߫ ߓߊ߲߫ ߖߊ߬ߕߋߛߌ߰ߟߴߌߓߟߏ߫ ߏ߬ ߓߊ߫ ߞߍ߫ ߸\nߞߣߐ߫ ߛߓߍߟߌ߫ ߞߊߡߊ߬ ߞߊ߬ ߞߐߕߐ߮ ߞߎߘߊ ߘߏ߫ ߘߊߦߟߍ߬ ߸ ߏ߬ ߞߐ߫ ߞߊ߬ ߛߓߍߛߋ߲ ߠߎ߬ ߦߪߐ ߟߊߞߊ߬ ߞߊ߬ ߒߞߏ ߕߊ ߛߎߥߊ߲ߘߌ߫ ߸ ߞߺߵߊ߬ ߕߘߍ߬ ߓߘߊ߫ ߓߊ߲߫ ߖߊ߬ߕߋߛߌ߰ߟߴߌߓߟߏ߫ ߏ߬ ߓߊ߫ ߞߍ߫ ߸"
  specimen_16: "ߞߣߐ߫ ߛߓߍߟߌ߫ ߞߊߡߊ߬ ߞߊ߬ ߞߐߕߐ߮ ߞߎߘߊ ߘߏ߫ ߘߊߦߟߍ߬ ߸ ߏ߬ ߞߐ߫ ߞߊ߬ ߛߓߍߛߋ߲ ߠߎ߬ ߦߪߐ ߟߊߞߊ߬ ߞߊ߬ ߒߞߏ ߕߊ ߛߎߥߊ߲ߘߌ߫ ߸ ߞߺߵߊ߬ ߕߘߍ߬ ߓߘߊ߫ ߓߊ߲߫ ߖߊ߬ߕߋߛߌ߰ߟߴߌߓߟߏ߫ ߏ߬ ߓߊ߫ ߞߍ߫ ߸\nߞߣߐ߫ ߛߓߍߟߌ߫ ߞߊߡߊ߬ ߞߊ߬ ߞߐߕߐ߮ ߞߎߘߊ ߘߏ߫ ߘߊߦߟߍ߬ ߸ ߏ߬ ߞߐ߫ ߞߊ߬ ߛߓߍߛߋ߲ ߠߎ߬ ߦߪߐ ߟߊߞߊ߬ ߞߊ߬ ߒߞߏ ߕߊ ߛߎߥߊ߲ߘߌ߫ ߸ ߞߺߵߊ߬ ߕߘߍ߬ ߓߘߊ߫ ߓߊ߲߫ ߖߊ߬ߕߋߛߌ߰ߟߴߌߓߟߏ߫ ߏ߬ ߓߊ߫ ߞߍ߫ ߸\nߞߣߐ߫ ߛߓߍߟߌ߫ ߞߊߡߊ߬ ߞߊ߬ ߞߐߕߐ߮ ߞߎߘߊ ߘߏ߫ ߘߊߦߟߍ߬ ߸ ߏ߬ ߞߐ߫ ߞߊ߬ ߛߓߍߛߋ߲ ߠߎ߬ ߦߪߐ ߟߊߞߊ߬ ߞߊ߬ ߒߞߏ ߕߊ ߛߎߥߊ߲ߘߌ߫ ߸ ߞߺߵߊ߬ ߕߘߍ߬ ߓߘߊ߫ ߓߊ߲߫ ߖߊ߬ߕߋߛߌ߰ߟߴߌߓߟߏ߫ ߏ߬ ߓߊ߫ ߞߍ߫ ߸\nߞߣߐ߫ ߛߓߍߟߌ߫ ߞߊߡߊ߬ ߞߊ߬ ߞߐߕߐ߮ ߞߎߘߊ ߘߏ߫ ߘߊߦߟߍ߬ ߸ ߏ߬ ߞߐ߫ ߞߊ߬ ߛߓߍߛߋ߲ ߠߎ߬ ߦߪߐ ߟߊߞߊ߬ ߞߊ߬ ߒߞߏ ߕߊ ߛߎߥߊ߲ߘߌ߫ ߸ ߞߺߵߊ߬ ߕߘߍ߬ ߓߘߊ߫ ߓߊ߲߫ ߖߊ߬ߕߋߛߌ߰ߟߴߌߓߟߏ߫ ߏ߬ ߓߊ߫ ߞߍ߫ ߸\nߞߣߐ߫ ߛߓߍߟߌ߫ ߞߊߡߊ߬ ߞߊ߬ ߞߐߕߐ߮ ߞߎߘߊ ߘߏ߫ ߘߊߦߟߍ߬ ߸ ߏ߬ ߞߐ߫ ߞߊ߬ ߛߓߍߛߋ߲ ߠߎ߬ ߦߪߐ ߟߊߞߊ߬ ߞߊ߬ ߒߞߏ ߕߊ ߛߎߥߊ߲ߘߌ߫ ߸ ߞߺߵߊ߬ ߕߘߍ߬ ߓߘߊ߫ ߓߊ߲߫ ߖߊ߬ߕߋߛߌ߰ߟߴߌߓߟߏ߫ ߏ߬ ߓߊ߫ ߞߍ߫ ߸"
}
