id: "sa_Mult"
language: "sa"
script: "Mult"
name: "Sanskrit, Multani"
region: "IN"
sample_text {
  masthead_full: "𑊥𑊢𑊤𑊠"
  masthead_partial: "𑊚𑊦"
  styles: "𑊡𑊖𑊢 𑊌𑊆𑊖 𑊥𑊚𑊖𑊚𑊡𑊡𑊥𑊤𑊖𑊚𑊖𑊢𑊡𑊕𑊚 𑊀𑊙𑊢𑊦 𑊠𑊚𑊤𑊛𑊢𑊤𑊢𑊥𑊡 𑊥𑊢𑊤𑊥𑊠𑊛"
  tester: "𑊥𑊢𑊤 𑊠𑊚𑊤𑊦 𑊥𑊤𑊖𑊚𑊖𑊢𑊦 𑊥𑊠𑊖𑊛𑊚𑊚𑊦 𑊤𑊢𑊖𑊚𑊖 𑊀𑊛 𑊊, 𑊆𑊢𑊤𑊘𑊢𑊥 𑊀𑊙𑊄𑊢𑊘𑊢𑊥 𑊊 𑊥𑊠𑊚𑊦 𑊃𑊤"
  poster_sm: "𑊀𑊥𑊡𑊚 𑊀𑊟𑊈𑊥𑊕𑊡𑊚"
  poster_md: "𑊃𑊖𑊘𑊖𑊢𑊄𑊖𑊠,"
  poster_lg: "𑊥𑊢𑊤"
  specimen_48: "𑊚 𑊄𑊠𑊛 𑊌𑊚𑊚 𑊘𑊥𑊖𑊤𑊚 𑊛𑊢𑊙𑊚𑊖𑊤𑊚 𑊤𑊀 𑊙𑊢𑊡𑊖𑊚 𑊀𑊚𑊌𑊏𑊥𑊡𑊖। 𑊀𑊛 𑊊 𑊘𑊥𑊤𑊡𑊛𑊢𑊦 𑊛𑊢𑊕𑊢𑊛𑊕"
  specimen_36: "𑊤𑊙𑊚𑊀 𑊥𑊚𑊤𑊙𑊚𑊚 𑊤𑊀 𑊛𑊢𑊘𑊖𑊖𑊚𑊚 𑊠𑊣𑊄𑊙𑊄𑊢𑊕𑊠𑊣𑊣𑊚𑊈𑊚𑊄𑊢𑊡𑊕𑊚 𑊄𑊢𑊖, 𑊡𑊆𑊡𑊦 𑊢𑊥𑊐𑊢𑊡𑊚𑊡𑊡𑊛𑊑𑊦 𑊥𑊚𑊥𑊖𑊖𑊚𑊚 𑊛𑊢𑊟𑊤𑊚𑊚 𑊥𑊠𑊛𑊡𑊚𑊚 𑊛𑊢𑊡𑊆𑊢𑊦 𑊦𑊁 𑊥𑊢𑊤 𑊌𑊚𑊥𑊖।"
  specimen_32: "𑊥𑊢𑊤𑊛 𑊌𑊚𑊦, 𑊥𑊤𑊚 𑊤𑊢𑊙𑊡 𑊛𑊢𑊤𑊢𑊖𑊖𑊖𑊥𑊡 𑊄𑊥𑊡𑊛 𑊀𑊛𑊢𑊙𑊄𑊄𑊥𑊛𑊥𑊡, 𑊥𑊤𑊡𑊙𑊄𑊢𑊕𑊚 𑊘𑊡𑊖𑊤𑊚𑊚 𑊊, 𑊤𑊚𑊢𑊙𑊢𑊕𑊥𑊡 𑊊 𑊄𑊢𑊖, 𑊥𑊤𑊙𑊚𑊚 𑊚𑊥𑊛𑊄𑊥𑊕 𑊊 𑊚𑊡𑊡𑊛𑊑𑊚 𑊤𑊙𑊡𑊠𑊚𑊥𑊡 𑊥𑊠𑊊𑊖𑊥𑊡 𑊥𑊢𑊤𑊌𑊚𑊄𑊥𑊡 𑊥𑊢𑊤𑊕𑊥𑊡 𑊊 𑊄𑊢𑊖 𑊥𑊢𑊤𑊛 𑊌𑊚𑊦 𑊛𑊢𑊕𑊚 𑊥𑊠𑊚𑊖𑊚 𑊙𑊢𑊡𑊖।"
  specimen_21: "𑊚 𑊄𑊥𑊡𑊛 𑊤𑊡𑊄𑊖𑊆𑊖 𑊛𑊢𑊤𑊢𑊄𑊃 𑊊 𑊌𑊤𑊚, 𑊆𑊢𑊦, 𑊛𑊖𑊢𑊤𑊡𑊤𑊦𑊢 𑊊 𑊥𑊤𑊊𑊋𑊡 𑊦𑊥𑊖𑊄𑊥𑊛𑊚𑊌𑊏𑊥𑊡𑊖, 𑊚 𑊤𑊀 𑊄𑊥𑊡𑊛 𑊅𑊡𑊖𑊚 𑊥𑊠𑊠𑊚𑊚 𑊤𑊄𑊢𑊚𑊖𑊚 𑊄𑊛 𑊥𑊄𑊥𑊡𑊖। 𑊃𑊖𑊦𑊄𑊦𑊥𑊖𑊄𑊥𑊛𑊄𑊢𑊠𑊕𑊚 𑊤𑊢𑊙𑊡 𑊛𑊢𑊖𑊡𑊄𑊠𑊛𑊌𑊚𑊦 𑊤𑊙𑊥𑊚𑊢𑊄𑊥𑊕𑊚 𑊥𑊚𑊙𑊖𑊖।\n𑊛𑊢𑊖𑊡𑊄𑊠𑊛 𑊤𑊊𑊢𑊕𑊚 𑊊𑊖𑊚𑊡𑊦 𑊙𑊢𑊠𑊥𑊡 𑊊𑊥𑊤𑊖𑊚𑊖𑊢𑊡𑊙𑊄𑊢𑊚 𑊥𑊚𑊙𑊖𑊖। 𑊀𑊥𑊠𑊚 𑊀𑊙𑊄𑊢𑊃, 𑊥𑊤𑊡𑊚 𑊙𑊢𑊠𑊚 𑊤𑊥𑊤𑊥𑊚 𑊤𑊀 𑊥𑊄𑊥𑊡𑊖𑊚 𑊀𑊟𑊡𑊥𑊖𑊚 𑊀𑊢𑊊𑊖𑊚 𑊛𑊢𑊛𑊣𑊡𑊖𑊚 𑊤𑊀, 𑊤𑊡𑊄𑊖𑊄 𑊥𑊠𑊌𑊄 𑊊 𑊌𑊤𑊚, 𑊀𑊚𑊡𑊥𑊊 𑊥𑊦 𑊥𑊠𑊘𑊡𑊄𑊌𑊤𑊚 𑊃𑊄𑊄𑊚𑊀 𑊤𑊀 𑊥𑊤𑊡𑊚 𑊙𑊢𑊠𑊚 𑊤𑊥𑊤𑊥𑊚𑊥𑊤𑊖𑊚𑊖𑊢𑊡𑊚 𑊊 𑊛𑊢𑊤𑊢𑊖𑊡𑊖𑊠𑊛 𑊛𑊢𑊖𑊡𑊄𑊚 𑊌𑊚𑊦 𑊥𑊤𑊖𑊚𑊖𑊢𑊡𑊚 𑊙𑊢𑊡𑊖।"
  specimen_16: "𑊛𑊢𑊖𑊡𑊄𑊠𑊛 𑊠𑊚𑊖𑊤𑊡𑊟𑊤𑊡𑊄𑊖𑊡𑊦 𑊀𑊙𑊄𑊢𑊚 𑊥𑊚𑊙𑊖𑊖। 𑊥𑊠𑊤𑊡𑊤𑊙𑊚𑊚 𑊀𑊤𑊆𑊕𑊡𑊡, 𑊄𑊚𑊛𑊁 𑊥𑊚𑊊𑊢𑊠𑊙𑊡𑊠𑊚 𑊤𑊊𑊢𑊕𑊚 𑊥𑊊𑊚𑊚𑊚 𑊊 𑊀𑊘𑊚𑊛𑊢𑊘𑊚𑊢𑊗𑊚 𑊤𑊚𑊤 𑊦𑊥𑊖𑊄𑊥𑊛𑊚 𑊄𑊥𑊊𑊘𑊛 𑊌𑊚𑊦, 𑊥𑊤𑊡𑊠𑊚𑊖𑊤𑊡𑊥𑊚𑊈𑊢𑊕𑊢𑊗𑊚 𑊀𑊙𑊄𑊢𑊥𑊠𑊚 𑊀𑊢𑊦𑊥𑊡𑊖।\n𑊛𑊢𑊖𑊡𑊄𑊠𑊤 𑊌𑊚𑊦, 𑊥𑊠𑊌𑊄𑊖𑊤𑊖, 𑊥𑊠𑊌𑊄𑊥𑊢𑊄𑊥𑊡 𑊀𑊙𑊄𑊢𑊚 𑊥𑊚𑊙𑊢𑊡𑊖; 𑊀𑊥 𑊦𑊁 𑊢𑊥𑊐𑊢𑊡𑊛𑊢𑊡𑊥𑊚 𑊀𑊚𑊖𑊢𑊥𑊐𑊢𑊡𑊥𑊦𑊡𑊆 𑊚 𑊊 𑊛𑊢𑊖𑊡𑊄𑊚 𑊢𑊌𑊡𑊥𑊡 𑊥𑊚𑊈𑊐𑊚𑊥𑊚𑊥𑊙𑊚𑊚𑊢𑊛𑊠, 𑊥𑊤𑊡𑊤𑊟𑊌𑊡𑊢𑊗𑊄𑊥𑊠𑊌𑊄𑊥𑊚𑊥𑊄𑊢𑊖𑊄𑊙𑊄𑊢𑊕𑊚 𑊛𑊢𑊖𑊥𑊑𑊡, 𑊥𑊤𑊡𑊤𑊡𑊄𑊖𑊖𑊤𑊥𑊡 𑊂𑊚𑊠𑊄𑊖 {𑊥𑊢𑊤𑊚𑊆𑊕} 𑊤𑊄𑊥𑊢𑊗𑊚 𑊊 𑊥𑊚𑊥𑊘𑊙𑊚 𑊀𑊢𑊦𑊖।\n𑊄𑊢𑊡𑊦𑊢𑊕𑊚 𑊥𑊠𑊊𑊖𑊚𑊡𑊠𑊚𑊛𑊢𑊥𑊥𑊢𑊠, 𑊥𑊤𑊖𑊚𑊚 𑊊 𑊚𑊡𑊖𑊤𑊙𑊄𑊤𑊄𑊥𑊚 𑊥𑊦 𑊤𑊥𑊢𑊠𑊙𑊄𑊢𑊦 𑊛𑊢𑊖𑊡𑊄𑊥𑊠 𑊛𑊢𑊘𑊡𑊥𑊖।\n𑊀𑊥𑊡𑊚 𑊀𑊟𑊈𑊥𑊕𑊡𑊚 𑊚𑊢𑊘𑊥𑊐𑊚𑊚 𑊀𑊙𑊄𑊢𑊕𑊚 𑊥𑊤𑊖𑊚𑊖𑊢𑊡𑊕𑊚 𑊊 𑊛𑊢𑊛𑊖𑊡 𑊥𑊠𑊌𑊄𑊚𑊖𑊢𑊥𑊐𑊢𑊄𑊤𑊡𑊤𑊥𑊗𑊡𑊚 𑊊 𑊛𑊢𑊕𑊖𑊡 𑊃𑊖𑊚 𑊀𑊙𑊆𑊚𑊖𑊚 𑊛𑊢𑊖𑊡𑊄𑊠𑊛 𑊌𑊚𑊢𑊦𑊥𑊡𑊖।\n𑊀𑊥𑊡𑊚 𑊀𑊟𑊈𑊥𑊕𑊡𑊚 𑊚𑊢𑊘𑊥𑊐𑊚𑊚 𑊀𑊙𑊄𑊢𑊕𑊚 𑊥𑊤𑊖𑊚𑊖𑊢𑊡𑊕𑊚 𑊊 𑊚 𑊄𑊛𑊡𑊚𑊥𑊦, 𑊛𑊢𑊕𑊥𑊣𑊄𑊥𑊡𑊙𑊢𑊕 𑊄𑊠𑊛 𑊄𑊢𑊡𑊠𑊚𑊥𑊑𑊖𑊚 𑊃𑊖𑊘𑊢𑊄𑊄𑊢𑊡𑊚𑊥𑊑𑊚𑊢𑊗𑊚 𑊤𑊀 𑊄𑊥𑊡𑊊𑊖 𑊢𑊥𑊐𑊢𑊥𑊡 𑊤𑊢𑊆𑊥𑊡 𑊌𑊚𑊥𑊡 𑊤𑊀 𑊥𑊠𑊦𑊖𑊥𑊘𑊙𑊡𑊢𑊗𑊚 𑊀𑊚𑊡𑊗 𑊤𑊡𑊅𑊡𑊖𑊚 𑊚𑊤 𑊥𑊄𑊥𑊡𑊖।"
}
historical: true
