id: "tly_Cyrl"
language: "tly"
script: "Cyrl"
name: "Talysh, Cyrillic"
autonym: "Толыши"
population: 0
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Ј Ғ Ҹ Ҝ Һ Ә Ы а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш ј ғ ҹ ҝ һ ә ы"
  marks: "◌̆"
}
