id: "xsa_Sarb"
language: "xsa"
script: "Sarb"
name: "Sabaean"
population: 0
sample_text {
  masthead_full: "𐩡𐩢𐩺𐩲"
  masthead_partial: "𐩻𐩩"
  styles: "𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠"
  tester: "𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠"
  poster_sm: "𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠"
  poster_md: "𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠"
  poster_lg: "𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠"
  specimen_48: "𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠"
  specimen_36: "𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠"
  specimen_32: "𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠"
  specimen_21: "𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠\n𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠\n𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠\n𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠"
  specimen_16: "𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠\n𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠\n𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠\n𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠\n𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠\n𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠\n𐩡𐩢𐩺𐩲𐩻𐩩𐩽𐩪𐩷𐩧𐩬𐩽𐩫𐩨𐩧𐩽𐩰𐩺𐩦𐩬𐩽𐩨𐩬𐩺𐩽𐩥𐩠𐩥𐩻𐩧𐩽𐩥𐩦𐩤𐩧𐩽𐩢𐩧𐩩𐩬𐩠𐩬𐩽𐩹𐩩𐩺𐩦𐩡𐩻𐩬𐩽𐩫𐩡𐩥𐩩𐩬𐩽𐩡𐩬𐩭𐩡𐩺𐩠𐩥𐩽𐩣𐩷𐩧𐩩𐩥𐩣𐩥𐩠𐩧𐩠𐩽𐩨𐩲𐩻𐩩𐩧𐩽𐩥𐩨𐩽𐩱𐩡𐩣𐩤𐩠"
}
historical: true
