name: "Interactive animations with variable fonts"
authors: "Nick Sherman"
reviewers: "Laurence Penney"
reviewers: "Piper Haywood"
topics: "variable_fonts"
related_terms: "variable_fonts"
prev_lessons: "optimizing_typographic_space_with_variable_fonts"
next_lessons: "factors_that_influence_the_efficiency_of_variable_web_fonts"
excerpt: "Variable font animations can provide subtle effects for user interactions and visual semantics, or they can be used for more dramatic special effects."
