name: "Interactive animations with variable fonts"
authors: "Nick Sherman"
reviewers: "Laurence Penney"
reviewers: "Piper Haywood"
topics: "variable_fonts"
prev_lessons: "INSERT"
next_lessons: "INSERT"
related_terms: "variable_fonts"
excerpt: "INSERT"
