name: "Ruthie"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2011-12-19"
fonts {
  name: "Ruthie"
  style: "normal"
  weight: 400
  filename: "Ruthie-Regular.ttf"
  post_script_name: "Ruthie-Regular"
  full_name: "Ruthie Regular"
  copyright: "Copyright 2014 The Ruthie Project Authors (https://github.com/googlefonts/ruthie)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
