id: "njo"
name: "Ao Naga"
preferred_name: ""
autonym: ""
population: 305000
region: "IN"
script: "Latin"
exemplar_chars {
  base: "A B C E I J K L M N O P R S T U Y Z a b c e i j k l m n o p r s t u y z"
}
