name: "Drop cap"
excerpt: "A large, uppercase letter used for decoration in the opening of a piece (or section) of text, most often employed in editorial scenarios."
related_lessons: "choosing_typefaces_that_have_optical_sizes"
related_lessons: "introducing_weights_styles"
