id: "kk"
name: "Kazakh"
preferred_name: ""
autonym: "Қазақ тілі"
population: 12219390
region: "KZ"
region: "TR"
script: "Perso-Arabic"
script: "Cyrillic"
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я Ё І Ғ Қ Ң Ү Ұ Һ Ә Ө а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я ё і ғ қ ң ү ұ һ ә ө"
  auxiliary: ""
  marks: "◌̆ ◌̈"
  numerals: "  \\- ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … \' ‘ ’ \" “ ” « » ( ) \\[ \\] \\{ \\} § @ * / \\& #"
  index: "А Ә Б В Г Ғ Д Е Ё Ж З И Й К Қ Л М Н Ң О Ө П Р С Т У Ұ Ү Ф Х Һ Ц Ч Ш Щ Ъ Ы І Ь Э Ю Я"
}
