id: "nzi"
name: "Nzima"
preferred_name: ""
autonym: ""
population: 293402
region: "GH"
script: "Latin"
exemplar_chars {
  base: "A B D E Ɛ F G H I K L M N O Ɔ P R S T U V W Y Z a b d e ɛ f g h i k l m n o ɔ p r s t u v w y z"
}
