name: "YomogiFont"
designer: "Satsuyako"
license: "OFL"
category: "HANDWRITING"
date_added: "2020-12-09"
fonts {
  name: "YomogiFont"
  style: "normal"
  weight: 400
  filename: "YomogiFont-Regular.ttf"
  post_script_name: "YomogiFont-Regular"
  full_name: "YomogiFont Regular"
  copyright: "Copyright 2020 The Yomogi Font Project Authors (https://github.com/satsuyako/YomogiFont), all rights reserved."
}
subsets: "chinese-simplified"
subsets: "chinese-traditional"
subsets: "cyrillic"
subsets: "japanese"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
