name: "Itim"
designer: "Cadson Demak"
license: "OFL"
category: "HANDWRITING"
date_added: "2015-07-01"
fonts {
  name: "Itim"
  style: "normal"
  weight: 400
  filename: "Itim-Regular.ttf"
  post_script_name: "Itim-Regular"
  full_name: "Itim"
  copyright: "Copyright (c) 2015, Cadson Demak (info@cadsondemak.com), Copyright (c) 2014, Pablo Impallari (www.impallari.com|impallari@gmail.com)"
}
subsets: "menu"
subsets: "latin"
subsets: "latin-ext"
subsets: "thai"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
