name: "Avoiding widows & orphans"
authors: "Elliot Jay Stocks"
reviewers: "Doug Wilson"
reviewers: "Frank Rausch"
reviewers: "Jessica Hische"
reviewers: "Mark Boulton"
reviewers: "Richard Rutter"
reviewers: "Trent Walton"
topics: "essentials"
topics: "systems"
prev_lessons: "manual_kerning_is_rarely_required"
next_lessons: "working_with_hanging_punctuation"
related_terms: "widows_orphans"
excerpt: "Like so many things in typography, avoiding widows and orphans means breaking the rules a little."
