name: "Sitara"
designer: "Neelakash Kshetrimayum"
license: "OFL"
category: "SERIF"
date_added: "2015-06-10"
fonts {
  name: "Sitara"
  style: "normal"
  weight: 400
  filename: "Sitara-Regular.ttf"
  post_script_name: "Sitara-Regular"
  full_name: "Sitara"
  copyright: "Copyright (c) 2014, Neelakash Kshetrimayum (github.com/Neelakash/sitara). Copyright 2013, Google Corporation."
}
fonts {
  name: "Sitara"
  style: "italic"
  weight: 400
  filename: "Sitara-Italic.ttf"
  post_script_name: "Sitara-Italic"
  full_name: "Sitara Italic"
  copyright: "Copyright (c) 2014, Neelakash Kshetrimayum (github.com/Neelakash/sitara). Copyright 2013, Google Corporation."
}
fonts {
  name: "Sitara"
  style: "normal"
  weight: 700
  filename: "Sitara-Bold.ttf"
  post_script_name: "Sitara-Bold"
  full_name: "Sitara Bold"
  copyright: "Copyright (c) 2014, Neelakash Kshetrimayum (github.com/Neelakash/sitara). Copyright 2013, Google Corporation."
}
fonts {
  name: "Sitara"
  style: "italic"
  weight: 700
  filename: "Sitara-BoldItalic.ttf"
  post_script_name: "Sitara-BoldItalic"
  full_name: "Sitara Bold Italic"
  copyright: "Copyright (c) 2014, Neelakash Kshetrimayum (github.com/Neelakash/sitara). Copyright 2013, Google Corporation."
}
subsets: "menu"
subsets: "devanagari"
subsets: "latin"
subsets: "latin-ext"
languages: "anp_Deva"
languages: "awa_Deva"
languages: "bap_Deva"
languages: "bfy_Deva"
languages: "bgc_Deva"
languages: "bhb_Deva"
languages: "bhi_Deva"
languages: "bho_Deva"
languages: "bjj_Deva"
languages: "bra_Deva"
languages: "brx_Deva"
languages: "btv_Deva"
languages: "byh_Deva"
languages: "chx_Deva"
languages: "dhi_Deva"
languages: "dhw_Deva"
languages: "doi_Deva"
languages: "dty_Deva"
languages: "gbm_Deva"
languages: "ggn_Deva"
languages: "gju_Deva"
languages: "gom_Deva"
languages: "gon_Deva"
languages: "gvr_Deva"
languages: "hi_Deva"
languages: "hif_Deva"
languages: "hne_Deva"
languages: "hoc_Deva"
languages: "hoj_Deva"
languages: "jml_Deva"
languages: "kfr_Deva"
languages: "kfy_Deva"
languages: "kgj_Deva"
languages: "khn_Deva"
languages: "khr_Deva"
languages: "kok_Deva"
languages: "kru_Deva"
languages: "ks_Deva"
languages: "lhm_Deva"
languages: "lif_Deva"
languages: "mag_Deva"
languages: "mai_Deva"
languages: "mgp_Deva"
languages: "mr_Deva"
languages: "mrd_Deva"
languages: "mtr_Deva"
languages: "mwr_Deva"
languages: "ne_Deva"
languages: "new_Deva"
languages: "nnp_Deva"
languages: "noe_Deva"
languages: "pi_Deva"
languages: "rab_Deva"
languages: "raj_Deva"
languages: "rjs_Deva"
languages: "sa_Deva"
languages: "sat_Deva"
languages: "sck_Deva"
languages: "sd_Deva"
languages: "srx_Deva"
languages: "swv_Deva"
languages: "taj_Deva"
languages: "tdg_Deva"
languages: "tdh_Deva"
languages: "thf_Deva"
languages: "thl_Deva"
languages: "thq_Deva"
languages: "thr_Deva"
languages: "ths_Deva"
languages: "tkt_Deva"
languages: "tsf_Deva"
languages: "unr_Deva"
languages: "unx_Deva"
languages: "wbr_Deva"
languages: "wtm_Deva"
languages: "xnr_Deva"
languages: "xsr_Deva"
languages: "ybh_Deva"
