ui_layout {
  layout_id: "expressive"
  ui_group_id: "Feeling"
  ui_group_id: "Appearance"
  ui_group_id: "Calligraphy"
  ui_group_id: "Serif"
  ui_group_id: "Sans Serif"
  ui_group_id: "Technology"
  ui_group_id: "Seasonal"
}

id_to_group {
  key: "Seasonal"
  value: {
    group_icon: "Interests"
    group_label: "Seasonal"
    group_member_id: "Halloween"
    group_member_id: "Diwali"
  }
}

id_to_group {
  key: "Feeling"
  value: {
    group_icon: "Sentiment_satisfied"
    group_label: "Feeling"
    group_member_id: "Business"
    group_member_id: "Calm"
    group_member_id: "Cute"
    group_member_id: "Playful"
    group_member_id: "Fancy"
    group_member_id: "Stiff"
    group_member_id: "Vintage"
    group_member_id: "Happy"
    group_member_id: "Futuristic"
    group_member_id: "Excited"
    group_member_id: "Rugged"
    group_member_id: "Childlike"
    group_member_id: "Loud"
    group_member_id: "Artistic"
    group_member_id: "Sophisticated"
    group_member_id: "Awkward"
    group_member_id: "Active"
    group_member_id: "Innovative"
  }
}

id_to_group {
  key: "Appearance"
  value: {
    group_icon: "apparel"
    group_label: "Appearance"
    group_member_id: "Brush"
    group_member_id: "Techno"
    group_member_id: "Distressed"
    group_member_id: "Wacky"
    group_member_id: "Woodtype"
    group_member_id: "Blobby"
    group_member_id: "Monospace"
    group_member_id: "Blackletter"
    group_member_id: "Stencil"
    group_member_id: "Inline"
    group_member_id: "Medieval"
    group_member_id: "Art Deco"
    group_member_id: "Pixel"
    group_member_id: "Shaded"
    group_member_id: "Art Nouveau"
    group_member_id: "Tuscan"
    group_member_id: "Not text"
  }
}

id_to_group {
  key: "Serif"
  value: {
    group_icon: "serif"
    group_label: "Serif"
    group_member_id: "Serif All"
    group_member_id: "Serif Transitional"
    group_member_id: "Slab"
    group_member_id: "Serif Old Style"
    group_member_id: "Serif Modern"
    group_member_id: "Serif Humanist"
    group_member_id: "Serif Scotch"
    group_member_id: "Serif Fatface"
    group_member_id: "Serif Didone"
  }
}

id_to_group {
  key: "Sans Serif"
  value: {
    group_icon: "font_download"
    group_label: "Sans Serif"
    group_member_id: "Sans All"
    group_member_id: "Sans Humanist"
    group_member_id: "Sans Geometric"
    group_member_id: "Sans Neo Grotesque"
    group_member_id: "Sans Rounded"
    group_member_id: "Sans Superellipse"
    group_member_id: "Sans Grotesque"
    group_member_id: "Sans Glyphic"
  }
}

id_to_group {
  key: "Calligraphy"
  value: {
    group_icon: "script"
    group_label: "Calligraphy"
    group_member_id: "Calligraphy All"
    group_member_id: "Handwritten"
    group_member_id: "Formal"
    group_member_id: "Informal"
    group_member_id: "Upright"
  }
}

id_to_group {
  key: "Technology"
  value: {
    group_icon: "custom_typography"
    group_label: "Technology"
    group_member_id: "Variable"
    group_member_id: "Color"
  }
}

id_to_group_member {
  key: "Business"
  value: {
    tag_names: "/Expressive/Business"
    display_name: "Business"
    display_font: "Roboto"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Calm"
  value: {
    tag_names: "/Expressive/Calm"
    display_name: "Calm"
    display_font: "Poppins"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Cute"
  value: {
    tag_names: "/Expressive/Cute"
    display_name: "Cute"
    display_font: "Caveat"
    display_font_size: "20px"
  }
}

id_to_group_member {
  key: "Playful"
  value: {
    tag_names: "/Expressive/Playful"
    display_name: "Playful"
    display_font: "DynaPuff"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Fancy"
  value: {
    tag_names: "/Expressive/Fancy"
    display_name: "Fancy"
    display_font: "Great Vibes"
    display_font_size: "19px"
  }
}

id_to_group_member {
  key: "Stiff"
  value: {
    tag_names: "/Expressive/Stiff"
    display_name: "Stiff"
    display_font: "Iceberg"
    display_font_size: "15px"
  }
}

id_to_group_member {
  key: "Vintage"
  value: {
    tag_names: "/Expressive/Vintage"
    display_name: "Vintage"
    display_font: "Pirata One"
    display_font_size: "17px"
  }
}

id_to_group_member {
  key: "Happy"
  value: {
    tag_names: "/Expressive/Happy"
    display_name: "Happy"
    display_font: "Lobster"
    display_font_size: "15px"
  }
}

id_to_group_member {
  key: "Futuristic"
  value: {
    tag_names: "/Expressive/Futuristic"
    display_name: "Futuristic"
    display_font: "Audiowide"
    display_font_size: "13px"
  }
}

id_to_group_member {
  key: "Excited"
  value: {
    tag_names: "/Expressive/Excited"
    display_name: "Excited"
    display_font: "Kablammo"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Rugged"
  value: {
    tag_names: "/Expressive/Rugged"
    display_name: "Rugged"
    display_font: "Cabin Sketch"
    display_font_size: "15px"
  }
}

id_to_group_member {
  key: "Childlike"
  value: {
    tag_names: "/Expressive/Childlike"
    display_name: "Childlike"
    display_font: "Fuzzy Bubbles"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Loud"
  value: {
    tag_names: "/Expressive/Loud"
    display_name: "Loud"
    display_font: "Limelight"
    display_font_size: "15px"
  }
}

id_to_group_member {
  key: "Artistic"
  value: {
    tag_names: "/Expressive/Artistic"
    display_name: "Artistic"
    display_font: "Leckerli One"
    display_font_size: "17px"
  }
}

id_to_group_member {
  key: "Sophisticated"
  value: {
    tag_names: "/Expressive/Sophisticated"
    display_name: "Sophisticated"
    display_font: "Quintessential"
    display_font_size: "15px"
  }
}

id_to_group_member {
  key: "Awkward"
  value: {
    tag_names: "/Expressive/Awkward"
    display_name: "Awkward"
    display_font: "Barriecito"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Active"
  value: {
    tag_names: "/Expressive/Active"
    display_name: "Active"
    display_font: "Racing Sans One"
    display_font_size: "16px"
  }
}

id_to_group_member {
  key: "Innovative"
  value: {
    tag_names: "/Expressive/Innovative"
    display_name: "Innovative"
    display_font: "Rubik Glitch"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Brush"
  value: {
    tag_names: "/Theme/Brush"
    display_name: "Marker"
    display_font: "Kavivanar"
    display_font_size: "15px"
  }
}

id_to_group_member {
  key: "Techno"
  value: {
    tag_names: "/Theme/Techno"
    display_name: "Techno"
    display_font: "Audiowide"
    display_font_size: "15px"
  }
}

id_to_group_member {
  key: "Distressed"
  value: {
    tag_names: "/Theme/Distressed"
    display_name: "Distressed"
    display_font: "Averia Libre"
    display_font_size: "16px"
  }
}

id_to_group_member {
  key: "Wacky"
  value: {
    tag_names: "/Theme/Wacky"
    display_name: "Wacky"
    display_font: "Kablammo"
    display_font_size: "15px"
  }
}

id_to_group_member {
  key: "Woodtype"
  value: {
    tag_names: "/Theme/Woodtype"
    display_name: "Wood type"
    display_font: "Rye"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Blobby"
  value: {
    tag_names: "/Theme/Blobby"
    display_name: "Blobby"
    display_font: "Chicle"
    display_font_size: "17px"
  }
}

id_to_group_member {
  key: "Monospace"
  value: {
    tag_names: "/Monospace/Monospace"
    display_name: "Monospaced"
    display_font: "Roboto Mono"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Blackletter"
  value: {
    tag_names: "/Theme/Blackletter"
    display_name: "Blackletter"
    display_font: "New Rocker"
    display_font_size: "16px"
  }
}

id_to_group_member {
  key: "Stencil"
  value: {
    tag_names: "/Theme/Stencil"
    display_name: "Stencil"
    display_font: "Black Ops One"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Inline"
  value: {
    tag_names: "/Theme/Inline"
    display_name: "Inline"
    display_font: "Train One"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Medieval"
  value: {
    tag_names: "/Theme/Medieval"
    display_name: "Medieval"
    display_font: "Metamorphous"
    display_font_size: "13px"
  }
}

id_to_group_member {
  key: "Art Deco"
  value: {
    tag_names: "/Theme/Art Deco"
    display_name: "Art Deco"
    display_font: "Ribeye"
    display_font_size: "15px"
  }
}

id_to_group_member {
  key: "Pixel"
  value: {
    tag_names: "/Theme/Pixel"
    display_name: "Pixel"
    display_font: "Pixelify Sans"
    display_font_size: "17px"
  }
}

id_to_group_member {
  key: "Shaded"
  value: {
    tag_names: "/Theme/Shaded"
    display_name: "Shaded"
    display_font: "Vast Shadow"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Art Nouveau"
  value: {
    tag_names: "/Theme/Art Nouveau"
    display_name: "Art Nouveau"
    display_font: "Amarante"
    display_font_size: "15px"
  }
}

id_to_group_member {
  key: "Tuscan"
  value: {
    tag_names: "/Theme/Tuscan"
    display_name: "Tuscan"
    display_font: "Sancreek"
    display_font_size: "15px"
  }
}

id_to_group_member {
  key: "Not text"
  value: {
    tag_names: "/Not text/Symbols"
    display_name: "Not text"
    display_font: "Noto Music"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Serif All"
  value: {
    tag_names: "/Serif/*"
    tag_names: "/Slab/*"
    display_name: "All"
    display_font: "Google Sans Text"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Serif Transitional"
  value: {
    tag_names: "/Serif/Transitional"
    display_name: "Transitional"
    display_font: "Tiro Bangla"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Slab"
  value: {
    tag_names: "/Slab/*"
    display_name: "Slab"
    display_font: "Roboto Slab"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Serif Old Style"
  value: {
    tag_names: "/Serif/Old Style Garalde"
    display_name: "Old Style"
    display_font: "EB Garamond"
    display_font_size: "16px"
  }
}

id_to_group_member {
  key: "Serif Modern"
  value: {
    tag_names: "/Serif/Modern"
    display_name: "Modern"
    display_font: "Playfair Display"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Serif Humanist"
  value: {
    tag_names: "/Serif/Humanist Venetian"
    display_name: "Humanist"
    display_font: "Rakkas"
    display_font_size: "16px"
  }
}

id_to_group_member {
  key: "Serif Scotch"
  value: {
    tag_names: "/Serif/Scotch"
    display_name: "Scotch"
    display_font: "STIX Two Text"
    display_font_size: "16px"
  }
}

id_to_group_member {
  key: "Serif Fatface"
  value: {
    tag_names: "/Serif/Fat Face"
    display_name: "Fatface"
    display_font: "Gravitas One"
    display_font_size: "13px"
  }
}

id_to_group_member {
  key: "Serif Didone"
  value: {
    tag_names: "/Serif/Didone"
    display_name: "Didone"
    display_font: "Vidaloka"
    display_font_size: "15px"
  }
}

id_to_group_member {
  key: "Sans All"
  value: {
    tag_names: "/Sans/*"
    display_name: "All"
    display_font: "Google Sans Text"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Sans Humanist"
  value: {
    tag_names: "/Sans/Humanist"
    display_name: "Humanist"
    display_font: "Merriweather Sans"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Sans Geometric"
  value: {
    tag_names: "/Sans/Geometric"
    display_name: "Geometric"
    display_font: "Poppins"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Sans Neo Grotesque"
  value: {
    tag_names: "/Sans/Neo Grotesque"
    display_name: "Neo Grotesque"
    display_font: "Roboto Flex"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Sans Rounded"
  value: {
    tag_names: "/Sans/Rounded"
    display_name: "Rounded"
    display_font: "Nunito"
    display_font_size: "15px"
  }
}

id_to_group_member {
  key: "Sans Superellipse"
  value: {
    tag_names: "/Sans/Superellipse"
    display_name: "Superellipse"
    display_font: "Oxanium"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Sans Grotesque"
  value: {
    tag_names: "/Sans/Grotesque"
    display_name: "Grotesque"
    display_font: "Oswald"
    display_font_size: "15px"
  }
}

id_to_group_member {
  key: "Sans Glyphic"
  value: {
    tag_names: "/Sans/Glyphic"
    display_name: "Glyphic"
    display_font: "Red Rose"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Calligraphy All"
  value: {
    tag_names: "/Script/*"
    display_name: "All"
    display_font: "Google Sans Text"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Handwritten"
  value: {
    tag_names: "/Script/Handwritten"
    display_name: "Handwritten"
    display_font: "Kalam"
    display_font_size: "16px"
  }
}

id_to_group_member {
  key: "Formal"
  value: {
    tag_names: "/Script/Formal"
    display_name: "Formal"
    display_font: "Dancing Script"
    display_font_size: "19px"
  }
}

id_to_group_member {
  key: "Informal"
  value: {
    tag_names: "/Script/Informal"
    display_name: "Informal"
    display_font: "Mansalva"
    display_font_size: "16px"
  }
}

id_to_group_member {
  key: "Upright"
  value: {
    tag_names: "/Script/Upright"
    display_name: "Upright"
    display_font: "Gamja Flower"
    display_font_size: "17px"
  }
}

id_to_group_member {
  key: "Variable"
  value: {
    tag_names: "/Technology/Variable"
    display_name: "Variable"
    display_font: "Google Sans Text"
    display_font_size: "14px"
  }
}

id_to_group_member {
  key: "Color"
  value: {
    tag_names: "/Technology/Color"
    display_name: "Color"
    display_font: "Google Sans Text"
    display_font_size: "14px"
  }
}


id_to_group_member {
  key: "Halloween"
  value: {
    tag_names: "/Seasonal/Halloween"
    display_name: "Halloween"
    display_font: "Creepster"
    display_font_size: "18px"
  }
}

id_to_group_member {
  key: "Diwali"
  value: {
    tag_names: "/Seasonal/Diwali"
    display_name: "Diwali"
    display_font: "Eagle Lake"
    display_font_size: "15px"
  }
}
