name: "Twinkle Star"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-11-26"
fonts {
  name: "Twinkle Star"
  style: "normal"
  weight: 400
  filename: "TwinkleStar-Regular.ttf"
  post_script_name: "TwinkleStar-Regular"
  full_name: "Twinkle Star Regular"
  copyright: "Copyright 2003 The Twinkle Star Project Authors (https://github.com/googlefonts/twinkle-star)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
