name: "Greek script"
excerpt: "The writing system used for the Greek language, not be confused with the erroneously used “Greek” placeholder text."
related_lessons: "INSERT_RELATED_LESSONS_AS_MANY_AS_NEEDED"
