name: "Neonderthaw"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-11-18"
fonts {
  name: "Neonderthaw"
  style: "normal"
  weight: 400
  filename: "Neonderthaw-Regular.ttf"
  post_script_name: "Neonderthaw-Regular"
  full_name: "Neonderthaw Regular"
  copyright: "Copyright 2014-2021 The Neonderthaw Project Authors (https://github.com/googlefonts/neonderthaw)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
