name: "Superscript & subscript"
excerpt: "Text formatted to appear smaller than the surrounding text, usually aligned slightly above the top (super) or bottom (sub) of regular type."
related_lessons: "breaking_the_rules"
related_lessons: "choosing_reliable_typefaces"
