name: "Fleur De Leah"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-09-02"
fonts {
  name: "Fleur De Leah"
  style: "normal"
  weight: 400
  filename: "FleurDeLeah-Regular.ttf"
  post_script_name: "FleurDeLeah-Regular"
  full_name: "Fleur De Leah Regular"
  copyright: "Copyright 2008-2021 The Fleur De Leah Project Authors (https://github.com/googlefonts/fleurdeleah)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
