name: "Sans serif"
excerpt: "A typeface designed without serifs. Typically, sans serif faces have lower contrast and larger x-heights than serifs."
related_lessons: "making_sense_of_typographic_classifications"
related_lessons: "pairing_typefaces_within_a_family_superfamily"
