name: "Stroke"
excerpt: "The main line that makes up the appearance of a character. The term is derived from the penmanship inherent in hand-lettering."
related_lessons: "why_care_about_typography"
related_lessons: "choosing_typefaces_that_have_optical_sizes"
