id: "vec"
name: "Venetian"
preferred_name: ""
autonym: "Vèneto"
population: 811235
region: "IT"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z À Á Ç È É Ì Í Ò Ó Ù Ł Ž a b c d e f g h i j k l m n o p q r s t u v w x y z à á ç è é ì í ò ó ù ł ž"
  marks: "◌̀ ◌́ ◌̌ ◌̧"
}
