id: "ace"
name: "Achinese"
preferred_name: ""
autonym: "Bahsa Acèh"
population: 3738364
region: "ID"
script: "Latin"
exemplar_chars {
  base: "A B C D E G H I J K L M N O P R S T W Y É È Ë Ô Ö a b c d e g h i j k l m n o p r s t w y é è ë ô ö \'"
  marks: "◌̀ ◌́ ◌̂ ◌̈"
}
