id: "bal"
name: "Baluchi"
preferred_name: "Balochi"
autonym: "بلۏچی"
population: 10796398
region: "AE"
region: "IR"
region: "PK"
region: "OM"
script: "Perso-Arabic"
exemplar_chars {
  base: "ء آ ا ب ت ج د ر ز س ش ل م ن ه و ٹ پ چ ڈ ژ ک گ ی ۏ ے ݔ ࢣ"
  marks: "◌َ ◌ُ ◌ِ ◌ٓ"
  numerals: "۰ ۱ ۲ ۳ ۴ ۵ ۶ ۷ ۸ ۹ 0 1 2 3 4 5 6 7 8 9"
}
