name: "Bungee Hairline"
designer: "David Jonathan Ross"
license: "OFL"
category: "DISPLAY"
date_added: "2016-06-20"
fonts {
  name: "Bungee Hairline"
  style: "normal"
  weight: 400
  filename: "BungeeHairline-Regular.ttf"
  post_script_name: "BungeeHairline-Regular"
  full_name: "Bungee Hairline Regular"
  copyright: "Copyright 2008 The Bungee Project Authors (david@djr.com)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
stroke: "SANS_SERIF"
classifications: "DISPLAY"
