name: "How to make type feel authentic"
authors: "Elliot Jay Stocks"
reviewers: "Laurence Penney"
reviewers: "Gerry Leonidas"
topics: "open_type"
topics: "families"
related_terms: "open_type"
prev_lessons: "vertical_spacing_and_line_height_in_design_systems"
next_lessons: "installing_and_managing_fonts"
excerpt: "There are occasions when the uniformity of type strips it off authenticity, but with a few simple tricks, we can re-introduce the human element into our typography."
