name: "An alphabet for reading and writing"
authors: "Darrell Penta"
reviewers: "Cassidy Curtis"
reviewers: "Minjoo Ham"
reviewers: "Min-Young Kim"
reviewers: "SeHee Lee"
topics: "hangeul"
topics: "type_history"
prev_lessons: "making_the_details_matter"
next_lessons: "lessons_from_hangeul"
related_terms: "alphabet"
related_terms: "letters"
related_terms: "script_writing_system"
excerpt: "Part 4 in our in-depth look at the creation of Hangeul, the Korean alphabet."
