id: "nv"
name: "Navajo"
preferred_name: ""
autonym: "Diné Bizaad"
population: 166319
region: "US"
script: "Latin"
exemplar_chars {
  base: "A Ą B C D E Ę G H I Į J K L Ł M N O Ǫ S T W X Y Z a á ą ą́ b c d e é ę ę́ g h i í į į́ j k l ł m n o ó ǫ ǫ́ s t w x y z ʼ"
  marks: "◌́ ◌̨"
}
