name: "Adobe Blank"
designer: "Dr. Ken Lunde"
license: "OFL"
category: "MONOSPACE"
date_added: "2016-03-23"
fonts {
  name: "Adobe Blank"
  style: "normal"
  weight: 400
  filename: "AdobeBlank-Regular.ttf"
  post_script_name: "AdobeBlank-Regular"
  full_name: "Adobe Blank"
  copyright: "Copyright  2013, 2015 Adobe Systems Incorporated (http://www.adobe.com/)."
}
subsets: "arabic"
subsets: "bengali"
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "devanagari"
subsets: "ethiopic"
subsets: "greek"
subsets: "greek-ext"
subsets: "gujarati"
subsets: "gurmukhi"
subsets: "hebrew"
subsets: "japanese"
subsets: "kannada"
subsets: "khmer"
subsets: "lao"
subsets: "latin"
subsets: "latin-ext"
subsets: "malayalam"
subsets: "menu"
subsets: "myanmar"
subsets: "oriya"
subsets: "sinhala"
subsets: "tamil"
subsets: "telugu"
subsets: "thai"
subsets: "vietnamese"
