name: "Reversed-out"
excerpt: "The scenario of setting white or light-colored type on top of a black or dark-colored background."
related_lessons: "exploring_typefaces_with_multiple_weights_or_grades"
