id: "ab"
name: "Abkhazian"
preferred_name: ""
autonym: "Аԥсшәа"
population: 91952
region: "TR"
region: "GE"
script: "Cyrillic"
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я Џ Қ Ҟ Ҩ Ҭ Ҳ Ҵ Ҷ Ҽ Ҿ Ә Ӡ Ӷ Ԥ а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я џ қ ҟ ҩ ҭ ҳ ҵ ҷ ҽ ҿ ә ӡ ӷ ԥ"
  marks: "◌̆"
}
