name: "Width"
excerpt: "The amount of horizontal space taken up by a typeface’s characters. A condensed face takes up considerably less space than a wide face."
related_lessons: "exploring_width_in_type"
related_lessons: "introducing_variable_fonts"
related_lessons: "pairing_typefaces_within_a_family_superfamily"
