// See https://observablehq.com/framework/config for documentation.
import { readdirSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const srcDir = join(here, "src");
const standaloneDir = join(here, ".."); // .ci/ — where the standalone HTML lives

// Read the `title:` from a Markdown page's frontmatter.
function frontmatterTitle(file) {
  const m = readFileSync(file, "utf8").match(/^---\n([\s\S]*?)\n---/);
  const t = m && m[1].match(/^title:\s*(.+)$/m);
  return t ? t[1].trim().replace(/^["']|["']$/g, "") : null;
}

// Framework pages: every src/*.md except the home page (index.md). Discovered
// dynamically and ordered by title, matching Framework's default sidebar, so
// new dashboard pages show up without touching this file.
const frameworkPages = readdirSync(srcDir)
  .filter((f) => f.endsWith(".md") && f !== "index.md")
  .map((f) => ({
    name: frontmatterTitle(join(srcDir, f)) ?? f.replace(/\.md$/, ""),
    path: `/${f.replace(/\.md$/, "")}`,
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

// Standalone pages: hand-written HTML that report.yaml copies into the build
// root *after* Framework runs. `cp ../*.html build/` deploys every .ci/*.html,
// so we discover them the same way. meta.html is generated by `gftools
// compare-meta` straight into build/ (it isn't in .ci/ at eval time), so it's
// added explicitly. The label is just the file name with -/_ turned into
// spaces and the .html dropped.
const standaloneFiles = ["meta.html", ...readdirSync(standaloneDir).filter((f) => f.endsWith(".html"))].filter(
  (f, i, a) => a.indexOf(f) === i,
);
const standalonePages = standaloneFiles.map((f) => ({
  name: f.replace(/\.html$/, "").replace(/[-_]/g, " "),
  path: `/${f}`,
}));

export default {
  title: "Google Fonts QA Dashboard",
  root: "src",
  footer: "",
  sidebar: true, // whether to show the sidebar
  output: "build", // path to the output root for build
  preserveExtension: true,
  style: "style.css",
  // Explicit sidebar navigation. Defining `pages` replaces Framework's
  // auto-generated sidebar, so we rebuild the Markdown pages list (above) and
  // then append the standalone HTML pages. `pager: null` on the section marks
  // those pages as not Framework-built — otherwise the build tries to load a
  // source page for each and fails with "page not found". They still render in
  // the sidebar and link to the copied files.
  pages: [
    ...frameworkPages,
    {
      name: "Standalone pages",
      open: true,
      pager: null,
      pages: standalonePages,
    },
  ],
};
