name: "Web font comparisons: variable vs. static"
authors: "Nick Sherman"
reviewers: "Laurence Penney"
reviewers: "Piper Haywood"
topics: "variable_fonts"
related_terms: "variable_fonts"
excerpt: "INSERT"
