name: "Web font comparisons: variable vs. static"
authors: "Nick Sherman"
reviewers: "Laurence Penney"
reviewers: "Piper Haywood"
topics: "variable_fonts"
related_terms: "variable_fonts"
prev_lessons: "variable_fonts_are_here"
next_lessons: "optimizing_typographic_space_with_variable_fonts"
excerpt: "How efficient are variable web fonts when compared to static fonts? As with most questions related to typography, the answer—for better or worse—is “it depends.”"
