name: "Licensing"
excerpt: "In typography, the process of obtaining a font license by a user. A license is a legal statement made by the type foundry about what users can and can’t do with the fonts. Even fonts obtained for free are licensed."
related_lessons: "choosing_reliable_typefaces"
related_lessons: "pairing_typefaces_by_the_same_type_designer_or_type_foundry"
