name: "Choosing web fonts: A beginner's all-in-one guide"
authors: "Dave Crossland"
reviewers: "Dave Crossland"
topics: "essentials"
topics: "web_fonts"
prev_lessons: "why_care_about_typography"
related_terms: "typography"
related_terms: "serif"
related_terms: "sans_serif"