name: "Choosing web fonts: A beginner's all-in-one guide"
authors: "Charles Berret"
reviewers: "Bryn Smith"
reviewers: "Dave Crossland"
reviewers: "Yuin Chien"
reviewers: "Joana Correia"
reviewers: "Natanael Gama"
reviewers: "Octavio Pardo"
reviewers: "Eben Sorkin"
reviewers: "Eduardo Tunni"
topics: "essentials"
topics: "choosing_type"
prev_lessons: "a_checklist_for_choosing_type"
related_terms: "typography"
related_terms: "serif"
related_terms: "sans_serif"
excerpt: "A beginners' guide to choosing web fonts."
