name: "EB Garamond"
designer: "Georg Duffner"
license: "OFL"
category: "SERIF"
date_added: "2011-03-23"
fonts {
  name: "EB Garamond"
  style: "normal"
  weight: 400
  filename: "EBGaramond-Regular.ttf"
  post_script_name: "EBGaramond"
  full_name: "EB Garamond"
  copyright: "Copyright (c) 2010, 2011, 2012 Georg Duffner (http://www.georgduffner.at g.duffner@gmail.com)"
}
subsets: "menu"
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "latin"
subsets: "latin-ext"
subsets: "vietnamese"
