id: "tet"
name: "Tetum"
preferred_name: ""
autonym: "Lia Tetun"
population: 816394
region: "TL"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z Ñ Á Ó É Í a b c d e f g h i j k l m n o p q r s t u v w x y z ñ á ó é í"
  marks: "◌́ ◌̃"
}
