name: "Web font"
excerpt: "Any font that’s used in a website’s design that isn’t installed by default on the end user’s device—a counterpart to a “system font."
related_lessons: "using_web_fonts"
related_lessons: "using_web_fonts_from_a_font_delivery_service"
related_lessons: "self_hosting_web_fonts"
