name: "Display type"
authors: "John Boardley"
reviewers: "Gerry Leonidas"
reviewers: "Ben Weiner"
topics: "type_history"
related_terms: "sans_serif"
related_terms: "display"
related_terms: "contrast"
related_terms: "letterform"
related_terms: "bold"
related_terms: "x_height"
related_terms: "typesetting"
related_terms: "condensed_narrow_compressed"
related_terms: "classification"
related_terms: "legibility"
related_terms: "readability"
related_terms: "serif"
related_terms: "type_foundry"
prev_lessons: "modern_type"
next_lessons: "from_metal_to_digital"
excerpt: "The rise of display fonts in the 19th century, and the invention of the sans serif."
