name: "Japanese typography basics"
authors: "Min-Young Kim"
reviewers: "Lisa Huang"
reviewers: "Minjoo Ham"
reviewers: "Shoko Mugikura"
topics: "cjk"
related_terms: "cjk"
related_terms: "script_writing_system"
prev_lessons: "cjk_typesetting_rules"
next_lessons: "the_evolution_of_hangeul_type_design"
excerpt: "Japanese typesetting is complicated due to the use of three different kinds of scripts in one language. This article explains the fundamentals, from the structure of Japanese script to the kerning system called Tsume."
