name: "Japanese typography basics"
authors: "Min-Young Kim"
reviewers: "Lisa Huang"
reviewers: "Minjoo Ham"
reviewers: "Shoko Mugikura"
topics: "cjk"
related_terms: "cjk"
related_terms: "script_writing_system"
prev_lessons: "cjk_typesetting_rules"
next_lessons: "the_evolution_of_hangeul_type_design"
excerpt: "INSERT_EXCERPT"
