name: "Swash glyph"
excerpt: "A decorative variant of a glyph, most commonly found in serif typefaces, which has more elaborate and ornate flourishes than its regular version."
related_lessons: "introducing_alternate_glyphs"
related_lessons: "open_type_features_in_practice"
related_lessons: "implementing_open_type_features_on_the_web"
