name: "Advancing type"
lessons: "space"
lessons: "size"
lessons: "weight"
excerpt: "David Berlow has been at the forefront of type design and font development for multiple decades. In recent years, he’s become a close collaborator with Google, focusing his expertise on variable fonts—a technology he helped create. Here, in “Advancing Type,” David shares his thoughts in an ongoing series of essays on the past, present, and future of type’s evolution.
