name: "Condensed, narrow, or compressed"
excerpt: "A reference to a typeface’s width, usually implying a narrower version of its normal width."
related_lessons: "exploring_width_in_type"
related_lessons: "introducing_variable_fonts"
related_lessons: "pairing_typefaces_within_a_family_superfamily"
related_lessons: "making_sense_of_typographic_classifications"
