alt_ids: "writing_system"
name: "Script"
excerpt: "A visual representation of verbal speech, which, when combined with usage conventions, constitutes a writing system."
related_lessons: "language_support_in_fonts"
related_lessons: "choosing_reliable_typefaces"
related_lessons: "an_overview_of_latin_type_anatomy"
related_content_urls: "https://www.youtube.com/embed/ro6XnC_U-I8"
