name: "Hangeul"
lessons: "1_introduction_to_hangeul"
lessons: "2_designing_for_learnability"
lessons: "3_making_the_details_matter"
lessons: "4_an_alphabet_for_reading_and_writing"
lessons: "5_lessons_from_hangeul"
excerpt: "TBC"
