name: "Hangeul"
lessons: "1-introduction-to-hangeul"
lessons: "2-designing-for-learnability"
lessons: "3-making-the-details-matter"
lessons: "4-an-alphabet-for-reading-and-writing"
lessons: "5-lessons-from-hangeul"
excerpt: "TBC"
