name: "Hangeul"
lessons: "an_introduction_to_hangeul"
lessons: "designing_for_learnability"
lessons: "making_the_details_matter"
lessons: "an_alphabet_for_reading_and_writing"
lessons: "lessons_from_hangeul"
excerpt: "TBC"
