id: "lo"
name: "Lao"
preferred_name: ""
autonym: "ພາສາລາວ"
population: 5138706
region: "LA"
script: "Lao"
exemplar_chars {
  base: "ກ ຂ ຄ ງ ຈ ສ ຊ ຍ ດ ຕ ຖ ທ ນ ບ ປ ຜ ຝ ພ ຟ ມ ຢ ຣ ລ ວ ຫ ອ ຮ ະ າ ເ ແ ໂ ໃ ໄ ຽ"
  auxiliary: "\\u200B ໐ ໑ ໒ ໓ ໔ ໕ ໖ ໗ ໘ ໙"
  marks: "◌ັ ◌ິ ◌ີ ◌ຶ ◌ື ◌ຸ ◌ູ ◌ົ ◌ຼ ◌່ ◌້ ◌໊ ◌໋ ◌໌ ◌ໍ"
  numerals: "໐ ໑ ໒ ໓ ໔ ໕ ໖ ໗ ໘ ໙ 0 1 2 3 4 5 6 7 8 9"
  punctuation: "ຯ ໆ"
  index: "ກ ຂ ຄ ງ ຈ ສ ຊ ຍ ດ ຕ ຖ ທ ນ ບ ປ ຜ ຝ ພ ຟ ມ ຢ ຣ ລ ວ ຫ {ຫງ} {ຫຍ} {ຫນ} {ຫມ} {ຫລ} {ຫວ} ອ ຮ"
}
