name: "Lessons from Hangeul"
authors: "Darrell Penta"
reviewers: "Cassidy Curtis"
reviewers: "Minjoo Ham"
reviewers: "Min-Young Kim"
reviewers: "SeHee Lee"
topics: "hangeul"
prev_lessons: "an_alphabet_for_reading_and_writing"
related_terms: "alphabet"
related_terms: "letters"
related_terms: "script_writing_system"
excerpt: "INSERT"
