id: "mh"
name: "Marshallese"
preferred_name: ""
autonym: "Kajin M̧ajeļ"
population: 56879
region: "MH"
script: "Latin"
exemplar_chars {
  base: "A Ā B D E I J K L Ļ M M̧ N Ņ N̄ O Ō O̧ P R T U Ū W a ā b d e i j k l ļ m m̧ n ņ n̄ o ō o̧ p r t u ū w"
  marks: "◌̄ ◌̦ ◌̧ ◌̨"
}
