name: "Baseline"
excerpt: "The invisible line upon which a line of type rests. It’s used as a point from which other elements are measured, such as leading (line height) and x-height."
related_lessons: "exploring_x_height_the_em_square"
