name: "Andika"
designer: "SIL International"
license: "OFL"
category: "SANS_SERIF"
date_added: "2011-08-10"
fonts {
  name: "Andika"
  style: "normal"
  weight: 400
  filename: "Andika-R.ttf"
  post_script_name: "Andika"
  full_name: "Andika"
  copyright: "Copyright (c) 2004-2011, SIL International (http://www.sil.org/). Licensed under the SIL Open Font License, Version 1.1 (http://scripts.sil.org/OFL), with Reserved Font Names \"Andika\" and \"SIL\"."
}
subsets: "menu"
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "latin"
subsets: "latin-ext"
subsets: "vietnamese"
