name: "Making sense of typographic classifications"
authors: "Elliot Jay Stocks"
reviewers: "Bruce Willen"
reviewers: "Ellen Lupton"
reviewers: "Erik Spiekermann"
reviewers: "Gerry Leonidas"
reviewers: "Jamie Clarke"
reviewers: "Laurence Penney"
reviewers: "Richard Rutter"
reviewers: "Thomas Phinney"
reviewers: "Yves Peters"
topics: "essentials"
prev_lessons: "why_care_about_typography"
next_lessons: "exploring_punctuation"
next_lessons: "pairing_typefaces"
related_terms: "typeface"
related_terms: "serif"
related_terms: "sans_serif"
related_terms: "slab_serif_egyptian_clarendon"
related_terms: "monospaced"
excerpt: "With so many typefaces in the world, searching for the right one can be a daunting task, but filtering helps."
