name: "The evolution of Hangeul type design"
authors: "Min-Young Kim"
reviewers: "Lisa Huang"
reviewers: "Minjoo Ham"
reviewers: "Shoko Mugikura"
topics: "cjk"
related_terms: "cjk"
prev_lessons: "japanese_typography_basics"
next_lessons: "an_introduction_to_hangeul"
excerpt: "INSERT_EXCERPT"
