id: "loz"
name: "Lozi"
preferred_name: ""
autonym: "siLozi"
population: 1045596
region: "ZM"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I J K L M N Ñ O P S T U W Y Z a b c d e f g h i j k l m n ñ o p s t u w y z ʼ"
  marks: "◌̃"
}
