name: "Bespoke, or custom type"
excerpt: "Type specifically commissioned by a client, usually to serve as a brand typeface. It's not normally not available to the public."
related_lessons: "pairing_typefaces_by_the_same_type_designer_or_type_foundry"
related_lessons: "making_sense_of_typographic_classifications"
