name: "Smooch"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-11-02"
fonts {
  name: "Smooch"
  style: "normal"
  weight: 400
  filename: "Smooch-Regular.ttf"
  post_script_name: "Smooch-Regular"
  full_name: "Smooch Regular"
  copyright: "Copyright 2017 The Smooch Project Authors (https://github.com/googlefonts/smooch)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
