name: "Ink trap"
excerpt: "An intentional negative space built into letterforms to literally trap ink at certain intersections of the strokes."
related_lessons: "choosing_typefaces_that_have_optical_sizes"
