id: "ru"
name: "Russian"
preferred_name: ""
autonym: "Русский"
population: 195630064
region: "GE"
region: "US"
region: "KZ"
region: "SJ"
region: "CN"
region: "KG"
region: "TM"
region: "LT"
region: "UZ"
region: "TJ"
region: "DE"
region: "MD"
region: "RU"
region: "LV"
region: "FI"
region: "BY"
region: "MN"
region: "BG"
region: "PL"
region: "UA"
region: "EE"
region: "IL"
script: "Cyrillic"
exemplar_chars {
  base: "А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я Ё а б в г д е ж з и й к л м н о п р с т у ф х ц ч ш щ ъ ы ь э ю я ё"
  auxiliary: "А́ Е́ И́ О́ У́ Ы́ Э́ Ю́ Я́ а́ е́ и́ о́ у́ ы́ э́ ю́ я́"
  marks: "◌̆ ◌̈ ◌́"
  numerals: "  \\- ‑ , % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … \' ‘ ‚ \" “ „ « » ( ) \\[ \\] \\{ \\} § @ * / \\& #"
  index: "А Б В Г Д Е Ё Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ы Э Ю Я"
}
