name: "The invention of type"
authors: "John Boardley"
reviewers: "Gerry Leonidas"
reviewers: "Ben Weiner"
topics: "type_history"
next_lessons: "what_have_the_romans_ever_done_for_us"
related_terms: "blackletter"
related_terms: "calligraphy"
related_terms: "latin"
related_terms: "letterform"
excerpt: "The European advent of printing and the invention of fonts."
