name: "A checklist for choosing type"
authors: "Elliot Jay Stocks"
reviewers: "Doug Wilson"
reviewers: "Gerry Leonidas"
reviewers: "Laurence Penney"
reviewers: "Rich Rutter"
reviewers: "Thomas Phinney"
topics: "essentials"
topics: "families"
prev_lessons: "insert_slug"
next_lessons: "insert_slug"
related_terms: "weight"
excerpt: "TBC"
