name: "A checklist for choosing type"
authors: "Elliot Jay Stocks"
reviewers: "Doug Wilson"
reviewers: "Gerry Leonidas"
reviewers: "Laurence Penney"
reviewers: "Rich Rutter"
reviewers: "Thomas Phinney"
topics: "essentials"
topics: "families"
prev_lessons: "exploring_x_height_the_em_square"
next_lessons: "pairing_typefaces"
related_terms: "body"
related_terms: "weight"
related_terms: "width"
related_terms: "open_type"
related_terms: "optical_sizes"
excerpt: "TBC"
