name: "A checklist for choosing type"
authors: "Elliot Jay Stocks"
reviewers: "Doug Wilson"
reviewers: "Gerry Leonidas"
reviewers: "Laurence Penney"
reviewers: "Richard Rutter"
reviewers: "Thomas Phinney"
topics: "essentials"
topics: "families"
prev_lessons: "making_sense_of_typographic_classifications"
next_lessons: "emotive_considerations_for_choosing_typefaces"
related_terms: "body"
related_terms: "weight"
related_terms: "width"
related_terms: "open_type"
related_terms: "optical_sizes"
excerpt: "A simple but thorough checklist to reference every time we need to choose a new typeface, with each item explained in detail."
