name: "Adding fonts to Google Docs and Slides"
authors: "Elliot Jay Stocks"
reviewers: "Thomas Phinney"
topics: "essentials"
related_terms: "typeface"
related_terms: "italic"
related_terms: "weight"
prev_lessons: "how_typefaces_are_designed_and_fonts_are_made"
excerpt: "Google’s Workspace apps, such as Docs, Sheets, and Slides, come with a selection of typefaces to choose from, accessible via the Font menu. But did you know you can actually add any font from the Google Fonts library to this menu, too?"
