name: "Regular, or upright"
excerpt: "Either the “Regular” weight of a typeface, usually assigned the font-weight value of 400, or the “Regular” upright style (i.e., non-italic) of a typeface."
related_lessons: "introducing_weights_styles"
