id: "nn"
name: "Norwegian Nynorsk"
preferred_name: ""
autonym: ""
population: 1366860
region: "NO"
script: "Latin"
exemplar_chars {
  auxiliary: "á ǎ č ç đ è ê ń ñ ŋ š ŧ ü ž ä ö"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ? . … \' ‘ ’ \" “ ” ( ) \\[ \\] § @ * / \\& # † ‡ ′ ″"
}
