name: "An overview of Latin type anatomy"
authors: "Elliot Jay Stocks"
reviewers: "Doug Wilson"
reviewers: "Gerry Leonidas"
reviewers: "Laurence Penney"
reviewers: "Richard Rutter"
topics: "essentials"
topics: "families"
prev_lessons: "why_care_about_typography"
next_lessons: "making_sense_of_typographic_classifications"
related_terms: "x_height"
related_terms: "ascenders_descenders"
related_terms: "line_height_leading"
related_terms: "diacritic_accent_marks"
related_terms: "ligature"
excerpt: "A visual guide to the essential building blocks of typefaces that use the Latin script."
