name: "Technical challenges for typography in AR/VR"
authors: "Niteesh Yadav"
reviewers: "Andrew Johnson"
reviewers: "Gerry Leonidas"
topics: "ar_vr"
prev_lessons: "spatial_classification_of_typography_in_ar_vr"
excerpt: "EXCERPT_TBC"
