name: "Technical challenges for typography in AR/VR"
authors: "Niteesh Yadav"
reviewers: "Andrew Johnson"
reviewers: "Gerry Leonidas"
topics: "ar_vr"
prev_lessons: "spatial_classification_of_typography_in_ar_vr"
related_terms: "font"
related_terms: "glyph"
related_terms: "legibility"
related_terms: "width"
related_terms: "weight"
excerpt: "The rendering of text in AR/VR applications still follows models from  the ’90s, but the challenges for good typography don’t end there."
