id: "ast"
name: "Asturian"
preferred_name: ""
autonym: "Asturianu"
population: 650205
region: "ES"
script: "Latin"
exemplar_chars {
  base: "A B C D E F G H I L M N O P Q R S T U V X Y Z Á É Í Ñ Ó Ú Ü Ḥ Ḷ a b c d e f g h i l m n o p q r s t u v x y z á é í ñ ó ú ü ḥ ḷ"
  auxiliary: "ª à ă â å ä ã ā æ ç è ĕ ê ë ē ì ĭ î ï ī j k º ò ŏ ô ö ø ō œ ù ŭ û ū w ÿ"
  marks: "◌́ ◌̃ ◌̈ ◌̣"
  numerals: "\\- ‑ , . % ‰ + 0 1 2 3 4 5 6 7 8 9"
  punctuation: "\\- ‐ ‑ – — , ; \\: ! ¡ ? ¿ . … \' ‘ ’ \" “ ” « » ( ) \\[ \\] § @ * / \\\\ \\& # † ‡ ′ ″"
  index: "A B C D E F G H I L M N Ñ O P Q R S T U V X Y Z"
}
