name: "Justification & hyphenation"
authors: "Micah Rich"
authors: "Thomas Jockin"
topics: "variable_fonts"
prev_lessons: "fitting_the_line"
next_lessons: "the_tight_not_touching_style"
related_terms: "alignment_justification"
related_terms: "variable_fonts"
excerpt: "In western text, which reads left to right, justification and hyphenation are basic considerations for readability and clarity. But have you ever thought about how you can use them to create a look/feel that alludes to the literary culture of the past?"
