name: "Justification & hyphenation"
authors: "Micah Rich"
authors: "Thomas Jockin"
topics: "variable_fonts"
prev_lessons: "fitting_the_line"
next_lessons: "the_tight_not_touching_style"
related_terms: "alignment_justification"
related_terms: "variable_fonts"
excerpt: "EXCERPT_TBC"
