name: "Poiret One"
designer: "Denis Masharov"
license: "OFL"
category: "DISPLAY"
date_added: "2012-02-29"
fonts {
  name: "Poiret One"
  style: "normal"
  weight: 400
  filename: "PoiretOne-Regular.ttf"
  post_script_name: "PoiretOne-Regular"
  full_name: "Poiret One Regular"
  copyright: "Copyright 2011 The Poiret One Project Authors (https://github.com/alexeiva/poiretone)"
}
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
stroke: "SANS_SERIF"
classifications: "DISPLAY"
