name: "Exploring width in type"
authors: "Elliot Jay Stocks"
reviewers: "Doug Wilson"
reviewers: "Laurence Penney"
reviewers: "Micah Rich"
reviewers: "Thomas Phinney"
reviewers: "Yves Peters"
topics: "choosing_type"
topics: "width"
prev_lessons: "exploring_typefaces_with_multiple_weights_or_grades"
next_lessons: "choosing_typefaces_that_have_optical_sizes"
related_terms: "width"
related_terms: "variable_fonts"
excerpt: "Multiple widths offer the typographer more ways to work with type without the need to use more than one typeface."
