# Check font tags
name: Check font tags

on:
  push:
    paths:
    - 'tags/all/families.csv'
  pull_request:
    paths:
    - 'tags/all/families.csv'

jobs:
  test_server_files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Check font tags
      run: |
        python .ci/test_font_tags.py