# Check font tags
name: Check font tags

on:
  push:
    paths:
    - 'tags/all/families.csv'
  pull_request:
    paths:
    - 'tags/all/families.csv'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_font_tags:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install pytest requests
    - name: Check font tags
      env:
        SB_USERNAME: ${{ secrets.SB_USERNAME }}
        SB_PASSWORD: ${{ secrets.SB_PASSWORD }}
      run: |
        pytest .ci/test_font_tags.py