# Check font tagging spreadsheet is correctly structured
name: Font tagging structure

on:
  push:
    paths:
    - 'tags/all/families.csv'
  pull_request:
    paths:
    - 'tags/all/families.csv'

permissions:
  contents: read

jobs:
  test_server_files:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Set up Python
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: "3.10"

    # Check font tags data is correct
    - name: Install gftools
      run: pip install gftools[qa]
    - name: Test font tagging spreadsheet
      run: |
        gftools font-tags lint .