name: QA whole library
on:
  schedule:
    - cron: "12 1 * * *"
  workflow_dispatch:
jobs:
  rebuild:
    runs-on: macos-13 # More RAM, heh heh
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          lfs: true
      - name: Grab fontspector database
        run: |
          mkdir -p ~/.ssh/
          echo "$CORVEL_SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$CORVEL_KNOWNHOSTS" > ~/.ssh/known_hosts
          scp -i ../private.key fontspector@corvelsoftware.co.uk:fontspector.db .
        shell: bash
        env:
          CORVEL_SSH_PRIVATE_KEY: ${{secrets.CORVEL_SSH_PRIVATE_KEY}}
          CORVEL_KNOWNHOSTS: ${{secrets.CORVEL_KNOWNHOSTS}}
      - name: Install protoc
        run: brew install protobuf
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build fontspector
        run: cargo install --git https://github.com/fonttools/fontspector --features duckdb
      - name: Test all the things
        run: fontspector --profile googlefonts ofl/*/*{.ttf,.pb,.html,.svg,.jpg,.gif} --skip-network --succinct --duckdb fontspector.db || true
      - name: Stash database again
        run: "scp -i ../private.key fontspector.db fontspector@corvelsoftware.co.uk:"
      - name: Upload results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: gh-pages
          file_pattern: fontspector-dashboard
