name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install protoc
        run: sudo apt-get install protobuf-compiler
      - name: Build
        run: cargo build --verbose
      - name: Check for lints
        run: cargo clippy
      - name: Run tests
        run: |
          cargo test --verbose
