name: Google Fonts QA
permissions: read-all
on:
  pull_request:
    branches:
    - main

jobs:

  diffbrowsers:
    name: Build Google Fonts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10']
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Cancel previous
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
        with:
          access_token: ${{ github.token }}
    
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Python 3.10
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.10'
      - name: Install packages
        run: |
          pip install gftools[qa] pytest
        shell: bash
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@4f8e94349a351df0f048634f25fec36c3c91eded # latest
      - name: Setup Chrome Driver
        uses: nanasess/setup-chromedriver@e93e57b843c0c92788f22483f1a31af8ee48db25 # master

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@233224b712fc07910ded8c15fb95a555c86da76f # latest
      - name: Setup Firefox Driver
        uses: browser-actions/setup-geckodriver@43a66ae697b28edeb8c6fa3995fad360713e6ef6 # latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Diffbrowsers
        run: |
          mkdir out
          python -m youseedee 0x078A
          chromedriver --url-base=/wd/hub &
          python3 .ci/run.py --render
        env:
          PYTHONIOENCODING: 'utf-8'
          PYTHONUTF8: '1'
        shell: bash

      - name: Check file existence
        id: check_files
        uses: step-security/file-existence-action@e49061d3e43a16445f2518f344fca0e65417383a # v3.0.0
        with:
          files: "out"

      - name: Upload check results
        if: steps.check_files.outputs.files_exists == 'true'
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: qa
          path: out/

  diffenator:
    name: Diffenate fonts
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Cancel previous
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
        with:
          access_token: ${{ github.token }}
    
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Python 3.10
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.10'
      - name: Install packages
        # The --pre flag below will ensure we use the latest Font Bakery pre-releases
        # and benefit from its newest checks:
        run: |
          pip install --upgrade pip
          pip install --pre fontbakery[googlefonts]
          pip install gftools[qa] pytest
        shell: bash

      - name: Run Diffenator and Fontbakery
        run: |
          mkdir out
          python -m youseedee 0x078A
          python3 .ci/run.py --pr-number $PR_NUMBER --pr-url-body https://www.github.com/google/fonts/pull/
        env:
          PYTHONIOENCODING: 'utf-8'
          PYTHONUTF8: '1'
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
        shell: bash
      
      - name: Check file existence
        id: check_files
        uses: step-security/file-existence-action@e49061d3e43a16445f2518f344fca0e65417383a # v3.0.0
        with:
          files: "out"

      - name: Upload check results
        if: steps.check_files.outputs.files_exists == 'true'
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: qa
          path: out/
