sources:
    - ../Big-Shoulders-Inline/sources/BigShouldersInline.glyphs
recipe:
  ../Big-Shoulders-Inline/fonts/variable/text/BigShouldersInlineText[wght].ttf:
    - source: ../Big-Shoulders-Inline/sources/BigShouldersInline.glyphs
    - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
      operation: buildVariable
    - operation: subspace
      axes: opsz=10
    - operation: rename
      name: Big Shoulders Inline Text
      args: --just-family
    - operation: fix
    - postprocess: buildStat
  # And now the small caps family
  ../Big-Shoulders-Inline/fonts/variable/text/BigShouldersInlineTextSC[wght].ttf:
    - source: ../Big-Shoulders-Inline/sources/BigShouldersInline.glyphs
    - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
      operation: buildVariable
    - operation: subspace
      axes: opsz=10
    - args: '''smcp -> ccmp'''
      operation: remapLayout
    - operation: rename
      name: Big Shoulders Inline Text SC
      args: --just-family
    - operation: fix
    - postprocess: buildStat
