name: "Spatial classification of typography in AR/VR"
authors: "Niteesh Yadav"
reviewers: "Andrew Johnson"
reviewers: "Gerry Leonidas"
topics: "ar_vr"
prev_lessons: "type_selection_for_ar_vr"
next_lessons: "technical_challenges_for_typography_in_ar_vr"
related_terms: "font"
related_terms: "glyph"
related_terms: "legibility"
related_terms: "width"
related_terms: "weight"
excerpt: "Spatial classifications can help with considerations for choosing typefaces, setting text, and even designing typefaces for different applications—as well as picking the most appropriate rendering methods."
