name: "Transitional faces"
authors: "John Boardley"
reviewers: "Gerry Leonidas"
reviewers: "Ben Weiner"
topics: "type_history"
prev_lessons: "history_of_type_2"
next_lessons: "fitting_the_line"
related_terms: "blackletter"
related_terms: "contrast"
related_terms: "italic"
related_terms: "latin"
related_terms: "letterform"
related_terms: "transitional_neo_classical"
related_terms: "type_design"
excerpt: "INSERT_EXCERPT"
