name: "Luxurious Script"
designer: "Robert Leuschke"
license: "OFL"
category: "HANDWRITING"
date_added: "2021-11-02"
fonts {
  name: "Luxurious Script"
  style: "normal"
  weight: 400
  filename: "LuxuriousScript-Regular.ttf"
  post_script_name: "LuxuriousScript-Regular"
  full_name: "Luxurious Script Regular"
  copyright: "Copyright 2015-2021 The Luxurious Project Authors (https://github.com/googlefonts/luxurious)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
classifications: "DISPLAY"
classifications: "HANDWRITING"
