name: "Character"
excerpt: "A single unit of language, such as a letter or mark. Closely related to—but not the same as—a glyph."
related_lessons: "why_care_about_typography"
related_lessons: "introducing_alternate_glyphs"
