name: "Moo Lah Lah"
designer: "Robert Leuschke"
license: "OFL"
category: "DISPLAY"
date_added: "2021-11-26"
fonts {
  name: "Moo Lah Lah"
  style: "normal"
  weight: 400
  filename: "MooLahLah-Regular.ttf"
  post_script_name: "MooLahLah-Regular"
  full_name: "Moo Lah Lah Regular"
  copyright: "Copyright 2003-2021 The Moo Lah Lah Project Authors (https://github.com/googlefonts/moolahlah)"
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
stroke: "SANS_SERIF"
classifications: "DISPLAY"
